### ISSUE TITLE
How to use a FileChooser() in Compose.  

### ISSUE THREAD

**Issue by virogu** [JetBrains/compose-multiplatform#1003]
How to use a FileChooser() in Compose.  
The FileDialog() function can not do what i want,  it can not select a dictionary or select file wih a filter

**Comment by virogu** [comment]
I have tried to use the JFileChooser() like this.  It did achieve the effect I wanted. But it will be very stuck when it is displayed, and it will take a long time for the file selection box to pop up.
`  
      val jfc = JFileChooser()
        val path = preferences[prefKey, ""]
        if (path.isNotEmpty() && File(path).exists()) {
            jfc.currentDirectory = File(path)
        } else {
            jfc.currentDirectory = projectRootPath
        }
        jfc.fileSelectionMode = fileChooserType
        jfc.fileFilter = object : FileFilter() {
            override fun accept(f: File): Boolean {
                return when (fileChooserType) {
                    JFileChooser.FILES_ONLY -> {
                        f.isDirectory || f.name.endsWith(filesFilter)
                    }
                    JFileChooser.FILES_AND_DIRECTORIES -> {
                        f.isDirectory || (f.isFile && f.name.endsWith(filesFilter))
                    }
                    JFileChooser.DIRECTORIES_ONLY -> {
                        f.isDirectory
                    }
                    else -> {
                        false
                    }
                }
            }

            override fun getDescription(): String {
                return description
            }
        }
        val status = jfc.showOpenDialog(null)
`
![image](https://user-images.githubusercontent.com/43124403/128281063-2f14588c-12d7-45dd-89bf-c6d90834ddcd.png)

**Comment by Genie23** [comment]
Hello,

I found myself with the same lens just a few days ago. After asking the question (and getting a link to one of the examples that uses jswing dialogs as an answer) I wrote this function :
```kotlin
class Dialog {
    enum class Mode { LOAD, SAVE }
}

@OptIn(DelicateCoroutinesApi::class)
@Composable
fun WindowScope.DialogFile(
    mode:Dialog.Mode = Dialog.Mode.LOAD,
    title:String = "Choisissez un fichier",
    extensions:List<FileNameExtensionFilter> = listOf(),
    onResult: (files: List<File>) -> Unit
) {
    DisposableEffect(Unit) {
        val job = GlobalScope.launch(Dispatchers.Swing) {
            val fileChooser = JFileChooser()
            fileChooser.dialogTitle = title
            fileChooser.isMultiSelectionEnabled = mode == Dialog.Mode.LOAD
            fileChooser.isAcceptAllFileFilterUsed = extensions.isEmpty()
            extensions.forEach { fileChooser.addChoosableFileFilter(it) }

            var returned:Int;
            if(mode == Dialog.Mode.LOAD) {
                returned = fileChooser.showOpenDialog(window)
            }
            else {
                returned = fileChooser.showSaveDialog(window)
            }

            onResult(when(returned) {
                JFileChooser.APPROVE_OPTION -> {
                    if(mode == Dialog.Mode.LOAD) {
                        val files = fileChooser.selectedFiles.filter { it.canRead() }
                        if(files.isNotEmpty()) {
                            files
                        }
                        else {
                            listOf()
                        }
                    } else {
                        if(!fileChooser.fileFilter.accept(fileChooser.selectedFile)) {
                            val ext = (fileChooser.fileFilter as FileNameExtensionFilter).extensions[0]
                            fileChooser.selectedFile = File(fileChooser.selectedFile.absolutePath + ".$ext")
                        }
                        listOf(fileChooser.selectedFile)
                    }
                };
                else -> listOf();
            })
        }

        onDispose {
            job.cancel()
        }
    }
}
```

However, as it is `@Composable`, it is not possible to use it in a callback (like the onClick function of a button for example).

Usage (in this example I use a window to retrieve one or more PDF files) :
```kotlin
DialogFile(mode = Dialog.Mode.LOAD, title = "Your dialog title", extensions = listOf(FileNameExtensionFilter("PDF Files", "pdf"))) { files ->
    // files is a List<File> object
}
```

In LOAD mode, you can select several documents, as long as they exist. It returns a list of File objects corresponding to all the selected files and accessible in reading.

In SAVE mode, you can either choose a file that exists or type in the name you want. If the file does not have an extension that matches the currently selected filter, the extension is added to the entered name. It returns a list of a File object corresponding to the selected file (existing or not). If you want to check if this file exists before overwriting it, you have to do this check yourself using the canRead() method of the File class for example.

**Comment by akurasov** [comment]
@virogu does it work for you?

**Comment by virogu** [comment]
> Hello,
> 
> I found myself with the same lens just a few days ago. After asking the question (and getting a link to one of the examples that uses jswing dialogs as an answer) I wrote this function :
> 
> ```kotlin
> class Dialog {
>     enum class Mode { LOAD, SAVE }
> }
> 
> @OptIn(DelicateCoroutinesApi::class)
> @Composable
> fun WindowScope.DialogFile(
>     mode:Dialog.Mode = Dialog.Mode.LOAD,
>     title:String = "Choisissez un fichier",
>     extensions:List<FileNameExtensionFilter> = listOf(),
>     onResult: (files: List<File>) -> Unit
> ) {
>     DisposableEffect(Unit) {
>         val job = GlobalScope.launch(Dispatchers.Swing) {
>             val fileChooser = JFileChooser()
>             fileChooser.dialogTitle = title
>             fileChooser.isMultiSelectionEnabled = mode == Dialog.Mode.LOAD
>             fileChooser.isAcceptAllFileFilterUsed = extensions.isEmpty()
>             extensions.forEach { fileChooser.addChoosableFileFilter(it) }
> 
>             var returned:Int;
>             if(mode == Dialog.Mode.LOAD) {
>                 returned = fileChooser.showOpenDialog(window)
>             }
>             else {
>                 returned = fileChooser.showSaveDialog(window)
>             }
> 
>             onResult(when(returned) {
>                 JFileChooser.APPROVE_OPTION -> {
>                     if(mode == Dialog.Mode.LOAD) {
>                         val files = fileChooser.selectedFiles.filter { it.canRead() }
>                         if(files.isNotEmpty()) {
>                             files
>                         }
>                         else {
>                             listOf()
>                         }
>                     } else {
>                         if(!fileChooser.fileFilter.accept(fileChooser.selectedFile)) {
>                             val ext = (fileChooser.fileFilter as FileNameExtensionFilter).extensions[0]
>                             fileChooser.selectedFile = File(fileChooser.selectedFile.absolutePath + ".$ext")
>                         }
>                         listOf(fileChooser.selectedFile)
>                     }
>                 };
>                 else -> listOf();
>             })
>         }
> 
>         onDispose {
>             job.cancel()
>         }
>     }
> }
> ```
> 
> However, as it is `@Composable`, it is not possible to use it in a callback (like the onClick function of a button for example).
> 
> Usage (in this example I use a window to retrieve one or more PDF files) :
> 
> ```kotlin
> DialogFile(mode = Dialog.Mode.LOAD, title = "Your dialog title", extensions = listOf(FileNameExtensionFilter("PDF Files", "pdf"))) { files ->
>     // files is a List<File> object
> }
> ```
> 
> In LOAD mode, you can select several documents, as long as they exist. It returns a list of File objects corresponding to all the selected files and accessible in reading.
> 
> In SAVE mode, you can either choose a file that exists or type in the name you want. If the file does not have an extension that matches the currently selected filter, the extension is added to the entered name. It returns a list of a File object corresponding to the selected file (existing or not). If you want to check if this file exists before overwriting it, you have to do this check yourself using the canRead() method of the File class for example.
> 
> And to make your dialog box look native (and this is true for all the swing dialog boxes I've tested so far), just add this at the beginning of your main function :
> 
> ```kotlin
> UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName())
> ```

Thanks for your advice
The main problem I encountered when using JFileChooser() was lag. I needed to use setCurrentDirectory() to set a default open path. Setting this would cause the dialog box to pop up for a long time, especially when there are many files in the folder.

**Comment by Genie23** [comment]
Indeed, JFileChooser tends to lag a bit, mainly on Windows - but file explorer in general tends to lag on my computer too. I used it for my first application to allow the selection of PDF files (my application is used to merge PDFs which can be of different page formats). I also tested it on macOS and two Linux (Fedora and Debian), I had less lags (I had lags, but it's on virtual machines and it wasn't unusual compared to other actions I did on these machines).

**Comment by akurasov** [comment]
I think any FileChooser application will lag in a huge folder, because it needs to read all files before displaying due to sort order.

**Comment by Genie23** [comment]
It's true that I hadn't thought about it until now, but on my Windows (also 10), the JFileChooser opens in my My Documents folder, which contains almost 500 items (folders or files) not counting what the folders inside contain, whereas on my virtual machines, of course, I have a lot less stuff (the file chooser opens in the user's folder, which contains about ten folders at most).

So that explains it, even if browsing on Windows, in a sub-folder of My Documents, which contains only a few folders, is also quite slow after all. I think that the list of files of the folders already browsed is maybe kept somewhere in memory, which would explain why a folder that doesn't contain many subfolders and files lags so much after arriving from a folder that contained so many items.

**Comment by Genie23** [comment]
It's true that I hadn't thought about it until now, but on my Windows (also 10), the JFileChooser opens in my My Documents folder, which contains almost 500 items (folders or files) not counting what the folders inside contain, whereas on my virtual machines, of course, I have a lot less stuff (the file chooser opens in the user's folder, which contains about ten folders at most).

So that explains it, even if browsing on Windows, in a sub-folder of My Documents, which contains only a few folders, is also quite slow after all. I think that the list of files of the folders already browsed is maybe kept somewhere in cache, which would explain why a folder that doesn't contain many subfolders and files lags so much after arriving from a folder that contained so many items.

**Comment by yuchuangu85** [comment]
I use it like this:

`@Composable
fun FileChooserDialog(
    title: String,
    onResult: (result: File) -> Unit
) {
    val fileChooser = JFileChooser(FileSystemView.getFileSystemView())
    fileChooser.currentDirectory = File(System.getProperty("user.dir"))
    fileChooser.dialogTitle = title
    fileChooser.fileSelectionMode = JFileChooser.FILES_AND_DIRECTORIES
    fileChooser.isAcceptAllFileFilterUsed = true
    fileChooser.selectedFile = null
    fileChooser.currentDirectory = null
    if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        val file = fileChooser.selectedFile
        println("choose file or folder is: $file")
        onResult(file)
    } else {
//        onResult(java.io.File(""))
        println("No Selection ")
    }
}`

**Comment by yuchuangu85** [comment]
I use it like this:

```kotlin
@Composable
fun FileChooserDialog(
    title: String,
    onResult: (result: File) -> Unit
) {
    val fileChooser = JFileChooser(FileSystemView.getFileSystemView())
    fileChooser.currentDirectory = File(System.getProperty("user.dir"))
    fileChooser.dialogTitle = title
    fileChooser.fileSelectionMode = JFileChooser.FILES_AND_DIRECTORIES
    fileChooser.isAcceptAllFileFilterUsed = true
    fileChooser.selectedFile = null
    fileChooser.currentDirectory = null
    if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        val file = fileChooser.selectedFile
        println("choose file or folder is: $file")
        onResult(file)
    } else {
//        onResult(java.io.File(""))
        println("No Selection ")
    }
}
```

**Comment by IARI** [comment]
@Genie23 if you can'T use it in a callback, I don'T understand how I can even use it at all
(probably I'm missing something fundamental about compose here)

**Comment by aoussou** [comment]
@IARI It's rather hacky, but based on https://github.com/JetBrains/compose-jb/issues/1003#issuecomment-1001187264 you can do something like

```
@Composable
@Preview
fun App() {
    var text by remember { mutableStateOf("select file") }
    var selectedFileString by remember { mutableStateOf("") }

    MaterialTheme {
        Column(
            modifier = Modifier.fillMaxSize(),
            horizontalAlignment = Alignment.CenterHorizontally
            ) {
            Button(onClick = {
                selectedFileString = fileChooserDialog(text)
            }) {
                Text(text)
            }

            Text(text = selectedFileString.ifBlank { "no file selected" })
        }
    }

}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}

fun fileChooserDialog(
    title: String?
): String {
    val fileChooser = JFileChooser(FileSystemView.getFileSystemView())
    fileChooser.currentDirectory = File(System.getProperty("user.dir"))
    fileChooser.dialogTitle = title
    fileChooser.fileSelectionMode = JFileChooser.FILES_AND_DIRECTORIES
    fileChooser.isAcceptAllFileFilterUsed = true
    fileChooser.selectedFile = null
    fileChooser.currentDirectory = null
    val file = if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        fileChooser.selectedFile.toString()
    } else {

        ""

    }

    return file

}
```

**Comment by olk90** [comment]
I've implemented a rudimentary file chooser in compose, that serves my purpose. It's a work-in-progress, though, but is there any chance that we might see a standard-compose file chooser in the future? 

https://github.com/olk90/compose-fileChooser

**Comment by fourlastor** [comment]
I found a way to use native dialogs in compose - https://github.com/fourlastor/nla-editor/pull/17 this PR uses LWJGL's native folder dialogs implementation to show the user a native file picker

**Comment by Parzival-05** [comment]
Using this code in a project that applies Jetpack Compose
```
@Composable
fun SelectFile(
    title: String = "Select SQLite file",
    onResult: (files: File) -> Unit
) {
    val fileChooser = JFileChooser()
    var selectedFile: File?
    fileChooser.dialogTitle = title
    fileChooser.fileSelectionMode = JFileChooser.FILES_ONLY
    fileChooser.isMultiSelectionEnabled = false
    fileChooser.fileFilter = object : javax.swing.filechooser.FileFilter() {
        override fun accept(file: File): Boolean {
            return file.name.endsWith(".sqlite")
        }

        override fun getDescription(): String {
            return "SQLite files (*.sqlite)"
        }
    }
    val result = fileChooser.showOpenDialog(null)
    if (result == JFileChooser.APPROVE_OPTION) {
        selectedFile = fileChooser.selectedFile
        onResult(selectedFile)
    }
}
```

I get error logs like this:

`Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Already resumed, but proposed with update kotlin.Unit
	at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:482)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:447)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:417)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:310)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:309)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:109)
	at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:87)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:309)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:552)
	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer.redrawImmediately(Direct3DRedrawer.kt:67)
	at org.jetbrains.skiko.SkiaLayer.paint(SkiaLayer.awt.kt:392)
	at androidx.compose.ui.awt.ComposeLayer$ComponentImpl.paint(ComposeLayer.desktop.kt:241)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedFPScales(RepaintManager.java:1720)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1569)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5266)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5076)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:878)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception while removing reference.

Process finished with exit code 0
`
And I have no idea how to fix this. Could you explain me what's going wrong?

**Comment by virogu** [comment]
> 

It seems that this error has nothing to do with "JFileChooser". " java.lang.IllegalStateException: Already resumed, but proposed with update kotlin.Unit"  This error is thrown out by the ”suspendCancellableCoroutine“ method，It usually occurs when repeatedly calls the resume method or call the "resume" method after the scope has been canceled， like this 
`
suspend fun test() = suspendCancellableCoroutine<String> {
        it.resume("")
        it.resume("") // Maybe throw this error
    }
`
some code in  'CancellableContinuationImpl'
`
    private fun resumeImpl(
        proposedUpdate: Any?,
        resumeMode: Int,
        onCancellation: ((cause: Throwable) -> Unit)? = null
    ) {
        _state.loop { state ->
            when (state) {
                is NotCompleted -> {
                    val update = resumedState(state, proposedUpdate, resumeMode, onCancellation, idempotent = null)
                    if (!_state.compareAndSet(state, update)) return@loop // retry on cas failure
                    detachChildIfNonResuable()
                    dispatchResume(resumeMode) // dispatch resume, but it might get cancelled in process
                    return // done
                }
                is CancelledContinuation -> {
                    /*
                     * If continuation was cancelled, then resume attempt must be ignored,
                     * because cancellation is asynchronous and may race with resume.
                     * Racy exceptions will be lost, too.
                     */
                    if (state.makeResumed()) { // check if trying to resume one (otherwise error)
                        // call onCancellation
                        onCancellation?.let { callOnCancellation(it, state.cause) }
                        return // done
                    }
                }
            }
            alreadyResumedError(proposedUpdate) // otherwise, an error (second resume attempt)
        }
    }


    private fun alreadyResumedError(proposedUpdate: Any?): Nothing {
        error("Already resumed, but proposed with update $proposedUpdate")
    }

`
”at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)“

It may be a problem with the compose itself
