### ISSUE TITLE
Windows Distribution: "installationPath" does not work

### ISSUE THREAD

**Issue by ghost** [JetBrains/compose-multiplatform#1018]
In versions `0.4.0` and `1.0.0-alpha3` the property `installationPath` as documented in https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution has does not work with absolute paths like `C:/WhereIWant/Company/Product` and only with relative path's like `MyCompany/MyProduct`.

You should give an example and clarify that on Windows only relative paths work or fix it if that's not the intention.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5328">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
