### ISSUE TITLE
Problem with the Windows installer generated when the application is already installed in the same version

### ISSUE THREAD

**Issue by Genie23** [JetBrains/compose-multiplatform#1032]
Hello,

I had a little trouble with my windows installer generated with the packageExe task of gradle. I finally figured out why, however, I'm thinking that maybe the system could be improved to be made clearer, so I'm opening this issue.

Basically, I had generated the Windows installer of my Compose application, and installed it to test it (I suspect that runDistributable must generate a fairly similar application, but I still wanted to test the installer itself and make sure that the application worked as well). Then, because I noticed some details I didn't like, I made some changes to my code, then after testing with runDistributable, I of course retested the installer, still for the same reasons.

Except that the installer did not start. I had a loading window that opened for a short time, then everything closed with the Windows error sound, without any other message. However, a process remained active despite the failure of the installer, preventing its repair (I had to close/open my session several times before understanding which process it was and killing it manually).

After testing in all directions and recreating my installer from start to finish (I deleted the .gradle and build folders to recreate everything from scratch) while taking the opportunity to migrate to the alpha4 pre-release in case the problem I couldn't find was fixed in the meantime, I finally understood that it was crashing when the application was already installed (both with the alpha3 release and with the alpha4 pre-release). So I retested my installer that was crashing (regenerated quite a few times, but it was always the same one, of course) after uninstalling my application, it worked without any problem.

I took the opportunity to test further while I was writing this post, so I changed my version number in build.gradle.kts to create a new version of my installer, without uninstalling the previous version, it worked fine. Moreover, the first installer, the one that didn't work once the application was installed, also finally worked (before I installed the new version) offering me to repair the installation or remove the software.

So there must be an anomaly in the way Windows installers are compiled, and yet I didn't get any error message, neither when generating the installer nor when running it (I tried to run it from a PowerShell window to see if I had any errors displayed in the console, just in case).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5318">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
