### ISSUE TITLE
1.0.0-aphpa3 new window can not close

### ISSUE THREAD

**Issue by toplinuxsir** [JetBrains/compose-multiplatform#1035]
import androidx.compose.desktop.Window
and  import androidx.compose.ui.window.Window
If the mainwindow use the new androidx.compose.ui.window.Window, and set onCloseRequest=::exitApplication,
When press the close button , the Window closed ,but the process still alive!

**Comment by igordmn** [comment]
Maybe you have a similar issue as [here](https://github.com/JetBrains/compose-jb/issues/1021#issuecomment-895061919)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5315">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
