### ISSUE TITLE
Refactor API for DesktopScreenshotTestRule

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1041]
Compose 1.0.0-alpha3

Currently it contains implementation details which shouldn't be public (like GoldenConfig).

We probably need to mark DesktopScreenshotTestRule as experimental.

Also DesktopScreenshotTestRule doesn't contain anything regarding Compose. Is it right that we have it as a public API in Compose? Should we move it to skiko?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5310">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
