### ISSUE TITLE
Animation use very high CPU usage on macOS

### ISSUE THREAD

**Issue by YeungKC** [JetBrains/compose-multiplatform#1054]
example 0: 

```kotlin

import androidx.compose.animation.core.*
import androidx.compose.material.Text
import androidx.compose.runtime.getValue
import androidx.compose.ui.window.singleWindowApplication

fun main() {
    singleWindowApplication {
        val transition = rememberInfiniteTransition()
        val frameIndex by transition.animateValue(
            initialValue = 0,
            targetValue = 63,
            Int.VectorConverter,
            animationSpec = infiniteRepeatable(
                animation = keyframes {
                    durationMillis = 0
                    for (index in 0 until 64) {
                        index at durationMillis
                        durationMillis += 100
                    }
                }
            )
        )

        Text("frameIndex: $frameIndex")
    }
}

```

![image](https://user-images.githubusercontent.com/11473691/129437462-c2b51250-b387-4959-a6df-b2df291479c6.png)

example 1: 

```kotlin

import androidx.compose.animation.core.*
import androidx.compose.foundation.layout.Column
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.window.singleWindowApplication

fun main() {
    singleWindowApplication {
        var value by remember { mutableStateOf(0) }
        val transition = updateTransition(value)
        val transitionValue by transition.animateInt( {
            TweenSpec(durationMillis = 10000)
        }, targetValueByState = {
            it
        })

        Column {
            Text("transitionValue: $transitionValue")
            Button(onClick = {
                value = 64
            }) {
                Text("to 64")
            }
            Button(onClick = {
                value = 0
            }) {
                Text("to 0")
            }
        }
    }
}

```
![image](https://user-images.githubusercontent.com/11473691/129437418-3a670252-6798-41cb-91a7-646ded0a3fd4.png)

**Comment by igordmn** [comment]
Found the reason, investigating how to fix it.

If we don't use `application`/`singleWindowApplication`, just Swing's `ComposeWindow`:
```
import androidx.compose.animation.core.*
import androidx.compose.material.Text
import androidx.compose.runtime.getValue
import androidx.compose.ui.awt.ComposeWindow
import androidx.compose.ui.window.singleWindowApplication
import java.awt.Dimension
import javax.swing.SwingUtilities

fun main() = SwingUtilities.invokeLater {
    ComposeWindow().apply {
        size = Dimension(500, 500)
        setContent {
            val transition = rememberInfiniteTransition()
            val frameIndex by transition.animateValue(
                initialValue = 0,
                targetValue = 63,
                Int.VectorConverter,
                animationSpec = infiniteRepeatable(
                    animation = keyframes {
                        durationMillis = 0
                        for (index in 0 until 64) {
                            index at durationMillis
                            durationMillis += 100
                        }
                    }
                )
            )

            Text("frameIndex: $frameIndex")
        }
        isVisible = true
    }
}
```
then CPU usage is 1% instead of 10% (on Windows)

**Comment by YeungKC** [comment]
> Found the reason, investigating how to fix it.
> 
> If we don't use `application`/`singleWindowApplication`, just Swing's `ComposeWindow`:
> 
> ```
> import androidx.compose.animation.core.*
> import androidx.compose.material.Text
> import androidx.compose.runtime.getValue
> import androidx.compose.ui.awt.ComposeWindow
> import androidx.compose.ui.window.singleWindowApplication
> import java.awt.Dimension
> import javax.swing.SwingUtilities
> 
> fun main() = SwingUtilities.invokeLater {
>     ComposeWindow().apply {
>         size = Dimension(500, 500)
>         setContent {
>             val transition = rememberInfiniteTransition()
>             val frameIndex by transition.animateValue(
>                 initialValue = 0,
>                 targetValue = 63,
>                 Int.VectorConverter,
>                 animationSpec = infiniteRepeatable(
>                     animation = keyframes {
>                         durationMillis = 0
>                         for (index in 0 until 64) {
>                             index at durationMillis
>                             durationMillis += 100
>                         }
>                     }
>                 )
>             )
> 
>             Text("frameIndex: $frameIndex")
>         }
>         isVisible = true
>     }
> }
> ```
> 
> then CPU usage is 1% instead of 10% (on Windows)

This also work for macOS, then CPU usage is around 9%.

**Comment by igordmn** [comment]
The bug with `singleWindowApplication` is fixed in v1.0.0-alpha4-build396.

I leave this issue open, as there are more ways to improve CPU/GPU usage.

For example, when we call `animateValue` or `withFrameNanos`, we constantly redraw the whole window content with 1 frame per 16ms, even if the animation should be updated as 1 frame per 100ms (or per 500ms as TextField cursor).

To fix that, we should add [a new feature in skiko](https://github.com/JetBrains/skiko/issues/53), which will allow to keep the buffer intact if there is no changes.

**Comment by igordmn** [comment]
> I'm not sure if is is related to animation, but CPU usage is about 100% when TextField has focus and cursor is blinking in it.

Blinking of the cursor is an animation.

Is CPU usage low in 1.0.0-alpha4-build396?

**Comment by ice1000** [comment]
Wow! When will this improvement be adapted to Toolbox App?

**Comment by igordmn** [comment]
>Wow! When will this improvement be adapted to Toolbox App?

Toolbox doesn't use `application`/`singleWindowApplication`, it uses ComposeWindow directly. So the issue with the high CPU usage in Toolbox probably is another issue. Don't know if it will be fixed in the next build.

In Compose/Skiko there were two more fixes regarding CPU usage:
- [high CPU usage during animation on Linux GPU rendering (and Windows/Linux software rendering)](https://github.com/JetBrains/skiko/pull/148)
- [high CPU usage during a hidden state of the window](https://github.com/JetBrains/skiko/pull/149)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5303">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
