### ISSUE TITLE
suggest add multiple exe

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-multiplatform#1056]
As we know,It's only appear one exe file when created distributable, but it is not enough.
![image](https://user-images.githubusercontent.com/23566361/129480964-5a6f37d9-0698-404d-8d86-e08922938bea.png)
I must create another exe ("update.exe") to update my app, So I must generate the exe by C++, .Net ,and so on
and it is trouble
It is efficient if jetpack compose support multiple exe(multiple process)
We can specify a jar for each exe.In this way, multiple processes can be realized

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5301">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
