### ISSUE TITLE
Nested Menu looks bad

### ISSUE THREAD

**Issue by ctadlock** [JetBrains/compose-multiplatform#1068]
- kotlin: 1.5.21
- org.jetbrains.compose: 1.0.0-alpha3
- Windows 10

I took the example notepad application and added a nested `Menu` and `Item`s to it and it looks like this..

![image](https://user-images.githubusercontent.com/1539397/129679737-94e67662-d6dc-4c9d-a750-2a4f8793588b.png)

 A standard Swing menu should look like this...

![image](https://user-images.githubusercontent.com/1539397/129680152-5b4af736-1bd9-4c55-b43f-81f0e4ead7dc.png)

**Comment by igordmn** [comment]
> Nested Menu looks bad

I see two graphic glitches:
- the shadow line cuts when submenu is above the compose content
- resolution of ">" is too bad

> A standard Swing menu should look like this...

We don't use standard Swing look and feel, as it outdated and doesn't fit neither system design or material design.

We set this:
```
UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName())
```
for any application launched with Compose Gradle plugin (`./gradlew run`).

And don't use, if application is the part of another Swing application (like IDEA plugin)

**Comment by ctadlock** [comment]
@igordmn Where in the code is the look and feel of the menu bars set?

**Comment by igordmn** [comment]
> @igordmn Where in the code is the look and feel of the menu bars set?

It is [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/window/Application.desktop.kt;l=73;drc=f34661dba6bcbac9555bd4a8339fe48a40ab71b4)

If you set your own look and feel, run it with [-Dcompose.application.configure.swing.globals=false](https://github.com/JetBrains/compose-jb/blob/b1d8682cbe7495bcb176260db43aa05d009b3daa/gradle-plugins/compose/src/test/test-projects/application/defaultArgsOverride/build.gradle#L29)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5294">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
