### ISSUE TITLE
Asynchronous resource loading

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#107]
Android supports asynchronous loading:
```
@Composable
fun loadFontResource(...): DeferredResource<Typeface>

@Composable
fun loadVectorResource(...): DeferredResource<VectorAsset>

@Composable
fun loadImageResource(...): DeferredResource<ImageAsset>
```
We need to implement it on desktop too (and also move some of the classes to commonMain)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6388">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
