### ISSUE TITLE
Sign Windows .exe before packaging into .msi

### ISSUE THREAD

**Issue by ctadlock** [JetBrains/compose-multiplatform#1079]
Is there way to sign the generated `.exe` before it is packaged into the `.msi`?

Would need a way to run a Gradle task after the `createDistribution` task and before `packageMsi`.

Could use [jsign](https://ebourg.github.io/jsign/) or just command line:
`"C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe" sign /f $pfxPath /p $signPwd ".\output\MyApp.exe"`

The `.msi` can be signed after packaging with:
`"C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe" sign /f $pfxPath /p $signPwd $msiPath`

**Comment by ctadlock** [comment]
@AlexeyTsvetkov  Any update on this? I dont see how a production application could be deployed until this is resolved?

**Comment by ctadlock** [comment]
10 months later... is there a way to do this?

**Comment by ctadlock** [comment]
For anyone else that comes along my suggestion is to not use the compose desktop plugin for the creation of the runtime and installer. Much better to use [beryx/badass-runtime-plugin](https://github.com/beryx/badass-runtime-plugin). You can then add a task to call jsign to sign both the exe and the msi.

The one important thing you must do is add `-Dcompose.application.configure.swing.globals=true` as a command line arg. It ultimatley will run some code to configure swing and some other system code.

```
application {
    mainClass.set("...")
    applicationDefaultJvmArgs = listOf("-Dcompose.application.configure.swing.globals=true")
}
```

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/ConfigureSwingGlobalsForCompose.desktop.kt?q=configureSwingGlobalsForCompose&ss=androidx%2Fplatform%2Fframeworks%2Fsupport:compose%2Fui%2Fui%2Fsrc%2FdesktopMain%2Fkotlin%2Fandroidx%2Fcompose%2F

**Comment by sebkur** [comment]
@ctadlock is the application you were working on here open source by any chance?

**Comment by ctadlock** [comment]
@sebkur Nope, sorry

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5285">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
