### ISSUE TITLE
How to do string translation (i18n)?

### ISSUE THREAD

**Issue by ctadlock** [JetBrains/compose-multiplatform#1080]
Is there code/guidance on how to handle string translation? What is below works but is a bit clunky.

Here is a simple use case of translating a `Menu` `text`.

I created a `Strings.properties` file in `resources/` with:

```
main.menu.app.text=App
```

##### Menu code
```
Menu(text = stringResource("Strings","main.menu.app.text"))
```

##### Helper
```
fun stringResource(baseName: String, key: String) : String {

    val bundle = ResourceBundle.getBundle(baseName)

    return if (bundle.containsKey(key)) {
        bundle.getString(key)
    } else {
        key
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5284">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
