### ISSUE TITLE
Inconsistent LineHeight Desktop JVM Linux / Windows vs. Mac OS X

### ISSUE THREAD

**Issue by christoph-grimm** [JetBrains/compose-multiplatform#1082]
In a (Basic)Textfield or TextField or Text, the Lineheight specification results in inconsistent behavior on different Platforms (JVM on Linux/Windows vs. Mac OS X): 

```        
@Composable
BasicTextField(
            value = lines.value,
            textStyle = TextStyle(
                fontSize = AppTheme.fontSize,
//                lineHeight =AppTheme.fontSize*2.5f, // Needed on Mac to get correct line size that is too large for Linux. 
                ),
            onValueChange = { lines.value = it  }
) 
```

On MAC: 
- empty (or only space) lines get rendered with very small line height, unless lineHeight is explicitly set fo 2.5f * fontSize

On Linux/Windows: 
- empty (or only space) lines get rendered in the above case with much higher lineHeigt that seems to be more the intuitive expected behavior of the spec "LineHeigt". 

Unclear if unclear spec, issue in above code (but: what is correct rendering, then? ), or inconsistency in Implementation on Mac vs. Linux/Win platforms.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6319">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
