### ISSUE TITLE
Support fastlane for osx build code signing

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-multiplatform#1090]
I don't know much about signing ios based builds, but after having gone through the difficult process of setting everything up to sign my compose desktop build for osx on my machine I see exactly why something like fastlane exists. All iOS builds for iOS apps at my company are signed with fastlane, and it looks like a solution that allows signing iOS builds without requiring going through a lengthy machine setup process on every machine you want to build on. This also makes managing CI workflows much simpler, as OSX VMs can be used.

Compose Desktop needs something similar so that teams can setup CI for their production builds easily. I don't see an easy way to integrate this into the compose gradle plugin currently, but it would be nice for something like fastlane to be supported.

https://docs.fastlane.tools/codesigning/getting-started

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6318">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
