### ISSUE TITLE
example/widgets-gallery packaged+installed crashes on Windows 10

### ISSUE THREAD

**Issue by ehealthexperts-rk** [JetBrains/compose-multiplatform#1096]
In order to hunt down performance issues customers experienced on Windows 10 I tried to give them a plain app from the official examples as windows installer. As example I chose the [widgets-gallery](https://github.com/JetBrains/compose-jb/tree/master/examples/widgets-gallery) and followed the simple `gradlew :desktop:package` from the README. `gradlew :desktop:run` worked fine.

I could install the resulting msi. However when I executed the installed exe the UI did not show up and the launched process disappeared in the task manager. The same happened with the `todo`-app. 
I also changed the TargetFormat from MSI to EXE, installed via the exe installer but could not launch the app.
Unfortunately I don't know if or where logs would be written to determine what was actually failing.

I tried to build the app first within a virtualbox windows image (Version 1809 build 17763.1935 with an AdoptOpenJdk 16 Hotspot) and later on a "real" Windows PC (Version 21H1 build 19043.1110 with an Oracle OpenJdk 16.0.2) with the same result.

As I remember the try in virtualbox was first with the code version of v0.5.0-build262 while on the real PC was the master code from today (around v1.0.0-alpha4-build318).

Can you confirm the issue?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6259">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
