### ISSUE TITLE
Can't trigger previews from the keyboard

### ISSUE THREAD

**Issue by asapha** [JetBrains/compose-multiplatform#1105]
The action provided by the plugin (`RefreshOrRunPreviewAction`) can only be triggered once per IDE launch.

**Repro**
- Have an assigned shortcut to `RefreshOrRunPreviewAction` in Intellij's keymap.
- Start Intellij (or restart if you previously used compose previews during the session)
- Set your cursor to any `@Preview` methods
- Use your shortcut
- (The preview is successfully displayed)
- Make a change or move to another `@Preview` method
- Use your shortcut again

There's no build or preview change the second time.

**System Info**
```
IntelliJ IDEA 2021.2.1 (Ultimate Edition)
Build #IU-212.5080.55, built on August 24, 2021
Runtime version: 11.0.11+9-b1504.16 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3000M
Cores: 12
Registry: js.debugger.webconsole=false
Non-Bundled Plugins: org.jetbrains.compose.desktop.ide (1.0.0-alpha4-build328)
Kotlin: 212-1.5.30-release-409-IJ4638.7
```

**Additional info**
I poked a bit around the plugin code and `RefreshOrRunPreviewAction.actionPerformed` is only called once when using the shortcut. Removing [`e.presentation.isEnabled = false`](https://github.com/JetBrains/compose-jb/blob/e8e02771a0a5bfc58606344d84715fd33937ef08/idea-plugin/src/main/kotlin/org/jetbrains/compose/desktop/ide/preview/PreviewActions.kt#L42) fixes the issue but I don't know if there's any side effect. 🤷‍♂️

edit: added more details

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6046">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
