### ISSUE TITLE
Mounted DMG Image Uses Java Icon

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-multiplatform#1115]
<img width="58" alt="Screen Shot 2021-08-24 at 8 51 25 PM" src="https://user-images.githubusercontent.com/871169/130938717-5330275d-2fd8-47ab-8a0c-e261128148de.png">

When I open a dmg and the image is mounted, this is the icon that I see. I have a custom icon set for my icon, and that icon should be being used, but instead I'm left with what I assume is the default Java icon.

**Comment by qiujuer** [comment]
Can I choose the default disk style?
![image](https://user-images.githubusercontent.com/5687320/131771923-81ef9cf0-4660-4410-b58c-6d8a2289d5a4.png)

**Comment by ScottPierce** [comment]
Does anyone know of a work around for this in the mean time? Shipping an app with this is ugly.

**Comment by igordmn** [comment]
How do you set icon for the application?

Look at [imageviewer](https://github.com/JetBrains/compose-jb/blob/master/examples/imageviewer/desktop/build.gradle.kts#L34)

I made a package with JDK16:
```
./gradlew package
```

And the icon was okay (when we install app, or launch it)

**Comment by ryanmitchener** [comment]
@igordmn even with the iconFile set, the image of the mounted dmg on the desktop is the default java icon. The application icon is correct, just not the mounted dmg icon. This happens when "External Disks" is selected in finder preferences
![Screen Shot 2021-11-19 at 1 54 41 PM](https://user-images.githubusercontent.com/6433145/142676432-2228740f-3436-4aa6-b3bb-5ff6e47dd174.png)
.

**Comment by asapha** [comment]
When using `jpackage`, this is done by adding a `AppName-volume.icns` file to a "resource" folder. This folder needs to be passed via the `--custom-dir resource_dir` option.

[jpackage docs](https://docs.oracle.com/en/java/javase/16/jpackage/override-jpackage-resources.html)
[Related issue about --custom-dir](https://github.com/JetBrains/compose-jb/issues/773)

**Comment by joseluiskuuc** [comment]
@akurasov any updates about this bug? : When I open a dmg and the image is mounted, this is the icon that I see. I have a custom icon set for my icon, and that icon should be being used, but instead I'm left with what I assume is the default Java icon.
