### ISSUE TITLE
How to implement Flutter-like Draggable DragTarget widget?

### ISSUE THREAD

**Issue by LeonDevLifeLog** [JetBrains/compose-multiplatform#1120]
A widget that can be dragged from to a DragTarget.

https://api.flutter.dev/flutter/widgets/Draggable-class.html

like this https://youtu.be/QzA4c4QHZCY

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1120">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
