### ISSUE TITLE
SkijaLayer should support camera distance

### ISSUE THREAD

**Issue by nadewad** [JetBrains/compose-multiplatform#1129]
Google has added support for camera distance APIs to provide skew visual effects. However, the current implementation of SkijaLayer does not expose Sk3dView within Skia to support the same API surface:

See:
https://android-review.googlesource.com/c/platform/frameworks/support/+/1475539/11/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/SkijaLayer.kt

**Comment by igordmn** [comment]
[Related issue](https://github.com/JetBrains/compose-jb/issues/12)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6063">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
