### ISSUE TITLE
Figure out if we can get rid of DesktopRootForTest

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1137]
Compose 1.0.0-alpha3

Android target doesn't use some AndroidRootForTest, it uses RootForTest. Maybe desktop can do it too

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6307">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
