### ISSUE TITLE
Same background fill color rendered differently by Compose and Swing / Java2D

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-multiplatform#1156]
Run this under the latest alpha build:

```
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.awt.SwingPanel
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.*
import javax.swing.JPanel

fun main() = application {
    val state = rememberWindowState(
        placement = WindowPlacement.Floating,
        position = WindowPosition.Aligned(Alignment.Center),
        size = WindowSize(200.dp, 180.dp)
    )

    Window(
        title = "Panels",
        state = state,
        undecorated = true,
        onCloseRequest = ::exitApplication,
    ) {
        Column(modifier = Modifier.fillMaxSize()) {
            // This is Compose content
            Row(
                modifier = Modifier.fillMaxWidth().weight(0.5f)
                    .background(androidx.compose.ui.graphics.Color(0xfff9be84))
            ) {}

            // This is Swing content
            SwingPanel(
                modifier = Modifier.fillMaxWidth().weight(0.5f),
                factory = {
                    JPanel().apply {
                        background = java.awt.Color(0xf9be84)
                    }
                }
            )
        }
    }
}
```

See the difference in how the same color #F9BE84 is rendered.

**Comment by kirill-grouchnikov** [comment]
<img width="246" alt="panels" src="https://user-images.githubusercontent.com/52874/133120287-846208c4-5195-4d5e-9e8b-8213da8d3f8b.png">

**Comment by kirill-grouchnikov** [comment]
Top half rendered by Compose, bottom half rendered by Swing. There is a noticeable difference in vibrancy / saturation.

**Comment by igordmn** [comment]
I compared the colors with the default macOs Pages application - the color is the same as in Compose.

Probably Swing doesn't apply color correction which is set in the system settings.

In that case, the color correction should be applied manually to the Swing component, via skiko converters somehow (don't know yet how exactly).

Another option is to provide API to change color correction. Something like `ComposeWindow.setColorSpace(ColorSpace?)`, but it is not easy, and probably will be inconsistent with the rest of the system.

P.S. on Windows colors are the same.

**Comment by kirill-grouchnikov** [comment]
The real-world interop examples are going to be more complex than this, with multiple Swing components painted by the installed look-and-feel, so it might not be easy to go in and tweak every single background / foreground color on the Swing side.

When I run "Digital Color Meter" app and compare the colors, I see:

1. The requested color F9BE84 is red=249, green=190, blue=132
2. Swing paints red=245, green=190, blue=132
3. Compose paints red=240, green=191, blue=140

Swing is not exactly what was "requested", but much closer. I can't say which one is the "right" one, but this is going to be problematic for interop.

**Comment by igordmn** [comment]
Yes, it is definitely an issue for interop.

On one thing I am certain - we should be close to the colors which are dictated by OS.

I wish there was a method in Swing that allows us to change the color space of the Swing Component. If we won't find such method, all we can do is to provide a helper method to convert colors, or method to change color space for Compose.

**Comment by kirill-grouchnikov** [comment]
That's certainly something that I can plug into Radiance on the Swing side. Some sort of a `Color -> Color` mapping that, when present, is applied on all colors supplied by the look-and-feel, as well as by the application code set on core Swing components like panels, etc. 

There's still going to be direct painting with `paintComponent` drawing directly on `Graphics2D`, so it might not fully solve it without changing that application code.

**Comment by romainguy** [comment]
When using "Digital Color Meter", select "Display in sRGB" from the drop down to see the original values you've specified. I suspect what might be happening is that either Swing or Compose is not tagging its backing window as sRGB at the OS level. Using your screenshot, it seems Compose is doing the right thing, but Swing is not (a problem I had to fix in Android Studio for exactly the same reasons btw; my fix was to tag the backing window as sRGB).

**Comment by kirill-grouchnikov** [comment]
Is there an API to do this on AWT `Window` or Compose's `ComposeWindow`?

**Comment by romainguy** [comment]
Not that I know of no.

**Comment by kirill-grouchnikov** [comment]
Now this looks like a job for Skiko :)

**Comment by romainguy** [comment]
Alternatively Skiko could convert all colors to the display gamut :)

**Comment by kirill-grouchnikov** [comment]
Whichever magic way that treats the same RGB values to create the same final color on the screen (even if technically it might be "off" in one of the color meter modes) is fine with me

**Comment by kirill-grouchnikov** [comment]
Color spaces are already there - https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/ColorSpace.kt

**Comment by romainguy** [comment]
-ish :p

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5277">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
