### ISSUE TITLE
Hope compose-jb adds its own file selector API instead of continuing to use the old java's awt and swing

### ISSUE THREAD

**Issue by tzSharing** [JetBrains/compose-multiplatform#1158]
### Hope that compose-jb adds its own file selector API instead of continuing to use the old java's awt and swing.

`Benefits:`

- It will reduce the burden of error-prone interaction between kotlin and java
- It will reduce the burden of importing too many dependencies
- Direct and efficient

**Comment by christoph-grimm** [comment]
In our application we have created it based on a tree view composable. 
Willing to share these composables once more generic -- but do not know where to share ... 

Drop me message if interested.

**Comment by darvld** [comment]
@christoph-grimm you could submit a PR to this repo and add it as a component. It would really help. I'd be willing to contribute to it once available.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5275">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
