### ISSUE TITLE
Compose Gradle Plugin. Compile time check for Java version

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#117]
Minimal version for Android target should be Java 1.8
Minimal version for Desktop target should be Java 11

If Java has incompatible version we should throw exception with user-friendly message.

**Comment by AlexeyTsvetkov** [comment]
@igordmn why does the minimal version for desktop must be Java 11?

**Comment by igordmn** [comment]
> @igordmn why does the minimal version for desktop must be Java 11?

This is our decision for desktop - to support only Java 11-*. https://github.com/JetBrains/compose-jb/tree/master/tutorials/Getting_Started#prerequisites

**Comment by AlexeyTsvetkov** [comment]
I don't understand the rationale behind this, and what exactly is required.
Should we limit Kotlin JVM target bytecode version or Java compile target version?
Or is it about runtime JDK?

**Comment by igordmn** [comment]
It is about runtime JDK.

We can use features which was only introduced in Java 11.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5614">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
