### ISSUE TITLE
Implement all unimplemented methods inside ui-test module

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1177]
Search TODO() in this module:
![image](https://user-images.githubusercontent.com/5963351/133823208-4d752996-7586-4d80-a6f0-64ea96a404fa.png)

**Comment by qradimir** [comment]
Any ETA on this issue? It would be great to have an ability to use `performTextInput ` in desktop tests.

**Comment by serandel** [comment]
So you wanna use `performTextInput`? You're an ambitious one! I just wished to humbly call `assertIsDisplayed` on a node... ;)

(See https://github.com/JetBrains/androidx/blob/jb-main/compose/ui/ui-test/src/desktopMain/kotlin/androidx/compose/ui/test/DesktopAssertions.desktop.kt)

Now seriously, is this on the roadmap for 1.2.0? Desktop UI testing is basically impossible as of now...

**Comment by serandel** [comment]
By skimming the referenced commit, I'd say everything is done but for pressing keys down and release them up, am I right?

Also, which milestone is this added to? 1.2.0? 1.3.0?

Thanks!

**Comment by igordmn** [comment]
Oh, sorry for confusion. It was closed automatically, even when I wrote "Partially fixed" 🤦.

Full official test support is not on roadmap for 1.2, we are just doing small incremental fixes now.

**Comment by serandel** [comment]
I appreciate the quick answer! :)

**Comment by igordmn** [comment]
> I'd say everything is done but for pressing keys down and release them up

That, and:
- methods inside DesktopAssertions
- dialog testing support
- the main clock advancement (there are some issues)
- fix all bugs and race conditions

**Comment by igordmn** [comment]
Fixed in 1.5.0-beta02

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5264">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
