### ISSUE TITLE
Android artifacts. Get rid of publication of two artifacts ("debug" and "release")

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#118]
Now we have two android artifacts:
org.jetbrains.compose.animation:animation-android:0.2.0-build124
org.jetbrains.compose.animation:animation-android-debug:0.2.0-build124

The need of "debug" artifact seems strange.

Figure out how to change MPP publication configuration so we can only publish "org.jetbrains.compose.animation:animation-android".

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5613">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
