### ISSUE TITLE
Convenient way to use system dialogs from Composables in deep navigation hierarchy 

### ISSUE THREAD

**Issue by yaroslavkulinich** [JetBrains/compose-multiplatform#1181]
Hello.

Currently, to show system dialog for file selection (like JFileChooser) we need to provide an instance of the current Window to JFileChooser.showOpenDialog() function. And it's ok if your dialog call happens directly inside androidx.compose.ui.window.Window Composable (as show [here](https://github.com/JetBrains/compose-jb/issues/1003#issuecomment-893530038)). 

But when we need to call dialog from the Composable that is located deeper in the navigation hierarchy of the app, we have a problem. Somehow we need to:
- Provide WindowScope (to get Window instance) through all hierarchy layers down to our call site;
- Abstract from platform-specific Window instance to make it possible to use our Composable in the common source set.

So I think it would be great to have a clear, convenient, and well-described way to use system dialogs from Composable functions. 

Maybe I missed something and the problem is already solved or there is no problem at all - so I ask you to share this information or show another approach of using system dialogs.

Thank you.

**Comment by Omico** [comment]
The easiest way to get rid of `WindowScope` is to provide a `LocalWindowScope`.

```kotlin
val LocalWindowScope = staticCompositionLocalOf<WindowScope> {
    error("LocalWindowScope is not initialized")
}

Window {
    CompositionLocalProvider(
        LocalWindowScope provides this@Window,
        content = { MainUI() }
    )
}

@Composable
fun WindowScope.DialogFile() {
// Same thing in https://github.com/JetBrains/compose-jb/issues/1003#issuecomment-893530038
}

@Composable
fun DialogFile() {
    LocalWindowScope.current.DialogFile()
}

@Composable
fun MainUI() {
    DialogFile()
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5260">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
