### ISSUE TITLE
Fix deadlock in MenuBarTest

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1184]
The deadlock is happened if we run all tests on 15c82ee9 commit on macOs. If we run MenuBarTest individually, there is no deadlock.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5257">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
