### ISSUE TITLE
Native distribution, produces invalid package*.args.txt 

### ISSUE THREAD

**Issue by Louis9902** [JetBrains/compose-multiplatform#1204]
I encountered the following problem when building a native distribution for my compose app:
```
External tool execution failed:
* Command: [/usr/lib/jvm/java-17-openjdk-17.0.0.0.35-1.rolling.fc34.x86_64/bin/jpackage, @/home/louis/Downloads/freiheit-crm/build/compose/tmp/packageRpm.args.txt]
* Working dir: []
* Exit code: 1
* Standard output log: /home/louis/Downloads/freiheit-crm/build/compose/logs/packageRpm/jpackage-2021-09-28-08-40-01-out.txt
* Error log: /home/louis/Downloads/freiheit-crm/build/compose/logs/packageRpm/jpackage-2021-09-28-08-40-01-err.txt
```

The packageRpm.args.txt file looks like: 
[packageRpm.args.txt](https://github.com/JetBrains/compose-jb/files/7241799/packageRpm.args.txt)

I narrowed the problem down to the `--input` and the `--main-jar` arguments that seems to point to no where. Now the question is should they point to an actual file or are they just wrong? If I point them to the `.../build/libs/` folder and to other to the main artifact it works as expected

Some additional system information:
I'm on fedora 35 and using IntelliJ CE (Build #IC-212.5284.40)
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment 21.9 (build 17+35)
OpenJDK 64-Bit Server VM 21.9 (build 17+35, mixed mode, sharing)
```

> __side note:__ Maybe add an information to the native package README that on some distros the jmods must be installed as separate package and the native package tools like (rpm,dpkg) must be also installed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5245">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
