### ISSUE TITLE
[Web] Mounting a stylesheet with CSS classes in components generates no-style intermediate composition

### ISSUE THREAD

**Issue by SalomonBrys** [JetBrains/compose-multiplatform#1207]
Using "CSS classes in components" with the following syntax:

```kotlin
classes(AppStyleSheet.css {
    backgroundColor(if (bool) Color.red else Color.blue)
})
```

...with `MyStyleSheet` being mounted at the beginning of the compose tree:

```kotlin
fun main() = renderComposableInBody { 
    Style(AppStyleSheet)
    // ...
}
```

...creates intermediate composition with new classes not being rendered (as shown in the demo project).

This intermediate composition creates janks that becomes visible on big compose trees.

[Here is a project demonstrating the issue](https://github.com/SalomonBrys/demo-InHeadComposeStyleSheet) and [a proposed solution](https://github.com/SalomonBrys/demo-InHeadComposeStyleSheet/blob/main/src/jsMain/kotlin/style/InHeadRulesHolder.kt).

I propose extracting style rendering outside of Compose, which makes new classes immediately available, provokes no recomposition when new classes are generated, and eliminates visible janks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5244">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
