### ISSUE TITLE
Multiplatform examples and templates. Merge all modules into one single module

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#121]
We separated multiplatform project into common/android/desktop modules because we had issues with plugin compatibility ("application" plugin doesn't compatible with "com.android.application").

But now we don't use "application" plugin, so maybe we can rewrite most of our examples and templates with single module.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5610">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
