### ISSUE TITLE
SVG doesn't support CSS classes (the image is black)

### ISSUE THREAD

**Issue by RedStoneCats101** [JetBrains/compose-multiplatform#1217]
.svg is drawn incorrectly, IntelliJ displays it properly, .png works fine (Mac OS intel)

kotlin("jvm") version "1.5.31"
id("org.jetbrains.compose") version "1.0.0-alpha4-build366"

svg
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1000 1000"><defs><style>.cls-1{fill:url(#linear-gradient);}.cls-2{fill:#fff;}.cls-3{fill:none;}</style><linearGradient id="linear-gradient" x1="99.57739" y1="896.26053" x2="907.57939" y2="88.25852" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#00b3ff"/><stop offset="0.06646" stop-color="#11a9ff"/><stop offset="0.19876" stop-color="#3f8dff"/><stop offset="0.3827" stop-color="#8762ff"/><stop offset="0.48334" stop-color="#b148ff"/><stop offset="0.68363" stop-color="#ce5d9f"/><stop offset="1" stop-color="#ff8100"/></linearGradient></defs><rect class="cls-1" x="99.57739" y="88.25852" width="808.002" height="808.002"/><path class="cls-2" d="M93.82016,135.38033c-13.85638,0-24.24761,10.41994-24.24761,24.31459s10.39334,24.3146,24.24761,10.41994h128.1641c13.85638,13.89466,24.24761,3.4726,24.24761-10.41994,0-10.422-10.39123-20.842-24.24761-24.31459Z" transform="translate(375 375)"/><path class="cls-2" d="M-51.66125,180.53479l86.59708-79.889c3.463-3.47473,3.463-13.89466,0-17.36727L-51.66125-3.55777c-6.92819-10.41993-20.78456-10.41993-31.17579,0-10.39123,6.94521-10.39123,20.83987,0,31.2598l51.95825,52.10179c3.46515,3.47472,3.46515,13.89466,0,17.36726L-82.837,149.27287c-10.39123,6.94733-10.39123,20.842,0,31.26192C-75.90885,190.95473-62.05247,190.95473-51.66125,180.53479Z" transform="translate(375 375)"/><path class="cls-2" d="M-214.79961,435.78781V-84.38846a26.73749,26.73749,0,0,1,26.70053-26.7743h671.315a26.7375,26.7375,0,0,1,26.70054,26.7743V435.78781a26.7375,26.7375,0,0,1-26.70054,26.7743h-671.315A26.73749,26.73749,0,0,1-214.79961,435.78781Zm762.859,49.72236V-248.857a53.47382,53.47382,0,0,0-53.3999-53.54742h-732.344a53.475,53.475,0,0,0-53.40106,53.54859V485.51133a53.47381,53.47381,0,0,0,53.3999,53.54742H494.65834A53.475,53.475,0,0,0,548.05941,485.51017ZM250.54486-176.18537a34.23383,34.23383,0,0,1-34.32959-34.42326,34.23383,34.23383,0,0,1,34.32959-34.42326,34.23383,34.23383,0,0,1,34.32958,34.42326A34.23529,34.23529,0,0,1,250.54486-176.18537Zm102.98643,0a34.23383,34.23383,0,0,1-34.32959-34.42326,34.23383,34.23383,0,0,1,34.32959-34.42326,34.23384,34.23384,0,0,1,34.32959,34.42326C384.04518-191.48447,368.78707-176.18537,353.53129-176.18537Zm99.17074,0a34.23383,34.23383,0,0,1-34.32959-34.42326A34.23383,34.23383,0,0,1,452.702-245.03189a34.23383,34.23383,0,0,1,34.32959,34.42326A34.23383,34.23383,0,0,1,452.702-176.18537Z" transform="translate(375 375)"/><rect class="cls-3" width="1000" height="1000"/></svg>

bug
![image](https://user-images.githubusercontent.com/76897751/135602697-b09f761e-64a6-400a-b069-73e7e3e07eb3.png)
![image](https://user-images.githubusercontent.com/76897751/135602756-a3c40a32-80ca-4585-8e8f-5cf6ebd99461.png)

**Comment by igordmn** [comment]
Yeah, it is the known bug in [Skia](https://bugs.chromium.org/p/skia/issues/detail?id=12251).

It doesn't support CSS classes at the moment.

Workaround is to inject all CSS classes into `style` attributes.

**Comment by RedStoneCats101** [comment]
ok thanks

**Comment by RedStoneCats101** [comment]
Exporting using inline styling worked for me

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5235">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
