### ISSUE TITLE
Gradle package task skipping targets

### ISSUE THREAD

**Issue by foldsters** [JetBrains/compose-multiplatform#1219]
We're following the desktop-template example, trying to package the project for LinuxX64.

We've set the implementation to `compose.desktop.linux_x64`,  and java version to 16 to make sure jpackage is satisfied.

![studio64_QfyAcJU7pt](https://user-images.githubusercontent.com/37962412/135695311-83ad9e4a-7091-4c64-83f1-43464ef22f4c.png)

The package task  "builds successfully" and creates the `.msi` target, but always skips the `.deb` and `.dmg` targets, despite running the task with the `--rerun-tasks` flag and other attempts.

![studio64_kjFrsQhNaf](https://user-images.githubusercontent.com/37962412/135695290-de5af58d-7d49-45bd-9400-c1e935625c39.png)

Is cross-compilation not supported for packaging compose binaries?

**Comment by akurasov** [comment]
Yes, we do not support cross-compilation at the moment

**Comment by foldsters** [comment]
Ah, thank you! We're hoping to use the compose runtime features for state management between peripheral devices. Much appreciated!

**Comment by akurasov** [comment]
@olonho FYI
