### ISSUE TITLE
Preview stops working at random points

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#1221]
In IJ 212, using the latest Compose Multiplatform plugin, the preview panel just stops working at random points and the only way to make it show anything is to restart the IDE.

It may or may not be related to the fact that the project JAR file may be leaked and left open in some cases (that, in turn, seems to happen in general with Gradle, and may not be related to CfD — I have seen it happen in Android projects too.)

**Comment by ChrisAJS** [comment]
This started happening to me whilst using Jetpack Compose Desktop as soon as I started using resources from the classpath - specifically attempting to load a font from resources. Only mentioning as it seems like it could potentially be related.

**Comment by rock3r** [comment]
I was also using classpath resources (including fonts), hope this helps too.

**Comment by Him188** [comment]
Still seeing this problem. 

![image](https://user-images.githubusercontent.com/12100985/185598245-18955ace-2c7b-4503-aa83-1d8e005bb271.png)

Stacktrace shows:
```
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
```
which might be caused by opening files.
