### ISSUE TITLE
Focusable modifier stops working once a composable is clicked

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#1222]
If you have a Composable that is both focusable and clickable, the tab focus stops working for the composable once they've been clicked.

**Comment by akurasov** [comment]
@rock3r do you still have this issue?

**Comment by rock3r** [comment]
Haven't checked in a while... Let me see.

**Comment by rock3r** [comment]
Just checked on 1.0.0 and yes, seems like it still happens ç)

**Comment by akurasov** [comment]
Have you tried my code or another? If another, could you share it, please?

**Comment by rock3r** [comment]
Your code seems to be working, albeit with some weird things happening. Have shared further information in private.

**Comment by rock3r** [comment]
Probably obsolete.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6002">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
