### ISSUE TITLE
Feature: reuse Swing fonts on desktop

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#1225]
There isn't an easy way to take a font used from Swing and apply it to CfD too. That makes it very hard to integrate with existing Swing apps.

**Comment by rock3r** [comment]
This was done by me in Skiko. Closing as completed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6003">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
