### ISSUE TITLE
Checkbox base padding too high.

### ISSUE THREAD

**Issue by Exidel** [JetBrains/compose-multiplatform#1232]
When use Checkbox() as it is - it's very big empty space around checkbox. 
But if I add Modifier.padding(2.dp).size(20.dp) all become to normal. Any manipulations with Modifier.size() doesn't affect on checkbox size, just make padding less or higher.
v1.0.0-alpha4-366. Last time I was used it with v0.5.0-262 and all was fine.

![v1](https://user-images.githubusercontent.com/80458677/136110724-d2da5d64-2213-4baa-abc7-551232d90cec.jpg)
![v2](https://user-images.githubusercontent.com/80458677/136110735-39c8ed5c-b1e2-4f18-aacb-0e6f69fe25bf.jpg)

<details>
        <summary>Code</summary>

```
           Column {
                for (i in 1..10) {
                    Row {
                        Checkbox(checkboxBoolean, { checkboxBoolean = !checkboxBoolean }, Modifier.padding(2.dp).size(20.dp))
                        Text("item$i", Modifier.align(Alignment.CenterVertically))
                    }
                }
            }
```   

</details>

**Comment by igordmn** [comment]
There is [a commit](https://android-review.googlesource.com/c/platform/frameworks/support/+/1818946) which adds additional paddings for accessibility purposes. It seems reasonable for touch devices, but probably looks too high on desktop. 

I checked what are the paddings in [Material design for web](https://material-components.github.io/material-components-web-catalog/#/component/checkbox) and in Chrome settings. Paddings are high too there.

Anyway, I think we should investigate, if it is the right approach to enforce paddings for material components on desktop.

We have two options:
- leave additional paddings as they are now
- make them smaller for desktop target (we need to take into account ChromeOS too)

To disable paddings, use this:
```
@OptIn(ExperimentalMaterialApi::class)
CompositionLocalProvider(LocalMinimumTouchTargetEnforcement provides false) {
   App()
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6256">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
