### ISSUE TITLE
White window when I use the VideoPlayer component from this repository with undecorated window

### ISSUE THREAD

**Issue by lsiem** [JetBrains/compose-multiplatform#1240]
When I use this component: [https://github.com/JetBrains/compose-jb/tree/master/components/VideoPlayer](url)

and set the parameter `undecorated` to `true` in the method `singleWindowApplication`, I only get a completely white window (The sound is played)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6038">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
