### ISSUE TITLE
How to trigger the Aero Snap with undecorated window on Windows?

### ISSUE THREAD

**Issue by GaoXing0608** [JetBrains/compose-multiplatform#1248]
I have created a control bar for my app with undecorated window,  such as the following imag

However, it could not drag to the top window to trigger full screen and the left or right to trigger split window. I could simulate the full scrren function while drag to top, the split window couldn't.

How to enable the Aero Snap with undecorated window?

![image](https://user-images.githubusercontent.com/47878271/136885702-fac59ef0-f357-4db4-932d-ebd6d004d6b6.PNG)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6039">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
