### ISSUE TITLE
Web Template does not compile

### ISSUE THREAD

**Issue by eiswind** [JetBrains/compose-multiplatform#1254]
When I try to run the web-template (fresh clone)
I get

```
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (/home/thomas/projects/github/web-template/build/js/node_modules/webpack-cli/lib/webpack-cli.js:173:21)
``` 

Does anyone see that error too?

I have Node 14.8 and Temurin JDK 11  installed on my machine.

Any help getting me started will be appreciated.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6284">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
