### ISSUE TITLE
Sharing Resources In Compose Multiplatform

### ISSUE THREAD

**Issue by wakaztahir** [JetBrains/compose-multiplatform#1255]
- Icons
on Android `painterResource` accepts an integer , on Desktop `painterResource` accepts string & there's no common implementation to get the icon resource
How can I share an icon between android & jvm targets , do I need to place the icon in both of resources , this will create some serious duplication

- Strings
on Desktop there's no stringResource , I would like to use my `strings.xml` file from Android on desktop jvm

**Comment by igordmn** [comment]
Workaround until this feature isn't implemented:
[build.gradle](https://github.com/JetBrains/compose-jb/blob/dc0335b210f5e0b3bb02325dc690e4e39f9fe1f4/examples/widgets-gallery/common/build.gradle.kts#L52)

[commonMain](https://github.com/JetBrains/compose-jb/blob/dc0335b210f5e0b3bb02325dc690e4e39f9fe1f4/examples/widgets-gallery/common/src/commonMain/kotlin/org/jetbrains/compose/demo/widgets/platform/Resources.kt#L7)
[desktopMain](https://github.com/JetBrains/compose-jb/blob/dc0335b210f5e0b3bb02325dc690e4e39f9fe1f4/examples/widgets-gallery/common/src/desktopMain/kotlin/org/jetbrains/compose/demo/widgets/platform/Resources.kt)
[androidMain](https://github.com/JetBrains/compose-jb/blob/dc0335b210f5e0b3bb02325dc690e4e39f9fe1f4/examples/widgets-gallery/common/src/androidMain/kotlin/org/jetbrains/compose/demo/widgets/platform/Resources.kt)

**Comment by Alex009** [comment]
Also you can use https://github.com/icerockdev/moko-resources with support of compose desktop, android, web.

**Comment by Farouk-abichou** [comment]
@igordmn 
okay but what about ios?

**Comment by terrakok** [comment]
In the next compose multiplatform there will be a new resources library with strings, fonts and images support on all supported platforms. You can try it now in the latest dev version. See a demo here: https://github.com/JetBrains/compose-multiplatform/tree/master/components/resources/demo

**Comment by wakaztahir** [comment]
The only feature lacking in moko-resources I noticed is that you cannot delete unused resources, Because IDE doesn't suggest, its unused. I hope there's IDE support for this feature, or maybe at compile time in release, resources that are unused should be omitted.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6020">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
