### ISSUE TITLE
Support Compose foundation module for JS

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-multiplatform#1257]
Lack of support compose foundation for JS stops the `extensions-compose-jetbrains` module from [Decompose](https://github.com/arkivanov/Decompose) being usable on compose web. It'd be great to get support for this.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6280">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
