### ISSUE TITLE
AlertDialog doesn't show Shape correctly

### ISSUE THREAD

**Issue by serbelga** [JetBrains/compose-multiplatform#1269]
**Description** 

The AlertDialog composable shape not showing correctly. It shows a surface behind the AlertDialog background.

```kotlin
val shapes = Shapes(
    small = RoundedCornerShape(24.dp),
    medium = RoundedCornerShape(24.dp),
    large = RoundedCornerShape(12.dp)
)
```

```kotlin
    AlertDialog(
        backgroundColor = Color.Gray,
        onDismissRequest = {},
        title = { Text("Title") },
        text = { Text("Text") },
        confirmButton = {
            Button(
                onClick = {}
            ) {
                Text("Confirm")
            }
        },
        dismissButton = {
            Button(
                onClick = {}
            ) {
                Text("Dismiss")
            }
        }
    )
```

<img width="640" alt="Captura de pantalla 2021-10-18 a las 22 34 34" src="https://user-images.githubusercontent.com/26246782/137802975-4ae4fc71-115f-42a5-b50b-4ac4695e12d9.png">

**Library version**
1.0.0-alpha3

**OS**
Mac OS 11 Big Sur

**Comment by rylexr** [comment]
Is there any news on this?

**Comment by dima-avdeev-jb** [comment]
Reproduce in sample:
https://github.com/dima-avdeev-jb/reproduce-bug-with-alert-dialog

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6065">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
