### ISSUE TITLE
Is there a way to package executable files?

### ISSUE THREAD

**Issue by olbb** [JetBrains/compose-multiplatform#1272]
I'm trying to use compose desktop to build app on windows.
As so far, it works pretty well.
But I found I can only get a installer file after packge with the targetFormats as follows.
`
 targetFormats(TargetFormat.Exe, TargetFormat.Msi)
`
Is there a way to get an executable file?

**Comment by carbonhe** [comment]
Can anyone answer it?

**Comment by StragaSevera** [comment]
It would be great to have this ability!..

**Comment by AlexeyTsvetkov** [comment]
Am I correct, that the question is about the possibility of creating portable apps?
This is not possible at the moment, as far as I know.

**Comment by olbb** [comment]
Okay thank you!
 Then, are there plans for future support?

**Comment by AlexeyTsvetkov** [comment]
No, no such plans at the moment

**Comment by fl619616995** [comment]
Using a "createDistributable" might solve your problem

**Comment by olbb** [comment]
> Using a "createDistributable" might solve your problem

Thanks for your reply.
I got executable files in binaries folder. 
Although it requires resources in folder to run, but it that's also better than an installer file.

**Comment by Xinerfapre** [comment]
Hello,

At this day, is there still no plan for that?

**Comment by ellet0** [comment]
Until now, it's not built-in in jpackage as far as I know

It's possible using third party tools that create exe, like [launch4j](https://launch4j.sourceforge.net/)

The Gradle plugin

https://github.com/TheBoegl/gradle-launch4j

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6000">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
