### ISSUE TITLE
AwtWindow does not render on KDE Plasma Desktop with freetype2 2.11.0-4

### ISSUE THREAD

**Issue by maximilianproell** [JetBrains/compose-multiplatform#1279]
I tried to run the Notepad example application on my desktop and everything works, except when I try to open the "Open..." or the "Save" window from the menu bar, I only get a transparent window with visual artifacts. In the terminal I get the following error messages:

`
(java:38970): Gtk-WARNING **: 22:03:10.434: drawing failure for widget 'GtkFileChooserDialog': error occurred in libfreetype

(java:38970): Gtk-WARNING **: 22:06:47.595: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(java:38970): Gtk-WARNING **: 22:06:47.595: drawing failure for widget 'GtkGrid': error occurred in libfreetype

(java:38970): Gtk-WARNING **: 22:06:47.595: drawing failure for widget 'GtkBox': error occurred in libfreetype

(java:38970): Gtk-WARNING **: 22:06:47.595: drawing failure for widget 'GtkFileChooserWidget': error occurred in libfreetype

(java:38970): Gtk-WARNING **: 22:06:47.595: drawing failure for widget 'GtkBox': error occurred in libfreetype

(java:38970): Gtk-WARNING **: 22:06:47.595: drawing failure for widget 'GtkFileChooserDialog': error occurred in libfreetype

(java:38970): Gtk-WARNING **: 22:06:47.605: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(java:38970): Gtk-WARNING **: 22:06:47.605: drawing failure for widget 'GtkBox': error occurred in libfreetype

(java:38970): Gtk-WARNING **: 22:06:47.605: drawing failure for widget 'GtkEventBox': error occurred in libfreetype
...
`
My system:
Operating System: Manjaro Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.2
Kernel Version: 5.10.70-1-MANJARO (64-bit)
Graphics Platform: X11
Graphics Processor: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2

FreeType version: freetype2 2.11.0-4

**Comment by virogu** [comment]
![QU6OU)3@$YUE)YQT}Q B~UA](https://user-images.githubusercontent.com/43124403/138045833-a9ce93cb-1308-4afb-bd74-0d4e9bd7c679.png)

**Comment by virogu** [comment]
Here is the crash inf
![70L(F7K28PN97Z)3EK7ZBK3](https://user-images.githubusercontent.com/43124403/138046060-0662fab7-230d-4a43-b465-352ba8984e63.png)
o

**Comment by maximilianproell** [comment]
@igordmn I din't find any other usage of AwtWindow in the other examples, everything else which only uses default Compose functions seems to work fine. The FileDialog created in the AwtWindow Composable causes the issue. I only found one similar issue, where someone gets the same errors, but I don't know if it's related: [https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1827418.html](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1827418.html)
Either way, the problem also seems to be caused by the freeType version. I also tried setting `gsettings set org.gnome.desktop.interface font-antialiasing grayscale` which didn't help.

**Comment by igordmn** [comment]
> I din't find any other usage of AwtWindow in the other examples

I wanted to check if there are the other application (not related to Compose, better some preinstalled application) is able to open the default system file chooser.

**Comment by maximilianproell** [comment]
> which able to open the default system file chooser.

Ah, yes. For example, all chromium based browsers use the system default file chooser (Brave in my example) and that's just working perfectly fine.

**Comment by igordmn** [comment]
I have a draft of another implementation of file chooser (using [lwjgl](https://javadoc.lwjgl.org/org/lwjgl/util/nfd/NativeFileDialog.html)):

https://github.com/JetBrains/compose-jb/tree/components_nativedialogs

It would be great, if you can check it:
```
git checkout components_nativedialogs
cd components
./gradlew nativedialogs:demo:run
```

**Comment by maximilianproell** [comment]
> It would be great, if you can check it:

I just tried that implementation out, but I get exactly the same errors and the file chooser is a blank window with visual artifacts which are influenced by the mouse movement:
![grafik](https://user-images.githubusercontent.com/22836467/140316989-929457bc-f6a4-4fb4-9cf5-f9fff2aa2cea.png)
The errors are again:
`(java:4800): Gtk-WARNING **: 13:53:02.139: drawing failure for widget 'GtkFileChooserDialog': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkBox': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkEventBox': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkRevealer': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkSidebarRow': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkListBox': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkViewport': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkPlacesSidebar': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkPaned': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkBox': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkFileChooserWidget': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkBox': error occurred in libfreetype

(java:4800): Gtk-WARNING **: 13:53:02.156: drawing failure for widget 'GtkFileChooserDialog': error occurred in libfreetype
...
`

**Comment by igordmn** [comment]
> Brave

As far as I know, Chromium based browser uses their own bundled `freetype`, so it seems everything work because the version is different.

**Comment by maximilianproell** [comment]
Ok I did some further research: I tried the notepad example app on another Manjaro KDE system: The same error happens there (same freetype version is installed, so the problem can be boiled down to the freetype version).

But GTK file choosers work without a problem on all my KDE systems (Thunderbird, Firefox and Gimp use them for example). I also created a minimal JavaFX Application and open the FileChooser like that and it opens just fine:
![image](https://user-images.githubusercontent.com/22836467/140344586-1d26c1ed-eca5-43d8-bdd3-cae12018b86e.png)


> NativeDialogs uses [GTK directly](https://github.com/mlabbe/nativefiledialog/blob/master/src/nfd_gtk.c#L328).

Native Dialogs use QT on KDE and they look different, as it can be seen here: [https://askubuntu.com/questions/1150404/kubuntu-18-10-how-do-i-change-this-file-picker](https://askubuntu.com/questions/1150404/kubuntu-18-10-how-do-i-change-this-file-picker)
I also forced Firefox to use the native KDE file picker as described in that post and it works fine. So both GTK and the KDE native QT based file pickers work. So I guess the problem is in the old Java Swing library, as JavaFX works?

**Comment by maximilianproell** [comment]
> NativeDialogs uses [GTK directly](https://github.com/mlabbe/nativefiledialog/blob/master/src/nfd_gtk.c#L328).

Ah, you mean Swing uses this Library? So does JavaFX also use it?

**Comment by igordmn** [comment]
No, Swing doesn't use NativeDialogs library (by "NativeDialogs" I mean the name of the library, not real native dialogs :) ), it probably also uses GTK (#include <gtk/gtk.h>) to open GTK file chooser. NativeDialogs  is just a wrapper around GTK/WinApi/AppKit.

I don't know what is used by JavaFX, but my guess it uses JavaFX based file chooser, written from scratch, not the native one.

> I also forced Firefox to use the native KDE

Firefox probably also uses a bundled freetype, not the system one.

So we have 2 issues:
- GTK file chooser probably doesn't work with freetype2 2.11.0-4
- Swing/NativeDialogs uses GTK file chooser on KDE instead of QT one

**Comment by TimerErTim** [comment]
What is the current status regarding this issue?

The problem still persists with Compose version 1.0.1 and freetype2 2.11.1-1.
This is a major deal breaker as this also prevents any other AWT component to be correctly rendered (like the Menubar for example) and I can't expect my Linux users to downgrade their freetype2 version. I, for example, can't even do that because of my distribution repository only having the latest version.

**Comment by AzimMuradov** [comment]
I ended up using [bonsai](https://github.com/adrielcafe/bonsai#file-system-integration). At least it works and has consistent design.

**Comment by AChep** [comment]
Same issue using https://github.com/WonderzGmbH/nativefiledialog-java

**Comment by AzimMuradov** [comment]
Current version of [compose-multiplatform-file-picker](https://github.com/Wavesonics/compose-multiplatform-file-picker) fixed all my issues.

**Comment by AzimMuradov** [comment]
From what I understand, the problem occurs when using the GTK file picker (from `<gtk/gtk.h>`) in conjunction with Compose. But when using [zenity](https://github.com/GNOME/zenity) it works fine (maybe because it's an external process?). When using any of these tools by themselves (without Compose), everything works fine.

Currently, `compose-multiplatform-file-picker` uses [tinyfd](https://github.com/LWJGL/lwjgl3/tree/master/modules/lwjgl/tinyfd) by default. On Linux, `tinyfd` tries will first try to use `zenity` if available. That's why `compose-multiplatform-file-picker` works. Any other solution ends up using bindings to native functions (using JNA) that call `<gtk/gtk.h>`.

My guess is that Skia or Compose is interfering with GTK or something.

I'll try to add test files soon.

**Comment by ptitjes** [comment]
On my Fedora 39/Fedora 45/JDK 17, this fixed the issue for me:
```shell
gsettings set org.gnome.desktop.interface font-antialiasing grayscale
```

**Comment by KevinT3Hu** [comment]
This issue still occurs with lwjgl nfd module, the libfreetype version is 2.13.2-1

**Comment by AzimMuradov** [comment]
> This issue still occurs with lwjgl nfd module, the libfreetype version is 2.13.2-1

If it's an option, you can try to use lwjgl [tinyfd](https://github.com/LWJGL/lwjgl3/tree/master/modules/lwjgl/tinyfd).

Example:

https://github.com/AzimMuradov/stardew-valley-designer/tree/master/common/cmp-libs/file-dialogs-ui/src/jvmMain/kotlin/io/stardewvalleydesigner/cmplib/filedialogs

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6022">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
