### ISSUE TITLE
Support animated vector drawables

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#1290]
Somewhat related to #362, it'd be great if it were possible to load and render animated vector drawables. It's currently only possible to load non-animated vector drawables.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6269">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
