### ISSUE TITLE
CSSpxValue capitilzation typo

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-multiplatform#1291]
https://github.com/JetBrains/compose-jb/blob/581b5f0b0af764c855adb53bf2aa75bc2ca6972f/web/core/src/jsMain/kotlin/org/jetbrains/compose/web/css/CSSUnits.kt#L36

Currently: `CSSpxValue`

To be consistent with other typealiases, should be: `CSSPxValue`

Not a big deal but probably best to fix before 1.0

**Comment by bitspittle** [comment]
Funny, I ran into this again today and came to report it, but it seems like I already did in the past :)

Since 1.0 is out, maybe it's best to define CSSPxValue just beside it. Can you deprecate a typealias?

**Comment by ShreckYe** [comment]
I found this problem too and I suspect that this name may be left like this intentionally to be consistent with units in `CSSUnit`, because there are units with capital letters such as `Hz`. And those interfaces in `CSSUnit` are unconventional too as a lot of them start with lowercase letters.

**Comment by bitspittle** [comment]
Sigh: https://developer.mozilla.org/en-US/docs/Web/CSS/frequency Thanks for the comment, it's interesting.

I'd argue that `Hz` is also inconsistent with all other values and probably a mistake -- that they should probably have stuck to Kotlin conventions and avoided the temptation to match to the JS name. (There's precedence, as they use `cssRem` instead of `rem` because `rem` is a stdlib method already)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6076">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
