### ISSUE TITLE
Add "ui-util" and make composeDependency() public in ComposePlugin

### ISSUE THREAD

**Issue by PhilipDukhov** [JetBrains/compose-multiplatform#1295]
I need `compose:ui-util` to use `fastAll`/`fastAny` in custom gestures handling.

I'd like to use
```
implementation(compose.desktop.components.uiUtil)
```
Instead of 
```
implementation("org.jetbrains.compose.ui:ui-util:1.0.0-alpha3")
```
It would also be nice to have a public `composeDependency()` or `composeVersion` for such cases, which can be used temporarily until a new system library can be added to `ComposePlugin`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6274">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
