### ISSUE TITLE
Add support of DatePicker/Calendar widget.

### ISSUE THREAD

**Issue by dnrusakov** [JetBrains/compose-multiplatform#1299]
As I understand there is no a DatePicker/Calendar widget right now in Jetpack compose for Desktop. At the same time it is extremely widespread use case appeared in numerous modern interfaces.
Could you guys, please, add one to Jetpack compose for Desktop?
Thank you!

**Comment by helmysaeed** [comment]
> As I understand there is no a DatePicker/Calendar widget right now in Jetpack compose for Desktop. At the same time it is extremely widespread use case appeared in numerous modern interfaces. Could you guys, please, add one to Jetpack compose for Desktop? Thank you!

it's very important widget

**Comment by lazaroofarrill** [comment]
> > As I understand there is no a DatePicker/Calendar widget right now in Jetpack compose for Desktop. At the same time it is extremely widespread use case appeared in numerous modern interfaces. Could you guys, please, add one to Jetpack compose for Desktop? Thank you!
> 
> it's very important widget

Like @olonho said using LGoodDatePicker in compose is extremely easy and will work wonderfully for most desktop apps. The team would better expend their time making the core framework more powerful, which in turn will make easier for the rest of us build our own components, rather than making some materialish hard to customize date picker.

**Comment by hfeky** [comment]
Are there any plans on when the material date picker will be implemented? I agree it's also very important for desktop apps.

**Comment by fflopsi** [comment]
#3256 seems to address the bigger issue of the version of Material 3 being 1.0.1, while version 1.1.0 supports date picker composables.

**Comment by lazaroofarrill** [comment]
Bumping up the material version won't automatically give you a component that depends on platform specific code. It shouldn't take you that long to implement the widget yourself if you really belief the material date picker fits a desktop application, but as someone said earlier is hard to justify something like this being part of the framework.

**Comment by serandel** [comment]
Hard disagree, @lazaroofarrill. Compose for Desktop already supports that library, just an older version. So I expect it contains no platform-specific code, but standard Compose.

**Comment by erdevasconcellos** [comment]
[es] Mi implementación de DatePicker en un único archivo Kotlin, sin librerías externas. Probado en un proyecto personal en Compose Desktop.

[en] My DatePicker implementation in a single Kotlin-file, without external libraries or dependencies. Tested in a Compose Desktop project.

<img src="https://github.com/JetBrains/compose-multiplatform/assets/80974003/7a0a0c74-3cfa-4f18-bb57-5607e5d58bab" width="400">

[https://gist.github.com/erdevasconcellos/8d38a6124b27151f87bdbb4edf4e5cf3](https://gist.github.com/erdevasconcellos/8d38a6124b27151f87bdbb4edf4e5cf3)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5232">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
