### ISSUE TITLE
Modifier.drawLayer(alpha=), optimization of drawing top-level transparent layers

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#13]
Now we draw every transparent layer into intermediate buffer using saveLayer (see SkijaLayer, performDrawLayer).

Think if we can don't use intermediate buffer for top-level transparent layers. Maybe we can use PaintFilterCanvas for that:

https://github.com/JetBrains/skija/blob/fc1757bd0d31cf02481da1671a17ba51d9451fa0/examples/lwjgl/src/main/java/org/jetbrains/skija/examples/lwjgl/PictureRecorderScene.java#L134

https://cs.android.com/android/_/android/platform/frameworks/base/+/613e6e3e9a0001b29af363318b6c123505d898c7:libs/hwui/pipeline/skia/RenderNodeDrawable.cpp;l=184;drc=fe2dcf1877b0666e0395619a7de0353babbb1aee

But keep in mind that for nested transparent layers we can't use such optimization. Because nested layers should apply alpha to nested layer background to which alpha has not yet been applied:

Example:
```kotlin
Box(Modifier.drawLayer(alpha=0.5).background(Color.Red)) {
  Box(Modifier.drawLayer(alpha=0.5).background(Color.Blue))
}
```

We can't draw both layers without intermideate buffer, because nested layer will be drawn with wrong color.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6067">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5630">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
