### ISSUE TITLE
Add StyleBuilder.borderColor and borderStyle functions

### ISSUE THREAD

**Issue by gsteckman** [JetBrains/compose-multiplatform#1303]
There are StyleBuilder extension functions for border-width and border-radius CSS properties, but corresponding functions for border-color and border-style are missing.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5230">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
