### ISSUE TITLE
Support "Select All" for usual non-editable text (not only for TextField)

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1309]
Currently we can only Copy it. We can implement Select All in the bounds of a single SelectionContainer

![Screenshot from 2021-10-25 15-39-01](https://user-images.githubusercontent.com/5963351/138696603-9a1f0004-3aee-4f89-a716-e6a70201324f.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5226">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
