### ISSUE TITLE
Support @font-face for web

### ISSUE THREAD

**Issue by LeoColman** [JetBrains/compose-multiplatform#1310]
Currently, there's no way to declare a `@font-face` apart from using a separate `style.css` file. Perhaps we should have it supported natively.

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5225">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
