### ISSUE TITLE
1.0.0-beta1 causes issues with R8 in an android app

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-multiplatform#1311]
I have an android app where I updated to 1.0.0-beta1, and then when making a release build of my android app (which uses r8) it crashes at launch.

If I revert back down to 1.0.0-alpha4-build418 then the issue goes away.

Here is part of the stacktrace:

```
Fatal Exception: java.lang.IllegalAccessError: Method 'void android.view.View.onAnimationEnd()' implementing interface method 'void coil.target.Target.onAnimationEnd()' is not public (declaration of 'androidx.compose.ui.platform.AndroidComposeView' appears in /data/app/~~D83UUWaeF7V8xBltnyPXpw==/base.apk)
```

You can see that the stacktrace somehow points to the coil library (used for image loading on android) https://github.com/coil-kt/coil

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5224">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
