### ISSUE TITLE
multiplatform-template doesn't support @Preview in androidMain

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-multiplatform#1327]
I took the latest multiplatform-template, updated AGP and tried to add a simple @Preview in androidMain, but it didn't work.

Here is the diff that I made on top of multiplatform-template.

`git apply repro.diff.txt`
[repro.diff.txt](https://github.com/JetBrains/compose-jb/files/7442774/repro.diff.txt)

<img width="942" alt="Screen Shot 2021-10-29 at 10 38 42 AM" src="https://user-images.githubusercontent.com/31751141/139454287-dc9e7c3e-56a8-4319-8221-e3caf4abb5ed.png">

**Comment by ColtonIdle** [comment]
You're right. Sorry, I was taking this out of a conversation in kotlinlang slack and had some more details there.

Basically, I'm expecting to see this in order to see a preview. As you can see in the screenshot. The Preview annotation seems to be found. The Ide highlights the fact that I can deploy the preview onto the device. But the usual "preview" pane switcher isn't found.

<img width="214" alt="Screen Shot 2021-10-29 at 1 05 07 AM" src="https://user-images.githubusercontent.com/31751141/139501952-819ec4f2-f5fe-4f06-9a4f-08d859aeb24c.png">

**Comment by SerggioC** [comment]
The preview still does not work?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5215">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
