### ISSUE TITLE
Executable Permissions aren't transferring to packaged resources

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-multiplatform#1330]
I have the .kexe file is also not getting the executable permission (chmod +x). Getting this permission added in the build phase has actually proven very challenging as well. Since permissions can be checked in through git, it seems like there should be a way to transfer them into the dmg as well.

**Comment by AlexeyTsvetkov** [comment]
@ScottPierce can you provide a more detailed description of the use case and the issue? How do you get the file? Does it have the executable permission before packaging?

**Comment by ScottPierce** [comment]
Sure

> How do you get the file?

The file is generated by a submodule in the project.

> Does it have the executable permission before packaging?

Yes. I have tried several things, but have even gone so far as to stop generating the file, manually `chmod +x` the file and place it in the resources directory, and then package the dmg again, and it still doesn't work.

**Comment by ScottPierce** [comment]
One more thing of note, I'm renaming the file extension to `.dylib` so that the file gets properly signed.

**Comment by ScottPierce** [comment]
@AlexeyTsvetkov Why not just sign every file?
https://github.com/JetBrains/compose-jb/blob/8342d370d6ba14ccfb3519c496f2cfe65367798b/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/files/MacJarSignFileCopyingProcessor.kt#L24-L26

**Comment by ScottPierce** [comment]
> can you provide a more detailed description of the use case and the issue

I got sick of trying to use JNI in my project, so I instead created a separate kotlin-native application that I ship along with my compose jvm application. The compose jvm application calls into the kotlin-native application, which interacts with the C library and then serializes a response back to the parent application. The kotlin-native application needs executable permission to run.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5213">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
