### ISSUE TITLE
Add support for setting css height and width properties to values other than auto, <length>, <percentage>

### ISSUE THREAD

**Issue by gsteckman** [JetBrains/compose-multiplatform#1331]
CSS allows the height and width properties to be additionally set to min-content, max-content, fit-content, and fit-content(\<length-percentage\>). See [https://developer.mozilla.org/en-US/docs/Web/CSS/height](https://developer.mozilla.org/en-US/docs/Web/CSS/height).

As of 1.0.0-beta5, to set one of these values the type-unsafe property(String, String) function must be used.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5212">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
