### ISSUE TITLE
Style individual sides of CSS borders

### ISSUE THREAD

**Issue by brianguertin** [JetBrains/compose-multiplatform#1337]
There are no functions to access the individial borders (top/left/right/bottom). E.g. `border-top-color`. It would be nice to have builders for those.

Perhaps there could just be overloads of the `border {}` builder function for the individual sides, e.g. `borderTop { color(blue) }`.

**Comment by brianguertin** [comment]
Note: there's a big difference between "border-top: blue" and "border-top-color: blue". Hopefully, the API could make it intuitive which one of those is going to be applied. `border-top-color: blue` only sets the color, but using the short-hand property `border-top: blue` also resets border-top-width and border-top-style.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5207">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
