### ISSUE TITLE
Improve scrolling performance by batching multiple scroll events

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1345]
1.0.0-beta5

Currently we handle all scroll events. Each scroll event can take 20-50 ms, so we will notice visible lags, if we scroll very fast.

To solve some laggyness we use [asynchronous events](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/awt/ComposeLayer.desktop.kt;l=58;drc=73805b3fb267d6c7070f7ba99bd9dc8bfc6c3d99).

The better approach would be to batch all incoming scrolling events into one bigger scrolling event.

**Comment by felixdivo** [comment]
This would be a great feature! Scrolling is indeed quite laggy when the content is more complicated.

**Comment by felixdivo** [comment]
@igordmn, are these changes available in [v1.1.0-alpha03](https://github.com/JetBrains/compose-jb/releases/tag/v1.1.0-alpha03) or [v1.2.0-alpha01-dev602](https://github.com/JetBrains/compose-jb/releases/tag/v1.2.0-alpha01-dev602) for testing?

**Comment by felixdivo** [comment]
Okay, thanks for the swift reply!

Well, then I'll look somewhere else. Overall, profiling a Compose Desktop app is kind of tricky since the composition and rendering layers (pardon my impreciseness) really hide which parts of the UI slow down rendering. Do you know of any tools that could help (except for "profiling" by commenting-out and observing changes in runtime)?

**Comment by igordmn** [comment]
I am not aware of any special tools, and we haven't develop any for Compose (but that is a great idea). Just a default profiler + "profiling" by commenting out. You can profile the default function `ComposeScene.render`, in which all composition/layouting happens.

Rendering itself happens on GPU, so it is hard to profile. You can measure FPS though. `-Dskiko.fps.enabled=true` will print FPS to the console). But you need also disable vsync (`-Dskiko.vsync.enabled=false`) and add something like `CircularProgressIndicator` to render continuously, without stops.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5200">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
