### ISSUE TITLE
How to use VideoPlayer component in a separate project?

### ISSUE THREAD

**Issue by kyoybs** [JetBrains/compose-multiplatform#1354]
I create a new project,  add  "implementation(project(":VideoPlayer:library"))" to dependencies in build.gradle.kts.
But I got an error "Project with path ':VideoPlayer:library' could not be found in root project xxx".

Please help.

**Comment by RulerKun** [comment]
have you solved this?

**Comment by tberghuis** [comment]
Does anyone have any clues on how to solve this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5194">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
