### ISSUE TITLE
Improve or let customize the warning, when installing to existing custom location

### ISSUE THREAD

**Issue by virogu** [JetBrains/compose-multiplatform#1356]
How to customize the installation program so that it does not delete the files in the installation directory but overwrites the files that need to be updated. The current installation program will first delete all files in the installation directory. This operation is very dangerous and will delete many user customizations document. I have a user who accidentally selected the root directory of the disk as the installation directory.  As a result, the installation program deleted all the files on the entire disk. This is too bad!!!

**Comment by AlexeyTsvetkov** [comment]
@virogu I've checked, and when an existing installation directory is chosen, the installer asks, whether a user actually wants to install to the existing dir:
```
The folder [INSTALLDIR] already exist. Would you like to install to that folder anyway?
```
I think this is a normal Windows installer behaviour.
What do you think should happen instead?

To preserve files between different versions of your app, you could use a few ways:
1. Create an application specific directory under `user.home`:
```
File("${System.getProperty("user.home")}/.my-app").mkdirs()
```
2. Create an application specific directory in Application Data dir (Windows only):
```
File("${System.getenv("APPDATA")}/.my-app").mkdirs()
```
3. Use Windows specific tools such as Registry.

**Comment by virogu** [comment]
Thank you for your answer, there will indeed be a prompt during installation. However, this prompt does not allow the user to clarify what will happen. The user only knows that the folder already exists, but does not know that continuing to delete all files in the directory, and this prompt cannot be customized and is in English. Therefore, many users may not understand it. Now my solution is not to use the ".exe" installation program. I have installed it on my computer, and then compressed the installation directory and sent it to the user, so that they can unzip it directly to any directory.

**Comment by AlexeyTsvetkov** [comment]
ok, we will try to look into either changing the warning or allowing to customize it

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5192">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
