### ISSUE TITLE
Context menu divider

### ISSUE THREAD

**Issue by JetpackDuba** [JetBrains/compose-multiplatform#1357]
I haven't found a way of adding dividers to the options in a context menu like in the material design [menu specification [Dropdown (Desktop)]](https://material.io/components/menus#specs)

Are there any plans on adding them?

Looking at the current implementation, I'd suggest to change the `ContextMenuArea` to accept a list of `ContextMenuElement`, being this a parent interface (or super class, depening on the needs) of the current `ContextMenuItem` and a new class/object `ContextMenuDivider`. So you can pass to the `ContextMenuArea` a list of `ContextMenuElement` with whatever items and dividers you want.

**Comment by Burtan** [comment]
There is also a need of nested ContextMenus which could be implemented similiary or at least give the user the chance to do it on his own with some kind of ContextMenuElement interface

**Comment by Sage-Kreiter** [comment]
Any update on this? Seems like the only way to do this now would be to create a completely custom context menu.

**Comment by dzirbel** [comment]
Small plug and another example for anyone still looking for an easy way to add dividers to context menus - I've created a simple library with support for material styling of context menus, including dividers: https://github.com/dzirbel/compose-material-context-menu

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5191">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
