### ISSUE TITLE
How to upgrade app in windows?

### ISSUE THREAD

**Issue by wznshuai** [JetBrains/compose-multiplatform#1359]
I'm try make app with compose-desktop in Windows.  But i can't find guide about how to online upgrade. 

pls, help me . thx

**Comment by rustamsmax** [comment]
And what about installing additional modules?

**Comment by aeab13** [comment]
That's not really compose related. You can find info about it in this post: [Stackoverflow - How can I write a Java application that can update itself at runtime?](https://stackoverflow.com/questions/4002462/how-can-i-write-a-java-application-that-can-update-itself-at-runtime)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5189">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
