### ISSUE TITLE
Tutorial on Publishing MPP Artifacts

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-multiplatform#1363]
We should add a tutorial on how users building a multiplatform widget can build and publish their artifacts (Canvas widgets in common code for Desktop+Android) and (expect/actual widgets for Desktop+Android+Web).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5185">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
