### ISSUE TITLE
request(TextOverflow): ReverseEllipsis

### ISSUE THREAD

**Issue by codymikol** [JetBrains/compose-multiplatform#1365]
It would be great if you could specify that overflowing text should show an ellipsis from the left side with 

`overflow = TextOverflow.ReverseEllipsis`

 a good use case for this would be displaying a list of files

```
...oo/bar/baz/bax/test.kt
..bar/baz/bax/foo/foo.kt
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5184">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
