### ISSUE TITLE
Support Compose.material on JS target

### ISSUE THREAD

**Issue by MEJIOMAH17** [JetBrains/compose-multiplatform#1369]
Currently I can't use compose.foundation and compose.material on JS target. Do you have any plans for adoption ui components from android compose to js target?

**Comment by arkivanov** [comment]
Partially duplicate of https://github.com/JetBrains/compose-jb/issues/1257

**Comment by MEJIOMAH17** [comment]
@akurasov  no, I won't. Rename it

**Comment by Schahen** [comment]
we lucky to find ourselves in situation when material is supported in both wasm and js )

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6007">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
