### ISSUE TITLE
Add test to Project Template

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-multiplatform#1370]
Currently the generated project contains a simple `Hello World` single window app, but no test.

Add a test to the template when it is generated by the project wizard:

- New project
- Compose Desktop

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6240">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
