### ISSUE TITLE
`org.jetbrains.compose.web.css.StyleSheet` does not support `@import` rule

### ISSUE THREAD

**Issue by thubalek** [JetBrains/compose-multiplatform#1371]
Hi, it looks like `org.jetbrains.compose.web.css.StyleSheet` does not support `@import` rule. Could it be added?

**Comment by Ayfri** [comment]
Any update on this ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6109">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
