### ISSUE TITLE
Request: Publish iOS/native artifacts for Compose runtime

### ISSUE THREAD

**Issue by brianguertin** [JetBrains/compose-multiplatform#1374]
*This is not about Compose UI or Material Components*

The Compose runtime works on iOS & native, but there are no easily available artifacts. I think the Kotlin community would greatly benefit from having native artifacts of Compose runtime available, even without a UI library. And I think JetBrains is already in a great position to offer them (since you already offer JVM and JS artifacts).

The compose compiler and runtime are useful even for non-UI use cases. It's a cool general purpose library for any kind of tree manipulation.

The community has already demonstrated some interesting use cases like:
- [Mosaic](https://github.com/JakeWharton/mosaic), a tool for building native Console UI 
- As a DSL for [Generating GraphViz dot files](https://arunkumar.dev/jetpack-compose-for-non-ui-tree-construction-and-code-generation/)
- Driving iOS UI [with UIKit](https://twitter.com/jakewharton/status/1399561083204026369?lang=en)
- For pure-business logic by writing [Presenters in Compose](https://code.cash.app/the-state-of-managing-state-with-compose)

Having easily available artifacts would make it easier for people to experiment and share their work.

"Google really should be shipping the Compose runtime as a proper multiplatform artifact for all Kotlin targets to remedy this situation. Unfortunately their Kotlin multiplatform story is a few years behind the community’s need and the prospect of this happening anytime soon is very unlikely. The best we can hope for now is JetBrains to ship a proper multiplatform artifact of the Compose runtime" - https://jakewharton.com/multiplatform-compose-and-gradle-module-metadata-abuse/

Please? :smile_cat:

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6088">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
