### ISSUE TITLE
Pointer event delay

### ISSUE THREAD

**Issue by shynline** [JetBrains/compose-multiplatform#1384]
There is a noticeable delay between each pointer event.
   I'm not sure if I'm doing it incorrectly, if it's on purpose or if there is a bug.
 I also observed how `PointerInputChange` is implemented and how delta time is taken into account.
  Consider the following simple example
  ```
  WithoutTouchSlop {
              MaterialTheme {
                  Column {
                      var pos by remember { mutableStateOf(Offset(0f, 0f)) }
                      Box(Modifier.size(500.dp).background(Color.Cyan).pointerInput(Unit) {
                          awaitPointerEventScope {
                              while (true) {
                                  val event = awaitPointerEvent()
                                  val point = event.changes.first().position
                                  pos = pos.copy(x = point.x, y = point.y)
                                  event.changes.forEach { it.consumeAllChanges() }
                              }
                          }
                      }) {
                          Canvas(modifier = Modifier.fillMaxSize()) {
                              drawCircle(color = Color.Red, radius = 15f, center = pos)
                          }
                      }
                  }
              }
          }
  ```
  A red dot should follow the mouse pointer but if you move the mouse too quickly the red dot will lag behind.
Just to make it more sensible the lag distance can go up to 1cm on screen. 
The same logic in Qt(A C++ Gui framework) gives up to 1mm lag.
So is it something that can be improved or what?

---

Also, I'm using the latest version which is `1.0.0-beta5` by now on `Ubuntu`

**Comment by shynline** [comment]
It turns out the delay is caused by recomposition (Updating UI)  and it's not related to the input event.
I still don't know if it's going to be improved or it's supposed to be this way.
Any thoughts?

**Comment by shynline** [comment]
Probably not related to compose
Same issue exists with `LWJGL` & `Skija`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6180">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
