### ISSUE TITLE
Some SVG files cannot be rendered correctly.

### ISSUE THREAD

**Issue by Konyaco** [JetBrains/compose-multiplatform#1389]
This SVG cannot be rendered correctly. But works well if I translate it to Android XML.

[SVG files.zip](https://github.com/JetBrains/compose-jb/files/7526512/files.zip)

![image](https://user-images.githubusercontent.com/17498623/141445417-d92baa4f-0c4b-4522-b442-71be59f5a96b.png)
![image](https://user-images.githubusercontent.com/17498623/141445435-061864dc-e1b4-48cf-b018-a90587d16191.png)

```kotlin
Image(
    modifier = Modifier.size(93.dp, 24.dp),
    painter = painterResource("logo_text.xml"),
    contentDescription = null,
    colorFilter = ColorFilter.tint(Color.White)
)
```

**Comment by FlyingYu-Z** [comment]
这是大厂开始用jetpack compose了吗？

**Comment by Konyaco** [comment]
> 这是大厂开始用jetpack compose了吗？

不是，自己做着玩的:p

**Comment by FlyingYu-Z** [comment]
大佬有没有兴趣做一个代码编辑器？

**Comment by Konyaco** [comment]
> 大佬有没有兴趣做一个代码编辑器？

不是大佬，我太菜了，做不来😢

**Comment by akurasov** [comment]
Please use English here, so other people also can understand discussion

**Comment by Konyaco** [comment]
> Please use English here, so other people also can understand discussion

I am very apologizing for that, these are just chats, you can delete them. 😄

**Comment by Melodeiro** [comment]
I have the same problem. Seems the wrong the behaviour is when you use size modifier on a svg.
Converting to xml format worked for me as well.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6051">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
