### ISSUE TITLE
ImageComposeScene unnecessarily initializes JVM GUI Head

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-multiplatform#1397]
Probably ImageComposeScene shouldn't initialize the JVM GUI Head (eg Swing/AWT).  You can reproduce on Mac OSX where running the code below will cause a JVM Application icon to appear in the dock and become focusable as a real application.  This is especially frustrating when forking hundreds of processes to run unit tests in parallel in isolated JVMs.

```
fun main() {
    ImageComposeScene(50, 50) {}.close()
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6225">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
