### ISSUE TITLE
MouseScrollEvent doesn't contain information about CTRL key

### ISSUE THREAD

**Issue by vovahost** [JetBrains/compose-multiplatform#1399]
I'm using `Modifier.mouseScrollFilter()` to track mouse scroll events but I also need to know if the CTRL key was pressed.
In Swing I used `MouseWheelListener.mouseWheelMoved(MouseWheelEvent)`. `MouseWheelEvent` contains a `isControlDown` function which I can check. This allows to quickly track zoom in/out using mouse scroll wheel while the user is pressing CTRL. There was no need for any focus management to track key events.
Is there any workaround for this as I want to track the Mouse wheel + CTRL events?

I was also using `MouseWheelEvent.getLocationOnScreen()` to place the zoom in pivot point where the mouse was. Any suggestions how to do it now?

**Comment by mbunderline76** [comment]
I need this too

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6059">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
