### ISSUE TITLE
Publish API docs generated using Dokka

### ISSUE THREAD

**Issue by jakobkmar** [JetBrains/compose-multiplatform#1400]
There are docs on https://developer.android.com/reference, but they don't fit into the Dokka and Javadoc ecosystem and don't include the compose-jb extras.
Additionally, these android docs can't be referenced from other Dokka docs for linking between the two.

Therefore it would be great to have docs generated using Dokka published somewhere.

**Comment by akurasov** [comment]
I think this request should be raised to Google, as they are publishing API documentation

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6154">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
