### ISSUE TITLE
Transparent window doesn't ignore mouse events since it's still opaque

### ISSUE THREAD

**Issue by nomis51** [JetBrains/compose-multiplatform#1401]
**What the problem ?**
With an overlay app, we want parts that are opaque (not affected by transparency), while having a window that is fully transparent,
so you can have let's say a button floating on screen without any "visible" window around.

But, it seems like, the `transparent=true` property of `Window` (with `undecorated=true`, of course), basically makes the background transparent, but the window itself stays opaque (I've been looking at the ComposeWindow JFrame at the root of the app and `isOpaque=true`). That causes any mouse events to be "blocked" by the invisible window, which makes the overlay usable, since you can't interact with what's behind.

**What have you tried so far ?**
Basically all the "solutions" I knew (Not really familiar with Swing to be honest, but knowledge from JavaFX and WPF) and a lot coming from StackOverflow, and none of them were 100% successfull. 

- Changing opacity, background, opaque, etc.
- Using AWTUtilities....
- WinAPI (JNA) to change Window flags
- name it..

They all ended up with one of the following ending : 

- The window is still transparent, but you can't click, mouse move, etc. through it
- The window is still transparent, but also it's content, that's unusable, since the window doesn't exists visually anymore

**Any workarounds ?**
Well, the only thing that kind of work, but that's horrible honestly, is to register to `pointerInput` on the root `Composable` of the app to find the `ComposeWindow` `JFrame` behind the app and set its background to RGBA(0,0,0,0) which allows mouse events (because the window doesn't exists anymore), re-send the same mouse event (so it simulate the pass through), then reset the background of the `ComposeWindow`... For situations where only mouse clicks matters, that's kind of usuable, cause the background switching is quick enough, but if I want to have mouse move events to pass through, it's flickering insanely.... as expected.

**What do you need ?**
Basically, if you create an empty WPF app (C#), and set the attributes 

- `AllowTransparency=true`
- `Background=Transparent`
- `WindowStyle=None`

and add a button in the middle of the window, 
you end up with a floating button on your screen and the mouse events are not blocked by the invisible window. The only time it does grab the events, is when you hover/interact with a opaque control (e.g. the button is this case)

So, I would be nice to be able to create transparent windows, that react exactly like if they were `opacity=0f`, but still allow opaque controls in it. I know it's doable in Swing, but since with Compose, we don't create the actual Window behind ourselve, I can't really workaround that myself so far..

Also, I know this is the kind of thing that is platform dependant, like, for example on Linux the WPF app won't react like described (e.g. it's going to block mouse events), but on Windows it does. I'm only targeting Windows myself.

Kotlin 1.5.31
Compose for Desktop 1.0.0-beta5 - 1.0.0-beta6-dev474
JDK 11
Windows 10

**Comment by nomis51** [comment]
Just a follow up with some of my experimentations :

Here is an example where I initialized the `ComposeWindow` myself, and notice `isOpaque=false`, and it does react properly to mouse events, because the content (in this case, a `JButton`) was added _after_ the background and opaque changes :

![image](https://user-images.githubusercontent.com/25111613/142058513-b907b646-1934-4729-b468-d484bd74da88.png)

The background of the Window is transparent as expected

![image](https://user-images.githubusercontent.com/25111613/142061703-dd4702c4-3f5e-4dcb-b98f-a7178ec0cbf4.png)

Here is an example where I initialized the window using the `Window(...) { }` composable, and notice `isOpaque=true` even with `transparent=true`

![image](https://user-images.githubusercontent.com/25111613/142058797-b2443b06-c9ea-4794-8823-64e1b6bf3195.png)

If I change the background of the `ComposeWindow` on a mouse event (after initialisation) or in the `key(true) { ... }` scope of the `Window(...) { }`, `isOpaque=false`, as expected. but it spreads to child components by making their opacity = 0, so no more window on screen..

![image](https://user-images.githubusercontent.com/25111613/142059103-13a4bf11-de41-43e7-9f10-c7f6b545e462.png)

And, trying to set the `isOpaque` property to `false` on any panel or sub-panel of the `ComposeWindow` after initialisation does basically nothing, because the Window itself is opaque since it's not transparent it seems.

![image](https://user-images.githubusercontent.com/25111613/142061531-07106404-1f3c-4b22-9a88-168223ef4ae3.png)

So maybe the solution here, is to either make the contentPane to `isOpaque=false` of the `Window` (which is the `ComposeWindowDelegate.pane` panel located in the `ComposeWindow`) on the initialisation
or
add another param in the `Window` like `isOpaque: Boolean` so the developer can decide, like in Java

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6036">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
