### ISSUE TITLE
Adding any compose dependency breaks resolving the Gradle configuration

### ISSUE THREAD

**Issue by jakobkmar** [JetBrains/compose-multiplatform#1404]
When I am adding the compose dependency to a (resolvable) Gradle configuration (`includeImplementation` is my custom configuration) as follows:
```kt
includeImplementation(compose.desktop.currentOs) // same with common
```
and then trying to resolve the dependencies of this configuration

```kt
includeImplementation.resolvedConfiguration.firstLevelModuleDependencies
```

I am getting the following error
```kt
Caused by: org.gradle.internal.component.AmbiguousConfigurationSelectionException: Cannot choose between the following variants of org.jetbrains.compose.foundation:foundation:1.0.0-beta5:
  - debugRuntimeElements-published
  - desktopRuntimeElements-published
  - releaseRuntimeElements-published
```
([probably relates to this](https://docs.gradle.org/current/userguide/variant_model.html#sec:variant-select-errors))

My custom configuration above is one example, but there are other scenarios where you have to use custom configurations from third-party Gradle plugins, and therefore using this together with Compose does not work.

**Comment by akurasov** [comment]
Do you use Kotlin multiplatform gradle plugin? Since Compose is published like a multiplatform solution, this plugin is required for dependency resolution

**Comment by jakobkmar** [comment]
I am not using the multiplatform plugin, because I am having trouble to use the custom configuration from the third party plugin in the scope of `KotlinDependencyHandler`, as this scope only has some predefined standard configurations available for use.

**Comment by jakobkmar** [comment]
```kt
plugins {
    kotlin("jvm") version "1.5.31"
    id("fabric-loom") version "0.10-SNAPSHOT"
    kotlin("plugin.serialization") version "1.5.31"
    id("org.jetbrains.compose") version "1.0.0-beta5"
}

repositories {
    mavenCentral()
    google()
    maven("https://maven.fabricmc.net/")
    mavenLocal()
    maven("https://oss.sonatype.org/content/repositories/snapshots")
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
}

val includeImplementation by configurations.creating {
    configurations.implementation.configure { extendsFrom(this@creating) }
}

dependencies {
    minecraft("com.mojang:minecraft:$minecraftVersion")
    mappings("net.fabricmc:yarn:$yarnMappingsVersion")
    modImplementation("net.fabricmc:fabric-loader:$fabricLoaderVersion")
    modImplementation("net.fabricmc.fabric-api:fabric-api:$fabricApiVersion")
    modImplementation("net.fabricmc:fabric-language-kotlin:$fabricLanguageKotlinVersion")

    implementation(compose.desktop.currentOs)

    includeImplementation("org.litote.kmongo:kmongo-coroutine-core:4.3.0")
    includeImplementation("org.litote.kmongo:kmongo-serialization-mapping:4.3.0")
    includeImplementation("org.slf4j:slf4j-simple:1.7.32")
    includeImplementation("org.apache.commons:commons-text:1.9")

    // example usage which triggers the error
    includeImplementation.resolvedConfiguration.firstLevelModuleDependencies
}
```

Or is there any way I could convert this project using Compose to a project using the multiplatform plugin?

**Comment by akurasov** [comment]
>Or is there any way I could convert this project using Compose to a project using the multiplatform plugin?

Yes, it is quite easy. 

Replace kotlin("jvm") version "1.5.31" with kotlin("multiplatform") version "1.5.31"

 add the code below and move dependencies there. It should work. 

```
kotlin {
    jvm {
        withJava()
    }
    sourceSets {
        named("jvmMain") {
            dependencies {
>>put dependencies here
            }
        }
    }
}

```

**Comment by jakobkmar** [comment]
Yes I already tried that, but he custom configurations such as modImplementation etc are not available there.

**Comment by akurasov** [comment]
What are these custom functions for?

**Comment by akurasov** [comment]
As an option, you could split code in two modules. Use Compose+mpp plugin in one module and custom imports in another.

**Comment by jakobkmar** [comment]
> What are these custom functions for?

They are [Gradle configurations](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:what-are-dependency-configurations), `minecraft` specified the Minecraft dependency, `mappings` specifies the mappings for Minecraft and `modImplementation` adds Minecraft mods.

**Comment by jakobkmar** [comment]
> As an option, you could split code in two modules. Use Compose+mpp plugin in one module and custom imports in another.

I could do that, but I would still have to execute `includeImplementation.resolvedConfiguration.firstLevelModuleDependencies` in the other module dependening on the compose module, which would lead to the same error.

**Comment by akurasov** [comment]
>>I could do that, but I would still have to execute includeImplementation.resolvedConfiguration.firstLevelModuleDependencies in the other module dependening on the compose module, which would lead to the same error

Could you share you build scripts? I struggle to understand that is the issue

**Comment by jakobkmar** [comment]
The simplest example would be just to try and shade the compose dependency using the Gradle shadow plugin in a JVM context. Not that I'd recommend this, but this will trigger the problem I mean, as it tried to resolve the compose dependency as well.

**Comment by jakobkmar** [comment]
To trigger the problem:
```kt
plugins {
    kotlin("jvm") version "1.6.10"
    id("org.jetbrains.compose") version "1.0.1-rc2"
    id("com.github.johnrengelman.shadow") version "7.1.1"
}

repositories {
    mavenCentral()
    google()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
}

val embed: Configuration by configurations.creating

dependencies {
    embed(implementation(compose.desktop.currentOs)!!)
}

tasks {
    shadowJar {
        configurations = listOf(embed)
    }
}
```

**Comment by akurasov** [comment]
I guess you meant don not provide. What exactly is missing?

**Comment by jakobkmar** [comment]
> I guess you meant don not provide.

correct

> What exactly is missing?

The custom Gradle configurations and compatiblity with other Gradle plugins as shown in [my previous comment](https://github.com/JetBrains/compose-jb/issues/1404#issuecomment-972952209).

**Comment by jakobkmar** [comment]
With release `1.0.1` the issue was resolved, but with `1.1.0` it was reintroduced.

**Comment by trychen** [comment]
having the same issues building fatjar with compose dependencies

**Comment by trychen** [comment]
Have the same issues building fatjar with compose dependencies

**Comment by jakobkmar** [comment]
I tried to use a separate project with the Kotlin Multiplatform Gradle plugin, but the same issue comes up there as well.

Asking more generally:
How can I get a list of all transitive dependencies of `compose.desktop.common`, using either the JVM or the Multiplatform Plugin. With all the methods I tried, I always get the "Cannot choose between the following variants" error.

**Comment by jakobkmar** [comment]
Related issue: https://github.com/JetBrains/skiko/issues/547

---

Generally speaking, the issue here is not if one uses the Kotlin Multiplatform plugin or not, but that Gradle does not have enough information about which artifact it should use.

**To fix this, the Compose Gradle plugin should ask for the correct UI attribute.** For this to work correctly, I think skiko has to provide the correct attributes with each artifact first. Also, skiko should add a namespace to the ui attribute - I also added that to the skiko issue.

### Temporary fix

I found out that you can apparently "fix" this by using some weird Gradle behaviour, and ask for an ui attribute that does not even exist. Let's use <code>awt</code>, just because it makes sense in this case.

To apply this fix, do this, either using `configurations.all` or just for your configuration which you use to shade or include dependencies:
```kt
configurations.all {
    attributes {
        attribute(Attribute.of("ui", String::class.java), "awt")
    }
}
```
</details>

**Comment by kirill-grouchnikov** [comment]
Some time ago I was running into `Cannot choose between the following variants` and came up with this snippet:

```
tasks.register("printRuntimeDependencies") {
    println("Project runtime dependencies:")
    allprojects {
        println()
        println("-------- ${project.name} --------")
        project.configurations.matching { it.name == "desktopRuntimeClasspath" }
            .matching { !it.allDependencies.isEmpty() }
            .forEach {
                it.allDependencies.forEach { dep ->
                    if (dep.group != null) {
                        println("${dep.group}:${dep.name}:${dep.version}")
                    }
                }
            }
    }
}
```

**Comment by mikehearn** [comment]
@jakobkmar Thank you for your workaround!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6112">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
