### ISSUE TITLE
(IDE Plugin) Doesn't work when the function is in a class

### ISSUE THREAD

**Issue by dkim19375** [JetBrains/compose-multiplatform#1409]
Note: I don't know where I could add this feature/bug(?) request.. so I just made one here 🤷 

There is no button to view the preview when the function is in a class.
Example:
```kt
@Composable
@Preview
fun app() {

}
```
works but
```kt
class SomeClass {
    @Composable
    @Preview
    fun app() {
    
    }
}
```
doesn't :/

**Comment by AlexeyTsvetkov** [comment]
Annotating a non-static method with `@Preview` is not supported intentionally.
It would lead to bad UX in my opinion: while we can run a non-static method for a class with a default constructor, 
it would not be possible to run a non-static method for a class without a default constructor.
Consider a user adding a mandatory parameter to `SomeClass`:
```
class SomeClass(val otherClass: OtherClass) {
    @Composable
    @Preview
    fun app() {
    
    }
}
```
How would we construct an instance of `SomeClass` in this case?

Adding preview support for a non-static method only for classes with a default constructor does not seem worth it.
JetPack Compose for Android also does not support this AFAIK.

However, you should be able to use `@Preview` in companion objects (and probably normal objects as well), but it seems to be broken at the moment (this will be fixed) :(

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6179">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
