### ISSUE TITLE
Add 'always on top' functionality to new Window API

### ISSUE THREAD

**Issue by jmoore34** [JetBrains/compose-multiplatform#1410]
It'd be nice if the new declarative Window API directly supported making windows stay on top of other windows. Electron equivalent: https://www.electronjs.org/docs/latest/api/browser-window#winsetalwaysontopflag-level-relativelevel

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6177">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
