### ISSUE TITLE
Simplify CSS API Builder hierarchy

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-multiplatform#1412]
Currently we have:

 * interface CSSBuilder : CSSStyleRuleBuilder, GenericStyleSheetBuilder<CSSBuilder>
 * class CSSBuilderImpl : CSSRuleBuilderImpl(), CSSBuilder, CSSRulesHolder by rulesHolder
 * interface CSSStyleRuleBuilder : StyleBuilder
 * open class CSSRuleBuilderImpl : CSSStyleRuleBuilder, StyleBuilderImpl()
 * interface StyleBuilder 
 * interface CSSRulesHolder
 * interface GenericStyleSheetBuilder<TBuilder> : CSSRulesHolder 
 
 We need to revisit all this entities and do following:
 
 1) Remove all entities that make sense to remove
 2) Make sure only entities that are intended to be public are public
 3) If the final set of entities is still big and confusing - document the hierarchy and explicitly justify it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6220">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
