### ISSUE TITLE
Compose-Desktop : clip Modifier does not work on SwingPanel as a child

### ISSUE THREAD

**Issue by Vshnv** [JetBrains/compose-multiplatform#1414]
Using the clip modifier with any shape does not seem to affect content inside a SwingPanel.

**Comment by MatkovIvan** [comment]
Same as #1449

Fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/915 (under the flag)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5997">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
