### ISSUE TITLE
SwingPanel doesn't honor JComponent's preferredSize

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-multiplatform#1417]
Using a SwingPanel doesn't seem to honor the JComponent's preferred size:

https://docs.oracle.com/javase/7/docs/api/javax/swing/JComponent.html#getPreferredSize()

Probably by default, unless otherwise constrained by layout and/or a modifier, the SwingPanel should by default honor the JComponent's preferred size as part of layout calculations.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6176">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
