### ISSUE TITLE
Textfield jumps on each symbol if there is an emoji in it

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1419]
Windows 11, 1.25 density

https://user-images.githubusercontent.com/5963351/142463740-33fb1e69-d951-463c-8a94-1ccae067a088.mp4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6218">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
