### ISSUE TITLE
Wrong script name in web-template index.html

### ISSUE THREAD

**Issue by snksoft** [JetBrains/compose-multiplatform#1422]
index.html in templates/web-template loads script called web-template.js, but build system generates script named KotlinWeb.js. As a result, running the project just shows an empty page as script is not found. Changing script name in the index.html to KotlinWeb.js appears to fix the issue and everything works as expected. So, I assume it's just a typo in the index.html.

**Comment by eymar** [comment]
Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6053">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
