### ISSUE TITLE
LazyListState.isScrollInProgress is always false on desktop

### ISSUE THREAD

**Issue by JoeSteven** [JetBrains/compose-multiplatform#1423]
Compose-jb version: 1.0.0-beta5
kotlin version: 1.5.31
Hi,  I want to save the first item position after scroll,  here is my code:
```kotlin
            MaterialTheme {
                val listState = rememberLazyListState()
                LaunchedEffect(Unit) {
                    snapshotFlow { listState.isScrollInProgress }
                        .distinctUntilChanged()
                        .filter {
                            println("is scroll in Progress:$it")
                            !it
                        }.collect {
                            //save state here..
                        }
                }
                LazyColumn(state = listState) {
                    items(500) { index ->
                        Text("Test item $index")
                    }
                }
            }
```
it works perfect on Android, isScrollInProgress updated  every time the list start to scroll and stop scroll
```
2021-11-19 14:26:37.012 16032-16032/? I/System.out: is scroll in Progress:true
2021-11-19 14:26:37.495 16032-16032/? I/System.out: is scroll in Progress:false
2021-11-19 14:26:37.860 16032-16032/? I/System.out: is scroll in Progress:true
2021-11-19 14:26:39.333 16032-16032/? I/System.out: is scroll in Progress:false
2021-11-19 14:26:58.640 16032-16032/? I/System.out: is scroll in Progress:true
2021-11-19 14:27:00.484 16032-16032/? I/System.out: is scroll in Progress:false
```
But on desktop (MacOS BigSur/ Windows10) I found that  isScrollInProgress ```is always false``` even list is clearly in scroll。BTW， I've tested this code both on my project and Compose-jb/examples/imageViewer, the results is the same.

**Comment by zacharee** [comment]
I'm running into this issue too. It seems like on desktop `DefaultScrollableState.scroll()` isn't being called. Instead, `dispatchRawDelta()` is. Since that second method doesn't affect `isScrollInProgress`, it's always false.

I think it's because of the `touchScrollable()` vs `mouseScrollable()` differences [here](https://github.com/JetBrains/androidx/blob/jb-main/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt#L129).

**Comment by SebastianAigner** [comment]
Encountered this problem while trying to synchronize the scroll position of multiple parallel `LazyColumn`s. 
Inspired by these answers on StackOverflow:

https://stackoverflow.com/questions/71206165/shared-lazyliststate-across-multiple-lazyrow-result-in-strange-behavior?noredirect=1&lq=1,
https://stackoverflow.com/questions/69565303/scroll-multiple-lists-at-different-speeds-in-jetpack-compose/69613111#69613111

**Comment by MatkovIvan** [comment]
It should be mitigated after implementing [smooth (animated) scrolling](https://github.com/JetBrains/compose-multiplatform-core/pull/438), but if you need to check if there was a scroll, you should subscribe to `firstVisibleItemIndex` and `firstVisibleItemScrollOffset` (as @SebastianAigner mentioned above) instead:
```
snapshotFlow { listState.firstVisibleItemIndex to listState.firstVisibleItemScrollOffset }
    .distinctUntilChanged()
```

Semantics of `isScrollInProgress` returns `true` only if we have a scroll across multiple frames, i.e. we have something continuous, not instant. Unlike dragging where we can detect start, move and end of gesture (in different frames), it's not a case with single event from mouse wheel. As I mentioned above it can be mitigated by introduction animated transaction, but still even after that, there can be a situation where transaction doesn't have an animation, and scroll position will be changed from one place to another in one single frame.

**Comment by MatkovIvan** [comment]
It worth to mention that [smooth (animated) scrolling](https://github.com/JetBrains/compose-multiplatform-core/pull/438) is merged, so currently there is a [TODO](https://github.com/JetBrains/compose-multiplatform-core/blob/abd75ea142aa1c13dd2fc6183b7c0beeb6a0f681/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt#L350-L358) in code about this flag. Please note that it's still not exactly about mouse wheel, since it's just single-frame event (as explained above).

**Comment by YektaDev** [comment]
`ScrollState` has a similar field. It's also always `false` on desktop.

**Comment by aljohnston112** [comment]
> It should be mitigated after implementing [smooth (animated) scrolling](https://github.com/JetBrains/compose-multiplatform-core/pull/438), but if you need to check if there was a scroll, you should subscribe to `firstVisibleItemIndex` and `firstVisibleItemScrollOffset` (as @SebastianAigner mentioned above) instead:
> 
> ```
> snapshotFlow { listState.firstVisibleItemIndex to listState.firstVisibleItemScrollOffset }
>     .distinctUntilChanged()
> ```
> 
> Semantics of `isScrollInProgress` returns `true` only if we have a scroll across multiple frames, i.e. we have something continuous, not instant. Unlike dragging where we can detect start, move and end of gesture (in different frames), it's not a case with single event from mouse wheel. As I mentioned above it can be mitigated by introduction animated transaction, but still even after that, there can be a situation where transaction doesn't have an animation, and scroll position will be changed from one place to another in one single frame.

I tried this

```kt
    LaunchedEffect(lazyListState) {
        snapshotFlow {
            lazyListState.firstVisibleItemIndex to
                    lazyListState.firstVisibleItemScrollOffset
        }.distinctUntilChanged().collect { (i, offset) ->
            println("Changed")
            lazyListState.scrollToItem(i, offset)
        }
    }
    ```
    and it only triggers twice and then scrolling stops working.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6016">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
