### ISSUE TITLE
"package" does not honour file execution flags.

### ISSUE THREAD

**Issue by Klurige** [JetBrains/compose-multiplatform#1431]
I'm trying to add a script with my application, by placing it in a system-specific folder (resources/linux, resources/window). However, when installing with dpkg, the exe flag is gone.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5180">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
