### ISSUE TITLE
Compiler: value in destructuring declaration of MutableState doesn't get updated

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-multiplatform#1436]
```kotlin
var (foo, setFoo) =  mutableStateOf(0)
setFoo(123) // set
foo == 123 // expected, but false
foo == 0 // actual, but should be 123
```

it works like this because `foo` gets initialised by the initial value of mutableState (like `var foo = mutableState.value`). and foo never changes. IR looks like this (explains the behaviour):
```
// kotlin
val (abc, def) = mutableStateOf(0)
val i = abc

// ir
COMPOSITE type=kotlin.Unit origin=DESTRUCTURING_DECLARATION
      VAR IR_TEMPORARY_VARIABLE name:tmp0_container type:androidx.compose.runtime.MutableState<kotlin.Int> [val]
        CALL 'public final fun mutableStateOf <T> (value: T of androidx.compose.runtime.mutableStateOf, policy: androidx.compose.runtime.SnapshotMutationPolicy<T of androidx.compose.runtime.mutableStateOf>): androidx.compose.runtime.MutableState<T of androidx.compose.runtime.mutableStateOf> declared in androidx.compose.runtime' type=androidx.compose.runtime.MutableState<kotlin.Int> origin=null
          <T>: kotlin.Int
          value: CONST Int type=kotlin.Int value=0
      VAR name:abc type:kotlin.Int [val]
        CALL 'public abstract fun component1 (): T of androidx.compose.runtime.MutableState [operator] declared in androidx.compose.runtime.MutableState' type=kotlin.Int origin=COMPONENT_N(index=1)
          $this: GET_VAR 'val tmp0_container: androidx.compose.runtime.MutableState<kotlin.Int> [val] declared in androidx.compose.runtime.Ac' type=androidx.compose.runtime.MutableState<kotlin.Int> origin=null
      VAR name:def type:kotlin.Function1<kotlin.Int, kotlin.Unit> [val]
        CALL 'public abstract fun component2 (): kotlin.Function1<T of androidx.compose.runtime.MutableState, kotlin.Unit> [operator] declared in androidx.compose.runtime.MutableState' type=kotlin.Function1<kotlin.Int, kotlin.Unit> origin=COMPONENT_N(index=2)
          $this: GET_VAR 'val tmp0_container: androidx.compose.runtime.MutableState<kotlin.Int> [val] declared in androidx.compose.runtime.Ac' type=androidx.compose.runtime.MutableState<kotlin.Int> origin=null

VAR name:i type:kotlin.Int [val]
      GET_VAR 'val abc: kotlin.Int [val] declared in androidx.compose.runtime.Ac' type=kotlin.Int origin=null 
```

Some possible options to fix:
1) make `MutableState<T>.component1()` return `State<T>` instead of its immediate value. (Unfortunately, this is a breaking change. Users will need to write `abc.value` instead of just `abc`)
2) make IR transformation to replace `GET_VAR` of destructured values (component1) by getting values from mutableState (`VAR IR_TEMPORARY_VARIABLE name:tmp0_container`). This will ensure that Composable Scopes  "subscribe" to changes of MutableState and restart when needed. The disadvantage is that it can be confusing when debugging such an example: `abc` value might  differ from state.value used in generated code. Perhaps, there is a possible fix for a debugger too, I'm just not aware of it.

**Comment by eymar** [comment]
@jimgoog Jim, do you think any of 2 options above could be ok to use as a fix? Or maybe there're other options I didn't think about. Thanks!

**Comment by eymar** [comment]
the problem (if it's a problem at all) might be hidden by the way how Composable functions work (so when used within remember, the behaviour of the Composable function is absolutely correct):

```kotlin
@Composable
fun Foo() {
   // this is the moment when state.value read happens, so Foo will restart on every `setFoo(...)`
    val (foo, setFoo) =  remember { mutableStateOf(1) } 

    SomeButton(text = "$foo") {
          setFoo(foo + 1)
    }
}
```

To conclude:
it seems better to avoid using the desctructuring syntax for mutableState without @Composable scope, like declaring a top level state `val (foo, setFoo) =  mutableStateOf(1)`, since `foo` never changes.

So now I see, why this can behaviour can be okay. Then maybe the comment in SnapshotState.kt is a bit confusing: https://github.com/androidx/androidx/blob/androidx-main/compose/runtime/runtime/src/commonMain/kotlin/androidx/compose/runtime/SnapshotState.kt#L199

```kotlin
/**
     * The componentN() operators allow state objects to be used with the property destructuring
     * syntax
     *
     * ```
     * var (foo, setFoo) = remember { mutableStateOf(0) }
     * setFoo(123) // set
     * foo == 123 // get
     * ```
     */
    override operator fun component1(): T = value
    ```

**Comment by jimgoog** [comment]
Yeah, I suspect the comment is probably closer to what was the desired behavior, but we failed to test it adequately prior to release.  I suspect we probably should have made `component1` return a getter lambda instead of an unwrapped T, but changing that now would be an API-signature-breaking change.  Since this is now stable API, I'm not sure there is much we could do about this, other than deprecate the destructuring operators.  I'll discuss with my team and see what they think.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5176">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
