### ISSUE TITLE
SwingPanel not clipped by containing widget

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-multiplatform#1449]
Consider the following code:

```
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        Column {
            Card(modifier = Modifier.size(100.dp), shape = RoundedCornerShape(30.dp), elevation = 10.dp) {
                Box(Modifier.fillMaxSize().background(Color.Green)) {
                    SwingPanel(background = Color.Green, factory = { JLabel(" ")}, update={it.text = " "})
                }
            }
        }
    }
}
```

It should look like this:
<img width="145" alt="Screen Shot 2021-11-23 at 1 13 21 PM" src="https://user-images.githubusercontent.com/29311816/143130256-754e6001-8276-4f16-a13e-ff00c800d70c.png">

But it actually looks like this:
<img width="160" alt="Screen Shot 2021-11-23 at 1 12 55 PM" src="https://user-images.githubusercontent.com/29311816/143130289-fd8ab94b-5f9d-4bc7-aa0b-bbad2390aa47.png">

Notice the content of the box is not clipped by the rounded corners of its container card.  You can reproduce by commenting out the SwingPanel and notice that the content is clipped by the containing card when there is no SwingPane inside the card.

cc @igordmn

**Comment by igordmn** [comment]
Unfortunately this is how SwingPanel works currently. I added docs about it.

We draw all Swing component over all compose components now.

To properly fix the issue, we need to draw Swing into texture/bitmap (preferably with hardware acceleration), or map all Swing Graphics2D operations to Skia operations.

**Comment by felixdivo** [comment]
Possibly related to #1202

**Comment by jimgoog** [comment]
Huh, [skijagraphics2d](https://github.com/jfree/skijagraphics2d) is actually kinda cute/clever - it could also improve the situation for screenshot testing too, which currently crashes if a widget contains a swing subcomponent.

I don't think I have the knowledge to recommend one approach or the other, but as @felixdivo observed, many things are going to be broken if clipping and layering are wrong.

**Comment by MatkovIvan** [comment]
Fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/915 (under the flag)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5169">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
