### ISSUE TITLE
SelectionContainer  not work with any clickable component

### ISSUE THREAD

**Issue by HuixingWong** [JetBrains/compose-multiplatform#1450]
```kotlin
SelectionContainer {
        ClickableText(
            text = AnnotatedString("Click Me"),
            onClick = { offset ->
                println("ClickableText $offset -th character is clicked.")
            }
        )
    }
 ```

This code works fine on Android but does not respond to desktop clicks

**Comment by akurasov** [comment]
Reproduced on 1.0.0

**Comment by theapache64** [comment]
Any update on this guys?

**Comment by wgryglas** [comment]
I can confirm it does not work still. 

I was trying to create a Box as an InlineTextContent instead of using ClickableText in order to capture clicks - I thought ClickableText was the only one affected. 
It turns out that the "hover" event propagates correctly because the interaction (background highlight) works. 
However, it looks like the "click" event is not. 

It seems SelectionContainer somehow prevents from propagating the click event deeper.

**Comment by HuixingWong** [comment]
@akurasov   😂 ？

**Comment by OrientLegend** [comment]
Is this problem solved?

**Comment by gandrewstone** [comment]
> Is this problem solved?

no @ compose 1.4.0

**Comment by ialokim** [comment]
Here is another workaround which leaves the whole text selectable:

```kotlin
    var lastLayoutResult: TextLayoutResult? by remember { mutableStateOf(null) }

    BasicText(
        text = formattedString,
        modifier = modifier
            // workaround for https://github.com/JetBrains/compose-multiplatform/issues/1450
            // todo: when fixed, change to ClickableText and move logic to onClick parameter
            .onPointerEvent(PointerEventType.Release) {
                val offset = lastLayoutResult?.getOffsetForPosition(it.changes.first().position) ?: 0
                formattedString
                    .getStringAnnotations(tag = "link", start = offset, end = offset)
                    .firstOrNull()
                    ?.let { annotation ->
                        handleLink(annotation.item)
                    }
            },
        onTextLayout = { layoutResult ->
            lastLayoutResult = layoutResult
        }
    )
```

**Comment by sunny-chung** [comment]
The workaround using `DisableSelection` is not working in Compose Multiplatform 1.6.0-beta02. After clicking a selectable text, and then click the image button, the `clickable` handler is not triggered. It is only triggered on the consecutive second click.

```
SelectionContainer {
        Row {
            DisableSelection {
                Image(
                    painter = painterResource("copy-to-clipboard.svg"),
                    colorFilter = ColorFilter.tint(Color(0f, 0f, 1f)),
                    contentDescription = null,
                    modifier = Modifier.size(40.dp)
                        .clickable(onClick = { ++count })
                )
            }
            Text(text = "Count: $count", fontSize = 40.sp)
        }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5168">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
