### ISSUE TITLE
useResource and loadImageBitmap not Multiplatform: not defined for Android target

### ISSUE THREAD

**Issue by sonique6784** [JetBrains/compose-multiplatform#1456]
I'm not able to use `useResource` and `loadImageBitmap` when targeting Android.
I do use these functions on Desktop (Mac), and it works well.

```
val bitmap = useResource(fileName) { loadImageBitmap(it) }
```

I believe it is because `useResource` doesn't exists in the Android API, instead we have `painterResource`, `fontResource`...

https://developer.android.com/reference/kotlin/androidx/compose/ui/res/package-summary

```
# build.gradle config common module

 val commonMain by getting {
            dependencies {
                api(composemm.runtime)
                api(composemm.foundation)
                api(composemm.material)
                api(composemm.ui). // org.jetbrains.compose.ui:ui
                api(composemm.desktop.currentOs)
                implementation("org.openrndr:openrndr-math:0.3.47")
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
        }
        val androidMain by getting {
            dependencies {
                api("androidx.appcompat:appcompat:1.4.0")
                api("androidx.core:core-ktx:1.6.0")
                api(ComposeAndroid.ui) // androidx.compose.ui:ui:1.0.0
                api(ComposeAndroid.runtime)
                api(ComposeAndroid.material)
                api(ComposeAndroid.ui)
            
            }
        }
```

**Comment by Andrew0000** [comment]
My thoughts on Roman's answer [here](https://youtrack.jetbrains.com/issue/KT-22841/Prohibit-different-member-scopes-for-non-final-expect-and-its-actual#focus=Comments-27-8182106.0-0): 
While we are waiting K2, why not to warn users of the `useResource` function that it works only on desktop? Like it's done with expect/actual if you forget to implement all actuals.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5165">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
