### ISSUE TITLE
API to load images from internet

### ISSUE THREAD

**Issue by NewDay126** [JetBrains/compose-multiplatform#1468]
please make the **image** component support  load pictures from the remote web server。
ex：just like flutter  load pictures from the remote web server **Image.network ( " picture's web link " )**

the **image** component for desktop  now only support load Local device pictures，not support load pictures from the remote web server。that is not friendly for developer.

**Comment by dragossusi** [comment]
Can you explain more?  There's literally no description provided and a confusing title

**Comment by akurasov** [comment]
Yes, please clarify what exactly you believe should be added

**Comment by NewDay126** [comment]
make the image Component  support load the network iamge, （ for windows desktop）

**Comment by NewDay126** [comment]
> laod  pictures of the remote web server，ex：just like flutter ：Image.network( " picture's  web link  " )

**Comment by GabrielLasso** [comment]
You can use libs such as https://github.com/alialbaali/Kamel or https://github.com/ltttttttttttt/load-the-image

Or, for android you can use https://github.com/coil-kt/coil

But I agree that it should have native support out of the box...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5158">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
