### ISSUE TITLE
MenuBar not visible in 1.0.0-beta5

### ISSUE THREAD

**Issue by Adiudiu** [JetBrains/compose-multiplatform#1469]
When I switch tabs dynamically and switch to a Swing control in a SwingPanel, MenuBar doesn't show up, it needs to manually resize the window to show up.

How to solve this problem? What are the alternative methods?

![QQ截图20211126163012](https://user-images.githubusercontent.com/23241782/144961314-6c9c6427-6f6f-40bd-8f3e-113d9bedb695.png)

**Comment by Adiudiu** [comment]
How to solve this problem? What are the alternative methods?

**Comment by akurasov** [comment]
Could you share some small reproducer to this issue?

**Comment by Adiudiu** [comment]
I tried version 1.0.0 and still have problems.

**Comment by Adiudiu** [comment]
You can reproduce the problem with the official Demo -widgets- Gallery.

You need to make 4 changes to the Demo.
1. Modify main.kt
![QQ截图20211208204603](https://user-images.githubusercontent.com/23241782/145211621-9f616378-b0eb-498d-ab7d-03b08feac70e.png)

> MenuBar {
        Menu("File", mnemonic = 'F') {
            Item("New", onClick = {  })
            Item("Open", onClick = {  })
            Item("Import", onClick = {  })
        }
    }

2. Modify Chips.kt
![QQ截图20211208204642](https://user-images.githubusercontent.com/23241782/145211757-a1df6035-b51d-46c1-8364-532e8aec27dc.png)

> ComboBox("",
        0,
        mutableListOf("1", "2"),
        onItemSelected = {
            print("lihj, ComboBox $it")
        })

3.Add file ComboBox.kt  in Common lib 
![QQ截图20211208210539](https://user-images.githubusercontent.com/23241782/145213332-e26271c1-2db0-4c11-88b4-1601e91edd6a.png)

> @Composable
expect fun ComboBox(
    title: String?,
    selectIndex: Int? = 0,
    items: MutableList<String>,
    onItemSelected: (String) -> Unit
)

4.Add class ComboBox.kt in desktop platform
![QQ截图20211208204725](https://user-images.githubusercontent.com/23241782/145211806-53ccd286-8295-4359-ac3f-13ccdc1df612.png)

>`@Composable
actual fun ComboBox(
    title: String?,
    selectIndex: Int?,
    items: MutableList<String>,
    onItemSelected: (String) -> Unit
) {
    Row(modifier = Modifier
        .fillMaxWidth()
        .wrapContentHeight()
        .padding(0.dp, 8.dp, 0.dp, 0.dp),
        verticalAlignment = Alignment.Top,
        horizontalArrangement = Arrangement.Center) {
        title?.let {
            Text(text = title,
                fontSize = 14.sp,
                modifier = Modifier.padding(0.dp, 6.dp, 0.dp, 0.dp))
        }
        SwingPanel(
            background = Color.White,
            modifier = Modifier
                .size(100.dp, 30.dp),
            factory = {
                JPanel().apply {
                    background = JColor.WHITE
//                    add(JComboBox(items.toTypedArray()).apply {
//                        selectedIndex = selectIndex ?: 0
//                        addItemListener {
//                            if (it.stateChange == ItemEvent.SELECTED) {
//                                onItemSelected.invoke(it.item as String)
//                            }
//                        }
//                    })
                    val value = SpinnerNumberModel(5,0,10,1)
                    layout = BoxLayout(this, BoxLayout.Y_AXIS)
                        .apply {

                            val spinner = JSpinner(value).apply {
                                setBounds(0,0,50,30)
                            }
                            add(spinner)
                        }
                }
            }
        )
    }
}`

**Comment by akurasov** [comment]
I tried with 1.0.0 on Mac (only added MenuBar itself as other changes doesn't seem related to it). What is your OS?

**Comment by Adiudiu** [comment]
> I tried with 1.0.0 on Mac (only added MenuBar itself as other changes doesn't seem related to it). What is your OS?

I use Windows 10 Professional.

I guess this has something to do with Swing showing the hide on the Compose UI.

**Comment by gregbarski** [comment]
I also got the same problem frequently. The menu is not visible until windows got resized. Calling `window.invalidate()` does not hepl too.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5157">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
