### ISSUE TITLE
How to make "Title bar window shake" work, when Window undecorated is enabled.

### ISSUE THREAD

**Issue by Omico** [JetBrains/compose-multiplatform#1472]
In Windows, we have a "Title bar window shake" feature.

![image](https://user-images.githubusercontent.com/14316223/143584132-addbe16e-5458-49a8-98cd-01c65572847b.png)

When I use a custom title bar via `WindowDraggableArea`, the "Title bar window shake" feature has gone.

What should I do?

**Comment by Omico** [comment]
With custom title bar

**Comment by mahozad** [comment]
The below solution will probably get you in the right direction.
I think you should implement the hit test function in the `CustomWindowProcessor` as was implemented in the Swing (JFrame) version linked in the comment:

- https://github.com/JetBrains/compose-multiplatform/issues/3388#issuecomment-1672732504

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5155">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
