### ISSUE TITLE
Rich Text Implementation?

### ISSUE THREAD

**Issue by SKeeneCode** [JetBrains/compose-multiplatform#1477]
Thinking about switching from JavaFX to compose for desktop. One of the most frustrating things I encountered was having to implement a rich text implementation in JavaFX with RichTextFX (fonts/bold/itallic/underline/bullet point lists/paragraph alignment etc). 

Does compose for desktop have a rich text implementation and if not is the library mature enough that it would be possible to implement it?

**Comment by akurasov** [comment]
@SKeeneCode there is no RT component in Compose at the moment. However it should be possible to implement it using current API.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5151">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
