### ISSUE TITLE
RadioButtonItem glitches after changing the state

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1488]
Compose 1.0.0, Windows 11

https://user-images.githubusercontent.com/5963351/143778528-0b8e1f1c-e20c-4bb4-aab8-e4cc75891bc5.mp4

See that after changing the item, and open the menu again, we can see the old state for some time

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5142">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
