### ISSUE TITLE
Selection isn't updated during scrolling if we don't move mouse

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1491]
Compose 1.0.0-rc6

https://user-images.githubusercontent.com/5963351/143783497-6761859e-b06d-48f1-bf6e-c9e7fa4a3032.mp4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5139">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
