### ISSUE TITLE
Selection doesn't move scroll in scrollable Box

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1492]
Compose 1.0.0-rc5

https://user-images.githubusercontent.com/5963351/143783665-bc21b504-1a3e-4808-81e9-d5937844d25b.mp4

See that feature is implemented in TextField, but isn't implemented in the usual scrollable text.

Also isn't implemented on Android (1.0.0 and 1.1-beta5)

It should be implemented for all scrollables, including [LazyList](https://github.com/JetBrains/compose-multiplatform/issues/3333).

**Comment by amank22** [comment]
Any update on this?

**Comment by vdshb** [comment]
Horizontal scrolling (if text line wider than the scrollable box) is also the case.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5138">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
