### ISSUE TITLE
Potentially low hanging fruit: Introduce support for Java 17

### ISSUE THREAD

**Issue by loxal** [JetBrains/compose-multiplatform#1495]
![Screenshot_20211129_052545](https://user-images.githubusercontent.com/87507/143808881-0029835b-31e2-4a10-a1a3-220dea5dc62a.png)
![Screenshot_20211129_052605](https://user-images.githubusercontent.com/87507/143808889-01818049-d69e-4d61-9707-3e9c5ea50502.png)

...is what I get with my Java 17 setup. I know there are ways to workaround this but even setting JAVA_HOME to point to Java 16 HOME did not resolved the problem without a re-login which I have not tried yet. So the examples are broken for me and might be broken for many other users. So even though I choose Java 16 in the wizard above, I am getting the error below. 

Just execute a `./gradlew wrapper --gradle-version 7.3` in all projects that contain a `gradle-wrapper.properties` file to use Gradle 7.3 that supports Java 17.

**Comment by loxal** [comment]
![Screenshot_20211129_052545](https://user-images.githubusercontent.com/87507/143809238-4a3aee48-c004-4482-bff8-048fec1fff64.png)

**Comment by dragossusi** [comment]
The error explains that your version of gradle is not supporting java 17, you should always search which versions of gradle support which versions of java, you usually change the version in `gradle-wrapper.properties`

**Comment by loxal** [comment]
I know, there are fixes that can be applied but it's not a good out-of-the-box experience.
