### ISSUE TITLE
TextField's maxLines is ignored when pasting text

### ISSUE THREAD

**Issue by JetpackDuba** [JetBrains/compose-multiplatform#1503]
Here goes a weird issue: When a TextField has a maxLines limit you simply can't add new lines by hitting the enter key. However, you can copy and paste a text with multiple lines. The weird part here is that it seems that everything is pasted in a single line which has it's own "scroll".

It's easier to understand with some GIFs.

Example without maxLines (works nicely):
![without_max_lines](https://user-images.githubusercontent.com/16917468/143911356-e4b45b22-0613-43a7-a55c-15a0bb353ee8.gif)

Example with maxLines = 1 (weird behavior):
![with_max_lines](https://user-images.githubusercontent.com/16917468/143911559-d2a295e7-bb38-478d-87f1-e0a54a37f7a5.gif)

Taking Intellij IDEA as an example of how it should behave (I've tried with a couple of random fields), if (pastedTextLines) > (maxLines - currentLineNumber) the last line should contain all the "overflowing" lines in a single one by removing the new lines character (not sure if it's possible to keep it while still having it in a single line).

Test code:
```
var textFieldValue by remember { mutableStateOf("") }
MaterialTheme {
    Column {
        OutlinedTextField(
            value = textFieldValue,
            onValueChange = {
                textFieldValue = it
            },
            modifier = Modifier.size(200.dp),
            maxLines = 1,
        )
        OutlinedTextField(
            value = textFieldValue,
            onValueChange = {
                textFieldValue = it
            },
            maxLines = 1,
        )
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6202">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
