### ISSUE TITLE
Question: is Swing 's pointer coordinate and Compose's coordinate interchangable?

### ISSUE THREAD

**Issue by anhanh11001** [JetBrains/compose-multiplatform#1512]
```
modifier.pointerInput(Unit) { // this - PointerInputScope
    val size = this.size
    while (true) {
        val event = awaitPointerEventScope { awaitPointerEvent() }
        val awtEvent = event.awtEvent
        when (event.type) {
            PointerEventType.Press -> {
                val pressLocation = Pair(awtEvent.x, awtEvent.y)
                // TODO: Some logic to determine the place of event press by calculating % of x, y in terms of pointerInputScore's size.
            }
        }
    }
}
```

An example of my use case is to calculate the width, height from the starting point to the press location. But it seems to me that (x,y) coordinate of Swing is not the same as Compose's PointerInputScope. 

Is it correct?
Any suggestions to achieve what I'm describing above?

This is related to the mouse tutorial

**Comment by akurasov** [comment]
Hello! Compose coordinates are awt coordinates * screen density

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6146">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
