### ISSUE TITLE
Popup inconsistent behavior

### ISSUE THREAD

**Issue by JetpackDuba** [JetBrains/compose-multiplatform#1513]
I have been trying to use `Popup` but I've found a couple of weird behaviors. The component docs says:

> Opens a popup with the given content.
> The popup is positioned relative to its parent, using the alignment and offset. The popup is visible as long as it is part of the composition hierarchy.

In my opinion it should provide an option to be positioned relatively to the window instead of the parent, but that's a different topic. The first issue can be seen in the following code:

```
fun main() = singleWindowApplication {
    MaterialTheme {
        var showPopup by remember { mutableStateOf(false) }
        Box {
            Column(
                modifier =
                Modifier.background(MaterialTheme.colors.background)
            ) {
                Button(onClick = { showPopup = false }) {
                    Text("Close popup")
                }

                Box(
                    modifier = Modifier
                        .weight(1f)
                        .fillMaxWidth()
                        .background(Color.Cyan)
                ) {
                    if (showPopup) {
                        Popup(focusable = true) {
                            Box(
                                modifier = Modifier
                                    .fillMaxSize()
                                    .background(
                                        Color(0xBB000000)
                                    ),
                            )
                        }
                    }
                    Button(onClick = { showPopup = true }) {
                        Text("Open popup")
                    }
                }
            }
        }
    }
}
```

In this example we see how we have a button and a box with a second button. The popup fills it's parent (`Box`) but not the windows, that's correct acording to the docs. The second button opens the `Popup` and the first one closes it. 

The issue starts when trying to close the popup with the first button, basically because the first button becomes unresponsive randomly.  Demo:

https://user-images.githubusercontent.com/16917468/144141363-4dca3f59-49b4-41da-9fda-6ad735b436c0.mp4

For some reason seems that moving the mouse allows the click to work (not sure if it's just a coincidence or related to the issue since doesn't always work).

After seeing that, I thought that I would try add a `Text` composable to show whenever an action occurs:

```
fun main() = singleWindowApplication {
    MaterialTheme {
        var lastAction by remember { mutableStateOf("") }
        var showPopup by remember { mutableStateOf(false) }
        Box {
            Column(
                modifier =
                Modifier.background(MaterialTheme.colors.background)
            ) {
                Button(onClick = {
                    lastAction = "Close popup clicked"
                    showPopup = false
                }) {
                    Text("Close popup")
                }

                Box(
                    modifier = Modifier
                        .weight(1f)
                        .fillMaxWidth()
                        .background(Color.Cyan)
                ) {
                    if (showPopup) {
                        Popup(focusable = true, onDismissRequest = { lastAction = "OnDismissRequest called" }) {
                            Box(
                                modifier = Modifier
                                    .fillMaxSize()
                                    .background(
                                        Color(0xBB000000)
                                    )
                                    .clickable { lastAction ="Clicked on box" },
                            )
                        }
                    }
                    Button(onClick = { showPopup = true }) {
                        Text("Open popup")
                    }
                }

                Text("Last action = $lastAction")
            }
        }
    }
}
```

After adding `onDismissRequest` to the Popup, clicking on the button has started to work properly if you always used the primary button, however it screwsup again if using a secondary mouse button. Demo:

https://user-images.githubusercontent.com/16917468/144142700-039e643f-ffca-4779-9887-324655b82c44.mp4

Not sure if you have noticed it, but in the last video a new unexpected behavior appeared aside from the unresponsiveness: I was expecting the popup to be limited to the Box area, as we have seen with the first button, however now it's also covering the "last action" `Text` which is not inside the `Box` (the `Popup`'s parent).

The main goal of this issue is to remark the unconsistent behavior of the Popup:
- How should clicks outside the parent Popup behave?
- Is it correct to overlap more components aside from the parent? If yes, why is it covering the next item in the `Column` but not the previous one?

Compose 1.0.0-rc6 on Linux.

Not sure if related to https://github.com/JetBrains/compose-jb/issues/1485

**Comment by igordmn** [comment]
Thanks for the detailed report! 

> In my opinion it should provide an option to be positivion relatively to the window instead of the parent

You can pass a custom `PopupPositionProvider`, as done [here](https://github.com/JetBrains/androidx/blob/a4e02138cf5fc4ce9235b6c8362698bae701821f/compose/material/material/src/desktopMain/kotlin/androidx/compose/material/DesktopAlertDialog.desktop.kt#L193)

> Is it correct to overlap more components aside from the parent? If yes, why is it covering the next item in the Column but not the previous one?

If we don't pass `PopupPositionProvider`, by default it is aligned by the parent's bounds, but measured by the window's bounds. So if we use `fillMaxSize` inside Popup, its size equals to the window size. It isn't obvious, and have limited usage, so I think [we should](https://github.com/JetBrains/compose-jb/issues/1516) cover that in docs, and add something like `PopupSizeProvider` (not sure yet).

In your second example, we measure Popup content by the window bounds and align it within the parent bounds. Alignment is `TopStart` by default.

> How should clicks outside the parent Popup behave?

We have two issues here:
1. unpredictable/wrong behavior, when we use `focusable=true` and `onDismissRequest=null`. The popup intercepts `mousePress` and do nothing
2. wrong behavior when we use `focusable=true` and `onDismissRequest={ showPopup = false }` and when we click with the right button outside of Popup (it should close, when we click with the right button).

Сan't reproduce the second one yet. Will look at the first one first.

**Comment by aeab13** [comment]
Sorry for the late response, I've been a bit busy.


> You can pass a custom `PopupPositionProvider`, as done [here](https://github.com/JetBrains/androidx/blob/a4e02138cf5fc4ce9235b6c8362698bae701821f/compose/material/material/src/desktopMain/kotlin/androidx/compose/material/DesktopAlertDialog.desktop.kt#L193)

Thanks! I've done it and works nicely :+1: 

> We have two issues here:
> 
>     1. unpredictable/wrong behavior, when we use `focusable=true` and `onDismissRequest=null`. The popup intercepts `mousePress` and do nothing
> 
>     2. wrong behavior when we use `focusable=true` and `onDismissRequest={ showPopup = false }` and when we click with the right button outside of Popup (it should close, when we click with the right button).
> 
> 
> Сan't reproduce the second one yet. Will look at the first one first.

The second one is a bit... weird. Instead of having a lambda  with `showPop = false`, simply leave it as an empty lambda.

**Comment by igordmn** [comment]
>The second one is a bit... weird. Instead of having a lambda with showPope = false

Oh, in that case it is similar to the first issue, if not the same.

As far as I remember, we don't distinguish between `null` and empty lambda.

So, we have a wrong/unexpected behavior if `onDismissRequest` doesn't close the popup.

**Comment by m-sasha** [comment]
Another set of complaints about popup behavior: https://github.com/JetBrains/compose-multiplatform/issues/3493

**Comment by MatkovIvan** [comment]
In 1.5.0 `Popup` has been unified with Android. This issue isn't relevant anymore.

> The popup fills it's parent (Box) but not the windows, that's correct acording to the docs.

BTW currently it fills the whole window/screen on both Android and Desktop. Docs here are only about position, not size.

> `Popup(focusable = true)`

it's `Popup(properties = PopupProperties(focusable = true))` now

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6042">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
