### ISSUE TITLE
Cleanup old MouseScroll API in AOSP

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-multiplatform#1514]
The compose-jb version of TestComposeWindow is already using the new API.  The only reason we are using the old MouseScroll API in AOSP is because we want to wait until 1.2-alpha to merge aosp/1837304 which provides the replacement API, but that replacement API is already in the compose-jb repo, which means that Compose MPP 1.0 does not use the old MouseScroll API and this API can thus be removed without being a breaking change and without a major version number bump.

We should remove the deprecation the AOSP copy of DesktopScrollableTest.kt and tests should either be deleted or updated to perform the same test using the new API.

Place where suppression was added:
- compose/foundation/foundation/src/desktopTest/kotlin/androidx/compose/foundation/gestures/DesktopScrollableTest.kt
- compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/TestComposeWindow.desktop.kt
- compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/input/mouse/MouseHoverFilterTest.kt
- compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/input/mouse/MouseScrollFilterTest.kt
- compose/ui/ui/src/desktopTest/kotlin/androidx/compose/ui/window/window/WindowInputEventTest.kt
- compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/input/mouse/MouseScrollFilter.skiko.kt

**Comment by igordmn** [comment]
> to merge aosp/1837304 which provides the replacement API, but that replacement API is already in the compose-jb repo, which means that Compose MPP 1.0 does not use the old MouseScroll API

We haven't cherry-picked that CL unfortunately.

We still use mouseScrollFilter here:
https://github.com/JetBrains/androidx/blob/a4e02138cf5fc4ce9235b6c8362698bae701821f/compose/foundation/foundation/src/desktopMain/kotlin/androidx/compose/foundation/gestures/DesktopScrollable.desktop.kt#L53

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6181">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
