### ISSUE TITLE
IDEA preview plugin doesn't work for compose multiplatform application

### ISSUE THREAD

**Issue by iptton** [JetBrains/compose-multiplatform#1515]
when run task:  desktop:configureDesktopPreviewJvm or common:configureDesktopPreviewDesktop, error  occurs

Some problems were found with the configuration of task ':desktop:configureDesktopPreviewJvm' (type 'AbstractConfigureDesktopPreviewTask').
  - In plugin 'org.jetbrains.compose.ComposeCompilerKotlinSupportPlugin' type 'org.jetbrains.compose.desktop.preview.tasks.AbstractConfigureDesktopPreviewTask' property 'idePort$compose' doesn't have a configured value.

**Comment by akurasov** [comment]
Hello! Which IDEA and which plugin version do you use?

**Comment by iptton** [comment]
> Hello! Which IDEA and which plugin version do you use?

IDEA 2021.2.3(Ultimate Edition) Build #IU-212.5457.46
Compose Multiplatform IDEA Support : 1.0.0 

It works only in "Compose Desktop" project.

**Comment by iptton** [comment]
after  update to 1.0.0 , still not work.  @Preview annotation cann't be resolved

**Comment by AlexeyTsvetkov** [comment]
>Some problems were found with the configuration of task ':desktop:configureDesktopPreviewJvm' (type 'AbstractConfigureDesktopPreviewTask').

@iptton do you run the task manually? It should be run only from Intellij plugin.

> @Preview annotation cann't be resolved

Do you have a dependency on `compose.desktop.currentOs`?
Please note, that the preview annotation and functionality is not available in common code yet.
Here is the example of MPP project configuration https://github.com/JetBrains/compose-jb/blob/master/idea-plugin/examples/simple-preview-example/mpp-jvm/build.gradle.kts (note that in the example the preview is available only in desktopMain source set, but unavailable in commonMain source set)

**Comment by iptton** [comment]
> @iptton do you run the task manually? It should be run only from Intellij plugin.

yes ,because i cannot see preview, i tried to run it manually

> Do you have a dependency on compose.desktop.currentOs?

I am using `@preview` in common module androidMain/commonMain/desktopMain folders of this project: https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp

seams it has configured correctly but not work.

And i saw some error in file: desktopMain/kotlin/example..../Utils.kt
```
Cannot access 'java.io.Serializable' which is a supertype of 'kotlin.Int'. Check your module classpath for missing or conflicting dependencies
```

The project's clean, not changed any thing but add code like:

```kotlin
@Preview
@Composable
fun Test(){

}
```

**Comment by ryanmitchener** [comment]
@iptton I had a similar problem and I just found out that Preview was not working with Java 17. In order to get previews to work I set kotlinOptions.jvmTarget = "16" in my build.gradle.kts.

**Comment by mrlem** [comment]
I experience a similar issue on IDEA 2022.3.3: no preview.
Turns out it's just a misleading user experience for someone used compose on Android Studio.

The preview doesn't appear automatically, I need those 2 steps to get it:
* run the app once, this will add a small icon in front of composable functions
* click the small preview icon of the composable I want see

**Comment by musokeharun** [comment]
i renamed my preview functions to <>Preview() with the annotation and it worked

**Comment by hereisderek** [comment]
> 

saved 

> @iptton I had a similar problem and I just found out that Preview was not working with Java 17. In order to get previews to work I set kotlinOptions.jvmTarget = "16" in my build.gradle.kts.

saved my life. I'd never thought it'd be the sdk's problem

**Comment by xinkunZ** [comment]
Why is it still not fixed in 2023?? 
Java 17 is so popular today :stuck_out_tongue_closed_eyes:

**Comment by Krobys** [comment]
issue still here

**Comment by hasanelfalakiy** [comment]
yeah still not working

**Comment by ThuanPx** [comment]
it still not working

**Comment by hasanelfalakiy** [comment]
> @ThuanPx  No，Fleet can't preview... , Just follow  [guide](https://www.jetbrains.com/help/kotlin-multiplatform-dev/fleet.html#get-started-with-fleet) , I can't preview any desktop preview ~  Fleet -1.35.115
> ![image](https://github.com/JetBrains/compose-multiplatform/assets/45779049/e8e161d9-e490-4471-bd37-20d2bb569542)
> 

are you using jdk 11 or 17?

**Comment by ALuoBo** [comment]
> > @ThuanPx  No，Fleet can't preview... , Just follow  [guide](https://www.jetbrains.com/help/kotlin-multiplatform-dev/fleet.html#get-started-with-fleet) , I can't preview any desktop preview ~  Fleet -1.35.115
> > ![image](https://private-user-images.githubusercontent.com/45779049/336423261-e8e161d9-e490-4471-bd37-20d2bb569542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTIxODksIm5iZiI6MTcxNzU1MTg4OSwicGF0aCI6Ii80NTc3OTA0OS8zMzY0MjMyNjEtZThlMTYxZDktZTQ5MC00NDcxLWJkMzctMjBkMmJiNTY5NTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDAxNDQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MzIzNmE5MDkyNGMzNzQwMDc5Y2M1ZTUzNzg3MDE4MzE4MjY2YjU2YWI0ZmVkN2JmNTMyNjg4MjEzODkzNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OOENRh_F3hVNwQ874-JeMb3Hj1uEdwpFNmpf4oFa1A4)
> 
> are you using jdk 11 or 17?

I am using openjdk 17 ~

**Comment by ALuoBo** [comment]
> kotlinOptions.jvmTarget = "16"
Excuse , I not good at gradle or fleet ，Could you tell me how to set the jdk version?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5999">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
