### ISSUE TITLE
Selection doesn't work correctly in some cases (Windows)

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1526]
Compose 1.0.0, Windows 11, `issues` example

https://user-images.githubusercontent.com/5963351/144286121-c2ced900-3648-4f5b-bf70-82869fad2c32.mp4

**Comment by igordmn** [comment]
on macOs works correctly

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6106">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
