### ISSUE TITLE
How to support touchscreen?

### ISSUE THREAD

**Issue by Richyeoh** [JetBrains/compose-multiplatform#1555]
I have a window pad，I running app on that，App is very simple just a LazyColumn，It can use mouse wheel scroll，but not use touchscreen scroll.

**Comment by Richyeoh** [comment]
I see  Modifier extensions function has a mouseScroll and mouseTouch，How to use it ? Thx~

**Comment by Richyeoh** [comment]
Hi @akurasov, Do you know how to solve this problem? I saw that you mentioned relevant problems and tried to solve the problem of unable to drag and scroll on the touch screen.

**Comment by Richyeoh** [comment]
```kotlin
val scrollState = rememberLazyListState()
val data = (0 until 1000).map { "Item $it" }
LazyColumn(
    modifier = Modifier.draggable(rememberDraggableState { delta ->
        println("delta=$delta")
        runBlocking {
            scrollState.scrollBy(-delta)
        }
    }, orientation = Orientation.Vertical),
    state = scrollState
) {
    items(data) { i ->
        Text(
            i,
            Modifier
                .padding(14.dp)
                .fillMaxWidth()
        )
    }
}
```
See above code:
Maybe, I has solve the problem.

**Comment by akurasov** [comment]
Yes, if you want to handle dragging gesture, you should use this API. 

There is no explicit touch screen support, Compose relies on OS level conversion of touch Screen events to mouse events.

**Comment by hasali19** [comment]
Is there a plan to implement proper touch screen support? I actually attempted to pass through touch events while trying out compose, using the `ComposeScene`, but found that certain components such as `TextField` are hard coded to only work properly for mouse on desktop.

**Comment by akurasov** [comment]
There are no immediate plans for it. Could you please describe some scenarios, where current support is not enough?

**Comment by hasali19** [comment]
There's no fling behaviour when scrolling with the above method, and no way to differentiate between mouse and touch gestures.

**Comment by ianbrandt** [comment]
> There are no immediate plans for it. Could you please describe some scenarios, where current support is not enough?

My use case is a GUI client that includes 2D and 3D mapping functionality. It can be run on any Windows or Linux multitouch-enabled device. Examples include laptops and desktops with monitors having multitouch support, Microsoft Surface and Linux tablet devices, and similar. For 2D maps (think Google Maps) it supports simultaneous pinch-to-zoom, drag-to-pan, and twist-to-rotate two-finger gestures. For 3D maps (think Google Earth) it's the same, with the addition that switching to three-fingered gestures changes drag-to-pan to drag-to-pan-horizontally-and-tilt-vertically. The client can sometimes be used in high-criticality (i.e. [potential loss of life](https://en.wikipedia.org/wiki/Cockburn_Scale#Definition)) situations, so precise, performant touch and gesture control is vital.

Currently we use [OpenJFX](https://openjdk.org/projects/openjfx/) for this, in particular its [`TouchEvent`](https://openjfx.io/javadoc/17/javafx.graphics/javafx/scene/input/TouchEvent.html) and [`GestureEvent`](https://openjfx.io/javadoc/12/javafx.graphics/javafx/scene/input/GestureEvent.html) multitouch support. See also ["Handling JavaFX Events: Working with Events from Touch-Enabled Devices"](https://docs.oracle.com/javafx/2/events/gestures.htm) and ["Handling JavaFX Events: Working with Touch Events"](https://docs.oracle.com/javafx/2/events/touch_events.htm).

I'd like to consider porting to Compose Multiplatform in the future to support Windows and Linux desktop, Android, and WASM targets all from a single client, but multitouch support would be required for each.

I could also see gaming and 3D modelling applications being two other use cases.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6005">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
