### ISSUE TITLE
Server-driven UI

### ISSUE THREAD

**Issue by StokeMasterJack** [JetBrains/compose-multiplatform#1560]
I would love to see a feature where the UI state lives on the server, UI events are sent from the UI to the server (by the framework). Dom diffs are send from the server to client (by the framework). And essentially all custom code lives on the server.

I do not know if this pattern has a name yet. But I am starting to see it all over the place. And it seems like a big productivity boost for business apps.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6178">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
