### ISSUE TITLE
能不能支持桌面tableview,chart等，类似javafx的tableview,chart

### ISSUE THREAD

**Issue by wuwensen007** [JetBrains/compose-multiplatform#1561]

**Comment by akurasov** [comment]
Could you please provide issue name and description in English?

**Comment by icuxika** [comment]
@akurasov  He wants to know whether this project will provide some components whicn are  similar to the TableView and Chart in JavaFX in the future.

**Comment by akurasov** [comment]
Table could be implemented via multiple Rows using the same layout. And for Charts existing 3rd party Swing components could be used

**Comment by akurasov** [comment]
Todo: write tutorial about tables

**Comment by victororlyk** [comment]
it would be cool to have something like https://github.com/Shopify/react-native-skia or some other way to draw charts

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6032">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
