### ISSUE TITLE
WindowPosition.Aligned is occupying screen insets (taskbar)

### ISSUE THREAD

**Issue by davidgomesdev** [JetBrains/compose-multiplatform#1565]
`WindowPosition.Aligned` mentions in the docs that the `Window will be aligned in the area that is not occupied by the screen insets (taskbar, OS menubar)`

However, I'm not seeing such behavior.

![image](https://user-images.githubusercontent.com/10091092/145205815-ff526c0f-4c77-4777-993a-a6a7f5fc0387.png)

With the following code:
```kt
 val windowState = rememberWindowState(
      position = WindowPosition.Aligned(Alignment.BottomEnd),
      width = Dp.Unspecified,
      height = Dp.Unspecified,
  )
    
Window(
    state = windowState,
    undecorated = true,
    resizable = false,
    focusable = true,
    alwaysOnTop = true,
    onCloseRequest = {},
) {
    Box {
        Column {
            Text("test1")
            Text("test2")
            Text("test3")
            Text("test4")
        }
    }
}
```

Tried messing with all those attributes as well as removing the `Box`, but nothing seems to change this.

**Comment by LegendL3n** [comment]
Just saw #1553, but I think this needs a different solution/workaround

**Comment by AtriusX** [comment]
I wrote up a quick workaround that might be helpful for you:
```kt
@Composable
fun ComposeWindow.subtractInset() {
    LaunchedEffect(Unit) {
        val inset = Toolkit.getDefaultToolkit().getScreenInsets(Frame().graphicsConfiguration)
        val size = Toolkit.getDefaultToolkit().screenSize.apply {
            // Only one side will have an inset at any point in time, all others remain at 0
            // We need to find the one side that has it and apply it to the appropriate dimension
            width -= max(inset.left, inset.right)
            height -= max(inset.top, inset.bottom)
        }
        val rangeX = 0 .. size.width
        val rangeY = 0 .. size.height
        // Works when taskbar is on top or left of screen
        if (x !in rangeX || y !in rangeY)
            setLocation(
                x.coerceIn(rangeX),
                y.coerceIn(rangeY)
            )
        // Works for when taskbar is on right or bottom of screen
        if (x + width !in rangeX || y + height !in rangeY)
            setLocation(
                (x + width).coerceIn(rangeX) - width,
                (y + height).coerceIn(rangeY) - height
            )
    }
}
```
The function is fairly long but it should fix the problem you're having and also cover alignment for all alternative taskbar layouts as well. Just call `window.subtractInset()` within your application's `FrameWindowScope` to use it.

**Comment by LegendL3n** [comment]
Yea it did solve, thanks!

I had tried that something like that, guess I was missing the `LaunchedEffect` 😅

**Comment by AtriusX** [comment]
Might want to keep the issue open for now since it references a bug that still exists in the library. What I gave you only works as a workaround for the time being. 🙂

**Comment by LegendL3n** [comment]
Yeah right 😅

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6037">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
