### ISSUE TITLE
The content will be deformed when I change the size of the window 

### ISSUE THREAD

**Issue by LvQGit** [JetBrains/compose-multiplatform#1570]
![image](https://user-images.githubusercontent.com/50766599/145508245-b7a04a28-74a5-4682-ac24-9c9cfa7ade0f.png)
![image](https://user-images.githubusercontent.com/50766599/145508287-3a141530-0c87-4981-9683-7c88c3e3ac02.png)
![image](https://user-images.githubusercontent.com/50766599/145508312-9df958a6-178c-4e91-aa0c-92ee0c94e1f9.png)

OS : Windows 7

**Comment by akurasov** [comment]
Could you please share your code, so we can reproduce it locally? Ideally-minimal snippet.

**Comment by LvQGit** [comment]
> Could you please share your code, so we can reproduce it locally? Ideally-minimal snippet.

I just cloned the examples project [notepad](https://github.com/JetBrains/compose-jb/tree/master/examples/notepad) and did not change any code.

**Comment by akurasov** [comment]
I see, thank you. Let me try it. BTW, do you have x86 or x64?

**Comment by LvQGit** [comment]
Thanks, I only tried it on Windows 7 x64. 

Sorry for my bad English, I might understand something wrong.

**Comment by akurasov** [comment]
Everything is fine) Last question - which JDK do you use?

**Comment by LvQGit** [comment]
Tried both openjdk 16 and openjdk 15

**Comment by LvQGit** [comment]
I tried it on two other Windows 7 computers. One works, the other cannot be opened at all. It seems that it can be opened after updating the universal [CRT](https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c), not sure if it is because of the update. 

For this issue, Is there also a problem with a runtime library installed, or what library should I install to run the project?

**Comment by LvQGit** [comment]
It was solved by adding the code `System.setProperty("skiko.renderApi", "SOFTWARE_FAST")`.

I tried DIRECT3D or OPENGL, but they didn't work properly on my computer.

**Comment by akurasov** [comment]
Yesterday I also tried it. I saw the following behavior - if I resize the image fast, it was indeed deformed, but only until the image was redrawn.  

>I tried DIRECT3D or OPENGL, but they didn't work properly on my computer.
Both deform the window content at resizing?

**Comment by LvQGit** [comment]
Yes, both of them deformed.

The console will print `Failed to create DirectX12 device.`
And the click position is correct, but the rendering position is incorrect. 

![iss](https://user-images.githubusercontent.com/50766599/146342632-0bef7782-f740-4b5c-bfa2-22d79fc7c233.gif)

**Comment by akurasov** [comment]
We will take a look at it further after NY, when Roman is back from vacation.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1570">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
