### ISSUE TITLE
[desktop] package.cfg contains unwanted classpath

### ISSUE THREAD

**Issue by Omico** [JetBrains/compose-multiplatform#1578]
### **Notice: This happened in every Compose desktop app, and it shouldn't exist in any release version.**

After generating a native distribution, it will create a [packageName].cfg in `build\compose\binaries\main\app\[packageName]\app`, which contains a source code real path.
For example, for `compose-jb\examples\todoapp\desktop`, In my PC, the project is in `E:\Git\JetBrains\compose-jb`.
It will generate `compose-jb\examples\todoapp\desktop\build\compose\binaries\main\app\ComposeDesktopTodo\app\ComposeDesktopTodo.cfg`
![image](https://user-images.githubusercontent.com/14316223/145726286-4aa46a97-8b13-4117-8f41-b13ddc6d4edf.png)

### We can also see @theapache64 's `stackzy`

After install [Stackzy-1.1.1.msi](https://github.com/theapache64/stackzy/releases/download/1.1.1/Stackzy-1.1.1.msi)

![image](https://user-images.githubusercontent.com/14316223/145726669-6e7a2767-a6b8-4fca-8269-e2ca64daa75d.png)

### Or my project [genshin-imapct-server-switcher.zip](https://github.com/Omico/genshin-impact-server-switcher/releases/download/v1.0.0/genshin-imapct-server-switcher.zip)

![image](https://user-images.githubusercontent.com/14316223/145726914-18994506-28c7-4dee-9be7-ecbe477bbc80.png)

**Comment by AlexeyTsvetkov** [comment]
Fixed in 8d78c4ac67b3e6e6492e7068291727b9e6bba8ae

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1578">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
