### ISSUE TITLE
Best practices to include emojis in text

### ISSUE THREAD

**Issue by ialokim** [JetBrains/compose-multiplatform#1579]
We are currently trying to display emojis within `Text` and `TextField`. We would like to make sure our application looks the same across different systems, but the amount and type of emojis supported by the default font is heavily system-dependant, Therefore, we tried different color emoji fonts, namely [OpenMoji](https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/font/OpenMoji-Color.ttf) (which is however displayed as black-and-white glyphs in Compose instead) and [NotoEmoji](https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf) (which works well on several Linux systems, leads to a crash on macOS and renders with strange aliasing on Windows). One disadvantage of both fonts is that they _only_ include emojis and no other characters.

We are wondering now what would be the best approach to support emojis in Text using Compose for Desktop:
- Is there a way to define a "fallback" font, i.e., a font that is used for all characters that don't exist in the color emoji fonts?
- Would it be sensible to try to merge the emoji font file with another font to support both emojis and normal text within the same TTF file? If so, has anyone any tips about tools etc that could help us here?
- Should we go the way used e.g. in Android by third-party libraries as [this one](https://github.com/vanniktech/Emoji) and don't use an emoji font, but replace all emojis with images in an `AnnotatedString`? Would that also work for `TextField`s?

Also, we couldn't find information about which [type of color font](https://www.colorfonts.wtf/#section2) should at all be supported by Compose for Desktop or the underlying rendering engine. Why are OpenMojis rendered black-and-white while NotoEmojis are displayed with colors?

**Comment by prepor** [comment]
Hi! Thank you for good questions!

> Is there a way to define a "fallback" font, i.e., a font that is used for all characters that don't exist in the color emoji fonts?

It looks like it's missing part of Compose API, I asked google folks in internal Slack about it. SkiaParagraph supports it, I even made a prototype.

> Would it be sensible to try to merge the emoji font file with another font to support both emojis and normal text within the same TTF file? If so, has anyone any tips about tools etc that could help us here?

It should work but I can't give any tips about it, sorry :)

> Should we go the way used e.g. in Android by third-party libraries as this one and don't use an emoji font, but replace all emojis with images in an AnnotatedString? Would that also work for TextFields?

It should work with `Text` via `inlineContent` but TextField doesn't have the support of it.

> Also, we couldn't find information about which type of color font should at all be supported by Compose for Desktop or the underlying rendering engine. Why are OpenMojis rendered black-and-white while NotoEmojis are displayed with colors?

We are using SkiaParagraph to render text. How exactly it renders fonts depends on OS.

**Comment by ialokim** [comment]
> It looks like it's missing part of Compose API, I asked google folks in internal Slack about it. SkiaParagraph supports it, I even made a prototype.

Hi @prepor did you get any reactions over there?

**Comment by YektaDev** [comment]
Any updates?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5136">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
