### ISSUE TITLE
Material3 button not found

### ISSUE THREAD

**Issue by dragossusi** [JetBrains/compose-multiplatform#1582]
I added material 3 succesfully in my app, and most of the widgets work, but the `Button` widget is nowhere to be found.

Material3 `Text`, `Icon`, `IconButton`, `Scaffold` and `TopAppBars` work, but I can't import `material3.Button`, only `material.Button` works

**Comment by YoshiRulz** [comment]
Also `Switch` (renamed `SwitchMaterial`?). Per https://github.com/JetBrains/compose-jb/pull/1390#issue-1052375115 it was intentionally added without all the components.

**Comment by dragossusi** [comment]
Material 3 navigation bar is not working either

**Comment by jakobkmar** [comment]
The only problem here is that the material3 dependency exposed by compose-jb is very old, while `1.0.0-alpha02` is already around and all documentation is made for that version. It just has to be updated.

**Comment by dragossusi** [comment]
@jakobkmar is this a bug for AndroidX repository?

**Comment by jakobkmar** [comment]
@dragossusi you can see the state of Material 3 compose-jb is [currently using here](https://github.com/JetBrains/androidx/tree/bc4f98ccbba27171f1bc419f2fb5b920401bc781/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3) while the origin repo already [has a lot more components](https://github.com/androidx/androidx/tree/androidx-main/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3). This is not really a bug, it is just behind.

**Comment by dragossusi** [comment]
Update: `Button` is now available with material 3 in jetbrains compose `1.1.0-alpha02`.

Thank you!

**Comment by akurasov** [comment]
@igordmn should we close it?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5133">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
