### ISSUE TITLE
TargetFormat.Pkg build fails

### ISSUE THREAD

**Issue by sergeych** [JetBrains/compose-multiplatform#1594]
MacOS building native distribution in pkg format fails. Error is reported by jpackage: 

    Bundler Mac PKG Package skipped because of a configuration problem: "Missing --main-jar parameter for non modular application

(file ./build/compose/logs/packagePkg/jpackage-2021-12-14-19-10-24-err.txt)

**Comment by gabrielpaim** [comment]
Any updates on this? I'm also having this issue. Using jpackage directly works, though (jdk17.0.2).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5129">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
