### ISSUE TITLE
[Web app] Syntax to embed video, audio, pdf into web application

### ISSUE THREAD

**Issue by antranvn** [JetBrains/compose-multiplatform#1595]
Hi guys, 
I know that the tutorial and document are limited at the moment.
Please add references on how to add video, audio, pdf HTML into the web app.
The Div, Text, Button is simple and easy to add, but video, audio, pdf ... is quite vague in term of syntax.
Thank you

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5128">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
