### ISSUE TITLE
Icon with ImaveVector breaks Preview

### ISSUE THREAD

**Issue by mnonnenmacher** [JetBrains/compose-multiplatform#1598]
If an `Icon` is initialized with an `ImageVector` the preview fails to render the result. Also other previews do not work anymore until the IDE is restarted. This can be reproduced with the following code snippet and the Compose Desktop Application template:

```kotlin
@Composable
@Preview
fun App() {
    MaterialTheme {
        Icon(Icons.Filled.Settings, "Settings")
    }
}
``` 

As a workaround this works, even though the `Icon` function does also call `rememberVectorPainter` if called with an `ImageVector`:

```kotlin
@Composable
@Preview
fun App() {
    MaterialTheme {
        val settings = rememberVectorPainter(Icons.Filled.Settings)
        Icon(settings, "Settings")
    }
}
```

I have tested this with versions `1.0.0` and `1.0.1-rc2` of the Compose plugin and IntelliJ IDEA Community Edition 2021.3 on Windows 10.

**Comment by mnonnenmacher** [comment]
The mentioned workaround only works for the simple example, even with it the preview often breaks and requires an IDE restart.

This seems to be related to #1221.

**Comment by sphrak** [comment]
I have the same issue but I was not able to get it to work via `Icon` and painter

```
IntelliJ IDEA 2021.3 (Community Edition)
Build #IC-213.5744.223, built on November 27, 2021
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.16.0-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins:
    org.toml.lang (213.5744.224)
    org.jetbrains.kotlin (213-1.6.10-release-923-IJ5744.223)
    org.jetbrains.compose.desktop.ide (1.0.0)
    com.suusan2go.kotlin-fill-class (1.0.11)
    com.squareup.sqldelight (1.5.3)

Kotlin: 213-1.6.10-release-923-IJ5744.223
Current Desktop: GNOME
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5126">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
