### ISSUE TITLE
Upload to Apple App Store (Universal macOS Binary required, signing issues)

### ISSUE THREAD

**Issue by Thomas-Vos** [JetBrains/compose-multiplatform#1599]
To be able to upload a Compose for Desktop app to the Apple App Store, there are multiple issues that need to be resolved.

- [ ] Universal macOS Binary (optional)
- [x] Signing for Mac App Store (required) #1613 
- [x] Fix TestFlight builds (optional) #1812

# Universal macOS Binary (optional)

To be able to support both Intel and ARM64 Macs natively, there needs to be a way to build a Universal pkg (Intel + ARM64). That is needed to be able to upload it to the Apple App Store. The only alternative for now is to upload an Intel-only app.

<img width="502" alt="Screenshot 2021-12-15 at 19 56 49" src="https://user-images.githubusercontent.com/11077217/146248046-e7b19ec7-ba1e-4167-8590-eba5e6a231f1.png">

I tried adding both `compose.desktop.macos_arm64` and `compose.desktop.macos_x64` dependencies as suggested on Slack. However, the produced app is still not Universal. 

I am building the project on an M1 Mac with an ARM64 JDK. When doing a right click and get info on the produced `.app` it shows Apple Silicon instead of Universal.

Furthermore, I am not sure what to do about the bundled JRE. Would I need to include it twice (for Intel and for ARM64) or so?

Slack discussion: https://kotlinlang.slack.com/archives/C01D6HTPATV/p1639570539349100

Found some information on this here: https://bugs.openjdk.java.net/browse/JDK-8266259

**Comment by Thomas-Vos** [comment]
Just wanted to add that it is not technically mandatory for the AppStore, as I think you can still upload Intel only apps at this time. However, if you want the app to run natively on M1 Macs, you are required to build a Universal app with support for both architectures.

**Comment by Thomas-Vos** [comment]
I am working on support for the Apple App Store. Could use some guidance on this if possible. See #1613

**Comment by Thomas-Vos** [comment]
Does anyone have any idea how to fix the univeral binary issue? Intel and ARM64 in one binary.

**Comment by Thomas-Vos** [comment]
It is now possible to upload apps to the App Store now that https://github.com/JetBrains/compose-jb/pull/1613 is merged. However, TestFlight is not working and universal binaries are not supported. Any suggestions?

**Comment by Thomas-Vos** [comment]
I opened a TSI with Apple and am working with them to get the TestFligth issues resolved. They were able to provide me with more detailed error message, so I am working on that.

Already opened some PRs with other related fixes: #1797, #1798, #1799

**Comment by Thomas-Vos** [comment]
Got TestFlight working thanks to Apple's help with the remaining errors. See #1812.

<img width="641" alt="Screenshot 2022-02-08 at 17 35 20" src="https://user-images.githubusercontent.com/11077217/153032614-836ec681-cb3c-4f43-81b0-0db6e073ad61.png">

**Comment by akurasov** [comment]
@Thomas-Vos is there anything left for this task?

**Comment by akurasov** [comment]
I think these are a bit different issues. What you are saying - we need to publish Skiko and Compose for MacOS M1, right?

**Comment by Thomas-Vos** [comment]
Apple approved my Compose app for the Mac App Store: https://apps.apple.com/app/id1462943921

TestFlight builds are also working great. Now all that is missing is a universal build so that M1 is supported natively.

**Comment by kenyee** [comment]
This complicates builds too...e.g., M1 Mac Minis are typically used in CI, but we can't built an Intel binary on those.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5125">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
