### ISSUE TITLE
Changing window icon does not work

### ISSUE THREAD

**Issue by brolicious12** [JetBrains/compose-multiplatform#1600]
when I click the button in the example below, the icon is not changed. Am I doing something wrong or is it a bug? 

```
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AccountBox
import androidx.compose.material.icons.filled.BrokenImage
import androidx.compose.runtime.mutableStateOf
import androidx.compose.ui.graphics.vector.rememberVectorPainter
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

val windowIcon = mutableStateOf(Icons.Filled.AccountBox)

fun main() = application {
	Window(onCloseRequest = this::exitApplication,
	       icon = rememberVectorPainter(windowIcon.value)) {
		Button(onClick = {
			windowIcon.value = Icons.Filled.BrokenImage
		}) {
			Text("Change icon to BrokenImage")
		}
	}
}
```

```
id("org.jetbrains.kotlin.jvm") version ("1.6.10")
id("org.jetbrains.compose") version ("1.0.1-rc2")
```

**Comment by brolicious12** [comment]
@Kanialdo thanks for the effort but unfortunately it doesn't work with your example either

**Comment by AnonymousGeekDev** [comment]
Please @brolicious12 did you try making `windowIcon` a `var` ?

**Comment by brolicious12** [comment]
`val windowIcon` as far as I understand is itself just an object that holds the state (`windowIcon.value`). I don't change the object, so it doesn't have to be var (although I tested it with var too, it doesn't work).

**Comment by AnonymousGeekDev** [comment]
@brolicious12 Please did you try using delegation with the `by` keyword? That is, `val windowIcon by remember { `

**Comment by brolicious12** [comment]
@AnonymousGeekDev I tried it but it didn't work either, I would be surprised if it worked that way and not the other way around

**Comment by shenliuyang** [comment]
rememberVectorPainter fun always return the same instance, even argument changed. 
I use pre allocate icons.  it'work
`
var titleState = mutableStateOf("new")
var iconIndex = mutableStateOf(1)
fun main() = application {

    var icons = listOf(rememberVectorPainter(Icons.Filled.AccountCircle), rememberVectorPainter(Icons.Filled.Call))


    Window(onCloseRequest = this::exitApplication, icon = icons[iconIndex.value % icons.size], title = titleState.value) {
        Button(onClick = {
            iconIndex.value++
        }) {
            Text(titleState.value)
        }
    }
}`

**Comment by AnonymousGeekDev** [comment]
@shenliuyang cool!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5124">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
