### ISSUE TITLE
FR: Add support for running R8 on JVM Desktop

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-multiplatform#1604]
The performance benefits for R8 and Compose on Android is significant (supposedly because of its optimizations of Lambdas). I recently found out that [R8 can just be run on Java class files](https://github.com/JakeWharton/dependency-tree-diff/blob/trunk/build.gradle#L45-L63). It'd be nice to be able to add support to use R8 directly from the compose Gradle plugin on Compose Desktop projects, so that people can easily take advantage of the performance improvements on Compose Desktop.

**Comment by Thomas-Vos** [comment]
Would love to see R8 support for code obfuscation. This is currently blocking me from publishing my app.

**Comment by ScottPierce** [comment]
@Thomas-Vos look at the link I posted where a gradle project has a task to run r8 on it.

You should be able to do it yourself in 30 minutes or so:
1. Use the [Shadow Jar Gradle plugin](https://github.com/johnrengelman/shadow) to create an Uber / Fat Jar. This is a jar that contains all your other Jar files.
2. Run R8 on it similar to my above link
3. Swap out your jar files in your packaged application with the newly optimized / obfuscated single jar file. There is also a text file that lives alongside the jar files that define the running classpath. Edit it to remove all the jar files from the classpath, and ensure your optimized fat jar is the only jar in that file now.

**Comment by mcpiroman** [comment]
@ScottPierce Is there a way to run R8 selectively on jars e.g. not to obfuscate (certain) third-parties instead of user-jar way?

This has to be somewhat easily hackable to achieve that, just the 30 minutes was not enough for me with my gradle-fu.
Generally we would all appreciate if one would share sample gist gradle.kts file for CfD app so that we don't have to arrive to the same solution independently 🙏 .

**Comment by ScottPierce** [comment]
R8 has similar functionality and accepts the same configs as Proguard. You can tell it to ignore certain packages.

**Comment by mcpiroman** [comment]
I finally managed to do that with ProGuard ([example setup](https://gist.github.com/mcpiroman/cf511c5f9312a59e8f821706738eeab3)), without uberjar though. It's actually not *that* hard. I guess it should be similar for R8.

**Comment by ScottPierce** [comment]
No uber jar has benefits imo. While doing updates, that would allow you to only swap out the file that's been changed. Uber jars with compose can be 50+ MB

**Comment by ScottPierce** [comment]
Another point that was brought up about R8 - R8 has the ability to read rules directly from jars, meaning that its a significantly better user experience to build a library ecosystem with.

**Comment by mipastgt** [comment]
Taking into account all the recent problems with ProGuard, e.g.,
https://github.com/JetBrains/compose-multiplatform/issues/3387
https://github.com/JetBrains/compose-multiplatform/pull/3408#discussion_r1274012736
https://github.com/square/okio/issues/1298
it may be worthwile to reconsider supporting R8 on desktops again.

**Comment by YektaDev** [comment]
Dropping [this tweet](https://twitter.com/YektaDev/status/1647904429880889345) here. It might be useful.

**Comment by gogopro-dev** [comment]
bump

**Comment by JakeWharton** [comment]
Compose Desktop seems to be speed-running the problems of Android from a decade past by not using R8.

https://github.com/Kotlin/kotlinx.coroutines/issues/4025

**Comment by mikedawson** [comment]
I think right now the biggest problem is that whilst the Compose/Desktop documentation states that proguard is supported it is not really being fully used even on official-ish examples. Even if rules are not auto-bundled, just enabling proguard (including obfuscation) for release jvm builds would uncover many (if not most) issues.

**Comment by ellet0** [comment]
> Another point that was brought up about R8 - R8 has the ability to read rules directly from jars, meaning that its a significantly better user experience to build a library ecosystem with.

While Proguard doesn't have this functionality built-in, it should be easy to implement, use `JarFile` to read the fat JAR file, you will usually find the rules of the supported libraries in `META-INF/proguard`

Which will be included by libraries even if you don't use Proguard. 

This approach is less flexible and could produce issues later. For most use cases and projects, it works as expected.

Unless I'm mistaken, R8 uses the rules from `META-INF/com.android.build.tools/r8` or fallback to `META-INF/proguard`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5121">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5121">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5121">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
