### ISSUE TITLE
CSS API: Deprecate style invocation in CSS queries

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-multiplatform#1610]
Following code generates exactly the same CSS:

```kotlin

val cls by style {
                (self + hover)  {
                    color(rgb(10, 20, 30))
                }
        }
        
val cls by style {
                (self + hover)  style {
                    color(rgb(10, 20, 30))
                }
        }        
```

In this issue we are not consider here the selectors API itself (in this case, the `self + hover`) - the goal of this task would be to deprecate second syntax, with style since it actually doesn't provide any technical or usability benefits compared to the first syntax.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5118">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
