### ISSUE TITLE
Preview doesn't work with falling-balls example

### ISSUE THREAD

**Issue by DragonKnightOfBreeze** [JetBrains/compose-multiplatform#1634]
'Cause: java.net.URLEncoder.encode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String;' when execute task 'configureDesktopPreview'

When try to preview a compose project ([falling-balls](https://github.com/JetBrains/compose-jb/tree/master/examples/falling-balls)) in my computer, it occurs an error

![image](https://user-images.githubusercontent.com/34092666/147240306-867cbe99-9476-4234-a61b-58f930cccaae.png)

Run / debug this compose project is OK, just preview.

![image](https://user-images.githubusercontent.com/34092666/147240534-714d508b-971d-48de-9e28-d4694ac8acc7.png)

**Comment by olonho** [comment]
Seems you use pre 10 JDK, and method above was added in it: https://docs.oracle.com/javase/10/docs/api/java/net/URLEncoder.html
Use more recent JDK.

**Comment by kirin521** [comment]
I got this problem too. you can try to change the gradle sdk in settings->gradle->Gradle Jvm  to 11.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5099">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
