### ISSUE TITLE
[Web App] How can I add display markup text

### ISSUE THREAD

**Issue by antranvn** [JetBrains/compose-multiplatform#1646]
Hello guys, how can I display markup text? Can we use tag or inline style for `innerHTML`?

**Comment by koyakei** [comment]
import androidx.compose.runtime.*
import org.jetbrains.compose.web.dom.*
import org.jetbrains.compose.web.renderComposable
import kotlinx.browser.document
import org.w3c.dom.HTMLElement

fun main() {
    renderComposable(rootElementId = "content") {
        Div {
            Button(attrs = {
                onClick {
                    val contentDiv = document.getElementById("content") as HTMLElement
                    contentDiv.innerHTML = "<h1>Hello, Compose Multiplatform!</h1><p>This is an example of using innerHTML.</p>"
                }
            }) {
                Text("Click me")
            }
        }
    }
}

Is it ok?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5095">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
