### ISSUE TITLE
BasicTextField cursor width or height cannot be customised

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-multiplatform#1669]
When setting the cursor for `BasicTextField`, we can provide `SolidColor` or some _"gradients"_ as input to the `cursorBrush` parameter. However, we cannot configure the width or height of the `cursorBrush`.

We're working with `1.0.0-rc3` right now, which was pretty recent. And when we look at our dependency of `CoreTextField.kt`, we can see that the width of the cursor is provided by an `expected DefaultCursorThickness`, which is defined by an `actual DefaultCursorThickness` in `TextFieldCursor.desktop.kt`. Looks like this is something that should not be hardcoded in this way? Is it possible to make `DefaultCursorThickness` to be configurable?

**Comment by vovahost** [comment]
When can this be fixed? I want to set increase the cursor width because the default width makes the cursor very hard to notice.

**Comment by dima-avdeev-jb** [comment]
Do you need this feature for Desktop Compose application?

**Comment by haikalpribadi** [comment]
Well, yes. It's a library available to use for Desktop Compose, so it should be made to work properly. Regardless of where it's used, I doubt hard-coded values for things that should be configurable is appropriate in any case. @dima-avdeev-jb

**Comment by Nohus** [comment]
I need this for a Compose Desktop application. Are there plans to make the thickness configurable?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1669">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
