### ISSUE TITLE
BasicTextField cursor information on line number

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-multiplatform#1671]
When using `BasicTextField` the only callback we can use to respond to the user's cursor activity, is through `onValueChange`, which emits `TextFieldValue`, which contains `selection: TextRange` information. This provides us information of `start` and `end` position of the cursor selection (which may be collapsed as one position). However, these positions are relative to the entire length of the string. 

Would it be possible to provide an extra field for us to access: `lineNumber` ? 

Without this field, we have to compute it ourselves by splitting the string by new lines, which is not very efficient. Meanwhile, I believe this is information that you already have internally in the library, given the fact that `onLayoutTextLayout` already emits `TextLayoutResult` which contains `lineCount` information -- which means you already had to parse the text internally.

**Comment by akurasov** [comment]
@jimgoog WHYT?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1671">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
