### ISSUE TITLE
BasicTextField registers tab key as one character white space

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-multiplatform#1672]
When you hit `tab` in multiline `BasicTextField`, the text input only registers one character whitespace. Is this a bug? How can we configure this?

**Comment by akurasov** [comment]
Am I correct, that it behave differently in another inputs?

**Comment by haikalpribadi** [comment]
Can you elaborate on what you mean by "differently in another inputs", @akurasov ? Every other input from the keyboard seems to work fine so far.

**Comment by akurasov** [comment]
I mean, have you checked if common TextField behaves differently?

**Comment by taodongl** [comment]
If you want to implement editor of customized DSL, I feel scintilla library is good for you, which could support "tab stops".
Refer to: https://www.scintilla.org/ScintillaDoc.html#TabsAndIndentationGuides

**Comment by haikalpribadi** [comment]
I haven't had a chance to test, @akurasov, but it seems like the most natural expectation, given that we're still registering the `\t` character, that we should show more than one white space.

@taodongl I would love to use a library and not have to build one myself, but all the available libraries are all so outdated, ugly, archaic, and doesn't play nice with the new Compose declarative paradigm. I'd love to see a Text Editor library built by the Compose Desktop team!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1672">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
