### ISSUE TITLE
Missing ExposedDropdownMenuBox composable

### ISSUE THREAD

**Issue by jakobkmar** [JetBrains/compose-multiplatform#1673]
The desktop implementation for menus is missing the `ExposedDropdownMenuBox` composable. Additionally, all classes related to exposed dropdown menus are missing as well, including the important `ExposedDropdownMenu` and `ExposedDropdownMenu.TrailingIcon` classes.

**Comment by jakobkmar** [comment]
It is currently only available in the androidMain module: https://github.com/androidx/androidx/blob/androidx-main/compose/material/material/src/androidMain/kotlin/androidx/compose/material/ExposedDropdownMenu.kt

**Comment by mahozad** [comment]
Also, see https://github.com/JetBrains/compose-jb/issues/2037#issuecomment-1132020917

**Comment by mahozad** [comment]
[The issue on Google IssueTracker](https://issuetracker.google.com/issues/201051696) was marked **`Won't fix`** with this message:
> Please track the JetBrains bug on this as we do not have work planned here

So, is there any time estimate on when this is going to be implemented?

**Comment by eygraber** [comment]
It looks like the Android version has some dependencies on the View system so it's not just a case of moving it to common; it has to be ported.

**Comment by helmysaeed** [comment]
ExposedDropdownMenuBox is missing even  in release 1.3  we have been waiting for this  component for a long time 
we need to search in DropdownMenu with  keyboard navigation

**Comment by Tiebe** [comment]
@igordmn, any updates on this?

**Comment by lightdev-top** [comment]
> @igordmn, any updates on this?

i writen one
https://gist.github.com/lightdev-top/4f42c4d20d975e077853d0859e976c40

**Comment by sizoune** [comment]
> > @igordmn, any updates on this?
> 
> i writen one https://gist.github.com/lightdev-top/4f42c4d20d975e077853d0859e976c40

unresolved reference:fastAll 
compose v1.4.0

**Comment by lightdev-top** [comment]
> > > @igordmn, any updates on this?
> > 
> > 
> > i writen one https://gist.github.com/lightdev-top/4f42c4d20d975e077853d0859e976c40
> 
> unresolved reference:fastAll compose v1.4.0

sorry i forgot it，i have updated it.😊

**Comment by helmysaeed** [comment]
> > > > @igordmn, any updates on this?
> > > 
> > > 
> > > i writen one https://gist.github.com/lightdev-top/4f42c4d20d975e077853d0859e976c40
> > 
> > 
> > unresolved reference:fastAll compose v1.4.0
> 
> sorry i forgot it，i have updated it.😊

????????????????

**Comment by lightdev-top** [comment]
> > > > > @igordmn, any updates on this?
> > > > 
> > > > 
> > > > i writen one https://gist.github.com/lightdev-top/4f42c4d20d975e077853d0859e976c40
> > > 
> > > 
> > > unresolved reference:fastAll compose v1.4.0
> > 
> > 
> > sorry i forgot it，i have updated it.😊
> 
> ????????????????

??????????????????????????????????????????

**Comment by helmysaeed** [comment]
> > > > > > @igordmn, any updates on this?
> > > > > 
> > > > > 
> > > > > i writen one https://gist.github.com/lightdev-top/4f42c4d20d975e077853d0859e976c40
> > > > 
> > > > 
> > > > unresolved reference:fastAll compose v1.4.0
> > > 
> > > 
> > > sorry i forgot it，i have updated it.😊
> > 
> > 
> > ????????????????
> 
> ??????????????????????????????????????????

In which version we can find this "ExposedDropdownMenuBox for Compose Multiplatform"

**Comment by lightdev-top** [comment]
> > > > > > > @igordmn, any updates on this?
> > > > > > 
> > > > > > 
> > > > > > i writen one https://gist.github.com/lightdev-top/4f42c4d20d975e077853d0859e976c40
> > > > > 
> > > > > 
> > > > > unresolved reference:fastAll compose v1.4.0
> > > > 
> > > > 
> > > > sorry i forgot it，i have updated it.😊
> > > 
> > > 
> > > ????????????????
> > 
> > 
> > ??????????????????????????????????????????
> 
> In which version we can find this "ExposedDropdownMenuBox for Compose Multiplatform"

Add the code from the link I posted earlier to your project. 😋

**Comment by helmysaeed** [comment]
> > > > > > > > @igordmn, any updates on this?
> > > > > > > 
> > > > > > > 
> > > > > > > i writen one https://gist.github.com/lightdev-top/4f42c4d20d975e077853d0859e976c40
> > > > > > 
> > > > > > 
> > > > > > unresolved reference:fastAll compose v1.4.0
> > > > > 
> > > > > 
> > > > > sorry i forgot it，i have updated it.😊
> > > > 
> > > > 
> > > > ????????????????
> > > 
> > > 
> > > ??????????????????????????????????????????
> > 
> > 
> > In which version we can find this "ExposedDropdownMenuBox for Compose Multiplatform"
> 
> Add the code from the link I posted earlier to your project. 😋

The main issue still exists you can not filter the menu  by textfiled  because the menu blocks the  texfiled

**Comment by Tiebe** [comment]
@helmysaeed, please don't spam the issue with `???`

**Comment by MatkovIvan** [comment]
We are tracking this in more generic thread - #2037
I know, this issue was opened first, but let's track it in #2037 instead. Closing this as "duplicate"

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1673">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
