### ISSUE TITLE
Is there a way to make Composable view always above the SwingPanel?

### ISSUE THREAD

**Issue by llhbadboy** [JetBrains/compose-multiplatform#1674]
Is there a way to make Composable view always above the SwingPanel? I'm working on a 3D application which using Swing Canvas to draw the 3D, but all the Composable view is covered by the Swing Canvas.
![16417951152167](https://user-images.githubusercontent.com/1784401/148724799-79d5c009-f126-44d8-80e5-a4673185f4e9.png)

**Comment by yaroslavkulinich** [comment]
@llhbadboy I'm tracking the progress regarding this feature (have added a similar issue). As I understand it will be implemented in the 1.1.0 milestone (ongoing).

**Comment by llhbadboy** [comment]
> 

@yaroslavkulinich Thanks for telling me that. 
And do you know when the 1.1.0 milestone will be released？

**Comment by llhbadboy** [comment]
It's not fixed in the 1.1.0 release.

**Comment by akurasov** [comment]
Have you checked swing tutorials? I guess they cover most of the use cases

**Comment by yaroslavkulinich** [comment]
@llhbadboy 
It was fixed in 1.1.0.
Check Swing Interop tutorial.

**Comment by llhbadboy** [comment]
@yaroslavkulinich @akurasov 
Thank you, guys.
But I think the tutorial just let me not use the SwingPanel at this situation. My case is using Tooltips, and it cut off by the SwingPanel.

Quote the Swing Interop tutorial:
Below you can find several cases where the use of SwingPanel is justified:

there are no popups, tooltips, context menus, etc. in your application. or they are not used inside your SwingPanel
in your application, the SwingPanel will always be in the same position. This will reduce the risk of glitches and artifacts when changing the position of the Swing component (this condition is not mandatory and you need to test each such case separately)

**Comment by akurasov** [comment]
@llhbadboy it is restriction of the architecture and it doesn't seem feasible to change. At least I don't see how. If, looking at explanation, you have any ideas, please share them.

**Comment by Kalkulu** [comment]
+1, is there any workaround for this right now? I've tried to put a DropdownMenu within a ComposePanel within a SwingPanel and it doesn't work.

**Comment by MatkovIvan** [comment]
Fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/915 (under the flag).

Please note that drawing above GPU views has a bit more limitations because it requires blending on OS side that might not be supported in some cases

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1674">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
