### ISSUE TITLE
Introduce SVG-context-agnostic attribute builders for most common attributes in SVG

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-multiplatform#1676]
As of one has nothing to do other than writing code as follows:

```
        Circle(200f, 200f, 0.5f * radius.value, attrs = { attr("fill", rgbColor()) })

```
While fill, for instance, is a very common attribute used literally almost anywhere in SVG.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1676">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
