### ISSUE TITLE
Implement isSystemInDarkTheme for desktop

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#169]
In Android target we can know if the system is in a dark mode using androidx.compose.foundation.isSystemInDarkTheme.

Probably we can implement it for desktop too. Some OS'es support dark mode.

P.S. if we will implement it, we should define "expect fun isSystemInDarkTheme" in the common code.

**Comment by tkuenneth** [comment]
Would bei a great addition.

**Comment by GGorAA** [comment]
yea

For now using the same code for android and desktop for light and dark theme result to an error "Unresolved reference"
![image](https://user-images.githubusercontent.com/61655029/101237553-7a761580-36e2-11eb-8707-78679dad4298.png)

**Comment by GGorAA** [comment]
I agree. Will be very useful :D

**Comment by GGorAA** [comment]
Where we can track the progress of implementing `isSystemInDarkTheme()`?

**Comment by akurasov** [comment]
@igordmn, am I correct that isSystemInDarkTheme is working for desktop now?

**Comment by igordmn** [comment]
It works, but we still need to:
1. support Linux (Ubuntu at least)
2. observe theme changing

**Comment by rylexr** [comment]
Any progress on this? I tried it on MacOS, Ubuntu, and Windows and it's not working.

**Comment by long76** [comment]
look at this https://github.com/Dansoftowner/jSystemThemeDetector
