### ISSUE TITLE
Composable operator invoke

### ISSUE THREAD

**Issue by InsanusMokrassar** [JetBrains/compose-multiplatform#1692]
* Kotlin: `1.6.10`
* Compose: `1.0.1`
* Platform: `Web`

Currently in case if you will create composable operator invoke function with an lambda and default value for it, you will get an error in runtime. For example:

```kotlin
sealed interface Example {
    operator fun invoke(
        attributesCustomizer: AttrBuilderContext<HTMLSpanElement> = {}
    ) {
        Span(
            {
                attributesCustomizer()
            }
        )
    }
    object Real: Example
}
```

In case of calling `Example.Real()` I am getting an error like `attributesCustomizer is not defined` in runtime web console

**Comment by akurasov** [comment]
As far as I remember, composable operators are not supported at the moment. Will check.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1692">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
