### ISSUE TITLE
Make TextFieldKeyInput and KeyMapping public

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-multiplatform#1695]
Would it be possible to make [TextFieldKeyInput](https://github.com/JetBrains/androidx/blob/jb-main/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/TextFieldKeyInput.kt) and [KeyMapping](https://github.com/JetBrains/androidx/blob/jb-main/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/KeyMapping.kt) public? These libraries would be very useful in creating custom text fields/editors, which we really need at the moment.

**Comment by akurasov** [comment]
@jimgoog WDYT? 
cc: @igordmn @olonho

**Comment by Kalkulu** [comment]
bump

**Comment by haikalpribadi** [comment]
TBH, we don't need this anymore, as we've implemented one ourselves. So, @akurasov, feel free to deprioritise it, but it seems @Kalkulu you need it. Perhaps you can explain to the Compose team your use case.

**Comment by akurasov** [comment]
@haikalpribadi do you use your own Compose fork?

**Comment by haikalpribadi** [comment]
No, we don't have a fork @akurasov . We just reimplemented few key libraries to fit our needs in our codebase.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1695">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
