### ISSUE TITLE
Horizontal scroll using MacBook Pro touch pad is laggy and not smooth

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-multiplatform#1702]
When horizontally scrolling a component using (specifically) the MacBook Pro **touch pad** (confirmed on multiple machines), you will find the movement to be laggy and not smooth. This problem does not exist when you use a proper mouse. Here's a minimal code to reproduce the problem:

```kotlin
Column(modifier = Modifier.width(400.dp).horizontalScroll(rememberScrollState())) {
    Text(text = "abc".repeat(1000))
    Text(text = "def".repeat(1000))
    Text(text = "ghi".repeat(1000))
    Text(text = "jkl".repeat(1000))
}
```

With the above code, the text is meant to overflow horizontally. Try to swipe horizontally on a MacBook Pro **touch pad**, at slow and medium/regular speed, and you will find it to be very laggy and not smooth. The problem does not occur when you swipe the touch pad at relatively high speed. The movement also does not occur when you use a proper mouse.

This behaviour doesn't seem to occur on other desktop or web application interfaces.

Can we look into what's causing this issue and get it improved?

**Comment by akurasov** [comment]
Could you please share a whole reproducer?

**Comment by haikalpribadi** [comment]
That was the whole reproduce, wrapping inside a simple `Window`, @akurasov.

**Comment by haikalpribadi** [comment]
Then just try scrolling left and right on the overflowing text, on MacBook Pro touch pad, and you'll see what I mean.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1702">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
