### ISSUE TITLE
Incorrect path for app image (in higher JDK versions?)

### ISSUE THREAD

**Issue by Thomas-Vos** [JetBrains/compose-multiplatform#1712]
When creating a pkg using `packagePkg` task, after installation on my Mac it is installed like this:
![image](https://user-images.githubusercontent.com/11077217/149996914-d280836c-fde9-45db-a344-d2b69767b711.png)

This is incorrect, should not be in a subfolder.

Maybe it's only for the newer JDK version, not sure. This was with JDK 17.

I originally found the issue while working on https://github.com/JetBrains/compose-jb/pull/1613. Because this bug would cause the build to fail completely in that case.

I added a workaround for building with `appStore = true`:

https://github.com/JetBrains/compose-jb/blob/ca382431c57f76e48ca27be531b3898879ae556b/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/tasks/AbstractJPackageTask.kt#L304-L309

However, the screenshot shown in this issue is without building for the app store, so the workaround should be extended to all build/packages.

Maybe it's only an issue for a certain JDK version. Not sure if any other platforms have this issue.

**Comment by Thomas-Vos** [comment]
@AlexeyTsvetkov

**Comment by realrubbish** [comment]
I am still experiencing this issue, when I install my application from the pkg file built with `buildPkg` it is installed into `/Applications/app/Myapp.app` subfolder instead of `/Applications/Myapp.app` (without `appStore = true`)

Is there a solution or a workaround?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1712">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
