### ISSUE TITLE
BUG :  Graphics layer 3D perspective matrix transformation is not properly applied to the object touch targets.

### ISSUE THREAD

**Issue by Condo-Colin** [JetBrains/compose-multiplatform#1718]
When a graphics layer has a 3D perspective matrix transformation applied, the visible object touch targets are not affected properly to match the rotated image.
When the graphics layer is rotated backwards using simple X axis rotation, the touch targets are also disconnected from the displayed object.

Conversation here on Slack with Romain Guy, Nader Jawad and George Mount:
https://kotlinlang.slack.com/archives/C01D6HTPATV/p163832377509490

![3D rotation clicking](https://user-images.githubusercontent.com/85348898/150133340-b28ecbf2-f862-47a6-a802-53224142d0c5.gif)
0

Thanks! Top product anyway Team.

**Comment by MatkovIvan** [comment]
It was solved in https://github.com/JetBrains/compose-multiplatform-core/pull/598 and will be available in next release.

Closing the issue. If it still the problem in your case please let us know
