### ISSUE TITLE
Make default menu bar items (file, edit, and so on)

### ISSUE THREAD

**Issue by voltangle** [JetBrains/compose-multiplatform#172]
Something like this:

![image](https://user-images.githubusercontent.com/61655029/101287784-2ad73d00-37fb-11eb-8663-c17cc809b286.png)

So you don't need to make every menu item from scratch by yourself.

**Comment by olonho** [comment]
Not sure if this is a feature request for Compose itself, guess creating library on top of Compose with such functionality is fully possible.

**Comment by GGorAA** [comment]
I think it can be a built-in feature of Compose for Desktop. It will be pretty useful, so you - again - don't need to write that functionality by yourself

**Comment by olonho** [comment]
We support building ecosystem around Compose, and feature like that seems good candidate for an extension library.

**Comment by GGorAA** [comment]
Well, without this feature I lose functionality to copy and paste text, minimise windows, go to fullscreen(on a Mac btw), and many more, without explicitly declaring the default menu items by myself. I need to manually create every menu item to make those basic functions work. I think that those "basic" menu items need to be right in the Compose, so we don't need to use an external library. That basic functionality needs to be in the core, by my opinion.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6385">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
