### ISSUE TITLE
How to close it when mouse click out of window

### ISSUE THREAD

**Issue by Citrussss** [JetBrains/compose-multiplatform#1725]
I want auto close a window ,when i click other place

**Comment by Citrussss** [comment]
i found a method 
`FrameWindowScope::window.addWindowFocusListener(windowFocusListener)`
but it means must working after when click the window

**Comment by akurasov** [comment]
Could you describe the scenario in full? 

You have an application consist of a single window. You want this window to be closed once it loses focus. What else is needed?

**Comment by Citrussss** [comment]
yes ,and also click any outside close the window

**Comment by akurasov** [comment]
Then what is the problem with windowFocusListener?

**Comment by Citrussss** [comment]
> Then what is the problem with windowFocusListener?

If a window has never been focused, then clicking on the outer area will not lose focus, and windowFocusListener will not callback（it's means should click inside of window ,then click outside）
