### ISSUE TITLE
combinedClickable consumes click event

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#1735]
`id("org.jetbrains.compose") version "1.0.0"`

I have an outer element that listens to click events via `clickable` and an inner element that listens to double click events via `combinedClickable`. If `combinedClickable` is used, the outer element does not receive the click events.

Code:
```
@OptIn(ExperimentalFoundationApi::class)
@Composable
fun CombinedClickableBug(){
    Box(
        modifier = Modifier
            .fillMaxSize()
            .clickable{
                println("Outer click")
            }
    ){
        Box(
            modifier = Modifier
                .fillMaxSize()
                .combinedClickable(
                    interactionSource = remember { MutableInteractionSource() },
                    indication = null,
                    onDoubleClick = {
                        println("Inner double click")
                    },
                    onClick = {
                        println("Inner click")
                    }
                )
        ){
            Text(
                text = "Click or double click me",
                modifier = Modifier.align(Alignment.Center)
            )
        }
    }
}
```

With the above code, clicking results in only "Inner click" being printed.
If `combinedClickable` is commented out, clicking prints "Outer click".

Note that unlike the other listeners, the `onClick` parameter in `combinedClickable` is not optional.

**Comment by akurasov** [comment]
In your example outer box is fully covered with the internal one. So click event is consumer by inner box and thus is not processed by clickable of the outer box. If you add padding to the inner box and click outer box itself, everything will work fine.

**Comment by m-sasha** [comment]
I understand that, but it's not the behavior I want. I want the outer box to respond to single click events and the inner one to respond to double click events.

Typically mouse events propagate up the hierarchy until they are consumed (like in AWT). `combinedClickable` appears to consume the (single-click) event, even though I didn't ask it (`onClick` is not optional, so I can't not provide it).

**Comment by akurasov** [comment]
I got it now. Yes, indeed currently it is not possible. We will discuss what could be done here, however I wouldn't expect that this will be corrected soon.

**Comment by igordmn** [comment]
Do you want exactly click for outer Box (Press + Release), or it is better to handle only Press?

Usually if component/components should handle double click and click simultaneously, the click should be delayed by 300ms. And that can cause some UX inconvenience.

Also handling click + double click on different components probably isn't easy to implement with the current internal implementation of events in Compose. Compose don't treat click as a real event. It don't pass click through widgets hierarchy, so we can't consume it. Compose treat only elementary events as real events (such as Press/Release). I am not saying it is right, only that it requires new concepts to support this case.

But even if we want to handle only Press, there is a bug in Compose:
```
    Box(
        modifier = Modifier
            .fillMaxSize()
            .pointerInput(Unit) {
                detectTapGestures(
                    onPress = {
                        println("Outer press")
                    }
                )
            }
    ){
        Box(
            modifier = Modifier
                .fillMaxSize()
                .pointerInput(Unit) {
                    detectTapGestures(
                        onDoubleTap = {
                            println("Inner double click")
                        }
                    )
                }
        ){
            Text(
                text = "Click or double click me",
                modifier = Modifier.align(Alignment.Center)
            )
        }
    }
```

As we can see, the first Press is consumed by double click handler, and the second is not consumed. It probably should be opposite - the first press shouldn't be consumed, and the second should be.

Also, it would be convenient, if we don't have to use `detectTapGestures`, and use `combinedClickable`. We should probably make `onClick` not required for that.

**Comment by m-sasha** [comment]
It is my understanding that currently I have to process AWT events myself if I want to detect press-only.

This is unfortunate, as some things (list item selection, for example) are typically done on mouse-press, not click. But that's somewhat unrelated to this ticket...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1735">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
