### ISSUE TITLE
Remove more AWT related code

### ISSUE THREAD

**Issue by smallshen** [JetBrains/compose-multiplatform#1736]
The `rememberCursorPositionProvider` only uses a few awt related things but breaks a lot of compatibility.

```kotlin
val component = LocalLayerContainer.current
val cursorPoint = remember {
    val awtMousePosition = MouseInfo.getPointerInfo().location
    convertPointFromScreen(awtMousePosition, component)
    IntOffset(
        (awtMousePosition.x * component.density.density).toInt(),
        (awtMousePosition.y * component.density.density).toInt()
    )
}
```
It will break the tooltip, cursor position popup. 
It breaks when using OpenGL or another non awt environment with ComposeSence.

https://github.com/HumbleUI/JWM/issues/172

Can we have a `LocalMouseLocationProvider` with CompositionLocal and set defaults to the code above in rememberCursorPositionProvider?

related to: https://github.com/JetBrains/compose-jb/issues/652

**Comment by Walingar** [comment]
In 1.4.0 rememberCursorPositionProvider doesn't rely on AWT anymore, so it should fine with non-awt environment

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1736">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
