### ISSUE TITLE
Compiler Web: Fails when 2 files have the same name

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-multiplatform#1744]
The "normal" js compiler is able to build a project when two files have the same names.

When applying compose, it fails with a useless error message: `java.lang.IllegalStateException: Validation failed in file main.kt`

Compose 1.0.1 and Kotlin 1.6.10

Reproducer: 
Compose
[untitled1.zip](https://github.com/JetBrains/compose-jb/files/7927784/untitled1.zip)

Plain js: 
[untitled2.zip](https://github.com/JetBrains/compose-jb/files/7927783/untitled2.zip)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1744">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
