### ISSUE TITLE
web: compiler error with composable inline function and anonymous object (Assertion failed)

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-multiplatform#1751]
Versions:
- compose 1.0.1, kotlin 1.6.10
- compose 1.0.0, kotlin 1.5.31
- compose 1.0.0-alpha1-rc1, kotlin 1.5.21

As for now, the issue-causing sample was reduced to this:
```kotlin
@Composable
inline fun InlineComposableFoo(content: @Composable () -> Unit) {
    content()
}

@Composable
fun Game() = InlineComposableFoo {
    var message by remember { mutableStateOf<String?>(null) }
    val onWin = { message = "You win!" }
    val difficulty = object {}
}
```

It fails at `compileDevelopmentExecutableKotlinJs`:
```
// fails when translating call arguments. There is 1 value argument in the call and it's null, so `assert(validWithNullArgs)` fails


e: java.lang.AssertionError: Assertion failed
        at org.jetbrains.kotlin.ir.backend.js.transformers.irToJs.JsAstUtilsKt.translateCallArguments(jsAstUtils.kt:343)
        at org.jetbrains.kotlin.ir.backend.js.transformers.irToJs.JsAstUtilsKt.translateCall(jsAstUtils.kt:111)
        ...
        
IR (dump kotlin like):
Call (has no argument):
return Game$composable$<anonymous>$lambda-2()

the function (has 1 parameter):
private fun Game$composable$<anonymous>$lambda-2($message$delegate: MutableState<String?>): Function0<Unit> {
  return <no name provided>$factory($$message$delegate = $message$delegate)
}
```

It doesn't fail if either:
- remove ```val difficulty = object {}```  (or moved out of the fun Game)
- remove ```val onWin = { message = "You win!" }```
- not use remember - ```var message by  mutableStateOf<String?>(null)```
- make ```inline fun InlineComposableFoo``` not inline

tried to create a similar code (with `by`, lambda using delegated value, object) without compose (plain k/js) - no error

**Comment by eymar** [comment]
The root cuase has been fixed in k/js - https://youtrack.jetbrains.com/issue/KT-51102

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1751">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
