### ISSUE TITLE
Make showCharacterPalette() public

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-multiplatform#1754]
Can we make [`showCharacterPalette()` in `KeyEventHelpers.desktop.kt`](https://github.com/JetBrains/androidx/blob/jb-main/compose/foundation/foundation/src/desktopMain/kotlin/androidx/compose/foundation/text/KeyEventHelpers.desktop.kt#L24) public? We need to use it in or code but it's currently set to `internal`. Depending on `org.jetbrains.skiko.orderEmojiAndSymbolsPopup` from Skia directly would make our JARs OS-dependent, which we can't work with.

**Comment by akurasov** [comment]
@igordmn WDYT?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1754">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
