### ISSUE TITLE
TextLayoutResult.getWordBoundary() doesn't break on expected characters

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-multiplatform#1762]
When we use `TextLayoutResult.getWordBoundary(offset: Int)` to get the boundaries of work from a given offset, it seems to be skipping boundaries we expect it to break at. For example, take the following string:

```kotlin
private fun mayScrollToCoordinate(x: Int, y:asdf Int, padding: Int = 0) { }
```

In Chrome and Intellij, the word boundaries that the cursor will stop for (before/after), include `,`, `(`, `)`, `:`, `=`, `{`, and `}`. However, all these characters seem to be ignored (not considered as boundaries) by `TextLayoutResult.getWordBoundary(offset: Int)`.

Can we get the `TextLayoutResult.getWordBoundary(offset: Int)` to adhere to the same behaviour as Intellij?

**Comment by akurasov** [comment]
Does it work the same way on Android?

**Comment by haikalpribadi** [comment]
@akurasov I have no idea. We don't work on any Android platforms.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1762">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
