### ISSUE TITLE
[linux] Scripts (preinst, postinst) inserted on installation resources don't execute

### ISSUE THREAD

**Issue by rodrigoknob** [JetBrains/compose-multiplatform#1766]
I'm trying to run script (postinst) after installing my application.
I'm able to put the scripts in the resources folder of the installation directory, but after the complete installation, they are not executed.

Follow the script instructions from this link:
http://www.embeddedlinux.org.cn/OEManual/recipes_installation_scripts.html

When I create the installer through jpackage via terminal, the scripts are executed normally, however, when I create the installer through the compose plugin, they are not executed.

I created a repository to simulate this situation, follow the link:
https://github.com/rodrigoknob/test_compose

If you run the create_package.sh script inside the jpackage_manual folder, it will create the .deb installer, and when you run the installer, the postinst scripts will run normally.

Now, if you are going to create the installer from the ./gradlew package task, the installer will be generated, however, if it is executed, no script is executed.

I don't know if some configuration is missing, or the plugin is not executing the scripts. 
Then, how to run the .deb package scripts via installer created by the plugin?

**Comment by AltNico** [comment]
Looking at the .deb files produced by the `packageDeb` task, one can see that the files from the source's _resource/_ directory land in _/opt/briar-desktop/lib/app/resources/_ inside the _data.tar.xz_ archive. However, one can see that the default `preinst` and `postinst` scripts land in the _control.tar.xz_ archive.

The respective code that handles this in Compose is this:
```kotlin
val appResourcesRootDir = app.nativeDistributions.appResourcesRootDir
if (appResourcesRootDir.isPresent) {
from(appResourcesRootDir.dir("common"))
from(appResourcesRootDir.dir(currentOS.id))
from(appResourcesRootDir.dir(currentTarget.id))
}

val destDir = project.layout.buildDirectory.dir("compose/tmp/${app.name}/resources")
into(destDir)
```
https://github.com/JetBrains/compose-jb/blob/aa08279/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/configureApplication.kt#L86

**Comment by AltNico** [comment]
I think I found the problem and fixed it in https://github.com/JetBrains/compose-jb/pull/1843.

**Comment by AltNico** [comment]
Until #1843 gets merged, we're using the following code at Briar Desktop to re-package the .deb files produced by Compose, in case anyone is interested:
```bash
fakeroot sh -c '
  mkdir tmp
  dpkg-deb -R briar-desktop.original.deb tmp
  cp ../../../../../src/packagingResources/linux/postinst tmp/DEBIAN/postinst
  cp ../../../../../src/packagingResources/linux/preinst tmp/DEBIAN/preinst
  cp ../../../../../src/packagingResources/linux/prerm tmp/DEBIAN/prerm
  dpkg-deb -b tmp briar-desktop.deb
'

```

https://code.briarproject.org/briar/briar-desktop/-/blob/9d1a68920b52f5dd0f5764e89639e28cf0f5e837/utils/finalize-deb.sh

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1766">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
