### ISSUE TITLE
rememberCursorPositionProvider() doesn't register mouse position when clicking while moving and previous popup still open

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-multiplatform#1769]
When using the `androidx.compose.ui.window.Popup()` we provide `popupPositionProvider = rememberCursorPositionProvider()`. This function is what determines the mouse location to open the popup. It works perfectly fine when you perform the right-click without moving the mouse. However, sometimes your mouse moves a little when you right-click (this should be expected as normal as our hands can shake a tiny bit). This is also fine, if you right-click (and move) when there is NO popup shown.

However, if a popup is currently visible, and you right-click-and-move (outside the first popup) to trigger another popup, then the `popupPositionProvider` does NOT get updated with the new mouse location. I suspect this is either because
a) inside `rememberCursorPositionProvider()` we `remember { }` the `IntOffset` of the mouse, or 
b) when when we right-click-and-move outside the popup, the `onDismissRequest()` function does not get called.

Can we get some help on getting this fixed? Thanks, guys!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1769">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
