### ISSUE TITLE
I am having rendering issues

### ISSUE THREAD

**Issue by Vikng412** [JetBrains/compose-multiplatform#1771]
I am using an app called spotiflyer (https://github.com/Shabinder/SpotiFlyer) on my desktop but for some reason the app doesn't load any visual content (in a region cursor changes to I-cursor). Developer suggested that I report it here as he said app is working fine the problem is with rendering. 
![image](https://user-images.githubusercontent.com/78209058/151815998-8ef1a40c-19cd-445b-bcbd-9133dd78abc7.png)

**Comment by Shabinder** [comment]
https://github.com/Shabinder/SpotiFlyer/issues/715#issuecomment-1027124412
Seems like windows specific issue

**Comment by asapha** [comment]
@Vikng412, @Shabinder does the app work after you doing this?

- In the Windows start menu, type environment
- Open the first item
- Click on Environment Variables
- Click on New
- Set SKIKO_RENDER_API as variable name
- Set SOFTWARE as variable value
- Click OK on all windows
- Start SpotiFlyer

![CleanShot 2022-03-03 at 13 28 09](https://user-images.githubusercontent.com/1147807/156564808-7b917b60-f305-4c9b-8c7a-b3bc7250f839.png)

As asked [here](https://github.com/JetBrains/compose-jb/issues/446#issuecomment-791281590), could you please post your PC specifications?
> Could you please give your PC specification?
> OS version: ?
> Graphics card: ?
> Graphics card driver version: ?

Example:
> Notebook Asus ROG
> Windows 10 Version 2004
> Graphic Cards:
> Intel HD Graphics 530 - driver version 21.20.16.4550
> Nvidia GeForce GTX 960M - driver version 27.21.14.6140

Linked issue?
https://github.com/JetBrains/compose-jb/issues/446

(Some keywords to find the issue: Blank screen, White window)

**Comment by Vikng412** [comment]
the issue was resolved thanks to you

FYI
Windows 10 Pro 21H2 64bit
Intel i5 4590
Intel HD Graphics 4600

**Comment by asapha** [comment]
Nice, thanks for testing.
But could we please let this issue open until there's a permanent solution?

**Comment by asapha** [comment]
If this can help resolve the issue:
- [Intel has an official list of graphics card compatible with DirectX 12](https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html)
- [On some intel graphics card, DirectX 12 won't work if the driver is... too recent](https://www.intel.com/content/www/us/en/support/articles/000057520/graphics/graphics-for-4th-generation-intel-processors.html)

**Comment by davidwhitman** [comment]
A user reported the same issue to me (empty white window, Direct3D error), which we resolved using the helpful image above to set their environment variable.

I didn't get their full system specs, but here is their CPU.
> Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1771">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
