### ISSUE TITLE
Reload not properly browser

### ISSUE THREAD

**Issue by RWOverdijk** [JetBrains/compose-multiplatform#1783]
[In this guide](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Web/Getting_Started) it says:

> Instead of manually compiling and executing a Kotlin/JS project every time you want to see the changes you made, you can use the continuous compilation mode: `./gradlew jsBrowserRun --continuous`

This doesn't seem to work for me. The page reloads, but nothing changes. All I did was change the text of the button as a simple test.

```diff
- Text("-")
+ Text("haha reload go brrrr")
```

I am using jdk 16 and I am using:

```kts
plugins {
    kotlin("multiplatform") version "1.6.10"
    id("org.jetbrains.compose") version "1.0.1"
}
```

I figured I'd try updating instead of just following the guide since I noticed it was a bit behind. I also added:

```kts
rootProject.plugins.withType<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin> {
    rootProject.the<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension>().nodeVersion = "16.0.0"
}
```

because of this: https://youtrack.jetbrains.com/issue/KT-49109

Other than that it's identical to the guide.

Am I doing something wrong here or is this broken?

**Comment by eymar** [comment]
if changes are not detected, `Ctrl+S` or `CMD+S` helps. 
Does it help in your case?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1783">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
