### ISSUE TITLE
Support extended color spaces for Window

### ISSUE THREAD

**Issue by bvitaliyg** [JetBrains/compose-multiplatform#1784]
Currently, all Window content is in sRGB color space.

You can use this code to test the color (tested on Macbook with DisplayP3 support):
```
Canvas(Modifier.fillMaxSize()) {
    drawRect(Color(0f, 1f, 0f, 1f, ColorSpaces.DisplayP3))
}
```
The reference colour can be obtained in Photoshop or Affinity Photo when creating new file with DisplayP3 support.

The reason is that `ComposeWindow` [uses](https://github.com/androidx/androidx/blob/e881053441801ca41431b0bf02a13a95dc53d203/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/awt/ComposeWindow.desktop.kt#L38) default constructor of `JFrame`.

This limits the color management for Compose desktop. Even when you use `ComposeWindow` class directly, there's no was to change the color profile.

**Comment by igordmn** [comment]
> The reason is that ComposeWindow [uses](https://github.com/androidx/androidx/blob/e881053441801ca41431b0bf02a13a95dc53d203/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/awt/ComposeWindow.desktop.kt#L38) default constructor of JFrame.

`ComposeWindow` has [a constructor](https://github.com/JetBrains/androidx/blob/21f72b75f863c1dcc9408987fb82a6c26d929c6f/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/awt/ComposeWindow.desktop.kt#L44) that accepts `GraphicsConfiguration`. This change is only available in 1.0/1.1 versions. 1.2 version (or `androidx-main` branch in `androidx` repo) doesn't have this change yet. We will upstream it in the near future.

**Comment by akurasov** [comment]
@bvitaliyg does it work for you?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1784">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
