### ISSUE TITLE
output program from the installation of packageMsi doesn't have uninstall shortcut

### ISSUE THREAD

**Issue by ArthurKun21** [JetBrains/compose-multiplatform#1785]
![image](https://user-images.githubusercontent.com/16458204/152294194-2bc2bd5c-1c21-4d3e-8c47-1424447f6672.png)

would it be possible to make the windows program that is created by the compose desktop also created inside the programs folder have uninstall shortcut/program?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1785">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
