### ISSUE TITLE
Consecutive mouse clicks on button get lost if mouse is not moved between clicks

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/compose-multiplatform#1806]
In a simple application I have a Button which acts as a toggle button by altering some state in its onClick lambda. This worked perfectly until v1.1.0-alpha03 but stopped working reliably after this version. I found out that consecutive clicks are just ignored if I do not slightly move the mouse between the clicks. If I move the mouse just a little bit everything seems to be ok but if I keep the mouse at the same position then the clicks seem to get lost.

I tested this on a Mac with versions v1.1.0-alpha03, v1.2.0-alpha01-dev602 and v1.2.0-alpha01-dev606.

**Comment by akurasov** [comment]
Am I correct, that you have issues in 1.2.* builds, while 1.1.0-alpha03+ is fine?

**Comment by mipastgt** [comment]
@akurasov Yes, exactly.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1806">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
