### ISSUE TITLE
How to manage data storage on desktop?

### ISSUE THREAD

**Issue by RubiTree** [JetBrains/compose-multiplatform#1810]
On the desktop side, if I need to manage some new files generated, how should I store them?  I haven't found relevant tutorials. These rules are similar to those on Android: https://developer.android.com/training/data-storage

I'm an Android Developer, so I don't know much about desktop development. I'm not sure if I need to find some desktop native related content to learn. So i first ask this question, thx for read.

**Comment by akurasov** [comment]
Hello! What kind of files do you want to store? If it is just pictures, you can check imageviewer app as an example

**Comment by artillerymans** [comment]
I have similar questions, but what I want to know is whether I can use Jetpack DataStore directly on Desktop

**Comment by elonzh** [comment]
`androidx.datastore:datastore-core` does not have Android dependceny but [it is not working in Windows for now](https://issuetracker.google.com/issues/194301881), I am using [Realm](https://realm.io/) as a solution and it's very promising.

**Comment by hakanai** [comment]
I have some use cases for this one as well. I could use `Preferences` ...

Hmm, would this DataStore be built on `Preferences`, or is there more to it than that? There are some pretty sharp limitations of what Java lets you store.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1810">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
