### ISSUE TITLE
[Feature] Support hot module replacement (HMR) for compose-web

### ISSUE THREAD

**Issue by rocketraman** [JetBrains/compose-multiplatform#1818]
Support hot module replacement (https://webpack.js.org/concepts/hot-module-replacement/) with Compose/Web.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1818">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
