### ISSUE TITLE
information required about packaging  app to windows 32Bit 

### ISSUE THREAD

**Issue by memonahmedanees** [JetBrains/compose-multiplatform#1819]
hi to all ,
my question is simple , 
i didnt find any resources about packing a windows app to 32bit , because when i check in setting in gradle file ,
it compose only current os  . i am working on windows 11  , so may be app not worked correctly in to backward compatibility such a windows 7 , or windows xp .
dependency only works for windows 64 bit so please if any one know about this reply this post

**Comment by akurasov** [comment]
Compose Multiplatform doesn't support 32bit OSes

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1819">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
