### ISSUE TITLE
I import the compose-template. and sync success, but I got this error.

### ISSUE THREAD

**Issue by kirin233x** [JetBrains/compose-multiplatform#1826]
![image](https://user-images.githubusercontent.com/8955465/153546534-145ff7a0-e24a-47b1-a73d-9514c50ee27a.png)

**Comment by akurasov** [comment]
Is there anything wrong the file/project? I don't see any issues

**Comment by kirin521** [comment]
> 

thanks for your reply. my gradle is sync success, but my project view do not show the 'src' directory, when i open the build.gradle.kts, the ide show the error message "Code insight unavaliable(scripte configurations not loaded)". I even reinstalled the IDE, but the error remain.

**Comment by kirin521** [comment]
> Is there anything wrong the file/project? I don't see any issues

thanks for your reply. my gradle is sync success, but my project view do not show the 'src' directory, when i open the build.gradle.kts, the ide show the error message "Code insight unavaliable(scripte configurations not loaded)". I even reinstalled the IDE, but the error remain.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1826">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
