### ISSUE TITLE
Strange Behavior in Composable function

### ISSUE THREAD

**Issue by zerofancy** [JetBrains/compose-multiplatform#1830]
JVM: adopt-openjdk-15.0.2
OS: macOS 12.2.1 21D62 x86_64
Compose Version: 1.0.0

I often use the below method instead of if-else, but there is a problem in the Composable function.

```kotlin
obj?.let {
    // case 1
} ?: kotlin.run {
    // case 2
}
```

I tried using it like this in the Composable function, but found that **neither branch went**.

demo:

```kotlin
import androidx.compose.desktop.ui.tooling.preview.Preview
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@Composable
@Preview
fun App() {
    val text = remember { mutableStateOf<String?>(null) }

    MaterialTheme {
        println("start ${text.value}")
        text.value?.let {
            println("value is $it")
            Button(onClick = {
            }) {
                Text("case 1")
            }
        } ?: run {
            println("browse")
            Button(onClick = {
            }) {
                Text("case 2")
            }
        }
        println("end")
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}
```

output:

```plain
start null
end
```

And there are no buttons displayed on the screen.

**Comment by hfhbd** [comment]
See also: https://issuetracker.google.com/issues/198511576

**Comment by zerofancy** [comment]
> See also: https://issuetracker.google.com/issues/198511576
> 
> The biggest question, is why do you use this instead `if/else`, which works. Using `let/run` could result into unexpected behavior after an accidentally refactoring.
> 
> ```kotlin
> null?.let {
>     foo()
> ?: run {
>     bar() 
> }
> fun bar() { }
> 
> // before
> fun foo() { }
> // after
> fun foo(): Int? = null
> ```
> 
> If you return `null` in `foo`, `bar` will also be executed!

Thanks a lot for your answer. I use this trick to avoid non-null assertions and I'll avoid coding like this later.

**Comment by akurasov** [comment]
waiting to be fixed in the upstream

**Comment by Philipp91** [comment]
Using `also()` instead of `let()` should work around the problem, and it's still readable and logical Kotlin code.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1830">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
