### ISSUE TITLE
Custom copy action for SelectionContainer if nothing selected

### ISSUE THREAD

**Issue by ialokim** [JetBrains/compose-multiplatform#1837]
The current behavior is that the "Copy" action is added to the context menu even if nothing is selected inside the `SelectionContainer`, but clicking on it results in nothing being copied (i.e., the clipboard is not changed). It would be better to have at least one of the following behaviors instead:
1. Hide the copy action from the context menu.
2. Automatically copy everything inside the `SelectionContainer` (i.e. as if everything would have been selected before, related to #1309)
3. Provide a way to have a custom callback called if nothing is selected.

**Comment by ialokim** [comment]
For future reference:

> 1. Hide the copy action from the context menu.

see https://github.com/JetBrains/androidx/blob/b94c918ceb25b95b5a4d05888bcac0ae8e0681aa/compose/foundation/foundation/src/desktopMain/kotlin/androidx/compose/foundation/text/ContextMenu.desktop.kt#L115

> 2. Automatically copy everything inside the SelectionContainer (i.e. as if everything would have been selected before)

see https://github.com/JetBrains/androidx/blob/b94c918ceb25b95b5a4d05888bcac0ae8e0681aa/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/selection/SelectionManager.kt#L400

**Comment by ialokim** [comment]
For others encountering the same issue: We were able to implement option 1 from above using the new `LocalTextContextMenu` composition local, basically reproducing `TextContextMenu.Default` with an additional if-clause:

```kotlin
import androidx.compose.foundation.ContextMenuArea
import androidx.compose.foundation.ContextMenuItem
import androidx.compose.foundation.ContextMenuState
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.text.TextContextMenu
import androidx.compose.foundation.text.TextContextMenu.TextManager
import androidx.compose.runtime.Composable
import org.briarproject.briar.desktop.utils.InternationalizationUtils.i18n

@OptIn(ExperimentalFoundationApi::class)
object CustomTextContextMenu : TextContextMenu {
    @Composable
    override fun Area(textManager: TextManager, state: ContextMenuState, content: @Composable () -> Unit) {
        val localization = LocalLocalization.current
        val items = {
            listOfNotNull(
                textManager.cut?.let {
                    ContextMenuItem(localization.cut, it)
                },
                textManager.copy?.let {
                    // don't show copy option if no text is selected
                    if (textManager.selectedText.isEmpty()) null
                    else ContextMenuItem(localization.copy, it)
                },
                textManager.paste?.let {
                    ContextMenuItem(localization.paste, it)
                },
                textManager.selectAll?.let {
                    ContextMenuItem(localization.selectAll, it)
                },
            )
        }

        ContextMenuArea(items, state, content = content)
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1837">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
