### ISSUE TITLE
Blurry icon in application switcher

### ISSUE THREAD

**Issue by ialokim** [JetBrains/compose-multiplatform#1838]
When setting the window icon using the Windows API, the icon looks blurry / pixelated in the XFCE application switcher (when pressing ALT+TAB). I think it has to do with how the icon is rasterized and set in `Window.desktop.kt`:

```kotlin
// In fact, this size doesn't affect anything on Windows/Linux, and isn't used by macOs (macOs
// doesn't have separate Window icons). We specify it to support Painter's with
// Unspecified intrinsicSize
private val iconSize = Size(32f, 32f)

internal fun Window.setIcon(painter: Painter?) {
    setIconImage(painter?.toAwtImage(density, layoutDirection, iconSize))
}
```

Java Swing/AWT has support for setting multiple versions of the window icon by [`setIconImages()`](https://docs.oracle.com/javase/7/docs/api/java/awt/Window.html#setIconImages(java.util.List)) from which the OS / Window Manager should be able to choose the right one depending on the resolution.

**Comment by ialokim** [comment]
Since you've added the windows label: I'm actually experiencing this on a XFCE desktop, so I don't know if the same problems occurs on Windows too, but it's definitely not something Windows-specific.

**Comment by ptitjes** [comment]
Yep, I observe the same on Fedora/Linux with Wayland and Gnome.
Do you have a workaround?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1838">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
