### ISSUE TITLE
Multimedia key shortcuts lack of support

### ISSUE THREAD

**Issue by bassstorm** [JetBrains/compose-multiplatform#1840]
Multimedia key shortcuts are not recognized.
For example, `Key.MediaPlayPause` is displayed as `Unknown keyCode: 0x-3b9aca49`, see screenshot below.
![MediaPlayPause](https://user-images.githubusercontent.com/749825/153772535-8b7fc493-3fb6-4f89-8a9e-13318a9b4c05.png)
Needless to say that there's no reaction to actual multimedia key press.

**System**: Manjaro Linux, kernel 5.15, KDE 5.23
**Compose**: 1.0.1
**JDK**: OpenJDK 11.0.13

I understand that API is marked as experimental, but hopefully this is a valid issue still. Thank you in advance!

Code to quickly reproduce:
```
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.input.key.Key
import androidx.compose.ui.input.key.KeyShortcut
import androidx.compose.ui.window.MenuBar
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@OptIn(ExperimentalComposeUiApi::class)
fun main() = application {
    Window(
        onCloseRequest = { exitApplication() },
        title = "MyApp"
    ) {
        MenuBar {
            Menu(text = "Playback") {
                Item(
                    text = "Play/Pause",
                    shortcut = KeyShortcut(key = Key.MediaPlayPause),
                    onClick = { println("Toggle pause") }
                )
                Item(
                    text = "Stop",
                    shortcut = KeyShortcut(key = Key.Escape),
                    onClick = { println("Stop") }
                )
            }
        }
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1840">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
