### ISSUE TITLE
Allow a keyboard shortcut to update the IDE plugin preview

### ISSUE THREAD

**Issue by codymikol** [JetBrains/compose-multiplatform#1841]
Either this, or some version of live updating would make iteration much faster.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1841">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by codymikol** [comment]
![image](https://github.com/user-attachments/assets/72bb40c6-49c0-4b01-a224-42f6a19321f9)

**Comment by codymikol** [comment]
![image](https://github.com/user-attachments/assets/42fb3c7c-9983-4ca4-ab38-d34333b1d443)

**Comment by codymikol** [comment]
![image](https://github.com/user-attachments/assets/5e64a9e4-8430-485a-acb8-ab2e8b4c93bb)

**Comment by codymikol** [comment]
![image](https://github.com/user-attachments/assets/92741093-ce83-4e5e-92d6-82b799aed262)
