### ISSUE TITLE
Not updating window when changing state from key event

### ISSUE THREAD

**Issue by dkim19375** [JetBrains/compose-multiplatform#1842]
In `onKeyEvent` in the `Window` parameter, I have it change the state in another function to update the window
However, it doesn't update, so how should I force the window to update?
Code: https://paste.helpch.at/lomewinoqo.java
Logs: 
```
updated (open window)
got key (press a key)
got key (press a key)
got key (press a key)
```
It only prints `update` when the window is first created

**Comment by akurasov** [comment]
Try to use update variable in some composable. E.g. add a checkbox showing its state.

**Comment by dkim19375** [comment]
> Try to use update variable in some composable. E.g. add a checkbox showing its state.

The thing is, that my app is supposed to change a color of a `Box` when certain keys are pressed, not from a checkbox.
I also haven't found a KeyEvent function that is composable

**Comment by dkim19375** [comment]
Found a solution (?) or workaround to this issue: I just added 
```kt
update
```
at line 25 like this: https://paste.helpch.at/amebejedih.cs

**Comment by akurasov** [comment]
Nope, this shouldn't be done like this. Try to add a Box, which color depends on the state. It also should work.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1842">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
