### ISSUE TITLE
System tray icon not showing (correctly) with Gnome (Xorg/Wayland)

### ISSUE THREAD

**Issue by Jeansen** [JetBrains/compose-multiplatform#1847]
Currently I am on Debian with Gnome 41.3.

 When I run the https://github.com/JetBrains/compose-jb/tree/master/tutorials/Tray_Notifications_MenuBar_new I get two things:

- With Gnome on Wayland I get an icon, but the circle is double the size it should, be, therefore clipped and the background is white (instead of transparent)
- With Gnome on Xorg, I have a black icon.

Context menu works in both scenarios.

Note: Tray only works when this extension is installed: https://extensions.gnome.org/extension/615/appindicator-support/ .

On Windows, it works fine. On both systems I can invoke the tray menu, increase the counter and close the application. It's simply that the tray icon itself has issues with Gnome.

**Comment by Jeansen** [comment]
One addition: [dorkbox.systemTray.SystemTray](https://github.com/dorkbox/SystemTray) works perfectly fine with an older app I'd like to transition from JavaFX + Kotlin to Compose.

**Comment by ChrisAJS** [comment]
Fwiw: When using the Tray functionality, I get a `JavaEmbeddedFrame` task in my task switcher, which does display the requested tray icon.

Also when using multiple monitors, the resultant menu that opens when tapping on the tray icon, may appear on the incorrect display.

(On Gnome 40.4.0 and using X11 windowing system)

**Comment by Jeansen** [comment]
I tried again with OpenJDK 17, Compose 1.0.1 and Kotlin 1.6.10. Same issues.

**Comment by ChrisAJS** [comment]
I ended up using Dorkbox as @Jeansen recommended. Here's a little snippet on how to get up and running with it:

h3. Gradle dependency
```kotlin
implementation("com.dorkbox:SystemTray:4.1")
```

h3. Sample use
```kotlin
@Composable
fun DorkTray() {
    val tray by remember { mutableStateOf(SystemTray.get()!!) }

    LaunchedEffect(true) {
        tray.installShutdownHook() // Auto-remove icon when application is killed
        tray.setImage(javaClass.getResourceAsStream("/icon.png")) // Use icon in src/main/resources/icon.png
        tray.menu.add(MenuItem("Click me!").apply {
            setCallback { println("Handled click!") }
        })
    }
}
```

This should be enough to get someone going if they find themselves here.

**Comment by Giuliopime** [comment]
Didn't you get this error @ChrisAJS 
`loader 'bootstrap' attempted duplicate class definition for java.awt.TrayIcon. (java.awt.TrayIcon is in module java.desktop of loader 'bootstrap')`

**Comment by Nohus** [comment]
> Didn't you get this error @ChrisAJS `loader 'bootstrap' attempted duplicate class definition for java.awt.TrayIcon. (java.awt.TrayIcon is in module java.desktop of loader 'bootstrap')`

Did you solve this? Getting the same issue. : )

**Comment by realrubbish** [comment]
> Didn't you get this error @ChrisAJS `loader 'bootstrap' attempted duplicate class definition for java.awt.TrayIcon. (java.awt.TrayIcon is in module java.desktop of loader 'bootstrap')`

Just managed to run the cod of ChrisAJS by setting `SystemTray.FORCE_TRAY_TYPE` manually before the `SystemTray.get()` call to `Swing` on macOS (14.5):
```
fun DorkTray() {
    SystemTray.FORCE_TRAY_TYPE = SystemTray.TrayType.Swing
    val tray by remember { mutableStateOf(SystemTray.get()!!) }
...
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1847">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
