### ISSUE TITLE
Document education steps for newcomers

### ISSUE THREAD

**Issue by mcpiroman** [JetBrains/compose-multiplatform#1855]
[From Slack]
It looks like it's a standard process, at least for now, that a lot of people look for when coming to CfD, so I propose to prepend to readme something along these lines: "If you're new to writing apps with Compose, first start with [Google's tutorial for Jetpack Compose](https://developer.android.com/jetpack/compose/tutorial), then take a look [here](https://github.com/JetBrains/compose-jb/tree/master/tutorials) for bits related to development for desktop platforms".

**Comment by akurasov** [comment]
Yes, it is important to refer excellent Google documentation from CfD tutorials. It is on our list.
