### ISSUE TITLE
Text: letterSpacing and TextAlign.Center break text centering

### ISSUE THREAD

**Issue by mcpiroman** [JetBrains/compose-multiplatform#1856]
```kotlin
MaterialTheme {
    Column {
        /*A*/ Text("BLAH", Modifier.border(2.dp, Color.Red), letterSpacing = 10.sp)
        /*B*/ Text("BLAH", Modifier.border(2.dp, Color.Red), letterSpacing = 10.sp, textAlign = TextAlign.Center)
    }
}
```

### Actual:
![image](https://user-images.githubusercontent.com/38111589/154487110-f7247355-6ded-4cfc-bb8d-acb74f4d06d3.png)

### Expected:
I expect `letterSpacing` not to add any padding (so that all letters touch the border).

However, if it is meant to do so, then:
- `B` should be centered as `A`
- Not sure about `A`, probably it's OK, but since it is not explicitly centered, maybe should be as `B`

<br>
Not sure if it's specific to CfD, I'd file it at Google's tracker, but I'm not sure which Jetpack's versions correspond to CfD.

**Comment by SudoDios** [comment]
Hi.
letterSpacing get padding in end of text
![Screenshot from 2023-11-19 10-42-48](https://github.com/JetBrains/compose-multiplatform/assets/62701838/f764cf26-00b7-45ad-aa22-2c68ae3ab02e)
How to fix it ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1856">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
