### ISSUE TITLE
macos: packageDmg: vendor and description values from NativeDistribution are not showing up in App->About screen

### ISSUE THREAD

**Issue by harishrpatel** [JetBrains/compose-multiplatform#1859]
Minor enhancement/issue.

- I specified `vendor` and `description` values in build.gradle (as shown below).
- Expecting those two to show up in App's About screen. But it only shows `packageName` and `packageVersion`.
- Version info about Compose (see attached gradle excerpt).

```

plugins {
    kotlin("jvm") version "1.6.10"
    id("org.jetbrains.compose") version "1.0.1"
}

compose.desktop {
    application {
        mainClass = "com.example.AbcKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg)
            packageName = "Abc"
            description = "Abc - a helper tool."
            vendor = "XYZ Inc."
            packageVersion = "1.0.0"

            macOS {
                iconFile.set(project.file(".../ic_launcher_APP.icns"))
            }
        }
    }
}

```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1859">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
