### ISSUE TITLE
Change window title or icon using state brings window to front

### ISSUE THREAD

**Issue by ialokim** [JetBrains/compose-multiplatform#1861]
When updating the title of a window by the use of `State` variable, the window is taken back to front if it was hidden behind another window or even minimized. The same happens when the window icon is changed through a backing state.

When updating the title or icon using the `ComposeWindow` object of the `WindowScope`, the window is not brought to the front.

Minimal reproducer: Start the following application and minimize it directly. You will notice that the window is focused after 10s when the title is changed through the state. If you minimize it again, it will not be focused after 10 more seconds.
```kotlin
application {
    val title by produceState("Title") {
        delay(10000)
        value = "Title updated from State"
    }

    Window(
        title = title,
        onCloseRequest = {}
    ) {
        LaunchedEffect(Unit) {
            delay(20000)
            window.title = "Title updated from LaunchedEffect"
        }
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1861">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
