### ISSUE TITLE
Alignment enums get overflow strategy wrong

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-multiplatform#1863]
For example: https://github.com/JetBrains/compose-jb/blob/2536c297668b6d309507433236849c3b299eefce/web/core/src/jsMain/kotlin/org/jetbrains/compose/web/css/CSSEnums.kt#L138

```
        inline val SafeCenter get() = AlignItems("safe center")
        inline val UnsafeCenter get() = AlignItems("unsafe center")
```

However, you can apply the overflow strategy to ANY positional element, e.g. left, center, start, etc.

See also: https://developer.mozilla.org/en-US/docs/Web/CSS/align-items#formal_syntax

This issue affects all alignment CSS enums, not just the one I linked to

---

If the API wants to be typesafe, probably the "safe" and "unsafe" keywords should be extracted into their own class and then a method gets added like:

```
alignItems(overflowPosition: AlignmentOverflowPosition, position: AlignItems) {
   property("align-items", "${overflowPosition.value} ${position.value}")
}
```

It may be too late for this now due to Compose for Web being 1.0 unforutnately, but probably the positional arguments should also be extracted into their own class:

```
alignItems(overflowPosition: AlignmentOverflowPosition, position: AlignmentPosition) {
   property("align-items", "${overflowPosition.value} ${position.value}")
}
```

so you can't do something like mix "safe unset" or some other invalid combo.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1863">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
