### ISSUE TITLE
Missing various alignment enums / setters

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-multiplatform#1864]
Missing (that I found so far, probably worth auditing the general area):

* https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self
* https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content
* https://developer.mozilla.org/en-US/docs/Web/CSS/place-self 
  * `placeSelf(value)` exists but there should be `placeSelf(alignSelf, justifySelf)`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1864">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
