### ISSUE TITLE
Task :kotlinNpmInstall shows warnings

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-multiplatform#1865]
Noticed this only after upgrading Kotlin (and the multiplatform plugin) to 1.6.10 (and Compose to 1.0.1 but I don't think that matters)

Started getting this:
```
> Task :kotlinNpmInstall                   
warning workspace-aggregator-1bb757f5-9f00-4637-b8f2-763422759100 > opengl > webpack-dev-server > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning Ignored scripts due to flag.
```

and also it unceremoniously dumps a "kotlin-js-store" folder in my root project. I added a `.gitignore` for that folder but just making sure that was intentional. It seems kind of strange.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1865">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by toffeantyri** [comment]
I have the same problem: 
at first:
Execution failed for task ':kotlinStoreYarnLock'.

then 
> Task :kotlinNpmInstall
warning Ignored scripts due to flag.

> Task :kotlinStoreYarnLock FAILED

**Comment by bitspittle** [comment]
@toffeantyri Yeah, it turns out that behavior is intentional

https://kotlinlang.org/docs/js-project-setup.html#version-locking-via-kotlin-js-store

You need to run a task which intentionally updates the yarn versions.
