### ISSUE TITLE
Implement WindowPosition relative to parent

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#1873]
I want to show a Dialog in the center of its parent, but currently both `WindowPosition.Aligned` and `WindowPosition.Absolute` are relative to the screen (excluding insets).

**Comment by m-sasha** [comment]
Trying to find workarounds...

`LocalLayerContainer` and `LocalWindow` are `internal`.

`LocalWindowInfo` doesn't provide window position.

As it is, it seems I have to either pass down the `WindowState` to the place where I want to create the dialog or create my own `LocalWindowState`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1873">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
