### ISSUE TITLE
How to make a DESKTOP + WEB multi-platform app?

### ISSUE THREAD

**Issue by jsomeara** [JetBrains/compose-multiplatform#1874]
I haven't found any intuitive guides or docs on this. How would one go about making a DESKTOP + WEB multi-platform app? This would mean shared styling, etc.

Thanks!

**Comment by akurasov** [comment]
Web and Desktop doesn't share UI elements at the moment, as they have different rendering engines. So you can share only runtime part (recomposition logic).

We are working on Web-Canvas implementation, that will allow you to share UI elements too.

**Comment by meshpaul** [comment]
will there be any afpha preview of this anytime soon ?

**Comment by GabrielLasso** [comment]
Is it available yet?

**Comment by wakaztahir** [comment]
Compose now targets web canvas , lot of bugs though and skia lib is huge

**Comment by GabrielLasso** [comment]
How can I add web canvas to an existing desktop+android project?

The current bugs are not a problem for now, since I plan to release this only next year

**Comment by wakaztahir** [comment]
I have a project code editor that you can look at

https://github.com/Qawaz/compose-code-editor

**Comment by pablichjenkov** [comment]
You can check the experimental examples here:
https://github.com/JetBrains/compose-jb/tree/master/experimental/examples

I have created a project to play with compose multiplatform and also help to discover bugs, can check it here:
https://github.com/pablichjenkov/templato

**Comment by GabrielLasso** [comment]
Thanks!

I will see how it is done in this projects

I think it should be better documented in readme and in Intellij project creation. You have an schedule for web canvas and ios becoming stable?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1874">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
