### ISSUE TITLE
Dropdown Menu item stylings are hard-coded and not configurable

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-multiplatform#1878]
Hi, we're using `DropdownMenuItem()`, and as you can see here, such as min width, max width, and min height are hard-coded and not configurable: https://github.com/JetBrains/androidx/blob/e62838f496d592c019a3539669a9fbfd33928121/compose/material/material/src/commonMain/kotlin/androidx/compose/material/Menu.kt#L187-L193

```kotlin
private val MenuElevation = 8.dp
internal val MenuVerticalMargin = 48.dp
private val DropdownMenuItemHorizontalPadding = 16.dp
internal val DropdownMenuVerticalPadding = 8.dp
private val DropdownMenuItemDefaultMinWidth = 112.dp
private val DropdownMenuItemDefaultMaxWidth = 280.dp
private val DropdownMenuItemDefaultMinHeight = 48.dp
```

Can we make these parameters configurable, please?

**Comment by haikalpribadi** [comment]
Those values are used here: https://github.com/JetBrains/androidx/blob/e62838f496d592c019a3539669a9fbfd33928121/compose/material/material/src/commonMain/kotlin/androidx/compose/material/Menu.kt#L155-L159

**Comment by HolenZhou** [comment]
+1

**Comment by borichellow** [comment]
+1

**Comment by Shahz-B** [comment]
+1

**Comment by rylexr** [comment]
+1

**Comment by rylexr** [comment]
+1. Any news about this?

**Comment by AleSpero** [comment]
+1

**Comment by m-sasha** [comment]
A lot of paddings and sizes are hardcoded in Material widgets. We should decide on a strategy to deal with them across all widgets.

Some options:
- Add a `CompositionLocal` configuration/theme object (with defaults equal to the current Material values).
- Add a configuration parameter to each widget (with defaults equal to the current Material values).

Both these options can be done by either changing the implementation of the material widgets themselves (which would require upstreaming) or by copy/pasting the widgets to a different package/module.

**Comment by uniquePWD** [comment]
Has there been any progress on this?

**Comment by MatkovIvan** [comment]
We cannot _change_ common public API in fork - it won't be available on Android in this case. Such things are better to track in Google issue tracker.

**Comment by uniquePWD** [comment]
Thanks for the info.

**Comment by s97712** [comment]
+1. Any news about this?

**Comment by MatkovIvan** [comment]
As I already wrote above

> We cannot _change_ common public API in fork - it won't be available on Android in this case. Such things are better to track in Google issue tracker.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1878">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
