### ISSUE TITLE
Linux hidpi scaling

### ISSUE THREAD

**Issue by audkar** [JetBrains/compose-multiplatform#188]
UI is not upscaled properly on some Linux desktops. Would be useful if compose-jb could use same logic as Intellij uses ([ref](https://intellij-support.jetbrains.com/hc/en-us/articles/360007994999-HiDPI-configuration))

> Linux
> jvm 14
> Gnome 3.38 wayland

Intellij `show hidpi info` content:

> Per-monitor DPI-aware : enabled
> Monitor resolution : 1920x1080
> Monitor scale : 2.0
> User (IDE) scale : 1.0
> Xft.DPI : 192
> GSettings scale factor : undefined
> GDK_SCALE : undefined
> GDK_DPI_SCALE : undefined

**Comment by arkivanov** [comment]
Is there any workaround for now?

**Comment by igordmn** [comment]
> Is there any workaround for now?

Only manually set system parameter -Dsun.java2d.uiScale=2.0

**Comment by arkivanov** [comment]
Tried specifying "-Dsun.java2d.uiScale=2.0" in IDEA Run Configurations VM options, does not work.

**Comment by igordmn** [comment]
System properties which are set by IDEA Run Configuration are visible only to gradle.

If they should be visible to application, we need to define them in build.gradle.kts:

```
compose.desktop {
    application {
        jvmArgs("-Dsun.java2d.uiScale=2.0")
```

**Comment by floatingrain** [comment]
> System properties which are set by IDEA Run Configuration are visible only to gradle.
> 
> If they should be visible to application, we need to define them in build.gradle.kts:
> 
> ```
> compose.desktop {
>     application {
>         jvmArgs("-Dsun.java2d.uiScale=2.0")
> ```

still don't work on wayland

**Comment by igordmn** [comment]
> Still don't work on Linux

We [fixed](https://github.com/JetBrains/skiko/pull/128) DPI on some Linux'es some versions ago. But it seems that doesn't help in [Fedora](https://github.com/JetBrains/skiko/issues/124), and probably in KDE-based distro's.

**Comment by igordmn** [comment]
By the way, don't call any `java.swing.*`, `java.awt.*` functions before calling `application` or the old `Window`.

Otherwise DPI will not be set.

If you call these kind of functions, you should call `configureSwingGlobalsForCompose()` explicitly before any code, at the start of the `fun main() { }`

**Comment by floatingrain** [comment]
> > Still don't work on Linux
> 
> We [fixed](https://github.com/JetBrains/skiko/pull/128) DPI on some Linux'es some versions ago. But it seems that doesn't help in [Fedora](https://github.com/JetBrains/skiko/issues/124), probably in KDE-based distro's, and probably in Wayland

I'm using Ubuntu with Gnome, all latest, I tried the simplest app created by IDEA, the "Hello, Desktop" button is so small in both Wayland and X11. And I added "jvmArgs("-Dsun.java2d.uiScale=2.0")" like you said, then noting happened. Might be something wrong?

**Comment by igordmn** [comment]
> I tried the simplest app created by IDEA
> And I tried your example app "todoapp", it scaled correctly

IDEA uses the old version `0.4.0`, and todoapp uses `1.0.0-alpha1-rc3`.

**Comment by floatingrain** [comment]
> > I tried the simplest app created by IDEA
> > And I tried your example app "todoapp", it scaled correctly
> 
> IDEA uses the old version `0.4.0`, and todoapp uses `1.0.0-alpha1-rc3`.

Now we find the problem. How could I update the version?

**Comment by igordmn** [comment]
> Now we find the problem. How could I update the version?

Change it as described [here](https://github.com/JetBrains/compose-jb/blob/master/templates/desktop-template/build.gradle.kts#L8) for desktop-only project or [here](https://github.com/JetBrains/compose-jb/blob/master/templates/multiplatform-template/build.gradle.kts#L3) for MPP project.

(don't add COMPOSE_TEMPLATE_COMPOSE_VERSION, it is only for our CI)

**Comment by floatingrain** [comment]
> > > I tried the simplest app created by IDEA
> > > And I tried your example app "todoapp", it scaled correctly
> > 
> > 
> > IDEA uses the old version `0.4.0`, and todoapp uses `1.0.0-alpha1-rc3`.
> 
> Now we find the problem. How could I update the version?

I found it, in build.gradle.kts->plugins. Maybe I should update my IDEA to preview version for always getting default latest compose version.

**Comment by floatingrain** [comment]
> > Now we find the problem. How could I update the version?
> 
> Change it as described [here](https://github.com/JetBrains/compose-jb/blob/master/templates/desktop-template/build.gradle.kts#L8) for desktop-only project or [here](https://github.com/JetBrains/compose-jb/blob/master/templates/multiplatform-template/build.gradle.kts#L3) for MPP project.
> 
> (don't add COMPOSE_TEMPLATE_COMPOSE_VERSION, it is only for our CI)

Thank you very much.

**Comment by igordmn** [comment]
>  Maybe I should update my IDEA to preview version for always getting default latest compose version.

IDEA will be always behind the latest version, even Preview version (but it gets the updated version faster, we usually change it after releasing the stable version of Compose)

**Comment by tom-pratt** [comment]
I can't get it to scale on Ubuntu 21.04. I've tried the todo app and some of the suggestions here. It always looks tiny!

**Comment by dsvi** [comment]
The IDEA itself looks fine though. 
Why simply reading the output of `xrdb -q | grep Xft.dpi` and setting the scale accordingly is not an option anymore?
At least until some better option arrive.

**Comment by dsvi** [comment]
Nah it doesn't. Maybe because im under KDE.

BTW with wayland scaling is ok out of the box.
That was Kubuntu 22.04

**Comment by Burtan** [comment]
Ok, for me it helped under debian testing (bookworm) wayland Gnome

**Comment by bqMoonlight** [comment]
This is an issue only when running in debugging mode for me, when i run this in release mode it works properly 
ie :

`./gradlew runRelease` == works properly.

This was on PopOs  with wayland

**Comment by montanajava** [comment]
> ./gradlew runRelease == works properly.

> This was on PopOs with wayland

Ditto for me on Fedora 37 Wayland.  The normal interactive run button in IntelliJ renders an application very small.

**Comment by sschuberth** [comment]
FYI, I believe scaling used to be ok in Jetbrains Toolbox (which is written with Compose itself) until a few versions ago, but now the toolbox fonts render ridiculously small compared to other windows on a 2560x1440 pixel display. I'm also on Fedora 38 on Wayland.

**Comment by nishp77** [comment]
Hi everyone, I was facing the same issue whenever I'm switch from my monitors to laptop screen. Having read the above comment, running with `gradlew runRelease` works for me. So my plan is work on this issue and make a PR however no clue as to where to begin from like I have no clue on compose nor much on wayland, could somebody help me out with references if they have worked on this similar issue?

**Comment by kravemir** [comment]
It would be great, if Wayland's [Fractional scale protocol](https://wayland.app/protocols/fractional-scale-v1) was supported.

Nowadays, monitors come with quite odd PPI's, that integer HiDPI scaling isn't particularly usable anymore. The 2x makes everything too big, but 1x makes everything too small.

Besides the odd PPI of modern displays, fractional scaling helps with accessibility - some people scale normal DPI displays to 125%.

**Comment by cromefire** [comment]
One thing I haven't tested, but might help, is trying the jbr (jetbrains runtime) as a JDK/JRE, as I believe it contains certain fixes/improvement for the Java display stuff and that's what the toolbox (I believe) and idea use.

**Comment by sschuberth** [comment]
> One thing I haven't tested, but might help, is trying the [jbr (jetbrains runtime)](https://github.com/JetBrains/JetBrainsRuntime) as a JDK/JRE

Given that JetBrains ToolBox (which AFAIK runs on JBR) has the [same issues](https://youtrack.jetbrains.com/issues/TBX?q=scaling), I doubt that's going to help.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6004">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
