### ISSUE TITLE
DropDownMenu should allow specifying area to not cover

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#1903]
I'm trying to implement an auto-suggest box by using a `TextField` for entering text and a `DropDownMenu` for the list of suggestions. Unfortunately, if the dropdown doesn't fit below the textfield, it will cover it and expand up to the top of the window, making it unusable for auto-suggest.

There should be a way to specify an area inside the window the dropdown menu should not overlap. It could try fitting below, above and if it fails, simply limit itself in height.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1903">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
