### ISSUE TITLE
[question] Is there a widget like flutter's datatable

### ISSUE THREAD

**Issue by lovehzj** [JetBrains/compose-multiplatform#1906]
Is there a widget like flutter's datatable?
I want to show some text tables, like 

|xxx|xxx|xxx|
---|--|----
|yy|yy|yy|
|zz|zz|zz|

**Comment by mcpiroman** [comment]
See #344

**Comment by mcpiroman** [comment]
Right now there is also `LazyVerticalGrid`

**Comment by akurasov** [comment]
Currently there is no such component, but you can achieve it by having a number of rows

**Comment by goflutterjava** [comment]
@akurasov Is this a planned feature? 
I want to know how could I auto the same align by having a number of rows

**Comment by akurasov** [comment]
It is on the roadmap, but not for the nearest future. 

Could you describe your use case and maybe share some snippet on what you try now?

**Comment by feivur** [comment]
There is good idea https://stackoverflow.com/a/71665355/2416823

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1906">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
