### ISSUE TITLE
compese web NumberInput support decimal numbers

### ISSUE THREAD

**Issue by mihbor** [JetBrains/compose-multiplatform#1907]
Compose for Web 1.1.0 and 1.0.1

NumberInput doesn't accept typing in decimal numbers, as the trailing decimal point is always removed.
However it allows pasting in decimal numbers as well as putting a decimal point in between digits.

As I understand this is caused by the conversion after the keystroke, from e.g. the string "1." to the number one and then on recomposition, the number one is rendered without the trainling dot as "1", hence not letting to put in a decimal number normally.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1907">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
