### ISSUE TITLE
CfD for IJ IDEA has classpath clash when exception is thrown.

### ISSUE THREAD

**Issue by lamba92** [JetBrains/compose-multiplatform#1909]
Have a look at [Jewel #5](https://github.com/JetBrains/jewel/issues/5) or [IDEA-285839](https://youtrack.jetbrains.com/issue/IDEA-285839).

**Comment by akurasov** [comment]
Seems to be related with Dispatchers topic

**Comment by igordmn** [comment]
Can you check if it is fixed in 1.1.1?

It contains [this fix](https://github.com/JetBrains/compose-jb/issues/1943)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1909">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
