### ISSUE TITLE
Limited window menu APIs

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-multiplatform#191]
Looking at the current state of `MenuBar` and `MenuItem` APIs, I'm missing:

- Nested / second level (etc) menus
- Menus with built in check box / radio button support
- Disabling a menu item or a menu
- Styling support for menus in general

The last item looks to be a bit problematic on non-mac OSes where the swing `JMenuBar` is going to be displayed as part of the application frame. How is it going to be skinned in the compose world? Is the intent to create a Compose-specific implementation of the menu bar, or somehow use one of the third-party look-and-feels for a menu bar look-and-feel that is consistent with the rest of the app?

**Comment by olonho** [comment]
Are there Swing APIs for doing that?

**Comment by Rsedaikin** [comment]
We plan for non-Mac operating systems to create a Compose-specific implementation of the menu bar that allows you to style it however you want. And all features that you listed above will be available on all OSes (obviously, on MacOs MenuBar styling will be limited).

**Comment by adamsiembida** [comment]
Does this mean that the current implementation of the MenuBar just a temporary solution? The styling looks like it's from the year 2000. This is the problem I find with most desktop UI frameworks: they either look _extremely_ outdated, or they look like too mobile-influenced (e.g., huge padding on menus, like in UWP).

If I look at 90% of actual desktop apps I use on a daily basis, they still use regular menu bars; to me, a proper desktop-style MenuBar is essential for a desktop UI framework.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6094">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
