### ISSUE TITLE
[question] Text Field: Is there any way to set the paragraph spacing?

### ISSUE THREAD

**Issue by drakeet** [JetBrains/compose-multiplatform#1913]
**Paragraph Spacing** is a common feature for implementing text editors, and it makes the text more readable. I think it's well worth implementing or supporting.

For example, Typora supports this feature by default:

![image](https://user-images.githubusercontent.com/5214214/156141748-8db84c3b-8151-4a53-a950-79f2585b436f.png)

Thanks!

**Comment by drakeet** [comment]
Hi. Is there any help? If there is a guide or reference, maybe I can try to modify the relevant source code by myself.

**Comment by ArtyomZhukov** [comment]
+1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1913">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
