### ISSUE TITLE
CoreTextField does not respect annotatedString spans when comsping text

### ISSUE THREAD

**Issue by pChochura** [JetBrains/compose-multiplatform#1914]
I'm trying to create a rich text editor in compose and I'm struggling with not ending spiral of recompositions.
```kotlin
// value: TextFieldValue,
// onValueChange: (TextFieldValue) -> Unit,

BasicTextField(
	value = value,
	onValueChange = onValueChange,
)
```

This snippet shows that I'm using `TextFieldValue` for the `BasicTextField` value to be able to add span and paragraph styles.
After adding them and supplying them to the `BasicTextField` everything is great at first. But after changing the position of the cursor, so that the text composition is started (meaning: a word is highlighted and used for autocompletion on the keyboard), recompositions start. `onValueChanged` returns `annotatedString` object without any spans and paragraphs! And it does not match the object I'm supplying, so it recomposes.

I don't know what is happening because on the stable version (1.1.0) everything is working perfectly.

> composeVersion: 1.2.0-alpha04

**Comment by pChochura** [comment]
On the stable version sometimes I'm also getting `annotatedString` without any spans and it does not matter.
Now I don't really know what is the cause of all of this. I'm confused.

**Comment by akurasov** [comment]
Could you share a whole reproduction snippet, please?

**Comment by pChochura** [comment]
@akurasov Yeah, of course.
So basically I found out that the CoreTextField implementation does not take into account in all scenarios that the input can consist of AnnotatedString that has styles. This is snippet from the CoreTextField.kt file:
```kotlin
381  ...
382  setText {
383      onValueChangeWrapper(TextFieldValue(it.text, TextRange(it.text.length)))
384      true
385  }
386  ...
```
I belive that the correct way of handling this would be to copy the input AnnotatedString object and replace the text. Let me know if it is intentional.

A wrokaround (or the correct way; I don't know at this point) is to use VisualTransformation to pass the AnnotatedString with styles

**Comment by noe** [comment]
Maybe related to this compose issue: https://issuetracker.google.com/issues/135556699

**Comment by EStepiuk** [comment]
Facing the same issue. 
`onValueChange` callback drops all styles and annotations added earlier.
Any updates on this issue?

**Comment by dima-avdeev-jb** [comment]
@EStepiuk Can you please provide a minimal reproducible sample on GitHub?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1914">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
