### ISSUE TITLE
Modifier.focusable(enabled = false) doesn't work for TextFields, Buttons

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#1917]
Slightly modified example from https://github.com/JetBrains/compose-jb/tree/master/tutorials/Tab_Navigation:

```

fun main() = application {
    Window(
        state = WindowState(size = DpSize(350.dp, 500.dp)),
        onCloseRequest = ::exitApplication
    ) {
        Box(
            modifier = Modifier.fillMaxSize(),
            contentAlignment = Alignment.Center
        ) {
            Column(
                modifier = Modifier.padding(50.dp)
            ) {
                for (x in 1..4) {
                    val text = remember { mutableStateOf("") }
                    OutlinedTextField(
                        value = text.value,
                        singleLine = true,
                        onValueChange = { text.value = it },
                        modifier = Modifier.focusable(x % 2 == 0)  // <-- Note this
                    )
                    Spacer(modifier = Modifier.height(20.dp))
                }

                Row{
                    var text by remember { mutableStateOf("Not clicked") }
                    Button(
                        onClick = { text = "Clicked" },
                        modifier = Modifier.focusable(false)  // <-- Note this
                    ){
                        Text("Click Me!")
                    }

                    Text(text, modifier = Modifier.padding(12.dp))
                }
            }
        }
    }
}
```

Only even-indexed text fields are supposed to be focusable, and the button is supposed to be non-focusable.
I expected that:
1. Only even-indexed textfields would participate in focus navigation (by pressing 'tab').
2. The odd-indexed textfields will not be usable (can't type if they have no focus).
3. The button will not participate in focus navigation and will not be clickable by pressing 'ENTER'.

What happens, however is:
1. All textfields participate in focus navigation. Transitioning from focusable to non-focusable textfields strangely requires pressing 'tab' twice for the focus indicator to show. However even after one press, I can type text into the textfield.
2. All textfields behave normally when clicked with the mouse (become focused, can be typed into).
3. The button participates in focus navigation (pressing tab when the last textfield has focus moves the focus to the button). Pressing `ENTER` clicks the button.

https://user-images.githubusercontent.com/5230206/156199322-39409fb3-e2b1-4177-a4b7-39cc495c6e2f.mp4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1917">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
