### ISSUE TITLE
Virtual keyboard is not shown when clicking on a TextField in a tablet with Windows OS

### ISSUE THREAD

**Issue by kmenesesp** [JetBrains/compose-multiplatform#1919]
I am creating a desktop application for a Windows tablet but clicking or focusing a TextField doesn't open the virtual keyboard, is there any method or workaround to open and close the virtual keyboard? PD. only for a tablet device (no physical keyboard).

**Comment by kmenesesp** [comment]
I had to do a workaround, this is how I implemented it https://stackoverflow.com/a/71410876/12346089

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1919">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
