### ISSUE TITLE
[question] Does compose-jb support application's autoupdate

### ISSUE THREAD

**Issue by goflutterjava** [JetBrains/compose-multiplatform#1921]
I use `nativeDistributions` to package, I want to know does compose-jb support application's `autoupdate`

Thanks
Any Help will be greatful.

**Comment by akurasov** [comment]
There is no autoupdate support in Compose Multiplatform for desktop at the moment

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1921">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
