### ISSUE TITLE
Kotlin-Native Support for Desktop

### ISSUE THREAD

**Issue by caffeine-mgn** [JetBrains/compose-multiplatform#1923]
Can you add support of kotlin-native? Kotlin-native doesn't have any common UI library.

**Comment by akurasov** [comment]
You are speaking about desktop platfrom, right?

**Comment by caffeine-mgn** [comment]
> You are speaking about desktop platfrom, right? 

yep. I mean kotlin-native desctop application with ui

**Comment by akurasov** [comment]
Yes, I see. Development of desktop-native Compose is significant work and we are focused on different platforms at the moment, since desktop is covered by desktop-jvm platform. 

But yes, it is one of possible long-term goals.

**Comment by AhmedvHashem** [comment]
Compose for Kotlin/Native will serve iOS the most as there are no JIT in iOS

**Comment by wakaztahir** [comment]
any updates on this ?

**Comment by tuduongquyet** [comment]
Hi,
Any updates on this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1923">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
