### ISSUE TITLE
TextField retains focus on background click

### ISSUE THREAD

**Issue by dzirbel** [JetBrains/compose-multiplatform#1924]
I would expect TextField elements to lose their focus when the user clicks on the background or interacts with other focusable elements (e.g. clicking a button), but this doesn't happen as of v1.1.0. This behavior is the standard everywhere, as far as I know, for example in the Material design text field [demo](https://material.io/components/text-fields).

The behavior can be demonstrated [here](https://github.com/dzirbel/compose-playground/tree/e474d230e2d8b753e223a1c05f83a970dbf3fb1e) as well as the sample [todo app](https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp).

Is there a recommended workaround? The [tutorial](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Tab_Navigation) doesn't appear to cover this, and any manual way of handling focus on each TextField seems hard to manage for a large application.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1924">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
