### ISSUE TITLE
combinedClickable does not expose MouseClickScope

### ISSUE THREAD

**Issue by lamba92** [JetBrains/compose-multiplatform#1927]
The APIs for mouse clicks do not give any context about the key presses. `Modifier.combinedClickable` should expose information about which key is currently being pressed using `MouseClickScope`. For the double click even, you might pass only the latest `MouseClickScope` or 2 scopes, each for event.

**Comment by akurasov** [comment]
Lamberto, have you seen section "Mouse right/middle clicks and keyboard modifiers" of the Mouse events tutorial? I guess it answers your question.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1927">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
