### ISSUE TITLE
How can i show a dialog over all window?

### ISSUE THREAD

**Issue by RubiTree** [JetBrains/compose-multiplatform#1933]
How can i show a dialog over all window because i need to give user some reminders when they doing other things in other app？

I tried compose Dialog  but i find it will not show on the top.

**Comment by RubiTree** [comment]
I find i can use window with alwaysOnTop enable to solve this, and i suggest add this param to Dialog.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1933">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
