### ISSUE TITLE
Using Chinese characters in tray will generate garbled code

### ISSUE THREAD

**Issue by whitescent** [JetBrains/compose-multiplatform#1936]
```kotlin
Tray(
    icon = AppIcon(),
    tooltip = "Kftp",
    onAction = { isVisible = true },
    menu = {
        Item("Exit", onClick = ::exitApplication)
    }
)
```

It shows well.

![PNKUY TSA6Y3OVP1H$R 2GB](https://user-images.githubusercontent.com/31311826/157169745-f0bcf959-2a8c-4874-aa91-d7488aca2fbf.png)

```kotlin
Tray(
    icon = AppIcon(),
    tooltip = "Kftp",
    onAction = { isVisible = true },
    menu = {
        Item("退出程序", onClick = ::exitApplication)
    }
)
```

![image](https://user-images.githubusercontent.com/31311826/157169850-3fde69ea-0582-4395-8a8c-03126a929a3a.png)

info
```
compose: 1.1.0
os: windows 11
```

Update:

I found that if I run the program directly from `IDEA`, it shows garbled code, but if I run it as a `jar` or `exe`, it doesn't have this error.

![image](https://user-images.githubusercontent.com/31311826/157274691-099fbd2e-4187-4b8e-a03d-411044871b66.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1936">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
