### ISSUE TITLE
Broken link on landing page

### ISSUE THREAD

**Issue by koperagen** [JetBrains/compose-multiplatform#1937]
"Explore the source code" link of falling balls example card at https://compose-web.ui.pages.jetbrains.team/ leads to the https://github.com/JetBrains/compose-jb/tree/master/examples/falling-balls-web which is a 404 error

**Comment by olonho** [comment]
This page is no longer the proper landing, please refer to https://www.jetbrains.com/lp/compose-mpp/ for all flavours of Compose.

**Comment by koperagen** [comment]
Oh, i see. Totally missed new landing. That outdated one is what i found in google. But here https://www.jetbrains.com/lp/compose-mpp/ link is also broken :(

**Comment by shalva97** [comment]
The link is still broken...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1937">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
