### ISSUE TITLE
Missing "Input" example at landing page

### ISSUE THREAD

**Issue by koperagen** [JetBrains/compose-multiplatform#1938]
I'm not familiar with compose, but i decided to try it and build a simple web form with compose for web. I started from https://compose-web.ui.pages.jetbrains.team/, but there are no examples of how to handle text inputs. I also tried to search "documentation" on that page, but there is no such link either. Here i found https://github.com/JetBrains/compose-jb/tree/master/tutorials/Web/Controlled_Uncontrolled_Inputs, and it is what I was looking for. 
Maybe it's worth adding an example with some text input?

**Comment by akurasov** [comment]
Thank you for the feedback. And how have you found that landing page?

**Comment by akurasov** [comment]
@olonho maybe we should replace old CfW landing with redirect to Compose MPP landing, WDYT?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1938">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
