### ISSUE TITLE
InlineTextContent alignment not working a expected.

### ISSUE THREAD

**Issue by Dominaezzz** [JetBrains/compose-multiplatform#194]
I expected `PlaceholderVerticalAlign.Center` to align the centre of the image with the center of the text but it aligns the center of the image with the bottom of the text.
For all values of `PlaceholderVerticalAlign.*`, the *align* of the image is always aligned with the bottom of the text.

```
import androidx.compose.desktop.Window
import androidx.compose.foundation.Image
import androidx.compose.foundation.text.InlineTextContent
import androidx.compose.foundation.text.appendInlineContent
import androidx.compose.material.Text
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Person
import androidx.compose.ui.text.Placeholder
import androidx.compose.ui.text.PlaceholderVerticalAlign
import androidx.compose.ui.text.buildAnnotatedString
import androidx.compose.ui.unit.IntSize
import androidx.compose.ui.unit.em

fun main() {
	Window(title = "Bad Text", size = IntSize(300, 300)) {
		val text = buildAnnotatedString {
			appendInlineContent("image")
			append(" is a person.")
		}
		val person = InlineTextContent(
			placeholder = Placeholder(1.em, 1.em, PlaceholderVerticalAlign.Center),
			children = {
				Image(Icons.Filled.Person)
			}
		)
		Text(text, inlineContent = mapOf("image" to person))
	}
}
```

**Comment by olonho** [comment]
Is the same problem present in Android Compose? Why do you believe that behavior we get is not correct?

**Comment by Dominaezzz** [comment]
The reason why I think the behaviour is different is because the docs say otherwise.

https://developer.android.com/reference/kotlin/androidx/compose/ui/text/PlaceholderVerticalAlign#center

It says,
> Align the center of the placeholder with the center of the entire line

**Comment by Dominaezzz** [comment]
I don't know if this behaviour is present in Android compose.

**Comment by Dominaezzz** [comment]
![inline_text_content](https://user-images.githubusercontent.com/14130965/121255215-0e4bb880-c8a3-11eb-850d-1fc7d35c5770.png)

Is what it looks like

**Comment by Dominaezzz** [comment]
https://kotlinlang.slack.com/archives/CJLTWPH7S/p1623185440192700?thread_ts=1623185440.192700&cid=CJLTWPH7S

Looks like it's not present in Android compose.

**Comment by Dominaezzz** [comment]
![image (1)](https://user-images.githubusercontent.com/14130965/121820700-31ec7580-cc8c-11eb-86f6-583e482faa18.png)

**Comment by m-sasha** [comment]
@mgroth0 Could you post a reproducer? Both the op's reproducer and the test below seem to work correctly:

```
fun main() = singleWindowApplication {
    val text = buildAnnotatedString {
        append("Hello ")
        appendInlineContent(inlineContentId, "[myBox]")
        append(" inline content")
    }

    Column {
        Text(
            text = text,
            inlineContent = redSquare(2.em),
            style = TextStyle(fontSize = 32.sp),
            modifier = Modifier
                .padding(8.dp)
                .border(Dp.Hairline, color = Color.Black)
        )
        Text(
            text = text,
            inlineContent = redSquare(0.5.em),
            style = TextStyle(fontSize = 32.sp),
            modifier = Modifier
                .padding(8.dp)
                .border(Dp.Hairline, color = Color.Black)
        )
    }
}

const val inlineContentId = "inlineContent"

private fun redSquare(size: TextUnit) =
    mapOf(
        Pair(
            inlineContentId,
            InlineTextContent(
                Placeholder(
                    width = size,
                    height = size,
                    placeholderVerticalAlign = PlaceholderVerticalAlign.Center
                )
            ) {
                Box(modifier = Modifier.fillMaxSize().background(color = Color.Red))
            }
        )
    )
```

<img width="404" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5230206/e2eec4c9-626a-4a46-a6c9-626c84601eaf">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5994">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
