### ISSUE TITLE
Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.SomeStyleSheet-root @page {}'.

### ISSUE THREAD

**Issue by LouisCAD** [JetBrains/compose-multiplatform#1941]
Hello,

I tried to migrate from `1.0.0-alpha1-rc4` to `1.0.0-rc5` (and not later because I'm blocked by #1940),
and I'm encountering the following **runtime** error:

> Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.SomeStyleSheet-root @page {}'.

This should be a reproducing snippet, granted you use this stylesheet in a Web/DOM composable.
```kotlin
object SomeStyleSheet : StyleSheet() {

    init {
        "@page" {
            property("size", "A4 landscape")
            margin(0.mm)
        }
    }
}
```

It used to work in `1.0.0-alpha1-rc4`, do you when and why it stopped working?

**Comment by eymar** [comment]
Could you please provide a more detailed example to reproduce? 
The snippet above works in my case (using 1.0.0-rc5 and 1.1.1) + print preview has correct margin.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1941">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
