### ISSUE TITLE
Request focus on click

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#1946]
Compose 1.1.0

Native applications move focus when we click on focusable widgets (text fields, buttons, etc).

Most certainly we need to do it in Compose too. Currently focus move only for text fields, but not for `clickable`, `toggleable` widgets.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1946">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
