### ISSUE TITLE
PackageMsi result not work well but packageUberJarForCurrentOS can works very well 

### ISSUE THREAD

**Issue by fl619616995** [JetBrains/compose-multiplatform#1947]
Premise:
1. OS: Windows 10,
2. IDE: IntelliJ IDEA 2021.3.1
Detail:
I had a project that involves ktor, when I used gradle tool:"packageUberJarForCurrentOS " to get a jar and use cmd "java -jar xxx.jar",it can work very well. But when I used "packageMsi" or "createDistributable" to get a xxx.exe, it can opened and UI is correct, but some function not worked well, and it report like this(configuration console = true):

> Failed to instantiate SLF4J LoggerFactory
> Reported exception:
> java.lang.NoClassDefFoundError: javax/naming/NamingException

I had try some method like change the version of JDK11/15 ( javax/naming likes from JDK),but i  doesn't seem to work. Pleae help me.
And why "packageUberJarForCurrentOS " can works well ? It contains all dependencies?

![ktor_error](https://user-images.githubusercontent.com/22070193/157614481-b7f5a9f5-cbdc-49de-b47c-a4d444940650.png)

**Comment by akurasov** [comment]
Try approach from section "Configuring included JDK modules" of https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution

**Comment by akurasov** [comment]
@AlexeyTsvetkov what is the proper way of adding dlls to the application package? I guess adding them as resources is not the proper way.

**Comment by fl619616995** [comment]
if i add dlls like this:"fromFiles(project.fileTree("libs/") { include("**/*.dll") })",it contains in "/app/xxx.dll",but appliction can not find it. if i add dlls in the installation directory( copy by hand),it can works. My code is:
`System.loadLibrary("Dll_IM_Native")`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1947">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
