### ISSUE TITLE
Support pinch-to-zoom gesture on notebook touchpads (like MacBook trackpad)

### ISSUE THREAD

**Issue by ghost** [JetBrains/compose-multiplatform#1953]
On my MacBook trackpad going up and down with two fingers is scrolling like mouse wheel.

But how can I detect pinch-to-zoom?

I looked at the imageviewer sample which uses `detectTransformGestures`.

That works on my Android tablet, but does nothing on my MacBooks trackpad.
Also not on several never Dell Notebooks running Windows 10.

I feel it should be supported.

**Comment by touchnotes** [comment]
When should be supported?
I try v1.5.3, but still not work.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1953">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
