### ISSUE TITLE
Smooth scrolling not supported in Linux

### ISSUE THREAD

**Issue by Skaldebane** [JetBrains/compose-multiplatform#1955]
Hi! I'm using Compose Desktop v1.1.1 and to this day smooth scrolling is still not supported in Linux, both using a mouse wheel (it just jumps, no smooth animation like Windows/macOS), and touchpad (multiple instant jumps; doesn't sync 1-to-1 with the touchpad).

I use Fedora 35 with GNOME 41. It would be great if scrolling behavior is identical to Microsoft Edge (or Chromium, in general). It syncs perfectly with a touchpad (1-to-1), and with a mouse wheel it smoothly scrolls to the desired position instead of abruptly jumping to it.

**Comment by jakobkmar** [comment]
> (it just jumps, no smooth animation like Windows/macOS)

at least on windows, when using a mouse wheel scrolling can also not be configured to be smooth - so I am not sure if this issue is really linux specific?

**Comment by Skaldebane** [comment]
@jakobkmar Thanks, I barely use a mouse wheel nor do I use Windows so I'm probably wrong there. That might also be the case for macOS, and other native Linux (GTK) apps that support super smooth scrolling with the touchpad just jump when used with a mouse wheel, so that's maybe just the way it should be.

This issue is mainly about the issue of smooth scrolling with touchpads (1-to-1 scrolling, like on phones) and high-precision mouse wheels (these are rare, but they act exactly like a touchpad).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1955">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
