### ISSUE TITLE
How to place the window in the upper right corner of the screen and keep the window always in the upper right corner of the current screen when the user switches the screen (MAC)

### ISSUE THREAD

**Issue by RubiTree** [JetBrains/compose-multiplatform#1956]
To place the window in the upper right corner of the screen, I need to be able to obtain the size of the screen. I can get it on Android, but I can't find the corresponding API on Desktop.

When the user switches the screen, the window is always in the upper right corner of the current screen. It needs to be able to perceive the user's switching screen operation and reposition the window. No relevant tutorials are found.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1956">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
