### ISSUE TITLE
public setContent(parentComposition, onPreviewKeyEvent, onKeyEvent, content)

### ISSUE THREAD

**Issue by smallshen** [JetBrains/compose-multiplatform#1959]
![image](https://user-images.githubusercontent.com/39912494/158716928-2ebbee85-5638-4164-83e8-ee4fb658dd8b.png)
This method is internal

Usecase: Top-level key events in a custom ComposeScene

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1959">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
