### ISSUE TITLE
Initial steps on setup KMM projects which include ios, android, web application, desktop

### ISSUE THREAD

**Issue by antranvn** [JetBrains/compose-multiplatform#1963]
Hey team,
I saw the great example here: https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp.
Can you give the tutorial on initial steps for setting up the project:
1. What is IDE for this kind of project.
2. Detail steps to setup an empty project.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1963">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
