### ISSUE TITLE
Compose UI platform scroll on web and native.

### ISSUE THREAD

**Issue by luca992** [JetBrains/compose-multiplatform#1967]
I've been trying out the alpha releases of compose ui for web and native. It has been working great, and I'm really excited for the initial release! The only issue I've had with it is the lack of scrolling support, as it has [not been implemented yet in androidx](https://github.com/JetBrains/androidx/blob/jb-main/compose/foundation/foundation/src/jsMain/kotlin/androidx/compose/foundation/gestures/DesktopScrollable.js.kt)

I was wondering if you guys have any sort of timeline for a compose ui build with a scrolling implementation? And if it's a ways off, would you take community contributions for it's implementation?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1967">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
