### ISSUE TITLE
Can't render image: load image failed

### ISSUE THREAD

**Issue by BreimerR** [JetBrains/compose-multiplatform#1968]
Is there a way to catch this instead of the printed message?

Icon(loadSvgPainter(inputStream),"Content")

Use case rendering SVG's in a directory would want to skip unsupported files instead of getting a black Icon view

![image](https://user-images.githubusercontent.com/25663524/159167012-efeeb281-e144-4a20-aaf5-ed9287aff9d3.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1968">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
