### ISSUE TITLE
Web Testing: Use kotlinx-coroutine-test virtual time skipping scheduler

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-multiplatform#1970]
The new kotlinx-coroutine-test package supports a time skipping scheduler and exports this skipping `TimeSource` via `testTimeSource`.

```kt
val flow = flow {
    emit(1)
    delay(10.seconds)
    emit(2)
}

@Test
fun toTest() = runTest {
    composition {
        val counter = remember { flow }.collectAsState(0).value
        Text("$counter")
    }
    assertEquals("0", root.innerHTML)
    delay(10.seconds)
    waitForRecompositionComplete()
    assertEquals("2", root.innerHTML)
}
```
To test this composable, you need to wait 10 seconds. The current karma timeout is 2 seconds. Instead changing the timeout, it would be nice, if the test could support time skipping.

**Comment by eymar** [comment]
In general this makes sense. I'll look into it.

Just to be sure: is `delay(10.seconds)` just for an example? I don't see a need to use delay(...) in that case.

**Comment by hfhbd** [comment]
@eymar Yes, it is just an example.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1970">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
