### ISSUE TITLE
createDistributable produces duplicated skiko-awt.jar and skiko-awt-runtime-windows-x64.jar

### ISSUE THREAD

**Issue by mcpiroman** [JetBrains/compose-multiplatform#1971]
Project: default minimal desktop template
OS: Windows 10

The produced distributable (build/compose/main/app/name/app) has, beside stdlib, compose jars etc., two files:
-skiko-awt-0.7.16-ac2aad883d25328b57c14462e1dbf7fa.jar
-skiko-awt-runtime-windows-x64-0.7.16-77be4ee89592fdb7cbb2f5436a94b5d.jar

They are nearly identical, it seems the only difference is in line encoding of `not-supported-adapter.list` file inside the archive.

Besides wasted space, this duplication creates problems with tools like proguard.

**Comment by mcpiroman** [comment]
This is because skiko publishes, among others, two jars: `skiko-awt.jar` and `skiko-awt-runtime-platform-arch.jar`, where the letter = the former + platform specific files. Apparently, clients are meant to only use the letter one (or `skiko.jar` as a common divider), while CfD declares dependency on both.

**Comment by AlexeyTsvetkov** [comment]
Yeah, I understand, why it happens. I don't see a clean solution, but we could be able to make a hacky workaround

**Comment by mcpiroman** [comment]
Cannot we remove the source of this dependency, some `implementation("skiko-awt")` I suppose, and leave `implementation("skiko-awt-runtime-platform-arch")`? Or at least change it to `compileOnly`.

**Comment by mcpiroman** [comment]
To be verified but https://github.com/JetBrains/skiko/pull/608 should have fixed it.
