### ISSUE TITLE
Support for custom WXS entries during MSI packaging

### ISSUE THREAD

**Issue by dmvanderuit** [JetBrains/compose-multiplatform#1972]
Hi,

I've got a question regarding the packaging of the application. In the [section on native distributions](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution), the docs mention that the packaging uses JPackage under the hood. In JPackage, it's possible to [further customise the installer using WXS files](https://stackoverflow.com/a/71050276). Is this something that is supported in the packaging of MSI packages run by the Gradle task in Compose too?

Thanks in advance.

**Comment by sebkur** [comment]
I think this might already be possible. In [AbstractJPackageTask.kt](https://github.com/JetBrains/compose-jb/blob/master/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/tasks/AbstractJPackageTask.kt) we already have

```kotlin
if (targetFormat != TargetFormat.AppImage) {
    …
    cliArg("--resource-dir", jpackageResources)
    …
}
```

where `jpackageResources` is defined here:

```kotlin
@get:LocalState
protected val jpackageResources: Provider<Directory> = project.layout.buildDirectory.dir("compose/tmp/resources")
```

so apparently `compose/tmp/resources` is passed to `jpackage` via `--resource-dir` and files to modify the input for Wix creating the `msi` such as a modified `main.wxs` could be copied there.

**Comment by sebkur** [comment]
ah, well, OK, but then there's also `cleanDirs(jpackageResources)` executed during `prepareWorkingDir`, so essentially anything we copy to `compose/tmp/resources` to modify the input data for Wix will be deleted before running `jpackage`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1972">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
