### ISSUE TITLE
How to add a desktop shortcut (or direct access) on windows installer

### ISSUE THREAD

**Issue by kmenesesp** [JetBrains/compose-multiplatform#1974]
I need to add a desktop shortcut when installing my application, is there any option or workaround to do this?

![image](https://user-images.githubusercontent.com/60014455/159757276-61a62cdf-0fd5-4736-b576-fc8ec61508be.png)

I need something like that, thank you.

**Comment by JuanOrtegaT** [comment]
Can somebody answer if this is already possible or in plans to be implemented?

**Comment by kmenesesp** [comment]
it seems that you can set this in a property as true:

`compose.desktop {
    application {
        nativeDistributions {           
            windows {
                shortcut = true
            }
        }
    }
}`

**Comment by kmenesesp** [comment]
There is something weird about the shortcut property, it creates the shortcut automatically without giving the option to the user to select if he wants a shortcut or not.

**Comment by tetexxr** [comment]
Any news about this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1974">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
