### ISSUE TITLE
Can't use Material3 Card

### ISSUE THREAD

**Issue by gnawf** [JetBrains/compose-multiplatform#1978]
I can see `Card`, `ElevatedCard` and `OutlinedCard` under `CardKt.class` in the material3 library but I can't access any of them even though they're public.

I'm using Compose 1.1.0 and the material3 library version is 1.0.0-alpha05

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1978">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
