### ISSUE TITLE
LazyListState scrolling with keyboard

### ISSUE THREAD

**Issue by memonahmedanees** [JetBrains/compose-multiplatform#1981]
hi my question is simple ,  when i scroll with lazy column working fine with mouse but key when i use keyboard to scroll down only scroll with visible screen items not down

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1981">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
