### ISSUE TITLE
How to get currentOs And packageName in code?

### ISSUE THREAD

**Issue by wznshuai** [JetBrains/compose-multiplatform#1985]
I need know currentOs to make my app reboot, but I can't find right way to get currentOs .

**Comment by dmondon-accor** [comment]
Hi @wznshuai, did you succeed finding currentOs in code?

**Comment by m-sasha** [comment]
You can get the OS from `org.jetbrains.skiko.hostOs`.

**Comment by m-sasha** [comment]
As for the package name, you can "pass" it to yourself from the `build.gradle` file via something like [com.github.gmazzo.buildconfig](https://github.com/gmazzo/gradle-buildconfig-plugin)
