### ISSUE TITLE
isSystemInDarkTheme should dynamically update when system theme is changed

### ISSUE THREAD

**Issue by PhilipDukhov** [JetBrains/compose-multiplatform#1986]
I'm using **macOS** **12.0.1** and **Compose** **1.1.1**

I'm running this basic view:
```
Box(
    Modifier.fillMaxSize()
        .background(
            if (isSystemInDarkTheme()) Color.Black else Color.White
        )
)
```
It shows a correct value, but when I change the theme it doesn't update. Window top bar color is updated, but the view is not recomposed. I need to re-run the app to apply theme changes.

[Video](https://www.youtube.com/watch?v=-GeD-tPktjI)

**Comment by egorikftp** [comment]
Sample code snipped with proposed solution: https://github.com/egorikftp/LadyHappy-Admin/blob/577c173cbf0ccf49417ea0084315a55ff1f7da9d/desktop/src/jvmMain/kotlin/theme/LadyHappyDesktopTheme.kt#L24

All you need is to call **rememberDesktopDarkTheme** function 🙂

**Comment by Cricin** [comment]
anyone knows how to makes the title bar dark in win10? compose window seems always created with a white title bar, a white title bar with dark content looks very strangely. is there a solution for it?

**Comment by akilajwasala** [comment]
Make sure you haven't set the night mode programmatically
`AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)`

**Comment by Mats-Hjalmar** [comment]
Is there a solution for this on iOS devices?

**Comment by MatkovIvan** [comment]
For iOS, it has been already fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/715 (included into [1.5.0](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0))

**Comment by Mats-Hjalmar** [comment]
Thank you, @MatkovIvan. Will test later.

**Comment by PMARZV** [comment]
@MatkovIvan this is not exclusive of macos, in windows there is the same problem. isSystemInDarkTheme() is like a constant that stays with the value initted, thoughout the entire app "lifecycle".
Actual Windows Implementation (in Skiko SystemTheme.awt.kt): 
````
actual val currentSystemTheme: SystemTheme
    get() = when (SystemThemeHelper.getCurrentSystemTheme()) {
        0 -> SystemTheme.LIGHT
        1 -> SystemTheme.DARK
        else -> SystemTheme.UNKNOWN
    }

private object SystemThemeHelper {
    init {
        Library.load()
    }

    external fun getCurrentSystemTheme(): Int
}
````

**Comment by m-sasha** [comment]
You can use this utility: https://kotlinlang.slack.com/archives/C01D6HTPATV/p1706915254041629?thread_ts=1706910745.532729&channel=C01D6HTPATV&message_ts=1706915254.041629

**Comment by PMARZV** [comment]
Cant access link!

**Comment by ZacSweers** [comment]
Pasting what was linked

```kotlin
package theorycrafter.utils

import androidx.compose.runtime.*
import androidx.compose.ui.SystemTheme
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import org.jetbrains.skiko.currentSystemTheme


/**
 * Returns whether the system's color theme is a dark one.
 */
@Composable
@ReadOnlyComposable
fun isSystemThemeDark(): Boolean {
    return LocalSystemTheme.current == SystemTheme.Dark
}


/**
 * A composition local for the system theme.
 */
val LocalSystemTheme = staticCompositionLocalOf<SystemTheme> {
    error("System theme not provided")
}


/**
 * Provides the system theme.
 */
@Composable
fun ProvideSystemTheme(content: @Composable () -> Unit) {
    val systemTheme by produceState(initialValue = currentSystemTheme.asComposeSystemTheme()) {
        // Launch on a thread other than the event dispatching thread because tests typically
        // wait for the event dispatching thread to become idle.
        // Running this in the event dispatching thread means it will never be idle.
        launch(Dispatchers.IO) {
            while (true) {
                delay(1000)
                value = currentSystemTheme.asComposeSystemTheme()
            }
        }
    }

    CompositionLocalProvider(LocalSystemTheme provides systemTheme) {
        content()
    }
}


/**
 * Converts Skiko system theme type to Compose [SystemTheme].
 */
private fun org.jetbrains.skiko.SystemTheme.asComposeSystemTheme() : SystemTheme {
    return when (this) {
        org.jetbrains.skiko.SystemTheme.DARK -> SystemTheme.Dark
        org.jetbrains.skiko.SystemTheme.LIGHT -> SystemTheme.Light
        org.jetbrains.skiko.SystemTheme.UNKNOWN -> SystemTheme.Unknown
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1986">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
