### ISSUE TITLE
Problem in Window with size=DpSize.Unspecified on undecorated windows

### ISSUE THREAD

**Issue by amir1376** [JetBrains/compose-multiplatform#1995]
as I saw in `WindowState::size` if height or width is set to  Dp.Unspecified
window should size itself equal to its content (width or height or both)
but this is just work on decorated 

```kotlin
val state = rememberWindowState(
     size = DpSize.Unspecified,
)
Window(
    state = state,
    undecorated = true,
    onCloseRequest = onCloseRequest
) {
    Text("text")
}
```
in that above code .window ,instead of size itself as its content size
it will size itself as entire screen size!

is this a bug?
if it is not. what should we do to handle this?

**Comment by lucasm997** [comment]
+1

Did you manage to solve this? I'm also trying to make window behave like wrap content, but i'm having trouble doing so

**Comment by mahozad** [comment]
Relate?: https://github.com/JetBrains/compose-jb/issues/986

**Comment by m-sasha** [comment]
This appears to be a duplicate of https://github.com/JetBrains/compose-jb/issues/2676

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1995">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
