### ISSUE TITLE
Implement all supported color spaces in Compose

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#20]
See ColorSpaces. We implemented part of them in DesktopImageAsset.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5625">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6390">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
