### ISSUE TITLE
Ability to change implementation of Dialog/Popup

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2000]
Compose 1.1.1

Currently, when we use Dialog or Popup, we use hard-coded implementation:
- to open a Dialog we use native platform window
- to open a Popup we just draw the content of the popup over all other content on Canvas.

This prevents usage of Dialog/Popups in the other implementations of Compose:
- LWJGL
- ui-test

These implementations use ComposeScene under the hood. We need to invent some API, which allows to specify the factory for creating Dialogs/Popups, and pass it via ComposeScene constructor, or as a CompositionLocal.

**Comment by AlexeyTsvetkov** [comment]
A relevant issue https://github.com/JetBrains/compose-multiplatform/issues/2924

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2000">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
