### ISSUE TITLE
Broken transparency in maximized mode

### ISSUE THREAD

**Issue by TheDome0** [JetBrains/compose-multiplatform#2001]
When the parent windows placement is `WindowPlacement.Floating` below code works as expected and the dialog window is transparent. However, `WindowPlacement.Maximized` breaks the transparency and all I get is a plain black background.

```
Dialog(
        onCloseRequest = { isOpen = false },
        undecorated = true,
        state = dialogState,
        transparent = true,
    ) {
        Box(
            modifier = Modifier.fillMaxSize().background(Color.Black.copy(alpha = 0.5f)),
        )
```
So this is what I want it to look like:
![image](https://user-images.githubusercontent.com/85122272/162999934-80242280-7cc6-4aac-b3a2-0607926779ab.png)

Now, if I switch to a different application while having it maximized, the dialog becomes transparent. Switching back leaves it transparent until I e.g. hover over a button within the box

**Comment by TheDome0** [comment]
I also noticed that attempting to open the dialog after moving the entire window to a different screen freezes the application.

`state = rememberWindowState(width = 1280.dp, height = 800.dp, placement = WindowPlacement.Floating)`
`dialogState = rememberDialogState(size = state.size, position = state.position)`

this only happens if the dialog is transparent, it works fine if `transparent = false`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2001">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
