### ISSUE TITLE
High CPU usage with focused TextField on Linux

### ISSUE THREAD

**Issue by RocketJannis** [JetBrains/compose-multiplatform#2002]
As long as a TextField is focused on Linux it will consume 100% of one core/thread of my CPU.

This does not occur if a textfield is on the screen but not focused or another window is focused. Also, it does not happen on Windows.

System: amd64 Linux Mint / Cinnamon
Compose versions: tested with 1.1.1, 1.2.0, 1.4.0 but was already there on 1.0.0 beta builds

Also tested on: Fedora / Gnome/Wayland (here it "just" uses 40-60% of one core)

If someone knows how I can provide additional information on this, I would be my pleasure to help :)

**Comment by XilinJia** [comment]
Wow, so I didn't get to be the first to report it.

The same is happening with me on Ubuntu 22.04 with Compose 1.1.1.

Both TextField and OutlinedTextField have the problem.  Once they have focus, the entire UI is very lagging.

```
                            var lag by remember { mutableStateOf("0") }
                            OutlinedTextField(
                                value = lag,
                                modifier = Modifier.width(100.dp),
                                onValueChange = { lag = it },
                                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                                placeholder = { Text(text = "lag") },
                            )

```

**Comment by kkmoskalenko** [comment]
I can confirm the same issue is present on macOS 12.2.1 as well.

**Comment by ialokim** [comment]
Seems related to #1054, and especially to the comment https://github.com/JetBrains/compose-jb/issues/1054#issuecomment-940964569.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2002">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
