### ISSUE TITLE
WindowDraggableArea not working with mouseClickable()

### ISSUE THREAD

**Issue by Jeansen** [JetBrains/compose-multiplatform#2003]
If I have a dragable Area but also would like to have an action, e.g. when the user right-clicks somewhere, I thought something like this would work:

```
WindowDraggableArea {
  Box(
      Modifier.fillMaxWidth().fillMaxHeight().background(Color.Transparent).mouseClickable(
          onClick = {
              if (buttons.isSecondaryPressed) println("right click")
          }
      ),
  )
  }
```

I can see the "right click", but I can no longer drag my window with this. If I am missing something, any hint is appreciated.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2003">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
