### ISSUE TITLE
When we can expect Skia rendering for the web

### ISSUE THREAD

**Issue by JimeFuture** [JetBrains/compose-multiplatform#2006]
Is there a roadmap somewhere where we could find information about the planned features and their expected release time?

**Comment by ScottPierce** [comment]
Canvas rendering for web looks like it's being worked on now. You can check it out in it's samples for Compose 1.2. The Compose 1.2 is the first chance we have of seeing any web or ios canvas rendering in any preview form.

You can already go to the experimental features and try them out though.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2006">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
