### ISSUE TITLE
UI thread is blocked on Linux when display is in power saving mode

### ISSUE THREAD

**Issue by akwizgran** [JetBrains/compose-multiplatform#2010]
Thanks for making this amazing UI framework. :-)

When Compose is running on Linux with XOrg, the Swing UI thread is blocked while the display is in power saving mode. This doesn't happen with plain Swing. Here's a minimal test app that can be used to reproduce the issue and show that it doesn't happen with plain Swing:

https://code.briarproject.org/akwizgran/ui-thread-blocked

I can reproduce the issue locally with my laptop's internal display or an external monitor, and a colleague can also reproduce it, but I guess it may be hardware-specific in some way.

**Comment by akwizgran** [comment]
My local setup:

* Debian Bullseye
* XOrg 7.7
* XFCE 4.16
* Lenovo ThinkPad X270
* ASUS VC239H monitor connected via HDMI

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2010">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
