### ISSUE TITLE
Binary distributable package can not access class loader resource

### ISSUE THREAD

**Issue by shaokeyibb** [JetBrains/compose-multiplatform#2011]
First,if there's a json file in `src/main/kotlin/resources/locales/en_US.json`, and when I try to access this file or its inputstream by using the distributeable package, it always return null. Neither Using jar distribution nor execute the `run` task have these matter.
I tried these way to acess the file:
- `this::class.java.getResource`
- `androidx.compose.ui.res.useResource`
- `ClassLoaderResourceLoader.load`

Information:
- Kotlin Version: 1.6.10
- Java Version: OpenJDK 17.0.2
- Compose Version: 1.1.1

build.gradle.kts:
```Kotlin
import org.jetbrains.compose.compose
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    id("java")
    kotlin("jvm") version "1.6.10"
    id("org.jetbrains.compose") version "1.1.1"
}

version = "1.0.0"

repositories {
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    google()
}

dependencies {
    implementation(compose.desktop.currentOs)
    implementation("com.google.code.gson:gson:2.9.0")
    implementation("com.squareup.okhttp3:okhttp:4.9.3")
}

tasks.withType(KotlinCompile::class) {
    kotlinOptions.jvmTarget = "17"
    kotlinOptions.freeCompilerArgs += listOf("-opt-in=kotlin.RequiresOptIn")
}

compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageVersion = version as String
        }
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2011">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
