### ISSUE TITLE
CursorDropdownMenu is not taking new position after fast click

### ISSUE THREAD

**Issue by PhilipDukhov** [JetBrains/compose-multiplatform#2012]
I'm using the following code to show a menu on right clicks:
```kotlin
var expanded by remember { mutableStateOf(false) }
Box(
    Modifier
        .fillMaxSize()
        .mouseClickable {
            if (buttons.isSecondaryPressed) {
                expanded = true
            }
        }
)
CursorDropdownMenu(
    expanded = expanded,
    onDismissRequest = {
        expanded = false
    }
) {
    Text("Hi")
}
```
The problem is that when I click and release the button too fast, during `CursorDropdownMenu` disappearing transition, it appears on the old position.

![res](https://user-images.githubusercontent.com/6103621/163703442-496d042f-3b1a-4a9e-b29b-790ca683f0f1.gif)

I ended up using this workaround to also keep the disappearance transition, but I think it should work that way out of the box:
```kotlin
var renderCount by remember { mutableStateOf(0) }
listOf(renderCount, renderCount - 1).forEach { renderId ->
    val isActive = renderId == renderCount
    key(renderId) {
        CursorDropdownMenu(
            expanded = expanded && isActive,
            onDismissRequest = {
                if (isActive) {
                    renderCount += 1
                    expanded = false
                }
            },
        ) {
            Text("Hi")
        }
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2012">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
