### ISSUE TITLE
Example of using from Java

### ISSUE THREAD

**Issue by staypufd** [JetBrains/compose-multiplatform#2016]
Glad to see a new framework based on Android Compose. I’d like to see an example of using it from
Java like they have on Android.

**Comment by Winterreisender** [comment]
You may check this question in StackOverflow: https://stackoverflow.com/questions/66433437/can-i-write-jetpack-compose-components-in-java

The best answer of that question is:

> No, you can't write Jetpack Compose components in Java, and there are no future plans to allow this (source: I work on Compose). Note that this is not the same thing as using components created in Compose from a Java app, which [is possible](https://developer.android.com/jetpack/compose/interop).
> Jetpack Compose makes heavy use of Kotlin features such as coroutines, and `@Composable` methods require transformations that are done by a Kotlin compiler plugin. There is no way to get access to these from Java.
> [Ryan M](https://stackoverflow.com/users/208273/ryan-m) answered Mar 2, 2021 at 5:06

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2016">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
