### ISSUE TITLE
"gradle package" task throws error, when description is Cyrillic

### ISSUE THREAD

**Issue by DareFox** [JetBrains/compose-multiplatform#2021]
When description in `nativeDistributions` is written in Cyrillic, `"gradle package"` throws error: 
```
External tool execution failed:
External tool execution failed:
* Command: [C:\Users\DareFox\.jdks\openjdk-17.0.2\bin\jpackage.exe, @C:\workspace\Kotlin\SaveDTF-Compose\build\compose\tmp\packageMsi.args.txt]
* Working dir: []
* Exit code: 1
* Standard output log: C:\workspace\Kotlin\SaveDTF-Compose\build\compose\logs\packageMsi\jpackage-2022-04-20-14-51-07-out.txt
* Error log: C:\workspace\Kotlin\SaveDTF-Compose\build\compose\logs\packageMsi\jpackage-2022-04-20-14-51-07-err.txt
```

![изображение](https://user-images.githubusercontent.com/47672780/164224391-70ff4d8f-3fc0-4d37-8d39-bce6afa1d338.png)

If I remove description or change it to English, it'll work

![изображение](https://user-images.githubusercontent.com/47672780/164225013-942497ec-6d2e-4cc4-8dde-113ff1fe5441.png)

Arguments for external tool (`jpackage.exe`):
```
--input
"C:\\workspace\\Kotlin\\SaveDTF-Compose\\build\\compose\\tmp\\packageMsi\\libs"
--runtime-image
"C:\\workspace\\Kotlin\\SaveDTF-Compose\\build\\compose\\tmp\\main\\runtime"
--resource-dir
"C:\\workspace\\Kotlin\\SaveDTF-Compose\\build\\compose\\tmp\\resources"
--java-options
"'-Dcompose.application.resources.dir=$APPDIR\\resources'"
--main-jar
"C:\\workspace\\Kotlin\\SaveDTF-Compose\\build\\compose\\tmp\\packageMsi\\libs\\saveDTF-compose-1.0.0-93dca718aae942fc15036ffba508c5.jar"
--main-class
"MainKt"
--icon
"C:\\workspace\\Kotlin\\SaveDTF-Compose\\src\\main\\resources\\img\\DTF_logo.ico"
--java-options
"'-Dcompose.application.configure.swing.globals=true'"
--java-options
"'-Dskiko.library.path=$APPDIR'"
--resource-dir
"C:\\workspace\\Kotlin\\SaveDTF-Compose\\build\\compose\\tmp\\resources"
--win-dir-chooser
--win-upgrade-uuid
"71454f6a-55e9-44d8-830b-59ca8fc9f418"
--type
"msi"
--dest
"C:\\workspace\\Kotlin\\SaveDTF-Compose\\build\\compose\\binaries\\main\\msi"
--name
"SaveDTF"
--description
"Забекапь все свои (и не только свои) статьи при помощи одной кнопки!"
--app-version
"1.0.0"
--vendor
"DareFox"
```

External tool error log: 
```
Input length = 1
```

Standard output of external tool is empty

**Comment by ltttttttttttt** [comment]
The packageExe command I used also reported this error, Is it solved?

**Comment by ltttttttttttt** [comment]
My suppliers and copyrights contain Chinese, so they cannot be packaged. It can be packaged when it does not use Chinese

**Comment by sunny-chung** [comment]
I start to encounter this issue after upgrading IntelliJ IDEA to 2023.2. If I change to build via `gradlew` command, it succeeds even if there is a non-ASCII character.

**Comment by gutnikvk** [comment]
Running into the same problem, any updates?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2021">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
