### ISSUE TITLE
Rescaling image with modifier makes it "pixelated"

### ISSUE THREAD

**Issue by DareFox** [JetBrains/compose-multiplatform#2026]
When I rescale the image with modifier attribute, the image looks sharp, pixelated. Like no anti-aliasing was applied to it.
Also, I tried to downscale image file to 150px, to see if it'll look sharp too, but no. It looks normal

![java_E0necAxe5F](https://user-images.githubusercontent.com/47672780/164257565-0efb9774-1a23-4b67-83fb-84253f6c555f.png)
```kotlin
fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
    ) {
        Column() {
            Image(painterResource("img/test.png"), null,  Modifier.size(150.dp, Dp.Unspecified))
            Image(painterResource("img/150px.png"), null)
        }
    }
}
```
Images used in test: [images.zip](https://github.com/JetBrains/compose-jb/files/8522551/images.zip)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2026">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
