### ISSUE TITLE
Is Kotlin/JS DCE working in a Compose for Web project?

### ISSUE THREAD

**Issue by ShreckYe** [JetBrains/compose-multiplatform#2033]
In an ordinary Kotlin/JS project or an ordinary Kotlin Multiplatform project with a JS target, Kotlin/JS DCE is enabled by default, and there is a folder at "build/js/packages/\<project-name\>/kotlin-dce" containing its output and disabling it does make a difference in the size of the generated JS bundle file in "build/distributions". In a Compose for Web project, such a folder is missing, and disabling DCE doesn't seem to make a difference.

However, when manually adding a dummy function that's not used, the generated JS bundle doesn't get bigger.

These experiments led to 2 questions of mine about Compose for Web projects:
1. Is Kotlin/JS DCE working properly for all code?
1. is [the official way of disabling DCE](https://kotlinlang.org/docs/javascript-dce.html#disable-dce) working?

Sorry to have asked such questions here, but I have been trying to reduce the JS bundle size which is 2 MB with all the dependencies, and I couldn't find any related docs in the repository.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2033">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
