### ISSUE TITLE
Gradle task packageExe fails on subtask unzipWix on WIndows

### ISSUE THREAD

**Issue by oxiadenine** [JetBrains/compose-multiplatform#2035]
If from a clean project you execute the `:packageExe` task, it fails with an error, and as you can notice, it seems that the error is related with the ZIP name, since it tries to unzip something that is not a ZIP file.

![jb-compose-issue-winzip-1 1](https://user-images.githubusercontent.com/12253808/164915866-e0e138d9-0257-413a-a1cb-f344461dd42d.png)

![jb-compose-issue-winzip-1 2](https://user-images.githubusercontent.com/12253808/164914779-945922cf-6bf0-492c-bda4-228899001b24.png)

Also, if I rename the real ZIP file to the expected name for the `:unzipWix` task, it fails anyway with another error, and this is a known error related with Gradle wrapper starting from some version, where something like `duplicatesStrategy = DuplicatesStrategy.EXCLUDE` is necessary to work.

![jb-compose-issue-winzip-2 1](https://user-images.githubusercontent.com/12253808/164914905-9402270a-350c-4022-b412-575be8bd28e0.png)

![jb-compose-issue-winzip-2 2](https://user-images.githubusercontent.com/12253808/164914908-c2d03709-c4e3-4096-a4a4-9c405fb87658.png)

The Project where I'm having this issue is [https://github.com/sunlandx/chain-pass](https://github.com/sunlandx/chain-pass).

Windows 10
IntelliJ Community v2021.3
Gradle wrapper v7.4.2
Compose v1.1.1

**Comment by mcpiroman** [comment]
Probably the same as #1250. There is a walkaround here.

**Comment by samgarasx** [comment]
> Probably the same as #1250. There is a walkaround here.

Thank you, the workaround is working!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2035">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
