### ISSUE TITLE
Intermittent framerate drops when running from IntelliJ

### ISSUE THREAD

**Issue by zeruth** [JetBrains/compose-multiplatform#2038]
If running my app through IntelliJ, if the window is in focus, the framerate drops significantly (from 160 all the way down to as low as 40) every couple seconds. It makes the game unplayable and doesn't affect packaged builds.

Here is an example, the foreground is IntelliJ, background is exe with the same exact configuration.
![VaNIfmDQtU](https://user-images.githubusercontent.com/2943260/165202926-f4f0277f-56b4-48e6-acfe-a1449ae4aecb.gif)

While I would be open to the idea that this is IntelliJ's fault, I NEVER had this issue before switching to Compose desktop, and the issue persists irregardless of iJ / jdk / kotlin / compose versions

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2038">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
