### ISSUE TITLE
How can I use Kotlin standard function in the Web application

### ISSUE THREAD

**Issue by antranvn** [JetBrains/compose-multiplatform#2039]
Let's say I want to use Kotlin standard function for the web application. For example, I want to use `String.format()` which is not available in `String` class of `org.jetbrains.kotlin:kotlin-stdlib-js`, for example in the `web-landing` project. How can I use it?

**Comment by hfhbd** [comment]
You can use every Kotlin/JS function/class from the standard lib, but https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/format.html is JVM only and is not related to Compose (Web).
