### ISSUE TITLE
Can‘t set DMG file .VolumeIcon.icns

### ISSUE THREAD

**Issue by huiyh** [JetBrains/compose-multiplatform#2042]
In gradle plugin org.jetbrains.compose:1.0.1，when invoke comand jpackage, lacks the parameter  --icon 

At AbstractJPackageTask

  if (targetFormat != TargetFormat.AppImage) {
    XXXXXX
  }

**Comment by huiyh** [comment]
You can see jpackage parameters result in file： build/compose/tmp/packageDmg.args.txt

**Comment by huiyh** [comment]
--app-image
"/Users/xxx/Projects/Compose/XXXX/build/compose/binaries/main/app"
--resource-dir
"/Users/xxx/Projects/Compose/XXXX/build/compose/tmp/resources"
--type
"dmg"
--dest
"/Users/xxx/Projects/Compose/XXXX/build/compose/binaries/main/dmg"
--name
"XXXX"
--description
"XXXX"
--copyright
"©2022 XX"
--app-version
"1.0.0"
--vendor
"XXX"
--mac-package-name
"XXXImporter"
--mac-package-identifier
"com.xx.devops.xxx"

**Comment by xinkunZ** [comment]
+1

**Comment by heytherewill** [comment]
The (disgusting) but solid workaround that I found is to patch it up myself with a nasty bash script, something among the lines of this:

```bash
#Creates a .dmg we can write to
hdiutil convert -format UDRW -o rw_your_app.dmg "./build/compose/binaries/main/dmg/your_app-1.0.0.dmg"

# Changes the .dmg file icon 
cp ./src/main/resources/app_icon.icns icon.icns
sips -i ./icon.icns
DeRez -only icns ./icon.icns > icns.rsrc
Rez -append icns.rsrc -o rw_your_app.dmg
SetFile -a C rw_your_app.dmg

# Changes the volume icon
hdiutil attach rw_your_app.dmg
sudo cp ./src/main/resources/app_icon.icns '/Volumes/your_app/.VolumeIcon.icns'
SetFile -a C '/Volumes/your_app/'
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2042">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Shabinder** [comment]
```
tasks.withType<AbstractJPackageTask>().all {
    if (targetFormat == TargetFormat.Dmg) {
      freeArgs.addAll("--icon", "path_to_icon_mac.icns")
    }
  }
```

If anyone comes across, this will do the trick 🙌
