### ISSUE TITLE
TextField swallowing input if typing too fast

### ISSUE THREAD

**Issue by YiffyToys** [JetBrains/compose-multiplatform#2052]
It seems on longer input (> about 10 characters) happening very fast from a hardware keyboard
e.g. from a barcode reader
the TextField component starts to garble the input.

Some characters are swallowed (in the middle as well as at the start of the input)
while additional characters that aren't part of the input are added behind the cursor.

Example:

```
var intermediateSearchTerm by remember { mutableStateOf("") }
TextField(
            value = intermediateSearchTerm,
            label = { Text(searchTerm) },
            onValueChange = { value ->
                val temp = value.replace('\n', ' ').replace('\r', ' ')
                if (!intermediateSearchTerm.contentEquals(temp)) {
                    intermediateSearchTerm = temp
                }
            },
            singleLine = true
        )
```

This may or may not be related to
https://issuetracker.google.com/issues/200577798
or
https://issuetracker.google.com/issues/206656075 fixed Feb 9, 2022

**Comment by gsrathoreniks** [comment]
@YiffyToys did you find any solution for this?

**Comment by YiffyToys** [comment]
> @YiffyToys did you find any solution for this?

We updated our internal app and can no longer reproduce this issue with the current release.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2052">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
