### ISSUE TITLE
[Web] DOM effects race conditions

### ISSUE THREAD

**Issue by mpetuska** [JetBrains/compose-multiplatform#2053]
Currently, we have two ways to reach native HTML element from compose-web context:
1. `AttrsScope::ref`
2. `ElementScope::DisposableEffect`

However, it seems that #⁠2 are applied before #⁠1.

I believe applying #⁠1 before #⁠2 makes a lot more sense.
My reasoning for such order is that `attrs` (i.e. #⁠1) are part of HTML Element's "metadata" and as such should be resolved before the `content` (i.e. #⁠2)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2053">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
