### ISSUE TITLE
jlink strip-native-commands

### ISSUE THREAD

**Issue by lucasmeneghin** [JetBrains/compose-multiplatform#2057]
I'd like to be able to keep native commands on the runtime image.

Only workaround i found so far was debuigging AbstractJLinkTask and manually setting stripNativeCommands default value to false when instantiating the property.

**Comment by lucasm997** [comment]
If someone point the way i can make a PR

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2057">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
