### ISSUE TITLE
Is it possible to activate Aero Snap when using the undecorated option?

### ISSUE THREAD

**Issue by GreatWolfXX** [JetBrains/compose-multiplatform#2062]

**Comment by mahozad** [comment]
The below solution will probably get you in the right direction.
I think you should implement the hit test function in the `CustomWindowProcessor` as was implemented in the Swing (JFrame) version linked in the comment:

- https://github.com/JetBrains/compose-multiplatform/issues/3388#issuecomment-1672732504

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2062">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
