### ISSUE TITLE
Support live edit please.

### ISSUE THREAD

**Issue by wwalkingg** [JetBrains/compose-multiplatform#2063]
Jetpack Compose has supported **live edit** already. what's the plan of compose-multiplatform?

**Comment by hm-tamim** [comment]
Any update on this? Pretty important

**Comment by bartekpacia** [comment]
Hi, I'm also very interested in this feature. Live Edit seems to be one of the great features of Compose on Android, and since Compose Multiplatform on Android is basically Compose, how can we take advantage of it?

It's quite surprising to me there's no mention of it anywhere.

**Comment by juhaodong** [comment]
no comment?

**Comment by adrianegraphene** [comment]
Add me to the list. Would be so great for workflows.....

**Comment by levrik** [comment]
After I had a very bad time trying React Native I wanted to go a bit more native so I tried Compose Multiplatform. Not having some kind of hot reload is shocking to me. Iteration times, especially when still learning, are awfully slow and I can't believe this is not supported.

**Comment by cempack** [comment]
Same for me, planned to learn Compose Multiplatform, but Android Studio and KMP are such a mess. It feels like coding in Java with its horrible build times and incomprehensible errors. Dammit, I thought Kotlin was the better replacement for Java! A modern language should not require a bloated IDE to be able to run a simple Hello World!

**Comment by etolstoy** [comment]
We're working on building the best possible experience for working with Compose Multiplatform in Fleet. Starting with Fleet 1.31, we offer [support for previews](https://www.jetbrains.com/help/fleet/getting-started-with-kotlin-multiplatform.html#-dxt9e_76) for composable functions in common and desktop source sets. These previews automatically update with code changes, significantly reducing the feedback loop. We are eager to hear your feedback, so please submit any feature requests or feedback in [our Fleet tracker](https://youtrack.jetbrains.com/issues/FL).

As for LiveEdit, it is not currently on our roadmap. If you have specific use cases where Previews are insufficient and LiveEdit would work better, please let us know.

**Comment by bartekpacia** [comment]
@etolstoy fyi, `@Preview` performance is really bad on JB Fleet rn. On my M1 Mac it's so slow that sometimes it's faster to rebuild and re-run my simple app on Android emulator. I hope there are plans to optimize performance of it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2063">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
