### ISSUE TITLE
compose-web runtime error: `render$composable_634nic_k$ is not a function`

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-multiplatform#2067]
```
app.js:6393 Uncaught TypeError: $instance.render$composable_634nic_k$ is not a function
```
Reproducer:

```kotlin
fun main() {
	val instance = createRenderersComposableInstance {}
	renderComposable(rootElementId = "root") {
		instance.render() // this call fails
	}
}

interface RendersComposale {

	@Composable
	fun render()
}

fun createRenderersComposableInstance(
	render: @Composable () -> Unit
        // render: () -> Unit
): RendersComposale = object : RendersComposale {

	@Composable
	override fun render() {
		println("render from createRenderersComposableInstance")
		render()
	}
}
```
Prototype of `instance` has only `render_djxu4b_k$` function (no `render$composable_634nic_k$`).

making `render` lambda not composable `render: () -> Unit` makes `instance.render()` call work and Prototype of `$insance` has `render$composable_634nic_k$`.

Most likely, we need to look into how compose plugin (for k/js) processes `createRenderersComposableInstance` - not `@Composale` fun but with `@Composable` parameter + returning a value.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2067">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
