### ISSUE TITLE
window.printAll doesn't get right screenshot

### ISSUE THREAD

**Issue by Yan-CR** [JetBrains/compose-multiplatform#2068]
using Compose-Desktop, want to take a screenshot for a composable function, but there is no var like LocalView in Compose-Android.

I turn to java swing, using window in FrameWindowScope, and printAll, but the image content is empty, nothing like the actual window.

```
val i = BufferedImage(1500, 768, BufferedImage.TYPE_INT_ARGB)
val g = i.createGraphics()
window.printAll(g)
g.dispose()
ImageIO.write(i, "png", File("aaaa.png"))
```

Is there any other way to screenshot a composable function?

**Comment by onivas** [comment]
I am having the same issue, the saved image is white... anyone found a solution?

**Comment by bnovakovic** [comment]
The closest I came to taking screenshot is this:
```
val robot = Robot()
val img = robot.createScreenCapture(window.bounds)
val outputfile = File("saved.png")
ImageIO.write(img, "png", outputfile)
```
But this is not app (window) specific. If you move window to another monitor, size will be wrong. If your window is behind something, it will take screenshot of that too... etc. 

I hope it can help someone, at least temporary.

**Comment by onivas** [comment]
Thanks to @bnovakovic I come to this, where I was able to take a screenshot of a specific composable
 
   
    val robot = Robot()    
    val img = robot.createScreenCapture(frameWindowScope.window.bounds)
    val subImg = img.getSubimage(xStart, yStart, xEnd, yEnd) // <- take a sub image from the main one
    val outputfile = File("name.png")
    ImageIO.write(subImg, "png", outputfile)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2068">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
