### ISSUE TITLE
How to control the LazyColumn scroll velocity because default is too slow?

### ISSUE THREAD

**Issue by RubiTree** [JetBrains/compose-multiplatform#2086]
How to control the LazyColumn scroll velocity because default is too slow?

I just find flingBehavior about scroll but it is not the target.

Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2086">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
