### ISSUE TITLE
How to change ViewConfiguration in my @Composable function?

### ISSUE THREAD

**Issue by RubiTree** [JetBrains/compose-multiplatform#2095]
Because I want to change the ViewConfiguration#doubleTapTimeoutMillis on my button.
Thanks for help!

**Comment by andraantariksa** [comment]
+1. I also looking for a way to change the `minimumTouchTargetSize`.

**Comment by igordmn** [comment]
Will [this example](https://github.com/JetBrains/compose-jb/issues/343#issuecomment-775149957) help?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2095">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
