### ISSUE TITLE
Multiplatform template in IDEA / Android Studio. Compose classes are underlined in desktop module

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#21]
If we open multiplatform template in IDEA or Android studio (templates/multiplatform), all compose classes will be underlined:

"Class 'androidx.compose.runtime.MutableState' is compiled by a new Kotlin compiler backend and cannot be loaded by the old compiler"

![image](https://user-images.githubusercontent.com/5963351/96694586-51e3c780-1391-11eb-90fc-b137e5b298a5.png)

P.S. templates/desktop template is working fine

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6533">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5624">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
