### ISSUE TITLE
ClipboardManager.getText() does not return AnnotatedString with all its SpanStyles

### ISSUE THREAD

**Issue by haikalpribadi** [JetBrains/compose-multiplatform#2103]
When you pass an `AnnotatedString` with `SpanStyles` into `ClipboardManager.setText(annotatedString: AnnotatedString)`, and you try to get back the string via `ClipboardManager.getText(): AnnotatedString?`, the returned string looses all of its `SpanStyles`. This looks like a bug, right?

The `ClipboardManager` class is the one at `androidx.compose.ui.platform`.

**Comment by Legotier** [comment]
Also, the `AnnotatedString` loses all its styles when copied from another program. For example, when I copy a styled text from somewhere (e.g., Microsoft Word or Libre Office), I can paste it into another program (e.g., Microsoft Paint) and it's styled in the same way. It doesn't seem to be possible to access this style information via Compose though.

This happens both on Linux and Windows.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2103">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
