### ISSUE TITLE
Nested menu for DropDownMenu

### ISSUE THREAD

**Issue by shynline** [JetBrains/compose-multiplatform#2104]
From what i see there's currently no way to implement nested menu for ContextMenu or DropDownMenu.

![SmartSelect_20220608-161655_Chrome](https://user-images.githubusercontent.com/13237505/172608754-4b64557b-546f-40df-bdb6-3cd9759b8b36.jpg)

Do you have any plan to add it in future? If yes when ? 
Or It's intended and we have to do it manually ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2104">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
