### ISSUE TITLE
Support drawing text onto a `DrawScope`

### ISSUE THREAD

**Issue by alexjpwalker** [JetBrains/compose-multiplatform#2117]
## Problem to Solve

`DrawScope` provides methods to draw polygons (`drawOval`, `drawRoundRect`, etc.) but it doesn't provide one to draw **text**, a common requirement - e.g: when drawing a flowchart, we draw shaped 'nodes' which have text labels.

We've found two possible workarounds:

1. Create a container (such as `androidx.compose.foundation.layout.Box`) containing both a `Canvas` and other composables. Draw polygons in the `Canvas`, and place `androidx.compose.material.Text` composables at the same offset in the container. However, this is inelegant, as shapes and their label texts are now in different logical parts of the application, and we've found it can cause "jitter" as the shape redraws faster than the text.
2.
```kt
drawIntoCanvas { canvas ->
    canvas.nativeCanvas.drawTextLine(TextLine.make(text, font), x, y, paint.toFrameworkPaint())
}
```
where `font` is `org.jetbrains.skia.Font`, `paint` is `androidx.compose.ui.graphics.Paint`. This lets us efficiently draw text on the `Canvas`, but requires pulling in a new dependency (`skiko-awt`) and creating a new kind of `Font` (as well as Skia's `Typeface`, `Data` and `TextLine`), that represents the same font as our `androidx.compose.ui.text.platform.Font`, and is loaded from the same resource, but comes from a different library.

## Proposed Solution

Implement `drawTextLine` in `androidx.compose.ui.graphics.drawscope.DrawScope`

## Additional Information

Compose Version: 1.1.0-alpha04
Environment: Desktop

**Comment by alexjpwalker** [comment]
I've just noticed https://github.com/JetBrains/compose-jb/issues/2077 and https://issuetracker.google.com/issues/190787898. Seems like this has been an open issue in Jetpack Compose since mid-2021.

In that case, feel free to close this issue (hopefully the workarounds I've described can help others down the line 🙂  )

**Comment by yaroslavkulinich** [comment]
@alexjpwalker Do you have problems positioning Text drawn in your second workaround? 
I have a problem positioning text vertically relative to other elements. For example, I need to draw something like " - Text" (Line and Text centered vertically to each other), I have a Y coordinate of Line element and to center Text I need to know the exact height of the Text. Moreover, I need to know the Text height without vertical font padding to make it look fine.

**Comment by alexjpwalker** [comment]
> @alexjpwalker Do you have problems positioning Text drawn in your second workaround? I have a problem positioning text vertically relative to other elements. For example, I need to draw something like " - Text" (Line and Text centered vertically to each other), I have a Y coordinate of Line element and to center Text I need to know the exact height of the Text. Moreover, I need to know the Text height without vertical font padding to make it look fine.

We have a similar requirement, actually! In our case we want the `Text` to be centred at a specific point on the `Canvas` (as opposed to the default behaviour of `drawTextLine`, which draws the top-left corner of the text at the `Offset` passed in to it.)

To draw it centred at a specific point, we have the following code.
```kt
fun drawSingleLine(drawScope: DrawScope, text: String, center: Offset, font: Font) {
    val textLine = TextLine.make(text, font)
    drawScope.drawIntoCanvas {
        it.nativeCanvas.drawTextLine(
            textLine,
            center.x - textLine.width / 2,
            center.y + textLine.capHeight / 2,
            Paint().apply { this.color = color }.asFrameworkPaint()
        )
    }
}
```
You can adapt it to your needs.

My understanding is that `TextLine.capHeight` represents the height of the glyphs (rendered characters), while `TextLine.height` is the "line height", so when rendering multiple `TextLine`s, the `n`th `TextLine` should be offset by `TextLine.height * (n-1)` relative to the offset of line 1.

**Comment by mipastgt** [comment]
This is an extremely annoying issue and I hope that it will get fixed soon. I wonder how you are supposed to do serious graphics without beeing able to handle text at the same level. Having to use workarounds like the ones mentioned is just a PITA.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2117">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
