### ISSUE TITLE
Accessibility: marking component as header has no effect

### ISSUE THREAD

**Issue by ialokim** [JetBrains/compose-multiplatform#2119]
The `header()` function as [defined in Jetpack Compose](https://developer.android.com/jetpack/compose/accessibility#define-headings) has no effect on macOs with VoiceOver (Ctrl+Opt+Cmd+H just tells "Header not found").

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2119">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
