### ISSUE TITLE
xcodebuild: error: SDK "iphonesimulator12.4" cannot be located

### ISSUE THREAD

**Issue by tristancaron** [JetBrains/compose-multiplatform#2123]
On MacOS `12.3.1` with Xcode `13.3.1`.

I dowloaded the repo as a ZIP file, navigated to `experimental/examples/falling-balls-mpp` and ran the command `./gradlew iosDeployIPhone8Debug` which game me the following error:
```
> External tool execution failed:
  * Command: [/usr/bin/xcrun, xcodebuild, -scheme, FallingBalls, -project, ., -configuration, Debug, -derivedDataPath, build, -arch, x86_64, -sdk, iphonesimulator12.4]
  * Working dir: [/Users/tristan.caron/Downloads/compose-jb-master/experimental/examples/falling-balls-mpp/build/ios/IPhone8/FallingBalls.xcodeproj]
  * Exit code: 64
  * Standard output log: /Users/tristan.caron/Downloads/compose-jb-master/experimental/examples/falling-balls-mpp/build/compose/logs/iosSimulatorBuildIPhone8Debug/xcrun-2022-06-16-18-56-52-out.txt
  * Error log: /Users/tristan.caron/Downloads/compose-jb-master/experimental/examples/falling-balls-mpp/build/compose/logs/iosSimulatorBuildIPhone8Debug/xcrun-2022-06-16-18-56-52-err.txt
```
```
2022-06-16 18:40:35.194 xcodebuild[52500:20767174] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-06-16 18:40:35.195 xcodebuild[52500:20767174] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
xcodebuild: error: SDK "iphonesimulator12.4" cannot be located.
```

Although, the simulator gets open with the correct configuration.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/9624669/174208569-bef6abee-c43f-488e-9ed4-695a7197181b.png">

**Comment by chris-hatton** [comment]
I've also encountered this; it seems the Compose/iOS Gradle plugin design confuses installed SDK's with installed Simulator Runtime's - these are not necessarily 1:1 and by picking the first available Simulator Runtime version the code is often left trying to access a missing SDK and failing.

Here's a [relevant Slack conversation](https://kotlinlang.slack.com/archives/C0346LWVBJ4/p1658794788943079) with @dima-avdeev-jb .

The unreliable logic can be found here: `org.jetbrains.compose.experimental.uikit.internal.RegisterConnectedDeviceTasksKt#registerConnectedDeviceTasks`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2123">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
