### ISSUE TITLE
Add shortcut to Applications directory to Mac DMG contents

### ISSUE THREAD

**Issue by gnawf** [JetBrains/compose-multiplatform#2124]
e.g. from Firefox DMG you can see the Applications folder and you can drag into it

<img width="920" alt="Screen Shot 2022-06-17 at 4 32 44 pm" src="https://user-images.githubusercontent.com/9077461/174225501-5c1cc06d-3546-4dc1-8d7c-fd4171c058fc.png">

It doesn't need the fancy screen with the arrow, just as long as the DMG contents has a shortcut to the Applications folder that would be great.

**Comment by gnawf** [comment]
Hmm turns out this is supported, but only if you grant "Automation" permissions to the app building the dmg.

You can find it under `System Preferences` app -> `Security & Privacy` -> `Privacy` tab -> `Automation` in the list.

Though for me, this only seems to work when I build using IntelliJ's built in terminal. I have granted `Finder.app` permission  to `iTerm.app` but building it using iTerm doesn't seem to yield the same result.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2124">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
