### ISSUE TITLE
Accessibility: TextField labels are not exposed to screen reader

### ISSUE THREAD

**Issue by ialokim** [JetBrains/compose-multiplatform#2136]
```kotlin
fun main() = singleWindowApplication {
    Column {

        var input by remember { mutableStateOf("") }
        TextField(
            value = input,
            onValueChange = { input = it },
            label = {
                Text("Input field")
            }
        )
        Button(onClick = {}) {
            Text("Button")
        }
    }
```

as long as the text field is empty, the following is exposed for accessibility:

<img width="797" alt="Bildschirmfoto 2022-06-22 um 15 11 28" src="https://user-images.githubusercontent.com/18088991/175038087-d09d7807-69f2-4cfc-bc45-06db467bb333.png">

As soon as you start typing, both "label" and "value" are updated to the text field content.

I would expect "label" to contain the actual label information ("Input field" in this case) and only "value" containing the text field content.

Same applies to `OutlinedTextField` as well.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2136">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
