### ISSUE TITLE
Add android target to experimental examples

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/compose-multiplatform#2141]
For completness and for showing the full potential of Compose multiplatform it would be nice to add an android target to both experimental examples (falling-balls-mpp and minesweeper).

**Comment by dima-avdeev-jb** [comment]
@mipastgt 
For now we made Android target in this experimental example: https://github.com/JetBrains/compose-jb/tree/master/experimental/examples/chat-mpp

**Comment by mipastgt** [comment]
I am already trying to apply that to my own project :-)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2141">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
