### ISSUE TITLE
how can I add `Frameworks` directory to the bundle runtime?

### ISSUE THREAD

**Issue by xinkunZ** [JetBrains/compose-multiplatform#2145]
I want to use jcef in my project, so I want to use jbr as the bundle runtime
but after building, the target app for macOS only has jdk in runtime directory, but not copy `Frameworks` to runtime directory

* the jbr:
![image](https://user-images.githubusercontent.com/7759897/176377126-23405f41-0bef-4f6f-80f4-274ecf059bd8.png)

* the app bundle runtime:
![image](https://user-images.githubusercontent.com/7759897/176377375-090dc0b8-4400-427a-8a46-07606f807acd.png)

**Comment by xinkunZ** [comment]
> Will [these docs](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution#adding-files-to-packaged-application) help to include this directory?

I have read these docs , and I found  that the gradle plugin can only add something to app directory, can not modify the runtime directory

**Comment by igordmn** [comment]
Understand. It needs investigation. We use jlink/jpackage under the hood. If it isn't possible with them, we have to make a proposal/feature request in the JDK bug tracker.

**Comment by xiaobo0113** [comment]
If you just need some moules, for example "java.sql", which is reqired when you use gson(google), add module like this:
`compose.desktop {
    application {
        mainClass = "com.xxx.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb, TargetFormat.Exe)
            packageName = "Xxx"
            packageVersion = "1.0.0"

            modules("java.sql")
        }
    }
}`

If you do not do this step(gson used). You will get error: classDefNotFoundError: java.sql.Time, when you start your exe file after installation completed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2145">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
