### ISSUE TITLE
How to display dialog on the bottom of the phone or other locations？

### ISSUE THREAD

**Issue by xingyao1015** [JetBrains/compose-multiplatform#2146]
当我在使用dialog时，发现无法设置dialog的展示位置，而只能展示在屏幕中间，可以提供设置展示位置的属性吗？

When I use dialog, I find that the display position of the dialog cannot be set, but can only be displayed in the middle of the screen. Can I provide the attribute to set the display position?

**Comment by ArtyomZhukov** [comment]
Same issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2146">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
