### ISSUE TITLE
Cursor does not work correctly in text fields when using scaling - Windows

### ISSUE THREAD

**Issue by joseluiskuuc** [JetBrains/compose-multiplatform#2168]
1.- The cursor does not appear at some points where it is clicked
2.- Appears when clicking on some points, but when moving the direction keys it is lost
3.- The cursor does not appear when clicking on the beginning or end of the text field
4.- Cursor appears when window is resized

![Captura](https://user-images.githubusercontent.com/46909828/177434192-b17e8284-ac69-4405-8db5-e877d1585ea3.PNG)

https://user-images.githubusercontent.com/46909828/177434514-f049e18b-439c-4223-a765-a32815322652.mp4

**Comment by Syer10** [comment]
Was able to fix it with reflection, it makes the cursor bigger in some cases but its better then no cursor
```kotlin
        try {
            val field = Class.forName("androidx.compose.foundation.text.TextFieldCursor_desktopKt")
                .getDeclaredField("DefaultCursorThickness")
            field.trySetAccessible()

            val unsafeField = Unsafe::class.java.getDeclaredField("theUnsafe")
            unsafeField.trySetAccessible()
            val unsafe = unsafeField.get(null) as Unsafe

            val base = unsafe.staticFieldBase(field)
            val offset = unsafe.staticFieldOffset(field)

            unsafe.putFloat(base, offset, 2.0f)

            val updatedValue = field.get(null)
            println("Updated DefaultCursorThickness: $updatedValue")
        } catch (e: Throwable) {
            e.printStackTrace()
        }
```

**Comment by dima-avdeev-jb** [comment]
Please be carefull, because reflection call may break in future versions

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2168">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
