### ISSUE TITLE
Missing sources in IDE

### ISSUE THREAD

**Issue by koperagen** [JetBrains/compose-multiplatform#2178]
Hi! 
context: 
i created a project in IntelliJ 2022.2 Beta with `Compose multiplatform` project wizard, compose version 1.1.0, single platform, JDK 11.

on `desktop` platform, IDE cannot resolve sources when i navigate to the implementation for many declarations 
For example, i can see sources only for `mutableStateOf` and `::exitApplication` from sample code.
![image](https://user-images.githubusercontent.com/12936457/178104759-4a7eccc1-9031-47e0-919e-482ce1bb7fc6.png)
![image](https://user-images.githubusercontent.com/12936457/178105135-cd57c3cb-21e6-4981-91da-b7a3b3e52d9d.png)

but on `web` platform, it seems, Go To implementation works in 100% cases.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2178">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
