### ISSUE TITLE
Bug when using SwingPanel in 0.0.0-unmerged-build21 Compose

### ISSUE THREAD

**Issue by ggoraa** [JetBrains/compose-multiplatform#218]
I tried to add a swing component to my Compose app. `SwingPanel`: unresolved reference. When `SwingPanel` will be available in Compose?

**Comment by kirill-grouchnikov** [comment]
0.0.0-unmerged-build21

**Comment by GGorAA** [comment]
Thanks, ill try it

**Comment by GGorAA** [comment]
So, I tried to run may app with a SwingPanel. That's what I get:
![image](https://user-images.githubusercontent.com/61655029/103141482-70ea3700-46fd-11eb-8975-4587fa5e5889.png)
the code it is referencing is
![image](https://user-images.githubusercontent.com/61655029/103141486-80698000-46fd-11eb-8e9b-afa83fea32fd.png)

**Comment by kirill-grouchnikov** [comment]
They'll probably need a bit more than just one line to reproduce and fix

**Comment by GGorAA** [comment]
I can send the project here

**Comment by GGorAA** [comment]
https://github.com/Dynamium/OKSM-Desktop And here it is :D

**Comment by GGorAA** [comment]
I made a small update for that app, I replaced the buttons with an OpenStreetMap map :D

**Comment by Rsedaikin** [comment]
This bug is not related to the SwingPanel component. You can try an example here https://github.com/JetBrains/compose-jb/issues/200 where there is no SwingPanel and you get the same error. There is something wrong with the window disposing in `0.0.0-unmerged-build21` and this needs investigation.

**Comment by nfrankel** [comment]
It would be great to have the version in [the tutorial](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Swing_Integration).

I came upon this issue for the same initial reason as @GGorAA, namely the missing `SwingPanel` in the latest release.

**Comment by Omnieboer** [comment]
Is the only way to access SwingPanel by going back to 0.0.0-unmerged-build21 ? The Tutorial version that's actually featured doesn't seem to work and mentions nothing about versions. As @nfrankel said, it would be great if that version would just be available.

**Comment by MatkovIvan** [comment]
Seems outdated, closing

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5998">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
