### ISSUE TITLE
CSS Functions

### ISSUE THREAD

**Issue by rnett** [JetBrains/compose-multiplatform#2188]
It would be very nice to have support for [CSS functions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions), at least the basic math functions on numeric types, e.g. `min`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2188">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
