### ISSUE TITLE
Resource file not added to distributed .msi installer

### ISSUE THREAD

**Issue by rottajuliano** [JetBrains/compose-multiplatform#2190]
Pro project requires that a file cert.pem is read from the resources folder. When I distribute and install the application, i can see that the resource folder is empty and the certificate file was not copied during installations.

I'm following the guidelines present at https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution#packaging-resources

The file is currently at **src > main > resources > common > cert.pem**, and my build.gradle looks just like the example:
```
compose.desktop {
    application {
        mainClass = "TesterMainKt"
        nativeDistributions {
            modules("java.sql")
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageVersion = "1.0.0"

            appResourcesRootDir.set(project.layout.projectDirectory.dir("resources"))
        }
    }
}
```

Any idea what im doing wrong here? I also tried moving the cert file to the root of the resources folder without success.

**Comment by GuilhE** [comment]
Had the same problem and the only way I made it work was by using [getResource](https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/lang/Class.html#getResource(java.lang.String)).
In [my case](https://github.com/GuilhE/Expressus/blob/main/desktopApp/src/jvmMain/kotlin/SoundPlayer.kt) I wanted to play a .wav file.

Maybe it may help you too 😉

**Comment by sebkur** [comment]
@rottajuliano you need to put your file `cert.pem` into a directory `resources` at the top level of your project with your current settings in your Gradle build file. You're referencing `project.layout.projectDirectory.dir("resources")` which is a direct subdirectory from the project directory. What you could also do is modify this to `project.layout.projectDirectory.dir("src/main/resources")` which should also work. 

See here for a working sample project that includes a file from `src/appdata`:
https://github.com/sebkur/test-compose-for-desktop/blob/0085bdff9086cfa9e69943342ed9f3c91c4a1f7c/build.gradle.kts#L78

There the directory used is located here: https://github.com/sebkur/test-compose-for-desktop/tree/0085bdff9086cfa9e69943342ed9f3c91c4a1f7c/src/appdata/common

**Comment by fcat97** [comment]
> What you could also do is modify this to project.layout.projectDirectory.dir("src/main/resources") which should also work.

Didn't work either.

My setup:

```kotlin
compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            packageName = "desktopApp"
            packageVersion = "1.0.0"
            modules("java.sql")
            appResourcesRootDir.set(project.layout.projectDirectory.dir("src/main/resources/"))
            linux {
                iconFile.set(project.layout.projectDirectory.file("src/main/resources/bn.png"))
            }
            targetFormats(
                TargetFormat.Msi,
                TargetFormat.Deb,
                TargetFormat.AppImage,
                TargetFormat.Rpm
            )
        }
    }
}
```

How I'm trying to get the resource:

```kotlin
@Synchronized
fun getInstance(): WordsRepository {
    Class.forName("org.sqlite.JDBC")
    val databaseDirectory = File(System.getProperty("compose.application.resources.dir"))
    val dbPath = "${databaseDirectory.path}/dictionary.db"
```

**Comment by fcat97** [comment]
**To clearify,**
you must put your resources into one of the described directories, **not directly inside `project/resources` directory.**

Say, your project directory is `/home/someone/MyProjects/project1/`. You may have different submodule such as `/desktop`, `/android`, `/ios` etc. Say, you want to include a resource for desktop only. So the correct configuration for `/home/someone/MyProjects/project1/desktop/build.gradle.kts` will be `project.layout.projectDirectory.dir("resources")`. Now the fact is, you must have to put your resources into one of these directories to be copied in release build:

- `/home/someone/MyProjects/project1/desktop/resources/common/`
- `/home/someone/MyProjects/project1/desktop/resources/linux/`
- `/home/someone/MyProjects/project1/desktop/resources/mac/`
- `/home/someone/MyProjects/project1/desktop/resources/windows/`
- `/home/someone/MyProjects/project1/desktop/resources/linux-x86/`

**Comment by Moriafly** [comment]
I also encountered this issue, is there any other solution? The above method doesn't seem to work

**Comment by he-dev** [comment]
The resource folder does remain empty. I also couldn't read resources after deployment. Then I found out (through debugging) that **resources are case sensitive**! When you debug your app resources are read directly from your hard drive which is case insensitive. Later it changes!

**Comment by rajumark** [comment]
yes same thing happened with me ,i put 1 zip file in resources but when make dmg file then install in mac then at path there is resource folder is empty.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2190">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
