### ISSUE TITLE
touchpad scroll behavior

### ISSUE THREAD

**Issue by kobutri** [JetBrains/compose-multiplatform#2197]
Currently the scroll behavior matches platforms behavior when using a mouse wheel, but both Windows and Mac OS exhibit significantly different behavior when using a touchpad.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2197">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
