### ISSUE TITLE
Graphics layer does not render items offset outside of it

### ISSUE THREAD

**Issue by ejektaflex** [JetBrains/compose-multiplatform#2198]
This seems to be intentional (since normally the graphics layer's contents are confined within the layer). However, there is a use case for why one might want a graphics layer the renders regardless of it's position/size:

For my application I am using the layer as a sort of cartesian graph where the user can pan/zoom/etc, and all of the contents can exist at any (X,Y) value in space. Each of those elements is offset with `.offset { their x, y pos }`. The problem is that when you pan up above the origin and drag an element above the origin, it disappears because it is no longer within the graphics layer, which is set to only be the max size of it's container box. 

The ability to be able to render items outside of the bounds of the graphics layer is what I would need to get around this - it might require a new type of graphics layer that does not do bounds checking when deciding whether to render or not - since the entire "graph" is an infinite cartesian plane, items should be able to be rendered anywhere, even outside of the bounds of the graphics layer. 

I have tried another method to get around this limitation, which is by choosing *not* to pan the graphics layer at all and place all elements at `.offset { their x, y pos + graph pan x, y }`, but this causes an enormous amount of lag when panning and there are a lot of elements in the graph, because whenever the pan amount changes it will cause every single element in the graph to update their position at once. The more performant option is just to stuff all elements inside of the graphics layer that gets panned, eliminating the cascading updates occurring to each element, but that's impossible if panning the graph makes it all disappear when the main graph goes offscreen.

I'm not sure if there are any methods that I am unaware of that would solve this problem. Thanks!

**Comment by Antimonit** [comment]
I've run into the same issue. This issue manifests even with high-level composables, such as `Modifier.offset`.

Example:
```kotlin
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        var offset by remember { mutableStateOf(IntOffset.Zero) }

        LaunchedEffect(Unit) {
            repeat(200) {
                delay(10)
                offset -= IntOffset(10, 0)
            }
        }

        Box(
            modifier = Modifier
                .fillMaxSize()
                .background(Color.Red)
                .offset { offset }
                .background(Color.Blue)
        ) {
            repeat(20) {
                Text(
                    text = "$it",
                    modifier = Modifier
                        .size(50.dp)
                        .offset(100.dp * it, 0.dp)
                        .background(Color.Green),
                )
            }
        }
    }
}
```

We add enough `Text` composables so that some of them extend beyond the boundaries of the parent `Box`. Then, if we `.offset { offset }` the `Box` enough that the blue background is no longer visible, it will also hide all `Text`s, although some of them should still be visible.

Not sure what to do about this.

**Comment by Antimonit** [comment]
Oh wow. This happens only with the pixel-based `offset`. Once replaced with the DP-based `offset`, the issue disappears.

```kotlin
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        var offset by remember { mutableStateOf(DpOffset.Zero) }

        LaunchedEffect(Unit) {
            repeat(200) {
                delay(10)
                offset -= DpOffset(10.dp, 0.dp)
            }
        }

        Box(
            modifier = Modifier
                .fillMaxSize()
                .background(Color.Red)
                .offset(offset.x, offset.y)
                .background(Color.Blue)
        ) {
            repeat(20) {
                Text(
                    text = "$it",
                    modifier = Modifier
                        .size(50.dp)
                        .offset(100.dp * it, 0.dp)
                        .background(Color.Green),
                )
            }
        }
    }
}
```

**Comment by ejektaflex** [comment]
I just checked this out again in 2023, and it is still present a year later in Jetbrains Compose 1.4.3 on Desktop.

**Comment by ejektaflex** [comment]
Seems to also be related to #2817 (and by extension perhaps #1559)

**Comment by igordmn** [comment]
The core issue is the same as in https://github.com/JetBrains/compose-multiplatform/issues/2807, let's keep only 2807.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2198">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
