### ISSUE TITLE
Multiplatform template in IDEA / Android Studio. Desktop module doesn't see classes from common module

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#22]
Reproduced in examples/todoapp template and templates/multiplatform

![image](https://user-images.githubusercontent.com/5963351/96694586-51e3c780-1391-11eb-90fc-b137e5b298a5.png)

(App is a function from common module)

See also https://github.com/JetBrains/compose-jb/pull/10#issuecomment-713038689

P.S. templates/desktop are working fine

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6534">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5623">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
