### ISSUE TITLE
Support extraKeysRawXml for Native macOS target.

### ISSUE THREAD

**Issue by Tlaster** [JetBrains/compose-multiplatform#2202]
It would be great to add `extraKeysRawXml` support for `NativeApplicationMacOSPlatformSettings` since `JvmMacOSPlatformSettings` already support it

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2202">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
