### ISSUE TITLE
web: consider adding onload event handler 

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-multiplatform#2204]
> Hello, did you consider onload event to be part of the “standard” set? It’s available for <body>, <frame>, <iframe>, <img>, <input type="image">, <link>, <script>, <style> and probably most useful on img?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2204">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
