### ISSUE TITLE
Add PreviewParameterProvider in ui.tooling.preview package

### ISSUE THREAD

**Issue by Burtan** [JetBrains/compose-multiplatform#2207]
Hi,

the [androidx.compose.ui.tooling.preview package](https://developer.android.com/reference/kotlin/androidx/compose/ui/tooling/preview/PreviewParameterProvider) has the PreviewParameterProvider interface. It seems to be very useful for Preview. Please add it to the desktop package :-)
Thanks!

**Comment by Burtan** [comment]
Any news to this as there are some classes/functions being moved to multiplatform lately.

**Comment by dima-avdeev-jb** [comment]
Thanks for enhancment description. We will discuss it internally.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2207">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
