### ISSUE TITLE
Unable to zoom using detectTransformGestures in Modifier.pointerInput

### ISSUE THREAD

**Issue by AnyUnderstanding** [JetBrains/compose-multiplatform#2209]
# Tested on:
  Compose versions: 1.1.1, 1.2.0-alpha01-dev753
  Kotlin versions: 1.6.10, 1.7.0
  Java version: openjdk-16.0.1-1
  OS: Arch, Windows 11

# Code:
```kt
Modifier.pointerInput(Unit){
      detectTransformGestures(
          onGesture = {centroid, pan, zoom, rotation ->
              println(zoom)
          }
      )
  }
```
# Behavior:
Trying to zoom on a touchscreen of a laptop with two fingers (pinch), the above code always prints "1.0", regardless of the pinch direction. 

# Expected Behavior:
The above code should yield different zoom levels in relation to the distance between touchpoints. If the distance between the touchpoints is increasing, zoom should increase as well. Otherwise, if the distance is decreasing, zoom should also decrease.

While debugging, I noticed that zoom is calculated in the function calculateZoom by dividing currentCentroidSize / previousCentroidSize. To calculate the CentroidSize the function calculateCentroidSize is used. The function calculateCentroidSize iterates through the list changes (seems to hold the changed touch positions) and averages over the distance of all changes to the Centroid. Interestingly, the list changes always holds only one value, even if two fingers are on the touchscreen, therefore the distance to the centroid is always zero and currentCentroidSize and previousCentroidSize is also zero. To prevent division by zero, calculateZoom checks:
```kt
    if (currentCentroidSize == 0f || previousCentroidSize == 0f) {
        return 1f
    }
```
As a result, zoom is always one and the code works as described in the "Behavior" section.

All the functions described above can be found in TransformGestureDetector.kt.

**Comment by saket** [comment]
I'd love to use this for creating zoomable images on desktop using telephoto https://saket.github.io/telephoto/zoomableimage/

**Comment by gsteckman** [comment]
Some applications, e.g. Firefox, let you use ctrl + scroll wheel on the mouse to zoom, and this also doesn't work. In this case, the onGesture callback to detectTransformGestures isn't invoked at all.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2209">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
