### ISSUE TITLE
0.0.0-unmerged-build21: the SwingPanel is shown above all composables, and I can't change that

### ISSUE THREAD

**Issue by ggoraa** [JetBrains/compose-multiplatform#221]
I wanted to make my SwingPanel behind some other composables, like the Sidebar. How to make that?

**Comment by Dominaezzz** [comment]
Reproducer?

**Comment by GGorAA** [comment]
https://github.com/Dynamium/OKSM-Desktop

**Comment by GGorAA** [comment]
wait, I can't push my local code there, do not use it for now

**Comment by GGorAA** [comment]
I pushed everything, check it now

**Comment by yaroslavkulinich** [comment]
@ggoraa Have you found the solution to use Composables over SwingPanel?

**Comment by HuixingWong** [comment]
Is it any plan for fix this ?

**Comment by JoeSteven** [comment]
is it the same issue with #1087  ?

**Comment by MatkovIvan** [comment]
Fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/915 (under the flag)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5996">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
