### ISSUE TITLE
Using a androidx.compose.ui.window.Application as UIViewController

### ISSUE THREAD

**Issue by CoronelGlober** [JetBrains/compose-multiplatform#2211]
Hi everyone!

I'm wondering if there is a way of using the fun `androidx.compose.ui.window.Application` as a normal UIViewController on a normal storyboard screen, this would be useful for displaying a screen made entirely on compose as a modal section as stated on [Present a View Controller Modally](https://developer.apple.com/documentation/uikit/view_controllers/showing_and_hiding_view_controllers#3370706) instead of creating a single `UIApplicationMain` from the iOS sourceset of KMM.

For trying this, I've created this [small demo project](https://github.com/CoronelGlober/sharedcompose) that exports a val to be used as a UIViewController
![Screen Shot 2022-07-26 at 9 40 22 PM](https://user-images.githubusercontent.com/69470506/181148973-8b9f2e99-24fe-49a5-bb1a-d7fbc52c51b5.png)
 
But by adding compose to a multi-platform module that generates a XCode Framework I've broken the building process, now I'm seeing this error related to building skia on MAC when running the task that generates it, this is the build error 👇 

<details><summary>Stacktrace</summary><p>

`ld: warning: object file (/var/folders/qq/3429lmbj3ln050t897b4dk2h0000gs/T/included3426265202794303766/libskia.a(libdng_sdk.dng_pthread.o)) was built for newer iOS Simulator version (14.4) than being linked (9.0)
Undefined symbols for architecture x86_64:
  "_CTFontGetXHeight", referenced from:
      SkScalerContext_Mac::generateFontMetrics(SkFontMetrics*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontGetUnderlineThickness", referenced from:
      SkScalerContext_Mac::generateFontMetrics(SkFontMetrics*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontGetUnderlinePosition", referenced from:
      SkScalerContext_Mac::generateFontMetrics(SkFontMetrics*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontGetAdvancesForGlyphs", referenced from:
      SkScalerContext_Mac::generateMetrics(SkGlyph*, SkArenaAlloc*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontCreatePathForGlyph", referenced from:
      SkScalerContext_Mac::generateMetrics(SkGlyph*, SkArenaAlloc*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
      SkScalerContext_Mac::generatePath(SkGlyph const&, SkPath*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontDrawGlyphs", referenced from:
      SkCTFontGetSmoothBehavior() in libskia.a(libskia.SkCTFont.o)
      SkScalerContext_Mac::Offscreen::getCG(SkScalerContext_Mac const&, SkGlyph const&, unsigned short, unsigned long*, bool) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontGetSize", referenced from:
      SkCTFontCreateExactCopy(__CTFont const*, double, OpszVariation) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkScalerContext_Mac::generateFontMetrics(SkFontMetrics*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_kCTFontVariationAxisMaximumValueKey", referenced from:
      SkCTVariationFromSkFontArguments(__CTFont const*, SkFontArguments const&) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetVariationDesignParameters(SkFontParameters::Variation::Axis*, int) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_kCTFontFormatAttribute", referenced from:
      SkTypeface_Mac::onOpenStream(int*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontCopyFullName", referenced from:
      SkTypeface_Mac::onGetFontDescriptor(SkFontDescriptor*, bool*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontCopyFamilyName", referenced from:
      SkTypeface_Mac::onGetFamilyName(SkString*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetFontDescriptor(SkFontDescriptor*, bool*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontCopyTable", referenced from:
      SkTypeface_Mac::onGetTableData(unsigned int, unsigned long, unsigned long, void*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onCopyTableData(unsigned int) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_kCTFontFamilyNameAttribute", referenced from:
      (anonymous namespace)::SkCopyAvailableFontFamilyNames(__CTFontCollection const*)::$_1::__invoke(void const*, void*) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkFontMgr_Mac::CreateSet(__CFString const*) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      create_descriptor(char const*, SkFontStyle const&) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
  "_CTFontCopyGraphicsFont", referenced from:
      SkTypeface_Mac::onGetUPEM() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetTableData(unsigned int, unsigned long, unsigned long, void*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onCopyTableData(unsigned int) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkScalerContext_Mac::SkScalerContext_Mac(sk_sp<SkTypeface_Mac>, SkScalerContextEffects const&, SkDescriptor const*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_kCTFontVariationAxisIdentifierKey", referenced from:
      SkTypeface_Mac::onGetVariationDesignPosition(SkFontArguments::VariationPosition::Coordinate*, int) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkCTVariationFromSkFontArguments(__CTFont const*, SkFontArguments const&) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetVariationDesignParameters(SkFontParameters::Variation::Axis*, int) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontCopyVariationAxes", referenced from:
      SkTypeface_Mac::onGetAdvancedMetrics() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetVariationDesignPosition(SkFontArguments::VariationPosition::Coordinate*, int) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkCTVariationFromSkFontArguments(__CTFont const*, SkFontArguments const&) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetVariationDesignParameters(SkFontParameters::Variation::Axis*, int) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkScalerContext_Mac::generateFontMetrics(SkFontMetrics*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontGetAscent", referenced from:
      SkTypeface_Mac::onGetAdvancedMetrics() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkScalerContext_Mac::generateFontMetrics(SkFontMetrics*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontCopyCharacterSet", referenced from:
      SkTypeface_Mac::getGlyphToUnicodeMap(int*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontCreateCopyWithSymbolicTraits", referenced from:
      create_from_name(char const*, SkFontStyle const&) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
  "_kCTFontVariationAxisMinimumValueKey", referenced from:
      SkCTVariationFromSkFontArguments(__CTFont const*, SkFontArguments const&) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetVariationDesignParameters(SkFontParameters::Variation::Axis*, int) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontGetGlyphCount", referenced from:
      SkTypeface_Mac::getGlyphToUnicodeMap(int*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onCountGlyphs() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontGetCapHeight", referenced from:
      SkTypeface_Mac::onGetAdvancedMetrics() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkScalerContext_Mac::generateFontMetrics(SkFontMetrics*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontCopyAvailableTables", referenced from:
      SkTypeface_Mac::onGetTableTags(unsigned int*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontCopyFontDescriptor", referenced from:
      SkTypeface_Mac::Make(std::__1::unique_ptr<__CTFont const, SkFunctionWrapper<void (void const*), &(CFRelease)> >, OpszVariation, std::__1::unique_ptr<SkStreamAsset, std::__1::default_delete<SkStreamAsset> >)::$_0::operator()() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkCTFontGetDataFontWeightMapping() in libskia.a(libskia.SkCTFont.o)
  "_kCTFontTraitsAttribute", referenced from:
      create_descriptor(char const*, SkFontStyle const&) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkCTFontDescriptorGetSkFontStyle(__CTFontDescriptor const*, bool) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkCTFontGetDataFontWeightMapping() in libskia.a(libskia.SkCTFont.o)
  "_kCTFontWidthTrait", referenced from:
      create_descriptor(char const*, SkFontStyle const&) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkCTFontDescriptorGetSkFontStyle(__CTFontDescriptor const*, bool) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontManagerCreateFontDescriptorFromData", referenced from:
      (anonymous namespace)::ctfont_from_skdata(sk_sp<SkData>, int) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkCTFontGetSmoothBehavior() in libskia.a(libskia.SkCTFont.o)
      SkCTFontGetDataFontWeightMapping() in libskia.a(libskia.SkCTFont.o)
  "_CTFontDescriptorCreateMatchingFontDescriptors", referenced from:
      SkFontMgr_Mac::CreateSet(__CFString const*) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
  "_kCTFontWeightTrait", referenced from:
      create_descriptor(char const*, SkFontStyle const&) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkCTFontDescriptorGetSkFontStyle(__CTFontDescriptor const*, bool) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkCTFontGetDataFontWeightMapping() in libskia.a(libskia.SkCTFont.o)
  "_kCTFontVariationAxisDefaultValueKey", referenced from:
      SkTypeface_Mac::onGetVariationDesignPosition(SkFontArguments::VariationPosition::Coordinate*, int) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkCTVariationFromSkFontArguments(__CTFont const*, SkFontArguments const&) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetVariationDesignParameters(SkFontParameters::Variation::Axis*, int) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_kCTFontVariationAttribute", referenced from:
      SkFontMgr_Mac::onMakeFromStreamArgs(std::__1::unique_ptr<SkStreamAsset, std::__1::default_delete<SkStreamAsset> >, SkFontArguments const&) const in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkTypeface_Mac::onMakeClone(SkFontArguments const&) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_kCTFontStyleNameAttribute", referenced from:
      (anonymous namespace)::SkFontStyleSet_Mac::getStyle(int, SkFontStyle*, SkString*) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
  "_CTFontCreateCopyWithAttributes", referenced from:
      SkFontMgr_Mac::onMakeFromStreamArgs(std::__1::unique_ptr<SkStreamAsset, std::__1::default_delete<SkStreamAsset> >, SkFontArguments const&) const in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkCTFontCreateExactCopy(__CTFont const*, double, OpszVariation) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onMakeClone(SkFontArguments const&) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontGetDescent", referenced from:
      SkTypeface_Mac::onGetAdvancedMetrics() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkScalerContext_Mac::generateFontMetrics(SkFontMetrics*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontGetUnitsPerEm", referenced from:
      SkTypeface_Mac::getGlyphToUnicodeMap(int*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetAdvancedMetrics() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkScalerContext_Mac::generateFontMetrics(SkFontMetrics*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontGetGlyphsForCharacters", referenced from:
      SkTypeface_Mac::getGlyphToUnicodeMap(int*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetAdvancedMetrics() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onCharsToGlyphs(int const*, int, unsigned short*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      get_plane_glyph_map(unsigned char const*, __CTFont const*, long, int*, unsigned char) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontGetLeading", referenced from:
      SkScalerContext_Mac::generateFontMetrics(SkFontMetrics*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontCopyPostScriptName", referenced from:
      SkTypeface_Mac::onGetAdvancedMetrics() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetPostScriptName(SkString*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetFontDescriptor(SkFontDescriptor*, bool*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontGetSlantAngle", referenced from:
      SkTypeface_Mac::onGetAdvancedMetrics() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontDescriptorCreateWithAttributes", referenced from:
      SkFontMgr_Mac::onMakeFromStreamArgs(std::__1::unique_ptr<SkStreamAsset, std::__1::default_delete<SkStreamAsset> >, SkFontArguments const&) const in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkFontMgr_Mac::CreateSet(__CFString const*) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      create_descriptor(char const*, SkFontStyle const&) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkCTFontCreateExactCopy(__CTFont const*, double, OpszVariation) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onMakeClone(SkFontArguments const&) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontGetBoundingBox", referenced from:
      SkTypeface_Mac::onGetAdvancedMetrics() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkScalerContext_Mac::generateFontMetrics(SkFontMetrics*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontCopyLocalizedName", referenced from:
      SkTypeface_Mac::onCreateFamilyNameIterator() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontGetBoundingRectsForGlyphs", referenced from:
      SkTypeface_Mac::onGetAdvancedMetrics() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkScalerContext_Mac::generateMetrics(SkGlyph*, SkArenaAlloc*) in libskia.a(fontmgr_mac_ct.SkScalerContext_mac_ct.o)
  "_CTFontDescriptorCopyAttribute", referenced from:
      (anonymous namespace)::SkCopyAvailableFontFamilyNames(__CTFontCollection const*)::$_1::__invoke(void const*, void*) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      (anonymous namespace)::SkFontStyleSet_Mac::getStyle(int, SkFontStyle*, SkString*) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkCTFontDescriptorGetSkFontStyle(__CTFontDescriptor const*, bool) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkCTFontGetDataFontWeightMapping() in libskia.a(libskia.SkCTFont.o)
  "_kCTFontSlantTrait", referenced from:
      create_descriptor(char const*, SkFontStyle const&) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkCTFontDescriptorGetSkFontStyle(__CTFontDescriptor const*, bool) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontCopyAttribute", referenced from:
      SkCTFontCreateExactCopy(__CTFont const*, double, OpszVariation) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onOpenStream(int*) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontCreateForString", referenced from:
      SkFontMgr_Mac::onMatchFamilyStyleCharacter(char const*, SkFontStyle const&, char const**, int, int) const in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
  "_CTFontCopyVariation", referenced from:
      SkTypeface_Mac::onGetVariationDesignPosition(SkFontArguments::VariationPosition::Coordinate*, int) const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkCTVariationFromSkFontArguments(__CTFont const*, SkFontArguments const&) in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontCollectionCreateFromAvailableFonts", referenced from:
      SkFontMgr_Mac::SkFontMgr_Mac(__CTFontCollection const*) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
  "_CTFontCreateWithFontDescriptor", referenced from:
      SkFontMgr_Mac::onMatchFamilyStyle(char const*, SkFontStyle const&) const in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkFontMgr_Mac::onMatchFamilyStyleCharacter(char const*, SkFontStyle const&, char const**, int, int) const in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      (anonymous namespace)::SkFontStyleSet_Mac::createTypeface(int) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      (anonymous namespace)::SkFontStyleSet_Mac::matchStyle(SkFontStyle const&) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      (anonymous namespace)::ctfont_from_skdata(sk_sp<SkData>, int) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      create_from_name(char const*, SkFontStyle const&) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkCTFontGetSmoothBehavior() in libskia.a(libskia.SkCTFont.o)
      ...
  "_CTFontGetSymbolicTraits", referenced from:
      create_from_name(char const*, SkFontStyle const&) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
      SkTypeface_Mac::Make(std::__1::unique_ptr<__CTFont const, SkFunctionWrapper<void (void const*), &(CFRelease)> >, OpszVariation, std::__1::unique_ptr<SkStreamAsset, std::__1::default_delete<SkStreamAsset> >)::$_0::operator()() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
      SkTypeface_Mac::onGetAdvancedMetrics() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_kCTFontFamilyNameKey", referenced from:
      SkTypeface_Mac::onCreateFamilyNameIterator() const in libskia.a(fontmgr_mac_ct.SkTypeface_mac_ct.o)
  "_CTFontCollectionCreateMatchingFontDescriptors", referenced from:
      (anonymous namespace)::SkCopyAvailableFontFamilyNames(__CTFontCollection const*) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
ld: symbol(s) not found for architecture x86_64`
</p></details>

Any other ideas about how to use compose views on small iOS UI sections?

Thanks!
CC: @arkivanov and @dima-avdeev-jb 😃

**Comment by dima-avdeev-jb** [comment]
@CoronelGlober 
UIKit not ready for stable.
But Desktop will be 1.2.0 stable. But, before we need to fix bugs

**Comment by CoronelGlober** [comment]
Hi @dima-avdeev-jb!
Oh, I see, I'll keep up testing the versions you bring to us, 🤞 for a soon stable release!

**Comment by CoronelGlober** [comment]
Hello again @dima-avdeev-jb 👋!
We are following closely any progress on this issue so we can use some of our compose code as small sections on iOS (as a starter point), [I've created a small demo](https://github.com/CoronelGlober/demo-compose-multiplatform/) and also presented a small talk to my company about the cool features we have with Jetbrains compose.
Please let me know if the demo works to be used as an additional demo on the Jetbrains page.
Thanks!

**Comment by dima-avdeev-jb** [comment]
Hello, @CoronelGlober 
Wow, it looks amazing!

**Comment by ahmadhassan5** [comment]
I’m facing this issue, is there any solution?

**Comment by xxfast** [comment]
I'm also running into a similar issue here 

```
> Task :app:ui:linkPodDebugFrameworkIosSimulatorArm64

e: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors

/Users/TFNX46/Developer/MULTIPLATFORM/PSCore-Multiplatform/app/ios/Pods/ld:1:1: object file (/var/folders/46/j7qr6bgj4f777vw39y0810d40000gp/T/included4393063786838865862/libskresources.a(libskresources.SkResources.o)) was built for newer iOS Simulator version (15.2) than being linked (9.0) 
  ^ this is repeated many times - omitted for brevity 

Undefined symbols for architecture arm64:
  "_CTFontCollectionCreateFromAvailableFonts", referenced from:
      SkFontMgr_Mac::SkFontMgr_Mac(__CTFontCollection const*) in libskia.a(fontmgr_mac_ct.SkFontMgr_mac_ct.o)
  ^ this goes further deep - omitted for brevity (check full stacktrace)

ld: symbol(s) not found for architecture arm64

> Task :app:ui:linkPodDebugFrameworkIosSimulatorArm64 FAILED
```
[full-stacktrace.log](https://github.com/JetBrains/compose-multiplatform/files/11025303/full-stacktrace.log)

**Comment by xxfast** [comment]
For me this was fixed by setting the right deployment target
```
cocoapods {
  ..
  framework {
   ..
    isStatic = true
  }
  ios.deploymentTarget = "14.1"
}
```

Let me know if that works for you too @ahmadhassan5

**Comment by CoronelGlober** [comment]
Hi everyone!
I've just realized that it is possible now! We are now using Composables and SwiftUi views side by side on our iOS application, thank you very much for all your help @dima-avdeev-jb!

**Comment by CoronelGlober** [comment]
By the way, I've updated my [demo project](https://github.com/CoronelGlober/demo-compose-multiplatform/) for anyone curious!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2211">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
