### ISSUE TITLE
The desktop createDistribution task should be able to target any platform

### ISSUE THREAD

**Issue by corneil** [JetBrains/compose-multiplatform#2218]
At the moment it isn't possible to build a distribution or uber jar for another platform.
Since it entails including a native library it shouldn't be a problem to provide the cross platform version.

I would suggest it even be possible to include all libraries and choose the correct one at startup.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2218">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
