### ISSUE TITLE
Chinese character is not support on compose web

### ISSUE THREAD

**Issue by ricson-hoo** [JetBrains/compose-multiplatform#2219]
I recently downloaded the chat-mpp source code from : (https://github.com/JetBrains/compose-jb/tree/master/experimental/examples/chat-mpp), and run it with ./gradlew jsBrowserDevelopmentRun

The page show up and everything seems work.

Just one problem, it dosn't support Chinese, I modify the code:

```
topBar = {
                    TopAppBar(
                        title = { Text("Chat sample") }
                    )
                }

```
**to:**

```
TopAppBar(
                        title = { Text("聊天") }
                    )

```
then the title just display as “口口”。

The project's File Encoding already being set to UTF-8.

![chineseUnsupported](https://user-images.githubusercontent.com/33590203/182027838-51e8f628-adc2-498b-a73d-5e6eff96dc1d.jpg)

**Comment by DXueShengKa** [comment]
I'm having this issue too

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2219">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
