### ISSUE TITLE
Will support drag and drop file into widget?

### ISSUE THREAD

**Issue by gtf35** [JetBrains/compose-multiplatform#222]
Will compose support drag and drop file into widget?
Sometimes useful，for example, drag and drop an apk to the window to install it to phone.😉

**Comment by Dominaezzz** [comment]
https://github.com/JetBrains/compose-jb/issues/176

**Comment by gtf35** [comment]
Thanks，but it will open a dialog.
I mean we can drag and drop files directly from the Explorer to the window。🤔

**Comment by Dominaezzz** [comment]
Oh sorry. Compose itself won't support that. You can register for drap and drop events with [`DropTargetListener`](https://docs.oracle.com/javase/7/docs/api/java/awt/dnd/DropTargetListener.html) on `AppWindowAmbient.current`.

**Comment by Dominaezzz** [comment]
Here's a more concrete example https://twitter.com/tkuenneth/status/1331993022955917312?s=20 .

**Comment by gtf35** [comment]
🤔 It is based on the window.
If I want to trigger in a specific area, I guess, this way could not be possible

By the way, thanks again

**Comment by gtf35** [comment]
This link looks like what I want, thank you so much

**Comment by Dominaezzz** [comment]
There isn't an immediately obvious way to limit it to a specific area. I think it's worth leaving this issue open.

**Comment by Dominaezzz** [comment]
Maybe you can limit it with the new `SwingPanel`.

**Comment by gtf35** [comment]
Yeah, you are right. 
I only watch the video, he drop it in the widget, actually he doesnt  limit it.

**Comment by gtf35** [comment]
I thought about that idea, but in the latest「0.3.0-build136」
![image](https://user-images.githubusercontent.com/22125696/103172719-5ac0b000-4890-11eb-894c-1f3ae2af8bdd.png)

**Comment by Dominaezzz** [comment]
I think you need to use this version `0.0.0-unmerged-build21`.

**Comment by gtf35** [comment]
Yeah, I see this version in issues, but I dont known how to find unmerged version.😉

by the way, this version ...  
But this is another issues
![image](https://user-images.githubusercontent.com/22125696/103173004-cd328f80-4892-11eb-852a-40ad281e58fc.png)

**Comment by Dominaezzz** [comment]
You have to update the version in `build.gradle`

**Comment by gtf35** [comment]
Yes, you are right🙌
Thanks a looooot

**Comment by olonho** [comment]
Guess we could close it, once SwingPanel support merged.

**Comment by gtf35** [comment]
But wouldn’t it be better to let compose-jb support it?

**Comment by illuminator3** [comment]
bump still no support for file drag and drop on a single element instead of the entire window?

**Comment by felixdivo** [comment]
You can also embed a `androidx.compose.ui.awt.SwingPanel` an have it accept drops, but that's also inconvenient to work with (and changes the style).

**Comment by gtf35** [comment]
@felixdivo Yeah, compatibility with Swing is not compose's own behavior

**Comment by felixdivo** [comment]
> You can also embed a `androidx.compose.ui.awt.SwingPanel` an have it accept drops

That also does not work nicely due to #1062 and (very importantly!) #1202. I thought about putting a compose UI in the drop traget by nesting a `ComposePanel` in a `SwingPanel`, but that also does not work due to #1060 and #1061.

**Comment by tunjid** [comment]
You can do this with a custom modifier. Here's source for one [here](https://github.com/tunjid/me/blob/main/common/core-ui/src/commonMain/kotlin/com/tunjid/me/core/ui/dragdrop/DropTarget.kt)

Here's a Compose desktop [implementation](https://github.com/tunjid/me/blob/main/common/core-ui/src/desktopMain/kotlin/com/tunjid/me/core/ui/dragdrop/SwingDropTargetModifier.kt)

And an Android [implementation](https://github.com/tunjid/me/blob/main/common/core-ui/src/androidMain/kotlin/com/tunjid/me/core/ui/dragdrop/ViewDropTargetModifier.kt).

Here's a gif of both side by side

![DnD](https://user-images.githubusercontent.com/8147224/159084192-81767e4a-36c4-4c4b-8660-cf8a1c6de9b6.gif)

**Comment by hakanai** [comment]
I have a number of use cases for this:
- Drag selected text from text views out into other apps
- Drag text from other apps into text views
- Drag images from other apps into text views
- Drag images from other apps into specific drop areas (similar to what previous example showed)
- Drag files from other apps (including file explorers) into specific drop areas
- Drag things between two slots in the same app (probably possible without using real dnd)
- Drag nodes from my app out into files

**Comment by Walingar** [comment]
Hello everyone, thank you for your request and use cases! Experimental drag and drop functionality for desktop has been merged and will be available in the next dev builds. It allows moving files/images/text inside your Compose desktop application out of the box!

**Comment by hakanai** [comment]
Sample code for a text field receiving dropped text replacing the selection, working in desktop on v1.4.0.

Still missing the equivalent behaviour in the other direction.

```kotlin
var isDroppable by remember { mutableStateOf(false) }
val (textFieldValue, setTextFieldValue) = remember { mutableStateOf(TextFieldValue()) }

TextField(
    value = textFieldValue,
    onValueChange = setTextFieldValue,
    modifier = Modifier
        .border(4.dp, if (isDroppable) Color.Green else Color.Red)
        .onExternalDrag(
            onDragStart = { externalDragValue ->
                isDroppable = externalDragValue.dragData is androidx.compose.ui.DragData.Text
            },
        onDragExit = {
            isDroppable = false
        },
        onDrop = { externalDragValue ->
            isDroppable = false
            val dragData = externalDragValue.dragData
            if (dragData is androidx.compose.ui.DragData.Text) {
                setTextFieldValue(textFieldValue.copy(
                    text = textFieldValue.text.substring(0, textFieldValue.selection.start) +
                        dragData.readText() +
                        textFieldValue.text.substring(textFieldValue.selection.end),
                    selection = TextRange(textFieldValue.selection.end)
                ))
            }
        },
    )
)
```

**Comment by Walingar** [comment]
@hakanai thank you for your example! 
Indeed, it is available in 1.4.0 as an experimental feature. So, please try it out and provide us feedback!

Also, @hakanai can you please describe your use case for DnD from Compose app. I will be glad if you can create a separate issue for that and describe it there!

**Comment by June6-android** [comment]
What if I want to drop an image and send it somewhere as a file? How can I transform a Painter object to a file object?

`.onExternalDrag(
        onDragStart = {
            isDroppable = true
        },
        onDragExit = {
            isDroppable = false
        },
        onDrop = { externalDragValue ->
            isDroppable = false
            val dragData = externalDragValue.dragData
            if (dragData is androidx.compose.ui.DragData.Image) {
                val img = dragData.readImage()

            }
        }
    )`

**Comment by dima-avdeev-jb** [comment]
@June6-android You can try this code:
```Kotlin
fun savePainterToFile(painter: Painter, file: File) {
    val image: Image = painter.toAwtImage(Density(1f), LayoutDirection.Ltr)
    val bufferedImage = BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_RGB)
    bufferedImage.graphics.drawImage(image, 0, 0, null);
    ImageIO.write(bufferedImage, "png", file)
}
```

**Comment by SinaMegapolis** [comment]
Currently im trying to disable/enable drag and drop for a widget using this modifier, but on runtime the component never gets recomposed to check for the drag data type
Is there any better way to do this?
`kotlin
var isDroppable by remember { mutableStateOf(false) }
val dragModifier: Modifier = Modifier.onExternalDrag (
                                                      enabled = isDroppable,
                                                      onDragStart = {
                                                           val data = it.dragData
                                                           isDroppable = data is DragData.FilesList
                                                      }
                                               )`

**Comment by okushnikov** [comment]
Please check the [following ticket](<a href="https://youtrack.jetbrains.com/issue/CMP-222">following ticket</a>) on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-222">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
