### ISSUE TITLE
is there more example about compose web?

### ISSUE THREAD

**Issue by MansonLuo** [JetBrains/compose-multiplatform#2221]

**Comment by eymar** [comment]
the list of examples is here https://github.com/JetBrains/compose-jb/tree/master/tutorials/Web#examples

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2221">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
