### ISSUE TITLE
how to get pic Paint in IOS platform

### ISSUE THREAD

**Issue by happyjun** [JetBrains/compose-multiplatform#2229]
I want use Image(painter = BitMapPaint) in IOS platform ,but i don't know how to get image Paint in ios platform

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2229">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
