### ISSUE TITLE
How do I get the background color of the tray bar on a mac?

### ISSUE THREAD

**Issue by gtoxlili** [JetBrains/compose-multiplatform#2234]
The color of the tray on a mac is usually related to the wallpaper rather than whether it is dark mode, on electron you usually use [template-image](https://github.com/electron/electron/blob/main/docs/api/native-image.md#template-image) to solve this problem, I wonder if there is such a solution in compose-jb or an interface to get the background color of the tray bar?

**Comment by heytherewill** [comment]
This can be done via AWT using `System.setProperty("apple.awt.enableTemplateImages", "true")` (assuming that your image follows the template conventions of just using pure black and the alpha channel)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2234">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
