### ISSUE TITLE
GrMtlCaps::getGPUFamily doesNotRecognizeSelector

### ISSUE THREAD

**Issue by happyjun** [JetBrains/compose-multiplatform#2235]
when run experiment ios demo on iphone 7, crash whith below exception backtrace:

0x182386d8c __exceptionPreprocess + 228
0x1815405ec objc_exception_throw + 55
0x182394098 -[NSObject+ 1388696 (NSObject) doesNotRecognizeSelector:] + 139
0x18238c5c8 ___forwarding___ + 1379
0x18227241c _CF_forwarding_prep_0 + 91
0x1055274c8 GrMtlCaps::getGPUFamily+ 11187400 (id<MTLDevice>, GrMtlCaps::GPUFamily*, int*) + 51
0x1055261b4 GrMtlCaps::GrMtlCaps+ 11182516 (GrContextOptions const&, id<MTLDevice>) + 411
0x10552a9b0 GrMtlGpu::GrMtlGpu+ 11200944 (GrDirectContext*, GrContextOptions const&, id<MTLDevice>, id<MTLCommandQueue>, void const*) + 235
0x10552a888 GrMtlGpu::Make+ 11200648 (GrMtlBackendContext const&, GrContextOptions const&, GrDirectContext*) + 91
0x1054215f4 GrDirectContext::MakeMetal+ 10114548 (GrMtlBackendContext const&, GrContextOptions const&) + 203
0x10542150c GrDirectContext::MakeMetal+ 10114316 (GrMtlBackendContext const&) + 183
0x10574693c org_jetbrains_skia_DirectContext__1nMakeMetal + 107
0x104d5ffc8 kfun:org.jetbrains.skia.DirectContext.Companion#makeMetal+ 3030984 (kotlin.native.internal.NativePtr;kotlin.native.internal.NativePt
0x104dc3818 kfun:org.jetbrains.skiko.redrawer.MetalRedrawer#makeContext+ 3438616 (){}org.jetbrains.skia.DirectContext + 267
0x104dc137c kfun:org.jetbrains.skiko.context.MetalContextHandler#initContext+ 3429244 (){}kotlin.Boolean + 467
0x104da59e8 kfun:org.jetbrains.skiko.context.ContextHandler#draw+ 3316200 (){} + 227
0x104dc55f4 kfun:org.jetbrains.skiko.redrawer.MetalRedrawer.draw#internal + 343
0x104dc5da4 kfun:org.jetbrains.skiko.redrawer.MetalRedrawer.$<init>$lambda-0COROUTINE$147.invokeSuspend#internal + 331
0x104dc6028 kfun:org.jetbrains.skiko.redrawer.MetalRedrawer.$<init>$lambda-0COROUTINE$147.invoke#internal + 199
0x104da357c kfun:org.jetbrains.skiko.FrameDispatcher.$<init>$lambda-0COROUTINE$146.invokeSuspend#internal + 1031
0x104aa2438 kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith+ 156728 (kotlin.Result<kotlin.Any?>){} + 563
0x104bf3dbc kfun:kotlinx.coroutines.DispatchedTask#run+ 1539516 (){} + 2675
0x104da6874 kfun:org.jetbrains.skiko.NsQueueDispatcher.dispatch$lambda-0#internal + 131
0x104da6b94 kfun:org.jetbrains.skiko.NsQueueDispatcher.$dispatch$lambda-0$FUNCTION_REFERENCE$785.invoke#internal + 71
0x104da6c8c kfun:org.jetbrains.skiko.NsQueueDispatcher.$dispatch$lambda-0$FUNCTION_REFERENCE$785.$<bridge-UNN>invoke+ 3320972 (){}#internal + 71
0x104da7d3c _6f72672e6a6574627261696e732e736b696b6f3a736b696b6f_knbridge130 + 251
0x181c78aa0 _dispatch_call_block_and_release + 23
0x181c78a60 _dispatch_client_callout + 15
0x181c8565c _dispatch_main_queue_callback_4CF$VARIANT$mp + 1011
0x18232f070 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 11
0x18232cbc8 __CFRunLoopRun + 2271
0x18224cda8 CFRunLoopRunSpecific + 551
0x184232020 GSEventRunModal + 99
0x18c26c758 UIApplicationMain + 235
0x10516cffc kfun:#main+ 7278588 (){} + 1347
0x10516ee44 Konan_start + 107
0x1051f6ce8 Init_and_run_start + 107
0x181cddfc0 start + 3

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2235">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
