### ISSUE TITLE
Rendering problem on windows platform

### ISSUE THREAD

**Issue by Someonewow** [JetBrains/compose-multiplatform#2246]
Apps built on the Windows platform, when the window is zoomed in and out, the rendering of the background does not seem to keep up, and some frames are dropped.

The project that demonstrates the problem is [official example codeviewer](https://github.com/JetBrains/compose-jb/tree/master/examples/codeviewer)

<img alt="demo" src="https://github.com/Someonewow/ImageSpace/blob/main/compose-jb-issue.gif?raw=true" height="400" />

**Comment by esp-er** [comment]
Try running with command line flag `-Dskiko.vsync.enabled=false` -- It's not a solution, really, but you could try and see how much Vsync is affecting things.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2246">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
