### ISSUE TITLE
Material3 version out-of-date

### ISSUE THREAD

**Issue by SaltyQuetzals** [JetBrains/compose-multiplatform#2263]
It looks like the Material 3 implementation being used in Compose Multiplatform is 1.0.0-alpha01. Is there any effort to modernize the version (latest is 1.0.0-alpha16)?

**Comment by stashymane** [comment]
Beta version has been released as well. Looking forward to any updates :)

**Comment by MatkovIvan** [comment]
Outdated, we update regularly. Compose 1.6.1 contains Material 3 1.2.1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2263">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
