### ISSUE TITLE
Compatibility between Android and Desktop versions of material3

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2284]
When users develop a multiplatform project and use material3 library, they face crashes when they run Android target:

https://github.com/JetBrains/compose-jb/issues/2176
https://github.com/JetBrains/compose-jb/issues/2037
https://github.com/JetBrains/compose-jb/issues/1978
https://github.com/JetBrains/compose-jb/issues/1582
https://github.com/JetBrains/compose-jb/issues/1890

This happens, because when we compile Android target, we use artifact of Jetpack Compose Material3 published by Google. And this artifact most probably contain incompatible with desktop experimental functions. That is because material3 has its own release cycle, and when we release desktop, we pick the release commit of the main Jetpack Compose. There can be distance in 2 weeks between this commit and the commit of the Material3 release. And at this time there can be new incompatible changes for experimental functions.

Solutions for this issue:
1. Wait for the Material3 stable release. Then, at least for non-experimental functions, we won't face this issue because of backward compatibility.
2. Maintain a separate fork, only for material3, and ship desktop releases of material3 separately, and in sync with Jetpack Compose Material3 releases.
3. Ship our own material3 for Android. Most probably isn't an option, because we lose compatibility with Android libraries that depend on materlal3
4. Manually cherry-pick all commits for material3 into desktop release

**Comment by igordmn** [comment]
Workaround is to define own expect/actual function when there is crash because of incompatibility, and implement it differently in androidMain/desktopMain.

For example, we face crash "Cannot find a parameter with this name: values
No value passed for parameter 'value'", because of [this](https://android-review.googlesource.com/c/platform/frameworks/support/+/2134393) change.

v1.2.0-alpha01-dev774 doesn't have this change, but Jetpack Compose Material3 Jetpack Compose Material3 1.0.0-alpha14 has this change.

Then, we create our own `fun expect RangeSliderFix(values: ClosedFloatingPointRange<Float>, ...)`, and in androidMain we use `RangeSlider(value, ...)` and in desktopMain we use `RangeSlider(values, ...)`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2284">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
