### ISSUE TITLE
Min/Max size window

### ISSUE THREAD

**Issue by denchic45** [JetBrains/compose-multiplatform#2285]
Is it possible to limit the size of a resizable window?

**Comment by Winterreisender** [comment]
Maybe this would help

```kotlin
fun main() {
    application {
        val winState = rememberWindowState(size = DpSize(500.dp,500.dp))
        Window(::exitApplication,winState) {
            LaunchedEffect(winState.size) {
                if(winState.size.width < 400.dp)
                    winState.size = DpSize(400.dp,winState.size.height)
            }
            Text(winState.size.toString())
        }
    }
}
```

But it sometimes has a bug like this: the winState.size.with is not the real width

![image](https://user-images.githubusercontent.com/72203788/188273543-7447677f-82c8-494c-8fb7-f13a3f541509.png)

**Comment by Burtan** [comment]
Would be nice to add this to the windowState api.

**Comment by succlz123** [comment]
```
        Window(...){
            window.minimumSize = Dimension(1080,720)
        }
```

Give it a try.

**Comment by denchic45** [comment]
Yes it works. but I noticed another problem, maximumSize does not work, it does not limit window scaling in any way

**Comment by DuchGhast** [comment]
> ```
>         Window(...){
>             window.minimumSize = Dimension(1080,720)
>         }
> ```
> 
> Give it a try.

On Windows 11, compose 1.4.0, kotlin 1.8.20, scale 200%.

```
window.minimumSize = Dimension(1080,720)
```

sets the window to the passed size but the window can be resized to half of the passed size

**Comment by m-sasha** [comment]
> sets the window to the passed size but the window can be resized to half of the passed size

The `window.minimumSize` is Swing API, not compose. Therefore it's values are (system; logical) pixels, not Compose `dp`.

**Comment by DuchGhast** [comment]
@m-sasha
> Swing API, not compose
I am aware of that but there does not seem to be way to set minimum size in compose.
And `window.minimumSize` does not seem to respect the system scale.

**Comment by tterebko** [comment]
Hi All,
I faced the same challenge while implementing transparent and undecorated window with custom resize by dragging composable  in the right bottom corner. I worked out the translation from dp to pixels out with `LocalDensity`.

```
fun main() {
    application {
        val winState = rememberWindowState(size = DpSize(800.dp, 600.dp) * 1.2f)
        Window(::exitApplication,winState) {
            with (LocalDensity.current) {
            val minSize = DpSize(800.dp, 600.dp).toSize()
            window.minimumSize = java.awt.Dimension(minSize.width.toInt(), minSize.height.toInt())
        }
        }
    }
}
```

**Comment by Omico** [comment]
Since it is a Swing API, we only need to set it once. Check this out.
```
@Composable
fun FrameWindowScope.setMinimumSize(
    width: Dp = Dp.Unspecified,
    height: Dp = Dp.Unspecified,
) {
    val density = LocalDensity.current
    LaunchedEffect(density) {
        window.minimumSize = with(density) {
            Dimension(width.toPx().toInt(), height.toPx().toInt())
        }
    }
}

@Composable
fun FrameWindowScope.setMinimumSize(size: Dp = Dp.Unspecified): Unit =
    setMinimumSize(
        width = size,
        height = size,
    )

@Composable
fun FrameWindowScope.setMinimumSize(size: DpSize = DpSize.Unspecified): Unit =
    setMinimumSize(
        width = size.width,
        height = size.height,
    )
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2285">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
