### ISSUE TITLE
Can't Build Compose project when interface contains composable function

### ISSUE THREAD

**Issue by BreimerR** [JetBrains/compose-multiplatform#2291]
When I add fun add to my interface then the project does not build at all
```
interface SomeCoreScope {
    val composables: MutableList<@Composable () -> Unit>
    fun add(composable: @Composable () -> Unit) {
        composables.add(
            composable
        )
    }
}
```

If i utilize this in else where i.e 
```
interface SomeInterface: SomeCoreScope
```
Project fails to build with ```org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering``` thrown as the error

Project sample https://github.com/BreimerR/ComposeInterfaceException.git

**Comment by eymar** [comment]
could you please try with compose 1.2.0-alpha01-dev774?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2291">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
