### ISSUE TITLE
Are there any specific plans for iOS support? When?

### ISSUE THREAD

**Issue by GavinNovate** [JetBrains/compose-multiplatform#2292]

**Comment by fendo8888** [comment]
同问

**Comment by ToyajNigamByjus** [comment]
I m trying to build but no luck, when we can expect working version in iOS

**Comment by etolstoy** [comment]
Since Compose Multiplatform 1.4.0 the framework is able to target iOS!

- [Announcement blog post](https://blog.jetbrains.com/kotlin/2023/05/compose-multiplatform-for-ios-is-in-alpha/)
- [Sample project](https://github.com/JetBrains/compose-multiplatform-ios-android-template#readme)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2292">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
