### ISSUE TITLE
skiko.wasm and skiko.js not being generated during first build

### ISSUE THREAD

**Issue by mykola-dev** [JetBrains/compose-multiplatform#2295]
Steps to reproduce:
- clean project
- gradlew jsBrowserDistribution
make sure `skiko.wasm` and `skiko.js` are absent in the `build/distributions`
- do gradlew jsBrowserDistribution again
make sure all the required files are in place.

Android Studio Electric Eel preview 10
win10

you can reproduce it on https://github.com/mykola-dev/Tetris

**Comment by Xerosigma** [comment]
This isn't an issue in the latest tooling. So long as as you include `compose.experimental { web.application {} }` you should see skiko.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2295">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
