### ISSUE TITLE
Undo doesn't work properly after we cut or paste text into TextField

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2298]
Reproduced in 1.2.0-alpha01-dev774 and 1.1.0

```
import androidx.compose.material.TextField
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.window.singleWindowApplication

var text by mutableStateOf("")

fun main() = singleWindowApplication {
    TextField(text, { text = it })
}
```

1. Type "123456"
2. Select "23"
3. Press "Ctrl-X" to cut text
4. Press "Ctrl-Z" to undo the cut

Expected: 123456 in the TextField
Actual: 1234 in the TextField

https://user-images.githubusercontent.com/5963351/189001217-e847217c-5e7a-4ecb-9a9f-db098e90cc53.mov

**Comment by elijah-semyonov** [comment]
Observation:
Works fine when keyboard is used to select the text, can help to track the exact problem.

https://user-images.githubusercontent.com/4167681/236196164-25648ab8-d536-45a6-83ea-7e4ed2ef90cc.mov

**Comment by elijah-semyonov** [comment]
UndoManager.makeSnapshot is not called occasionally, if user typed something in and selected a text.
