### ISSUE TITLE
mingwX64 support

### ISSUE THREAD

**Issue by bulatgaleev** [JetBrains/compose-multiplatform#2305]
Any plans to add support for mingwX64?

**Comment by shalva97** [comment]
Yeah, there is MacOS so why not Windows...

**Comment by m-sasha** [comment]
Support it in what sense?

**Comment by titanseason** [comment]
Still got same error with `org.jetbrains.compose.foundation:foundation:1.5.10`
Any plan to support mingwX64?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2305">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
