### ISSUE TITLE
Select Input with multiple=true not working as expected

### ISSUE THREAD

**Issue by DanielScholzde** [JetBrains/compose-multiplatform#2311]
I want to use a Select input (Compose for web) with the option multiple=true. The selected values are stored in a variable of type MutableState&lt;List&lt;String&gt;&gt;.

    val roles = remember { mutableStateOf(listOf("role1", "role2")) }
    val options: Pair<String, String> = ....

    Select(
        multiple = true,
        attrs = {
            onInput {
                roles.value = it.value // does not work; it.value is always a single value (the first selected option) and not a list 
            }
        }
    ) {
        options.forEach {
            Option(it.first, attrs = { if (it.first in roles.value) selected() }) {
                Text(it.second)
            }
        }
    }

The issue is that the onInput event-handler always gets a single selected entry (the first one) and not all selected entries. Is it a bug or am I using it wrong?

**Comment by eymar** [comment]
Unfortunately, the current API doesn't provide a convenient way to handle multiple selected options.

As a workaround, you may use something like:

```kotlin
roles.value = it.target.selectedOptions.asList().map { it.asDynamic().value }
```

And we'll try to improve the API for multiple selection.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2311">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
