### ISSUE TITLE
packageDmg run or UberJar run both error

### ISSUE THREAD

**Issue by simplepeng** [JetBrains/compose-multiplatform#2316]
![image](https://user-images.githubusercontent.com/12198830/190370845-30b3e3f8-d92e-4272-8eef-6dbea2881284.png)

**Comment by simplepeng** [comment]
kotlin.version=1.6.10
agp.version=4.2.2
compose.version=1.1.0

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2316">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
