### ISSUE TITLE
TooltipArea does not allow passing in popup parameters

### ISSUE THREAD

**Issue by SageKreiter** [JetBrains/compose-multiplatform#2322]
It would be useful to be able to pass in parameters like `onKeyEvent` and `focusable` into the `TooltipArea` composable. This would allow a caller to use a key press when the popup is open.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2322">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
