### ISSUE TITLE
Consider publishing MPP runtime-rxjava artifacts

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/compose-multiplatform#2325]
These should be available on the JVM as RxJava is a JVM library. This is only possible in this repo (as opposed to in AndroidX) because you publish the runtime for the JVM which these libraries depend on.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2325">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
