### ISSUE TITLE
Cannot modify image assets used in MSI installer

### ISSUE THREAD

**Issue by sebkur** [JetBrains/compose-multiplatform#2335]
I'm successfully packaging MSI files using the Gradle plugin, however I cannot yet specify the images used in the MSI installer.

**Comment by sebnuc** [comment]
This is what I'm trying to achieve, swap out the images on the left in the first screen and the banner at the top of the second screen:

![Screenshot 2022-09-21 125500](https://user-images.githubusercontent.com/113822008/191502667-e36b24df-2c14-4bc2-b176-67cefe7075e3.png)
![Screenshot 2022-09-21 125517](https://user-images.githubusercontent.com/113822008/191502672-05f5424d-019c-4df7-a6bc-5851fb7f9a59.png)

**Comment by sebkur** [comment]
As explained in the [WIX documentation](https://wixtoolset.org//documentation/manual/v3/wixui/wixui_customizations.html) it is possible to set those images using these options in `main.wxs`, for example like this:

```xml
<?define JpResources = $(env.GRADLE_PROJECT_DIR)\src\jpackage\assets?>
<WixVariable Id="WixUIBannerBmp" Value="$(var.JpResources)\banner.bmp" />
<WixVariable Id="WixUIDialogBmp" Value="$(var.JpResources)\dialog.bmp" />
```

in order for this to work two things are necessary:
1. we need to be able to add additional resources into the directory passed to `jpackage` with flag `--resource-dir` (#1972)
2. we need to have some way to define an environment variable that is accessible from thw WX toolchain process

**Comment by sebkur** [comment]
I have a solution for 1.) ready here at: #2331 and will prepare a solution for 2.) shortly.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2335">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
