### ISSUE TITLE
how to change the behavior of default menu on macOS

### ISSUE THREAD

**Issue by xinkun-mini** [JetBrains/compose-multiplatform#2344]
![image](https://user-images.githubusercontent.com/112530409/192722060-c926932a-d804-40a0-bfab-3c5c74117a22.png)

1. Can I add some item to the default menu, like: 'check update' ?

2. Can I make the `quit` action use cmd+Q same logic as `window.onCloseRequest` ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2344">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
