### ISSUE TITLE
Button bounds become incorrect after adding an onClick or pointerInput modifier

### ISSUE THREAD

**Issue by hakanai** [JetBrains/compose-multiplatform#2348]
1. Given this sample app:

```kotlin
@file:OptIn(ExperimentalFoundationApi::class)

import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.PointerMatcher
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.requiredSize
import androidx.compose.foundation.onClick
import androidx.compose.material.MaterialTheme
import androidx.compose.material.OutlinedButton
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.RectangleShape
import androidx.compose.ui.input.pointer.PointerButton
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    MaterialTheme {
        Column {
            repeat(3) {
                Row {
                    repeat(3) {
                        OutlinedButton(
                            onClick = {},
                            shape = RectangleShape,
                            contentPadding = PaddingValues(0.dp),
                            modifier = Modifier
                                .requiredSize(40.dp)
                                .onClick(
                                    matcher = PointerMatcher.mouse(PointerButton.Secondary),
                                    onClick = {}
                                )
                        ) {
                            // ...
                        }
                    }
                }
            }
        }
    }
}
```

2. Run it and observe what happens when the mouse is very close to button borders.

Expected result:
![image](https://user-images.githubusercontent.com/43236/193178318-88ae6306-5ff0-4b06-9a91-1f4fba636341.png)

Actual result:
![image](https://user-images.githubusercontent.com/43236/193178380-7802e53e-bcfb-4c68-86cf-993a33cf8ce9.png)

And it turns out that if I right-click, the onClick is delivered to the button immediately below, not the one I'm hovering over. This was what hinted to me that it was caused by adding the experimental onClick handler, and in fact, if I comment that out, the button behaves correctly again (other than now having no way to right-click).

**Comment by hakanai** [comment]
Tested with `pointerInput`, same result there. Just adding pointerInput is enough to break it (no need to try and detect gestures):

```kotlin
                            modifier = Modifier
                                .requiredSize(40.dp)
                                .pointerInput(Unit) {}
```

**Comment by hakanai** [comment]
Same deal with `clickable` except now it highlights the area, which gives a good idea of how many pixels out it is.

![image](https://user-images.githubusercontent.com/43236/193182091-683eac65-6e6e-444e-a002-2c3fe5141ff0.png)

**Comment by eymar** [comment]
> There must be something different

There is `minimumTouchTargetSize()` modifier added internally. And what makes the difference is the order of modifiers. Your custom Modifier.clickable modifier is applied before  `minimumTouchTargetSize`, but the original button's clickable is applied after it.

For you desktop app, you might try wrap your entry point with:
```kotlin
CompositionLocalProvider(LocalMinimumTouchTargetEnforcement provides false) { ... }
```
(but it's not a good workaround for android apps where it's difficult to click small buttons using Touch) Did you try your example on android by chance? 


Another way: simply making `.requiredSize(56.dp)` or any value bigger than default minTouchArea (48.dp) also makes the issue go away (at least makes it hidden).

**Comment by hakanai** [comment]
`LocalMinimumTouchTargetEnforcement` works nicely. This app's desktop only anyway.

I kind of get the Android thing where it forces a minimum size, I just find it surprising how when two touch areas overlap, it doesn't always go for the closest one to the click location. I play a few games on iOS with much smaller touch areas and those always seem to go for the button which the tap is closer to, rather than always choosing the lower one.

**Comment by eymar** [comment]
>  I just find it surprising how when two touch areas overlap, it doesn't always go for the closest one to the click location

Indeed. It goes not to the closest by x,y, but to the most top area. Touch areas can be imagined as layers. The later added areas (components) can partially or completely overlap the areas added before them (if their area is bigger than of those added before them).  And if a certain layer on top covers x, y coordinates of  a pointer event then it's assumed to be the receiver of that event.

Ideally, the adjacent components' touch areas shouldn't overlap. 
In your example each button has 2 touch areas (one for default clickable, and another one added by Modifier.onClick).
And only one area had its minimumTouchTargetSize forced. And when one of the areas became bigger, it covered earlier added areas.

I think we need to carefully think about how new experimental onClick affects components with default clickable.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2348">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
