### ISSUE TITLE
Drawer acts weird while resizing the application

### ISSUE THREAD

**Issue by EmreAka** [JetBrains/compose-multiplatform#2354]
https://user-images.githubusercontent.com/77541730/193756599-445fb534-0f4a-46f4-af0c-c154a497c4ff.mp4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2354">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
