### ISSUE TITLE
Can't enable subpixel antialias in linux

### ISSUE THREAD

**Issue by yuulf** [JetBrains/compose-multiplatform#2358]
Rendered fonts in compose seems to use only grayscale antialias on my system (compose 1.2.0-beta01, openSUSE Leap 15.3, java 11). Somehow this problem is similar to https://github.com/JetBrains/compose-jb/issues/875, but even even if i run this example https://github.com/JetBrains/compose-jb/issues/875#issuecomment-900322796 it has only grayscale antialias. Is there a problem with my setup or  [the mentioned issue in skia](https://bugs.chromium.org/p/skia/issues/detail?id=10833)?

**Comment by igordmn** [comment]
#875 is only about Windows.

For Linux we should add a separate fix. Skia/Skiko doesn't read system text properties a t the moment

**Comment by yuulf** [comment]
Thank you, looking forward to it.

**Comment by imherrera** [comment]
Any update on this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2358">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
