### ISSUE TITLE
Catch-22 calling singleWindowApplication with icon parameter

### ISSUE THREAD

**Issue by hakanai** [JetBrains/compose-multiplatform#2369]
In my main function, I tried to add an icon:
```kotlin
fun main() = singleWindowApplication(
    title = "Calculator",
    icon = painterResource("/AppIcon.png"),
) {
    MainUi()
}
```

This fails to compile:
```
e: ...\Main.kt: (7, 5): Functions which invoke @Composable functions must be marked with the @Composable annotation
e: ...\Main.kt: (9, 12): @Composable invocations can only happen from the context of a @Composable function
```

Fair enough, so I try to make the function `@Composable`:
```kotlin
@Composable
fun main() = singleWindowApplication(
    title = "Calculator",
    icon = painterResource("/AppIcon.png"),
) {
    MainUi()
}
```

This fails to compile too:
```
e: ...\Main.kt: (9, 5): Composable main functions are not currently supported
```

So it seems impossible to call `painterResource` in order to pass the painter in as the icon. Maybe there is an alternative way to get an icon, but I wasn't able to find it and the docs don't even talk about how to get an icon. The `painterResource` function itself is implemented using internal functions, so there doesn't seem to be anything lower level I can use that isn't composable?

As a workaround, avoiding using `singleWindowApplication` works fine:

```kotlin
fun main() = application {
    Window(
        ::exitApplication,
        title = "Calculator",
        icon = painterResource("/AppIcon.png"),
    ) {
        MainUi()
    }
}
```

But if the `icon` parameter is going to remain on `singleWindowApplication`, it would be nice if it were possible to use that.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2369">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by sschuberth** [comment]
> `icon = BitmapPainter(useResource("sample.png", ::loadImageBitmap))`

How to solve this now with Compose 1.7.0 where `useResource()` is deprecated in favor of Compose resources?

**Comment by mahozad** [comment]
I've used the following code:

```kotlin
val icon= Res
    .getUri("drawable/logo.svg")
    .let(::URI)
    .toURL()
    .readBytes()
    .decodeToSvgPainter(Density(1f))
singleWindowApplication(
    icon = icon,
    // ...
```

It would be nice to have a synchronous/blocking variant of `Res.readBytes()` for this use case.

**Comment by sschuberth** [comment]
Here's my variant for bitmaps based on yours:

```kotlin
val iconBytes = URI.create(Res.getUri("drawable/app-icon/icon.png")).toURL().readBytes()
val icon = BitmapPainter(iconBytes.decodeToImageBitmap())
```
