### ISSUE TITLE
Provide a JUnit 5 Extension instead of a JUnit 4 Rule

### ISSUE THREAD

**Issue by hakanai** [JetBrains/compose-multiplatform#2371]
Since the test API is considered experimental anyway, and given that JUnit 4 has been outdated for some time now, it would be nice if the current `TestRule` were replaced by a `Extension`.

I already took a shot at writing such a thing in my own code, but the structure of the current `TestRule` makes it impossible to reuse - it's implemented by wrapping _around_ the test execution, which is the one kind of extension which JUnit 5 doesn't have support for.

I also attempted to pull the code out of the current test rule to write a new extension, but it's relying on a lot of internal classes, so I think I'd have to clone the entire module to get anything working.

**Comment by mahozad** [comment]
Related: https://github.com/android/android-test/issues/224

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2371">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
