### ISSUE TITLE
compose with opengl

### ISSUE THREAD

**Issue by daocaoren123** [JetBrains/compose-multiplatform#2375]
I recently experimented with a desktop application for compose and opengl. A window contains basic controls such as button and image rendering area. Is there any control that can implement opengl image rendering?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2375">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
