### ISSUE TITLE
Main JavaScript file doesn't load in Compose Multiplatform project

### ISSUE THREAD

**Issue by jorn86** [JetBrains/compose-multiplatform#2380]
Originally posted [on StackOverflow](https://stackoverflow.com/q/73949956/8681), I was requested to file an issue here.

I'm trying to follow the [Compose Multiplatform Web](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Web/Getting_Started) Getting Started guide. Most of it seems to work fine, but when I try to actually run the thing (`gradle jsBrowserRun`), it starts a browser, but it can't find the generated JavaScript file. The browser console shows a 404 for `GET http://localhost:8080/kotlin-multi-web.js`.

The file `kotlin-multi-web.js` is indeed the name of a file generated in `web/build/compileSync/main/developmentExecutable/kotlin`.

The page title matches the one I defined in my `index.html`, so that gets loaded correctly.

I have tried a pure Compose Web project (which isn't a Gradle multi module project), and there it does all load correctly. I checked, and didn't see any differences between the Gradle build files other than the extra dependency from the `web` project on `common`.

I have uploaded my project to [github.com/jorn86/fox-kotlin-multi](https://github.com/jorn86/fox-kotlin-multi), if anyone wants to reproduce this.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2380">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2380">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
