### ISSUE TITLE
Material 3 Text is not centered (has top and right margin/padding)

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#2383]
I'm migrating to Material Design 3 and using components from `androidx.compose.material3` instead of `androidx.compose.material`.

The string in `Text` composable has a little top margin/padding (and also end or right margin/padding) in the new Material 3:

| Material 2 (old) | Material 3 (new) |
| ----------------- | ------------------ |
| ![material-2](https://user-images.githubusercontent.com/29678011/194923817-93d85858-a0e3-484a-ad27-0228dcff4566.jpg) | ![material-3](https://user-images.githubusercontent.com/29678011/194923868-51f36abd-97e2-41b7-9e96-438fecfd9360.jpg) |

Here is a minimum reproducible project:
[test-text.zip](https://github.com/JetBrains/compose-jb/files/9747957/test-text.zip)

I'm using Compose JB 1.1.1, Kotlin 1.6.10, Java 17.0.4 and I am on Windows 11 and the app sets `System.setProperty("skiko.renderApi", "OPENGL")` because of #610.

**Comment by mahozad** [comment]
The problem still exists in compose multiplatform 1.3.0-rc5 and Kotlin 1.8.0 and Oracle JDK 17.0.5.

**Comment by dima-avdeev-jb** [comment]
@mahozad Thanks for this Issue!
Can you please provide reproducible sample on GitHub?

**Comment by dima-avdeev-jb** [comment]
Sorry, I missed [test-text.zip](https://github.com/JetBrains/compose-jb/files/9747957/test-text.zip).
I will look into it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2383">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
