### ISSUE TITLE
 "Expected function 'Dialog' has no actual declaration in module XXXX.androidAndroidTestRelease for JVM"

### ISSUE THREAD

**Issue by nadyboy** [JetBrains/compose-multiplatform#2385]
I learned the "todoapp" project. There is a technology "expect" in this project. After I started writing, a warning appeared, "Expected function 'Dialog' has no actual declaration in module XXXX.androidAndroidTestRelease for JVM". However, I did not set "androidAndroidTestRelease". I have "androidMain" and "desktopMain" but no "androidAndroidTestRelease", I'll eliminate this warning in this way

我学习了“todoapp”项目,在这个项目中有一项技术“expect”，我开始书写后出现了一个警告，“Expected function 'Dialog' has no actual declaration in module XXXX.androidAndroidTestRelease for JVM”，然而我并没有设置"androidAndroidTestRelease",我有“androidMain”和“desktopMain”但是并没有“androidAndroidTestRelease”，我改这么消除这个警告

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2385">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
