### ISSUE TITLE
Support material3-window-size-class

### ISSUE THREAD

**Issue by manosbatsis** [JetBrains/compose-multiplatform#2404]
See https://developer.android.com/reference/kotlin/androidx/compose/material3/windowsizeclass/WindowSizeClass

**Comment by egorikftp** [comment]
any updates?

**Comment by wakaztahir** [comment]
any updates?

**Comment by LaylaMeower** [comment]
Bumping this up!

**Comment by pablichjenkov** [comment]
> Bumping this up! Any info?

What makes it different than just getting the size of your root composable and using CompositionLocal to pass it down the tree?

**Comment by LaylaMeower** [comment]
> > Bumping this up! Any info?
> 
> What makes it different than just getting the size of your root composable and using CompositionLocal to pass it down the tree?

Material3 theme guidelines have exact descriptions of what to use with different size classes, for example, drawer for large, rail for medium, and bar for small.

**Comment by pablichjenkov** [comment]
> > > Bumping this up! Any info?
> > 
> > What makes it different than just getting the size of your root composable and using CompositionLocal to pass it down the tree?
> 
> Material3 theme guidelines have exact descriptions of what to use with different size classes, for example, drawer for large, rail for medium, and bar for small.

I see your point but what I mean is that this is something in the application side rather than in compose itself. It is in the material spec however I don't see a size to describe TV. Also I believe the width/height aspect ratio is important too, not just one dimension size.
So that is why I believe JB/Google has not include it in compose but keep it as separate Library.
And it is not hard to compute too.

**Comment by LaylaMeower** [comment]
> I see your point but what I mean is that this is something in the application side rather than in compose itself. It is in the material spec however I don't see a size to describe TV. Also I believe the width/height aspect ratio is important too, not just one dimension size.

Well, it is not a separate library - for JetBrains Compose it simply does not exist. I do not see why would you not implement features that can be found in Google Compose.

For me, writing the math myself isn't worth it. Sure, it is simple, but I have lots of these small simple stuff to implement. If it was a library, android & iOS support could be a thing - but it is not, and implementing support for them manually, as I said, will take too much time.

**Comment by pablichjenkov** [comment]
> > I see your point but what I mean is that this is something in the application side rather than in compose itself. It is in the material spec however I don't see a size to describe TV. Also I believe the width/height aspect ratio is important too, not just one dimension size.
> 
> Well, it is not a separate library - for JetBrains Compose it simply does not exist. I do not see why would you not implement features that can be found in Google Compose.
> 
> For me, writing the math myself isn't worth it. Sure, it is simple, but I have lots of these small simple stuff to implement. If it was a library, android & iOS support could be a thing - but it is not, and implementing support for them manually, as I said, will take too much time.
> 
> This will be a neat thing, but not really major for me. I do not see why would you object to the addition of such an API?

Oh I see, excuse my ignorance. I see it has been released as part of material 3 artifact recently. Sorry I didn't know that, I thought it was still being released as a separate library. In such a case I believe it is just a matter of time until JB catches up with Google stuff.

**Comment by chrisbanes** [comment]
FYI: I built https://github.com/chrisbanes/material3-windowsizeclass-multiplatform as a stop-gap until support comes to Compose Multiplatform.

**Comment by Shabinder** [comment]
With 1.5.0 release.

in desktop, **LocalWindow**.current is marked **internal** and hence not accessible, any known alternative to get current windows DpSize ?

**Comment by egorikftp** [comment]
@igordmn 
Any updates for this issue?

**Comment by issamux** [comment]
hi,

I wonder why we can’t integrate it into the CompositionLocal (at least in android side)

It was very easy to use this like : 

`val LocalDevicePostureFlow = compositionLocalOf<DevicePosture> {
    error("No DevicePostureFlow provided")
}

val LocalWindowSize = compositionLocalOf<WindowSizeClass> {
    error("No WindowSizeClass provided")
}` 

and use it in code : 
`
    val windowSize = calculateWindowSizeClass(this)
                    val devicePosture = devicePostureFlow.collectAsState()
                    CompositionLocalProvider(
                        LocalDevicePostureFlow provides devicePosture.value,
                        LocalWindowSize provides windowSize
                    ) {
                        MyAppComposeUi(uiState)
                    }
`
Am I missing something about using it in Local composition !!!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2404">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
