### ISSUE TITLE
Change the signature of `AttrBuilderContext`

### ISSUE THREAD

**Issue by erikhuizinga** [JetBrains/compose-multiplatform#2409]
I ran into a coincidence when I declared a web composable like so:

```kotlin
@Composable
fun MyComposable(
    attrs = AttrBuilderContext<HTMLDivElement>? = null,
    vararg composables: @Composable () -> Unit,
) { /* impl using div that applies attrs */ }
```

When I called the following, it didn't compile (though my IDE didn't show any issues).

```kotlin
MyComposable(
    { /* Call some composable */ },
    { /* Call some composable */ },
)
```

This doesn't compile, because `AttrBuilderContext` is not composable and must therefore not call composables, which is what happens because the signature of `@Composable () -> Unit` happens to match the signature of `AttrBuilderContext`! See its source:

https://github.com/JetBrains/compose-jb/blob/v1.2.0/web/core/src/jsMain/kotlin/org/jetbrains/compose/web/elements/Elements.kt#L65

This wouldn't be a problem if the signatures certainly wouldn't match, which is what's assumably always the case in compose frameworks that use `Modifier`, like Compose JB for Desktop and Jetpack Compose. However, the `AttrBuilderContext` is so generic (being just a lambda), that it easily clashes with composable lambdas in the lambda-heavy code bases that compose-web has.

I'm not sure how to proceed with this issue. Maybe an 'easy' solution would be to introduce a `fun interface AttrBuilderContext<T>` so that it becomes more explicitly (strongly) typed, instead of using a typealias? Though, that's just a solution and we should consider what the requirements and design goals are for compose-jb/-web and find a solution that fits that.

Note:
A possibly conflicting issue would be #2304, because if that one is implemented, then the code above would compile and lead to currently undefined behaviour.

**Comment by brianguertin** [comment]
I would argue that vararg Composables is not very idiomatic, normally you would just take a single composable. Your issue is only because of your use of varargs.

With a single Composable, the caller can already call multiple composable functions
```kotlin
MyComposable {
    Composable1()
    Composable2()
}
```

If you need a concept of individual "items", you can use a DSL like `LazyColumn`:

```kotlin
LazyColumn {
    item {
        Text(text = "First item")
    }
}
```

This is a more future-proof API.

**Comment by erikhuizinga** [comment]
While non-`vararg` arguments are nore idiomatic compose, it is in the language. And there might be use cases for it that we don't know.

Also, the example described in the issue is expected behaviour for the language. Still, the signature match is not nice, so the issue stands pending on a decision about what to do about it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2409">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2409">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
