### ISSUE TITLE
Image Tutorial: path to imageResource is wrong

### ISSUE THREAD

**Issue by MartinMajewski** [JetBrains/compose-multiplatform#241]
Hi there!

This is related to https://github.com/JetBrains/compose-jb/tree/master/tutorials/Image_And_Icons_Manipulations

`imageResource` requires all subdirectories inside the `resources` folder.

If the image is stored, as stated in the tutorial, in `images/sample.png` inside the `resources` directory, the function call has to be

`Image( bitmap = imageResource("images/sample.png"))`

Cheers,
Martin

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5564">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
