### ISSUE TITLE
 Koltin's' expect/actual '

### ISSUE THREAD

**Issue by nadyboy** [JetBrains/compose-multiplatform#2424]
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/12806468/196959993-d7eef13b-e03e-470d-ab68-b2a3d7aa157e.png">
I use Koltin's' expect/actual 'for cross platform development, but the development tool reminds me that I need to add another "androidAndroidTestRelease", instead of reminding me that I need to implement the interface in "androidMain". How do I modify this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2424">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2424">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
