### ISSUE TITLE
Provide a panel component like the JetBrains Fleet

### ISSUE THREAD

**Issue by ShirasawaSama** [JetBrains/compose-multiplatform#2429]
As shown, fleet's panels can be dragged in multiple fixed areas:

![image](https://user-images.githubusercontent.com/17093811/197633283-96fd95ac-1f92-4c4d-8c5a-8c79779ec690.png)

![image](https://user-images.githubusercontent.com/17093811/197633034-5a241855-15ff-470e-a3c1-1ffbe95f0aba.png)

It can even be opened as a separate window:

![image](https://user-images.githubusercontent.com/17093811/197633509-15bcee52-a1fd-43d6-bec3-421e1d142a7e.png)

So I would really like the compose or a third party can offer a similar solution.

**Comment by DavideCannizzo** [comment]
I think such a component shouldn't be part of Compose — it could be realized as part of a third-party library. You may want implement your own for your own use.

Just some thoughts, for such a component to be implemented by a third-party, we'd need to be able to:
- create a new window to place content on;
- define a custom drag handle to move a borderless window.
I think the above points should already be possible, though I'm not informed about the drag handle.

What would be your reasons to providing such a component as part of Compose? I feel like a generic solution to such a broad problem would be limiting, as different applications might want to have those panels designed in significantly differ manners.
