### ISSUE TITLE
How to add unity into compose project

### ISSUE THREAD

**Issue by Besame521** [JetBrains/compose-multiplatform#2430]
I want use unity to draw some 3D scenes， but i don't know how to add unity to may compose project.  Who can give me some advises?

**Comment by eymar** [comment]
I guess there is no guides for unity + compose cooperation yet.

https://docs.unity3d.com/Manual/UnityasaLibrary.html - Unity as a Library is probably a good starting point:

> Unity as a Library is intended for specialist users who use native platform technologies such as Java/Android, Objective C/iOS, or Windows Win32/UWP, and want to include Unity-powered features in their games or applications.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2430">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
