### ISSUE TITLE
How can I add a round corner to a window when its `undecorated` attribute was set to `true`?

### ISSUE THREAD

**Issue by SpaceXC** [JetBrains/compose-multiplatform#2433]
I don't want the white bar on the top of the window, so I set `undecorated` to `true` and add a customized close and minimize button to the top of the window. But I want my window to be round-cornered and I want to add the system-followed close and minimize button like this 
<img width="162" alt="image" src="https://user-images.githubusercontent.com/60663465/198806159-0843dfbb-fb55-44cf-99ae-6d616ca8f634.png">
How can I do that? Thanks a lot (XD

**Comment by tangshimin** [comment]
related issue https://github.com/JetBrains/compose-jb/issues/877

**Comment by SpaceXC** [comment]
Thanks for answering, but I would like to add more margin like chrome, currently the toolbar is too close to the window edge. Also, how can I implement this on Windows?
<img width="174" alt="image" src="https://user-images.githubusercontent.com/60663465/200828686-659512d5-6bb4-43d9-8140-7b2bc7d79ffd.png">

**Comment by guiyanakuang** [comment]
@SpaceXC You can do this by adding addComponentListener

```kotlin
    Window(onCloseRequest = ::exitApplication,
        undecorated = true) {

        window.addComponentListener(object : java.awt.event.ComponentAdapter() {
            override fun componentResized(e: java.awt.event.ComponentEvent?) {
                window.shape = RoundRectangle2D.Double(
                    0.0,
                    0.0,
                    window.width.toDouble(),
                    window.height.toDouble(),
                    30.0,
                    30.0
                )

            }
        })

        App()
    }
```

**Comment by SpaceXC** [comment]
@guiyanakuang thanks! I'll try that out!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2433">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
