### ISSUE TITLE
issues when I use JpopupTextMenu in Compose for desktop

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/compose-multiplatform#2434]
When I use JPopupTextMenu in Compose for desktop, I have the problem with the following image，I'm using a Windows 10 computer

![image](https://user-images.githubusercontent.com/19502034/198821211-9bc23a50-8fca-493b-ae8d-110a180e8839.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2434">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
