### ISSUE TITLE
[Feature] Empty KeyStroke for assigning menu item shortcuts

### ISSUE THREAD

**Issue by xetra11** [JetBrains/compose-multiplatform#245]
Quoting @tkuenneth
> On Windows the "About" menu item usually has no shortcut. However, Compose for Desktop currently uses KeyStroke(Key.Unknown) as a default (if I do not pass one in), so I end with this.

We need a way to define an "empty" keystroke. The default Unknown renders this
![image](https://user-images.githubusercontent.com/8149023/103369870-867baa00-4acb-11eb-8194-ff021296ef36.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5562">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
