### ISSUE TITLE
need some information about always focus a box like window or dialogue 

### ISSUE THREAD

**Issue by memonahmedanees** [JetBrains/compose-multiplatform#2460]
dear all desktop compose user i hope your are all well i need to know to about how i focus a box always like a window or dialogue currently i cant find this material on git your co operation highly appreciated

**Comment by kirill-grouchnikov** [comment]
Do you mean to have a way to force the focus always in a specific window and prevent the user from interacting with any other application / window on their OS? I certainly hope that such a functionality is not available to any apps on any OS, besides the absolutely useless system-level security prompts in Windows.

**Comment by igordmn** [comment]
Can you provide example of this feature, or describe it in more detail?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2460">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
