### ISSUE TITLE
Update the default app icons

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#2462]
Please update the default icons used for app executables if no icon is provided by the developer.

The current icons contain Kotlin logo (its old version).

I can create a pull request if you'd like (have not tested the *.icns* file).

![compose-logo](https://user-images.githubusercontent.com/29678011/201169741-7f95aae5-4cf7-462c-8cbd-e4dc5b0b2346.svg)

| Old | New |
| --- | --- |
| ![3](https://user-images.githubusercontent.com/29678011/201169508-eeebb541-e182-494b-8e67-0788550a6dac.png) | ![4](https://user-images.githubusercontent.com/29678011/201169575-27dd73e5-6212-4139-9220-d9eace692573.png) |
| ![1](https://user-images.githubusercontent.com/29678011/201169625-74baa9e9-40ef-4dcb-9b8b-d90eba1e1a01.png) | ![2](https://user-images.githubusercontent.com/29678011/201169653-6ebf5ca1-ec87-4386-9216-5bc4e74a6993.png) |

**Comment by igordmn** [comment]
We will change the icon to the new Kotlin icon.

**Comment by mahozad** [comment]
@igordmn Wouldn't it be better to use the compose logo?

I should also mention that the existing .ICO file contains 128x128 size which may not be needed and makes the file unnecessarily large. [The standard sizes for an exe icon can be found here](https://stackoverflow.com/a/74392449/8583692).

**Comment by igordmn** [comment]
> Wouldn't it be better to use the Compose Multiplatform logo?

There are more obstacles for that - discussing with Google, and deciding which icon should be used. There is the separate blue icon for other Compose's than Jetpack Compose (you can see it on [this](https://www.jetbrains.com/lp/compose-mpp/) page), which can be not look good in small scale and on different backgrounds (but I am not sure).

> taking only a vector (SVG) image

That will be great :). But I am not sure that we find resources to implement that in the near future. If you or someone else implements that, we'll gladly review it, and merge if everything is okay.

**Comment by Akhil-Hothi** [comment]
How can we replace the default icon with custom icon in desktop? I am on windows and .exe file has kotlin logo as shown in image.
