### ISSUE TITLE
Window resizing on wayland stutters and lags

### ISSUE THREAD

**Issue by bq-wrongway** [JetBrains/compose-multiplatform#2475]
As tittle says,window resizing stutters, especially when dragging the left edge of the window.
It works much better on wayland, but still not flawless.

I can provide a video if needed.
I am on fedora 37,gnome on wayland, amd graphic card rx580 and ryzen 5 1600
I made a test app and i also downloades one of the example apps, result is the same.

**Comment by eymar** [comment]
> Here is the video, i used also flutter for desktop as comparation. (this is on wayland) https://www.veed.io/view/1c56727c-743e-4da8-901e-dfb84157cace?sharingWidget=true&panel=share

The links shows a page saying that the video has been archived.
I think you can attach a video here right away.

**Comment by mahozad** [comment]
I think the following issue is related;
https://github.com/JetBrains/compose-jb/issues/2283#issuecomment-1341323240

**Comment by weazyexe** [comment]
I have the same issue but on Windows 11.
Kotlin Slack conversation: https://kotlinlang.slack.com/archives/C01D6HTPATV/p1671780372815379

https://user-images.githubusercontent.com/35996778/209327540-119e5daf-fe70-47cb-a631-00031270fcb4.mp4

**Comment by bqMoonlight** [comment]
Hi. this is error on my part. 
It happens only when running in debuging mode (through intellij run command) but when i use 
`./gradlew runRelease` it works with no issues.
Try this, if it fixes your issue as well i would close the issue.

**Comment by weazyexe** [comment]
Thank you for your help but it didn't fix the issue :(
I still have this weird resizing behavior. Neither `gradlew runRelease` doesn't work nor `gradlew runReleaseDistributable`.

**Comment by aykxt** [comment]
The issue title should probably be renamed for discoverability to not be limited to Wayland, as it's affecting Windows (and maybe MacOS?) as well.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2475">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
