### ISSUE TITLE
Dose compose-jb support 32bit JDK on windows?

### ISSUE THREAD

**Issue by whyrookie** [JetBrains/compose-multiplatform#2485]
My program relies on 32-bit dll files, so I have to use Liberica JDK  for 32-bit jdk17（The version is for supporting all features of compose-jb include ”jpackage“ ）.However it's failed. and there is no extra error information.Dose it not support 32-bit?

**Comment by dima-avdeev-jb** [comment]
Sorry, but it's not possible in Compose Multiplatform to support 32-bit dll files.
You can found additional information in this issues:

https://github.com/JetBrains/compose-jb/issues/1862
https://github.com/JetBrains/compose-jb/issues/1819
https://github.com/JetBrains/compose-jb/issues/1213

**Comment by whyrookie** [comment]
Got it. Thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2485">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
