### ISSUE TITLE
[macOS, Dark Theme] In the process of changing the size of the window, there will be some areas that cannot be drawn in time

### ISSUE THREAD

**Issue by drakeet** [JetBrains/compose-multiplatform#2494]
DUPLICATE OF THIS ISSUE: https://github.com/JetBrains/compose-jb/issues/1800

In the process of changing the size of the window, there will be some areas that cannot be drawn in time, resulting in white blocks, see the video:

https://user-images.githubusercontent.com/5214214/203485599-2b832ee1-8525-4d95-8b48-ce30c45b81f0.mp4

I would like to ask if there is any way to solve this kind of detail problem? Thanks!

```
kotlin.version=1.7.20
agp.version=7.1.3
compose.version=1.2.1
```
Reproducible on any Java runtime version.

**Comment by dima-avdeev-jb** [comment]
@drakeet 
 - Do you test it on MacOS, Windows, or Linux?
 - Do you have a dark theme enabled?

**Comment by drakeet** [comment]
@dima-avdeev-jb 
* Just test it on macOS. Use that [codeviewer](https://github.com/JetBrains/compose-jb/tree/master/examples/codeviewer) example to reproduce.
* Yes, the system dark theme/mode is enabled.

**Comment by dima-avdeev-jb** [comment]
**Thanks for the description!**
I think it's related to another issue: https://github.com/JetBrains/compose-jb/issues/1800

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2494">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
