### ISSUE TITLE
Initial rendering in IntelliJ takes a long time

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#2517]
When I open a toolwindow in IJ using Compose UI, the first time it's opened after starting the IDE it takes a significant amount of time to render and become interactive:

https://user-images.githubusercontent.com/153802/204784268-fdf6422e-b039-4655-bacc-b9302cd65f8f.mp4

It takes a visibly long time to do the first draw even when showing a second tab after the first one's very long init.

**Comment by igordmn** [comment]
1. Can you attach the project, where it is reproducible, so I can profile and found a reason?
2. Did it happen when you used Compose as an IDEA plugin dependency, not as maven artifact dependency?
3. Do you use custom fonts? We have [an issue](https://github.com/JetBrains/androidx/pull/336) with them

**Comment by rock3r** [comment]
It's just Jewel, in this case. Maven dependency, and no custom fonts (although I think the swing bridge was trying to load the awt font)

**Comment by m-sasha** [comment]
On my Mac the AWT example is 270ms, the Compose one is 500ms. If I preload all the `androidx.*` classes, the Compose example goes drops to 420ms.

**Comment by rock3r** [comment]
This was fixed in Skiko by my work on font loading, can be closed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2517">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
