### ISSUE TITLE
Ubuntu Touch Support

### ISSUE THREAD

**Issue by mehmetakify** [JetBrains/compose-multiplatform#2519]
Is there a way develop apps with compose for Ubuntu Touch devices that is using .click package? It would be great.

**Comment by pjBooms** [comment]
Touch support for desktop platforms will be added as a separate feature in the future. You can follow [this issue](https://github.com/JetBrains/compose-jb/issues/1555)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2519">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
