### ISSUE TITLE
Make it easier to take screenshots during Compose Desktop tests

### ISSUE THREAD

**Issue by jorn86** [JetBrains/compose-multiplatform#2520]
I have a Compose Desktop 1.2.1 application, and I'm running UI tests. During those tests, I'd like to take some screenshots. To make that possible, I needed to write some code using reflection:

```
class MyUiTest {
  private val uiTest = DesktopComposeUiTest(1920, 1080)
  @get:Rule val rule = createMyComposeRule()

  fun createMyComposeRule() {
    val constructor = DesktopComposeTestRule::class.primaryConstructor!!
    constructor.isAccessible = true
    return constructor.call(uiTest)
  }

  fun takeScreenshot() {
    val data = uiTest.captureToImage().encodeToData()!!
    // save data.bytes to file
  }

  @Test
  fun test() {
    rule.setContent { ... }
    takeScreenshot()
}
```

It would be nice if this was easier, for example by having configuration parameters for the window size on `createComposeRule` and exposing `captureAsImage` through the `Rule`.

**Comment by ialokim** [comment]
It is actually easier now since https://github.com/JetBrains/androidx/pull/310 got merged, see https://github.com/ialokim/androidx/blob/cb3c93a18437c756bb9b9fc272201b3b6e4f76ee/compose/ui/ui-test-junit4/src/desktopTest/kotlin/androidx/compose/ui/test/UseComposeUiTest.kt as an example.

**Comment by jorn86** [comment]
That's certainly a step in the right direction! But I still think it should be possible to do this using the JUnit DesktopComposeTestRule. That's not covered in the PR, as far as I can see.

**Comment by m-sasha** [comment]
This is now possible in Compose Multiplatform 1.5

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2520">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
