### ISSUE TITLE
Unable to use any class or function of jetbrains compose module in non jetbrains-compose module.

### ISSUE THREAD

**Issue by yuvaraj119** [JetBrains/compose-multiplatform#2522]
created branch for reference https://github.com/yuvaraj119/Expressus-temp/pull/1
Steps to reproduce:-
In windows when i run the android app it works perfectly no crash
 1. but when i do maven-publish it throws error in this file ExpressusViewModel
 2. unable to publish only the non-compose module which is consuming compose module.
 3. where all other modules which are not consuming compose module gets published.
 4. even the compose module gets published. 
In mac maven-publish get failed and none of the module gets published below mac error

Could not resolve all task dependencies for configuration ':shared:iosArm64CompileKlibraries'.
Could not resolve project :shared-ui-compose.
Required by:
project :shared
> No matching variant of project :shared-ui-compose was found. The consumer was configured to find a usage of 'kotlin-api' of a library, preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64' but:
- Variant 'debugApiElements' capability Expressus:shared-ui-compose:unspecified declares an API of a library, preferably optimized for Android:
- Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
- Other compatible attribute:
- Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
- Variant 'debugRuntimeElements' capability Expressus:shared-ui-compose:unspecified declares a runtime of a library, preferably optimized for Android:
- Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
- Other compatible attribute:
- Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
- Variant 'jvmApiElements' capability Expressus:shared-ui-compose:unspecified declares an API of a library, preferably optimized for standard JVMs:
- Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
- Other compatible attribute:
- Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
- Variant 'jvmRuntimeElements' capability Expressus:shared-ui-compose:unspecified declares a runtime of a library, preferably optimized for standard JVMs:
- Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
- Other compatible attribute:
- Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
- Variant 'metadataApiElements' capability Expressus:shared-ui-compose:unspecified declares a library, preferably optimized for non-jvm:
- Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
- Other compatible attribute:
- Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
- Variant 'releaseApiElements' capability Expressus:shared-ui-compose:unspecified declares an API of a library, preferably optimized for Android:
- Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
- Other compatible attribute:
- Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')
- Variant 'releaseRuntimeElements' capability Expressus:shared-ui-compose:unspecified declares a runtime of a library, preferably optimized for Android:
- Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
- Other compatible attribute:
- Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_arm64')

**Comment by yuvaraj119** [comment]
Is there anyway we can get it compiled only for jvm and Android and ignore ios* target?

**Comment by yuvaraj119** [comment]
> Hello!
> 
> Your `shared` module defines ios* targets while `shared-ui-compose` does not and `shared` depends on `shared-ui-compose`. So to fix this issue you need to add ios* targets to `shared-ui-compose` and implement actuals for ios target.
> 
> Some useful settings you may need to add to `gradle.properties`:
> 
> ```
> org.jetbrains.compose.experimental.uikit.enabled=true
> kotlin.native.cacheKind=none
> # Enable kotlin/native experimental memory model
> kotlin.native.binary.memoryModel=experimental
> ```

@pjBooms - If Kotlin-Multiplatform dosent support this today then this should be part of new feature or enhancement. If there is already a ticket could you share the link so i can followup with updates.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2522">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
