### ISSUE TITLE
Gradle config cache error when running tests on a compose experimental web application module

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-multiplatform#2523]
If I have the gradle config cache enabled and run `gradle allTests` on the root module and I have a submodule that uses:

```
compose.experimental {
  web.application {}
}
```

I get the following error:

```
Invocation of 'Task.project' by task ':myModule:unpackSkikoWasmRuntimeJs' at execution time is unsupported.
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2523">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
