### ISSUE TITLE
Packaging tasks are skipped

### ISSUE THREAD

**Issue by aivanovski** [JetBrains/compose-multiplatform#2525]
I see this output in a console when running `packageDmg` or `packageMsi` tasks:
```
> Task :packageDmg SKIPPED
Skipping task ':packageDmg' as task onlyIf is false.
```

Environment:
Arch Linux
OpenJDK 17/19 (both have similar results)
Kotlin 1.7.20
Compose 1.2.1

Here is the source code to reproduce: https://github.com/aivanovski/autokpass/tree/feature/compose
Please don't forget to checkout branch `feature/compose`

**Comment by kirill-grouchnikov** [comment]
You can only build for the platform you're on. So on Arch Linux you can't build for macOS (DMG) or Windows (MSI)

**Comment by aivanovski** [comment]
Thank you for the answer! `packageDmg` works fine on MacOS

Is it a limitation of Java platform or compose plugin? The necessity of Linux, MacOS and Windows machines makes package creation quite complicated. Especially for open source projects.

**Comment by kirill-grouchnikov** [comment]
You can use GitHub actions to run jobs on different OSes (remotely, not locally). Not sure if there's a handy example available for that today in the desktop Compose world. 

https://conveyor.hydraulic.dev/ is another option, but it's not free.

**Comment by kirill-grouchnikov** [comment]
Small correction - Conveyor is free for open-source apps, but I'm not going to comment further on any particular third-party tooling chain

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2525">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
