### ISSUE TITLE
Button hover state persists after moving mouse off of button

### ISSUE THREAD

**Issue by veyndan** [JetBrains/compose-multiplatform#2529]
Using Material 3 components with WebAssembly Skia, I'm encountering a bug where the hover state of a button persists after clicking the button and moving the mouse off the button. To get it back to the correct state, I need to hover on and off the button again.

This only happens on the initial load of the screen. On subsequent clicks, the hover state is removed when no longer hovering.

I've attached code to reproduce the bug, as well as a gif to visually describe the above.

```kotlin
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.window.Window
import org.jetbrains.skiko.wasm.onWasmReady

fun main() {
    onWasmReady {
        Window {
            TextButton(onClick = {}) {
                Text("Hello")
            }
        }
    }
}
```

https://user-images.githubusercontent.com/6900601/205409950-75de6542-54c1-4eca-a050-89f6e84ffc5d.mov

### Tested on

Kotlin: 1.7.20
Compose: 1.3.0-beta02
Device: Apple M1 Max (13.0.1)
Browsers: Firefox 107.0, Chrome 107.0.5304.121, Safari Version 16.1 (18614.2.9.1.12)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2529">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
