### ISSUE TITLE
Different line height and baseline reported depending on font weight (Mac OS X)

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#2530]
Writing this ticket just so people encountering this don't lose their minds, as the bug is not in Compose, but either in Skia or the font itself.

On Mac OS X, Compose for Desktop uses Helvetica Neue as the default font. Unfortunately Skiko (probably Skia) reports different line heights and baselines for this font when different weights are used. This makes it difficult to align bold and regular text. This is a bunch of `Texts` in a `Row`, each with a different weight:

<img width="439" alt="Screenshot 2022-12-02 at 18 07 11" src="https://user-images.githubusercontent.com/5230206/205441659-f3874100-c6d1-402c-b250-757a9e72b37c.png">

```
val fonts = FontCollection()
val fontProvider = TypefaceFontProvider()
fonts.setDefaultFontManager(FontMgr.default)
fonts.setAssetFontManager(fontProvider)

fun skTextStyle(weight: Int): SkTextStyle = SkTextStyle().apply {
    fontSize = 28.0f
    fontFamilies = arrayOf("Helvetica Neue")
    fontStyle = fontStyle.withWeight(weight)
}

fun paragraphHeight(weight: Int): Float{
    val skParagraph = SkParagraphBuilder(style = SkParagraphStyle(), fc=fonts)
        .pushStyle(skTextStyle(weight))
        .addText("Skiko")
        .build()
    skParagraph.layout(200f)
    return skParagraph.height
}

println(
    IntRange(1, 10)
        .map { paragraphHeight(it*100) }
        .toSet()
        .sorted()
        .joinToString()
)
```
This prints `33.0, 34.0`. For any other font I've tried it prints just a single number.

Similar results in AWT:
```
val fontsByName = GraphicsEnvironment.getLocalGraphicsEnvironment().allFonts.associateBy { it.fontName }
val awtFont = fontsByName["HelveticaNeue"]!!.deriveFont(28.0f)
val graphics2D = BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB).createGraphics()

println(awtFont.deriveFont(AwtFont.PLAIN).getLineMetrics("Awt", graphics2D.fontRenderContext).height)
println(awtFont.deriveFont(AwtFont.BOLD).getLineMetrics("Awt", graphics2D.fontRenderContext).height)
```
prints
```
33.404
34.188
```

This is how Firefox on Mac OS X renders mixed normal and bold Helvetica Neue:
<img width="126" alt="Screenshot 2022-12-03 at 14 38 01" src="https://user-images.githubusercontent.com/5230206/205441848-55a0ad15-ac6c-4da6-a986-453f8706b451.png">

Interestingly, Safari and Chrome don't have this problem.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2530">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
