### ISSUE TITLE
Setup Window & App Icon in Windows

### ISSUE THREAD

**Issue by joseluiskuuc** [JetBrains/compose-multiplatform#2537]
1.- The window icon looks stretched horizontally, what are the measurements you should have?

![streched](https://user-images.githubusercontent.com/46909828/205771061-b2c92d9a-897c-43a2-bb00-7e8722e975f6.PNG)

2.- when the window icon is not set, the java icon is the default, is it possible to make the application icon take the window icon?

![javaicon](https://user-images.githubusercontent.com/46909828/205771298-4ef812c3-f2cf-4688-9715-e75787e1dbb9.jpg)

3.- My goal is to have the same icon in any window and thread, however when matching the icons of both the application and the window, they look blurry.

![intellij](https://user-images.githubusercontent.com/46909828/205772382-ccdab4aa-4209-4974-a60f-7077a35ac4df.jpg)

I understand that the icon of the application is set in build.gradle and that of the window (and taskbar) is set in the icon property of the window, so I think that it is best to have icons with different sizes, which would be recommended To avoid as much as possible that they look blurry or stretched?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2537">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
