### ISSUE TITLE
[MacOS 11.1]Practice compose-jb/tutorials/Keyboard/ Performance is inconsistent with expectations

### ISSUE THREAD

**Issue by seeeeal** [JetBrains/compose-multiplatform#254]
after Key.CtrlLeft + Key.Equals text = "" is not working, I dont know why

    fun main() = Window(title = "Compose for Desktop", size = IntSize(300, 300)) {
        MaterialTheme {
            var consumedText by remember { mutableStateOf(0) }
            var text by remember { mutableStateOf("") }
            Column(Modifier.fillMaxSize(), Arrangement.spacedBy(5.dp)) {
                Text("Consumed text: $consumedText")
                TextField(
                    value = text,
                    onValueChange = { text = it },
                    modifier = Modifier.shortcuts {
                        on(Key.CtrlLeft + Key.Minus) {
                            consumedText -= text.length
                            text = ""
                        }
                        on(Key.CtrlLeft + Key.Equals) {
                            consumedText += text.length
                            text = ""  // here is not working ???
                        }
                    }
                )
            }
        }
    }

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5556">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
