### ISSUE TITLE
CodeViewer: fix rotation on iOS

### ISSUE THREAD

**Issue by pjBooms** [JetBrains/compose-multiplatform#2546]
[Codeviewer](https://github.com/JetBrains/compose-jb/tree/master/experimental/examples/codeviewer) is not rendered correctly on rotation:

<img width="800" alt="Screenshot 2022-12-08 at 4 24 20 PM" src="https://user-images.githubusercontent.com/2777612/206478389-6736c2b8-3021-4e03-86cb-031edee7ea9c.png">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2546">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
