### ISSUE TITLE
SwingPanel alternative for iOS

### ISSUE THREAD

**Issue by Tiebe** [JetBrains/compose-multiplatform#2550]
I would like to use an WebView on both iOS and Android, how could I add SwiftUI/UIKit code into compose? Similiar to this: https://github.com/JetBrains/compose-jb/tree/master/tutorials/Swing_Integration#adding-a-swing-component-to-compose-multiplatform-composition-using-swingpanel

I already have my Android side, since that just used an `AndroidView`. How can I add iOS UI code into `iosMain` using compose?

**Comment by igordmn** [comment]
We are working on it: https://github.com/JetBrains/androidx/pull/350 (look for UIKitInteropView). Can't tell ETA, when it will be in the build, because there is a lot needed to be done.

**Comment by Tiebe** [comment]
I saw that https://github.com/JetBrains/compose-multiplatform-core/pull/419 was just merged! Do you know when I could expect to see a dev build available?

**Comment by dima-avdeev-jb** [comment]
@Tiebe 
It's not fully supported, yes. Touches are not working.
You can try:
kotlin.version=1.8.0
agp.version=7.1.3
compose.version=1.4.0-alpha01-dev968

**Comment by dima-avdeev-jb** [comment]
The first part is done. 

Next moves to issue:
https://github.com/JetBrains/compose-multiplatform/issues/2848

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2550">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
