### ISSUE TITLE
How to navigate to other composable function with new tab in compose web?

### ISSUE THREAD

**Issue by GRNHACKER** [JetBrains/compose-multiplatform#2552]
I do not figure out how to create multiple pages and navigate from one to another. Help me with that.

**Comment by pablichjenkov** [comment]
There are a couple of options to do navigation and/or state management. Look for the following projects in github
- Decompose
- Ballast

I am working on one setup too. I need help with it so anyone welcome to participate.
https://github.com/pablichjenkov/uistate3

**Comment by arkivanov** [comment]
Most likely you will need to setup deep-links in your app, and then just open a link in a new tab. The way you setup deep-links depends on what navigation library you are using, if any. [routing-compose](https://github.com/hfhbd/routing-compose) should work pretty well for Compose for Web.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2552">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
