### ISSUE TITLE
All CJK characters / UTF-8 characters in packaged MSI/EXE installer are garbled

### ISSUE THREAD

**Issue by kenvix** [JetBrains/compose-multiplatform#2564]
For my instance, all Chinese characters in `compose.desktop.nativeDistributions.windows.menuGroup` `compose.desktop.nativeDistributions.packageName` `compose.desktop.nativeDistributions.licenseFile` will be garbled and cannot be read at all.

The reason I think caused the bug is that the installer uses location-specific encoding e.g. GBK encoding for Chinese users, while Compose uses UTF-8 encoding. This really confused me, because my customers may only know Chinese characters and I can't use an English application name for them.

A garbled license: 
![image](https://user-images.githubusercontent.com/4546175/208333960-2a87cc09-e4d7-405a-8ff2-63e02445f46e.png)

**Comment by nasamio** [comment]
i faced the same condition as you reached.bro,plz tell me if you have already handle this issue.

**Comment by kenvix** [comment]
Not yet. This issue still exists in the latest version. We can only to use an ASCII name to avoid this.

**Comment by dima-avdeev-jb** [comment]
Is this problem related to Windows only?

**Comment by kenvix** [comment]
Maybe. Other platforms like Linux use UTF-8 as default and they should have no encoding issues.

**Comment by nasamio** [comment]
Certainly, in my testing scenario, this situation only occurs on the Windows platform.

**Comment by Softtanck** [comment]
how to address this issue?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2564">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
