### ISSUE TITLE
Support Density.density on iOS

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2566]
- Now we pass density = 1. We need to get it from the system. Because we pass 1, images have wrong size.
- We need to take density into account in events positions, and in the view size
- [Less important] We need to react on the density changes

**Comment by eymar** [comment]
fix in progress - https://github.com/JetBrains/androidx/pull/360

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2566">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
