### ISSUE TITLE
Support Density.textSize on iOS

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2567]
Code:
```
@Composable
fun MyText() {
    Text("Text", fontSize = 20.sp)
}
```

The size of the text should be relative to the font size settings in the iOS system.

As far, as I know, this setting is called "Dynamic type". We need to pass the value to `ComposeScene(density = Density(textSize)`. 1.0 - no text scaling, 2.0 - double scaling

We also need to react on changes of this property.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2567">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
