### ISSUE TITLE
[Ubuntu]  App becomes unresponsive if the theme is switched while the app is running

### ISSUE THREAD

**Issue by tkuenneth** [JetBrains/compose-multiplatform#257]
Below demo on Ubuntu 20.04 becomes unresponsive if the theme is switched while the app is running.

- On Ubuntu run this app; button presses print hello
- While the app is running, open Settings and change the scheme to/from dark mode
- now button clicks no longer print something, also, the window does no longer react to clicking the Close button and the content is not updated during window resizes

```kotlin
package com.thomaskuenneth

import androidx.compose.desktop.Window
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
fun main() = Window {
    Box(contentAlignment = Alignment.Center,
            modifier = Modifier.fillMaxSize()) {
        Button(onClick = {
            println("Hello")
        }) {
            Text("Hallo")
        }
    }
}
```

https://user-images.githubusercontent.com/13284437/104018513-316e2100-51ba-11eb-88d0-73d4a79909d9.mp4

**Comment by Rsedaikin** [comment]
Hi! What version of compose for desktop are you using?

**Comment by tkuenneth** [comment]
Hi.

```
plugins {
    kotlin("jvm") version "1.4.21"
    id("org.jetbrains.compose") version "0.3.0-build139"
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5554">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
