### ISSUE TITLE
TextLayoutResult.getOffsetForPosition returns wrong offset for some points when multiple inline contents are in text

### ISSUE THREAD

**Issue by huhle** [JetBrains/compose-multiplatform#2570]
Hello,

I was playing a bit with the TextLayoutResult and it seems that sometimes it returns wrong offsets.

Operating System: Windows 10
JVM: OpenJDK 17.0.1
Compose version: 1.2.2

In case there are at least two inline contents, the offsets are a little bit off when calling getOffsetForPosition for points within these inline content.
I created small app, which visualizes the returned offsets for every x point in the text. This is the result
![image](https://user-images.githubusercontent.com/43252730/208989233-adab40ab-29e8-4e89-aada-fafb87f4a537.png)
The color under the text represents returned offset (top row shows which color means which offset)
For every character (and first inline content) the offset changes right at the middle of the character.
But for the other inline contents the offset stays the same through all the content and changes only for next character
When the inline content is last (second row) I never get the offset pointing to the right side of inline content.

Source of the tester application
```
fun main() = application {

  val colorPalette = listOf(
    Color.Black,
    Color.DarkGray,
    Color.Gray,
    Color.LightGray,
    Color.White,
    Color.Red,
    Color.Green,
    Color.Blue,
    Color.Yellow,
    Color.Cyan,
    Color.Black,
    Color.Magenta,
  )


  Window(onCloseRequest = ::exitApplication) {
    MaterialTheme {
      val colors = remember { mutableStateListOf<Color>() }
      val stringBuilder = AnnotatedString.Builder()
      val contents = mutableMapOf<String, InlineTextContent>()

      stringBuilder.append("be")
      stringBuilder.appendInlineContent("0")
      stringBuilder.append("hewo")
      stringBuilder.appendInlineContent("1")
      contents["0"] = InlineTextContent(
        placeholder = Placeholder(width = 1.em, height = 1.em, placeholderVerticalAlign = PlaceholderVerticalAlign.TextCenter),
      ) {
        Box(modifier = Modifier
          .fillMaxWidth()
          .fillMaxHeight()
          .border(width = 1.dp, color = Color.Red))
      }
      contents["1"] = InlineTextContent(
        placeholder = Placeholder(width = 1.em, height = 1.em, placeholderVerticalAlign = PlaceholderVerticalAlign.TextCenter),
      ) {
        Box(modifier = Modifier
          .fillMaxWidth()
          .fillMaxHeight()
          .border(width = 1.dp, color = Color.Red))
      }

      Column(modifier = Modifier.padding(10.dp)) {
        Row {
          for(i in colorPalette.indices) {
            Box(modifier = Modifier.background(colorPalette[i])) {
              Text(i.toString())
            }
          }
        }

        Text(
          text = stringBuilder.toAnnotatedString(),
          onTextLayout = { layout ->
            if (colors.isEmpty()) {
              for(i in 0..(layout.size.width + 50)) {
                val offset = layout.getOffsetForPosition(Offset(i.toFloat(), 5.0f))
                colors.add(colorPalette[offset])
              }
            }
          },
          inlineContent = contents
        )

        Row {
          for (color in colors) {
            Spacer(modifier = Modifier.size(1.dp, 20.dp).background(color))
          }
        }
      }
    }
  }
}
```
Or maybe I am doing something wrong?
Thanks for checking

**Comment by huhle** [comment]
Hello @eymar 
First of all thanks for checking so fast!

You are, of course ,right about the dp -> pixel conversion. Sorry about that
Regarding the difference between result of `getOffsetForPosition`. I Think that getOffsetForPosition is suposed to return closest position BETWEEN the characters. That's why I use it. I am using this function to determine where to place cursor when user clicks on text in my custom editor component.
That's why it make sense to me that the boxes have offset of half a character. Click on left half of character makes caret go before character, and click on the right half makes caret to go to the right size (offset + 1)
This works for all the characters and for first inline content. But it doesn't work for second and following inline contents
![image](https://user-images.githubusercontent.com/43252730/209204391-8d03bb6d-23c5-46f2-af05-b81fe184714a.png)
In this image I also added the expected (by me :)) result.
First inline content (light and semi-light gray - offsets 2 and 3) works the same as for any other character in text. Left half returns 2, right half returns 3.
But for second inline content I got different values - blue(7) for the whole content.

You may be right about the whole `getOffsetForPosition ` working wrong. Reading javadoc I would expect (same as you) that it will just find offset of the character on the position without any half-offsetting magic. But I cannot say what was the original purpose.
Anyway I see some inconsistency in returned values for the first inline content and the following...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2570">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
