### ISSUE TITLE
Updating apps

### ISSUE THREAD

**Issue by gnawf** [JetBrains/compose-multiplatform#2579]
Beyond [Building a native distribution](https://github.com/JetBrains/compose-jb/blob/master/tutorials/Native_distributions_and_local_execution) what are our options for updating our apps once we've distributed them?

I am targeting Mac and am planning on a Brew cask for now, but it would be nice if we could use [Sparkle](https://github.com/sparkle-project/Sparkle) on MacOS.

**Comment by AlexeyTsvetkov** [comment]
We don't provide any updating mechanisms at this moment and we don't have immediate plans for implementing them either.
For now:
* One option would be to publish to Mac App Store/Windows App Store;
* Another would be to use a third party tool like [Conveyor](https://conveyor.hydraulic.dev) (it's a proprietary third party tool, which is expected to be paid for commercial use, but should be free for open source).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2579">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
