### ISSUE TITLE
AlertDialog is dismissed when clicking on the dialog

### ISSUE THREAD

**Issue by sproctor** [JetBrains/compose-multiplatform#2581]
The background `Box` from `AlertDialog` registers gestures from the content of the dialog and closes the dialog on clicks both inside and outside of the dialog.

Adding a `Modifier.onClick {}` to the `Surface` should fix it: https://github.com/JetBrains/androidx/blob/jb-main/compose/material/material/src/desktopMain/kotlin/androidx/compose/material/DesktopAlertDialog.desktop.kt#L229

Perhaps that a better way, but that one works for me.

**Comment by dima-avdeev-jb** [comment]
Thanks for the proposal. I will discuss it with our team.
onDismissRequest callback means that you can skip it.
If you want to close AlertDialog by clicking to some Button - you may react only at Button callback.

**Comment by sproctor** [comment]
Clicking outside of the dialog to close it might be a behavior inherited from Android, but it seems sensible. Having a dialog accidentally close by clicking on it doesn't. Currently, onDismissRequest is unusable to me. I've imported the AlertDialog from material3 and added my above change since there is currently no AlertDialog in material3.

**Comment by dima-avdeev-jb** [comment]
Thanks. We will discuss it.

**Comment by m-sasha** [comment]
@dima-avdeev-jb This seems to be fixed, no? Should we close the ticket?

**Comment by sproctor** [comment]
I can confirm this is fixed in 1.3.1, so I'm closing it. Thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2581">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
