### ISSUE TITLE
Publish Windows ARM library

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#2584]
While Skiko supports Windows aarch64, currently Compose doesn't. It'd be great if a `windows-arm64` version were published, too, fully supporting the Windows devices with an ARM SoC.

**Comment by igordmn** [comment]
Skiko with Windows ARM support is only available in Compose >= 1.3.0-..., which will be released soon

**Comment by zacharee** [comment]
Has there been any progress on this? The Windows ARM64 target seems to still be missing in 1.6.0.

**Comment by igordmn** [comment]
We'll include them in the future, when we are sure that they work properly on Windows ARM.

**Comment by kylebrock** [comment]
Any updates now that copilot+ PCs are available?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2584">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
