### ISSUE TITLE
[CfD, Linux] Surface size changes immediately after lunch

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-multiplatform#2585]
The following code:

```kotlin
    application {
        Window(onCloseRequest = ::exitApplication) {
            Surface(modifier = Modifier.fillMaxSize().onSizeChanged { println(it) }) {
                MaterialTheme {
                    Text("Hello")
                }
            }
        }
    }
```

Produces the following output:

```
1592 x 1172
1600 x 1114
```

This causes undesired animations immediately after the app lunch, e.g. in the case when `BoxWithConstraints` is used and the animation relies on `constraints`. It would be good to have the size calculated properly in the very beginning.

Compose: `1.2.0` and `1.3.0-rc01`
Kotlin: `1.7.20`
OS: Ubuntu 22.04.1

**Comment by dima-avdeev-jb** [comment]
Compose 1.1.1 has the same bug.

Also, reproduce here: https://github.com/dima-avdeev-jb/reproduce-linux-resize-bug

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2585">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
