### ISSUE TITLE
DropDownMenu: rest of the window is clickable when expanded

### ISSUE THREAD

**Issue by wiiznokes** [JetBrains/compose-multiplatform#2586]
I'm trying to create a simple DropDownMenu with an IconButton to expand it, but when expanded is true, and we click on the icon button, onDismissRequest is called in the first place but onClick of the icon button is also called. I tried the same thing on Android and the onClick function is not called.

I don't know if it has to be different on Desktop but I can't figure it out a solution to this problem.
Here is a simplified version of my code: 

```
@Composable
fun dropDownMenu() {
    val expanded = remember { mutableStateOf(false) }
    Row {
        Text("label")
        IconButton(
            onClick = { expanded.value = !expanded.value }
        ) {
            Icon(
                painter = when (expanded.value) {
                    true -> getIcon("expand_less")
                    false -> getIcon("expand_more")
                }
            )
        }
    }
    DropdownMenu(
        expanded = expanded.value,
        onDismissRequest = { expanded.value = false }
    ) {
        DropdownMenuItem(onClick = {}) {
            Text("content")
        }
    }
}
```

**Comment by dima-avdeev-jb** [comment]
Made reproducible sample
https://github.com/dima-avdeev-jb/reproduce-desktop-dropdown-bug

**Comment by dima-avdeev-jb** [comment]
We found problems in Popup implementation. So, at first we need to fix them.
Related issue https://github.com/JetBrains/compose-jb/issues/1513

**Comment by mgood7123** [comment]
in case anyone asks, the specific behaviour is as follows

```
WINDOWS:

mouse down: nothing
mouse up: OPEN (click)

mouse down: DISMISS_REQUEST
mouse up: OPEN (click)

ANDROID:

touch down: nothing
touch up: OPEN (click)

touch down: DISMISS_REQUEST
touch up: nothing
```

**Comment by mgood7123** [comment]
> in case anyone asks, the specific behaviour is as follows
> 
> ```
> WINDOWS:
> 
> mouse down: nothing
> mouse up: OPEN (click)
> 
> mouse down: DISMISS_REQUEST
> mouse up: OPEN (click)
> 
> ANDROID:
> 
> touch down: nothing
> touch up: OPEN (click)
> 
> touch down: DISMISS_REQUEST
> touch up: nothing
> ```

PLEASE NOTE: this `DOES NOT` apply to `AlertDialog`

**Comment by MatkovIvan** [comment]
Mentioned behaviour depends on `focusable` flag of `Popup`. It was unified with Android in 1.5.0, so it should work as expected now. Closing

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2586">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
