### ISSUE TITLE
Rename imageResource to rememberImageResource

### ISSUE THREAD

**Issue by orangy** [JetBrains/compose-multiplatform#259]
From Slack chat:

> Another confusing piece is imageResource (composable with remember) vs imageFromResource (just creates ImageBitmap). In a composable context it’s easy to use the wrong one and cause excessive bitmap creations. Consider renaming one of them to be not so similar and making it more obvious from the name when to use which.

> imageResource should be renamed to rememberImageResource to conform to our internal API guidelines

**Comment by jimgoog** [comment]
Err, actually, I know that was my initial inclination, but after looking at this, let me bring this up with API Council for a second opinion.

**Comment by akurasov** [comment]
@igordmn what was decided about it?

**Comment by igordmn** [comment]
We will remove `imageFromResource`, and keep only one Composable function `painterResource`, similar to Android.

If it is needed to load image from non-Composable function, we can use `loadImageBitmap(inputStream)`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5552">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
