### ISSUE TITLE
iOS. Adjust the display and text size according system settings

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2593]
Compose 1.3.0-rc01

See https://support.apple.com/en-gb/guide/iphone/iph3e2e1fb0/16.0/ios/16.0. We can not only [adjust text size](https://github.com/JetBrains/compose-jb/issues/2567), but also can change other things (make text bold, increase contrast, reduce transparency, etc)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2593">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
