### ISSUE TITLE
Compose for Web: elements for <summary> and <details>

### ISSUE THREAD

**Issue by foatto** [JetBrains/compose-multiplatform#2594]
Not found subject elements for "summary" and "details" html tags.
When should we expect them to appear? :)

**Comment by foatto** [comment]
1. Please add to Elements.kt:

private val Details: ElementBuilder<HTMLDetailsElement> = ElementBuilderImplementation("details")
private val Summary: ElementBuilder<HTMLElement> = ElementBuilderImplementation("summary")

@Composable
fun Details(
    attrs: AttrBuilderContext<HTMLDetailsElement>? = null,
    content: ContentBuilder<HTMLDetailsElement>? = null
) {
    TagElement(
        elementBuilder = Details,
        applyAttrs = attrs,
        content = content
    )
}

@Composable
fun Summary(
    attrs: AttrBuilderContext<HTMLElement>? = null,
    content: ContentBuilder<HTMLElement>? = null
) {
    TagElement(
        elementBuilder = Summary,
        applyAttrs = attrs,
        content = content
    )
}

2. Add to ElementsTests.kt:

            Pair({ Details() }, "DETAILS"),
            Pair({ Summary() }, "SUMMARY"),



P.S. Can't create a new pull request: Push failed: remote: Permission to JetBrains/compose-jb.git denied to foatto. unable to access 'https://github.com/JetBrains/compose-jb.git/': The requested URL returned error: 403
:(

**Comment by foatto** [comment]
I would like to add more new features:

1. border.kt:

fun StyleScope.borderTop(
    width: CSSNumeric,
    lineStyle: LineStyle,
    color: CSSColorValue,
) {
    property("border-top", "$width $lineStyle $color")
}

fun StyleScope.borderRight(
    width: CSSNumeric,
    lineStyle: LineStyle,
    color: CSSColorValue,
) {
    property("border-right", "$width $lineStyle $color")
}

fun StyleScope.borderBottom(
    width: CSSNumeric,
    lineStyle: LineStyle,
    color: CSSColorValue,
) {
    property("border-bottom", "$width $lineStyle $color")
}

fun StyleScope.borderLeft(
    width: CSSNumeric,
    lineStyle: LineStyle,
    color: CSSColorValue,
) {
    property("border-left", "$width $lineStyle $color")
}

fun StyleScope.borderColor(
    top: CSSColorValue,
    right: CSSColorValue,
    bottom: CSSColorValue,
    left: CSSColorValue,
) {
    property("border-color", "$top $right $bottom $left")
}

2. position.kt:

fun StyleScope.zIndex(level: Int) {
    property("z-index", "$level")
}

3. ui.kt:

fun StyleScope.appearance(value: String) {
    property("appearance", value)
}

fun StyleScope.userSelect(value: String) {
    property("user-select", value)
}

**Comment by esafak** [comment]
> P.S. Can't create a new pull request: Push failed: remote: Permission to JetBrains/compose-jb.git denied to foatto. unable to access 'https://github.com/JetBrains/compose-jb.git/': The requested URL returned error: 403 :(

Don't try to push to the JetBrains repo, but clone it to your own user space, push to it, then create a pull request.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2594">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
