### ISSUE TITLE
[CfD] DisposableEffect onDispose is not called on SIGTERM signal

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-multiplatform#2596]
I'm not sure whether this is by design or not, but `onDispose` callback is not called when the application is finished with SIGTERM signal. Perhaps, the behaviour should be consistent when the window is closed with `X` (`onDispose` is called) and e.g. when the user is logged out (`onDispose` is not called).

One of the use cases is to save the application's state (like navigation state, etc.) when the application is closed. Releasing resources sounds also important.

A possible workaround currently is to use `Runtime#addShutdownHook`.

**Comment by igordmn** [comment]
The design is "Call onDispose at the same conditions, as for `finally` blocks".

If `finally` blocks are not called on SIGTERM, then it is probably a bigger issue, but it it is usually resolved on the application level, not on the framework level, as framework can't control all places, where it needs to clear resources.

Maybe we can control composition disposing though, but we need to investigate if it the right thing to do, having the fact, that `finally` blocks still won't be called.

If we have SIGTERM signal on logout, and we don't have finally blocks called, it is bad, and we need to look for an appropriate solution. Maybe we can configure the VM somehow, not sure.

Quick test on Windows, where a `finally` block isn't called:
```
fun main() {
    Runtime.getRuntime().addShutdownHook(object : Thread() {
        override fun run() {
            println("Q3")
        }
    })
    while (!Thread.interrupted()) {
        try {
            println("Q1")
            Thread.sleep(100000)
        } finally {
            println("Q2")
        }
    }
}
```
Run via IDEA (not Gradle) -> Stop via IDEA. We will see Q1 and Q3, but not Q2.

**Comment by arkivanov** [comment]
Please correct me if I'm wrong, but I guess finally blocks wouldn't be called when the user closes the window "X" button. But `onDispose` is called in this case.

**Comment by igordmn** [comment]
> finally blocks wouldn't be called when the user closes the window "X" button

Indeed, I remembered, that in Compose we added a process exit after the last closed window, so we won't trigger `finally` blocks. This decision was controversial, and if we find another way to fix [this issue](https://github.com/JetBrains/compose-jb/issues/748), I would remove `exitProcess` from the default behavior.

Without process exit, finally blocks are called when we close the window.

```
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.ui.window.singleWindowApplication
import kotlin.concurrent.thread
import kotlinx.coroutines.delay

fun main() = singleWindowApplication(exitProcessOnExit = false) {
    LaunchedEffect(Unit) {
        thread {
            try {
                println("W1")
                Thread.sleep(5000)
            } finally {
                println("W2")
            }
        }

        try {
            println("Q1")
            delay(5000)
        } finally {
            println("Q2")
        }
    }
}
```

Anyway, we have obvious inconsistencies, and should decide how to fix them.

**Comment by igordmn** [comment]
Related issues (Cmd-Q handling): 
https://github.com/JetBrains/compose-jb/issues/1948
https://github.com/JetBrains/compose-jb/issues/754

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2596">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
