### ISSUE TITLE
Irrelevant error message with Dialog

### ISSUE THREAD

**Issue by wiiznokes** [JetBrains/compose-multiplatform#2601]
I had implemented a dialog this way: 

```
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {

        val expanded = remember { mutableStateOf(false) }

        Box(Modifier.fillMaxSize()) {
            Button(
                modifier = Modifier.align(Alignment.Center),
                onClick = { expanded.value = true }
            ) {
                Text("open dialog")
            }
        }

        if (expanded.value) {
            Dialog(
                onCloseRequest = { expanded.value = false },
                visible = expanded.value
            ) {
                
            }
        }

    }
}
```

but this way cause crash on Windows. There was no error message, just EXCEPTION_ACCESS_VIOLATION. I found later that I should have remove the `if (expanded.value)` condition.

**Comment by igordmn** [comment]
Regarding the crash - is it the same crash described [here](https://github.com/JetBrains/compose-jb/issues/2624)?

Regarding the message - the crash itself is in the native code, and we can't throw a java exception in this case. Actually we can, but native memory can be corrupted and that can lead to other crashes and bugs. When we work with JVM, we should be aware that there can be native non-JVM crashes, and they are reported differently - via log file, not via console output and java exceptions. All we can do is to minimize bugs in our framework, so users encounter native crashes very rarely.

Also, if application developers need to provide a way for applications users to report crashes, we can write a separate utility that runs in a separate process and observes native crashes (and maybe include it in the default Compose configuration somehow). But that's is another feature.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2601">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
