### ISSUE TITLE
Support `TextStyle.lineHeightStyle`

### ISSUE THREAD

**Issue by AiHMin** [JetBrains/compose-multiplatform#2602]
I'm trying to set `lineHeight` and `lineHeightStyle` to `TextStyle` but I found that `lineHeightStyle` doesn't work

minimum reproduced code: 
```kt
Text(
     "Hello World!",
      style = TextStyle(
          lineHeight = 36.sp,
          lineHeightStyle = LineHeightStyle(
              LineHeightStyle.Alignment.Center, // or any kind of Alignment
              LineHeightStyle.Trim.None
           )
       
)
```

version properties:
```properties
kotlin.version=1.7.20
agp.version=7.3.1
# also test 1.2.2
compose.version=1.3.0-beta04-dev903
```

Actual: 
<img width="111" alt="image" src="https://user-images.githubusercontent.com/28809242/211029500-c2e029fa-52ea-4af0-94a2-fdeb6e8397ad.png">

Expect (use html and css😂):
<img width="116" alt="image" src="https://user-images.githubusercontent.com/28809242/211030050-b5a082d8-8656-43b3-8ffb-fefc19a4eee5.png">

**Comment by willflier** [comment]
You can try this `LineHeightStyle.Trim.Both`

**Comment by m-sasha** [comment]
The problem seems to be that in `SkiaParagraph.skiko.kt`, the line height style alignment is never added to `SkTextStyle.baselineShift`. Only `BaselineShift.multiplier` is taken into account.

**Comment by AiHMin** [comment]
It worked but seems different line height need multiplier to be recalculated.
Hope line height style alignment is added to `SkTextStyle.baselineShift` soon.

**Comment by m-sasha** [comment]
@igordmn We would need to decide how to merge `BaselineShift` and `LineHeightStyle` if both are specified.

**Comment by dima-avdeev-jb** [comment]
@jershell Sorry, not yet

**Comment by igordmn** [comment]
As `LineHeightStyle.Alignment.Center` became the default of `MaterialTheme`, text looks different on Android now. Increasing the priority

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2602">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
