### ISSUE TITLE
Basic text field print keyEvent add  key character on its value changed callback

### ISSUE THREAD

**Issue by memonahmedanees** [JetBrains/compose-multiplatform#2603]
Hi to all
Its seem strange thing today i am working on basictextfield.
When i add onpreviewkeyevent
And pressed the desired key which print key values on textfield vales
On outlinetextfield working fine

**Comment by igordmn** [comment]
Can you clarify the issue more?

And maybe provide a small reproducer describing actual/expected behavior. That will help us to understand the issue. Similar to this:
```
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.input.key.onPreviewKeyEvent
import androidx.compose.ui.window.singleWindowApplication

var value by mutableStateOf("")

fun main() = singleWindowApplication {
    BasicTextField(value, { value = it}, Modifier.onPreviewKeyEvent {
        true
    })
}
```
(in this snippet there is no issue though, we need a snippet with the issue you described)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2603">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
