### ISSUE TITLE
Dialog crashes on Desktop when removed from hierarchy

### ISSUE THREAD

**Issue by Wavesonics** [JetBrains/compose-multiplatform#2624]
**kotlin.version=1.7.20
compose.version=1.2.2**

_Crashing on Windows 11, haven't tested other OSs._

Having a `Dialog` in part of the hierarchy where it is added and removed, causes a crash:
[hs_err_pid19892.log](https://github.com/JetBrains/compose-jb/files/10398847/hs_err_pid19892.log)

Actually it looks like even just showing and hiding the dialog via something like this will crash:
```kotlin
    if(showDialog) {
        Dialog(
            onCloseRequest = { showDialog = false },
        ) {
            Button(onClick = { showDialog = false }) {
                Text("Hide")
            }
        }
    }
```

Example Project:
[DialogCrashProject.zip](https://github.com/JetBrains/compose-jb/files/10398945/DialogCrashProject.zip)

**Comment by Ayagikei** [comment]
I also encountered a similar problem.

When I run the program on Windows 11 22621.1105, **as long as a new Window or Dialog pops up, the original Window of the program will get stuck, and then the program crash.**

Switch to one of my old laptops with Windows 11 22610.1, and the program will run normally.

I also tried other JDK versions like 11, 18, and 19.

[hs_err_pid20368.log](https://github.com/JetBrains/compose-jb/files/10419605/hs_err_pid20368.log)

**Comment by Ayagikei** [comment]
> I also encountered a similar problem.
> 
> When I run the program on Windows 11 22621.1105, **as long as a new Window or Dialog pops up, the original Window of the program will get stuck, and then the program crash.**
> 
> Switch to one of my old laptops with Windows 11 22610.1, and the program will run normally.
> 
> I also tried other JDK versions like 11, 18, and 19.
> 
> [hs_err_pid20368.log](https://github.com/JetBrains/compose-jb/files/10419605/hs_err_pid20368.log)

I found that my case is related to https://github.com/JetBrains/compose-jb/issues/610. After adding ```System.setProperty("skiko.renderApi", "OPENGL")```, it works fine.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2624">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
