### ISSUE TITLE
Windows admin privileges

### ISSUE THREAD

**Issue by zhzc0x** [JetBrains/compose-multiplatform#2625]
If my app needs to store data, but the app may be installed on the system disk by the user, administrator privileges are required to operate files on the system disk, what should I do at this time? Is there a method or api that can apply for Windows administrator privileges?

**Comment by pjBooms** [comment]
No, there is no such method. You just need to run your app as administrator or make a custom launcher with provided elevating manifest (https://learn.microsoft.com/en-gb/windows/win32/sbscs/application-manifests?redirectedfrom=MSDN) to always run your application as admin. Anyway the issue does not relate to Compose so I close it.

**Comment by GaoXing0608** [comment]
1. You could save the data to user path rather than the installed path

2. You could enalbe the "perUserInstall" and disable the "dirChooser", it will not install the application to "C://Program Files" path

**Comment by zicheng2019** [comment]
> No, there is no such method. You just need to run your app as administrator or make a custom launcher with provided elevating manifest (https://learn.microsoft.com/en-gb/windows/win32/sbscs/application-manifests?redirectedfrom=MSDN) to always run your application as admin. Anyway the issue does not relate to Compose so I close it.

How to configure and load the application-manifests file in Compose?

**Comment by GaoXing0608** [comment]
> > * You could save the data to user path rather than the installed path
> > * You could enalbe the "perUserInstall" and disable the "dirChooser", it will not install the application to "C://Program Files" path
> 
> Thank you for your reply; for the second method, if the user's computer has only one C drive, it may not be possible to install it

It will install to the C:\xxx\AppData\Local ranther than the  C:\Program Files

**Comment by mikehearn** [comment]
Some people are being pointed to this thread in chat, so I'll note that if you use Conveyor you can enable admin mode at packaging time like this:

https://conveyor.hydraulic.dev/latest/configs/windows/#requesting-administrator-access

**Comment by zicheng2019** [comment]
> Some people are being pointed to this thread in chat, so I'll note that if you use Conveyor you can enable admin mode at packaging time like this:
> 
> https://conveyor.hydraulic.dev/latest/configs/windows/#requesting-administrator-access

Thanks a lot, I'll try it

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2625">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by mahozad** [comment]
Check out [this Gradle plugin](https://github.com/mahozad/compose-exe-manifest).

It embeds a manifest file in your exe so it always runs as administrator.
For an example manifest file see see the plugin README.

Related issue: https://github.com/JetBrains/compose-multiplatform/issues/4251
