### ISSUE TITLE
BasicTextField could not input any Chinese character when using JBR

### ISSUE THREAD

**Issue by AiHMin** [JetBrains/compose-multiplatform#2628]
I'm trying to use JBR to run compose-jb application in order to customize title style. But after that, `BasicTextField` could not input any Chinese character.

Platform: macOS 13.1-aarch64, also tried x64
JBR tried `17-b653.23`, `17-b653.25`, `17-b791.1`
compose-jb tried `1.2.2`, `1.3.0-beta04-dev903`, `1.3.0-rc02`

test code:
```kt
fun main() = application {
    Window(
        onCloseRequest = { exitApplication() }
    ) {
        var text by remember { mutableStateOf("") }
        BasicTextField(text, { text = it })
    }
}
```

Look at this:

https://user-images.githubusercontent.com/28809242/212084072-2a94efae-c822-4943-8d3a-f4ab29f46d31.mp4

Expected behavior: (switch JBR to other JDK like corretto, Graalvm etc)

https://user-images.githubusercontent.com/28809242/212084729-93e159e4-0042-4067-9867-9dd76847f267.mp4

But I switch to windows with JBR, everything works fine. So I could not figure out that is JBR-macos bug or compose-macos bug

**Comment by AiHMin** [comment]
After tried several JBR versions, I found the last version that works fine is [17.0.4.1-b469.62](https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.4.1b469.62) and the broken starts to [17.0.4.1-b597.1](https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.4.1b597.1) 

I've no idea if it should blame to this JBR update.

**Comment by AiHMin** [comment]
I compared the commit diffs between two branches and found that the problem occurred in commit [JBR-4638 Regression: Unable to enter emoji in editor via Emoji & Symbols on macOS](https://github.com/JetBrains/JetBrainsRuntime/commit/22518885a1c20c1fb06683cd047b1d6f9ca0476b)
This commit broke the compose-multiplatform input method functionality. 
I tried to reverting this commit locally and recompiling JBR, the input method functionality was restored to normal.
Is there any way to fix this without affecting the JBR's fix?

**Comment by AiHMin** [comment]
I added `Modifier.onKeyEvent` to `BasicTextField` for listening and printing out the KeyEvent. 
```kotlin
BasicTextField(
    text,
    { text = it },
    Modifier.onKeyEvent {
        println(it)
        false
    }
)
```
After I typed `nihao` and space to commit text, the print results:
**broken version**: 
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/28809242/234736407-2d4241ba-d70b-4b47-af97-8982561e97a8.png">

**normal version**: 
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/28809242/234736619-472c5d9d-03d2-4d24-9e96-79d3641f484e.png">

**Comment by eymar** [comment]
Similar issue was reported here - https://github.com/JetBrains/compose-multiplatform/issues/3221 

cc @JustYummy

**Comment by AiHMin** [comment]
Is there any progress on this issue? 

I did some investigation recently and found that [the lines of code submitted in JBR-4638](https://github.com/JetBrains/JetBrainsRuntime/commit/8b9a00915df501ae9778034e882c972a494c2767#diff-01651348382f7df0cfec4fd34fa82401d4bae2f3531c0c7da50974ec15d6308cR285-R290) are likely the cause of the malfunction. I commented out those lines of code and recompiled the latest JBR branch, and the feature is now working properly.
<img width="869" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/28809242/a15c3897-1d9b-4247-9a8b-94fafbc43845">

By the way, it seems that the input method is also far away from the input content.
actual:
<img width="165" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/28809242/046dc760-9469-4e42-81f7-b85e7de24b6a">
expect: 
<img width="156" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/28809242/7edcfca2-7f69-41dd-885f-470ea37fbe12">

**Comment by igordmn** [comment]
@m-sasha, could you please try to reproduce? It can be a serious issue.

**Comment by AiHMin** [comment]
I almost forgot it. Jetbrains Toolbox also faced the same issue since the runtime update to 17.0.6-b829.9

**Comment by igordmn** [comment]
> it seems that the input method is also far away from the input content.

I created [a separate issue](https://github.com/JetBrains/compose-multiplatform/issues/3838), thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2628">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
