### ISSUE TITLE
Add Backdrop Filter

### ISSUE THREAD

**Issue by 6xingyv** [JetBrains/compose-multiplatform#2636]
To achieve a blur behind effect, can we add a backdrop modifier like flutter?

**Comment by pjBooms** [comment]
You'd better provide such a request to Google androidx

**Comment by 6xingyv** [comment]
Oops...It's my fault of not describing this feature-request.
In this project[visual-effects](https://github.com/chachako/visual-effects/blob/main/library/src/androidMain/kotlin/chachako/visual/effects/Blur.android.kt), the author made the background blur effect using LocalView.current, but compose-jb haven't any similar value that can replace it....

**Comment by 6xingyv** [comment]
> You'd better provide such a request to Google androidx

So could you reopen this issue? Thanks

**Comment by pjBooms** [comment]
LocalView is Android specific, right

**Comment by kirill-grouchnikov** [comment]
In compose-jb, there's no such concept. The entire Window is one big Skia-backed canvas.

**Comment by 6xingyv** [comment]
> In compose-jb, there's no such concept. The entire Window is one big Skia-backed canvas.

so...is there any way to nest another skia-based canvas to place composable and enable such operation?

**Comment by kirill-grouchnikov** [comment]
You can already apply shaders on individual nodes in your hierarchy

**Comment by kirill-grouchnikov** [comment]
See https://www.pushing-pixels.org/2022/04/09/shader-based-render-effects-in-compose-desktop-with-skia.html

**Comment by Nourepide** [comment]
> See https://www.pushing-pixels.org/2022/04/09/shader-based-render-effects-in-compose-desktop-with-skia.html

Does not work with bitmaps images in the background
Also need to manually set the size

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2636">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
