### ISSUE TITLE
TextLayoutResult gives incorrect offset values for >16 bit characters 

### ISSUE THREAD

**Issue by jamesreprise** [JetBrains/compose-multiplatform#2654]
When using functions of `TextLayoutResult` such as `getBoundingBox`, `getWordBoundary`, `getOffsetForPosition`, providing a given offset behaves strangely when the string for which the `TextLayoutResult` was generated has characters larger than 16 bits, which spill over into other characters in Kotlin.

I suspect this is down to the fact that a Kotlin `Char` is 16 bits. As such, when we seek to represent a character such as `😍` or `𫞔`, it ends up occupying multiple `Char`s in a `CharSequence`, the interface which `AnnotatedString` implements.

My expectation is that when I have a `TextLayoutResult` for a string "𫞔", and pass an offset 1 to the function `getBoundingBox`, I would get an error due to the index being out of bounds. This is because, in my mind, a `TextLayoutResult` is representing a series of glyphs (i.e. visual representations of characters on screen) rather than being linked to the underlying data structure that incidentally uses 2 `Char`s to store the character.

In fact, this is valid and we get a Rect that assumes that the width of the character is the default width, rather than the width of the character that it is the latter half of, starting from to the right (in a left-to-right writing system) of the character it is the latter half of.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2654">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
