### ISSUE TITLE
Crash on Linux arm64

### ISSUE THREAD

**Issue by sebkur** [JetBrains/compose-multiplatform#2655]
I'm trying to run a basic [sample app](https://github.com/sebkur/test-compose-for-desktop) on a Linux arm64 machine. It's a virtual machine run on an M1 macbook using Parallels. The app crashes on launch with SIGSEGV. I think it has to do with skiko. When I try to run the skiko sample app, I get a similar crash which I reported here: https://github.com/JetBrains/skiko/issues/649

**Comment by hfhbd** [comment]
Do I miss something? There is no linuxArm64 support in atomicfu, coroutines, runtime nor in skiko. How do you even compile it?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2655">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
