### ISSUE TITLE
Rename this library to compose-multiplatform 

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-multiplatform#2669]
People don't know what `compose-jb` is. Wouldn't this library be better suited with the name `compose-multiplatform`?

**Comment by mahozad** [comment]
I hope you do not accidentally make this repository private.

The library [httpie](https://github.com/httpie/httpie#we-lost-54k-github-stars) lost 50K of its stars apparently because they made their repository private for just a moment.

**Comment by ScottPierce** [comment]
Github creates redirects to the new name when the repository is renamed also.

**Comment by dima-avdeev-jb** [comment]
@ScottPierce 
Do you want only to rename repository name `compose-jb` -> `compose-multiplatform`?

**Comment by ScottPierce** [comment]
That seems like some low hanging fruit. It'd be clearer what this project does, right?

All I know is that right now, when I tell people to find this project, unless I link them directly, people don't know what `compose-jb` is.

**Comment by yantlord** [comment]
Agreed, it is unnecessarily confusing and compose-multiplatform would be better imo. I overlooked the docs and tutorials myself at the beginning (couple months ago), because of this issue exactly.

**Comment by dima-avdeev-jb** [comment]
Ok, we will discuss it in our team

**Comment by dima-avdeev-jb** [comment]
We should take time to prepare, so we will give answer a few weeks later.

**Comment by igordmn** [comment]
Done

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2669">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
