### ISSUE TITLE
iOS TextField, Incorrect behavior of text selection by double tap

### ISSUE THREAD

**Issue by etolstoy** [JetBrains/compose-multiplatform#2682]
<img width="337" alt="SCR-20230131-htk" src="https://user-images.githubusercontent.com/3955262/215752328-8855f8b3-7501-4493-ba4c-237249a96910.png">
There are some bugs in text selection in `TextField` on iOS Simulator in the `widgets-gallery` sample:

- The selection overlay layout is broken
- The selection doesn't appear on a double-click on a text as in native apps
- Double tap on a string of emojis selects nothing, but should select a single emoji

_Simulator: iOS 16.2, iPhone 14_

Moved ContextMenu related bugs to issue: https://github.com/JetBrains/compose-multiplatform/issues/3276

**Comment by mazunin-v-jb** [comment]
Selection overlay layout should be re-checked, I guess It was fixed in another issue.
![image](https://github.com/JetBrains/compose-multiplatform/assets/124871594/66612d8f-df08-44f3-896c-5f48ab5e8fe4)

Problem with double tap selection still reproduces, I'm working on a fix for it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2682">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
