### ISSUE TITLE
Add roadmap docs

### ISSUE THREAD

**Issue by madroidmaq** [JetBrains/compose-multiplatform#2692]
Expect to add a Roadmap document that will let developers know when big features are expected to be supported. It can also increase people's confidence in the project, so that it can be more accepted. A similar Roadmap goes something like this:

1. Jetpack Compose Roadmap：https://developer.android.com/jetpack/androidx/compose-roadmap
2. Flutter Roadmap：https://github.com/flutter/flutter/wiki/Roadmap

**Comment by wwalkingg** [comment]
Use GitHub Project Panel is a good idea too.

**Comment by chrisjenx** [comment]
While dates would be nice, we all know they are hard to keep to, I would mostly be interested in priorities so we can plan our own internal roadmap(i.e. is iOS support going to be stable before alpha wasm? etc) Just knowing at what versions we can start targeting different targets really helps long term planning.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2692">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
