### ISSUE TITLE
"TypeError: xyz is not a function" with production webpack output after upgrading to Kotlin 1.8.0 / Compose 1.3.0

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-multiplatform#2697]
Full stack I get when running a release distribution of my site:

```
Uncaught TypeError: t.h14 is not a function
    at Ae.f14 (Standard.kt:158:24870)
    at Recomposer.kt:1078:39
    at Bf (Snapshot.kt:1834:14)
    at ec.w1l (SnapshotStateList.kt:50:55)
    at ec.c (SnapshotStateList.kt:70:36)
    at Elements.kt:991:45
    at qc.p1m (ComposableLambda.js.kt:116:22)
    at En.E (clock.js:1:439088)
    at mn (Base.kt:140:13)
    at En (Elements.kt:983:5)
```

Note: This may be the same issue as https://github.com/JetBrains/compose-jb/issues/2684, but I thought I'd open a parallel bug in case it's different, and as a way to leave notes as I dig. @eymar 

**EDIT: Consider jumping to https://github.com/JetBrains/compose-jb/issues/2697#issuecomment-1416919231 and https://github.com/JetBrains/compose-jb/issues/2697#issuecomment-1416920576. It seems the issue may be some standard library methods getting DCE'd incorrectly?**

---

## Background

I'm working on a library called Kobweb (https://github.com/varabyte/kobweb) which sits on top of Compose for Web. It adds its own pipeline to the mix, so instead of `./gradlew jsBrowserRun`, you run `kobweb run` which spins up its own custom server.

Bad news is that means more moving parts (but I'll try to isolate the root issue and update this bug over time once I do).

Good news is it should make things easy to reproduce.

## Reproduction steps

0. Install, download, or build the kobweb binary ([steps here](https://github.com/varabyte/kobweb#trying-it-out-yourself))

### Working case

First, let's see a working case, as a base to compare with. These steps use Kobweb 0.11.9, which targets Kotlin 1.7.20 and Compose 1.2.2

0. In a tmp directory somewhere...
1. `$ kobweb create examples/clock --branch kobweb-0_11_9` (and accept all default values)
2. `$ cd clock`
3. `$ kobweb export` (and wait...)
4. `$ kobweb run --env prod`
5. Open https://localhost:8080
6. **Observe the working clock demo**
7. Press Q to quit kobweb and shutdown the server
8. Delete the `clock` folder

### Broken case

These steps use Kobweb 0.12.0, which targets Kotlin 1.8.0 and Compose 1.3.0. Otherwise, the feature-set for 0.12.0 is identical to 0.11.9.

1. `$ kobweb create examples/clock --branch kobweb-0_12_0` (and accept all default values)
2. `$ cd clock` (or `$ cd clock2` if you didn't delete the folder in the previous steps)
3. `$ kobweb export` (and wait...)
4. `$ kobweb run --env prod`
5. Open https://localhost:8080
6. Observe the blank screen...
7. **Inspect the page and look at its console, observing the typeerror**.
9. Press Q to quit kobweb and shutdown the server

Optional:

The next steps trigger the development path, not the production path, in order to emphasize that this path works and it's only the production output that is broken:

10. `$ kobweb run` (and wait)
11. Open https://localhost:8080
12. Observe the working clock demo

**Comment by bitspittle** [comment]
## Dependent tasks for Kobweb 0.11.9 export:

```
$ ./gradlew kobwebExport -PkobwebEnv=DEV -PkobwebRunLayout=KOBWEB -PkobwebBuildTarget=RELEASE -PkobwebExportLayout=KOBWEB --dry-run

:kobwebCopyDepResources SKIPPED
:kobwebGenSiteIndex SKIPPED
:jsProcessResources SKIPPED
:jsBrowserDevelopmentExecutableDistributeResources SKIPPED
:kotlinNpmCachesSetup SKIPPED
:jsPackageJson SKIPPED
:kotlinNodeJsSetup SKIPPED
:kotlinRestoreYarnLock SKIPPED
:kotlinYarnSetup SKIPPED
:jsTestPackageJson SKIPPED
:packageJsonUmbrella SKIPPED
:rootPackageJson SKIPPED
:kotlinNpmInstall SKIPPED
:jsGenerateExternalsIntegrated SKIPPED
:kobwebGenFrontendMetadata SKIPPED
:kobwebGenSiteEntry SKIPPED
:compileKotlinJs SKIPPED
:jsMainClasses SKIPPED
:compileDevelopmentExecutableKotlinJs SKIPPED
:jsDevelopmentExecutableCompileSync SKIPPED
:jsBrowserDevelopmentWebpack SKIPPED
:kobwebGenFrontend SKIPPED
:kobwebGen SKIPPED
:kobwebStart SKIPPED
:jsBrowserProductionExecutableDistributeResources SKIPPED
:compileProductionExecutableKotlinJs SKIPPED
:jsProductionExecutableCompileSync SKIPPED
:kotlinStoreYarnLock SKIPPED
:jsBrowserProductionWebpack SKIPPED
:kobwebCleanExport SKIPPED
:kobwebExport SKIPPED
```

## Dependent tasks for Kobweb 0.12.0 export:

```bash
$ ./gradlew kobwebExport -PkobwebEnv=DEV -PkobwebRunLayout=KOBWEB -PkobwebBuildTarget=RELEASE -PkobwebExportLayout=KOBWEB --dry-run

:kobwebCopyDepResources SKIPPED
:kobwebGenSiteIndex SKIPPED
:jsProcessResources SKIPPED
:jsBrowserDevelopmentExecutableDistributeResources SKIPPED
:kotlinNpmCachesSetup SKIPPED
:jsPackageJson SKIPPED
:kotlinNodeJsSetup SKIPPED
:kotlinRestoreYarnLock SKIPPED
:kotlinYarnSetup SKIPPED
:jsTestPackageJson SKIPPED
:packageJsonUmbrella SKIPPED
:rootPackageJson SKIPPED
:kotlinNpmInstall SKIPPED
:kotlinStoreYarnLock SKIPPED
:jsGenerateExternalsIntegrated SKIPPED
:kobwebGenFrontendMetadata SKIPPED
:kobwebGenSiteEntry SKIPPED
:compileKotlinJs SKIPPED
:jsMainClasses SKIPPED
:compileDevelopmentExecutableKotlinJs SKIPPED
:jsDevelopmentExecutableValidateGeneratedByCompilerTypeScript SKIPPED
:jsDevelopmentExecutableCompileSync SKIPPED
:jsBrowserDevelopmentWebpack SKIPPED
:kobwebGenFrontend SKIPPED
:kobwebGen SKIPPED
:kobwebStart SKIPPED
:jsBrowserProductionExecutableDistributeResources SKIPPED
:compileProductionExecutableKotlinJs SKIPPED
:jsProductionExecutableValidateGeneratedByCompilerTypeScript SKIPPED
:jsProductionExecutableCompileSync SKIPPED
:jsBrowserProductionWebpack SKIPPED
:kobwebCleanExport SKIPPED
:kobwebExport SKIPPED
```

**Comment by bitspittle** [comment]
[yarnlockdiff.txt](https://github.com/JetBrains/compose-jb/files/10609975/yarnlockdiff.txt)

^ Diff between the yarn.lock generated by Kotlin 1.7.20 and Kotlin 1.8

**Comment by bitspittle** [comment]
[yarnlockdiff.txt](https://github.com/JetBrains/compose-jb/files/10609975/yarnlockdiff.txt)

^ Diff between the yarn.lock generated by Kotlin 1.7.20 and Kotlin 1.8

**Comment by bitspittle** [comment]
**New set of repro steps. Still not sure what's going on but hopefully this brings me closer to an isolated project.**

1. `$ kobweb create app/empty --branch kobweb-0_12_0`
2. `$ cd empty`
3. `$cd kobweb export` (and wait...)
4. `$ kobweb run --env prod`
5. Open https://localhost:8080/, then inspect the console
6. **Observe the TypeError error message**
7. Press Q to quit kobweb and shutdown the server
---
8. Edit  `site/src/jsMain/kotlin/org/example/empty/MyApp.kt`
9. Comment out the `Surface` declaration on line 23 (and its closing brace on line 25):
```
@App
@Composable
fun MyApp(...) {
   SilkApp {
//    Surface(...) {
         content()
//    }
   }
}
```
10. `$ kobweb run --env prod`
11. Open https://localhost:8080/, then inspect the console
12. **Observe no crashes, just the message "Hello World"**

--- 

This implies that something I'm doing in [the Kobweb Silk widgets module](https://github.com/varabyte/kobweb/tree/main/frontend/kobweb-silk-widgets) is causing webpack to fail when generating production output. Will use trial and error to see if I can narrow things down.

**Comment by bitspittle** [comment]
OK, I've got a local dev project where I can modify my Silk library, disabling and enabling features to see what causes the crash or not. It's a little slow going because I have to re-export every time, but it seems like one place that's crashing is:

https://github.com/varabyte/kobweb/blob/c57006f0590f239dd09e07300aec9f55ac5a26ac/frontend/kobweb-silk-widgets/src/jsMain/kotlin/com/varabyte/kobweb/silk/components/style/ComponentStyle.kt#L576

Specifically, by calling `SilkTheme.componentStyles.getValue(name)` (which is just a map access), I'm crashing. If I change it to `SilkTheme.componentStyles[name]!!`, then I don't crash...

I haven't been able to duplicate this behavior to an isolated environment yet, so I'm still investigating. I may have to stop until Monday, however.

**Comment by bitspittle** [comment]
Sure enough, when I replaced all `getValue` calls in my Silk widget library and re-exported, my site worked.

Please see this change: https://github.com/varabyte/kobweb/commit/d5e5473fe0159535f28769dddc3c12f870071ed5


It seems like somehow a combination of Kotlin 1.8 and latest webpack changes has resulted in the `Map.getValue` operator getting incorrectly DCE'd.

**Comment by eymar** [comment]
A similar issue was reported here 
https://github.com/JetBrains/compose-jb/issues/2638
But the reason was rather more clear. There were 2 identical minified names for different things (a function and an argument).

Maybe in your case the minified names is also the reason of the problem. I would expect it to be this case. 

I think we can try to eliminate a mistake of DCE by using this flag:

https://youtrack.jetbrains.com/issue/KT-45059/KJS-IR-Add-possibility-for-runtime-diagnostics-of-DCE-result
Xir-dce-runtime-diagnostic={log|exception}

My assumption is that the error would be the same with that flag. Probably looking at minified final js where 'getValue' were used could reveal more details. 

Or -Xir-dce=true could be used even for dev distribution. If it's DCE causing the issue, it would probably show up.

**Comment by bitspittle** [comment]
Basically, I should add this into the build.gradle.kts file, right? And then just do a regular dev run?

```
tasks.withType(KotlinCompile::class.java).all {
    kotlinOptions {
      freeCompilerArgs += listOf("-Xir-dce-runtime-diagnostic=exception", "-Xir-dce=true")
    }
}
```

It doesn't seem to be doing anything, although maybe I'm setting the flags wrong.

**Comment by bitspittle** [comment]
Ah hold on, maybe it needs to be done differently in multiplatform?

I'm trying this:
```
    js {
        compilations.all {
            compilerOptions.configure {
                freeCompilerArgs.addAll(listOf("-Xir-dce-runtime-diagnostic=log", "-Xir-dce=true"))
            }
        }
    }
```

which seems to be better (when I put print statements in there, they're getting hit), but no change yet for a dev run.

**Comment by bitspittle** [comment]
Well, still no luck. Probably user error, since I'm not too familiar with these feature flags.

I'm afraid I need to call it for the day. And tomorrow I'm AFK. 

If someone on your team wants to try before I can get back...

1) `$ git clone https://github.com/varabyte/kobweb`
2) `$./gradlew :cli:kobweb:installDist`
3) `$ cd examples/helloworld`

Dev run:
`$ ../../cli/kobweb/build/install/kobweb/bin/kobweb run`

Prod run:
`$ ../../cli/kobweb/build/install/kobweb/bin/kobweb export`
`$ ../../cli/kobweb/build/install/kobweb/bin/kobweb run --env prod`

The dev run should work and the export / prod run should fail.
The module that is causing trouble is located at `frontend/kobweb-silk-widgets`.

**Comment by eymar** [comment]
Filed a report to kotlin/js team: https://youtrack.jetbrains.com/issue/KT-56463/KJS-IR-TypeError-abc-is-not-a-function-in-release-distribution

Setting `kotlin.js.ir.output.granularity=whole-program` indeed helps. Thank you, David

**Comment by eymar** [comment]
Fixed by https://youtrack.jetbrains.com/issue/KT-56463/KJS-IR-TypeError-abc-is-not-a-function-in-release-distribution

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2697">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
