### ISSUE TITLE
downloadWix no progress prompt

### ISSUE THREAD

**Issue by sunny-zhang-98** [JetBrains/compose-multiplatform#2699]
Hopefully you can support progress notifications

I hope you can support manual download,And prompt the user to put the downloaded file where

**Comment by AlexeyTsvetkov** [comment]
@Doinng Hi! Please describe the issue in a more clear way. 
I don't understand, what progress notification do you expect? 

As for manual download, it is possible to download wix toolset manually 
([link to 3.11.2 release](https://github.com/wixtoolset/wix3/releases/tag/wix3112rtm)).
Then set `WIX_PATH` environment variable to the directory, containing unpacked wix.

**Comment by Doinng** [comment]
@AlexeyTsvetkov Thank you very much for your reply, this is a not so important question
1. I hope there will be a progress bar in the status bar below IDEA when users download
2. I would like to be able to use Gradle to tell the user where the download is located when the download task is executed

**Comment by Doinng** [comment]
If I don't use the agent then the download will be slow, but I don't know the download progress, I want to download manually but I don't know where to put it, so far I have got the answer by looking at the source code, but I don't want everyone to look at the source code to solve the problem, I want to print some instructions in the download task.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2699">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
