### ISSUE TITLE
[UIKit, Keyboard] fix magicMultiplier

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#2709]
In this PR I made workaround for keyboard display.
https://github.com/JetBrains/androidx/pull/397
It needs to proper interop with SwiftUI.

Need to fix it in the proper way.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2709">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
