### ISSUE TITLE
IDEA New Project Wizard, Compose Multiplatform: `[UNSUPPORTED_FEATURE] The feature "multi platform projects" is experimental and should be enabled explicitly` right after creation

### ISSUE THREAD

**Issue by wild-lynx** [JetBrains/compose-multiplatform#271]
Cross-post of https://youtrack.jetbrains.com/issue/KTIJ-906, by request of @olonho. 

Create Compose Multiplatform project through New Project Wizard in IDEA.
Open `common/src/commonMain/kotlin/me/jetbrains/common/platform.kt`: expect fun getPlatformName(): String is reported with `[UNSUPPORTED_FEATURE] The feature "multi platform projects" is experimental and should be enabled explicitly` error. That's the issue: the project after generation should be properly imported as is.

Gradle build passes successfully.

Failed to reproduce with:

IDEA 2021.1 Nightly (211.4452), Kotlin plugin 211-1.4.21-release-IJ4452
IDEA 2020.3.1 Release (203.6682.168), Kotlin plugin 203-1.4.10-release-IJ6682.9
IDEA 2020.3.1 Release (203.6682.168), Kotlin plugin 203-1.4.21-release-IJ6682.9

Reproduced with:

IDEA 2020.3.1 Release (203.6682.168), Kotlin plugin 203-1.5.0-dev-1161-IJ5981.133
IDEA 2020.3.1 Release (203.6682.168), Kotlin plugin 203-1.4.30-M1-IJ5981.133

**Comment by bahaa-ka** [comment]
Still reproducible in 
IntelliJ IDEA 2020.3.3 (Ultimate Edition)
Build #IU-203.7717.56, built on March 15, 2021
Runtime version: 11.0.10+8-b1145.96 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
![image](https://user-images.githubusercontent.com/36090644/114281697-8aaf5000-9a48-11eb-921f-e84caadeb734.png)

**Comment by loehnertz** [comment]
@akurasov
Maybe it should be a lower level than an error then. Otherwise, the entire directory in IntelliJ and all its parents up to the root have a red squiggly line under the name due to it in the project browser. If this is the default behavior on a newly created Compose Multiplatform project, it hides away other, actual errors quite easily.

**Comment by TomTruyen** [comment]
I agree with @loehnertz it shouldn't be classified as an error if it is just a warning/notice

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5542">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
