### ISSUE TITLE
Cursor in empty BasicTextField only on Left (Start) side on Linux when TextAlign is on Right (End) side

### ISSUE THREAD

**Issue by GazimSoliev** [JetBrains/compose-multiplatform#2711]
Cursor in empty BasicTextField only on Left (Start) side on Linux when TextAlign is on Right (End) side

Compose: 1.3.0
Kotlin: 1.8.0
OS: 6.1.9-1-MANJARO
Architecture: x86

On Linux:
![image](https://user-images.githubusercontent.com/63443274/217107381-dbf10f63-bc36-4cf9-ae63-ce218501bdad.png)
If write something:
![image](https://user-images.githubusercontent.com/63443274/217107451-441283a4-99ca-4b05-b9ac-11041b95b011.png)

On Android:
![image](https://user-images.githubusercontent.com/63443274/217107946-9e79e08b-3d02-4d22-85b8-1a2661c6abbe.png)
If write something:
![image](https://user-images.githubusercontent.com/63443274/217108173-2da32ffe-c4ec-47e4-ad51-4e61cf9da476.png)

**Comment by pjBooms** [comment]
THank you for your report! It would be great, if you could attach the reproducing sample, not only the screenshot so we would not need to make it from the screenshot.

**Comment by igordmn** [comment]
Reproduces on Windows too
```
import androidx.compose.material.TextField
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    var text by remember { mutableStateOf("") }
    TextField(text, { text = it }, textStyle = TextStyle.Default.copy(textAlign = TextAlign.End))
}
```

**Comment by GazimSoliev** [comment]
> Thank you for your report! It would be great, if you could attach the reproducing sample not only the screenshot so we would not need to make it from the screenshot.

```
AppTheme {
    Surface(Modifier.fillMaxSize()) {
                Box(contentAlignment = Alignment.Center) {
                    var text by remember {
                        mutableStateOf(TextFieldValue())
                    }
                    BasicTextField(
                        modifier = Modifier
                            .height(100.dp).width(300.dp)
                            .background(Color.Yellow).padding(32.dp),
                        value = text, onValueChange = {
                            text = it
                        }, textStyle = TextStyle.Default.copy(textAlign = TextAlign.Right)
                    )
                }
            }
}
```

**Comment by mahozad** [comment]
**Center** alignment in desktop has this problem too.
When field becomes empty, the cursor goes to the left instead of staying at the center:

```kotlin
BasicTextField(
            value = "",
            onValueChange = {},
            textStyle = LocalTextStyle.current.copy(
                textAlign = TextAlign.Center
            ),
```

**Comment by gutnikvk** [comment]
Any updates on this? Still reproducing on Compose 1.6.2.

**Comment by MatkovIvan** [comment]
Should be fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/1354

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2711">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
