### ISSUE TITLE
Fix `GraphicsLayerTest.rotationY` test

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2713]
**Describe the bug**

It seems `needRedraw` sometimes called from non-UI thread. We should either remove the thread requirement in skiko, or move this call to UI thread.

https://teamcity.jetbrains.com/buildConfiguration/JetBrainsPublicProjects_Compose_Publish_2_AllGitHubRelease/4074124?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true

**Affected platforms**
- Desktop

**Versions**
- Compose Multiplatform version*: 1.4-alpha01

**Comment by igordmn** [comment]
The test seems flaky

**Comment by m-sasha** [comment]
`needRedraw` does two things:
- Checks `isDisposed`, which is modified in `dispose`, which is also marked as being needed to be called from the AWT thread.
- Fetches `redrawer`, which is also set and cleared in the AWT thread. 
- Calls `Redrawer.needRedraw`, which in all implementations ends up calling 

```
    fun scheduleFrame() {
        if (!frameScheduled) {
            frameScheduled = true
            frameChannel.trySend(Unit).isSuccess
        }
    }
```
which seems like it would be ok if called from several threads.
But in `LinuxOpenGLRedrawer` it also adds the redrawer to some mutable set.

So it doesn't appear that we can simply remove the requirement for `SkiaLayer.needRedraw` to be called from the AWT thread. At least not without protecting the above things from race conditions and stale memory access.

**Comment by m-sasha** [comment]
Looking again at the stack trace, it appears that the issue here is the wrong (possibly undisposed) `ComposeScene` receiving snapshot notifications, because the failing test doesn't use `SkiaLayer` itself.

**Comment by m-sasha** [comment]
Not 100% sure that PR fixes it; we'll see.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2713">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
