### ISSUE TITLE
Native Distributable with JavaFX WebView "libprism_xx.dylib can't be opened"

### ISSUE THREAD

**Issue by sunilson** [JetBrains/compose-multiplatform#2718]
**Describe the bug**
When I package and sign a native distributable for MacOS I get the following error when executing the app and opening the WebView: `"libprism_es2.dylib" can't be opened because Apple cannot check it for malicious software.` Do I have to adjust how I include JavaFX or how I sign the app? I use the JavaFX gradle plugin for the integration.

**Affected platforms**
- [ ] All
- [x] Desktop
- [ ] Web (K/JS) - HTML based API
- [ ] Web (K/JS) - Canvas based API
- [ ] iOS
- [ ] other

**Versions**
- Kotlin version*: 1.7.10
- Compose Multiplatform version*: 1.3.0
- OS version(s)* (required for Desktop and iOS issues): macOS Monerey Version 12.1
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

**Screenshots**
<img width="270" alt="image" src="https://user-images.githubusercontent.com/8208775/217367637-af0df2a7-37ff-41df-9fa2-bf7e7b83a262.png">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2718">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
