### ISSUE TITLE
Kotlin/JS API - transition events are missing

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-multiplatform#2719]
See also: https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent

* transitionCancel
* transitionEnd
* transitionRun
* transitionStart

Side note: Consider removing the "internal" restriction of the synthetic event constructor, so users can extend the core APIs if necessary. https://github.com/JetBrains/compose-jb/blob/master/web/core/src/jsMain/kotlin/org/jetbrains/compose/web/events/SyntheticEvent.kt

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2719">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
