### ISSUE TITLE
TextField readOnly property changing makes it impossible to open the keyboard

### ISSUE THREAD

**Issue by slartus** [JetBrains/compose-multiplatform#2722]
**Describe the bug**
changing the readonly value makes it impossible to open the keyboard

**Affected platforms**
- [ ] Android

**Versions**
- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.3.0

**To Reproduce**
```
var value by remember { mutableStateOf("1111") }
var readOnly by remember { mutableStateOf(false) }
val onValueChange: (String) -> Unit = remember { { value = it } }
val requester = remember { FocusRequester() }

TextField(
    modifier = Modifier.fillMaxWidth().focusRequester(requester),
    value = value,
    onValueChange = onValueChange,
    readOnly = readOnly
)
LaunchedEffect(Unit) {
    delay(300)
    requester.requestFocus()
    delay(1000)
    readOnly = true
    delay(1000)
    readOnly = false
    value = ""
    requester.requestFocus()
}
```
[device-2023-02-10-080244.webm](https://user-images.githubusercontent.com/1107015/218015526-899a5056-a2bd-4589-a0db-2d6061a82991.webm)

**Comment by slartus** [comment]
the error is not reproduced in clear Android compose

**Comment by pjBooms** [comment]
>the error is not reproduced in clear Android compose

Can you check your sample on Jetpack Compose UI 1.3.3 in clear Android Compose? Does not it have the same issue?

Please note that Compose Multiplatform 1.3.0 is based on Jetpack Compose UI 1.3.3 as stated here:  https://github.com/JetBrains/compose-jb/releases

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2722">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
