### ISSUE TITLE
initDeps(project) is not accessible.

### ISSUE THREAD

**Issue by chanjungkim** [JetBrains/compose-multiplatform#2728]
**Describe the bug**
I am doing copy and paste for my Android Project with jetpack compose to make it build even in desktop and web.

But, initDeps(project) is not accessible.

I correctly copied the buildSrc file. And there's a Deps.kt file. And android-setup.gradle.kts calls initDeps(project).

And I get, `Unresolved reference: initDeps` error. 

When I click inintDeps, it goes right to the Deps.kt file. I don't know what's wrong here.

**Affected platforms**
Select one of the platforms below:
- Android
- Desktop

**Versions**
- Kotlin version*: the same with project version
- Compose Multiplatform version*: the same with project version
- OS version(s)* (required for Desktop and iOS issues): any
- OS architecture (x86 or arm64):  arm64

**To Reproduce**
...

**Expected behavior**
Buildable.

**Screenshots**
...

**Additional context**
...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2728">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
