### ISSUE TITLE
Cannot display a notification in singleWindowApplication

### ISSUE THREAD

**Issue by adb-shell** [JetBrains/compose-multiplatform#2732]
**Describe the bug**
Cannot display a notification in singleWindowApplication.

**Affected platforms**
- [x] Desktop

**Versions**
- Kotlin version*: 1.7.20 
- Compose Multiplatform version*: 1.2.2
- OS version(s)* (required for Desktop and iOS issues): Mac OS 12.6.1 
- OS architecture (x86 or arm64): x86

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a singleWindowApplication
2. Try sending notifications using TrayState
3. No error message and the notification won't be shown

Also, is creating a `Tray` mandatory in a window in-order to send notifications?

**Comment by pjBooms** [comment]
To facilitate our examining of the issue I would suggest to add a reproducing example nevertheless it seems the reproducing scenario looks simple.

**Comment by igordmn** [comment]
> Also, is creating a Tray mandatory in a window in-order to send notifications?

Yes, unfortunately. It is limitation of the current implementation. We plan to provide API that don't require it in the future. Until then, you have to look for a third-party library or call the native API directly.

**Comment by adb-shell** [comment]
> > Also, is creating a Tray mandatory in a window in-order to send notifications?
> 
> Yes, unfortunately. It is limitation of the current implementation. We plan to provide API that don't require it in the future. Until then, you have to look for a third-party library or call the native API directly, if you don't need an icon in the tray

I think this answers my question since `Tray` can be created only in an `ApplicationScope` and not in a `FrameWindowScope`, As suggested I might need to use native API directly.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2732">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
