### ISSUE TITLE
iOS TextField keyboardOptions, capitalization

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#2735]
TextField should handle capitalization argument:

keyboardOptions = KeyboardOptions(
            **capitalization = KeyboardCapitalization.None**,
            autoCorrect = false,
            keyboardType = KeyboardType.Password,
            imeAction = ImeAction.Send,
        ),

Slack discussion: https://kotlinlang.slack.com/archives/C0346LWVBJ4/p1676283616991399

**Comment by Aidanvii7** [comment]
Any updates on when this will be fixed roughly? It's a blocker for passwords :/

**Comment by dima-avdeev-jb** [comment]
> Any updates on when this will be fixed roughly? It's a blocker for passwords :/

We will take this issue in the next 3 months

**Comment by ahmedsalemelzeiny** [comment]
@mazunin-v-jb any timeline for this?

**Comment by dima-avdeev-jb** [comment]
@ahmedsalemelzeiny 
You can check it in version Compose 1.5.0-beta01

**Comment by Aidanvii7** [comment]
It still seems (as of 1.5.10) that changing `ImeAction` dynamically based on some state, that the keyboard doesn't update the `ImeAction` on iOS. This works fine on Android. Say for example, I change from `ImeAction.None` to `ImeAction.Next` when the text becomes non-empty or some other condition.

**Comment by dima-avdeev-jb** [comment]
@Aidanvii7 it was fixed in newest dev versions like in 1.6.0-dev1347

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2735">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
