### ISSUE TITLE
Enhance  Modifier.combinedClickable() with onAltClick

### ISSUE THREAD

**Issue by pjBooms** [JetBrains/compose-multiplatform#2739]
Following up Slack discussion: https://kotlinlang.slack.com/archives/C01D6HTPATV/p1676007479789079

onAltClick modifier can map to a right click on desktop, and a long press on touch screens.

It can be used in our https://github.com/JetBrains/compose-jb/tree/master/experimental/examples/minesweeper then

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2739">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
