### ISSUE TITLE
Fix top bar for iOS

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2744]
Currently iOS samples use constant offset from the top to show the content.

Instead we should calculate top bar height (that is different for different devices) and use it as offset.

The calculation should be done automatically and embedded to `androidx.compose.ui.window.Application`.

We probably also need a new parameter - `topBarColor` in this function to automatically color the top bar.

Then all iOS samples should b fixed to remove current constant offset workaround.

**Comment by mipastgt** [comment]
Isn't that approach a little bit too simplistic? See for example: https://blog.felgo.com/cross-platform-app-development/notch-developer-guide-ios-android

**Comment by dima-avdeev-jb** [comment]
Useful links.
How it works on Android: [/Users/dim/Desktop/github/dima-avdeev-jb/android-intets ](https://github.com/dima-avdeev-jb/android-intets)
Experiments on iOS: https://github.com/JetBrains/androidx/commit/36d9f9a0cefca52016ebb61fd6c29d59a2ac7413

**Comment by dima-avdeev-jb** [comment]
Done in this PR:
 - https://github.com/JetBrains/compose-multiplatform-core/pull/586

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2744">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
