### ISSUE TITLE
MenuBar KeyShortcut should take precedence over Window onKeyEvent

### ISSUE THREAD

**Issue by adrientetar** [JetBrains/compose-multiplatform#2747]
I think there is an issue where Window onKeyEvent is currently taking precedence over MenuBar Item's KeyShortcut:

I have a MenuBar Item with `KeyShortcut(Key.V, meta = true)`, but it's not being triggered because my Window onKeyEvent is handling `Key.V` for another action.

As a workaround, I could check that no modifier is pressed in my Window onKeyEvent, but I think the precedence is not right, in other toolkits that I've worked with the key shortcuts take precedence by default (e.g. Qt has a QEvent::Shortcut, but if the focus item needs to actually claim precedence it has QEvent::ShortcutOverride <https://wiki.qt.io/ShortcutOverride>).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2747">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
