### ISSUE TITLE
Handle caret position changes in input methods

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2758]
**Describe the bug**
Caret position isn't changed when we press arrow keys when we use Input methods.

**Affected platforms**
- Desktop (Windows, macOs, Linux)

**Versions**
- Compose Multiplatform version*: 1.3.1
- OS version(s)* (required for Desktop and iOS issues): Windows 11, macOs, Linux
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): OpenJDK 17

**To Reproduce**
1. Add TextField
2. Switch to Chinese layout
3. Type `q`, type `w`, press 5x Arrow Left, type `r`
4. `r` is typed in the beginning of the sentence, but the caret is in the end of the line

https://user-images.githubusercontent.com/5963351/219657315-7f250712-ff5b-4762-b561-5b0826622bff.mp4

**Expected behavior**
Caret position changes according Arrow keys
Or don't handle Arrow key at all (we need to investigate use cases for that decision)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2758">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
