### ISSUE TITLE
Ability to automatically create `UIViewControllerRepresentable` SwiftUI wrapper for Composables

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#2762]
Currently, a small wrapper function needs to be provided, for example as in [chat-mpp](https://github.com/JetBrains/compose-jb/blob/4f6c7aacb525c8ca12d2c581f3353bd25ef89114/experimental/examples/chat-mpp/iosApp/iosApp/ComposeViewControllerToSwiftUI.swift#L5-L16):

```swift
struct ComposeViewControllerToSwiftUI: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        return Main_iosKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
    }

    func sizeThatFits(_ proposal: ProposedViewSize, uiViewController: UIViewControllerType, context: Context) -> CGSize? {
        return uiViewController.view.frame.size
    }
}
```

It would be nice if this boilerplate adapter would be auto-generated for select composables (perhaps via annotation?)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2762">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
