### ISSUE TITLE
CSSStyleVariable APIs allow setting values of the wrong type

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-multiplatform#2763]
Simple example code to demonstrate the problem (here, setting a `LineStyle` variable with a `DisplayStyle` value):

```kotlin
val unexpectedVariableAssignment by variable<LineStyle>()

@Composable
fun demoUnexpectedVariableAssignment() {
    Div(attrs = {
        style { 
            unexpectedVariableAssignment(DisplayStyle.Flex)
        }
    })
}
```

**Expected**: The line `unexpectedVariableAssignment(DisplayStyle.Flex)` should not compile

**Actual**: The code compiles and runs fine.

**Comment by bitspittle** [comment]
Digging a bit more, it seems this is because CSSStyleVariable's class declaration uses `out` variance:

```kotlin
class CSSStyleVariable<out TValue : StylePropertyValue>(override val name: String) : CSSVariable
```

and the call for invoking a variable has the following API:

```kotlin
operator fun <TValue : StylePropertyValue> CSSStyleVariable<TValue>.invoke(value: TValue) { ... }
```

so it seems like what is happening is the compiler sees the line `unexpectedVariableAssignment(DisplayStyle.Flex)` and sees that `LineStyle` and `DisplayStyle` are both `StylePropertyEnum`s, so it chooses `StylePropertyEnum` as the generic type to satisfy invoking the variable.

---

I'm still not sure why this case is broken but the same code with `List` (which is also a class that uses `out` variance) seems to reject the code as expected:

```kotlin
val testVar by variable<LineStyle>()
fun <T> listTest(list: MutableList<T>, value: T) {}
fun <T : StylePropertyValue> varTest(variable: CSSStyleVariable<T>, value: T) {}

@Page
@Composable
fun demoUnexpecedVariableAssignment() {
    val list = mutableListOf<LineStyle>()

    listTest(list, LineStyle.Solid) // OK
    listTest(list, DisplayStyle.Flex) // Required: LineStyle, Found: DisplayStyle
    varTest(testVar, LineStyle.Solid) // OK
    varTest(testVar, DisplayStyle.Flex) // OK?!
```

**Comment by bitspittle** [comment]
So I'm thinking (not 100% sure if there's some other use-case I'm missing though) that `CSSStyleVariable` should *not* use any variance parameter. Instead, the method where you set the variable should be the flexible place.

In other words, I *think* this is the the way to go:

```
class CSSStyleVariable<T : StylePropertyValue>(override val name: String) : CSSVariable
operator fun <T : StylePropertyValue, V: T> CSSStyleVariable<T>.invoke(value: V) { ... }
```

This way, you ensure that the type system won't ever substitute a type with a superclass of CSSStyleVariable's original type, but you still let the target value be a subclass of the variable's type.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2763">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
