### ISSUE TITLE
Monospace is rendered as sans-serif on iOS

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#2767]
`Text` with `fontFamily = FontFamily.Monospace` on iOS/Desktop/Android:
<img width="1523" alt="image" src="https://user-images.githubusercontent.com/2178959/219983552-342545a7-69b4-4b8e-997b-429d8f8b938b.png">

**Comment by MatkovIvan** [comment]
I believe that it was fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/552

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2767">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
