### ISSUE TITLE
ImageViewer [iOS]. Add taking photos from Camera

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2774]
The current application look this way:
![image](https://user-images.githubusercontent.com/5963351/220399315-62b7789f-9d23-40b8-8d5a-b70e6f3d6b25.png)

When an user presses on the "Plus" button - we should:
1. request persmissions to access Camera
2. open a separate screen that, which contains a camera widget that occopies the whole screen, and a button at the bottom, which takes the photo, saves it to Gallery, and clothes the camera screen

The separate screen should be written on SwiftUI.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2774">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
