### ISSUE TITLE
ImageViewer [Android]. Add taking photos from Camera

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2775]
Implement https://github.com/JetBrains/compose-jb/issues/2774 for Android (use native Java API for that, and open the separate screen in a new Activity).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2775">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
