### ISSUE TITLE
ImageViewer [iOS]. Read images from Gallery

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2778]
After implementing https://github.com/JetBrains/compose-jb/issues/2774, we need to show taked photos in the application.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2778">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
