### ISSUE TITLE
ImageViewer [Desktop]. Read images from local folder

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2780]
Implement https://github.com/JetBrains/compose-jb/issues/2778 for Desktop. Read photos from local folder

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2780">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
