### ISSUE TITLE
ImageViewer [Web]. Read images from local storage

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2781]
Implement https://github.com/JetBrains/compose-jb/issues/2778 for Web. Read photos from local storage

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2781">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
