### ISSUE TITLE
FlowLayout equivalent

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#2783]
Flow layouts were removed from regular Jetpack Compose and are now only available in the Accompanist library.

Unlike the standard Row and Column composables, these layout children across multiple rows/columns if they exceed the available space.

It would be nice to have an equivalent implementation for multiplatform.

https://google.github.io/accompanist/flowlayout/

**Comment by SebastianAigner** [comment]
https://android-review.googlesource.com/c/platform/frameworks/support/+/1521704

**Comment by syt0r** [comment]
Looks like they are coming back in [`androidx.compose.foundation:foundation:1.4.0-alpha04`](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.4.0-alpha04). 

Had to implement it on my own after they initially removed, but turned out it's not that hard

**Comment by igordmn** [comment]
Yes, it should be returned in 1.4.0. Will close this issue after we rebase on Jetpack Compose 1.4.

**Comment by wwalkingg** [comment]
should be closed

**Comment by SebastianAigner** [comment]
Indeed — they’re in Compose Multiplatform 1.4.
