### ISSUE TITLE
Using GoogleMap Android composable in Desktop

### ISSUE THREAD

**Issue by JonasVautherin** [JetBrains/compose-multiplatform#2784]
Can Android elements like e.g. [GoogleMap](https://googlemaps.github.io/android-maps-compose/maps-compose/com.google.maps.android.compose/index.html) be used for a desktop app using compose-jb?

I am interested in what would make it Android-specific or not. Is it just the fact that it is packaged as an `.aar`, or is there something more fundamental?

**Comment by kirill-grouchnikov** [comment]
From https://developers.google.com/maps/documentation/android-sdk/maps-compose#installation - a required dependency is `com.google.android.gms:play-services-maps` and that is not something that exists for Desktop.

**Comment by igordmn** [comment]
Yes, it should be ported.

Looking at the source code, it seems it is written from scratch on Compose, uses some Android API (like Location API) and, as Kirill mentioned, uses an Android library `com.google.android.gms:play-services-maps` (that communicates with Google Maps API probably). The Compose code itself can be easely ported, not sure about `com.google.android.gms:play-services-maps`.

**Comment by aabolfazl** [comment]
@igordmn Did you test that we can use Android components on the KMP desktop?

**Comment by cryptrr** [comment]
Any updates?

**Comment by skillAndroid** [comment]
https://github.com/skillAndroid/openStreetMapComposeMultiplatform this is my Code pls look here for desktope Map for Compose Multiplatform and do not forget to put Starts thank you All )

**Comment by JonasVautherin** [comment]
Closing because I am not interested anymore. Rather I am looking at MapLibre for Compose Multiplatform: https://github.com/maplibre/maplibre-native/issues/2638.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2784">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
