### ISSUE TITLE
Move multiplatform examples to `Foo.<sourceSetName>.kt` and `Foo.kt` naming schemes

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#2791]
- Naming for platform code: `Foo.<sourceSetName>.kt`
- Naming for related common code: `Foo.kt` (**not** `Foo.common.kt`!)

...since we expect common code to be much more common (pun intended) in a typical multiplatform project.

(internal discussion that sparked this issue: https://jetbrains.slack.com/archives/C3F2QMT1P/p1677061789757109)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2791">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
