### ISSUE TITLE
iOS TextField options & actions are not used

### ISSUE THREAD

**Issue by codlab** [JetBrains/compose-multiplatform#2794]
**Describe the bug**
TextFields (material or material3) do not behave as expected on iOS :

- keyboardOptions's imeAction is not properly set
- keyboardActions's callbacks are not called (using onAny or specific implementations like onGo, onDone etc...)
- using maxLines = 1, singleLine = true doesn't prevent usage of "return", multiple lines are then present in the view even tho only 1 is displayed 

Android doesn't have those issues

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.3.0 (reproduced with latest 1.4.0-alpha01-dev950)
- OS version(s): 16.2
- OS architecture: arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. add a TextField or OutlinedTextField in a compose view
2. set any ImeAction, callbacks

**Expected behavior**
When the keyboard opens, it should display the expected ime type

**Screenshots**

<img width="331" alt="Screenshot" src="https://user-images.githubusercontent.com/3624067/221153435-94fb6d73-41d1-4aae-b981-7ae168614889.png">

**Additional context**

Here is a snippet reproducing the issue

```
    val textStateUserName = remember { mutableStateOf(TextFieldValue("Default Value")) }

    TextField(
        modifier = Modifier
            .fillMaxWidth()
        value = textStateUserName.value,
        onValueChange = {
            textStateUserName.value = it
            viewModel.userNameChanged(it.text)
        },
        singleLine = true,
        maxLines = 1,
        label = { Text(text = "Username") },
        keyboardOptions = KeyboardOptions(imeAction = ImeAction.Go),
        keyboardActions = KeyboardActions {
            textStateUserName.value = TextFieldValue("onAny called")
        }
    )
```

**Comment by dima-avdeev-jb** [comment]
Options described also here:
https://github.com/JetBrains/compose-multiplatform/issues/3116

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2794">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
