### ISSUE TITLE
Shadow comes up when scrolling on LazyColumn on Windows

### ISSUE THREAD

**Issue by ionull** [JetBrains/compose-multiplatform#2801]
**Describe the bug**
There is a shadow when scrolling on LazyColumn on Windows, it works well on Mac OS.

**Affected platforms**
Select one of the platforms below:
- Windows

**Versions**
- Kotlin version*:  1.8.0
- Compose Multiplatform version*:  1.3.0
- OS version(s)* (required for Desktop and iOS issues):  Windows 10
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues):  corretto-18

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Scroll on LazyColumn
2. See the error

**Expected behavior**
No shadow on the whole page

**Screenshots**

Wrong behavior
![photo_2023-02-26 19 10 33](https://user-images.githubusercontent.com/242295/221406986-45ec35fc-09d5-4548-ae02-95e2dcbf165e.jpeg)
Right behavior
![photo_2023-02-26 19 11 02](https://user-images.githubusercontent.com/242295/221407005-c3ae9dfc-4408-405e-a8c7-596ed39661ca.jpeg)

**Additional context**

**Comment by igordmn** [comment]
Could you attach the reproducer? `LazyColumn` by itself shouldn't cause this.

**Comment by ionull** [comment]
Hi, I think it may be some bug with BootCamp Windows ( I have no native Windows to test, my friend said it was ok on his device)

**Comment by igordmn** [comment]
>Will do it when I have time

Ok, thanks! Closing this issue for now, as it lack neccesseary information to know where the issue (in which component, and on which side - your application, or the framework).

When you have more information, post it here, and we'll reopen the issue.

> inline content is not supported yet

It should be supported. Depends on what you use. A reproducer and expected behavior would be helpful (create a separate issue).

>withTextStyle(with image brush)

That is fixed [here](https://github.com/JetBrains/compose-multiplatform-core/pull/426)(will be in the future builds)

**Comment by ionull** [comment]
@igordmn inline content is only available for Text not for TextField? I am testing on compose 1.3.0.

**Comment by igordmn** [comment]
Sorry for the misundersanding. Yes, `inlineContent` isn't supported in the default TextField. You'll have to find a third-party solution, or write a rich editor from scratch.

**Comment by ionull** [comment]
@igordmn can you provide more info, what is "scratch"

**Comment by igordmn** [comment]
Write completly your own editor, without using TextField under the hood. Only reusing basic events, and basic drawing primitives (canvas.drawText)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2801">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
