### ISSUE TITLE
[iOS] detectTransformGestures doesn't catch zoom and rotation gestures

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#2802]
**Describe the bug**

```detectTransformGestures``` does't work for `zoom` (always 1) and `rotation` (always 0). `centroid` and `pan` work as expected.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.3.0
- OS version(s)*: iOS 16.3.1
- OS architecture (x86 or arm64): arm64

**To Reproduce**
```kotlin
@Composable
fun foo(){
    Box(modifier = Modifier
      .fillMaxSize()
      .pointerInput(Unit) {
          detectTransformGestures { _, _, zoom, rotation ->
              println("$zoom $rotation")
          }
      }
    )
}

```

**Comment by igordmn** [comment]
It is work in progress right now, will be fixed soon

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2802">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
