### ISSUE TITLE
Use `buildDir` instead when unzipping WixTools

### ISSUE THREAD

**Issue by jasonsparc** [JetBrains/compose-multiplatform#2804]
Recently, I noticed that a directory `wix311` is being created whenever I run the task `runDistributable`, and the culprit appears to be, https://github.com/JetBrains/compose-jb/blob/f6c36c392696a2d4229f1cd5db02248ba9b8ff62/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/wixToolset.kt#L40

I believe it should've been `root.buildDir`, rather than `root.projectDir`

Looking into the pull request related to it,
https://github.com/JetBrains/compose-jb/pull/2639/files#diff-c17db91fb640e81e12c9c330652e7388a45e41d222dc27014b8e0d7c6fbd76f3

…you'll see that `buildDir` was indeed used before that pull request.

This is currently a hassle in version control and I see no reason why it shouldn't reside in the `build` directory instead.

**Comment by igordmn** [comment]
Thanks!

Reproduced with Compose 1.3.0 in `desktop-template` on Windows. After we run `./gradlew runDistributable`, we see this folder:

![image](https://user-images.githubusercontent.com/5963351/221746048-2980d4f6-332f-479c-94aa-b68852a85ca9.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2804">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
