### ISSUE TITLE
Unexpected behaviour of `drawBehind` and `drawWithContent`

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#2807]
**Describe the bug**

`drawBehind` and `drawWithContent` have unexpected behaviour when drawing is outside of composable bounds and composable itself is outside of screen bounds

**Affected platforms**
- Desktop
- Web (K/JS) - Canvas based API
- iOS

**Versions**
- Kotlin version: 1.8.0 
- Compose Multiplatform version: 1.3.0 
- OS version(s): MacOS 13.2.1, iOS 16.3.1, 
- OS architecture: arm64 
- JDK: jbr-11

**To Reproduce**

[Project](https://github.com/alexzhirkevich/compose-draw)

```kotlin

@Composable
fun App() {

    var offset by remember {
        mutableStateOf(Offset.Zero)
    }

    Box(modifier = Modifier
        .fillMaxSize()
        .pointerInput(Unit) {
            detectTransformGestures { _, pan, _, _ ->
                offset += pan
            }
        }
    ){
        Box(modifier = Modifier
            .size(50.dp)
            .offset {
                offset.round()
            }
            .drawBehind {
                drawRect(
                    Color.Red,
                    Offset(-size.width*2.5f, -size.height*2.5f),
                    size * 5f,
                )
            }
            .background(Color.Green)
        )
    }
}

```

**Expected behaviour (works as expected on Android)**

https://user-images.githubusercontent.com/63979218/221611452-5d4d5664-880f-4751-8020-a630cce4e861.mov

---

**Actual behaviour (all platforms except Android)**

https://user-images.githubusercontent.com/63979218/221611473-a549c668-d4b9-4631-a5c7-2268476112e1.mov

**Comment by igordmn** [comment]
Thanks! Reproduced.

### Investigation

The function `override fun drawLayer(canvas: Canvas)` (`SkiaLayer.skiko.kt`) inside Compose causes the issue.

When we replace it by:
```
    override fun drawLayer(canvas: Canvas) {
        canvas.save()
        canvas.concat(matrix)
        canvas.translate(position.x.toFloat(), position.y.toFloat())
        performDrawLayer(canvas, Rect.Zero)
        canvas.restore()
    }
```
The issue dissapeared.

A reproducer on a pure skia Canvas:
```
@Composable
fun App2() {
    Box(modifier = Modifier
        .size(200.dp)
        .drawBehind {
            drawIntoCanvas {
                val pictureRecorder = PictureRecorder()
                val pictureCanvas = pictureRecorder.beginRecording(Rect.makeXYWH(0.0f, 0.0f, 50.0f, 50.0f))
                pictureCanvas.drawRect(
                    Rect.makeXYWH(-50f * 2.5f, -50f * 2.5f, 50f * 5f, 50f * 5f),
                    Paint().apply {
                        color = org.jetbrains.skia.Color.RED
                    }
                )
                pictureCanvas.drawRect(
                    Rect.makeXYWH(0f, 0f, 50f, 50f),
                    Paint().apply {
                        color = org.jetbrains.skia.Color.GREEN
                    }
                )
                val picture = pictureRecorder.finishRecordingAsPicture()
                it.nativeCanvas.save()
                it.nativeCanvas.translate(-51f, -51f)  // works with it.nativeCanvas.translate(500f, 500f)
                it.nativeCanvas.drawPicture(picture)
                it.nativeCanvas.restore()
            }
        })
}
```

Usually, `finishRecordingAsPicture` shouldn't clip the content out of the passed to `beginRecording` bounds, but it seems is not the case when we pass negative offset here.

**Comment by igordmn** [comment]
Probably related: https://github.com/JetBrains/compose-jb/issues/1559

**Comment by alexzhirkevich** [comment]
Hi. Any updates about this issue?

**Comment by ejektaflex** [comment]
@igordmn It seems as though this happens for positive offsets, too, not just negative offsets. If you boost the offset high enough that the green box in your reproduction moves off screen, the red box disappears.

It seems to me that whenever the rect passed to `beginRecording` is entirely off of the canvas (AKA there is no intersection), `finishRecordingAsPicture` will clip the entire content out of the picture.

**Comment by igordmn** [comment]
I tried multiple approaches, still haven't found a proper way to draw a picture outside of its bounds.

I tried:
- disable picture caching. Affects FPS significantly
- use [SkBBHFactory](https://api.skia.org/classSkPictureRecorder.html#ac7fda486f1c7b5f468253cbc5807acf1) to calculate real cullRect - it is calculated correctly, but it is clipped by the main cullRect pased to `beginRecording`. If we use some big initial rect (with coordinates greater 1E10), we experience float overflows
- use [finishRecordingAsDrawable](https://api.skia.org/classSkPictureRecorder.html#a8415ed1854ca28a778cdaa22693af87b) instead. Doesn't affect anything.

**Comment by alexzhirkevich** [comment]
@igordmn 
>If we use some big initial rect (with coordinates greater than 1E10), we experience float overflows

The maximum allowed size of composable component is  2^32 pixels. You can try to use initial react  with ~2^16 -1 side. I use this approach to workaround this issue and make an infinite canvas.

**Comment by alexzhirkevich** [comment]
But it is just my use case. It probably still can break if the offset is bigger than 2^16

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2807">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
