### ISSUE TITLE
Js compilation errors surrounding usage of value class when using compose-jb 1.3.0 with kotlin 1.7.20

### ISSUE THREAD

**Issue by jeran** [JetBrains/compose-multiplatform#2808]
**Describe the bug**
There are a couple scenarios that cause js compilation errors when using `compose-jb 1.3.0` with `kotlin 1.7.20`. Specifically providing a default parameter in a `Composable` function of type `androidx.compose.ui.semantics.Role` will cause an error. Also using a provided `androidx.compose.ui.semantics.Role` in the `Modifier.selectable()` function can cause a compilation error.

You can see the stack traces [here](https://github.com/jeran/compose-jb-value-class-bug/commit/073fa68f9f27b64145022044eb526b000aa3a1d3).

I haven't attempted with my own `value class`, but given the other two similar open issue, I'm guessing this is probably the culprit.

**Affected platforms**
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.7.20
- Compose Multiplatform version*: 1.3.0
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Clone https://github.com/jeran/compose-jb-value-class-bug
2. Run `./gradlew jsBrowserRun`

**Expected behavior**
The project should compile.

**Additional context**
This error looks related to [#2683](https://github.com/JetBrains/compose-jb/issues/2683) and [#2613](https://github.com/JetBrains/compose-jb/issues/2613), but I wanted to file a new one so it's clear this happens with `kotlin 1.7.20` and `compose-jb 1.3.0`. Also the `java.util.NoSuchElementException: Sequence is empty.` error looks unique.

**Comment by igordmn** [comment]
Thanks!

Reproduced with the attached project on Kotlin 1.7.20 and 1.8.0. Attaching code here:
```
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.selection.selectable
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.window.Window
import org.jetbrains.skiko.wasm.onWasmReady

fun main() {
    onWasmReady {
        Window("") {
            Broken()
//            Okay(Role.RadioButton)
//            Broken(role = Role.RadioButton) // okay
        }
    }
}

@Composable
fun Broken(role: Role = Role.RadioButton) {

}

@Composable
fun Okay(role: Role) {

}

//@Composable
//fun AlsoBroken(role: Role) {
//    Box(
//        modifier = Modifier
//            .selectable(
//                selected = true,
//                interactionSource = remember { MutableInteractionSource() },
//                indication = null,
//                role = role,
//                onClick = { },
//            ),
//    )
//}
```

Stacktrace:
```
e: java.util.NoSuchElementException: Sequence is empty.
        at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:112)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer.defaultValue(ComposerParamTransformer.kt:283)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer.defaultValue$default(ComposerParamTransformer.kt:262)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer.defaultArgumentFor(ComposerParamTransformer.kt:246)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer.withComposerParamIfNeeded(ComposerParamTransformer.kt:198)
        at androidx.compose.compiler.plugins.kotlin.lower.ComposerParamTransformer$copyWithComposerParam$2$2.visitCall(ComposerParamTransformer.kt:617)
```

**Comment by eymar** [comment]
+ k/native also affected

`AlsoBroken` works with kotlin 1.8.10 and compose 1.3.1-rc01, but `Broken` is still broken - I'll investigate.

**Comment by eymar** [comment]
Compose Multiplatform 1.3.1-rc02 has a fix for this. It requires using kotlin 1.8.10

**Comment by eymar** [comment]
Fixed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2808">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
