### ISSUE TITLE
Implement key handling for Slider/RangeSlider in material3

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2809]
Compose 1.3.0

We already [implemented](https://github.com/JetBrains/androidx/pull/254) that for material, we need to do the same for material3.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2809">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
