### ISSUE TITLE
Implement Paragraph.paint(...brush...) for SkiaParagraph

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2814]
Implement the new `SkiaParagraph.paint(...brush...)`.

![image](https://user-images.githubusercontent.com/5963351/222214342-7a9fe8bb-a8ee-49a7-8150-aac32d234589.png)

This is for [this feature](https://medium.com/androiddevelopers/brushing-up-on-compose-text-coloring-84d7d70dd8fa).

https://issuetracker.google.com/issues/229518449

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2814">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
