### ISSUE TITLE
Restructure Compose repositories

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2823]
1. [Done] rename https://github.com/JetBrains/androidx to https://github.com/JetBrains/compose-multiplatform-core
2. [Done] [rename compose-jb to compose-multiplatform](https://github.com/JetBrains/compose-jb/issues/2669)
3. [Done] create 3 [Github template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) repositories:

https://github.com/JetBrains/compose-multiplatform-template
https://github.com/JetBrains/compose-multiplatform-desktop-template
https://github.com/JetBrains/compose-multiplatform-web-template

4. [Done] copy the content of https://github.com/JetBrains/compose-jb/tree/master/experimental/templates to these repositories
5. [Done] add `JetBrains official` badge
6. [Done] add LICENSE file and the license badge
7. [Done] add the link to https://github.com/JetBrains/compose-multiplatform in the title of the template (Something like `<Compose Multiplatform> template`
8. [Done] enable PR's, disable issues
9. remove `experimental/templates` in `compose-multiplatform` repo
10. [Done] add the links to the templates on the main page under the experimental section

**Comment by igordmn** [comment]
сс @jimgoog, for your information, regarding first 2 points.

**Comment by pjBooms** [comment]
The last thing to do:  remove `experimental/templates` in `compose-multiplatform` repo
Only admin can do it

**Comment by francismariano** [comment]
Hello. Great job. Could you also remove the content of https://github.com/JetBrains/compose-multiplatform/tree/master/templates ??

**Comment by pjBooms** [comment]
We will do that later

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2823">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
