### ISSUE TITLE
compose/README.md says JDK 11, but the build expects JDK 17

### ISSUE THREAD

**Issue by OliverO2** [JetBrains/compose-multiplatform#2826]
**Describe the bug**
Trying the build as described in [compose/README.md](https://github.com/JetBrains/compose-jb/blob/master/compose/README.md):

```
androidx/benchmark/gradle/Adb has been compiled by a more recent version of the Java Runtime
```

**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Compose Multiplatform version*: latest sources at 5b1ce09

**Comment by dima-avdeev-jb** [comment]
Thanks!
This instruction is useful for contributors of Compose Multiplatform.
In my environment, it is also works with JDK 11.
But for that, you also need to follow another steps of this README, like this:

> ./compose/frameworks/support/jbdeps/android-sdk/downloadAndroidSdk

**Comment by OliverO2** [comment]
Interesting. I did follow the other step and downloaded the SDK. Wondering what the difference might be.

**Comment by dima-avdeev-jb** [comment]
Thanks for this research! We will check it!
What OS do you have?

**Comment by OliverO2** [comment]
Ubuntu 20.04.5 LTS (yes, I'm lazy with upgrading this one).

**Comment by dima-avdeev-jb** [comment]
@OliverO2 So, with JDK17 your development environment works well?

**Comment by dima-avdeev-jb** [comment]
I think soon we will update this doc to use JDK17 and newer.

**Comment by OliverO2** [comment]
> So, with JDK17 your development environment works well?

Yes, so far it does. I have successfully ported [compose-counting-grid](https://github.com/OliverO2/compose-counting-grid) to Wasm as you can see in this [Slack thread](https://kotlinlang.slack.com/archives/CDFP59223/p1677968419321199?thread_ts=1677885198.715929&cid=CDFP59223). Somewhat hacky, but I was able to integrate it as another example next to `compose-jb/compose/frameworks/support/compose/mpp/demo`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2826">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
