### ISSUE TITLE
Allow plugging "Preferences…" (⌘,) menu in macOS built-in app's menu

### ISSUE THREAD

**Issue by opatry** [JetBrains/compose-multiplatform#2833]
On macOS, like the about menu, the preference menu is kind of built-in.
How one can tell Compose Desktop to enable it and provide a callback when clicked?

![Capture d’écran 2023-03-05 à 21 23 33](https://user-images.githubusercontent.com/362710/222983921-563fda43-fe55-470f-8582-caf14bbda4db.png)

**Comment by dima-avdeev-jb** [comment]
```Kotlin
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.key.Key
import androidx.compose.ui.input.key.KeyShortcut
import androidx.compose.ui.window.MenuBar
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@OptIn(ExperimentalComposeUiApi::class)
fun main() = application {
    var showPreferences by remember { mutableStateOf(false) }

    Window(onCloseRequest = ::exitApplication) {
        MenuBar {
            Menu("MyMenu") {
                Item("Preferences...", shortcut = KeyShortcut(Key.Comma, meta = true), onClick = {
                    println("Preferences menu action")
                    showPreferences = true
                })
            }
        }
        Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
            Text("Click to MyMenu, or hotkey Cmd + ,")
        }
    }

    Window(
        title = "Preferences",
        onCloseRequest = { showPreferences = false },
        alwaysOnTop = true,
        visible = showPreferences
    ) {
        Box(Modifier.fillMaxSize().background(Color.LightGray), contentAlignment = Alignment.Center) {
            Text("Preferences Window")
        }
    }
}
```

**Comment by opatry** [comment]
@dima-avdeev-jb if you do that, the preferences menu will be placed under the "MyMenu" menu.
I was trying to add it as a native entry of the macOS app menu (like showcased in the IntelliJ one).

**Comment by opatry** [comment]
There used to be a way to do that with Swing application using a macOS specific `Application` class.

```java
Application macApplication = Application.getApplication();
MyApplicationAdapter macAdapter = new MyApplicationAdapter(this);
macApplication.addApplicationListener(macAdapter);

// need to enable the preferences option manually
macApplication.setEnabledPreferencesMenu(true);
```

See here: https://alvinalexander.com/java/java-mac-osx-about-preferences-quit-application-adapter/

I can't find any reference to Java API on Apple site though. 
All mentioned links are dead.

**Comment by opatry** [comment]
Knowing where to search, I finally understood that this is now covered by [JEP 272](https://openjdk.org/jeps/272), aka the `java.awat.Desktop` class.

```kotlin
var showPreferences by remember { mutableStateOf(false) }

Desktop.getDesktop().setPreferencesHandler {
    showPreferences = true
}

...

Window(
    title = "Preferences",
    onCloseRequest = { showPreferences = false },
    alwaysOnTop = true,
    visible = showPreferences
) {
    Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
        Text("Preferences Window")
    }
}
```

**Comment by opatry** [comment]
Maybe we could add the [`native distribution`](https://github.com/JetBrains/compose-multiplatform/labels/native%20distribution) label?

**Comment by dima-avdeev-jb** [comment]
> Maybe we could add the [`native distribution`](https://github.com/JetBrains/compose-multiplatform/labels/native%20distribution) label?

I think it's not related to distribution.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2833">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
