### ISSUE TITLE
AlertDialog is too narrow by default

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#2836]
**Describe the bug**
If you don't specify a concrete width for an `AlertDialog`, it attempts to display it as narrowly as possible, which often leaves a lot of unused horizontal space that could be used for a better result.

Reproducer:

```
@OptIn(ExperimentalMaterialApi::class)
fun main() = singleWindowApplication(
    state = WindowState(width = 400.dp, height = 300.dp),
) {
    MaterialTheme{
        AlertDialog(
            onDismissRequest = {},
            title = { Text("This is the title") },
            text = { Text("This is the text") },
            confirmButton = { }
        )
    }
}
```

**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Compose Multiplatform version: 1.3.0

**Expected behavior**
The alert dialog should be wider, not breaking lines as long as there is more horizontal room.

**Screenshots**
<img width="401" alt="image" src="https://user-images.githubusercontent.com/5230206/223367817-38d8464e-b05c-4f6a-b42d-6c28802f4534.png">

**Comment by m-sasha** [comment]
Another important issue caused by the same problem is that `widthIn` is ignored:

```
@OptIn(ExperimentalMaterialApi::class)
fun main() = singleWindowApplication(
    state = WindowState(width = 500.dp, height = 400.dp),
) {
    MaterialTheme{
        AlertDialog(
            modifier = Modifier.widthIn(max = 400.dp).padding(horizontal = 30.dp),
            onDismissRequest = { },
            title = { Text("This is the title") },
            text = { Text("This is the text This is the text This is the text This is the text This is the text This is the text This is the text") },
            confirmButton = {}
        )
    }
}
```

<img width="501" alt="image" src="https://user-images.githubusercontent.com/5230206/224483876-5e1a1a9b-3d22-4e54-8814-f709246f39db.png">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2836">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
