### ISSUE TITLE
ImageViewer [iOS]. Map Component

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#2840]
We'd like to show off a complex composable in the ImageViewer "Memories" page (currently, it's just a picture mockup).

For this, we need:

 - [x] provide a wrapped `MapKit` map.
 - [x] add animations or interactions to MapKit

**Comment by SebastianAigner** [comment]
cc @dima-avdeev-jb :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2840">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
