### ISSUE TITLE
Support for touch interactions in UIKit interop

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#2848]
For e.g. #2840

cc @dima-avdeev-jb

**Comment by dima-avdeev-jb** [comment]
Done

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2848">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
