### ISSUE TITLE
`Image` component renders blurry on Desktop

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#2849]
Reproducible in current experimental ImageViewer implementation.

iOS vs Desktop:
<img width="689" alt="Screenshot 2023-03-08 at 20 52 39" src="https://user-images.githubusercontent.com/2178959/223831040-4f48cc8e-544b-4927-9cf0-e1b118fc3297.png">

Android:
<img width="630" alt="Screenshot 2023-03-08 at 20 55 26" src="https://user-images.githubusercontent.com/2178959/223831991-682bc907-19a9-4f66-8e23-0d3bec922b64.png">

**Comment by malliaridis** [comment]
@SebastianAigner is this still reproducible with the latest changes? I cannot reproduce the error anymore (images changed too) in the experimental example.

**Comment by SebastianAigner** [comment]
Nope, looks good now!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2849">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
