### ISSUE TITLE
UIKit Compose inside SwiftUI. Fix visual problems on device rotation.

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#2855]
**Describe the bug**
Visual problems when device is rotated.

**Affected platforms**
Select one of the platforms below:
- iOS

**To Reproduce**
 - Use Compose inside SwiftUI.
 - Rotate device (Cmd + Right).
 
 
 ## Some additional info
 layer.layer.needRedraw()
most likely it needs to be changed to layer.layer.redrawImmediately. And implement redrawImmediately, if not already done (for destop there is).
This video shows the problem that we have Compose frames out of sync with UIKit. And because of this, just the black bars are visible during the interop. I don't know if we need to sync at all, but we'll have to think about it.

Also, fix TODOs in this PR: https://github.com/JetBrains/compose-multiplatform-core/pull/427

**Comment by dima-avdeev-jb** [comment]
Will be fixed in next dev releases

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2855">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
