### ISSUE TITLE
AlertDialog doesn't size shadow to content

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#2857]
**Describe the bug**
If padding is applied to an `AlertDialog`, the shadow will be drawn at the bounds where the dialog would have been had it not had the padding.

**Versions**
- Compose 1.3.1

**To Reproduce**

```
@OptIn(ExperimentalMaterialApi::class)
fun main() = singleWindowApplication(
    state = WindowState(width = 400.dp, height = 300.dp),
) {
    MaterialTheme{
        AlertDialog(
            modifier = Modifier.width(300.dp).padding(horizontal = 30.dp),
            onDismissRequest = { },
            title = { Text("This is the title") },
            text = { Text("This is the text") },
            dismissButton = {},
            confirmButton = {},
        )
    }
}
```

**Expected behavior**
The shadow should be at the dialog's content bounds.

**Screenshots**
<img width="401" alt="image" src="https://user-images.githubusercontent.com/5230206/224303077-c5244eb9-c013-43a7-9992-125dcbcc4631.png">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2857">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
