### ISSUE TITLE
Wrong text color inside of desktop dialogs when dark theme is used (Material3)

### ISSUE THREAD

**Issue by syt0r** [JetBrains/compose-multiplatform#2858]
**Describe the bug**
Text color for both Dialog and AlertDialog is dark when dark theme is used even though I've tried to additionally wrap dialog's content with material3 Surface and my own AppTheme

**Affected platforms**
- I'm only testing Desktop for now

**Versions**
- Kotlin version: 1.7.20 
- Compose Multiplatform version: 1.3
- OS version(s)* (required for Desktop and iOS issues): Arch Linux 
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): 

**Expected behavior**
Text should have light color as in the rest of the app

**Screenshots**
![image](https://user-images.githubusercontent.com/7478653/224382678-95c1bf1d-35df-437f-adb4-f04fd3e4bc45.png)
![image](https://user-images.githubusercontent.com/7478653/224383233-8292ec3c-91af-4944-98f1-da358fe563b2.png)

**Snippet**
```
@OptIn(ExperimentalMaterialApi::class)
@Composable
actual fun MultiplatformDialog(
    onDismissRequest: () -> Unit,
    content: @Composable () -> Unit
) {
    AlertDialog(
        onDismissRequest = onDismissRequest,
//        dialogProvider = UndecoratedWindowAlertDialogProvider,
        buttons = {
            AppTheme {
                Surface(
                    modifier = Modifier.width(IntrinsicSize.Max)
                ) { content() }
            }
        }
    )
//    Dialog(
//        onCloseRequest = onDismissRequest
//    ){
//        AppTheme {
//            Surface(
//                modifier = Modifier.width(IntrinsicSize.Max)
//            ) { content() }
//        }
//    }
}
```

```
MultiplatformDialog(
        onDismissRequest = onDismiss
    ) {

        Column(
            modifier = Modifier.padding(bottom = 18.dp)
        ) {

            Text(
                text = resolveString { createPracticeDialog.title },
                style = MaterialTheme.typography.headlineSmall,
                modifier = Modifier.padding(top = 24.dp, start = 24.dp, end = 24.dp, bottom = 8.dp)
            )

            Text(
                text = resolveString { createPracticeDialog.selectMessage },
                style = MaterialTheme.typography.bodyMedium,
                modifier = Modifier
                    .fillMaxWidth()
                    .clickable(onClick = { delayedClick(DialogOption.SELECT) })
                    .padding(vertical = 16.dp, horizontal = 24.dp)
            )

            Text(
                text = resolveString { createPracticeDialog.createMessage },
                style = MaterialTheme.typography.bodyMedium,
                modifier = Modifier
                    .fillMaxWidth()
                    .clickable(onClick = { delayedClick(DialogOption.CREATE) })
                    .padding(vertical = 16.dp, horizontal = 24.dp)
            )

        }
    }
```

**Comment by syt0r** [comment]
Managed to run it on Android, the same issue. My app was initially written without multiplatform support and there was no such issues

**Comment by JuBan1** [comment]
`@OptIn(ExperimentalMaterialApi::class)`

Could it be that you are using the Material (2) dialog in a Material 3 app? Because M3 components would be annotated with `ExperimentalMaterial3Api` if anything.

**Comment by syt0r** [comment]
Yeah, seems like there are no m3 multiplatform dialogs yet. But still I think it should work by explicitly wrapping content with theme and surface

**Comment by malliaridis** [comment]
Depending on your `AppTheme` implementation it might not properly use the dark theme colors (implementation not included).

For Material 3 your `AppTheme` should look something like this:

```kotlin
val lightColors = lightColorScheme()
val darkColors = darkColorScheme()

@Composable
fun AppTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = if (isSystemInDarkTheme()) darkColors else lightColors,
        content = content,
    )
}
```
With that set, your `AppTheme` usage (under below condition) should make proper use of colors. You can also check if you are in dark theme with `isSystemInDarkTheme()`, just for double checking everything.

Additionally, if you are mixing Material 2 with Material 3 as assumed before by JuBan1 then you can expect everything because they are not compatible as far as I experienced.

**Comment by m-sasha** [comment]
@syt0r Can you post a complete (starting from `main`) reproducer?

**Comment by syt0r** [comment]
Oh, after trying to reproduce the issue looks like I had wrong Text in imports, colors are fine with correct imports, there is no issue
It's kinda easy to import something wrong because of this :sweat_smile: 
![image](https://user-images.githubusercontent.com/7478653/224479629-50f836ec-d53c-4809-8c52-0f9d8315c705.png)

**Comment by syt0r** [comment]
Btw, are these white dots in the corners of `buttons` composable parameter expected? I'm not using parameters of AlertDialog in a right way but still

**Comment by m-sasha** [comment]
Those are probably the result of https://github.com/JetBrains/compose-multiplatform/issues/1269 which I've just recently fixed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2858">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
