### ISSUE TITLE
Context menu lacks some capabilities

### ISSUE THREAD

**Issue by adrientetar** [JetBrains/compose-multiplatform#2859]
- Right now, only the colors of [DefaultContextMenuRepresentation](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/foundation/foundation/src/desktopMain/kotlin/androidx/compose/foundation/BasicContextMenuRepresentation.desktop.kt#L96) can be customized. It would be nice to be able to customize the margins and text size etc. of both the menu and the menu items.
  + For the menu, it could take a `modifier` parameter applied to the Column inner composable.
  + For the menu item, perhaps [ContextMenuItem](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/foundation/foundation/src/desktopMain/kotlin/androidx/compose/foundation/ContextMenuProvider.desktop.kt#L140) should take a composable content lambda instead of a string label.
- Right now, it's not possible to display an icon or a keyboard shortcut in the menu. It is spec'ed in Material Design context menus, though:
![image](https://user-images.githubusercontent.com/1250894/224387674-ffa351d4-3dbb-43a0-9894-b2fb0275771f.png)

- Right now, it's not possible to add a divider to a context menu (and customize divider styling), see #1357 
- Right now, it's not possible to have a disabled menu item
- Right now, it's not possible to add an item with a submenu
- Styling:
  + Right now, the shadow looks larger/more diffuse than in the Material spec.
  + The menu item hover color is quite dark in light mode, I think it's a lighter color in the Material spec.
  + I think it would be nice to add more corner rounding, like in the Material 3 spec (it would match the current desktop UI trends better).

**Comment by m-sasha** [comment]
Thanks, we'll discuss this with the team.

**Comment by adrientetar** [comment]
@m-sasha have any update on the discussion?

**Comment by m-sasha** [comment]
I apologize for taking a long time; we were busy with M1 and Kotlinconf. And now our team lead is on vacation, so unfortunately it'll take a little longer.

**Comment by m-sasha** [comment]
Hi. So, these suggestions are good, but right now we're focusing on other issues for the desktop. We should, however, add material3 soon-ish, which should address some of the requests here. And of course, we will get to polishing our context menu APIs some time.

**Comment by dzirbel** [comment]
In the meantime, I've put together a library that adds quite a bit of this missing functionality (icons, dividers, sub-menus, styling, etc): https://github.com/dzirbel/compose-material-context-menu. I hope this can cover most use cases until the team can dedicate time toward the builtin representation.

I also ran into a few limitations along the way, which I'll raise in a separate issue for discussion.

**Comment by PMARZV** [comment]
a simple modifier in context menu and a composable function to ContextMenuItem would be awesome! It lacks customization and that rect shape looks terrible😅

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2859">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
