### ISSUE TITLE
Improve error about not supporting the latest version of Kotlin

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2865]
In Compose 1.4.0-alpha01-dev954, we have this error:
```
This version of Compose Multiplatform doesn't support Kotlin 1.8.10. Please see https://github.com/JetBrains/compose-jb/blob/master/VERSIONING.md#kotlin-compatibility to know the latest supported version of Kotlin.
```

But it is better to say what is the latest version is supported, because the page only describes stable Compose versions:
```
This version of Compose Multiplatform doesn't support Kotlin 1.8.10 (the latest supported is 1.8.0). Please see https://github.com/JetBrains/compose-jb/blob/master/VERSIONING.md#kotlin-compatibility to know the latest supported version of Kotlin.
```

**Comment by eymar** [comment]
Also we can add the compose version itself:

for example:
"This version (**1.3.1)** of Compose Multiplatform ..."

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2865">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
