### ISSUE TITLE
Many error messages when we use unsupported version of Kotlin

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2866]
Compose 1.3.1

If we use multiple modules and use unsupported version of Kotlin, we see many errors:

![image](https://user-images.githubusercontent.com/5963351/224756259-755ddc54-bfe0-4b71-82b8-d8311c88ddcd.png)

There should be only one message in the console.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2866">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
