### ISSUE TITLE
iOS. Implement Snapshot.asContextElement()

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2869]
We should implement `SnapshotContextElementImpl` in `ActualNative.native.kt` file:
![image](https://user-images.githubusercontent.com/5963351/224868420-591bee40-f043-4a60-8a07-7216347b457e.png)

**Comment by MatkovIvan** [comment]
Related to https://github.com/Kotlin/kotlinx.coroutines/issues/3326

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2869">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
