### ISSUE TITLE
iOS. implement AnnotatedString.transform

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2870]
NativeAnnotatedString.kt:
![image](https://user-images.githubusercontent.com/5963351/224870016-3288fb55-9e9f-42bb-b518-7d992d98084f.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2870">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
