### ISSUE TITLE
iOS. Implement NativeLocale.toLanguageTag

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2872]
NativePlatformLocale.native.kt:
![image](https://user-images.githubusercontent.com/5963351/224870516-71641bf4-7c0c-4a51-b9c3-e40567a9bdc1.png)

**Comment by igordmn** [comment]
Fixed here: https://github.com/JetBrains/compose-multiplatform-core/pull/408/files

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2872">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
