### ISSUE TITLE
iOS. specify GenericFontFamiliesMapping

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2874]
We need to specify iOS fonts in NativeFont.native.kt:
![image](https://user-images.githubusercontent.com/5963351/224870901-8ea22b3f-9496-4069-a67f-f2fbea46c59d.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2874">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
