### ISSUE TITLE
iOS. Implement NativeParagraphIntrinsics.native.kt

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2875]
![image](https://user-images.githubusercontent.com/5963351/224871089-50e2393c-cb44-425a-90ad-434c00d1c2c5.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2875">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
