### ISSUE TITLE
iOS. Implement NativeStringDelegate.native.kt

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2876]
![image](https://user-images.githubusercontent.com/5963351/224871200-fdf8c829-f22c-4941-9c8b-dcaa82f4ec07.png)
(we need to pass locale)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2876">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
