### ISSUE TITLE
iOS. Implement WeakHashMap.native.kt

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2877]
WeakHashMap.native.kt:
![image](https://user-images.githubusercontent.com/5963351/224871557-55ddf514-e166-4e5c-b6b5-97aa02c9b773.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2877">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
