### ISSUE TITLE
iOS. Implement TreeSet.native.kt

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2878]
TreeSet.native.kt:
![image](https://user-images.githubusercontent.com/5963351/224872201-d37680f6-9bd4-4f22-808b-4ab2bb5a5678.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2878">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
