### ISSUE TITLE
Template compose-multiplatform-ios-android-template

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2880]
Similar to https://github.com/JetBrains/compose-multiplatform/issues/2823

We need a template that supports only iOS and Android, because removing the other targets isn't easy right now, but they may not be needed.

**Comment by katia-energizer** [comment]
We don't want to use `mobile` in naming. It may associate just with Android. Let's use `compose-multiplatform-ios-android-template` to avoid confusion as discussed with @SebastianAigner in Slack.

**Comment by pjBooms** [comment]
Here it is: https://github.com/JetBrains/compose-multiplatform-ios-android-template
Couple of things to be done:
1. Remove issues
2. Add About

**Comment by igordmn** [comment]
> Couple of things to be done:

Done

**Comment by igordmn** [comment]
@katia-energizer, should we change the title to `Compose Multiplatform iOS+Android Application`?

![image](https://user-images.githubusercontent.com/5963351/227214947-176bb62f-bb97-48d7-9880-64f556193689.png)

**Comment by subchannel13** [comment]
How to use this template?

I have Koplin Multiplatform Mobile and Compose Multiplatform IDE Support plugins installed for Android Studio. When I pick Kotlin Multiplatform App template I get project structure that is on the first look similar to compose-multiplatform-ios-android-template but is actually implemented in not multiplatform friendly way. Shared module has no UI components (no `App`). Instead each platform has it's own `Greeting` and theme implementation. I can't find any information how to add a template to AS (so I assumed it's shipped with a plugin) and there is no info about it in readme files nor on wiki...

**Comment by pjBooms** [comment]
>How to use this template?

**Comment by subchannel13** [comment]
Yes?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2880">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
