### ISSUE TITLE
In examples imageviewer,When showPopUpMessage is called repeatedly in a short time, Toast will never show

### ISSUE THREAD

**Issue by CaiDingxian** [JetBrains/compose-multiplatform#2882]
**Describe the bug**
In examples imageviewer When showPopUpMessage is called repeatedly in a short time, Toast will never show.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.6
- Compose Multiplatform version*: 1.1.1
- OS version(s)*: Windows 11 22H2
- OS architecture: arm64
- JDK (for desktop issues): JDK11

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. click dots button in any miniature image 
2. then click dots button in another miniature,fast
3. then the Toast will never show when you click again and again

**Additional context**
the bug may cause by Toast.kt    
code:
`
 if (isShown) {
        return
 }
`

![图片](https://user-images.githubusercontent.com/37413956/225269288-d6d30470-f4ac-4044-816f-9766da52d8fe.png)

video

https://user-images.githubusercontent.com/37413956/226234664-8cdcdd61-6213-40dd-a384-978012a5078a.mp4

**Comment by CaiDingxian** [comment]
OK,I have add a video reproducing the issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2882">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
