### ISSUE TITLE
Implement paragraph's drawStyle paramenter experimental API

### ISSUE THREAD

**Issue by MatkovIvan** [JetBrains/compose-multiplatform#2883]
In `1.4.0`, Jetpack Compose introduces `DrawStyle` parameter `TextStyle` that enables drawing outlined text. It needs to be supported on multiplatform.

Note: To get the same look on previous versions you can use `Canvas`/`Paint` API.

References:
- https://partnerissuetracker.corp.google.com/issues/155421273
- https://android-review.googlesource.com/c/platform/frameworks/support/+/2185560

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2883">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
