### ISSUE TITLE
cursor should be HAND when item could be clickable

### ISSUE THREAD

**Issue by wwalkingg** [JetBrains/compose-multiplatform#2889]

**Comment by StefanOltmann** [comment]
I think the default hovering effect for clickables, as it is currently implemented, is the standard in modern apps. I wouldn't want a hand cursor in my app.

**Comment by m-sasha** [comment]
The hand cursor is meant to be used when it's not clear that something is clickable. Compose doesn't have that information about your widgets, so we leave the choice to you, with `Modifier.pointerHoverIcon`.
