### ISSUE TITLE
API to get system tray location

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#289]
For toolbar helper applications (like JetBrains Toolbox or 1Password), we usually want to place an (undecorated) window close to the tray icon bar. However, as far as I can tell, there is no way to currently obtain the location of the tray icon for a CFD application, so an API for it would be great!

**Comment by falcon4ever** [comment]
Would love to have a helper function like this. For the time being, what would be the advised workaround (or how does JetBrains Toolbox solve this problem?)

An idea I had would be to use the mouse cursor position and attempt to position an (undecorated) window close to the top of the screen (that would only work for Linux and macOS, unsure what the desired behavior should be for Windows)?

**Comment by y9vad9** [comment]
very actual for me

**Comment by y9vad9** [comment]
that's great, thanks for your response 

hope we will have it sometime

**Comment by lanwen** [comment]
Could you point to an example of how to use a system API within the compose-multiplatform? Maybe you could also point to a system API examples to get the location?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5529">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by guiyanakuang** [comment]
Here I'd like to share my solution. I use JNA to call the Mac system API to obtain the tray icon window position information. This implementation can simultaneously retrieve the current application's tray icon position information from multiple displays. I hope this will be helpful to those who need it.

First, here's the Kotlin code that defines the JNA interface and structures:
```kotlin
import com.sun.jna.Library
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure

interface MacosApi : Library {

    fun getTrayWindowInfos(pid: Long): Pointer?

    companion object {
        val INSTANCE: MacosApi = Native.load("MacosApi", MacosApi::class.java)

        fun getTrayWindowInfos(pid: Long): List<WindowInfo> {
            return INSTANCE.getTrayWindowInfos(pid)?.let {
                val windowInfoArray = WindowInfoArray(it)
                windowInfoArray.read()

                val count = windowInfoArray.count
                val windowInfos = windowInfoArray.windowInfos!!

                (0 until count).map { i ->
                    val windowInfo = WindowInfo(windowInfos.share((i * WindowInfo().size()).toLong()))
                    windowInfo.read()
                    windowInfo
                }
            } ?: emptyList()
        }
    }
}

@Structure.FieldOrder("x", "y", "width", "height", "displayID")
class WindowInfo : Structure {
    @JvmField var x: Float = 0f

    @JvmField var y: Float = 0f

    @JvmField var width: Float = 0f

    @JvmField var height: Float = 0f

    @JvmField var displayID: Int = 0

    constructor() : super()

    constructor(p: Pointer) : super(p) {
        read()
    }

    fun contains(
        x: Int,
        y: Int,
    ): Boolean {
        return x >= this.x && x <= this.x + width && y >= this.y && y <= this.y + height
    }

    override fun toString(): String {
        return "WindowInfo(x=$x, y=$y, width=$width, height=$height, displayID=$displayID)"
    }
}

@Structure.FieldOrder("count", "windowInfos")
class WindowInfoArray(p: Pointer) : Structure(p) {
    @JvmField var count: Int = 0

    @JvmField var windowInfos: Pointer? = null

    init {
        read()
    }
}
```

Swift code for native macOS functionality 
```swift
import AppKit

public struct WindowInfo {
   var x: Float
   var y: Float
   var width: Float
   var height: Float
   var displayID: UInt32
}

public struct WindowInfoArray {
    var count: Int32
    var windowInfos: UnsafeMutableRawPointer
}

@_cdecl("getTrayWindowInfos")
public func getTrayWindowInfos(pid: Int) -> UnsafeMutableRawPointer? {
    var trayWindows: [WindowInfo] = []
    let options: CGWindowListOption = [.optionOnScreenOnly, .excludeDesktopElements]
    if let windowInfo = CGWindowListCopyWindowInfo(options, kCGNullWindowID) as? [[String: Any]] {
       for info in windowInfo {
           if let bounds = info[kCGWindowBounds as String] as? [String: Any],
              let layer = info[kCGWindowLayer as String] as? Int,
              layer == 25,  // Menu bar/status item layer
              let ownerPID = info[kCGWindowOwnerPID as String] as? Int,
              ownerPID == pid,
              let x = bounds["X"] as? CGFloat,
              let y = bounds["Y"] as? CGFloat,
              let width = bounds["Width"] as? CGFloat,
              let height = bounds["Height"] as? CGFloat,
              width < 50 && height < 50 {
                  var displayID = CGMainDisplayID()  // Default to main display
                  for screen in NSScreen.screens {
                      if let screenNumber = screen.deviceDescription[NSDeviceDescriptionKey("NSScreenNumber")] as? NSNumber,
                         screen.frame.contains(CGPoint(x: x, y: y)) {
                          displayID = screenNumber.uint32Value
                          break
                      }
                  }
                  let windowInfo = WindowInfo(
                      x: Float(x),
                      y: Float(y),
                      width: Float(width),
                      height: Float(height),
                      displayID: displayID
                  )
                  trayWindows.append(windowInfo)
           }
       }
    }
    let arrayPtr = UnsafeMutablePointer<WindowInfoArray>.allocate(capacity: 1)
    // Allocate memory for the array of WindowInfo structs
    let count = trayWindows.count
    let bufferPtr = UnsafeMutableBufferPointer<WindowInfo>.allocate(capacity: count)

    // Copy the WindowInfo structs into the allocated memory
    for (index, window) in trayWindows.enumerated() {
        bufferPtr[index] = window
    }

    arrayPtr.pointee = WindowInfoArray(count: Int32(count), windowInfos: UnsafeMutableRawPointer(bufferPtr.baseAddress!))

    return UnsafeMutableRawPointer(arrayPtr)
}
```

For the complete implementation, see: https://github.com/CrossPaste/crosspaste-desktop/pull/1612/files

**Comment by enciyo** [comment]
I found a workaround like below. At least one click is needed to get Windows location of the TrayIcon

    import androidx.compose.runtime.compositionLocalOf
    import androidx.compose.ui.unit.dp
    import androidx.compose.ui.window.WindowPosition
    import java.awt.SystemTray
    import java.awt.TrayIcon
    import java.awt.event.MouseEvent
    import java.awt.event.MouseListener
    import java.beans.PropertyChangeEvent
    import java.beans.PropertyChangeListener
    
    
    val LocalTrayIconWindowPosition = compositionLocalOf { TrayIconWindowPosition() }
    
    class TrayIconWindowPosition : PropertyChangeListener, MouseListenerWrapper {
    
        @Volatile
        var currentLocation: WindowPosition = WindowPosition(0.dp, 0.dp)
        private val propertyName = "trayIcons"
    
        init {
            if (SystemTray.getSystemTray().trayIcons.isEmpty())
                SystemTray.getSystemTray().addPropertyChangeListener(propertyName, this)
        }
    
    
        override fun propertyChange(evt: PropertyChangeEvent?) {
            getLastTray().addMouseListener(this)
        }
    
        override fun mousePressed(e: MouseEvent) {
            synchronized(this) {
                currentLocation = WindowPosition(e.x.dp, e.y.dp)
            }
            getLastTray().removeMouseListener(this)
        }
    
    
        private fun getLastTray(): TrayIcon {
            return SystemTray.getSystemTray().trayIcons.last()
        }
    
    }
    
    private interface MouseListenerWrapper : MouseListener {
        override fun mouseClicked(e: MouseEvent?) = Unit
        override fun mousePressed(e: MouseEvent) = Unit
        override fun mouseReleased(e: MouseEvent?) = Unit
        override fun mouseEntered(e: MouseEvent?) = Unit
        override fun mouseExited(e: MouseEvent?) = Unit
    
    }
