### ISSUE TITLE
iOS ImageViewer MKMapView can't click/move/touch

### ISSUE THREAD

**Issue by evenlan1990** [JetBrains/compose-multiplatform#2892]
Describe the bug
experimental/examples/image-viewer MKMapView can't click/move/touch  on iOS

Affected platforms

iOS
Versions
kotlin.version=1.8.0
agp.version=7.1.3
compose.version=1.4.0-alpha01-dev977

To Reproduce
On simulator iPhone 14.
MKMapView can't click/move/touch.

We need to interact with the map, hope this problem can be solved as soon as possible, thanks. @dima-avdeev-jb 

![image](https://user-images.githubusercontent.com/57431230/225844105-0e799e08-525d-464a-a7a2-1e48d29c908f.png)

**Comment by dima-avdeev-jb** [comment]
Thanks! Yes, we know it, and we will fix it.

**Comment by dima-avdeev-jb** [comment]
Please follow the already created issue here:
https://github.com/JetBrains/compose-multiplatform/issues/2848

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2892">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
