### ISSUE TITLE
WindowTests flaky after fix closing ComposeScenes

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#2893]
After merging the [PR to enforce closing of ComposeScenes](https://github.com/JetBrains/compose-multiplatform-core/pull/440) we have `WindowTest`s failing randomly in the CI:

https://teamcity.jetbrains.com/buildConfiguration/JetBrainsPublicProjects_Compose_DesktopTestsForPullRequests/4100568?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true

**Affected platforms**
- Desktop (Linux, our CI)

The tests seem to run fine on Mac OS X, even when run 100 times in a row.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2893">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
