### ISSUE TITLE
Text selection doesn't work correctly in Codeviewer

### ISSUE THREAD

**Issue by MatkovIvan** [JetBrains/compose-multiplatform#2899]
**Affected platforms**
- Desktop

**Versions**
- Compose Multiplatform version*: `1.3.1`
- OS version(s)* (required for Desktop and iOS issues): macOS

**To Reproduce**
1. Run examples/codeviewer (`./gradlew run`)
1. Try to select text starting from empty line
1. Only 1 line can be selected

**Expected behavior**
Text is selecting to the cursor

**Screenshots**

https://user-images.githubusercontent.com/1836384/226384996-b849308f-60cd-4e8b-b634-d50dba34568b.mov

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2899">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
