### ISSUE TITLE
onClick handlers for tray icon

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#290]
Currently, it's only possible to attach a menu to the tray icon. For small helper applications, it would be nice to also have access to an onClick event on the icon directly, without having to go through a single-entry menu. Examples of applications that work like this are 1Password, JetBrains Toolbox, [Coca](https://apps.apple.com/de/app/coca/id1000808993?mt=12) and others.

**Comment by Simsimplus** [comment]
I modify Tray function, and it does print log when mouse is clicked

...
```kotlin
val tray = remember {
        TrayIcon(awtIcon).apply {
            isImageAutoSize = true
            addMouseListener(
                object :MouseListener{
                    override fun mouseClicked(e: MouseEvent?) {
                        println("mouseClicked")
                    }

                    override fun mousePressed(e: MouseEvent?) {
                        println("mousePressed")
                    }

                    override fun mouseReleased(e: MouseEvent?) {
                        println("mouseReleased")
                    }

                    override fun mouseEntered(e: MouseEvent?) {
                        println("mouseEntered")
                    }

                    override fun mouseExited(e: MouseEvent?) {
                        println("mouseExited")
                    }

                }
            )
            addActionListener {
                currentOnAction()
            }
        }
    }
```
...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5528">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
