### ISSUE TITLE
Using a public property extensions with a @Composable backing delegate fails to link for iOS targets

### ISSUE THREAD

**Issue by xxfast** [JetBrains/compose-multiplatform#2901]
**Describe the bug**
I have property extensions with a @Composable backing delegate that looks like this 
```kotlin
val text: String @Composable get() = "Some text"
```
This works as expected for android/desktop, but fails to link for ios clients and throws this error 
```
> Task :app:ui:linkPodDebugFrameworkIosSimulatorArm64

Showing All Messages
> Task :app:ios-compose:linkPodDebugFrameworkIosSimulatorArm64 FAILED
e: There is still an unbound symbol after generation of IR module <NyTimes>:

Unbound public symbol IrSimpleFunctionPublicSymbolImpl: io.github.xxfast.nytimes.ios.compose/text.<get-text>|8349765969627210272[0]

This could happen if there are two libraries, where one library was compiled against the different version of the other library than the one currently used in the project. Please check that the project configuration is correct and has consistent versions of dependencies.
```

Current work around is to keep these either private or internal 
```kotlin
private val text: String @Composable get() = "Some text"
// or
private val text: String @Composable get() = "Some text"
```

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.10 
- Compose Multiplatform version*:  1.3.1
- OS version(s)*:  iOS 16.2
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Checkout https://github.com/xxfast/NYTimes-KMP/commit/fc231fca88e46cd7d928c65ac71a1dffbbaf1fb4
2. Open `app/ios/ios.xcworkspace` and run

**Expected behavior**
`@Composable` backing delegates for iOS targets to behave the same as other platforms.

This is similar to #2903 so feel free to close this or that if it is the same underlying issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2901">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
