### ISSUE TITLE
Including a public ProvidableCompositionLocal causes linking for iOS targets to fail

### ISSUE THREAD

**Issue by xxfast** [JetBrains/compose-multiplatform#2903]
**Describe the bug**
I have a `ProvidableCompositionLocal` defined as 
```kotlin
val LocalUnit: ProvidableCompositionLocal<Unit> = staticCompositionLocalOf { }
```
This causes linking to fail
```
> Task :app:ios-compose:linkPodDebugFrameworkIosSimulatorArm64
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: androidx.compose.runtime/CompositionLocal.current.<get-current>|-5302841245303420610[0]
```
Current workaround is to mark these either private or internal
```kotlin
private val LocalUnit: ProvidableCompositionLocal<Unit> = staticCompositionLocalOf { }
// or
internal val LocalUnit: ProvidableCompositionLocal<Unit> = staticCompositionLocalOf { }
```

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.10 
- Compose Multiplatform version*:  1.3.1
- OS version(s)*:  iOS 16.2
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Checkout https://github.com/xxfast/NYTimes-KMP/commit/add79ab738c5bd2c18a01dc903e77e1fa5caf9a0
2. Open `app/ios/ios.xcworkspace` from xcode and run

**Expected behavior**
iOS targets to support `ProvidableCompositionLocal` similar to android and desktop targets

**Comment by eymar** [comment]
Another workaround is to add an annotation:
```kotlin
@HiddenFromObjC
val LocalUnit: ProvidableCompositionLocal<Unit> = staticCompositionLocalOf { }
```
It can be added to properties and functions (you may try it for other issues you reported). 

Our goal is to fix it so there won't be a need to use `internal` or the `@HiddenFromObjC` annotation.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2903">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
