### ISSUE TITLE
Application uses discrete GPU when we attach a second monitor (Windows)

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2905]
**Describe the bug**
Application uses discrete GPU when we attach the second monitor

Reported [here](https://jetbrains.slack.com/archives/C01G87BMA2Z/p1679402536028469)

Compose 1.2.1, Windows

[Not verified]:
1. Connect a second monitor to a laptop via usb
2. Run Compose application
3. See, that it uses discrete GPU:

![image](https://user-images.githubusercontent.com/5963351/226678451-0f8c7026-d97c-4d98-b8d8-f7a00ffb9dfe.png)

**Expected behavior**
It should use integrated GPU

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2905">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
