### ISSUE TITLE
White color of text when input via input methods

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2916]
When we input text via input methods, the current input characters has the White color instead of the default Black:

https://user-images.githubusercontent.com/5963351/227558788-0110c568-3a39-4574-a821-bcd52427b28e.mp4

Regression after https://github.com/JetBrains/compose-multiplatform-core/pull/426 (a revert fixes it)

**Affected platforms**
Desktop

**Versions**
OS: Windows
Compose Version: 7fdfeeab (core repo)

**Expected behavior**
1. run this example:
```
import androidx.compose.material.TextField
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    var text by remember { mutableStateOf("") }
    TextField(text, { text = it })
}
```
2. Install Korean input in the system
3. Switch to the Korean layout, start typing
5. See that the current typed characters in the White color

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2916">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
