### ISSUE TITLE
Linux gradlew desktop:packageMsi /desktop:packageExe

### ISSUE THREAD

**Issue by ThraaxSession** [JetBrains/compose-multiplatform#2918]
**Describe the bug**
When running `gradlew desktop:packageMsi; gradlew desktop:packageExe` it's successful, but nothing is built.
I also installed msitools. But it has no affection.

**Affected platforms**
Select one of the platforms below:
- Desktop

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.3.1
- OS version(s)* (required for Desktop and iOS issues): WSL2 Debian
- OS architecture (x86 or arm64): amd64
- JDK (for desktop issues): OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Install WSL 2 Debian
2. navigate to your local windows project
3. run above commands

**Expected behavior**
It's possible to cross-compile Compose Desktop from Linux to Windows.

**Screenshots**
`gradlew desktop:packageMsi`
![image](https://user-images.githubusercontent.com/3085830/227705137-4c6849d6-efa8-4aae-a308-aedbc910e5e7.png)

`gradlew desktop:packageExe`
![image](https://user-images.githubusercontent.com/3085830/227705195-a60a6b8d-f2e4-434f-a5ff-5eb4ef6b6d18.png)

**Comment by pjBooms** [comment]
I believe that packaging to Windows distros is not supported on Linux but at least the gradle plugin  should clearly report it.

**Comment by ThraaxSession** [comment]
I would also expect a clear report. At least. :D but it would be more awesome to have cross compile. 
Can you tell me if it somehow works from Linux to Windows? @pjBooms

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2918">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
