### ISSUE TITLE
Signed MacOS app crashes with (Code Signature Invalid)

### ISSUE THREAD

**Issue by rjuszczyk** [JetBrains/compose-multiplatform#2919]
**Describe the bug**
Signed MacOS app crashes with (Code Signature Invalid). It passes verification in the Transporter app.

**Affected platforms**
- Desktop

**Versions**
- kotlin.code.style=official
- kotlin.version=1.7.10 (tested also on 1.8.10)
- agp.version=7.3.0
- compose.version=1.2.0 (tested also on 1.3.1)
- jdk-18.0.2.1.jdk
- on MacOS Ventura 13.1 M1pro
- XCode Version 14.2 (14C18)

**To Reproduce**
I am trying to create a .pkg to upload it to the Mac AppStore with the TestFlight enabled..

1. Create a project in IntelliJ:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/1647827/227714045-79847e82-d8c9-4914-866e-713963191d2a.png">

2. Certificates:

Add two certificates to the Keychain Access:

Mac App Distribution
Mac Installer Distribution

<img width="596" alt="image" src="https://user-images.githubusercontent.com/1647827/227714067-a54a8178-524b-4054-aa75-0d8707243fd4.png">

3. Register App IDs:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/1647827/227714073-2bd56284-ff1c-4bf8-8702-7ed343780455.png">

4. Prepare Provisioning Profiles:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/1647827/227714106-17182b33-64e3-4f7c-97f1-587b9d402261.png">

(Make sure that the provisioning profiles are prepared for the right certificates)

5. Configure Gradle DSL:

Copiy **_EmbeddedForComposeForMacOs.provisionprofile_** to the projectDir and rename to:
**_embedded.provisionprofile_**
Copy **_runtimeComposeForMacOs.provisionprofile_** to the projectDir and rename to:
**_runtime.provisionprofile_**

Add entitlements files:

In my case in entitlements.plist I used these values:

```
...
<key>com.apple.application-identifier</key>
<string>6B2GN3FRAK.com.rjuszczyk.composeformacos</string>
<key>com.apple.developer.team-identifier</key>
<string>6B2GN3FRAK</string>
...
```

6. Create the app in the appstoreconnect.apple.com:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/1647827/227714176-477ef7b0-e088-4cf4-8537-744a53960b44.png">

7. Run `packagePkg` task
8. Drag and drop generated .pkg to **_Transporter app_** and click Verify
9. I was getting this error:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/1647827/227714197-936e5556-e888-47c4-93c4-09205701c354.png">

10. So I specified javaHome to point to x64 jdk in (build.gradle)

  `javaHome = "/Library/Java/JavaVirtualMachines/jdk-18.0.2.1.jdk/Contents/Home/"`

Clean and run `packagePkg` again and check it in the **_Transporter app_**

Now it verifies without errors:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/1647827/227714242-7331e775-2433-40b6-a18d-eb9397443b3c.png">

11. But when I try to run the .app from _**build/compose/binaries/main/app**_ directory it fails with error:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/1647827/227714254-d4c2928d-8dd4-4833-b438-de57c0208f9c.png">

12. Then I published it to the App Store Connect and added a test group and added a version to TestFlight which then I downloaded via the TestFlight app and tried to open:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/1647827/227715506-a76389b4-270e-44ab-950d-577156aa8077.png">

But when I click OPEN, nothing happens.

**Expected behavior**

- The .app should not crash with Code Signature Invalid. 
- The .pkg should install (now nothing happens).
- The TestFlight build should open in TestFlight (now nothing happens)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2919">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
