### ISSUE TITLE
Automatic Preview Updates

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#2921]
Is there any way to make the Desktop Preview update automatically as you type your code? Even with macros? Is there at least a keyboard shortcut? Clicking the little icon over and over is not very efficient, and I can't tell if there is any alternative.

**Comment by sergeshustoff** [comment]
Could you please at least add a button somewhere in the preview window to refresh it manually? Sometimes it requires some scrolling to find the preview button and refresh after some changes. Preview itself is quite usefull, but requires extra steps to use)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2921">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
