### ISSUE TITLE
Popups aren't created in their own separate window

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#2924]
Popups in Compose Desktop should be put in their own popup window, like Swing does. This helps to avoid issues with z-fighting with Swing components, and lets popups (such as tooltips and drop downs) appear outside the Compose panel that owns them.

**Comment by m-sasha** [comment]
Not saying that this shouldn't be considered, but putting tooltips into a native window could have its own issues. I remember such windows stealing keyboard focus, for example, or make the parent window drawn like a "background" window.

**Comment by rock3r** [comment]
@m-sasha surely there will be side effects, but this is a pretty important feature to have for desktop apps, especially for [Jewel](https://github.com/jetbrains/jewel) and its ability to interop with the Swing components in IJ, which do use popup windows

**Comment by Nohus** [comment]
This prevents tooltips (from `TooltipArea`) from being able to be drawn outside a window. I have a tooltip that is supposed to be centered above an element. That element is near the edge of the window, so half of the tooltip should display past the edge of the window, but currently this breaks.

**Comment by hamen** [comment]
Hi all

I tried the current `compose.layers.type=WINDOW` experimental solution, but I'm noticing some unexpected behavior:
https://github.com/JetBrains/jewel/issues/97#issuecomment-2286621700

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2924">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
