### ISSUE TITLE
Resizing windows displays black bars

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#2925]
On desktop, when resizing a window, there can be black bars appearing on the edges of the window when it grows, or can cause the Compose contents of the window to be briefly cut off due to lack of recomposition during the resize.

**Comment by quarrant** [comment]
same...

**Comment by dudusandi** [comment]
same

**Comment by babramovitch** [comment]
@MatkovIvan When closing #4744 you mentioned that running on windows with OpenGL instead of DirectX was somewhat better with black bars instead of content streching? Is there a way to configure the apps to use OpenGL instead?

**Comment by MatkovIvan** [comment]
@babramovitch 
```kt
System.setProperty("skiko.renderApi", "OPENGL")
```

**Comment by babramovitch** [comment]
@MatkovIvan That doesn't seem to make any change for me on Windows 10, does the same resizing instead of black bars calling it first thing in main()

**Comment by MatkovIvan** [comment]
Make sure that you've set it before initialization
```kt
fun main() {
    System.setProperty("skiko.renderApi", "OPENGL")
    singleWindowApplication {
        println("RENDER API: ${window.renderApi}")
        Box(Modifier.size(200.dp).background(color = Color.Green)) {}
    }
}
```

**Comment by MatkovIvan** [comment]
Also, I've prepared a skiko fix that also should make it better - https://github.com/JetBrains/skiko/pull/923

**Comment by babramovitch** [comment]
Ah that was it, I was using the fun `main() = application {` and after was already too late.  

Oh awesome about making it better as well, I'll keep an eye on that one.  In the meantime using OpenGL looks better than what it was doing.

**Comment by rock3r** [comment]
A note — on desktop you can set the `compose.swing.render.on.graphics` property to `true` — _before_ the `ComposePanel` is added to the hierarchy! — to use the slower, but not artifact-prone Swing-based compositing. The tradeoff is mainly in CPU usage.

**Comment by DroidLin** [comment]
@MatkovIvan works just fine on win11

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2925">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2925">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
