### ISSUE TITLE
`Window.isVisible = true` does not work

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#2928]
**Describe the bug**

I have some simple code to reproduce this issue, and I think the code is self explanatory.

**Affected platforms**

Desktop

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*:  `org.jetbrains.compose:compose-gradle-plugin:1.3.1`
- OS version(s)* (required for Desktop and iOS issues):  MacOSX Venture 13.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17 or 1.8 (unsure because there is an android module present. I can figure this out if it is neccesary)

**To Reproduce**

1. Create a project with the code below
2. Run the code and observe that the window hides but then does not show
3. comment out the line `window.isVisible = windowShouldBeVisible` (inside the lambda)
4. Uncomment the line `visible = windowShouldBeVisible` (the function parameter value)
5. Run the code again and observe that the window hides and then shows; it works as expected

```kotlin
import androidx.compose.material.Text
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import kotlin.concurrent.thread

fun main() {

    var windowShouldBeVisible by mutableStateOf(true)

    thread {
        println("sleeping for 3 seconds...")
        Thread.sleep(3000)
        println("hiding window")
        windowShouldBeVisible = false
        println("window should now be hiding")
        println("sleeping for 3 seconds...")
        Thread.sleep(3000)
        println("showing window")
        windowShouldBeVisible = true
        println("window should now be showing")
    }

    application {

        println("recomposing application")



        Window(
            onCloseRequest = ::exitApplication,
            alwaysOnTop = true,
            /*visible = windowShouldBeVisible*/
        ) {
            println("recomposing window: window.isVisible=${window.isVisible}, windowShouldBeVisible=${windowShouldBeVisible}")
            window.isVisible = windowShouldBeVisible
            Text("Hello World")
        }


    }
}

```

**Expected behavior**

I expect the window to hide and then show regardless if I set window visibility in the function parameter or in the lambda

**Comment by m-sasha** [comment]
When the window is invisible, its content is not part of the composition, so setting "windowShouldBeVisible = true` doesn't cause the window's content to be recomposed, and therefore `window.isVisible` isn't called.

Composition should be free of side-effects, and yours isn't

**Comment by m-sasha** [comment]
A good place to ask such questions is our [Slack](kotlinlang.slack.com).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2928">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
