### ISSUE TITLE
compiler plugin: k/js IrSimpleFunctionPublicSymbolImpl is already bound

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-multiplatform#2929]
**Describe the bug**
Initially, the error was:
```
e: java.lang.IllegalStateException: IdSignature clash: ...
```
But the WA was applied:
```
tasks.withType<org.jetbrains.kotlin.gradle.dsl.KotlinJsCompile>().configureEach {
    kotlinOptions.freeCompilerArgs += listOf(
        "-Xklib-enable-signature-clash-checks=false",
    )
}
```
and then another error showed up:
```
Using Kotlin/JS IR backend
i: found daemon on port 17448 (41271503 ms old), trying to connect
i: connected to the daemon
e: java.lang.IllegalStateException: IrSimpleFunctionPublicSymbolImpl for com.github.jetbrains.rssreader.compose/$get-navigationBars$$composable|8383160220186553660[0] is already bound: FUN DEFAULT_PROPERTY_ACCESSOR name:$get-navigationBars$$composable visibility:internal modality:FINAL <> ($receiver:androidx.compose.foundation.layout.WindowInsets.Companion, $composer:androidx.compose.runtime.Composer?, $changed:kotlin.Int) returnType:androidx.compose.foundation.layout.WindowInsets
        at org.jetbrains.kotlin.ir.symbols.impl.IrBindablePublicSymbolBase.bind(IrPublicSymbolBase.kt:58)
        at org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl.<init>(IrFunctionImpl.kt:100)
```

![image](https://user-images.githubusercontent.com/7372778/228186589-c5d36ebd-4b4b-45ca-8d0a-40c9f72b31c3.png)

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - HTML based API
- Web (K/JS) - Canvas based API
If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*:  1.4.0-alpha01-dev980

**Comment by eymar** [comment]
The reproducer:

https://github.com/Kotlin/kmm-production-sample/tree/issue-2929
`./gradlew :composeApp:jsBrowserRun -i`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2929">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
