### ISSUE TITLE
API for system tray text (macOS)

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#293]
macOS allows tray applications to write text in the tray area ("menu bar extra") instead of simply displaying an icon. It would be nice if the same could be achieved via Compose for Desktop.
![image](https://user-images.githubusercontent.com/2178959/105135442-5171de80-5af0-11eb-99fa-819f60ca5fe1.png)

Other examples I could find are https://www.macstories.net/mac/textbar-puts-your-text-into-the-menu-bar/, https://apps.apple.com/us/app/infinite-menu-bar/id1439179659?mt=12

**Comment by tetexxr** [comment]
Is there any news on this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5525">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
