### ISSUE TITLE
how to get current window position?

### ISSUE THREAD

**Issue by wangzhigang1112** [JetBrains/compose-multiplatform#2930]
how to get current window position?

**Comment by malliaridis** [comment]
In [Top Level Windows Management](https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Window_API_new) you have an overview of what you can do with window states.

For getting the window position you can simply do something like:

```kotlin
application {
    // get the window state
    val state = rememberWindowState()
    Window(onCloseRequest = ::exitApplication, state) {
        // Pass the window state position information to the composable function that needs it
        App(state.position)
    }
}
```

**Comment by wangzhigang1112** [comment]
Thank you for your reply. The problem has been resolved

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2930">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
