### ISSUE TITLE
Some 'release' tasks don't use proguard

### ISSUE THREAD

**Issue by zTrap** [JetBrains/compose-multiplatform#2931]
Tasks `packageReleaseUberJarForCurrentOS` and `runRelease` uses jars from `jar` and dont even run `proguardReleaseJars`

**Versions**
- Kotlin version: 1.8.10
- Compose Multiplatform version: 1.3.1

**Comment by mamenglong** [comment]
try this [guide](https://github.com/JetBrains/compose-multiplatform/blob/aa08279104cacc46a063a4322369a3b2bc66462f/tutorials/Native_distributions_and_local_execution/README.md#obfuscation)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2931">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
