### ISSUE TITLE
[Web,Canvas] LazyColumn or Column can't scroll

### ISSUE THREAD

**Issue by yellowcath** [JetBrains/compose-multiplatform#2932]
version 
`
kotlin.version=1.8.0   
compose.version=1.4.0-alpha01-dev954
`
Is this bug or not support?
<img width="934" alt="image" src="https://user-images.githubusercontent.com/5828577/228236740-4ad7922b-fb73-44ad-a553-f4901584f3c3.png">

<img width="430" alt="image" src="https://user-images.githubusercontent.com/5828577/228236781-c9c81ae3-814d-4135-9dd6-dab45210ede5.png">

**Comment by eymar** [comment]
Fixed in 1.6.0-alpha01 and later version. 1.6.0-rc01 is the latest available

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2932">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
