### ISSUE TITLE
Investigate new features in the focus system and apply them to ComposePanel/SwingPanel interop

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2944]
After we rebased on Jetpack Compose 1.4, there are few new features in FocusOwner.kt:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/5963351/229038760-831c5ce4-f29f-430c-b3dc-dff15d225158.png">

We don't handle them when we use ComposePanel/SwingPanel.

Old features (moveFocus/clearFocus work) correctly

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2944">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
