### ISSUE TITLE
Selection doesn't work correctly when we select a line from right to left

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2945]
Compose b8ccac759f3a4b2f515cb75a0b8b70d677dfc389, Windows 11

1. run `desktop/run1` in the Compose sources. Or use this snippet:
```
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.material.Text
import androidx.compose.ui.*
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    SelectionContainer {
        Text(
            text = "fun <T : Comparable<T>> List<T>.quickSort(): List<T> = when {\n" +
                    "  size < 2 -> this\n" +
                    "  else -> {\n" +
                    "    val pivot = first()\n" +
                    "    val (smaller, greater) = drop(1).partition { it <= pivot }\n" +
                    "    smaller.quickSort() + pivot + greater.quickSort()\n" +
                    "   }\n" +
                    "}",
            modifier = Modifier
                .padding(10.dp)
        )
    }
}

```
2. select text from right to left
3 See that that upper lines are selected too:
https://user-images.githubusercontent.com/5963351/229040757-97f46afd-e99c-47ff-ad7c-e67cbd3da1ae.mp4

Expected:
we select only the current line

**Comment by igordmn** [comment]
Reproducible also in 1.2.0, no need to fix in 1.4.0

**Comment by igordmn** [comment]
The same whe we select from left to right - we select all text to the end.

Let's treat it as a feature.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2945">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
