### ISSUE TITLE
CompositionLocalProvider causes an infinite loop

### ISSUE THREAD

**Issue by ShirasawaSama** [JetBrains/compose-multiplatform#2946]
**Describe the bug**
When using the code below, an infinite loop occurs when the button is clicked, and then the process is stuck.

This problem does not exist in version `1.4.0-alpha01-dev985`

```kotlin
fun main() {
    application {
        var isDarkTheme by remember { mutableStateOf(true) }
        val color = if (isDarkTheme) Color.White else Color.Black
        val style = remember(color) {
            ScrollbarStyle(16.dp, 8.dp, RoundedCornerShape(4.dp), 300, color, color)
        }
        CompositionLocalProvider(LocalScrollbarStyle.provides(style)) {
            Window(::exitApplication) {
                Button({ isDarkTheme = !isDarkTheme }) {
                    Text("Toggle theme")
                }
                LocalScrollbarStyle.current
            }
        }
    }
}
```

**Affected platforms**
Desktop

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.4.0-alpha01-dev991
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): liberica-19.0.2

**To Reproduce**
Click the `Toggle theme` button.

**Screenshots**

![test1](https://user-images.githubusercontent.com/17093811/229040326-a4f378aa-9c87-4e0f-a2ce-b77f10a22092.gif)

![test2](https://user-images.githubusercontent.com/17093811/229040792-f84e5627-2564-4116-b5af-1a6f024ac1af.gif)

**Additional context**

Call stacks:

![image](https://user-images.githubusercontent.com/17093811/229040989-52662b6e-0944-4885-8df6-78ca079b9a7e.png)

I found that the providerUpdates in Composer were not stored in order, and some 0 values appeared in the middle, which caused an infinite loop in the binary search.

![image](https://user-images.githubusercontent.com/17093811/229041197-841ada3e-0f2d-45a0-83da-23f9db316fe8.png)

**Comment by kirill-grouchnikov** [comment]
Same is seen in Aurora on anything that involves usage of composition local provider. Builds 991 and 1000 hand indefinitely.

**Comment by eymar** [comment]
The fix is waiting for the buid: https://github.com/JetBrains/compose-multiplatform-core/pull/472

**Comment by igordmn** [comment]
Should be fixed in 1.4.0-alpha01-dev1003

**Comment by kirill-grouchnikov** [comment]
Fix confirmed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2946">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
