### ISSUE TITLE
Implement IntMap without MutableMap

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2950]
After [this PR](https://github.com/JetBrains/compose-multiplatform-core/pull/472) we use MutableMap as IntMap implementation, because there are bugs in the previous implementation.

It may be not optimal because of boxing.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2950">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
