### ISSUE TITLE
Window is recomposed 2 times at the start of the application

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2951]
Compose 1.4.0-alpha01-dev985, Windows

```
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    BoxWithConstraints {
        println(maxWidth)
    }
}
```

The window is recomposed 2 times, and the first time we have 0x0 size of the window.

Actual output:
```
0.0.dp
786.0.dp
```
Expected output:
```
786.0.dp
```
Isn't reproducible in 1.4.0-alpa01-dev984

This behavior can break certain cases. For example, when we need to check the initial size of the window, we can write something like this:

```
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
    BoxWithConstraints {
        val initialWidth = remember { it.maxWidth }
    }
}
```

(see, for example "set the initial zoom by the screen/window" size [here](https://github.com/JetBrains/compose-multiplatform/blob/538903b57b6e1cc1609ec7724794bf62bb8099d6/experimental/examples/imageviewer/shared/src/commonMain/kotlin/example/imageviewer/view/ScalableImage.common.kt#L33))

**Comment by igordmn** [comment]
See also https://kotlinlang.slack.com/archives/C01D6HTPATV/p1680280112367149

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2951">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
