### ISSUE TITLE
Expose Undo/Redo state in TextField

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2958]
Compose 1.3.1

There are cases when we need to reset the Undo/Redo state. For example, look at [the Notepad example](https://github.com/JetBrains/compose-multiplatform/tree/master/examples/notepad).

https://user-images.githubusercontent.com/5963351/229469925-9313483f-2612-48f1-8b91-efb5dbf3428b.mp4

We need to be able:

1. to call undo/redo via toolbar buttons
2. to reset undo/redo when we open the new file

The alternative of 2. will be ressetting undo/redo state when the value is changed programmatically (it needs to be investigated, maybe it is not right to do that)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2958">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
