### ISSUE TITLE
AlertDialog applies its modifiers outside the padding

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#2959]
The modifier passed to `AlertDialog` is applied outside the dialog's padding. For example, applying a border:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/5230206/229477443-c27e6006-991e-489c-a8ed-6a7cd85c5ed7.png">

**Affected platforms**
- Desktop

Compose Multiplatform version* 1.4.0-alpha01-dev985

**To Reproduce**
```
@OptIn(ExperimentalMaterialApi::class)
fun main() = singleWindowApplication(
    state = WindowState(width = 800.dp, height = 400.dp),
) {
    MaterialTheme{
        AlertDialog(
            onDismissRequest = {  },
            title = { Text("Title") },
            text  = { Text("Text blah blah blah Text blah blah blah Text blah blah blah Text blah blah blah Text blah blah blah") },
            buttons = {},
            modifier = Modifier.width(600.dp).border(1.dp, Color.Black),
        )
    }
}

```

**Expected behavior**
The border should appear inside the padding.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/5230206/229478166-b0f32795-ed8e-4e2c-80f9-10cebe4eecfa.png">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2959">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
