### ISSUE TITLE
Support runDesktopComposeUiTest.effectContext argument

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2960]
ComposeUiTest.desktop.kt, Compose 1.4.0-rc01

<img width="512" alt="image" src="https://user-images.githubusercontent.com/5963351/229483012-12f139c8-81e7-49ed-a8c9-a9b4774974ef.png">

We throw an excetpion in 1.4.0-rc01

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2960">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
