### ISSUE TITLE
TextField. Support PlatformTextInputPluginRegistry for non-android targets

### ISSUE THREAD

**Issue by pjBooms** [JetBrains/compose-multiplatform#2964]
Compose 1.4 adds new abstraction: 

`androidx.compose.ui.text.input.PlatformTextInputPluginRegistry`

Documentation says:

```
The only time a new service type and adapter should be defined is
if you are building your own text input system from scratch, including your own `TextField`
composables.
```

There is also a demo for the new feature: `androidx.compose.foundation.demos.text.PlatformTextInputAdapterDemo.kt`

See also: https://partnerissuetracker.corp.google.com/issues/267235947

Support the new feature on demand.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2964">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
