### ISSUE TITLE
Check ignored tests in copyPasteAndroidTests\ScrollableTest.kt and ScrollableFocusableInteractionTest

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2965]
Compose 6ba06f4a

We copied them from Android sourceSet, but they fail on desktop.

<img width="949" alt="image" src="https://user-images.githubusercontent.com/5963351/229576514-5b2fbb25-4da6-4591-ab24-e409fb3084d2.png">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2965">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
