### ISSUE TITLE
(🐞) `js()

### ISSUE THREAD

**Issue by KotlinIsland** [JetBrains/compose-multiplatform#2966]
**Describe the bug**
```kt
plugins {
    kotlin("multiplatform") version "1.8.20"
    id("org.jetbrains.compose") version "1.3.0"
}

repositories {
    mavenCentral()
}

kotlin {
    js(IR) {
        browser()
    }
}

compose{
    kotlinCompilerPlugin.set(dependencies.compiler.forKotlin("1.8.0"))
    kotlinCompilerPluginArgs.add("suppressKotlinVersionCompatibilityCheck=1.8.20")
}
```
**Affected platforms**
Select one of the platforms below:
- All
- Desktop
- Web (K/JS) - HTML based API
- Web (K/JS) - Canvas based API
- iOS
- Other

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 
- Compose Multiplatform version*: 
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2966">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
