### ISSUE TITLE
(🐞) `js(IR)` causes `java.lang.IllegalStateException: Cannot find the Composer class in the classpath`

### ISSUE THREAD

**Issue by KotlinIsland** [JetBrains/compose-multiplatform#2967]
**Describe the bug**
Can't build when using `js(IR)`

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - HTML based API 
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.3.0 / 1.4.0-alpha01-dev1008
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 

**To Reproduce**
```kt
plugins {
    kotlin("multiplatform") version "1.8.0"
    id("org.jetbrains.compose") version "1.3.0" //"1.4.0-alpha01-dev1008"
}

repositories {
    mavenCentral()
}

kotlin {
    js(IR) {
        browser()
    }
}

```
run gradle build

```
> Task :compileKotlinJs FAILED
e: java.lang.IllegalStateException: Cannot find the Composer class in the classpath
	at androidx.compose.compiler.plugins.kotlin.lower.AbstractComposeLowering.<init>(AbstractComposeLowering.kt:111)
	at androidx.compose.compiler.plugins.kotlin.lower.ClassStabilityTransformer.<init>(ClassStabilityTransformer.kt:68)
	at androidx.compose.compiler.plugins.kotlin.ComposeIrGenerationExtension.generate(ComposeIrGenerationExtension.kt:79)
```
**Expected behavior**
doesn't fail

**Screenshots**

**Additional context**

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2967">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
