### ISSUE TITLE
Proguard removes custom resources from release or breaks its names causing 'file not found' exception in runtime

### ISSUE THREAD

**Issue by alexmaryin** [JetBrains/compose-multiplatform#2969]
**Describe the bug**
I use shared resources in my multiplatform project with Compose. Here is a part from my Gradle file (common module):
```
kotlin {
     sourceSets {
        val commonMain by getting {
            resources.srcDirs("resources")
            dependencies {
                ///////
            }
        }
}

android {
    sourceSets {
        named("main") {
            manifest.srcFile("src/androidMain/AndroidManifest.xml")
            res.srcDirs("resources")
        }
    }
}
```
There are some other folders inside `resources` such as `raw` with custom json file or `drawable` with used images. Both debug version and package version without Proguard run well and open resource files properly. But Proguard applying makes something which causes `file not found` excption in runtime. I use `compose-desktop.pro` file with Proguard rules from this issue tracker with custom rules for Compose and Realm, but only the following rules allow Release to run properly:
```
-dontshrink
-dontoptimize
```
Applying these rules makes task with Proguard fully no use.

**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.3.0
- OS version(s)* (required for Desktop and iOS issues): Ubunti 22.10
- OS architecture (x86 or arm64): 64
- JDK (for desktop issues): openJDK 17

[compose-desktop.pro.txt](https://github.com/JetBrains/compose-multiplatform/files/11145545/compose-desktop.pro.txt)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2969">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
