### ISSUE TITLE
Review how ambientShadowColor, spotShadowColor work in non-Android targets

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2971]
They were added in Jetpack Compose 1.2 and moved to Compose Multiplatform 1.2 without proper testing:

```
Modifier.graphicsLayer(spotShadowColor = Color.Red, ambientShadowColor = Color.Green)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2971">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
