### ISSUE TITLE
Check how new scroll on focus work in tests

### ISSUE THREAD

**Issue by Walingar** [JetBrains/compose-multiplatform#2979]
It appeared that scroll on focus was reworked in Compose 1.4. See [commit](https://github.com/JetBrains/compose-multiplatform-core/commit/7e77bb541331ce0d62cabad732e43eca41ac978a)

Previously it used simple animation, and it worked fine for tests, but with the new implementation it can be endless, or doesn't work right.

Related to PR: https://github.com/JetBrains/compose-multiplatform-core/pull/493

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2979">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
