### ISSUE TITLE
Improve default fonts in androidx

### ISSUE THREAD

**Issue by adrientetar** [JetBrains/compose-multiplatform#2985]
On Mac OS, the monospace font from `FontFamily.Monospace` is Courier:

![image](https://user-images.githubusercontent.com/1250894/230145510-05a1ff24-fcc7-4684-b1ae-2352e9c05e1f.png)

https://github.com/JetBrains/compose-multiplatform-core/blob/617003013309e84633fdf5b4689512e241fc4fad/compose/ui/ui-text/src/desktopMain/kotlin/androidx/compose/ui/text/platform/DesktopFont.desktop.kt#L57

But that's an old typewriter style font that looks out of place in UI. Can it be replaced with SF Mono or Menlo?

```kt
listOf("SF Mono", "Menlo")
```

Also on Windows, there is a UI font called Segoe UI:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/1250894/230146253-a29db6a7-377b-4c04-b058-1e70e778616e.png">

```kt
listOf("Segoe UI", "Arial")
```

Thank you.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2985">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
