### ISSUE TITLE
iOS TextField bugs

### ISSUE THREAD

**Issue by etolstoy** [JetBrains/compose-multiplatform#2986]
- https://github.com/JetBrains/compose-multiplatform/issues/2984
 - https://github.com/JetBrains/compose-multiplatform/issues/2682
   - https://github.com/JetBrains/compose-multiplatform/issues/3102
 - https://github.com/JetBrains/compose-multiplatform/issues/2752
 - https://github.com/JetBrains/compose-multiplatform/issues/2794
   - https://github.com/JetBrains/compose-multiplatform/issues/3116
   - https://github.com/JetBrains/compose-multiplatform/issues/2735
 - https://github.com/JetBrains/compose-multiplatform/issues/2988
 - https://github.com/JetBrains/compose-multiplatform/issues/2991
 - https://github.com/JetBrains/compose-multiplatform/issues/3104
 - https://github.com/JetBrains/compose-multiplatform/issues/3098
 - https://github.com/JetBrains/compose-multiplatform/issues/3096
 - https://github.com/JetBrains/compose-multiplatform/issues/3128
 - https://github.com/JetBrains/compose-multiplatform/issues/3242
 - https://github.com/JetBrains/compose-multiplatform/issues/3101
 - https://github.com/JetBrains/compose-multiplatform/issues/2964
 - https://github.com/JetBrains/compose-multiplatform/issues/3276
 - https://github.com/JetBrains/compose-multiplatform/issues/3621
 - https://github.com/JetBrains/compose-multiplatform/issues/3416
 - https://github.com/JetBrains/compose-multiplatform/issues/3101
 - https://github.com/JetBrains/compose-multiplatform/issues/3473
 - https://github.com/JetBrains/compose-multiplatform/issues/3856
 - https://github.com/JetBrains/compose-multiplatform/issues/3276
 - https://github.com/JetBrains/compose-multiplatform/issues/3103
 - https://github.com/JetBrains/compose-multiplatform/issues/2987

**Comment by Ribesg** [comment]
I think this one is related to some of these issues but not directly covered by any of them: https://github.com/JetBrains/compose-multiplatform/issues/3242

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2986">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2986">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
