### ISSUE TITLE
iOS TextField, backspace behavior on simulator

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#2987]
On physical keyboard backspace - deletes 2 symbols

https://user-images.githubusercontent.com/99798741/230149088-f8bd97e7-0189-479a-8aeb-59baf8344cd3.mp4

**Comment by magdalenatsolaki** [comment]
maybe similar problem:
Issue found f.e. on “BoxScope.EditMemoryDialog” (example "imageviewer")
The caps key random activates and deactives while typing after backspace key and return key

**Comment by paxbun** [comment]
I think JetBrains/compose-multiplatform-core#699 fixed this; could you please double-check this?

**Comment by dima-avdeev-jb** [comment]
Thanks, Done!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2987">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
