### ISSUE TITLE
iOS TextField with password type. Prevent autofill, copy/paster, etc.

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#2988]
We should research how password uses in TextFields on iOS, and add same logic.
We should prevent autofill for passwords.
Maybe we should block clipboard as well.

**Comment by dima-avdeev-jb** [comment]
Related issue for Desktop: https://github.com/JetBrains/compose-multiplatform/issues/3062

**Comment by dima-avdeev-jb** [comment]
Will be fixed in Compose multiplatform 1.6.0

**Comment by zacharee** [comment]
This still seems to be an issue on 1.6.1. When `keyboardType = KeyboardType.Password`, the context options don't show up.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2988">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
