### ISSUE TITLE
Snapshot testing for compose-web

### ISSUE THREAD

**Issue by Burtan** [JetBrains/compose-multiplatform#2992]
Hey,
has anyone succeeded in using snapshot testing for compose-web? I there are some tools lacking to test the ui, especially as there is also no compose preview for compose web.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2992">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
