### ISSUE TITLE
Window loses its focus after recomposition of another window

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2994]
Compose 1.3.1, Desktop, Windows 11, OpenJDK 17

1. Open the examples/notepad (gradlew run)
2. Open the second window
3. Hide the tray using the menu of the second window
4. The first window receives the focus

https://user-images.githubusercontent.com/5963351/230204526-83e66722-d2ec-4264-b2d1-ddd0a769bf14.mp4

Expected:
The second window remains in the focus

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2994">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
