### ISSUE TITLE
js, macos Native - fix sending pointer events

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#2999]
Compose b13dac17, jscanvas, macos native targets.

Clicks doesn't work in these targets.

The issue that skiko sends wrongly event.pressedButtons on each event:
```
demo.js:61209 onPointerEvent [LEFT]
demo.js:61209 onPointerEvent 
demo.js:61209 onPointerEvent [LEFT]
demo.js:61209 onPointerEvent 
demo.js:61209 onPointerEvent [LEFT]
```
<img width="676" alt="image" src="https://user-images.githubusercontent.com/5963351/230409545-66e6d373-0f08-4423-a6f8-212f507bd7f9.png">

Probably because we change a global variable on each event [here](https://github.com/JetBrains/skiko/blob/66c5e2bf2d69677fd5668e39ea044949019f878a/skiko/src/jsMain/kotlin/org/jetbrains/skiko/Convertors.js.kt#L148)

There is a temporary fix in [this PR](https://github.com/JetBrains/compose-multiplatform-core/pull/497)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2999">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
