### ISSUE TITLE
[JS, Canvas] Some composables like `Button` with externally defined `shape` argument cause crash when shape is `RoundedCornerShape` with one or more zero corners

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#3013]
`BottomSheetScaffold` causes crash when `sheetShape` is `RoundedCornerShape` with one or more zero corners

EDIT: not only scaffold.  Some other composables like `Button` with externally defined `shape` argument also causes crash

**Affected platforms**
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version: 1.8.10 
- Compose Multiplatform version: 1.3.1
- OS version(s): Mac OS 13.3, Chrome 

**To Reproduce**

```kotlin

fun App() {
    onWasmReady {
        Window {
            BottomSheetScaffold(
                sheetContent = {
                    Text("Content")
                },
                sheetShape = RoundedCornerShape(10.dp, 10.dp, 10.dp, 0.dp)
            ) {

            }
        }
    }
}
```

**Screenshots**
<img width="772" alt="image" src="https://user-images.githubusercontent.com/63979218/230697704-47959461-487d-4364-adab-b2d00c674ca7.png">

**Comment by alexzhirkevich** [comment]
Still reproduces in 1.4.0-rc03 but also causes `IndexOutOfBoundsException` before runtime error if content inside the scaffold is empty

**Comment by dima-avdeev-jb** [comment]
Reproduced this crash on PR:
https://github.com/JetBrains/compose-multiplatform-core/pull/503

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3013">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
