### ISSUE TITLE
In the Windows 10 system, the window flickers.

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/compose-multiplatform#3014]
**Describe the bug**
In the Windows 10 system, the window is set to be maximized, and after clicking the close button, the window flickers.

**Affected platforms**
Select one of the platforms below:
- Desktop

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.4.0-rc03
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): 64
- JDK (for desktop issues): jdk 17

**To Reproduce**
fun main() = application {
    var isOpen by remember { mutableStateOf(true) }
    var isAskingToClose by remember { mutableStateOf(false) }
//    val state = rememberWindowState(placement = WindowPlacement.Maximized)
    val name = buildString {
        append("mosfet")
    }
    //        val data by remember { mutableStateOf(listOf("A", "B", "C")) }

    val filePath = "src/jvmMain/kotlin/devices/$name.json"
    val file = File(filePath)
    val chips = Klaxon().parse<Device?>(file)
    val data = chips?.paras?.toList()
    println(data)
    val headerData by remember {
        mutableStateOf(
            listOf(
                " ",
                "Symbal",
                "Desc",
                "Con",
                "Min",
                "Act",
                "Max",
                "Unit",
                "Note",
                "Pass",
                "Fail"
            )
        )
    }
//    println(state)
    if (isOpen) {
        Window(onCloseRequest = { isAskingToClose = true },
               state = rememberWindowState(placement = WindowPlacement.Maximized),
               title = "", transparent = true,
               undecorated = true) {

            if (isAskingToClose) {
                Dialog(
                    onCloseRequest = { isAskingToClose = false },
                    title = "Close the document without saving?",
                ) {
                    Button(
                        onClick = { isOpen = false }
                    ) {
                        Text("Yes")
                    }
                }
            }

           

            

            Scaffold(
                topBar = {
                    TopAppBar(title = {
                        Text(
                            "Desktop", modifier = Modifier.fillMaxWidth().wrapContentSize(
                                Alignment.Center
                            )
                        )
                    }, modifier = Modifier.fillMaxWidth(), navigationIcon = {
                        IconButton(onClick = { println("点击了返回按钮") }) {
                            Icon(Icons.Filled.ArrowBack, null)
                        }
                    }, actions = {

                        IconButton(onClick = {  }) {
                            Icon(Icons.Filled.Settings, null)
                        }
                        IconButton(onClick = { isAskingToClose = true }) {
                            Icon(Icons.Filled.Close, null)
                        }
                    })
                },
                content = {
                    LazyColumn(
                        modifier = Modifier.fillMaxSize(),
                        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp)
                    ) {
                        item {
                            Row(
                                modifier = Modifier.fillMaxWidth().background(Color.LightGray).padding(
                                    5.dp
                                ),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                headerData.forEach {
                                    if (it == " ") {
                                        Text(text = it, modifier = Modifier.weight(0.5f), textAlign = TextAlign.Center)
                                    } else {

                                        Text(text = it, modifier = Modifier.weight(1f), textAlign = TextAlign.Center)
                                    }
                                }

                            }
                        }

                        items(data!!.size) {

                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Checkbox(
                                    checked = data[it].isSelected,
                                    onCheckedChange = {},
                                    modifier = Modifier.weight(0.5f)
                                )
                                Text(
                                    text = data[it].name.toString(),
                                    modifier = Modifier.weight(1f),
                                    textAlign = TextAlign.Center
                                )
                                Text(
                                    data[it].desc.toString(),
                                    modifier = Modifier.weight(1f),
                                    maxLines = 1,
                                    textAlign = TextAlign.Center
                                )
                                Text(
                                    data[it].conditions.toString(),
                                    modifier = Modifier.weight(1f),
                                    textAlign = TextAlign.Center
                                )
                                Text(
                                    data[it].minValue.toString(),
                                    modifier = Modifier.weight(1f),
                                    textAlign = TextAlign.Center
                                )
                                Text(
                                    data[it].actValue.toString(),
                                    modifier = Modifier.weight(1f),
                                    textAlign = TextAlign.Center
                                )
                                Text(
                                    data[it].maxValue.toString(),
                                    modifier = Modifier.weight(1f),
                                    textAlign = TextAlign.Center
                                )
                                Text(
                                    data[it].unit.toString(),
                                    modifier = Modifier.weight(1f),
                                    textAlign = TextAlign.Center
                                )
                                Text(
                                    data[it].note.toString(),
                                    modifier = Modifier.weight(1f),
                                    textAlign = TextAlign.Center
                                )
                                Text(
                                    data[it].passBin.toString(),
                                    modifier = Modifier.weight(1f),
                                    textAlign = TextAlign.Center
                                )
                                Text(
                                    data[it].failBin.toString(),
                                    modifier = Modifier.weight(1f),
                                    textAlign = TextAlign.Center
                                )
                            }

                        }

                    }
                }
            )
        }

    }

}

https://user-images.githubusercontent.com/19502034/230698546-7cb69e22-66e4-429c-bb15-ebb7cc1825c7.mp4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3014">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
