### ISSUE TITLE
Low FPS on Linux with maximized window

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#302]
Compose 0.0.0-vsync-build30
Compose 0.3.0-build141 (without delay in FrameDispatcher and DefaultMonotonicFrameClock)

Ubuntu 20.04.1 LTS (X11 Window Manager), 100Hz display
Intel 9900K, NVIDIA 2080 Ti

1. run ./gradle :compose:desktop:desktop-samples:run1 (example with animation)
2. measure FPS. Result - 100 FPS
3. maximize the window
4. measure FPS. Result - 30 FPS

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6383">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
