### ISSUE TITLE
Request: Modifier extension for composable bounds relative to screen

### ISSUE THREAD

**Issue by bennysway** [JetBrains/compose-multiplatform#3035]
I have been using this snippet for some requirements:

```kotlin
.onGloballyPositioned { coords ->
    size = Rect(coords.localToWindow(Offset.Zero), coords.size.toSize())
    println("Size at $size")
}
```
The new requirements need to fullfil opening a new window/dialog/surface in using bounds as anchors. I tried modifying `DropdownMenuPositionProvider` since it has some implementation on bound calculation. But after creating a custom class of it, and passing the coords to new window initialization, the values are offsetted to the previous window. But yes as I'm typing this, I am now thinking of using this offset as well, but if its possible, can there be a new modifier like `onScreenPositioned` or similar?

**Comment by dima-avdeev-jb** [comment]
You need `Modifier. onScreenPositioned{ }`
That arguments do you need inside it?

**Comment by bennysway** [comment]
A custom object similar to LayoutCoordinates that can have a query `.positionInScreen()` extension that does external calculations of app window offset, density etc. I did a work around and I think it can be condensed to on function
```
val density = LocalDensity.current
    val localWindowX = (windowLocation?.x ?: 0f) / density.density
    val localWindowY = (windowLocation?.y ?: 0f) / density.density
    ...
    val dialogState = rememberDialogState(
        width = 350.dp,
        height = Dp.Unspecified,
        position = WindowPosition(
            windowX,
            windowY
        )
    )
    Dialog(
        state = dialogState,
        ...
```

**Comment by dima-avdeev-jb** [comment]
Something like this?
```Kotlin
Modifier.onScreenPositioned { windowCoordinates ->
    val currentWidowsPosition: Offset = windowCoordinates.positionInScreen()
    println("current window coordinates: $currentWidowsPosition")
}
```

**Comment by bennysway** [comment]
If it returns
```
|     [    (component)  ]       |
|                               |
|<---------^ Offest.x   ^       |
|                               |
|_______________________________|
```
then well done sir

**Comment by dima-avdeev-jb** [comment]
It should be offset related to a current opened window?

**Comment by bennysway** [comment]
Yes, because in multi window scenario, we can get the wrong offset, knowing that the active window triggered the action

**Comment by dima-avdeev-jb** [comment]
```Kotlin
Modifier.onScreenPositioned { currentComponentCoords: Offset ->
    println("current component relative position in opened screen: $currentComponentCoords")
}
```
May be this way?

**Comment by bennysway** [comment]
Honestly I cant define the standard of how it should look, but yes, screen position of a component should be like the coordinates relative to the active windows screen. I had done some Robot test from the AWT lib. and they always get coordinates of the screen/monitor that the active window is in.

**Comment by dima-avdeev-jb** [comment]
Ok, thanks for the feature description

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3035">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by bennysway** [comment]
Checked the latest version, (like months ago) Works well so I'm closing this issue <3
