### ISSUE TITLE
Date and Time

### ISSUE THREAD

**Issue by PriyaAnju** [JetBrains/compose-multiplatform#3043]
Hi Team 
It will be great if date and time support below 26 version, it works fine in above 26. i integrated desugar_jdk_libs but its not supporting.I request you to give some solution for this issue. Thanks in advance

Process: com.myapplication.MyApplication, PID: 6051
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/Math8;
at j$.time.Duration.ofSeconds(Duration.java:245)
at j$.time.temporal.ChronoUnit.<clinit>(ChronoUnit.java:190)
at j$.time.temporal.ChronoField.<clinit>(ChronoField.java:120)
at j$.time.LocalDate.of(LocalDate.java:266)
at j$.time.LocalDate.<clinit>(LocalDate.java:144)

**Comment by dima-avdeev-jb** [comment]
Hello!
This is an Android related question.
I think you should check the official Android documentation: https://developer.android.com/studio/write/java8-support#library-desugaring

I made a sample with usage of java.time.LocalDate here:
https://github.com/dima-avdeev-jb/question-android-desugaring

And exactly this commit adds desugarring:
https://github.com/dima-avdeev-jb/question-android-desugaring/commit/b0c9f50cb9e6da80ba72c9aae1d7764ad637c493

If it does not help, you can contact the Google Android team in issue tracker:
For Android platform bugs: https://partnerissuetracker.corp.google.com/issues/new?component=190923&template=841312
Or for documentation problems: https://partnerissuetracker.corp.google.com/issues/new?component=192697&template=845603

**Comment by PriyaAnju** [comment]
Hello  team,

Now Date and time is working in the less than  26 version i updated android
studio and agp version and desugar version.

Thank you

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3043">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
