### ISSUE TITLE
Usage of deprecated forEachGesture in Scrollbar.desktop.kt

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-multiplatform#3045]
https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/foundation/foundation/src/desktopMain/kotlin/androidx/compose/foundation/Scrollbar.desktop.kt#L842 is using the deprecated `forEachGesture`:

```
'forEachGesture(suspend PointerInputScope.() -> Unit): Unit' is deprecated. 
Use awaitEachGesture instead. forEachGesture() can drop events between gestures.
```

However, it can't be simply replaced by `awaitEachGesture`, as the `awaitPointerEventScope` is defined on `PointerInputScope`, but `awaitEachGesture` expects `AwaitPointerEventScope`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3045">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
