### ISSUE TITLE
[UIKit] API for navigation between Compose screens

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#3046]
Short description:
**Provide API for native like(or really native) navigation between Compose screens on iOS with native gestures.**

Previous title:
**[UIKit] Unclear behaviour of nested `UIViewController`s lifecycle**

[Fixed together with memory leak fix]

~~I try to implement something like native uikit navigation for compose using `UINavigationController` and `UiKitView`. And i faced the moment when i need to be notified when controller is popped.
 I cannot override `viewDidDissapear` of `UIViewController` cause `ComposeWindow` is internal, so i tried to use `DisposableEffect` for that. But when ComposeWindow pops from `UINavigationController`, `DisposableEffect` inside composable block does never execute `onDispose`.~~

**Comment by dima-avdeev-jb** [comment]
Thanks, your current goal is to have native iOS navigation with UINavigationController?
Do you want to navigate betwee UIKit and Compose screens, or just navigate between different Compose screens?

I think it's completed to use this code:
```
 UIKitView(
        modifier = Modifier.fillMaxSize(),
        factory = {
            navController.view
        }
    )
```
This UIKitView looks redundant.

Maybe we can provide a better API for navigation between Compose screens and between UIKit screen and Compose.

**Comment by dima-avdeev-jb** [comment]
Ok, thanks!
For now we have different goals for better performance and fixing other bugs in Compose, but this issue is important as well.
We will provide the needful API in the future.

**Comment by alexzhirkevich** [comment]
Just a little example of what can be done for now with `UINavigationController`. It is awesome, isn't it?

https://user-images.githubusercontent.com/63979218/231277302-1a7972d4-42bc-4dab-9b6a-8d041db811bf.mp4

**Comment by dima-avdeev-jb** [comment]
Cool!

**Comment by matteocrippa** [comment]
@alexzhirkevich the plan is to release it as PR in `Precompose` lib?

**Comment by lukwol** [comment]
I'm currently experimenting with a way to abstract navigation for all Compose targets in my [project](https://github.com/lukwol/cm-navigation).
Right now navigation on iOS or Desktop looks the same as on Android - screens are changed with crossfade animation.
For now there is no back gesture on iOS (like on Android) but I might consider adding one.

**Comment by alexzhirkevich** [comment]
Original issue is related to #3201

**Comment by arkivanov** [comment]
Just FYI, Decompose supports the predictive back gesture on all platforms. There is one known bug which I will fix soon, though. 
https://arkivanov.github.io/Decompose/extensions/compose/#predictive-back-gesture

Plus, there are feature requests to make it better customizable, so it could look closer to the native variant.

**Comment by AhmedMourad0** [comment]
Any updates on this? As awesome as the community libraries addressing this are, I think Compose Multiplatform needs first party navigation and resource management solutions as those are parts of the app that can't be migrated easily if a library gets abandoned or isn't quick enough to fix critical bugs or update to newer kotlin/compose releases.

**Comment by dima-avdeev-jb** [comment]
@AhmedMourad0 Thanks! Yeah - you are right!
We have resources library and want to enhance it. Code samples https://github.com/JetBrains/compose-multiplatform/blob/master/components/resources/demo/shared/src/commonMain/kotlin/org/jetbrains/compose/resources/demo/shared/UseResources.kt

Also we are looking at navigation as well! For now we are investigating different approaches and trying to find the best direction!

**Comment by lukwol** [comment]
Great news. I'm looking forward to first party solutions for navigation and resource management.
In the meantime I've updated my [navigation](https://github.com/lukwol/navigation) library to benefit from custom transitions and finally published it on [Maven Central](https://central.sonatype.com/).
As for the string resources on mobile, Android XMLs and iOS Strings Catalog, hidden behind common API works fine for me.

**Comment by MatkovIvan** [comment]
For navigation inside compose we have ported jetpack compose navigation - see https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-navigation-routing.html
If you need navigate between native screens and compose - use native/platform solution.

Supporting back gesture is tracked here - https://github.com/JetBrains/compose-multiplatform/issues/4419

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3046">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3046">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3046">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
