### ISSUE TITLE
Falling Balls iOS crash

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3049]
Compose 1.4.0, Kotlin 1.8.20, Compose Multiplatform repo commit 4c225aa, iPhone 11 simulator

1. run examples/falling-balls on iOS
2. click "start"
3. wait 4 min 
[Crash iOS 2023-04-13.txt](https://github.com/JetBrains/compose-multiplatform/files/11221378/Crash.iOS.2023-04-13.txt)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3049">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
