### ISSUE TITLE
Shader Compilation Error

### ISSUE THREAD

**Issue by ScottPierce** [JetBrains/compose-multiplatform#3052]
**Describe the bug**
The Desktop Compose app won't run on a Mac. It was working, but with an update it seems to have stopped working for the user.

![image](https://user-images.githubusercontent.com/871169/231887525-14179208-9869-4248-bb41-d026ecb5114e.png)

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.3.1
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues):  17.0.6 Coretto

**To Reproduce**
The users device is Late 2012 Mac Mini with 2.5 Ghz i5m and HD Graphics 4000, running Ventura 13.3.1.

**Expected behavior**
The app runs correctly.

**Comment by dima-avdeev-jb** [comment]
Hello, Thanks for this report!
Can you please create a minimal reproducible sample on GitHub?

**Comment by ScottPierce** [comment]
No. We can't even reproduce this locally. We found out the person running this is running a patched OS with an unofficial patch. We're thinking maybe that they are missing a framework that they are supposed to have.

In the mean time, this doesn't seem worthwhile for you guys to waste your time on.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3052">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
