### ISSUE TITLE
How to obtain the system API? For example, obtaining a list of system processes and operating to end a process. What technical solution is suitable, such as supporting MAC, WIN, Linux

### ISSUE THREAD

**Issue by wangzhigang1112** [JetBrains/compose-multiplatform#3055]
How to obtain the system API? For example, obtaining a list of system processes and operating to end a process. What technical solution is suitable, such as supporting MAC, WIN, Linux

**Comment by dima-avdeev-jb** [comment]
I think it is more related to JVM specific question.
On Compose for Desktop, you can use any API available on your version of JVM.
https://stackoverflow.com/a/45068036/20579036

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3055">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
