### ISSUE TITLE
NinePath images

### ISSUE THREAD

**Issue by Adiudiu** [JetBrains/compose-multiplatform#3056]

**Comment by dima-avdeev-jb** [comment]
For now, we don't support NinePath images.

**Comment by dima-avdeev-jb** [comment]
I think it should be not only a desktop feature, but also multiplatform.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3056">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
