### ISSUE TITLE
No recompose when value to Text changes

### ISSUE THREAD

**Issue by jay-tux** [JetBrains/compose-multiplatform#3058]
**Describe the bug**
(When trying to implement a dropdown using a Text to hold the current value), it seems like the Text isn't updated when the State (`by remember { mutableStateOf(...) }`) changes (done by the menu items, see code below)

**Affected platforms**
Select one of the platforms below:
- Desktop

(only tested on Desktop)

**Versions**
- Kotlin version*: 1.9
- Compose Multiplatform version*: 0.40.1
- OS version(s)* (required for Desktop and iOS issues): `Linux kaya 6.2.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 07 Apr 2023 02:10:43 +0000 x86_64 GNU/Linux` (result of `uname -a`)
- OS architecture (x86 or arm64): x86-64
- JDK (for desktop issues): `java-19-openjdk`

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Click the dropdown to bring up the menu
2. Select a different value

Code for the dropdown:
```kotlin
@Composable
fun SimpleDropdown() {
    val options = listOf("Q", "W", "E", "R", "T", "Y")
    var selected by remember { mutableStateOf(0) }
    var expanded by remember { mutableStateOf(false) }

    Box {
        IconButton(onClick = { expanded = true }) {
            Row {
                Text(options[selected])
                Spacer(Modifier.width(8.dp))
                Icon(
                    imageVector = Icons.Filled.ArrowDropDown,
                    contentDescription = "Show dropdown content"
                )
            }
        }
        DropdownMenu(expanded, { expanded = false }) {
            options.forEachIndexed { idx, item ->
                DropdownMenuItem(onClick = { selected = idx; expanded = false }) {
                    Text(item)
                }
            }
        }
    }
}
```

**Expected behavior**
Upon changing the value by choosing a different one in the dropdown, the related text should change.

**Screenshots**

**Additional context**
Strangely enough, the whole thing works perfectly when using a `TextField` instead (disabled, empty `onValueChange` callback)

**Comment by dima-avdeev-jb** [comment]
This bug is not reproduced on stable Compose 1.4.0 with Kotlin 1.8.20
https://github.com/dima-avdeev-jb/desktop-issue-3058-not-reproduced

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3058">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
