### ISSUE TITLE
iOS onDismissRequest is not used in SkiaBasedOwner

### ISSUE THREAD

**Issue by ANIKINKIRILL** [JetBrains/compose-multiplatform#3059]
**Describe the bug**
For iOS platform onDismissRequest is not used in SkiaBasedOwner. That is why DropdownMenuPopup can not hide.
In previous versions all was fine

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0

**Comment by dima-avdeev-jb** [comment]
Thanks, I will take a look at it.

**Comment by dima-avdeev-jb** [comment]
Can you please provide a sample code to reproduce this bug?

**Comment by MatkovIvan** [comment]
I guess it was solved a while ago, closing

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3059">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
