### ISSUE TITLE
Fatal error signing Mac App

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#3060]
**Describe the bug**

I am building a desktop application. The build works completely fine without signing. With signing, I get the following error:

```
Caused by: org.gradle.api.InvalidUserCodeException: Starting an external process '/usr/bin/security find-certificate -a -c Developer ID Application: <my dev id> <my-keychain-path>' during configuration time is unsupported.
```

**Affected platforms**

Desktop

**Versions**
- Kotlin version*:  1.8.20
- Compose Multiplatform version*: compiler version 1.4.5, plugin version 1.4.0
- OS version: Mac OSX 
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17
- Gradle: 8.1

**To Reproduce**
1. Create a desktop project using the versions above. I suspect the gradle version is the most critical one.
2. In the buildscript, configure the mac app to be signed
3. Execute the build

**Expected behavior**

The build to succeed

**Workaround**

Use `--no-configuration-cache` in the gradle process. However, this prevents using the configuration cache.

**Additional context**

I suspect this issue is related to the latest Gradle version. Gradle has been tightening restrictions related to the configuration cache.

**Comment by dima-avdeev-jb** [comment]
What MacOS version do you have?

**Comment by dima-avdeev-jb** [comment]
Can you please create a minimal reproducible sample on GitHub?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3060">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
