### ISSUE TITLE
When the scaffolding window is maximized on the windows desktop, the left side is all blank

### ISSUE THREAD

**Issue by guwan** [JetBrains/compose-multiplatform#3061]
**Describe the bug**
The start window is like this
![image](https://user-images.githubusercontent.com/5222986/232262320-e16b1ec5-5e73-4dbd-9dea-b568d03ee49f.png)

 when I click to maximize the window, all the left side of him becomes blank
![image](https://user-images.githubusercontent.com/5222986/232262359-14a0dcda-037f-4152-86d2-fa8708546b1d.png)

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): windows 10
- OS architecture (x86 or arm64): 64
- JDK (for desktop issues): 17,kotlin("jvm") version "1.8.20"

**To Reproduce**

@Composable
@Preview
fun App() {

    val scaffoldState = rememberScaffoldState()
    var currentScreen by remember { mutableStateOf(Screen.Home) }
    val coroutineScope = rememberCoroutineScope()
    Scaffold(
        scaffoldState = scaffoldState,
        topBar = {
            TopAppBar(
                title = { Text(text = "title") },
                navigationIcon = {
                    IconButton(onClick = { coroutineScope.launch { scaffoldState.drawerState.open() } }) {
                        Icon(Icons.Default.Menu, contentDescription = "Menu")
                    }
                },
                /*actions = {
                    IconButton(onClick = { */
                /* Handle settings click */
                /* }) {
                                            Icon(Icons.Default.Settings, contentDescription = "Settings")
                                        }
                                    }*/
            )
        },
        drawerContent = {
        },
        content = {
        }
    )

}

**Expected behavior**
A normal window, the left is already hidden

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3061">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
