### ISSUE TITLE
How to use @Preview for Compose Multiplatform with iOS?

### ISSUE THREAD

**Issue by EBfVince** [JetBrains/compose-multiplatform#3063]
This is a question about the development Compose Multiplatform with iOS.

First, I cloned this repository https://github.com/JetBrains/compose-multiplatform-ios-android-template.
Then, I tried to add a preview in the `commonMain` directory. But I quickly realize that `@Preview` annotation is not importable. I tried to add the dependency in the shared `build.gradle.kts` with `implementation(compose.preview)` but I got some Gradle errors when I synced.

Is there a way to use `@Preview` annotations in a Compose Multiplatform with iOS project?

**Comment by dima-avdeev-jb** [comment]
Thanks! It is now working now for iOS and commonMain source sets.
Related Issue already created: https://github.com/JetBrains/compose-multiplatform/issues/2045

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3063">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
