### ISSUE TITLE
exception "...reflect.InvocationTargetException" when using a jsr223 kotlin script to create compose(-multiplatform) UI

### ISSUE THREAD

**Issue by hg42** [JetBrains/compose-multiplatform#3065]
I am not sure if this is not supported (then it would be a feature request) or if this is a bug, or if I am doing something wrong or missing something.
As it seems to be a combination of jsr223 and compose, I could also create the issue there, but I tested with compose-multiplatform, so I put it here...

**Describe the bug**

In a multiplatform project, I am trying to create script plugins, that can create UI elements.

I get such an exception:
```
Exception in thread "AWT-EventQueue-0" java.lang.Error: ??? java.lang.reflect.InvocationTargetException
javax.script.ScriptException: java.lang.reflect.InvocationTargetException
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.asJsr223EvalResult(KotlinJsr223JvmScriptEngineBase.kt:101)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:63)
	at kotlin.script.experimental.jvmhost.jsr223.KotlinJsr223ScriptEngineImpl.compileAndEval(KotlinJsr223ScriptEngineImpl.kt:95)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	at com.hg42.common.Scripting$Companion.runScript(Scripting.kt:31)
	at com.hg42.common.Scripting$Companion.runScript$default(Scripting.kt:27)
	at com.hg42.common.AppKt$ScriptRunner$1$1$2.invoke(App.kt:141)
```

Usually I would return a reference to the function, but we cannot use references to composable functions.

Anyway, it's better to use a class, so I created a Plugin class:

```

data class X(val i: Int = 1, val s: String = "test")

open class Plugin(
    val name: String,
) {
    override fun toString(): String =
        "${javaClass.simpleName}(name = $name)"

    open fun getObject(): Any {
        return X()
    }

    open fun doit(): Unit {}
}
```

which works well, I can use it with getObject or toString.
E.g. I used this script:
```
val testScript = """

package com.hg42.common

import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import com.hg42.common.Plugin

@Composable fun composeFun(): Unit { Text("<test>") }
 
println("test begin")
    
class TestPlugin : Plugin(
    name = "test",
)

val plugin = TestPlugin()

println("test plugin = " + plugin.toString())

plugin

"""
```

I also created a derived class to be used for UI purposes:
```
open class UiPlugin(
    name: String,
    val ui: @Composable () -> Unit = { Text("not initialized") },
) : Plugin(name = name) {
    @Composable
    fun compose() {
        ui()
    }
}
```

To ensure it's working, I also created a test class that is used without script:
```
class NativePlugin : UiPlugin(
        name = "native",
        ui = {
            println("compose NativePlugin ui")
            Text("ui from NativePlugin")
        },
)
```
and it works.

My script looks like this:
```
val uiScript = """

package com.hg42.common

import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import com.hg42.common.UiPlugin

println("script begin")
    
class ScriptPlugin : UiPlugin(
    name = "script",
    ui = @Composable {
        println("compose ScriptPlugin ui")
        Text("ui from ScriptPlugin")
    },
)

val plugin = ScriptPlugin()

println("script = " + plugin.toString())

plugin

"""
```

When I run it, it throws the mentioned exception.

Note, the working test script also has a composable function and doesn't throw an exception.
The exception is thrown when running the script, not when composing.

**Affected platforms**
- Desktop

didn't test Android, yet, because I think it not Android specific, but a problem with the combination Compose + jsr223 scripting.
I guess it's about the hidden code the compiler creates.

**Versions**
- kotlin.version=1.8.20 (also tried 1.8.0 before)
- agp.version=7.4.1
- compose.version=1.4.0 (also 1.3.0)
- runtimeOnly(kotlin("scripting-jsr223"))
- jvm("desktop") {  jvmToolchain(11)  }

**To Reproduce**

1. check out [crossplatform](https://github.com/hg42/crossplatform/) test project
2. run desktop/src/jvmMain/kotlin/Main.kt
3. See error

**Expected behavior**
no crash (or finally the UI created in the script should be shown at the bottom of the window)

**Comment by hg42** [comment]
if I use this script:

```
val uiScript = """

package com.hg42.common

import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import com.hg42.common.UiPlugin

println("script begin")
    
class ScriptPlugin : UiPlugin(
    name = "script",
)

val plugin = ScriptPlugin()

println("script = " + plugin.toString())

plugin

"""
```

and remove the UI from  the UiPlugin:

```
open class UiPlugin(
    name: String,
    val ui: @Composable () -> Unit = { /* Text("not initialized") */ },
) : Plugin(name = name) {
    @Composable
    fun compose() {
        ui()
    }
}
```

so it's basically the same like TestScript above... (even less, because there is no composable function at all), it's still crashing.

if I also exclude the two @Composable parts:
```
open class UiPlugin(
    name: String,
    val ui: /* @Composable */ () -> Unit = { /* Text("not initialized") */ },
) : Plugin(name = name) {
    /* @Composable */
    fun compose() {
        ui()
    }
}
```

it doesn't crash any more.

The crash is caused internally by:

`'void com.hg42.common.UiPlugin.<init>(java.lang.String, kotlin.jvm.functions.Function0, int, kotlin.jvm.internal.DefaultConstructorMarker)'`

with this stack trace:

```
0 = {StackTraceElement@16104} "java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79)"
1 = {StackTraceElement@16105} "java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)"
2 = {StackTraceElement@16106} "java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)"
3 = {StackTraceElement@16107} "kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.evalWithConfigAndOtherScriptsResults(BasicJvmScriptEvaluator.kt:105)"
4 = {StackTraceElement@16108} "kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke$suspendImpl(BasicJvmScriptEvaluator.kt:47)"
5 = {StackTraceElement@16109} "kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke(BasicJvmScriptEvaluator.kt)"
6 = {StackTraceElement@16110} "kotlin.script.experimental.jvmhost.repl.JvmReplEvaluator$eval$1$res$1.invokeSuspend(legacyReplEvaluation.kt:62)"
7 = {StackTraceElement@16111} "kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)"
8 = {StackTraceElement@16112} "kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)"
9 = {StackTraceElement@16113} "kotlin.script.experimental.impl.RunSuspendKt.internalScriptingRunSuspend(runSuspend.kt:19)"
10 = {StackTraceElement@16114} "kotlin.script.experimental.jvmhost.repl.JvmReplEvaluator.eval(legacyReplEvaluation.kt:62)"
11 = {StackTraceElement@16115} "org.jetbrains.kotlin.cli.common.repl.GenericReplCompilingEvaluatorBase.eval(GenericReplCompilingEvaluator.kt:76)"
12 = {StackTraceElement@16116} "org.jetbrains.kotlin.cli.common.repl.GenericReplCompilingEvaluatorBase.compileAndEval(GenericReplCompilingEvaluator.kt:51)"
13 = {StackTraceElement@16117} "org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase$compileAndEval$1.invoke(KotlinJsr223JvmScriptEngineBase.kt:64)"
14 = {StackTraceElement@16118} "org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase$compileAndEval$1.invoke(KotlinJsr223JvmScriptEngineBase.kt:63)"
15 = {StackTraceElement@16119} "org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.asJsr223EvalResult(KotlinJsr223JvmScriptEngineBase.kt:90)"
16 = {StackTraceElement@16120} "org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:63)"
17 = {StackTraceElement@16121} "kotlin.script.experimental.jvmhost.jsr223.KotlinJsr223ScriptEngineImpl.compileAndEval(KotlinJsr223ScriptEngineImpl.kt:95)"
18 = {StackTraceElement@16122} "org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)"
19 = {StackTraceElement@16123} "java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)"
20 = {StackTraceElement@16124} "com.hg42.common.Scripting$Companion.runScript(Scripting.kt:31)"
```

indeed the `target` field doe not exist:

![image](https://user-images.githubusercontent.com/4707597/232539061-f1fc45af-39f0-42fb-9986-44de74da6a61.png)

**Comment by hg42** [comment]
* updated the sample repository to kotlin 1.8.20 and compose 1.4.0
* reduced the crashing script to a minimum as described above
* made it automatically crash (no more button press necessary)

**Comment by dima-avdeev-jb** [comment]
I don't see your project https://github.com/hg42/crossplatform/
Maybe access is private

**Comment by hg42** [comment]
oh, sorry, should be fixed now.
I created it directly from the IDE for the first time... looks like that's the default

**Comment by dima-avdeev-jb** [comment]
Thanks, project is public now!

**Comment by dima-avdeev-jb** [comment]
Checked!
You are right.
Composable functions can't be used inside a dynamically loaded script.
```@Composable fun composeFun(): Unit { Text("<test>") }```
Because Composable needs a special Compiler plugin that transforms it to another function with additional arguments.
We can't implement this feature yet.

**Comment by hg42** [comment]
ok, it may be that it's not possible at the m8ment.

However, it looks like this doesn't fully explain what happens:

1. The function *can* be compiled without error (even it may not work), as you see in the first test plugin, where I added such a composable function

2. it's never invoked in the test that fails, instead it does not compile

may be it's because the resulting function is different in the base class and the derived class in the script? but it's another error. Or is it because the constructor is called? I will try later...

The other question coming to mind is, if it's possible to use the compose plugin in the script? or why not?

**Comment by dima-avdeev-jb** [comment]
> The other question coming to mind is, if it's possible to use the compose plugin in the script?

It is an interesting question. For now, it is not possible because we don't have such an API. But in the future, it is a good feature for scripting to support it. (I don't know is it possible or not)

**Comment by hg42** [comment]
thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3065">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
