### ISSUE TITLE
Draw Text on Canvas

### ISSUE THREAD

**Issue by allonmj** [JetBrains/compose-multiplatform#307]
There's currently no way to draw text onto a Canvas. I can see that internally the Text() function is using the native canvas to draw text, but there's no way that I can see of doing it on my own.

**Comment by jimgoog** [comment]
The MPP canvas API is limited by whatever is available in the Android Canvas API.  Please feel free to file a bug against Compose upstream (https://issuetracker.google.com/issues/new?component=612128) and link the bug here in this thread.

**Comment by ynsok** [comment]
any update?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6123">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
