### ISSUE TITLE
iosApp run configuration not found

### ISSUE THREAD

**Issue by sedubois** [JetBrains/compose-multiplatform#3070]
**Describe the bug**
I cloned https://github.com/JetBrains/compose-multiplatform-ios-android-template/tree/dde60620de9f8e3ba4d82e08141712a467af5d86 and tried to run the demo on an iOS simulator from Android Studio as the README says. However, Android Studio does not show any iosApp run configuration and no option is available to create one.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: `kotlin.version=1.8.20`
- Compose Multiplatform version*: `compose.version=1.4.0`
- OS version(s)* (required for Desktop and iOS issues): macOS Ventura 13.3.1
- OS architecture (x86 or arm64): Apple M2 - arm64
- Android Studio Flamingo | 2022.2.1

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. unzip https://github.com/JetBrains/compose-multiplatform-ios-android-template/archive/dde60620de9f8e3ba4d82e08141712a467af5d86.zip
2. Open directory in Android Studio
3. NB: there are warnings, see screenshot below
4. As per the screenshots, there is no iosApp run configuration

**Expected behavior**
It should be possible to run the iosApp in an iOS simulator from Android Studio.

**Screenshots**

![Screenshot 2023-04-18 at 09 47 26](https://user-images.githubusercontent.com/4217871/232708460-99bd0061-670e-47f4-83e7-c8c602b2b289.png)

![Screenshot 2023-04-18 at 09 50 26](https://user-images.githubusercontent.com/4217871/232709169-06fcbc2f-5330-4871-bc23-48e7b29aa3b9.png)

![Screenshot 2023-04-18 at 09 50 39](https://user-images.githubusercontent.com/4217871/232709184-8351da9b-c370-4b56-8448-88388a27f27d.png)

![Screenshot 2023-04-18 at 09 58 04](https://user-images.githubusercontent.com/4217871/232711023-c1de9142-f21b-4cca-9004-56388154c610.png)

**Comment by eymar** [comment]
Do you have the latest KMM plugin installed in your Android Studio?

<img width="761" alt="Screenshot 2023-04-19 at 11 22 51" src="https://user-images.githubusercontent.com/7372778/233031027-a0b3c58c-4f6d-4125-a752-65eb289b8326.png">

**Comment by sedubois** [comment]
Thank you @eymar, sorry that I missed that item in the README. It would be nice if kdoctor could check that.

After installing the plugin "Kotlin Multiplatform Mobile" (v 4.22) I can start the app in the iPhone 14 simulator.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3070">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
