### ISSUE TITLE
CfW: caught RuntimeError: remainder by zero at skiko.wasm:0x28a295

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-multiplatform#3072]
**Describe the bug**
`caught RuntimeError: remainder by zero at skiko.wasm:0x28a295`

From slack: https://kotlinlang.slack.com/archives/C01F2HV7868/p1681770975118669
> I've managed to trace down one cause of this to a rather specific shadow modifier:
> .shadow(elevation = 2.dp, shape = RoundedCornerShape(topStart = 28.dp, topEnd = 28.dp))
> Different elevation values don't trigger the crash. However, different shape values do. For example, this runs without an issue:
> .shadow(elevation = 2.dp, shape = RoundedCornerShape(8.dp))

**Affected platforms**
Select one of the platforms below:
- Web 

**Versions**
- Kotlin version*:  1.8.20
- Compose Multiplatform version*:  1.4.0 or earlier

**To Reproduce**
[Steps and/or the code snippet to reproduce the behavior:
2. Click on '...'
3. Scroll down to '...'
4. See error](https://github.com/JetBrains/compose-multiplatform-core/blob/30150346d8c4c04c6a17e537a9c0a1f259aa2b8e/compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/RoundedCornerCrashOnJS.kt#L36)

**Expected behavior**
It should work. Same as on other platforms.

**Comment by alexzhirkevich** [comment]
`RoundedCornerShape(topStart = 28.dp, topEnd = 28.dp)` causes runtime error cause `bottomLeft` and `bottomRight` values are `0.dp` by default (#3013). 
`RoundedCornerShape(8.dp)` runs without an issue cause all corners are `8.dp` in this case.

**Comment by eymar** [comment]
Thanks! I somehow missed that we already have this issue reported.
I close this one as duplicate of - https://github.com/JetBrains/compose-multiplatform/issues/3013

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3072">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
