### ISSUE TITLE
iOS Resources without CocoaPods

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#3073]
Ability to use org.jetbrains.compose.resources.painterResource without requiring CocoaPods.
Related to https://github.com/JetBrains/compose-multiplatform/issues/3066

**Comment by raghavpai** [comment]
This feature will be a game changer

**Comment by ronjunevaldoz** [comment]
I thought I was the only one encountered this issue

**Comment by dima-avdeev-jb** [comment]
@mpierucci Can you please create a minimal reproducible sample project on GitHub?
Also - you can try to create a project with [new wizard](https://kmp.jetbrains.com/) and compare gradle files with your own project.

**Comment by mpierucci** [comment]
Hey @dima-avdeev-jb  Thanks for the reply. I was able to get a minimal reproducer based on the new wizard but mimicking our set up closely.
The App runs well on Android but fails on iOS simulator with the above-mentioned error 
[You can find the reproducer here](https://github.com/mpierucci/ComposeMPResourcesIssue)

**Comment by terrakok** [comment]
The issue fixed long time ago. Check the [documentation](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html) carefully: multimodule projects are not supported yet. Your reproducer has two modules, am I right?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3073">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
