### ISSUE TITLE
TextLayoutResult#isLineEllipsized always returns false

### ISSUE THREAD

**Issue by fornewid** [JetBrains/compose-multiplatform#3074]
**Describe the bug**
Currently I'm working on [ReadMoreTextView](https://github.com/webtoon/ReadMoreTextView) library to support Compose Multiplatform. (https://github.com/webtoon/ReadMoreTextView/pull/60)

But I have an issue on `Text` composables.
When `TextLayoutResult` is received through `onTextLayout` of `CoreText`,
**[`TextLayoutResult#isLineEllipsized`](https://github.com/JetBrains/compose-multiplatform-core/blob/d4b2366ba56e8cafa7ce5b2e31c9e2b98c0d62cb/compose/ui/ui-text/src/commonMain/kotlin/androidx/compose/ui/text/TextLayoutResult.kt#L412) always returns false.**

Please let me know, if I should report this bug in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128).

**Affected platforms**
Select one of the platforms below:
- Desktop
  (working on Android perfectly)

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): macOS Ventura
- OS architecture (x86 or arm64): arm64 (Apple M1 Pro)
- JDK (for desktop issues): JDK 11

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

```kt
BasicText(
    text = currentText,
    modifier = Modifier,
    style = style,
    onTextLayout = { result ->
        result.isLineEllipsized(lineIndex = 3) // always returns false
    },
    overflow = TextOverflow.Ellipsis,
    maxLines = 3,
)
```

**Expected behavior**
If `currentText` exceeds `maxLines` and `currentText` is ellipsized, `result.isLineEllipsized()` should return `true`.

**Screenshots**

**Additional context**

**Comment by eymar** [comment]
Reproduced:

```kotlin
@Composable
@Preview
fun App() {
    var currentText: String by remember { mutableStateOf("") }

    Column {
        BasicText(
            text = currentText,
            modifier = Modifier.width(100.dp),
            onTextLayout = { result ->
                val lastLine = result.lineCount - 1
                val isEllipsized = result.isLineEllipsized(lineIndex = lastLine) // always returns false
                println("isEllipsized($lastLine) = $isEllipsized")
            },
            overflow = TextOverflow.Ellipsis,
            maxLines = 3,
        )

        TextField(currentText, onValueChange = { currentText = it })
    }
}
```

<img width="391" alt="Screenshot 2023-04-19 at 11 54 46" src="https://user-images.githubusercontent.com/7372778/233038994-92950b61-bf8a-4eea-a0d9-e2ce6c9fec88.png">

**Comment by AntonButov** [comment]
@fornewid 

> 
> Please let me know, if I should report this bug in the 
> 

Hi, I found problem in:
> ```kotlin
> androidx.compose.ui.text.SkiaParagraph.skiko.kt
>
> override fun isLineEllipsized(lineIndex: Int) = false
>```
This class responses for desktop realisation. Obviosly, the result, which you wait always returns false. You should report about the bug.

**Comment by fornewid** [comment]
@AntonButov 
Yes, that's right.

However, only the android library is published in Jetpack Compose.
So I thought the `SkiaParagraph.skiko.kt` code should be modified in [compose-multiplatform-core](https://github.com/JetBrains/compose-multiplatform-core) project.

Did I think wrong?

**Comment by AntonButov** [comment]
[compose-multiplatform-core](https://github.com/JetBrains/compose-multiplatform-core) is fork of JetPack Compose. 
Yes, it's really strange why the desktop implementation placed in Android's Jatpack and called AndroidX. 
But I am sure that AndroidParagraph.android.kt::isLineEllipsized works when launching the Android application. Work good. The desktop application uses SkiaParagraph.skiko.kt::isLineEllipsized. Work bad. Both of these classes resolve [interface](https://github.com/androidx/androidx/blob/35a30ac13331b270f0609319465013671de9651a/compose/ui/ui-text/src/skikoMain/kotlin/androidx/compose/ui/text/Paragraph.skiko.kt#L34). 
Perhaps androidx is not being renamed becouse not to break compatibility.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3074">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
