### ISSUE TITLE
How to force pointer movement to a given x, y coordinates?

### ISSUE THREAD

**Issue by jeancsanchez** [JetBrains/compose-multiplatform#3078]

**Comment by eymar** [comment]
Could you elaborate please? What are you trying to achieve and on what platform?

Do you want to move the cursor with Compose for Desktop from code?

**Comment by jeancsanchez** [comment]
@eymar Exactly. I want to move the mouse cursor with Compose for Desktop from the code. The Android module will send the coordinates to the Desktop application and move the cursor.

**Comment by m-sasha** [comment]
@jeancsanchez This is outside of the scope of Compose, but you can try using the AWT Robot API: https://docs.oracle.com/javase/7/docs/api/java/awt/Robot.html

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3078">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
