### ISSUE TITLE
How does the Image display webp animation?

### ISSUE THREAD

**Issue by Adiudiu** [JetBrains/compose-multiplatform#3082]

**Comment by eymar** [comment]
I tried to use an animated webp in Compose for Desktop and it simply shows the static image, without an animation.

As for Jetpack Compose (android), it seems animated webps are not supported out of a box either. But some suggest to try  Coil lib https://coil-kt.github.io/coil/compose/ (it's not available in Compose Multiplatform though, so andorid only)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3082">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
