### ISSUE TITLE
`linkDebugFrameworkIosSimulatorArm64` failures with "Module ... has a reference to symbol ... CompositionLocalProvider ... Neither the module itself nor its dependencies contain such declaration."

### ISSUE THREAD

**Issue by ZacSweers** [JetBrains/compose-multiplatform#3088]
**Describe the bug**
When trying to use an `iosSimulatorArm64` target with 1.4.0, I see the following error at build time

```
> Task :samples:counter:linkDebugFrameworkIosSimulatorArm64 FAILED
error: Module "org.jetbrains.compose.ui:ui" has a reference to symbol androidx.compose.runtime/CompositionLocalProvider|-195475592741065473[0]. Neither the module itself nor its dependencies contain such declaration.
```

Followed by a long list of printed dependencies ([errorlog.txt](https://github.com/JetBrains/compose-multiplatform/files/11304251/errorlog.txt)). I don't really know what to do about this issue or why it's happening.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): macOS Ventura 13.3.1 (22E261)
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 19

**To Reproduce**
Clone this PR and run `./gradlew :samples:counter:linkDebugFrameworkIosSimulatorArm64`

https://github.com/slackhq/circuit/pull/583

**Expected behavior**
I expect this to work without build failures, or at least give a meaningful explanation of what is wrong and how to fix it.

**Screenshots**
N/A

**Additional context**
Available in kotlin-lang if you have any other questions!

**Comment by eymar** [comment]
While I was able to reproduce the error, I have some questions:

`samples:counter` builds.gradle.kts doesn't use `id("org.jetbrains.compose")` plugin:
```
plugins {
  kotlin("multiplatform")
  kotlin("native.cocoapods")
  id("com.android.library")
}
```
It is a bit suspicious. Could it be that some modules in your project use different compose compiler plugins?
There're two compiler plugins: published by Jetpack Compose (supports android and desktop jvm), and another one for Compose Multiplatform -  https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/compiler/ (1.4.5 is the latest version)
The second one supports android, destkop, k/native (ios), k/js. 
The gradle plugin `id("org.jetbrains.compose")` enables the Compose Multiplatform compiler plugin implicitly. It chooses the right version automatically depending on the kotlin version (1.8.20 is the latest supported). 

I tried to add `id("org.jetbrains.compose")`, but than some other similar error popped up in some other module, so I guess the project needs to use id("org.jetbrains.compose") in all modules. 

I hope the above helps.

**Comment by eymar** [comment]
Both multiplatform and compose gradle plugins have to be applied to use Compose Multiplatform.

**Comment by MessiasLima** [comment]
Im having the same issue. In my case, All modules have `id("org.jetbrains.compose")`. Basically I have copied the same settings from [compose-multiplatform-ios-android-template](https://github.com/JetBrains/compose-multiplatform-ios-android-template) and got the same error

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3088">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
