### ISSUE TITLE
TextFields cursor changes its position while typing/deleting text

### ISSUE THREAD

**Issue by aivanovski** [JetBrains/compose-multiplatform#3089]
**Describe the bug**
While typing text in `OutlinedTextField` sometimes cursor is moved from end to somewhere in the middle, what leads to incorrectly typed text inside `OutlinedTextField`. For example, when type "Hello" I usually have something like "Hlloe", because after I typed "He" cursor was moved from the end to the middle, then after other part of the word is typed the result will be "Hlloe".
Simillar problem happens while deleting text from `OutlinedTextField`.

**Important:** This bug happens only if TextField state is handled by `MutableStateFlow`. TextField works fine if its state is handled with `remember { mutableStateOf("") }`

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.7.20
- Coroutines version: 1.7.0-RC or lower
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Linux
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): openJDK 17

**To Reproduce**
1. Write and launch this code
```
class ScreenViewModel {
    val text = MutableStateFlow("")
}

@Composable
fun Test(viewModel: ScreenViewModel) {
    val text = viewModel.text.collectAsState(initial = "")

    OutlinedTextField(
        value = text.value,
        onValueChange = { viewModel.text.value = it }
    )
}
```
2. Type "Hello"
3. Check text in `OutlinedTextField`

**Comment by m-sasha** [comment]
See https://medium.com/androiddevelopers/effective-state-management-for-textfield-in-compose-d6e5b070fbe5 for a discussion of the problem.

**Comment by aivanovski** [comment]
Looks like this code fixes the issue:
```
val text = viewModel.text.collectAsState(
    context = Dispatchers.Main.immediate
)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3089">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
