### ISSUE TITLE
Rollback redundant workaround after Kotlin 1.9.0

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#3090]
Rollback redundant workaround from
https://github.com/JetBrains/compose-multiplatform-core/pull/522
https://github.com/JetBrains/compose-multiplatform-core/pull/297

after Kotlin 1.9.0 will be added to Compose

And check examples in mpp/demo project:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/99798741/234053098-4588802d-cf67-4527-95af-1e3c9ed501e9.png">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3090">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
