### ISSUE TITLE
Video driver reboots on first Toolbox open

### ISSUE THREAD

**Issue by Walingar** [JetBrains/compose-multiplatform#3091]
**Describe the bug**
From time to time, on a first attempt to open Toolbox app, display becomes black (seems like video driver reboots) and then everything works fine. Not reproducible 100%.

**Affected platforms**
- Desktop

**Versions**
* Windows 10
* Toolbox version: 1.28.0.15062
* CPU: Ryzen 7 5800x3d (never happened with Ryzen 3700x before)
* GPU: Nvidia RTX 2700S
* Display: One monitor — LG 27gl850 via DisplayPort

**To Reproduce**
Try to open Toolbox app on the setup

**Discussions**
Related discussion in [internal slack](https://jetbrains.slack.com/archives/C01G87BMA2Z/p1681894290505579)

**Comment by eymar** [comment]
https://youtrack.jetbrains.com/issue/TBX-6693/Opening-Jetbrains-Toolbox-causes-monitor-to-go-black-flicker - could be related

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3091">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
