### ISSUE TITLE
Cross-platform resources: Support different pixel densities / scale factors for images

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#3092]
Cross-platform resources should be able to select from a range of different resolutions for the same asset – e.g. `foo.png`, `foo@2x.png` / `drawable/xxhdpi`, `drawable/ldpi`.

Further reading: 
- https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp
- https://developer.apple.com/design/human-interface-guidelines/foundations/images/#scale-factors

**Comment by aplha98** [comment]
.

**Comment by igordmn** [comment]
Resources by density will be available in 1.6.0

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3092">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
