### ISSUE TITLE
Bad quality of icon in the titlebar of the window

### ISSUE THREAD

**Issue by rukins** [JetBrains/compose-multiplatform#3093]
When i set an image on Window it has a bad quality, though the real quality is good. I follow [this guide](https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Image_And_Icons_Manipulations), use *painterResource("sample.png")*

If i set the image using 
```
Image(
    painter = painterResource("sample.png"),
    contentDescription = "Icon",
    modifier = Modifier.fillMaxSize()
)
```
it looks good

![Screenshot from 2023-04-24 17-08-57](https://user-images.githubusercontent.com/78296949/233991875-b1bedf3a-27b9-4d9f-862c-309b7cbed100.png)

My OS: Fedora Linux

**Comment by rukins** [comment]
@eymar, yes, it works, the image has good quality, but it sets image only 
![Screenshot from 2023-04-24 18-47-47](https://user-images.githubusercontent.com/78296949/234016206-1742ab33-36cc-4443-9268-96f2a8216715.png)

**Comment by rukins** [comment]
Here. And it runs as separate application

![Screenshot from 2023-04-24 19-25-39](https://user-images.githubusercontent.com/78296949/234026557-8493f4cd-2663-4a9c-b979-a747803b585e.png)

**Comment by MessiasLima** [comment]
I'm having the same problem.
I'm using Ubuntu LTS

**Comment by AzimMuradov** [comment]
Having similar (?) issues with 16 bit PNG images. Is there are any way to control [filter quality](https://developer.android.com/reference/kotlin/androidx/compose/ui/graphics/FilterQuality) of painter resources?

**Comment by QiXi** [comment]
Similar issue in Ubuntu 22.04.2 LTS. I determined that regardless of the original resolution, the icon is always 32 pixels, if the system is set to 48px, then the icon of the KMM application is severely distorted.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3093">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
