### ISSUE TITLE
iOS TextField issues with RTL text editing

### ISSUE THREAD

**Issue by etolstoy** [JetBrains/compose-multiplatform#3096]
There are some issues with handling the RTL text. Sample code:

```kotlin
CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl ) {
    TextField(
        value = text,
        onValueChange = {
            text = it
        }
    )
}
```

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0

**To Reproduce**
Bug #1: Type a word. Than press space. In RTL mode the caret jumps to the beginning of the line and a whitespace appears before the actual content. If you continue typing something other than whitespaces, the caret returns to its original position.

![rtl-bug](https://user-images.githubusercontent.com/3955262/234049928-ece812ab-eae3-4d1e-841f-ca680dddba09.gif)

Bug #2: Selection handles behave very weird, both in the whitespace case from bug #1, with other pieces of RTL text and when you try to select all.

![photo_2023-04-24 16 51 38 (1)](https://user-images.githubusercontent.com/3955262/234050013-85f1c8b9-2a88-4308-a9c9-4a32dfa36f79.jpeg)
![photo_2023-04-24 16 51 38](https://user-images.githubusercontent.com/3955262/234050018-279cd2c6-da2c-45d2-8e0f-62165010057d.jpeg)
![photo_2023-04-24 16 51 37](https://user-images.githubusercontent.com/3955262/234050023-36fd2372-74ce-4414-9ca4-85826b3bcf1d.jpeg)
![photo_2023-04-24 16 51 36](https://user-images.githubusercontent.com/3955262/234050025-010e7efe-9530-4f00-8408-b3baa636ad3c.jpeg)

Related issues:
 - https://github.com/JetBrains/compose-multiplatform/issues/3997
 - https://github.com/JetBrains/compose-multiplatform/issues/2831
 - https://github.com/JetBrains/compose-multiplatform/issues/2772

**Comment by hfeky** [comment]
This issue also occurs on Desktop.

**Comment by hfeky** [comment]
RTL text support in Compose has many issues. These are also 2 other RTL text issues.

- https://github.com/JetBrains/compose-multiplatform/issues/2772
- https://github.com/JetBrains/compose-multiplatform/issues/2831

**Comment by dima-avdeev-jb** [comment]
Related to: https://github.com/JetBrains/compose-multiplatform/issues/2831

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3096">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
