### ISSUE TITLE
iOS TextField issues with Center and Right text alignment

### ISSUE THREAD

**Issue by etolstoy** [JetBrains/compose-multiplatform#3098]
**Describe the bug**
There are some bugs with `Center` or `Right` text alignment on iOS. Sample code:

```kotlin
TextField(
        value = text,
        onValueChange = {
            text = it
        },
        textStyle = LocalTextStyle.current.copy(textAlign = TextAlign.Right),
    )
```

Bug #1: In empty TextField the caret is placed always on the left side, and doesn't respect text alignment. Same happens with each new line.

https://user-images.githubusercontent.com/3955262/234054834-da28e67a-c3a8-4059-82ef-7ed654a13352.mov

Bug #2: With `Right` layout a whitespaces after a symbol aren't displayed until a next symbol is entered. It works fine with `Left` and `Center` layouts.

https://user-images.githubusercontent.com/3955262/234055764-59bbfbde-97f0-48de-a437-dd8a752c1bf2.mov

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0

**Comment by mazunin-v-jb** [comment]
@dima-avdeev-jb checked on Android as requested:
1) caret is being showed according to TextField's text alignment
2) whitespace after word is showing correctly on right text alignment

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3098">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
