### ISSUE TITLE
Scrolling on both y & x axises is not possible at the same time on compose v1.4.0, but possible in v.1.3.1 and 1.2.2

### ISSUE THREAD

**Issue by NuruNabiyev** [JetBrains/compose-multiplatform#3099]
**Describe the bug**
I noticed a regression in compose-multiplatform 1.4.0 related to scrolls on both the x and y axes. I have a modifier with scrollable arguments. In compose versions 1.2.2 & 1.3.1 I was able to use my touchpad to scroll in both directions simultaneously, but in 1.4.0 it is not possible anymore - only 1 direction at a time.

For slack thread: https://kotlinlang.slack.com/archives/C01D6HTPATV/p1682269433928629

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues):  MacOS Monterey v 12.6.5 (21G531)
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): JDK 15 (azul)

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Run the following compose in your main
```
@Composable
fun test() {
    var offsetX by remember { mutableStateOf(0f) }
    var offsetY by remember { mutableStateOf(0f) }

    // background
    Box(
        Modifier.fillMaxSize()
            .background(Color.LightGray)
            .scrollable(
                state = ScrollableState {
                    offsetY += it
                    it
                },
                orientation = Orientation.Vertical
            )
            .scrollable(
                state = ScrollableState {
                    offsetX += it
                    it
                },
                orientation = Orientation.Horizontal
            )
    ) {
        // scrollable box
        Box(Modifier
            .requiredSize(200.dp)
            .offset {
                IntOffset(offsetX.roundToInt(), offsetY.roundToInt())
            }
            .background(Color.Blue)
        ) {

        }
    }
}
```
2. Try to use touchpad to scroll in both directions (e.g. diagonally). In compose v1.3.1 you can but in v.1.4.0. you can do it only in one direction, so scrolling becomes jiggish

**Expected behavior**
Should scroll the canvas/box diagonally

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3099">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
