### ISSUE TITLE
Uneven border width when using `RoundedCornerShape`

### ISSUE THREAD

**Issue by ragunathjawahar** [JetBrains/compose-multiplatform#310]
<img width="912" alt="Screenshot 2021-01-23 at 1 52 14 PM" src="https://user-images.githubusercontent.com/1141970/105573275-5f3e9280-5d82-11eb-9983-492215eabf81.png">

**Example**
```kotlin
fun main() = Window {
  Box(
    modifier = Modifier
      .padding(16.dp)
      .preferredWidth(40.dp)
      .preferredHeight(40.dp)
      .background(color = Color.White)
      .border(2.dp, Color.Red, shape = RoundedCornerShape(20.dp))
  )
}
```

**Comment by olonho** [comment]
Could you please clarify, what is expected result here?

**Comment by ragunathjawahar** [comment]
The entire circle border should have the same width. If you look closely, the top half looks uniform but the bottom half does not.

**Comment by olonho** [comment]
Indeed, it's somewhat distorted. Is Android behavior the same?

**Comment by igordmn** [comment]
Same on Android

```
            Box(
                modifier = Modifier
                    .padding(16.dp)
                    .width(300.dp)
                    .height(300.dp)
                    .background(color = Color.White)
                    .border(20.dp, Color.Red, shape = RoundedCornerShape(150.dp))
            )
```
![image](https://user-images.githubusercontent.com/5963351/105679773-f7ae5180-5eff-11eb-9265-6b8d53b5b84b.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6382">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
