### ISSUE TITLE
Application doesn't respond to touch events in split window mode on iPad

### ISSUE THREAD

**Issue by etolstoy** [JetBrains/compose-multiplatform#3100]
**Describe the bug**
When the application is being run in a split view mode in iPad, it responds to touches only when being launched in the left pane. When it's dragged to the right pane, it stops responding. Though if a physical keyboard is connected, it doesn't loose focus and you can continue typing.

https://user-images.githubusercontent.com/3955262/234070381-fff90c58-81aa-4078-a178-5b09c9966012.MOV

**Affected platforms**
- iOS (iPad only)

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): iPadOS 16.1.1

**To Reproduce**
1. Launch the Compose app.
2. Run it in a split view with another app.
3. Drag Compose app to the right pane.

**Comment by paxbun** [comment]
Same thing happens when the app is launched in full-screen mode and then switched into a slide over window.

**Comment by paxbun** [comment]
It seems like Compose always assumes that the window is at (0, 0). The left split view works well and on the left slide over mode, the buttons that are slightly off from the touch position are pressed.

**Comment by paxbun** [comment]
Would this line be the culprit? I think it should be `touch.locationInView(this)`, not `null`.
https://github.com/JetBrains/skiko/blob/39fb88f6a22bdd20f1cd82e3719b005885ca3648/skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt#L228

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3100">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
