### ISSUE TITLE
iOS TextField, text selection with a physical keyboard doesn't show handles on iPad

### ISSUE THREAD

**Issue by etolstoy** [JetBrains/compose-multiplatform#3102]
**Describe the bug**
You can select some piece of text in `TextField` using Shift + arrows. However, if you do so, it gets selected without showing any handles, so you can't expand the selection scope using touchscreen. Native `UITextField` shows handles with such type of selection.

![telegram-cloud-photo-size-2-5346286496363170801-x](https://user-images.githubusercontent.com/3955262/234071342-9ff44512-fab1-490a-82ee-6048ca8dc7e3.jpg)

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): iPadOS 16.1.1

**Comment by etolstoy** [comment]
Still reproduces on `1.5.0-beta01`

**Comment by mazunin-v-jb** [comment]
[Asked Google here](https://partnerissuetracker.corp.google.com/issues/295368404) because the fix will affect common code, and in Textfield2 there is no such problem. Either they'll fix that themselves or we'll need to coordinate our work with textfields.

**Comment by mazunin-v-jb** [comment]
upd. Google answered that they are planning to fix it by themselves. I'll leave this issue open for now, we need to check that later.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3102">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
