### ISSUE TITLE
iOS TextField, Duplication of backspace and newline in TextField using a physical keyboard.

### ISSUE THREAD

**Issue by etolstoy** [JetBrains/compose-multiplatform#3103]
**Describe the bug**
When you use a physical keyboard to type some text in `TextField`, it duplicates all backspace and newline events.

https://user-images.githubusercontent.com/3955262/234072500-17ba4a1b-2df7-4e8d-9671-b9e944e77e3c.MP4

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0

**Also reproduced with simulator**

**Comment by MohamedRejeb** [comment]
The same issue is happening using the iOS simulator

**Comment by dima-avdeev-jb** [comment]
Related to:
 - https://github.com/JetBrains/compose-multiplatform/issues/2987

**Comment by dima-avdeev-jb** [comment]
Take a look at:
 - https://github.com/JetBrains/compose-multiplatform/issues/3242

**Comment by paxbun** [comment]
I think JetBrains/compose-multiplatform-core#699 fixed this; could you please double-check this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3103">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
