### ISSUE TITLE
Add my Compose Multiplatform application to SendTo menu in Windows

### ISSUE THREAD

**Issue by bartwell** [JetBrains/compose-multiplatform#3106]
I have a cross-platform application created using Compose Multiplatform. I need to add it to SendTo menu (this menu is available in Windows Explorer when user right-clicked a file).

I've tried to find any options to implement it using Gradle. But there is no special options in nativeDistributions/windows.

Is it possible to add option to create shortcut in Windows SendTo directory for MSI/EXE installers?

**Comment by m-sasha** [comment]
This is not currently in the scope of Compose for Desktop. If something like that exists, it's probably a library for the JVM wrapping some native code.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3106">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
