### ISSUE TITLE
TextField, Tab characters displaying as spaces in multiline TextField

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#3112]
**Describe the bug**

Tab characters are displaying as spaces in `TextField`. This is occuring whether or not the TextField is inside of a `MaterialTheme` Block. While using `MaterialTheme`, I have found that tabs look idential to spaces for all `FontFamily` instances except for `FontFamily.Cursive`. I have also tried loading system fonts on Desktop, and the same issue occured.

**Affected platforms**

I am only using Android and Desktop (Mac) and it is occuring on both.

**Versions**
- Kotlin version*:  1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Mac OSX 13.3.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a multiline `TextField`
2. Type some text in it, including some tab characters
3. Observe that the tab characters look like spaces.

**Expected behavior**
I expected the tab character to display as multiple spaces, consistent with most text editors. It would be ideal if we could programmatically control the width of the tab character.

**Comment by dima-avdeev-jb** [comment]
Characters visualisation depends on font.
But, also you can apply visual transform to a TextField. Please take a look at sample project here: https://github.com/dima-avdeev-jb/issue-tab-as-spaces

If something goes wrong, feel free to reopen this issue and ask more questions

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3112">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
