### ISSUE TITLE
Create a list of community-driven samples

### ISSUE THREAD

**Issue by gleb-skobinsky** [JetBrains/compose-multiplatform#3115]
It might be a great idea to create and maintain a list of example Compose Multiplatform projects in addition to the official samples. While building an excersise-like [chat app](https://github.com/gleb-skobinsky/compose-connect) with Compose to improve my experience, I felt that it would be nice to have many repos where I could look for solutions of some rare use-cases and widgets.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3115">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
