### ISSUE TITLE
iOS TextField, Add support for keyboardOptions in iOS

### ISSUE THREAD

**Issue by alexzaitsev** [JetBrains/compose-multiplatform#3116]
Right now if to set `keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number)` to `TextField` it works for Android but is ignored for iOS. 
Android:
<img width="400" src="https://user-images.githubusercontent.com/2372414/235396673-2d00afcd-adfd-4366-b102-84e26c104d9f.png"/>
iOS:
<img width="400" src="https://user-images.githubusercontent.com/2372414/235396683-635445e2-5fd0-4ae8-ab3b-0ad2bdb083d1.png"/>

**Comment by mazunin-v-jb** [comment]
The fix for that will be available in the next release of Compose Multiplatform 1.5.0 (was fixed in the related issue #2735)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3116">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
