### ISSUE TITLE
DesktopComposeTestRule.waitForIdle() can return even though the compose state isn't idle

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#3117]
**Describe the bug**

Because of GlobalSnapshotManager calling `Snapshot.sendApplyNotifications()` which immediately advances the snapshot but takes some time to send the notifications, `DesktopComposeTestRule.isIdle()` can return false before the apply notifications have been sent (`Snapshot.current.hasPendingChanges()` already returns false but `scene.hasInvalidations()` still returns false).

**Versions**
- Compose Multiplatform version: 1.4.x

**To Reproduce**
```
    @Test
    fun idleIsReallyIdle() = repeat(300){
        val globalValue = AtomicInteger()
        rule.setContent {
            var localValue by remember{ mutableStateOf(0) }

            remember(localValue) {
                globalValue.set(localValue)
            }

            Layout(
                {},
                Modifier.size(50.dp),
                measurePolicy = { _, constraints ->
                    localValue = 100
                    layout(constraints.maxWidth, constraints.maxHeight) {}
                }
            )
        }

        assertEquals(100, globalValue.get())
    }
```

**Expected behavior**
`rule.setContent` calls `waitForIdle` before returning, therefore `globalValue` should be 100 when that happens. In reality, it ends up remaining 0 every once in a while (hence the `repeat(300)`.

**Additional context**
A solution suggested by Chuck from Google, which we're working on, is to add a counter of "current callers inside `Snapshot.advanceGlobalSnapshot`" which would allow `isIdle()` to detect the transitional state when the apply notifications haven't been sent yet.

**Comment by m-sasha** [comment]
Note that Android has a completely different way of implementing `isIdle()` - it appears to check there are no tasks scheduled on the main looper.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3117">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
