### ISSUE TITLE
UIKit views disappear if their factory lambda recreates

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#3119]
**Describe the bug**

<strike>UIKit views disappear if their update action mutates a remembered object.</strike>
UIKit views disappear if their factory lambda recreates. 

- <i>It may happen if this lambda have a reference to a remembered object.</i>

❗️<b>Workaround: </b> remember factory lambda
 ```kotlin
val factory = remember {
    { UITextField()  }
} 

UIKitView(
    factory = factory
)
```
**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0

**To Reproduce**

```kotlin

class SomeObject {

    private var counter  = 0

    fun mutate(){
        counter++
    }
}

val someGlobalObject = SomeObject()

fun MainViewController() = ComposeUIViewController {

    val someRememberedObject = remember {
        SomeObject()
    }

    var text by remember {
        mutableStateOf("some text")
    }

    Column(
        Modifier.fillMaxSize(),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {

        ComposeUITextField(
            value = text,
            onValueChange = {
                text = it
                someRememberedObject.mutate()
            },
            modifier = Modifier.width(200.dp).height(50.dp)
        )
        ComposeUITextField(
            value = text,
            onValueChange = {
                text = it
                someGlobalObject.mutate()
            },
            modifier = Modifier.width(200.dp).height(50.dp)
        )

        ComposeUITextField(
            value = text,
            onValueChange = { text = it },
            modifier = Modifier.width(200.dp).height(50.dp)
        )
    }
}
```

https://user-images.githubusercontent.com/63979218/235663219-76532044-f731-4d97-9c5a-5f8e0102a03e.mov

**Comment by dima-avdeev-jb** [comment]
Thanks! It is very interesting, I will take a look!

**Comment by alexzhirkevich** [comment]
@dima-avdeev-jb 

Also if the view is inside scrollable container, it appears back after scroll performed

**Comment by elijah-semyonov** [comment]
### Findings:
- On initial composition UITextField is created 4 times.

**Comment by elijah-semyonov** [comment]
### Investigation continuation
I've tagged all new and disappearing UITextFields using a monotonic counter, they are created and added in a right order, hierarchy itself is correct.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3119">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
