### ISSUE TITLE
Window.onKeyEvent gets called even if propagation to the parent is stopped in the child

### ISSUE THREAD

**Issue by dimsuz** [JetBrains/compose-multiplatform#3122]
**Describe the bug**
According to `Modifier.onKeyEvent` documentation, returning `true` will prevent it's propagation to the parent, but this is currently not the case at least for `Window` and its child.

Here's the sample code which can be used to reporduce the problem:

```kotlin
fun main() = application {
  Window(
    title = "Test",
    state = rememberWindowState(position = WindowPosition(Alignment.Center), width = 1280.dp, height = 920.dp),
    onCloseRequest = ::exitApplication,
    onKeyEvent = { event ->
      exitApplication()
      true
    }
  ) {
    Box(
      modifier = Modifier
        .size(200.dp)
        .onKeyEvent {
        // do stuff
        true
      }
    )
  }
}
```

According to the docs, `Box` should not propagate key event to the `Window`, but if you run this program and press any key, the app will exit.

Note that both `onKeyEvent` handlers are getting called.

**Affected platforms**
Select one of the platforms below:
- Desktop
(Maybe others, I didn't test)

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.3.1
- OS version(s)* (required for Desktop and iOS issues): `Linux 6.2.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 26 Apr 2023 20:50:14 +0000 x86_64 GNU/Linux`
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): `openjdk 11.0.19 2023-04-18`

**Comment by dimsuz** [comment]
> Note that both onKeyEvent handlers are getting called.

This is an incorrect statement, actually only `Window`'s callback is getting called, which is not mentioned in it's documentation, I would expect that events would flow bottom up in composable hierarchy.

If this is somehow an expected behavior I'd suggest to mention it in documentation of `Window.onKeyEvent`.

Also: what's the right way to receive event in a child first?

**Comment by m-sasha** [comment]
In your example the Box is not focused, so it's not receiving (and not consuming) key events. This will work as you expect:

```
fun main() = application {
    Window(
        title = "Test",
        state = rememberWindowState(position = WindowPosition(Alignment.Center), width = 1280.dp, height = 920.dp),
        onCloseRequest = ::exitApplication,
        onKeyEvent = { event ->
            exitApplication()
            true
        }
    ) {
        val focusRequester = remember { FocusRequester() }
        Box(
            modifier = Modifier
                .size(200.dp)
                .onKeyEvent {
                    println("Key pressed in box")
                    true
                }
                .focusRequester(focusRequester)
                .focusable(true)
        )

        LaunchedEffect(Unit){
            focusRequester.requestFocus()
        }
    }
}
```

**Comment by dimsuz** [comment]
I see! Thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3122">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
