### ISSUE TITLE
Crash in iOS simulator on virtual MacOS 

### ISSUE THREAD

**Issue by alekseyHunter** [JetBrains/compose-multiplatform#3124]
**Describe the bug**
After successfully building the project, the iOS simulator starts, the application is installed, launched, a white screen is displayed and an error appears.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*:  1.4.0
- OS version(s)* (required for Desktop and iOS issues): MacOS (VirtualBox on Win10)
- OS architecture (x86 or arm64): x86

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Clone your template (https://github.com/JetBrains/compose-multiplatform-ios-android-template/)
2. Change platform to "iosApp"
3. Run app

**Expected behavior**
Хочу, чтобы приложение запустилось на симуляторе iOS на виртуалке без макбука ;)

**Screenshots**
![image](https://user-images.githubusercontent.com/42331576/235943379-235001a0-8f7e-4235-b05a-0deb557ba2ea.png)
![image](https://user-images.githubusercontent.com/42331576/235940455-f5f7c7ea-f483-44c7-ae46-905fa296b557.png)
![image](https://user-images.githubusercontent.com/42331576/235940523-5b062876-f02e-4a3c-8aa6-627ef570368e.png)

**Comment by pjBooms** [comment]
Can you share us MacOS image that you use for VirtualBox?

**Comment by pjBooms** [comment]
Have you tried easier samples in your environment? Like "Hello World" for Xcode (pure Swift or ObjC) in Simulator or "Hello World" for KMM? Do they work?

**Comment by alekseyHunter** [comment]
> Have you tried easier samples in your environment? Like "Hello World" for Xcode (pure Swift or ObjC) in Simulator or "Hello World" for KMM? Do they work?

Yes, pure KMM + SwiftUI works well on the iOS simulator. Swift + SwiftUI works too.

**Comment by alekseyHunter** [comment]
I updated macOS to Monterey (12.0.1), XCode 13.4, Java 17, Gradle 7.5, but the error remains:
![image](https://user-images.githubusercontent.com/42331576/236295658-dfc2f1f0-f12a-4b07-844e-8f09e5a8e5b1.png)

**Comment by pjBooms** [comment]
We have found that the crash may occur if Simulator does not support Metal (which may be the case for Virtual MacOS).

**Comment by alekseyHunter** [comment]
> Metal is not supported
> Is it your case?

I checked, yes.

![image](https://github.com/JetBrains/compose-multiplatform/assets/42331576/7ee92e18-1aab-4528-a257-28460d550f2b)

**Comment by pjBooms** [comment]
So, you are not lucky. Compose for iOS is based on Metal, we can't do anything except issuing a right message for this case (https://github.com/JetBrains/skiko/pull/704)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3124">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
