### ISSUE TITLE
No android TV composable in Jetpack Compose Multiplatform

### ISSUE THREAD

**Issue by kodeplateform** [JetBrains/compose-multiplatform#3125]
Hello,

I have developed an app using Android Jetpack Compose, making it compatible with both mobile and Android TV devices. 

Now, I am facing difficulties when trying to port this app to Jetpack Compose Multiplatform. The issue arises from the fact that the current implementation of Jetpack Compose Multiplatform does not include  any TV composable, https://developer.android.com/jetpack/androidx/releases/tv , which are crucial for maintaining compatibility across both platforms.

This absences of composables in Jetpack Compose Multiplatform and  KMP who does not target specificaly android TV  hinders the development process for developers who have built applications that target both mobile and Android TV devices. The lack of support for these composables makes it for peoples like me , the jetpack multiplateform library almost useless since we would have to add a specific code for android.

So could you please consider adding TV composables to Jetpack Compose Multiplatform on same way as they are on https://developer.android.com/jetpack/androidx/releases/tv (i dont expect a TvGrid for exemple to works on iOS or desktop but only on android) 

Thanks

**Comment by pjBooms** [comment]
Why not to keep Android TV related stuff in androidMain sourceSet (where you can add and use the dependency indeed)?

**Comment by kodeplateform** [comment]
Thank you for your response. I understand that the androidMain source set solution you propose, which likely involves the actual/expect mechanism, could introduce complexity to the project structure. This would require separate UI factory implementations for each platform, which seems to contradict the multiplatform goal of sharing as much code as possible across different platforms.

Additionally, it increases the maintenance effort needed to manage separate implementations and keep track of platform-specific code. In the Android app I've developed so far, I use a boolean isTV, and depending on its value, I customs composables like  for exemple  MyLazyRow:


```
@Composable
fun MyLazyRow(
    modifier: Modifier = Modifier,
    tvState: TvLazyListState ,
    mobileState: LazyListState,
    contentPadding: PaddingValues = PaddingValues(0.dp),
    reverseLayout: Boolean = false,
    horizontalArrangement: Arrangement.Horizontal = if (!reverseLayout) Arrangement.Start else Arrangement.End,
    verticalAlignment: Alignment.Vertical = Alignment.Top,
    flingBehavior: FlingBehavior = ScrollableDefaults.flingBehavior(),
    userScrollEnabled: Boolean = true,
    content: Any,
) {
    if (isTV) {
        TvLazyRow(
            modifier = modifier,
            state = tvState,
            contentPadding = contentPadding,
            reverseLayout = reverseLayout,
            horizontalArrangement = horizontalArrangement,
            verticalAlignment = verticalAlignment,
            userScrollEnabled = false,
            pivotOffsets = pivotOffsets,
            content = content as TvLazyListScope.() -> Unit,
        )
    } else {
        LazyRow(
            modifier = modifier,
            state = mobileState,
            contentPadding = contentPadding,
            reverseLayout = reverseLayout,
            horizontalArrangement = horizontalArrangement,
            verticalAlignment = verticalAlignment,
            flingBehavior = flingBehavior,
            userScrollEnabled = userScrollEnabled,
            content = content as LazyListScope.() -> Unit,
        )
    }
}
```

**Comment by pjBooms** [comment]
>If yes this would introduce complexity to the project structure and require separate UI factory implementations for each>
> platform, which seems to contradict the multiplatform goal of sharing as much code as possible across different platforms.

It is debatable. Multiplatform expect/actual mechanism was designed to move and maintain platform specific parts in a separate sourceSets.

Currently you use `if (platform)` approach for platform specific code (yes we may consider TV as another platform) that seems to be not the best practice for Kotlin Multiplatform.

>reimplement code on each other target (android,ios, and desktop on my project) .

You may introduce TV and commonButTV sourceSets. Then `MyLazyRow` would be expect/actual  with two actual implementations one is TV-specific another pure compose implementation (that can be reused in all non-tv platforms including android, ios, and desktop). It would require for you to build different artifacts for Android TV and Android, but it seems to be right approach to not have a code in an artifact that won't actually run. Won't it work?

**Comment by kodeplateform** [comment]
Thank you for your response. I'm going to try to address your concerns, but I'm not entirely sure I understand the solution you're proposing.

In the suggested approach, would the commonButTv source set be placed alongside commonMain?

Does the tv source set refer specifically to the TV app?

If so, I'm worried that introducing an additional source set might cause compatibility issues with KMP libraries like Ktor, Koin, and others.

Would this approach also require publishing two separate apps on the Google Play Store ? (its really a big plus to me to have a single app to publish instead of two for reviews,uploads,compilation ), but thats not the most important 

I'm also unsure how I could avoid reimplementing MyLazyRow for each target platform if I'm using the actual/expect mechanism.

**Comment by kodeplateform** [comment]
Thank you for your explanations. I think I understood, but I'm not 100% sure, as I'm still a beginner in Kotlin and Jetpack Compose.

Having two build flavors is something I want to avoid. In the title, I said "Android TV," but it's not just about "Android TV." There are many Android devices made for TV that don't run Android TV. With the suggested solution, none of these files would work for these devices (mobile build -> touchscreen, TV build -> key listener). I know I could make both work, but that's a different topic.

I think I'm going to stick with and adapt my initial solution:

```
commonMain

@Composable
expect fun  MyLazyRow(
    modifier: Modifier = Modifier,
    state: Any,
    contentPadding: PaddingValues = PaddingValues(0.dp),
    reverseLayout: Boolean = false,
    horizontalArrangement: Arrangement.Horizontal = if (!reverseLayout) Arrangement.Start else Arrangement.End,
    verticalAlignment: Alignment.Vertical = Alignment.Top,
    flingBehavior: FlingBehavior = ScrollableDefaults.flingBehavior(),
    userScrollEnabled: Boolean = true,
    content: Any,
)

AND 


@Composable
fun  MyLazyRowImpl(
    modifier: Modifier = Modifier,
    state: Any ,
    contentPadding: PaddingValues = PaddingValues(0.dp),
    reverseLayout: Boolean = false,
    horizontalArrangement: Arrangement.Horizontal = if (!reverseLayout) Arrangement.Start else Arrangement.End,
    verticalAlignment: Alignment.Vertical = Alignment.Top,
    flingBehavior: FlingBehavior = ScrollableDefaults.flingBehavior(),
    userScrollEnabled: Boolean = true,
    content: Any,

) {
    LazyRow(
        modifier = modifier,
        state = state as LazyListState,
        contentPadding = contentPadding,
        reverseLayout = reverseLayout,
        horizontalArrangement = horizontalArrangement,
        verticalAlignment = verticalAlignment,
        flingBehavior = flingBehavior,
        userScrollEnabled = userScrollEnabled,
        content = content as LazyListScope.() -> Unit
    )
}
```


```
for androidMain : 

@Composable
actual  fun  MyLazyRow(
    modifier: Modifier,
    state: Any,
    contentPadding: PaddingValues ,
    reverseLayout: Boolean ,
    horizontalArrangement: Arrangement.Horizontal ,
    verticalAlignment: Alignment.Vertical,
    flingBehavior: FlingBehavior ,
    userScrollEnabled: Boolean ,
    content: Any,
){
    if(TvDetector.getIsTv()){
        TvLazyRow(
            modifier = modifier,
            state = state as TvLazyListState,
            contentPadding = contentPadding,
            reverseLayout = reverseLayout,
            horizontalArrangement = horizontalArrangement,
            verticalAlignment = verticalAlignment,
            userScrollEnabled = false,
            pivotOffsets = PivotOffsets(),
            content=content as TvLazyListScope.() -> Unit,
        )

    }
    else {
        MyLazyRowImpl(
            modifier = modifier,
            state=state ,
            contentPadding = contentPadding,
            reverseLayout = reverseLayout,
            horizontalArrangement = horizontalArrangement,
            verticalAlignment = verticalAlignment,
            flingBehavior = flingBehavior,
            userScrollEnabled=userScrollEnabled,
            content= content
        )
    }
}

```
```
And for iosMain and desktopMain 
@Composable
actual  fun  MyLazyRow(
    modifier: Modifier,
    state: Any,
    contentPadding: PaddingValues ,
    reverseLayout: Boolean ,
    horizontalArrangement: Arrangement.Horizontal ,
    verticalAlignment: Alignment.Vertical,
    flingBehavior: FlingBehavior ,
    userScrollEnabled: Boolean ,
    // pivotOffsets: PivotOffsets = PivotOffsets(),
    content: Any,
){
    MyLazyRowImpl(
        modifier = modifier,
        state=state ,
        contentPadding = contentPadding,
        reverseLayout = reverseLayout,
        horizontalArrangement = horizontalArrangement,
        verticalAlignment = verticalAlignment,
        flingBehavior = flingBehavior,
        userScrollEnabled=userScrollEnabled,
        content= content
    )
}

```

What would have been great and not just for that case would have be able to define a default implementation for an "expect" function on KMP but this is not depdnds on your project

**Comment by pjBooms** [comment]
Yes, your approach should work as well. If you need tv-related stuff to be present for all android targets then the most probably it is a preferable solution.

**Comment by pjBooms** [comment]
We are not going to port `androidx.tv` library to Compose Multiplatform now until it will be proved to be useful outside of Android.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3125">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
