### ISSUE TITLE
Using Kotlin's C-Interop together with Compose Multiplatform

### ISSUE THREAD

**Issue by jay-tux** [JetBrains/compose-multiplatform#3130]
Is there an example of how to use the C-interop with Compose Multiplatform?

I can't seem to get it working - adding the `import` and the plugin from the default-generated `build.gradle.kts` for Compose Multiplatform gets my IDE screaming at me.

This is the (non-Compose) `build.gradle.kts` I'm using at the moment:
```
plugins {
    kotlin("multiplatform") version "1.8.20"
}

group = "me.jay"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

kotlin {
    val hostOs = System.getProperty("os.name")
    val isMingwX64 = hostOs.startsWith("Windows")
    val nativeTarget = when {
        hostOs == "Mac OS X" -> macosX64("native")
        hostOs == "Linux" -> linuxX64("native")
        isMingwX64 -> mingwX64("native")
        else -> throw GradleException("Host OS is not supported in Kotlin/Native.")
    }

    nativeTarget.apply {
        compilations.getByName("main") {
            cinterops {
                val libnative by creating
            }
        }
        binaries {
            executable {
                entryPoint = "main"
            }
        }
    }
    sourceSets {
        val nativeMain by getting
        val nativeTest by getting
    }
}
```

How do I add Compose Multiplatform to this app?

**Comment by pjBooms** [comment]
Would you like to add desktop? We have only MacOS native target for desktop in Compose Multiplatform and even it is in very experimental phase. Compose Multiplatform for Desktop is based on JVM, where you are limited with C-interop to JNI.

**Comment by bulatgaleev** [comment]
Kinda related to #2305

**Comment by shalva97** [comment]
Are there plans to support native Linux?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3130">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
