### ISSUE TITLE
Improve C-interop for UIEdgeInsets Type

### ISSUE THREAD

**Issue by MohamedRejeb** [JetBrains/compose-multiplatform#3131]
There are several use cases where we need to use `safeAreaInsets: UIEdgeInsets` but the problem is that we can't have access to the properties of `UIEdgeInsets` such us `top`, `botton`...

For now these are the only two properties available under `UIEdgeInsets` and both are useless.

<img width="876" alt="Screenshot 2023-05-07 at 12 59 05 AM" src="https://user-images.githubusercontent.com/41842296/236651071-ea6790dd-1fc1-4530-b80a-32a86d01e9c5.png">

**Comment by alexzhirkevich** [comment]
Probably you work with `CValue<UIEdgeInsets>`.
Try this:
<img width="309" alt="image" src="https://user-images.githubusercontent.com/63979218/236671610-f7e1067e-eee2-4215-8753-1d2a28573254.png">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3131">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
