### ISSUE TITLE
Can't run commonTest on iOS simulator

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#3135]
When trying to run test from commonMain in iOS simulator:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/99798741/236774697-69c503cf-aa8d-414c-b68b-b41d77767b80.png">

Test fails with error:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MTLCommandBufferDescriptor", referenced from:
      objc-class-ref in libskia.a(gpu.GrMtlCommandBuffer.o)
 ...
```

Slack discussion: https://kotlinlang.slack.com/archives/C0346LWVBJ4/p1682502923227539

**Comment by AKJAW** [comment]
I've also came across this issue (Apple M1 Pro) 

Here's my repository branch to reproduce this issue: https://github.com/AKJAW/Kotlin-Native-Implementations/pull/1/commits/03420e66d3479973372c79538e872c66cdf07977

Besides the
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MTLCommandBufferDescriptor", referenced from:
      objc-class-ref in libskia.a(gpu.GrMtlCommandBuffer.o)
  "_OBJC_CLASS_$_MTLCompileOptions", referenced from:
      objc-class-ref in libskia.a(gpu.GrMtlUtil.o)
  "_OBJC_CLASS_$_MTLDepthStencilDescriptor", referenced from:
      objc-class-ref in libskia.a(gpu.GrMtlDepthStencil.o)
...
```
I'm also getting a lot of warning for skia being built for a newer version:

```
e: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors

The /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
output:
ld: warning: object file (/var/folders/y1/97tpgdnx58512tm7gcdq69r80000gn/T/konan_temp3073245421618510485/result.o) was built for newer iOS Simulator version (14.0) than being linked (9.0)
ld: warning: object file (/var/folders/y1/97tpgdnx58512tm7gcdq69r80000gn/T/included7250380580247839097/libskresources.a(libskresources.SkResources.o)) was built for newer iOS Simulator version (15.2) than being linked (9.0)
....
ld: warning: object file (/var/folders/y1/97tpgdnx58512tm7gcdq69r80000gn/T/included7250380580247839097/libskia.a(libexpat.xmlparse.o)) was built for newer iOS Simulator version (15.2) than being linked (9.0)
ld: warning: object file (/var/folders/y1/97tpgdnx58512tm7gcdq69r80000gn/T/included7250380580247839097/libskia.a(libexpat.xmlrole.o)) was built for newer iOS Simulator version (15.2) than being linked (9.0)
ld: warning: object file (/var/folders/y1/97tpgdnx58512tm7gcdq69r80000gn/T/included7250380580247839097/libskia.a(libexpat.xmltok.o)) was built for newer iOS Simulator version (15.2) than being linked (9.0)
```

To fix this issue, I needed to comment out the following libraries:
``` kotlin
        val commonMain by getting {
            dependencies {
                implementation(compose.runtime)
//                implementation(compose.foundation)
//                implementation(compose.material)
//                @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
//                implementation(compose.components.resources)
            }
        }
```
Here's the commit: https://github.com/AKJAW/Kotlin-Native-Implementations/pull/1/commits/03d573b1e86825d772c0a67ec8274d92fa87ee2e

**Comment by haydenkaizeta** [comment]
when    

    cocoapods {
        ..
        framework {
            ..
            isStatic = false

I also get this issue. Any timeline on when we can set this value to the default (false)

**Comment by dmitry-stakhov** [comment]
Related: https://github.com/JetBrains/compose-multiplatform/issues/3178

**Comment by AKJAW** [comment]
Are there any fixes / workarounds for this issue? Being unable to run iOS tests is a big issue for the Shared codebase

**Comment by pjBooms** [comment]
Yes it is fixed in the [1.5.0-beta01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0-beta01)

**Comment by pjBooms** [comment]
For previous versions look at this workaround: https://github.com/JetBrains/compose-multiplatform/pull/3378/files

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3135">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
