### ISSUE TITLE
ConstraintLayout for Compose Multiplatform

### ISSUE THREAD

**Issue by hm-tamim** [JetBrains/compose-multiplatform#3136]
Now that compose has iOS support, it would be great if Compose Multiplatform had ConstraintLayout support

https://developer.android.com/jetpack/compose/layouts/constraintlayout

**Comment by igordmn** [comment]
Let's keep only [this issue](https://github.com/JetBrains/compose-multiplatform/issues/858)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3136">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
