### ISSUE TITLE
`Text` doesn't redraw when its value changes on Mac OS X

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#3137]
When the `text` parameter of `Text` changes, the value drawn on the screen doesn't immediately change:

```
import androidx.compose.foundation.layout.width
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.WindowState
import androidx.compose.ui.window.singleWindowApplication
import kotlinx.coroutines.delay


fun main() {
    singleWindowApplication(
        title = "Test",
        state = WindowState(
            width = 400.dp,
            height = 600.dp,
        )
    ) {
        var state by remember { mutableStateOf(0) }
        println("Value: $state")

        Text(
            text = "Value: $state",
            modifier = Modifier.width(200.dp)
        )

        LaunchedEffect(Unit) {
            delay(1000)
            state += 1
        }
    }
}
```

**Affected platforms**
- Desktop - Mac OS X only

**Versions**
- Compose Multiplatform version: 1.3.x, 1.4.0

**To Reproduce**
Run the code above. The displayed text should change to `Value: 1` after a second, but it doesn't.

**Additional context**
The issue appears to be a combination of two problems:
1. When the value of `text` changes, it takes 3 runs of `ComposeScene.render` for the actual new value to be drawn.
2. `MetalRedrawer` in skiko doesn't sync with the monitor refresh rate, simply sending each completed picture to Metal. Apparently, Metal
   1. Draws the 1st command buffer immediately.
   2. Delays the drawing of the 2nd command buffer until after the next vsync.
   3. Drops the 3rd command buffer completely.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3137">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
