### ISSUE TITLE
`LocalLayoutDirection` isn't propagated into `Popup`

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#3142]
**Describe the bug**
`LocalLayoutDirection.current` returns LTR even when set to RTL outside a `Popup`:

```
    @Test
    fun `LocalLayoutDirection is seen in popup`() {
        lateinit var layoutDirectionInPopup: LayoutDirection
        rule.setContent {
            CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl) {
                Popup{
                    layoutDirectionInPopup = LocalLayoutDirection.current
                }
            }
        }

        assertThat(layoutDirectionInPopup).isEqualTo(LayoutDirection.Rtl)
    }
```

This is related to https://github.com/JetBrains/compose-multiplatform/issues/3129

**Affected platforms**
- Desktop

**Versions**
- Compose Multiplatform version*: 1.3.x, 1.4.0

**Expected behavior**
The provided layout direction should be seen inside the popup composable.

**Comment by mahozad** [comment]
@m-sasha `LocalLayoutDirection` isn't propagated into `Dialog`s too.

Could you please fix that too?

I'm using Compose-Multiplatform 1.4.1

Workaround:

```kotlin
Dialog(
    state = rememberDialogState(
        size = DpSize(400.dp, 300.dp),
        position = WindowPosition(Alignment.Center)
    ),
    resizable = false,
    undecorated = true,
    transparent = true,
    onCloseRequest = onCloseRequest
) {
    val language = LocalLanguage.current
    CompositionLocalProvider(LocalLayoutDirection provides language.layoutDirection) {
        // ...
    }
}
```

**Comment by m-sasha** [comment]
Can you open a new bug report for this?

**Comment by mahozad** [comment]
Yes. Here it is: https://github.com/JetBrains/compose-multiplatform/issues/3382

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3142">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
