### ISSUE TITLE
Serialization / Compose / KSP: NullPointerException during compileKotlinJs in mpp project with AndroidTarget

### ISSUE THREAD

**Issue by ltttttttttttt** [JetBrains/compose-multiplatform#3145]
**Describe the bug**
Serialization / Compose / KSP: NullPointerException during compileKotlinJs in mpp project with AndroidTarget

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - Canvas based API
- iOS

**Versions**
android studio 2022.2.1
kotlin 1.8.20
compose-jb 1.4.0
kotlin serialization 1.5.0 plugin 1.8.20
ksp 1.8.20-1.0.10
jdk 17

For details, please refer to: https://youtrack.jetbrains.com/issue/KT-58000

**Comment by MatkovIvan** [comment]
It's probably related to this one #2635

**Comment by ltttttttttttt** [comment]
Yes, I made a mistake before. After making the necessary changes, it will be ready

```kotlin
compose {
    //kotlinCompilerPlugin.set("androidx.compose.compiler:compiler:$composeCompilerVersion")//old
    kotlinCompilerPlugin.set("org.jetbrains.compose.compiler:compiler:$composeCompilerVersion")//new
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3145">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
