### ISSUE TITLE
Jetpack compose DESKTOP BasicTextField - how to Shift Enter to line skip

### ISSUE THREAD

**Issue by June6-android** [JetBrains/compose-multiplatform#3150]
I want to use the ENTER KEY to trigger send action, and use SHIFT + ENTER as a line skip command.

I've tried two attempts with no luck.

My first attempt - tried to use keyboard options, but didn't work.
` BasicTextField(
                value = textFieldState,
                onValueChange = { input ->
                    textFieldState = input
                },
                modifier = Modifier.fillMaxSize(),
                keyboardOptions = KeyboardOptions(imeAction = ImeAction.Send),
                keyboardActions = KeyboardActions(onSend = {
                    mPresenter.sendTextMsg(textFieldState)
                    textFieldState = ""
                }),
                textStyle = TextStyle(
                    fontSize = 14.sp,
                    textAlign = TextAlign.Start,
                    fontWeight = FontWeight.Normal,
                    fontFamily = NotoSans,
                    color = Color.Black
                )
)`
   

Second attempt - tried to utilize onPreviewKeyEvent. Sending the message works, but line skip doesn't work.

` BasicTextField(
                value = textFieldState,
                onValueChange = { input ->
                    textFieldState = input
                },
                modifier = Modifier.fillMaxSize().onPreviewKeyEvent {
                    if (it.key == Key.Enter) {
                        if (it.isShiftPressed) {
                            textFieldState += "\n"
                        } else {
                            mPresenter.sendTextMsg(textFieldState)
                            textFieldState = ""
                        }
                        true
                    } else {
                        false
                    }
                },
                textStyle = TextStyle(
                    fontSize = 14.sp,
                    textAlign = TextAlign.Start,
                    fontWeight = FontWeight.Normal,
                    fontFamily = NotoSans,
                    color = Color.Black
                )
 )`
   

Is there a way to implement such action?

**Comment by igordmn** [comment]
It can be done this way:
```
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.input.key.*
import androidx.compose.ui.text.TextRange
import androidx.compose.ui.text.input.TextFieldValue
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

var text by mutableStateOf(TextFieldValue("Hello, World!"))

@OptIn(ExperimentalComposeUiApi::class)
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        BasicTextField(
            value = text,
            onValueChange = { input -> text = input },
            modifier = Modifier.fillMaxSize().onPreviewKeyEvent {
                if (it.key == Key.Enter && it.type == KeyEventType.KeyDown) {
                    if (it.isShiftPressed) {
                        text = TextFieldValue(
                            text.text.substring(0 until text.selection.start)
                                    + "\n"
                                    + text.text.substring(text.selection.end until text.text.length),
                            TextRange(text.selection.end + 1)
                        )
                    } else {
                        println("SEND")
                    }
                    true
                } else {
                    false
                }
            }
        )
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3150">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
