### ISSUE TITLE
Fix unicode related TODOs in `SkiaParagraph.skiko.kt`

### ISSUE THREAD

**Issue by MatkovIvan** [JetBrains/compose-multiplatform#3151]
[SkiaParagraph.skiko.kt](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/ui/ui-text/src/skikoMain/kotlin/androidx/compose/ui/text/SkiaParagraph.skiko.kt) contains a couple of TODOs related to unicode multi-char symbols. We need to address it.

**Affected platforms**
- All

**Versions**
- Compose Multiplatform version*: `jb-main`

**Expected behavior**
Unicode strings should be fully supported. The implementation must be covered by tests and match Android as much as possible.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3151">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
