### ISSUE TITLE
`org.jetbrains.skia.*` shouldn't be exposed by default

### ISSUE THREAD

**Issue by MatkovIvan** [JetBrains/compose-multiplatform#3152]
**Describe the bug**
Skiko library is currently [included](https://github.com/JetBrains/compose-multiplatform-core/blob/feaab5420821266f10982a0b36d41b22d89bc3bf/compose/ui/ui/build.gradle#LL201C30-L201C41) as `api` that makes possible using this unstable API without explicit adding the library.
It's even [used](https://github.com/JetBrains/compose-multiplatform/blob/master/examples/imageviewer/shared/src/iosMain/kotlin/example/imageviewer/filter/BitmapFilter.ios.kt#L7) in the official samples that might lead to widespread usage of it.

**Affected platforms**
- All

**Versions**
- Compose Multiplatform version*: `1.4.0` `jb-main`

**Expected behavior**
Since it's an implementation details, it should not be exposed by default. In the same time we need to allow users use it "as is" by adding skiko as explicit dependency to their project.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3152">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
