### ISSUE TITLE
JavaFX WebView

### ISSUE THREAD

**Issue by SWRHARD** [JetBrains/compose-multiplatform#3158]
Hi, i'm trying to use JavaFX Webview component, but don't know how can i get request and response headers. In my desktop app i want to login via webview and after that get some headers, thats needed for making api requests, is it possible or i wasting my time?)
Maybe is there analogues for android webview component, that i can use in desktop compose application? Thanks!

**code ex:**

    private fun initialiseJavaFXScene() {
        val webView = WebView()

        val cookieManager = CookieManager()
        CookieHandler.setDefault(cookieManager)
        //URL.setURLStreamHandlerFactory(CustomURLStreamHandlerFactory()) //not working

        with(webView.engine) {
            loadWorker.stateProperty().addListener { _, oldValue, newValue ->
                with(cookieManager.cookieStore.cookies) {
                           //...
                    }
                }
            }
            load(BASE_URL)
        }

        val scene = Scene(webView)
        setScene(scene)
    }

**Comment by igordmn** [comment]
>  use JavaFX Webview component, but don't know how can i get request and response headers ... is it possible or i wasting my time?

This question is not related to Compose Multiplatform. You can ask it on StackOverflow.

> is there analogues for android webview component, that i can use in desktop compose application

There is no official WebView for Compose for Desktop at the moment. You can follow [this issue](https://github.com/JetBrains/compose-multiplatform/issues/668)

**Comment by KevinnZou** [comment]
I would recommend this library https://github.com/KevinnZou/compose-webview-multiplatform. It supports WebView on the desktop side using JCEF.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3158">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
