### ISSUE TITLE
Resources are not found in JVM project depending on multiplatform library

### ISSUE THREAD

**Issue by avwie** [JetBrains/compose-multiplatform#3162]
**Describe the bug**
Resources in a Multiplatform library common target can not be resolved in a consuming JVM project.

See https://github.com/avwie/resources-issues-compose for a working minimal example of the bug.

**Affected platforms**
Select one of the platforms below:
- Desktop, so far I could see

**Versions**
- Kotlin version: 1.8.20 
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues):  
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): Azure

**To Reproduce**
- Create multiplatform project (named icons) with target JVM
- Add resources to this project
- Create jvm project and add icons project to dependencies
- Resources can not be found
- Create multiplatform project with JVM target and add icons project to dependencies
- Resources _can_ be found

Or see readme in my linked repo.

**Expected behavior**
I expect resources in the commonMain/resources folder also to be resolvable in a kotlin("jvm") project.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3162">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
