### ISSUE TITLE
Converting color from `CieLab` colorspace to `Srgb` differs between 1.3.1 and 1.4.0

### ISSUE THREAD

**Issue by haluzpav** [JetBrains/compose-multiplatform#3163]
**Describe the bug**

I'm auto-generating some colors in CieLab color space, and noticed they look different after upgrading `id("org.jetbrains.compose") version "1.3.1"` to `1.4.0`. I discovered that the problem is probably in converting from CieLab to Srgb.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Fedora 37
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): openjdk 17.0.6 2023-01-17

**To Reproduce**

Here's an example, showing the inconsistency. Notice the difference in the last lines of the output.

Source scratch file:

```kotlin
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.colorspace.ColorSpaces

Color(0, 180, 0)
Color(0, 180, 0).convert(ColorSpaces.CieLab)
Color(63.9375f, -61.03125f, 62.34375f, colorSpace = ColorSpaces.CieLab)
Color(63.9375f, -61.03125f, 62.34375f, colorSpace = ColorSpaces.CieLab).convert(ColorSpaces.Srgb)
```

Output with 1.3.1:

```
Color(0.0, 0.7058824, 0.0, 1.0, sRGB IEC61966-2.1)
Color(63.9375, -61.03125, 62.34375, 1.0, Generic L*a*b*)
Color(63.9375, -61.03125, 62.34375, 1.0, Generic L*a*b*)
Color(0.0, 0.7058824, 0.0, 1.0, sRGB IEC61966-2.1)  // matches the first line, OK
```

Output with 1.4.0:

```
Color(0.0, 0.7058824, 0.0, 1.0, sRGB IEC61966-2.1)
Color(63.9375, -61.03125, 62.34375, 1.0, Generic L*a*b*)
Color(63.9375, -61.03125, 62.34375, 1.0, Generic L*a*b*)
Color(1.0, 0.37254903, 0.17254902, 1.0, sRGB IEC61966-2.1) // different than 1.3.1, and also the first line, wut?
```

**Comment by haluzpav** [comment]
I somehow missed your issue template when I had to log in, sorry. Adjusted the report.

**Comment by igordmn** [comment]
Thanks!

Reproducible also on Windows and on Android. Created [an issue](https://issuetracker.google.com/issues/282780823) in the Jetpack Compose tracker. Follow it there.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3163">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
