### ISSUE TITLE
Missing window restore animation on Windows 10

### ISSUE THREAD

**Issue by hristogochev** [JetBrains/compose-multiplatform#3166]
**Describe the bug**
When restoring a window from being minimized on Windows 10 by calling `window.isMinimized = false` there is no restore animation.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Windows 10 
- OS architecture (x86 or arm64): 86_64
- JDK (for desktop issues): 17

**To Reproduce**
1. Run the following code snippet:
```kotlin
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        val coroutineScope= rememberCoroutineScope()
        coroutineScope.launch {
            delay(5000)
            window.isMinimized=false
        }
    }
}
```
2. Minimize the window manually 5 seconds before the window is restored automatically

**Expected behavior**
Window should be restored with the windows restore animation.

**Proposed fix**
Windows should be restored using the JNA function `User32.INSTANCE.ShowWindow(WinDef.HWND(Pointer(window.windowHandle)), 1)`

**Comment by igordmn** [comment]
Thanks!

We also don't have animation during maximazing and minimizing:

```
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        val coroutineScope= rememberCoroutineScope()
        coroutineScope.launch {
            delay(3000)
            window.placement = WindowPlacement.Maximized
            delay(3000)
            window.isMinimized=true
            delay(3000)
            window.isMinimized=false
        }
    }
}
```

If `User32.INSTANCE.ShowWindow` function helps solving the issue, we need to switch to it (and find other functions for other states on different platforms).

**Comment by hristogochev** [comment]
Using `User32.INSTANCE.ShowWindow` I was able to get animations for minimizing and maximizing as well!

Not only do they display the animations but they automatically set `window.placement` and `window.isMinimized` when used.

``` kotlin
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.WindowPlacement
import androidx.compose.ui.window.application
import com.sun.jna.Pointer
import com.sun.jna.platform.win32.User32
import com.sun.jna.platform.win32.WinDef
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        val coroutineScope= rememberCoroutineScope()
        coroutineScope.launch {
            delay(3000)
            // Instead of window.placement = WindowPlacement.Maximized
            User32.INSTANCE.ShowWindow(WinDef.HWND(Pointer(window.windowHandle)), 3)
            assert(window.placement == WindowPlacement.Maximized)
            delay(3000)
            // Instead of window.isMinimized=true
            User32.INSTANCE.ShowWindow(WinDef.HWND(Pointer(window.windowHandle)), 2)
            assert(window.isMinimized)
            delay(3000)
            // Instead window.isMinimized=false
            User32.INSTANCE.ShowWindow(WinDef.HWND(Pointer(window.windowHandle)), 1)
            assert(!window.isMinimized)
        }
    }
}
````

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3166">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
