### ISSUE TITLE
App Crashing with onPointerEvent import on Android

### ISSUE THREAD

**Issue by ngengesenior** [JetBrains/compose-multiplatform#3167]
I am running a project in which I implemented pointer events to detect enter and exit pointer events. My interest is in detecting this behavior on platforms that support these input types generally. There is the import `import androidx.compose.ui.input.pointer.onPointerEvent` , the project compiles on iOS without a problem and on Desktop but fails to compile on Android with the error, `Unresolved reference: onPinterEvent`. 
The project is compiled with `Android Studio Giraffe | 2022.3.1 Canary 11`

**Comment by MatkovIvan** [comment]
Hi @ngengesenior,

`onPinterEvent` != `onPointerEvent`, so first of all please check typos in Android source set.

If problem is still there, please follow instruction in issue template and
1. "If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)"
2. Provide required data according the template.

**Comment by MatkovIvan** [comment]
Regarding `androidx.compose.ui.input.pointer.onPointerEvent` - this function is not available on Android. Currently we're discussing how to sync a few things including this with Google upstream repo (or maybe move it to separate library).
We'll keep you updated. For now changing tag to "enhancement"

**Comment by ngengesenior** [comment]
I made a typo while typing. The error is actually real. Here is a screenshot when I attempt building on Android

![Screen Shot 2023-05-15 at 3 49 50 PM](https://github.com/JetBrains/compose-multiplatform/assets/17143469/9c097154-2c63-4b89-9591-c907c00d3c0b)

**Comment by igordmn** [comment]
Actually, here is an IDE error as well. IDE should highlight `onPointerEvent` with the red color, because it is not availalable in `commonMain`

**Comment by zhelenskiy** [comment]
For me it does not
<img width="1344" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/55230817/7aa60a95-fd42-449d-a2a0-f6440c8adc09">

**Comment by andylamax** [comment]
It does not highlight on the IDE for me as well

**Comment by Yusufjon1224** [comment]
neverthless , it does to me I mean it highlights on the IDE

**Comment by Yusufjon1224** [comment]
Can I use onPointerEvent for the android not for the desktop ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3167">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
