### ISSUE TITLE
Avoid resolving Kotlin compile classpath during configuration phase

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [JetBrains/compose-multiplatform#3169]
Kotlin Multiplatform Team requested to avoid resolving compile classpath configuration when checking flags
for experimental targets, because it can break Kotlin 1.9.0
Here is the problematic line: https://github.com/JetBrains/compose-multiplatform/blob/1f39fa4ba165e2ada409f523e907201ca9888099/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/experimental/internal/checkExperimentalTargets.kt#L66
Previous versions of Kotlin could added some dependencies in the first round of `afterEvaluate {}`
Our check resolves compile dependencies in the second round of `afterEvaluate`.
Kotlin 1.9.0 might want to add dependencies in the third round  of `afterEvaluate` or even later.
Gradle prohibits adding dependencies after resolution, so with current implementation Kotlin 1.9.0 would fail.

Internal discussion: https://jetbrains.slack.com/archives/C015PT6ALK1/p1684158039161129

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3169">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
