### ISSUE TITLE
Setting any Window or Dialog to undecorated and transparent leads to an exception in SKIKO

### ISSUE THREAD

**Issue by hristogochev** [JetBrains/compose-multiplatform#3171]
**Describe the bug**
Setting any Window or Dialog to undecorated and transparent leads to an exception in SKIKO.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): x86_64
- JDK (for desktop issues): OpenJDK-17

**To Reproduce**
1. Run the last official example from [WINDOW_API_NEW](https://github.com/JetBrains/compose-multiplatform/blob/21f74f92df7fa2bcc1a08c02b95d5f404a6c0437/tutorials/Window_API_new/README.md):

``` kotlin
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.Surface
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import androidx.compose.material.Text
import androidx.compose.runtime.*

fun main() = application {
    var isOpen by remember { mutableStateOf(true) }
    if (isOpen) {
        Window(
            onCloseRequest = { isOpen = false },
            title = "Transparent Window Example",
            transparent = true,
            undecorated = true, //transparent window must be undecorated
        ) {
            Surface(
                modifier = Modifier.fillMaxSize().padding(5.dp).shadow(3.dp, RoundedCornerShape(20.dp)),
                color = Color(55, 55, 55),
                shape = RoundedCornerShape(20.dp) //window has round corners now
            ) {
                Text("Hello World!", color = Color.White)
            }
        }
    }
}
```
2. A exception will pop up with the message:
```
[SKIKO] warn: Fallback to next API
org.jetbrains.skiko.RenderException: Failed to create DirectX12 device.
```

**Comment by dima-avdeev-jb** [comment]
Thanks, we already have this bug in skiko repository.
You can follow here: https://github.com/JetBrains/skiko/issues/327

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3171">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
