### ISSUE TITLE
iOS: Font should default to SF Pro

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#3173]
https://developer.apple.com/design/human-interface-guidelines/typography#Using-system-fonts

**Comment by MatkovIvan** [comment]
Duplicate of #2874

**Comment by MatkovIvan** [comment]
It should be fixed in last dev build, please re-open if something still goes wrong here

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3173">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
