### ISSUE TITLE
update description of plugin or plugin iteself (Intellij)

### ISSUE THREAD

**Issue by victororlyk** [JetBrains/compose-multiplatform#3176]
I hope that plugin https://plugins.jetbrains.com/plugin/16541-compose-multiplatform-ide-support should support ios/android and desktop not only desktop as it tells in the page

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3176">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
