### ISSUE TITLE
ios-Compose `ComposeUIViewController` executes twice

### ISSUE THREAD

**Issue by Juanlu-bf** [JetBrains/compose-multiplatform#3177]
**Describe the bug**
When starting the app, the code inside `ComposeUIViewController` is called twice, which means whole app UI is being recomposed.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): iOS 16.2
- OS architecture (x86 or arm64): arm64 simulator

**To Reproduce**
1. Download ios compose template (https://github.com/JetBrains/compose-multiplatform-ios-android-template)
2. Put a print inside `App()` composable (for example, `println("App composable")`.
3. Execute iOS and Android apps.
4. You will see in iOS app the print twice, while it is only printed once in Android app. 

**Expected behavior**
To be printed once on both platforms.

**Screenshots**
Android execution: 
<img width="497" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/130052214/db931b26-7da7-499f-af21-9d136e0d2975">
iOS execution: 
<img width="196" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/130052214/48c3ad11-a558-4f6d-8f73-1f78af5f9c4a">

**Comment by mashtabiei-fourthline** [comment]
Just bringing more visibility. 

I've tried the template with the newest [Compose 1.5.3](https://github.com/JetBrains/compose-multiplatform-ios-android-template/commit/8380eb51d72e333f00a52783b714d26d08e2461e) and the bug, sadly, is still there.

Is there any workaround possible? It brings problems in our project

**Comment by elijah-semyonov** [comment]
The fix wasn't included in the 1.5.3. It will be in in 1.5.10-RC

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3177">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
