### ISSUE TITLE
Need support for Composable with dynamically changing height on iOS

### ISSUE THREAD

**Issue by Quantamm** [JetBrains/compose-multiplatform#3179]
I would like to be using Compose Multiplatform for an Android / iOS app. The use case is to display a collapsible list of items. The list will initially show as collapsed, then when the user taps it, it shows the full list. I will be embedding this in an existing UI. On Android, it works as expected and when the list expands, the non-Compose UI elements below the list are pushed further down the screen.

But, on iOS, the height can either be a fixed number of pixels or the entire screen, but I haven't found a way to make it respond dynamically to the height of the Composable.

Similarly, this issue prevents wrapping the Composable so that it takes up only the space it needs in the iOS UI, so I believe solving this would have greater benefits than just my particular use-case.

I did hack a workaround together where I created a callback function from the Composable that returns the current height of the Composable in onGloballyPositioned(), but this then requires that I know the exact PPI for every iOS device that I want to run the app on so that I can do the dp -> pixel conversion.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3179">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
