### ISSUE TITLE
Composable method with receivers doesn't work?

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#3182]
**Describe the bug**
Am i doing something wrong or why is this an error?

UPD: Not a problem of Compose.  Actually don't see the problem in this code.

<img width="300" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/63979218/2b8d25f0-15aa-45b3-a2e2-797a79cdf7d0">

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0

**To Reproduce**

```kotlin
@Composable
fun foo() {
    Box {
        Test.Content()

        with(Test){
            Content()
        }
    }
}

object Test {
    @Composable
    fun BoxScope.Content() {

    }
}


```

**Expected behavior**
Should compile???

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3182">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
