### ISSUE TITLE
Text not recomposing after toggling dark mode on Compose 1.4.0 and JDK 11

### ISSUE THREAD

**Issue by anikrajc** [JetBrains/compose-multiplatform#3183]
**Describe the bug**
On Compose 1.4.0 with JDK 11, when changing the colors (toggling dark mode), the Text Component is not recomposing with the updated Colors. This was working as expected on Compose 1.3.0 and JDK 11. Please check the attached video for more information.

JDK 17 and Compose 1.4.0 work as expected. This is only happening on JDK 11.

**Affected platforms**
Select one of the platforms below:
- Desktop - Tested only on Desktop, but might also be on others.

**Versions**
- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): MacOS 13.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 11

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Change MaterialTheme colors at runtime to dark/light
2. Observe Text Component

**Expected behavior**
Text Should recompose with the updated color.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/6180066/658b901f-b0f6-4499-987f-ab850508739f

**Comment by andreykavo** [comment]
We've been stuck on Compose 1.3.1 because of that issue. And I've been trying to resolve it this whole day. After creating two reproducers (the first one failed) I came to a conclusion that it happens only when using child animation with Decompose library. Basically, this code works as expected:
```kotlin
Children(navRoot.childStack) { it.instance() }
```
While this one causes colors to break:
```kotlin
Children(navRoot.childStack, animation = stackAnimation(fade())) {
    it.instance()
}
```

@arkivanov

**Comment by arkivanov** [comment]
@andreykavo, the issue with Decompose animations might be different from the original reported here, it's already known.

See: https://github.com/arkivanov/Decompose/issues/330

The actual cause: https://issuetracker.google.com/issues/270656235

Please update Decompose to at least 2.0.0, and your case with `stackAnimation(...)` should be working. However, `stackAnimation {...}` will be still broken, and will be fixed on Compose side, perhaps in `v1.5.0` (not quite sure).

**Comment by dima-avdeev-jb** [comment]
@anikrajc Can you please check your project with Kotlin 1.9.0 and Compose 1.5.0-beta01 ?

**Comment by anikrajc** [comment]
@dima-avdeev-jb That fixes the issue. Thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3183">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
