### ISSUE TITLE
(📚) Can you document in a README how to use the dev versions

### ISSUE THREAD

**Issue by KotlinIsland** [JetBrains/compose-multiplatform#3184]
I spent half an hour trying to find out which repo I needed to add to get the dev versions to work, maybe there could be an FAQ/readme that says how to do it? "Using pre-release versions"

**Comment by alexzhirkevich** [comment]
maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3184">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
