### ISSUE TITLE
KDoctor falsely reports "Xcode requires to perform the First Launch tasks"

### ISSUE THREAD

**Issue by gosr** [JetBrains/compose-multiplatform#3186]
**Describe the bug**
I cloned the https://github.com/JetBrains/compose-multiplatform-template template. Then I ran `kdoctor` which reported:

```
Environment diagnose (to see all details, use -v option):
[✓] Operation System
[✓] Java
[✓] Android Studio
[✖] Xcode
  ✖ Xcode requires to perform the First Launch tasks
    Launch Xcode and complete setup
[✖] Cocoapods
  ✖ System ruby is currently used
    CocoaPods is not compatible with system ruby installation on Apple M1 computers.
    Please install ruby via Homebrew, rvm, rbenv or other tool and make it default
    Detailed information: https://stackoverflow.com/questions/64901180/how-to-run-cocoapods-on-apple-silicon-m1/66556339#66556339
  ✖ cocoapods not found
    Get cocoapods from https://guides.cocoapods.org/using/getting-started.html#installation

Conclusion:
  ✖ KDoctor has diagnosed one or more problems while checking your environment.
    Please check the output for problem description and possible solutions.
```

I went ahead and ran Xcode (14.3 14E222b) which didn't ask for any "initial setup". It runs normally without asking for anything.

Running `kdoctor -v` produces:

```
[✖] Xcode
  ➤ Xcode (14.3)
    Location: /Applications/Xcode.app
  ✖ Xcode requires to perform the First Launch tasks
    Launch Xcode and complete setup
  i Xcode JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
    Xcode JAVA_HOME can be configured in Xcode -> Preferences -> Locations -> Custom Paths
```

**Versions**
- OS version(s)* (required for Desktop and iOS issues): macOS Ventura 13.3.1 (a)
- OS architecture (x86 or arm64): arm64

MacBook Pro M2

**Comment by gosr** [comment]
This may be a hint:

After some googling, I fired off the command `sudo xcodebuild -installComponents` which printed:
`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

Based on further googling, I then ran the command `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`.

Now the `kdoctor` command gives me a nice green checkmark next to Xcode.

Perhaps this information could be used to increase the usability of the `kdoctor` output in case of errors regarding Xcode.

**Comment by AlexeyTsvetkov** [comment]
@gosr Hi! Thanks for the report and providing the solution! The kdoctor is developed by a different team in a different repository, so I'm closing this issue.
Here is the relevant issue in kdoctor repository https://github.com/Kotlin/kdoctor/issues/34

**Comment by olukayodepaul** [comment]
thanks for the great work

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3186">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
