### ISSUE TITLE
Gradle task runDistributable in IntelliJ is skipping modules

### ISSUE THREAD

**Issue by garretyoder** [JetBrains/compose-multiplatform#3188]
I am using another library that in the background somewhere links to com.sun.net.httpserver. While just using the gradle run task, everything works fine. When I create a distributable, it seems to skip linking this and it exits with a ClassNotFoundException.

I found an old build of this library on the maven central repo and linked it in gradle and resolved that, however now it's also missing java.lang.management.ManagementFactory which is odd if it's in the greater java.lang.* group.

Is there something I'm missing in the gradle file or is this a bug? this isn't the release distributable task so proguard isn't involved yet where it could be skipping modules. In theory the entire JDK (openJDK 17) should be linked. 

**Affected platforms**
- Desktop

**Versions**
- 1.8.2
- Compose Multiplatform version*: 1.4
- OS version(s)* MacOS
- OS architecture am64
- JDK (for desktop issues): OpenJDK 17

**To Reproduce**
- Build a project using MS Graph & Compose, run the runDistributable gradle task.

**Comment by garretyoder** [comment]
Resolved on my own. For anyone who comes across on google, the documentation does actually go over this and I glossed past it. You have to manually specify modules outside of the stdlib. See https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Native_distributions_and_local_execution/README.md

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3188">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
