### ISSUE TITLE
the state will be lost when using desktop Compose in the toolwindow of the idea plugin

### ISSUE THREAD

**Issue by whataa** [JetBrains/compose-multiplatform#3191]
**Describe the bug**

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): macOS
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 11

**To Reproduce**
1. create a sample idea plugin project, setup compose dependencies
2. write  some @Composable UI, use mutablestate variable and modify it when clicked for example
3. add one toolwindow and put the composeUI into it
4. open toolwindow and modify mutablestate, then hide and reopen the toolwindow

You will find that the state of @composable UI is reset

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3191">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
