### ISSUE TITLE
White Screen when adding SelectionContainer Composable in Web

### ISSUE THREAD

**Issue by MohamedRejeb** [JetBrains/compose-multiplatform#3195]
Currently adding `SelectionContainer` to the screen blocks the main thread for a bit and makes the whole screen white, you won't get any error to know what's the problem. I was just removing things to see what's wrong and removing `SelectionContainer` fixed the problem.

Target: Compose Web
Version: 1.4.0

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3195">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
