### ISSUE TITLE
Some links not pointing to the correct location in FAQ docs.

### ISSUE THREAD

**Issue by megabyte6** [JetBrains/compose-multiplatform#3197]
**Describe the bug**
This is a small issue but I decided to submit it here and someone can fix it when they get to it. On the FAQ [here](https://github.com/JetBrains/compose-multiplatform/blob/master/docs/FAQ.md), a few links no longer point to the correct location. For example, [the link that says "this page"](https://github.com/JetBrains/compose-multiplatform/blob/master/docs/FAQ.md#:~:text=more%20tutorials%20on-,this%20page,-.) should point to [this](https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/README.md) but it does not. Probably from a move or something. Another case is [the link that says "multiple examples for all platforms"](https://github.com/JetBrains/compose-multiplatform/blob/master/docs/FAQ.md#:~:text=multiple%20examples%20for%20all%20platforms) that should point to [here](https://github.com/JetBrains/compose-multiplatform/blob/master/examples/README.md)

**Affected platforms**
Select one of the platforms below:
- [ ] All
- [ ] Desktop
- [ ] Web (K/Wasm) - Canvas based API
- [ ] Web (K/JS) - Canvas based API
- [ ] Web (K/JS) - HTML library
- [ ] iOS
- [x] Other (Docs)

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: n/a
- Compose Multiplatform version*: n/a
- OS version(s)* (required for Desktop and iOS issues): n/a
- OS architecture (x86 or arm64): n/a
- JDK (for desktop issues): n/a

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Go to the [FAQ Docs](https://github.com/JetBrains/compose-multiplatform/blob/master/docs/FAQ.md)
2. Click through the links.

**Expected behavior**
Explained in the description.

**Screenshots**
This is what it looks like when you click the tutorial link:
![image](https://github.com/JetBrains/compose-multiplatform/assets/72172597/237e131a-0453-4c7b-8659-ffc694d9e316)
This is what it should link to:
![image](https://github.com/JetBrains/compose-multiplatform/assets/72172597/03201f7f-96a2-49f8-91a4-ab7d6d75b36f)

**Additional context**
None

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3197">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
