### ISSUE TITLE
Dock Panel App icon create two luncher icons

### ISSUE THREAD

**Issue by SudoDios** [JetBrains/compose-multiplatform#3200]
new window create new icon on dock panel!
How to to merge all windows to one icon on dock panel
![IJ3Aa.jpg](https://github.com/JetBrains/compose-multiplatform/assets/62701838/82dbbe5c-5a00-434d-b96a-3ef5e5f9eeba)
https://askubuntu.com/questions/1144214/why-does-my-custom-launcher-file-create-two-icons-on-the-launcher-bar

How to fix in compose ?

**Comment by dima-avdeev-jb** [comment]
Thanks for the Issue description!
Can you please also provide that exact Ubuntu version do you use?
And can you please create a minimal reproducible sample of this problem and share it on GitHub?

**Comment by SudoDios** [comment]
you're welcome.
my ubuntu version (Ubuntu 20.04.6 LTS) gnome version (3.36.8) X11
I will soon publish the project I am working on in GitHub. 
But if you want another example, you have to wait a little.
But in my opinion, there is no need to build a sample project.
When I make dep file from the raw project, it has the same problem.

**Comment by dima-avdeev-jb** [comment]
Is it reproduced on a template project https://github.com/JetBrains/compose-multiplatform-desktop-template ?

**Comment by dima-avdeev-jb** [comment]
I found another issue with this bug:
I will close this one and you can follow the previously created issue:
https://github.com/JetBrains/compose-multiplatform/issues/956

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3200">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
