### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by DRSchlaubi** [JetBrains/compose-multiplatform#3202]
The ability to build distributions for compose applications is really useful, however, only supporting `dpkg`  is very limiting. 

Because supporting every package manager out there might be a lot of work, mit would make sense to distribute the application as a flatpak as it's independent of the linux distribution

It shouldn't be too hard to implement I might do a PR if you're interested in supporting it.

Documentation: https://docs.flatpak.org/en/latest/first-build.html

**Comment by dima-avdeev-jb** [comment]
@AlexeyTsvetkov That do you think? Do we need support of **flatpak** distribution?

**Comment by AChep** [comment]
This would be amazing to have.

**Comment by DRSchlaubi** [comment]
> This would be amazing to have.

You can do that now, I have my app [on flathub](https://github.com/flathub/dev.schlaubi.Tonbrett) although it requires some additional setup

**Comment by DRSchlaubi** [comment]
But first party Support would be great for more modern formats like flatpak and msix, sadly oracle doesn't seem to really have plans to add them to jpackage, however adding them is still fairly easy

**Comment by mipastgt** [comment]
There are more and more requests for flatpak. Just got [one more](https://github.com/mipastgt/AIPBrowserDE-Public/issues/5) from a user.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3202">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
