### ISSUE TITLE
Composed into the View which doesn't propagate ViewTreeLifecycleOwner!

### ISSUE THREAD

**Issue by HGaurav328** [JetBrains/compose-multiplatform#3203]
Fatal Exception: java.lang.IllegalStateException: Composed into the View which doesn't propagate ViewTreeLifecycleOwner! at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1157) at android.view.View.dispatchAttachedToWindow(View.java:20714) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3538) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3545) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3545) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3545) at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3545) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2658) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2161) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8634) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031) at android.view.Choreographer.doCallbacks(Choreographer.java:849) at android.view.Choreographer.doFrame(Choreographer.java:779) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:257) at android.app.ActivityThread.main(ActivityThread.java:8155) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by dima-avdeev-jb** [comment]
Hello! Thanks for the bug description. 

Can you please add more context:
Are you having an Android only Compose project?
What project are you trying to launch?

**Comment by dima-avdeev-jb** [comment]
Can you please create a minimal reproducible sample of this problem and share it on GitHub?

**Comment by alexzhirkevich** [comment]
Slack discussion: https://app.slack.com/client/T09229ZC6/CJLTWPH7S/thread/CJLTWPH7S-1684844945.124319

**Comment by Prithuld** [comment]
We are also facing similar issue , any root cause found?

**Comment by MatkovIvan** [comment]
Compose multiplatform uses original Google's binaries on Android - ANY fixes for android should be made in AOSP, not in this fork. Please report/track this issue in [Google issue tracker](https://issuetracker.google.com/issues/new?component=612128)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3203">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
