### ISSUE TITLE
SwingPanel doesn't respect clipping

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#3207]
**Describe the bug**
SwingPanel contents don't respect clipping set on themselves nor their parents. This is especially problematic when used in a scrollable container that has other composable around it along the scroll axis.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.7.20
- Compose Multiplatform version*: 1.2.1
- OS version(s)* (required for Desktop and iOS issues): macOS Ventura, Swing
- OS architecture (x86 or arm64): arm64 but irrelevant
- JDK (for desktop issues): 17

**To Reproduce**
1. Create a Box, set a fixed size on it, and clipToBounds
2. Add a SwingPanel inside with a Swing component that's larger than the Box
3. Observe that the SwingPanel content doesn't respect the clipping

**Expected behavior**
Clipping should always be respected

**Comment by MatkovIvan** [comment]
Should be mitigated by https://github.com/JetBrains/compose-multiplatform-core/pull/915

**Comment by MatkovIvan** [comment]
Actually, it works even without https://github.com/JetBrains/compose-multiplatform-core/pull/915

The most likely fix is https://github.com/JetBrains/compose-multiplatform-core/pull/922 (not sure, there are a few changes there). Anyway, it should work in 1.6.0. Please let me know if it doesn't

**Comment by MatkovIvan** [comment]
Ah. It sets bounds instead of actual clipping now. Reopening


https://github.com/JetBrains/compose-multiplatform/assets/1836384/84f093a6-4c45-4d2b-aa50-a48e83023c5e

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3207">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
