### ISSUE TITLE
Switch to notarytool

### ISSUE THREAD

**Issue by DRSchlaubi** [JetBrains/compose-multiplatform#3208]
Currently both the [guide](https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Signing_and_notarization_on_macOS/README.md) [gradle plugin](https://github.com/JetBrains/compose-multiplatform/blob/dab4531fe4ffe8509ac4ce7a7336f1016960d67c/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/tasks/AbstractUploadAppForNotarizationTask.kt#L42) use`altool` which has been deprecated in favor of [notarytool](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow#3087734)

**Comment by bnovakovic** [comment]
Starting November this year, `atool` will be unsupported for notarization. Do we have any ETA for this task?

**Comment by igordmn** [comment]
Setting `p:high` as `altool` will stop working on [2023-11-01](https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3208">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
