### ISSUE TITLE
DropdownMenu outside click

### ISSUE THREAD

**Issue by SudoDios** [JetBrains/compose-multiplatform#3209]
**HI. When the menu is open, things outside of it should not be clicked
But here are the keys**

**Affected platforms**
- Desktop

**Versions**
- Kotlin version : 1.8.0 
- Compose Multiplatform version : 1.3.0
- OS version : Ubuntu 20.04.6 LTS  

**Screen shot**
![scr_err](https://github.com/JetBrains/compose-multiplatform/assets/62701838/0c307848-0640-47c7-a8ac-afd095018fe1)

**Comment by dima-avdeev-jb** [comment]
Thanks.
Maybe we can add the possibility to filter clicks outside the DropdownMenu.

For now, you can use `Box(Modifier.fillMaxSize().clickable{  })` between UI elements and the DropdownMenu.
Also, you can add .background(Color.Black.copy(alpha = 0.5f)) for shadow in this Box.

**Comment by SudoDios** [comment]
thanks a lot.  
But this is not a basic task, the **popup** itself should handle this issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3209">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
