### ISSUE TITLE
Revert a commit after Jetpack Compose 1.5 merging

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3211]
After merging Jetpack Compose 1.4.3, we discovered that some tests are failing. That was fixed in Jetpack Compose 1.5 branch.

We disabled these tests in the commit `3a9237839569298854ee96a2accbe5e2313c5892`. After we merge Jetpack Compose 1.5, we should revert it.

The tests are failing because in 1.4.3 we don't have [a fix](https://android-review.googlesource.com/c/platform/frameworks/support/+/2469922) for Compose Compiler. We don't build it from the main branch, so there is no issues in the production libraries.

[The 1.4.3 merge PR](https://github.com/JetBrains/compose-multiplatform-core/pull/580/files)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3211">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
