### ISSUE TITLE
Launching on iOS failed after adding org.jetbrains.compose dependency

### ISSUE THREAD

**Issue by turkovsky** [JetBrains/compose-multiplatform#3212]
**Describe the bug**
After adding org.jetbrains.compose dependency to gradle of shared module iOS configuration stops building

Adding/removing `id("org.jetbrains.compose")` into block `plugins` leads to appearing/disappearing of this error
(even without any dependencies in `sourceSets`)

Error log:
> Task :shared:linkDebugFrameworkIosX64 FAILED
e: Module "org.jetbrains.compose.runtime:runtime-saveable (org.jetbrains.compose.runtime:runtime-saveable-uikitx64)" has a reference to symbol androidx.compose.runtime/remember|-2215966373931868872[0]. Neither the module itself nor its dependencies contain such declaration.

> This could happen if the required dependency is missing in the project. Or if there is a dependency of "org.jetbrains.compose.runtime:runtime-saveable (org.jetbrains.compose.runtime:runtime-saveable-uikitx64)" that has a different version in the project than the version that "org.jetbrains.compose.runtime:runtime-saveable (org.jetbrains.compose.runtime:runtime-saveable-uikitx64): 1.4.0" was initially compiled with. Please check that the project configuration is correct and has consistent versions of all required dependencies.

> The list of "org.jetbrains.compose.runtime:runtime-saveable (org.jetbrains.compose.runtime:runtime-saveable-uikitx64): 1.4.0" dependencies that may lead to conflicts:
> 1. "stdlib: 1.8.10" (was initially compiled with "stdlib: 1.6.20")
> 2. "org.jetbrains.kotlin.native.platform.CoreFoundation: 1.8.10" (was initially compiled with "org.jetbrains.kotlin.native.platform.CoreFoundation: 1.6.21")
> 3. "org.jetbrains.kotlin.native.platform.darwin: 1.8.10" (was initially compiled with "org.jetbrains.kotlin.native.platform.darwin: 1.6.21")
> 4. "org.jetbrains.kotlin.native.platform.posix: 1.8.10" (was initially compiled with "org.jetbrains.kotlin.native.platform.posix: 1.6.20")
> 5. "org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.3" (was initially compiled with "org.jetbrains.kotlinx:atomicfu (org.jetbrains.kotlinx:atomicfu-iosx64): 0.17.0")
> 6. "org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64): 1.6.4" (was initially compiled with "org.jetbrains.kotlinx:kotlinx-coroutines-core (org.jetbrains.kotlinx:kotlinx-coroutines-core-iosx64)")

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): 16.4(simulator) and 15.5 (physical)
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**Additional context**
build.gradle top level:
```
plugins {
    id("com.android.application").version(Versions.agp).apply(false)
    id("com.android.library").version(Versions.agp).apply(false)
    kotlin("android").version(Versions.kotlin).apply(false)
    kotlin("multiplatform").version(Versions.kotlin).apply(false)
    id("org.jetbrains.compose").version(Versions.compose).apply(false)
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }
}
```

Versions:
```
object Versions {
    const val kotlin = "1.8.10"
    const val compose = "1.4.0"
    const val agp = "8.0.2"
}
```

**Comment by dima-avdeev-jb** [comment]
I think you can try to add `isStatic=true`, as in the template project:
https://github.com/JetBrains/compose-multiplatform-template/blob/main/shared/build.gradle.kts#L25

Also, you should add `kotlin.native.cacheKind=none` at gradle.properties file:
https://github.com/JetBrains/compose-multiplatform-template/blob/main/gradle.properties#L14

**Comment by turkovsky** [comment]
Thanks @dima-avdeev-jb , you pushed me on right direction
First of all - I didn't use cocoapods in project
So, I created new one with cocoapods
Tried different things. But, it seems that it works only with both of your solutions

So, at the end I could launch iOS app with Jetpack Compose UI

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3212">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
