### ISSUE TITLE
Support Kotlin 1.8.21

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#3214]
Kotlin 1.8.21 is not present on the [compatibility chart](https://github.com/JetBrains/compose-multiplatform/blob/master/VERSIONING.md#kotlin-compatibility), and using this kotlin version produces a warning or error.

**Comment by dima-avdeev-jb** [comment]
Thanks. We will fix it.

While you waiting, you can check the RC version of our compiler plugin.
To do this, add these lines to all your gradle modules:
```
compose {
    kotlinCompilerPlugin.set("org.jetbrains.compose.compiler:compiler:1.4.7-rc01")
    kotlinCompilerPluginArgs.add("suppressKotlinVersionCompatibilityCheck=1.8.21")
}
```

**Comment by JakeWharton** [comment]
Would be great to have your release support .22 as well since it's such [an exceedingly minor bump](https://github.com/JetBrains/kotlin/compare/v1.8.21...v1.8.22) (with no impact on a compiler plugins).

**Comment by JakeWharton** [comment]
JB Compose compiler 1.4.7 out yesterday supports 1.8.21 but does NOT support 1.8.22 😬.

**Comment by dima-avdeev-jb** [comment]
> JB Compose compiler 1.4.7 out yesterday supports 1.8.21 but does NOT support 1.8.22 😬.

Yeah, we are waiting for Google JetPack Compose compiler with support for 1.8.22 for now

**Comment by JakeWharton** [comment]
It's out today as 1.4.8. Would be amazing to get a fast-follow from you all so we can all be up-to-date before 1.9.

**Comment by dima-avdeev-jb** [comment]
@eymar Do we plan to publish new Compose compiler with Kotlin 1.8.22 before next release of Compose Multiplatform?

**Comment by eymar** [comment]
> Do we plan to publish new Compose compiler with Kotlin 1.8.22 before next release of Compose Multiplatform?

It was not planned. Anyway, here it is: https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/compiler/compiler/1.4.8/

it requires:
```kotlin
compose {
    kotlinCompilerPlugin.set("1.4.8")
}
```

cc: @JakeWharton

**Comment by eymar** [comment]
kotlin 1.8.21 is currently supported with:

```kotlin
compose {
    kotlinCompilerPlugin.set("1.4.7")
}
```

closing this issue.

**Comment by JakeWharton** [comment]
Thanks! Will that get synchronized to Maven Central so we can rely on it in places other than Compose UI multiplatform?

**Comment by JakeWharton** [comment]
Just got the notification. Many thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3214">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
