### ISSUE TITLE
[iOS] Composable doesn't recompose when screen orientation changes

### ISSUE THREAD

**Issue by JunkFood02** [JetBrains/compose-multiplatform#3215]
**Describe the bug**
Composable doesn't recompose when screen orientation changes

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
Using the [Compose for iOS template](https://github.com/JetBrains/compose-multiplatform-ios-android-template/#readme)

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
Add `println("Screen rotated!")` in the `App()` function, then rotate the iOS simulator (command + left/right)
The message shows as expected on Android emulator but not on a iOS simulator

**Expected behavior**
Composable recompose when screen orientation changes on iOS

**Additional context**
Might be a duplicate of #2855

**Comment by sergeshustoff** [comment]
Any workarounds for this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3215">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
