### ISSUE TITLE
Support drag&drop of text to other applications and to other text fields

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#322]

**Comment by prepor** [comment]
It's not only about TextField, but text in general

**Comment by prepor** [comment]
https://user-images.githubusercontent.com/2827/106172203-d5803200-6192-11eb-9326-969ccf31f6ea.mov

simple reference

**Comment by igordmn** [comment]
On web it is needed as well: https://github.com/JetBrains/compose-multiplatform/issues/4053

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6023">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
