### ISSUE TITLE
Compose for Desktop: TextField can't input Chinese!

### ISSUE THREAD

**Issue by JustYummy** [JetBrains/compose-multiplatform#3221]
**Describe the bug**
Can not input any Chinese when I using compose for desktop, I also testing the official sample. code: [Jewel New UI Sample](https://github.com/JetBrains/jewel), it has the same result. The input method box is not on right location, when I selected any suggestion it can not input.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): macOS 13.4 (22F66)
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): jbr 17.0.6

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Run the sample  [Jewel New UI Sample](https://github.com/JetBrains/jewel)
2. Set TextField to be editable
3. Using Input method to Input  Chinese character
4. Textfield can't receive Chinese character

**Expected behavior**
Chinese character should be on the textField box.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/16171813/56606eea-813a-4f8e-ab28-302cc546507d

**Comment by JustYummy** [comment]
> I tried to reproduce on my mac x86 (os version - 12.5.1).
> 
> It works, although I'm not sure what I'm typing and wheter I've chose the correct input source (I tried several).
> 
> <img alt="Screenshot 2023-05-31 at 14 20 38" width="536" src="https://user-images.githubusercontent.com/7372778/242273275-eb340bc0-d727-4776-8dfd-00ed673b62f7.png">
> What input source do you use?
> 
>  chinese_input_compose.mov

Thank you for reply!
I'm using JBR SDK, version `17.0.7`. If I change SDK to others such as Azul Zulu version `17.0.1`, and it's OK.
<img width="724" alt="1" src="https://github.com/JetBrains/compose-multiplatform/assets/16171813/decf486a-ab17-4734-b3cc-fb86acd6011b">
<img width="512" alt="2" src="https://github.com/JetBrains/compose-multiplatform/assets/16171813/ba129994-ee4b-4955-a052-3a28a1295d35">
But Zulu version can't hide the macOS default window title bar.
<img width="956" alt="3" src="https://github.com/JetBrains/compose-multiplatform/assets/16171813/43a8cdb5-2636-4fd5-8524-a6f90610f410">
<img width="933" alt="4" src="https://github.com/JetBrains/compose-multiplatform/assets/16171813/1bb14ee0-ae15-4fd0-996e-1ea24a9f001f">
may be is something wrong when using Compose with JBR.

same issue [BasicTextField could not input any Chinese character when using JBR](https://github.com/JetBrains/compose-multiplatform/issues/2628)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3221">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
