### ISSUE TITLE
BlendMode does not work correctly on Metal

### ISSUE THREAD

**Issue by MatkovIvan** [JetBrains/compose-multiplatform#3222]
**Affected platforms**
Select one of the platforms below:
- macOS
- iOS

**Versions**
- Compose Multiplatform version*: 1.4.0

**To Reproduce**
Try to use `blendMode` inside canvas

```kt
Canvas(Modifier.fillMaxSize()) {
    val radius = size.minDimension / 4
    drawCircle(
        Color.Red,
        center = Offset(center.x - radius / 2, center.y),
        radius = radius,
        alpha = 0.5f,
    )

    drawCircle(
        Color.Red,
        center = Offset(center.x + radius / 2, center.y),
        radius = radius,
        alpha = 0.5f,
        blendMode = MODE
    )
}
```

**Expected behavior**
Same as Android

**Screenshots**
<img width="1569" alt="Screenshot 2023-05-31 at 12 05 07" src="https://github.com/JetBrains/compose-multiplatform/assets/1836384/5cd1d8e2-c21a-4b7f-82d4-4f370ca496ec">
<img width="1569" alt="Screenshot 2023-05-31 at 12 05 35" src="https://github.com/JetBrains/compose-multiplatform/assets/1836384/2692287a-3962-424b-ad08-00d2e18ebd23">
<img width="1569" alt="Screenshot 2023-05-31 at 12 05 47" src="https://github.com/JetBrains/compose-multiplatform/assets/1836384/5abb0981-6c8a-4ca1-bfad-f12ff6b51a55">

**Additional context**
https://github.com/JetBrains/compose-multiplatform/issues/2034
https://kotlinlang.slack.com/archives/C0346LWVBJ4/p1685512898934519
https://skia.org/docs/user/api/skblendmode_overview/

**Comment by MohamedRejeb** [comment]
Is the iOS fix going to be published in one of the dev versions soon ?

**Comment by MatkovIvan** [comment]
It will be available on some version, sure. I doubt that it will be included in the next one since skiko should be released first.

**Comment by MatkovIvan** [comment]
@MohamedRejeb [1.5.0-dev1082](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0-dev1082) contains the fix

**Comment by MohamedRejeb** [comment]
@MatkovIvan Thanks I'll give it a try

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3222">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
