### ISSUE TITLE
Backspace+shift does nothing in BasicTextField

### ISSUE THREAD

**Issue by mcpiroman** [JetBrains/compose-multiplatform#3226]
**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*:  1.5.0-dev1049
- OS version(s)* (required for Desktop and iOS issues): Windows NT 10.0.19045.0
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 19.0.2

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Add `BasicTextField`
2. Write something into it
3. Press backspace
4. One character is removed
5. Press backspace while holding left shift
6. Nothing happens

**Expected behavior**

Shift should have no effect on backspace.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3226">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
