### ISSUE TITLE
[Kotlin 1.9.0-Beta] KJS/Serialization/Compose: NullPointerException during compilation when Compose plugin is present

### ISSUE THREAD

**Issue by OliverO2** [JetBrains/compose-multiplatform#3229]
**Describe the bug**
Kotlin 1.9.0-Beta with the current master version of the Compose Multiplatform plugin fails to compile the following declaration for Js:

```
import kotlinx.serialization.Serializable

@Serializable
class MyClass(val s: String)
```

**Affected platforms**
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library

**Versions**
- Kotlin version*: 1.9.0-Beta
- Compose Multiplatform version*: [Compose Multiplatform Gradle plugin](https://github.com/JetBrains/compose-multiplatform/tree/master/gradle-plugins) at commit dab4531fe4ffe8509ac4ce7a7336f1016960d67c
- Jetpack Compose Compiler version: [androidx.compose.compiler:compiler:1.4.7-dev-k1.9.0-Beta-bb7dc8b44eb](https://androidx.dev/storage/compose-compiler/repository)

**To Reproduce**
[KT-58911](https://youtrack.jetbrains.com/issue/KT-58911) contains a reproducer. A description is provided under the heading "To reproduce".

**Additional context**
This may be similar to the former #2635, also tracked as [KT-55746](https://youtrack.jetbrains.com/issue/KT-55746).

**Comment by OliverO2** [comment]
It seems that https://github.com/JetBrains/compose-multiplatform-core/commit/bd69f1f128addaa4b36a9563c221acb03a33063c did not make it into the Google monorepo, so even the latest versions of the Jetpack Compose compiler are still missing this fix.

**Comment by eymar** [comment]
A note for the future issue readers:

Indeed, the fix was not upstreamed and that's why the Jetpack Compose compiler plugin version doesn't work:
> Jetpack Compose Compiler version: [androidx.compose.compiler:compiler:1.4.7-dev-k1.9.0-Beta-bb7dc8b44eb](https://androidx.dev/storage/compose-compiler/repository)
___

I would close this issue if you don't mind since the root issue is fixed. And upstreaming the changes from our fork to jetpack compose is a separate task involving this and a few other fixes/workarounds.
