### ISSUE TITLE
TextField should not use text cursor when disabled

### ISSUE THREAD

**Issue by adrientetar** [JetBrains/compose-multiplatform#3231]
Currently, BasicTextField uses a text (selection caret) pointer icon (aka, cursor) even when it's disabled. When enabled=false is set, the normal arrow pointer icon should be used since it's not possible to interact with the control.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3231">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
