### ISSUE TITLE
Compose Web JS is Needed

### ISSUE THREAD

**Issue by bgcl** [JetBrains/compose-multiplatform#3232]
A few months ago I proudly wrote my web app in Kotlin using Compose for Web.

It was a beautiful thing. It just worked in normal browsers. I loved showing it off to my developer friends, emphasizing that even the CSS was in Kotlin.

Alas, when this week I returned to further develop the app -- it's all gone :-( Compose for Web no longer seems to compile to JS. It seems to compile to wasm, which means it doesn't work in normal browsers.

Here's the key problem -- while wasm is good, how could anyone get their users to upgrade their browsers or apply a special flag to get wasm to work?

Is there really no way to compile to javascript so it just runs on normal users browsers? I really hope I am mistaken in understanding that even when compose is fully implemented on wasm development, it will still need months to years of upgrades to propagate in user-land, before we can successfully consider using production apps. (I'm staring at nodjs/React hell as I write this .. please tell me there's a way to get back the beautiful Compose web I saw and used just a few months ago)

**Comment by alexzhirkevich** [comment]
Compose js isn't gone. It was just renamed to Compose HTML. You still can use it like before!

**Comment by bgcl** [comment]
wow, so glad to hear that. thank you so much @alexzhirkevich   I will close this issue and look forward to requesting help with compile errors instead, if any : )

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3232">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
