### ISSUE TITLE
jlink error

### ISSUE THREAD

**Issue by zoga-com** [JetBrains/compose-multiplatform#3235]
**Describe the bug**
Doesn't compile with jlink error.
```
> Task :createRuntimeImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createRuntimeImage'.
> External tool execution failed:
  * Command: [/usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc38.x86_64/bin/jlink, @/home/dima/IdeaProjects/minecraft-launcher/build/compose/tmp/createRuntimeImage.args.txt]
  * Working dir: []
  * Exit code: 2
  * Standard output log: /home/dima/IdeaProjects/minecraft-launcher/build/compose/logs/createRuntimeImage/jlink-2023-06-05-11-21-31-out.txt
  * Error log: /home/dima/IdeaProjects/minecraft-launcher/build/compose/logs/createRuntimeImage/jlink-2023-06-05-11-21-31-err.txt
```
Error log is empty. 
Output log:
```
Error: --module-path is not specified and this runtime image does not contain jmods directory.
Usage: jlink <options> --module-path <modulepath> --add-modules <module>[,<module>...]
Use --help for a list of possible options
```

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*:  1.8.0
- Compose Multiplatform version*:  1.3.0
- OS version(s)* (required for Desktop and iOS issues):  Fedora 38 
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 17.0.6

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create Compose project on IDEA
2. Go to project
3. Compile with ./gradlew package

**Expected behavior**
App compiled.

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/42349670/879ff1fd-51c8-42f1-bd2f-fa123154490b)

**Additional context**
--

**Comment by OliverRhyme** [comment]
This is also happening with the Compose KMM template. Unedited template will throw the error

**Comment by RandyWei** [comment]
> I know the cause of the problem, It is because I am using the bundled java jdk (jbr). It dosent have the jmods directory. Changing the jdk to openjdk (or iguess to any jdk that have jmods directory) fixed the problem

Thanks! Fixed the problem

**Comment by Goooler** [comment]
Check https://github.com/JetBrains/JetBrainsRuntime.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3235">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
