### ISSUE TITLE
1.4.0 painterResource Image in LazyLists issue

### ISSUE THREAD

**Issue by snakemr** [JetBrains/compose-multiplatform#3236]
**Describe the bug**
Images from painterResource in all Lazy Lists, Rows, Pagers etc are wrong after scrolling.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*:  1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): windows 10
- OS architecture (x86 or arm64):  x86-64
- JDK (for desktop issues): jbr-17

**To Reproduce**
very simple project:

val fruits = List(8) { "p${it+1}.jpg" }

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        MaterialTheme {
            LazyColumn(horizontalAlignment = Alignment.CenterHorizontally) {
                repeat(100) {
                    items(fruits) {
                        Image(painterResource(it), it)
                        Text(it)
                        Divider()
                    }
                }
            }
        }
    }
}

Fruits are jpg images p1.jpg .. p8.jpg in resources. e.g., p1.jpg == apple

**Expected behavior**
At start, images are corerct. 
Compose 1.3.1: After any scroll, images are corect.
Compose 1.4.0: After some scroll, images shuffles, e.g., p1 == banana

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/56929990/652aef88-b7c3-45fc-a051-285676d5fd01)
![image](https://github.com/JetBrains/compose-multiplatform/assets/56929990/4093004c-6bc4-447d-87a2-4d46a2289552)

**Comment by MatkovIvan** [comment]
Looks like #3189 duplicate

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3236">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
