### ISSUE TITLE
Cannot click on scaled content in 1.4.0

### ISSUE THREAD

**Issue by Syer10** [JetBrains/compose-multiplatform#3238]
**Describe the bug**
In one of the apps I develop I scale the UI based on the window size, this worked great since it allowed for standard screen sizes in my app. This feature broke when I updated the app to 1.4.0 today, making the app unusable. 

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): Temurin 17.0.6

**To Reproduce**
- Clone sample project: https://github.com/Syer10/compose-scaling-issue
- Hover over a button and click on it, it does not make the button click

**Expected behavior**
Clicking in the app clicks the button the curser is on

**Additional context**
This worked previously in Compose 1.3.0 with Kotlin 1.8.0

**Comment by alexzhirkevich** [comment]
It's really annoying thing. I also develop an app when scaling is almost a key feature and this issue breaks everything. Maybe `p:high`?

**Comment by MatkovIvan** [comment]
Yep, it's a duplicate. The fix is on the way.
Closing this one, please follow #3230

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3238">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
