### ISSUE TITLE
Canvas image goes beyond the canvas

### ISSUE THREAD

**Issue by vastausf** [JetBrains/compose-multiplatform#324]
If I set the size of the canvas to be smaller than the size of what I am drawing (canvas 50x25, square 100x50), then the image on the canvas does not appear (as it should be), but goes beyond the canvas

```
fun main() = Window {
	MaterialTheme {
		Column(
			modifier = Modifier
				.fillMaxSize(),
			horizontalAlignment = Alignment.CenterHorizontally,
			verticalArrangement = Arrangement.Center
		) {
			buildCircle()
		}
	}
}

@Composable
fun buildCircle() {
	Canvas(
		modifier = Modifier
			.background(Color.Black)
			.size(50f.dp, 25f.dp)
	) {
		drawRect(
			color = Color.Blue,
			topLeft = Offset(0f, 0f),
			size = Size(100f, 50f)
		)
	}
}
```

![image](https://user-images.githubusercontent.com/28383763/106173087-9b1f9080-61a4-11eb-801b-039b3da529a5.png)

**Comment by jimgoog** [comment]
Is the behavior the same on Android?  Typically, if you want clipping, you need to turn that on explicitly.

**Comment by igordmn** [comment]
The behavior is the same on Android.

Most of the components don't clip child components by default.

You need to explicitly set clipping with 'clipToBounds':

```
Canvas(
    modifier = Modifier
        .background(Color.Black)
        .size(5f.dp, 5f.dp)
        .clipToBounds()
)
```

@jimgoog, what do you think, should we apply clipToBounds() to Canvas by default?

It is applied to verticalScroll/horizontalScroll/LazyList/Image/Surface.

**Comment by vastausf** [comment]
clipToBounds() works
It also seems to me that .clipToBounds() should be used by default, because by default nothing should go beyond the canvas.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6381">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
