### ISSUE TITLE
distribute and use .so files for linux platform

### ISSUE THREAD

**Issue by Lefix2** [JetBrains/compose-multiplatform#3240]
Hello,

I'm struggling while installing/loading some dynamic libraries into my app.

I'm currently developing only for Linux but i want to be "future-proof" for possible windows port of my application.

Currently, i have so custom .so files, some used with jni, that i want to embed in my App without creating an AppImage.

The solution I found is to put my libraries into ${PROJECT_DIR}/main/resources/linux/lib/*.so and addig the following lines to my build.gradle:

```
compose.desktop {
    application {
        mainClass = "ManufacturingHostKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageVersion = "1.0.0"

            appResourcesRootDir.set(project.layout.projectDirectory.dir("resources"))
        }
    }
}
```

Then in my application load libraries with:
```

val resourcesDir = File(System.getProperty("compose.application.resources.dir"))
System.load(resourcesDir.resolve("lib/libMylib.so").path)
```
Note that calling a .so is platform dependant and I will prefer something like
```
System.loadLibrary("Mylib")
```

But when I create distributable (./gradlew createDistributable) the files are not copied into ```build/compose/binaries/main/app/MyApp/lib/app/resources/```
At runtime, the path to search for library is correct:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: <path-to-my-app>/build/compose/binaries/main/app/MyApp/lib/app/resources/lib/libMylib.so
```

- Kotlin version: jvm v1.8.20 
- Compose Multiplatform version: 1.4

**Comment by m-sasha** [comment]
Does it work when you run the app from the IDE? Only the packaged app fails?

**Comment by Lefix2** [comment]
Yes i tried everything, it fails as for 'run' and 'runDistributable'

I don't mentioned it but manually copying files works

**Comment by m-sasha** [comment]
@AlexeyTsvetkov Can you help here?

By the way, in my app I put resources (although they're not native libs) under `src/main/resources/resource.ext` and they are packaged and loadable with `ClassLoader.getResourceAsStream` without configuring anything in gradle at all.

**Comment by m-sasha** [comment]
@Lefix2 Also, you could ask in our #compose-desktop slack channel; maybe someone could help you faster.

**Comment by Lefix2** [comment]
I've also pointed that:
For my app icon (in src/main/resources/icon.svg), it is loaded when i run the app but it is also not present in the distributable resource folder

**Comment by Lefix2** [comment]
> @Lefix2 Also, you could ask in our #compose-desktop slack channel; maybe someone could help you faster.

I'll do that!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3240">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
