### ISSUE TITLE
Support Kotlin 1.9.0-Beta

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3241]
Adapt Jetpack Compose Compiler [1.4.7-dev-k1.9.0-Beta-bb7dc8b44eb](https://androidx.dev/storage/compose-compiler/repository) for Compose Multiplatform. Build `Compose Multiplatform Compiler 1.4.7-beta`, add use it when `Kotlin 1.9.0-Beta` is used.

**Comment by eymar** [comment]
fixed. we have published 1.4.7.1-beta

**Comment by igordmn** [comment]
iOS target fails on configuration phase with Kotlin 1.9.0-Beta and 1.9.0-RC

[imageviewer.zip](https://github.com/JetBrains/compose-multiplatform/files/11868559/imageviewer.zip)

1.9.0-RC:
```
A problem occurred configuring project ':shared'.
> Cannot change attributes of dependency configuration ':shared:iosArm64CInteropApiElements' after it has been resolved
```
1.9.0-Beta:
```
A problem occurred configuring project ':shared'.
> Cannot change dependencies of dependency configuration ':shared:iosSimulatorArm64TestCompilationApi' after it has been included in dependency resolution.
```

**Comment by eymar** [comment]
I think we need https://github.com/JetBrains/compose-multiplatform/pull/3170 to include into 1.4.1 (compose gradle plugin)
