### ISSUE TITLE
Unknown host 'Этот хост неизвестен (objects.githubusercontent.com)'. You may need to adjust the proxy settings in Gradle.

### ISSUE THREAD

**Issue by Artrosis** [JetBrains/compose-multiplatform#3245]
I'm trying to run an example: https://github.com/Kotlin/kotlin-wasm-examples/tree/main/compose-jetsnack#jetsnack

I run gradlle task :web:wasmRun and get error: Unknown host 'Этот хост неизвестен (objects.githubusercontent.com)'. You may need to adjust the proxy settings in Gradle.

platform - Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*:  1.8.20
- Compose Multiplatform version*: 1.4.0-dev-wasm06
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): 64
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Download example: https://github.com/Kotlin/kotlin-wasm-examples/tree/main/compose-jetsnack#jetsnack
2. Open example in InteliJ IDEA 2023.1.2 Community
3. Wait index
4. run task :web:wasmRun
5. See error

**Expected behavior**
Run example in browser

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/12668763/65f99e97-f9d6-4e69-add7-8f7b8502a4d1)

**Comment by m-sasha** [comment]
Maybe a local DNS issue? What does running `nslookup objects.githubusercontent.com` say?

**Comment by Artrosis** [comment]
пока поставил Yarn вручную

**Comment by m-sasha** [comment]
https://github.com/yarnpkq/yarn/releases/download/v1.22.17/yarn-v1.22.17.tar.gz downloads fine for me.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3245">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
