### ISSUE TITLE
Use `org.gradle.toolchains.foojay-resolver-convention` plugin in templates

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3248]
We have an issue if we create the project template from IDEA wizard. If the template contains:
```
toolchain(17)
```
And user choose to run the project on JDK 11, we will an exception. To solve this, we can add in the template:
```
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
}
```

We need to understand, will we really need that. And if we need, where we should add that (only in the wizard template, or in all our templates).

It is possible, that we will need it anyway starting from [Gradle 8.0.2](https://docs.gradle.org/8.0.2/userguide/toolchains.html#sub:download_repositories).

See [a related issue](https://youtrack.jetbrains.com/issue/KTIJ-25448/When-project-JDK-is-less-than-one-defines-in-jvmToolchain-block-run-with-Idea-fails-with-has-been-compiled-by-a-more-recent) for other IDEA wizards (not Compose) and the same [solution](https://youtrack.jetbrains.com/issue/KTIJ-24912/Add-foojay-toolchains-plugin-into-settings.gradle.kts).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3248">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
