### ISSUE TITLE
Template not work: The project is using an incompatible version (AGP 7.4.2) of the Android Gradle plugin. Latest supported version is AGP 7.2.0 See Android Studio & AGP compatibility options.

### ISSUE THREAD

**Issue by evangerlions** [JetBrains/compose-multiplatform#3249]
**Describe the bug**

**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version*: 
- Compose Multiplatform version*: 
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**To Reproduce**
git clone https://github.com/JetBrains/compose-multiplatform-template
and use IntelliJ IDEA 2022.2.3 (Community Edition) open the folder
trigger gradle sync 
will show 
![image](https://github.com/JetBrains/compose-multiplatform/assets/32103614/9488d51a-4ea5-4c17-a858-7c4619a3fb63)

**Expected behavior**

**Screenshots**

**Additional context**
![image](https://github.com/JetBrains/compose-multiplatform/assets/32103614/259ea3ec-1d7f-4e34-8197-c0e99e02cf55)

**Comment by m-sasha** [comment]
You need to use Android Studio, not IDEA.

**Comment by evangerlions** [comment]
> You need to use Android Studio, not IDEA.

Thanks your answer, BTW how about required Android Studio version? 

I use Android Studio Flamingo | 2022.2.1 Beta 4

But gradle sync has some error like:

Cannot convert object of class org.jetbrains.kotlin.idea.gradleTooling.arguments.CachedExtractedArgsInfoImpl to org.jetbrains.kotlin.idea.projectModel.CachedArgsInfo<?>.
![image](https://github.com/JetBrains/compose-multiplatform/assets/32103614/e799f5e8-1d5a-4bf7-9f61-105bc310f8bb)

**Comment by m-sasha** [comment]
I'm on Android Studio Flamingo | 2022.2.1 Patch 2 and it appears to work for me. Can you try all the steps from https://github.com/JetBrains/compose-multiplatform-template from scratch, using Android Studio?

**Comment by m-sasha** [comment]
Perhaps clearing some cache (gradle and/or Android Studio) will help? Also try the latest stable `Android Studio Flamingo | 2022.2.1 Patch 2`

**Comment by m-sasha** [comment]
Also make sure you have the Kotlin Multiplatform Mobile plugin installed:

<img width="799" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5230206/ca3a68bd-7462-4519-887b-8c8620f078c8">

**Comment by evangerlions** [comment]
> Also make sure you have the Kotlin Multiplatform Mobile plugin installed:
> 
> <img alt="image" width="799" src="https://user-images.githubusercontent.com/5230206/245449947-ca3a68bd-7462-4519-887b-8c8620f078c8.png">

Android Studio Flamingo | 2022.2.1 Patch 2 can work，Thank you very much1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3249">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
