### ISSUE TITLE
Window resize cursor doesn't clear if mouse is down

### ISSUE THREAD

**Issue by adrientetar** [JetBrains/compose-multiplatform#3254]
If you do the following:

1. Press and hold mouse down inside a control
2. Move over to the edge of the window -> the resize cursor shows
3. Go back inside the window -> the resize cursor sticks and doesn't clear

The cursor should clear when leaving the resize area, even if the mouse is currently down on a control (which i think makes that control receive the mouse events?).

Reproduced on MacOS / Compose 1.4.

**Comment by m-sasha** [comment]
Can you post a short reproducer? I can't seem to reproduce the issue with this code, on Mac OS X:
```
fun main() = singleWindowApplication {
    TextField(value = "Text", onValueChange = {})
}
```

**Comment by adrientetar** [comment]
@m-sasha, I reproduced with the compose-multiplatform-desktop-template repository latest commit:

https://github.com/JetBrains/compose-multiplatform/assets/1250894/b3ecc7cd-b5ec-4e59-9fc9-db87228d3f91

I click and drag inside the window, then when dragging to the edge of the window, it changes to <-> and stays that way until I release the mouse. But it should revert back to the previous pointer icon when I stop hovering over the edge of the window.

**Comment by adrientetar** [comment]
Interesting: IntelliJ IDEA has the same behavior as Compose desktop. But native macOS apps revert the cursor back when you return inside the window.

The reason this is undesired for me is I'm making a vector graphics editor, where different tools have different pointer icons. So like when you drag a selection rectangle outside of the screen and come back there is no longer the cursor telling you which tool you're using.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3254">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
