### ISSUE TITLE
Support Material 3 1.1

### ISSUE THREAD

**Issue by serandel** [JetBrains/compose-multiplatform#3256]
Please, add support for, at least, `androidx.compose.material3:material3:1.1.0`.

It has new components, as tooltips, which are very interesting for desktop applications as well.

**Comment by SakurajimaMaii** [comment]
I also have the same need.

**Comment by fflopsi** [comment]
I would really appreciate this, too. The most important thing in 1.1 probably are the date picker composables, because on desktop we cannot just use the Material MDC date picker.

**Comment by chrisbanes** [comment]
Big +1 here. It seems to have landed, and was then reverted in https://github.com/JetBrains/compose-multiplatform-core/pull/463?

**Comment by serandel** [comment]
No pressure but any ETA? Q3? End of year?

**Comment by MatkovIvan** [comment]
We'll ship it as a part of Compose Multiplatform `1.5` release (in case of no big blockers). It will also be available in some 1.5-dev version, but I can't say in which one yet.
The current progress is in [this branch](https://github.com/JetBrains/compose-multiplatform-core/tree/igor.demin/material3-1.1.0) - so far, there are no blockers.

**Comment by mahramane** [comment]
I also have the same need.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3256">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
