### ISSUE TITLE
Support AR/VR it!

### ISSUE THREAD

**Issue by jackhb1999** [JetBrains/compose-multiplatform#3258]
So let's aim for the stars and support making AR/VR apps and games!

**Comment by m-sasha** [comment]
I'm sure we'll eventually do.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3258">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
