### ISSUE TITLE
rememberPagerState() forcing overload error due to mismatch between Compose Foundation versions in androidMain and commonMain

### ISSUE THREAD

**Issue by cryptrr** [JetBrains/compose-multiplatform#3260]
**Describe the bug**

```Using 'rememberPagerState(Int = ..., Float = ...): PagerState' is an error. Please use the overload where you can provide a source of truth for the pageCount.```

I'm using the official compose multiplatform template. [From here](https://github.com/JetBrains/compose-multiplatform-ios-android-template)

androidMain is using foundation  1.5.0-beta01 while commonMain is using 1.4.0

old overloads of rememberPagerState has been force disabled in Foundation 1.5.0-beta with the above error.

So it is impossible to use Pagers in commonMain code because the latest version of foundation available for multiplatform is 1.4.0 and does not have the overloads necessary to compile.

So how to downgrade ```foundation``` in androidMain since i'm not seeing this gradle dependency in the ```val androidMain by getting {}``` block.

Or do I need to copy all the code from foundation 1.5.0-beta?
 
**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Go to https://github.com/JetBrains/compose-multiplatform-ios-android-template and clone
2. Use VerticalPager or HorizontalPager with rememberPagerState()
3. See error ```Using 'rememberPagerState(Int = ..., Float = ...): PagerState' is an error. Please use the overload where you can provide a source of truth for the pageCount.```

**Expected behavior**
The foundation versions should be same or there should be a better way to downgrade

**Comment by cryptrr** [comment]
This error happens during compile time hence the compose compiler must be checking for every usage of rememberPagerState().
So I guess the compose compiler should also be downgraded to prevent this error.

**Comment by m-sasha** [comment]
How did you get `1.5.0-beta` for foundation in `androidMain`?

I added this snipped to inside the `Column` in `App.kt` (in `commonMain`) and it works perfectly for me:
```
            val pagerState = rememberPagerState()
            HorizontalPager(
                pageCount = 10,
                modifier = Modifier.fillMaxWidth().padding(top = 32.dp),
                state = pagerState
            ){
                Text(
                    text = "Page $it",
                    textAlign = TextAlign.Center,
                    modifier = Modifier.fillMaxWidth().background(Color.LightGray).padding(40.dp)
                )
            }
```

### iOS

![Simulator Screenshot - iPhone 14 - 2023-06-13 at 13 11 30](https://github.com/JetBrains/compose-multiplatform/assets/5230206/6a85a4de-52ee-4f81-bdaf-6a4c6ecaa845)

### Android

![Screenshot_1686651105](https://github.com/JetBrains/compose-multiplatform/assets/5230206/b8c5a1d4-094a-4254-a6e6-be5334533644)

**Comment by cryptrr** [comment]
I have no idea :/ This is my androidMain dependencies list 

```
val androidMain by getting {
            dependencies {
                api("androidx.activity:activity-compose:1.7.2")
                implementation("androidx.media3:media3-exoplayer:1.0.2")
                implementation("androidx.media3:media3-ui:1.0.2")
                implementation("androidx.constraintlayout:constraintlayout-compose:1.1.0-alpha10")
                api("androidx.appcompat:appcompat:1.6.1")
                api("androidx.core:core-ktx:1.10.1")
                implementation ("com.github.skydoves:cloudy:0.1.2")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1")
                implementation("com.google.accompanist:accompanist-systemuicontroller:0.31.3-beta")
            }
        }
```

**Comment by cryptrr** [comment]
All of these dependencies are somehow using 1.5.0-beta in androidMain
![Screenshot from 2023-06-13 19-25-41](https://github.com/JetBrains/compose-multiplatform/assets/135767626/4bead26b-56ae-4c68-8740-6d3acd979ebf)

**Comment by cryptrr** [comment]
Thanks. Is downgrading these dependencies the only way to fix this problem?

**Comment by cryptrr** [comment]
Downgrading accompanist to v0.30.1 uses compose 1.4.0 and fixes this.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3260">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
