### ISSUE TITLE
How can i get the window is minimized or no

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#3263]
How can I run a code when the window is minimized or re-displayed?

**Comment by MatkovIvan** [comment]
It sounds like you are looking for this window management API:
```kt
    val state = rememberWindowState()
    state.isMinimized
```

Please follow this tutorial: https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Window_API_new#listening-the-state-of-the-window

**Comment by mahramane** [comment]
So when a window is open, and I enter another window of the same program or another program (not minimized), listen to it and run a code.

**Comment by mahramane** [comment]
@MatkovIvan 
thank you for your guide.
So when a window is open, and I enter another window of the same program or another program (not minimized), listen to it and run a code.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3263">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
