### ISSUE TITLE
Intellij toolwindow with compose content issues with notification pop-up

### ISSUE THREAD

**Issue by YasserDbeis** [JetBrains/compose-multiplatform#3265]
**Describe the bug**
When implementing the content of a Intellij tool window in Compose, a couple issues arise when pop-up/notifications appear.

1. The pop-up gets hidden behind the compose content.
2. The hidden pop-up intercepts the on-click events from when the user clicks on the compose content. As in, because of (1), when you click on the compose content that has the notification behind it, the notification pop-up receives the on-click event, and not the compose content.

**Affected platforms**
Select one of the platforms below:
- Desktop, MacOS Arm

**Versions**
- Kotlin version*: 1.6 (1.8.21 compiler)
- Compose Multiplatform version*: 1.3.1
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
Could not repro it with the intellij-plugin example located here: https://github.com/JetBrains/compose-multiplatform/tree/master/examples/intellij-plugin, but was getting some weird shadows when the notification showed up above the tool window.

Only repro I could do is within Android Studio itself, but I do not believe you have access to that development build. My hope is that that you have this problem already noted internally, and I have on good authority from my contacts with JetBrains that you do.

**Expected behavior**
Should show pop-up notification on top of tool window with compose content with no shadows.

**Comment by m-sasha** [comment]
Yes, we are aware of these issues and are working on them.
@Walingar

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3265">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
