### ISSUE TITLE
rememberWindowState Bug

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#3270]
**Describe the bug**
Hello
When I use rememberWindowState for the state of the window and listen to isMinimized changes, every time I minimize or display the windows, the codes inside the windows are re-executed.
for example :

```
        val state = rememberWindowState(
                placement = WindowPlacement.Maximized, position = WindowPosition.Aligned(Alignment.Center)
            )


        if (state.isMinimized) {
            println("OnPause")
        } else {
            println("OnResume")
        }


        Window(
            onCloseRequest = ::exitApplication,
            title = "حسابداری آینو",
            state = state,
            //resizable = false,
            //undecorated = true,
            icon = rememberVectorPainter(Icons.IcAinoLogo)
        ) {
            println("run")
            //App()
        }
```

Now every time Windows is minimized or displayed, the word "run" is printed
what's the reason?

When I remove the following code, the problem is solved

```
        if (state.isMinimized) {
            println("OnPause")
        } else {
            println("OnResume")
        }
```

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): windows
- OS architecture (x86 or arm64): 64
- JDK (for desktop issues): 17

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3270">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
