### ISSUE TITLE
[iOS] Text glitch with Dynamic Type

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#3274]
There is an interesting text glitch on iOS 16.5 in `1.5.0-dev1071`.
If we rapidly change Dynamic Type 2-7 times we can discover a secret elven localization 😄

https://github.com/JetBrains/compose-multiplatform/assets/63979218/02de535e-4072-469e-9311-9b41d6f110a0

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3274">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
