### ISSUE TITLE
compose multiplatform does not support kotlin version 1.8.21 

### ISSUE THREAD

**Issue by anuj72** [JetBrains/compose-multiplatform#3277]
**Describe the bug**

**Affected platforms**
Select one of the platforms below:
- All
- Desktop

compose multiplatform does not support kotlin version 1.8.21

**Comment by MatkovIvan** [comment]
Duplicate of #3214

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3277">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
