### ISSUE TITLE
Draw dispatch before scene was updated with latest UITouch.

### ISSUE THREAD

**Issue by elijah-semyonov** [JetBrains/compose-multiplatform#3278]
**Describe the bug**
On iOS, some of compose machinery is driven by system events. The issue is created by interaction of UITouch processing and CADisplayLink, which drives the rendering. On iOS those are always delivered sequentially: CADisplayLink after UITouch events are sent to UIViews. 

Touch processing inside Compose is run on coroutines, which creates an interesting anomaly:
On 120hz displays, the code wrapping and dispatching the touches reenters the coroutines inside, while on 60hz displays it doesn't, so they are processed asynchronously after OS-driven even dispatch method quits. That leads to a situation where CADisplayLink callback is fired before Compose state was updated after the latest touches. If a current scene was invalidated at least twice before the next vsync, that will lead CADisplayLink to immediately dispatch draw call, which will create a visual stutter, because content doesn't follow the touch for a frame (touch wasn't processed yet). 

A solution to that would be to process events synchronously in a main run loop to avoid this data race. While explicitly flushing current Compose coroutines tasks could be a viable work-around, it still doesn't explain why the behavior is different on 120hz and 60hz devices.

Resolution of this situation requires an ability to debug this specific situation on real device and observe the stacktraces to figure out what's the source of incorrect (60hz devices) behavior. Real iOS device debug from IJ is WIP by @dima-avdeev-jb.

Raising a flag reflecting existence of UITouch events to defer draw dispatch at this frame is not viable solution, because while we have explicit `invalidate`, implementing a specific `user events were consumed and didn't result in invalidation` callback will require a lot of internal API changes.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*:  1.8.20
- Compose Multiplatform version*: latest dev
- OS version(s)* (required for Desktop and iOS issues): 16.0

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3278">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
