### ISSUE TITLE
[Web] Skia for Web has a huge size

### ISSUE THREAD

**Issue by wakaztahir** [JetBrains/compose-multiplatform#3279]
Hi , I wanted to create this issue for a long time as I think it should be implemented in Compose at some stage because its very important.

My internet or a regular internet connection at the moment cannot afford to download Skia library before rendering the Composables to Canvas , I would expect there's a plan to eliminate Skia as its huge , replacing it with canvas / webgl / webgpu.

Is there any plan to do this ? If there is when can we expect anything regarding this ?

Compose is a blessing on other platforms

**Comment by Walingar** [comment]
Hi @wakaztahir thank you for feedback, this is a really good point!

Since Compose for Web is in the experimental stage, any changes can be made with the rendering engine even we can change it completely, but for the nearest future we are going to keep using Skia

**Comment by wakaztahir** [comment]
If rendering Engine is going to change in the future why rely on Skia now , It could be changed now

Do you guys want to keep using Skia currently because Rendering Engine is harder to implement

Or

To be consistent with other platforms in terms of rendering

Where can I find rendering Engine implementation in compose , to see if this is something I can do on my own until a proper fix is available

**Comment by Walingar** [comment]
Rendering engine **can** change in the future, but there are no particular plans regarding that. I'm sorry if I put it wrong

You can find sources of Skia that we are using here: https://github.com/jetbrains/skia
To use Skia in kotlin, we have jvm bindings here: https://github.com/jetbrains/skiko

**Comment by wakaztahir** [comment]
@Walingar I have a question just out of curiosity , Is IntelliJ IDEA new UI being built using Compose ?

**Comment by Walingar** [comment]
@wakaztahir it is a bit out of the scope of the issue :) And worth discussing it in a separate discussion (may be in [discussions](https://github.com/JetBrains/compose-multiplatform/discussions))
But answer your question: no, IntelliJ new UI is built using Swing

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3279">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
