### ISSUE TITLE
DMG create distribution fails 

### ISSUE THREAD

**Issue by ch8n** [JetBrains/compose-multiplatform#3280]
Whenever I try to run `packageDmg` command either by UI gradle or integrated terminal `./gradlew packageDmg --stacktrace`, it fails

```gradle
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':packageDmg'.
> External tool execution failed:
  * Command: [/Users/chetangupta/Library/Java/JavaVirtualMachines/azul-19.0.2/Contents/Home/bin/jpackage, @/Users/chetangupta/Desktop/chetan/compose/desktop/DsaTrainer/build/compose/tmp/packageDmg.args.txt]
  * Working dir: []
  * Exit code: 1
  * Standard output log: /Users/chetangupta/Desktop/chetan/compose/desktop/DsaTrainer/build/compose/logs/packageDmg/jpackage-2023-06-20-20-33-05-out.txt
  * Error log: /Users/chetangupta/Desktop/chetan/compose/desktop/DsaTrainer/build/compose/logs/packageDmg/jpackage-2023-06-20-20-33-05-err.txt
```

Error log file content (jpackage-2023-06-20-20-33-05-err.txt)
```
java.io.IOException: Command [/usr/bin/hdiutil, attach, /var/folders/bt/qz_284cn3218q0rrftztswpc0000gr/T/jdk.jpackage4683290700534445689/images/DsaTrainer-tmp.dmg, -quiet, -mountroot, /var/folders/bt/qz_284cn3218q0rrftztswpc0000gr/T/jdk.jpackage4683290700534445689/images] exited with 1 code
```

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.3.0
- OS version(s)* (required for Desktop and iOS issues): MacOS ,
- OS architecture (x86 or arm64): Apple M1 arm64
- JDK (for desktop issues): azul-19 - 19.0.2 (have tried with multiple jdk version)

**Comment by Walingar** [comment]
Hello @ch8n thank you for sharing this issue!
I tried to reproduce it with the same configuration and MacOS Ventura Version 13.2, but it works fine for me.

Could you please share what MacOS version you use?

If it is possible, can you try using 1.4.0 version of Compose Multiplatform? So the newest gradle plugin will be used.

Also, I would be glad if you can try running `packageDmg` with the simple project that you can take from [this template](https://github.com/JetBrains/compose-multiplatform-desktop-template), so we can understand that it doesn't depend on your particular project.

**Comment by ch8n** [comment]
hi @Walingar thanks for follow up, i tried same template and running gradle packageDMG command gives same error
```gradle
External tool execution failed:
* Command: [/Library/Java/JavaVirtualMachines/temurin-18.jdk/Contents/Home/bin/jpackage, @/Users/chetangupta/Desktop/chetan/android/compose-multiplatform-desktop-template/build/compose/tmp/packageDmg.args.txt]
* Working dir: []
* Exit code: 1
* Standard output log: /Users/chetangupta/Desktop/chetan/android/compose-multiplatform-desktop-template/build/compose/logs/packageDmg/jpackage-2023-06-21-19-19-33-out.txt
* Error log: /Users/chetangupta/Desktop/chetan/android/compose-multiplatform-desktop-template/build/compose/logs/packageDmg/jpackage-2023-06-21-19-19-33-err.txt
```

error in file
```
java.io.IOException: Command [/usr/bin/hdiutil, attach, /var/folders/bt/qz_284cn3218q0rrftztswpc0000gr/T/jdk.jpackage18294761177205694952/images/KotlinJvmComposeDesktopApplication-tmp.dmg, -quiet, -mountroot, /var/folders/bt/qz_284cn3218q0rrftztswpc0000gr/T/jdk.jpackage18294761177205694952/images] exited with 1 code
```

My OS is 
<img width="263" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/11576342/684990af-dd5c-4078-bbcc-7a04c326d984">

**Comment by Walingar** [comment]
@ch8n thank you for an instant response!

It seems like the issue could be with MacOS 12.5 + M1. @AlexeyTsvetkov can you please take a look?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3280">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
