### ISSUE TITLE
Slider add paramater to disable keyboard events

### ISSUE THREAD

**Issue by RocketJannis** [JetBrains/compose-multiplatform#3283]
The Slider Composable always uses the internal Modifier.slideOnKeyEvents (defined in Slider.kt). It would be cool if this behavior could be disabled using a parameter, something like:

```kotlin
Slider(
    ...,
    enableSlideOnKeyEvents = false,
)
```

My use case: I use left/right/up/down keyboard events in my Window for a custom behavior (media app, skip song/skip 10 secs). As soon as the Slider is focused using the mouse, those events don't work anymore as the Slider catches all the key events.

My current workaround: As soon as `onValueChangeFinished` is called, the Slider is shortly disabled (clears focus) and reenabled:

```kotlin
var canHaveFocus by remember { mutableStateOf(false) }

Slider(
    value = [...],
    onValueChange = { slidingState = it },
    enabled = canHaveFocus,
    onValueChangeFinished = {
        // [...]
        canHaveFocus = false
    }
)

LaunchedEffect(canHaveFocus){
    if(!canHaveFocus) canHaveFocus = true
}
```

**Comment by Walingar** [comment]
Hello @RocketJannis please try this code:
```kotlin
var value by remember { mutableStateOf(0.1f) }
Slider(
    value,
    onValueChange = {
        value = it
    },
    modifier = Modifier.focusProperties { canFocus = false }
)
```
It makes Slider non-focusable, so it won't receive any key events, but still will receive pointer events.

Please let me know and reopen the issue if it doesn't suit you!

**Comment by RocketJannis** [comment]
@Walingar thank you very much, I didn't know :+1: sorry for opening an issue xD

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3283">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
