### ISSUE TITLE
How to prevent copy/paste/cut context menu when right click on textfield

### ISSUE THREAD

**Issue by ning-drift** [JetBrains/compose-multiplatform#3286]
[as this link says](https://stackoverflow.com/questions/76550327/how-to-prevent-copy-paste-cut-context-menu-when-right-click-jetpack-compose-des?noredirect=1&lq=1).I want to prevent copy/paste/cut context menu when right click on textfield on desktop platfrom.i try to provied a EmptyTextToolbar to LocalTextToolbar it's does't work

**Comment by ning-drift** [comment]
https://stackoverflow.com/a/76550780/22128385
emm, i find a solution.it's recommended practice?
Please help me improve it, or close this issue

**Comment by Walingar** [comment]
Hello @ning-drift, thank you for your question!
The solution that you provided is good! You can see the documentation regarding this topic here: https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Context_Menu/README.md#custom-text-context-menu

**Comment by ning-drift** [comment]
yeah documentation it‘s clear.I missed them, the description about reuse the original TextContextMenu misled me

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3286">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
