### ISSUE TITLE
Improve naming of ScrollbarStyle "unhoverColor" property

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#3290]
The `ScrollbarStyle.unhoverColor` property has a really odd name. Shouldn't it be called something like `color`, `idleColor`, or `normalColor`? I don't think `unhover` is either intuitive nor grammatically correct :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3290">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
