### ISSUE TITLE
no implementation for FUN MISSING_DECLARATION ... FINAL <> () returnType:kotlin.Nothing

### ISSUE THREAD

**Issue by jbruchanov** [JetBrains/compose-multiplatform#3292]
**Describe the bug**
Unable to compile a project, getting following error
```
> Task :shared:linkPodDebugFrameworkIosSimulatorArm64 FAILED
e: Compilation failed: no implementation for FUN MISSING_DECLARATION name:Screen visibility:public modality:FINAL <> () returnType:kotlin.Nothing
in testapp.TestApp

 * Source files: 
 * Compiler version: 1.9.0-RC
 * Output kind: FRAMEWORK

e: java.lang.IllegalStateException: no implementation for FUN MISSING_DECLARATION name:Screen visibility:public modality:FINAL <> () returnType:kotlin.Nothing
```

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.0-RC
- Compose Multiplatform version*: 1.5.0-dev1074
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): openjdk version "17.0.6" 2023-01-17

Follow up of this issue
https://youtrack.jetbrains.com/issue/KT-59231/Exception-during-IR-lowering-during-iOS-build

Reproducible repo
https://github.com/jbruchanov/KT-59231

run
`./gradlew appIos:build` to reproduce it

**Comment by jbruchanov** [comment]
looks like having everything what is @Composable also @HiddenFromObjC solves the issue.

**Comment by eymar** [comment]
@jbruchanov You're using `kotlinCompilerPlugin.set("androidx.compose.compiler:compiler:1.4.8-dev-k1.9.0-RC-5532d15c918")`

Jetpack Compose compiler plugin doesn't contain all the patches necessary for k/js and k/native (it should work fine for desktop though). 

In your case you need to use:
```
kotlinCompilerPlugin.set("org.jetbrains.compose.compiler:compiler:1.4.8-beta")
```

**Comment by jbruchanov** [comment]
@eymar 
thanks I'll give it a try...
is there some page I can see these "hidden" relations ?

I was taking it from https://androidx.dev/storage/compose-compiler/repository, but that's obviously inaccurate for my case

**Comment by eymar** [comment]
> is there some page I can see these "hidden" relations ?

Do you mean the relation between supported Kotlin version and Compose compiler plugin?

We have this table - https://github.com/JetBrains/compose-multiplatform/blob/master/VERSIONING.md#kotlin-compatibility
But it shows the relatation between kotlin version and Compose Multiplatform. It includes only those kotlin versions, which it supports out of a box (meaning, there is no need to override the compiler plugin version).

The compose compiler plugin may actually support more recent kotlin version. We'll consider adding such a table too. 
So it would look like:

`Kotlin 1.9.0-RC` -> `org.jetbrains.compose.compiler:compiler:1.4.8-beta`
___

Is that what you mean?

**Comment by eymar** [comment]
One more place to see it: https://github.com/JetBrains/compose-multiplatform/blob/master/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/ComposeCompilerCompatibility.kt#L7

**Comment by jbruchanov** [comment]
@eymar 
thanks a lot, having 1.9.0-RC + correct compiler fixes the compiler issue.

There is another one in runtime though
```
Uncaught Kotlin exception: kotlin.native.internal.IrLinkageError: Function 'LimitedValuesRadioSwitch' can not be called: No function found for symbol ...
```

but need to invest it little bit more...

thanks for help

**Comment by rvenky125** [comment]
My compose compiler version: 1.5.7

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3292">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
