### ISSUE TITLE
LWJGL Integration 

### ISSUE THREAD

**Issue by ronjunevaldoz** [JetBrains/compose-multiplatform#3298]
https://github.com/JetBrains/compose-multiplatform/blob/master/experimental/lwjgl-integration/src/main/kotlin/main.kt

How to properly setup game loop? I'm not sure if this is an issue but using the above example, when I render a compose component, it does not fill the width and height but instead it was rendered bottom below, how do I make the origin at the top?

compose version: 1.4.1

Issues encountered:
- Surface is not centered
- Input events not working (glfw events are working but not being sent to AWT, button click not working) 

```kotlin
@Composable
fun App () {
   Column {
       // AndroidView(factory ={GLSurface}) working android
       // UIKitView(factory ={GLKView}) working ios
       // i'm not sure what component  to use here to port lwjgl here
       DesktopGameView(
          factory={glfwWindowHere}, 
          update={
            // init buffers
            // run game 
            gameLoop()
          }, 
          onRelease={
            disposeGame()
       })
   }
}

fun gameLoop() {... }
```

**Comment by MatkovIvan** [comment]
Related:
- #652

**Comment by AlexeyTsvetkov** [comment]
@ronjunevaldoz please note that LWJGL integration is an experimental example of using Compose. It is not guaranteed to work, and we don't have plans to work on it in the near future. 
You are welcome to ask the [community Slack](https://kotlinlang.slack.com/archives/C01D6HTPATV) or investigate on your own.
Now I'm closing the issue in favor of more general #652

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3298">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
