### ISSUE TITLE
error while trying to display spotify 's android icon on windows : unknown fillType: 1 

### ISSUE THREAD

**Issue by ElisaMin** [JetBrains/compose-multiplatform#3301]
**Describe the bug**
I'm trying to display a android drawable xml image that exctrack form spotify's apk, then I have this exception. my runtime is windows jvm
```
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: unknown fillType: 1
	at androidx.compose.ui.res.vector.DesktopValueParsers_desktopKt.parseFillType(DesktopValueParsers.desktop.kt:73)
```

**Affected platforms**
- Desktop

**Versions**
- Kotlin version:1. 8.20
- Compose Multiplatform version: 1.4.0
- OS version:  Desktop Windows
- OS architecture : x86
- JDK : 17

**To Reproduce**
> spotify 's icon drawable
```xml
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:height="108dp" android:width="108dp" android:viewportWidth="108.0" android:viewportHeight="108.0">
	<path android:fillColor="#ff1db954" android:pathData="M70.563,50.822C61.537,45.462 46.65,44.97 38.034,47.585C36.65,48.005 35.187,47.223 34.768,45.84C34.348,44.455 35.129,42.993 36.513,42.573C46.404,39.57 62.846,40.15 73.236,46.318C74.481,47.057 74.889,48.664 74.151,49.907C73.413,51.151 71.804,51.561 70.563,50.822ZM70.267,58.761C69.634,59.789 68.29,60.111 67.264,59.48C59.74,54.855 48.266,53.515 39.363,56.217C38.209,56.566 36.99,55.915 36.639,54.763C36.291,53.609 36.942,52.391 38.095,52.041C48.264,48.954 60.907,50.449 69.549,55.76C70.575,56.392 70.898,57.736 70.267,58.761ZM66.841,66.386C66.338,67.211 65.264,67.469 64.441,66.966C57.866,62.948 49.59,62.04 39.844,64.267C38.905,64.482 37.969,63.893 37.755,62.955C37.539,62.015 38.126,61.079 39.067,60.865C49.733,58.427 58.882,59.476 66.262,63.986C67.085,64.488 67.344,65.563 66.841,66.386ZM54,26C38.536,26 26,38.536 26,53.999C26,69.465 38.536,82 54,82C69.464,82 82,69.465 82,53.999C82,38.536 69.464,26 54,26L54,26Z" android:strokeColor="#0000" android:strokeWidth="1.0" android:fillType="1" />
</vector>
```

**Comment by alexzhirkevich** [comment]
`1` is actually invalid value for `fillType`. Project with such a drawable won't even compile for Android. 

Valid ones are `evenOdd`  and `nonZero`

**Comment by AlexeyTsvetkov** [comment]
Confirming the answer by @alexzhirkevich 

The original drawable fails the build on Android:
```
Android resource linking failed
com.example.myapplication.app-main-46:/drawable/customicon.xml:3: error: '1' is incompatible with attribute fillType (attr) enum [evenOdd=1, nonZero=0].
error: failed linking file resources.
```

When `android:fillType="1"` is replaced with `android:fillType="evenOdd"`, the icon shows successfully on both platforms.

**Comment by AlexeyTsvetkov** [comment]
That being said, while the error itself is justified, the UX could be improved.
I've created #3302 and #3303 issues for build-time verification and better error messages respectively.
Feel free to subscribe/vote.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3301">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
