### ISSUE TITLE
Verify drawable xmls during packaging

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [JetBrains/compose-multiplatform#3302]
Currently, Compose Multiplatform does not verify drawables' attributes during the build.

The drawable from #3301 fails in runtime with Compose Multiplatform non-Android targets:
```
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: unknown fillType: 1
	at androidx.compose.ui.res.vector.DesktopValueParsers_desktopKt.parseFillType(DesktopValueParsers.desktop.kt:73)
```

However, the same drawable causes a build time error, when targeting Android:
```
Android resource linking failed
com.example.myapplication.app-main-46:/drawable/customicon.xml:3: error: '1' is incompatible with attribute fillType (attr) enum [evenOdd=1, nonZero=0].
error: failed linking file resources.
```

I think the build time verification would benefit all platforms,
as it would make shipping drawables with unsupported or unparseable attributes less likely.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3302">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
