### ISSUE TITLE
Improve drawable errors for attributes with known values

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [JetBrains/compose-multiplatform#3303]
The drawable xml from #3301 contains `android:fillType` attribute with unsupported value `1`.
This causes an exception at runtime:
```
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: unknown fillType: 1
	at androidx.compose.ui.res.vector.DesktopValueParsers_desktopKt.parseFillType(DesktopValueParsers.desktop.kt:73)
```

The error is justified, because the `1` is not a valid value for the `fillType`.
However, the error could list valid possible values like happens during build on Android (Android's message is also somewhat confusing, but at least it mentions the valid values):
```
Android resource linking failed
com.example.myapplication.app-main-46:/drawable/customicon.xml:3: error: '1' is incompatible with attribute fillType (attr) enum [evenOdd=1, nonZero=0].
error: failed linking file resources.
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3303">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
