### ISSUE TITLE
When reading CJK characters from a file, they are load garbled (after packaged to MSI)

### ISSUE THREAD

**Issue by JellyBrick** [JetBrains/compose-multiplatform#3306]
**Describe the bug**
When reading CJK characters from a file, they are load garbled.

### Msi Packaged version

![image](https://github.com/JetBrains/compose-multiplatform/assets/16558115/40f9e794-1b9e-4cb1-bb10-135aad4661cf)

### When running with `java ...` command

![image](https://github.com/JetBrains/compose-multiplatform/assets/16558115/5b3c44a8-3dce-44b6-b31e-64bcb5033f27)

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.22
- Compose Multiplatform version*: 1.4.1
- OS version(s)* (required for Desktop and iOS issues): Windows 11 Pro, 22H2 (System encoding: CP949, file encoding: UTF-8)
- OS architecture (x86 or arm64): x86 (x86_64)
- JDK (for desktop issues): OpenJDK 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Write code to read a file.
2. Running `.exe` after packaging to `.msi`

code: https://github.com/JellyBrick/AlsongSRTUploader

**Expected behavior**
![image](https://github.com/JetBrains/compose-multiplatform/assets/16558115/5b3c44a8-3dce-44b6-b31e-64bcb5033f27)

It should be able to load text from the file without distortion.

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/16558115/40f9e794-1b9e-4cb1-bb10-135aad4661cf)

**Additional context**
None

**Comment by igordmn** [comment]
I haven't reproduced it, but the reason can be that you have set "file.encoding" in ~/.gradle/gradle.properties.

Try to check what is printed, calling `println(System.getProperty("file.encoding"))` in your application, in both cases.

I suspect that it will print UTF-8 when you run via `./gradlew run`, and CP949 when you run via `./gradlew runDistributable` (an alternative to running an exe). In default conditions they shouldn't differ.

Anyway, even if they differ, you should write code in a way that it works in different environments.

You either should fix the default encoding for the application:
```
compose.desktop {
    application {
        mainClass = "MainKt"
        jvmArgs += "-Dfile.encoding=UTF-8"

        ...
    }
}
```

or read files different way that support [BOM marker of UTF-8 files](https://stackoverflow.com/questions/4897876/reading-utf-8-bom-marker) or using automatic [charset detection](https://stackoverflow.com/questions/499010/java-how-to-determine-the-correct-charset-encoding-of-a-stream)

**Comment by JellyBrick** [comment]
The result is 'UTF-8' when running via `gradlew run`, and 'MS949' (CP949) when running via `gradlew runDistributable`.

```kotlin
compose.desktop {
    application {
        mainClass = "MainKt"
        jvmArgs += "-Dfile.encoding=UTF-8"

        ...
    }
}
```

This workaround resolved this issue, thank you.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3306">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
