### ISSUE TITLE
Linux GNOME application menu name in top bar

### ISSUE THREAD

**Issue by jeffdgr8** [JetBrains/compose-multiplatform#3308]
**Describe the bug**
When building a Compose Multiplatform app for Linux, the application menu in the top bar shows the `mainClass` MainKt instead of the `packageName`, which is used for the menu on macOS by default. This is when running `runDistributable` or `run` (`run` shows MainKt on macOS too).

**Affected platforms**
- Desktop (Linux)

**Versions**
- Kotlin version: 1.8.20
- Compose Multiplatform version: 1.4.1
- OS version(s): Ubuntu 23.04
- OS architecture: x64
- JDK (for desktop issues): 17

**To Reproduce**
1. Define `compose.desktop.application.nativeDistributions.packageName` in `build.gradle.kts`.
2. Build and run the Compose desktop app on Linux with `./gradlew runDistributable`.
3. Note the menu difference vs doing the same on macOS.

**Expected behavior**
The menu should use the `packageName` title the same as macOS.

**Screenshots**
![linux-app-menu-mainkt](https://github.com/JetBrains/compose-multiplatform/assets/2053817/71212c4d-0258-41da-9307-11199ff9670e)

**Additional context**
macOS also has the `dockName` configuration option to customize the menu name to differ from the `packageName` default. A similar option would also be helpful on Linux.

**Comment by avently** [comment]
In the meantime, is it possible to fix on our side? Or do you plan to fix it in the near future?

**Comment by epoberezkin** [comment]
Is it planned for fix? It's certainly annoying to the users.

**Comment by dima-avdeev-jb** [comment]
@avently Sorry, for now we have more higher priority issues

**Comment by DATL4G** [comment]
@jeffdgr8 @avently

## Workaround

In your desktop application code:

```kotlin
fun applyTitle(title: String): Boolean = runCatching {
	val toolkit = Toolkit.getDefaultToolkit()
	val awtAppClassNameField = toolkit.javaClass.getDeclaredField("awtAppClassName")
	val working = try {
		awtAppClassNameField.isAccessible = true
		awtAppClassNameField.isAccessible
	} catch (ignored: Throwable) {
		awtAppClassNameField.trySetAccessible()
	}
	awtAppClassNameField.set(toolkit, title)
	working
}.getOrNull() ?: false
```

Then call:

```kotlin
fun main() {
	if (applyTitle("Your AppName")) {
		// Title got applied
	} else {
		// Could not apply title
	}
}
```

### JVM Args

Since Java 17 we can't access the necessary field by default anymore, so we need to add some JVM Args.

In your app `build.gradle.kts` add the following lines:

```kotlin
compose {
	desktop {
		application {
			// your configuration, like mainClass etc
			
			// do a check to know if the current host is a linux host
			// you can use [com.google.osdetector] for example
			if (getHost() == Host.Linux) {
				jvmArgs("--add-opens", "java.desktop/sun.awt.X11=ALL-UNNAMED")
				jvmArgs("--add-opens", "java.desktop/sun.awt.wl=ALL-UNNAMED")
			}
		}
	}
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3308">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
