### ISSUE TITLE
Document how to work with files on desktop

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [JetBrains/compose-multiplatform#3309]
Being able to open a file (via a dialog or drag & drop) is essential for many desktop apps.

While the project does not provide relevant widgets, there are known solutions:
* [java.awt.FileDialog](https://docs.oracle.com/javase/8/docs/api/java/awt/FileDialog.html) or [javax.swing.JFileChooser](https://docs.oracle.com/javase/7/docs/api/javax/swing/JFileChooser.html) can be used as a file dialog;
* Since 1.4.0 it became possible to implement a drag & drop widget easily by using `onExternalDrag` API (#222);

However, there is no easily discoverable tutorial or example showcasing these solutions.

Questions regarding working with files have been asked and commented many times:
* #176;
* #197;
* #222;
* #1003;
* #3294;

The issues above contain answers, but searching for documentation in issue tracker is suboptimal.
It would be better to have a tutorial or a simple example, showcasing how to use AWT/Swing file dialogs and `onExternalDrag`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3309">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
