### ISSUE TITLE
Modifier.draggable onDragStopped not called.

### ISSUE THREAD

**Issue by elijah-semyonov** [JetBrains/compose-multiplatform#3310]
**Describe the bug**
If a user drags his finger to the right part of the screen until the finger leaves the screen during scrolling content, onDragStopped lambda is not called.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
jb-main 864ab80ff12dc70377d2f28d0a9bfbafd402ea44

**Expected behavior**
It must be called.

**Notes**
Not reproducible on Android.

**Comment by elijah-semyonov** [comment]
## Investigation
On Android DragStopped event generated when finger leaves screen on both sides, on iOS - only left side.

**Comment by elijah-semyonov** [comment]
## Investigation # 2

**Comment by elijah-semyonov** [comment]
## Resolution
Event is not sent in ComposeScene.processRelease because pressOwner is null due to logical error and hoveredOwner is also null, because the touch is slightly outside the bounds of window due to floating-point multiplication error.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3310">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
