### ISSUE TITLE
iOS Shared Pod: Compilation failed: No file for /App

### ISSUE THREAD

**Issue by chrisjenx** [JetBrains/compose-multiplatform#3311]
**Describe the bug**
When trying to compile the library I get the attached error from the shared iOS Library:

```
> Task :application:shared:linkPodDebugFrameworkIosSimulatorArm64 FAILED
warning: Cannot infer a bundle ID from packages of source files and exported dependencies, use the bundle name instead: shared. Please specify the bundle ID explicitly using the -Xbinary=bundleId=<id> compiler flag.
error: Compilation failed: No file for /App|3770576908038690392[0]

 * Source files: 
 * Compiler version info: Konan: 1.8.22 / Kotlin: 1.8.22
 * Output kind: FRAMEWORK

error: java.lang.IllegalStateException: No file for /App|3770576908038690392[0]
	at org.jetbrains.kotlin.backend.konan.serialization.KonanIrLinker$KonanPartialModuleDeserializer.getFileNameOf(KonanIrlinker.kt:500)
...
```

Other shared platforms run correctly, either I'm missing an iOS setting or Xcode incompatibility etc...

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.22 
- Compose Multiplatform version*: 1.4.1
- OS version(s)* (required for Desktop and iOS issues): OSx 13.4
- OS architecture (x86 or arm64): arm64, M2
- JDK (for desktop issues): Zulu JDK 19 

**To Reproduce**
1. Try and run the iOSApp using the shared code (from AS/Intellij/Xcode)
2. Gradle will run the compile scripts
3. Get error trying to build the shared pod

**Expected behavior**
Compile the shared pod and run the iOSApp

[compose-app-gh.zip](https://github.com/JetBrains/compose-multiplatform/files/11955226/compose-app-gh.zip)

**Comment by chrisjenx** [comment]
I tried `v1.5.0-dev1084` as well and that didn't help.

**Comment by eymar** [comment]
Jetpack Compose compiler plugin (`androidx.compose.compiler:compiler:`) doesn't contain all the patches necessary for k/js and k/native (it should work fine for desktop though).

Here is how to make it work:
```kotlin
// in build.gradle.kts of `shared` module
compose {
    val version = libs.versions.compose.compiler.get()
-    kotlinCompilerPlugin.set("androidx.compose.compiler:compiler:$version")
+   kotlinCompilerPlugin.set("org.jetbrains.compose.compiler:compiler:1.4.8")
}
```

**Comment by chrisjenx** [comment]
The version is set to 1.4.8 in the version catalog.

Downgrading to the one the plugin picks out of the box seemed to fix it.
Guess I didn't realize how closely tied they are.

**Comment by chrisjenx** [comment]
I got it working pretty consistantly, reopened the project this morning, same error again, reverted back to kotlin 1.8.20 and default compiler version, cleanup.sh, sync etc, same error, can't get it to work now :/

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3311">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
