### ISSUE TITLE
Design Scrollbars customization

### ISSUE THREAD

**Issue by Walingar** [JetBrains/compose-multiplatform#3312]
In the current implementation in 1.4.0 version, Scrollbar thumbs are customized only by using data class `ScrollbarStyle` that allows simple customization of the thumb. But for e.g. IntelliJ theming more customization is needed (for example, [border on Windows/Linux](https://jetbrains.design/intellij/controls/scrollbar/#style)). 
So we need to design API that allows customizing a scrollbar thumb and probably scrollbar track

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3312">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
