### ISSUE TITLE
compose desktop mainJar not work with error `Main jar was not processed correctly`

### ISSUE THREAD

**Issue by xinkunZ** [JetBrains/compose-multiplatform#3314]
* config
```

// use spring boot jar as main jar
tasks.bootJar {
    archiveFileName.set("boot.jar")
}

compose.desktop {
    application {
     ...
        disableDefaultConfiguration()
        mainClass = "org.springframework.boot.loader.JarLauncher"
        mainJar.set(tasks.bootJar.get().archiveFile)
     ...
}
```
* the mapping is empty, what is `libsMapping`? 
![image](https://github.com/JetBrains/compose-multiplatform/assets/7759897/6901607f-4999-49bf-9873-0aaa7ae56a8d)
* the launcherMainJar param is correct and the file exists too

![image](https://github.com/JetBrains/compose-multiplatform/assets/7759897/73718fa9-1617-4058-99b9-84171a4c1352)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3314">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
