### ISSUE TITLE
iOS. Use `nativeScale` instead of `scale` when we pass events to Compose, and create the Canvas for Compose

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3316]
We should use `value * uiview.nativeScale` for:
1. the draw buffer size in pixels (see MetalContextHandler.kt and SkiaLayer.ios.kt)
2. the ComposeScene size
3. the event position sent via scene.sendPointerEvent

Now we use `scale`. If it is different from `nativeScale` - it leads to resizing artifacts.

We should use  `uiview.scale` for:
1. the density of ComposeScene.density (it is used when we use `354.dp` in Compose)

To do all that, we need to change public API of skiko as well. One of the solutions:
- `SkiaLayer.contentScale` - still returns `scale` (but it isn't used for internal calculations)
- SkikoPointerEvent.x - return pixels instead of pointers, calculated via `nativeScale`
- we don't multiply `SkikoPointerEvent.x`, just send it directly to scene.sendPointerEvent

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3316">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
