### ISSUE TITLE
Html library testutils waitForChanges does not timeout

### ISSUE THREAD

**Issue by Burtan** [JetBrains/compose-multiplatform#3317]
**Describe the bug**
The following code will never throw an error, even if waiting longer than 2 seconds.
```
    withTimeout(2.seconds) {
        waitForChanges("testRoot")
    }
```
In contrast, the timeout works on this code.
```
    withTimeout(2.seconds) {
        delay(4.seconds)
    }
```

Maybe the `wait* ` functions could all take an optional timeout themselves?

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - HTML library

**Versions**
- Kotlin version*: 1.8.22
- Compose Multiplatform version*: 1.4.1 and 1.5.0-dev1084
- OS version(s)* (required for Desktop and iOS issues): Debian testing/sid (trixie)
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): eclipse-temurin 17.0.7

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3317">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
