### ISSUE TITLE
IrLinkageError: Function can not be called: No function found for symbol

### ISSUE THREAD

**Issue by jbruchanov** [JetBrains/compose-multiplatform#3318]
Runtime iOS crash (x86 simulator)

```
Uncaught Kotlin exception: kotlin.native.internal.IrLinkageError: Function 'GenericText' can not be called: No function found for symbol ...
```

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*:  "1.9.0-RC"
- Compose Multiplatform version*: 1.5.0-dev1084
- OS architecture (x86 or arm64): x86
JDK (for desktop issues): openjdk version "17.0.6" 2023-01-17

Reproducible repo
https://github.com/jbruchanov/KT-59231

run the app and observe the crash

**Additional context**
the issue is in [following code](https://github.com/jbruchanov/KT-59231/blob/master/lib-compose/src/commonMain/kotlin/com/jibru/compose/UpnpTypeInputComposable.kt)
```
internal interface UpnpTypeInputComposable {

    @Composable
    fun GenericText() {
       ...
    }
    companion object : UpnpTypeInputComposable
}

@Composable
fun UpnpInput(...) = with(UpnpTypeInputComposable) {
     GenericText()
}
````

has warnings during compile time
```
w: <...:lib-compose> @/Users/scurab/work/test-fail2/lib-compose/src/commonMain/kotlin/com/jibru/compose/UpnpTypeInputComposable.kt:60:29: Function 'GenericText' can not be called: No function found for symbol 'com.jibru.compose/UpnpTypeInputComposable.Companion.GenericText|1250094527037353215[0]'
...
w: <missing declarations>: No function found for symbol 'com.jibru.compose/UpnpTypeInputComposable.Companion.GenericText|1250094527037353215[0]'
```
and crashes in the runtime...

removing the ^ interface and making it simple `internal object UpnpTypeInputComposable`
fixes the issue

**Comment by eymar** [comment]
A possible workaround I found is to override the function and call its super method:

```kotlin
companion object : UpnpTypeInputComposable {

        @Composable
        override fun GenericText(
            label: String,
            defaultValue: String,
            onValueChanged: (String) -> Unit,
            modifier: Modifier,
            enabled: Boolean
        ) {
            super.GenericText(label, defaultValue, onValueChanged, modifier, enabled)
        }
    }
```
No runtime crash with it.

**Comment by eymar** [comment]
A simpler snipper to reproduce:

```kotlin
interface DefaultComposableContent {
    @Composable
    fun ComposableContent(
        any: String = "any" // default value is required to reproduce
    ) {
        Text("DefaultComposableContent - $any")
    }
}

class Impl : DefaultComposableContent

// then call
Impl().DefaultComposableContent()
```

It crashes with any k/native target and k/js target. k/jvm doesn't crash.

**Comment by jbruchanov** [comment]
retested and still reproducible with 

Kotlin version*: "1.9.0"
Compose Multiplatform version*: 1.5.0-dev1114

**Comment by jbruchanov** [comment]
retested and still reproducible with

Kotlin version*: "1.9.10"
Compose Multiplatform version*: 1.5.1

**Comment by jbruchanov** [comment]
retested and still reproducible with

Kotlin version*: "1.9.20"
Compose Multiplatform version*: 1.5.10

**Comment by umesh0492** [comment]
retested and still reproducible with

Kotlin version*: "1.9.21"
Compose Multiplatform version*: 1.5.11

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3318">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
