### ISSUE TITLE
Unexpected behaviour for window.minimumSize

### ISSUE THREAD

**Issue by FrankYang6921** [JetBrains/compose-multiplatform#3322]
**Describe the bug**
`window.minimumSize` does not take system DPI into consideration. The actual minimum size gets smaller than expected. When converted `Dp` to physical pixels using `LocalDensity`, the minimum size works as expected, but the initial window size gets larger than expected.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.1
- OS version(s)* (required for Desktop and iOS issues): Windows 11 Enterprise (22H2)
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues): OpenJDK 20.0.1
```
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9-29)
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)
```

**To Reproduce**
The following code gets correct initial window size, but a smaller minimum size on a HIDPI system
```java
fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
        state = WindowState(width = 800.dp, height = 600.dp)
    ) {
        window.minimumSize = Dimension(800, 600)
    }
}
```

The following code gets correct minimum window size, but a larger window size on a HIDPI system
```java
fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
        state = WindowState(width = 800.dp, height = 600.dp)
    ) {
        with(LocalDensity.current) {
            val dim = Dimension(
                800.dp.toPx().toInt(),
                600.dp.toPx().toInt()
            )
            window.minimumSize = dim
            // window.size = dim
            // this has completely no effect
        }
    }
}
```

**Expected behavior**
The second code fragment should result in a window with a initial and minimum size of 800dp by 600dp.

**Screenshots**
A smaller minimum window size (150% HIDPI scaling):
![image](https://github.com/JetBrains/compose-multiplatform/assets/47714406/7b19a775-2871-4d88-a74c-441946f762f9)

A bigger initial window size (150% HIDPI scaling):
![image](https://github.com/JetBrains/compose-multiplatform/assets/47714406/3529587f-9c11-429c-8331-799b9b4e1e7f)

**Comment by igordmn** [comment]
`window.minimumSize` isn't part of Compose Multiplatform, it is part of JDK. Please, report it [here](https://bugs.openjdk.org/projects/JDK/issues)

For `minSize` provided in `Window` argument, follow [this](https://github.com/JetBrains/compose-multiplatform/issues/2285).

Anyway, thanks for the issue, it should be taken into account when we will implement this.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3322">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
