### ISSUE TITLE
Kotlin 1.9.0

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#3323]
Kotlin 1.9.0 came.
Please use Kotlin 1.9.0.

**Comment by kirill-grouchnikov** [comment]
It hasn't even been a full hour since 1.9.0 was released

**Comment by mahramane** [comment]
> It hasn't even been a full hour since 1.9.0 was released

Yes, I was impatiently waiting for it. 😂

**Comment by alexzhirkevich** [comment]
And don't forget to fix #3201 with a new language feature :)

**Comment by igordmn** [comment]
It is supported in `CM 1.5.0-dev1114` (uses `CM Compiler 1.5.0`)

**Comment by igordmn** [comment]
We'll publish 1.4.2 soon with Kotlin 1.9.0 support
