### ISSUE TITLE
APP_NAME is not respected

### ISSUE THREAD

**Issue by chrisjenx** [JetBrains/compose-multiplatform#3324]
**Describe the bug**
When changing app name it won't respect the name change and launch the new binary.

There's two issues:
1. The scripts will try and launch "My Application" despite clearly building template application:
<img width="1151" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/1167793/af22edf2-89c6-495b-85c8-4e7c4a2374c4">

2. On some projects, it won't even change the binary name compiled:
<img width="681" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/1167793/016ec2e8-701c-4e71-8113-83c1b56b5cee">

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.8.22
- Compose Multiplatform version*: 1.4.1
- OS version(s)* (required for Desktop and iOS issues):  OSx: 13.4
- OS architecture (x86 or arm64): M2 arm64
- JDK (for desktop issues): Zulu JDK19

**To Reproduce**
1. Change APP_NAME
2. run `./cleanup.sh`
3. `./gradlew --stop`
4.  Sync project
5. Run ios target

App will either not run (as it try's to launch "My application", that doesn't exist), or it builds an old name "My Application" instead of "HayNet" new binary (so you see no changes...)

**Expected behavior**
Should respect the new name and build and run that target

**Screenshots**
See above

**Additional context**
Tried downgrading kotlin/gradle etc
Running from xcode will build and run the project correctly with the correct name

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3324">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
