### ISSUE TITLE
The Compose Multiplatform for iOS template doesn't build because of wrong JAVA_HOME

### ISSUE THREAD

**Issue by zhangchf** [JetBrains/compose-multiplatform#3326]
**Describe the bug**
With Android Studio Flamingo | 2022.2.1 Patch 2, 
`JAVA_HOME` is actually "/Applications/Android Studio.app/Contents/**jbr**/Contents/Home"

But the iOS build script is looking for `jre` folder, thus got the error:
>ERROR: JAVA_HOME is set to an invalid directory: /Applications/Android Studio.app/Contents/`jre`/Contents/Home

**Affected platforms**
- iOS

**Versions**
Android Studio Flamingo | 2022.2.1 Patch 2

**To Reproduce**
Download the template repo, open it in Android Studio, and build, it will report an error.

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/8181146/b268ef26-47fa-427b-84f5-0c69996c33ee)

**Comment by igordmn** [comment]
The template itself doesn't contain any paths to JDK.

By default, Android Studio should use JDK set in JAVA_HOME environment variable.

What will be printed if you call `echo $JAVA_HOME` in console outside Android Studio?

Also, check what is selected in `File - Settings - Build... - Build tools - Gradle`:
![image](https://github.com/JetBrains/compose-multiplatform/assets/5963351/558c1465-1d69-4466-83d5-918e87a007a3)

**Comment by zhangchf** [comment]
yes, the problem is export shows "JAVA_HOME" is set to "**jbr**" path.

I guess some embedded iOS libraries didn't respect the JAVA_HOME environment variable?

![image](https://github.com/JetBrains/compose-multiplatform/assets/8181146/33091b94-4c5d-4ee8-832f-533bb2f32c21)

**Comment by igordmn** [comment]
Check your evironement with [kdoctor](https://github.com/JetBrains/compose-multiplatform-ios-android-template#check-your-environment)

Additional checks:
1. Check if you have `JAVA_HOME` in Xcode: `Xcode -> Settings -> Locations -> Custom Paths`

2. Check what will be printed, if you call `echo $JAVA_HOME` in the `Terminal` tab of AS.

<img width="241" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5963351/e4a26b55-d190-4f37-bf5c-ffb1356fbe8e">

**Comment by zhangchf** [comment]
Sorry I don't remember I set `JAVA_HOME` in `Xcode -> Custom Paths` before. Now it's working after I update that. Thanks!

#### A little bit more information:
1. T**he latest `kdoctor` version finds no issue, but this is actually an issue.**
    -  A previous version of `kdoctor` will report Xcode is using a different `JAVA_HOME` by default and ask me to set `JAVA_HOME` in `Xcode -> Settings -> Locations -> Custom Paths`. Without this, if I open the iosApp project in Xcode, it can't build. (It's the same for KMM projects)
    - Now after I set `JAVA_HOME` in `Xcode -> Settings -> Locations -> Custom Paths`, it doesn't build in Android Studio immediately. But after a while, it can build.
2. `echo $JAVA_HOME` prints correctly in AS Terminal.


![image](https://github.com/JetBrains/compose-multiplatform/assets/8181146/a26ef6f6-a470-482c-a7d8-c39a994b218e)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8181146/e530022b-61ee-4ec2-99d9-064777d5e1c5)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8181146/0caddf33-c022-4214-86d2-009ba9b6260a)

**Comment by igordmn** [comment]
Glad the issue has been resolved

> The latest kdoctor version finds no issue, but this is actually an issue.

Does't it show a warning on your screnshot?

**Comment by zhangchf** [comment]
> Doesn't it show a warning on your screenshot?

No warning, as you can see from the screenshot, `JAVA_HOME` is correct, and it didn't find Xcode is using a different path.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3326">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
