### ISSUE TITLE
iOS. Improve documentation how to build ipa and run tests on CI

### ISSUE THREAD

**Issue by jbruchanov** [JetBrains/compose-multiplatform#3327]
As an android dev I'm struggling with building iOS app (in CI).
For some reason I have to always run `xcodebuild` twice or get xcode involved to make it get "** BUILD SUCCEEDED **" at the end.

It would be really nice if there was a documentation for dummies how to deal with the "other" platform(s) you are not super experienced with. 
After reading [this](https://kotlinlang.org/docs/apple-framework.html#xcode-for-ios-targets) for example. I understand the text, but it's very difficult to do so for non iOS dev.

I guess many iOS developers might be struggling with gradle having a lot of "why is this so painful" moments like I do for iOS builds coming from Android world.

My main issue here is, I'm trying to have CI running for iOS build to build & test.
I tried this based on [this](https://slack-chats.kotlinlang.org/t/10507374/in-the-https-github-com-jetbrains-compose-multiplatform-temp)
```
./gradlew generateDummyFramework
./gradlew podspec
cd appIos
pod install
cd ..
#what's the best gradle task to run ? assemble builds release/debug which doesn't have to be necessary for simple cases or there might be a step for parallelism etc., is it even necessary ? xcodebuild is running gradle task as well, but looks like I have to do it, because even later repeating xcodebuild doesn't end up with success
./gradlew shared:assemble
cd appIos
pod install
#this one fails
xcodebuild -workspace appIos.xcworkspace/ -scheme appIos build
#call it again and it has success..
pod install
xcodebuild -workspace appIos.xcworkspace/ -scheme appIos build
```

Something what would well explain where/how/... to do stuff for "other platform beginners" from very beginning "create new project" to have debug/release apk/ipa.

Configuration in Xcode in my eyes is extremely overwhelming with tons of settings in different tabs/windows comparing to gradle scripts where a lot of complexity is just hidden until needed.

**Comment by igordmn** [comment]
Is the suggestion about adding information how to build ipa from the terminal?

We already have [the docs](https://github.com/JetBrains/compose-multiplatform-ios-android-template) how to run the iOS app from AS. It can have caveats and be complicated, but to simplify it we need to know exact issues that people experience.

**Comment by jbruchanov** [comment]
@igordmn
thanks for quick reply.
 I've seen the template project, but that doesn't cover the case I mentioned about building/running the iOS tests from terminal/CI.

I'm not clear how the gradle tasks are related to the iOS project.
the xcodebuild seems to be running `gradlew :shared:syncFramework` which doesn't simply exist if I run `gradlew :shared:tasks`.
Also as mentioned in initial message, for some reason I have to get xcode involved or I have to rerun xcodebuild multiple times to get 🟢 result.


If you could add tiny custom gradle/script in the ios part how to simply run "build & test" + maybe github actions yml that would be highly appreciated.

**Comment by igordmn** [comment]
Got it, thanks.

Adding `.github/ci.yml` to the template that just works and builds ipa and run tests can be a simple solution for now.

As the next steps, we can:
1. add docs for this case somewhere - as a section in the template's README, or as a tutorial in the [tutorials](https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/README.md)
2. make simple Gradle tasks that hide all complexity under the hood (needs to be investigated)

**Comment by jbruchanov** [comment]
@igordmn @dima-avdeev-jb 
Sorry guys for dm, is there any progress on this ?

I'm really finding it difficult to work with KMP if I can't run the iOS part on CI.
Any "official" guide/bash script or anything what can do `git clone` -> `build` -> `test` for iOS would be amazing...

**Comment by dima-avdeev-jb** [comment]
@jbruchanov Sorry, but not yet

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3327">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
