### ISSUE TITLE
[desktop] should not generate `-Dskiko.library.path=$APPDIR'` when use `disableDefaultConfiguration`  

### ISSUE THREAD

**Issue by xinkunZ** [JetBrains/compose-multiplatform#3328]
if I use a fat jar or spring boot jar as main jar, the skiko library will be at classpath, so there is no need to add these java options at runtime

```
--java-options
"'-Dskiko.library.path=$APPDIR'"
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3328">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
