### ISSUE TITLE
Focus Issues after Animation Runs

### ISSUE THREAD

**Issue by Syer10** [JetBrains/compose-multiplatform#3329]
**Describe the bug**
When a animation is run during a focus requester requesting focus, focus is then broken from then on. This only happens after 1.4, as 1.3 correctly applies focus and has no issues.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4+, 1.3 works perfectly
- OS version(s)* (required for Desktop and iOS issues): Windows/MacOS
- OS architecture (x86 or arm64): Both
- JDK (for desktop issues): Corretto and Temurin

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Clone https://github.com/Syer10/compose-focus-issue/ and run the project
2. Click next screen, the issue seems to be related to the animation and focus requester running at the same time.
3. Try to type, nothing happens
4. Click the next TextField, typing inputs in the first text field instead.

**Expected behaviour**
Focus selects and types in the correct TextField

**Screenshots**
![MeVBqRM 1](https://github.com/JetBrains/compose-multiplatform/assets/6090655/f794c9c8-57cc-43cd-9518-d8cc8f0b00b6)

**Additional context**
I was only able to reproduce it using a Decompose example project with my screens.

**Comment by arkivanov** [comment]
This is most likely related to `movableContentOf`, which is used by Decompose for some animations. It looks like the issue happens when `movableContentOf` is moved.

**Comment by igordmn** [comment]
A reproducer without Decompose:
```
import androidx.compose.foundation.layout.Column
import androidx.compose.material.TextField
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication { Bug() }

@Composable
fun Bug() {
    val content = remember {
        movableContentOf {
            Column {
                val focusRequester = remember { FocusRequester() }
                TextField("", { }, Modifier.focusRequester(focusRequester))
                TextField("", { })
                LaunchedEffect(Unit) {
                    focusRequester.requestFocus()
                }
            }
        }
    }

    var foo by remember { mutableStateOf(true) }
    if (foo) {
        LaunchedEffect(Unit) {
            foo = false
        }
        content()
    } else {
        content()
    }
}
```

**Comment by igordmn** [comment]
Reported [here](https://partnerissuetracker.corp.google.com/issues/290343159)
