### ISSUE TITLE
Toast for Android and iOS

### ISSUE THREAD

**Issue by iadcialim** [JetBrains/compose-multiplatform#3331]
Is there a sample code for showing Toasts in Android and iOS?

**Comment by Tiebe** [comment]
I'm currently using SnackbarHost. [Here's the docs](https://developer.android.com/reference/kotlin/androidx/compose/material/SnackbarHostState)

**Comment by igordmn** [comment]
Popup notifications are supported via SnackbarHost as mentioned in the above comment.

Supporting API that shows the native `Toast.makeText` toast on Android and something on iOS (there is no native toasts on iOS) won't be supported in the foreseeable future.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3331">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by mayurr1512** [comment]
> Is there a sample code for showing Toasts in Android and iOS?

You can checkout this toast library

[https://github.com/Chaintech-Network/CMPToast]
