### ISSUE TITLE
VerticalScrollBar crashed in compose web

### ISSUE THREAD

**Issue by sunildhiman90** [JetBrains/compose-multiplatform#3332]
**Describe the bug**
I am using VerticalScrollBar with LazyColumn in compose web, it works fine with desktop, but crashes on web with following error in the console:
```
An operation is not implemented: implement js setter for rawPosition
```
ALso i checked its code,  i can see some code is commented in Scrollbars.js.kt file:

```
private var rawPosition: Float
        get() = scrollScale * adapter.scrollOffset
        set(value) {
            TODO("implement js setter for rawPosition")
            //runBlocking {
            //    adapter.scrollTo(containerSize, value / scrollScale)
            //}
        }
```

So are we planning to implement this?
ANd is there any workaround available for as of now for using scrollbars with LazyColumn ?

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Try to use VerticalScrollBar with LazyColumn as we use for Desktop, it will crash while we will click on scrollbar to scroll.

**Expected behavior**
It should not crash.

**Screenshots**

**Additional context**

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3332">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
