### ISSUE TITLE
Compose-desktop: LazyColumn cannot auto scroll when SelectionContainer selects text exceed to the end

### ISSUE THREAD

**Issue by SanchezABCs** [JetBrains/compose-multiplatform#3333]
`    SelectionContainer {
        LazyColumn {
            items(datas) {
                Text(it)
            }
        }
    }`

**Comment by igordmn** [comment]
Follow [this issue](https://github.com/JetBrains/compose-multiplatform/issues/1492)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3333">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
