### ISSUE TITLE
JS/Web: Resizable Canvas

### ISSUE THREAD

**Issue by luca992** [JetBrains/compose-multiplatform#3337]
As far as I've tested there's no good way to have the web canvas fill the window and properly re-render upon window size changes. This is probably the biggest blocker I have to be able to actually use compose-ui for web.

**Comment by alexzhirkevich** [comment]
Duplicate of https://github.com/JetBrains/compose-multiplatform/issues/2896

**Comment by luca992** [comment]
@alexzhirkevich ah okay. Missed that. Thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3337">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
