### ISSUE TITLE
Config gradle for application build native Kotlin linux binary using moduler Java

### ISSUE THREAD

**Issue by nguyentthai96** [JetBrains/compose-multiplatform#3339]
Hi, I'm a beginner with Kotlin multiplatform native.

I want to use structure to build a Kotlin execution with binary native on the Linux application CLI.
I have modular source Java code as API logic service now don't want public API (olds) -> I need transfers code to a module sub in the project, and Kotlin code application module nativeMain can call load olds module Java source (and maybe Java code call into Kotlin code)

Java olds <---> Kotlin native (main application)

But now I'm stuck when config build Gradle to load module, have any solution for that problem that.
Issue reuse old code Java for project native Kotlin

Thank response to my problem.

**Comment by pjBooms** [comment]
Kotlin native does not support Java

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3339">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
