### ISSUE TITLE
Support isComposeRootInScrollableContainer for all targets

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3341]
Compose 1.4.1

Search for `actual fun CompositionLocalConsumerModifierNode`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3341">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
