### ISSUE TITLE
Use LocalminimumTouchTarGetenForcement to cause crash

### ISSUE THREAD

**Issue by Atlands** [JetBrains/compose-multiplatform#3343]
**Describe the bug**
Android: Use **LocalminimumTouchTarGetenForcement** to cause crash
iOS: no problem
Jetpack Compose: no problem
```
CompositionLocalProvider(LocalMinimumTouchTargetEnforcement provides  false) {
    Checkbox(
        checked = selected,
        onCheckedChange = { onSelectedChange() }, modifier = Modifier
            .background(Color.Gray)
    )
}
```
use device: HONOR(DUK-AL20)-9.0 / emulator-13.0

**Affected platforms**
Select one of the platforms below:
- Android

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.5.0-dev1080
- OS version(s)* (required for Desktop and iOS issues): MacOS 13.4.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17.0.7

**Comment by pjBooms** [comment]
I have copy&pasted your code and it does not crash on my side with 1.5.0-dev1080 on Android. 
BTW, does it crash with CMP 1.4.1 on your side?
Can you provide the whole reproducer?

 >Jetpack Compose: no problem

When you see that Jetpack Compose does not have an issue but Compose Multiplatform has on Android, please check version of Jetpack Compose and compare it with Compose Multiplatform redirection version to Jetpack Compose (https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.4.1). Compose Multiplatform is just Jetpack Compose on Android, so the most probably the versions do not match.

**Comment by Atlands** [comment]
> I have copy&pasted your code and it does not crash on my side with 1.5.0-dev1080 on Android. BTW, does it crash with CMP 1.4.1 on your side? Can you provide the whole reproducer?
> 
> > Jetpack Compose: no problem
> 
> When you see that Jetpack Compose does not have an issue but Compose Multiplatform has on Android, please check version of Jetpack Compose and compare it with Compose Multiplatform redirection version to Jetpack Compose (https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.4.1). Compose Multiplatform is just Jetpack Compose on Android, so the most probably the versions do not match.

@pjBooms Thank you for your reply. You are right. I have introduced an incompatible version in the Android branch

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3343">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
