### ISSUE TITLE
Add linuxArm64 and watchosDeviceArm64 targets to runtime

### ISSUE THREAD

**Issue by gabrielittner** [JetBrains/compose-multiplatform#3344]
`linuxArm64` was added before but reverted because of missing coroutines support: https://github.com/JetBrains/compose-multiplatform-core/pull/382 Coroutines 1.7.x added support for these targets. 

I'd submit a pr for adding these targets but `jb-main` is still using coroutines 1.6.x and I'm not sure how your process is for pulling changes from `androidx-main` works.

**Comment by gabrielittner** [comment]
The `androidNative*` targets also are supported by coroutines now but not sure how much sense it makes to add these to the compose runtime.

**Comment by pjBooms** [comment]
Hello. Unfortunately we have to wait til Compose starts using Coroutines 1.7. As we see Jetpack Compose uses Coroutines 1.7 only in Compose 1.6 so the most probably Compose Multiplatform will start using Coroutines 1.7 in Compose 1.6 as well (and it won't happen in the near months).

**Comment by gabrielittner** [comment]
Thanks for the update

**Comment by gabrielittner** [comment]
https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/gradle/libs.versions.toml#L45 It looks like the main branch is now on couroutines 1.8.0-RC so the blocked should be gone. Maybe runtime could even get the new wasm target?

**Comment by hfhbd** [comment]
The runtime already has wasmJS support since 1.6.0-alpha01.

**Comment by gabrielittner** [comment]
Ah nice, I somehow missed that, then it's just the 2 targets from the original request

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3344">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
