### ISSUE TITLE
kdoctor: Make it more visible that it is only for Mac or provide non-mac versions

### ISSUE THREAD

**Issue by dragetd** [JetBrains/compose-multiplatform#3347]
**Describe the bug**

I followed the documentation to build an all-platform compose app (https://github.com/JetBrains/compose-multiplatform-template#readme). It told me to check my system using 'kdoctor' (https://github.com/Kotlin/kdoctor)

The README of kdoctor then says:

```
You can download an archive from GitHub:

    Go to [Releases](https://github.com/Kotlin/kdoctor/releases) page
    Download the latest available version there
    Unpack it to preferred place
```

I actually do prefer a simple static binary for installation of such a helper-utility, so I checked the releases page.
The release page does not name or describe that one single artifact it has: ` kdoctor_1.0.1+92.zip`. This ZIP file contains a single binary which turns out to be ARM64.

I like the idea to have a utility to check system config, akin to what Flutter provides with `flutter doctor` out of the box. Only then I noticed the note in the README that kdoctor is only for Mac.

Why is this only for Mac? If there is a good reason, could this be added more prominently to the title of the application? But having this for other platforms as well would be nice.

**Comment by pjBooms** [comment]
You may find the following sentence  in the beginning of [the readme](https://github.com/JetBrains/compose-multiplatform-template#set-up-the-environment):

>You need a Mac with macOS to write and run iOS-specific code on simulated or real devices. This is an Apple requirement.

I am not sure how to make it more visible. 

kdoctor is a diagnosis tool for KMM development and makes sense only if you are targeting iOS that requires macOS for development as stated above.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3347">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
