### ISSUE TITLE
Row composable only displays first element.

### ISSUE THREAD

**Issue by CodeRoutineDev** [JetBrains/compose-multiplatform#3348]
**Describe the bug**
The `Row` layout composable only displays the first element composed in it.

**Affected platforms**
Select one of the platforms below
- Desktop
- Maybe other platforms as well

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.1
- OS version(s)* (required for Desktop and iOS issues): Ubuntu-like 22.04 with KDE (jammy)
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 17

**To Reproduce**
Git repo with minimal project that reproduces the issue:
https://codeberg.org/CodeRoutineDev/Compose-Multiplatform-Row-Bug

You can also open a simple template project from IntelliJ with all the defaults, bump the version of Compose and Kotlin and then replace the Main.kt file content with this:

```kotlin
@Composable
@Preview
fun App() {
    MaterialTheme {
        Row {
            Column {
                Text("Foo")
                Divider()
            }
            Divider()
            Column {
                Text("Bar")
                Divider()
            }
            Divider()
            Column {
                Text("Bla")
                Divider()
            }
        }
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}
```

**Expected behavior**
The Row should render all elements composed in it.

---

If you need more information, please let me know.

**Comment by m-sasha** [comment]
`Divider` is only usable in a vertical layout (e.g. `Column`) because it uses all available horizontal space (`fillMaxWidth()`).
In your case, it causes the first `Column` to fill the entire width of the window, pushing the following elements beyond it.

**Comment by CodeRoutineDev** [comment]
Thank you for the swift reply.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3348">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
