### ISSUE TITLE
Improve handling multi-owner input

### ISSUE THREAD

**Issue by MatkovIvan** [JetBrains/compose-multiplatform#3349]
Followup after https://github.com/JetBrains/compose-multiplatform-core/pull/634

- Make sure that `Press` event always sent to the owner before `Release` (check possible broken use cases)
- Check assigning `pressOwner` in multi-touch (should we change/nullify it?)

**Comment by m-sasha** [comment]
I think the right thing is not to simulate a press, but rather avoid delivering the release.

**Comment by MatkovIvan** [comment]
Actually it's already simulated - see `SyntheticEventSender`

**Comment by igordmn** [comment]
> Actually it's already simulated - see SyntheticEventSender

It generates presses based on the `Pointer.pressed` state, not based on fact that we have release without press.

This how it was designed, not sure how it behaves in reality now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3349">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
