### ISSUE TITLE
Improve skiko-only Popup overload

### ISSUE THREAD

**Issue by MatkovIvan** [JetBrains/compose-multiplatform#3350]
Followup after https://github.com/JetBrains/compose-multiplatform-core/pull/611

After commonization we need to decide what to do with our existing Popup overloads. It was decided to leave it as-is for now because it contains extra functionality like handling keyboard events directly, but it requires one more look to provide more consistent API. Most likely it's about redesign it in common with Android/Google cooperation.

**Comment by MatkovIvan** [comment]
Deprecated in https://github.com/JetBrains/compose-multiplatform-core/pull/716

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3350">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
