### ISSUE TITLE
When using SwingPanel in Compose for Desktop, it blocks PopupWindow

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/compose-multiplatform#3353]
**Describe the bug**
When using SwingPanel in Compose for Desktop, it blocks PopupWindow

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64): 64
- JDK (for desktop issues): jdk16
<img width="700" alt="problem" src="https://github.com/JetBrains/compose-multiplatform/assets/19502034/4142165b-9648-4fea-bd45-d6f497673b90">

**Comment by pjBooms** [comment]
It seems to be related to #2926

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3353">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
