### ISSUE TITLE
Missing Material 3 DatePicker component

### ISSUE THREAD

**Issue by Omico** [JetBrains/compose-multiplatform#3354]
The Material 3 DatePicker doesn't exist in Compose Multiplatform. Please add it!

https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#DatePicker(androidx.compose.material3.DatePickerState,androidx.compose.ui.Modifier,androidx.compose.material3.DatePickerFormatter,kotlin.Function0,kotlin.Function0,kotlin.Boolean,androidx.compose.material3.DatePickerColors)

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/DatePicker.kt

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3354">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
