### ISSUE TITLE
Improve official documentation

### ISSUE THREAD

**Issue by devjorgecastro** [JetBrains/compose-multiplatform#3355]
## Improve official documentation

I think that one of the most difficult things to start with Compose Multiplatform is to find a standard guide where all the necessary concepts are applied to create a complete application that covers the following topics:

- Architecture
- Navigation
- Status management
- Among other

Please improve the documentation, the community helps a lot with third party repositories and dependencies but it would be nice to start having a good reference guide.

**Comment by Chandra-Mauli-Sharma** [comment]
I would like to contribute to the official documentation. Can you assign this to me if possible?

**Comment by pjBooms** [comment]
Hello! Yes we are planning to work on documentation

**Comment by Chandra-Mauli-Sharma** [comment]
That's great

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3355">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
