### ISSUE TITLE
material3. Support DatePicker for iOS and Web

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3359]
After [merging](https://github.com/JetBrains/compose-multiplatform-core/pull/682) material3 1.1.1, Compose only supports DatePicker for Desktop and Android.

To support it for iOS and Web, [CalendarModel ](https://github.com/JetBrains/compose-multiplatform-core/blob/e845fb613d7563cb9f191b02a41ec0dfa16437ac/compose/material3/material3/src/desktopMain/kotlin/androidx/compose/material3/CalendarModel.desktop.kt)should be implemented. A possible implementation will use kotlinx datetime and native formatters/parsers (maybe ICU bundled in skiko also have this functionality)

**Comment by alexzhirkevich** [comment]
Kotlinx datetime [will soon support formatting and parsing](https://github.com/Kotlin/kotlinx-datetime/pull/251#issuecomment-1655603790)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3359">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
