### ISSUE TITLE
Support localization of bundled strings

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3360]
Currently, material3 has English Strings [hardcoded](https://github.com/JetBrains/compose-multiplatform-core/blob/e845fb613d7563cb9f191b02a41ec0dfa16437ac/compose/material3/material3/src/skikoMain/kotlin/androidx/compose/material3/Strings.skiko.kt):
<img width="1052" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5963351/1b319937-8a4c-4751-a052-1ffb46a9a752">

**Comment by igordmn** [comment]
Possible solutions is to provide a CompositionLocal

**Comment by igordmn** [comment]
Another solution - support strings.xml, similar to Android way

**Comment by igordmn** [comment]
Also in foundation/../BasicTooltipBoxInternal

**Comment by gleb-skobinsky** [comment]
Hi, are there any plans to fix this issue, maybe some approximate dates? In our team, these English labels in otherwise completely Russian-language app look really bad

**Comment by dima-avdeev-jb** [comment]
@gleb-skobinsky
Hello! We need some architectural changes between modules (artifacts) to solve this Issue. So, we need a time to plan it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3360">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
