### ISSUE TITLE
Review usage of global objects

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3362]
In some places of Compose there are global objects used:
```
CanFocusChecker
MinLinesConstrainer.last
LazyGridItemSpanScopeImpl
TextLayoutResult
```

(discovered from an iOS [build log](https://teamcity.jetbrains.com/buildConfiguration/JetBrainsPublicProjects_Compose_BuildNativeForPullRequests/4232288?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildChangesSection=true))

**Comment by m-sasha** [comment]
There's also 

- [SentinelHead](https://issuetracker.google.com/issues/283162626)
- [PlacementScope.Companion](https://issuetracker.google.com/issues/283216580)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3362">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by NunoPontes** [comment]
The issues still persists. Every time I use minLines attribute I get a memory leak (Android here)
