### ISSUE TITLE
Compose sources. Remove redundant @OptIn of experimental annotations in the same module

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3364]
After https://github.com/JetBrains/compose-multiplatform-core/pull/687 it is no longer required.

We should remove it in all sourcesets, except commonMain, androidMain

Example:
```
// foundation module
@OptIn(ExperimentalFoundationApi::class) // it is no longer needed
class SomeClass


// material module
@OptIn(ExperimentalFoundationApi::class) // still needed (and shouldn't be used to keep backward compatibility)
class SomeClass
```

**Comment by SnehangshuChakraborty** [comment]
Taking a look into this

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3364">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
