### ISSUE TITLE
Support dispatching move and release events to a node different from the pressed node

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3365]
Composee 1.4.1

```
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.PointerEventType
import androidx.compose.ui.input.pointer.onPointerEvent
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication

@OptIn(ExperimentalComposeUiApi::class)
fun main() = singleWindowApplication {
    var visible by remember { mutableStateOf(false) }
    Box(Modifier.size(100.dp).background(Color.Red).onPointerEvent(PointerEventType.Press) {
        visible = true
        println("Press")
    })

    if (visible) {
        Box(Modifier.size(60.dp).background(Color.Blue).onPointerEvent(PointerEventType.Release) {
            visible = false
            println("Release")
        })
    }
}
```
(need to support for `Popup` as well)

Use cases:
- drag&drop from one node to another
- a temporary popup that only shows during pressed state

Not sure how it can be properly supported. Worth to look at other frameworks.

**Comment by m-sasha** [comment]
The most common use-case here is a context menu which opens on right-mouse-button press, and you can select an item by moving the mouse over it and then releasing.


https://github.com/JetBrains/compose-multiplatform/assets/5230206/724116f7-226f-4356-a1ab-9018c3d930e7

**Comment by MatkovIvan** [comment]
`Popup` and `Box` here are unrelated because `Box`es are inside single focusable owner

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3365">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
