### ISSUE TITLE
Scrolling LazyColumn via mouse wheel stops working

### ISSUE THREAD

**Issue by wojn** [JetBrains/compose-multiplatform#3366]
**Describe the bug**
Scrolling lazy list via mouse wheel while new elements are added to the list and _scrollToItem_ method is called on _LazyListState_, breaks scrolling via mouse wheel.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.0 
- Compose Multiplatform version*:  v1.4.0, v1.4.1 (NOT reproducible with v1.3.1)
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues): 15, 17

**To Reproduce**
Minimal reproducible example:

```kotlin
import androidx.compose.material.MaterialTheme
import androidx.compose.foundation.VerticalScrollbar
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.rememberScrollbarAdapter
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

@Composable
fun App(myStringList: List<String>) {
    MaterialTheme {
        Column(modifier = Modifier.fillMaxSize()) {
            var scrollToBottomEnabled by remember { mutableStateOf(false) }

            // Button used to control scroll-to-bottom feature
            Button(onClick = {scrollToBottomEnabled = !scrollToBottomEnabled}) {
                Text(if (!scrollToBottomEnabled) "Enable auto-scroll" else "Disable auto-scroll")
            }

            Box(modifier = Modifier.fillMaxSize()) {
                val state = rememberLazyListState()

                if (scrollToBottomEnabled) {
                    // Standard approach to implement scroll-to-bottom feature 
                    LaunchedEffect(myStringList.size) {
                        state.scrollToItem(myStringList.size - 1)
                    }
                }

                LazyColumn(Modifier.fillMaxSize(), state) {
                    items(items = myStringList) {
                        Text(it)
                    }
                }

                VerticalScrollbar(
                    modifier = Modifier.align(Alignment.CenterEnd).fillMaxHeight(),
                    adapter = rememberScrollbarAdapter(scrollState = state)
                )

            }
        }
    }
}

fun main() = application {
    val myStringList = mutableStateListOf<String>()

    // Coroutine which keeps adding elements into the myStringList
    CoroutineScope(Dispatchers.Default).launch {
        var someInt = 0

        while (true) {
            delay(50)
            myStringList.add("Element $someInt")
            someInt += 1
        }
    }

    Window(onCloseRequest = ::exitApplication) {
        App(myStringList)
    }
}

```
1. Run minimal reproducible example using Compose v1.4.0 or v1.4.1 
2. Use mouse wheel to scroll the list to make sure it is working fine by default
3. Click on button: "Enable auto-scroll"
4. Try to scroll the list using mouse wheel
5. Click on button: " Disable auto-scroll"
6. Try to scroll the list using mouse wheel

**Expected behavior**
It should be possible to scroll the list using mouse wheel.

**Actual behavior**
Using mouse wheel doesn't scroll the list. The list can still be scrolled by moving vertical scrollbar via mouse.

**Comment by m-sasha** [comment]
Not related to the issue, but there's a bug in your code: `myStringList` should be remembered. It only works correctly because that function never ends up being recomposed.

**Comment by m-sasha** [comment]
Ah, and also, you shouldn't launch a coroutine like that inside `application`: you should use `LaunchedEffect`.

**Comment by MatkovIvan** [comment]
Thanks for the report! It's related to [new mouse wheel animation](https://github.com/JetBrains/compose-multiplatform-core/pull/438).

For now you can [disable](https://github.com/JetBrains/compose-multiplatform-core/blob/release/1.4.1/compose/foundation/foundation/src/desktopMain/kotlin/androidx/compose/foundation/gestures/DesktopScrollable.desktop.kt#L49) this behaviour by setting `compose.scrolling.smooth.enabled`  system property to `false`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3366">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
