### ISSUE TITLE
Wasm 09 Artifact: dependency 'compose-multiplatform-core-compose-runtime-runtime' was not found when running js

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-multiplatform#3367]
**Describe the bug**
Running `jsBrowserDevelopmentRun` in a shared js/wasm app results in an error getting logged to the browser console when opening the page:

```
Uncaught Error: Error loading module 'simple-portal'. Its dependency 'compose-multiplatform-core-compose-runtime-runtime' was not found. Please, check whether 'compose-multiplatform-core-compose-runtime-runtime' is loaded prior to 'simple-portal'.
    at simple-portal.js:8:13
    at simple-portal.js:21:2
```

This can be reproed using the [wasm branch](https://github.com/eygraber/portal/commits/wasm) and running `./gradlew :samples:simple-portal:webApp:jsBrowserDevelopmentRun`

**Affected platforms**
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.4.0-dev-wasm09
- OS architecture (x86 or arm64): x86

**Comment by eymar** [comment]
Could you please check if the workaround from here https://github.com/JetBrains/compose-multiplatform/issues/3345 helps?

**Comment by eygraber** [comment]
Yeah that fixed it. Is that going to be necessary permanently, or can it be fixed on the Kotlin side?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3367">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
