### ISSUE TITLE
Feature for sorting `KotlinSoureSet`s with specific priority in the project explorer

### ISSUE THREAD

**Issue by paxbun** [JetBrains/compose-multiplatform#3368]
This is the state of my current project:
![image](https://github.com/JetBrains/compose-multiplatform/assets/17005454/d8728b07-7985-4acb-a684-33d22fef3663)

Since all non-common source sets are below `commonMain` while only `androidMain` is at the top, making `expect`-`actual` declarations is hard, especially when I need different logic for Android.

I think the IDE should do a topological sort on the source set dependency graph and reorder source sets in the project explorer, so the common source set comes first, and each platform-specific implementation sets come later.

**Comment by alexzhirkevich** [comment]
How it this related to compose multiplatform? =)

https://en.wikipedia.org/wiki/English_alphabet

**Comment by paxbun** [comment]
@alexzhirkevich This repo contains the source code for Compose Multiplatform IDEA plugin and Gradle plugin, so it is related to this repo. I just want to keep the name of the Android source set "androidMain". There also would be source sets whose names start with 'b' or 'c'...

**Comment by pjBooms** [comment]
@paxbun our plugin cannot implement this functionality.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3368">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
