### ISSUE TITLE
After using packageMsi packaging, an error occurred during installation.

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/compose-multiplatform#3369]
**Describe the bug**
After using packageMsi packaging, an error occurred during installation，The error message is as follows:
The installer has encounter an unexpected error installing this package. This may indicate a problem with this package.The error code is 2932.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.10
- Compose Multiplatform version*: 1.4.1
- OS version(s)* (required for Desktop and iOS issues): windows11
- OS architecture (x86 or arm64): 64
- JDK (for desktop issues): JDK17
<img width="281" alt="package_error" src="https://github.com/JetBrains/compose-multiplatform/assets/19502034/1961116e-94b3-4c74-9205-b67a1d76397c">

I don't know where the problem is, whether I can give a possible cause.

**Comment by changhexuefei** [comment]
After closing the antivirus software, I reinstalled it and still reported the same error.
![Uploading 无标题.png…]()

**Comment by pjBooms** [comment]
Compose Multiplatform uses jpackage tool from JDK to create MSI under the hood. Could you please try to create an MSI for simple HelloWorld and manual usage of jpackage in your environment: https://docs.oracle.com/en/java/javase/17/jpackage/packaging-overview.html

Is the problem reproduced with it?

**Comment by changhexuefei** [comment]
I found the cause of this issue, the setting icon caused the above error.
<img width="576" alt="iconset" src="https://github.com/JetBrains/compose-multiplatform/assets/19502034/06dc8d5a-f157-4426-a812-07d23414df1e">

**Comment by changhexuefei** [comment]
Thank you for your reply.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3369">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
