### ISSUE TITLE
Android Studio not showing gutter icons for desktop compose icons

### ISSUE THREAD

**Issue by rustamsmax** [JetBrains/compose-multiplatform#337]
![image](https://user-images.githubusercontent.com/36570577/106384262-b3352100-63eb-11eb-879d-6a43e729eaed.png)
Jetpack Compose

![image](https://user-images.githubusercontent.com/36570577/106384268-be884c80-63eb-11eb-87c2-d22f27448fb0.png)

JetBrains Compose

**Comment by olonho** [comment]
@jimgoog WDYT could be done here?

**Comment by jimgoog** [comment]
This problem confuses me.  The package name is the same, right?  How does AndroidStudio even know the diference?

Are you able to reproduce?  Presumably we should just file a bug against AndroidStudio.

**Comment by akurasov** [comment]
I tried it in latest IJ/AS. 
There is no color gutter for androidx.compose.ui.graphics.Color, only for java.awt.Color. Do we support it at all?

**Comment by akurasov** [comment]
In Bumblebee canary 10 gutters are shown for both Jetpack and JetBrains Compose. In IJ 212.1 - they are not shown.

**Comment by rustamsmax** [comment]
Where is it? I've updated AS to latest version
![image](https://user-images.githubusercontent.com/36570577/131838768-7aa23fd3-8c9a-49b3-8f62-9f62b6ab49c9.png)

**Comment by akurasov** [comment]
That's strange. Do you use Canary 10?

**Comment by rustamsmax** [comment]
Yes
![image](https://user-images.githubusercontent.com/36570577/131847421-b2fb20cc-907d-4b96-aed3-1251bc412432.png)

**Comment by rustamsmax** [comment]
I can't find any change in preferences
![image](https://user-images.githubusercontent.com/36570577/131850555-fd61be3a-563e-4cd2-b694-1b08108eb65d.png)

**Comment by akurasov** [comment]
Is it possible to share your project? I want to see it it will be the same in my env.

**Comment by tingweibai** [comment]
Download and add this plugin to your android studio https://plugins.jetbrains.com/plugin/15439-highlight-colors-for-compose

**Comment by esafak** [comment]
I have the same problem in Android Studio Dolphin | 2021.3.1 Patch 1

**Comment by rustamsmax** [comment]
Hey! Is there any news?

**Comment by BrianCZY** [comment]
> Download and add this plugin to your android studio https://plugins.jetbrains.com/plugin/15439-highlight-colors-for-compose

it work for me
