### ISSUE TITLE
`LocalLayoutDirection` isn't propagated into `DialogWindow`

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#3382]
**Describe the bug**
Creating this bug as was requested here: https://github.com/JetBrains/compose-multiplatform/issues/3142#issuecomment-1643890876

`LocalLayoutDirection.current` returns LTR even when set to RTL outside a `Dialog`.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.1
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): 17

**Expected behavior**
The provided layout direction should be seen inside the dialog composable.

**Comment by mahozad** [comment]
The new common `Dialog` component in version 1.5.0-beta01 does not have this problem.

**Comment by m-sasha** [comment]
Indeed. This is because `Dialog` has been reimplemented on top of `Popup`, which already had this fixed.

**Comment by m-sasha** [comment]
Although there's now the same issue with `DialogWindow`, most likely.

**Comment by mahozad** [comment]
The problem still exists with `DialogWindow` in version 1.5.0-beta01:

```kotlin
fun main() {
    application {
        var direction by remember { mutableStateOf(LayoutDirection.Rtl) }
        CompositionLocalProvider(LocalLayoutDirection provides direction) {
            DialogWindow(onCloseRequest = ::exitApplication) {
                // /* Workaround: */ CompositionLocalProvider(LocalLayoutDirection provides direction) {
                Column(modifier = Modifier.fillMaxWidth()) {
                    Text("$direction")
                    Button(onClick = { direction = if (direction == LayoutDirection.Rtl) LayoutDirection.Ltr else LayoutDirection.Rtl }) {
                        Text("Change direction")
                    }
                }
                // }
            }
        }
    }
}
```

**Comment by m-sasha** [comment]
Fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/777

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3382">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
