### ISSUE TITLE
Unable to add SQLDelight shared KMM code to the Compose Multiplatform template

### ISSUE THREAD

**Issue by sw-dev1** [JetBrains/compose-multiplatform#3386]
Related to

https://github.com/JetBrains/compose-multiplatform/issues/3178

https://github.com/JetBrains/compose-multiplatform/issues/3178#issuecomment-1568982375

**Comment by krisbitney** [comment]
I am having a different, but possibly related, problem when adding SQLDelight to my KMM Compose project. It's the same problem described by this other person who posted on stackoverflow: https://stackoverflow.com/questions/76676789/compose-multiplatform-gradle-plugins-build-errors

**Comment by Atlands** [comment]
```
//setting.gradle.kts
pluginManagement {
    repositories {
        maven(url = "https://oss.sonatype.org/content/repositories/snapshots")
    }
}


//share.build.gradle.kts
plugins {
    id("app.cash.sqldelight") version "2.0.0-rc02"
}

kotlin {
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach {
        it.binaries.framework {
            baseName = "shared"
            isStatic = true
            linkerOpts.add("-lsqlite3")
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
            }
        }
        val androidMain by getting {
            dependencies {
                //database
                implementation("app.cash.sqldelight:android-driver:2.0.0-rc02")
            }
        }
        val iosX64Main by getting
        val iosArm64Main by getting
        val iosSimulatorArm64Main by getting
        val iosMain by getting {
            dependencies {
                implementation("app.cash.sqldelight:native-driver:2.0.0-rc02")
            }
            iosX64Main.dependsOn(this)
            iosArm64Main.dependsOn(this)
            iosSimulatorArm64Main.dependsOn(this)
        }
    }
}

sqldelight {
    databases {
        create("LeDB") {
            packageName.set("com.le.database")
        }
    }

    linkSqlite.set(true)
}
```
in Xcode:
![xcode](https://github.com/JetBrains/compose-multiplatform/assets/46361457/fbe1aa47-f23e-43a4-8f0d-a64022d641e4)

I can use it through the above configuration

**Comment by abhriyaroy** [comment]
Also facing the same with sql delight version 1.5.5

**Comment by sw-dev1** [comment]
@Atlands Thanks, but when I upgrade to sqldelight version "2.0.0-rc02 (was on 1.5.5) I get an error "Compose 1.4.1 is not compatible with Kotlin 1.8.22", which is weird because I have Kotlin 1.8.20 everywhere in my configuration. Also `databases` in the `sqldelight` block is not recognized.

Can anyone suggest a set of compatible versions of

1. Kotlin
2. Compose Multiplatform
3. Compose compiler 
4. SQLDelight

that would work for an Android and iOS multiplatform project?

**Comment by sw-dev1** [comment]
Upgraded to SQLDelight 2.0.0-rc02. The problem persists.

**Comment by sw-dev1** [comment]
With Compose Multiplatform (CMP) [1.5.0-beta01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0-beta01) isStatic=true is no longer required for CMP. Thus one cocoapod can now host both CMP and SQLDelight.
Note: iOS build works only from Xcode, not from AS Giraffe | 2022.3.1
https://github.com/JetBrains/compose-multiplatform/issues/3178 is also closed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3386">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
