### ISSUE TITLE
java.lang.VerifyError when running release build

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/compose-multiplatform#3387]
**Describe the bug**
I have just upgraded my Compose multiplatform project (desktop & android) to Kotlin 1.9.0 and Compose 1.5.0-dev1114. This works without problems when I run from the IDE or when I execute the gradle task 'runDistributable'. But when I try to execute 'runReleaseDistributable' the build part works fine too but the program crashes immediately with:

```
Exception in thread "main" java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    androidx/compose/animation/core/AnimationSpecKt.estimateAnimationDurationMillis(FFFFF)J @604: dstore
  Reason:
    Type top (current frame, locals[68]) is not assignable to double (stack map, locals[68])

```

See the full output in the attachment. What I find strange too is that the location is pointing to AnimationSpecKt but the error happens already when I parse the command line parameters of the main program.

This all worked before with Kotlin 1.8.22 and Compose 1.5.0-dev1104.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-dev1114
- OS version(s)* (required for Desktop and iOS issues): macOS Ventura 13.4.1
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): OpenJDK 17.0.7+7

**To Reproduce**
Sorry, no reproducer.

**Expected behavior**
The release should work the same way as the non-release version.

[output.txt.zip](https://github.com/JetBrains/compose-multiplatform/files/12122235/output.txt.zip)

**Comment by mipastgt** [comment]
Just switching back to Kotlin 1.8.22 doesn't make a difference. Only when I also switch back to Compose 1.5.0-dev1103 the release build works again.

**Comment by pjBooms** [comment]
Can you try to disable proguard for  `runReleaseDistributable`? Will it help?

**Comment by mipastgt** [comment]
> Can you try to disable proguard for `runReleaseDistributable`? Will it help?

How do you do that correctly? Might be helpful for other reasons too.

**Comment by mipastgt** [comment]
With ProGuard disabled the release build seems to run as it did before.

**Comment by AlexeyTsvetkov** [comment]
The issue report in ProGuard repo https://github.com/Guardsquare/proguard/issues/349

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3387">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
