### ISSUE TITLE
Missing animations when minimizing/maximizing/restoring undecorated window

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#3388]
**Describe the bug**
I want to have custom title bar for my Desktop application (especially important to implement dark theme).
So, I set `undecorated = true`.

With undecorated in Windows OS, when maximizing or minimizing a window or restoring a window already minimized to taskbar, the window does not animate. Decorated windows, in contrast, have proper animations:

| Decorated window | Undecorated window |
| --- | --- |
| <video src="https://github.com/JetBrains/compose-multiplatform/assets/29678011/eb549648-17c1-44bf-b81d-d991611b9116"> | <video src="https://github.com/JetBrains/compose-multiplatform/assets/29678011/fa17baec-cc84-480c-98da-1bfe570aa775"> |

I tried the workaround in #3166 but it does not seem to work for undecorated windows (window minimizes but with no animation):

```kotlin
fun minimize() {
    User32.INSTANCE.ShowWindow(
        WinDef.HWND(Pointer((window as ComposeWindow).windowHandle)),
        User32.SW_MINIMIZE // == 6
    )
    // OR
    User32.INSTANCE.CloseWindow(
        WinDef.HWND(Pointer((window as ComposeWindow).windowHandle))
    )
}
```

Electron seems to have had this problem too in the past:
  - https://github.com/electron/electron/issues/32993
  - https://github.com/electron/electron/issues/751

This is the code they use to set proper windows decoration and preserve animations:

https://github.com/electron/electron/blob/3a5e2dd90c099b10679364642a0f7fa398dce875/shell/browser/native_window_views.cc#L367-L390

So, then tried setting just the flags that Electron sets like this for the window:

```kotlin
window(// ...) {
    val frameStyle = User32.WS_OVERLAPPED or User32.WS_MINIMIZEBOX
    User32.INSTANCE.SetWindowLong(
        WinDef.HWND(Pointer(window.windowHandle)),
        User32.GWL_STYLE,
        frameStyle
    )
    App()
}
```

OR modifying the existing window flags:

```kotlin
window(// ...) {
    val defaultStyle = User32.INSTANCE.GetWindowLong(WinDef.HWND(Pointer(window.windowHandle)), GWL_STYLE)
    val newStyle = defaultStyle and User32.WS_THICKFRAME.inv() and User32.WS_DLGFRAME.inv()
    User32.INSTANCE.SetWindowLong(
       WinDef.HWND(Pointer(window.windowHandle)),
       User32.GWL_STYLE,
       newStyle
    )
    App()
}
```

The default close, maximize, minimize buttons are removed but cannot get rid of the title bar.

The IntelliJ IDEA 2023.1 is undecorated and has proper animations.
Maybe you could consider getting a little help from them?

Fixing this problem could probably resolve or help resolve all the following issues:
  - https://github.com/JetBrains/compose-multiplatform/issues/3295
  - https://github.com/JetBrains/compose-multiplatform/issues/3164
  - https://github.com/JetBrains/compose-multiplatform/issues/2062
  - https://github.com/JetBrains/compose-multiplatform/issues/1472

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.1
- OS version(s)*: Windows 10, Windows 11
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): Oracle JDK 17.0.5

**To Reproduce**
Compare app minimize animation in these two:

decorated (default title bar):

```kotlin
fun main() {
    application {
        Window(
            state = rememberWindowState(size = DpSize(400.dp, 300.dp)),
            undecorated = false,
            transparent = false,
            onCloseRequest = ::exitApplication,
        ) {
            Text(text = "This is an example text")
        }
    }
}
```

undecorated (custom title bar):

```kotlin
fun main() {
    application {
        Window(
            state = rememberWindowState(size = DpSize(400.dp, 300.dp)),
            undecorated = true,
            transparent = true, // for rounded corners
            onCloseRequest = ::exitApplication,
        ) {
            Surface(
                modifier = Modifier
                    .fillMaxSize()
                    .border(Dp.Hairline, Color.Gray, RoundedCornerShape(8.dp))
                    .clip(RoundedCornerShape(8.dp))
            ) {
                Column {
                    WindowDraggableArea(modifier = Modifier.fillMaxWidth().height(30.dp)) {
                        Row(
                            horizontalArrangement = Arrangement.SpaceBetween,
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Text(text = "Title")
                            Row {
                                Box(
                                    contentAlignment = Alignment.Center,
                                    modifier = Modifier
                                        .width(48.dp)
                                        .fillMaxHeight()
                                        .clickable { window.isMinimized = true }
                                ) {
                                    Icon(
                                        imageVector = Icons.Custom.Minimize,
                                        contentDescription = null,
                                        modifier = Modifier.size(12.dp)
                                    )
                                }
                                Box(
                                    contentAlignment = Alignment.Center,
                                    modifier = Modifier
                                        .width(48.dp)
                                        .fillMaxHeight()
                                ) {
                                    Icon(
                                        imageVector = Icons.Custom.Close,
                                        contentDescription = null,
                                        modifier = Modifier.size(14.dp)
                                    )
                                }
                            }
                        }
                    }
                    Text(text = "This is an example text")
                }
            }
        }
    }
}
```

**Expected behavior**
Undecorated windows should have animations when minimizing/maximizing/restoring them.

**Comment by pjBooms** [comment]
Relates to https://github.com/JetBrains/compose-multiplatform/issues/3166

**Comment by mahozad** [comment]
A good example:
  - https://github.com/rossy/borderless-window
  - https://discourse.glfw.org/t/making-a-custom-titlebar/2392/3

**Comment by mahozad** [comment]
https://github.com/JetBrains/compose-multiplatform/assets/29678011/0078bab6-6833-4fe8-b064-713effc475ac


Fixed the problem in Windows (don't know if the **problem** applies to Linux or macOS).
Tried it successfully in Windows 7, Windows 10, Windows 11.

Adopted from https://github.com/kalibetre/CustomDecoratedJFrame which provides solution for Swing (Jframe) windows.

With this, native animations for window appearance (open), window disappearance (close), window minimize, window restore, and (possibly) window maximize work correctly. The repo above also implemented Aero snap feature (and possibly, shaking window title to hide other windows) but I omitted it.

The only missing thing is the native window border and shadows.
Also, the window cannot be made transparent (otherwise, it loses animations).

To be honest, I don't know how the `CustomWindowProcessor` below works. But made it to work.

```kotlin
implementation("net.java.dev.jna:jna-jpms:5.13.0")
implementation("net.java.dev.jna:jna-platform-jpms:5.13.0")
// ...
```

```kotlin
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.platform.win32.BaseTSD.LONG_PTR
import com.sun.jna.platform.win32.User32
import com.sun.jna.platform.win32.WinDef.*
import com.sun.jna.platform.win32.WinUser.WM_DESTROY
import com.sun.jna.platform.win32.WinUser.WindowProc
import com.sun.jna.win32.W32APIOptions
// ...

fun main() = application {
    Window(
        undecorated = false, // This should be set to false, but the window will be undecorated
        transparent = false,
        // ...
    ) {
        val windowHandle = remember(this.window) {
        val windowPointer = (this.window as? ComposeWindow)
                ?.windowHandle
                ?.let(::Pointer)
                ?: Native.getWindowPointer(window)
            HWND(windowPointer)
        }
        remember(windowHandle) { CustomWindowProcessor(windowHandle) }
        MyAppContent()
    }
}
```

```kotlin
@Suppress("FunctionName")
interface User32Ex : User32 {
    fun SetWindowLong(hWnd: HWND, nIndex: Int, wndProc: WindowProc): LONG_PTR
    fun SetWindowLong(hWnd: HWND, nIndex: Int, wndProc: LONG_PTR): LONG_PTR
    fun SetWindowLongPtr(hWnd: HWND, nIndex: Int, wndProc: WindowProc): LONG_PTR
    fun SetWindowLongPtr(hWnd: HWND, nIndex: Int, wndProc: LONG_PTR): LONG_PTR
    fun CallWindowProc(proc: LONG_PTR, hWnd: HWND, uMsg: Int, uParam: WPARAM, lParam: LPARAM): LRESULT
}

class CustomWindowProcessor(windowHandle: HWND) : WindowProc {
    // See https://learn.microsoft.com/en-us/windows/win32/winmsg/about-messages-and-message-queues#system-defined-messages
    private val WM_NCCALCSIZE = 0x0083
    private val WM_NCHITTEST = 0x0084
    private val GWLP_WNDPROC = -4
    private val USER32EX_INSTANCE = Native.load("user32", User32Ex::class.java, W32APIOptions.DEFAULT_OPTIONS)
    private var DEF_WND_PROC = if (is64Bit()) {
        USER32EX_INSTANCE.SetWindowLongPtr(windowHandle, GWLP_WNDPROC, this)
    } else {
        USER32EX_INSTANCE.SetWindowLong(windowHandle, GWLP_WNDPROC, this)
    }

    override fun callback(hWnd: HWND, uMsg: Int, wParam: WPARAM, lParam: LPARAM): LRESULT {
        return when (uMsg) {
            WM_NCCALCSIZE -> { LRESULT(0) }
            WM_NCHITTEST -> { USER32EX_INSTANCE.CallWindowProc(DEF_WND_PROC, hWnd, uMsg, wParam, lParam) }
            WM_DESTROY -> {
                if (is64Bit()) {
                    USER32EX_INSTANCE.SetWindowLongPtr(hWnd, GWLP_WNDPROC, DEF_WND_PROC)
                } else {
                    USER32EX_INSTANCE.SetWindowLong(hWnd, GWLP_WNDPROC, DEF_WND_PROC)
                }
                LRESULT(0)
            }
            else -> { USER32EX_INSTANCE.CallWindowProc(DEF_WND_PROC, hWnd, uMsg, wParam, lParam) }
        }
    }

    private fun is64Bit(): Boolean {
        val bitMode = System.getProperty("com.ibm.vm.bitmode")
        val model = System.getProperty("sun.arch.data.model", bitMode)
        return model == "64"
    }
}
```

To minimize the window, instead of using
`(window as? ComposeWindow)?.isMinimized = true` use `User32.INSTANCE.CloseWindow(windowHandle)`:

```kotlin
@Composable
fun WindowScope.MyCustomMinimizeButton() {
    val windowHandle = remember(this.window) {
        val windowPointer = (this.window as? ComposeWindow)
            ?.windowHandle
            ?.let(::Pointer)
            ?: Native.getWindowPointer(window)
        HWND(windowPointer)
    }
    Button(onclick = { User32.INSTANCE.CloseWindow(windowHandle) }) {
        Text("Minimize")
    }
}
```

**Comment by mahozad** [comment]
@pjBooms Fixed the problem with native animations and shadows as described in the above comment.

Can they be incorporated into Compose Multiplatform code?

**Comment by pjBooms** [comment]
@mahozad currently we are busy with other tasks

**Comment by mahozad** [comment]
OK, no problem.

**Comment by sheng-ri** [comment]
@mahozad 
I tried this,it works, but I can't resize the window.

**Comment by mahozad** [comment]
@sheng-ri 
My app did not need to be resized (I set `resizable = false`).
Sorry.

**Comment by sheng-ri** [comment]
> @sheng-ri My app did not need to be resized (I set `resizable = false`). Sorry.

I found a solution for resizable window base your code. You need make window style has WS_CAPTION.
.

**Comment by sleinexxx** [comment]
> > @sheng-riРазмер моего приложения не нужно было изменять (я установил `resizable = false`). Извини.
> 
> Я нашел решение для изменения размера окна в вашем коде. Вам нужно, чтобы стиль окна имел WS_CAPTION. .

how to set this style?

**Comment by sheng-ri** [comment]
@sleinexxx 

See [win32 api](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptra)  
You can convert this to use JNA.
Here a example(Using FFI):
```java
final var style = (long)GetWindowLongA.invoke(hWnd, GWL_STYLE);
SetWindowLongA.invoke(hWnd, GWL_STYLE, style |  WS_CAPTION);
```

**Comment by sleinexxx** [comment]
> @sleinexxx
> 
> See [win32 api](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptra) You can convert this to use JNA. Here a example(Using FFI):
> 
> ```java
> final var style = (long)GetWindowLongA.invoke(hWnd, GWL_STYLE);
> SetWindowLongA.invoke(hWnd, GWL_STYLE, style |  WS_CAPTION);
> ```

I tried to do this, but it didn't work. WS_SIZEBOX too

**Comment by sheng-ri** [comment]
> I tried to do this, but it didn't work. WS_SIZEBOX too

@sleinexxx
I forget one thing,This solution need set `undecorated=true`
I still can't undertstand that, but seems this works.

**Comment by sleinexxx** [comment]
> > I tried to do this, but it didn't work. WS_SIZEBOX too
> 
> @sleinexxx I forget one thing,This solution need set `undecorated=true` I still can't undertstand that, but seems this works.

it works! thanks a lot

**Comment by Sanlorng** [comment]
> No `undecorated = true` required

Hit test handled by `SkiaLayer`'s Canvas，See [TransparentDecorationWindowProc](https://github.com/lhwdev/compose-window/blob/main/modules/platform/windows/src/main/kotlin/com/lhwdev/compose/window/platform/windows/TransparentDecorationWindowProc.kt)
if hit non client area return `HTTRRANSPARENT `that will pass the event  and make `ComposeWindow `handled the `NCHITTEST `event，then we return the non client area hit test in the CustomWindowDecoration.
Another issue was `HTMAXBUTTON `will intercept the mouse event that will cause custom maximize button can't recieve the click event, so we need redirect the mouse event when hit area is `HTMAXBUTTON`
**Skia Layer hit test**
```Kotlin
    override fun callback(
        hwnd: WinDef.HWND,
        uMsg: Int,
        wParam: WinDef.WPARAM,
        lParam: WinDef.LPARAM
    ): WinDef.LRESULT {

        return when(uMsg) {
            WM_NCHITTEST -> {
                val x = lParam.toInt() and 0xFFFF
                val y = (lParam.toInt() shr 16) and 0xFFFF
                val point = POINT(x, y)
                USER32EX?.ScreenToClient(windowHandle, point)
                val offset = Offset(point.x.toFloat(), point.y.toFloat())
                point.clear()
                hitResult = hitTest(offset)
                when(hitResult) {
                    // 1 is client area, 9 is HTMAXBUTTON
                    1, 9 -> LRESULT(hitResult.toLong())
                    else -> LRESULT(-1)
                }
            }
            WM_NCMOUSEMOVE -> {
                //dispatch the mouse event to custom maximize button
                USER32EX?.SendMessage(contentHandle, WM_MOUSEMOVE, wParam, lParam)
                WinDef.LRESULT(0)
            }

            WM_NCLBUTTONDOWN -> {
                //dispatch the mouse event to custom maximize button
                USER32EX?.SendMessage(contentHandle, WM_LBUTTONDOWN, wParam, lParam)
                LRESULT(0)
            }

            WM_NCLBUTTONUP -> {
                //dispatch the mouse event to custom maximize button
                USER32EX?.SendMessage(contentHandle, WM_LBUTTONUP, wParam, lParam)
                return LRESULT(0)
            }

            else -> {
                USER32EX?.CallWindowProc(defaultWindowProc, hwnd, uMsg, wParam, lParam) ?: WinDef.LRESULT(
                    0
                )
            }
        }
    }
```
finally: i implement the window decoration like the video shows.

https://github.com/JetBrains/compose-multiplatform/assets/26089739/750ee5a7-7126-41eb-b5b0-1c94fda402c0

**Comment by mahozad** [comment]
@Sanlorng Can you please share how you obtain the `contentHandle`?

or even better, share your whole code for window decoration?

**Comment by Sanlorng** [comment]
> @Sanlorng Can you please share how you obtain the `contentHandle`?
> and your hitTest() function?
> 
> or even better, share your whole code for window decoration?

I will share it when i rearrange the code

**Comment by Sanlorng** [comment]
> @Sanlorng Can you please share how you obtain the `contentHandle`?
> and your hitTest() function?
> 
> or even better, share your whole code for window decoration?

contentHandle is HWND(SkiaLeyer.canvas)

**Comment by Sanlorng** [comment]
> @Sanlorng Can you please share how you obtain the `contentHandle`? and your hitTest() function?
> 
> or even better, share your whole code for window decoration?

@mahozad  i open a Pull Request which include the whole implementation in the one commit and reference this issue, you can fork the code at your app and try it

**Comment by mahozad** [comment]
It works! Thank you.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3388">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
