### ISSUE TITLE
iOS. Support resources in an arbitrary module (not only in `shared/src/commonMain/resources`)

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3391]
Compose 1.5.0-dev1114

Currently, Compose for iOS support resources only in the `shared/src/commonMain/resources` folder. Real world applications usually contain multiple modules, and they often need local stored resources (in `shared/catalog/src/commonMain/resources`, for example). This isn't supported, because `shared` module is either hardcoded in [project.pbxproj](https://github.com/JetBrains/compose-multiplatform/pull/3340/files#diff-cf069985d2f8eb184d10513583a7061da7cccb3cc86172128ad0c3c1b76ba678), or `kotlin("native.cocoapods")` is applied to this module.

As an use case, see the TiVi project:
1. clone the project https://github.com/chrisbanes/tivi/pull/1395
2. revert [the workaround](https://github.com/chrisbanes/tivi/pull/1395/commits/8fb3b0d406da7a17418dee8f5df8f5197d625d37)
3. try to access [resources](https://github.com/chrisbanes/tivi/tree/cb/kotlin-1.9/common/ui/resources/fonts/src/commonMain/resources/font) from the `ui/resources/fonts` module.
4. run it on iOS

**Comment by AlexeyTsvetkov** [comment]
@igordmn we have not implemented support of storing resources outside of one shared module. TiVi clearly stores them in multiple other modules. That is a non-trivial functionality we have not planned for 1.5.

**Comment by jbruchanov** [comment]
@AlexeyTsvetkov 
Sorry for DM, 
isn't there at least a way to do naive merge of resources and simply fail if there is a conflict ?

I have this setup
```
:shared [file1]
   :shared_dep1 [file2]
   :shared_dep2 [file3]
```

there is no conflict (assuming that only conflict can happen like on os filesystem level?), but I can only read `file1` in final ios product

**Comment by igordmn** [comment]
> isn't there at least a way to do naive merge of resources and simply fail if there is a conflict ?

There is definitely a way, we can do this with some Gradle magic. But to do it properly and provide it at the framework level, we should do a proper reaserch.

**Comment by jbruchanov** [comment]
@igordmn 
is there some other ticket with a discussion all around the problem ?
I'm trying to understand more the details what needs to be done under the hood, I'm still sort of seeing it simply as "copy all files into common place" and use it, otherwise fail with some "duplicated files error" like what happens with jar files

**Comment by igordmn** [comment]
There is no another public ticket for this issue.

> "copy all files into 1 common place" and use it, otherwise fail with some "duplicated files error"

In theory, yes, it can be one of the first solutions for the issue.

The future solution might involve making resources only visible to the module where they placed (that helps avoiding conflicts).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3391">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
