### ISSUE TITLE
Question: A direction about how to use my C++ library inside Compose Multiplatform

### ISSUE THREAD

**Issue by paulocoutinhox** [JetBrains/compose-multiplatform#3393]
Hi,

Im searching, but im lost. I want make a simple sample for my library using Compose Multiplatform.

My library:
https://github.com/xplpc/xplpc

Today, it generate the library for iOS, Android, Desktop, WASM and all Flutter supported targets. So, i want add support for Compose Multiplatform now.

I created a simple project and it is running:
<img width="1180" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/395096/4009a326-6c3f-4463-82a9-fb14a6d0917b">

Now, i need add my library to be called from Compose Multiplatform. 

So, some questions:
- How can i generate a library for desktop version?
- The existing Android library can be used in Compose Multiplatform Android target?

Thanks.

**Comment by paulocoutinhox** [comment]
I made a simple project that run on android and desktop:
https://github.com/xplpc/sample-compose

My problems with Android was solved, i can reuse my library.

Now i need understand:
- How i can create a library for desktop to put/use here: https://github.com/xplpc/sample-compose/blob/main/desktop/build.gradle.kts#L21
- What is the best approach to create a single interface, but each target need call their native library/implementation here: https://github.com/xplpc/sample-compose/blob/main/desktop/src/jvmMain/kotlin/Main.kt#L13-L42 and here: https://github.com/xplpc/sample-compose/blob/main/android/src/main/java/com/xplpc/runner/android/activity/MainActivity.kt#L23-L44

**Comment by pjBooms** [comment]
> How i can create a library for desktop to put/use here

JNI code is basically the same for Android and Desktop. AFAIK, there is no standard way to put/use a JNI native library in Kotlin Multiplatform, you need to write some custom gradle scripting. You may look at our Skiko repository (https://github.com/JetBrains/skiko/tree/master/skiko) where we are solving the same problem.

>What is the best approach to reuse string/drawable/etc resources?

There are two multiplatform libraries that handle string resources: https://github.com/icerockdev/moko-resources, https://github.com/Skeptick/libres . We are going to add strings support to our resource library as well.

>Can i reuse most of my android library things to a java desktop?

You may try.

**Comment by JackyKeke** [comment]
> > How i can create a library for desktop to put/use here
> 
> JNI code is basically the same for Android and Desktop. AFAIK, there is no standard way to put/use a JNI native library in Kotlin Multiplatform, you need to write some custom gradle scripting. You may look at our Skiko repository (https://github.com/JetBrains/skiko/tree/master/skiko) where we are solving the same problem.
> 
> > What is the best approach to reuse string/drawable/etc resources?
> 
> There are two multiplatform libraries that handle string resources: https://github.com/icerockdev/moko-resources, https://github.com/Skeptick/libres . We are going to add strings support to our resource library as well.
> 
> > Can i reuse most of my android library things to a java desktop?
> 
> You may try.

Hi， i have read all code of  skiko ,i wonder  how you compile c++ code ? by cmake or another compilation tools ?

**Comment by JackyKeke** [comment]
感谢你的来信，我会及时处理。祝工作顺利，万事如意

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3393">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by JackyKeke** [comment]
感谢你的来信，我会及时处理。祝工作顺利，万事如意
