### ISSUE TITLE
how to use jb-compose 1.5.0-dev1114

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#3394]
Hi
How can i use jb-compose version 1.5.0-dev1114?
When I added it to the project I got a lot of errors. Please create or introduce a sample project for me.
thank you.

**Comment by Atlands** [comment]
Perhaps you could try creating a new project?
It is possible that one of the libraries you imported is currently incompatible, which is the case for me

**Comment by mahramane** [comment]
@Atlands 
I think with this version, many code will change in build files. especially for web wasm.
do you know what we should do?

**Comment by pjBooms** [comment]
Hello. What errors do you have? If I change kotlin.version=1.9.0, compose.version=1.5.0-dev1114 in gradle.properties for https://github.com/JetBrains/compose-multiplatform-template everything seems working for me.

**Comment by pjBooms** [comment]
>especially for web wasm.

If you use wasm target there will be a separate dev build for 1.5

**Comment by Kashif-E** [comment]
it does not work properly with kotlin versions below 1.9.0

**Comment by pjBooms** [comment]
It is known problem. Will be fixed in next dev version

**Comment by pjBooms** [comment]
@Kashif-E  Please check [1.5.0-dev1122](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0-dev1122)

**Comment by Kashif-E** [comment]
Thanks @pjBooms new dev version is working fine

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3394">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
