### ISSUE TITLE
ViewConfiguration.touchSlop value is quite low on iOS

### ISSUE THREAD

**Issue by chrisbanes** [JetBrains/compose-multiplatform#3397]
`ViewConfiguration.touchSlop` is currently set to `3.dp` [here](https://github.com/JetBrains/compose-multiplatform-core/blob/0fdc2a17c507cae6040aac29e1f37f01723d2084/compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/window/ComposeWindow.uikit.kt#L283), which is quite low for anything which uses a combination of click listeners, vertical scrolling and horizontal scrolling (lots of clicks when the starting to drag, and other false-positive gestures).

I've increased the touch slop locally in my app to `8.dp` (the same value as what Android uses) and it works much better for my use case.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3397">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
