### ISSUE TITLE
iOS Support for voiceover

### ISSUE THREAD

**Issue by MikolajKakol** [JetBrains/compose-multiplatform#3401]
In order to provide apps to everyone we need to support voiceover.  https://support.apple.com/en-gb/guide/iphone/iph3e2e415f/ios

This means the usage of `Modifier.semantics` from
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/semantics/SemanticsProperties.kt;l=35?q=SemanticsProperties&ss=androidx%2Fplatform%2Fframeworks%2Fsupport
 should reflect iOSs accessibility protocol.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3401">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
