### ISSUE TITLE
Functions or classes can't call from DesktopApp/jvmMain (Unresolved reference)

### ISSUE THREAD

**Issue by dQqAn** [JetBrains/compose-multiplatform#3403]
**Describe the bug**
I opened this [project](https://github.com/JetBrains/compose-multiplatform/tree/master/examples/imageviewer) and i can't call the functions like [ImageViewerDesktop](https://github.com/JetBrains/compose-multiplatform/blob/master/examples/imageviewer/shared/src/desktopMain/kotlin/example/imageviewer/view/ImageViewer.desktop.kt) from DesktopApp/jvmMain. I didn't do anything, just opened the project.

**Affected platforms**
- Desktop 

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.1
- OS version(s)*: Windows 10
- JDK: 17

**Expected behavior**
DesktopApp/jvmMain have to access commonMain and jvmMain functions.

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/48219880/401e7a3c-7883-4e53-8f03-ccc2a5b37113)

**Comment by dima-avdeev-jb** [comment]
What kind of IDE and concrete version are you using?

**Comment by dima-avdeev-jb** [comment]
Thanks! One of possible workarounds is to temporary disable Android plugin in IDEA:


<img width="983" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/c6666ab6-ce1e-434e-bc4f-c4ccf1a79ea8">

**Comment by dima-avdeev-jb** [comment]
Also, similar issue on androidMain source set desctibed here:
 - https://github.com/JetBrains/compose-multiplatform/issues/2340

**Comment by dQqAn** [comment]
> Thanks! One of possible workarounds is to temporary disable Android plugin in IDEA:
> 
> <img alt="image" width="983" src="https://user-images.githubusercontent.com/99798741/255989471-c6666ab6-ce1e-434e-bc4f-c4ccf1a79ea8.png">

i did it but i have more problems,
(in addition,  I have Intellij idea 2023.1.4 and Intellij idea Community 2023.1.4 installed on my system. I tried both projects.)

![image](https://github.com/JetBrains/compose-multiplatform/assets/48219880/7df2e135-1666-4d90-a3bb-f6adf4ea054c)
![image](https://github.com/JetBrains/compose-multiplatform/assets/48219880/8d29c304-5fa9-4e62-929d-ddb57fda2b05)

**Comment by dQqAn** [comment]
if you want more details for this issue:

desktopApp only access its own module. It has to access shared/commonMain and shared/desktopMain. but it doesn't access them.
![image](https://github.com/JetBrains/compose-multiplatform/assets/48219880/ec1d8bb8-250a-49b0-b90e-02e9abfe3f52)

I haven't changed anything so far. But i want to show something for you.
![image](https://github.com/JetBrains/compose-multiplatform/assets/48219880/b639609c-b4c5-46c3-9906-4c8742db17ca)

When I change the jvmMain directory to commonMain (for dekstopApp), desktopApp/commonMain can see shared/commonMain.
Compare with the two previous pictures.
desktopApp's build.gradle.kts: val jvmMain by getting -> val commonMain by getting
![image](https://github.com/JetBrains/compose-multiplatform/assets/48219880/1fa0a0e6-216d-4cea-956b-d6b3fcde5052)

**Comment by dQqAn** [comment]
i found the problem, intellij idea > file > manage ide settings > restore default settings. Now, everything is working... Sorry for the problem.

**Comment by dQqAn** [comment]
i updated the jdk to 17.0.8
ide: 2023.0.5
don't update this kotlin plugin version:
![image](https://github.com/JetBrains/compose-multiplatform/assets/48219880/df58f777-738e-48e2-9db9-05d6f1fae2b7)

**Comment by pablichjenkov** [comment]
You can do a full cleanup and reinstall everything from zero. Perhaps some configuration file or dependency cache got corrupted.
Remove the directories referened in this url: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519
Remove **~/.gradle/caches**
Remove **.gradle** and **.idea** folders in your project as well as all build folders.
Uninstall the IDE and reinstall it again.

**Comment by dima-avdeev-jb** [comment]
@dQqAn 
Also, you can try open project with newer Kotlin plugin and use action "Main Menu" -> "File" -> "Invalidate caches...":

<img width="511" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/d006545e-632e-4153-9017-d206f7a4c070">

**Comment by dQqAn** [comment]
> @dQqAn Also, you can try open project with newer Kotlin plugin and use action "Main Menu" -> "File" -> "Invalidate caches...":
> 
> <img alt="image" width="511" src="https://user-images.githubusercontent.com/99798741/256428030-d006545e-632e-4153-9017-d206f7a4c070.png">

I already try it this, i will try [that](https://github.com/JetBrains/compose-multiplatform/issues/3403#issuecomment-1650799198) sometime.

**Comment by dQqAn** [comment]
i updated the ide to 2023.2 and kotlin plugin version is up to date now. My problem is solved.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3403">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
