### ISSUE TITLE
Custom Resource Loader for Fonts

### ISSUE THREAD

**Issue by daniel-jasinski** [JetBrains/compose-multiplatform#3405]
Provide API point that allows for providing custom ResourceLoader instance for loading fonts, similar to `painterResource` for icons.

**Comment by dima-avdeev-jb** [comment]
Thanks!
You can follow this similar issue:
 - https://github.com/JetBrains/compose-multiplatform/issues/3127

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3405">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
