### ISSUE TITLE
SIGSEGV detected by the Java Runtime Environment 

### ISSUE THREAD

**Issue by Mouwrice** [JetBrains/compose-multiplatform#3411]
Hi, I have been working on my first ever compose multiplatform [project](https://github.com/Mouwrice/proguard-core-visualizer) and I am amazed. So thanks for the great work!

Anyway, to come to the point. When running using a java JDK of version 17 or higher the application appears to be randomly crashing with the following exception:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa19f3379c8, pid=7545, tid=7559
#
# JRE version: OpenJDK Runtime Environment (17.0.2+8) (build 17.0.2+8-86)
# Java VM: OpenJDK 64-Bit Server VM (17.0.2+8-86, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xd379c8]  SymbolTable::do_lookup(char const*, int, unsigned long)+0xd8
#
# Core dump will be written.
```

It does seems to work with no issues on java 11 so that is what I have set my jvmToolchain for now.

**Affected platforms**
Select one of the platforms below:
- Desktop (only tested on Ubuntu 23.04, with Wayland and Gnome 44)

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.4.3
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 23.04
- OS architecture (x86 or arm64): x86_64
- JDK (for desktop issues): OpenJDK 64-Bit Server VM (17.0.2+8-86, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. ./gradlew jvmRun

**Expected behavior**
Evidently, it should not crash. But I fear that it has more something todo with a native library then compose multiplatform :/

I hope to have reported an actual issue and not a stupidity. But if I did please do tell :smile: 

**Additional context**
The log files produced:
[hs_err_pid7545.log](https://github.com/JetBrains/compose-multiplatform/files/12170620/hs_err_pid7545.log)
[replay_pid7545.log](https://github.com/JetBrains/compose-multiplatform/files/12170623/replay_pid7545.log)

**Comment by Mouwrice** [comment]
From the looks of it it may be skiko related?
On the last line of the replay log it shows:
`compile org/jetbrains/skiko/context/OpenGLContextHandler initCanvas ()V -1 3`

**Comment by dima-avdeev-jb** [comment]
@eymar Can you please try to reproduce?

**Comment by Mouwrice** [comment]
Oh thanks for your comment!

> Then I run ./gradlew run (a task created by compose gradle plugin) instead of ./gradlew jvmRun because of:

> > * What went wrong:
> > Execution failed for task ':jvmRun'.
> > No main class specified and classpath is not an executable jar.

> And the app finally launched. Do the steps above make sense to you? I'm wondering if those steps are necessary for you.

I remember once not having `./gradlew run` but this must have been a mistake. It is indeed just `./gradlew run`. `./gradlew jvmRun` is the configuration that IntelliJ used when clicking the "play" button in the gutter.
![image](https://github.com/JetBrains/compose-multiplatform/assets/56763273/0bae8420-30c0-4de8-aed1-c90d22ac8956)

> Was JvmVendorSpec.MICROSOFT vendor forced intentionally?

Was indeed intentional, this is just for conveyor to work:
https://github.com/hydraulic-software/conveyor/issues/72

Sorry for the confusion.

Ok so the crashes seem to happen when I interact with the treeview on the left hand side from when we used [bonsai](https://github.com/adrielcafe/bonsai). But the Bonsai library is no longer maintained and we wanted more control over the UI so we implemented it ourselves.
(https://github.com/Mouwrice/proguard-core-visualizer/commit/5572732bbc181212379cd6b052b022ec5e4e85c1)

I was able to reproduce it on commits before that (such as: https://github.com/Mouwrice/proguard-core-visualizer/commit/d2e441c513bd6d53674e2b1fff56b75afdbda746) but not on any commits after we replaced the tree view with our own.
Note that it does not have to happen immediately, it still seems random after having loaded and clicked on mutliple tree view items.

If you wish to inspect it, some changes need to be made, (we are moving fast, and using not yet released ProGuardCORE versions):
replace: https://github.com/Mouwrice/proguard-core-visualizer/blob/640aa7dd1a55ee061229583fe5e74ec12c1f931a/build.gradle.kts#L42
with: https://github.com/Mouwrice/proguard-core-visualizer/blob/1231208a4081a5f46ba9434ee9ba2f8b7cba690f/build.gradle.kts#L42

and `jsonPrinter` is `jsonprinter` as of the latest master version of proguard core (gradle will complain and point you to the location)

I will let someone else also test it out (who also had this issue), to see if it is resolved  on their side as well with recent versions of the project.

Some more testing is needed, but for now it seems that the no longer maintained bonsai library is to blame.


On a sidenote:
An issue that we seem to continue having are the following errors that are sometimes detected (on both Java 11 and 17):
`free(): unaligned chunk detected in tcache 2`
or
`free(): double free detected in tcache 2`

Is this a known issue?
If not, I will make a seperate issue for it.
These are a lot more rare though and pose less of a problem.

**Comment by eymar** [comment]
> On the older commits were I am able to sometimes reproduce it, the log files always end with the following line:
compile org/jetbrains/skiko/context/OpenGLContextHandler initCanvas ()V -1 3

Could you please link the commit hash where it's reproducible?

Would adding
```
    application {
        mainClass = "MainKt"
        jvmArgs += "-XX:+PrintCompilation"
        jvmArgs += "-XX:CompileThreshold=1"
```

increase the chances (decrease the time) to reproduce?

**Comment by Mouwrice** [comment]
Commit hash:
d2e441c513bd6d53674e2b1fff56b75afdbda746

**Comment by eymar** [comment]
jfyi: 

using Commit hash:
d2e441c513bd6d53674e2b1fff56b75afdbda746

It doesn't compile:
> Task :compileKotlinJvm FAILED
e: file:///home/sashko/Downloads/proguard-core-visualizer/src/jvmMain/kotlin/data/LoadUtil.kt:16:33 Unresolved reference: jsonPrinter
e: file:///home/sashko/Downloads/proguard-core-visualizer/src/jvmMain/kotlin/data/LoadUtil.kt:126:27 Unresolved reference: JsonPrinter

**Comment by eymar** [comment]
> I am not noticing any difference here.

Did you see 
> 49630 5628       3       org.jetbrains.skiko.context.OpenGLContextHandler::initCanvas (185 bytes)
in the logs?

**Comment by Mouwrice** [comment]
Indeed it will not.
> and jsonPrinter is jsonprinter as of the latest master version of proguard core (gradle will complain and point you to the location)

the older code is not adapted to this change

**Comment by Mouwrice** [comment]
> OpenGLContextHandler::initCanvas

Oh yes, it is in all the crash logs.
I can provide even more of them:
[hs_err_pid7545.log](https://github.com/JetBrains/compose-multiplatform/files/12241135/hs_err_pid7545.log)
[hs_err_pid20025.log](https://github.com/JetBrains/compose-multiplatform/files/12241136/hs_err_pid20025.log)
[hs_err_pid101452.log](https://github.com/JetBrains/compose-multiplatform/files/12241137/hs_err_pid101452.log)
[hs_err_pid104079.log](https://github.com/JetBrains/compose-multiplatform/files/12241138/hs_err_pid104079.log)
[hs_err_pid108671.log](https://github.com/JetBrains/compose-multiplatform/files/12241140/hs_err_pid108671.log)
[replay_pid7545.log](https://github.com/JetBrains/compose-multiplatform/files/12241141/replay_pid7545.log)
[replay_pid101452.log](https://github.com/JetBrains/compose-multiplatform/files/12241142/replay_pid101452.log)
[replay_pid104079.log](https://github.com/JetBrains/compose-multiplatform/files/12241144/replay_pid104079.log)
[replay_pid108671.log](https://github.com/JetBrains/compose-multiplatform/files/12241145/replay_pid108671.log)

**Comment by Mouwrice** [comment]
@eymar I have created a branch that that can be used to test:
https://github.com/Mouwrice/proguard-core-visualizer/tree/bug/hunt-for-sigsegv

On it i have gotten the following log output:
[log.log](https://github.com/JetBrains/compose-multiplatform/files/12241246/log.log)

```
22490 5518       3       org.jetbrains.skiko.DrawingSurfaceInfo::<init> (69 bytes)
  22504 3290       4       kotlinx.coroutines.internal.LockFreeTaskQueue::removeFirstOrNull (51 bytes)   made not entrant
  22539 5519       3       sun.awt.X11.XAtom::hashCode (15 bytes)
  22541 5520       3       kotlinx.coroutines.sync.MutexKt::access$getEMPTY_UNLOCKED$p (4 bytes)
  22543 5521       3       androidx.compose.material.ripple.RippleAnimation::draw-4WTKRHQ (532 bytes)
  22554 5522       3       kotlinx.coroutines.internal.LockFreeTaskQueue::removeFirstOrNull (51 bytes)
  22639 5523       3       org.jetbrains.skiko.SkiaLayer::getFullscreen (8 bytes)
  22640 5524       3       org.jetbrains.skiko.FullscreenAdapter::getFullscreen (22 bytes)
  22672 5525   !   3       org.jetbrains.skiko.context.OpenGLContextHandler::initContext (142 bytes)
  22672 5530     n 0       org.jetbrains.skia.SurfaceKt::_nGetCanvas (native)   (static)
  22672 5533     n 0       org.jetbrains.skia.CanvasKt::_nClear (native)   (static)
  22674 5526       3       org.jetbrains.skiko.context.OpenGLContextHandler::initCanvas (185 bytes)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f4cd4c158f8, pid=127895, tid=127909
#
# JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8+7) (build 17.0.8+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xe158f8]  SymbolTable::do_lookup(char const*, int, unsigned long)+0xd8
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/mauricev/Documents/proguard-core-visualizer/core.127895)
#
# An error report file with more information is saved as:
# /home/mauricev/Documents/proguard-core-visualizer/hs_err_pid127895.log
  22686 5536       4       androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2::create (20 bytes)
  22688 2905       3       androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2::create (20 bytes)   made not entrant
#
# Compiler replay data is saved as:
# /home/mauricev/Documents/proguard-core-visualizer/replay_pid127895.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
#

> Task :run FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
3 actionable tasks: 1 executed, 2 up-to-date
```

**Comment by Mouwrice** [comment]
@eymar @dima-avdeev-jb So we have not had the issues since removing the following library: https://github.com/adrielcafe/bonsai as I have mentioned. So from our side, the "issues" is "resolved".

The branch to try and replicate the issue is still available at: https://github.com/Mouwrice/proguard-core-visualizer/tree/bug/hunt-for-sigsegv If you guys want to look into it further. If not, you can close this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3411">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
