### ISSUE TITLE
 here

### ISSUE THREAD

**Issue by ThreeStepsLLC** [JetBrains/compose-multiplatform#3412]
**Describe the bug**

**Affected platforms**
Select one of the platforms below:
- All
- Desktop
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library
- iOS
- Other

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 
- Compose Multiplatform version*: 
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ThreeStepsLLC** [comment]
closed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3412">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
