### ISSUE TITLE
Wasm/JS Resources, relative path

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#3413]
We need to add the ability to use a relative path to resources in the resource library in the JS sourceset.

The problem might be with this line of code: https://github.com/JetBrains/compose-multiplatform/blob/1346feea5a52f6c2f76373f253602220a2f612b2/components/resources/library/src/jsMain/kotlin/org/jetbrains/compose/resources/Resource.js.kt#L29

Related slack discussion: https://kotlinlang.slack.com/archives/C01F2HV7868/p1689461585746039

**Comment by eymar** [comment]
The fix is expected to be available in 1.5.10-rc02

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3413">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
