### ISSUE TITLE
interactionSource.collectIsPressedAsState() does not work 

### ISSUE THREAD

**Issue by anakiK1to** [JetBrains/compose-multiplatform#3417]
**Describe the bug**
Trying to handle isPressed interaction with composable slider i encountered a problem thats its never returns true, it seems to
me, thats it's because isDragged fireing first and my click recognaized like very fast drag -> release
i'm not sure if this behavior is intended, but for it's more like a bug 

### **Affected platforms**
Tested on Desktop 

**### Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.4.3
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 23.04
- OS architecture (x86 or arm64): x86_64
- JDK Amazon corretto-17.0.7

**To Reproduce**

1. create slider with default implementation
2. init interaction source with  interactionSource = remember { MutableInteractionSource() }
3. init isPressed _with val isPressed by interactionSource.collectIsPressedAsState()_
4. init isDragged with  _val isDragged by interactionSource.collectIsDraggedAsState()_
5. create text to debug changing isPressed and isDraggeed values 
6. bind interactionSource to slider

**Expected behavior**
I expecteed isPressed to return true when tap on it's line/ point,
and expected isDragged to return true when slider's thumb is dragged  and false when dragged ends

**Comment by dima-avdeev-jb** [comment]
Can you please provide a reproducible sample project o GitHub?
Or just a block of code here in comments

**Comment by anakiK1to** [comment]
Sorry to keep you waiting for an answer,  simple version of code will look like that 
```
@Composable 
fun slider() {
 val interactionSource = remember { MutableInteractionSource() } 
 val isPressed by interactionSource.collectIsPressedAsState()
 val isDragged by interactionSource.collectIsDraggedAsState()
 val sliderValue by remeber { mutableStateOf(0f) }

Column{
  Slider(
      enabled = true,
      value = sliderValue,
      onValueChange = { newValue ->
      sliderValueRaw = newValue},
      valueRange = 0F..100f,
      interactionSource = interactionSource
   )
  Text(
      text = Text("isPressed: ${isPressed} || isDragged: ${isDragged}"
   )
 }
}
```
in this example isPressed never becomes true, but isDragged works correctly 
I'm not sure if isDragged is supposed to work on Slider, however for me it was the expected behavior

**Comment by sdzshn3** [comment]
I guess I have similar issue but slightly different use case.

I have a OutlinedTextField acting as DropDown but instead opens a ModalBottomSheet when clicked. So, I'm listening for `interactions` from `MutableInteractionSource` trying to invoke onClick when the `ineraction` is `PressInteraction.Release`. 

This code is working well with Android and iOS but not on Desktop (tested in Mac).

Use the following composable as a reproducer:
https://gist.github.com/sdzshn3/4f14132222df30151b4bec6ab84d4e79

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3417">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
