### ISSUE TITLE
White flashes when resizing window on Desktop in the beta version of 1.5.0

### ISSUE THREAD

**Issue by hichamboushaba** [JetBrains/compose-multiplatform#3420]
**Describe the bug**
When resizing the window on Desktop, if the app uses a dark theme, some white flashes appear when the dev or beta versions of 1.5.0, check the video for seeing what I mean:

| Compose 1.4.3 | Compose 1.5.0-beta01 |
| --- | --- |
| <video src="https://github.com/JetBrains/compose-multiplatform/assets/1657201/33a00709-52fb-40e0-95ef-3f6a3c75a02e"/> | <video src="https://github.com/JetBrains/compose-multiplatform/assets/1657201/3a97cced-0a39-4b6d-8b17-d2f4ef917684"/> |

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-beta01
- OS version(s)* (required for Desktop and iOS issues): Mac OS 13.3.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce**
1. Use the official desktop template: https://github.com/JetBrains/compose-multiplatform-desktop-template
2. Update Compose Multiplatform to 1.5.0-beta01
3. Apply the below patch to make the background dark

```patch
Index: src/main/kotlin/main.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/kotlin/main.kt b/src/main/kotlin/main.kt
--- a/src/main/kotlin/main.kt	(revision 5204842894b2f175fe4f8e4d8e0be79eeec9c749)
+++ b/src/main/kotlin/main.kt	(date 1690496255991)
@@ -1,12 +1,17 @@
 import androidx.compose.desktop.ui.tooling.preview.Preview
+import androidx.compose.foundation.layout.Box
+import androidx.compose.foundation.layout.fillMaxSize
 import androidx.compose.material.Button
 import androidx.compose.material.MaterialTheme
+import androidx.compose.material.Surface
 import androidx.compose.material.Text
+import androidx.compose.material.darkColors
 import androidx.compose.runtime.Composable
 import androidx.compose.runtime.getValue
 import androidx.compose.runtime.mutableStateOf
 import androidx.compose.runtime.remember
 import androidx.compose.runtime.setValue
+import androidx.compose.ui.Modifier
 import androidx.compose.ui.window.Window
 import androidx.compose.ui.window.application
 
@@ -15,11 +20,18 @@
 fun App() {
     var text by remember { mutableStateOf("Hello, World!") }
 
-    MaterialTheme {
-        Button(onClick = {
-            text = "Hello, Desktop!"
-        }) {
-            Text(text)
+    MaterialTheme(colors = darkColors()) {
+        Surface(
+            color = MaterialTheme.colors.background,
+            modifier = Modifier.fillMaxSize()
+        ) {
+            Box {
+                Button(onClick = {
+                    text = "Hello, Desktop!"
+                }) {
+                    Text(text)
+                }
+            }
         }
     }
 }
```

**Comment by dima-avdeev-jb** [comment]
Thanks, reproduced here: https://github.com/dima-avdeev-jb/1.5.0-beta-resize

**Comment by zacharee** [comment]
I've been running into this too, since I think 1.5.0-dev1104. Using software rendering instead of Metal fixes the flashing, but kills performance.

**Comment by eygraber** [comment]
This is happening in Ubuntu 22.04 using CMP 1.6.1. Should I file a separate issue?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3420">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
