### ISSUE TITLE
JS Module parse failed: Unterminated regular expression on 1.5.0-beta01

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-multiplatform#3426]
**Describe the bug**
Building my project with 1.5.0-beta01 fails with:

```
Execution failed for task ':samples:kotlin-inject:js-app:jsBrowserProductionWebpack'.
> Module parse failed: Unterminated regular expression (1609:34)
  File was processed with these loaders:
   * ../../node_modules/source-map-loader/dist/cjs.js
  You may need an additional loader to handle the result of these loaders.
  |       // Inline function 'kotlin.Long.div' call
  |       var tmp0_div = this.v7k_1;
  >       tmp = clampedPlayTime.if() / tmp0_div;
  |     }
  |     var rawFraction = tmp;
  
  Module parse failed: Unterminated regular expression (2[992](https://github.com/eygraber/portal/actions/runs/5693760276/job/15440839758?pr=433#step:7:993):23)
  File was processed with these loaders:
   * ../../node_modules/source-map-loader/dist/cjs.js
  You may need an additional loader to handle the result of these loaders.
  |       // Inline function 'kotlin.Long.div' call
  |       var tmp0_div = this.r86_1.if();
  >       tmp = time.if() / tmp0_div;
  |     } else {
  |       tmp = 1.0;
  
  Module parse failed: Unterminated regular expression (10397:35)
  File was processed with these loaders:
   * ../../node_modules/source-map-loader/dist/cjs.js
  You may need an additional loader to handle the result of these loaders.
  |         // Inline function 'kotlin.Long.div' call
  |         var tmp0_div = frameTime.b7(this$0.e8x_1);
  >         tmp$ret$0 = tmp0_div.if() / $durationScale;
  |         var tmp1_roundToLong = tmp$ret$0;
  |         tmp$ret$1 = roundToLong(tmp1_roundToLong);
```

[GitHub Actions run showing the error](https://github.com/eygraber/portal/actions/runs/5693760276/job/15440839758?pr=433)
[Branch this happens on](https://github.com/eygraber/portal/tree/renovate/composejetbrains)

**Affected platforms**
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-beta01

**Comment by eymar** [comment]
The second link with a branch is "404 - page not found". 
Did this happen with previous compose/kotlin versions?
On a first glance, it doesn't seem to be compose related (at least from looking at the code lines in the output)

**Comment by eygraber** [comment]
This didn't happen with previous versions of compose/Kotlin. I think it was introduced by https://github.com/eygraber/portal/pull/428 but I need to bisect to double check. 

I merged that PR so it can be reproed on the [master branch](https://github.com/eygraber/portal).

**Comment by eymar** [comment]
For example, modifying the app code forces kotlin to change the names:

```koltin
@OptIn(ExperimentalComposeUiApi::class)
fun main() {
  val mainPortal = appComponent.mainPortal

  onWasmReady {
    CanvasBasedWindow("KotlinInject") {
      mainPortal.Render()

      // added this:
      LazyVerticalStaggeredGrid(
        columns = StaggeredGridCells.Fixed(2)
      ) {

      }
    }
  }
}
```

and now, the name of that function is `jf()` :) 

```js
  protoOf(Long).jf = function () {
    return this.q8();
  };
  ....
  
tmp = clampedPlayTime.jf() / tmp0_div;
```

**Comment by eygraber** [comment]
Filed https://youtrack.jetbrains.com/issue/KT-60982/Kotlin-JS-Unterminated-regular-expression-when-webpack-encounters-if

**Comment by ilgonmic** [comment]
JFI
https://github.com/acornjs/acorn/issues/1232

**Comment by ilgonmic** [comment]
I think it is likely fixed with issue https://github.com/acornjs/acorn/issues/1232

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3426">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
