### ISSUE TITLE
Package Management Platform for Multiplatform Compose

### ISSUE THREAD

**Issue by Atlands** [JetBrains/compose-multiplatform#3429]
Is there a package management platform for "multiplatform composite"?
Similar to Flutter's' pub. dev '.
It can showcase the target platforms supported by the package, helping developers retrieve and discover the required dependencies.

**Comment by dima-avdeev-jb** [comment]
Hello! In Kotlin ecosystem uses Maven as a package platform. For searching packages on Maven, we have something similar here:
https://package-search.jetbrains.com/
Also, it is available right on IntelliJ IDEA https://www.jetbrains.com/help/idea/package-search.html

**Comment by dima-avdeev-jb** [comment]
Is this what you expect?

**Comment by dima-avdeev-jb** [comment]
Or maybe you need something like a Compose only gallery with libraries and UI samples ?

**Comment by Atlands** [comment]
> 你好！在 Kotlin 生态系统中使用 Maven 作为包平台。为了在Maven上搜索软件包，我们这里有类似的东西： https://package-search.jetbrains.com/ 此外，它可以直接在IntelliJ [IDEA上获得 https://www.jetbrains.com/help/idea/package-search.html](https://www.jetbrains.com/help/idea/package-search.html)
> 
> 这是你所期望的吗？



Thank you, this is exactly what I need.
For this website, I need to make a few suggestions:
1. In the search results, the different target platforms of the same Package are merged into one, showing the platform label in detail, just like Flutter
2. In details, put "Github Stars" in an obvious place, not in the middle of a text
3. In the details, Readme loaded unsuccessful
4. On the homepage, open up "Compose Multiplatform" to collect a batch of excellent Packages
5. In "Compose Multiplatform Readme", recommend this official website to everyone

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3429">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
