### ISSUE TITLE
Please don't spam 
With love ❤️  made with Ruby

### ISSUE THREAD

**Issue by RubyRusul** [JetBrains/compose-multiplatform#3430]
Please don't spam

_Originally posted in https://github.com/tensorflow/tensorflow/issues/61291#issuecomment-1637198403_
By ❤️with ruby

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3430">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
