### ISSUE TITLE
Preview Tool for sourceSets -> commonMain

### ISSUE THREAD

**Issue by devjorgecastro** [JetBrains/compose-multiplatform#3431]
Hello everyone, would it be possible to enable the Preview tool for @Composable in shared -> commonMain?

One of the things that interests me the most about the latest versions of Android Studio are the improvements in the rendering of the Preview, but I have not been able to make it work when I want to work with Compose Cross Platform with shared UI, is there documentation for this? is this currently being worked on?

**Comment by dima-avdeev-jb** [comment]
Hello! 
Please follow this issue: 
 - https://github.com/JetBrains/compose-multiplatform/issues/2045

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3431">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
