### ISSUE TITLE
Google map view in KMP compose

### ISSUE THREAD

**Issue by ismai117** [JetBrains/compose-multiplatform#3432]
How do I add an iOS specific feature like a map inside a compose screen? I've read some information that suggests using a UIKIT view inside a composable, but I don't know how to implement it. any help, please. thanks

**Comment by ismai117** [comment]
I figured it out but now my issue  is "uncaught exception 'GMSServicesException', reason: 'Google Maps SDK for iOS must be initialized via [GMSServices provideAPIKey:...] prior to use'"

**Comment by dima-avdeev-jb** [comment]
Hello, please take a lookt at our sample:
https://github.com/JetBrains/compose-multiplatform/tree/master/examples/imageviewer

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3432">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
