### ISSUE TITLE
Multiple characters per one keystroke added after browser window is resized.

### ISSUE THREAD

**Issue by rjuszczyk** [JetBrains/compose-multiplatform#3433]
**Describe the bug**
TextField acting weird. Multiple characters per one keystroke added after browser window is resized.

**Affected platforms** 
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API

**Versions**
compose.version=1.4.0
compose.wasm.version=1.4.0-dev-wasm09
kotlin.version=1.9.0

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. clone this repo https://github.com/rjuszczyk/MultipleKeystrokesAfterWindowResized
2. run ./gradlew :webApp:wasmRun 
3. resize window and type something

**Expected behavior**
One character per keystroke

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/99798741/ee770e51-70b7-4146-ab95-da757f9dca92

**Additional context**
Thread on slack (#compose-web):
https://kotlinlang.slack.com/archives/C01F2HV7868/p1690701185238059

**Comment by eymar** [comment]
It's fixed starting with 1.6.0-alpha01.  There is 1.6.0-rc01 already.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3433">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
