### ISSUE TITLE
How to get screen size for mobile multiplatform?

### ISSUE THREAD

**Issue by LionisIAm** [JetBrains/compose-multiplatform#3435]
In android I used to have 
`val configuration = LocalConfiguration.current`
but seems like it's not available here.
Any ways I can obtain screen size for android+ios app?
P.S. How to be invited to slack workspace?

**Comment by QiXi** [comment]
`BoxWithConstraints` it might be useful for this task

**Comment by dima-avdeev-jb** [comment]
@LionisIAm Slack invintation: http://slack.kotlinlang.org/

**Comment by dima-avdeev-jb** [comment]
@QiXi have a good solution to use BoxWithConstraints
Also, you can optain screen size on each platform with a platform way. Not in commonMain, but in iosMain. 
`val screenSize = UIScreen.mainScreen.bounds.useContents { size.width to size.height }`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3435">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
