### ISSUE TITLE
How to display the common Dialog when the app window has been minimized?

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#3438]
On Desktop, how can I show the `Dialog` on the screen when the application window has been minimized?

Currently, if the window has been minimized, the dialog does not appear on the screen and is only shown when the app window is restored.
On the other hand, the `DialogWindow` is always displayed on the screen no matter if the app window is minimized or not.

I don't think this is a bug because the current behavior may be desirable sometimes.
But is there a way to change it so the `Dialog` appears on screen even if the app window is minimized?

I'm using compose multiplatform 1.5.0-beta01.

**Comment by MatkovIvan** [comment]
Common `Dialog` is placed inside the window, so you need to restore minimized window or use `DialogWindow`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3438">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
