### ISSUE TITLE
Dialog scrim (aka background shadow or backdrop) does not take into account window rounded corners

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#3439]
**Describe the bug**
If I have an undecorated and transparent window with rounded corners, and showing the common `Dialog` component,
the dialog scrim (dark surface behind dialog) is not clipped for window rounded corners:

![Window with an exaggerated rounded corners](https://github.com/JetBrains/compose-multiplatform/assets/29678011/31aa858b-ebf2-4527-b184-bf57ca009d6a)

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-beta01
- OS version(s)*: Windows 10 and 11
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 17

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3439">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
