### ISSUE TITLE
org.gradle.api.plugins.UnknownPluginException

### ISSUE THREAD

**Issue by MrThiago** [JetBrains/compose-multiplatform#3440]
**Describe the bug**
Project compose-multiplatform-template-main, can not build.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.jetbrains.kotlin.multiplatform', version: '1.9.0', apply: false] was not found in any of the following sources:

Android Studio Hedgehog | 2023.1.1 Canary 14
Build #AI-231.9225.16.2311.10533651, built on July 20, 2023
Runtime version: 17.0.7+0-17.0.7b829.16-10353782 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 10
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.jetbrains.kmm (0.6.1(231)-9)

**Comment by dima-avdeev-jb** [comment]
@MrThiago Are you trying to run iOS application ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3440">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
