### ISSUE TITLE
Cross-platform text rendering stability

### ISSUE THREAD

**Issue by dzirbel** [JetBrains/compose-multiplatform#3442]
**Describe the bug**
Text rendering appears to be subtly different across desktop operating systems, even when providing the same font.

This may be an intentional or unavoidable result of using platform text rendering APIs. I wanted to confirm whether that is the case, or if it may be either (a) some aspect of platform dependency inadvertently relied on by my application or (b) a solvable issue in Compose Multiplatform.

**Affected platforms**
Desktop (and likely others)

**Versions**
- Kotlin version: 1.9.0
- Compose Multiplatform version: 1.4.3
- OS version(s): Windows Server 2022, Ubuntu 22.04 (via Github Actions `windows-latest` and `ubuntu-latest`, respectively)
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 18

**To Reproduce**
I don't have a minimal reproducing example. [This run](https://github.com/dzirbel/kotify/actions/runs/5720383485) of my CI job shows the failures (with `ubuntu-latest` passing and `windows-latest` failing; for example the reference image below is [here](https://github.com/dzirbel/kotify/blob/423302a3565cb22cf44ac40563a004bacbe57583/ui-common/src/test/resources/screenshots/com.dzirbel.kotify.ui.components.FlowTest/multiple-rows-simple.png) and the version generated on a windows machine can be downloaded from the `mismatching-screenshots` archive. Screenshot tests can be run on this project via `./gradlew testLocal` and the results can be compared across platforms (current [head](https://github.com/dzirbel/kotify/tree/423302a3565cb22cf44ac40563a004bacbe57583), with screenshots from Linux). Notably, I am using a resource-loaded font ([here](https://github.com/dzirbel/kotify/blob/423302a3565cb22cf44ac40563a004bacbe57583/ui-common/src/main/kotlin/com/dzirbel/kotify/ui/theme/Colors.kt#L149) and [here](https://github.com/dzirbel/kotify/blob/master/ui-common/src/main/kotlin/com/dzirbel/kotify/ui/theme/KotifyTypography.kt#L9)) rather than relying on the OS-specific default font family.

**Expected behavior**
Composable content should appear identical across desktop operating systems.

**Screenshots**
Ubuntu 22.04:
![multiple-rows-simple](https://github.com/JetBrains/compose-multiplatform/assets/1222738/8f4f03c7-bf30-4345-a4d7-845b0a0ec30b)

Windows:
![multiple-rows-simple-MISMATCH](https://github.com/JetBrains/compose-multiplatform/assets/1222738/7604e1e5-da8e-4e87-8790-2b6343771a0f)

These look very similar, but on close examination there are slight differences in anti-aliasing/kerning/etc.

**Additional context**
I am attempting to run my application's screenshot tests across different operating systems as part of the CI flow. These tests capture Composable content and compare them to past runs, requiring a pixel-perfect match. This isn't a necessity for me, just a nice-to-have. Given that (I believe) Compose uses Skia for platform-independent rendering of most (all?) content, it would appear to be possible to have these screenshots be identical across different operating systems, which is a nice and robust verification of my application's appearance.

**Comment by kirill-grouchnikov** [comment]
Skia is indeed the rendering engine, but it still delegates to native APIs for the final shaping of the glyphs. CoreText on macOS and ClearType on Windows do not have any guarantee that the same font at the same size and configuration is rendered identically down to the very last antialised pixel.

**Comment by dzirbel** [comment]
Makes sense, thanks! My last question then is whether there's any way to prevent that delegation or substitute it with a common implementation to make screenshots pixel-perfect across platforms? Any other ideas you might have for this situation would be appreciated :)

**Comment by kirill-grouchnikov** [comment]
I would say that the goal should be to have the text rendering consistent with the platform and its native apps. When Safari launched on windows it was pretty terrible. There was absolutely no user benefit to have a Mac styled text rendering on Windows. It was universally rejected, and rightfully so. 

If you’re looking for reproducible screenshots for testing, you can have it on one platform + one OS version + one Skia version. Anything else is a distraction.

**Comment by dzirbel** [comment]
That's fair, and I certainly don't need a fix anytime soon, but I'll just point out one salient downside: it's very difficult to have developers work on the same app across platforms if the screenshot tests will disagree. Even for my (solo) project, not being able to switch platforms or hand it off to a friend/contributor without regenerating all the screenshots is a pain. I think you're right about the end-user experience, but maybe making an exception for a developer-mode shared across platforms would be reasonable in the longer term. (Of course, VMs are also a decent workaround.)

**Comment by kirill-grouchnikov** [comment]
Even beyond text, Skia ends up using different backends on different platforms, be it OpenGL, Vulkan, Metal, etc. Having 100% match for every single pixel in your app across those is not feasibly attainable.

**Comment by dima-avdeev-jb** [comment]
Hello! Thanks for problem description. Unfortunatelly we can't fix it right now.

If you want to use screenshot testing and compare it on different operating system, then you can do the following:
 - Split screenshot between host OS. For example name files like screen1-mac.png, screen1-win.png
 - Replace text values with special characters, like ■ (square).
 - Make algorithm to compare screenshots with inaccuracy.
 
It is helpfull information for you?

**Comment by dzirbel** [comment]
Thanks! Those are all solid workarounds that I'll play around with, especially to allow fuzziness in the screenshot verification (I've used a Python script with [Pillow](https://pillow.readthedocs.io/en/stable/) for this in the past). None are quite perfect, so if there is a possibility to ever add a stable, platform-independent rendering mode (even at the cost of performance or e.g. antialiasing), I think there could be a use for it. But I understand it's probably impractical and I appreciate the discussion; feel free to close the issue if it's not something that will be on the roadmap :)

**Comment by dima-avdeev-jb** [comment]
Also, you can use special font with all symbols as a ■ (square)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3442">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
