### ISSUE TITLE
Add dependency to compose KMP plugin

### ISSUE THREAD

**Issue by dzmpr** [JetBrains/compose-multiplatform#3448]
Please add `runtimeSaveable` to available dependencies in plugin. 
To add this dependency now I should use version catalog.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3448">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
