### ISSUE TITLE
Merge Jetpack compose 1.5.0-rc01 please

### ISSUE THREAD

**Issue by wtfisthatzzz** [JetBrains/compose-multiplatform#3450]
[A clear and concise description of what the bug is.](https://issuetracker.google.com/issues/294137068)
Jetpack Compose 1.5.0-beta03’s new Text modifier is prone to crashing easily. Jetpack Compose 1.5.0-rc01 has fixed this issue, please merge it as soon as possible

**Affected platforms**
All

**Versions**
- Kotlin version*: 
- 1.9.0
- Compose Multiplatform version*: 
- 1.5.0-beta01

**Comment by igordmn** [comment]
Fixed in CM 1.5.0-beta02, it has JC 1.5.0

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3450">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
