### ISSUE TITLE
rememberSnapFlingBehavior does not snap on desktop when using a scroll wheel

### ISSUE THREAD

**Issue by aljohnston112** [JetBrains/compose-multiplatform#3454]
**Describe the bug**
rememberSnapFlingBehavior does not snap items to the center of the LazyColumn when scrolling via scroll wheel on desktop.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.4.3
- OS version(s)* (required for Desktop and iOS issues): Linux 6.4.6-100.fc37.x86_64
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): corretto-18.0.2

**To Reproduce**
Wrap this in a composable function
```kt
    val itemHeight = 48.dp
    val itemHeightModifier = modifier.height(itemHeight)
    LazyColumn(
        state = lazyListState,
        flingBehavior = rememberSnapFlingBehavior(lazyListState = lazyListState),
        modifier=itemHeightModifier.fillMaxWidth()
    ){
        items(
            5,
            key = { it }
        ){
            Text(it.toString(), modifier=itemHeightModifier)
        }
    }
```
    
**Expected behavior**
When scrolling through the LazyColumn and then stopping the scrolling, I expect the flingBehavior to snap the closest item to the center of the LazyColumn. 

I can test this on Windows 10 later.

**Comment by eymar** [comment]
reproduced on Ubuntu (I guess the behaviour is OS independent).

it's likely related: https://github.com/JetBrains/compose-multiplatform/issues/3447


Here is a screen recording. Desktop is on the left (scrolling using a mouse wheel), and android is on the right (using touch gestures: dragging). 

[simplescreenrecorder-2023-08-04_10.29.15.webm](https://github.com/JetBrains/compose-multiplatform/assets/7372778/dc6ab8e7-b5e3-4aa2-b415-4458154623fa)

**Comment by garretyoder** [comment]
In the other referenced similar issue #3447 I posted a [workaround](https://github.com/JetBrains/compose-multiplatform/issues/3447#issuecomment-1747128076) that works with a pager, it can probably be adapted for your use case as well.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3454">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
