### ISSUE TITLE
isScrollInProgress returns false when scrolling on desktop

### ISSUE THREAD

**Issue by aljohnston112** [JetBrains/compose-multiplatform#3455]
**Describe the bug**
When scrolling on desktop, LazyListState.isScrollInProgress returns false.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.4.3
- OS version(s)* (required for Desktop and iOS issues): Linux 6.4.6-100.fc37.x86_64
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): corretto-18.0.2

**To Reproduce**
Try to scroll this and see the output print "Scroll not in progress" over and over.
```kt
    val itemHeight = 48.dp
    val itemHeightModifier = modifier.height(itemHeight)
    LazyColumn(
        state = lazyListState,
        flingBehavior = rememberSnapFlingBehavior(lazyListState = lazyListState),
        modifier=itemHeightModifier.fillMaxWidth()
    ){
        items(
            5,
            key = { it }
        ){
            Text(it.toString(), modifier=itemHeightModifier)
        }
    }
    
        LaunchedEffect(lazyListState){
        snapshotFlow {
            lazyListState.isScrollInProgress
        }.collect{
            if (!it) {
                println("Scroll not in progress")
                val pos = if (
                    lazyListState.firstVisibleItemScrollOffset <= 24
                ) {
                    lazyListState.firstVisibleItemIndex
                } else{
                    min(cardsAllowed + 1, lazyListState.firstVisibleItemIndex + 1)
                }
                coroutineScope.launch {
                    lazyListState.animateScrollToItem(pos)
                }
            }
        }
    }
    ```

**Expected behavior**
That isScrollInProgress returns true when scrolling.

**Comment by aljohnston112** [comment]
My bad. I thought I searched, but this issue already exists.

**Comment by MatkovIvan** [comment]
Yep. See my explanation there - https://github.com/JetBrains/compose-multiplatform/issues/1423#issuecomment-1477679723

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3455">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
