### ISSUE TITLE
Use `CupertinoOverscrollEffect` for macOS desktop/native

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#3457]
It is native effect for macOS too.

Or make it available in skikoMain/commonMain source set and add an ability to provide it to lazy lists / scroll modifiers (so developers can choose if they want this effect or can create a custom one)

**Comment by alexzhirkevich** [comment]
Actually, this is native effect for a trackpad. I just realized that i never used macOS with a mouse 😂. And i don't have one to test. So probably it's not for a mouse

**Comment by elijah-semyonov** [comment]
You can also trigger it pressing "Up" key, not sure about mouse either

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3457">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
