### ISSUE TITLE
ColorMatrix value range for 5th column is incorrect on Skiko backed platforms

### ISSUE THREAD

**Issue by chrisbanes** [JetBrains/compose-multiplatform#3461]
**Describe the bug**

On Android, the matrix is passed to Android's own `ColorMatrix` class. That treats the final column in the range of `-255..255`. On Skiko backed platforms though, it is passed directly to Skia, and that treats the final column in the range of `-1f..1f`.

The docs on `androidx.compose.ui.graphics.ColorMatrix` in CMP list out the range `-255..255`, so it sounds like there's need to be a mapping before the matrix is set to Skiko?

Example:

``` kotlin
val cm = ColorMatrix().apply {
    this[0, 4] = 64f
    this[1, 4] = 64f
    this[2, 4] = 64f
}

Image(
    ...,
    colorFilter = ColorFilter.colorMatrix(colorMatrix),
)
```

On Android, the image will look brighter. On iOS, the image will be completely white.

**Affected platforms**
Select one of the platforms below:
- Skiko backed platforms

**Comment by elijah-semyonov** [comment]
[Will be fixed in this PR](https://github.com/JetBrains/compose-multiplatform-core/pull/739).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3461">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
