### ISSUE TITLE
Allow custom view controllers by delegating the compose logic inside ComposeWindow to another non-internal class

### ISSUE THREAD

**Issue by shibasis0801** [JetBrains/compose-multiplatform#3462]
Currently Compose on iOS works through the ComposeWindow which inherits UIViewController. 
It is internal in the compose package so we can't access it for subclassing. 
Even if we could access it, we can't subclass an existing subclass of an objective c class. 

This prevents us from writing our own view controllers, where I wish to use compose in parts of the UI and native views in other parts. I also need to trigger functions in my code based on lifecycle events which I can't right now. 

I was proposing if we can separate the logic from the ComposeWindow into a ComposeAdapter if you may, and then call its functions from ComposeWindow.
ComposeWindow's functionality would remain as is, and this will also allow custom view controllers to function as long as they call all adapter methods properly. 

I can also work on writing this and wanted your opinion whether this is a good idea. 
This is my first enhancement request so please let me know if I missed anything.

**Comment by dima-avdeev-jb** [comment]
Hello!
Compose starts from functions 
```Kotlin
val myComposeViewController: UIViewController = ComposeUIViewController {
    // Your Compose content
}
```
We don't want to provide a way to inherit ComposeUIViewController.

But, you already can use ComposeUIViewController as a part of the screen and combine with other UIViewController's
For example take a look at our example: https://github.com/JetBrains/compose-multiplatform/tree/master/examples/chat

For now, it is better to use Compose with SwiftUI hierarchy. Current limitations is to use one Compose view with fixed size. In the future this limitations will be fixed.

@shibasis0801 
Is it helpfull information for you?

**Comment by shibasis0801** [comment]
Yes we can combine view controllers but I was thinking if we could also have more granular control. 

Thank you for the response.

**Comment by elijah-semyonov** [comment]
@shibasis0801 
Can you share which functions you want to override? If it's a common use case, we could consider adding providing those as hooks on ComposeWindow API level.

**Comment by alexzhirkevich** [comment]
I also had a need to use some lifecycle methods of the compose VC. I wrote a wrapper for it, works pretty well:
```kotlin
private class UIViewControllerWrapper(
    private val controller: UIViewController, // compose view controller
    private val onDisappear : () -> Unit,
) : UIViewController(null,null){

    override fun loadView() {
        super.loadView()
        controller.willMoveToParentViewController(this)
        controller.view.setFrame(view.frame)
        view.addSubview(controller.view)
        addChildViewController(controller)
        controller.didMoveToParentViewController(this)
    }

    override fun viewDidDisappear(animated: Boolean) {
        super.viewDidDisappear(animated)
        onDisappear()
    }
}
```

**Comment by shibasis0801** [comment]
I'm also doing something similar to @alexzhirkevich 
I'm not overriding any functions yet
I was trying to write lifecycle aware components for iOS
We can still achieve them by doing container controllers
But I just felt that there could be an alternate

`@OptIn(ExperimentalStdlibApi::class)
interface DarwinLifecycleObserver: AutoCloseable, KoinComponent {
    fun viewDidLoad() // similar to onCreate
    fun viewWillAppear(animated: Boolean) // ~onStart
    fun viewDidAppear(animated: Boolean) // ~onResume
    fun viewWillDisappear(animated: Boolean) // ~onPause
    fun viewDidDisappear(animated: Boolean) // ~onStop
    override fun close() // ~onDestroy if needed
}`

**Comment by pablichjenkov** [comment]
Is the configuration available for the public. It seems marked as internal
```kotlin
internal lateinit var configuration: ComposeUIViewControllerConfiguration
```
I tried to access from the outside but no luck.

**Comment by MatkovIvan** [comment]
@pablichjenkov it's available as a constructor parameter, but you cannot change it after instantiation.

**Comment by elijah-semyonov** [comment]
```
fun ComposeUIViewController(
    configure: ComposeUIViewControllerConfiguration.() -> Unit = {},
    content: @Composable () -> Unit
): UIViewController = ComposeContainer(
    configuration = ComposeUIViewControllerConfiguration().apply(configure),
    content = content,
)
```

You can configure it in `configure` lambda in entry point for Compose.

**Comment by pablichjenkov** [comment]
Thank you so much

**Comment by pablichjenkov** [comment]
Humm, weird. For some reason I am only getting the first events: `viewWillAppear`, `viewDidAppear`. Nothing after. I don't think I am doing anything fancy.
```
class MacaoComposeUIViewControllerDelegate(
    val platformLifecyclePlugin: PlatformLifecyclePlugin
) : ComposeUIViewControllerDelegate {

    override fun viewWillAppear(animated: Boolean) {
        println("::_viewWillAppear")
    }

    override fun viewDidAppear(animated: Boolean) {
        println("::_viewDidAppear")
        platformLifecyclePlugin.dispatchAppLifecycleEvent(AppLifecycleEvent.Start)
    }

    override fun viewWillDisappear(animated: Boolean) {
        println("::_viewDidAppear")
    }

    override fun viewDidDisappear(animated: Boolean) {
        println("::_viewDidDisappear")
        platformLifecyclePlugin.dispatchAppLifecycleEvent(AppLifecycleEvent.Stop)
    }
}

fun buildDemoViewController(
    iosBridge: IosBridge,
    onBackPress: () -> Unit = {}
): UIViewController {

    return ComposeUIViewController(
        configure = {
            delegate = MacaoComposeUIViewControllerDelegate(iosBridge.platformLifecyclePlugin)
        }
    ) {

        val applicationState = MacaoKoinApplicationState(
            dispatcher = Dispatchers.IO,
            rootComponentKoinProvider = IosRootComponentKoinProvider(),
            koinModuleInitializer = DemoKoinModuleInitializer()
        )

        MacaoKoinApplication(
            iosBridge = iosBridge,
            onBackPress = onBackPress,
            applicationState = applicationState
        )
    }

}
```

Do you spot anything in above code?

**Comment by akhbulatov** [comment]
> @pablichjenkov
> 
> ```
> fun ComposeUIViewController(
>     configure: ComposeUIViewControllerConfiguration.() -> Unit = {},
>     content: @Composable () -> Unit
> ): UIViewController = ComposeContainer(
>     configuration = ComposeUIViewControllerConfiguration().apply(configure),
>     content = content,
> )
> ```
> 
> You can configure it in `configure` lambda in entry point for Compose.

This works with lifecycle functions, but what if I need to override another functions of `UIViewController`, for example, `motionEnded`?

**Comment by elijah-semyonov** [comment]
You can still use the workaround and make a wrapper UIViewController that nests the ComposeUIViewController inside.

**Comment by TheReprator** [comment]
@elijah-semyonov @akhbulatov @pablichjenkov can you please assist me with this question,  https://stackoverflow.com/questions/78446858/how-to-detect-lifecycle-of-ios-app-in-compose-multiplatform.  

Actually issue is "The methods viewDidLoad, viewWillAppear, and viewDidAppear are invoked once during the lifecycle of ViewController. However, the methods viewDidDisappear, viewWillDisappear are not being called as expected."

Repo: https://github.com/TheReprator/ExpenseManagment
Branch:  error/lifecycle

File Name: AccountBookUiViewController

**Comment by TheReprator** [comment]
> Humm, weird. For some reason I am only getting the first events: `viewWillAppear`, `viewDidAppear`. Nothing after. I don't think I am doing anything fancy.
> 
> ```
> class MacaoComposeUIViewControllerDelegate(
>     val platformLifecyclePlugin: PlatformLifecyclePlugin
> ) : ComposeUIViewControllerDelegate {
> 
>     override fun viewWillAppear(animated: Boolean) {
>         println("::_viewWillAppear")
>     }
> 
>     override fun viewDidAppear(animated: Boolean) {
>         println("::_viewDidAppear")
>         platformLifecyclePlugin.dispatchAppLifecycleEvent(AppLifecycleEvent.Start)
>     }
> 
>     override fun viewWillDisappear(animated: Boolean) {
>         println("::_viewDidAppear")
>     }
> 
>     override fun viewDidDisappear(animated: Boolean) {
>         println("::_viewDidDisappear")
>         platformLifecyclePlugin.dispatchAppLifecycleEvent(AppLifecycleEvent.Stop)
>     }
> }
> 
> fun buildDemoViewController(
>     iosBridge: IosBridge,
>     onBackPress: () -> Unit = {}
> ): UIViewController {
> 
>     return ComposeUIViewController(
>         configure = {
>             delegate = MacaoComposeUIViewControllerDelegate(iosBridge.platformLifecyclePlugin)
>         }
>     ) {
> 
>         val applicationState = MacaoKoinApplicationState(
>             dispatcher = Dispatchers.IO,
>             rootComponentKoinProvider = IosRootComponentKoinProvider(),
>             koinModuleInitializer = DemoKoinModuleInitializer()
>         )
> 
>         MacaoKoinApplication(
>             iosBridge = iosBridge,
>             onBackPress = onBackPress,
>             applicationState = applicationState
>         )
>     }
> 
> }
> ```
> 
> Do you spot anything in above code?
> 
> **kotlin.version=1.9.21** **compose.version=1.5.11**
> 
> Is maybe the swift-ui to view-controller event propagation that is not working as I expect 🤔
> 
> **Update**: After some research the **onAppear**/**onDissapear** events from swiftui have to be passed down to the UiViewController using a Coordinator class or an interface injected in the **UiViewController**. Another alternative was getting the from the **scenePhase**. In either case I had to create interfaces to pass down the event to the UiViewController instance returned in **UiViewControllerRepresentable**. That really makes no difference than passing the same interface to the root composable. IMO this API is handy for a pure UiViewController App but doesn't gain much benefit in a **SwiftUi** App. I actually ended up doing what they do in Appyx, get App lifecycle notification events from **NSNotificationCenter**.

Any work around for this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3462">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
