### ISSUE TITLE
TextField issues with Korean input.

### ISSUE THREAD

**Issue by kjsreleased** [JetBrains/compose-multiplatform#3464]
**Describe the bug**
While typing text in Korean, the last character duplicates itself when I press the spacebar, enter or some other function keys.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*:  1.9.0
- Compose Multiplatform version*:  id("org.jetbrains.compose") / jvmToolchain(11)
- OS version(s)* (required for Desktop and iOS issues):  Windows 10
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues):  jbr17 - 17.0.7

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
Just put a normal TextField in a window and start typing in it in Korean (maybe other Asian languages too?).

**Expected behavior**
Just normal and straight behavior.

**Screenshots**
1.
![textfield](https://github.com/JetBrains/compose-multiplatform/assets/141545043/adcb3cad-5c25-4d59-a9e0-0123bd929b74)

2.
![textfield2](https://github.com/JetBrains/compose-multiplatform/assets/141545043/43af63d1-1b98-4ce5-b7c1-c92d001b8853)

**Additional context**

**Comment by eymar** [comment]
What compose version did you use?

I tried to reproduce with compose 1.5.0-beta01, kotlin 1.9.0, windows 11, jbr17 - 17.0.7. The characters didn't duplicate after I pressed a space bar. Do I need to type some particular character before pressing a space bar?

cc @igordmn Igor, could you please also have a look? I'm not sure I know how to properly test korean text input manually.

**Comment by kjsreleased** [comment]
Thank you for your reply.
How do I check the version? I've been just creating a project via intellij menu "compose multiplatform - > single platform".
The gradle plugins are are all defaults. 
And It's not about particular characters. 
I tried in Japanese as well, but it seems there's no problem with Japanese.

![issue](https://github.com/JetBrains/compose-multiplatform/assets/141545043/a6e3dfde-303e-4929-ac9c-b534c19fb78b)

**Comment by kjsreleased** [comment]
Okay. It was the version! 
Mine was far too low, which was 1.3.0 (Why is it so low by default?) 
When I tried with the recent version, the problem was gone.
Thank you!

**Comment by eymar** [comment]
Great! Indeed the older version had a bug which was fixed.

> Mine was far too low, which was 1.3.0 (Why is it so low by default?)
the template depends on the IDEA version. If you update your IDEA, you would have 1.4.1 version by default.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3464">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
