### ISSUE TITLE
AGP Upgrade Assistant not working

### ISSUE THREAD

**Issue by SerggioC** [JetBrains/compose-multiplatform#3465]
I get the error when I try to use AGP Upgrade Assistant: 
```
This step is blocked
Cannot find AGP version in build files. Cannot locate the version specification for the Android Gradle Plugin dependency, possibly because the project's build files use features not currently supported by the Upgrade Assistant (for example: using constants defined in buildSrc). 
```

Android Studio Giraffe | 2022.3.1
Build #AI-223.8836.35.2231.10406996, built on June 29, 2023
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.8.0)
    org.moe (1.5.2)
    com.jetbrains.kmm (0.6.1(223)-18)
    com.squareup.sqldelight (2.0.0)
    org.jetbrains.compose.desktop.ide (1.4.3)

**Comment by eymar** [comment]
> possibly because the project's build files use features not currently supported by the Upgrade Assistant (for example: using constants defined in buildSrc). 


https://developer.android.com/build/agp-upgrade-assistant 

> Important: The AGP Upgrade Assistant does not yet support projects that use [Gradle Version Catalogs](https://docs.gradle.org/current/userguide/platforms.html) or buildSrc to define constants and variables used in build files. For better build performance, avoid storing variables in buildSrc, such as dependency versions.

Perhpas your project uses some features not supported by the Upgrade Assistant.

With the provided information, I can't see how AGP Upgrade Assistant update issue relates to Compose Multiplatform.

Please reopen this issue if you have more information about Compose affecting AGP Upgrade Assistant.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3465">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
