### ISSUE TITLE
Allow full handling of arrow keys in TextField in Compose Desktop

### ISSUE THREAD

**Issue by Raphael-N** [JetBrains/compose-multiplatform#3470]
Currently, arrow key (keydown) events are caught and not forwarded by the TextFieldKeyInput's process method. 
This makes sense as a default but as a developer, it would be great to have the option to react to these keys, just as I can react to other key events.
Ideally I would also like to be able to catch these events and not have them forwarded to the TextField itself.

An example use case of this is a TextField with a dropdown attached that opens and closes on arrow down and up keys.

**Comment by elijah-semyonov** [comment]
Did you try using `Modifier.onPreviewKeyEvent` on outer node?

**Comment by Raphael-N** [comment]
Brilliant, that is exactly what I needed!
Sorry for not properly checking the available options before.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3470">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
