### ISSUE TITLE
Add support for nonactivating panel on MacOS

### ISSUE THREAD

**Issue by Raphael-N** [JetBrains/compose-multiplatform#3471]
**Context**
What I am trying to achieve is to have a window that I can bring to the foreground with a hotkey, similar to Spotlight/Raycase/Alfred on Macos or the Power Toys Run on windows. This window should be the input focus and I can enter something and press enter to close it. For the most part this works but there are some limitations that make the exact behaviour hard to achieve.

**Current Behaviour**
Specifically, on MacOS, I cannot make the panel visible, bring it to the front and set it focused without activating the application. This means if there are any other windows, they are also activated. The reason for this is that I have to use the Java awt function `Desktop.getDesktop().requestForeground(false)` to get the window to receive input focus. On windows, changing the `visible` parameter of window  (something like this `Window(
        visible = viewModel.trackerOpen,
        onCloseRequest = exit,
        undecorated = true,
        resizable = false,
        alwaysOnTop = true,
        state = trackerWindowState,
        transparent = true
    )`) is enough to open it and receive focus.

**Desired Behaviour**
There is a way for my window to receive focus without having to activate the entire application.

**Additional Info**
It looked like this actually works on windows but is an issue on MacOS.

**Comment by elijah-semyonov** [comment]
Thanks for the proposal, we'll discuss it internally and come back with a specific plan.

**Comment by igordmn** [comment]
Did I understand the case correctly:

1. The application has multiple opened windows, but they are all in foreground (behind another applications, for example)
2. Should be a way to bring (or create) only one window to foreground without bringing the other windows.

And did understand correctly, that there is a workround, using AWT directly (`esktop.getDesktop().requestForeground(false)`)?

**Comment by igordmn** [comment]
> also brings the app into focus which means, when the relevant window is closed, the app is still in focus and the next app window pops to front.

This looks like [another bug](https://github.com/JetBrains/compose-multiplatform/issues/2994).

As a workaround, you can try to create the window [this way](https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Window_API_new#swing-interoperability)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3471">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
