### ISSUE TITLE
[desktop] SwingPanel not work with Snackbar

### ISSUE THREAD

**Issue by xinkunZ** [JetBrains/compose-multiplatform#3474]
1. Snackbar works with Text
```
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                Box(modifier = Modifier.matchParentSize()) {
                    Text("aaaa")
                    Snackbar(
                        action = { Button(onClick = {}) {} },
                        modifier = Modifier.padding(8.dp).align(Alignment.BottomCenter)
                    ) { Text(text = "This is a snackbar!") }
                }
            }
```
![image](https://github.com/JetBrains/compose-multiplatform/assets/7759897/142b276f-fc01-4c9a-b505-f5502848f88e)

2. not work with Swing JPanel
```
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                Box(modifier = Modifier.matchParentSize()) {
                    SwingPanel(factory = {
                        JPanel().apply {
                            background = java.awt.Color.red
                        }
                    })
                    Snackbar(
                        action = { Button(onClick = {}) {} },
                        modifier = Modifier.padding(8.dp).align(Alignment.BottomCenter)
                    ) { Text(text = "This is a snackbar!") }
                }
            }
```

![image](https://github.com/JetBrains/compose-multiplatform/assets/7759897/8bd13a3b-0752-43e2-b9c0-12bbb8267bf8)

**Comment by elijah-semyonov** [comment]
Thanks for the report, we will look into it.

**Comment by alexzhirkevich** [comment]
SwingPanel is always on top of compose content. Just use snackbar inside of panel or use column and display it below panel 
https://github.com/JetBrains/compose-multiplatform/issues/2926

**Comment by xinkunZ** [comment]
@alexzhirkevich  so the snackbar can only display below swingpanel but can not float on it?

**Comment by alexzhirkevich** [comment]
@xinkunZ You can have a `ComposePanel` with snackbar inside your swing panel component, but i guess you have to manually manage its size and position

**Comment by MatkovIvan** [comment]
> `SwingPanel` is always on top of compose content.

It's actually not how it works. It's always under Compose, but Compose uses those component bounds to clip the content.
https://github.com/JetBrains/compose-multiplatform-core/pull/915 changes a way of drawing "the hole" in Compose so it won't affect overlapping elements anymore. I've added the code snippet that shared above to show how it behaves now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3474">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
