### ISSUE TITLE
LazyVerticalGrid fixed columns not reflected in the UI (1.5.0-beta01)

### ISSUE THREAD

**Issue by taaeng** [JetBrains/compose-multiplatform#3475]
**Describe the bug**
When maxColumns changes in `GridCells.Fixed(maxColumns)`, the grid stays the same.

**Affected platforms**
Desktop

**Versions**
- Kotlin version: 1.7.10 
- Compose Multiplatform version: 1.5.0-beta01
- OS version Mac OS 13.5 (22G74)
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 11

**To Reproduce**
1. New Compose Multiplatform project
2. Code:

```
@Composable
@Preview
fun App() {
    MaterialTheme {
        BoxWithConstraints() {
            val maxColumns = when {
                maxWidth > 900.dp -> 4
                maxWidth > 600.dp -> 3
                maxWidth > 440.dp -> 2
                else -> 1
            }
            val gridItems = (0 until 20).toList()
            LazyVerticalGrid(
                columns = GridCells.Fixed(maxColumns),
                modifier = Modifier.fillMaxSize()
            ) {
                itemsIndexed(gridItems) { index, _->
                    Text("Item index: $index")
                }
            }
        }
    }
}
```

**Expected behavior**
Fewer columns as window size gets smaller

**Screenshots**
Version 1.5.0-beta01
![Screen Recording 2023-08-09 at 11 24 28](https://github.com/JetBrains/compose-multiplatform/assets/1119881/d9a293bf-10cb-4605-959f-29ee818c7de2)

Version 1.4.3
![Screen Recording 2023-08-09 at 11 25 32](https://github.com/JetBrains/compose-multiplatform/assets/1119881/d939b2f4-3a76-4baa-ba76-39587708d35a)

**Comment by elijah-semyonov** [comment]
Thanks for the report, looking into it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3475">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
