### ISSUE TITLE
Cursor isn't changed over the bottom edge of resizable undecorated window with MenuBar

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3476]
Compose 1.5.0-beta01, Windows 11, OpenJDK 17

1. Run this snippet:
```
import androidx.compose.ui.window.MenuBar
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication(undecorated = true, resizable = true) {
    MenuBar {
        Menu("Menu") {

        }
    }
}
```
2. Move cursor to the bottom edge

Actual:
The cursor stays with the default icon

Expected:
The cursor should have the resizable icon

It works as expected, if we remove the menu bar

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3476">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
