### ISSUE TITLE
Decide which values can be stored in `rememberSaveable`

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3480]
Android only allows to store [serializable values](https://github.com/JetBrains/compose-multiplatform-core/blob/a63b1dab53ff19709df01d415b721a59a6c9787a/compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/platform/DisposableSaveableStateRegistry.android.kt#L159).

On Desktop/Web/iOS by default every object is allowed to be saved, because they don't save/restore state anywhere yet (third-party navigations libraries on the other hand can add the restriction for saved state to be serializable).

Decide should we add a restriction for values inside `rememberSaveable` to be always serializable for all platforms.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3480">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
