### ISSUE TITLE
Cannot build on Mac for iOS

### ISSUE THREAD

**Issue by djnotes** [JetBrains/compose-multiplatform#3481]
**Describe the bug**
I have xcode 14.2 installed. On Android Studio Giraffe 2022.3.1 Beta 5. I have been trying to build Compose Multiplatform apps on this machine more than 7 times.  It all failed when selecting iosApp as target. 
Android and Desktop targets build successfully, though.  
The error: 

```
The following build commands failed:
	PhaseScriptExecution [CP-User]\ Build\ shared /Users/mhd/src/compose-multiplatform/examples/imageviewer/build/ios/Pods.build/Debug-iphonesimulator/shared.build/Script-BEA8885189D408D600647BDC228A6A20.sh (in target 'shared' from project 'Pods')
(1 failure)

```
Tried running via Xcode. Similar errors popped up as shown in the screenshots section.

**Affected platforms**
Select one of the platforms below:
- iOS
- Other

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin Multiplatform Plugin version: 0.6.1(223)-18
- Kotlin version*: Latest I guess. Difficult to know that from Android Studio anyway
- Compose Multiplatform version*: No idea. 
- OS version(s)* (required for Desktop and iOS issues): No idea. I'm on Mac 12.6.3 (Intel not M*)
- OS architecture (x86 or arm64): arm64 I guess because I want to run on simulator
- JDK (for desktop issues): 11

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1- Clone compose-multiplatform [repo](https://github.com/JetBrains/compose-multiplatform)
2- Open examples/imageviewer in Android Studio
3- Sync Gradle and select target iosApp.
4- Press Run

**Expected behavior**
The iOS version is expected to build and launch successfully on the simulator. 

**Screenshots**
![Screen Shot 2023-08-11 at 6 38 36 PM](https://github.com/JetBrains/compose-multiplatform/assets/9320387/b905fa6a-e7a0-4f73-b71a-67148bf01bb9)

![Screen Shot 2023-08-11 at 6 41 03 PM](https://github.com/JetBrains/compose-multiplatform/assets/9320387/21997c41-240d-4fb9-a2d4-ecd06b8892ef)

**Additional context**
I have not been able to get any successful builds for iOS on Mac so far, both for example JB projects and both for projects I create from scratch in Android Studio. Tried changing networks. Didn't help.

**Comment by m-sasha** [comment]
Seems like the compiler wants you to add an "opt-in" annotation. Did you try that (in Android Studio)?

**Comment by djnotes** [comment]
But, I am not building with commandline. How should I pass that option to the compiler?

**Comment by m-sasha** [comment]
It's not an issue of passing flags to the compiler. You need to add an @OptIn annotation in the code. If you open it in Android Studio you will see a fix suggestion there.

**Comment by clonedSemicolon** [comment]
Is the issue solved or is there some kind of workaround?

**Comment by JoeNajm** [comment]
I am encountering the same issue. Did you find a solution?

**Comment by djnotes** [comment]
Hi Joe,
On Mac version and which MacOS version are you? 

 
 
  On Sat, Mar 23, 2024 at 16:27, ***@***.***> wrote:   


I am encountering the same issue. Did you find a solution?

**Comment by JoeNajm** [comment]
Hello Mehdi,
I am using a Mac mini with Ventura 13.6.4 (however i am using it via a cloud platform called "MacinCloud")
Best,
Joe

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3481">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by djnotes** [comment]
Wow @JoeNajm That's interesting. I didn't know there was such a thing as Mac in Cloud. Can you deploy to local iPhone using that for testing?

**Comment by TSampley** [comment]
@djnotes For the imageviewer example, the kotlin and compose versions can be found in `gradle.properties` at the root.

Also, if your machine is still on 12.6/7+, you're probably still using an Intel-based processor, which means your architecture is x86. If you had Apple Silicon or a real device, it would be arm64, but you're not building on a real device and I don't think any Apple Silicon devices are still running MacOS 12.x, so you must have x86.
