### ISSUE TITLE
AlertDialog and DropDownMenu Missing

### ISSUE THREAD

**Issue by Anirban2022** [JetBrains/compose-multiplatform#3482]
**Describe the bug**
AlertDialog and DropDownMenu missing material3
`

**Affected platforms**
Select one of the platforms below:
- Android
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.5.0-dev1136
- OS version(s)* (required for Desktop and iOS issues): iOS 16.4

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. add the dependency 
2. add DropdownMenu or AlertDialog
3. not resolving

**Expected behavior**
should resolve.

**Comment by BruceMcRooster** [comment]
I also ran into this problem, and it seems to be purely IDE-related. I wrote out some test code for the dropdown menu and was able to run the app. I also opened the project in Fleet (IDEA didn't support AGP) and got the same problem, so I think this is something to do with IntelliJ.

**Comment by BruceMcRooster** [comment]
My thoughts are that it has something to do with the fact that `DropdownMenu` (and `DropdownMenuItem`) and `AlertDialog` are both in files named `*_androidKt` (`AndroidAlertDialog_androidKt` and `AndroidMenu_androidKt` respectively).

In the `classes.jar` of `androidx.compose.material3`, there are only 3 other files that end with `_androidKt`, but they just contain internal variables. I tried a test to access them, and Android Studio did give me an error that it is "Internal to `androidx.compose.material3`", so it is seeing these files to some extent. It seems to just be the Composable functions in files with these endings.

**Comment by BruceMcRooster** [comment]
I just did some more tests, and I think it's just common code having this problem. I created a DropdownMenu without any trouble from the editor in my root Android project (before it called common code). I also got editor autocomplete and no errors creating `DropdownMenu`s in my iOS- and desktop-specific Compose code.

**Comment by brewin** [comment]
[Duplicate](https://github.com/JetBrains/compose-multiplatform/issues/2037)

These were just added in [1.5.0-beta02](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0-beta02)

**Comment by Anirban2022** [comment]
Thanks for adding it. But after updating the version, it does not show in the UI. You can try this project too. https://github.com/Anirban2022/TestComposeUi/blob/8e63b798b4e2baf48f718104ef638eab252919dc/shared/src/commonMain/kotlin/com/sneha/dropdowntest/MainScreen.kt#L33

**Comment by Anirban2022** [comment]
Thanks for adding it. Testes working fine.

**Comment by brewin** [comment]
To be clear, I didn't add it. I'm just closely following progress of the project. Most of the changes are in [compose-multiplatform-core](https://github.com/JetBrains/compose-multiplatform-core).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3482">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
