### ISSUE TITLE
Support packaging Windows service

### ISSUE THREAD

**Issue by wiiznokes** [JetBrains/compose-multiplatform#3484]
My app use a windows service, and right now, is use a script to install it at runtime, but packing it with the app will be better.

**Comment by elijah-semyonov** [comment]
Could you be more specific? Right now it sounds quite vague.

**Comment by wiiznokes** [comment]
seems that you're using  Wix to package MSI (not sure about that).
I never use wix toolset but it seems to have an option to add a service at installation:
https://wixtoolset.org/docs/v3/xsd/wix/serviceinstall/.

Would be nice to have more control on that.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3484">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
