### ISSUE TITLE
Hardware Support

### ISSUE THREAD

**Issue by anuj72** [JetBrains/compose-multiplatform#3488]
Hi is there any way to support hardware like Bluetooth printers and USB printers in windows/mac/linux

**Comment by anuj72** [comment]
![computer_hardware](https://github.com/JetBrains/compose-multiplatform/assets/26837182/e682eeab-7b77-41cf-8639-db9f542bb2c3)

**Comment by elijah-semyonov** [comment]
It's out of scope for Compose Multiplatform. You can ask other people in [Kotlin community](https://kotlinlang.org/community/) about solution to your problem.
