### ISSUE TITLE
DropdownMenu over UIKitView is not clickable

### ISSUE THREAD

**Issue by brewin** [JetBrains/compose-multiplatform#3490]
**Describe the bug**
When a DropdownMenu pops up over a UIKitView, it is not clickable and clicking on the UIKitView does not dismiss it. On Android, it works correctly over an Android View. 

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-beta02
- OS version(s)* (required for Desktop and iOS issues): iOS 16.4

**To Reproduce**
https://github.com/brewin/DropdownMenuBug

**Expected behavior**
The menu should be clickable like on Android.

**Comment by elijah-semyonov** [comment]
Thanks for reporting the issue. We'll be looking into it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3490">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
