### ISSUE TITLE
Web: `LazyColumn` is not scrollable on mobile browser

### ISSUE THREAD

**Issue by JamshedAlamQaderi** [JetBrains/compose-multiplatform#3491]
**Describe the bug**
I've found that `LazyColumn` is not scrollable on mobile browser. But in desktop browser it's working with mouse

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*:  1.9.0
- Compose Multiplatform version*:  1.5.0-beta01
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Use `LazyColumn` which need to be overflow the screen height
2. Run the webpack server using `./gradlew -t :web:jsBrowserRun`
3. Visit the webpage using mobile phone
4. You won't be able to scroll in mobile

**Expected behavior**
`LazyColumn` and `LazyRow` should be scrollable from mobile browser

**Screenshots**

**Additional context**
try to visit my portfolio website using mobile and try to scroll
https://jamshedalamqaderi.com

**Comment by eymar** [comment]
Thank you for reporting!
Indeed, the support for touch events was not implemented yet in CfW. It will be implemented in the future.

**Comment by JamshedAlamQaderi** [comment]
Thanks @eymar

**Comment by garretyoder** [comment]
Is there a roadmap/milestone for this being implemented?

**Comment by pier-bezuhoff** [comment]
As far as i can tell this is implemented and works fine in version 1.6.0

**Comment by JamshedAlamQaderi** [comment]
Nice, I want to give it a try

**Comment by mdsadique-inam** [comment]
TextField focus on click and and even button is not working on android browser

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3491">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
