### ISSUE TITLE
Improve APIs for custom ContextMenuRepresentations

### ISSUE THREAD

**Issue by dzirbel** [JetBrains/compose-multiplatform#3493]
I recently wanted more features for context menus and ended up creating a [small library](https://github.com/dzirbel/compose-material-context-menu) which adds Material styling and a number of new features, including inline icons, dividers, and sub-menus. I ran into a few issues along the way which I think could be addressed relatively easily to allow third-party implementations like this to be much more powerful. I'll put them together in a single issue here.

---

First, if `LocalContextMenuItems` were public (it's currently file-private) this would allow making components that can access the context menu without a right-click. My use case would be an "overflow" triple-dot menu, where we could avoid passing in an items lambda in two different places by using the composition-local items. Here is [an example](https://github.com/dzirbel/compose-material-context-menu/blob/master/lib/src/main/kotlin/com/dzirbel/contextmenu/ContextMenuOverflowButton.kt).

---

Second, heights of context menu popups are slightly too large for the window. In particular, I _think_ (but I'm not entirely sure) that they don't account for the `windowMargin` that can be provided to `rememberNestedDropdownPositionProvider()`, so while the popup has the exact size of the window, it's shifted down by that margin and cut off. I believe the fix would be for `PopupLayout()` to accept a `windowMargin` itself and adjust its layout height accordingly.

Somewhat relatedly, while `rememberNestedDropdownPositionProvider()` generally works as expected, for positioning nested menus I had to re-implement `rememberComponentRectPositionProvider()` since the built-in one does not account for the window bounds. [Here](https://github.com/dzirbel/compose-material-context-menu/blob/master/lib/src/main/kotlin/com/dzirbel/contextmenu/NestedDropdownPositionProvider.kt) is my implementation, which basically just adds logic from `PopupPositionProviderAtPosition`. I'll humbly request this be added to the one provided by Compose so I can delete this code :D

---

Finally and most importantly, I wasn't able to find a perfect way to implement nested context menus since clicks on the menu group item (in the parent menu) will immediately close a nested one. I believe this is simply because that click on the parent menu is outside the nested menu's popup bounds, so it calls its `onDismissRequest` callback which cascades closing the menus. I don't see an obvious solution here, but conceptually the right approach feels like making the nested menu part of the same Composition rather than a new Popup with a new Composition.

Additionally, when building against the pre-releases for 1.5.0 (just tested against 1.5.0-dev1152, but this issue is not present in 1.4.3), even hover actions are consumed by nested menus, so once opened (via hover) a nested menu cannot be closed (by hovering a different item in the parent menu).

---

These issues can be replicated with the demo from my library; just run `./gradlew :demo:run` from https://github.com/dzirbel/compose-material-context-menu. I'd be happy to put up PR(s) for some of the simpler fixes here, but to be honest I'm not sure where the code is hosted since it doesn't seem to be in this repository. Thanks!

**Comment by dzirbel** [comment]
One small update: I did find a workaround for the last issue, nested menus being closed when the parent menu is clicked. I can simply [filter out](https://github.com/dzirbel/compose-material-context-menu/blob/74a96abfbd86a646d6edf46ab674b692b048c023/lib/src/main/kotlin/com/dzirbel/contextmenu/ContextMenuItemContent.kt#L130) the cascading calls to `onDismissRequest()` if the cursor is hovering the parent group item. This feels slightly hacky but seems to work. It does prevent having the group item itself be clickable and doesn't work in 1.5.0 pre-releases (since all pointer events now appear to be consumed by the child popup layer).

**Comment by m-sasha** [comment]
@dzirbel 

> First, if LocalContextMenuItems were public (it's currently file-private) this would allow making components that can access the context menu without a right-click. My use case would be an "overflow" triple-dot menu, where we could avoid passing in an items lambda in two different places by using the composition-local items. Here is [an example](https://github.com/dzirbel/compose-material-context-menu/blob/master/lib/src/main/kotlin/com/dzirbel/contextmenu/ContextMenuOverflowButton.kt).

I'm not 100% sure I understand you correctly, but if you're trying to open a context menu with a custom trigger, you can use the `ContextMenuArea` overload that takes a `ContextMenuState`.


> Second, heights of context menu popups are slightly too large for the window. In particular, I think (but I'm not entirely sure) that they don't account for the windowMargin that can be provided to rememberNestedDropdownPositionProvider(), so while the popup has the exact size of the window, it's shifted down by that margin and cut off. I believe the fix would be for PopupLayout() to accept a windowMargin itself and adjust its layout height accordingly.

Please submit a bug with a short reproducer for this (and tag me).


> Somewhat relatedly, while rememberNestedDropdownPositionProvider() generally works as expected, for positioning nested menus I had to re-implement rememberComponentRectPositionProvider() since the built-in one does not account for the window bounds. [Here](https://github.com/dzirbel/compose-material-context-menu/blob/master/lib/src/main/kotlin/com/dzirbel/contextmenu/NestedDropdownPositionProvider.kt) is my implementation, which basically just adds logic from PopupPositionProviderAtPosition. I'll humbly request this be added to the one provided by Compose so I can delete this code :D

Also, please submit a bug.


> Finally and most importantly, I wasn't able to find a perfect way to implement nested context menus since clicks on the menu group item (in the parent menu) will immediately close a nested one. I believe this is simply because that click on the parent menu is outside the nested menu's popup bounds, so it calls its onDismissRequest callback which cascades closing the menus. I don't see an obvious solution here, but conceptually the right approach feels like making the nested menu part of the same Composition rather than a new Popup with a new Composition.

This sounds to me like exactly the behavior you'd want for nested/cascading context menus, no? If There's an open context menu and an open submenu, and you click on a different submenu-item, the first submenu should be closed. Perhaps I don't understand what you mean, though.


> Additionally, when building against the pre-releases for 1.5.0 (just tested against 1.5.0-dev1152, but this issue is not present in 1.4.3), even hover actions are consumed by nested menus, so once opened (via hover) a nested menu cannot be closed (by hovering a different item in the parent menu).

Indeed we have changed this behavior in 1.5; perhaps we should reconsider it. @MatkovIvan I think this prevents mouse-move events from being sent to an `owner` below any "focusable" owner. In `ComposeScene.processMove`:
```
        if (!isInteractive(owner)) {
            owner = null
        }
```

**Comment by m-sasha** [comment]
> Additionally, when building against the pre-releases for 1.5.0 (just tested against 1.5.0-dev1152, but this issue is not present in 1.4.3), even hover actions are consumed by nested menus, so once opened (via hover) a nested menu cannot be closed (by hovering a different item in the parent menu).

Ok, after discussing it with the team:
1. In 1.5.0 we changed the behavior to match the way Android does this. We understand that this behavior is inadequate in the desktop use-case for nested context menus, and we will address it, but not in 1.5.0.
2. The behavior in 1.4 wasn't consistent to begin with. You would receive mouse-move events in the parent menu, but not mouse press/click events, so you couldn't click to select a different sub-menu than the currently opened one.
3. Until we support this use-case, you can try passing `properties = PopupProperties(focusable = false)` to the `Popup`, which should allow you to receive mouse-move and mouse-press events in the parent popup. You will lose the ability to receive key events in the popups, but maybe it's possible to handle them in the parent element (outside the popups).

**Comment by dzirbel** [comment]
@m-sasha Thank you so much for the detailed response, I really appreciate you looking into this :) OK, I'll submit separate bugs for the popup size/positing issues.

> I'm not 100% sure I understand you correctly, but if you're trying to open a context menu with a custom trigger, you can pass a ContextMenuState to the ContextMenuArea and control the open state via ContextMenuState.status programmatically. If you want to disable the right-click detector, you can pass enabled = false.

Ahh, you're right - that will work for my use case. Thank you! It does make me wonder if perhaps `ContextMenuArea` should provide its `items` to the `LocalContextMenuData` inside its content since right now the simplest way to use an overflow button looks like this:

```
ContextMenuDataProvider(items = { listOf(item1, item2, item3) }) {
    ContextMenuArea(items = { emptyList() }) {
        // ... regular content
        ContextMenuOverflowButton()
    }
}
```

which would be cleaner if either (a) `ContextMenuArea` propagated its items to `LocalContextMenuData` automatically, so we could drop the wrapping in `ContextMenuDataProvider` or (b) the `items` parameter in `ContextMenuArea` had a default value returning `emptyList()` (but this could be confusing for the simpler cases with just a `ContextMenuArea`). Just a small thought, not a big deal.

> This sounds to me like exactly the behavior you'd want for nested/cascading context menus, no? If There's an open context menu and an open submenu, and you click on a different submenu-item, the first submenu should be closed. Perhaps I don't understand what you mean, though.

Yeah, this is a bit hard to explain, here's an example of what I mean:

![ezgif-1-52adb4bee4](https://github.com/JetBrains/compose-multiplatform/assets/1222738/e59f08e4-7255-48f3-b9a4-8a4c56b1ba11)

Before my second comment adding [this filter](https://github.com/dzirbel/compose-material-context-menu/blob/74a96abfbd86a646d6edf46ab674b692b048c023/lib/src/main/kotlin/com/dzirbel/contextmenu/ContextMenuItemContent.kt#L130), there was an issue where clicking any of these items in the parent menu would close the child one, since that would be a click outside its popup area. In retrospect, this was essentially just a bug in my code since that would cascading closing the parent menu as well.

> Until we support this use-case, you can try passing properties = PopupProperties(focusable = false) to the Popup, which should allow you to receive mouse-move and mouse-press events in the parent popup. You will lose the ability to receive key events in the popups, but maybe it's possible to handle them in the parent element (outside the popups).

Ah, yes, this works perfectly and will also allow me to make the group items themselves clickable (and potentially support "open-submenu-on-click" rather than "open-submenu-on-hover" if that's ever desired). It's too bad to lose key events, which I could see being an accessibility issue but I think this will work for my use case until you're able to address it in the future.

Thanks again, I think that resolves my questions for the moment outside of the ones I'll file bug reports for, so I'll close this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3493">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
