### ISSUE TITLE
LazyColumn not recomposing on update

### ISSUE THREAD

**Issue by paulorb** [JetBrains/compose-multiplatform#3494]
**Describe the bug**
I am trying to use LazyColumn with a list, when the list is updated the UI is not recomposing. When removing or adding it works fine. I tried deep copy but it still doesn't work. 
**This project is using decompose library**

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*:  1.9.0
- Compose Multiplatform version*:  1.4.3
- OS version(s)* (required for Desktop and iOS issues):  MacOs Catalina 10.15.7
- OS architecture (x86 or arm64):  x64
- JDK (for desktop issues):  openjdk 17.0.3 2022-04-19

**To Reproduce**

Component
```
interface TestComponent {
 val model: Value<Model>
 data class Model(
        val  testList: List<Information>
 )

 data class Information(
        var name: String,
 )
}

class DefaultTestComponent(
    componentContext: ComponentContext) :
    TestComponent,
    ComponentContext by componentContext {

    private val _model = MutableValue<Model>(Model(listOf()))
    override val model: Value<Model>
        get() = _model

    init {
        lifecycle.subscribe(
            onCreate = { },
            onStart = {
                Thread {
                    var i = 1
                    while (1 == 1) {
                        Thread.sleep(10000)
                        val mutableTestList = _model.value.testList.toMutableList()
                        mutableTestList.find { it.name == i.toString() }!!.name = "OK"
                        _model.update { Model(mutableTestList.toList()) }
                        i++;
                    }
                }.start()
            })

    }
}
```

Composable function

```
   val model by component.model.subscribeAsState()

   LazyColumn(modifier = modifier.fillMaxSize()) {
                    items(items = model.testList) { item ->
          Text(item.name)
   }
```

**Additional context**
On the real project, I am receiving a callback from another thread, this is a sample to demonstrate the possible issue.  I don't think the fact that I am updating the state from another thread could be the root cause of the issue. According to Decompose:

_Even though both Value and MutableValue are thread-safe, it's recommended to subscribe and update it only on the main thread._

I understand it will only recompose when it detect changes, in this case I am changing the value and creating another instance (deep copy) of the  object. 

Am I doing something wrong or is there any known issue on LazyColumn or related components?

**Comment by dima-avdeev-jb** [comment]
It is hard to understand thats wrong. Is it Compose Desktop, or Decompose library, or even wrong usage of both in your project.
Can you create a minimal reproducible sample and share it on GitHub?
And after it try to minify project without Decompose library.

It will be helpfull to us.

After you do so, we also can ask @arkivanov for help with Decompose.

**Comment by arkivanov** [comment]
It looks the issue is because you are mutating the `name` property. Please try making it `val` and copy the `Information` class instead, and also create a new copy of List with the new Information instance.

**Comment by paulorb** [comment]
Thanks @arkivanov after changing to val (immutable) and copying the whole list it worked fine.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3494">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
