### ISSUE TITLE
[1.5.0-beta02] Dialog has no background scrim on Android

### ISSUE THREAD

**Issue by chrisbanes** [JetBrains/compose-multiplatform#3495]
Using the new `Dialog` support in 1.5.0-beta02, on Android there is no background scrim drawn.

~Seems to be missing a call to `window.setBackgroundDrawable(ColorDrawable(properties.scrimColor))` in [DialogWrapper.updateProperties](https://github.com/JetBrains/compose-multiplatform-core/blob/40e76ce83f97147ce441667936039cc31f867618/compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/window/AndroidDialog.android.kt#L411C9-L411C25).~

**Comment by dima-avdeev-jb** [comment]
Thanks!
Do you mean, that there are some code in Android JetPack Compose, that we should pull to our fork for Release of Comose Multiplatform 1.5.0 ?

**Comment by chrisbanes** [comment]
Not quite. DialogWrapper explicit sets the [window background to transparent](https://github.com/JetBrains/compose-multiplatform-core/blob/40e76ce83f97147ce441667936039cc31f867618/compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/window/AndroidDialog.android.kt#L323C9-L323C74) (not sure why?). If you remove that, you should get the default platform behaviour (a translucent scrim).

Ignore what I said about `scrimColor`. That doesn't seem to exist on `main` (I saw it by clicking through in IJ)

**Comment by dima-avdeev-jb** [comment]
@igordmn We can control Android part only with Google artifacts that we are targetting.
Should we check it with another one android artifacts?

**Comment by dima-avdeev-jb** [comment]
@chrisbanes Can you please create a minimal reproducible sample on GitHub ?

**Comment by igordmn** [comment]
The first issue is needed to be adressed soon.

Not sure about the second issue, it depends on how much it affects the users. Chris, can you describe the case why you needed to change it?

**Comment by chrisbanes** [comment]
Hmmm, I just tested on a physical Android device and the dialogs have a scrim. I was seeing no scrim on an Android SDK 34 emulator so not sure why its different. Anyway, I think we can close this.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3495">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
