### ISSUE TITLE
Add Android preview to android-ios compose template

### ISSUE THREAD

**Issue by gastsail** [JetBrains/compose-multiplatform#3499]
**Describe the bug**
I'm trying to preview my composables on the android side to see what I'm doing before compiling.

I have added the preview tooling lib to the androidMain

![Screen Shot 2023-08-15 at 15 02 21](https://github.com/JetBrains/compose-multiplatform/assets/24615408/033f654b-ba14-4b11-97bc-1351f740299a)

And then used the @Preview annotation on my androidmain package inside my shared folder

![Screen Shot 2023-08-15 at 15 02 47](https://github.com/JetBrains/compose-multiplatform/assets/24615408/12d5c9c7-77ca-4d19-ad6c-40fa8f9c816d)

I cannot even see the preview icon on the top right corner to see the composable preview

This is my setup

![Screen Shot 2023-08-15 at 15 15 44](https://github.com/JetBrains/compose-multiplatform/assets/24615408/7c9a53fc-e121-4362-ad72-fdebf615ab24)

**Affected platforms**
Select one of the platforms below:
- All
- <s> iOS </s> (we don't support Preview on iOS, @dima-avdeev-jb )
- Android

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 0.6.1
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): corretto-17

**Expected behavior**
I should be able to see the preview

**Comment by mazunin-v-jb** [comment]
Hello! Thanks for the issue.
Could you please provide info about the affected platform?
And could you check again your Compose Multiplatform version?

**Comment by gastsail** [comment]
Hey how are you thanks for your reply, compose plugin version is 0.6.0 , I have also tried downgrading jdk to 11 , 16 and still the same.

Im trying only to run this on the Android side, thanks.

**Comment by mazunin-v-jb** [comment]
Thank you for providing information. Could you please try to create a new Android project and check if it works in it?
And if so, could you please check how you connect artifacts and dependencies in androidApp/build.gradle.kts in both your projects?

**Comment by gastsail** [comment]
Hey @mazunin-v-jb I have used this template https://github.com/JetBrains/compose-multiplatform-ios-android-template#readme I did not start it from scratch, surprisingly I cannot find any example that uses the @Preview annotation, is just me or for now is it having issues ?

**Comment by mazunin-v-jb** [comment]
That's correct, [that template](https://github.com/JetBrains/compose-multiplatform-ios-android-template#readme) doesn't have a preview setting for Android. We're planning to fix this later.

**Comment by gastsail** [comment]
Thanks a lot @mazunin-v-jb , I will be waiting and trying out new things, will close this for now :)

**Comment by gastsail** [comment]
or should we keep it open for when an update is available ?

**Comment by fernandozanutto** [comment]
I added these settings inside the android block of the root build.gradle.kts
```
buildFeatures {
      compose = true
  }
  composeOptions {
      kotlinCompilerExtensionVersion = "1.5.1"
  }
```

Besides this dependencies for androidMain

```
api(compose.preview)
api(compose.uiTooling)
```

And my previews are showing

<img width="1027" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/15229294/2d6c40b7-d3e1-48f6-9143-a2dfa6bf6f94">

**Comment by gastsail** [comment]
Thanks a lot @fernandozanutto will try this one and let you know 👍

**Comment by gastsail** [comment]
Ok, so, I have added 

```
composeOptions {
        kotlinCompilerExtensionVersion = "1.5.1"
    }
    buildFeatures {
        compose = true
    }
```

As @fernandozanutto suggested inside the `:androidApp buildGradle file` , then added 

```
api(compose.preview)
api(compose.uiTooling)
```

Inside androidMain in the `:shared build.gradle file`, and now from `androidApp` package I can render the previews

![Screenshot 2023-08-21 at 11 14 06](https://github.com/JetBrains/compose-multiplatform/assets/24615408/08cda1de-a50a-4c98-897c-96d6efab6a90)


Btw, on gradle.properties I'm using

```
#Gradle
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"

#Kotlin
kotlin.code.style=official

#MPP
kotlin.mpp.stability.nowarn=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2

#Compose
org.jetbrains.compose.experimental.uikit.enabled=true
compose.ios.resources.sync=false

#Android
android.useAndroidX=true
android.compileSdk=34
android.targetSdk=33
android.minSdk=24

#Versions
kotlin.version=1.9.0
agp.version=8.0.2
compose.version=1.5.0-beta02
```

**Comment by realityexpander** [comment]
This has been broken again with kotlin 1.9.10, compose 1.5.2, agp 8.0.2

**Comment by dima-avdeev-jb** [comment]
Related PR and discussion here: https://github.com/JetBrains/compose-multiplatform-template/pull/18

**Comment by ariefannur** [comment]
same with @realityexpander got this error 
` Cannot cast androidx.compose.compiler.plugins.kotlin.ComposePluginRegistrar to org.jetbrains.kotlin.compiler.plugin.CompilerPluginRegistrar`

**Comment by virtanAnton** [comment]
To solve [ambiguous behaviour](https://github.com/JetBrains/compose-multiplatform-template/pull/18#discussion_r1304094662) in gradle plugin and make Layout Inspector work, you may define separate gradle module for Android build.gradle(:app) and for multiplatform build.gradle (:shared) with mentioned configuration https://github.com/JetBrains/compose-multiplatform/issues/3499#issuecomment-1686417059

```
android {
    buildFeatures {
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = extensions.getByType(ComposeExtension::class.java)
            .dependencies.compiler.auto.substringAfterLast(":")
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }

    dependencies {
        debugImplementation(compose.uiTooling)
    }
}
```

**Comment by virtanAnton** [comment]
Check resources demo project here: https://github.com/virtanAnton/compose-multiplatform/tree/local-dev
 To open: open ./components/build.gradle.kts

**Comment by virtanAnton** [comment]
> > To solve [ambiguous behaviour](https://github.com/JetBrains/compose-multiplatform-template/pull/18#discussion_r1304094662) in gradle plugin and make Layout Inspector work, you may define separate gradle module for Android build.gradle(:app) and for multiplatform build.gradle (:shared) with mentioned configuration [#3499 (comment)](https://github.com/JetBrains/compose-multiplatform/issues/3499#issuecomment-1686417059)
> > ```
> > android {
> >     buildFeatures {
> >         compose = true
> >     }
> > 
> >     composeOptions {
> >         kotlinCompilerExtensionVersion = extensions.getByType(ComposeExtension::class.java)
> >             .dependencies.compiler.auto.substringAfterLast(":")
> >     }
> > 
> >     packaging {
> >         resources {
> >             excludes += "/META-INF/{AL2.0,LGPL2.1}"
> >         }
> >     }
> > 
> >     dependencies {
> >         debugImplementation(compose.uiTooling)
> >     }
> > }
> > ```
> 
> What are the versions of the plug-ins you are using for this?
> 
> I tried to apply your suggestion to my project : https://github.com/realityexpander/FredsRoadtripStoryteller.git
> 
> ![image](https://private-user-images.githubusercontent.com/5157474/298700446-d02ae628-39f8-48ef-91b6-c0ee0b969a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDg2NTUsIm5iZiI6MTcwNjAwODM1NSwicGF0aCI6Ii81MTU3NDc0LzI5ODcwMDQ0Ni1kMDJhZTYyOC0zOWY4LTQ4ZWYtOTFiNi1jMGVlMGI5NjlhNDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTExMjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzhlMzY1MzYzMjFhMzc4NzczOWMyMGMzMDJhZWY3NjE2MjFiN2ZhMDUxNTFiZmFhNWI4YjFmMDhhOWFlNGI3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6NN2u6nNTcE3NbYNOpNcpqlPeeMQq6OfHMe8Nx3qlxw)

Check resources demo project here: https://github.com/virtanAnton/compose-multiplatform/tree/local-dev
To open: open ./components/build.gradle.kts
It's use compose.version=1.6.0-dev1378

**Comment by hafiz013** [comment]
Why my ticket request feature link to this ticket which actually not answering my request which is compose preview not applicable in folder composeApp.

**Comment by brucemax** [comment]
> Why my ticket request feature link to this ticket which actually not answering my request which is compose preview not applicable in folder composeApp.

Totaly agree, I haven't "Code/Splite/Design" buttons for files in composeApp folder at all.

BTW Preview feature is very important, but all their template projects just ignore it, disappointed

**Comment by hafiz013** [comment]
I know that preview can do inside android folder but it is wasting time double instead can focus only composeApp folder. Please make it visibile to view. Thanks in advance

**Comment by dima-avdeev-jb** [comment]
@hafiz013 Thanks for description.
Yes, we plan to do so in commonMain - but it is really a huge task.

**Comment by gastsail** [comment]
@dima-avdeev-jb take your time, you guys are doing an awesome job already porting compose to multiplatform, thanks a lot !

**Comment by brucemax** [comment]
> @dima-avdeev-jb take your time, you guys are doing an awesome job already porting compose to multiplatform, thanks a lot !

Agreed. Compose and KMP is best best happened with mobile development last 10 years 👍

**Comment by andrey2ag** [comment]
Following the thread... I would love to see the Preview issue fixed

**Comment by brucemax** [comment]
> Following the thread... I would love to see the Preview issue fixed

Do you Preview in commonMain ? But how?
I placed implementation (compose.components.uiToolingPreview) in commonMain. Preview annotation is available but design section not appeared

**Comment by arok** [comment]
For me @Preview annotation works in Android Studio in common module but it seems AS does not support compose multiplatform resources so if my composable uses any `Res.drawable` I get the following error `org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: drawable/ic_plus_16.xml`

**Comment by hafiz013** [comment]
@arok if you follow information from kmp they say that have to add res in gradle then import it by using you own id for example import project res.sample.com so when call in main screen res.drawable.ic_plus_16 . However, i have been bugs if you add new drawable seem like kmp composeApp not trigger. To fix it you have to run unit test first then error import trigger then you have click command + enter ( to import). Then running again unit test, later install package composeApp to device, it ok.

**Comment by hafiz013** [comment]
@dima-avdeev-jb  you doing super great things. Do you that, nowadays folder composeApp can have notation @preview however can’t preview the screen. By the way if this @preview work (can preview live screen) in composeApp, i believe this kmp can beat flutter and react native in th future. In fact, in this future kmp is game changer for feature development. I try convey my boss but he eliminated my suggestion say that react native is importance and our client use this. Hopefully, one day i can prove that to my boss kmp can same level or better than react native and flutter.

**Comment by arok** [comment]
@hafiz013 completely did not get you, could you point me to the info from KMP?

**Comment by hafiz013** [comment]
@previewnotation can add in composeApp but couldn’t view ui live

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3499">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
