### ISSUE TITLE
TextOverflow.Ellipsis behaves differently on desktop and Android platforms

### ISSUE THREAD

**Issue by gleb-skobinsky** [JetBrains/compose-multiplatform#3504]
**Describe the bug**
In Android, `TextOverflow.Ellipsis` results in adding an ellipsis immediately when no more space is available, therefore an ellipsis can be added in the middle of a word. In Desktop, the ellipsis is always added after the last word that has any available space. Due to that the user experience differs when using the same code on different platforms. A workaround for this can easily be found, but our team would want to use a standard solution for that or at least know the reason why this happens.

**Affected platforms**
- Desktop
- Android

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.4.3
- OS version(s)*: Ubuntu 20.04.6 LTS, Windows 11
- OS architecture: x86
- JDK: OpenJDK 11

**To Reproduce**
I've created a small testing repository to replroduce the issue using the official Compose Multiplatform Github template. You can simply clone it and launch Desktop and Android app: https://github.com/gleb-skobinsky/text-overflow

**Expected behavior**
Same code renders same UI in both platforms.

**Screenshots**
![show_desktop](https://github.com/JetBrains/compose-multiplatform/assets/90451272/b79129e5-dbf0-4cac-8158-03aff73628ae)
![show_android](https://github.com/JetBrains/compose-multiplatform/assets/90451272/571a5473-65ef-4365-8437-eeaea84898e9)

**Comment by mazunin-v-jb** [comment]
Hello! 
Thanks for submitting the issue and the reproducer.
I'll pass this to the appropriate person.

**Comment by mazunin-v-jb** [comment]
[Found similar issue.](https://github.com/JetBrains/compose-multiplatform/issues/1888)
Closing this issue as duplicate, all possible fixes will be in that earlier issue.

Please feel free to reopen this issue if you have any questions or objections.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3504">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
