### ISSUE TITLE
Focus behavior while mouse/touch interactions on different platforms

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#3508]
Figure out how to make focus onClick feature device-dependent (Mouse/Touch/Keyboard) instead of platform dependent (Desktop/iOS/Android)

Take a look at this PR: https://github.com/JetBrains/compose-multiplatform-core/pull/757

Also, take at usage of function https://github.com/JetBrains/compose-multiplatform-core/blob/033e69f0c9464c50d255e99e06504824d11e93a2/compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/focus/FocusRequesterModifierNode.kt#L39

And function https://github.com/JetBrains/compose-multiplatform-core/blob/033e69f0c9464c50d255e99e06504824d11e93a2/compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/focus/FocusRequester.kt#L62

**Comment by igordmn** [comment]
Moved to https://youtrack.jetbrains.com/issue/CMP-5814/Review-Request-focus-on-click-feature

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3508">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3508">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
