### ISSUE TITLE
Default FloatingActionButton implementation shape is romboid instead of a circle

### ISSUE THREAD

**Issue by gastsail** [JetBrains/compose-multiplatform#3510]
**Describe the bug**
I have implemented the default FloatingActionButton on my project, output is a romboid instead of a circle shape, default implementation has a 50% radius that should be applied to it.

**Affected platforms**
Select one of the platforms below:
- Android
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 0.6.1
- JDK (for desktop issues): 17
- Compose version : 1.4.3

**Expected behavior**

**Screenshots**
![Screen Shot 2023-08-16 at 16 31 16](https://github.com/JetBrains/compose-multiplatform/assets/24615408/e443d96f-1871-40ad-9d77-a49548f750c5)
![Screen Shot 2023-08-16 at 16 31 32](https://github.com/JetBrains/compose-multiplatform/assets/24615408/837e47d6-6b30-4c6e-a325-7c5f395c2865)

If I add shape to it, it successfully apply the desired shape

![Screen Shot 2023-08-16 at 16 32 52](https://github.com/JetBrains/compose-multiplatform/assets/24615408/3f836a75-5f11-4036-9f14-a9035a7aea44)

**Comment by mazunin-v-jb** [comment]
Hello! Thanks for submitting the issue.

For now, I don't see anything that would cause that behavior in your screenshots. Could you please create a minimal reproducible example?

**Comment by gastsail** [comment]
hey @mazunin-v-jb currently in a fresh new project the problem is not there, seems like that from the jetpack compose template is where the problem comes from.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3510">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
