### ISSUE TITLE
Material 3 HorizontalDivider and VerticalDivider

### ISSUE THREAD

**Issue by skolson** [JetBrains/compose-multiplatform#3512]
Compose material3 1.2.0-alpha04 added `HorizontalDivider` and `VerticalDivider` and began deprecating `Divider`. Add HorizontalDivider and VerticalDivider to Compose multiplatform. 
A small issue and easy to work around :-) But would be good to have consistency with material 3 on these.
See [1.2.0-alpha4 source](https://android-review.googlesource.com/c/platform/frameworks/support/+/2640776/5/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/Divider.kt)

**Comment by mazunin-v-jb** [comment]
Hello! Thanks for the issue.
As soon as we will merge Material3 we will have these changes in Compose Multiplatform. 
But unfortunately, I can't say right now where it will happen.
Please stay tuned!

**Comment by hrach** [comment]
Is there a ticket to follow M3 1.2 merge?

**Comment by phzi** [comment]
> Is there a ticket to follow M3 1.2 merge?

https://github.com/JetBrains/compose-multiplatform/issues/4124

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3512">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
