### ISSUE TITLE
rememberComponentRectPositionProvider() does not respect window bounds

### ISSUE THREAD

**Issue by dzirbel** [JetBrains/compose-multiplatform#3514]
**Describe the bug**
Using `rememberComponentRectPositionProvider()` (for my use case, to position nested context menus) positions popups in a way that allows them to overflow the side of the window. This is especially unexpected because `rememberPopupPositionProviderAtPosition()` avoids popups extending beyond the window bounds.

In `1.5.0-dev1152` the behavior is changed - PopupLayout now has built-in checks against window overflow, but it still does not behave quite as expected. While `rememberPopupPositionProviderAtPosition()` will shift the popup `alignment` relative to its anchor when it cannot fit (i.e. from the right to the left of the cursor), `rememberComponentRectPositionProvider()` does not do this, so the popup can be on top of the component rect. That's not the desired behavior for my use case (which I can fix with a custom PopupPositionProvider), but it might be acceptable for general use of `rememberComponentRectPositionProvider()`.

Moreover, in both versions `rememberComponentRectPositionProvider()` does not accept a `windowMargin` parameter like `rememberPopupPositionProviderAtPosition()`, which would be a nice-to-have. See also #3513 

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.4.3 and 1.5.0-dev1152
- OS version(s)* (required for Desktop and iOS issues): Linux Mint 21.2 Cinnamon
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 11

**To Reproduce**
This can be demonstrated from the `bug/rememberComponentRectPositionProvider` branch of my project: https://github.com/dzirbel/compose-material-context-menu/tree/bug/rememberComponentRectPositionProvider with `./gradlew :demo:run`. Then hover a sub-menu when the context menu is near the edge of the window.

**Expected behavior**
`rememberComponentRectPositionProvider()` should match the behavior of `rememberPopupPositionProviderAtPosition()` to position the popup inside the window, ideally with an optional `windowMargin`. This is more or less just a matter of copying that logic to it, for example in a [custom provider](https://github.com/dzirbel/compose-material-context-menu/blob/master/lib/src/main/kotlin/com/dzirbel/contextmenu/NestedDropdownPositionProvider.kt) I made for my project.

**Screenshots**
1.4.3:

![Screenshot from 2023-08-16 15-15-47](https://github.com/JetBrains/compose-multiplatform/assets/1222738/3fd1df47-5648-4545-af88-e6f1a0cb1575)

1.5.0-dev1152:

![Screenshot from 2023-08-16 15-18-02](https://github.com/JetBrains/compose-multiplatform/assets/1222738/b6f2ff21-d7a4-4f48-a71b-b930429bd9db)

(note that a `windowMargin` of 4 dp is not being respected)

**Additional context**
See also discussion in https://github.com/JetBrains/compose-multiplatform/issues/3493; cc @m-sasha

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3514">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
