### ISSUE TITLE
`runtime-saveable`: supports `tvos` and `watchos` 

### ISSUE THREAD

**Issue by hoc081098** [JetBrains/compose-multiplatform#3521]
Currently, this modules supports android, jvm, js, ios and macos.
Please support `tvos` and `watchos`.

**Comment by mazunin-v-jb** [comment]
Hello, thanks for the issue!
I'll pass it on to the team.

**Comment by dima-avdeev-jb** [comment]
For now, `runtime-saveable` have a sence only for Android. For other platform it works the same a `remember`. So, you can create your own `expect fun myRememberSaveable(...)` with empty actuals on all platforms and only one real implementation on androidMain sourceSet: `actual fun myRememberSaveable() = rememberSaveable(...)`

**Comment by hoc081098** [comment]
> For now, `runtime-saveable` have a sence only for Android. For other platform it works the same as `remember`. So, you can create your own `expect fun myRememberSaveable(...)` with`actual fun myRememberSaveable(...) = remember(...)` on all platforms and only one real implementation on androidMain sourceSet: `actual fun myRememberSaveable() = rememberSaveable(...)`

Thanks for your reply.
Imo, using `rememberSavable()` with `rememberStateHolder()` is useful in navigation pattern.
It allows state of a composable can be saved and restored (via Bundle on Android and in-memory on other platforms)

**Comment by hoc081098** [comment]
I did some investigation and looks like `rememberSaveable` actually works, but you need to implement additional thing to make it work, it's just that android's navigation library already has it implemented underneath. Also on desktop serialization is not really is necessary since everything is stored in memory

To make it work you need to create instance of `SaveableStateHolder` with `rememberSaveableStateHolder()` and wrap you navigation destinations with `stateHolder.SaveableStateProvider(stringKey) { content }`, it will assosiate your content with key and save data for specific destinations, then when removing destination you just need to invoke `SaveableStateHolder.removeState(key)` 

Here is snippet of what I did in my project:

```
interface MultiplatformMainNavigationState : MainNavigationState {
    val currentDestination: State<MainDestination>
    val stateHolder: SaveableStateHolder
}

@Composable
fun MultiplatformMainNavigation(
    state: MainNavigationState
) {

    state as MultiplatformMainNavigationState

    val destination = state.currentDestination.value

    state.stateHolder.SaveableStateProvider(destination.toString()) {
        when (destination) {
            MainDestination.Home -> {
                val homeNavigationState = rememberHomeNavigationState()
                HomeScreen(
                    viewModel = getMultiplatformViewModel(),
                    mainNavigationState = state,
                    homeNavigationState = homeNavigationState
                )
            }
            MainDestination.About -> {
                AboutScreen(
                    mainNavigationState = state,
                    viewModel = getMultiplatformViewModel()
                )
            }
            // ...others
        }
    }

}

@Composable
fun rememberMultiplatformMainNavigationState(): MainNavigationState {
    val stack = remember { mutableStateOf<List<MainDestination>>(listOf(MainDestination.Home)) }
    val currentDestinationState = remember { derivedStateOf { stack.value.last() } }

    val stateHolder = rememberSaveableStateHolder()

    return remember {
        object : MultiplatformMainNavigationState {

            override val currentDestination = currentDestinationState
            override val stateHolder: SaveableStateHolder = stateHolder

            override fun navigateBack() {
                val lastItem = stack.value.last()
                stack.value = stack.value.dropLast(1)
                stateHolder.removeState(lastItem.toString())
            }

            override fun popUpToHome() {
                val itemsToRemove = stack.value.drop(1)
                stack.value = stack.value.take(1)
                itemsToRemove.forEach { stateHolder.removeState(it) }
            }

            override fun navigate(destination: MainDestination) {
                stack.value = stack.value.plus(destination)
            }

        }
    }
}
```

_Originally posted by @syt0r in https://github.com/JetBrains/compose-multiplatform/issues/1932#issuecomment-1469735146_

**Comment by hoc081098** [comment]
Closed by https://github.com/JetBrains/compose-multiplatform/issues/3899

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3521">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
