### ISSUE TITLE
Execution failed for task ':domain:kaptDebugKotlin'.

### ISSUE THREAD

**Issue by AnkitaManiya314** [JetBrains/compose-multiplatform#3523]
**Describe the bug**
Project build kotlin  error after updating  gradle - version.

**Versions**
-  dependencies {
        classpath 'com.android.tools.build:gradle:7.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10"
        classpath "io.realm:realm-gradle-plugin:10.11.1"
    
    }
- subprojects {
    afterEvaluate {
        if (project.hasProperty('kapt')) {
            kapt {
                javacOptions {
                    option("-source", "8")
                    option("-target", "8")
                }
            }
        }
    }
}
-  distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip
-  composeOptions {
        kotlinCompilerExtensionVersion = "1.3.0"
    }

**Expected behavior**
Want to Project in runnable mode with Kotlin version 1.7.10 only. Give me stability version related this of others libs..

**Additional context**
This will give me RealM issues too.

**Comment by mazunin-v-jb** [comment]
Hello, thanks for the issue.
Could you provide the following information:
- Affected platforms
- Compose Multiplatform version
- OS version
- OS architecture
- JDK 

Also, could you create a minimal reproducer?
You can use [this template](https://github.com/JetBrains/compose-multiplatform-template), It contains all relevant versions of the required libraries.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3523">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
