### ISSUE TITLE
Bug in LazyColumn when you have an interactive UIKitView inside

### ISSUE THREAD

**Issue by MohamedRejeb** [JetBrains/compose-multiplatform#3525]
**Describe the bug**
When you have a LazyColumn with an interactive UIKitView that has some animations like the time picker, if the time picker is animating, the LazyColumn scroll behavior is not correct.

**Affected platforms**
- iOS

**Versions**
- Kotlin version: 1.9.0
- Compose Multiplatform version: 1.5.0-beta02
- OS version(s): All

**To Reproduce**
1. Add a lazy column
2. Add some demo composables to have a scroll
3. Add a UIKitView to the lazy column (The UiKit time picker wheel or something similar)

**Expected behavior**
It should scroll normally.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/124871594/1f44f392-f86d-4e96-ba6c-63101bb0c490

**Comment by kirvigen** [comment]
I have the same proble with AVPlayerViewController inside UIKitView

https://github.com/JetBrains/compose-multiplatform/assets/38012174/54e17219-9b17-44e7-9588-492a44779ae2

**Comment by kasem-sm** [comment]
any updates on this issue?

**Comment by elijah-semyonov** [comment]
Not yet. I'll have a look at it asap.

**Comment by elijah-semyonov** [comment]
I've performed a little investigation on this, but no resolution yet. It's a low priority issue at the moment. I'd advise against using animated interop views at the same time as changing their frames within Compose due to the CATransaction mechanism causing awkward bugs like that.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3525">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
