### ISSUE TITLE
Missing Material 3 Components 1.5.0-rc01

### ISSUE THREAD

**Issue by 456634** [JetBrains/compose-multiplatform#3528]
Missing components for material 3 1.1.1

- ModalBottomSheet
- SearchBar, DockedSearchBar
- ExposedDropdownMenuBox
 
Plattform:
- Desktop

- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.5.0 -beta02 / -rc01
- OS version(s)* (required for Desktop and iOS issues): Arch Linux

**Comment by igordmn** [comment]
We resolved the major blocker (a common Popup) for such commonization, but we postponed commonization of the components itself after the 1.5.0 release.

I can't tell the ETA, but we will be working on this commonization in the near months.

We also planned an intermediiate small feature release 1.5.10 before the 1.6. If there won't be major blockers for the commonization, some of the components (or all) will be in 1.5.10.

**Comment by kodeplateform** [comment]
Not available in 1.5.1

**Comment by MatkovIvan** [comment]
All mentioned components were merged in main branch and will be available in the next release

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3528">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
