### ISSUE TITLE
iOS keyboard not showing when focus TextField

### ISSUE THREAD

**Issue by gastsail** [JetBrains/compose-multiplatform#3530]
**Describe the bug**
I'm trying to pop up the keyboard on iOS when TextField is tapped, this works well on Android but on iOS I need to use the shortkey as described here

<img width="1348" alt="Screen Shot 2023-08-18 at 15 58 53" src="https://github.com/JetBrains/compose-multiplatform/assets/24615408/4d7ea9ab-5f7e-4767-a35f-f7f1af822fea">

Either way, is not taking the number keyboardOptions type

Is there any way as today to pop up the keyboard by just focusing on iOS, thanks a lot

**Affected platforms**
- iOS
- Other

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 0.6.1
- OS version(s)* (required for Desktop and iOS issues):  16.2
- Compose version: 1.4.3
- JDK: 17

**Comment by mazunin-v-jb** [comment]
Hello! Thanks for submitting the issue.

I'll look into it, but for now could you please try to check on real device? 

That's usual problem with iOS simulators. If on device it will work fine, 90% chance that it is simulator problem.

**Comment by gastsail** [comment]
Thanks @mazunin-v-jb , I cannot compile the project from xCode, I wanted to know if I Can run the app from Android studio to my device. Is there any guide to execute the app on a real device? Thanks again

**Comment by mazunin-v-jb** [comment]
Yes, that's possible. 
The easiest way to run the app on a real iOS device.

1) Open Run configurations and select "Edit configurations"
<img width="444" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/124871594/8a86bd09-a1f2-48fd-9e50-5e932b0969ca">
2) Select your iOS target in the left panel:
<img width="341" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/124871594/9eefc7cc-bffe-400a-998e-a214e69900b4">
3) In the Execution target, select the real device (usually it is the first one)
<img width="737" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/124871594/a422761f-c319-4f07-8eb4-0b28ee4fb7e7">

After that, you need to open your Xcode xcworkspace project, and select the project (not Pods!) in the left panel. You should see something like this:
<img width="962" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/124871594/03878dab-5c25-4f57-9ca8-35b832ed3279">
Then you need to select your target, "Signing and Capabilities" and select an appropriate team. 

As soon as you select the team and there are no signing errors in the Xcode project, save the project, close Xcode and try to run app from Android Studio. It should work.

**Comment by gastsail** [comment]
Thanks @mazunin-v-jb  for bearing with me.

On Android I cannot see my device, I have enabled developer settings on my iOS phone and restarted it multiple times.

![Screen Shot 2023-08-18 at 19 56 02](https://github.com/JetBrains/compose-multiplatform/assets/24615408/989913f9-d526-4ac8-b308-76ab04b95d13)


On xCode I'm having these two errors 

![Screen Shot 2023-08-18 at 19 56 16](https://github.com/JetBrains/compose-multiplatform/assets/24615408/24b8b335-9da0-42d6-8343-fb63cf5e89e7)

For the second one I have theses settings


![Screen Shot 2023-08-18 at 19 57 25](https://github.com/JetBrains/compose-multiplatform/assets/24615408/2e5c425a-14cc-45ce-ac0e-a56791f9e4b0)

And I cannot see my phone working either

![Screen Shot 2023-08-18 at 19 56 24](https://github.com/JetBrains/compose-multiplatform/assets/24615408/3066488e-f089-48ff-ae59-a8934cb45947)


Little bit frustrating haha, since I'm an Android guy, this is the first time trying to touch some xCode IDE settings and trying to setup the project to run into my phone

**Comment by gastsail** [comment]
Ok, so for these errors I just did what the error said, just changing the bundle identifier

![Screen Shot 2023-08-18 at 20 00 29](https://github.com/JetBrains/compose-multiplatform/assets/24615408/1d1a52ff-0d6f-4ef9-8181-3c119e9cc581)

Now the issue is that my phone is not listed on Android Studio

**Comment by pablichjenkov** [comment]
One of those errors suggests updating xCode.

**Comment by gastsail** [comment]
hey, I'm downloading 15 beta 6 from xCode page, I think that could solve the problem, because 16.x OS are not supported with 14.2 stable version, will keep you up to date.

**Comment by gastsail** [comment]
Ok, so far so good, installed the new Mac OS Ventura, it let me install xCode 16 beta 6 which accepted my OS with 16.6

<img width="1129" alt="Screenshot 2023-08-18 at 21 29 03" src="https://github.com/JetBrains/compose-multiplatform/assets/24615408/fe6e3bc4-c5b8-41bf-b1ea-4852b0f9d675">


But the problem is that from xCode I cannot execute the app, now, if I go back to Android Studio, I can see that it installed OS 17 but my iPhone is not listed 

![Screenshot 2023-08-18 at 21 29 13](https://github.com/JetBrains/compose-multiplatform/assets/24615408/9771d9a9-4de5-4c9c-b8b7-6167c4e90359)

I tried closing and opening it again, but I think something has to do from where this is pulling the device info 🤔

**Comment by gastsail** [comment]
Ok, uninstalled previous xCode version and leaved the xCode-Beta one, now I do not see any emulator or even my device

![Screenshot 2023-08-18 at 21 43 19](https://github.com/JetBrains/compose-multiplatform/assets/24615408/7ab019b9-f3c6-498b-bb6c-392f08bc2f0b)

**Comment by pablichjenkov** [comment]
Try running it successfully from Xcode then do Android Studio. 
From the picture it seems the .xcframework hasn't been built yet. Try running  `pod install` then run the task that generated the framework. Or if you are not using cocoapods then the other assemble command.
Once everything works using Xcode you can then move to fix AS, imo.

**Comment by gastsail** [comment]
Which is the other command aside from the pod install ?

**Comment by pablichjenkov** [comment]
> Which is the other command aside from the pod install ?

`podPublishDebugXCFramework` or `podPublishXCFramework`

**Comment by gastsail** [comment]
Nice ! A simple pod install did the work , I runned the command on `iosApp` folder that contains the `PodFile`, now working on my iPhone, thanks a lot !

I can confirm that the keyboard is displayed on real device, will close this issue now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3530">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
