### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by andihasan97** [JetBrains/compose-multiplatform#3532]
where is documentation of navigation activity or fragment for desktop? is it the same as the library on android?

**Comment by mazunin-v-jb** [comment]
Compose for desktop doesn't have Activity.
Instead, please use SwingPanel (like ComposePanel).
There are no fragments as well.

In addition, for desktop related questions you may use [related channel in Slack](https://kotlinlang.slack.com/archives/C01D6HTPATV)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3532">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
