### ISSUE TITLE
build fail on ios

### ISSUE THREAD

**Issue by wangzhigang1112** [JetBrains/compose-multiplatform#3533]
**Describe the bug**

**Affected platforms**
Select one of the platforms below:
- iOS

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.9
- Compose Multiplatform version*: 1.4.3
- OS version(s)* (required for Desktop and iOS issues): MacOS ventura 13.4.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
build fail on ios, build error log:
link: [Log Detail](https://app.epoint.com.cn/hellodoc/#/publish/BCcjF8AF/4823)

**Comment by mazunin-v-jb** [comment]
Hello, thanks for submitting the issue.

I can't see anything bad in logs, except strange symbols in a root path. I can't say that it is a bug or it's just app.epoint.com.cn problem.
Could you make a small reproducer, please?

**Comment by gastsail** [comment]
Hi , did you started this project with [this template](https://github.com/JetBrains/compose-multiplatform-ios-android-template#readme)? or is a new project from scratch ?

**Comment by wangzhigang1112** [comment]
> Hello, thanks for submitting the issue.
> 
> I can't see anything bad in logs, except strange symbols in a root path. I can't say that it is a bug or it's just app.epoint.com.cn problem. Could you make a small reproducer, please?

Thank you for replying. Here's a different link. Please try it again, thank you. [ErrorLog](https://docs.qq.com/doc/DQVFQeFJIUU5CTUx0)

**Comment by mazunin-v-jb** [comment]
Thanks for providing info.
Could you try Gradle 7.4.2 please? It seems like Android Studio force updated your project version, and there may be a possible reason for that behavior.
You may need to change the version of AGP in Android Studio. `git reset --hard` in your project directory should reset the AGP version to the default one.

**Comment by wangzhigang1112** [comment]
> need to c

Running "git reset --hard" again to compile and run iOS still failed. [ErrorLog](https://docs.qq.com/doc/DQVFQeFJIUU5CTUx0)

**Comment by pablichjenkov** [comment]
What version of java you have installed?
Logs show bellow message. Just in case update java to 11 or 17 in your MAC
```
    - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
```

**Comment by wangzhigang1112** [comment]
> What version of java you have installed? Logs show bellow message. Just in case update java to 11 or 17 in your MAC
> 
> ```
>     - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
> ```

Thank you very much for your attention. The information you provided is very useful. It turns out that the issue is related to the version of Java installed locally, which is Java 1.8. Changing it to JAVA 17 solved the problem and the program can now run smoothly.

**Comment by wangzhigang1112** [comment]
> Hi @wangzhigang1112 , did you started this project with [this template](https://github.com/JetBrains/compose-multiplatform-ios-android-template#readme)? or is a new project from scratch ?
> 
> Can you provide more details on your build environment ?

Thank you for your interest. The issue has been resolved. It was related to the version of Java installed locally, which was Java 1.8. Changing it to JAVA 17 solved the problem and the program can now run smoothly.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3533">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
