### ISSUE TITLE
UIKitView issues

### ISSUE THREAD

**Issue by alexeiartsimovich** [JetBrains/compose-multiplatform#3534]
**Describe the bug**
`UIKitView` has rendering issues: when scrolling `LazyColumn`, the position of `UIKitView` is unstable.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.3
- OS version(s)* (required for Desktop and iOS issues): iOS 16.4
- OS architecture (x86 or arm64): x86_64

**To Reproduce**
[Here](https://gist.github.com/alexeiartsimovich/61488bb41eac4f5175abd146ad198500) is the code of the `VideoPlayer` component and [here](https://gist.github.com/alexeiartsimovich/e5cd92a4c2568431b7a32c64be8c6e66) is the code of the screen.
Steps and/or the code snippet to reproduce the behavior:
1. Wait for the videos to load.
2. Scroll down a little and then immediately up.
3. See how video goes out of the views bounds.

**Expected behavior**
`UIKitView` renders correctly `LazyColumn`.

**Videos**

https://github.com/JetBrains/compose-multiplatform/assets/61359788/e4f44b8d-d710-4f23-bfa8-3fcbc412a78e

**Comment by mazunin-v-jb** [comment]
Hello, thanks for submitting the issues.
[That's known problem](https://github.com/JetBrains/compose-multiplatform/issues/3525), we'll look into it.

I'll close this issue as duplicate. All works will be in earlier issues, please stay tuned, and feel free to reopen if you have any questions.

**Comment by elijah-semyonov** [comment]
Will be fixed in [this PR](https://github.com/JetBrains/compose-multiplatform-core/pull/773)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3534">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
