### ISSUE TITLE
jsApp configuration of all example projects fails

### ISSUE THREAD

**Issue by garretyoder** [JetBrains/compose-multiplatform#3542]
**Describe the bug**
For seemingly all of the example projects (I've tested falling-balls, minesweeper) the build fails due to failed dependency resolution. androidx.* and org.jetbrains.* cannot be resolved. Other targets build fine, and I cannot see anything wrong in the build file. 

**Affected platforms**

- All
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.4.3

**To Reproduce**
1. Download one of the example projects that has a web target
2. Attempt to build the web target (or even just open it in Android Studio/IntelliJ
3. Errors about unresolved imports will populate

**Expected behavior**
Import should work and project should run as it does on all other configurations

**Additional context**
I have made no modifications to the example project, only tried to build it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3542">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
