### ISSUE TITLE
method signature of fun rememberDatePickerState has changed - one new argument

### ISSUE THREAD

**Issue by skolson** [JetBrains/compose-multiplatform#3545]
Using:
Kotlin 1.9
Compose material3 MP 1.5.0-rc02
android compose material3 1.6.0-alpha03

With the above combination, defining an MP Composable using the DatePicker stuff builds fine, but fails at runtime with this exception:

`java.lang.NoSuchMethodError: No static method rememberDatePickerState`

After research, looks like Android Compose has added a 5th argument to function rememberDatePickerState, so now it has this signature (I'm unsure which release started this):
```
fun rememberDatePickerState(
    @Suppress("AutoBoxing") initialSelectedDateMillis: Long? = null,
    @Suppress("AutoBoxing") initialDisplayedMonthMillis: Long? = initialSelectedDateMillis,
    yearRange: IntRange = DatePickerDefaults.YearRange,
    initialDisplayMode: DisplayMode = DisplayMode.Picker,
    selectableDates: SelectableDates = object : SelectableDates {}
): DatePickerState
```

The MP signature for the same function does not have the `selectableDates` argument. So build works but runtime fails. The Gradle build seems to resolve with the android signature, not the MP signature.

For ongoing compatibility with android Compose, looks like the MP signature for this function needs an update. Here's the current MP signature for this function:

```
fun rememberDatePickerState(
    @Suppress("AutoBoxing") initialSelectedDateMillis: Long? = null,
    @Suppress("AutoBoxing") initialDisplayedMonthMillis: Long? = initialSelectedDateMillis,
    yearRange: IntRange = DatePickerDefaults.YearRange,
    initialDisplayMode: DisplayMode = DisplayMode.Picker
): DatePickerState
```

**Comment by alexzhirkevich** [comment]
`SelectableDates` was introduced in m3 [1.2.0-alpha-02](https://developer.android.com/jetpack/androidx/releases/compose-material3#1.2.0-alpha02). Compose multiplatform is currently based on m3 1.1.1

**Comment by skolson** [comment]
Sounds like Material 3 1.2.0 support is not targeted for CMP 1.5.0. Is there a target release of CMP planned yet for support of Material 3 1.2.0?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3545">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
