### ISSUE TITLE
Error with converting ByteArray to ImageBitmap in iOS

### ISSUE THREAD

**Issue by MohamedRejeb** [JetBrains/compose-multiplatform#3546]
**Description**
For some images the ByteArray conversion to ImageBitmap fails, I'm using the code below:
`Image.makeFromEncoded(this).toComposeImageBitmap() // 'this' is the ByteArray`

I'm receiving the following error message in xCode:
`IllegalArgumentException: Failed to Image::makeFromEncoded`

Here's the code that I'm using for converting NSDate to ByteArray:
```
@OptIn(ExperimentalForeignApi::class)
actual fun KmpFile.readByteArray(): ByteArray = ByteArray(this@readByteArray.length.toInt()).apply {
    usePinned {
        memcpy(it.addressOf(0), this@readByteArray.bytes, this@readByteArray.length)
    }
}
```

I tried it with the default 6 images available in the iOS simulator, and it works fine for five images, but it fails for one image.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-beta02
- OS version(s)*: Tested on iOS 16.4

**To Reproduce**
1. Open iOS file picker
2. Pick the first image
3. Convert NSData to ByteArray
4. Try to make a new image from the ByteArray

**Expected behavior**
The image should load like other images.

**Screenshots**
https://github.com/JetBrains/compose-multiplatform/assets/41842296/06ddc57b-052a-4a4d-a8ba-7fb3d175484d

**Comment by alexzhirkevich** [comment]
size of this image is greater than Int.MAX_VALUE, you cannot put it in ByteArray 🤷‍♂️

**Comment by MohamedRejeb** [comment]
That makes sense, I will try to resize the image before converting it to a ByteArray, thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3546">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
