### ISSUE TITLE
Selection container stops being selectable

### ISSUE THREAD

**Issue by tariq-g** [JetBrains/compose-multiplatform#3550]
Selection container stops being selectable when logs get too long and too big and too fat

    private fun getColor(priority: Int): Int {
        val color: Int = when (priority) {
            2 -> android.graphics.Color.rgb(0x00, 0x00, 0x00) //black
            3 -> android.graphics.Color.rgb(0x00, 0x70, 0xBB) //blue
            4 -> android.graphics.Color.rgb(0x48, 0xBB, 0x31) //green
            5 -> android.graphics.Color.rgb(0xBB, 0xBB, 0x23) //yellow
            7 -> android.graphics.Color.rgb(0xFF, 0x00, 0x06) //red
            else -> android.graphics.Color.rgb(0x00, 0x00, 0x00)
        }
        return color
    }

    @OptIn(ExperimentalMaterial3Api::class)
    @Composable
    fun LogComponent(log: List<LogData>) {
        val scrollState = rememberLazyListState()
        val coroutineScope = rememberCoroutineScope()

        SelectionContainer {
            Card(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(0.dp),

                shape = RoundedCornerShape(16.dp),
                elevation = CardDefaults.cardElevation(8.dp)
            ) {

                LazyColumn(
                    state = scrollState,
                    modifier = Modifier
                        .fillMaxSize()
                        .padding(16.dp)
                ) {
                    coroutineScope.launch {
                        scrollState.scrollToItem(log.size)
                    }
                    items(log) {
                        Text(
                            text = it.log,
                            color = Color(getColor(it.colorIndex))
                        )
                    }
                }
            }
        }
    }

    @Preview
    @Composable
    fun PreviewLogComponent() {
        val logs = mutableListOf<LogData>()

        // Add logs many many many logs and long long long logs
        logs.add(LogData("log data", 2))
        logs.add(LogData("log data", 2))
        logs.add(LogData("log data", 2))
        logs.add(LogData("log data", 2))
        logs.add(LogData("log data", 2))
        // ...

        LogComponent(log = logs)
    }

**Comment by Walingar** [comment]
Hello @tariq-g thank you for raising this issue! As I checked this issue is also reproducible for Android projects.
Does it reproduces there for you too? If so, can you please file an issue to the [android bug tracker](https://source.android.com/docs/setup/contribute/report-bugs)

Thank you

**Comment by sunny-chung** [comment]
Google made some fixes related to the issue.
https://issuetracker.google.com/issues/195049010

I would like to verify if it could fix the issue, but `SelectionContainer` with the argument `onSelectionChange` is an internal function in compose foundation desktop.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3550">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
