### ISSUE TITLE
when camera capture or closed, on the root screen will auto disappear.

### ISSUE THREAD

**Issue by NakiriYuuzu** [JetBrains/compose-multiplatform#3558]
**Describe the bug**
Hi, my problem is when camera capture or closed, on the root screen will auto disappear.

This is the Repository: https://github.com/NakiriYuuzu/DebugKmm

**Affected platforms**
Select one of the platforms below:
- iOS

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-rc01
- OS version(s)* (required for Desktop and iOS issues): 14.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**Screenshots**
https://drive.google.com/file/d/1Wo_nmCDCGiZnXYVHsZBfkckDIT7UGO5r/view?usp=sharing

**Additional context**
when the compose version at 1.4.0 is working fine.

**Comment by elijah-semyonov** [comment]
[ComposeScene is now destroyed when UIViewController disappears from the screen.](https://github.com/JetBrains/compose-multiplatform-core/pull/747).

In your case, you can restructure the code to keep your `rememberNavigator` outside of `setContent`.

**Comment by NakiriYuuzu** [comment]
> [ComposeScene is now destroyed when UIViewController disappears from the screen.](https://github.com/JetBrains/compose-multiplatform-core/pull/747).
> 
> In your case, you can restructure the code to keep your `rememberNavigator` outside of `setContent`.

thank you, I finally fix my problem, but how to avoid compose recreate the screen? When I take a photo and get the respond, but no showing in UI.

**Comment by elijah-semyonov** [comment]
You can't avoid it as of now. Regarding the image loss, I don't see hard blocks for working around this problem.
Ask in [Kotlin slack community](kotlinlang.slack.com), perhaps somebody already did something similar and knows the solution.

**Comment by NakiriYuuzu** [comment]
> You can't avoid it as of now (we are not sure about if we want to bring UIViewController-lifetime bound behavior due to many problems it brings for Compose). Regarding the image loss, I don't see hard blocks for working around this problem. Ask in [Kotlin slack community](kotlinlang.slack.com), perhaps somebody already did something similar and knows the solution.

Thank you.

**Comment by elijah-semyonov** [comment]
Sorry, the link was broken, fixed it now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3558">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
