### ISSUE TITLE
codeviewer. text isn't fully selectable after scrolling

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3560]
Compose 1.5.0-rc04, [codeviewer](https://github.com/JetBrains/compose-multiplatform/tree/support/1.5.0/examples/codeviewer) example, Windows 11

Doesn't happen with 1.4.3

1. Run codeviewer
2. Open a medium size file (that can be scrolled)
3. Scroll to some position
4. Try to select text

Actual:
text isn't selected

Expected:
text is selected

https://github.com/JetBrains/compose-multiplatform/assets/5963351/0f809f07-78f4-4d90-96fa-cf4ca6c44ca9

**Comment by eymar** [comment]
same issue on android

**Comment by igordmn** [comment]
> same issue on android

Is it with touch, or mouse?

**Comment by eymar** [comment]
> Is it with touch, or mouse?
tested with touch only for now

**Comment by igordmn** [comment]
Fixed in 1.5.0-rc05
