### ISSUE TITLE
iOS Decimal Keyboard is different on device and emulator

### ISSUE THREAD

**Issue by gastsail** [JetBrains/compose-multiplatform#3562]
**Describe the bug**
I have a TextField that has a KeyboardType as Decimal 

```
keyboardOptions = KeyboardOptions.Default.copy(
                    keyboardType = KeyboardType.Decimal,
                    imeAction = ImeAction.Done
                )

```

Now, on iOS 17 iPhone 14 pro I get the dot (expected)

![Simulator Screenshot - iPhone 14 Pro - 2023-08-24 at 12 00 40](https://github.com/JetBrains/compose-multiplatform/assets/24615408/85f500fa-b42f-4b46-964b-05d25a31f0bd)

But when Using the same app on real iOS device I get a comma

![pic](https://github.com/JetBrains/compose-multiplatform/assets/24615408/136dd2fd-ea23-4652-923d-b5fc7724b3f9)

In the real device when I place the comma, in my main screen the number 10.5 is added as 105.0 , if I use the emulator and use the dot, the 10.5 is visualized and added as 10.5 as it should.

Real device OS is 16.6 and emulator OS is 17

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*:  1.9.0
- Compose Multiplatform version*:  1.5.0-beta02
- OS version(s)* (required for Desktop and iOS issues): 16.6
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 17

**Comment by mazunin-v-jb** [comment]
Hello!
This behavior is set on the iOS side, we don't do any separate decimal keyboard logic for different devices.
Usually, it depends on device region.
As far as I remember, specifically it is Number Format setting. 
I guess, on of your device has comma to separate fractional part and the other has dot.

If I'm wrong in my assumption, could you please attach screenshots of both your devices Language & Region settings? This would be helpful for us to understand the problem better.

**Comment by gastsail** [comment]
Hey @mazunin-v-jb yes, I was able to reproduce it only on Spanish and in Argentina region, changed that to United States and English and I can see the dot properly

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3562">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
