### ISSUE TITLE
Commonize insets Modifier's (additionally to WindowInsets.*)

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3563]
Compose 1.5.0-rc04

WindowInsets.* are already commonized, but there are modifiers in Compose that are still Android-only (see [WindowInsetsPadding.android.kt](https://github.com/JetBrains/compose-multiplatform-core/blob/44dbd3b3623f29571dab34ecd4116461d75725e6/compose/foundation/foundation-layout/src/androidMain/kotlin/androidx/compose/foundation/layout/WindowInsetsPadding.android.kt#L40)):
```
Modifier.safeDrawingPadding()
...
Modifier.displayCutoutPadding()
```
It seems they can be easily commonized. Also, they mentioned in [the docs](https://developer.android.com/jetpack/compose/layouts/insets#compose-apis)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3563">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
