### ISSUE TITLE
iOS: LazyColumn Bug

### ISSUE THREAD

**Issue by Caij** [JetBrains/compose-multiplatform#3565]
**Describe the bug**
iOS LazyColumn:
When there are two items of content within the list, if any item's content is not completely displayed on the screen, clicking its content will result in an automatic scrolling of the list to fully show its content.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*:  1.9.0
- Compose Multiplatform version*:  1.4.3
- OS version(s)* (required for Desktop and iOS issues):  iOS Iphone 12 Pro 16.4

**code**
[https://github.com/Caij/compose-multiplatform-template-bugreport](https://github.com/Caij/compose-multiplatform-template-bugreport)
```
val items = ArrayList<String>()
        items.add("1")
        items.add("1")
        items.add("1")
        items.add("1")
        LazyColumn {
            itemsIndexed(items) { index, item ->
                Text(text = "1\n2\n3\n4\n1\n" +
                        "2\n" +
                        "3\n" +
                        "4\n1\n" +
                        "2\n" +
                        "3\n" +
                        "4\n1\n" +
                        "2\n" +
                        "3\n" +
                        "4\n1\n" +
                        "2\n" +
                        "3\n" +
                        "3\n" +
                        "4\n1\n" +
                        "2\n" +
                        "3\n" +
                        "4\n\n\n\n\n",
                    modifier = Modifier.fillMaxWidth().clickable {

                    })
            }
        }
```

https://github.com/JetBrains/compose-multiplatform/assets/8597839/fbf43967-5854-4264-a27c-6f0d49559213

**Comment by m-sasha** [comment]
This is the expected behavior for Modifier.clickable items.

**Comment by Caij** [comment]
@m-sasha Why does it work fine on Android

**Comment by m-sasha** [comment]
See this issue for more details and a workaround: https://github.com/JetBrains/compose-multiplatform/issues/3132

**Comment by Caij** [comment]
@m-sasha  The first click will still trigger automatic scrolling, but the second click will not.
```
val items = ArrayList<String>()
        items.add("1")
        items.add("1")
        items.add("1")
        items.add("1")
        LazyColumn {
            itemsIndexed(items) { index, item ->
                Text(text = "1\n2\n3\n4\n1\n" +
                        "2\n" +
                        "3\n" +
                        "4\n1\n" +
                        "2\n" +
                        "3\n" +
                        "4\n1\n" +
                        "2\n" +
                        "3\n" +
                        "4\n1\n" +
                        "2\n" +
                        "3\n" +
                        "3\n" +
                        "4\n1\n" +
                        "2\n" +
                        "3\n" +
                        "4\n\n\n\n\n",
                    modifier = Modifier.fillMaxWidth().clickable {

                    }.focusProperties {
                        canFocus = false
                    })
            }
        }
```

**Comment by Caij** [comment]
thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3565">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
