### ISSUE TITLE
MultiWidgetSelectionDelegate. replace @Synchronized to SynchronizedObject

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3568]
Compose 1.5.0-rc04

<img width="471" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5963351/3b1884ee-11d0-416c-9c50-abf04144a830">

@Synchronized doesn't work for native/web

**Comment by igordmn** [comment]
Duplicate https://github.com/JetBrains/compose-multiplatform/issues/3363

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3568">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
