### ISSUE TITLE
Support Kotlin 1.9.10

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3570]
It is already supported with Compose Compiler 1.5.2-beta01:
```
compose {
    kotlinCompilerPlugin.set("1.5.2-beta01")
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3570">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
