### ISSUE TITLE
CompositionLocals given in application scope are not take into account in window scope (such as LocalLayoutDirection)

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#3571]
**Describe the bug**
All `Arrangement.Absolute.spacedBy()` overloads refer to `Arrangement.spacedBy()` in their documentation for the direction-aware alternative.

But the `Arrangement.spacedBy()` does not honor RTL layout direction.

**Affected platforms**
- Desktop
- and probably others

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-rc01
- OS version(s)*: Windows 10, Windows 11
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): Oracle JDK 17.0.7

**To Reproduce**
```kotlin
// ...
import androidx.compose.foundation.layout.Arrangement.spacedBy

fun main() {
    application {
        CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl) {
            Window(onCloseRequest = ::exitApplication) {
                Row(horizontalArrangement = spacedBy(24.dp)) {
                    Box(modifier = Modifier.size(64.dp).background(Color.Red))
                    Box(modifier = Modifier.size(64.dp).background(Color.Green))
                }
            }
        }
    }
}
```

**Expected behavior**
When layout direction is RTL, the components should be placed in reverse order (green box should be on the left).

![Untitled](https://github.com/JetBrains/compose-multiplatform/assets/29678011/a0939306-78f6-4ccb-94d6-a6b48fbb624e)

**Comment by mahozad** [comment]
When I moved `CompositionLocalProvider` into `Window` content, it works correctly:

```kotlin
fun main() {
    application {
        Window(onCloseRequest = ::exitApplication) {
            CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl) {
                Row(horizontalArrangement = spacedBy(24.dp)) {
                    Box(modifier = Modifier.size(64.dp).background(Color.Red))
                    Box(modifier = Modifier.size(64.dp).background(Color.Green))
                }
            }
        }
    }
}
```

So, it should be the same problem as this:
  - https://github.com/JetBrains/compose-multiplatform/issues/3382

**Comment by Walingar** [comment]
Hello @mahozad, thank you for submitting the issue. 
This is related to this issue: https://github.com/JetBrains/compose-multiplatform/issues/3289. See the [comment](https://github.com/JetBrains/compose-multiplatform/issues/3289#issuecomment-1606883805)

For now we provide CompositionLocals in Window scope and given LayoutDirection is overriden by default values

**Comment by mahozad** [comment]
Thanks for the relevant information.

**Comment by m-sasha** [comment]
Fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/777

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3571">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
