### ISSUE TITLE
new root package name

### ISSUE THREAD

**Issue by pynixwang** [JetBrains/compose-multiplatform#3573]
now root package is `androidx`

any plan to change it. for example `com.jb`

when I develop a desktop app, `androidx` is not good. because compose is `multiplatform`

**Comment by Walingar** [comment]
Hello @pynixwang thank you for the request! 
For now, we don't have such plans especially for the common part, since multiplatform part should be compatible with Jetpack Compose's (for Android) and it uses androidx packages

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3573">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
