### ISSUE TITLE
[Compose-iOS] - The isSystemInDarkTheme() flag does not set dark theme on iOS

### ISSUE THREAD

**Issue by priyanshuhere** [JetBrains/compose-multiplatform#3575]
**Describe the bug**
When using the isSystemInDarkTheme() flag, the theme colors don't change on iOS based on the system appearance.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-rc06 (using material3)
- OS version(s)* (required for Desktop and iOS issues):  iOS 16.2 (Simulator Device)
- OS architecture (x86 or arm64): x86 Architecture

**To Reproduce**
Here's a minimal reproducible [project](https://github.com/JetBrains/compose-multiplatform/files/12450585/TestApp.zip) based on the compose-multiplatform-ios template.

The theme file is structured as follows:

The commonMain directory has an expect fun declaration for the theme. Here, the useDarkTheme variable is set to isSystemInDarkTheme() flag.
```
@Composable
expect fun AppTheme(
    useDarkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit
)
```
And here's the iosMain actual implementation of the theme:
```
@Composable
actual fun AppTheme(
    useDarkTheme: Boolean,
    content: @Composable () -> Unit
) {
    val colors = when {
        useDarkTheme -> DarkColors
        else -> LightColors
    }
    MaterialTheme(
        colorScheme = colors,
        content = content
    )
}

```

I am aware that the app does not change theme during run time but I also face this issue after removing the app from recents, changing the theme and relaunching the app.

**Expected behavior**
The app theme on iOS should follow system appearance when using the isSystemInDarkTheme() flag.

**Screenshots**
iOS App with Dark Theme enabled

![image](https://github.com/JetBrains/compose-multiplatform/assets/42600072/a06f36ea-1deb-4efb-9ce2-1c348892ab01)

Android App with Dark Theme enabled

![image](https://github.com/JetBrains/compose-multiplatform/assets/42600072/bcb9411d-15fb-4d12-a927-5f397efd51e1)

**Comment by dima-avdeev-jb** [comment]
Thanks! Yes, it happends because of this line of code in SwiftUI:
```
.preferredColorScheme(.light)
```

https://github.com/dima-avdeev-jb/check-issues-3575/blob/60753355f27810ce3b686650fb2f80d6f0c73939/iosApp/iosApp/iOSApp.swift#L10

You should remove it. Also, we will change our templates soon

**Comment by priyanshuhere** [comment]
Thanks. Should have checked the Swift file as well 😅.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3575">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
