### ISSUE TITLE
the content of the site is not visible or does not work. (compose web)

### ISSUE THREAD

**Issue by dQqAn** [JetBrains/compose-multiplatform#3578]
**Describe the bug**
I opened a new project for Compose web and I can't see the content of the website at all. But in a different project, for example, when I open [this](https://github.com/JetBrains/compose-multiplatform/tree/master/examples/chat), I can view it without any problems. I checked the gradle files of that project, everything is the same, but I can't display any content on my own project's site. What can I do?
The picture below is from the chat example...

**Affected platforms**
Select one of the platforms below:
- Web 

**Versions**
- Kotlin version*: 1.8.22
- Compose Multiplatform version*:  1.4.3 
- JDK (for desktop issues): 17

**To Reproduce**
 My [project ](https://github.com/dQqAn/testWeb).
  
**Screenshots**

### **The picture below is from the chat example...** 

![image](https://github.com/JetBrains/compose-multiplatform/assets/48219880/ac2377d4-f5f9-4f9b-aed2-8841e900d063)

**Comment by dQqAn** [comment]
i found the problem, sorry....

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3578">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
