### ISSUE TITLE
onDoubleClick doesn't work as expected (delay is between mouseUp's, not mouseDown's)

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#358]
Compose 0.3.0-build150

Example:

```
import androidx.compose.desktop.Window
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.size
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

@OptIn(ExperimentalFoundationApi::class)
fun main() = Window {
    Box(
        Modifier
            .size(200.dp)
            .background(Color.Red)
            .combinedClickable(
                onClick = { },
                onDoubleClick = {
                    println("onDoubleClick")
                }
            )
    )
}
```

Actual:
Mouse down -> wait 2 seconds -> Mouse up -> Mouse down -> wait 2 seconds -> double click

Expected:
Mouse down -> wait 2 seconds -> Mouse up -> Mouse down -> wait 2 seconds -> no double click
Mouse down -> Mouse up -> wait 200 milliseconds -> Mouse down -> double click
Mouse down -> wait 200 milliseconds -> Mouse up -> Mouse down -> double click

**Comment by JetpackDuba** [comment]
I've noticed this problem too (v1.1.1). Issue aside, I was wondering if the value should be really 200 ms hardcoded or read the system configuration. If I'm not mistaken Windows has some config about this, not sure about other OS.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6077">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
