### ISSUE TITLE
Global exception handler for application or window

### ISSUE THREAD

**Issue by EzzPress** [JetBrains/compose-multiplatform#3580]
To get a feedback (crash report) from client apps is there any possible way to catch exceptions while composing? For example if some screen crashes because of unexpected logic or due to freezing.

**Comment by Walingar** [comment]
Hello @EzzPress, thank you for your question. There are 2 ways right now (both are experimental and may be changed in the future), you can:
* Provide `ComposeDialog#exceptionHandler` that allows to handle all exception in your way.
* And there is an experimental `LocalWindowExceptionHandlerFactory` that allows to handle exceptions with window inside the callback.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3580">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
