### ISSUE TITLE
Camera support for desktop

### ISSUE THREAD

**Issue by codaman** [JetBrains/compose-multiplatform#3581]
I searched but couldn't find a built-in camera for desktop. And can run in all os (macOs,Windows,Linux)

**Comment by m-sasha** [comment]
This is probably out of scope for Compose. Definitely not planned anytime soon.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3581">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
