### ISSUE TITLE
LocalUriHandler does not work on Linux

### ISSUE THREAD

**Issue by Nohus** [JetBrains/compose-multiplatform#3583]
**Describe the bug**
`UriHandler` from `LocalUriHandler` fails to open URLs on Linux (or KDE).

**Affected platforms**
- Desktop

**Versions**
- Kotlin version: 1.9.0
- Compose Multiplatform version: 1.4.3
- OS version: Kubuntu 23.04
- OS architecture: x86_64
- JDK: openjdk-17

**To Reproduce**
```Kotlin
val uriHandler = LocalUriHandler.current
TextButton(onClick = { uriHandler.openUri("https://www.jetbrains.com") }) {
    Text("Open URL")
}
```

**Expected behavior**
https://www.jetbrains.com opens in the default web browser. Instead the app crashes.

**Screenshots**
![Error Dialog](https://github.com/JetBrains/compose-multiplatform/assets/11064768/63061a00-1993-469a-b4ab-caa42661dcb4)

**Additional context**
This is because `java.awt.Desktop.browse` throws `UnsupportedOperationException`.

The AWT Desktop class correctly reports the action will fail if checked:
```Kotlin
val desktop = Desktop.getDesktop()
desktop.isSupported(Desktop.Action.BROWSE) // false
```

The function `internal actual fun URIHandler_openUri(uri: String)` in `org.jetbrains.skiko.Actuals.awt.kt` is currently:
```Kotlin
Desktop.getDesktop().browse(URI(uri))
```

A solution could be to change it to:

```Kotlin
val desktop = Desktop.getDesktop()
if (desktop.isSupported(Desktop.Action.BROWSE)) {
    desktop.browse(URI(uri))
} else {
    Runtime.getRuntime().exec("xdg-open $uri")
}
```

**Comment by m-sasha** [comment]
Thanks for the suggestion, we'll consider it. In the meanwhile, you can wrap the code you suggested into your own provided `UriHandler` like so: 
```
object BetterUriHandler: UriHandler {
    override fun openUri(uri: String) {
        val desktop = Desktop.getDesktop()
        if (desktop.isSupported(Desktop.Action.BROWSE)) {
            desktop.browse(URI(uri))
        } else {
            Runtime.getRuntime().exec("xdg-open $uri")
        }
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        CompositionLocalProvider(LocalUriHandler provides BetterUriHandler){
            ...
        }
    }
}

```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3583">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
