### ISSUE TITLE
ComposeUiViewController forces a white background

### ISSUE THREAD

**Issue by chrisbanes** [JetBrains/compose-multiplatform#3584]
The rootView used by the `ComposeUiViewController` is set to `UIColor.whiteColor` ([here](https://github.com/JetBrains/compose-multiplatform-core/blob/40e76ce83f97147ce441667936039cc31f867618/compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/window/ComposeWindow.uikit.kt#L253)). This is usually not usually an issue as it only happens when the `ComposeUiViewController` and is then drawn over as soon as a composition + draw happens.

I'm working on a project though where we are using `ComposeUiViewController`s in select parts of the app, therefore we pop on/off `ComposeUiViewController` fairly frequently. The app is dark themed, meaning that we see a brief flash of white before the content of each `ComposeUiViewController` is drawn.

Is there a reason why white is used? Can me make this configurable or maybe transparent?

**Comment by elijah-semyonov** [comment]
It's already [fixed](https://github.com/JetBrains/compose-multiplatform/issues/3492) and will be deployed in next version.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3584">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by quochungnguyen97** [comment]
Dear @elijah-semyonov

Now I still face this problem when navigating, could you explain more details that it's already fixed or I can do any workaround?

You said that: "you can already do that from within `setContent`\". So what does `setContent` mean?

In Android I can fix with setting window background color but in iOS I don't know how. I tried `uiViewController.view.backgroundColor = UIColor(named: "BackgroundColor")` in `func updateUIViewController` but it doesn't work.

https://github.com/user-attachments/assets/baa277bf-ad4b-40a5-9cf4-382d723693b6
