### ISSUE TITLE
packageDmg fails

### ISSUE THREAD

**Issue by hyvenzhu** [JetBrains/compose-multiplatform#3586]
java.io.IOException: Command [/usr/bin/codesign, --remove-signature, /xxx/libskiko-macos-x64.dylib] exited with 1 code

**Comment by m-sasha** [comment]
Are there any other errors? Can you upload a project reproducing this to github?

**Comment by hyvenzhu** [comment]
What went wrong:
Execution failed for task ':createDistributable'.
> External tool execution failed:
  * Command: [/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/jpackage, @/Users/zhuhf/Desktop/IPGTimeStatsDesktop/build/compose/tmp/createDistributable.args.txt]
  * Working dir: []
  * Exit code: 1
  * Standard output log: /Users/zhuhf/Desktop/IPGTimeStatsDesktop/build/compose/logs/createDistributable/jpackage-2023-08-30-10-51-51-out.txt
  * Error log: /Users/zhuhf/Desktop/IPGTimeStatsDesktop/build/compose/logs/createDistributable/jpackage-2023-08-30-10-51-51-err.txt

----------------------------------------
jpackage-2023-08-30-10-51-51-err.txt：

java.io.IOException: Command [/usr/bin/codesign, --remove-signature, /Users/zhuhf/Desktop/IPGTimeStatsDesktop/build/compose/binaries/main/app/IPGTimeStats.app/Contents/app/libskiko-macos-x64.dylib] exited with 1 code

**Comment by hyvenzhu** [comment]
> Are there any other errors? Can you upload a project reproducing this to github?

What went wrong:
Execution failed for task ':createDistributable'.

External tool execution failed:

Command: [/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/jpackage, @/Users/zhuhf/Desktop/IPGTimeStatsDesktop/build/compose/tmp/createDistributable.args.txt]
Working dir: []
Exit code: 1
Standard output log: /Users/zhuhf/Desktop/IPGTimeStatsDesktop/build/compose/logs/createDistributable/jpackage-2023-08-30-10-51-51-out.txt
Error log: /Users/zhuhf/Desktop/IPGTimeStatsDesktop/build/compose/logs/createDistributable/jpackage-2023-08-30-10-51-51-err.txt
jpackage-2023-08-30-10-51-51-err.txt：

java.io.IOException: Command [/usr/bin/codesign, --remove-signature, /Users/zhuhf/Desktop/IPGTimeStatsDesktop/build/compose/binaries/main/app/IPGTimeStats.app/Contents/app/libskiko-macos-x64.dylib] exited with 1 code

**Comment by m-sasha** [comment]
Please see [this issue](https://github.com/JetBrains/compose-multiplatform/issues/1666).
Does it work with JDK 18?

**Comment by hyvenzhu** [comment]
> Please see [this issue](https://github.com/JetBrains/compose-multiplatform/issues/1666). Does it work with JDK 18?

Downgrading to Java 16 fixed this for me.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3586">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
