### ISSUE TITLE
Desktop test API doesn't fully integrate with child scenes in Window/DialogWindow

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#3587]
**Describe the bug**
The test API allows one to create `Window` and `DialogWindow`, and even obtain nodes in them, but because rendering in them is driven by a regular `ComposeScene`, the test has no control over that. For example, this:

```
    @Test
    fun obtainingSemanticsNodeInteractionInChildSceneWaitsUntilIdle() {
        var text by mutableStateOf("1")

        rule.setContent {
            // Window creates a child scene in ComposeScene
            Window(onCloseRequest = {}) {
                Text(text, modifier = Modifier.testTag("text"))
            }
        }

        rule.onNodeWithTag("text").assertTextEquals("1")
        text = "2"
        rule.onNodeWithTag("text").assertTextEquals("2")
    }
```
will fail because the test will not wait for the child scene to become idle before asserting the text value in the last line.

**Affected platforms**
- Desktop

**Comment by m-sasha** [comment]
@igordmn suggested that we should create "virtual" windows in `Window` and `DialogWindow` by passing a `WindowFactory` via a `Local` and delegating the creation of the window/dialog to it.

`SkikoComposeUiTest` can then pass its own implementation of a `WindowFactory` and create virtual windows with `ComposeScene` instances that it has control over.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3587">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
