### ISSUE TITLE
Today's date is not highlighted with a circle in the material3 datePicker on iOS.

### ISSUE THREAD

**Issue by topmotree** [JetBrains/compose-multiplatform#3591]
**Describe the bug**
Today should be in the circle, like on the Android

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0

**To Reproduce**
Create DatePicker element and everything will be clear.

**Expected behavior**
Today should be in a circle, like on Android

**Screenshots**
![Screenshot 2023-08-30 at 16 35 10](https://github.com/JetBrains/compose-multiplatform/assets/64073182/5aa9d8fa-5ad4-43d2-9ffb-f31f51cfa7f7)
![Screenshot 2023-08-30 at 16 35 22](https://github.com/JetBrains/compose-multiplatform/assets/64073182/87c989e3-d175-45de-9bc3-5cbbffab6eac)

On android everything is fine on iOS - 30.08 is not in the circle.

**Comment by m-sasha** [comment]
Can you post your code? I'm a bit confused as `DatePicker` is only available since material3 1.2.0-alpha06 but Compose 1.5.0 is based on material3 1.1.1

**Comment by m-sasha** [comment]
Never mind, it seems there's an error at Google's docs: https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#DatePicker(androidx.compose.material3.DatePickerState,androidx.compose.ui.Modifier,androidx.compose.material3.DatePickerFormatter,kotlin.Function0,kotlin.Function0,kotlin.Boolean,androidx.compose.material3.DatePickerColors)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3591">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
