### ISSUE TITLE
DLL files in Windows installer or distributable can be shrunk by over 20 MB

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#3593]
Using [UPX tool](https://github.com/upx/upx), size of `skiko-windows-x64.dll` file (generated in `<APP_DIRECTORY>/app/`) can be reduced from 16.2 MB to 5.2 MB.  
A reduction of about 11 MB which is a large amount in my opinion.

I also executed UPX on the Java DLL files (in `<APP_DIRECTORY>/runtime/`) and the total size reduced from about 61 MB to about 51 MB (for JDK 17). So, overall, the app uncompressed size reduced by about 21 MB.

The tool says it can be used for Linux and macOS executables as well.

Please consider including running UPX in the Gradle tasks that generate the installer or distribution.

[UPX promises its results to run exactly as before](https://github.com/upx/upx#:~:text=Programs%20and%20libraries%20compressed%20by%20UPX%20are%20completely%20self%2Dcontained%0Aand%20run%20exactly%20as%20before%2C%20with%20no%20runtime%20or%20memory%20penalty%20for%20most%0Aof%20the%20supported%20formats), but if you think this might introduce subtle or hard-to-detect bugs, please provide an option in `compose.desktop { // ...` block for the programmer to be able to enable/disable this feature.

**Comment by m-sasha** [comment]
@igordmn @AlexeyTsvetkov What do you think? I don't know if we can use a 3rd party library in our distribution-building, but maybe we can mention it as an option in the tutorial.

**Comment by igordmn** [comment]
Before mentioning/supporting UPX, we should investigate advantages/disadvantages of it. Unpacking the compressed skiko binary in runtime theoretically can slow down the startup.

As for using 3rd party tools - it is possible to integrate them into the Compose Plugin, if the license allows it, the tool is stable and it won't cause much burden for supporting it.

**Comment by apolostudio** [comment]
@mahozad Have you encountered critical issues when using it? I want to reduce an app's size and im looking for even the smallest optimization. Thanks!

**Comment by mahozad** [comment]
So far, no issue for the app that I'm aware of.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3593">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
