### ISSUE TITLE
The warning about explicit cacheKind=none is not shown on configuration cache hit

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [JetBrains/compose-multiplatform#3595]
## To Reproduce

1. Open any Compose Multiplatform template (https://github.com/JetBrains/compose-multiplatform-ios-android-template).
2. Run `./gradlew --configuration-cache -Pkotlin.native.cacheKind=none`.
3. Once again, run `./gradlew --configuration-cache -Pkotlin.native.cacheKind=none`.

## Expected behavior

Both times, the following warning is printed:
```
Warning: 'kotlin.native.cacheKind' is explicitly set to 'none'.
Compose Multiplatform Gradle plugin manages this property automatically based on a Kotlin compiler version being used.
In future versions of Compose Multiplatform this warning will become an error.
  * Recommended action: remove explicit 'kotlin.native.cacheKind=none' from gradle.properties. 
  * Alternative action: disable cache kind management by adding 'compose.kotlin.native.manageCacheKind=false' to your 'gradle.properties'.
```

## Actual behavior

The warning is printed on the step 2, but it is not printed on the step 3.

The same problem happens with the warning, which should be printed, when androidx compose compiler is used with non-JVM targets.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3595">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
