### ISSUE TITLE
Based on the next Jetpack Compose libraries ...?

### ISSUE THREAD

**Issue by wakaztahir** [JetBrains/compose-multiplatform#3601]
Compose 1.5 doesn't have 

"This version of Compose Multiplatform is based on the next Jetpack Compose libraries:" like previous version had

I previously had

compose.jb.version=1.4.0
compose_compiler_version=1.4.4
compose_runtime_version=1.4.0
compose_ui_version=1.4.0
compose_foundation_version=1.4.0
compose_material2_version=1.4.0
compose_material3_version=1.0.1

How would I go about updating this...

**Comment by 456634** [comment]
### [1.5.0](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0)
> This is a combined changelog from the prerelease versions:
[1.5.0-beta01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0-beta01)
[1.5.0-beta02](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0-beta02)



### [1.5.0-beta02](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0-beta02)
> This version of Compose Multiplatform is based on the next Jetpack Compose libraries:
Compiler 1.5.0](https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.5.0)
[Runtime 1.5.0](https://developer.android.com/jetpack/androidx/releases/compose-runtime#1.5.0)
[UI 1.5.0](https://developer.android.com/jetpack/androidx/releases/compose-ui#1.5.0)
[Foundation 1.5.0](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.5.0)
[Material 1.5.0](https://developer.android.com/jetpack/androidx/releases/compose-material#1.5.0)
[Material3 1.1.1](https://developer.android.com/jetpack/androidx/releases/compose-material3#1.1.1)

**Comment by m-sasha** [comment]
Also note that you don't have to specify all these individually. See the templates for:
- [Android+iOS](https://github.com/JetBrains/compose-multiplatform-ios-android-template)
- [Desktop](https://github.com/JetBrains/compose-multiplatform-desktop-template)
- [Web](https://github.com/Kotlin/kotlin-wasm-examples/tree/main/compose-imageviewer#compose-multiplatform-for-web)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3601">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
