### ISSUE TITLE
Compose Multiplatform Navigation

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#3610]
Hi
I use [PreCompose](https://github.com/Tlaster/PreCompose) For Navigation, it look like to Jetpack compose navigation and also it has viewmodel and koin inject for viewmodel.
this library is simple and amazing and i think if you support it, It can be used instead of [Decompose](https://github.com/arkivanov/Decompose)
Thank you.

**Comment by m-sasha** [comment]
Thanks for the suggestion. I believe there are some plans in the works to support navigation (nothing definite yet, though).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3610">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
