### ISSUE TITLE
Compose HTML: Add Wbr

### ISSUE THREAD

**Issue by Queatz** [JetBrains/compose-multiplatform#3612]
Add `Wbr` to support Line Break Opportunities

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr

**Comment by m-sasha** [comment]
Thank you for the suggestion.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3612">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
