### ISSUE TITLE
Compose Desk pkg to DMG, Function not working

### ISSUE THREAD

**Issue by Taoaozw** [JetBrains/compose-multiplatform#3614]
**Describe the bug**
use  gradle run and `/Applications/<PACKAGE_NAME>.app/Contents/MacOS/<PACKAGE_NAME>` activate that application, when i click a  button get web request and work well.  but if i use application folder app，He's not responding, and i cant get any effective information when i click button , Is it a permission issue?

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): macOS 13.5.1 (22G90) 
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 20

**To Reproduce**

**Expected behavior**
click button will  get result

**Comment by Taoaozw** [comment]
i find write some log in system dir, so it crashed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3614">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
