### ISSUE TITLE
No matching toolchains found

### ISSUE THREAD

**Issue by younas-bangash** [JetBrains/compose-multiplatform#3615]
**Describe the bug**

    Could not create task ':androidApp:compileDebugJavaWithJavac'.
    Could not create task ':shared:compileDebugJavaWithJavac'.
    Could not create task ':androidApp:compileDebugJavaWithJavac'.
    Failed to calculate the value of task ':androidApp:compileDebugJavaWithJavac' property 'javaCompiler'.
    No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}  for MAC_OS on x86_64.
    No locally installed toolchains match and toolchain download repositories have not been configured.

**Affected platforms**

- iOS
- Android

**Versions**
- Android Studio Giraffe | 2022.3.1 Patch 1
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5

**To Reproduce**
1. Just use the template form https://github.com/JetBrains/compose-multiplatform-template#readme

**Comment by ykong1337** [comment]
![image](https://github.com/JetBrains/compose-multiplatform/assets/66518156/9c853e83-134e-4dfe-936c-cf7ac2d4bfb2)
try download a jdk11?

**Comment by m-sasha** [comment]
@younas-bangash What version of JDK do you have installed?

**Comment by igordmn** [comment]
This is a regression after we added `jvmToolchain(11)` into [the template](https://github.com/JetBrains/compose-multiplatform-ios-android-template/blob/b3cca0be20dba514cfd911ae3313a02d46458c90/shared/build.gradle.kts#L66C9-L66C9). I reproduced it on a my machine.

After this, there should be Java 11 installed in the system (not sure how Gradle determines that).

As we shouldn't require specific Java to be installed (we require only minimal version), we should either remove `jvmToolchain(11)`, or add toolchain repositories via [org.gradle.toolchains.foojay-resolver-convention](https://docs.gradle.org/current/userguide/toolchains.html#sub:download_repositories).

**Comment by igordmn** [comment]
As a temporary workaround, install JDK 11 to `/Library/Java/JavaVirtualMachines` (for example, [Amazon Corretto](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/macos-install.html))

**Comment by younas-bangash** [comment]
@m-sasha After installing the JDK 11 it fix the problem I think it will be great either we remove the jvmToolchain(11) or either add the or add toolchain repositories as the solution suggested by @igordmn

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3615">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
