### ISSUE TITLE
Unknown iOS platform: 'macosx' - Compose 1.5

### ISSUE THREAD

**Issue by EBfVince** [JetBrains/compose-multiplatform#3617]
**Describe the bug**
I have created a **macOS target** in my Compose Multiplatform project.
When I build my app for that macOS target, I have an error: `Unknown iOS platform: 'macosx'`. It works well when I build for the default iOS target.
It worked well when I was using Compose 1.4 but after upgrading to 1.5, the error happened.

**Affected platforms**
macOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0
- OS version(s)* (required for Desktop and iOS issues): macOS 13.5
- OS architecture (x86 or arm64): Apple M1 Pro
- JDK (for desktop issues): no, native macOS using Xcode

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a Compose Multiplatform project using this template with Compose 1.5
2. Go to Xcode and open the iosApp.xcodeproj of the project.
3. Create a new macOS target.
4. Copy the content of iOSApp.swift and paste it in the macOS.swift file.
5. Select the new macOS target, select your device in the top Xcode selector and try to launch it.
6. Error happened.

**Expected behavior**
Should work like with Compose 1.4

**Screenshots**
<img width="987" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/24540801/259fa837-d625-455a-a322-1d9f4cc3e4a8">

**Additional context**
Here is the log of the error:

```
Run custom shell script 'Compile Kotlin' 38.9 seconds

> Configure project :shared
w: file:///Users/vincent/AndroidStudioProjects/Teleport/shared/build.gradle.kts:73:13: Variable 'commonTest' is never used
w: file:///Users/vincent/AndroidStudioProjects/Teleport/shared/build.gradle.kts:98:13: Variable 'androidMain' is never used
w: file:///Users/vincent/AndroidStudioProjects/Teleport/shared/build.gradle.kts:120:13: Variable 'appleMain' is never used
w: file:///Users/vincent/AndroidStudioProjects/Teleport/shared/build.gradle.kts:135:13: Variable 'macosMain' is never used
w: file:///Users/vincent/AndroidStudioProjects/Teleport/shared/build.gradle.kts:143:13: Variable 'desktopMain' is never used
Configuration 'kspKotlinMacosArm64ProcessorClasspath' was resolved during configuration time.
This is a build performance and scalability issue.
See https://github.com/gradle/gradle/issues/2298
Run with --info for a stacktrace.

> Task :shared:generateAppleMainNonAndroidBuildConfig UP-TO-DATE
> Task :shared:generateGeneratedByKspKotlinMacosArm64NonAndroidBuildConfig UP-TO-DATE
> Task :shared:generateMacosArm64MainNonAndroidBuildConfig UP-TO-DATE
> Task :shared:generateMacosMainNonAndroidBuildConfig UP-TO-DATE
> Task :shared:generateNativeMainNonAndroidBuildConfig UP-TO-DATE
> Task :shared:generateNonAndroidBuildConfig UP-TO-DATE

> Task :shared:kspKotlinMacosArm64
note: [ksp] loaded provider(s): [com.rickclephas.kmp.nativecoroutines.ksp.KmpNativeCoroutinesSymbolProcessorProvider]

> Task :shared:compileKotlinMacosArm64
warning: Opt-in requirement marker androidx.compose.material3.ExperimentalMaterial3Api is unresolved. Please make sure it's present in the module dependencies
warning: Opt-in requirement marker com.google.accompanist.permissions.ExperimentalPermissionsApi is unresolved. Please make sure it's present in the module dependencies

> Task :shared:linkDebugFrameworkMacosArm64
warning: Cannot infer a bundle ID from packages of source files and exported dependencies, use the bundle name instead: shared. Please specify the bundle ID explicitly using the -Xbinary=bundleId=<id> compiler flag.

> Task :shared:assembleDebugAppleFrameworkForXcodeMacosArm64
> Task :shared:syncComposeResourcesForIos FAILED
error: Unknown iOS platform: 'macosx'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared:syncComposeResourcesForIos'.
> Unknown iOS platform: 'macosx'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 39s
11 actionable tasks: 5 executed, 6 up-to-date

> Configure project :shared
w: file:///Users/vincent/AndroidStudioProjects/Teleport/shared/build.gradle.kts:73:13: Variable 'commonTest' is never used
w: file:///Users/vincent/AndroidStudioProjects/Teleport/shared/build.gradle.kts:98:13: Variable 'androidMain' is never used
w: file:///Users/vincent/AndroidStudioProjects/Teleport/shared/build.gradle.kts:120:13: Variable 'appleMain' is never used
w: file:///Users/vincent/AndroidStudioProjects/Teleport/shared/build.gradle.kts:135:13: Variable 'macosMain' is never used
w: file:///Users/vincent/AndroidStudioProjects/Teleport/shared/build.gradle.kts:143:13: Variable 'desktopMain' is never used
Configuration 'kspKotlinMacosArm64ProcessorClasspath' was resolved during configuration time.
This is a build performance and scalability issue.
See https://github.com/gradle/gradle/issues/2298
Run with --info for a stacktrace.

> Task :shared:generateAppleMainNonAndroidBuildConfig UP-TO-DATE
> Task :shared:generateGeneratedByKspKotlinMacosArm64NonAndroidBuildConfig UP-TO-DATE
> Task :shared:generateMacosArm64MainNonAndroidBuildConfig UP-TO-DATE
> Task :shared:generateMacosMainNonAndroidBuildConfig UP-TO-DATE
> Task :shared:generateNativeMainNonAndroidBuildConfig UP-TO-DATE
> Task :shared:generateNonAndroidBuildConfig UP-TO-DATE
> Task :shared:kspKotlinMacosArm64
> Task :shared:compileKotlinMacosArm64
[ksp] loaded provider(s): [com.rickclephas.kmp.nativecoroutines.ksp.KmpNativeCoroutinesSymbolProcessorProvider]
Opt-in requirement marker androidx.compose.material3.ExperimentalMaterial3Api is unresolved. Please make sure it's present in the module dependencies

> Task :shared:linkDebugFrameworkMacosArm64
Opt-in requirement marker com.google.accompanist.permissions.ExperimentalPermissionsApi is unresolved. Please make sure it's present in the module dependencies

> Task :shared:assembleDebugAppleFrameworkForXcodeMacosArm64
> Task :shared:syncComposeResourcesForIos FAILED
Cannot infer a bundle ID from packages of source files and exported dependencies, use the bundle name instead: shared. Please specify the bundle ID explicitly using the -Xbinary=bundleId=<id> compiler flag.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared:syncComposeResourcesForIos'.
> Unknown iOS platform: 'macosx'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 39s
11 actionable tasks: 5 executed, 6 up-to-date
Unknown iOS platform: 'macosx'
```

**Comment by m-sasha** [comment]
Hi. Can you be more specific about the reproduction steps, or share a complete reproducer project?

I was able to run a macOS target in Compose 1.5.0 by:
1. Check out the template project and following the instructions from: https://github.com/JetBrains/compose-multiplatform-ios-android-template/
2. Open XCode and open the iosApp project in it.
3. Duplicate and rename the iosApp target in XCode:

<img width="300" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5230206/cce7146d-779c-4528-b89e-d743d033983d">

4. Rename the bundle identifier to match my team id.
5. Select "macosApp -> My Mac (designed for iPad)" target at the top in XCode.
6. Press the "play" button in XCode

The result is:

<img width="1026" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5230206/9364cfcd-a43a-4cd3-86b1-379300b286ca">

**Comment by EBfVince** [comment]
Sure! I found an easier setup to reproduce the problem:

1. Check out the template project and following the instructions from: https://github.com/JetBrains/compose-multiplatform-ios-android-template/
2. Open XCode and open the iosApp project in it.
3. Open the iosApp Target and go to "Supported Destinations"
4. Remove "Mac (Designed for iPad)" from the list and add "Mac"
5. Select "iosApp -> My Mac" target at the top in XCode.
6. Press the "play" button in XCode

![image](https://github.com/JetBrains/compose-multiplatform/assets/24540801/fbd8ac45-ef1f-4bd6-b810-50478ec8c72b)


Here is a reproducer project if you want, you just need to press play on XCode:
https://github.com/EBfVince/compose-multiplatform-macosx-bug

I want to target the macOS SDK to be able to access [MenuBarExtra](https://developer.apple.com/documentation/swiftui/menubarextra).

**Comment by m-sasha** [comment]
Are you sure this (SDK=macOS) worked before with Compose 1.4?

**Comment by elijah-semyonov** [comment]
@EBfVince 
I'm not sure how that could work in the first place.
iOSApp.swift is using `UIViewControllerRepresentable` transitively, which doesn't exist in macOS SDK.

**Comment by EBfVince** [comment]
Yes, you're right: using the compose plugin with macOS SDK should not work at all.

After some investigation, I realized that I had managed to get the compose plugin working with macOS SDK and Compose 1.4 using a dubious workaround. With Compose 1.5, this solution no longer works. I thought it was a bug, but it is just the expected behavior.

Thank you for your time. I close the issue.

**Comment by EBfVince** [comment]
@m-sasha, @elijah-semyonov 
If you are curious to reproduce the behavior I was talking about:

- Clone this repository: https://github.com/joreilly/Confetti
- Open the project in Xcode 
- Try to launch "ConfettiMac" on your Mac.

**Comment by LionZXY** [comment]
@vinceglb Did you eventually find a way to use MenuBarExtra with Compose Multiplatform?

**Comment by vinceglb** [comment]
Unfortunately I did not continue my investigations. But it seems doable using JNA to call native macOS API from Kotlin. I've done something similar to access native macOS file picker with Kotlin : [here is an example](https://github.com/vinceglb/FileKit/blob/0f4c68211ef238db2760e0022ff0acd506f8d313/filekit-core/src/jvmMain/kotlin/io/github/vinceglb/filekit/core/platform/mac/MacOSFilePicker.kt#L66)
