### ISSUE TITLE
Support loading Lottie animations

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#362]
Skia already supports Lottie animations:
https://skia.org/user/modules/skottie

We can implement Composable's to load and show these animations.

**Comment by igordmn** [comment]
Support for GIF animations: https://github.com/JetBrains/compose-jb/issues/153

**Comment by SebastianAigner** [comment]
NB, the folks from Airbnb are also designing a Compose API for Lottie animations on Android: https://github.com/airbnb/lottie/blob/master/android-compose.md

**Comment by sureshg** [comment]
@SebastianAigner Lottie compose doesn't have plans to support CFD as it's using Android Canvas under the hood - https://twitter.com/gpeal8/status/1378443883890180097

**Comment by YektaDev** [comment]
Since it's been 2 years, I wonder if there are any plans for this feature any time soon?

**Comment by wwalkingg** [comment]
Lottie is important in client!

**Comment by jflavio11** [comment]
Hello guys, is there any update on this topic?

I'm not pretty sure where to find a kind of roadmap for supporting Lottie in Compose Multiplatform in Mobile

**Comment by MatkovIvan** [comment]
Currently you can use skia API directly (`org.jetbrains.skia.*`). Please note that it's part of [skiko](https://github.com/JetBrains/skiko) library with no public API stability guarantees for now.

There is an internal [demo](https://github.com/JetBrains/compose-multiplatform-core/pull/560) with some [issue](https://github.com/JetBrains/compose-multiplatform/issues/3149) and existing workaround:
> Reading `time` reference inside `drawIntoCanvas` block solves the issue.

Also almost a year ago we saw successful usage of it [in our Slack](https://kotlinlang.slack.com/archives/C0346LWVBJ4/p1662820821763109).

This topic is intended to track adding support in compose library itself

**Comment by gulabsagevadiya** [comment]
is there any update about lottie support?

**Comment by StarsEnd33A2D17** [comment]
> is there any update about lottie support?

You might want to try out this project: [Kottie](https://github.com/ismai117/kottie).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6017">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
