### ISSUE TITLE
QR code

### ISSUE THREAD

**Issue by adelsaramii** [JetBrains/compose-multiplatform#3623]
I know it's not about the compose multiplatform itself but im looking for a library that provide QR Code scanning on compose multiplatform (android & ios)
anyone knows the solution?

**Comment by m-sasha** [comment]
Since this not in the scope for Compose Multiplatform, perhaps it's better to ask in our #compose, #compose-ios and #compose-android channels in kotlinlang Slack.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3623">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
