### ISSUE TITLE
Weird behavior of undecorated window in its maximized state

### ISSUE THREAD

**Issue by gleb-skobinsky** [JetBrains/compose-multiplatform#3625]
In Compose Desktop, when a new window is created with `undecorated = true, resizable = true` and its placement is set to `Maximized`, the user is still able to resize it, but instead of resizing in a normal way, it flashes multiple times and stays maximized.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 20.04.6 LTS
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): JDK 11

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a desktop window like this:
 ```
Window(
            title = "ComposeConnect",
            onCloseRequest = ::exitApplication,
            undecorated = true,
            state = state,
            transparent = true,
        ) { 
...
}
```
3. Run the app
4. Try to resize the window when it is maximized
5. See flashy lines all over the window and be still unable to resize it

**Expected behavior**
No resizing in the maximized state and no cursor change indicating it.

I strongly believe that the option to resize the window must not be available in its maximized and fullscreen states at all.  

**Screenshots**
Here is a screen recording of what's happening:
https://github.com/JetBrains/compose-multiplatform/assets/90451272/024e053d-84fd-4ebc-af6a-b9fd7f8a4bdc

**Additional context**
The `UndecoratedWindowResizer`'s property `enabled` is set like this in the `ComposeWindow` class:
```
delegate.undecoratedWindowResizer.enabled = isUndecorated && isResizable
```
I think the fix should be as simple as something like:
```
delegate.undecoratedWindowResizer.enabled = isUndecorated && isResizable && placement == WindowPlacement.Floating
```

**Comment by m-sasha** [comment]
I think "maximized + resizable" is a valid state, and it works fine on Mac OS X. When the user resizes the window, it automatically changes the placement to `Floating`.

The bug here is that this doesn't seem to happen in Linux.

**Comment by igordmn** [comment]
Windows also doesn't have resizing handles in the maximized state in a decorated window.

We probably should make it platform-specific (show handles only on macOs). `resizable` argument for undecorated window should mimic behavior for decorated window.

**Comment by igordmn** [comment]
On Windows (comparing to Linux) we can still resize the window, and its state becomes Floating after we resize.

**Comment by m-sasha** [comment]
@igordmn The way I see it is that an undecorated window is a different animal from a regular window. Its purpose is to allow the developer to customize/implement all the aspects a "decorated" window provides (title bar, resizing etc.).

As such, its goal is not to emulate platform-specific behaviors, but to allow maximum customizability. The requested behavior is already possible (just set `maximized=true, resizable=false`) and we shouldn't limit other options by enforcing that maximized implies non-resizable (on some platforms).

In this way of looking at it, the issue here is just that the window doesn't properly resize in Linux.

**Comment by gleb-skobinsky** [comment]
Well, the problem is that once set to `resizable = false` you can no longer control floating/maximizing either. I have not yet tested this on other platforms, but if you launch a window with `state = WindowState(WindowPlacement.Floating), resizable = false`, you can no longer maximize the window to cover all of the space. That is, in code its state changes to `Maximized`, but in the UI nothing happens. The same applies to the opposite setting (`state = WindowState(WindowPlacement.Maximized, resizable = false`). I wonder if there is a workaround for this.

**Comment by gleb-skobinsky** [comment]
Setting resizability dynamically based on placement (that is, when the user clicks on maximize, change to `resizable = false`, when on floating `resizable = true` has the same effect.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3625">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
