### ISSUE TITLE
Setting popup size breaks scrolling

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#3629]
**Describe the bug**

If I want a scrollable text popup, it works only if I do not set the size of the popup. If I set the size, the scrolling no longer works.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*:  1.9.10
- Compose Multiplatform version*:  1.5.0
- OS version(s)* (required for Desktop and iOS issues): Mac
- OS architecture (x86 or arm64):  arm64
- JDK (for desktop issues): 17

**To Reproduce**

This works:

```kotlin
      Popup(
                onDismissRequest = ::dismissErrorAlert,
                alignment = Alignment.Center
            ) {

                Column(
                    verticalArrangement = Arrangement.SpaceAround,
                    modifier = Modifier
                        .verticalScroll(rememberScrollState())
//                        .size(300.dp, 500.dp)
                ) {
					Text(e)
                }


            }
```

When the size line is commented out, it breaks scrolling. As in, scrolling no longer has any affect.

**Expected behavior**

For size to not break scrolling

**Comment by igordmn** [comment]
The size after `verticalScroll` sets the size of the content. it is the same as setting it on the content itself:
```
Column(
    verticalArrangement = Arrangement.SpaceAround,
    modifier = Modifier
        .size(300.dp, 400.dp)
        .verticalScroll(rememberScrollState())
) {
    // can't be scrolled, because the size is less/equal the size of the container
    Box(Modifier.size(300.dp, 400.dp)) {
        repeat(100) {
            Text("Text")
        }
    }
}
```

We can't help to avoid such cases, because the case of setting the size of the content is a valid use case.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3629">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
