### ISSUE TITLE
Reduce overhead of iOS binary size compared to a pure KMP application

### ISSUE THREAD

**Issue by aplha98** [JetBrains/compose-multiplatform#3632]
After adding Compose to the KMM module, the iOS app's production size increased from 70 to 86 Mb.

**Affected platforms**
- iOS

**Versions**
- Kotlin version: 1.9.0
- Compose Multiplatform version:  1.5.0

**Comment by igordmn** [comment]
> the iOS app's production performance

Is this a typo, and you meant "production size"?

> from 70 to 86.

Is this in Mb?

**Comment by aplha98** [comment]
yes the size was 70mb and right now it is 86

**Comment by aplha98** [comment]
@igordmn thank you 😊

**Comment by igordmn** [comment]
Not sure that it can be reduced significantly, but it is worth to look at possible optimizations for Skiko/Compose binaries (removing unused code, removing debug info, etc).

**Comment by marchy** [comment]
⚠️ This is a total deal-breaker for us, as we are strictly adhering to the AppClip size limit (iOS 15: 10MB, iOS 16: 15MB)

An extra 16MB blows the entire budget on a Hello World app!

**Comment by laurentlr** [comment]
Looking at this [article](https://www.jacobras.nl/2023/09/android-ios-native-flutter-compose-kmp/), iOS App increase is mainly due to Skia that is coming from compose multiplatform. Maybe stable version size will be reduced, but if you want to drastically reduce size you might want to go with native iOS UI.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3632">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
