### ISSUE TITLE
UIKitView layout bug

### ISSUE THREAD

**Issue by Khang-NT** [JetBrains/compose-multiplatform#3635]
**Describe the bug**
UIKitView displays behind another view within a `Column`, let's look at the screenshot, the text view on iPhone is behind the text box.

![Screenshot 2023-09-07 at 10 45 00](https://github.com/JetBrains/compose-multiplatform/assets/13332950/32496391-cb29-48ce-ab11-0ce8bec996b0)

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*:  1.5.0
- OS version(s)* (required for Desktop and iOS issues): 16
- OS architecture (x86 or arm64): x86

**To Reproduce**
```kotlin
// common
@Composable
fun Reproduce() {
    Column(Modifier.fillMaxWidth().padding(8.dp)) {
        Row {
            OutlinedTextField(
                value = "",
                onValueChange = { },
                modifier = Modifier.weight(1f),
            )

            Button(
                onClick = {
                },
                modifier = Modifier.align(Alignment.CenterVertically),
            ) {
                Text("Test")
            }
        }

        TestPlatformView(Modifier.weight(1f))
    }
}
expect fun TestPlatformView(modifier: Modifier)

// Android
@Composable
actual fun TestPlatformView(modifier: Modifier) {
    AndroidView(
        factory = { context ->
            TextView(context).apply {
                this.text = Array(100) { "$it" }.joinToString("\n")
            }
        },
    )
}

// iOS
@Composable
actual fun TestPlatformView(modifier: Modifier) {
    UIKitView(
        factory = {
            UITextView().apply {
                this.text = Array(100) { "$it" }.joinToString("\n")
            }
        },
        modifier = modifier,
    )
}

```
**Expected behavior**
`UITextView` shouldn't be overlapped.

**Additional context**
If wrap `UIKitView` with `Box`, the issue will be gone:
```kotlin
Box(modifier) {
   UIKitView(modifier = Modifier.fillMaxSize(), ...)
}
```

**Comment by elijah-semyonov** [comment]
If you replace TestPlatformView(Modifier.weight(1f)) with TestPlatformView(Modifier.fillMaxSize()) it's also working well.

**Comment by Khang-NT** [comment]
Maybe a related issue on JVM:
![Screenshot 2023-09-08 at 20 29 42](https://github.com/JetBrains/compose-multiplatform/assets/13332950/3d06747b-e566-4747-817b-f08d895b212b)
![Screenshot 2023-09-08 at 20 29 52](https://github.com/JetBrains/compose-multiplatform/assets/13332950/504a195d-31f2-4fd5-ad35-bddd7d6f8d11)

**Comment by elijah-semyonov** [comment]
UIKitView widget doesn't properly communicate its layout when used alone.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3635">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
