### ISSUE TITLE
Compose Web - KeyEvent mappings

### ISSUE THREAD

**Issue by sc941737** [JetBrains/compose-multiplatform#3644]
**Describe the bug**
Observing KeyEvents via the Modifier.onKeyEvent (or the like) function shows that the key "t" is mapped to KEY_UNKNOWN, and the key "6" to KEY_T. As far as I can tell, other keys seem fine.

**Affected platforms**
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-beta02

**To Reproduce**
1. Add onKeyEvent call to a modifier of any TextField or parent.
2. Log the KeyEvent inside the lambda.
3. Run the app, press buttons.
4. Open browser console and see logs.

**Expected behavior**
T key should map to KEY_T
6 key to KEY_6

**Comment by igordmn** [comment]
We have 2 issues here:
1. wrong mapped key codes for some keys in web.
2. returning `Key.Unknown` instead of `Key(keyCode)`. We should return `Key(keyCode)` even if there is no knowing mapping in Compose. `Unknown` should be returned only if the platform doesn't know about this key code.

**Comment by dhakehurst** [comment]
seem to be many issues with KeyEvents on web platform !

#2296

**Comment by eymar** [comment]
Reproduced with 1.5.0 and 1.6.0.

But it works correctly in `1.6.10-dev1571` (which contains key events related changes).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3644">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
