### ISSUE TITLE
how to build my ios app on real device

### ISSUE THREAD

**Issue by adelsaramii** [JetBrains/compose-multiplatform#3650]
Im building my ios app on ios simulator but i need to test the performance on real device.
how can i connect the iphone for android studio and get release test

**Comment by SongOnWater** [comment]
Click the down-ward triangle arrow on the right side of the iOS platform indicator(typically with name "iosApp"), select the "Edit Configurations" item, then on the "Run/Debug Configurations" panel, there is an Execution target spinner, select your connected real device on the selection list.

**Comment by igordmn** [comment]
Follow [this guide](https://github.com/JetBrains/compose-multiplatform-ios-android-template#running-on-a-real-device)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3650">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
