### ISSUE TITLE
crash for on ios for missing resource

### ISSUE THREAD

**Issue by adelsaramii** [JetBrains/compose-multiplatform#3651]
this is the exeption
Uncaught Kotlin exception: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: drawable/splash_bg.xml

it runs on android very well but on ios side it just not regonize the "drawable/splash_bg.xml" and crash

**Comment by SongOnWater** [comment]
There is a middle path of "/compose-resources/" in  UIKitResourceImpl for iOS, You can add this  path to your resource path.

**Comment by pjBooms** [comment]
What Compose Multiplatform version do you use? Can you provide a reproducible sample?

**Comment by igordmn** [comment]
Try a solution described [here](https://github.com/JetBrains/compose-multiplatform/issues/3637#issuecomment-1713815077). You don't need to create `compose-resources` manually.

Let us know, if it helps. If it doesn't help, please provide a sample with the issue.

**Comment by adelsaramii** [comment]
> What Compose Multiplatform version do you use? Can you provide a reproducible sample?

kotlin.version=1.9.0
agp.version=8.0.2
compose.version=1.5.0

**Comment by igordmn** [comment]
Can you share a project (better a minimal version of it) where the issue is reproducible?

**Comment by adelsaramii** [comment]
The problem get fixed automatically

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3651">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
