### ISSUE TITLE
Two textfields have focus simultaneously

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#3652]
**Describe the bug**
Opening a dialog with a textfield while another textfield has focus will show focus in both textfields.

**Affected platforms**
All

**Versions**
- Kotlin version: 1.9.10
- Compose Multiplatform version: 1.5.1 
- OS version(s) (required for Desktop and iOS issues): Mac OS X

**To Reproduce**
```
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.graphics.*
import androidx.compose.ui.unit.*
import androidx.compose.ui.window.*

@OptIn(ExperimentalFoundationApi::class)
fun main() = singleWindowApplication {
    Column(Modifier.fillMaxSize().background(Color.White)){
        val focusRequester = remember { FocusRequester() }
        TextField(
            value = "",
            onValueChange = { },
            modifier = Modifier.focusRequester(focusRequester)
        )
        LaunchedEffect(Unit) {
            focusRequester.requestFocus()
        }

        var showDialog by remember { mutableStateOf(false) }
        Text(
            text = "Open Dialog",
            modifier = Modifier
                .onClick {
                    showDialog = true
                }
                .padding(8.dp)
                .background(Color.LightGray, shape = RoundedCornerShape(4.dp))
                .padding(16.dp)
        )

        if (showDialog) {
            Dialog(
                onDismissRequest = { showDialog = false },
            ) {
                Surface (
                    elevation = 20.dp
                ) {
                    Box(Modifier.padding(40.dp)) {
                        val dialogFocusRequester = remember { FocusRequester() }
                        TextField(
                            value = "",
                            onValueChange = { },
                            modifier = Modifier.focusRequester(dialogFocusRequester)
                        )

                        LaunchedEffect(Unit){
                            dialogFocusRequester.requestFocus()
                        }
                    }
                }
            }
        }
    }
}
```

**Expected behavior**
Only the textfield in the dialog should show as focused.

https://github.com/JetBrains/compose-multiplatform/assets/5230206/b77eeb0c-5242-48f4-9322-dec88f605aea

**Comment by m-sasha** [comment]
Strangely Android behaves the same way.

**Comment by m-sasha** [comment]
Added a [comment](https://partnerissuetracker.corp.google.com/issues/170977431#comment5) to the relevant Android ticket.

**Comment by m-sasha** [comment]
Looking at the code, there are two issues:
1. The textfield in the background continues to think it has focus because the previously focused owner doesn't receive any notifications in `ComposeScene.attach(SkiaBasedOwner)`.
2. Normally, when the window loses focus, the The textfield stops drawing the caret. This is implemented by checking `LocalWindowInfo.current.isWindowFocused`. In the case of a `Dialog`, however, we're still in the same window, with the same `LocalWindowInfo`.

Note that there's currently no mechanism for the owner to restore the focus to the right element after losing it, so we probably can't easily "unfocus" it. But we could at least stop drawing the caret by checking whether we're in a focused toplevel owner. However, we would need to add this ability to common because `Modifier.cursor` is in common.

**Comment by TheMelody** [comment]
```
 val focusRequester = remember { FocusRequester() }
focusRequester.freeFocus()
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3652">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
