### ISSUE TITLE
Missing `ambientOf` api

### ISSUE THREAD

**Issue by FlysoftBeta** [JetBrains/compose-multiplatform#3653]
Missing ambientOf from jetpack compose

Platform: Desktop
Compose multiplatform: 1.4.1
Kotlin: 1.8.20

**Comment by kirill-grouchnikov** [comment]
That has been removed a long time ago. Ambients have been renamed to composition locals.

**Comment by FlysoftBeta** [comment]
> That has been removed a long time ago. Ambients have been renamed to composition locals.

Ah, I see. Thanks for pointing out!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3653">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
