### ISSUE TITLE
"Visual effects" example app has performance issues

### ISSUE THREAD

**Issue by azarovalex** [JetBrains/compose-multiplatform#3654]
**Describe the problem**
I was testing public examples in this repo and noticed that [visual effects example](https://github.com/JetBrains/compose-multiplatform/tree/v1.5.1/examples/visual-effects) has noticeable performance issues, at least on iOS. A Release build without a debugger connected shows around 20-30fps on iPhone 11 Pro.

As we can see from the Metal debug HUD each frames takes around ~47ms to render and less than 2ms of that time is spent on GPU, so CPU seems to be a bottle neck in this case.
<img src="https://github.com/JetBrains/compose-multiplatform/assets/1976216/a404bd57-3edf-4e13-b898-c5b604bebbdd" width="400">

It's possible that the reason for bad performance is in the sample app itself (in which case it probably shouldn't be a public sample?) or it can be a performance issue in Compose Multiplatform + Skia.

**Affected platforms**
At least iOS, I didn't measure performance on Android.

**Versions**
- Kotlin version: 1.9.10
- Compose Multiplatform version: 1.5.1
- OS version(s) (required for Desktop and iOS issues): 17.0

**Sample code**
[Example app lives in this repo.](https://github.com/JetBrains/compose-multiplatform/tree/v1.5.1/examples/visual-effects)

**Reproduction steps**
Build example on iOS device, enable [Metal HUD](https://developer.apple.com/documentation/xcode/monitoring-your-metal-apps-graphics-performance) and observe performance on "Wave Effect" or "Happy New Year" screens.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3654">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
