### ISSUE TITLE
Some releases mentioned in VERSIONING.md are missing

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-multiplatform#3658]
**Describe the bug**

The [VERSIONING.md](https://github.com/JetBrains/compose-multiplatform/blob/master/VERSIONING.md) file mentions the following mappings:

```
1.9.10 | 1.5.2 
1.9.20-Beta | 1.5.2.1-Beta
```

However those versions were not published? E.g. I couldn't find `v1.5.2` on [Maven Central](https://mvnrepository.com/artifact/org.jetbrains.compose/compose-gradle-plugin), and couldn't find `v1.5.2.1-Beta` here: https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/compose-gradle-plugin/.

**Comment by igordmn** [comment]
Thanks!

It seem there were a mistake, and we added compiler versions to this table.

@eymar, could you fix this file?

**Comment by eymar** [comment]
Sorry!
Yes, my mistake

**Comment by eymar** [comment]
Fixed in #3659

**Comment by joreilly** [comment]
What is the compiler version in that case that we should use with Kotlfin 1.9.20-Beta....or is expectation to still use https://maven.pkg.jetbrains.space/public/p/compose/dev for now (and use 1.5.2.1-Beta ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3658">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
