### ISSUE TITLE
The Dialog seems to have bugs

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#3663]
**Describe the bug**

~~When I try to animate the closing of a androidx.compose.ui.window.Dialog using `scaleOut`, the dialog animates but another ghost of the dialog remains on the app.~~

~~I also noticed that the dialog background scrim seems too dark. So maybe multiple instances of it are created?~~

When I try to take a screenshot of a Dialog in a test, the test fails with the following error:

```stacktrace
java.lang.AssertionError: Failed: assertExists.
Reason: Expected exactly '1' node but found '2' nodes that satisfy: (isRoot)
Nodes found:
1) Node #1 at (l=0.0, t=0.0, r=0.0, b=0.0)px
2) Node #2 at (l=0.0, t=0.0, r=1024.0, b=768.0)px
[IsDialog]
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:145)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:79)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode$default(SemanticsNodeInteraction.kt:78)
	at androidx.compose.ui.test.OutputKt.printToString(Output.kt:45)
	at androidx.compose.ui.test.OutputKt.printToString$default(Output.kt:41)
       ...
```

Minimal reproducible code:

```kotlin
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onRoot
import androidx.compose.ui.test.printToString
import androidx.compose.ui.window.Dialog
import org.junit.Rule
import org.junit.Test

class DialogProblemReproducerTest {
    @get:Rule
    val composeTestRule = createComposeRule()

    @Test
    fun `Take screenshot of the dialog`() {
        composeTestRule.setContent {
            Dialog(onDismissRequest = {}, content = {})
        }
        composeTestRule.onRoot().printToString()
    }
}
```

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0
- OS version(s)*: Windows 10
- OS architecture (x86 or arm64): x86_64
- JDK (for desktop issues): Oracle JDK 17.0.7

**Comment by m-sasha** [comment]
Thanks for the report. We'll investigate.

**Comment by m-sasha** [comment]
This fails on Android in the same way, because both the "regular" root and the dialog itself are considered roots.
So unfortunately we won't be fixing this.

Is the issue with animating the dialog still present? I see you striked-out that part...

**Comment by mahozad** [comment]
Sorry, I cannot try the animation now but the problem was that two separate pieces of code were reacting to a `showMyDialog` property and two dialogs were displayed. I removed one of the codes and now the scrim is correct too.
So, probably the animation should also have been fixed.

**Comment by m-sasha** [comment]
Ok, thanks. I'll close this issue then.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3663">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
