### ISSUE TITLE
Can the community provide a complete set of desktop component libraries for more people to quickly complete some functional applications

### ISSUE THREAD

**Issue by Kale1314** [JetBrains/compose-multiplatform#3670]
As a non front-end developer, when creating some small tools, there may be more focus on functional implementation. If there are some common components that can create a beautiful interface, it will attract more people to pay attention to this project and promote community development

[UI design Refer To：https://ant.design/docs/spec/introduce](https://ant.design/docs/spec/introduce)

[Components Refer To：https://ant.design/components/overview/](https://ant.design/components/overview/)

**Comment by MatkovIvan** [comment]
We would be delighted if such components were introduced. For instance, the community is already creating a [compose-look-and-feel](https://github.com/alexzhirkevich/compose-look-and-feel), and [Jewel](https://github.com/JetBrains/jewel) is being developed by JetBrains. However, this tracker is for tasks that can be accomplished within the framework, not for community projects. Therefore, this is the reason we are closing this issue.

**Comment by Kale1314** [comment]
Thank you for your reply. We did not see that the relevant project already exists, so we raised this question. Thank you for your dedication to this project

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3670">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
