### ISSUE TITLE
Kindly include imePadding()

### ISSUE THREAD

**Issue by Lilytreasure** [JetBrains/compose-multiplatform#3679]
Kindly include the imepadding API to  react to keyboard  changes

**Comment by MatkovIvan** [comment]
For now `WindowInsets.ime` is already available, so you can use this API to react to keyboard changes.

Adding modifiers is already tracked, so closing it as duplicate of #3563

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3679">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
