### ISSUE TITLE
Add an example/tutorial of using unit tests

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#368]
Also we need to add `uiTestJUnit4` to gradle plugin:

```
    object Dependencies {
        val desktop = DesktopDependencies
        val animation get() = composeDependency("org.jetbrains.compose.animation:animation")
        val foundation get() = composeDependency("org.jetbrains.compose.foundation:foundation")
        val material get() = composeDependency("org.jetbrains.compose.material:material")
        val runtime get() = composeDependency("org.jetbrains.compose.runtime:runtime")
        val ui get() = composeDependency("org.jetbrains.compose.ui:ui")
        val materialIconsExtended get() = composeDependency("org.jetbrains.compose.material:material-icons-extended")
        val uiTestJUnit4 get() = composeDependency("org.jetbrains.compose.ui:ui-test-junit4")
    }
```

**Comment by igordmn** [comment]
For now we can use this in build.gradle.kts:
```
dependencies {
    testImplementation(compose("org.jetbrains.compose.ui:ui-test-junit4"))
}
```

[Example](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/[…]sktopTest/kotlin/androidx/compose/foundation/ScrollbarTest.kt) of unit test

**Comment by igordmn** [comment]
Also we need to add docs how to do screenshot-based testing:

```
val window = TestComposeWindow(width = 1024, height = 768)
window.setContent {

}
File(path).writeBytes(window.surface.makeImageSnapshot().encodeToData()!!.bytes)
```

**Comment by igordmn** [comment]
We should also add an important note about JUnit version: `createComposeRule` only works with JUnit 4.

**Comment by tylergannon** [comment]
Hi all!  Would appreciate any notes at all, on how to get started setting up multiplatform tests using the above mentioned library.

**Comment by m-sasha** [comment]
Added an example to both the compose multiplatform desktop template, and the `imageviewer` example project.
Do we need anything else here, @igordmn?

**Comment by igordmn** [comment]
> Added an example to both the compose multiplatform desktop template, and the imageviewer example project.
Do we need anything else here, @igordmn?

We can close the issue after we add a doc and merge everything to master.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5520">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
