### ISSUE TITLE
ArtifactNotFoundException: Could not find runtime-js-1.5.10-beta01.klib

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#3683]
**Describe the bug**

After upgrading the gradle plugin to 1.5.10-beta01, I get the following error:

```
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find runtime-js-1.5.10-beta01.klib (org.jetbrains.compose.runtime:runtime-js:1.5.10-beta01)
```

I get this error alongside many other similar errors.

**Affected platforms**
Select one of the platforms below:

- JS

**Versions**
- Kotlin version*: 1.9.20-Beta
- Compose Multiplatform version*: 1.5.10-beta01
- OS version(s)* (required for Desktop and iOS issues):  Mac OS
- OS architecture (x86 or arm64):  arm64

**To Reproduce**

Setup a project with the versions above, targeting JS.

**Expected behavior**

For there to be no errors.

**Comment by Walingar** [comment]
Hello @mgroth0. Thank you for pointing on that! Can you please check it now? It seems that at the moment when you checked it library wasn't published to Maven Central

**Comment by Walingar** [comment]
@mgroth0 can you please check do you have mavenCentral() in your repositories in gradle script?

Seems like you have only gradle plugins portal for some reason. 
Thank you!

**Comment by Taltus1337** [comment]
I had basically same issue with iOS targets.  Solved it by removing `gradlePluginPortal()` from `dependencyResolutionManagement`.


```

dependencyResolutionManagement {
    repositories {

//        gradlePluginPortal()
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3683">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
