### ISSUE TITLE
Moving window in desktop App with different screen resolutions causes Switch Thumb to misalign

### ISSUE THREAD

**Issue by xavimolloy** [JetBrains/compose-multiplatform#3685]
**Describe the bug**

When moving a desktop app from one screen to another with different resolution the thumb in the switch component gets dis-aligned within the track.

Changing screens and back causes the item to recompose and go back to correct position. item is moved to one side or another depending on whether you move the window to a higher or a lower resolution

currently using compose  1.5.1 version occurs also in version 1.5.10-beta01

**Affected platforms**
Select one of the platforms below:
- Desktop
- Web? haven't tested

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*:  1.5.1, 1.5.10-beta01
- OS version(s)* Windows
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 

**To Reproduce**
Use the Switch component
launch it with desktop version
move app window to a screen with a different resolution

code snippet: 

` Switch(
            modifier = modifier,
            checked = isChecked,
            onCheckedChange = { onCheckedChange.invoke(isChecked) },
            enabled = enabled,
            thumbContent = {
                if (isChecked) {
                    Icon(
                        imageVector = Icons.Filled.Check,
                        contentDescription = null,
                        modifier = Modifier.size(SwitchDefaults.IconSize),
                    )
                } else {
                    Icon(
                        imageVector = Icons.Outlined.Close,
                        contentDescription = null,
                        tint = TextColor.OnPrimary,
                        modifier = Modifier.size(SwitchDefaults.IconSize),
                    )
                }
            },
        )` 

**Expected behavior**
thumb inside the track of switch component should maintain same relative position and margin
**Screenshots**

![image](https://github.com/JetBrains/compose-multiplatform/assets/44061143/ff665335-ab18-4299-adaa-36f33fa04e15)
![image](https://github.com/JetBrains/compose-multiplatform/assets/44061143/12d0ebf8-b48c-48eb-a6df-a78e0f211699)
![image](https://github.com/JetBrains/compose-multiplatform/assets/44061143/0c8fef7a-4168-49b0-9a14-7184b43b65f8)
![image](https://github.com/JetBrains/compose-multiplatform/assets/44061143/958b71b6-7f44-4130-ba7b-e041c9371ec1)

**Additional context**

**Comment by MohamedRejeb** [comment]
I'm having the same issue on mac M1 as well.

**Comment by MohamedRejeb** [comment]
Here's a minimal reproducible project with compose: 1.5.0-beta01

https://github.com/MohamedRejeb/CMP-3685

For macOs just updating to compose: 1.5.1 fixes the issue, I will try with windows.

**Comment by MohamedRejeb** [comment]
Updating compose to 1.5.1 fixes the issue for windows as well (x86) 🎉

**Comment by MohamedRejeb** [comment]
I was having this issue with all of the components when I move the window to another monitor, now it's fixed. But as @xavimolloy mentioned, when you have Switch and you move the window back and forth this problem occurs. Currently for me it's happening only for Switch.


https://github.com/JetBrains/compose-multiplatform/assets/41842296/155f649e-b82c-4b50-8b59-798bd366515f

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3685">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
