### ISSUE TITLE
ComposeUIViewController has a white background

### ISSUE THREAD

**Issue by Mats-Hjalmar** [JetBrains/compose-multiplatform#3687]
**Describe the bug**
ComposeUIViewController has a white background when passed for a UiView.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-beta01
- OS version(s)* (required for Desktop and iOS issues): iOS 16.4
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): N/A

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

```kotlin
@Composable
fun ComposeViewInUIView(){
    Box(Modifier.fillMaxSize().background(Color.Blue)) {
        UIKitView(factory = {
            ComposeUIViewController {
                Box(Modifier.size(90.dp).background(Color.Gray))
            }.view
        }, modifier = Modifier.size(100.dp))
    }
}
```

![Simulator Screenshot - iPhone 14 - 2023-09-15 at 12 51 07](https://github.com/JetBrains/compose-multiplatform/assets/111428992/5ebff5f3-e87a-4046-916f-3e58f3d53cd9)

**Expected behavior**
The UIKitView should have a transparent background and let the background of the outer box fill up to the gray box.

Using a box as outer constraint: 
![Simulator Screenshot - iPhone 14 - 2023-09-15 at 12 55 05](https://github.com/JetBrains/compose-multiplatform/assets/111428992/41dbe973-5d1b-4c2f-936e-2e055c3bfb96)

When a size is not specified in the UIKitView then it should adapt to the ComposeUIViewController constraints.

**Screenshots**
See above for screenshots.

**Additional context**
Getting this solved would create opportunities for making custom pins for Apple Maps (MapKit) without specifying size.
![Screenshot of Custom Annotation View](https://github.com/JetBrains/compose-multiplatform/assets/111428992/8a9e7f13-46c1-41a8-b91b-4c196654f07a)

Code:

```kotlin
@OptIn(ExperimentalForeignApi::class)
class CustomAnnotationView(annotation: MKAnnotationProtocol?, reuseIdentifier: String?) :
    MKAnnotationView(annotation, reuseIdentifier) {
    override fun initWithAnnotation(
        annotation: MKAnnotationProtocol?,
        reuseIdentifier: String?
    ): MKAnnotationView {
        return CustomAnnotationView(annotation, reuseIdentifier)
    }

    init {
        addSubview(
            ComposeUIViewController {
                Text("Text")
            }.apply {
                loadView()
            }.view.apply {
                setFrame(
                    CGRectMake(0.0, 0.0, 100.0, 100.0)
                )
                setClipsToBounds(true)
            }
        )

    }
}
```

**Comment by Mats-Hjalmar** [comment]
Im wildly unqualified with iOS to understand what you did but i want to try. The reason it is "impossible" is because the metal renderer does not support opacity to background layers?

**Comment by elijah-semyonov** [comment]
It does support opacity, and in fact, we use it for interop with UIKit views, but it's only working correctly for "completely transparent" and "completely opaque" use cases. Anything more sophisticated will cause rendering issues. Alpha different from 1 or 0 due to text rendering antialiasing may cause these issues as well, so there are a lot of underlying problems with no clear resolution for now.

**Comment by Mats-Hjalmar** [comment]
But in my case i want the background to be completely transparent. Is this possible?

**Comment by elijah-semyonov** [comment]
It is possible to make it completely transparent, but it will still cause issues 
> due to text rendering antialiasing

**Comment by Mats-Hjalmar** [comment]
Thank you for your response.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3687">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
