### ISSUE TITLE
Support material3-adaptive

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3688]
This library is currently (15-09-2023) under development and haven't reach the stable 1.0 state yet: https://github.com/androidx/androidx/tree/androidx-main/compose/material3/material3-adaptive

It mostly developed in commonMain, so it is possible to port it to Compose Multiplatform

**Comment by Omico** [comment]
This has been moved to https://github.com/androidx/androidx/tree/androidx-main/compose/material3/adaptive.
See also https://developer.android.com/jetpack/androidx/releases/compose-material3-adaptive.

**Comment by Omico** [comment]
We need to modify & publish our own `androidx.window:window-core` first. I have done some work on this. I’m currently using Compose Multiplatform 1.6.11, and the ported Jetpack Compose Material3 Adaptive libraries are version 1.0.0-alpha08. Newer versions of Jetpack Compose Material3 Adaptive libraries require Compose 1.7.

My project only has a JVM desktop and WASM target.

![image](https://github.com/JetBrains/compose-multiplatform/assets/14316223/aa145055-510d-4fa7-a21d-78ba554f2016)

**Comment by doTTTTT** [comment]
@Omico In Window Manager 1.3.0 they added `Kotlin Multiplatform support for Window Size Classes.` this will help ?
https://developer.android.com/jetpack/androidx/releases/window#1.3.0

And Chris Banes publish a lib for the WindowSizeClass to be available in Kotlin Mutliplatform
https://github.com/chrisbanes/material3-windowsizeclass-multiplatform

**Comment by Omico** [comment]
> @Omico In Window Manager 1.3.0 they added `Kotlin Multiplatform support for Window Size Classes.` this will help ? https://developer.android.com/jetpack/androidx/releases/window#1.3.0
> 
> And Chris Banes publish a lib for the WindowSizeClass to be available in Kotlin Mutliplatform https://github.com/chrisbanes/material3-windowsizeclass-multiplatform

These two are not the same.

See the difference between:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:window/window-core/src/commonMain/kotlin/androidx/window/core/layout/WindowSizeClass.kt
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material3/material3-window-size-class/src/commonMain/kotlin/androidx/compose/material3/windowsizeclass/WindowSizeClass.kt

Jetpack Compose Material3 Adaptive libraries are using `androidx.window:window-core`.

I decided to open source the project ahead of time so you can check it out for yourself. https://github.com/OmicoDev/wwm

**Comment by dozy-programmer** [comment]
@Omico Is there a timeline of when this is expected to be available?

**Comment by Omico** [comment]
> @Omico Is there a timeline of when this is expected to be available?

I'm not a member of the JetBrains/Google team, and it's unclear which team should be responsible for publishing this component to Maven. I think you should ask @igordmn for more information. Anyway, you'll be able to copy my work on your project.

**Comment by MatkovIvan** [comment]
https://github.com/JetBrains/compose-multiplatform-core/pull/1468

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3688">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
