### ISSUE TITLE
[desktop] Supporting a `startDragging` API like tauri's

### ISSUE THREAD

**Issue by FlysoftBeta** [JetBrains/compose-multiplatform#3689]
We now have a WindowDraggableArea to specify which area can be dragged, however, I think there should be a more flexible way to do that conditionally.
(For reference, Tauri's document: https://tauri.app/v1/api/js/window/#startdragging)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3689">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
