### ISSUE TITLE
Support animatedVectorResource in commonMain

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3690]
See https://developer.android.com/jetpack/compose/animation/avd

Compose Multiplatform already supports `vectorDrawable` (in 1.5.0). We need to investigate if it can support `animatedVectorResource` as well, and support it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3690">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
