### ISSUE TITLE
Support configuration of overscroll effects in commonMain

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3691]
Android has [LocalOverscrollConfiguration](https://github.com/androidx/androidx/blob/41cb7d5c422180edd89efde4076f9dc724d3a313/compose/foundation/foundation/src/androidMain/kotlin/androidx/compose/foundation/OverscrollConfiguration.kt#L75) that configures Android-style overscroll, and has the `overscrollEffect` argument in `Modifier.scrollable`

Desktop/web don't have overscroll at the moment

iOS has a custom overscroll effect via `CupertinoOverscrollEffect`, and the current `LocalOverscrollConfiguration` isn't applicable for it (it doesn't have glowColor or drawPadding). But sometimes it needs to be configured. For example, we need to configure should we always apply overscroll, or configure the spring effect stiffness. Possible solutions:
- make `LocalOverscrollConfiguration` expect/actual
- deprecate `LocalOverscrollConfiguration` and provide `LocalOverscrollEffect` instead
- deprecate `LocalOverscrollConfiguration` and provide `LocalScrollableConfiguration` instead
- deprecate `LocalOverscrollConfiguration`, allow configuration only per-widget basis (LazyList, scrollable)

**Comment by PMARZV** [comment]
It would be amazing if ComposeMP had a custom overscroll effect (like in IOS but in other platforms too) and let us customize it. Android overscroll effect is very limited and if you have a lower Android version, the "Stretch overscroll" is not there. In my humble opinion, stretch overscroll should be implemented in all android versions! (i dont know if that possible or not)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3691">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
