### ISSUE TITLE
Commonize Modifier.magnifier

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3692]
See https://github.com/androidx/androidx/blob/41cb7d5c422180edd89efde4076f9dc724d3a313/compose/foundation/foundation/src/androidMain/kotlin/androidx/compose/foundation/Magnifier.kt#L94

It's API is applicable to `commonMain`, but it is in `androidMain`

Magnifier is usual useful during text selection

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3692">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
