### ISSUE TITLE
Commonize Modifier.systemGestureExclusion

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3693]
https://github.com/androidx/androidx/blob/41cb7d5c422180edd89efde4076f9dc724d3a313/compose/foundation/foundation/src/androidMain/kotlin/androidx/compose/foundation/SystemGestureExclusion.kt#L36

This API is in androidMain, but it can be applicable to other platforms as well.

iOS has [preferredScreenEdgesDeferringSystemGestures](https://developer.apple.com/documentation/uikit/uiviewcontroller/2887512-preferredscreenedgesdeferringsys).

See also, a similar request in [other library](https://github.com/software-mansion/react-native-gesture-handler/issues/833)

More info, why it is needed: https://medium.com/androiddevelopers/gesture-navigation-handling-gesture-conflicts-8ee9c2665c69

**Comment by Code-indomitus** [comment]
Hi is some one working on this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3693">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
