### ISSUE TITLE
Commonize Modifier.imeNestedScroll()

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3694]
https://github.com/androidx/androidx/blob/41cb7d5c422180edd89efde4076f9dc724d3a313/compose/foundation/foundation-layout/src/androidMain/kotlin/androidx/compose/foundation/layout/WindowInsetsConnection.android.kt#L72

It is in `androidMain`, but describes a useful behavior. We also need to investigate, if it is possible on iOS

See [this](https://developer.android.com/jetpack/compose/layouts/insets#ime-animations) to understand the feature.

**Comment by MohitMandalia** [comment]
I want to help explore this.

To get started iOS has something called [SafeAreaLayout](https://developer.apple.com/documentation/uikit/uiview/positioning_content_relative_to_the_safe_area/) which can be useful.

**Comment by igordmn** [comment]
> I want to help explore this.

Sounds good, thanks! We'll review it

**Comment by dima-avdeev-jb** [comment]
I started Issue with animated keyboard inset. It is dependent feature.
After that I want to add this feature too.

**Comment by dima-avdeev-jb** [comment]
> Any way I can help you in the same?

Thanks!
For now I know how to add first feature with animated `WindowsInsets.ime`. I should do it first.

But I didn't know for now how to add `Modifier.imeNestedScroll()` on iOS. We need some API from iOS to control Keyboard position or size. You may research in this direction I supposed.

**Comment by MohitMandalia** [comment]
> > Any way I can help you in the same?
> 
> Thanks!
> For now I know how to add first feature with animated `WindowsInsets.ime`. I should do it first.
> 
> But I didn't know for now how to add `Modifier.imeNestedScroll()` on iOS. We need some API from iOS to control Keyboard position or size. You may research in this direction I supposed. 

Sure I will look around and post my findings If I get something solid.

Thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3694">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
