### ISSUE TITLE
Provide a way to selectively disable native targets

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-multiplatform#3695]
My Gradle module has `org.jetbrains.compose` Gradle plugin applied and the following targets enabled: 

```kotlin
kotlin {
    androidTarget()
    jvm()
    js { browser() }
    ios()
}
```

But I don't need Compose for `ios` and `js` targets. I'm able to disable Compose for Web using the following configuration:

```kotlin
compose.web.targets()
```

However, it looks like there is no API for iOS. Currently I'm using the following workaround, which is not ideal.

```kotlin
plugins.removeAll { it is ComposeCompilerKotlinSupportPlugin }

class ComposeNoNativePlugin private constructor(
    private val delegate: KotlinCompilerPluginSupportPlugin = ComposeCompilerKotlinSupportPlugin(),
) : KotlinCompilerPluginSupportPlugin by delegate {
    @Inject constructor() : this(ComposeCompilerKotlinSupportPlugin())

    override fun isApplicable(kotlinCompilation: KotlinCompilation<*>): Boolean {
        return when (kotlinCompilation.target.platformType) {
            KotlinPlatformType.native -> false
            else -> delegate.isApplicable(kotlinCompilation)
        }
    }
}

apply<ComposeNoNativePlugin>()
```

**Comment by eymar** [comment]
Thanks!  Related: https://github.com/JetBrains/compose-multiplatform/pull/3657

**Comment by eymar** [comment]
To get it right, you have no Compose related code in the commonMain source set, right?

**Comment by arkivanov** [comment]
Correct. I have a module that supports Android, JVM/Desktop, JS and iOS. And I only use Compose in `androidMain` and `jvmMain` source sets. See the code [here](https://github.com/arkivanov/Decompose/tree/compose-experimental/sample/shared/dynamic-features/feature1Impl).

**Comment by eymar** [comment]
Closing this as fixed :) 
It should be available in 1.5.10-beta02

**Comment by arkivanov** [comment]
Thank you! 🙏

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3695">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
