### ISSUE TITLE
Cursor position sometimes dont update in compose desktop

### ISSUE THREAD

**Issue by GabrielLasso** [JetBrains/compose-multiplatform#3696]
**Describe the bug**
When I use an external class in onChangeValue, sometimes the cursor dont update correctly

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*:  1.19.10
- Compose Multiplatform version*: 1.5.1
- OS version(s)* (required for Desktop and iOS issues): Fedora 37
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues): 17

**To Reproduce**
Minimal example:
```
object ViewModel {
    val text = MutableStateFlow("")
    fun setText(text: String) {
        this.text.value = text
    }
}

fun main() {
    application {
        Window(onCloseRequest = ::exitApplication) {
            val text by ViewModel.text.collectAsState()
            TextField(
                value = text,
                onValueChange = ViewModel::setText
            )
        }
    }
}
```

**Expected behavior**

**Screenshots**
[Gravação de tela de 2023-09-15 11-33-33.webm](https://github.com/JetBrains/compose-multiplatform/assets/12103372/25a547e7-f05c-4f61-8af6-5a72ee3cda81)

**Additional context**

**Comment by m-sasha** [comment]
There's a known issue with using TextField together with StateFlow: https://medium.com/androiddevelopers/effective-state-management-for-textfield-in-compose-d6e5b070fbe5

Google are addressing this in a future version of TextField.

**Comment by GabrielLasso** [comment]
@m-sasha changing to mutableStateOf works, thanks

I will change the api of the viewmodels in my app to expose states instead of flows

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3696">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
