### ISSUE TITLE
Add debug/release visibility at runtime

### ISSUE THREAD

**Issue by dzirbel** [JetBrains/compose-multiplatform#3700]
I'd like to customize some behavior in my application based on whether running a debug or release build (e.g. `runDebug` vs `runRelease`), for example disabling debug tools, logging, or making deserialization more lenient for release builds. I may be missing something obvious, but I can't find a way to do this conveniently with Compose's builtin `buildTypes` configuration or its `(run|package)(Debug|Release)` tasks for desktop.

The closest workaround I've found is to configure `JavaExec` tasks, for example:
```
tasks.withType<JavaExec> {
    args = listOf("customArgs")
}
```

this will provide custom arguments only for the `runDebug` and `runRelease` tasks, but will not apply them to the distributable artifacts. This is pretty close to what I'm looking for in practice, since generally the run tasks are used for development and the distributables for releases, but it may be nice to test e.g. performance with any release-specific behavior via `runRelease` or sometimes build a debug distributable.

There are a number of ways to solve this use case, for example:
- `JvmApplicationBuildTypes` could provide an `args` setting that configures JVM arguments per build type (e.g. `buildTypes { release { args = "" } }`
- The Compose plugin could build from `debug` or `release` source sets for different build types, like the Android plugin does
- The Compose plugin could generate something similar to Android's `BuildConfig` with a `DEBUG` constant

Is there already a good solution for this case which I've missed? If so, it may be good to add it to https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Native_distributions_and_local_execution

**Comment by dima-avdeev-jb** [comment]
Thanks, good suggestion.
Also please take a look at library https://github.com/yshrsmz/BuildKonfig
But it is still not in stable version, please be carefull!

**Comment by solita-michalguspiel** [comment]
Does anyone have any updates on this? This seems like a necessary feature to me.

**Comment by dima-avdeev-jb** [comment]
@solita-michalguspiel Sorry, no updates yet

**Comment by wakaztahir** [comment]
Hi @dima-avdeev-jb I don't need debug / release visibility at runtime, However I do need to detect release mode in gradle kts, so I can assign it to a variable using `BuildKonfig`

This will make it easier for me when building program without having to manually change the variable in gradle kts files

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3700">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
