### ISSUE TITLE
Desktop: Can't type in TextField placed in ModalBottomSheet

### ISSUE THREAD

**Issue by sdzshn3** [JetBrains/compose-multiplatform#3703]
**Describe the bug**
I'm not able to type text in OutlinedTextField which is placed inside ModalBottomSheet.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.10-beta01
- OS version(s)* (required for Desktop and iOS issues): macOS Ventura 13.5.2
- OS architecture (x86 or arm64): x64

**To Reproduce**
1. Create a composable function for content of bottom sheet. 
2. Have a stateless OutlinedTextField (get the value and onValueChange from function params and set them to OutlinedTextField)
3. Call this function in ModalBottomSheet as it's content.
4. Have the mutableState of string for TextField in same place where you trigger the bottomsheet to open.

**Expected behavior**
Should be able to type.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3703">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
