### ISSUE TITLE
R.Drawable file not in Compose Multiplatform

### ISSUE THREAD

**Issue by doriancrutcher** [JetBrains/compose-multiplatform#3704]
I'm not sure if this is a big common issue, but I just underwent the Compose Tutorial for android specific apps and while building out my demo app I noticed that I can't seem to find a drawable folder to place test images in. 

And I can't find documentation on how to get around this.  

Is this a feature that can be added?

**Comment by yuroyami** [comment]
You should use moko-resources library to share resources between platforms.

**Comment by doriancrutcher** [comment]
> You should use moko-resources library to share resources between platforms.

Ah very cool thank you for the info!

**Comment by yuroyami** [comment]
@doriancrutcher  You're welcome. Let me know if you need anything when you try to integrate moko-resources into your KMM project. It can be a bit confusing at first.

**Comment by MatkovIvan** [comment]
It appears the issue you're experiencing isn't linked directly to Compose, but to the Android specific resource generation side of things.

As of now, we currently don't have plans to integrate this feature, but there are a few alternatives out there like 'moko resources' (as mentioned earlier).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3704">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
