### ISSUE TITLE
Provide a way to add addinitional binaries to MacOS folder

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/compose-multiplatform#3707]
To accommodate the macOS JVM version of my app, I require a method to include an extra binary within the "Contents/MacOS" directory. In my specific scenario, this binary represents a CLI utility designed for interfacing with Apple Photos. This binary must be placed in the directory before the code signing process takes place.

Currently, I haven't identified a configuration option to achieve this objective. The current configuration only supports the addition of resources.

Is there a workaround available for this situation? Can you provide guidance on executing a Gradle task after the entire assembly process has concluded but just before the signing process begins?

**Comment by dima-avdeev-jb** [comment]
Can you please provide a sample of desired API ?
Maybe some snippets of possible Gradle configuration ?

**Comment by StefanOltmann** [comment]
I could imagine it being similar to the `appResourcesRootDir`.


```
compose.desktop.application {

    mainClass = "MainKt"

    buildTypes.release.proguard {
        configurationFiles.from(project.file("proguard-rules.pro"))
        obfuscate.set(true)
        optimize.set(true)
    }

    nativeDistributions {

        /* For java.sql.DriverManager, used by SQLDelight */
        modules("java.sql")

        targetFormats(TargetFormat.Pkg)

        [...]

        appResourcesRootDir.set(
            project.layout.projectDirectory.dir("resources")
        )

        windows {
            iconFile.set(project.file("src/desktopMain/resources/icon.ico"))
        }

        macOS {

            extraBinaryRootDir.set(
                project.layout.projectDirectory.dir("helpers")
            )

            bundleID = "com.ashampoo.photos"

            iconFile.set(project.file("src/desktopMain/resources/icon.icns"))

            appCategory = "public.app-category.photography"

            [...]
        }
    }
}
```

**Comment by dima-avdeev-jb** [comment]
Unfortunatelly there are no workaround to place files right to Contents/MacOS dir yet.

**Comment by dima-avdeev-jb** [comment]
Can you share additional context, why standart resources with `appResourcesRootDir` works bad with your application?
What behavior do you want to achieve?

**Comment by dima-avdeev-jb** [comment]
I think - I understood. You want to place your binnary right in Content/MacOS dir, because it is executable file. And MacOS needs to place it here because of running restrictions.
Correct?

**Comment by ionull** [comment]
Same issue here, in order to use jcef, I need to put the jcef-bundle folder in the application installation root on all platforms

**Comment by StefanOltmann** [comment]
> I think - I understood. You want to place your binnary right in Content/MacOS dir, because it is executable file. And MacOS needs to place it here because of running restrictions. Correct?

Yes, that’s the exact issue I’m facing. I placed my executable in the app resources dir, but macOS won’t let it run with the required permissions to access the Apple Photos library. As far as I can see it needs to go into the said folder to execute with permissions.

**Comment by StefanOltmann** [comment]
> Hi, Did you manage to work with this issues ? I am also looking for a solution.

No, my app can continue functioning without the specific feature I require the native library for a bit longer. I understand that resolving this issue may not be high priority at the moment, especially as they focus on stabilizing Compose for web.

**Comment by purushred** [comment]
Thanks for the prompt response.
I am looking for a way to include a script in the .deb bundle and the script should retain the executable permissions. I am able to include the script but the permissions are not retained once the .deb package installed.
Any thoughts on how to make it work?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3707">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
