### ISSUE TITLE
WindowDraggableArea has a problem (jumps to bottom on click)

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#3709]
**Describe the bug**
Occasionally, clicking on an undecorated window that has a custom title bar (using `WindowDraggableArea`) causes the window to jump to bottom.

This happens every so often and may not be so easy to reproduce.

Here are two times that I reproduced the problem:

https://github.com/JetBrains/compose-multiplatform/assets/29678011/c5aa04a9-b6b4-4002-a736-48629fdac4bc

https://github.com/JetBrains/compose-multiplatform/assets/29678011/0f61fbc7-a619-4401-87c9-0fe346bc4012

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.20-Beta
- Compose Multiplatform version*: 1.5.10-beta01
- OS version(s)*: Windows 11
- OS architecture (x86 or arm64): x86_64
- JDK (for desktop issues): Oracle JDK 17.0.5

**To Reproduce**

```kotlin
import androidx.compose.foundation.window.WindowDraggableArea
// ...

fun main() = application {
    Window(
        resizable = false,
        undecorated = true,
        onCloseRequest = ::exitApplication
    ) {
        WindowDraggableArea(
            modifier = Modifier
                .fillMaxWidth()
                .height(30.dp)
                .background(Color.Yellow)
        ) {
            Icon(
                imageVector = Icons.Outlined.Close,
                contentDescription = null,
                modifier = Modifier.clickable(onClick = ::exitApplication)
            )
        }
    }
}
```

**Comment by dima-avdeev-jb** [comment]
Created repository with reproducer:
https://github.com/dima-avdeev-jb/issue-3709/tree/main

@mahozad Can you please check this bug in my repository again?

**Comment by mahozad** [comment]
@dima-avdeev-jb Yes. I reproduced the bug with your repository in my Windows 11.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3709">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
