### ISSUE TITLE
FAQ does not answer its own question

### ISSUE THREAD

**Issue by Sternbach-Software** [JetBrains/compose-multiplatform#3711]
https://github.com/JetBrains/compose-multiplatform/blob/a73909e7eef7610201ac5240170cd7b06848b581/docs/FAQ.md?plain=1#L32
The ensuing paragraph does not answer when it will become stable, it just explains the difference between alpha, experimental, and stable.

**Comment by igordmn** [comment]
We can't provide any public ETA when iOS becomes stable at the moment. the FAQ section was rewritten [here](https://www.jetbrains.com/help/kotlin-multiplatform-dev/faq.html#can-i-use-compose-multiplatform-in-production)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3711">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
