### ISSUE TITLE
Desktop: Month Pager in DatePicker doesn't snap to center after stopping scroll

### ISSUE THREAD

**Issue by sdzshn3** [JetBrains/compose-multiplatform#3712]
**Describe the bug**
When showing a DatePicker inside a DatePickerDialog, if I scroll between months and leave it partially between two different months, it doesn't snap to either of month page.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.10-beta01
- OS version(s)* (required for Desktop and iOS issues): Ventura 13.5.2
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): 17

**To Reproduce**

1. Have a DatePicker in a DatePickerDialog
2. Open the dialog
3. Scroll to different month partially by doing a two finger swipe gesture on track pad and leave the fingers. (Not sure how it works when Mouse is used)
4. Observe that the month page doesn't snap to center

**Expected behavior**
When we lift our finger or stop scrolling, the month page which is taking most space should snap to center.

**Video**

https://github.com/JetBrains/compose-multiplatform/assets/36739949/f34ea7c6-7b61-4c48-b5eb-967aa1f813aa

**Comment by sdzshn3** [comment]
Understood. 
In such use cases where there is an alternative way to scroll, better disable the scrolling in desktop. 

Can take this DatePicker as an example. Since we have arrow marks to change the month, an option to disable swipe will be good for temporary purpose

**Comment by dima-avdeev-jb** [comment]
I will close this issue, because the desired behavior already described here:
https://github.com/JetBrains/compose-multiplatform/issues/3447

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3712">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
