### ISSUE TITLE
SelectionContainer crashes on Compose for iOS

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/compose-multiplatform#3718]
**Describe the bug**
I use the SelectionContainer Composable which works as expected for Android and JVM Desktop.
On my iPhone 12 Mini the selection of text crashes the app.

See the crash log:
[2023-09-20_07-30-23.3605_+0200-262104203cacf94f31579f9ab12f826c416bb0dc.crash.txt](https://github.com/JetBrains/compose-multiplatform/files/12681615/2023-09-20_07-30-23.3605_%2B0200-262104203cacf94f31579f9ab12f826c416bb0dc.crash.txt)

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.1
- OS version(s)* (required for Desktop and iOS issues): 17.0
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Use a SelectionContainer Composable around a Text
2. Start the app
3. Select the text

**Expected behavior**
No crash

**Comment by dima-avdeev-jb** [comment]
I was trying to reproduce on real iOS device iPhone13 mini and on simulator.
But it works without any crash in my sample https://github.com/dima-avdeev-jb/issue-3718-ios-selection-container

Can you please try to check my sample too?

**Comment by StefanOltmann** [comment]
@dima-avdeev-jb Thank you. It took me some time to figure this out.

It crashes if empty text and/or spacers are involved.

Try this:
```
    SelectionContainer {

        Column {

            Text("Some")

            Spacer(Modifier.height(8.dp))

            Text("multiline")

            Spacer(Modifier.height(8.dp))

            Text("")

            Spacer(Modifier.height(8.dp))

            Text("text to select in SelectionContainer")
        }
    }
```

As a workaround I will see to avoid displaying empty an text.

**Comment by dima-avdeev-jb** [comment]
Thanks! It reproduced

**Comment by dima-avdeev-jb** [comment]
This bug is also reproduced on Android here: 

Fixed in Android JetPack Compose here: https://android-review.googlesource.com/c/platform/frameworks/support/+/2616177

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3718">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3718">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3718">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
