### ISSUE TITLE
The packaged code (mac M1 platform) cannot directly run the app application, and it will flash back when the app is started.

### ISSUE THREAD

**Issue by dengdg** [JetBrains/compose-multiplatform#3723]
**Describe the bug**
The packaged code (mac M1 platform) cannot directly run the app application, and it will flash back when the app is started.

**Affected platforms**
Select one of the platforms below:
Desktop

**Versions**
- Kotlin version*: 1.8
- Compose Multiplatform version*: "1.5.1"
- OS version(s)* (required for Desktop and iOS issues): Desktop
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): Oracle JDK 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
N/A

**Expected behavior**
Expect the packaged app files to work as well as the Jar package

**Screenshots**
N/A

**Additional context**
N/A

**Comment by dima-avdeev-jb** [comment]
We made changes in version
`compose.version=1.5.10-beta02`
Can you please try to update and follow this instruction:
https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Signing_and_notarization_on_macOS

**Comment by sunny-chung** [comment]
I also experienced immediate crashes without logs when running the executable on a M2 mac, but does not crash when running the jar file. This happens to compose 1.3.0, 1.5.2 and 1.5.10-beta02.

However, I have another compose desktop project with compose 1.5.2 running fine on M2. Perhaps it relates to dependencies used by the application.

But we at least needs logs to make debug possible.

**Comment by dima-avdeev-jb** [comment]
@sunny-chung Can you provide minimal reproducible sample on GitHub with "immediate crashes without logs"?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3723">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
