### ISSUE TITLE
API to disable intrinsic sizes on Image coming from the Painter

### ISSUE THREAD

**Issue by alexfacciorusso** [JetBrains/compose-multiplatform#3727]
Suggestion to add a flag to the `Image` composable to ignore the size coming from the given `Painter` object to be applied as intrinsic sizes.

## Versions

```properties
kotlin = 1.9.10
compose = 1.5.1
```

## Case

The layout is an Image, together with other sibling composables, in a container (Row, Column, custom layouts, other).
The developer wants to use the other composables' intrinsic sizes in order to size the Image to the Min or Max intrinsic size.

Let's have a look at a simple example (backgrounds added for clarity):

```kotlin
@Composable
fun Content() {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        modifier = Modifier.background(Color.LightGray).height(IntrinsicSize.Min)
    ) {
        Text(
            "Text 1",
            modifier = Modifier.background(Color.Green),
        )
        Text(
            "Text 2\nMultiline",
            modifier = Modifier.background(Color.Yellow),
        )
        Image(
            painterResource("svg_logo.svg").also { println(it.intrinsicSize) },
            contentDescription = "The SVG logo",
            modifier = Modifier.background(Color.Cyan),
        )
        Text(
            "Text 3",
            modifier = Modifier.background(Color.Red),
        )
    }
}
```

(`svg_logo.svg` By W3C SVG Logo, CC BY-SA 4.0, https://commons.wikimedia.org/w/index.php?curid=105996438)

That layout would result into something like this:

![image](https://github.com/JetBrains/compose-multiplatform/assets/4479527/ae88d651-b119-4c64-96cf-691470831ab2)

The image will push the parent container to be as big as the intrinsic size set by the Painter is. 

> [!NOTE]  
> In this case the minimum intrinsic sizes for the Image composable are **100** for both width and height, which doesn't seem to make sense as it seems to be a representation of the `width="100%"` and `height="100%"` in the svg, as the viewBox is `viewBox="0 0 300 300"`. Again, it doesn't seem sensible, and I may create another bug for this, if we deem it necessary.

As an example, this is the result that we want to achieve:

![image](https://github.com/JetBrains/compose-multiplatform/assets/4479527/08111236-6827-4028-afaa-fdd5a9c8976a)

## Workaround

In order to reach the shown result, currently, the only way to "override" the intrinsics of the Image seems to be to wrap it with a Box, assign a `fillMaxHeight` and an aspect ratio modifier to the parent Box, and a `matchParentSize` to the Image itself.

This solution, although working, is a bit unelegant:

```kotlin
val aspectRatio = painterResource.intrinsicSize.width / painterResource.intrinsicSize.height

Box(modifier = Modifier.fillMaxHeight().aspectRatio(aspectRatio)) {
    Image(
        painterResource,
        contentDescription = "The SVG logo",
        modifier = Modifier.background(Color.Cyan).matchParentSize(),
    )
}
```

## Possible fix implementation

Those sizes are applied from the underlying `paint` modifier. The same modifier, though, offers a flag `sizeToIntrinsics` that would disable exactly the behaviour that might not be wanted. An easy fix would be to expose that flag to the Image composable, and setting it to `true` so that the default behaviour would be the current one and not break compatibility:

```kotlin
@Composable
fun Image(
    painter: Painter,
    // ...
    painterSizeToIntrinsics: Boolean = true,  // <-- To add this
) {
   // ...

    Layout(
        {},
        modifier.then(semantics).clipToBounds().paint(
            painter,
            alignment = alignment,
            contentScale = contentScale,
            alpha = alpha,
            colorFilter = colorFilter,
            sizeToIntrinsics = painterSizeToIntrinsics, // <-- To pass the flag to the paint Modifier here
        )
    ) { _, constraints ->
        // ...
    }
}
```

Once that would be done, the solution above would only require an `Image` composable:

```kotlin
val painterResource = painterResource("svg_logo.svg")

Image(
    painterResource,
    contentDescription = "The SVG logo",
    painterSizeToIntrinsics = false,
    modifier = Modifier.background(Color.Cyan).fillMaxHeight().aspectRatio(
        painterResource.intrinsicSize.width / painterResource.intrinsicSize.height
    ),
)
```

![image](https://github.com/JetBrains/compose-multiplatform/assets/4479527/65b8e34b-7ad1-461b-b6de-3a2d77955c78)

Obviously this issue is to discuss the API and potential additions like exposing another flag that would automatically set the aspect ratio, or even creating a totally new composable (something like `UnboundedImage`, which would have a nicer documentation explaining why is that there and a flag to set the aspect ratio automatically).

I would be open to write a PR for this, once the API for this case has been discussed and agreed.

**Comment by dima-avdeev-jb** [comment]
Thanks for this feature request! Looks interesting.
 - We can't simply add an argument to the `Image` function. We should be compatible with Android JetPack Compose. We can try to add it to Android side, but it is harder.
 - I will try to do own research of possible workarounds with current API.

**Comment by lisonge** [comment]
I need to show some `Drawable`  returned from the Android system API

but `Drawable.intrinsicSize` prevents it from narrowing to the height of the parent layout

```kt
val aspectRatio = painterResource.intrinsicSize.width / painterResource.intrinsicSize.height

Box(modifier = Modifier.fillMaxHeight().aspectRatio(aspectRatio)) {
    Image(
        painterResource,
        contentDescription = "The SVG logo",
        modifier = Modifier.background(Color.Cyan).matchParentSize(),
    )
}
```

thanks, your code example work for me

**Comment by m-sasha** [comment]
You can "reset" the icon's intrinsic size with 
```
Modifier.fillMaxHeight().height(1.dp)
```

For example:
```
fun main() = singleWindowApplication {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        modifier = Modifier.background(Color.LightGray).height(IntrinsicSize.Min)
    ) {
        Text(
            "Text 1",
            modifier = Modifier.background(Color.Green),
        )
        Text(
            "Text 2\nMultiline",
            modifier = Modifier.background(Color.Yellow),
        )
        Image(
            painterResource("svg_logo.svg").also { println(it.intrinsicSize) },
            contentDescription = "The SVG logo",
            modifier = Modifier
                .background(Color.Cyan)
                .fillMaxHeight()
                .height(1.dp),
        )
        Text(
            "Text 3",
            modifier = Modifier.background(Color.Red),
        )
    }
}
```

results in 

<img width="195" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5230206/6738f468-012b-4c43-a004-e680e9e8f4d5">

**Comment by m-sasha** [comment]
@alexfacciorusso if this solves the issue for you, can we close the ticket?

**Comment by lisonge** [comment]
`Modifier.fillMaxHeight().height(1.dp)` is not working with `Icon`
```kt
Icon(
    imageVector = Icons.Default.Android,
    contentDescription = null,
    modifier = Modifier.fillMaxHeight().height(1.dp)
// modifier = Modifier.fillMaxHeight() // not working
)
```
but `Icon` can work with `aspectRatio` and it doesn't need to be wrapped by `Box`
```kt
Icon(
    imageVector = Icons.Default.Android,
    contentDescription = null,
    modifier = Modifier
        .aspectRatio(1f)
        .fillMaxHeight()
)
```

**Comment by m-sasha** [comment]
> Modifier.fillMaxHeight().height(1.dp) is not working with Icon

Not working in what sense? Can you post a reproducer?

**Comment by lisonge** [comment]
<https://github.com/gkd-kit/gkd/blob/72e0f0fc7dff1f16de64a0b8806350bdae7c0fa8/app/src/main/kotlin/li/songe/gkd/ui/component/SubsAppCard.kt#L80-L86>

![image](https://github.com/JetBrains/compose-multiplatform/assets/38517192/f9a050df-7c56-4ce4-8745-368d5f15ae61)

![img_v3_028p_a664bb9b-74ae-4329-8dd0-1d7e5083503g](https://github.com/JetBrains/compose-multiplatform/assets/38517192/4369f999-1c2c-487d-bb42-b23e0eea8544)

**Comment by lisonge** [comment]
<https://github.com/gkd-kit/gkd/issues/546>

`Modifier.fillMaxHeight().height(1.dp)` is not working on some devices

I don't know why

But `Box+matchParentSize` is working, so I will use `Box+matchParentSize` instead of `height(1.dp)`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3727">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
