### ISSUE TITLE
Can you use Compose for desktop to achieve the effect in the picture?

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/compose-multiplatform#3729]
Can you use Compose for desktop to achieve the effect in the picture? Each part is a separate exe. The ToolBar above occupies the upper part of the computer desktop, and other application icons automatically move down to make way for them.

![image](https://github.com/JetBrains/compose-multiplatform/assets/19502034/59eb8d36-ff4c-4830-ac03-b57666fafbb2)

**Comment by wakaztahir** [comment]
But building a single application with all these separated windows is possible. There's a flag that makes window bars transparent to give you control over how bars are styled , you just need to position and size the windows, This will take some time but accomplishable

You could build each window in a separate program, Have a common launcher that launches all these windows. That launcher would need to know location of all the executables. So you should be able to accomplish this, Take some time to read the docs though

**Comment by changhexuefei** [comment]
![image](https://github.com/JetBrains/compose-multiplatform/assets/19502034/0fc02527-9aac-4dc7-bf3f-2104422f109c)
Are you referring to the setting of the transparent attribute? I set the property to true, but the part that is set to transparent will block the operation.

https://github.com/JetBrains/compose-multiplatform/assets/19502034/00941824-868e-49ff-abc8-be68154fbc1b

**Comment by wakaztahir** [comment]
What do you mean block the operation, I haven't tried this, If there's a bug this you should change the title to reflect a bug is the issue

**Comment by wakaztahir** [comment]
Can you try and create multiple windows in the application block

**Comment by changhexuefei** [comment]
Thank you for your suggestion. I will try to use a multi-window program to achieve the above requirements.

**Comment by alexfacciorusso** [comment]
@changhexuefei I think I understand what you mean by "blocking the operation". 

Potentially, the window you are creating is not "wrapping" its content, e.g. the size of the window is bigger than its content, making it capture the clicks on it, even if you can't see (again, because it's transparent). I can see it from a frame of your video where your mouse passes where one of the borders of the window should be and it transforms to a resize cursor:

![image](https://github.com/JetBrains/compose-multiplatform/assets/4479527/3c626905-6812-4a86-aed5-b5f748e48cf9)

Try creating the window with `WindowState(size=DpSize.Unspecified)`, and that should resize the window to be exactly the content's size, achieving the desired effect.

**Comment by changhexuefei** [comment]
![Uploading image.png…]()
I set the WindowState(size=DpSize.Unspecified) property, clicked the exit button, and when I needed to pop up the query box, it became like this.

**Comment by changhexuefei** [comment]
![image](https://github.com/JetBrains/compose-multiplatform/assets/19502034/a6197cfc-bf9f-43cb-a8da-daa146128eb4)

**Comment by alexfacciorusso** [comment]
I think you should be able to create the dialog **outside** of the parent Window.

Something like this (this one uses a preview API but you should be able to simply use a `Dialog` composable for doing the same):

```kotlin
@OptIn(ExperimentalMaterialApi::class)
fun main() = application {
    var showDialog by remember { mutableStateOf(false) }

    Window(onCloseRequest = ::exitApplication, state = rememberWindowState(size = DpSize.Unspecified)) {
        App(onClick = {
            showDialog = true
        })
    }

    if (showDialog) {
        AlertDialog(
            onDismissRequest = { showDialog = false },
            dialogProvider = UndecoratedWindowAlertDialogProvider,
            text = { Text("Yay or nay?") },
            confirmButton = {
                Button(onClick = { showDialog = false }) { Text("Yay") }
            },
            dismissButton = {
                Button(onClick = { showDialog = false }) { Text("Nay") }
            }
        )
    }
}
```

https://github.com/JetBrains/compose-multiplatform/assets/4479527/cfa846b4-08a7-46e3-9eb5-1a8617a05e81

As you can see, the dialog is outside of my main window, created as its own [borderless] window.

**Comment by alexfacciorusso** [comment]
Also, for more information about Dialogs, here it is a useful page https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Window_API_new#dialogs

**Comment by changhexuefei** [comment]
ok，thank you

**Comment by changhexuefei** [comment]
![image](https://github.com/JetBrains/compose-multiplatform/assets/19502034/c78ce48d-eab7-4a0b-86f4-802b915e7144)

Hello, would you like to ask, what are the attributes that are not circled in AlertDialog? Which version of AlertDialog are you using?

**Comment by changhexuefei** [comment]
Why did AlertDialog in compose.version=1.5.0 remove "dialogProvider=UndecoratedWindowAlertDialogProvider"?

**Comment by changhexuefei** [comment]
In Compose multiplatform 1.5.0 and above, DialogWindow is used to replace the "dialogProvider=UndecoratedWindowAlertDialogProvider" attribute in AlertDialog to achieve this requirement.

**Comment by dima-avdeev-jb** [comment]
@changhexuefei Can we close this issue as resolved now?

**Comment by changhexuefei** [comment]
yes

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3729">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
