### ISSUE TITLE
1.5.2 Gradle plugin missing on mavenCentral

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-multiplatform#3730]
**Describe the bug**

https://repo1.maven.org/maven2/org/jetbrains/compose/compose-gradle-plugin/

**Affected platforms**
- All
- Gradle

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 
- Compose Multiplatform version*: 1.5.2
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**To Reproduce**
Missing release artifact

**Expected behavior**
Uploaded gradle plugin

**Comment by hfhbd** [comment]
Only the compiler is uploaded, all other artifacts are missing. Is this expected?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3730">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
