### ISSUE TITLE
SVGPainter returns the wrong default size when percentage units are used in the SVG file

### ISSUE THREAD

**Issue by alexfacciorusso** [JetBrains/compose-multiplatform#3732]
**Describe the bug**

The `androidx.compose.ui.res.SVGPainter` class returns a `defaultSize` (and in turn, sets the intrinsic sizes in the `Image` composable) even when a size in concrete units is not specified in the SVG file.

**Affected platforms**

Desktop (reproduced), and potentially any platform using the `SVGPainter` class.

**Versions**
- Kotlin 1.8.20 (but also 1.9.10)
- Compose Multiplatform version*: 1.4.1, 1.5.1
- OS version(s)* (required for Desktop and iOS issues): Windows 11, any build
- OS architecture (x86 or arm64): x86_64
- JDK (for desktop issues): 17

**To Reproduce**

Create a painter loaded from an SVG resource with width and height set to `100%` (`<svg ... width="100%" height="100%">`:

```
val painterResource = painterResource("svg_logo.svg")
```

Where `svg_logo.svg` is [this one](https://commons.wikimedia.org/w/index.php?curid=105996438) (By W3C SVG Logo, CC BY-SA 4.0)

Inspect the `painterResource`'s `intrinsicSize` property. It will be `Size(100.0, 100.0)`.

**Expected behavior**

Assigning 100 **pixels** to be the intrinsic size of an SVG that sets a **percentage** as its size is not sensible in that context.

Possibly, it should not be set at all, or perhaps the `viewBox` boundaries in the SVG should be taken into consideration.

**Screenshots**

![image](https://github.com/JetBrains/compose-multiplatform/assets/4479527/98f4885c-c6d2-427d-9cb7-cfbf2c775b6a)

**Additional context**

By debugging and digging in the source code, the problem happens in the `DesktopSvgResources.desktop.kt` file, where this code calculates the default size in px of the painter:

```kotlin
private val defaultSizePx: Size = run {
    val width = root?.width?.withUnit(SVGLengthUnit.PX)?.value ?: 0f // <-- here
    val height = root?.height?.withUnit(SVGLengthUnit.PX)?.value ?: 0f // <-- and here
    if (width == 0f && height == 0f) {
        Size.Unspecified
    } else {
        Size(width, height)
    }
}
```

Maybe a check can be put into place to ignore that size if the original unit is `PERCENTAGE`.

**Comment by eymar** [comment]
`withUnit` doesn't really do any conversion of the value, it just creates a new SVGLength with the same value.
So, as I understand this code completely ignores the units from an `.svg` file, which is likely a bug (I'll check with the team). 
___

I think the easiest way for us is to treat it as Size.Unspecified.  What is your expectation for image behaviour when its size unit is PERCENTAGE?


cc: @igordmn Maybe we can convert other units to pixels. But not sure for now how to correctly handle PERCENTAGE unit.

**Comment by igordmn** [comment]
> I think the easiest way for us is to treat it as Size.Unspecified. What is your expectation for image behaviour when its size unit is PERCENTAGE?](cc: @igordmn Maybe we can convert other units to pixels. But not sure for now how to correctly handle PERCENTAGE unit.)

I would treat percentage as unspecified, and convert other units to px (that was the idea, but it seems we have a bug)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3732">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
