### ISSUE TITLE
[Question] Can you create a window (or dialog) that is undecorated, alwaysOnTop and does not appear in taskbar?

### ISSUE THREAD

**Issue by franmatesic** [JetBrains/compose-multiplatform#3736]
I have tried to make a window (always appears in taskbar), dialog (can't be alwaysOnTop) and had problems with Swing ComposeDialog approach.
What would be the best way to achieve this?

**Comment by eymar** [comment]
You might try to use DialogWindow - https://github.com/JetBrains/compose-multiplatform-core/blob/7d316a3651f395c877ad1bc89a2388ae6ab128b4/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/window/Dialog.desktop.kt#L330

it has `create` lambda that should return ComposeDialog which extends JDialog.
And for JDialog you can set:
```kotlin
dialog.isUndecorated = true
dialog.isAlwaysOnTop = true
dialog.type = Window.Type.POPUP
```

```kotlin
fun main() = application {
    DialogWindow(
        create = { ... }
        ...
```        

I tried it in compose source set by hardcoding those flags above in DialogWindow implementation. And It behaved as expected (tested on Ubuntu).

Did you try something like that?

**Comment by franmatesic** [comment]
Yeah that worked, thanks!
I wasn't aware of `DialogWindow` because I didn't update to the latest version.

**Comment by amir1376** [comment]
I try to change it inside a LaunchedEffect but it requires. to be set on creation time

it is a good idea to pass this type from parameters of `Window` composable function
so we can use `WindowState`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3736">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
