### ISSUE TITLE
Could not resolve all dependencies for configuration ':shared:jsCompileClasspath'. > Could not resolve io.realm.kotlin:library-base:1.11.0.   Required by:       project :shared

### ISSUE THREAD

**Issue by ismai117** [JetBrains/compose-multiplatform#3740]
I'm using realm in my kmp app, I know that realm isn't  compatible with web yet so I want to run web without realm library but I keep on receiving an error 

```
Could not resolve all dependencies for configuration ':shared:jsCompileClasspath'.
> Could not resolve io.realm.kotlin:library-base:1.11.0.
  Required by:
      project :shared
   > No matching variant of io.realm.kotlin:library-base:1.11.0 was found. The consumer was configured to find a library for use during 'kotlin-api', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js', attribute 'org.jetbrains.kotlin.js.compiler' with value 'ir' but:
       - Variant 'iosArm64ApiElements-published' capability io.realm.kotlin:library-base:1.11.0 declares a library for use during 'kotlin-api':
           - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
           - Other compatible attributes:
               - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
               - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
       - Variant 'iosArm64MetadataElements-published' capability io.realm.kotlin:library-base:1.11.0 declares a library:
           - Incompatible because this component declares a component for use during 'kotlin-metadata', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
           - Other compatible attributes:
               - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
               - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
       - Variant 'iosArm64SourcesElements-published' capability io.realm.kotlin:library-base:1.11.0:
           - Incompatible because this component declares documentation for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a library for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
           - Other compatible attributes:
               - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
               - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
       - Variant 'iosSimulatorArm64ApiElements-published' capability io.realm.kotlin:library-base:1.11.0 declares a library for use during 'kotlin-api':
           - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
           - Other compatible attributes:
               - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
               - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
       - Variant 'iosSimulatorArm64MetadataElements-published' capability io.realm.kotlin:library-base:1.11.0 declares a library:
           - Incompatible because this component declares a component for use during 'kotlin-metadata', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
           - Other compatible attributes:

**Comment by ismai117** [comment]
I tried this solution but its not working val jsMain by getting {
            dependsOn(commonMain)
            dependencies {
                implementation(compose.html.core)
                implementation("io.realm.kotlin:library-base:$realmVersion") {
                    exclude(group = "io.realm.kotlin", module = "library-base")
                }
                implementation("io.realm.kotlin:library-sync:$realmVersion") {
                    exclude(group = "io.realm.kotlin", module = "library-sync")
                }
            }
        }

**Comment by pablichjenkov** [comment]
It seems that Realm.db doesn't support JS target. 
- You can ask them to provide at least an empty wrapper to pass compilation. 
- Or you can take that dependency out of*commonMain* and place it in a custom target named *mobileOnlyLibs*.
- Or you can  completely abstract the database layer to interfaces and write code in each platform. This solution you write more but if you have already stuff in each platform you can reuse.

**Comment by ismai117** [comment]
thanks @pablichjenkov , it looks this  js(IR) { browser() } is causing the issue. can I exclude realm inside js(IR) { exclude ("io.realm.kotlin:library-base:1.11.0") } ?

**Comment by ismai117** [comment]
something like this  dependencies {
        
            implementation("io.realm.kotlin:library-base:$realmVersion") {
                because("Realm is not supported in Kotlin/JS")
                exclude(group = "io.realm.kotlin", module = "library-base")
            }
            implementation("io.realm.kotlin:library-sync:$realmVersion") {
                because("Realm is not supported in Kotlin/JS")
                exclude(group = "io.realm.kotlin", module = "library-sync")
            }
     
        }. but it won't work

**Comment by ismai117** [comment]
I did this and it working.  js(IR) {
        browser()
        configurations {
            all {
                exclude(group = "io.realm.kotlin", module = "library-base")
                exclude(group = "io.realm.kotlin", module = "library-sync")
            }
        }
    }. do you think it will cause any issues down the line ?

**Comment by pablichjenkov** [comment]
I don't think an exclusion rule will apply here. It would be a nice feature request but normally gradle tries to resolve all dependencies then apply the exclusion rule. In any case the exclusion rule should be applied in the JS target only, your code above is basically removing it from everywhere.

You should create an intermediate target named **onlyMobile**, it will have your only mobile dependencies, then make Android and iOS target depend on **onlyMobile**. Your realmdb dependency will be in onlyMobile not in common.
I could provide some code snippet but I am on my phone atm.

**Comment by ismai117** [comment]
yeah that would be a great feature, also I'm using realm for desktop so can you show a snippet when you're free please. thanks!

**Comment by pablichjenkov** [comment]
Check this project:
https://github.com/pablichjenkov/kmp-amadeus-api/blob/d4b296ccfd6416e79125143e24290a8c216a93c8/amadeus-api/build.gradle.kts#L153

**Comment by eymar** [comment]
Thank you @pablichjenkov for helping with this question! :) 

@ismai117 Feel free to add more questions if needed. 

To summarize:
If some libs don't support a particular target (k/js in this case), then that target shouldn't have it as a dependency. As @pablichjenkov has shown, it can be done by adding extra source sets to for supported/unsupported targets.

**Comment by ismai117** [comment]
that's all sorted on my side now, thanks for the help!!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3740">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
