### ISSUE TITLE
Black screens with UIKitView after navigating away and navigating back on 1.5.10-beta02

### ISSUE THREAD

**Issue by ToluwaniO** [JetBrains/compose-multiplatform#3749]
**Describe the bug**
After upgrading to `1.5.10-beta02`, I'm encountering issues with UIKitView when I navigate to a new screen and navigate back. I have a UIImageView inside the UIKitView that turns black.

The screens are SwiftUI and the content is compose. Navigation is done at the SwiftUI layer.

**Affected platforms**
Select one of the platforms below:
- iOS

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.10-beta02
- OS version(s)* (required for Desktop and iOS issues): iOS 16.6
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**Expected behavior**
No black screens after navigation

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/19718136/0d975944-fff7-4ddd-b2d3-60ac70571336

**Additional context**
```
@OptIn(ExperimentalForeignApi::class)
@Composable
actual fun NetworkImageImpl(
    modifier: Modifier,
    url: String?,
    contentDescription: String?,
    contentScale: ContentScale,
    usePlatform: Boolean
) {
    val imageLoader = LocalNetworkImageLoader.current
    UIKitView(
        modifier = modifier,
        background = Color.Transparent,
        factory = {
            UIImageView()
        },
        update = {
            when (contentScale) {
                ContentScale.Crop -> {
                    it.contentMode = UIViewContentMode.UIViewContentModeScaleAspectFill
                    it.clipsToBounds = true
                }
                ContentScale.Fit -> {
                    it.contentMode = UIViewContentMode.UIViewContentModeScaleAspectFit
                }
            }
            if (url != null) {
                imageLoader.loadUrlIntoImage(it, url)
            }
        },
        onRelease = {
                    Napier.d("image released", tag = "NetworkImageImpl")
        },
        interactive = false
    )
}

```

**Comment by elijah-semyonov** [comment]
Hi! Can you reproduce this in Compose 1.4.*?
Is `imageLoader.loadUrlIntoImage(it, url)` called on second appearance?
Can you show [UI debug hierarchy](https://stackoverflow.com/questions/28657634/xcode-cant-find-debug-view-hierarchy-button) in Xcode?

**Comment by eymar** [comment]
> After upgrading to 1.5.10-beta02
What was the previous version you used which didn't have an issue?

**Comment by ToluwaniO** [comment]
I added logs for `loadUrlIntoImage`, it gets called when I open the screen for the first time and when I navigate away and come back. I also see that `onRelease` gets called when I navigate back.

**Comment by ToluwaniO** [comment]
> > After upgrading to 1.5.10-beta02
> > What was the previous version you used which didn't have an issue?
`1.5.10-beta01` works normally

**Comment by ToluwaniO** [comment]
> > After upgrading to 1.5.10-beta02
> 
> What was the previous version you used which didn't have an issue?


1.5.10-beta01 works normally @eymar

**Comment by elijah-semyonov** [comment]
@ToluwaniO and regarding the Xcode UI debug? Could you please investigate it and see, if `UIImageView`s are present in the view hierarchy?

**Comment by elijah-semyonov** [comment]
Should be fixed in next release after https://github.com/JetBrains/compose-multiplatform-core/pull/857 is merged.

**Comment by ToluwaniO** [comment]
Gotcha, thanks! I'll drop an update if I encounter any issues.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3749">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
