### ISSUE TITLE
PointerIconHover Fails to Display Properly when using it with a DropdownMenu

### ISSUE THREAD

**Issue by Syer10** [JetBrains/compose-multiplatform#3750]
**Describe the bug**
When using a `pointerHoverIcon(PointerIcon.Hand)` and a `DropdownMenu`, the pointer hover icon will fail to display properly and will also make clicks fail half the time. The DropdownMenu also fails to display, so it is likely a issue releated to using them in conjunction.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.2
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): Amazon Corretto 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behaviour:
1. Clone https://github.com/Syer10/compose-pointer-issue
2. Hover over the button

**Expected behaviour**
The pointer icon is a solid hand icon.

**Screenshots**
![java_2023-09-29_13-56-15](https://github.com/JetBrains/compose-multiplatform/assets/6090655/2ce24dce-b48f-4890-be3b-df6bac8ff492)

**Additional context**
This worked fine in 1.4, I wanted to update to 1.5.2 for the touchscreen fix, but this bug has popped up

**Comment by igordmn** [comment]
Thanks for the report!

A smaller reproducer:
```
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Column
import androidx.compose.material.Button
import androidx.compose.material.DropdownMenu
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.input.pointer.PointerEventType
import androidx.compose.ui.input.pointer.PointerIcon
import androidx.compose.ui.input.pointer.onPointerEvent
import androidx.compose.ui.input.pointer.pointerHoverIcon
import androidx.compose.ui.unit.DpOffset
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication

@OptIn(ExperimentalComposeUiApi::class)
fun main() = singleWindowApplication {
    val displayHover = remember { mutableStateOf(false) }
    var text by remember { mutableStateOf("Hello, World!") }

    Column(
        modifier = Modifier
            .onPointerEvent(PointerEventType.Enter) {
                displayHover.value = true
            }
            .onPointerEvent(PointerEventType.Exit) {
                displayHover.value = false
            },
    ) {
        Button(
            onClick = { text = "Hello, Desktop!" },
            modifier = Modifier.pointerHoverIcon(PointerIcon.Hand)
        ) {
            Text(text)
        }
        DropdownMenu(
            displayHover.value,
            onDismissRequest = {
                displayHover.value = false
            },
            modifier = Modifier.background(MaterialTheme.colors.background),
            offset = DpOffset(x = 0.dp, y = 0.dp),
        ) {
            Text("My tooltip")
        }
    }
}
```
To fix the issue, you should pass `focusable = false`:
```
DropdownMenu(
    displayHover.value,
    onDismissRequest = {
        displayHover.value = false
    },
    modifier = Modifier.background(MaterialTheme.colors.background),
    offset = DpOffset(x = 0.dp, y = 0.dp),
    properties = PopupProperties(focusable = false)
) {
    Text("My tooltip")
}
```
When popup is focusable, it steals all hover/move/click events from the background content.

What happens:
1. hover the button
2. the button receives `PointerEventType.Enter`, displayHover = true
4. show DropdownMenu
5. the button receives `PointerEventType.Exit`, displayHover = false
6. hide DropdownMenu

So, we constantly show/hide the dropdownmenu. Changing the pointer icon is only a side effect of this.

This works as designed in 1.5. Before 1.5 we had inconsistent popup behavior, and allowed to pass all hover/move event to the background for focusable popups. This was a bug, as it doesn't behave as it was designed with `focusable  = true` (the default DropdownMenu value).

As for the clicks - they also aren't allowed to be passed behind focusable popups, only `onDismissRequest` should be called. The reason why clicks worked before 1.5 - clicks react to Release event, and Release event was passed after we closed the popup to response to `onDismissRequest`. Now Release isn't passed when we hide the popup.

Will `focusable = false` completely solve your issue?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3750">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
