### ISSUE TITLE
Support receiving media keys events

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#3756]
Currently, in compose desktop, `onKeyEvent` does not receive media keys (e.g. play, pause, next). Since compose manages windows creation, any workaround would be a hack. It would be ideal if compose multiplatform could support media keys events.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3756">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
