### ISSUE TITLE
Fatal error when creating undecorated and transparent window on Windows 11

### ISSUE THREAD

**Issue by franmatesic** [JetBrains/compose-multiplatform#3757]
**Describe the bug**
Getting a fatal error when trying to create a undecorated and transparent window on Windows 11:

```
A fatal error has been detected by the Java Runtime Environment:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff974f07061, pid=5700, tid=6040

JRE version: OpenJDK Runtime Environment (20.0.2+9) (build 20.0.2+9-78)
Java VM: OpenJDK 64-Bit Server VM (20.0.2+9-78, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
Problematic frame:
V  [jvm.dll+0x437061]
``` 

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.2
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64): AMD64
- JDK (for desktop issues): 20.0.2

**To Reproduce**
```kotlin
fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
        undecorated = true,
        transparent = true,
        ) {
        Box(Modifier.size(64.dp, 64.dp)) {
            Text("Hello World!")
        }
    }
}
``` 

**Expected behavior**
Program should create a transparent window.

**Additional context**
Started project on Windows 10 with described versions, but on x86 OS architecture and everything worked fine.
Opened project on Windows 11 and got this error.

**Comment by eymar** [comment]
There should be a file named like `hs_err_pid123123.log` added in the root folder of your project. 
Could you please post its content here? 
___

I tried to reproduce on my Windows 11 with the same versions:
```
JRE version: OpenJDK Runtime Environment (20.0.2+9) (build 20.0.2+9-78)
# Java VM: OpenJDK 64-Bit Server VM (20.0.2+9-78, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
```
But it doesn't crash in my case. I tried with differents JDK version and vendors - worked fine. 

Also in my case I see `org.jetbrains.skiko.RenderException: Failed to create DirectX12 device.` in the logs. It happens only when I have `transparent = true`. 
I guess it fall backs to software rendering in my case.  And it can be the reason why I can't reproduce. Do you see this line in the logs? 

Do you have the crash when `transparent = false`?
Can you please try different JDKs too?

**Comment by franmatesic** [comment]
I also get `org.jetbrains.skiko.RenderException: Failed to create DirectX12 device.`  on this machine and on the previous where it worked so I don't think that is part of the problem.
It works as expected when setting `transparent = false`. 
It's failing when setting `undecorated = true` and `transparent = true`.
I also tried this with JDKs 19 and 21, getting the same error on 19, but  `Unsupported Java` on 21.

Here's the error file:
[hs_err_pid5700.log](https://github.com/JetBrains/compose-multiplatform/files/12782895/hs_err_pid5700.log)

**Comment by eymar** [comment]
@igordmn Igor, do you have any ideas about how we can reproduce this on our side?

It crashes in [skiko-windows-x64.dll+0x598fc]
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.jetbrains.skiko.redrawer.WindowsOpenGLRedrawerKt.getDevice(J)J+0
j  org.jetbrains.skiko.redrawer.WindowsOpenGLRedrawerKt.access$getDevice(J)J+1
j  org.jetbrains.skiko.redrawer.WindowsOpenGLRedrawer$device$1.invoke(J)Ljava/lang/Long;+1
```

```kotlin
private external fun getDevice(platformInfo: Long): Long

...
JNIEXPORT jlong JNICALL Java_org_jetbrains_skiko_redrawer_WindowsOpenGLRedrawerKt_getDevice(JNIEnv *env, jobject redrawer, jlong platformInfoPtr)
```

Maybe `platformInfo: Long` is 0L.


Should we check that `val platformInfo: Long get() = getPlatformInfo(ptr)` is not `0L` like it's done for ptr?
https://github.com/JetBrains/skiko/blob/ed693b579e993cd8fe995b466c55c2fd7d285f88/skiko/src/awtMain/kotlin/org/jetbrains/skiko/AWT.kt#L65
It won't solve the issue, but can provide a better message.

**Comment by franmatesic** [comment]
> @franmatesic Could you please try just in case with Compose 1.5.10-beta02 (it has a newer skiko) and kotlin 1.9.20-Beta2?

Still doesn't work.
Error report is slightly different though: 
on line 661 `Internal exceptions (16 events):` instead of 15 events previously

**Comment by eymar** [comment]
We added some extra logs to skiko (0.0.0.7.81-dev41023) - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/skiko/skiko-awt-runtime-windows-x64/0.0.0.7.81-dev41023/

If you don't mind to try it out, so we can better understand what happens. 

To try it you would need to force gradle to use this version. It can be done like this:

```kotlin
// in root build.gradle.kts

allprojects {
    configurations.all {
         resolutionStrategy.eachDependency {
             if(requested.module.group.startsWith("org.jetbrains.skiko")) {
                  useVersion("0.0.0.7.81-dev41023")
             }
         }
    }
}
```
Please make sure you have `maven("https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev")` added to the repositories, that's where dev skiko artifacts are hosted. 
If you give it a try, please post the logs/stacktraces here.

**Comment by franmatesic** [comment]
I tried running older compose and kotlin versions, but no luck.

Here's the log when using newer version and skiko (0.0.0.7.81-dev41023):

[hs_err_pid11864.log](https://github.com/JetBrains/compose-multiplatform/files/12856230/hs_err_pid11864.log)

**Comment by AnmLobby** [comment]
I have the same problem as you, has it been solved?

**Comment by kingsword09** [comment]
the same

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3757">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by franmatesic** [comment]
Tried bumping up the versions for Kotlin and Compose and now it works.

```
#gradle.properties

kotlin.version=1.9.23
compose.version=1.6.11
```
