### ISSUE TITLE
Flicker When Setting `WindowState.size` to `DpSize.Unspecified`

### ISSUE THREAD

**Issue by ScottHamper** [JetBrains/compose-multiplatform#3760]
**Describe the bug**
Setting `WindowState.size` to `DpSize.Unspecified` after a window has been created often results in a brief flicker, in which the window seems to expand to fill the screen before resizing to fit its children.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.2
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): x86_64
- JDK (for desktop issues): 17

**To Reproduce**
```kotlin
fun main() = application {
    val state = rememberWindowState(size = DpSize.Unspecified)

    Window(
        onCloseRequest = ::exitApplication,
        state = state,
        title = "Adaptive Sizing Flicker Bug",
        resizable = false,
    ) {
        var width by remember { mutableStateOf(480.dp) }

        LaunchedEffect(width) {
            state.size = DpSize.Unspecified
        }

        Box(
            modifier = Modifier
                .background(Color.Red)
                .requiredWidth(width)
                .requiredHeight(width / 2)
        )

        MenuBar {
            Menu("View") {
                Item(text = "480x240", shortcut = KeyShortcut(Key.F1)) { width = 480.dp }
                Item(text = "800x400", shortcut = KeyShortcut(Key.F2)) { width = 800.dp }
                Item(text = "1024x512", shortcut = KeyShortcut(Key.F3)) { width = 1024.dp }
            }
        }
    }
}
```

Press F1/F2/F3 to change the window size (or interact with the menu bar items) and observe. The flicker does not always occur - it may take multiple resizes to reproduce.

**Expected behavior**
The window resizes to contain the child `Box` element without any intermediate sizing steps.

**Screenshots**
Here's a GIF with the frame time extended so we can see what's happening (in real time, the flicker is nearly instantaneous):
![flicker-bug](https://github.com/JetBrains/compose-multiplatform/assets/395192/8d0535fe-cbcc-4462-95a8-78e9a6d97daa)

**Comment by eymar** [comment]
Reproduced on macos with compose=1.5.10-beta02:
sometines the windows becomes completely white, and sometimes we can see red box shifted to the bottom

Tried on Ubuntu 22.04 - worked fine without flickering.
I'll check on windows 11 soon.

MacOs:

https://github.com/JetBrains/compose-multiplatform/assets/7372778/8c758aaf-3c35-4d43-b7b3-4d6b9f091c54

**Comment by eymar** [comment]
Reproduced the flickering on Windows 11 too.
But frequent white screen after resize issue seems to affect only MacOs.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3760">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
