### ISSUE TITLE
how to get IPA format release for IOS side?

### ISSUE THREAD

**Issue by adelsaramii** [JetBrains/compose-multiplatform#3767]
how we can get IPA format release for IOS side for App Store?

**Comment by pjBooms** [comment]
You may use regular XCode tooling for publishing iOS applications

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3767">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
