### ISSUE TITLE
is there way for Hex String Color format (#1F1F1E) to parse in Color

### ISSUE THREAD

**Issue by adelsaramii** [JetBrains/compose-multiplatform#3768]
in android side we used android.graphics.Color.parseColor for parsing Hex String Color
what is the solution in compose multiplatform

**Comment by adelsaramii** [comment]
> You can do it as in android compose:
> 
> ```kotlin
> androidx.compose.ui.graphics.Color(0xFF1F1F1E)
> ```

im lookin for multiplatform solution
is there a way?

**Comment by alexzhirkevich** [comment]
Yep

**Comment by adelsaramii** [comment]
> Yep. It works everywhere

because i get the color value from the backend i need to convert string format to Int/Long and this was my main problem 

**Sample**
val color = "0xFF1F1F1E"

when im using .toLong and .toInt it would crash
what should i do with this string to pass it in
androidx.compose.ui.graphics.Color()

**Comment by adelsaramii** [comment]
i find the solution in case if any one need it
[https://stackoverflow.com/a/69604651](url)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3768">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
