### ISSUE TITLE
Provide window snapping configuration parameter for `WindowDraggableArea` 

### ISSUE THREAD

**Issue by Skaldebane** [JetBrains/compose-multiplatform#3771]
**Describe the bug**
Hi! Window snapping using `WindowDraggableArea` doesn't work unfortunately. Snapping the window to one of the screen edges should work just like the native title bars.

**Affected platforms**
- Desktop (Linux, not tested on Windows/macOS)

**Versions**
- Kotlin version: 1.9.10
- Compose Multiplatform version: 1.5.2
- OS version: Fedora 38 / GNOME 44.5 (Wayland)
- OS architecture: x86
- JDK: Azul Zulu 17

**To Reproduce**
Create a `Column` with a `WindowDraggableArea` on top, and try to snap it. Tested on Linux only. (I can test Windows if needed)

**Additional context**
One question would be what if the `WindowDraggableArea` is not at the top of the window (maybe in the middle, or the bottom), but I think that doesn't matter much. When the mouse reaches the edge while dragging the draggable area, snapping should activate, no matter where the draggable area exists, or if itself doesn't reach the edge (e.g. when dragging the window to the top, the window will not move any further up).
It may also be a good idea to add a `snappingEnabled` parameter with a default value of `true` to customize this behavior.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3771">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
