### ISSUE TITLE
Can't drag a `Window` out of the screen bounds when using `WindowDraggableArea`

### ISSUE THREAD

**Issue by Skaldebane** [JetBrains/compose-multiplatform#3772]
**Describe the bug**
Hi! Using a `Window` ~_with `undecorated` and `transparent` parameters set to `true`_~, and a `WindowDraggableArea` to provide a custom header for users to drag the window, we can't seem to move the window outside of the screen bounds, to the right, left, or bottom like we can do with a normal, decorated window, which can be dragged out of the screen in all directions except the top of the window.

This is *not* about multiple monitors and dragging the window between them. The issue is about the whole "screen", the virtual space spanning all monitors. I only have one monitor and haven't tested the multi-monitor case.

**Update:** it doesn't matter if the `Window` is `undecorated`, dragging using a `WindowDraggableArea` always exhibits the same behavior. The native top bar doesn't have this issue. 

**Affected platforms**
- Desktop (Linux, not tested on Windows/macOS)

**Versions**
- Kotlin version: 1.9.10
- Compose Multiplatform version: 1.5.2
- OS version: Fedora 38 / GNOME 44.5 (Wayland)
- OS architecture: x86
- JDK: Azul Zulu 17

**To Reproduce**
Create an _~undecorated, transparent~_ `Window` with a `WindowDraggableArea` in it. Dragging the window works, but only when the entire window is inside the screen. Trying to move it such that only part of it is outside the screen doesn't work.

**Expected behavior**
Window should move outside the screen at least through the right, left, and bottom edges.

**Additional context**
I think it might be great if this behavior is customizable, allowing us to set the edges we want to allow the window to go through, with the default value being set to the right, left, and bottom, just like how it works with the native decorations.

This might be related to #3771.

**Comment by pjBooms** [comment]
I tested this sample on Mac (for another [issue](https://github.com/JetBrains/compose-multiplatform/issues/3709) with `WindowDraggableArea`): https://github.com/dima-avdeev-jb/issue-3709
 
and I am not sure what you mean. I noticed that moving window between screens using  `WindowDraggableArea` definitely has an issue (there is no "preview" of the window on another monitor until it is really moved to another monitor). 
However I have not noticed differences when moving the window out of the screen bounds when using `WindowDraggableArea` and usual title bar. Maybe it is a Linux specific -- can you record a video on what you mean? Do you have several virtual screens on Linux (so you are trying to move the window to another virtual screen)?

**Comment by Skaldebane** [comment]
Thanks for the response! No, I'm not trying to move between virtual screens (workspaces).

Here's a video:

https://github.com/JetBrains/compose-multiplatform/assets/35589610/375f275d-1ffe-4d71-91d4-b2b1d3512744

You can see how the window can go through the edges of the screen when using the native title bar, but can't do that when using the `WindowDraggableArea`.

Apparently this video also shows another bug: trying to move the `WindowDraggableArea` when there's also the native title bar, the window immediately moves down by the height of the native title bar (sometimes). I normally have the native title bar disabled, but enabled it here for the sake of demonstration, that's why I never noticed that before. But that's for another issue, I guess.

**Comment by m-sasha** [comment]
It's probably this issue: https://bugs.openjdk.org/browse/JDK-8205204

**Comment by Skaldebane** [comment]
That sure looks related, but it's not specific to undecorated windows, but for any "manual" handling of window position, just like Compose's `WindowDraggableArea`.

**Comment by m-sasha** [comment]
What happens in that ticket is exactly what happens here: attempting to set the location of the window such that it's (partially) outside the screen fails. Most likely `Window.setLocation` simply prevents it, or coerces the bounds to be fully inside the screen.

**Comment by Skaldebane** [comment]
Java issues like these make me believe much more in Kotlin/Native support for Compose Desktop, since we can wire it up directly to a low-level windowing library without these limitations.

We can also take the path that Jetbrains took with their IDEs and have thin native wrappers over some system APIs that allows us to break out of Java's limitations and have more when needed.

For example, IntelliJ IDEs merge their top bar with native window controls on Windows and macOS and control them as they like.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3772">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
