### ISSUE TITLE
Support FontFamily from a ttc font

### ISSUE THREAD

**Issue by sdercolin** [JetBrains/compose-multiplatform#3774]
Currently, we can only create a `FontFamily` by passing multiple `Font` instances.
However, it's difficult to extract individual font data and create `Font` instances because of the complexity of the ttc file structure.

I tried the `TypeFace` way as well, but it doesn't work because of
1. `SkiaTypeface.makeFromFile` fails when index > 0
2. We don't have APIs to merge typefaces into a font family

```kotlin
var index = 0
val typefaces = mutableListOf<TypeFace>()
// using org.apache.fontbox.ttf.TrueTypeCollection to parse the ttc 
ttc.processAllFonts { font ->
    val skiaTypeface = SkiaTypeface.makeFromFile(fontFile.absolutePath, index) // when index > 0, gets error
    val typeface = TypeFace(skiaTypeface)
    typefaces.add(typeface)
    index++
}

val fontFamily = FontFamily(typefaces) // we don't have such API
```

So we would have to ask users to convert the ttc fonts they want to use into ttf/otf files, which is inconvenient.
Would we have a chance to support this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3774">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
