### ISSUE TITLE
First screen is recomposed twice on iOS

### ISSUE THREAD

**Issue by pjBooms** [JetBrains/compose-multiplatform#3778]
The following code snippet:

```
@Composable
fun App() {
    val value = remember(LocalDensity.current) {
        (1..100).random()
    }
    println("Density: ${LocalDensity.current}")
    println("value is $value")
}
```

results in the following output:

```
Density: DensityImpl(density=1.0, fontScale=1.0)
value is 15
Density: DensityImpl(density=3.0, fontScale=1.0)
value is 34
```

on iOS.

That may have side effects like in the #3766 issue.

We should initialize density to correct value  before first composition to eliminate this.

**Comment by elijah-semyonov** [comment]
@dima-avdeev-jb 
We need to defer first recomposition until `didMoveToWindow` was called. That's when density is available.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3778">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
