### ISSUE TITLE
How do I load and display PDF files in Compose for desktop?

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/compose-multiplatform#3780]

**Comment by pjBooms** [comment]
Compose for Desktop does not have such a functionality out of the box and it is not planned to add it. You may look for third party solutions.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3780">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
