### ISSUE TITLE
Difference in Dialog between desktop and android causing error

### ISSUE THREAD

**Issue by Irineu333** [JetBrains/compose-multiplatform#3781]
**Describe the bug**
Difference in Dialog component parameters between desktop and android is causing compilation error.

**Affected platforms**
Select one of the platforms below:
- Desktop
- Android

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.3
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64): x86 
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a multiplatform project with android and desktop targets, and compose multiplatform 1.4.3
2. Implement a Dialog in the shared module
3. Run on android

**Expected behavior**
It should compile, after all they both point to being the same version.

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/45833588/eeb1aff0-2eb2-45a1-bfca-00eb60c1a112)
![image](https://github.com/JetBrains/compose-multiplatform/assets/45833588/3fc9ffbf-bb10-495a-8ba3-4b957c6beb6c)

**Comment by pablichjenkov** [comment]
I advise trying a more recent version of CMP

**Comment by pjBooms** [comment]
Dialogs in common code are available since CMP 1.5.0

**Comment by Irineu333** [comment]
@pjBooms I understand, how can I make these desktop-specific codes not appear in common?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3781">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
