### ISSUE TITLE
How to decode region of an image and downsample it on a desktop platform?

### ISSUE THREAD

**Issue by panpf** [JetBrains/compose-multiplatform#3782]
I'm currently developing a zoomable Image component for Compose Multiplatform and I'm running into a tricky problem.

On the desktop platform I need an API similar to BitmapRegionDecoder on Android, which can decode the region of the image and downsample it.

I searched google and stackoverflow but couldn't find the answer I wanted. Is there a similar API on the Compose Multiplatform platform?

**Comment by pjBooms** [comment]
Compose Multiplatform does not have a similar API out of the box and unfortunately I am not aware about third party solutions.

**Comment by m-sasha** [comment]
There's probably a Java API (possibly 3rd party) that does this.

**Comment by panpf** [comment]
> There's probably a Java API (possibly 3rd party) that does this.

Great. What's your name, please?

**Comment by elijah-semyonov** [comment]
> > There's probably a Java API (possibly 3rd party) that does this.
> 
> Great. What's your name, please?

Does [this](https://www.baeldung.com/java-resize-image) help?

**Comment by panpf** [comment]
The [ImageReader](https://docs.oracle.com/javase/8/docs/api/javax/imageio/ImageReader.html) class that comes with JDK can decode region and downsample, but it can only be used on the desktop. I still need a kotlin multiplatform dedicated image decoding library.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3782">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
