### ISSUE TITLE
Increase the size of libapplauncher.so

### ISSUE THREAD

**Issue by SudoDios** [JetBrains/compose-multiplatform#3783]
**Describe the bug**
Hi.
Hello
I used to get the output of the Release Deb package, the size of libapplauncher.so was 1.6Mb, but now it is 2.3Mb.
I have not made any changes in the project and the compose version.
I just went from ubuntu 20 to 22.
Why is the size increased ?
Of course, I think this is related to jdk (jpackage), right ?

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.2
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 22.04
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 18

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3783">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
