### ISSUE TITLE
BottomSheetScaffold m3 fully collapse even if you set sheetPeekHeight

### ISSUE THREAD

**Issue by adelsaramii** [JetBrains/compose-multiplatform#3784]
im using BottomSheetScaffold material3 and when i navigate and navigate back to the target screen
if you drag down the sheetContent it will fully collapse (ignore the min sheetPeekHeight we set)

bottom sheet:

    BottomSheetScaffold(
        sheetContent = {
            HomeBottomSheetNavigation(
                state = state,
                modifier = Modifier.fillMaxSize(),
                retryDailySummary = {
                    retryDailySummary()
                },
                retryAttendance = {
                    retryAttendance()
                },
                onSummaryItemClick = onSummaryItemClick,
                router = router
            )
        },
        sheetContainerColor = Color.White,
        sheetContentColor = Color.White,
        sheetPeekHeight = when (currentDestination.value) {
            HomeNavigation.Daily -> 550.dp
            HomeNavigation.Monthly -> 350.dp
        },
        modifier = modifier,
        scaffoldState = scaffoldState,
        sheetShape = RoundedCornerShape(topEnd = 16.dp, topStart = 16.dp),
    )

**Comment by pjBooms** [comment]
Is the same behavior reproduced on Android? If yes, please file the issue in Jetpack Compose issue tracker, if it is not, please provide a complete reproducible example.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3784">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
