### ISSUE TITLE
Add option to copy line break or custom string among multiple text in SelectionContainer

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#3787]
For a composable like this:
```
SelectionContainer {
    Column {
        Text(text = "abc")
        Text(text = "def")
    }
}
```

After selecting all the text and copy, "abcdef" is copied. It would be great if "abc\ndef" can be copied instead, and the separator can be configurable so that other layouts (e.g. Row {}) and Windows platform could also benefit.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3787">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
