### ISSUE TITLE
Unresolved reference: useResource

### ISSUE THREAD

**Issue by Andrew0000** [JetBrains/compose-multiplatform#3788]
**Describe the bug**
I created a Compose Multiplatform project in IntelliJ IDEA 2023.1 with desktop and android targets.
In **commonMain** I use:
```
import androidx.compose.ui.res.loadImageBitmap
import androidx.compose.ui.res.useResource

val image = useResource("img_1.png") { loadImageBitmap(it) }
```
for drawing images from commonMain resources. 
It works when I launch desktop target.
But when I try to launch android target, there is a build error:
`e: file:///C:/projects/.../App.kt:... Unresolved reference: useResource`

**Affected platforms**
Android in combination with Compose Multiplatform.

**Versions**
- Kotlin version*:  
There is nothing about version in templates that IDEA creates, just general declaration (which is another point to improve):
```
plugins {
    kotlin("multiplatform") apply false
    kotlin("android") apply false
    id("com.android.application") apply false
    id("com.android.library") apply false
    id("org.jetbrains.compose") apply false
}

plugins {
    kotlin("multiplatform")
    id("org.jetbrains.compose")
    id("com.android.library")
}
```
- Compose Multiplatform version*: 
There is nothing about version in templates that IDEA creates, just general declaration:
```
val commonMain by getting {
    dependencies {
        api(compose.runtime)
        api(compose.foundation)
        api(compose.material)
    }
}
```
- OS version(s)* (required for Desktop and iOS issues):  Windows
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues):  16

**To Reproduce**
1. Create Compose Multiplatform project in IDEA with desktop and android targets.
2. Use `androidx.compose.ui.res.loadImageBitmap` and related functions in commonMain
3. Try launch desktop target. It should work.
4. Try launch android target
5. See errors like this: `e: file:///C:/projects/.../App.kt:... Unresolved reference: useResource`

**Expected behavior**
Android depends on commonMain that works. Obviously dependent module should work as well.

**Screenshots**
Project structure (default by IDEA):  
![image](https://github.com/JetBrains/compose-multiplatform/assets/4018244/d0097b4d-8ce3-4fe5-ab53-3f1690f21ad5)

**Comment by MatkovIvan** [comment]
Hi @Andrew0000,

`useResource` [is defined in desktop sourceset](https://github.com/JetBrains/compose-multiplatform-core/blob/cc225fb05d0605c23c9b33b7b1b6657f524ebaa5/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/res/Resources.desktop.kt#L36) and NOT available on other platforms and in common source set.

> Android depends on commonMain that works. Obviously dependent module should work as well.

Currently common code is not compiled on its own, the code is just included to each platform compilation. It's possible subject to change in future to resolve IDE's issues like that. See [this explanation](https://youtrack.jetbrains.com/issue/KT-22841/Prohibit-different-member-scopes-for-non-final-expect-and-its-actual#focus=Comments-27-8182106.0-0)

Related issues:
- https://github.com/JetBrains/compose-multiplatform/issues/1456
- https://github.com/JetBrains/compose-multiplatform/issues/3503

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3788">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
