### ISSUE TITLE
Window flashes with background color when disposed

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#3790]
**Describe the bug**

When a compose `Window` is disposed, it briefly flashes its background color (white)

**Affected platforms**
- Desktop

**Versions**
- Compose Multiplatform version*: 1.5.2
- OS version(s)* (required for Desktop and iOS issues):  macOS
- JDK (for desktop issues): Correto 17.0.8, but probably doesn't matter

**To Reproduce**

Run this and close the window:

```
fun main() = application {
    var windowOpen by remember { mutableStateOf(true) }
    if (windowOpen) {
        Window(
            onCloseRequest = { windowOpen = false }
        ) {
            Box(
                Modifier
                    .fillMaxSize()
                    .background(Color.Black)
            )

        }
    }
}
```

**Expected behavior**
The window should not flash white.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/5230206/2d55a91e-9053-4419-bd3d-8c6e6db5849f

**Additional context**

At first glance, it doesn't seem the problem is with anything Compose doing wrong, such as removing its content before disposing the window. Removing all Compose code from the disposal process still results in a flash.

Perhaps the problem is in Skiko, or just an inherent problem with not drawing to the AWT `Graphics`.

**Comment by m-sasha** [comment]
A reasonable workaround is to set the window's background to the background color of your compose content, e.g.

```
            LaunchedEffect(window) {
                window.background = java.awt.Color.BLACK
            }
```

**Comment by m-sasha** [comment]
Closing, as I accidentally posted it on the wrong project. In any case, this will be the ticket for this issue: https://youtrack.jetbrains.com/issue/CMP-5651

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3790">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
