### ISSUE TITLE
Duplicate call of src in configureWix causes "Duplicate destination file" error

### ISSUE THREAD

**Issue by yttrian** [JetBrains/compose-multiplatform#3792]
**Describe the bug**
Using `apply` on `maybeCreate` causes multiple sources to be configured for `:downloadWix` causing it to fail when run.

https://github.com/JetBrains/compose-multiplatform/blob/d7a82a473261ac5397a2a3b39c0586f2b5a41fba/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/wixToolset.kt#L42-L44

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.0
- OS version(s)* (required for Desktop and iOS issues): Windows 11 (22621.2361)
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): Corretto 17.0.8

**To Reproduce**
1. Create two subprojects that use the Compose plugin
2. Run `packageMsi`

**Expected behavior**
`downloadWix` should not throw the "Duplicate destination file 'wix311.zip'" error.

**Additional context**
Using `maybeCreate` creates or returns an existing task. Calling `dest` updates the destination file, however `src` adds the source to a list. When `DownloadAction` from Undercouch Download tries to `getOutputFiles` it sees two sources but one destination and fails the build.

**Comment by eymar** [comment]
Could you please create a simple reproducer project? It would help us a lot.

**Comment by yttrian** [comment]
https://github.com/yttrian/compose-wix-error-sample

**Comment by dsvoronin** [comment]
Registering download and unzip tasks like that helps:

```
    val download = root.tasks.findByName(DOWNLOAD_WIX_TOOLSET_TASK_NAME) ?: root.tasks.register(
        DOWNLOAD_WIX_TOOLSET_TASK_NAME,
        Download::class.java
    ) {
        it.onlyIf { !zipFile.isFile }
        it.src("https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip")
        it.dest(zipFile)
    }
    val unzip = root.tasks.findByName(UNZIP_WIX_TOOLSET_TASK_NAME) ?: root.tasks.register(
        UNZIP_WIX_TOOLSET_TASK_NAME,
        Copy::class.java
    ) {
        it.dependsOn(download)
        it.from(project.zipTree(zipFile))
        it.destinationDir = unzipDir.ioFile
    }
```

**Comment by eymar** [comment]
@dsvoronin thanks!

**Comment by dsvoronin** [comment]
Hey @eymar , this issue has confusing "Wait for reply" label. Is there something missing to close it?
I saw your PR that should solve this issue. Did it land in the latest 1.5.11? Or when to expect it?

**Comment by eymar** [comment]
Yes, it's in 1.5.1. closing

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3792">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
