### ISSUE TITLE
Mouse Exit event not fired with context menu

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#3793]
**Describe the bug**

I have a component that has a hover state. It normally works, but when I introduce a context menu via ContextMenuArea there is a bug. If the user opens a context menu and then exits the component, an exit event is never fired.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*:  1.9.20-Beta2
- Compose Multiplatform version*: 1.5.10-beta02
- OS version(s)* (required for Desktop and iOS issues): MacOs
- OS architecture (x86 or arm64):  arm64
- JDK (for desktop issues): JDK 20

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a hoverable componet in the official way: https://blog.jetbrains.com/kotlin/2022/10/compose-multiplatform-1-2-is-out/#accessing-keyboard-modifiers
2. Wrap it in a `ContextMenuArea`
3. Observe that exit events are not fired when the context menu is open. Even after the context menu is closed, the exit event is not fired. 
4. Observe that it is possible for two components that are not connected on the screen to both have a hovered state of true at the same time due to this bug

**Expected behavior**

If the mouse exits the component while a context menu is open, then an exit event should fire at some point. I am not sure whether it should be fired before or after the context menu is closed.

**Comment by elijah-semyonov** [comment]
Repro:

```
import androidx.compose.desktop.ui.tooling.preview.Preview
import androidx.compose.foundation.ContextMenuArea
import androidx.compose.foundation.ContextMenuItem
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.size
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.PointerEventType
import androidx.compose.ui.input.pointer.onPointerEvent
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@OptIn(ExperimentalComposeUiApi::class)
@Composable
@Preview
fun App() {
    var text by remember { mutableStateOf("Hello, World!") }

    var hovered by remember { mutableStateOf(false) }
    MaterialTheme {
        ContextMenuArea(
            items = {
                listOf(
                    ContextMenuItem("hi1", { }),
                    ContextMenuItem("hi2", { }),
                    ContextMenuItem("hi3", { })
                )
            },
            enabled = hovered
        ) {
            Box(modifier = Modifier
                .size(200.dp)
                .background(Color.LightGray)
                .onPointerEvent(PointerEventType.Enter) {
                    hovered = true
                }.onPointerEvent(PointerEventType.Exit) {
                    hovered = false
                }
            ) {
                Text("Hover me and then press Ctrl $hovered", modifier = Modifier.align(Alignment.Center))
            }
        }
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}

```

https://github.com/JetBrains/compose-multiplatform/assets/4167681/ceb4c875-b4d7-4dc5-a106-8a92d7ada1e5

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3793">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
