### ISSUE TITLE
UIKitView turns white on trying embed child views

### ISSUE THREAD

**Issue by LaatonWalaBhoot** [JetBrains/compose-multiplatform#3797]
**Describe the bug**
Using UIKitView in conjunction with Compose multiplatform turns completely white on an iOS emulator device.

**Affected platforms**
- iOS

Versions
- Kotlin version: 1.9.10
- Compose Multiplatform version: 1.5.1 

**To Reproduce**
Using the following codebase

`@OptIn(ExperimentalForeignApi::class)
        @Composable
        actual fun Lottie(
            modifier: Modifier,
            animationRes: AssetResource,
            isPlaying: Boolean,
            isInfinite: Boolean,
            contentScale: ContentScale,
            speed: Float
        ) {
        
            var animation by remember { mutableStateOf<CompatibleAnimation?>(null) }
        
            LaunchedEffect(Unit) {
                animation = CompatibleAnimation(name = animationRes.path, subdirectory = "", NSBundle.mainBundle)
            }
        
            when(val value = animation) {
                null -> {}
                else -> {
                    val factory = remember {
                        {
                            CompatibleAnimationView(value).also {
                                it.setLoopAnimationCount(1.0)
                                it.setAnimationSpeed(speed.toDouble())
                                it.play()
                            }
                        }
                    }
        
                    UIKitView(
                        modifier = Modifier.fillMaxSize(),
                        factory = factory
                    )
                }
            }
        }`

**Expected behavior**
UIKitView should display the animation ideally. Replacing CompatibleAnimationView with UIButton also renders a completely white screen.

**Screenshots**
<img width="508" alt="Screenshot 2023-10-10 at 7 33 33 PM" src="https://github.com/JetBrains/compose-multiplatform/assets/30817376/123c32d3-ce04-4dd3-a381-695e7c9207d4">

**Comment by LaatonWalaBhoot** [comment]
Already tried that. Still the same result
Have followed this: https://github.com/JetBrains/compose-multiplatform/issues/3114

**Comment by elijah-semyonov** [comment]
I think it's related to [this one](https://github.com/JetBrains/compose-multiplatform/issues/3635), still not resolved.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3797">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
