### ISSUE TITLE
Feature request: Handling Deep link clicks from browser

### ISSUE THREAD

**Issue by rustamsmax** [JetBrains/compose-multiplatform#380]
I've implemented deep linking in android app. I also trying to achieve it in desktop version of this app.
But the handling must be processed outside the app. I think it's related to native distribution. 

I've googled and found related answer from stackoverflow: https://stackoverflow.com/questions/20074610/handle-custom-url-schemes-in-an-os-x-java-application

**Comment by rustamsmax** [comment]
For example the telegram app handles url schema starting with  t.me
 
![image](https://user-images.githubusercontent.com/36570577/107855021-c4494d80-6e41-11eb-9f98-45d0ed491f43.png)

**Comment by olonho** [comment]
Could you please elaborate why do you expect this kind of feature from UI toolkit Compose is? Looks like rather generic functionality that could be implemented in separate library. We not trying to implement all possible functionality inside Compose, to retain maintainability.

**Comment by rustamsmax** [comment]
What do you mean by separate library? Do we have to fork the desktop compose distribution plugin?

**Comment by olonho** [comment]
Cannot the app register click handlers on the first run? Why it shall be done in Gradle plugin at all?

**Comment by igordmn** [comment]
> Cannot the app register click handlers on the first run

If we don't run the application at all after the installation, then there no be registered pair "protocol -> application" in the OS. It should be part of the installer.

**Comment by jimgoog** [comment]
Maybe the installer can allow the user to run custom code as part of finalizing the install?

It would be ideal if something like this can be implemented by the user without needing custom support from our team for every little feature/thing that an installer might want to do.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5513">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
