### ISSUE TITLE
Hello, on an industrial tablet equipped with Windows 7 and Windows 10 systems, how to use Compose for desktop to bring up the system soft keyboard? Can this be achieved?

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/compose-multiplatform#3803]

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3803">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
