### ISSUE TITLE
Why commonMain cannot depend on java-library module under the same project

### ISSUE THREAD

**Issue by panpf** [JetBrains/compose-multiplatform#3805]
The project structure is as follows:
```kotlin
include(":zoomimage-compose")  // compose multiplatform, including androidMain, commonMain, desktopMain
include(":zoomimage-core-subsampling")  // java library
include(":zoomimage-core-zoomable")  // java library
include(":zoomimage-view")  // android library
```
zoomimage-view and zoomimage-compose's commonMain  requires depend zoomimage-core-subsampling and zoomimage-core-zoomable

The build configuration of zoomimage-compose is as follows:
```
sourceSets {
        named("commonMain") {
            dependencies {
                api(project(":zoomimage-core-zoomable"))  // invalid
                api(project(":zoomimage-core-subsampling"))  // invalid
                api(compose.foundation)
                api(compose.ui)
                api(compose.uiTooling.replace("ui-tooling", "ui-util"))
            }
        }
    }
```

The result is invalid. commonMain cannot access the classes within zoomimage-core-subsampling and zoomimage-core-zoomable. How can I solve this problem?

My current approach is to first publish zoomimage-core-subsampling and zoomimage-core-zoomable into jars and then use them in maven, as follows:
```
sourceSets {
        named("commonMain") {
            dependencies {
                api("io.github.panpf.zoomimage:zoomimage-core-zoomable:${property("versionName")}")
                api("io.github.panpf.zoomimage:zoomimage-core-subsampling:${property("versionName")}")
                api(compose.foundation)
                api(compose.ui)
                api(compose.uiTooling.replace("ui-tooling", "ui-util"))
            }
        }
    }
```
But this will bring many other problems, and I don't want to use it this way.

**Comment by MatkovIvan** [comment]
It might depend on your project targets, but in general `commonMain` is meant to be used on only in jvm based targets but also in js or iOS for example. If you want to share the same code between jvm-based targets I suggest you to use `jvmMain` instead.

Related doc: https://kotlinlang.org/docs/multiplatform-discover-project.html

Closing it as it's not related to Compose library.

**Comment by panpf** [comment]
Thanks! It seems that I need to change both `zoomimage-core-subsampling` and `zoomimage-core-zoomable` to multiplatform

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3805">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
