### ISSUE TITLE
Nested scrolling does not interopate with Swift UI scrolling on iOS

### ISSUE THREAD

**Issue by chrisbanes** [JetBrains/compose-multiplatform#3806]
**Describe the bug**

When you host a `ComposeUiViewController` within a scrolling container in either UiKit or Swift UI, the scrolling is messed up, as both views are trying to consume the touch events.

On Android, nested scrolling can be translated and propagated via `rememberNestedScrollInteropConnection()`, enabling Compose to work nicely with Android's nested scrolling. Can we do similar for iOS?

The simplest repro is to display some scrolling content within a `sheet` in Swift UI:

``` swift
struct ScrollingView: View {
    @State private var isShowingSheet = false
    
    var body: some View {
        HStack {
            Button(action: {
                isShowingSheet.toggle()
            }) {
                Text("Show License Agreement")
            }
        }
        .sheet(isPresented: isShowingSheet) {
            // ComposeUiViewController wrapped into UIViewControllerRepresentable
        }
    }
}
```

**Versions**
- Compose Multiplatform version*: 1.5.10
- OS version(s)*: iOS 17

**Comment by elijah-semyonov** [comment]
Hi, thanks for the report. We currently don't work on this specific scenario, but closely monitoring what people do with Compose to decide what to focus on.

**Comment by tylerwilson** [comment]
Same issue here: I have a Composable I am displaying in BottomSheet on Android, with a portion that is Column with vertical scroll enabled. The nestedScroll mostly solved the issue there.

Embedded same in iOS sheet results in not being able to scroll internal Column at all. 

Kindly request looking into handing this scenario. Thank you.

**Comment by syy555** [comment]
Same issue here, waiting for result

**Comment by tipsypotato** [comment]
+1

**Comment by jasin755** [comment]
+1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3806">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
