### ISSUE TITLE
App freezes on iOS if using VerticalScrollbar

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/compose-multiplatform#3807]
**Describe the bug**

The application may encounter freezing issues when utilizing the VerticalScrollbar.

I'm in the process of porting my production application, [Ashampoo Photos](https://ashampoo.com/photos), which is presently accessible on Windows and Android, to iOS. During the testing phase, I have observed instances of freezing while scrolling.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.3
- OS version(s)* (required for Desktop and iOS issues): iOS 17.0.3
- OS architecture (x86 or arm64): arm64

**To Reproduce**

Check out https://github.com/Ashampoo/scrollfreezereproducer and start the iOS application.

Allow the app to access all photos and restart it.

Engage with the scrollbar by holding the thumb and scrolling. Be aware that occasionally, it may require some time, but the application will ultimately freeze or halt the rendering process. This freezing issue tends to occur more frequently if the thumb is grasped during animated scrolling.

It's worth noting that the original application experiences freezing even more rapidly than the reproducer. Unfortunately, I am unable to disclose the complete code. Nevertheless, identifying the source of the problem will enable me to implement corrective measures.

**Expected behavior**

No freezes or render loop stopping.
VerticalScrollbar has no issues on Desktop.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3807">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
