### ISSUE TITLE
Screen transition lag on iOS 17.0 (simulator)

### ISSUE THREAD

**Issue by GuilhE** [JetBrains/compose-multiplatform#3808]
**Describe the problem**
I've updated to Xcode 15.0 and now using iOS 17.0 I'm noticing a screen transition lag when navigating between screens when running the app on the simulator (video attached below). On physical device (17.0.3) it's ok.

**Affected platforms**
- iOS

**Versions**
- Kotlin version: 1.9.10
- Compose Multiplatform version: 1.5.10-beta02
- OS version(s) (required for Desktop and iOS issues): 17.0
- OS architecture (x86 or arm64): arm64

**Sample code**
- https://github.com/GuilhE/Expressus
- Navigation being made [natively](https://github.com/GuilhE/Expressus/blob/6a739c1cb7e017226b938aa27ef44d1bd1de5f3c/iosApp/iosApp/Screens/ExpressusSelectorScreen.swift#L20)

**Reproduction steps**
Just run the app on iOS 17.0 simulator

**Video**

https://github.com/JetBrains/compose-multiplatform/assets/2677139/7c32bde5-2802-44cd-9675-4cc738643cf6

Same app on iOS 16.0 video sample [here](https://github.com/JetBrains/compose-multiplatform/issues/3492)

**Comment by GuilhE** [comment]
Tested, still happening with:

```
gradleComposeMultiplatform = "1.6.0-beta01"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
composeMultiplatformCompiler = "1.5.8-beta01"
androidxCompose = "1.6.0"
androidxComposeCompiler = "1.5.8-dev-k1.9.22-42b6ec2b037"
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3808">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
