### ISSUE TITLE
When installing the Msi installation package of Compose for desktop on a Windows 10 computer, the error in the picture occurred.

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/compose-multiplatform#3809]
**Describe the bug**

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0
- OS version(s)* (required for Desktop and iOS issues): windows10
- OS architecture (x86 or arm64): 64
- JDK (for desktop issues): 17

**Screenshots**
![微信图片_20231012134048](https://github.com/JetBrains/compose-multiplatform/assets/19502034/16672eeb-5661-48e0-9b17-98caddc04a76)
![微信图片_20231012134102](https://github.com/JetBrains/compose-multiplatform/assets/19502034/de1f9d24-29e6-475b-99e5-7f2f3d4f3f10)

**Comment by changhexuefei** [comment]
The reason for this problem is due to permission issues in Windows, which requires administrator rights to be installed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3809">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
