### ISSUE TITLE
Using Open GL with Compose Multiplatform 

### ISSUE THREAD

**Issue by wakaztahir** [JetBrains/compose-multiplatform#3810]
I have an app that is photo filters app, It applies filters on photos using Open GL, I've recently made the photo filter library multiplatform using `kgl` which is a kotlin multiplatform library that provides abstraction over Open GL.

On Android I can use a SurfaceView, on Desktop I need to integrate compose with Lwjgl or Jogl, on Web I do have a Canvas but no clear way to integrate Open GL with it alongside Compose

What I am looking for is a Multiplatform Compose Open GL Composable View
I can implement it on my own but there's no way to implement it

**Comment by elijah-semyonov** [comment]
> I can implement it on my own but there's no way to implement it

That sort of confused me.

There are no plans to make a general purpose widget OpenGL canvas a part of multiplatform. You can roll your own solution, using the interop APIs though, which will certainly require some tinkering.

**Comment by elijah-semyonov** [comment]
You will have to write `expect` wrappers around all GL functions you want to use, and implement the `actual`s for each platform.
I'm not sure about how you can use OpenGL to draw into Swing panel, which you can interop with iOS using `https://developer.apple.com/documentation/glkit/glkview?language=objc`.

Honestly, to me it seems quite a bad idea. If you need to draw custom stuff, perhaps have a look into `Canvas` widget? If it's 3D after all, Compose is just a wrong tool.

Even if some sort of 3D will be supported in the future, it will certainly be abstracted away from the specific graphics API.

**Comment by wakaztahir** [comment]
I have done this

> You will have to write expect wrappers around all GL functions you want to use, and implement the actuals for each platform.

I just need JVM & Web guide, On JVM I am using lwjgl or jogl, whatever works !
On Web, how can I make sure compose and webgl both render on to canvas and in their specific locations
So two composables, one for Web and one for Jvm that render Open GL View, I would love to do this on my own but I don't know how...

Photo processing is not performant enough and that's why I am using Open GL, I think Having a GL View inside compose is an actual use case, Because people write games with it and stuff and Open GL is used a lot. I am not implying that a multiplatform widget should be created for everybody to use, Just that APIs are available so this can be done.
I cannot just ditch Open GL since all of my code is already written using Open GL.

**Comment by wakaztahir** [comment]
Here's the Idea

### Android

I can use a `SurfaceView` wrapped in `AndroidView` Composable

### Web

On Web I get the underlying `Canvas` & webgl context, I also get the coordinates of the current composable using `BoxWithConstraints` and I call [`glViewport`](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glViewport.xhtml) with bounds of the current composable which will let Open GL draw into the `Canvas` only in the bounded region, Somehow I need to make sure Compose doesn't draw on this region

### JVM

I have no Idea, I am thinking Lwjgl Integration which currently requires some hacks.

**Comment by elijah-semyonov** [comment]
> Photo processing is not performant enough and that's why I am using Open GL, I think Having a GL View inside compose is an actual use case, Because people write games with it and stuff and Open GL is used a lot. I am not implying that a multiplatform widget should be created for everybody to use, Just that APIs are available so this can be done. I cannot just ditch Open GL since all of my code is already written using Open GL.

You can use custom Skia shaders for non-Android targets. Look at `RuntimeShaderBuilder`, `RuntimeEffect`.

**Comment by wakaztahir** [comment]
I cannot give up Open GL at the moment, It would mean rewriting everything, Maybe Vulkan one day since Open GL is deprecated

I guess I am going to keep using `SurfaceView` for Android and hope that multiplatform solutions catch up so that this is possible

I think Compose one day will have to use Open GL or Web GPU because Skia is 4 - 8 MB which is not doable when loading a web page & at the moment all my web apps load really slow, so I am not too worried, A multiplatform solution would've been more cleaner

**Comment by elijah-semyonov** [comment]
Multiplatform solution uses skia internally to perform rendering, there are not plans to change it to something for now. Even if we do it in platform specific way, it most likely be Vulcan for Desktop, wgpu for Web, and Metal for iOS.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3810">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
