### ISSUE TITLE
BasicTextField always crash on ios

### ISSUE THREAD

**Issue by NakiriYuuzu** [JetBrains/compose-multiplatform#3811]
**Describe the bug**
Using BasicTextField without English characters always causes crashes on iOS devices.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.10-beta02
- OS version(s)* (required for Desktop and iOS issues): iOS17

**Test**
BasicTextField input chinese or japanese after click to other basicTextField.

**Comment by dima-avdeev-jb** [comment]
Hello! Thanks for a bug description!
Is it reproduced on iOS simulator, or on real device?

What concrete language keyboards are you trying to use in iOS settings? Is it presented in this list?

<img width="234" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/9d6c918a-1306-40dd-8ba5-fe742abae0dd">

**Comment by NakiriYuuzu** [comment]
> Hello! Thanks for a bug description!
> 
> Is it reproduced on iOS simulator, or on real device?
> 
> 
> 
> What concrete language keyboards are you trying to use in iOS settings? Is it presented in this list?
> 
> 
> 
> <img width="234" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/9d6c918a-1306-40dd-8ba5-fe742abae0dd">
> 
> 

![image](https://github.com/JetBrains/compose-multiplatform/assets/72718339/32c68b3e-97a2-4cb6-b2a1-373452aabd94)

It is real device

**Comment by dima-avdeev-jb** [comment]
Ok, thanks!
I reproduced it!

**Comment by NakiriYuuzu** [comment]
> Ok, thanks! I reproduced it!

Ok thank you, 
here is the error message.

Uncaught Kotlin exception: kotlin.NotImplementedError: An operation is not implemented: implement isPosition
    at 0   iosApp                              0x102829baf        kfun:kotlin.Throwable#<init>(kotlin.String?){} + 123 
    at 1   iosApp                              0x1028235a3        kfun:kotlin.Error#<init>(kotlin.String?){} + 119 
    at 2   iosApp                              0x10295f693        kfun:kotlin.NotImplementedError#<init>(kotlin.String){} + 119 
    at 3   iosApp                              0x102f9e3d3        kfun:androidx.compose.ui.window.SkikoUIView.object-1.isPosition#internal + 263 
    at 4   iosApp                              0x102fa2527        _6f72672e6a6574627261696e732e636f6d706f73652e75693a75692f6f70742f6275696c644167656e742f776f726b2f356234626566333562333562396631322f636f6d706f73652f75692f75692f7372632f75696b69744d61696e2f6b6f746c696e2f616e64726f6964782f636f6d706f73652f75692f77696e646f772f536b696b6f5549566965772e6b74_knbridge178 + 311 
    at 5   iosApp                              0x1038ca623        _6f72672e6a6574627261696e732e636f6d706f73652e75693a75692f6f70742f6275696c644167656e742f776f726b2f356234626566333562333562396631322f636f6d706f73652f75692f75692f7372632f75696b69744d61696e2f6b6f746c696e2f616e64726f6964782f636f6d706f73652f75692f77696e646f772f536b696b6f5549566965772e6b74_kncfun179 + 11 
    at 6   UIKitCore                           0x108a58d73        -[UIResponder(UITextInput_Internal) _findPleasingWordBoundaryFromPosition:] + 75 
    at 7   UIKitCore                           0x108a58d07        -[UIResponder(UITextInput_Internal) _findBoundaryPositionClosestToPosition:withGranularity:] + 87 
    at 8   UIKitCore                           0x108a27e03        -[_UIKeyboardTextSelectionController selectPositionAtPoint:granularity:completionHandler:] + 335 
    at 9   UIKitCore                           0x108e2435b        -[UITextSelectionInteraction tappedToPositionCursorWithGesture:atPoint:granularity:completionHandler:] + 495 
    at 10  UIKitCore                           0x108e23d9b        -[UITextSelectionInteraction _checkForRepeatedTap:gestureLocationOut:] + 815 
    at 11  UIKitCore                           0x108e2486b        -[UITextSelectionInteraction _handleMultiTapGesture:] + 799 
    at 12  UIKitCore                           0x108b6ce8f        -[UIApplication sendAction:to:from:forEvent:] + 95 
    at 13  UIKitCore                           0x1085fd98b        -[UITextMultiTapRecognizer onStateUpdate:] + 163 
    at 14  UIKitCore                           0x1086b685f        -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 75 
    at 15  UIKitCore                           0x1086be253        _UIGestureRecognizerSendTargetActions + 87 
    at 16  UIKitCore                           0x1086bb91f        _UIGestureRecognizerSendActions + 295 
    at 17  UIKitCore                           0x1086bb07b        -[UIGestureRecognizer _updateGestureForActiveEvents] + 547 
    at 18  UIKitCore                           0x1086adfb3        _UIGestureEnvironmentUpdate + 2595 
    at 19  UIKitCore                           0x1086ad2af        -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 287 
    at 20  UIKitCore                           0x1086ad01f        -[UIGestureEnvironment _updateForEvent:window:] + 155 
    at 21  UIKitCore                           0x108ba19ff        -[UIWindow sendEvent:] + 3087 
    at 22  UIKitCore                           0x108b8168b        -[UIApplication sendEvent:] + 575 
    at 23  UIKitCore                           0x108c01013        __dispatchPreprocessedEventFromEventQueue + 1707 
    at 24  UIKitCore                           0x108c03ec3        __processEventQueue + 5519 
    at 25  UIKitCore                           0x108bfcf57        __eventFetcherSourceCallback + 155 
    at 26  CoreFoundation                      0x1803c669b        __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 23 
    at 27  CoreFoundation                      0x1803c65e3        __CFRunLoopDoSource0 + 171 
    at 28  CoreFoundation                      0x1803c5d53        __CFRunLoopDoSources0 + 231 
    at 29  CoreFoundation                      0x1803c043b        __CFRunLoopRun + 767 
    at 30  CoreFoundation                      0x1803bfd27        CFRunLoopRunSpecific + 571 
    at 31  GraphicsServices                    0x18986ebbf        GSEventRunModal + 159 
    at 32  UIKitCore                           0x108b67fdb        -[UIApplication _run] + 867 
    at 33  UIKitCore                           0x108b6bc53        UIApplicationMain + 123 
    at 34  SwiftUI                             0x10dc3c523        OUTLINED_FUNCTION_70 + 499 
    at 35  SwiftUI                             0x10dc3c3c3        OUTLINED_FUNCTION_70 + 147 
    at 36  SwiftUI                             0x10d94e107        OUTLINED_FUNCTION_2 + 91 
    at 37  iosApp                              0x10280a057        $s6iosApp6iOSAppV5$mainyyFZ + 39 
    at 38  iosApp                              0x10280a107        main + 11

**Comment by dima-avdeev-jb** [comment]
Fixed in [1.5.10-rc01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.10-rc01)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3811">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
