### ISSUE TITLE
Wrong cursor position after typing zero

### ISSUE THREAD

**Issue by elijah-semyonov** [JetBrains/compose-multiplatform#3812]
**Describe the bug**
Wrong cursor position after typing `0`.

https://github.com/JetBrains/compose-multiplatform/assets/4167681/048671cc-f434-4262-beab-98d3241b5bc7

**Affected platforms**
Select one of the platforms below:
- iOS

**Additional context**
Reported by **zfan93** from **kotlinglang** Slack

**Comment by m-sasha** [comment]
Is this using a StateFlow or some other indirection before updating the TextFieldValue?

**Comment by elijah-semyonov** [comment]
User uses StateFlow, deferring the input field update.
```
class PhoneScreenModel(private val navigator: Navigator) : MyViewModel() {
    val phone = MutableStateFlow("")
    fun updatePhone(newPhone: String) {
        if (newPhone.length <= 11 && newPhone.all { it.isDigit() }) {
            phone.value = newPhone
        }
    }
```
[It should be avoided](https://medium.com/androiddevelopers/effective-state-management-for-textfield-in-compose-d6e5b070fbe5).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3812">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
