### ISSUE TITLE
Disabling user scroll doesn't work for LazyRow with touchpad

### ISSUE THREAD

**Issue by gleb-skobinsky** [JetBrains/compose-multiplatform#3816]
**Describe the bug**
Creating a lazy row with `userScrollEnabled` set to `false` doesn't prevent the user from being able to scroll the list with the touchpad.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.3
- OS version(s)*: MacOS Ventura 
- OS architecture: arm64
- JDK (for desktop issues): Amazon Corretto 17.0.8

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create lazy row like this:
```
val scrollState = rememberLazyListState(1)
LazyRow(
    modifier = Modifier,
    state = scrollState,
    userScrollEnabled = false
) {
    ...
}
```
2. Try to scroll the lazy row with two fingers using touchpad
3. See the scroll

**Expected behavior**
No scrolling on the part of the user should be available.

**Screenshots**
The lazy row is used as a basis for a calendar widget to enable animated shifts between months. These details of implementation must be hidden from the user, however. The idea was to enable scrolling only with arrow buttons.
https://github.com/JetBrains/compose-multiplatform/assets/90451272/1140b9d2-abe8-4123-abc6-6ee25a2901bd

**Additional context**
I can still override user scroll events by adding this extension to the modifier:
```
fun Modifier.disableScroll() = this
    .pointerInput(Unit) {
        awaitEachGesture {
            val event = awaitPointerEvent(pass = PointerEventPass.Initial)
            if (event.type == PointerEventType.Scroll) {
                event.changes.onEach(PointerInputChange::consume)
            }
        }
    }
```
However, my impression is that the userScrollEnabled parameter is meant exactly for this, or am I wrong?

**Comment by elijah-semyonov** [comment]
The problem seems to be desktop only.

`MouseWheelScrollableElement` created in `Modifier.pointerScrollable` implementation ignores `enabled` argument.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3816">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
