### ISSUE TITLE
After upgrading to version 1.5.0, there is an issue with the display of Text content on iOS 11

### ISSUE THREAD

**Issue by DJ-LEE11** [JetBrains/compose-multiplatform#3817]
**Describe the bug**
With the Compose version 1.4.3, the display of text is normal on iOS 11, but after upgrading to version 1.5.0, there is an issue with the display of text on iOS 11, while it is normal on iOS 16.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.5.0
- OS version(s)* (required for Desktop and iOS issues): iOS 11.2.2
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create some Text like this:
```
@Composable
fun App() {
    Surface(color = Color(0xFFFFFFFF)) {
        Column {
            Text("Letter", Modifier.padding(top = 50.dp), color = Color.Red)
            Text(
                "Hello world!",
                color = Color.Black
            )
            Text("Number", Modifier.padding(top = 20.dp), color = Color.Red)
            Text(
                "2023.10.13 20:20",
                color = Color.Black
            )
            Text("Chinese", Modifier.padding(top = 20.dp), color = Color.Red)
            Text(
                "你好，世界！",
                color = Color.Black
            )
            Text("Symbol", Modifier.padding(top = 20.dp), color = Color.Red)
            Text(
                "~!@#$%^&*()_+{}:<>?|",
                color = Color.Black
            )
        }
    }
```

**Expected behavior**
Letter、Number、Symbol is normal on iOS 11.

**Screenshots**
iOS11、compose1.4.3、normal
<img width="517" alt="compose11old" src="https://github.com/JetBrains/compose-multiplatform/assets/30454011/a856770a-6310-44bf-9e8e-192e07667c9d">

**iOS11、compose1.5.0、abnormal**
<img width="512" alt="compose11new" src="https://github.com/JetBrains/compose-multiplatform/assets/30454011/bc28bbfa-31cd-489d-94ca-ee8eb46e5e34">

iOS16.6、compose1.5.0、normal
<img width="423" alt="compose14new" src="https://github.com/JetBrains/compose-multiplatform/assets/30454011/b581f87f-c865-4b1f-adf0-21930bc48aea">

**Comment by elijah-semyonov** [comment]
Hi, thanks for the report. I can't access the images. Unfortunately we dropped support for iOS 11 in Compose 1.5.0. Does the bug arise on iOS 12 as well?

**Comment by DJ-LEE11** [comment]
> Hi, thanks for the report. Unfortunately we dropped support for iOS 11 in Compose 1.5.0. Does the bug arise on iOS 12 as well?

I tried it, and iOS12 is well.

**Comment by elijah-semyonov** [comment]
Problem is not present on iOS 16, 15

**Comment by MatkovIvan** [comment]
Tested on iPad mini 2 (iOS 12.5.7) with `1.5.3` and the latest master state - it works fine, the issue was not reproduced

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3817">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
