### ISSUE TITLE
`AwtWindow`/`FileDialog` Closes When Parent Recomposes in Specific Situations

### ISSUE THREAD

**Issue by ScottHamper** [JetBrains/compose-multiplatform#3821]
**Describe the bug**
When using a composable function that abstracts around `AwtWindow`/`FileDialog` and accepts a parameter for the `FileDialog` parent, any composition changes in the parent `Window` seem to cause the `FileDialog` to close (via `setVisible(false)`).

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.3
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): x86_64
- JDK (for desktop issues): 17

**To Reproduce**
```kotlin
@Composable
fun FileDialog(
    parent: Frame,
    onCloseRequest: () -> Unit,
) = AwtWindow(
    create = {
        // Replacing `parent` usage here with `null as Frame?` prevents the bug from occurring.
        object : FileDialog(parent, "Load File", LOAD) {
            override fun setVisible(isVisible: Boolean) {
                if (isVisible) {
                    println("AWT FileDialog opening")
                }

                super.setVisible(isVisible)

                if (!isVisible) return

                println("AWT FileDialog closing")
                onCloseRequest()
            }
        }
    },
    dispose = FileDialog::dispose,
)

fun main() = application {
    Window(
        onCloseRequest = ::exitApplication,
        state = rememberWindowState(size = DpSize(width = 400.dp, height = 400.dp)),
        title = "AwtWindow Close On Recomposition Bug",
        resizable = false,
    ) {
        var count by remember { mutableStateOf(0) }
        var isFileDialogOpen by remember { mutableStateOf(false) }

        Column {
            // Commenting out the `Text` component prevents the bug from occurring.
            Text("$count")

            Button(
                onClick = {
                    println("Setting isFileDialogOpen to true")
                    isFileDialogOpen = true
                },
            ) {
                Text("Load")
            }
        }

        if (isFileDialogOpen) {
            LaunchedEffect(Unit) {
                delay(2000)
                println("Incrementing count")
                count++
            }

            // Replacing the `FileDialog` function call with its body will prevent the bug from
            // occurring.
            FileDialog(
                parent = window,
                onCloseRequest = {
                    println("Setting isFileDialogOpen to false")
                    isFileDialogOpen = false
                },
            )
        }
    }
}
```
1. Launch the program.
2. Click the "Load" button.
3. Wait two seconds.

**Expected behavior**
The `FileDialog` remains open while the main window behind it recomposes to display the updated `count` value.

**Screenshots**
![awtwindow-bug](https://github.com/JetBrains/compose-multiplatform/assets/395192/1b648e53-3c57-4295-aa62-dd30a8971ec7)

**Additional context**
Any one of a few small tweaks to the code can prevent the bug from occurring. Each of these can be done independently of each other to work around the issue:
- Don't observe `count` (comment out the `Text` component displaying its value).
- Remove the `FileDialog` composable function and inline its body where it is used in the main `Window`'s content.
- Pass in `null as Frame?` to the `java.awt.FileDialog` constructor.

I've also set up a number of print statements to trace order of execution. Here's the output for a sample run:
```
Setting isFileDialogOpen to true
AWT FileDialog opening
Incrementing count
AWT FileDialog opening
AWT FileDialog closing
Setting isFileDialogOpen to false
AWT FileDialog closing
Setting isFileDialogOpen to false
```

**Comment by m-sasha** [comment]
This sounds like it's been fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/863

Please try it in Compose 1.5.10-rc01

**Comment by ScottHamper** [comment]
Yes! The issue no longer occurs in `1.5.10-rc01`. Sorry for the extraneous issue, but thanks for your time!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3821">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
