### ISSUE TITLE
Any plans to support `App Extensions`?

### ISSUE THREAD

**Issue by robxyy** [JetBrains/compose-multiplatform#3826]
I've tried running `Compose` in [App Extensions](https://developer.apple.com/app-extensions/), but nothing is working so far.

Test code snippet:
```
let mainViewController = Main_iosKt.MainViewController()
present(mainViewController, animated: true)
```

<img src="https://github.com/JetBrains/compose-multiplatform/assets/9105106/1cfd950e-98ad-4450-a973-bcb8e28cb3f0" width="375" height="812">

**Comment by elijah-semyonov** [comment]
Thanks for the report. At some point we want to support all sensible usage scenarios. We still didn't approach this one in particular though, but we will certainly have a look at it at some point.

**Comment by cryptrr** [comment]
Okay. If I'm reading this right, Compose can't be used in Extensions like for example "Share Extension".

That is an unexpected bummer 😩

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3826">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
