### ISSUE TITLE
Invisible TextField on the outside screen.

### ISSUE THREAD

**Issue by NakiriYuuzu** [JetBrains/compose-multiplatform#3827]
**Describe the bug**
When click your own any TextField and type some word, then the invisible TextField (on the top screen) will show AutoFill selection.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.10-rc01
- OS version(s)* (required for Desktop and iOS issues): iOS17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. click your own any TextField
2. typing some word
3. it will show on the top screen

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/72718339/50f203e8-8586-45b4-b0bf-c4064bc6ffd9)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3827">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
