### ISSUE TITLE
required feature: interop for js/wasm target, like AndroidView or UIKitView

### ISSUE THREAD

**Issue by Gaubee** [JetBrains/compose-multiplatform#3832]
```kotlin
setContent{
  DomView(
    factory = { /* html-dom-element */ }
  )
}
```

**Comment by Hamamas** [comment]
Check this out
https://github.com/Hamamas/Kotlin-Wasm-Html-Interop

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3832">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
