### ISSUE TITLE
Desktop. Input methods popup has large offset

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3838]
Compose 1.5.10-rc01, checked on macOs/Windows

From [this comment](https://github.com/JetBrains/compose-multiplatform/issues/2628#issuecomment-1704562796)

When we type using input methods, the popup has large offset.

1. Install Chinese keyboard layout, choose it
2. Focus on a text field
3. Start typing
4. See the popup

Actual:
<img width="165" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/28809242/046dc760-9469-4e42-81f7-b85e7de24b6a">
Expect: 
<img width="156" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/28809242/7edcfca2-7f69-41dd-885f-470ea37fbe12">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3838">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
