### ISSUE TITLE
Desktop, macOs. Input methods always enabled, even if there is no TextField focused

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3839]
Compose 1.5.10, macOs (isn't reproducible on Windows/Linux)

1. Install Chinese keyboard layout, choose it
2. Open any Compose application
3. Start typing
4. See the popup

**Expected**
there is no popup

**Actual**
the input methods popup is shown, and users can type anything, even if it isn't received by any component
![image](https://github.com/JetBrains/compose-multiplatform/assets/5963351/98382d4f-6271-4736-87be-a287a56db861)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3839">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
