### ISSUE TITLE
Weird VoiceOver announcement for text fields with PasswordVisualTransformation

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#3842]
**Describe the bug**
For text fields with `visualTransformation = PasswordVisualTransformation()` VoiceOver correctly says it's a secure text element and it will not speak its content. But when you start typing it speaks "1 space c h a r a c t e r":

<img width="607" alt="Screenshot 2023-10-20 at 16 34 48" src="https://github.com/JetBrains/compose-multiplatform/assets/5230206/30970665-d61c-4327-8f55-749bcff0980c">

**Affected platforms**
- Desktop

**Versions**
- Compose Multiplatform version*: 1.5.10-rc01
- OS version(s)* (required for Desktop and iOS issues): macOS X Sonoma 14.0
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): corretto 17.0.9

**To Reproduce**
```
fun main() = = singleWindowApplication {
    var text by remember { mutableStateOf("") }
    TextField(
        value = text,
        onValueChange = { text = it },
        visualTransformation = PasswordVisualTransformation()
    )
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3842">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
