### ISSUE TITLE
iOS WKWebView NavigationDelegate methods with handlers doesn't work

### ISSUE THREAD

**Issue by slartus** [JetBrains/compose-multiplatform#3843]
**Describe the bug**
Overridden methods in NavigationDelegate with handlers do not work.
If you override the method, for example, of checking the availability of navigation and allow navigation to any URLs, then there will be a blank page.
When you remove this method, the links open.

example code: 
```
@OptIn(ExperimentalForeignApi::class)
@Composable
actual fun WebView(modifier: Modifier, url: String) {
    UIKitView(
        modifier = modifier,
        factory = {
            WKWebView(
                frame = CGRectZero.readValue(),
            ).apply {
                navigationDelegate = WKNavigationDelegate()
                loadRequest(
                    request = NSURLRequest(
                        uRL = NSURL(string = url),
                    )
                )
            }
        }
    )
}

class WKNavigationDelegate : NSObject(), WKNavigationDelegateProtocol {
    override fun webView(
        webView: WKWebView,
        decidePolicyForNavigationAction: WKNavigationAction,
        decisionHandler: (WKNavigationActionPolicy) -> Unit,
    ) {
        decisionHandler(WKNavigationActionPolicy.WKNavigationActionPolicyAllow)
    }
}
```
same behavior with certificate verification method:
```
override fun webView(
        webView: WKWebView,
        didReceiveAuthenticationChallenge: NSURLAuthenticationChallenge,
        completionHandler: (NSURLSessionAuthChallengeDisposition, NSURLCredential?) -> Unit
    )
```

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.2, 1.5.3
- OS version(s)* (required for Desktop and iOS issues): 16.4

**To Reproduce**
Download compose-multiplatform-template project and replace shared folder with [shared.zip](https://github.com/JetBrains/compose-multiplatform/files/13060203/shared.zip)

**Comment by KevinnZou** [comment]
I also encountered this issue in my [WebView project](https://github.com/KevinnZou/compose-webview-multiplatform) and could not find a solution.

**Comment by dima-avdeev-jb** [comment]
Hello! Thanks for Issue, you may try to use remember function to save a hard link to navigationDelegate:
```Kotlin
val rememberedNavigationDelegate = remember { WKNavigationDelegate() }
```
See examples here: https://github.com/dima-avdeev-jb/issue-3843-ios-webview

I will close this Issue, but if you will have some related questions, of something goes wrong - please feel free to reopen it

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3843">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
