### ISSUE TITLE
Make @Preview annotation accessible in commonMain

### ISSUE THREAD

**Issue by jbruchanov** [JetBrains/compose-multiplatform#3846]
I'm wondering why is the `androidx.compose.desktop.ui.tooling.preview.Preview` annotation
coming from `org.jetbrains.compose.ui:ui-tooling-preview-desktop` not working in commonMain ?
It gives me `No matching variant` error. Having it in jvmMain works fine.

![image](https://github.com/JetBrains/compose-multiplatform/assets/1651939/6e4c74b3-c240-4bc1-a549-cb6c5ef2a9f6)

It seems that IDE (or maybe compose plugin) needs the annotation to show the compose preview button. but that makes it quite hard to use if I need 
composable defined in commonMain, but the preview elsewhere. Presumably the preview doesn't really need any explicit platform context if it's moreless usable from IDE only.

Would be nice to be able to use `@Preview` annotation even in `commonMain` target...
Isn't there some workaround to have any argless composable function preview able ?

**Comment by codlab** [comment]
I'd really like to see this implemented as well. Currently what I do in my projects is to have the following :

- androidApp
- shared
  - commonMain
  - androidMain
  - jvmMain
  - ...
- uiApp <-
  - src/ <- symlink to shared/commonMain/src
  - build.gradle*'s dependencies mimicking shared/android's

**Comment by dima-avdeev-jb** [comment]
You can follow this issue: https://github.com/JetBrains/compose-multiplatform/issues/2045

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3846">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
