### ISSUE TITLE
Bug: Click indecator only triggers on double tap on Windows touch device

### ISSUE THREAD

**Issue by TheMrCodes** [JetBrains/compose-multiplatform#385]
### Bug: Click indecator only triggers on double tap on Windows touch device 

**Test environment:**
OS:  Windows
Device: Surface Laptop
Build: 152

**Described behavior shown in this short video:**
https://user-images.githubusercontent.com/28106561/107951800-2e283b00-6f99-11eb-9991-80ec8c5d0574.mp4

**Test source Code:**
```
@Composable
fun MainContent() {
    val TransparentRed = Color(255,0,0,50)
    val data = (0 until 1000).map { "Item $it" }
    LazyColumn(Modifier.fillMaxSize()) {
        items(data) { text ->
            val backColor = remember { mutableStateOf(Color.White) }
            Text(
                text,
                Modifier
                    .clickable {
                        println("Element $text clicked!")
                        backColor.value = if (backColor.value == Color.White) TransparentRed else Color.White
                    }
                    .background(backColor.value)
                    .padding(14.dp)
                    .fillMaxWidth()
            )
        }
    }
}
```

### Indicator animation doesn't finish properly on touchscreen devices

**Test environment:**
OS:  Windows
Device: Surface Laptop
Build: 153

**Description**
Click indicator animation get stuck wenn tapping on the touchscreen. The ripple fills the whole element and the background color stays the same as the color of the effect (maybe it extends indefinitely - do not know)

**Comment by TheMrCodes** [comment]
Update: This exect problem got fixed with build 153

A new problem appeared on the Microsoft Surface were the indicator get stuck after animation and the background color stays this color.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5511">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
