### ISSUE TITLE
iOS on-screen backspace not handled in `onPreviewKeyEvent`

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#3855]
**Describe the bug**

Backspace key not handled with iOS onscreen keyboard.
But it handled with physical keyboard on simulator.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.3, 1.5.10-rc01

**To Reproduce**
```Kotlin
Modifier.onPreviewKeyEvent { event ->
    if (event.key == Key.Backspace) {
        println("backspace pressed")
    }
}
```

Reproducer: https://github.com/dima-avdeev-jb/ios-simulator-preview-key-event-backspace

**Comment by farhazulmullick-pw** [comment]
@dima-avdeev-jb 
Do you know any workaround to detect backspace in iOS. Like how BasicTextField detect backspace.

**Comment by dima-avdeev-jb** [comment]
@farhazulmullick-pw Sorry, but I don't know any workaround

**Comment by SentsovSA** [comment]
Hello! Any updates about this bug?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3855">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
