### ISSUE TITLE
iOS keyboard loose focus when text field changes

### ISSUE THREAD

**Issue by KostadinAlmishev** [JetBrains/compose-multiplatform#3856]
**Describe the bug**
On iOS keyboard moves down and up when focus is changed to next text field. I tried to change onFocusBehavior = OnFocusBehavior.DoNothing in ComposeUIViewController, but nothing changed. On android keyboard is static as expected.

**Affected platforms**

- iOS

**Versions**
- Kotlin version: 1.9.10
- Compose Multiplatform version: 1.5.3
- iOS version: 17.0.3
- OS architecture: arm64

**To Reproduce**

- click on first text field
- click on second text field (keyboard goes down and up, but should not move)

**Expected behavior**
Keyboard should not move when text field focus is changed to next one like in android video.

**Video**

https://github.com/JetBrains/compose-multiplatform/assets/26711314/cdcf32a2-cdbd-4ebb-a653-297bd59c3aed

https://github.com/JetBrains/compose-multiplatform/assets/26711314/79a64f38-92f9-49f8-8417-8857b7fb9f53

**Additional context**
[Sample code to reproduce](https://github.com/KostadinAlmishev/ios-keyboard-sample)

**Comment by ruslantsyganok** [comment]
Same here

**Comment by Kashifmasood07** [comment]
Yep, we also faced the same issue, and eventually had to move to uikit textfields for ios.

**Comment by Kashif-E** [comment]
same issue

**Comment by Kashif-E** [comment]
@dima-avdeev-jb  can we expect this to be fixed with 1.6.0?

**Comment by dima-avdeev-jb** [comment]
@Kashif-E I will try to do it before 1.6.0 release

**Comment by Kashif-E** [comment]
@dima-avdeev-jb  can we expect a timeline? we have a pending ios release because of this

**Comment by Kashif-E** [comment]
@dima-avdeev-jb  any update on this?

**Comment by ASalavei** [comment]
https://github.com/JetBrains/compose-multiplatform-core/pull/964

**Comment by dima-avdeev-jb** [comment]
> @dima-avdeev-jb any update on this?

Sorry, not yet

**Comment by Kashif-E** [comment]
@ASalavei @dima-avdeev-jb in which update will this be available?

**Comment by ASalavei** [comment]
@Kashif-E , please try the latest dev build (`1.6.0-dev1357` for now)

**Comment by Kashif-E** [comment]
Thanks @ASalavei

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3856">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
