### ISSUE TITLE
Desktop: how to listen dock app icon click event

### ISSUE THREAD

**Issue by Caij** [JetBrains/compose-multiplatform#3863]
![image](https://github.com/JetBrains/compose-multiplatform/assets/8597839/c5212e45-900e-4b1a-9b0d-b1de13563608)

step:
1. click window close set window visible false

i want show window on click dock app icon (set visible true)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8597839/3baa1425-3a16-42d2-8c6d-cd1efd876aa3)

**Comment by Caij** [comment]
resolved
Desktop.getDesktop().addAppEventListener(object : AppReopenedListener {
                override fun appReopened(e: AppReopenedEvent) {
}

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3863">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
