### ISSUE TITLE
Support removing spacing between paragraphs

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#3866]
In Jetpack Compose, LineHeightStyle can be specified as an option to ParagraphStyle to remove additional spaces between paragraphs. According to the documentation:
> `trim` feature is available only when PlatformParagraphStyle.includeFontPadding is false.

https://developer.android.com/reference/kotlin/androidx/compose/ui/text/style/LineHeightStyle

In Compose Desktop, setting LineHeightStyle has no effect, and there is no `includeFontPadding` in the `PlatformParagraphStyle` class.

This is one of the blockers of implementing a soft-wrap-enabled code editor with line numbers.

**Comment by dima-avdeev-jb** [comment]
Thanks for Issue. We will discuss it in our team.

**Comment by ionull** [comment]
Hi, does it work on AnnotatedString?
`withStyle(
                ParagraphStyle(
                    textIndent = TextIndent(
                        firstLine = 0.sp,
                        restLine = 16.sp
                    ),
                    lineHeight = 16.sp,
                    platformStyle = PlatformParagraphStyle( includeFontPadding = false ),
                    lineHeightStyle = LineHeightStyle(
                        LineHeightStyle.Alignment.Center,
                        LineHeightStyle.Trim.Both
                    )
                )
            ) {
                content()
            }`

I tried with this but there is still margin after every paragraph.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3866">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
