### ISSUE TITLE
Explicit control over iOS StatusBarStyle

### ISSUE THREAD

**Issue by jdavisAR** [JetBrains/compose-multiplatform#3867]
It would be nice to be able to customize the icon color (light/dark) of the status bar icons. 

As of right now there is no way to explicitly tint the status bar icons light/dark. On newer version, the system will automatically tint the icons but for apps that target older version of iOS it would be nice to be able to control this behavior. This could be as simple as taking another lambda parameter in `ComposeUIViewController(...)`.

**Comment by dima-avdeev-jb** [comment]
Thanks for enhancment description!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3867">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by mianaliasjad** [comment]
any update on this? Is there a way to change ios status bar style in multi platform?
