### ISSUE TITLE
The Android Studio does not print all levels of logs for the iOSApp.

### ISSUE THREAD

**Issue by KevinnZou** [JetBrains/compose-multiplatform#3870]
**Describe the bug**
https://github.com/touchlab/Kermit/issues/380

When running the iOSApp from AS, only logs with a level above INFO will be printed. However, if we run it in Xcode, we can see all the logs. I believe this is a bug related to the KMM AS plugin, but I am unable to find where to submit the issue. Therefore, I am submitting it here.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.3

**To Reproduce**
You can directly test this project https://github.com/KevinnZou/compose-webview-multiplatform. Start by running it on desktop or Android, and then run iOSApp to observe the differences in the logs.

**Comment by dima-avdeev-jb** [comment]
Thanks!
I will told to KMM team.

Can you please provide a minimal reproducible sample?
In this sample should be easy to understand that logs are printer on AS, an what shoud to printed as well as in Xcode.

**Comment by KevinnZou** [comment]
@dima-avdeev-jb I think this would be enough to reproduce the bug https://github.com/KevinnZou/cmm-logger-sample

Basically, it should print out all 4 logs in AS when running on iOS target, but it just prints out the last two. Android and Desktop print all 4 logs.
```
Logger.v { "Verbose $showImage" }
Logger.d { "Debug $showImage" }
Logger.i { "Info $showImage" }
Logger.w { "Warn $showImage" }
```

**Comment by terrakok** [comment]
Could you file the issue here: https://youtrack.jetbrains.com/newIssue?project=KT&c=Subsystems+Apple+Ecosystem ?

**Comment by hanrw** [comment]
same issue with AppCode but not Xcode
AppCode show below
```shell
2024-03-10 22:35:21.140636+0800 Mint[29800:899637] 🟢 info
2024-03-10 22:35:21.140694+0800 Mint[29800:899637] 🟡 warning
2024-03-10 22:35:21.140731+0800 Mint[29800:899637] 🔴 error
```

Xcode shows below
```shell
🔵 debug
🟢 info
🟡 warning
🔴 error
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3870">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by slikasgiedrius** [comment]
I am also experiencing this exact issue. Is there any news on it?
