### ISSUE TITLE
Swift UI screen inside compose 

### ISSUE THREAD

**Issue by ismai117** [JetBrains/compose-multiplatform#3874]
I know there's examples showing Compose UI elements inside a Swift UI screen, but how do I do the opposite?

I've got a full compose multiplatform app with precompose navigation. I've got a splash screen with Lottie animation on the Android side.

How do I create a separate splash screen using SwiftUI so I can use Lottie-ios and other SwiftUI components?

**Comment by dima-avdeev-jb** [comment]
Hello! Right now we are preparing a way how you can experiment with that. Please stay tuned..

**Comment by sunny-chung** [comment]
And how about native views inside compose, would that be possible? I would like to use both Compose and third-party map views.

**Comment by sunny-chung** [comment]
This works because there is a Kotlin binding for the Apple MapKit. How about if I want to use views provided by third parties, e.g. a Mapbox map? Mapbox does not even have a SwiftUI implementation, just native views.

(Sorry for the distraction but this is the first question I seen about compose interoperability with iOS UI)

**Comment by dima-avdeev-jb** [comment]
@sunny-chung You can add thridparty libraries to project with cocapods
https://kotlinlang.org/docs/native-cocoapods.html#add-and-configure-kotlin-cocoapods-gradle-plugin
In this way you can use cocapods Compose project setup https://github.com/JetBrains/compose-multiplatform/tree/master/examples/cocoapods-ios-example

**Comment by anaesthez** [comment]
Hello, is there still no way to do it. Haven't you already have docs about it?
https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-ios-ui-integration.html#use-swiftui-inside-compose-multiplatform
Or I just misinterpreted your messages?...

**Comment by dima-avdeev-jb** [comment]
> Hello, is there still no way to do it? Haven't you already have docs referring it? https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-ios-ui-integration.html#use-swiftui-inside-compose-multiplatform Or I just misinterpreted your messages?...

You can use this doc.

**Comment by ismai117** [comment]
I was checking out the ios-swiftui-in-compose project, this is what i've been looking for but how do we use it for isolated components e.g. a bottom navigation or top bar

from looking at the sample project, the container is inside the window group - IosApp struct

**Comment by dima-avdeev-jb** [comment]
You can take a look to chat sample with SwiftUI bottom tab bar
https://github.com/JetBrains/compose-multiplatform/tree/master/examples/chat

It uses bottom tab bar as a separate SwiftUI view outside of Compose.

**Comment by dima-avdeev-jb** [comment]
Published documentation available https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-ios-ui-integration.html

**Comment by kumarmohit5189** [comment]
> > Published documentation available here https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-ios-ui-integration.html
> 
> last title says **Use SwiftUI inside Compose Multiplatform** but the example still shows swiftUI view in **ContentView.swift** file. How can I use ComposeEntryPointWithUIView kotlin function in my compose function?

@akardas16 are you able to use it? I am also interested in this. Say my first screen is compose multiplatform but second screen after navigation in in swiftUI for iOS. Any help here?

**Comment by michalguspiel** [comment]
This is doable in a completely different way than it is shown in the documentation.

https://gist.github.com/michalguspiel/9d0ae4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3874">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
