### ISSUE TITLE
Add offset information about selected text in TextContextMenu.

### ISSUE THREAD

**Issue by bezsahara** [JetBrains/compose-multiplatform#3875]
I have been trying to create a custom TextContextMenu for a text field via `LocalTextContextMenu provides CustomMenu`. However, in the Area function, you can find `textManager: TextContextMenu.TextManager` parameter there is no information about the position of selected text. You get an annotated string for styles, etc, but there is no offset information. Also, it would be nice to have the ability to turn off the context manager.

**Comment by eymar** [comment]
Could you please share more details how you would like to use the offset of the selected text?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3875">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
