### ISSUE TITLE
[Windows] TextField hangs under specific condition

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#3877]
**Describe the bug**
After setting a long text (around 350 KB), which is generated by a Jackson object mapper, to TextField, the application hangs forever. Currently, this issue seems to be only affecting Windows OS.

It does not reproduce when it is
- on macOS, or
- when the string is not processed by the Jackson library, or
- when the string is small

**Affected platforms**
- Desktop (Windows)

**Versions**
- Kotlin version*: 1.8.0, 1.8.20
- Compose Multiplatform version*: 1.5.2
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Run the sample project [here](https://github.com/sunny-chung/compose-desktop-textfield-long-text-issue).
2. The process hangs.

**Expected behavior**
Does not hang and show the text.

**Screenshots**
N/A

**Additional context**
Pausing the threads in debugger reveals the process stucks in the function `_nLayout` in `ParagraphKt`.

**Comment by eymar** [comment]
I made your snippet work by adding extra `replace("\r\n", "\n")`:

```kotlin 
longText = jacksonObjectMapper().readTree(longText).toPrettyString().replace("\r\n", "\n")
```

Small number of `\r\n` are not noticable. But the bigger their count, the more noticable the freeze.
```
        coroutineScope.launch {
            val longText = (0 .. 300 * 500).map { // 300 * 100 is less noticable. 300 * 500 will unfreeze eventually too
                val c = "abcdefghijklmnABCDEFGHIJK123456\":{}[] \n".random().toString()
                if (it % 20 == 0) return@map "\r\n"
                if (c == "\n") {
                    "$c    "
                } else {
                    c
                }
            }.joinToString("")

//            var longText = Thread.currentThread().contextClassLoader.getResourceAsStream("long-resp.txt")!!.readAllBytes().decodeToString()
//            longText = jacksonObjectMapper().readTree(longText).toPrettyString().replace("\r\n", "\n")
            println("longText has been prepared")
            text = text.copy(text = longText)
        }
        ```

**Comment by sunny-chung** [comment]
Thanks for the workaround and the findings. It unblocks my application development.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3877">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
