### ISSUE TITLE
Specifying minimum macOS version

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#3878]
Is there a way to specify minimum macOS version to run?

I tried to play with the `infoPlist` setting in build.gradle.kts to configure `LSMinimumSystemVersion` but have no progress. I could not find a way to set "minimum deployment target" as well.

**Comment by dima-avdeev-jb** [comment]
Are you want to use Compose for Desktop with JVM?

**Comment by sunny-chung** [comment]
Yes. I found artifacts built by recent macOS have a minimum requirement of 11.0, and I want to lower it to 10. I can workaround it by finding a mac with OS X 10.x to build.

**Comment by dima-avdeev-jb** [comment]
What behaviour are you want to achieve when User's want to launch your application on lower versions?

**Comment by sunny-chung** [comment]
Existing behaviour is fine -- showing an alert provided by OS. If application wants to behave differently, developer could set the lowest OS version as the minimum version, and handle that on app launch.

The only thing I am not sure is, if application uses a native library, and that library requires a newer OS to initialize or otherwise crashes, can the application developer detect the OS version beforehand and avoid the crash by not initializing the native library? This may need a JNI expert to answer.

**Comment by dima-avdeev-jb** [comment]
You Application may cheecking OS versions with JVM API on startup. Maybe it is not Compose related feautre.

```
System.out.println("OS Name: " + System.getProperty("os.name"))
System.out.println("OS Version: " + System.getProperty("os.version"))
```

**Comment by sunny-chung** [comment]
**Current Behaviour**

I produced a build via Compose Desktop in macOS 14.0, and then try to open it in macOS 10.15. Then, following OS dialog is shown, not even able to reach any part of the application.

<img width="532" alt="Screenshot 2023-10-31 at 9 29 34 PM" src="https://github.com/JetBrains/compose-multiplatform/assets/14835950/3a3d2b05-19ad-431d-82bc-7190a8e5cb5f">

**Feature Request**

Minimum OS version is configurable, so that I can set it to, for example, 10.8, and then able to open the application in macOS 10.15.

**Comment by eymar** [comment]
Hi @sunny-chung! 
> I tried to play with the infoPlist setting in build.gradle.kts to configure LSMinimumSystemVersion but have no progress

How exactly did you try to set LSMinimumSystemVersion?

Here is how I tried it and it works:
```
            macOS {
                infoPlist {
                    extraKeysRawXml = """
                        <key>LSMinimumSystemVersion</key>
                        <string>14.1</string>
                    """.trimIndent()
                }
            }
```

Then we can check that it's applied in:
```
.../notepad/build/compose/binaries/main-release/app/Notepad.app/Contents/Info.plist
```

I'm on macOS 13.5.2 and I see such message when I try to run the app:
<img width="267" alt="Screenshot 2023-10-31 at 15 07 03" src="https://github.com/JetBrains/compose-multiplatform/assets/7372778/214f4cd3-622f-463d-ba7a-dc68a83e0b84">
___

I don't think we'll extend the DSL for such configurations any time soon, since `extraKeysRawXml` should cover most of the custom cases.

**Comment by sunny-chung** [comment]
Please checkout this project and build on latest macOS version. I was using macOS 14.0. Note that `infoPlist` was customized to set minimum OS version to `10`.
https://github.com/sunny-chung/compose-desktop-app-icon-issue

Then, transfer the `.app` executable to macOS 10.x. The screenshot above shows upon the executable is launched.

Some people says "macOS deployment target" need to be set as well. I could not find a way to set this in the compose DSL nor via jpackage options.

If the app is compiled on macOS 10.x, it can be launched normally.

**Comment by eymar** [comment]
Unfortunately, I don't have two MacOS to try it. 
___

Could you please try to transfer not the .app, but .dmg? 

https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Native_distributions_and_local_execution#basic-usage

`./gradlew packageDmg` task

**Comment by sunny-chung** [comment]
Opening .dmg files yields the same result.

I found artifacts built by macOS 11.0 can be opened in macOS 10.x. I think the error shows because the artifacts were built by different CPU architectures, not related to OS versions. The error message shown by macOS is misleading.

The `extraKeysRawXml` looks adequate and is working as intended. I will close this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3878">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
