### ISSUE TITLE
iOS: TabView > UITableViewController > UIHostingController > Compose Configuration Causes Recompose and Horizontal Scroll Issues

### ISSUE THREAD

**Issue by 75py** [JetBrains/compose-multiplatform#3879]
**Describe the bug**
When integrating Compose Multiplatform within an iOS project that uses TabView (SwiftUI), UITableViewController, and UIHostingController, I experience the following issues:
1. Recomposition does not occur when pressing a button to change text in a Compose view. However, recomposition happens when I scroll the UITableView.
2. Horizontal scrolling is disabled in Compose views.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.3, 1.5.10-rc02
- OS version(s)*: iOS 17
- OS architecture: arm64

**To Reproduce**
1. Clone the minimum project at https://github.com/75py/Multiplatform-Sandbox
2. Navigate to the tab containing the UITableView.
3. Try clicking on a button inside the Compose view; observe that the text doesn't change.
4. Try scrolling horizontally; observe that horizontal scrolling is disabled.
5. Scroll the UITableView; observe that recomposition happens.

Main Code Files
- iOS: [ContentView.swift](https://github.com/75py/Multiplatform-Sandbox/blob/f9993c93eec26792d16c4ee93a4fdb274950e93e/iosApp/iosApp/ContentView.swift)
- Kotlin: [Views.kt](https://github.com/75py/Multiplatform-Sandbox/blob/f925bcd4ac7cdb78e58dfd407245f74625de3bb8/shared/src/commonMain/kotlin/com/nagopy/multiplatform/sandbox/Views.kt)

**Expected behavior**
1. The Compose view should recompose when pressing a button to change text.
2. Horizontal scrolling should work as expected in Compose views.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/3153211/f4b604ce-1d7b-4b4d-88db-5d1314e631b6

**Additional context**
The issue seems to occur only when using this specific configuration of TabView, UITableViewController, and UIHostingController.

**Comment by m-sasha** [comment]
LazyRow is already scrollable. You don't need to add a horizontalScrollable modifier to it.

**Comment by 75py** [comment]
I've recently updated the Compose plugin to version 1.6.0-beta01, and I'd like to share some updates regarding the issues previously reported:

1. The issue where the Compose view did not recompose when pressing a button to change text has been **resolved** with this update. This fix significantly improves the user interaction within Compose views on iOS.

2. Unfortunately, the problem with horizontal scrolling being disabled in Compose views **remains unresolved**. This continues to affect the usability of horizontally scrollable components in our iOS application.

You can view the changes made in this update here: [Tag Link](https://github.com/75py/Multiplatform-Sandbox/releases/tag/compose-multiplatform%2F3879%2F2).

I hope this information helps in tracking the progress of these issues. Looking forward to any suggestions or further updates on the unresolved matter.

https://github.com/JetBrains/compose-multiplatform/assets/3153211/ccc81e30-245b-45d1-8b05-9dc654880fc5

**Comment by tipsypotato** [comment]
Same here, looking forward to any workaround

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3879">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
