### ISSUE TITLE
Transparent windows don't work on Linux

### ISSUE THREAD

**Issue by Martmists-GH** [JetBrains/compose-multiplatform#3887]
**Describe the bug**
Creating a window with `Window(undecorated=true, transparent=true)` fails with 
```
[SKIKO] warn: Failed to create Skia OpenGL context!
java.lang.RuntimeException: Can't wrap nullptr
[SKIKO] warn: Exception in draw scope
org.jetbrains.skiko.RenderException: Cannot init graphic context
```

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.3
- OS version(s)* (required for Desktop and iOS issues): Arch Linux (all packages up-to-date)
- OS architecture (x86 or arm64): x86-64
- JDK (for desktop issues): Tried 11, 17 and 20.

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

```kt
fun main() = application {
    Window(undecorated = true, transparent=true, onCloseRequest = ::exitApplication) {
        // ...
    }
}
```

and use the `desktop` Gradle task.

**Expected behavior**
Transparent windows work as expected, instead of giving a warning and not displaying anything. Note that the application keeps running and doesn't throw a JVM Error.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by eymar** [comment]
I tried to reproduce on Ubuntu, but it worked fine.

> not displaying anything
Did you have any content in the window that you expected to see? Your snippet doesn't have anything, so I just want to make sure.

```kotlin
fun main() = application {
    Window(undecorated = true, transparent=true, onCloseRequest = ::exitApplication) {
        Box(modifier = Modifier.fillMaxSize().background(Color(1f, 1f, 1f, 0.5f))) {
            Text("Hello!")
        }
    }
}
```

Can you please also try to use just swing?
```kotlin
fun main(args: Array<String>) {
    SwingUtilities.invokeLater {
        createAndShowGUI()
    }
}

fun createAndShowGUI() {
    val frame = JFrame("Hello World")

    frame.isUndecorated = true

    // Make the window transparent
    frame.background = Color(0, 0, 0, 0)

    val label = JLabel("Hello World", JLabel.CENTER)
    label.foreground = Color.WHITE
    label.font = Font("Arial", Font.BOLD, 30)
    frame.add(label)

    frame.setSize(200, 200)
    frame.setLocationRelativeTo(null)

    frame.defaultCloseOperation = JFrame.EXIT_ON_CLOSE
    frame.isVisible = true
}
```
Does it work as expected?

And another thing to try is to use Compose Multiplatform 1.5.10

**Comment by Martmists-GH** [comment]
It seems it works as of Compose 1.5.10, *however* this seems to break shaders pretty badly.

**Comment by Martmists-GH** [comment]
The provided example does not work (using kotlin 1.9.21, compose 1.5.11) and instead produces a black screen which does not exit on SIGTERM.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3887">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
