### ISSUE TITLE
Expose UndoManager from CoreTextField

### ISSUE THREAD

**Issue by alex-vit** [JetBrains/compose-multiplatform#3891]
Please expose the `UndoManager` instead of hardcoding it in [`CoreTextField`](https://github.com/JetBrains/compose-multiplatform-core/blob/296fcc418dd88d684820a54490c3bd866412fc88/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/CoreTextField.kt#L276). Or provide an alternative to managing multiple unrelated undo / editing "sessions". ([brief Kotlin Slack discussion](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1698431081867269))

**Example use case** - `TextField` in "detail" view.

https://github.com/JetBrains/compose-multiplatform/assets/3646497/2bd7b576-5055-438f-8577-592ba2b5bcf5

Code for [`TextFieldUndoDemo.kt`](https://gist.github.com/alex-vit/7b37c88f6ff0a9671902b2da7a4a1c28).

In the video, You can see text from a different item "seeping" into the first item because as far as the `TextField`'s `UndoManager` is concerned, it's all one stream of text changes. And `Ctrl+Z` just un-does the latest synthetic change from `world --> hello` back to `world` (or whatever got recorded, `wo`, `worl`).

Please forward this issue if necessary and let me know how to submit next time. My journey was 
- JetBrains Compose Foundation issues closed, go to androidx
- androidx issues closed, go to mentioned [Android Issue Tracker](https://issuetracker.google.com/issues/new?component=192731&template=842428)
- `You do not have permission to create issues in this component.` 😆
- report here...

**Comment by eymar** [comment]
Hi @alex-vit ! I think you've selected a wrong component. Your component's name was jetpack, whily you wanted to add an issue to Jetpack Compose.

 You can submit it here: https://partnerissuetracker.corp.google.com/issues/new?component=612128&template=1253476

**Comment by eymar** [comment]
Sorry, I posted a wrong link above. I edited already.
Just in case, here is a correct link once again: https://issuetracker.google.com/issues/new?component=612128&template=1253476

**Comment by alex-vit** [comment]
Thanks for directing me to the issue tracker, @eymar! [Submitted an issue](https://issuetracker.google.com/u/1/issues/310510977). Closing this.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3891">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
