### ISSUE TITLE
Closing Awt file dialog by pressing Enter triggers previously focused button's on click

### ISSUE THREAD

**Issue by alex-vit** [JetBrains/compose-multiplatform#3892]
**Describe the bug**

In a Composable with a button that opens an Awt file picker, closing the dialog by pressing `Enter`
 or double-clicking a file (anything but clicking the dialog's native "Cancel" / "Save" / "Open" buttons), also triggers the focused button's on click, re-opening the file picker dialog immediately.

Workaround is to clear focus manually. See [code gist](https://gist.github.com/alex-vit/5cbe52fb6f39f77f7f03a230e75a44e2#file-filepickerfocusbug-kt-L44).

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.3
- OS version(s)* (required for Desktop and iOS issues): Mac OS Ventura 13.5.2 (22G91)
- OS architecture (x86 or arm64): arm
- JDK (for desktop issues): azul 15.0.8

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Click button, see file picker dialog open. 
2. Press `Enter`.
3. See file picker re-appear because `Pick file` was "clicked".

[Code gist](https://gist.github.com/alex-vit/5cbe52fb6f39f77f7f03a230e75a44e2).

**Expected behavior**
File picker closed. No phantom clicks. (Move focus to Awt window?)

**Screenshots**
Notice key-presses in the bottom left.

https://youtu.be/_I0y_oUKAOk

**Comment by eymar** [comment]
Reproduced on macos. 1.5.10 affected too. Not reproducible on Ubuntu.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3892">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
