### ISSUE TITLE
Add ui-util to gradle plugin

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#3894]
It brings useful extensions like `fastForEach` 

And now it looks like that in gradle:
```kotlin
implementation("org.jetbrains.compose.ui:ui-util:${libs.versions.compose.get()}")
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3894">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
