### ISSUE TITLE
Unify 'runtime-saveable' targets to match 'runtime'

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/compose-multiplatform#3899]
These should be published using the same targets. Right now 'runtime-saveable' is missing a bunch that 'runtime' supports'.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3899">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
