### ISSUE TITLE
Compose exe uses java in outside `jre` folder instead of bundled runtime

### ISSUE THREAD

**Issue by wispborne** [JetBrains/compose-multiplatform#3902]
**Describe the bug**
If there is a folder named `jre` next to the parent folder of your application's `.exe`, and that `jre` contains a JRE, then your Compose application will use the JRE in that folder instead of the one bundled with your application.

In nearly all situations, this will cause your application to silently fail to launch, as the JRE isn't compatible.

**Affected platforms**
Select one of the platforms below:
- Desktop (only Windows tested)

**Versions**
Note: this has been going on for the 2-3 years I've been using Compose Desktop.
- Kotlin version: 1.9.0
- Compose Multiplatform version: 1.5.10
- OS version(s): Windows 10 & 11
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 18

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create Hello World project and create a distributable, or use an existing Compose distributable.
2. Click on the .exe. Observe that the program launches.
3. Acquire a JRE that won't be compatible with your program, e.g. 1.7 or 1.8.
4. If your program's exe exists in `./Folder/App/App.exe`, then copy the JRE to `./Folder/`.
5. Rename the JRE's folder to `jre`. `Folder` should now contain `App` and `jre`, and `jre` should contain the `bin` folder.
6. Click on your program's .exe. Observe that it does not launch.

**Expected behavior**
The Compose-built .exe should ignore the presence of a Java runtime outside of its own folder and launch using the one in its own `runtime` folder.

**Screenshots**
Did **not** launch:
![image](https://github.com/JetBrains/compose-multiplatform/assets/1343347/ecd789b2-68cb-46e3-a61d-c849684c16f3)

Successfully launched:
![image](https://github.com/JetBrains/compose-multiplatform/assets/1343347/1c8cb180-a436-48d9-a35d-8927c7006065)

**Additional context**
This has been plaguing me for a while, as my application supports a third party program that itself uses a folder called `jre`. If a user does not read my warnings and places my program's folder in the third party program's folder, then the presence of the `jre` folder causes my program to silently fail.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3902">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
