### ISSUE TITLE
An error occurred while drawing an Image through the ContentDrawScope.drawImage() function

### ISSUE THREAD

**Issue by panpf** [JetBrains/compose-multiplatform#3904]
**Describe the bug**
I'm developing an image zoom library, ZoomImage, which is based on Compose Multiplatform and supports subsampling. 

I encountered a weird bug on the Desktop platform, the simple description is that an error always occurs when using the `ContentDrawScope.drawImage()` function to draw the tiles at the Bottom and End positions, which eventually leads to the loss of all component contents.

**Affected platforms**
- Desktop

*This problem is limited to the Desktop platform, everything is normal on the Android platform*

**Versions**
- Kotlin version*:  1.9.0
- Compose Multiplatform version*:  1.5.3
- OS version(s)*: macOS 13.4.1
- OS architecture (x86 or arm64): arm64
- JDK: 17
- Device: MacBook Pro 14 2021

**To Reproduce**
1. Clone sample code: https://github.com/panpf/ComposeDesktopTest
1. Execute the Main function of Main.kt to run the App
![Snipaste_2023-11-06_14-40-36](https://github.com/JetBrains/compose-multiplatform/assets/3250512/86b02330-335c-4685-9192-cb639e3311f2)
2. Double-click the image to enlarge it, and the ZoomImage library will decode the clear image at the current position and draw it on the surface of the component, so you can see the image gradually change from blurry thumbnail to clearer
![Snipaste_2023-11-06_14-41-01](https://github.com/JetBrains/compose-multiplatform/assets/3250512/a40b5633-1ad8-4f8b-8857-641dbafefc96)
3. Then slide down to the Offset(-144.9, -3677.4) position, and all component contents will disappear.
![Snipaste_2023-11-06_14-41-09](https://github.com/JetBrains/compose-multiplatform/assets/3250512/823ee53b-4d30-401c-97e2-ef5dda616b64)
4. Until you slide to the bottom of the picture (Offset(-144.9, -5828.0)), the content can no longer be displayed.
5. At this time, drag the lower right corner of the window and adjust the height of the window until the window size reaches 793x878 and the content at the bottom of the picture can suddenly be displayed again.
![Snipaste_2023-11-06_14-42-21](https://github.com/JetBrains/compose-multiplatform/assets/3250512/961f01df-0d77-4e14-b0b8-dfccc9423a0e)

**Video Reproduce**

https://github.com/JetBrains/compose-multiplatform/assets/3250512/4281715d-62da-425a-b18b-a4b0f830d5b6

**BUG summary**
- It is not a problem with a certain image. All images in the example of the https://github.com/panpf/zoomimage project can trigger this BUG.
- This BUG will only be triggered when you need to zoom in to a larger multiple and the window size is smaller. The image in the example needs to be 1.4 times or more. You can long press the left button and slide up and down to adjust the zoom factor.
- Only the tiles at the Bottom and End positions cannot be drawn. This problem does not occur at the Top, Start and Center positions.
- When the BUG is triggered, drag the lower right corner of the window to increase the window size to restore the display.
- An error in drawing a tile will cause other tiles and the basemap to disappear.

Hope this helps me solve this problem, thank you!

**Comment by alexzhirkevich** [comment]
Probably related : #2807

**Comment by igordmn** [comment]
Thanks for the example! The core issue is the same as in https://github.com/JetBrains/compose-multiplatform/issues/2807, let's keep only 2807.

**Comment by m-sasha** [comment]
@panpf Could you provide a minimal reproducer? Upon deeper investigation I'm not convinced this issue is the same as #2807

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3904">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
