### ISSUE TITLE
Weird behaviour when maximizing a partly maximized window (Linux)

### ISSUE THREAD

**Issue by Legotier** [JetBrains/compose-multiplatform#3908]
**Describe the bug**
If we have a partly maximized `ComposeWindow`, for example if `window.extendedState == JFrame.MAXIMIZED_HORIZ`, and then we set the window to be fully maximized (either through `window.placement = WindowPlacement.Maximized`, or through `window.extendedState = JFrame.MAXIMIZED_BOTH`), the window doesn't behave as expected (see below).

**Affected platforms**
- Desktop (Linux)

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10
- OS version(s)*: VanillaOS 22.10 all (GNOME 43.1, Wayland, 64-bit)
- OS architecture: x86
- JDK: OpenJDK 21

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Run the following code:
```kotlin
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.ui.awt.ComposeWindow
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.WindowPlacement
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState

fun main() = application {
    val state = rememberWindowState()
    Window(onCloseRequest = ::exitApplication, state = state) {
        Button(onClick = { maximizeOrRestore(window) }) {
            if (state.placement == WindowPlacement.Floating) Text("maximize")
            else Text("restore")
        }
    }
}

fun maximizeOrRestore(window: ComposeWindow) {
    println("before: ${window.placement}, ${window.extendedState}")
    if (window.placement == WindowPlacement.Maximized) window.placement = WindowPlacement.Floating
    else window.placement = WindowPlacement.Maximized
    println("after: ${window.placement}, ${window.extendedState}")
}
```
2. Drag the window to the side of the screen so that it snaps to the side and takes up half of the screen. It is maximized vertically but not horizontally. The button's text changes to `restore`.
3. Press the `restore` button. Nothing happens (including to the button's text), but the console output is
```
before: Maximized, 4
after: Floating, 0
```
4. Press the button again. The window get maximized horizontally but is no longer maximized vertically. The console output is
```
before: Floating, 0
after: Maximized, 6
```
5. Press the button again. The window restores to a floating state, at the correct position it was dragged to. The button's text changes back to `maximize`. The output is
```
before: Maximized, 2
after: Floating, 0
```

**Expected behavior**
The first press of the button should restore the window to a floating state at the same position it was dragged to, as `window.extendedState == JFrame.MAXIMIZED_VERT` implies `window.placement == WindowPlacement.Maximized`. The button's text should change back to `maximize`. The console output seems to reflect this, but the window and button themselves don't behave that way.

Additionally, something is happening between steps 4 and 5 that changes the window's `extendedState` from `JFrame.MAXIMIZED_BOTH` to `JFrame.MAXIMIZED_HORIZ`. This does reflect the actual state of the window on the screen; but instead, the window should just get maximized fully in step 4.

**Additional context**
The same problems exist if instead of setting `window.placement`, we set `window.extendedState`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3908">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
