### ISSUE TITLE
 Moving Window from one screen to the other duplicates items in itemsIndexed - Desktop

### ISSUE THREAD

**Issue by BoydyBoydy** [JetBrains/compose-multiplatform#3909]
**Describe the bug**
After modifying data in Application, everything has been updated and refreshed/recomposed.
I then move the window to a different monitor and the items seem to duplicate.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.8.0
- Compose Multiplatform version*: 1.5.3
- OS version(s)* (required for Desktop and iOS issues): Windows
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a Lazy Column and setup items for itemsIndexed
2. Add some items to your list, through code or in window of application (I used window and other functions)
3. Count how many items you have... (I used at least one, but happens with more)
4. Move window from one screen to another
5. Should now count and verify that the items are duplicated (1+1=2, etc.)

**Expected behavior**
After modifying the itemsIndexed, the refresh has completed.
After moving application to a different window, the itemsIndexed continue to stay the same, rather than duplicating.

**Additional context**
I am using Compose Desktop.
I couldn't find any other issues like this on the tracker, but perhaps similar.
Happy to provide code sample if needed.

This didn't seem to impact my application critically. The duplication only happens within the view...
I was able to recover by navigating out of the view and then back into it.

So it might just be a recomposition of the window once you move from one screen (Laptop -> Monitor) to the next that doesn't refresh the itemsIndexed properly... or the code developed here is not sufficient to cover this case.

**Comment by igordmn** [comment]
Please, provide a minimal snippet, where we can see the issue.

My preliminary guess, that you add items inside a composition, which isn't a valid usage, but to be sure I need to see the code.

**Comment by BoydyBoydy** [comment]
Hi, code snippet below specs:

Test in Kotlin Native - Default Template from intellij - Compose Project
Tested on Windows:
- Kotlin : 1.8.20
- Compose : 1.4.1 - NOK
- Compose : 1.5.3 - switched as the default template wasn't using the correct version - NOK

I have implemented a simple list add function.
I had used a proper list and copied that into the mutablestatelistof, but have left it as simple as possible for the moment.

TestObject.kt

`data class TestObject(var testName: String)`

Main.kt
```
import androidx.compose.desktop.ui.tooling.preview.Preview
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@Composable
@Preview
fun App() {
    var text by remember { mutableStateOf("Hello, World!") }
    val listSorted = remember {
        mutableStateListOf<TestObject>()
    }
    val testObjectOne = TestObject("Test One")
    val testObjectTwo = TestObject("Test Two")

    listSorted.add(testObjectOne)
    listSorted.add(testObjectTwo)
    // create listSorted
    // add to list with a button
    // move window from one screen to the other. see if that impacts the bug
    MaterialTheme {
        Button(onClick = {
            text = "Hello, Desktop!"
            listSorted.add(TestObject("New Object"))
        }) {
            Text(text)
        }

        LazyColumn {
            itemsIndexed(listSorted) { index, item ->
                Text(item.testName)
            }
        }
    }
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}
```

Results:
Bug still impacts with the minimal example.
Possibly this is as you had said with improper way of using it, but this is similar to how I have done it. Not sure how else to do it.

It shows the 2 New Objects fine (top left hidden on top of button though, in this example).
When I move the application to a new screen, it duplicates the 2 objects.

When I then add some more objects through the button.
I move the application to a different screen and it duplicates the initial Objects, rather than any of the new objects.

**Comment by m-sasha** [comment]
You are doing exactly as Igor guessed - adding to the list in the composition. So whenever the outer scope is recomposed, you are adding more items to the list. What you want to do, in order to add them only once, is this:
```
    val listSorted = remember {
        mutableStateListOf(
            TestObject("Test One"),
            TestObject("Test Two")
        )
    }
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3909">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
