### ISSUE TITLE
How to package into a single exe file in Windows without installation?

### ISSUE THREAD

**Issue by young-kingdom** [JetBrains/compose-multiplatform#3910]
Is there any solution?

**Comment by igordmn** [comment]
Use `gradlew createDistributable` (or createReleaseDistributable), it creates a folder with exe and other files. If you want to pack all the content into a single exe, use a third party utility for that.

**Comment by young-kingdom** [comment]
> Use `gradlew createDistributable` (or createReleaseDistributable), it creates a folder with an exe and other files. [使用 gradlew createDistributable （或 createReleaseDistributable），它会创建一个包含 exe 和其他文件的文件夹。] If you want to pack all the content into a single exe, use a third party utility for that. [如果您想将所有内容打包到一个 exe 中，请使用第三方实用程序。]

What third party utility can do this?

**Comment by igordmn** [comment]
I am not aware, but found some solutions, googling "pack folder to exe"

**Comment by young-kingdom** [comment]
> I am not aware of any, but found some solutions, googling "pack folder to exe" [我不知道，但找到了一些解决方案，谷歌搜索“将文件夹打包到exe”]

Do you mean to package the files created by `gradlew createDistributable`? What I mean is to directly generate a single exe like `gradlew packageExe`. I found a Java tool `JavaPackager` , but it conflicts with the `gradlew package` task of compose-multiplatform, so I gave up this plan for the time being.

**Comment by igordmn** [comment]
> Do you mean to package the files created by gradlew createDistributable

Yes.

> I found a Java tool JavaPackager

You can use it, if you don't apply Compose Multiplatform Gradle plugin this way:
```
import io.github.fvarrui.javapackager.gradle.PackagePluginExtension

plugins {
    kotlin("jvm")
    application
    id("io.github.fvarrui.javapackager.plugin") version "1.7.5"
}

repositories {
    mavenCentral()
}

dependencies {
    kotlinCompilerPluginClasspath("org.jetbrains.compose.compiler:compiler:1.5.3")
    implementation("org.jetbrains.compose.desktop:desktop-jvm-windows-x64:1.5.10")
}

application {
    mainClass = "MainKt"
}

configure<PackagePluginExtension> {
    mainClass("MainKt")
    bundleJre(true)
}
```

(the Compose Gradle plugin responsibility is to run/distribute Compose applications, but it can be done with other utilities)

**Comment by young-kingdom** [comment]
> > Do you mean to package the files created by gradlew createDistributable
> 
> Yes.
> 
> > I found a Java tool JavaPackager
> 
> You can use it, if you don't apply Compose Multiplatform Gradle plugin this way:
> 
> ```
> import io.github.fvarrui.javapackager.gradle.PackagePluginExtension
> 
> plugins {
>     kotlin("jvm")
>     application
>     id("io.github.fvarrui.javapackager.plugin") version "1.7.5"
> }
> 
> repositories {
>     mavenCentral()
> }
> 
> dependencies {
>     kotlinCompilerPluginClasspath("org.jetbrains.compose.compiler:compiler:1.5.3")
>     implementation("org.jetbrains.compose.desktop:desktop-jvm-windows-x64:1.5.10")
> }
> 
> application {
>     mainClass = "MainKt"
> }
> 
> configure<PackagePluginExtension> {
>     mainClass("MainKt")
>     bundleJre(true)
> }
> ```
> 
> (the Compose Multiplatform Gradle plugin responsibility is to run/distribute Compose applications, but it can be done with other utilities)

Thanks.I'll try it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3910">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
