### ISSUE TITLE
MacOS notarization broken with libsqlitejdbc

### ISSUE THREAD

**Issue by sproctor** [JetBrains/compose-multiplatform#3914]
**Describe the bug**
I'm attempting to generate a release with MacOS 11 (the only version I have access to test) and it throws an error while unsigning libsqlitejdbc.jnilib. The build worked with Compose 1.4 previously, but it appears that Apple now requires the teamID so the previously working version is no longer useable.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10
- OS version(s)* (required for Desktop and iOS issues): MacOS 11.7
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 17
- XCode: 13.2.1

**To Reproduce**
Source can be found: https://github.com/sproctor/warlock3
Steps and/or the code snippet to reproduce the behavior:
1. run ./gradlew packageReleaseDistributionForCurrentOS
2. See error

**Expected behavior**
I believe the notarization should work properly as in 1.4, but with the added teamID.

**Error Log**

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: fatal error: file not in an order that can be processed (code signature data out of place): /Users/sproctor/Code/warlock3/app/build/compose/tmp/sign/libsqlitejdbc.jnilib
/Users/sproctor/Code/warlock3/app/build/compose/tmp/sign/libsqlitejdbc.jnilib: the codesign_allocate helper tool cannot be found or used
```

**Comment by GaoXing0608** [comment]
same issue any update?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3914">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
