### ISSUE TITLE
Web: Don't use Monospace font by default

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#3915]
Monospace fonts like the one visible on https://zal.im/wasm/iv/ make the apps look unnecessarily raw and "unfinished":

- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API

While it's already possible to [bundle a font](https://github.com/Kotlin/kotlin-wasm-examples/blob/69ca280d551fa25e4ed0bd640ce3fb998d93b323/compose-jetsnack/web/src/wasmJsMain/kotlin/Main.kt#L7) and load it in Compose/Wasm, the **default visual aesthetics** would be much improved by using any sans-serif font available on the target system.

<img width="681" alt="Screenshot 2023-11-08 at 18 58 41" src="https://github.com/JetBrains/compose-multiplatform/assets/2178959/e517be88-d045-4f05-9000-26c64648476e">

**Comment by chrisjenx** [comment]
Doesn't Material use Roboto which I think is already a downloadable google font? Guessing this is just an issue of trying to use that font by downloading and setting it.

https://m3.material.io/styles/typography/fonts

**Comment by eymar** [comment]
The fix was merged. It  will be available in the next build of CfW with Kotlin/Wasm.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3915">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
