### ISSUE TITLE
Can not build distribution for Image Viewer

### ISSUE THREAD

**Issue by shalva97** [JetBrains/compose-multiplatform#3918]
**Describe the bug**
`./gradlew :desktop:packageDistributionForCurrentOS` fails to complete

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10
- OS version(s)* (required for Desktop and iOS issues): MacOS 13.5.2 (22G91)
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce**
- Clone the project
- run `./gradlew :desktop:packageDistributionForCurrentOS` task
- it fails with: 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktopApp:checkRuntime'.
> Failed to check JDK distribution: 'jpackage' is missing
  JDK distribution path: /Users/shalva/Applications/Android Studio.app/Contents/jbr/Contents/Home


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

**Expected behavior**
It should build successfully

**Comment by shalva97** [comment]
There seems to be something wrong with the Java distribution that comes with Android Studio. Fixed by selecting another distribution.

**Comment by iamcalledrob** [comment]
Just ran into this too.

For the benefit of anyone else who runs into this, the JDK being referred to is the one being used for running Gradle, and can be set in IntelliJ Settings (Build, Execution, Deployment -> Build Tools -> Gradle -> Gradle JVM).

In my case, it got set by default to GRADLE_LOCAL_JAVA_HOME, which appears to be hijacked by Android Studio to point there.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3918">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
