### ISSUE TITLE
iOS WKWebview addScriptMessageHandler does not work

### ISSUE THREAD

**Issue by KevinnZou** [JetBrains/compose-multiplatform#3922]
**Describe the bug**
I attempted to use the `addScriptMessageHandler` method to establish communication between a native app and WKWebView for my [multiplatform webview](https://github.com/KevinnZou/compose-webview-multiplatform/tree/main). Despite closely following the instructions, the method did not work as expected.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. create a `WKJsMessageHandler`:
```
class WKJsMessageHandler() : WKScriptMessageHandlerProtocol, NSObject() {
    override fun userContentController(
        userContentController: WKUserContentController,
        didReceiveScriptMessage: WKScriptMessage
    ) {
        KLogger.i { "didReceiveScriptMessage: $didReceiveScriptMessage" }
        val body = didReceiveScriptMessage.body
        val method = didReceiveScriptMessage.name
    }
}
```
2. register it in `WKWebViewConfiguration`
```
val jsMessageHandler = remember { WKJsMessageHandler(state.jsBridge) }
val webConfiguration = remember {
    WKWebViewConfiguration().apply {
        KLogger.i { "WKWebView addScriptMessageHandler" }
        userContentController.addScriptMessageHandler(jsMessageHandler, "jsBridge")
    }
}
```
3. call it in js:
```
function callIOS() {
    console.log('callIOS');
    window.webkit.messageHandlers.jsBridge.postMessage("hello")
}
```

```
<html>
<head>
    <header><meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no'></header>
    <link rel="stylesheet" type="text/css" href="styles.css">
    <script type="text/javascript" src="script.js"></script>
    <title>Compose WebView Multiplatform</title>
</head>
<body>
<h1>Compose WebView Multiplatform</h1>
<h2 id="subtitle">Basic Html Test</h2>
<button onclick="callAndroid()">callAndroid</button>
<button onclick="callIOS()" style="margin-top: 20px;">callIOS</button>
</body>
</html>
```

**Expected behavior**
didReceiveScriptMessage should be called and print out the logs.

**Comment by pjBooms** [comment]
I think it does not relate to Compose. What if you do the same outside of Compose world?

**Comment by KevinnZou** [comment]
> I think it does not relate to Compose. What if you do the same outside of Compose world?

Yes, it should not relate to Compose. However, it works well outside of the Compose world. Thus, I am not sure what caused that problem.

**Comment by pjBooms** [comment]
>However, it works well outside of the Compose world.

**Comment by KevinnZou** [comment]
> > However, it works well outside of the Compose world.
> 
> Can you provide two reproducible examples: pure KMP without Compose example that works and CMP example that does not work?

I'm not sure if the issue lies with KMP or CMP. However, since we need Compose to use the WebView, I have submitted the issue here.

**Comment by KevinnZou** [comment]
Are there any updates on this issue? I am experiencing another issue that is dependent on this one. You can find more information about it [here](https://github.com/KevinnZou/compose-webview-multiplatform/issues/31).
