### ISSUE TITLE
ExposedDropdownMenu can overlap the textfield

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#3923]
If the ExposedDropdownMenu is too tall, it will overlap the textfield:

```
@OptIn(ExperimentalMaterialApi::class)
fun main() = singleWindowApplication {
    Column(Modifier.padding(start = 8.dp)) {
        var expanded by remember { mutableStateOf(false) }
        ExposedDropdownMenuBox(
            expanded = expanded,
            onExpandedChange = { expanded = it}
        ) {
            var text by remember { mutableStateOf("") }
            TextField(
                value = text,
                onValueChange = { text = it },
                modifier = Modifier
                    .size(120.dp, 47.dp)  // Height must be less than 48.dp to reproduce
            )
            ExposedDropdownMenu(
                expanded = expanded,
                onDismissRequest = { expanded = false },
                modifier = Modifier.exposedDropdownSize(true)
            ) {
                repeat(100) {
                    DropdownMenuItem({}) { Text("Item $it") }
                }
            }
        }
    }
}
```

<img width="336" alt="SCR-20231111-rcqb" src="https://github.com/JetBrains/compose-multiplatform/assets/5230206/32869f6d-16f4-4f01-a61e-da66f57bdac1">

<img width="336" alt="SCR-20231111-rcqv" src="https://github.com/JetBrains/compose-multiplatform/assets/5230206/26d85c60-d2b6-4453-ae4f-7687c3aaeb62">

**Affected platforms**
- All
- Compose Multiplatform version: 1.5.10

**Comment by m-sasha** [comment]
The issue appears to be in the calculation of `menuHeight` in `ExposedDropdownMenuBox`:
```
        modifier.onGloballyPositioned {
            width = it.size.width
            val boundsInWindow = it.boundsInWindow()
            val visibleWindowBounds = windowInfo.containerSize.toIntRect()
            val heightAbove = boundsInWindow.top - visibleWindowBounds.top
            val heightBelow = visibleWindowBounds.height - boundsInWindow.bottom
            menuHeight = max(heightAbove, heightBelow).toInt() - verticalMarginInPx
        }
```
We're assuming the menu can overlap `verticalMarginInPx` either at the top or the bottom of the window, but not both. But if the textfield is short enough and close enough to the top of the window, and the menu is tall enough, the "heightBelow" can overlap `verticalMarginInPx` both at the top and the bottom of the window.

in Android code (`androidx-main` tip; not yet released) this is done like so: 
```
modifier.onGloballyPositioned {
    anchorCoordinates = it
    anchorWidth = it.size.width
    menuMaxHeight = calculateMaxHeight(
        windowBounds = view.rootView.getWindowBounds(),
        anchorBounds = anchorCoordinates.getAnchorBounds(),
        verticalMargin = verticalMargin,
    )
}

private fun calculateMaxHeight(
    windowBounds: Rect,
    anchorBounds: Rect?,
    verticalMargin: Int,
): Int {
    anchorBounds ?: return 0

    val marginedWindowTop = windowBounds.top + verticalMargin
    val marginedWindowBottom = windowBounds.bottom - verticalMargin
    val availableHeight =
        if (anchorBounds.top > windowBounds.bottom || anchorBounds.bottom < windowBounds.top) {
            (marginedWindowBottom - marginedWindowTop).roundToInt()
        } else {
            val heightAbove = anchorBounds.top - marginedWindowTop
            val heightBelow = marginedWindowBottom - anchorBounds.bottom
            max(heightAbove, heightBelow).roundToInt()
        }

    return max(availableHeight, 0)
}
```

**Comment by Kykara4uk** [comment]
any updates on this issue? Or maybe extended answer how to fix it by myself?

**Comment by abhishekrr** [comment]
how to fix it

**Comment by unomonteiro** [comment]
How can I apply the above workaround?

**Comment by radomartinec** [comment]
Same issue here. If there are more than a few items in the suggestions list, the whole ExposedDropdownMenu covers the TextField.

**Comment by m-sasha** [comment]
This is actually a problem in AOSP. I've reported the bug here: https://issuetracker.google.com/issues/360881340

The real issue is not in our menu height calculation. The dropdown menu should align to the bottom of text field even if it means going inside the vertical margin. We could improve the situation somewhat by limiting the dropdown height to
```
visibleWindowBounds.height - 2*verticalMarginInPx
```
but then the dropdown will look like this:

<img width="211" alt="image" src="https://github.com/user-attachments/assets/74994ad6-88d4-4caa-a50c-5cb368db9c11">

**Comment by nordfalk** [comment]
Please comment here when someone knows how to fix this

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3923">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by chandresh204** [comment]
providing max height can help 

`ExposedDropdownMenu(modifier = Modifier.heightIn(max = 200.dp) ....`
