### ISSUE TITLE
Attach Skikoview to Compose Web 

### ISSUE THREAD

**Issue by dbof10** [JetBrains/compose-multiplatform#3924]
For desktop, I use such snippet to wrap GenericSkikoView to convert it to a Composable Component .

```
@Composable
actual fun ComposeChartView(modifier: Modifier) {


    SwingPanel(factory = {

        JPanel().apply {
            layout = BoxLayout(this, Y_AXIS)

            val skiaLayer = SkiaLayer()
            skiaLayer.addView(GenericSkikoView(skiaLayer, ChartView()))

            skiaLayer.attachTo(this)
            skiaLayer.needRedraw()
        }
    }, modifier = modifier)
}
```
How do I do it for web wasm?

**Comment by pjBooms** [comment]
Look at this sample as a hint: https://github.com/JetBrains/skiko/blob/master/samples/SkiaMultiplatformSample/src/jsMain/kotlin/org/jetbrains/skiko/sample/App.js.kt#L14C11-L14C11

@eymar do you have thought how to adapt it to Compose?

**Comment by eymar** [comment]
Why would you like to use GenericSkikoView?
Do you want to draw something custom on a canvas? Then you can look at this example: https://github.com/terrakok/CMP-Tuner/blob/master/composeApp/src/commonMain/kotlin/org/jetbrains/tuner/App.kt#L130
____

In web you can manually create a `<canvas>` element, position it manually and manage it manually on top of Compose controlled canvas, and attach a skiko view to it like here: https://github.com/JetBrains/skiko/blob/master/samples/SkiaMultiplatformSample/src/jsMain/kotlin/org/jetbrains/skiko/sample/App.js.kt#L14C11-L14C11

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3924">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
