### ISSUE TITLE
[Desktop] Provide a unified way to set title bar to light/dark color according to system/user choice

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#3928]
I would like to make the background color of the window title bar matches system setting (dark / light mode).

For Mac, we can set via a system property `apple.awt.application.appearance`. For Windows, we seems have to dive into Swing's Look And Feel. As a cross-platform UI framework, could Jetpack Compose Desktop unify and provide an easy way to configure this? This would make the produced application looks more professional.

**Comment by pjBooms** [comment]
Relates to #169

**Comment by igordmn** [comment]
The same issue, but with suggestion to make it default: https://github.com/JetBrains/compose-multiplatform/issues/4393

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3928">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
