### ISSUE TITLE
How to implement FXLauncher automatic software update function in javafx on desktop

### ISSUE THREAD

**Issue by fendo8888** [JetBrains/compose-multiplatform#3935]
How to implement the automatic software update function of FXLauncher in javafx on the desktop, or how to implement the software upgrade in compose-multiplatform on the desktop according to the server version number and the local version number, if the server version number is larger than the current version number. The upgrade mode can be incremental upgrade or full upgrade. Incremental upgrade is to update some files, such as some jar packages in java, and full upgrade is to update all files

**Comment by pjBooms** [comment]
Compose Multiplatform does not support functionality you requested and is not going to support. So closing this issue. You may look for third-party alternatives.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3935">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
