### ISSUE TITLE
When the ModalBottomSheet of material3 is partially expanded, is it not possible to increase the vertical size?

### ISSUE THREAD

**Issue by naijun0403** [JetBrains/compose-multiplatform#3936]
## Environment
- OS: Android
- material3 version: 1.2.0-alpha11

## Content
When the ModalBottomSheet of material3 is partially expanded, is it not possible to increase the vertical size?

**Comment by naijun0403** [comment]
Sorry, I'll move to discussions tab

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3936">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
