### ISSUE TITLE
JS TextField loose focus when press quote char

### ISSUE THREAD

**Issue by hondogo** [JetBrains/compose-multiplatform#3941]
**Describe the bug**
When pressing quote char then TextField is loosing focus cause another text field appeared by browser (see screenshot below) 

**Affected platforms**
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version: 1.9.20 
- Compose Multiplatform version: 1.6.0-dev1276 
- OS version(s)* (required for Desktop and iOS issues): Linux, Firefox 116.0.2 (64-bit)
- OS architecture (x86 or arm64): amd64

**To Reproduce**
1) Set focus on TextField
2) Press quote char

Sample for reproduce:
```
@Composable
fun Test() {
    var v by remember { mutableStateOf("") }
    TextField(
        value = v,
        onValueChange = { v = it }
    )
}
```

**Expected behavior**
TextField not loosing focus. No browser specific dialogs/inputs appearing

**Screenshots**
![20231117_175810](https://github.com/JetBrains/compose-multiplatform/assets/7112579/8b183529-3c13-48bf-b349-9fe400147a0b)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3941">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
