### ISSUE TITLE
iOS View with ComposeUIViewController not rendered inside UIKitView

### ISSUE THREAD

**Issue by enoler** [JetBrains/compose-multiplatform#3942]
**Describe the bug**
I am creating the iOS version of my Android application with KMP and I am having some issues when rendering views inside UIKitView with a  `UIViewController`.

As a summary, I have an `Activity` in Android and a `View` in SwiftUI that renders a composable called `NavigationDrawer` that contains an `CenterAlignedTopAppBar` and a `ModalNavigationDrawer`. I pass the content (the screen that i want to show) as a property of the composable `NavigationDrawer`, and depending on the platform, I create a different content:

- In Android, the activity `MainActivity` renders the composable `NavigationDrawer` and the content is an `AndroidView` that inflates a fragment called `HelpFragment` and it works correctly.

`MainActivity`
```
setupView {
     NavigationDrawer(
          content = {
               AndroidView(
                    factory = { HelpFragment() }
               )
          }
     }
)
```

- In SwiftUI, the `MainView` renders the composable `NavigationDrawer` through a `ComposeUIViewController` and the content is a `UIKitView` that renders another `View`. 

`MainView`
```
func makeUIViewController(context: Context) -> some UIViewController {
        mainController.navigationDrawer()
}
```

`MainController`
```
fun navigationDrawer(helpView: UIView) =
     ComposeUIViewController {
          NavigationDrawer(
               content = {
                    UIKitView(
                         factory = { helpView() }
                    )
               }
          )
     }
```

- `HelpView` is another SwiftUI View that renders the UI of the screen that is another composable rendered through another `ComposeUIViewController`.

`HelpView`
```
func makeUIViewController(context: Context) -> some UIViewController {
        helpController.ui()
}
```

`HelpController`
```
fun ui() =
     ComposeUIViewController {
          HelpUi()
     }
```

The problem is that on iOS, the `NavigationDrawer` is rendered. The `UIKitView` is rendered and it executes the methods inside `HelpView`, including `makeUIViewController`.  The function `helpController.ui()` is called, but it never goes inside the `ComposeUIViewController`, so the composable `HelpUi` is not rendered.

If instead the `ComposeUIViewController` I render a native SwiftUI , it works. My conclusions on this is that `UIKitView` works and renders the `View`, but it doesn't work when you use a `UIViewController`

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.10
- OS version(s)* (required for Desktop and iOS issues): 14.1.1 (23B81)
- OS architecture (x86 or arm64): x86

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Use a View with a `UIViewController` that includes a `UIKitView`.
2. Inside the `UIKitView` you pass another `SwiftUI` View using a `UIViewController` to render another composable.

**Expected behavior**
The `View` inflated in the `UIKitView` is displayed correctly.

**Comment by dima-avdeev-jb** [comment]
@enoler Hello!
Do you saw this example?
https://github.com/JetBrains/compose-multiplatform/tree/master/examples/interop/ios-swiftui-in-compose
It may helps with your Issue. But, if not - can you please provide a minimal reproducible sample project on GitHub.

**Comment by enoler** [comment]
Hello @dima-avdeev-jb , thanks for the fast response. Yes I actually followed this example for my current implementation. 

I uploaded a sample project to Github where the issue is reproducible. [Here the link](https://github.com/enoler/UIKitViewBug)

Thank you!

**Comment by enoler** [comment]
After some researching, the problem description can be simplified. No matter about the containers and how many nested views are involved, the problem I see is that `UIKitView` can render `SwiftUI` native views, but it does not render a view that is created in compose.

So I have three classes:
`MainView.swift`
```
struct MainView: View {
    var body: some View {
        ZStack(alignment: .top) {
            MainComposeView()
        }
    }
}

struct MainComposeView: UIViewControllerRepresentable {
    let controller = MainViewController()
    
    func makeUIViewController(context: Context) -> some UIViewController {
        controller.statusComposable(
            initialView: SwiftUIInUIView(content: HelpView()) // Help View is a SwiftUIView and we pass it to MainControllerView as UIView
        )
    }
    
    func updateUIViewController(_ uiViewController: UIViewControllerType, context: Context) {}
}
```

`MainControllerView.kt`
```
fun statusComposable(initialView: UIView) =
        ComposeUIViewController {
                ...
                UIKitView(
                      factory = {  initialView  }, // This is the UIView created from HelpView
                      interactive = true
                )
                ...
        }
```

`HelpView.swift`
```
struct HelpComposeView: UIViewControllerRepresentable {
    let controller = HelpViewController()
         
    func makeUIViewController(context: Context) -> some UIViewController {
        controller.statusComposable()
    }
    
    func updateUIViewController(_ uiViewController: UIViewControllerType, context: Context) { }
}

struct HelpView: View {
    var body: some View {
        VStack {
            Text("Help") // This is rendered inside the UIKitView as it is SwiftUI native.
            HelpComposeView()  // This is not rendered inside the UIKitView as it is another compose view.
        }
    }
}
```

I have two theories:
- UIKitView is not able to render `UIViewControllerRepresentable` views.
- There is some problem with the function that converts `SwiftUI` to `UIView` (it's the one in the [provided example](https://github.com/JetBrains/compose-multiplatform/tree/master/examples/interop/ios-swiftui-in-compose) by @dima-avdeev-jb )

`SwiftUIInUIView`
```
class SwiftUIInUIView<Content: View>: UIView {
    init(content: Content) {
        super.init(frame: CGRect())
        let hostingController = UIHostingController(rootView: content)
        hostingController.view.translatesAutoresizingMaskIntoConstraints = false
        addSubview(hostingController.view)
        NSLayoutConstraint.activate([
            hostingController.view.topAnchor.constraint(equalTo: topAnchor),
            hostingController.view.leadingAnchor.constraint(equalTo: leadingAnchor),
            hostingController.view.trailingAnchor.constraint(equalTo: trailingAnchor),
            hostingController.view.bottomAnchor.constraint(equalTo: bottomAnchor)
        ])
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

**Comment by dima-avdeev-jb** [comment]
Can you please provide a minimal reproducible sample on GitHub?

**Comment by enoler** [comment]
> Can you please provide a minimal reproducible sample on GitHub?

I did it already [here](https://github.com/enoler/UIKitViewBug)

**Comment by dima-avdeev-jb** [comment]
@enoler 
Please take a look at this PR https://github.com/enoler/UIKitViewBug/pull/1

**Comment by enoler** [comment]
> @enoler Please take a look at this PR [enoler/UIKitViewBug#1](https://github.com/enoler/UIKitViewBug/pull/1)

Hello @dima-avdeev-jb , this is not the problem I reported. What I need to render is `HelpView` which is another composable.

HelpView is being rendered, but as you can see in the following screenshot, the `Swift View` is the only thing that is rendered but not the composable `HelpComposeView`:

<img width="431" alt="Captura de pantalla 2023-12-15 a las 14 13 50" src="https://github.com/JetBrains/compose-multiplatform/assets/6621035/e1824ee9-b810-4394-9a7b-39a931585087">

<img width="719" alt="Captura de pantalla 2023-12-15 a las 14 16 06 (1)" src="https://github.com/JetBrains/compose-multiplatform/assets/6621035/4f976290-91a3-40df-ac9b-01537ca97a7a">

In the other hand, if in Android you can see that it renders fine:
<img width="396" alt="Captura de pantalla 2023-12-15 a las 14 29 26" src="https://github.com/JetBrains/compose-multiplatform/assets/6621035/8ffb056d-be7e-4927-b67a-14bc70913345">

**Comment by cryptrr** [comment]
I have kindof the same problem.

Here, the `getViewController().view` is not rendered.

```kotlin
@Composable
actual fun MyContainer(id: String) {

    UIKitView(
        modifier = Modifier,
        factory = {
            val view = UIView()
            view.addSubview(getViewController(id).view)
            view
        }
    )
}

fun getViewController(id: String) : UIViewController  = ComposeUIViewController {
    //This is a composable
    MyView(id)
}
```

**Comment by dima-avdeev-jb** [comment]
@enoler 
I Compose dev version 1.6.0-dev1347 we provide a way how to use UIViewController in Compose. And I think it should help with your Issue. Please apply the same changes like in this PR: https://github.com/JetBrains/compose-multiplatform/pull/4062

**Comment by enoler** [comment]
> @enoler In Compose dev version 1.6.0-dev1347 we provide a way how to use UIViewController in Compose. And I think it should help with your Issue. Please apply the same changes like in this PR: #4062
> 
> Can you please try this?

Hello @dima-avdeev-jb , finally I was able to test it out and the solution proposed in this PR works perfectly. Thank you very much for your help!

**Comment by kocheick** [comment]
I have another kind of the same problem.
I want to render this simple Composable on iOS
```
@Composable
fun CallOutController() = ComposeUIViewController {
    Text("GREEN LIGHT")
}
```
on the iOS side I have a `class MapDelegate(val uiImage: UIImage? = null) : NSObject(), MKMapViewDelegateProtocol`... and inside the following method `override fun mapView(mapView: MKMapView, viewForAnnotation: MKAnnotationProtocol): MKAnnotationView? {....}`
I'm trying to render the Composable in this view via **`ComposeUIViewController`** but it does not render

this won't render:
```
annotationView.detailCalloutAccessoryView = UIView().apply {
                addSubview(  CallOutController().view    )
            }
```
this works fine as it is native
```
annotationView.detailCalloutAccessoryView = UIImageView( UIImage.imageNamed("icon.jpg") )
```

**Comment by kocheick** [comment]
> I have another kind of the same problem.
> I want to render this simple Composable on iOS
> ```
> @Composable
> fun CallOutController() = ComposeUIViewController {
>     Text("GREEN LIGHT")
> }
> ```
> on the iOS side I have a `class MapDelegate(val uiImage: UIImage? = null) : NSObject(), MKMapViewDelegateProtocol`... and inside the following method `override fun mapView(mapView: MKMapView, viewForAnnotation: MKAnnotationProtocol): MKAnnotationView? {....}`
> I'm trying to render the Composable in this view via **`ComposeUIViewController`** but it does not render
> 
> this won't render:
> ```
> annotationView.detailCalloutAccessoryView = UIView().apply {
>                 addSubview(  CallOutController().view    )
>             }
> ```
> this works fine as it is native
> ```
> annotationView.detailCalloutAccessoryView = UIImageView( UIImage.imageNamed("icon.jpg") )
> ```
> 
> 

I solved my issue by updating my code to the following the following for anybody interested :
> ```
> annotationView.detailCalloutAccessoryView = CallOutController().view.apply{ frame = CGRectMake(0.0,0.0,80.80.0)}    
>             
> ```


And now I can render my composable to a UIView which MKAnnotationView requires.

**Comment by tadius** [comment]
> @enoler In Compose dev version 1.6.0-dev1347 we provide a way how to use UIViewController in Compose. And I think it should help with your Issue. Please apply the same changes like in this PR: #4062
> 
> Can you please try this?

Hi! Thank you for solution! Now I'm trying to implement Yandex Ads Sticky block. It has dynamic height. With your solution we need to manually set the height of compose view. How can we get something like wrap content for this situation?

**Comment by harry248** [comment]
@tadius See https://johnoreilly.dev/posts/swiftui-component-compose-ios/

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3942">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
