### ISSUE TITLE
Js,Jvm Software keyboard is not shown again if focus not changing

### ISSUE THREAD

**Issue by hondogo** [JetBrains/compose-multiplatform#3943]
**Describe the bug**
If implementing soft keyboard then event for startInput is not triggering when keyboard was hidden while focus remains on TextInput and click on TextInput happening.

Android platform working normal.

**Affected platforms**
Select one of the platforms below:
- Desktop
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version: 1.9.20 
- Compose Multiplatform version: 1.6.0-dev1276 
- OS version(s)* (required for Desktop and iOS issues):  Linux, Firefox 116.0.2 (64-bit)
- OS architecture (x86 or arm64): amd64
- JDK (for desktop issues): GraalVM 17.0.8

**To Reproduce**
With reproducing code below:
1) set focus on TextField
2) wait for 2 seconds while LaunchedEffect code will hide keyboard
3) click on TextField again - no event startInput method of TextInputService called

Code for reproduce:
```

@OptIn(ExperimentalComposeUiApi::class)
@Composable
fun testKeyboard() {
    val testTextInputService = remember { TestTextInputService() }
    val inputService = remember(testTextInputService) { TextInputService(testTextInputService) }
    if (testTextInputService.keyboardShown) {
        LaunchedEffect(Unit) {
            delay(2000)
            testTextInputService.hide()
        }
    }
    CompositionLocalProvider(
        LocalTextInputService provides inputService,
        LocalSoftwareKeyboardController provides testTextInputService
    ) {
        var v by remember { mutableStateOf("") }
        Column {
            TextField(
                value = v,
                onValueChange = { v = it }
            )
            Text(if (testTextInputService.keyboardShown) "Keyboard shown" else "Keyboard hidden")
        }
    }
}

@OptIn(ExperimentalComposeUiApi::class)
@Stable
class TestTextInputService(
) : PlatformTextInputService, SoftwareKeyboardController {

    var keyboardShown by mutableStateOf(false)
        private set

    override fun hide() {
        keyboardShown = false
    }

    override fun show() {
        keyboardShown = true
    }

    @Deprecated(message = "", replaceWith = ReplaceWith("hide()"))
    override fun hideSoftwareKeyboard() {
        hide()
    }

    @Deprecated(message = "", replaceWith = ReplaceWith("hide()"))
    override fun showSoftwareKeyboard() {
        show()
    }

    override fun startInput(value: TextFieldValue, imeOptions: ImeOptions, onEditCommand: (List<EditCommand>) -> Unit, onImeActionPerformed: (ImeAction) -> Unit) { // not called again when hidden and there were no changes in input focus  
        keyboardShown = true
    }

    override fun stopInput() {
        keyboardShown = false
    }

    override fun updateState(oldValue: TextFieldValue?, newValue: TextFieldValue) {
    }
}
```
 
**Expected behavior**
If there is soft keyboard then if hidden and after clicking on TextField must be called startInput of  TextInputService even focus was not changed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3943">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
