### ISSUE TITLE
Buggy refresh rate in compose after version 1.5.10-beta02

### ISSUE THREAD

**Issue by JamshedAlamQaderi** [JetBrains/compose-multiplatform#3944]
**Describe the problem**
So, i have been working on a production application and i was using version 1.5.10-beta02. The refresh rate was fine until i updated the compose version to 1.5.10 then it's been laggy in the same codebase without changing anything except the compose version. 

- What specific issue did you encounter? (e.g. missing frames, high CPU usage, memory leaks) : Low refresh rate
- Have you noticed any patterns or specific circumstances under which the problem occurs?: Lagging screen where there is no network call. It's also happen in a static view and looks like lagging

**Affected platforms**
Select one of the platforms below:
- Android
- iOS

If the problem is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version: 1.9.10
- Compose Multiplatform version: 1.5.10
- OS version(s) (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 

**Sample code**
If possible, provide a small piece of code that reproduces the problem. If the code snippet is too large to paste here, please link to a Gist, a GitHub repo, or any other public code repository.

**Reproduction steps**
I have encountered this problem only when trying to update from `1.5.10-beta02` to `1.5.10`.

**Comment by elijah-semyonov** [comment]
Hi, if the Android is also affected, please, write a ticket with more information included (information you provided doesn't suffice) at https://issuetracker.google.com/issues/new?component=612128 and add a link to the issue here.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3944">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
