### ISSUE TITLE
Allow user to set internal jlink args

### ISSUE THREAD

**Issue by dosier** [JetBrains/compose-multiplatform#3946]
I am building a desktop launcher app with compose, this app is supposed to launch another java client that uses the same JRE as shipped with the launcher app. However, the JRE created in the distribution does not include native commands as `--strip-native-commands` is set to `true` in org.jetbrains.compose.desktop.application.tasks.AbstractJLinkTask. 

This property is currently not visible from task configuration as its visibility is internal:
```kt
    @get:Input
    internal val stripNativeCommands: Property<Boolean> = objects.notNullProperty(true)
```
It would be nice if we could set this option from the gradle task configuration.

Currently using this as a workaround:
```kt
tasks {
    // https://github.com/JetBrains/compose-multiplatform/issues/3946
    withType(AbstractJLinkTask::class) {
        try {
            val stripNativeCommandsField = AbstractJLinkTask::class.java.getDeclaredField("stripNativeCommands")
            stripNativeCommandsField.setAccessible(true)
            val stripNativeCommands = stripNativeCommandsField.get(this) as Property<Boolean>
            stripNativeCommands.set(false)
        } catch (e: Exception) {
            throw RuntimeException("Failed to modify stripNativeCommands property", e)
        }
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3946">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
