### ISSUE TITLE
Problem with Window Insets on Android

### ISSUE THREAD

**Issue by pitampoudel** [JetBrains/compose-multiplatform#3948]
I am facing a UI issue on Android. I am using an edge-to-edge feature provided at androidx.activity.enableEdgeToEdge and handling the window insets myself. Everything is fine but when I rotate my device my text fields go up and overlap with the status bar. And also sometimes when I scroll the page padding gets added to its opposite end.

**Versions**
- Kotlin version: 1.9.20
- Compose Multiplatform version: 1.5.10

https://github.com/JetBrains/compose-multiplatform/assets/54230060/9bef5d6c-9de6-4470-be43-abd330b79bf3

**Comment by m-sasha** [comment]
Compose Multiplatform team is not developing the Android part of Compose. Please file a bug in the Android Tracker, or ask a question in #compose-android on the kotlinlang slack, or just on stackoverflow.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3948">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
