### ISSUE TITLE
Will you consider a PR for updating target hierarchy for ImageViewer sample?

### ISSUE THREAD

**Issue by shalva97** [JetBrains/compose-multiplatform#3949]
A build file for shared code for ImageViewer uses old way of defining iosMain

https://github.com/JetBrains/compose-multiplatform/blob/4a020e98409e6166e8cd21ca75b0dc31fe5a2bfc/examples/imageviewer/shared/build.gradle.kts#L20

My plan is to refactor it according to https://kotlinlang.org/docs/whatsnew1920.html#set-up-the-target-hierarchy

**Comment by elijah-semyonov** [comment]
Please do! We accept PRs that bring enhancements and make things up-to-date.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3949">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
