### ISSUE TITLE
OutlinedTextField in iOS app exhibits strange behavior

### ISSUE THREAD

**Issue by jamesbmorris4444** [JetBrains/compose-multiplatform#3952]
**Describe the bug**
OutlinedTextField in iOS app exhibits strange behavior. The code is here:
```
val text by viewModel.refreshEditTextState.collectAsState()
            Spacer(modifier = Modifier.height(36.dp))
            Row {
                OutlinedTextField(
                    modifier = Modifier
                        .weight(0.7f)
                        .height(60.dp)
                        .testTag("OutlinedTextField"),
                    value = text,
                    onValueChange = {
                        viewModel.refreshEditTextState(it)
                    },
                    shape = RoundedCornerShape(10.dp),
                    label = { Text(Strings.get("initial_letters_of_last_name_text")) },
                    singleLine = true,
                    keyboardOptions = KeyboardOptions(imeAction = ImeAction.Done),
                    keyboardActions = KeyboardActions(
                        onDone = {
                            keyboardController?.hide()
                            handleSearchClick(text)
                        })
                )
            }
```
A video is attached. This issue occurs only on iOS. The same code on Android behaves normally.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.9.20
- OS version(s)* (required for Desktop and iOS issues): Sonoma 14.1
- OS architecture (x86 or arm64): iOS 17.0
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Click in OutlinedTextField and then type letters.
2. Observe the problem

**Expected behavior**
Normal behavior, which I get with the same code on Android.

**Screenshots**
Video is here at this link

https://drive.google.com/file/d/1HFfA3IJ3IUiqDapBxpbAw5HYuLRA80hR/view?usp=drive_link

**Additional context**

**Comment by elijah-semyonov** [comment]
It is a known problem and will be fixed eventually. For temporary fix, [avoid using StateFlow inside text input processing scope](https://medium.com/androiddevelopers/effective-state-management-for-textfield-in-compose-d6e5b070fbe5).
