### ISSUE TITLE
Get dp in Web Js

### ISSUE THREAD

**Issue by MrBzik** [JetBrains/compose-multiplatform#3954]
Hi. I have a Js module. There is no LocalDensity awailable or anything.
Using dppx from org.jetbrains.compose.web.css does not seem to take effect. Only px's.
Is there any way to use density pixels for web?

**Comment by eymar** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio - I guess you're asking about this.

**Comment by MrBzik** [comment]
Hi, I was looking into window's fields, but it won't contain information of actual screen dimensions so I could calculate density per inch. When laucnhing site on mobile, width is for example 360 px and ratio is 2, so resolution is 720. And it's not enough

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3954">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
