### ISSUE TITLE
Where is web version of ImageViewer sample?

### ISSUE THREAD

**Issue by shalva97** [JetBrains/compose-multiplatform#3957]
Here is a pic which is from Kotlin's website
![image](https://github.com/JetBrains/compose-multiplatform/assets/22417494/e09c3035-9f81-4e61-8e9e-934dd3a19857)

Where is the source for Web?

**Comment by imknown** [comment]
- online demo
> https://zal.im/wasm/iv/

- source
> https://github.com/Kotlin/kotlin-wasm-examples/tree/main/compose-imageviewer

**Comment by shalva97** [comment]
thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3957">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
