### ISSUE TITLE
`ComposeUIViewController` resources not released upon back navigation

### ISSUE THREAD

**Issue by brendanw** [JetBrains/compose-multiplatform#3958]
**Describe the bug**
`ComposeUIViewController` references are not freed when back navigating away from `ComposeUIViewController`.

Possibly related to https://github.com/JetBrains/compose-multiplatform/issues/3201 which was reported fixed in `1.9.0`, but folks commented in that thread there might still be further manifestations of the issue

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10
- OS version(s)* (required for Desktop and iOS issues): iOS 17.1.1 (can only reproduce memory leak on physical device, memory is freed in simulator)

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Build and run on physical ios device the `mapbox` branch of this PR that is built against the jetpack compose multiplatform starter template https://github.com/brendanw/compose-multiplatform-template/pull/1
2. Observed realtime memory usage. Observe it increases and does not decreaase as you navigate back and forth between the two view controllers.

**Expected behavior**
Memory allocated by the second viewcontroller should be freed when you back navigate away from that view controller.

**Screenshots**
Reproduction step
![2023-11-20 15 35 06](https://github.com/JetBrains/compose-multiplatform/assets/585321/ce9c0954-cda1-4543-a075-b47fe972f526)

Memory increasing while doing the above sequence of VC bouncing on a physical device
![2023-11-20 15 39 02](https://github.com/JetBrains/compose-multiplatform/assets/585321/36ed2f0e-1eb0-4050-9df3-e56291cb881c)

**Additional context**
Bizarrely I am able to fix the issue if I replace my own implementation of back navigation with the default system navigation bar.

This doesn't work for my use-case as I need a custom `TopAppBar` for my realworld app.

Other strategies I've attempted for mitigating:
- Wrapping the `createMapView` function reference passed to kotlin in a `WeakReference` and nulling out the `value` of that WeakReference when `UiKitView::release` is called.
- Creating my own `ReferenceHolder` class in swift that has one nil-able reference field and implements a ReferenceHolder interface defined in kotlin with a single `release` function. Pass a `ReferenceHolder` that references the native ios view and update `ReferenceHolder.value = null` when `UiKitView::release` is called.

Neither attempts to mitigate the memory leak were successful.

**Comment by elijah-semyonov** [comment]
Thank you for the issue and repro, I'll look into it.

**Comment by elijah-semyonov** [comment]
https://github.com/elijah-semyonov/compose-multiplatform-leak-repro/tree/mapbox
Recreated it without mapbox

**Comment by elijah-semyonov** [comment]
I managed to mitigate the memory leak by hoisting the lambda to pop the view controller inside the `MapWidget` factory function:

```swift
let mapboxVC = Mapbox_iosKt.createMapboxVC(
    createMapView: { [weak self] in 
        MapWidget(frame: self!.view.frame)
    },
    pop: { [weak self] in
        self?.navigationController?.popViewController(animated: true)
    })
```

```kotlin
fun createMapboxVC(
   createMapView: () -> UIView,
   pop: () -> Unit,
) = ComposeUIViewController {
   val mapView = remember { createMapView() }

   Column {
      TopAppBar(
         modifier = Modifier.padding(top = 50.dp),
         title = { Text("Title") },
         navigationIcon = {
            IconButton(
               onClick = { pop() }
            ) {
               Icon(imageVector = Icons.Default.ArrowBack, contentDescription = null)
            }
         },
      )
      UIKitView(factory = {
         mapView
      }, modifier = Modifier.fillMaxSize())
   }
}
```

**Comment by elijah-semyonov** [comment]
Actually, it's leaking too. I'll investigate further.

**Comment by RoniSapirstein** [comment]
Hi, I experience the same issue. I use ComposeUIViewController in a sheetPresentationController, and when I open and close the sheet, the memory increase.

**Comment by elijah-semyonov** [comment]
It should eventually decrease, GC is not deterministic.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3958">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
