### ISSUE TITLE
Mutli UIKitView unable to render compositing

### ISSUE THREAD

**Issue by Gaubee** [JetBrains/compose-multiplatform#3960]
**Describe the bug**
I render WKWebView using UIKitView, but when they are rendered on top of each other, the WebView created later looks transparent, showing the content of the previous WebView.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10
- OS version(s)* (required for Desktop and iOS issues): iOS 17.0.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce & Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/2151644/8bd18813-b7da-41d7-ac51-d63649fc37f1

**Expected behavior**
Both WebViews should display correctly, not penetrate

**Additional context**
here is my repo: https://github.com/BioforestChain/dweb_browser/
By the way, this is not a problem with WKWebView, I tested UILable and the same problem exists

**Comment by Gaubee** [comment]
look like this: #3154

**Comment by Gaubee** [comment]
@elijah-semyonov before release, Is there any way to hack this?

**Comment by elijah-semyonov** [comment]
Sadly, none that I'm aware off

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3960">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
