### ISSUE TITLE
Unresolved reference: containerSize in LocalWindowInfo.current.containerSize

### ISSUE THREAD

**Issue by sawil314** [JetBrains/compose-multiplatform#3963]
**Describe the bug**
If you use ` LocalWindowInfo.current.containerSize` in common Main the error Message "Unresolved reference: containerSize" apppears.
For Desktop it works as expected.

**Affected platforms**
Select one of the platforms below:
- Android

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a multiplatform Project.
2. Add the lines
3. ` var x by remember { mutableStateOf(0) }`
        `x = LocalWindowInfo.current.containerSize.width`
4. Start on Android

**Expected behavior**
There schouldn't be an error.

**Comment by MatkovIvan** [comment]
This API is not available in common/Android - it's declared in non-common `actual` implementation.
It's probably about an IDE bug that shows you API that is not available in common (desktop's Java implementation doesn't fit Android). We're tracking it here - #3503. Closing as duplicate.

PS JetBrains doesn't publish Android artifacts, so if you are facing with an Android only problem, it's better to use Google's issue tracker as mentioned in the template. But it's not this case.

**Comment by nowiwr01w** [comment]
Hey
I don’t know why IDE suggests `containerSize` hint in `commonMain`, but `containerSize` is not marked as `actual` value under the hood
```kotlin
actual interface WindowInfo {
    actual val isWindowFocused: Boolean

    actual val keyboardModifiers: PointerKeyboardModifiers
        get() = WindowInfoImpl.GlobalKeyboardModifiers.value
    
    val containerSize: IntSize get() = IntSize.Zero
}
```
so you can’t use it in `commonMain`

You need to define your own `expect` function like this:
```kotlin
@Composable
expect fun getScreenWidth(): Dp
```

Android implementation:
```kotlin
@Composable
actual fun getScreenWidth() = LocalConfiguration.current
    .screenWidthDp
    .dp
```
Others:
```kotlin
@OptIn(ExperimentalComposeUiApi::class)
@Composable
actual fun getScreenWidth() = LocalWindowInfo.current
    .containerSize
    .width
    .dp
```

**Comment by MatkovIvan** [comment]
@nowiwr01w `WindowInfo.containerSize` is in pixels, not `dp`. The correct way to get `dp` is
```kt
with(density) { containerSize.width.toDp() }
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3963">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
