### ISSUE TITLE
 CJK words can not correctly show in the browser

### ISSUE THREAD

**Issue by ISNing** [JetBrains/compose-multiplatform#3967]
**Describe the bug**
Currently CJK words can not correctly show in the browser
I don't know how does compose get latin font. it might be getting from local system or just package it in the web package, but according to sources i read, it seems compose obtain font from skia, or in other word, render in skia.
If the former one, we just need to add correct font fallback logic and configurations.
To load a a custom full weight font family such as noto sans in just simplified chinese can take up to more than 90 mega bytes, even in local test, it takes me several seconds to load the page with full font familly loaded, that's an unbearable cost.

And this also restricted user input. All the texts are rendered in skiko, so that all the text will have to ensure there's available font to show, If i designed a textfield that allows user to input any characters in unicode, then cjk words can't show up, emojis can't show up and any character not included in packaged font will not show up.(Then we can't simply do compress on font by only include chars we used in webpage like `font-spider`)

I think we must pay attention to this problem.

What I tried to avoid this problem is to load font by font name such as `"Microsoft Yahei"`, `"Noto Sans CJK"`, `"Noto Sans SC"` or all of them with space removed from SkTypeface and convert SkTypeface object into Typeface and then to FontFamily, but that doesn't work...
Or is there any other way available to load local fonts?

Thank you all for your great effort work on this great project.
**Affected platforms**
Select one of the platforms below:
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10

**To Reproduce**
1. Create a Text with cjk word(such as "你好") in canvas
2. Build it and open it in browser
3. And you can see that the word shows as two square

**Expected behavior**
Text should shows up correctly

**Screenshots**
<img width="371" alt="334086eb55d2b8f9a0cc50e16e009046" src="https://github.com/JetBrains/compose-multiplatform/assets/33572057/ccba5985-35cf-4747-93d2-25926e73cdc9">
The chinese words doesn' show correctly

**Comment by ISNing** [comment]
> i try to load resource by using `LaunchedEffect`, it works but the experience is a bit poor.
> 
> ```kotlin
> @OptIn(ExperimentalResourceApi::class)
> suspend fun loadCjkFont(): FontFamily {
>     val regular = resource("font/NotoSansCJKsc-Regular.ttf").readBytes()
>     val bold = resource("font/NotoSansCJKsc-Bold.ttf").readBytes()
>     val italic = resource("font/NotoSansCJKsc-Italic.ttf").readBytes()
> 
>     return FontFamily(
>         Font(identity = "CJKRegular", data = regular, weight = FontWeight.Normal),
>         Font(identity = "CJKBold", data = bold, weight = FontWeight.Bold),
>         Font(identity = "CJKItalic", data = italic, style = FontStyle.Italic),
>     )
> }
> 
> @Composable
> fun App() {
>     var typography by remember { mutableStateOf<Typography?>(null) }
>     LaunchedEffect(Unit) {
>         val font = loadCjkFont()
>         typography = Typography(defaultFontFamily = font)
>     }
> 
>     MaterialTheme(typography = typography ?: MaterialTheme.typography) {...
>     }
> }
> ```
> 
> ![record](https://private-user-images.githubusercontent.com/77878253/289031658-ccab2fdc-75db-4221-b147-0e6a61a09eb3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNzM3ODIsIm5iZiI6MTcwMjE3MzQ4MiwicGF0aCI6Ii83Nzg3ODI1My8yODkwMzE2NTgtY2NhYjJmZGMtNzVkYi00MjIxLWIxNDctMGU2YTYxYTA5ZWIzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDAxNTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NzQ3NDVjMmVjNTNhOWU3NGU5NDVlNTQzOWUwZjMwMjA5ODVhZjZhNWFmODNiYmU5NjMwZWIwYTAxZjExZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Ghpd974A98lFLc2zJq1ZJhTrct53enBrVO5c6XGWMA) [ ![record](https://private-user-images.githubusercontent.com/77878253/289031658-ccab2fdc-75db-4221-b147-0e6a61a09eb3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNzM3ODIsIm5iZiI6MTcwMjE3MzQ4MiwicGF0aCI6Ii83Nzg3ODI1My8yODkwMzE2NTgtY2NhYjJmZGMtNzVkYi00MjIxLWIxNDctMGU2YTYxYTA5ZWIzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDAxNTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NzQ3NDVjMmVjNTNhOWU3NGU5NDVlNTQzOWUwZjMwMjA5ODVhZjZhNWFmODNiYmU5NjMwZWIwYTAxZjExZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Ghpd974A98lFLc2zJq1ZJhTrct53enBrVO5c6XGWMA) ](https://private-user-images.githubusercontent.com/77878253/289031658-ccab2fdc-75db-4221-b147-0e6a61a09eb3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNzM3ODIsIm5iZiI6MTcwMjE3MzQ4MiwicGF0aCI6Ii83Nzg3ODI1My8yODkwMzE2NTgtY2NhYjJmZGMtNzVkYi00MjIxLWIxNDctMGU2YTYxYTA5ZWIzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDAxNTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NzQ3NDVjMmVjNTNhOWU3NGU5NDVlNTQzOWUwZjMwMjA5ODVhZjZhNWFmODNiYmU5NjMwZWIwYTAxZjExZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Ghpd974A98lFLc2zJq1ZJhTrct53enBrVO5c6XGWMA) [ ](https://private-user-images.githubusercontent.com/77878253/289031658-ccab2fdc-75db-4221-b147-0e6a61a09eb3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNzM3ODIsIm5iZiI6MTcwMjE3MzQ4MiwicGF0aCI6Ii83Nzg3ODI1My8yODkwMzE2NTgtY2NhYjJmZGMtNzVkYi00MjIxLWIxNDctMGU2YTYxYTA5ZWIzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDAxNTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NzQ3NDVjMmVjNTNhOWU3NGU5NDVlNTQzOWUwZjMwMjA5ODVhZjZhNWFmODNiYmU5NjMwZWIwYTAxZjExZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Ghpd974A98lFLc2zJq1ZJhTrct53enBrVO5c6XGWMA)

Thank you for your help, here's my implementation with lower invasivieness: https://github.com/ISNing/XWareManage/commit/7c3d63ce93efa6bc169f2c33c5c8be3511f59bb4

But it still can't help with the huge transportation for fetching font files(even if only to load three weights)

Looking forward to official solution.

**Comment by KevinnZou** [comment]
@eymar Is there a plan to address this issue?

**Comment by eymar** [comment]
Yes, we plan to address it after we address the issues which have no workarounds.

**Comment by HamusutaW** [comment]
> i try to load resource by using `LaunchedEffect`, it works but the experience is a bit poor.我尝试使用 `LaunchedEffect` 加载资源，它可以工作，但体验有点差。
> 
> ```kotlin
> @OptIn(ExperimentalResourceApi::class)
> suspend fun loadCjkFont(): FontFamily {
>     val regular = resource("font/NotoSansCJKsc-Regular.ttf").readBytes()
>     val bold = resource("font/NotoSansCJKsc-Bold.ttf").readBytes()
>     val italic = resource("font/NotoSansCJKsc-Italic.ttf").readBytes()
> 
>     return FontFamily(
>         Font(identity = "CJKRegular", data = regular, weight = FontWeight.Normal),
>         Font(identity = "CJKBold", data = bold, weight = FontWeight.Bold),
>         Font(identity = "CJKItalic", data = italic, style = FontStyle.Italic),
>     )
> }
> 
> @Composable
> fun App() {
>     var typography by remember { mutableStateOf<Typography?>(null) }
>     LaunchedEffect(Unit) {
>         val font = loadCjkFont()
>         typography = Typography(defaultFontFamily = font)
>     }
> 
>     MaterialTheme(typography = typography ?: MaterialTheme.typography) {...
>     }
> }
> ```

你好，请问能给一些详细的代码吗？试了一下好像不起作用 QAQ
```kt
@Composable
@Preview
fun MainApp() {
    var typography by remember { mutableStateOf<Typography?>(null) }
    val typographyWithFont = Typography(
        FontFamily(
            Font(
                resource = Res.font.misans_normal,
                weight = FontWeight.Normal,
                style = FontStyle.Normal
            ),
            Font(
                resource = Res.font.misans_bold,
                weight = FontWeight.Bold,
                style = FontStyle.Normal
            ),
            Font(
                resource = Res.font.misans_thin,
                weight = FontWeight.Thin,
                style = FontStyle.Normal
            )
        )
    )
    LaunchedEffect(Unit) {
        typography = typographyWithFont
    }
    MaterialTheme(typography = typography ?: MaterialTheme.typography) {
        Column(horizontalAlignment = Alignment.CenterHorizontally) {
            Row(horizontalArrangement = Arrangement.SpaceEvenly, verticalAlignment = Alignment.Top) {
                Text("首页")
                Text("EnglishText")
            }
        }
    }
}

@Composable
fun Typography(fontFamily: FontFamily, baseTypography: Typography = MaterialTheme.typography) =
    Typography(
        displayLarge = baseTypography.displayLarge.copy(fontFamily = fontFamily),
        displayMedium = baseTypography.displayMedium.copy(fontFamily = fontFamily),
        displaySmall = baseTypography.displaySmall.copy(fontFamily = fontFamily),
        headlineLarge = baseTypography.headlineLarge.copy(fontFamily = fontFamily),
        headlineMedium = baseTypography.headlineMedium.copy(fontFamily = fontFamily),
        headlineSmall = baseTypography.headlineSmall.copy(fontFamily = fontFamily),
        titleLarge = baseTypography.titleLarge.copy(fontFamily = fontFamily),
        titleMedium = baseTypography.titleMedium.copy(fontFamily = fontFamily),
        titleSmall = baseTypography.titleSmall.copy(fontFamily = fontFamily),
        bodyLarge = baseTypography.bodyLarge.copy(fontFamily = fontFamily),
        bodyMedium = baseTypography.bodyMedium.copy(fontFamily = fontFamily),
        bodySmall = baseTypography.bodySmall.copy(fontFamily = fontFamily),
        labelLarge = baseTypography.labelLarge.copy(fontFamily = fontFamily),
        labelMedium = baseTypography.labelMedium.copy(fontFamily = fontFamily),
        labelSmall = baseTypography.labelSmall.copy(fontFamily = fontFamily),
    )
```

**Comment by ISNing** [comment]
> > i try to load resource by using LaunchedEffect, it works but the experience is a bit poor.
> > 
> > ```kotlin
> > @OptIn(ExperimentalResourceApi::class)
> > suspend fun loadCjkFont(): FontFamily {
> >     val regular = resource("font/NotoSansCJKsc-Regular.ttf").readBytes()
> >     val bold = resource("font/NotoSansCJKsc-Bold.ttf").readBytes()
> >     val italic = resource("font/NotoSansCJKsc-Italic.ttf").readBytes()
> > 
> >     return FontFamily(
> >         Font(identity = "CJKRegular", data = regular, weight = FontWeight.Normal),
> >         Font(identity = "CJKBold", data = bold, weight = FontWeight.Bold),
> >         Font(identity = "CJKItalic", data = italic, style = FontStyle.Italic),
> >     )
> > }
> > 
> > @Composable
> > fun App() {
> >     var typography by remember { mutableStateOf<Typography?>(null) }
> >     LaunchedEffect(Unit) {
> >         val font = loadCjkFont()
> >         typography = Typography(defaultFontFamily = font)
> >     }
> > 
> >     MaterialTheme(typography = typography ?: MaterialTheme.typography) {...
> >     }
> > }
> > ```
> 
> <s>
> 你好，请问能给一些详细的代码吗？试了一下好像不起作用 QAQ
> 
> Hi, could you please give me some detailed code? I tried it but it doesn't work.
> </s>
> ```kt
> @Composable
> @Preview
> fun MainApp() {
>     var fontFamily by remember { mutableStateOf<FontFamily?>(null) }
>     val customFont = MiSansVfFont()
>     LaunchedEffect(Unit) {
>         fontFamilyby = customFont
>     }
>     MaterialTheme {
>         Column(horizontalAlignment = Alignment.CenterHorizontally) {
>             Row(horizontalArrangement = Arrangement.SpaceEvenly, verticalAlignment = Alignment.Top) {
>                 Text("首页", fontFamily = fontFamily ?: MaterialTheme.typography.displayMedium.fontFamily)
>                 Text("EnglishText", fontFamily = fontFamily ?: MaterialTheme.typography.displayMedium.fontFamily)
>             }
>         }
>     }
> }
> 
> @Composable
> fun MiSansVfFont() =
>     FontFamily(
>         Font(
>             resource = Res.font.misans_vf_normal,
>             weight = FontWeight.Normal,
>             style = FontStyle.Normal
>         ),
>         Font(
>             resource = Res.font.misans_vf_bold,
>             weight = FontWeight.Bold,
>             style = FontStyle.Normal
>         ),
>         Font(
>             resource = Res.font.misans_vf_thin,
>             weight = FontWeight.Thin,
>             style = FontStyle.Normal
>         )
>     )
> ```
> 
> 原来直接用就可以了，不需要这么麻烦 `Text("首页", fontFamily = MiSansFont()`
> 
> 但是上面的代码在 JVM 是正常的，在 Web 却显示方块，很奇怪
> 
> I found that it is OK to use it directly, no need to be so complicated. `Text("首页", fontFamily = MiSansFont()`
> 
> But the above code works in JVM, but it is displayed as a square on the Web, which is very strange

Don't know what resource library you're using, but I guess it's because for the web target, the font files are fetched asyncnormously (calling the getter of the resource will return null at the beginning when the page is loaded), and when it comes to the first composing, the fonts aren't loaded.
Then you will have to handle expected the application recomposing when the fonts loaded manually.

（虽然我英文很烂，但是应该能看懂，懒得中英再写两遍了[捂脸]）

**Comment by Omico** [comment]
Is there any method to avoid loading large fonts?
https://github.com/OmicoDev/wwm
https://wwm.omico.me
![image](https://github.com/JetBrains/compose-multiplatform/assets/14316223/d9fbfe24-fbf0-4f7d-8ab7-28a5725d266a)

**Comment by eymar** [comment]
@Omico you might try to use Local Font Access API https://developer.mozilla.org/en-US/docs/Web/API/Local_Font_Access_API, it's experimental and available only in Chrome and Edge.

**Comment by eymar** [comment]
Compose Multiplatform 1.7.0-dev1721 is out and it contains the Fonts fallback provider change:
https://github.com/JetBrains/compose-multiplatform-core/pull/1400 (please take a look to see a usage example).

That version of Compose for Web can be used either with kotlin 1.9.24 or with 2.0.10-RC-515 (it won't work with kotlin 2.0).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3967">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by djj20115502** [comment]
Also use skio，flutter can use browser fonts，compose ....
