### ISSUE TITLE
Glitch in navigation between Compose and Swift UI

### ISSUE THREAD

**Issue by GuilhE** [JetBrains/compose-multiplatform#3969]
**Describe the bug**
Glitch in navigation between Compose and Swift UI in a form of vertical white line on the device (simulator seems ok).
Navigation it's handled [natively](https://github.com/GuilhE/Expressus/blob/6a739c1cb7e017226b938aa27ef44d1bd1de5f3c/iosApp/iosApp/Screens/ExpressusSelectorScreen.swift#L20) on iOS side. All compose [screens](https://github.com/GuilhE/Expressus/tree/main/iosApp/iosApp/Screens) are inside `UIViewControllerRepresentable`.

Compose > Compose ✅ 
Compose > Swift UI ✅ 
Swift UI > Compose 🐛  

**Affected platforms**
- iOS (device)

**Versions**
- Kotlin version: **1.9.20**
- Compose Multiplatform version: **1.5.11** (then I've tested with **1.5.10** and it also has it)
- OS version(s) (required for Desktop and iOS issues): **iphone 13 mini iOS 17.1.1**
- OS architecture (x86 or arm64): **arm64**

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. checkout https://github.com/GuilhE/Expressus
2. run iosApp
3. enter in Swift_UI screen
4. go back

**Expected behavior**
No glitch

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/2677139/32379b90-08cf-4408-b13f-a1629690a8a6

Possible related https://github.com/JetBrains/compose-multiplatform/issues/3492?

**Comment by mazunin-v-jb** [comment]
Thank you for submitting, we will take a look.

**Comment by hoangchungk53qx1** [comment]
any news version 1.6.0

**Comment by GuilhE** [comment]
Tested, still happening with:

```
gradleComposeMultiplatform = "1.6.0-beta01"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
composeMultiplatformCompiler = "1.5.8-beta01"
androidxCompose = "1.6.0"
androidxComposeCompiler = "1.5.8-dev-k1.9.22-42b6ec2b037"
```

**Comment by GuilhE** [comment]
Tested, still happening with:```

kotlin = "1.9.22"
gradleComposeMultiplatform = "1.6.0-rc01"
composeMultiplatformCompiler = "1.5.8.1-beta02"
```

**Comment by GuilhE** [comment]
Tested, still happening with:

```
kotlin = "1.9.23"
gradleComposeMultiplatform = "1.6.1"
composeMultiplatformCompiler = "1.5.10.1"
```

**Comment by elijah-semyonov** [comment]
It's a visual glitch of the compositor services in iOS, that don't properly synchronise internal at-moment state of CATransaction responsible for the animation of CAMetalLayer frame and CAMetalDrawable presentation into this layer.

I'll keep my eyes on it and see if any solution arises, but for now it seems like something what we can't fix.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3969">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
