### ISSUE TITLE
Lwjgl crash in skiko 0.7.84

### ISSUE THREAD

**Issue by K-o-d-y** [JetBrains/compose-multiplatform#3972]
**Affected platforms**
Desktop

**Versions**
- Kotlin version*:  1.9.20
- Compose Multiplatform version*:  1.5.10
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues):  JDK 17.0.8

https://github.com/JetBrains/skiko/pull/811

![{798CBBA9-9FAB-47bf-8CCA-DCF98B0B239D}](https://github.com/JetBrains/compose-multiplatform/assets/45705915/95c39952-f3d4-4c83-b81c-f7598dc77285)

Current thread (0x000001d5ba2a9610):  JavaThread "main" [_thread_in_native, id=15916, stack(0x0000005496400000,0x0000005496500000)]

Stack: [0x0000005496400000,0x0000005496500000],  sp=0x00000054964fee20,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.jetbrains.skia.DirectContextKt._nMakeGL()J+0
j  org.jetbrains.skia.DirectContextKt.access$_nMakeGL()J+0
j  org.jetbrains.skia.DirectContext$Companion.makeGL()Lorg/jetbrains/skia/DirectContext;+10
j  MainKt.main()V+80
j  MainKt.main([Ljava/lang/String;)V+0
v  ~StubRoutines::call_stub

**Comment by fan87** [comment]
I had the exact same problem, and I did some debugging, and I can confirm it only confirms on Windows.

```kt
/**
 * Load OpenGL library into memory.
 *
 * Should be called before any OpenGL operation.
 *
 * The current implementation loads OpenGl lazily on Windows, and at app startup on Linux/macOs.
 *
 * Some Windows machines don't have OpenGL (usually CI machines), so we'll fallback to other renderers on them.
 *
 * Throws [RenderException] if OpenGL library can't be loaded.
 */
internal fun loadOpenGLLibrary() {
    if (hostOs.isWindows) {
        loadOpenGLLibraryWindows()
    } else {
        // do nothing, the library should be already available
    }
}
```

But DirectContext.makeGL() does not call loadOpenGLLibrary

In my case, it crashed here:
```cpp
    HGLRC WINAPI wglGetCurrentContext() {
        typedef HGLRC (WINAPI * PROC_wglGetCurrentContext) (void);
        static auto wglGetCurrentContext = (PROC_wglGetCurrentContext) GetProcAddress(OpenGL32Library, "wglGetCurrentContext");
        return wglGetCurrentContext();
    }
```
`OpenGL32Library` is nullptr, and it's set by `loadOpenGLLibraryWindows`, but it was never called.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3972">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
