### ISSUE TITLE
Change `positionPercentage` API of just created `SplitPaneState`.

### ISSUE THREAD

**Issue by vdshb** [JetBrains/compose-multiplatform#3973]
**Describe the bug**

I need to change `positionPercentage` of just created `SplitPaneState`. 

Long story short, recreating `SplitPaneState` is not an option in my architecture. Use it in `SplitPane` just to calculate internal `minPosition` and `maxPosition` is a poor option as well.

**Affected platforms**
- Desktop

**Reproducer**

```kotlin
import org.jetbrains.compose.splitpane.SplitPaneState

fun main() {
    val splitPaneState = SplitPaneState(0.6f, true)
    splitPaneState.dispatchRawMovement(0.2f)
    println(splitPaneState.positionPercentage)  // prints "NaN"
}
```

**Expected behavior**
Some API supposed to be available to change/reset  `positionPercentage` of already created but not yet used `SplitPaneState`.

**Expected behavior**
API are internal or buggy until put `SplitPaneState` into `SplitPane`.

**Comment by vdshb** [comment]
I've added https://github.com/JetBrains/compose-multiplatform/pull/3974. It solves this issue.

**Comment by vdshb** [comment]
Fixed in https://github.com/JetBrains/compose-multiplatform/pull/3974

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3973">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
