### ISSUE TITLE
Support for Downloadable Google Fonts (ui-text-google-fonts)

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#3976]
Jetpack Compose allows you to download fonts from Google Fonts asynchronously in your app, rather than having to bundle them in the application.

https://developer.android.com/jetpack/compose/text/fonts#downloadable-fonts

This is done via the `androidx.compose.ui:ui-text-google-fonts` artifact, which exposes a `GoogleFont.Provider`, allowing developers to quickly add new fonts to their apps (without increasing the size of the initial app download).

Would be great to have support for these downloadable fonts in Compose Multiplatform as well.

**Comment by kasem-sm** [comment]
Any updates on this? Thanks.

**Comment by terrakok** [comment]
We don't have a plan to support it in the near future

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3976">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
