### ISSUE TITLE
Expose Api to check if resource exists before using to avoid crashes 

### ISSUE THREAD

**Issue by ahna92** [JetBrains/compose-multiplatform#3979]
**Issue**
Sometime we need to load images from resources dynamically , like images as such

```kotlin
val code = country.code?: "default"
Image(
  painter = painterResource(
  "flags/flag_${code}.png"
  ),
  contentDescription = "country flag"
)
```

Now if code requested was not found this will crash with `MissingResourceException`

**Proposed solution** 

Adding `Resource.exists(name):Boolean` to check before using the resource 

```kotlin
var res = "flags/flag_${country.code}.png"
if (!Resource.exists(res))
     res = "flags/flag_default.png"
Image(
  painter = painterResource(res),
  contentDescription = "country flag"
)
```

**Another Proposed Solution** 
or provide a placeholder/default to `painterResource`
```kotlin
Image(
  painter = painterResource(
  id = "flags/flag_${code}.png",
  default = "flags/flag_default.png"
  ),
  contentDescription = "country flag"
)
```
**Another Proposed Solution** 
or return null Painter in case resource not found
```
fun painterResource(id: ResourceId): Painter?
```

```kotlin
Image(
  painter = painterResource("flags/flag_${code}.png") ?: painterResource("flags/flag_default.png"),
  contentDescription = "country flag"
)
```

**Comment by terrakok** [comment]
Hello!  We want to provide compile time checks for the resources API and to avoid scenarios with a dynamic resource access out of the box.
For your case you are supposed to make a map with a mapping a flag code -> resource.

There is a low level API to read resources by path but it doesn't have any guaranties and should be wrapped with `try {} catch {}`

**Comment by ahna92** [comment]
@terrakok a compile class like android's `R.*` would be great and fast 

Can you share the low level api ?

**Comment by terrakok** [comment]
https://github.com/JetBrains/compose-multiplatform/blob/55724f0b5a56a4a86cc45d74b77cd5b6cf3ac02a/components/resources/library/src/commonMain/kotlin/org/jetbrains/compose/resources/ResourceReader.kt#L15

**Comment by terrakok** [comment]
https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3979">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
