### ISSUE TITLE
Provide `TooltipArea` for Web target

### ISSUE THREAD

**Issue by AzimMuradov** [JetBrains/compose-multiplatform#3981]
There are should be `TooltipArea` for Compose Multiplatform for Web (`Canvas` based).

**Comment by elijah-semyonov** [comment]
I'll close this issue in favour of more general one:
https://github.com/JetBrains/compose-multiplatform/issues/4156

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3981">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
