### ISSUE TITLE
KeyboardActions onDone triggers on Key Down and leaves Key Up unhandled

### ISSUE THREAD

**Issue by findusl** [JetBrains/compose-multiplatform#3982]
**Describe the bug**
I have a dialog with an OutlinedTextField. It uses the `KeyboardActions(onDone = { onDone() }` to handle the enter key and close the dialog. However since the onDone triggers on "key down", the enter key has to eventually come back up. This "up" is now handled by the newly focussed view in the background. If that view is clickable, it handles the "key up " as a click.

I believe it is unintended to have the enter key handled twice. If a composable like the TextField handles the enter key press, I'd expect it to handle the whole event.

**Affected platforms**
Select one of the platforms below:
- Desktop
- ~~Possibly others with a keyboard connected~~ (@mazunin-v-jb: checked on iOS and Android too - not reproduced)

**To Reproduce**
1. Clone this repo: https://github.com/findusl/onDoneProblem
2. Run on JVM
3. click the "name" text
4. focus the textfield
5. press enter (it should disappear and reappear once you let go of enter, because the text gets focussed and handles the key up)

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10
- OS version(s)* (required for Desktop and iOS issues): MacOS 14.1.1 (23B81)
- OS architecture (x86 or arm64): Apple Silicon
- JDK (for desktop issues): 17

**Comment by mazunin-v-jb** [comment]
Hello, thank you for submitting the issue!
I'll pass it to the team.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3982">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
