### ISSUE TITLE
application doesn't wait for recompositions

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#3987]
`application` returns even when there should be a pending recomposition.

**Affected platforms**
- Desktop
- Possibly others

**Reproducer**
```
fun main() {
    application {
        var settingsLoaded by remember { mutableStateOf(false) }
        LaunchedEffect(Unit) {
            val value = withContext(Dispatchers.IO) {
                delay(1000)
                true
            }
            settingsLoaded = value
            println("Settings loaded")
        }

        if (settingsLoaded) {
            Window(onCloseRequest = {}) {
                Text("Application")
            }
        }
    }
}
```

Running the code above will print "Settings loaded" and then the process will die.
The reason for this is that `application` only waits until there are no more active coroutines in the composition. From the documentation:

> When there is no any active compositions, this function will end.
> Active composition is a composition that have active coroutine (for example, launched in
> [LaunchedEffect]) or that have child composition created inside [Window], [DialogWindow], or [Tray].

So when, in the code above, the coroutine in `LaunchedEffect` completes, `application` returns, even though there should be a pending recomposition due to the change in `settingsLoaded`.

This can be worked around by adding:
```
if (!settingsLoaded) {
    LaunchedEffect(Unit) {
        delay(Duration.INFINITE)
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3987">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
