### ISSUE TITLE
Cannot access class "Check your module classpath for missing or conflicting dependencies"

### ISSUE THREAD

**Issue by tethridge** [JetBrains/compose-multiplatform#3992]
**Describe the bug**
**NOTE:** the sqldelight team believes that they cannot fix this issue within their code base.

I created a new compose multiplatform project (for Android & iOS) using the [kmp.jetbrains.com](https://kmp.jetbrains.com/) wizard.  Then I added in sqldelight.  After adding in sqldelight, I added a reference to one of the sqldelight classes MainViewController.kt under iosMain.  This causes the build to fail with errors. 

Cannot access class 'app.cash.sqldelight.db.SqlSchema'. Check your module classpath for missing or conflicting dependencies
```
Unresolved reference: SqlDriver
Cannot access class 'app.cash.sqldelight.db.SqlSchema'. Check your module classpath for missing or conflicting dependencies
Cannot access class 'app.cash.sqldelight.db.SqlDriver'. Check your module classpath for missing or conflicting dependencies
```

**Affected platforms**
- iOS and Android because the build fails completely.

**Versions**
- Kotlin version*: 1.9.20 
- Compose Multiplatform version*: 1.5.4
- Compose plugin: 1.5.10
- Compose compiler: 1.5.4
- OS version(s)* (required for Desktop and iOS issues): Developing on Macbook Pro running Ventura 13.6.  Compiling to run in iOS simulator running Xcode 14.3.1 loaded with iOS 17 in the simulator.
- OS architecture (x86 or arm64):  Apple M1
- JDK (for desktop issues): JDK 17

**To Reproduce**
I created a sample project to reproduce the issue. https://github.com/tethridge/SqlDriverNotFound

Steps and/or the code snippet to reproduce the behavior:
1. Download the project
2. Open a command prompt and navigate into project directory
3. run $ ./gradlew :composeApp:clean
4. run $ ./gradlew :composeApp:assemble

**Expected behavior**
Build should compile without errors so that the program can run successfully.

**Additional context**
Members of the sqldelight team have already looked into this issue and they feel that they are unable to fix it from within the sqldelight code base.  See the comment when they closed the ticket.  https://github.com/cashapp/sqldelight/issues/4473

They are able to get rid of the exception by removing compose, but that is not an acceptable solution.  I would prefer to not have to create a separate KMP module either, which was their other solution.

**Comment by dima-avdeev-jb** [comment]
please follow this Issue https://github.com/JetBrains/compose-multiplatform/issues/3437

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3992">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
