### ISSUE TITLE
Compose Compiler build for KMM 2.0.0-Beta1

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-multiplatform#3993]
Looks like there is an issue running Compose Compiler on iOS: https://youtrack.jetbrains.com/issue/KT-63653

This bug is to track publishing of a Kotlin Multiplatform build of Compose Compiler for Kotlin 2.0.0-Beta1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3993">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
