### ISSUE TITLE
Setting cursor for window does not always behave as expected

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#40]
Consider the following snippet:

```kotlin
fun main() = Window(title = "JFrame properties") {
    var crosshairCursor by remember { mutableStateOf(false) }
    onCommit(crosshairCursor) {
        val jFrame = AppManager.focusedWindow?.window
        jFrame?.let {
            it.cursor =
                if (crosshairCursor) Cursor.getPredefinedCursor(Cursor.CROSSHAIR_CURSOR) else Cursor.getDefaultCursor()
        }
    }
    MaterialTheme {
        Button(onClick = { crosshairCursor = !crosshairCursor }) {
            Text("Toggle crosshair cursor")
        }
    }
}


```

- Toggling the cursor via button press works fine
- Defocusing the window resets the cursor to the default cursor when re-entering the window.
- Refocusing the window via the dock icon uses the correct custom cursor again.

![Untitled](https://user-images.githubusercontent.com/2178959/97716323-c4585400-1ac3-11eb-8b20-9948bbf6e83f.gif)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6394">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
