### ISSUE TITLE
[Linux] musl / Alpine support

### ISSUE THREAD

**Issue by xdevs23** [JetBrains/compose-multiplatform#4001]
Although Skia should be able to be run on musl (instead of glibc), Skiko does not appear to be built for musl and only GNU/Linux. This means that it does not work on Alpine-based distros such as postmarketOS.

It'd be great if you could provide Compose Multiplatform not just for glibc but also for Linux distributions that use musl.

If I run a Compose Multiplatform (Desktop) application on a musl system (I tried it on postmarketOS), I get an error that `ld-linux-aarch64.so.1` can't be found. Even after installing gcompat or glibc, it still does not work. It gives an error saying that the symbol `__sprintf_chk` can't be found by the skiko library.

I tried this on an ARM64 system so I'm not sure how this behaves on x86_64.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4001">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
