### ISSUE TITLE
SwingPanel doesn't apply Modifier.offset if it's after Modifier.size

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#4005]
When `SwingPanel` is given `modifier = Modifier.size(100.dp).offset(50.dp, 50.dp)`, the offset isn't applied.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: `jb-main` tip
- OS version(s)* (required for Desktop and iOS issues): macOS
- OS architecture (x86 or arm64): arm64

**To Reproduce**
```
fun main() = singleWindowApplication {
    Box(Modifier.fillMaxSize()) {
        SwingPanel(
            modifier = Modifier.size(100.dp).offset(50.dp, 50.dp),
            factory = {
                JPanel().also {
                    it.background = java.awt.Color.RED
                }
            }
        )
//        Box(
//            modifier = Modifier.size(100.dp).offset(50.dp, 50.dp),
//        ) {
//            Box(Modifier.fillMaxSize().background(Color.Red))
//        }
    }
}
```

**Expected behavior**
The red box should be offset inside the window.

**Screenshots**
<img width="801" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5230206/a20da959-7b47-49b2-a3e3-868195e52e81">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4005">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
