### ISSUE TITLE
Window doesn't enter maximized state after being in fullscreen one

### ISSUE THREAD

**Issue by FlamyCat** [JetBrains/compose-multiplatform#4006]
Window enters fullscreen mode when window placement is set dynamically to `WindowPlacement.Fullscreen` from maximized state, but not the other way around. However, window can enter the floating state after being in fullscreen one.

**Affected platforms**

- Desktop

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)*: Fedora Linux 39
- OS architecture: x86
- JDK: corretto-18

**Reproduction**
The following code demonstrates the problem:
```kotlin
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.WindowPlacement
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState


fun main() = application {
    val state = rememberWindowState(
        placement = WindowPlacement.Maximized
    )

    var isFullscreen by remember { mutableStateOf(false) }

    Window(onCloseRequest = ::exitApplication, state = state) {
        Button(
            onClick = {
                isFullscreen = !isFullscreen

                state.placement = if (isFullscreen) WindowPlacement.Fullscreen else WindowPlacement.Maximized
            }
        ) {
            Text("Toggle full screen")
        }
    }
}
```

**Expected behavior**
The window should enter maximized state after being in fullscreen mode.

**Demonstration**

https://github.com/JetBrains/compose-multiplatform/assets/91844722/14080707-80e6-44ac-a10a-dd9695785452

**Comment by m-sasha** [comment]
Thanks for the report. Fullscreen mode is known to be buggy on Linux, unfortunately.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4006">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
