### ISSUE TITLE
MissingResourceException for iOS build

### ISSUE THREAD

**Issue by krisbitney** [JetBrains/compose-multiplatform#4008]
**Describe the bug**
At runtime I get a MissingResourceException for my iOS build. I am using moko resources library.

`Uncaught Kotlin exception: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: font/nunito_black.ttf`

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Mac OS Ventura 13.16.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Clone app repo `https://github.com/krisbitney/yuli`
2. Download content of `https://github.com/krisbitney/yuli-ios-api` repo and edit `shared/build.gradle.kts` to point pod dependency path to `yuli-ios-api` root
3. Assemble packages using `./gradlew assemble` from yuli repo root
4. Try to launch launch iOS app

**Expected behavior**
Expected resources to be copied into app

**Additional context**
I am using cocoapods. I tried adding `extraSpecAttributes["resources"] = "['src/commonMain/resources/**', 'src/iosMain/resources/**', 'compose-resources']"` to the cocoapods configuration in `shared/build.gradle.kts` file but it did not fix the issue.

Project root: https://github.com/krisbitney/yuli/tree/main
root/shared/build.gradle.kts: https://github.com/krisbitney/yuli/blob/main/shared/build.gradle.kts

Note that I am running the ios app on xcode because I can't get the simulator to start from Android Studio or Fleet.

**Comment by m-sasha** [comment]
Please see the discussion [here](https://github.com/JetBrains/compose-multiplatform/issues/3800). Let me know if there are more questions.

**Comment by krisbitney** [comment]
> Please see the discussion [here](https://github.com/JetBrains/compose-multiplatform/issues/3800). Let me know if there are more questions.

It sounds like a potential fix is to add `['build/compose/ios/shared/compose-resources']`, but that directory doesn't seem to exist anywhere. Is it a temporary folder that is later removed? Or should I instead add something like `build/processedResources/metadata/iosMain`?

**Comment by m-sasha** [comment]
@dima-avdeev-jb Can you assist here?

**Comment by krisbitney** [comment]
I am writing my own simple localization setup and removing moko. I will update to say if this fixes the issue.

**Comment by krisbitney** [comment]
That worked. As others have said, the problem is that moko plugin actually blocks the generation of (or removes) the `build/compose` folder altogether. I know moko provides some xcode build phase scripts to copy the resources over, but those didn't work for me. I will post my custom localization solution soon in case anyone running into this problem decides to go that route as well.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4008">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
