### ISSUE TITLE
[Android only] TextField: Keyboard does not reopen on tap after an initial dismissal

### ISSUE THREAD

**Issue by creativedrewy** [JetBrains/compose-multiplatform#4010]
**Describe the bug**
Tapping on a TextField, then dismissing the keyboard, then tapping again does not bring the keyboard back up.

https://github.com/JetBrains/compose-multiplatform/assets/2018851/eabc9e8e-d230-4b96-ad04-5b941ac7ffa6

**Affected platforms**
Select one of the platforms below:
- Android

**NOTE**: I'm aware instructions for Android are to file with Google, but I'm only seeing this issue inside of a Kotlin multiplatfrom codebase, and not Android more generally.

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Android 11 & 13
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Tap on a TextField for the first time
2. Dismiss the system keyboard so that the textfield is still focused
3. Tap on the TextField again

**Expected behavior**
The keyboard should reopen so more text can be input. However, it does not.

**Comment by creativedrewy** [comment]
**UPDATE**: I have filed on the Google issue tracker as well: https://issuetracker.google.com/issues/315206572

**Comment by m-sasha** [comment]
Hi. A Kotlin multiplatform on android is just a plain android app, so you should be able to reproduce it in a regular Android project...

**Comment by ErickSorto** [comment]
I am also having the same issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4010">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
