### ISSUE TITLE
Popups/ExposedDropDown is covered by Keyboard on iOS

### ISSUE THREAD

**Issue by chrisjenx** [JetBrains/compose-multiplatform#4011]
**Describe the bug**

See screenshot

On iOS Popups or in this case the exposed drop down is covered by the virtual keyboard on iOS. (Correct on Android).

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*:  1.5.11
- OS version(s)* (required for Desktop and iOS issues): iOS 17.0.1 (macOS 13.6.2)
- OS architecture (x86 or arm64):  M2 (Arm64)
- JDK (for desktop issues):  Built with JDK 18

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create exposed dropdown with list longer than screen.
2. Open keyboard on iOS, anything that drops below the keyboard is hidden behind it

**Expected behavior**
-  Either the Popup should go over the keyboard
- Or pad the popup bottom so it doesn't get covered by the keyboard

**Screenshots**
iOS on left is covering dropdown results

<img width="944" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/1167793/c00a44ab-9b92-485f-ad6c-a5a941c64487">

**Additional context**
This Dropdown is inside `BottomSheetDialogModal`

Note setting windowInsetsPadding on the ExposedDropdown does help but is still covered a little:

```
ExposedDropdownMenu(
                expanded = expanded,
                modifier = Modifier.exposedDropdownSize().windowInsetsBottomHeight(WindowInsets.ime),
                onDismissRequest = { expanded = false },
            ) {
```

**Comment by m-sasha** [comment]
Thanks for the report. We're working on placing popups and dialogs in the correct layer.

**Comment by dima-avdeev-jb** [comment]
Thanks! I will take a look!

**Comment by dima-avdeev-jb** [comment]
@chrisjenx Can you please provide a minimal reproducible sample on GitHub?

**Comment by ShmuelCammebys** [comment]
So is this resolved?

**Comment by chrisjenx** [comment]
Still broken

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4011">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
