### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2023.3)

### ISSUE THREAD

**Issue by krasniuk** [JetBrains/compose-multiplatform#4012]
Not compatible with the version of your running IDE (IntelliJ IDEA 2023.3)
Please Update [Erlang](https://plugins.jetbrains.com/plugin/7083-erlang) plugin to be compatible with the latest version on IntelliJ

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4012">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
