### ISSUE TITLE
TextField always scroll to top on first focus

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#4014]
**Describe the bug**
When a TextField, which contains many lines of text initially, gets the first focus, it would scroll to the top unexpectedly.

**Affected platforms**
Select one of the platforms below:
- Desktop

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Mac 14.0 Beta
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

```
@Composable
fun App() {
    val text = remember { "Super long text\n\n".repeat(100) }
    val scrollState = rememberScrollState()

    Box {
        TextField(
            value = text,
            onValueChange = {},
            modifier = Modifier.fillMaxSize().verticalScroll(scrollState),
        )
        VerticalScrollbar(
            modifier = Modifier.align(Alignment.CenterEnd),
            adapter = rememberScrollbarAdapter(scrollState),
        )
    }
}
```

1. Run the app
2. Scroll the TextField to bottom without clicking it
3. Click on a line
4. The TextField would scroll to the top

**Expected behavior**
In step 4, the textfield should stay at the selected line without scrolling.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/14835950/dba5e748-b748-4721-a425-17bd46a8fc6e

**Additional context**
The issue is very noticable when there are many multiline TextField in the same screen.

**Comment by m-sasha** [comment]
This is a known bug in `TextField` itself, reported [on Google's bug tracker](https://partnerissuetracker.corp.google.com/issues/235693496). Please follow the issue there.

**Comment by glureau** [comment]
Is there a public link available @m-sasha ?

**Comment by MatkovIvan** [comment]
https://issuetracker.google.com/issues/235693496

Sorry, it auto-redirects each time for the logged-in account. The key part here is the issue number - it's the same for public and private hosts

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4014">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
