### ISSUE TITLE
[MacOS] CJK character text weight cannot be displayed correctly in MacOS

### ISSUE THREAD

**Issue by ShirasawaSama** [JetBrains/compose-multiplatform#4015]
**Describe the bug**

CJK characters text weight cannot be displayed correctly in MacOS.

After setting `ExtraBold` and `Bold` for `fontWeight`, only English letters have weight applied correctly. But CJK characters are still the default weight.

**Affected platforms**

- Desktop (MacOS)

**Versions**

- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.11
- OS version(s)*: MacOS Sonoma 14.1.1 (23B81)
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): BellSoft Liberica JDK 21 / Corretto 19

**To Reproduce**

```kotlin
import androidx.compose.material3.Text

Text("Hello, 1你好1, 1こんにちは1, 1안녕하세요1.", fontWeight = FontWeight.ExtraBold)
Text("Hello, 1你好1, 1こんにちは1, 1안녕하세요1.", fontWeight = FontWeight.Bold)
```

**Expected behavior**

All characters have the same weight.

**Screenshots**

MacOS (Wrong):

![a9f959173ca1604cbbdc3f46b243d5fe](https://github.com/JetBrains/compose-multiplatform/assets/17093811/dddffd3f-d20b-4362-b501-f04f19de635d)

Windows (Correct):

![ee433ba97a509a17be6c310416e529a6](https://github.com/JetBrains/compose-multiplatform/assets/17093811/f2c7b03c-a627-4857-9e3a-e861ff7a21cf)

Chrome in MacOS (Correct):

**Hello, 1你好1, 1こんにちは1, 1안녕하세요1.**

![5d9dd25a0551c38001f34e67ca81ccff](https://github.com/JetBrains/compose-multiplatform/assets/17093811/9628e316-72c0-4c55-abea-822942b45ad5)

**Comment by m-sasha** [comment]
There does seem to be a slight increase in thickness, but it's barely noticeable:

<img width="319" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5230206/0ecdd3a1-9e3a-417c-b042-7a730e5e6328">

**Comment by m-sasha** [comment]
Probably an issue with the font itself, but I don't know enough to say for sure.

**Comment by ShirasawaSama** [comment]
@m-sasha If font weight is set in composite, the width difference between CJK characters and English characters is particularly large, which is obviously abnormal.

I infer that there may be a lack of transitional preset fonts between fonts of different weights. As shown in the figure, there are only two fonts between 100-500 and 600-1000, while on Chrome, there are transitional fonts between 100, 200, 300, 400, 500, 600, and 700-900.

<img width="252" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/614e6fdd-5d5e-49e7-98e9-4ec6fb7ec468">

```kotlin
for (i in 100..1000 step 100) {
    Text("你好 こんにちは 안녕하세요 Hello", fontWeight = FontWeight(i))
}
```

I tried different fonts and they all performed correctly in Chrome.

- `font-family: system-ui`: <img width="369" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/d1d6b1d0-2d17-447c-a2ad-65566c58ba5c">
- `font-family: monospace`: <img width="399" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/533fcf01-2ef2-4cd6-9bbf-a77c1cec2ac8">
- `font-family: serif`: <img width="377" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/7fc2ff4e-ab4d-44fb-9e22-bb20ff901d3b">
- `font-family: sans-serif`: <img width="372" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/7efd37c5-b19c-4fe8-a26a-01a7390afeef">

**Comment by m-sasha** [comment]
There's a `fontSynthesis` option in `TextStyle` which, if I understand correctly, supposed to do "fake" font styles when the underlying font doesn't have the correct style. But it doesn't seem to do anything if I use it here.

**Comment by ShirasawaSama** [comment]
> There's a `fontSynthesis` option in `TextStyle` which, if I understand correctly, supposed to do "fake" font styles when the underlying font doesn't have the correct style. But it doesn't seem to do anything if I use it here.

It may be caused by this issue, I don't know if it's a bug.

**Comment by m-sasha** [comment]
Do you have any fonts you are sure have different weights for CJK glyphs? Can you try them?

**Comment by ShirasawaSama** [comment]
@m-sasha 

Taking Chinese as an example, the default font on MacOS is `苹方-简 (PingFan-SC)`.

`androidx.compose.ui.text.platform.PlatformFont.skiko.kt`:

<img width="768" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/07ae8426-ed03-4fb6-847c-ee4a5faeb0ff">

The we can use this css in chrome:

```css
span {
    font-weight: 500;
    font-family: ".AppleSystemUIFont";
}
```

<br><br>

We can get:

<img width="243" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/07ca11d6-ecd7-4b90-a0f4-ddd16ceac88e">

Chrome Dev Tools computed props:

<img width="363" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/88a3e641-d96b-49e3-980f-753de05b798a">

<br><br>
Then this font contains multiple font weights, both in the system's font preview and in Photoshop:

<img width="491" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/2515a360-4463-47ec-ac5b-10168ea48b0e">

<br>

<img width="341" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/eb7e91df-7d71-4287-a4ed-a0bb09d3b4f0">

**Comment by ShirasawaSama** [comment]
```kotlin
Canvas(Modifier.size(500.dp)) {
    for (i in 100..1000 step 100) {
        val sktf = SkTypeface.makeFromName("PingFang SC", FontStyle(i, 80, FontSlant.UPRIGHT))
        drawIntoCanvas {
            it.nativeCanvas.drawTextLine(
                TextLine.make("$i 你好 こんにちは 안녕하세요", Font(sktf, density * 16F)),
                0f, i.toFloat() / 2, Paint()
            )
        }
    }
}
```

<img width="245" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/b4df3120-8b17-461c-9c14-1fe18cd4b808">

**Comment by kirill-grouchnikov** [comment]
https://stackoverflow.com/questions/73865835/fontweight-not-work-with-chinese-in-flutter looks relevant in terms of what the specific font supports

**Comment by ShirasawaSama** [comment]
@kirill-grouchnikov Compose seems to lack a method to enforce the setting of global font fallback.

But I noticed a strange problem. It seems that some caches are not cleared correctly:

```kotlin
Canvas(Modifier.size(500.dp)) {
    for (i in 100..1000 step 100) {
        val sktf = Typeface.makeFromName("PingFang SC", FontStyle(
            i, // <----- here
            80, FontSlant.UPRIGHT
        ))
        drawText(
            textMeasurer.measure(
                AnnotatedString("$i 你好 こんにちは 안녕하세요", SpanStyle(fontFamily = FontFamily(Typeface(sktf)), fontWeight = FontWeight(i))),
                skipCache = true, maxLines = 1,
                style = TextStyle(fontFamily = FontFamily(Typeface(sktf)), fontWeight = FontWeight(i))
            ), topLeft = Offset(0f, i.toFloat() / 2)
        )
    }
}
```

<img width="114" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/c185cd8e-47ee-47e8-95cd-26258a8e68cb">


And:

```kotlin
Canvas(Modifier.size(500.dp)) {
    for (i in 100..1000 step 100) {
        val sktf = Typeface.makeFromName("PingFang SC", FontStyle(
            800, // <----- here
            80, FontSlant.UPRIGHT
        ))
        drawText(
            textMeasurer.measure(
                AnnotatedString("$i 你好 こんにちは 안녕하세요", SpanStyle(fontFamily = FontFamily(Typeface(sktf)), fontWeight = FontWeight(i))),
                skipCache = true, maxLines = 1,
                style = TextStyle(fontFamily = FontFamily(Typeface(sktf)), fontWeight = FontWeight(i))
            ), topLeft = Offset(0f, i.toFloat() / 2)
        )
    }
}
```

<img width="116" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/17093811/32302429-db1d-4c83-84cf-e7c86f2ead27">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4015">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
