### ISSUE TITLE
DirectX12 Adapter

### ISSUE THREAD

**Issue by SudoDios** [JetBrains/compose-multiplatform#4020]
**Describe the bug**
Hi.
I made a software for Windows.
But when I run it, it is very very slow and almost freezes.
and gives this error: `org.jetbrains.skiko.RenderException: Failed to choose DirectX12 adapter.‍`
This project is important to me.
What is this error for and how can I fix it?

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Windows 10 22H
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): 18

**Comment by SudoDios** [comment]
I changed `renderApi` to ‍`SOFTWARE`.
Better than before, but still very slow.

**Comment by m-sasha** [comment]
What graphics card do you have? Perhaps it doesn't support DirectX 12.

**Comment by SudoDios** [comment]
Thanks for the quick response.
The graphics card of the computer I am testing is Intel HD 4000. 
And inside Dxdiag write directx12

**Comment by SudoDios** [comment]
I took a look on the internet.
It was written that it supports directx 11.
Does it mean that Dircetx is wrongly installed on my computer?

**Comment by m-sasha** [comment]
Compose on Windows requires DirectX 12 for acceleration. If that's not available, it will fall back to OpenGL, or a software renderer, which are slower.

**Comment by SudoDios** [comment]
Does that mean there is no good alternative for it?
Should the software be slow in systems that do not support directx 12?

**Comment by m-sasha** [comment]
The non-accelerated renderers work, but they are slow, yes.

**Comment by SudoDios** [comment]
Thank you for your guidance.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4020">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
