### ISSUE TITLE
TextLayoutResult#getLineForOffset is too slow

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#4021]
**Describe the problem**
`TextLayoutResult#getLineForOffset` is too slow. I looked at source code, linear search is performed in the class `SkiaParagraph`. It can be optimized by using binary search.

**Affected platforms**
- Desktop
I only tried on Desktop.

If the problem is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version: 1.8.0
- Compose Multiplatform version: 1.5.11
- OS version(s) (required for Desktop and iOS issues): macOS 14.0 Beta
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**Sample code**
```kotlin
@Composable
fun App() {
    val text = remember { "Super long text\n".repeat(10000) }
    val scrollState = rememberScrollState()

    Box {
        BasicTextField(
            value = text,
            onValueChange = {},
            onTextLayout = { textLayoutResult ->
                val lineOffsets = listOf(0) + "\n".toRegex().findAll(text).map { it.range.endInclusive + 1 }
                val lineTops = lineOffsets.map { textLayoutResult.getLineTop(textLayoutResult.getLineForOffset(it)) }
                println("Done. ${lineTops.size}")
            },
            modifier = Modifier.fillMaxSize().verticalScroll(scrollState),
        )
        VerticalScrollbar(
            modifier = Modifier.align(Alignment.CenterEnd),
            adapter = rememberScrollbarAdapter(scrollState),
        )
    }
}
```

**Reproduction steps**
1. Run the app
2. Hangs until some minutes later

**Video**
N/A

**Profiling data**
N/A

**Additional information**
I was implementing line number display and text folding for a TextField. As #3866 is not available yet, I try an alternative using `TextLayoutResult#getLineForOffset`. Unfortunately, it only works for small number of lines. I wonder if there is a feasible workaround at this moment.

**Comment by m-sasha** [comment]
Thanks, I'll fix it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4021">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
