### ISSUE TITLE
safeDrawingPadding doesn't work on iOS app

### ISSUE THREAD

**Issue by alfietapping** [JetBrains/compose-multiplatform#4022]
**Describe the bug**
Using the [WindowInsets api](https://blog.jetbrains.com/kotlin/2023/08/compose-multiplatform-1-5-0-release/#compose-multiplatform-supports-dialogs,-popups,-and-windowinsets) to push my bottom bar from out under the system bottom bar doesn't work when running the iOS app. As you can see from the images attached it's fine when running Android, but not on iOS

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*:  1.9.20
- Compose Multiplatform version*:  1.5.10
- OS version(s)* (required for Desktop and iOS issues):  Sonoma 14.0
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**Screenshots**

<img width="1186" alt="Screenshot 2023-12-10 at 08 29 00" src="https://github.com/JetBrains/compose-multiplatform/assets/52085556/0c77a8f7-20eb-42bc-b51d-61e536dd9416">
<img width="1212" alt="Screenshot 2023-12-10 at 08 29 39" src="https://github.com/JetBrains/compose-multiplatform/assets/52085556/ebb1a150-8e82-4a73-988a-45c0ce682aa1">

**Comment by FunkyMuse** [comment]
Have the same issue, also if you do Modifier.systemBarsPadding on iOS with an element in the top, it pushes it way down than it should

**Comment by alfietapping** [comment]
@FunkyMuse  something i've got something working for the bottom bar for now

```
@Composable
private fun SystemNavigationPadding() {
    Spacer(
        Modifier.windowInsetsBottomHeight(
            WindowInsets.navigationBars,
        ),
    )
}
```

Which then can be dropped into a Column

```
@Composable
fun BottomNavBar(
    currentScreenKey: String,
    onItemClicked: (BottomNavItem) -> Unit,
) {
    Column(
        modifier = Modifier
            .background(color = Primary),
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp, vertical = 8.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically,
        ) {
            BottomNavItem.items().forEach { item ->

                val isSelected = item.screenKey == currentScreenKey

                BottomNavItemComponent(
                    item = item,
                    isSelected = isSelected,
                    onClick = onItemClicked,
                )
            }
        }

        SystemNavigationPadding()
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4022">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
