### ISSUE TITLE
VisualTransformation freezes the UI when there are lots of span styles

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#4023]
**Describe the problem**
`VisualTransformation` freezes UI and takes 6 seconds to render a text with 40000 span styles (all the styles are identical). It is much worse in the actual use cases, e.g. syntax highlighting, which uses different and more styles.

**Affected platforms**
- Desktop
Only tried in Desktop. Couldn't find a similar report in the Jetpack Compose tracker.

If the problem is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version: 1.8.20
- Compose Multiplatform version: 1.5.11
- OS version(s) (required for Desktop and iOS issues): macOS 14.0 Beta
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**Sample code**
```
class WonderfulTransformation : VisualTransformation {
    val style = SpanStyle(color = Color.Blue)

    override fun filter(text: AnnotatedString): TransformedText {
        val spans = "long".toRegex().findAll(text.text).map {
            AnnotatedString.Range(style, it.range.start, it.range.endInclusive + 1)
        }.toList()
        return TransformedText(AnnotatedString(text.text, text.spanStyles + spans), OffsetMapping.Identity)
    }
}

@Composable
fun App() {
    val text = remember { "Super long long text\n".repeat(20000) }
    val scrollState = rememberScrollState()
    var isShowText by remember { mutableStateOf(false) }

    Box {
        if (!isShowText) {
            TextButton(onClick = { isShowText = true }) {
                Text(text = "Show")
            }
        } else {
            BasicTextField(
                value = text,
                onValueChange = {},
                visualTransformation = WonderfulTransformation(),
                modifier = Modifier.fillMaxSize().verticalScroll(scrollState),
            )
            VerticalScrollbar(
                modifier = Modifier.align(Alignment.CenterEnd),
                adapter = rememberScrollbarAdapter(scrollState),
            )
        }
    }
}
```

**Reproduction steps**
1. Run the app
2. Click the button
3. UI freezes for some seconds

**Video**
N/A

**Profiling data**
N/A

**Additional information**
N/A

**Comment by m-sasha** [comment]
Thanks for the report.

I don't think `TextField` was meant to be used with such a large amount of text, much less styled text. It's not even about `TextField`, though - showing a `Text` with that much text will also freeze the UI for a long time. You need a widget that will layout and render the text in a lazy fashion; `TextField` and `Text` aren't lazy.

Perhaps look for a "rich text" widget library.

**Comment by sunny-chung** [comment]
Thanks for your reply. In fact, the `TextField` does not freeze if the line `visualTransformation = WonderfulTransformation()` is commented out, even if I multiply the number of lines by 10 times more. For `Text`, there is a workaround using `LazyColumn` though not satisfactory.

From your response, I can assume Compose Desktop is not ready for anything intensive, say a lightweight code editor (which is currently an official Compose example) dealing with 10000 lines of code or JSON, which is what I facing daily. I understand this is a limitation imposed by the original Android Compose's `TextField`, may be this is not something JB could change. Compose Desktop is just a desktop version of a mobile framework without optimizing for desktop, even though desktop computers have much more computing power than Android and usually process a larger volume of inputs. If somebody want to do that in Compose, they would need to reinvent the wheel that is not using `Text` or `TextField`. I could not find a Compose "rich text" widget library that is not using them. If this alternative exists, I doubt what `TextField` exists for?

In contrast, an Electron app could just do this with a `<textarea>`. Developers do not need to care if a foundation component is optimized or not. Now, I understand Compose Desktop's foundation blocks are not supposed to deal with large amount of data. Could this limitation be documented so that next developers would not be trapped?

**Comment by m-sasha** [comment]
> From your response, I can assume Compose Desktop is not ready for anything intensive

This is not a limitation of Compose for Desktop itself. Some widgets that are common to desktop apps have not yet been implemented as a 1st-part library; that is true. Some things we expect to implemented eventually; others we are hoping the community will provide.

> I could not find a Compose "rich text" widget library that is not using them

I haven't tried it, but here's one: https://github.com/MohamedRejeb/Compose-Rich-Editor
Maybe you can help with its development.

**Comment by sunny-chung** [comment]
Alright. I guess it has to be implemented by Canvas drawing or annotated `Text`. Perhaps I could help if I understand more on Compose's details.

Per my preliminary review, that library is based on `BasicTextField`.

**Comment by skillAndroid** [comment]
Currently I also having problems with desktope it is when opening or initialising new screen for some second freezed and like 1 - 2  and i have simple code with a lot of layouts in 1 screen but this kind of code is not promlem with Android even though the Desktope has a lot of pawer. I think desktope is not optimized yet. I tried in Windows maybe in mac there is not such kind of errors. But however the desktope is not optimized yet!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4023">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
