### ISSUE TITLE
How to load json from assets or resource in compose multiplatform??

### ISSUE THREAD

**Issue by hmshohrab** [JetBrains/compose-multiplatform#4024]

**Comment by MohamedRejeb** [comment]
You can use load the byte array of any file in your resources folder and then convert that bytearray to a string after that you can use kotlinx serialization to parse that json string. Maybe there's a better way to do it but this should work fine.

`resource("proposal.json").readBytes().decodeToString()`

**Comment by m-sasha** [comment]
Hi. We're working on a multiplatform resources solution. It should be available soon-ish, and you can already try it in our dev releases.

@terrakok Is there a ticket to follow for this?

**Comment by terrakok** [comment]
@shohrab-swl does it work for you? have you setup project properly? could you show your build config file?

**Comment by terrakok** [comment]
@hmshohrab the same question for you :)

**Comment by hmshohrab** [comment]
Works on every platform. Except for iOS.

**Comment by terrakok** [comment]
<img width="1920" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/3532155/0eb1e68a-e78c-4498-9a10-e2712feaf939">
[JsonResSample.zip](https://github.com/JetBrains/compose-multiplatform/files/13647419/JsonResSample.zip)

**Comment by terrakok** [comment]
Could you compare your project with my sample?

[JsonResSample.zip](https://github.com/JetBrains/compose-multiplatform/files/13647428/JsonResSample.zip)

**Comment by hmshohrab** [comment]
@OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
                        implementation(compose.components.resource)
That's probably the problem. Now it is working.

**Comment by pranjul1996** [comment]
@hmshohrab I think the correct impl is **_implementation(compose.components.resources)_**
if I am not wrong.

**Comment by rishabhsingh2002** [comment]
But tried with all of this, didn't work.
Any other solution?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4024">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by mibrahimd** [comment]
> You can use load the byte array of any file in your resources folder and then convert that bytearray to a string after that you can use kotlinx serialization to parse that json string. Maybe there's a better way to do it but this should work fine.
> 
> `resource("proposal.json").readBytes().decodeToString()`

My IDE can not resolve `resource` import, although I have the dependency in **commonMain.dependencies** 

<img width="590" alt="Screenshot 2024-07-23 at 1 04 14 PM" src="https://github.com/user-attachments/assets/efd1c371-4512-4cfe-a776-15bedc19584d">

<img width="782" alt="Screenshot 2024-07-23 at 1 05 07 PM" src="https://github.com/user-attachments/assets/4f837934-168c-4344-b792-080c771e932b">
