### ISSUE TITLE
[iOS] "Frameworks, Libraries and Embedded Content" section in Xcode is missing

### ISSUE THREAD

**Issue by herveweb** [JetBrains/compose-multiplatform#4026]
**Describe the bug**
The `Frameworks, Libraries and Embedded Content` section in Xcode is missing 

Therefore I cannot add any Frameworks to the iOS project

**Affected platforms**
Select one of the platforms below:
- iOS

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Start a brand new Multiplatform project from [here](https://kmp.jetbrains.com/?_gl=1*12ij3ny*_ga*MjQ3NTIzNDAzLjE2ODY3NzU2Mjg.*_ga_9J976DJZ68*MTcwMjI1NTM3OC40NS4xLjE3MDIyNTkwNTMuMzYuMC4w&_ga=2.10865396.1980343743.1702190107-247523403.1686775628&_gac=1.113235446.1699212566.Cj0KCQjw-pyqBhDmARIsAKd9XINIxPtiwVktzuF6OPWmlwGm7NiJd_1XQfTsH4rO-K7A6PZ-hXrMr2caAvzaEALw_wcB)
2. Open iosApp.xcodeproj in Xcode
3. Go to Targets > iosApp > General tab 
4. Notice that the `Frameworks, Libraries and Embedded Content` section is missing. It only shows `Embedded Content`

**Expected behavior**
`Frameworks, Libraries and Embedded Content` section is present, so that you can add Frameworks to the iOS project.

**Screenshots**

Expected:
<img width="307" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/11280628/98ec15cf-5c04-42c0-8f3e-68091e925b26">

Actual:
<img width="261" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/11280628/7f078a8f-88d7-43dc-8b35-6bf9aac36232">

**Comment by m-sasha** [comment]
@elijah-semyonov Can you take a look here?

**Comment by herveweb** [comment]
@elijah-semyonov @m-sasha Any solution to this?

**Comment by elijah-semyonov** [comment]
@dima-avdeev-jb did you have a look at it? :)

**Comment by dima-avdeev-jb** [comment]
Not yet. I plan to check it later on my Duty period

**Comment by pablichjenkov** [comment]
I think this is crucial to be able to integrate with swift package manager.

**Comment by ggajews** [comment]
Looks like the `Link Binary With Library` step is missing. As a workaround you can add it manually from the `Build phases` tab, and restart Xcode (few times 😅 )
<img width="826" alt="Screenshot 2024-01-17 at 09 58 27" src="https://github.com/JetBrains/compose-multiplatform/assets/1298590/aeeab261-793b-42c1-8f1b-3729041d9e93">

**Comment by pablichjenkov** [comment]
Thanks @ggajews this was the missing detail. Local integration working good now!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4026">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
