### ISSUE TITLE
ModalBottomSheet does not stick to the bottom of the screen 

### ISSUE THREAD

**Issue by ruslantsyganok** [JetBrains/compose-multiplatform#4032]
**Describe the bug**
When scrolling fast, modal bottom sheet does not stick to the bottom of the screen 

**Affected platforms**

- IOS
- Android

**Versions**

- Kotlin version: 1.9.10
- Compose Multiplatform version: 1.5.3
- iOS version: 17.0.3
- OS architecture: arm64

**To Reproduce**
1. Open bottom sheet
2. Scroll fast

**Expected behavior**
Bottomsheet sticks to the bottom

https://github.com/JetBrains/compose-multiplatform/assets/85478014/5a4b90f9-50f6-44af-adde-8f0880c7a08b

**Comment by terrakok** [comment]
there is an issue in AOSP: https://partnerissuetracker.corp.google.com/issues/201628457

**Comment by ruslantsyganok** [comment]
I don’t have access to the ticket. Is there any other way do to that?

Moreover, is there any workaround in order to fix the problem? Some dirty hack?)

**Comment by m-sasha** [comment]
Use this link: https://issuetracker.google.com/issues/201628457

**Comment by ruslantsyganok** [comment]
Thank you. However the issue address a problem for material2. I am using the third version. Sample code: 

`package com.flow.one.presentation.compose

import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.displayCutoutPadding
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.SheetState
import androidx.compose.material3.SheetValue
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TestModalBottomSheet() {
    ModalBottomSheet(
        sheetState = SheetState(
            initialValue = SheetValue.Expanded,
            skipPartiallyExpanded = true
        ),
        modifier = Modifier.displayCutoutPadding(),
        windowInsets = WindowInsets(0.dp),
        containerColor = Color.White,
        onDismissRequest = {},
        shape = RoundedCornerShape(
            bottomEnd = 0.dp, bottomStart = 0.dp, topEnd = 12.dp, topStart = 12.dp
        ),
        content = {
            LazyColumn(
                modifier = Modifier
                    .fillMaxWidth(),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                item {
                    Text(
                        "Title",
                        fontWeight = FontWeight(500),
                        fontSize = 16.sp
                    )
                    Spacer(modifier = Modifier.padding(vertical = 8.dp))
                    Text("Test")
                    Spacer(modifier = Modifier.padding(vertical = 20.dp))
                }
            }
        },
    )
}`

**Comment by ruslantsyganok** [comment]
```
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.displayCutoutPadding
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.SheetState
import androidx.compose.material3.SheetValue
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TestModalBottomSheet() {
    ModalBottomSheet(
        sheetState = SheetState(
            initialValue = SheetValue.Expanded,
            skipPartiallyExpanded = true
        ),
        modifier = Modifier.displayCutoutPadding(),
        windowInsets = WindowInsets(0.dp),
        containerColor = Color.White,
        onDismissRequest = {},
        shape = RoundedCornerShape(
            bottomEnd = 0.dp, bottomStart = 0.dp, topEnd = 12.dp, topStart = 12.dp
        ),
        content = {
            LazyColumn(
                modifier = Modifier
                    .fillMaxWidth(),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                item {
                    Text(
                        "Title",
                        fontWeight = FontWeight(500),
                        fontSize = 16.sp
                    )
                    Spacer(modifier = Modifier.padding(vertical = 8.dp))
                    Text("Test")
                    Spacer(modifier = Modifier.padding(vertical = 20.dp))
                }
            }
        },
    )
}
```

**Comment by ruslantsyganok** [comment]
For the sake of curiosity tried with material2. The same issue.


```
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.selection.toggleable
import androidx.compose.material.Button
import androidx.compose.material.Checkbox
import androidx.compose.material.ExperimentalMaterialApi
import androidx.compose.material.Icon
import androidx.compose.material.ListItem
import androidx.compose.material.ModalBottomSheetLayout
import androidx.compose.material.ModalBottomSheetValue
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Favorite
import androidx.compose.material.rememberModalBottomSheetState
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.launch
@Composable
@OptIn(ExperimentalMaterialApi::class)
fun FlowModalBottomSheet() {
    var skipHalfExpanded by remember { mutableStateOf(false) }
    val state = rememberModalBottomSheetState(
        initialValue = ModalBottomSheetValue.Hidden,
        skipHalfExpanded = skipHalfExpanded
    )
    val scope = rememberCoroutineScope()
    ModalBottomSheetLayout(
        sheetState = state,
        sheetContent = {
            LazyColumn {
                items(50) {
                    ListItem(
                        text = { Text("Item $it") },
                        icon = {
                            Icon(
                                Icons.Default.Favorite,
                                contentDescription = "Localized description"
                            )
                        }
                    )
                }
            }
        }
    ) {
        Column(
            modifier = Modifier.fillMaxSize().padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Row(
                Modifier.toggleable(
                    value = skipHalfExpanded,
                    role = Role.Checkbox,
                    onValueChange = { checked -> skipHalfExpanded = checked }
                )
            ) {
                Checkbox(checked = skipHalfExpanded, onCheckedChange = null)
                Spacer(Modifier.width(16.dp))
                Text("Skip Half Expanded State")
            }
            Spacer(Modifier.height(20.dp))
            Button(onClick = { scope.launch { state.show() } }) {
                Text("Click to show sheet")
            }
        }
    }
}
```

https://github.com/JetBrains/compose-multiplatform/assets/85478014/ed7b0849-2a50-4cfb-b253-e8022f2d2913

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4032">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
