### ISSUE TITLE
only DEFLATED entries can have EXT descriptor on packageDmg

### ISSUE THREAD

**Issue by cesargasca** [JetBrains/compose-multiplatform#4033]
When running packageDmg, to create dmg package in a Macbook pro I always get: 

> Execution failed for task ':createDistributable'.
> java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor

this only happens when attempting to sign the app just after input the password. (Also reproducible with createDistributable)

**Affected platforms**

- Desktop (Macbook pro M2)

**To Reproduce**
1. Set under nativeDistributions in build.gradle.kts
```
macOS {
                dmgPackageVersion = "1.2.1"

                dmgPackageBuildVersion = "1.2.1"

                bundleID = "com.myapp.app"
                signing {
                    sign.set(true)
                    identity.set("Cesar Gasca")
                }
            }
```
2. Execute 'packageDmg'

**Expected behavior**
Create dmg package under build/compose

**Comment by dima-avdeev-jb** [comment]
To reproduce we need to generate Desktop app in wizard https://terrakok.github.io/Compose-Multiplatform-Wizard/

Correct?

**Comment by cesargasca** [comment]
The Deskotp app was generated from IntelliJ, I created a project to reproduce the issue https://github.com/cesargasca/compose-reproduced-error
After some debugging I noticed it is due to a jar called apksigner.jar and only happens when signing is set for macOS.

Please let me know if something else is needed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4033">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
