### ISSUE TITLE
Gradle import

### ISSUE THREAD

**Issue by softcleandev** [JetBrains/compose-multiplatform#4034]
Currently you can only use Compose Multiplatform framework in one way:

- you import the template project from a Github repository and customize it.

It would be much more convenient if you could import the framework into an existing project using Gradle.

**Comment by softcleandev** [comment]
We have an gradle project with different submodules: 

- core (our kmm library)
- build-logic (our gradle plugins)
- 3x submodules (kmm app)

It is a monorepo for all our kmm projects.

**Comment by terrakok** [comment]
Still don't understand problem. What would you like to achieve?
Why you cannot add anoter one gradle module with a shared compose UI?

**Comment by softcleandev** [comment]
My thought was to implement the shared UI in the core and not another module.
But I will follow your advice and try using another module for the UI.
Thank you

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4034">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
