### ISSUE TITLE
For Compose Desktop, do not expose Compose Material dependency externally

### ISSUE THREAD

**Issue by Omico** [JetBrains/compose-multiplatform#4035]
See https://github.com/JetBrains/compose-multiplatform-core/blob/976f6feab9f7539a02c264c8adc1a6b35eadecd1/compose/desktop/desktop/build.gradle#L50

We should not expose Compose Material dependency externally. This will cause IDEA to import the wrong package by default, if we use Compose Material3.

Maybe it is time to remove `DesktopTheme.jvm.kt` completely.

**Comment by terrakok** [comment]
Duplicate: https://github.com/JetBrains/compose-multiplatform/issues/497

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4035">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
