### ISSUE TITLE
Kotlin/WASMJS is unable to continuously update the display content

### ISSUE THREAD

**Issue by pengxiaohua575527452** [JetBrains/compose-multiplatform#4038]
**Describe the bug**
When I use rememberSaveable to continuously update the text parameter in the Text method, the UI is unable to accurately display the text content after multiple changes.

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10-dev-wasm03
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17.08

**To Reproduce**
The following code demonstrates the problem:
```kotlin
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.unit.IntSize
import androidx.compose.ui.window.CanvasBasedWindow
import kotlinx.browser.window
import kotlinx.coroutines.CompletableDeferred

@OptIn(ExperimentalComposeUiApi::class)
fun main() {

    window.document.body?.let { body ->
        body.setAttribute(
            "style", """
            flex-direction: column;
        """.trimIndent()
        )
        window.document.createElement("canvas").also { canvas ->
            body.appendChild(canvas)
            canvas.setAttribute("style", """display: block;""")
            canvas.run {
                id = "canvas-top"
                var size = CompletableDeferred<IntSize>(IntSize(200, 200))
                var has = false
                CanvasBasedWindow("title", "canvas-top", requestResize = {
                    size.await().apply {
                        size = CompletableDeferred<IntSize>()
                    }
                }) {
                    var showDetail by rememberSaveable { mutableStateOf(false) }
                    if (!has) {
                        has = true
                        window.setInterval({
                            showDetail = !showDetail
                            "".toJsString()
                        }, 30)
                    }
                    Text("canvas-top ${if (showDetail) "showDetail" else "no showDetail"}")
                }
            }
        }
    }
}
```

**Screenshots**
- start 
![image](https://github.com/JetBrains/compose-multiplatform/assets/40903072/db7d4fd4-f8ee-4010-a98f-c7fa6c09a7e0)

- After a period of time
![image](https://github.com/JetBrains/compose-multiplatform/assets/40903072/f6c739a9-779c-4207-bdc6-392c9635f4df)
![image](https://github.com/JetBrains/compose-multiplatform/assets/40903072/ce63f4dd-0a0e-42fe-a306-243d2ca39f50)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4038">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
