### ISSUE TITLE
Respect system theme on an iOS app splash screen

### ISSUE THREAD

**Issue by terrakok** [JetBrains/compose-multiplatform#4040]
User report:
> When running iOS app in dark mode, I see a white flash every time I enter a view that is using Compose MP. It appears to me that the UIView(Controller) and/or Skiko view is clearing with white even in dark mode. Would be nice if it at least used .systemBackground...

**Comment by elijah-semyonov** [comment]
I believe [it should have been fixed](https://github.com/JetBrains/compose-multiplatform/issues/3492)

**Comment by terrakok** [comment]
The issue should be fixed. If it's not, provide a reproducer here, please, and reopen the issue

**Comment by tylerwilson** [comment]
After more testing, I have determined this is likely a byproduct of our apps feature that allows you to set the light/dark theme from within the app. That is, if the app light/dark theme differs from the currently set OS theme, this is when we see the flash.

We are adjusting the app theme via this magic line of code:

`UIApplication.shared.windows.first(where: \.isKeyWindow)?.overrideUserInterfaceStyle = .dark`

So I suspect that the Compose or Skiko layer of code is checking or watching the trait value, which may not have changed, though the app is rendering in a different mode.

I am unsure if this is a case you need to want to handle, though it would be convenient for me. :-/ We may simply disable this feature until such time as it can be handled better.

Thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4040">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
