### ISSUE TITLE
Kotlin/wasm removeEventListener function did not remove the event listener

### ISSUE THREAD

**Issue by pengxiaohua575527452** [JetBrains/compose-multiplatform#4041]
**Describe the bug**
I don't know if I should mention this issue here instead;
kotlin/wasm removeEventListener do not  work

**Affected platforms**
- Web (K/Wasm) 

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10-dev-wasm03
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17.08

**To Reproduce**
The following code demonstrates the problem:
```kotlin
import kotlinx.browser.window
import org.w3c.dom.events.Event

fun main(){
    val callback = {e: Event -> println("callback") }
    window.document.body?.appendChild(window.document.createElement("div").apply {
        addEventListener("click", callback)
        removeEventListener("click", callback)
        innerHTML = "click"
    })
}
```

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/40903072/3888866c-5ca3-4099-9815-f27c4e8a484d)

**Comment by terrakok** [comment]
I'm afraid here is no a compose specific code. Could you file an issue here, please https://kotl.in/issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4041">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
