### ISSUE TITLE
Release MSI can't obtain static method dispose from class com.sun.jna.Native

### ISSUE THREAD

**Issue by lizhongyue248** [JetBrains/compose-multiplatform#4043]
**Describe the bug**
I build application with [JNA](https://github.com/java-native-access/jna), and all is well during the development phase. But when I build it as an MSI file, the following error is thrown after installation

![image](https://github.com/JetBrains/compose-multiplatform/assets/29678316/0a5f111e-4dff-4518-b2d5-13f5ec1634bc)

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.4
- OS version(s)* (required for Desktop and iOS issues):   Windows 10.0.22631  22631
- OS architecture (x86 or arm64):  x86 
- JDK (for desktop issues): Graalvm-ce-17.0.8

**To Reproduce**
Development application with `jna` and `jan-platform`.

Open exe file after install succes.

Build command: `packageReleaseDistributionForCurrentOS` or `packageReleaseMsi`

Demo Repository https://github.com/lizhongyue248/PortView

**Expected behavior**
Open exe file success after install succes.

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/29678316/0a5f111e-4dff-4518-b2d5-13f5ec1634bc)

**Comment by m-sasha** [comment]
That class was probably optimized out by ProGuard. You need to configure it to not do that. See https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Native_distributions_and_local_execution#minification--obfuscation

**Comment by lizhongyue248** [comment]
> That class was probably optimized out by ProGuard. You need to configure it to not do that. See https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Native_distributions_and_local_execution#minification--obfuscation

Thanks, I solved this problem by adding `compose-desktop.pro` file and using `keep`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4043">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
