### ISSUE TITLE
Kotlin 2.0.0-Beta2 Support

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#4044]
I know its coming. I just want to get a ping as soon as it is ready :)

**Comment by Elelan** [comment]
Waiting for it so that i can start using kotlin 2.0.0Beta2 in my kmp project

**Comment by eymar** [comment]
JFYI: compose compiler plugin `1.5.6-dev1-kt2.0.0-Beta2` was published, but it's known to not work for ios with.

Kotlin 2.0.0-Beta2 enabled K2 by default.
Disabling it by downgrading the language version helps and ios app works too:

```kotlin
kotlin {
   compilerOptions {
        languageVersion.set(KotlinVersion.KOTLIN_1_9)
        apiVersion.set(KotlinVersion.KOTLIN_1_9)
    }
}
```

We are working on a proper solution.

**Comment by eymar** [comment]
I close this issue, since the issue was on Kotlin side - https://youtrack.jetbrains.com/issue/KT-64444
It's fixed, and to be release in Beta3.
