### ISSUE TITLE
Display cutout WindowInset do not work in landscape mode on iOS

### ISSUE THREAD

**Issue by Mats-Hjalmar** [JetBrains/compose-multiplatform#4045]
**Describe the bug**
`WindowInset.displayCutout` behaves like the camera is on both sides in the or none depending on what side you want calculated. (in Both layout directions)

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): 17.2
- OS architecture (x86 or arm64): arm64

**To Reproduce**
```kotlin
@Composable
internal fun App() = AppTheme {
    val rightCameraPadding =
        WindowInsets.displayCutout
            .asPaddingValues()
            .calculateRightPadding(LayoutDirection.Ltr)
    Box(
        Modifier.fillMaxSize()
            .padding(end = rightCameraPadding)
            .background(Color.Red)
    )
}
```

**Expected behavior**
The padding value should be 0 if there is no camera on the right side.

**Screenshots**
<img width="804" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/111428992/12ee5f62-ef0c-48fa-a11e-f7eea5d920fa">

**Additional context**
This do not work either (left display cutout values with app in landscape)
<img width="804" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/111428992/712cadb4-3180-4f54-a1c1-1343537c34b2">

**Comment by terrakok** [comment]
Do you have this code on the ios app side?
```
struct ContentView: View {
    var body: some View {
        ComposeView().ignoresSafeArea(.all)
    }
}
```

**Comment by terrakok** [comment]
Because I don't see the initial problem but found another one:
If to rotate app through an up side down state then insets won't be updated

```kotlin
@Composable
internal fun App() = AppTheme {
    Box(
        Modifier
            .fillMaxSize()
            .windowInsetsPadding(WindowInsets.displayCutout)
            .background(Color.Red)
    ) {
        Text("TEXT")
    }
}
```

<img width="293" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/3532155/face0091-25d4-4537-ae24-81250322d44b"> 
<img width="468" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/3532155/0d03e219-89ef-4048-bd07-65d73450a1ea">
<img width="293" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/3532155/31fa7cb1-90ea-4c50-9409-79a7b16700cd">
<img width="468" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/3532155/290cde85-d61f-4f48-82e8-a627a7000210">

**Comment by Mats-Hjalmar** [comment]
> Do you have this code on the ios app side?
> 
> ```
> struct ContentView: View {
>     var body: some View {
>         ComposeView().ignoresSafeArea(.all)
>     }
> }
> ```

That is exactly my code.

**Comment by Mats-Hjalmar** [comment]
> Because I don't see the initial problem but found another one: If to rotate app through an up side down state then insets won't be updated
> 
> ```kotlin
> @Composable
> internal fun App() = AppTheme {
>     Box(
>         Modifier
>             .fillMaxSize()
>             .windowInsetsPadding(WindowInsets.displayCutout)
>             .background(Color.Red)
>     ) {
>         Text("TEXT")
>     }
> }
> ```
> 
> <img alt="image" width="293" src="https://private-user-images.githubusercontent.com/3532155/291310905-face0091-25d4-4537-ae24-81250322d44b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzM1NTIsIm5iZiI6MTcwMzIzMzI1MiwicGF0aCI6Ii8zNTMyMTU1LzI5MTMxMDkwNS1mYWNlMDA5MS0yNWQ0LTQ1MzctYWUyNC04MTI1MDMyMmQ0NGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgyMDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJlMzg4NWU0ZGNmZTBmMjQyMGE1OGVhZmIyZmJmNzliNTAxYmZlYzA1MjcwZGMyNzRhYzVmZmMwNGYwMmU0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.h6Cu8bIr-cNDzclWc-HAjmasRIGBMdMYGOslBLd8evc"> <img alt="image" width="468" src="https://private-user-images.githubusercontent.com/3532155/291310951-0d03e219-89ef-4048-bd07-65d73450a1ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzM1NTIsIm5iZiI6MTcwMzIzMzI1MiwicGF0aCI6Ii8zNTMyMTU1LzI5MTMxMDk1MS0wZDAzZTIxOS04OWVmLTQwNDgtYmQwNy02NWQ3MzQ1MGExZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgyMDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTRhNDgwNDE5ZDRhYWVlMDFmMjE4Mjg5MGJlNWI1YjNhMGRiMTA1ZmExYjMyMzM3ZThiMWI3ZWJjYTBmMGIyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4afMASUW_CuEpm5eGP5jsroBlBED3P1MRBU2MMe6J4U"> <img alt="image" width="293" src="https://private-user-images.githubusercontent.com/3532155/291310985-31fa7cb1-90ea-4c50-9409-79a7b16700cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzM1NTIsIm5iZiI6MTcwMzIzMzI1MiwicGF0aCI6Ii8zNTMyMTU1LzI5MTMxMDk4NS0zMWZhN2NiMS05MGVhLTRjNTAtOTQwOS03OWE3YjE2NzAwY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgyMDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWZkOTcwYWQ3YTUxOTJkZWRmYWI2OTdjMDU4ODhkYTNmYmQ4ZGEwNzVhMzc4Mjc3ZGY4MjJlZDMwZWI2YjIzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iijhyI1Zyb3w0D23ptarckNtWQaYnPJArDjE_5nNRrs"> <img alt="image" width="468" src="https://private-user-images.githubusercontent.com/3532155/291311036-290cde85-d61f-4f48-82e8-a627a7000210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzM1NTIsIm5iZiI6MTcwMzIzMzI1MiwicGF0aCI6Ii8zNTMyMTU1LzI5MTMxMTAzNi0yOTBjZGU4NS1kNjFmLTRmNDgtODJlOC1hNjI3YTcwMDAyMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDgyMDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MThlZTk4NmIyY2ViOWMxMWQ3YmU0YmYxMzJkZGMzNDAyMzI3ZmQ2ZDcxMzdhZjM2M2NhYjY4NTViN2EyMzY2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.If-sVCWFzmfRoEP3SwJMvnVydRmjSEslGIJZP0-nNsc">

Quite amazing edge case. Any idea how to fix it?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4045">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
