### ISSUE TITLE
Does Tray support display control?

### ISSUE THREAD

**Issue by Xiaolangs** [JetBrains/compose-multiplatform#4047]
![20231219-112419](https://github.com/JetBrains/compose-multiplatform/assets/26102232/f06b75ca-5ef4-4acc-82a9-40c28589d84d)

As shown in the picture

**Comment by igordmn** [comment]
It is macOs? We have a feature request for enhancment menubar support here: https://github.com/JetBrains/compose-multiplatform/issues/850

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4047">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
