### ISSUE TITLE
Merge in Compose 1.6.0 changes

### ISSUE THREAD

**Issue by chrisbanes** [JetBrains/compose-multiplatform#4052]
**Describe the bug**
Currently Compose Multiplatform targets Jetpack Compose 1.5.x, but with Jetpack Compose 1.6.0 on the horizon it would be great if we could try out the 1.6.0 beta APIs in the new CMP 1.6.0-alphas.

**Affected platforms**
Select one of the platforms below:
- All

**Comment by MatkovIvan** [comment]
Available in 1.6.0-beta01

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4052">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
