### ISSUE TITLE
(Web) Support for drag & drop file

### ISSUE THREAD

**Issue by usert-4** [JetBrains/compose-multiplatform#4053]
Hello,

could the drag & drop file support be added in the next release ?

Thanks

**Comment by igordmn** [comment]
Closing, as we have a common issue here: https://github.com/JetBrains/compose-multiplatform/issues/322.

> be added in the next release ?

I can't provide ETA for this, but we don't plan to work on it in the near months

**Comment by usert-4** [comment]
i was talking more about dragging file to a composable, i saw since there is a onExternalDrag modifier to try, thanks

**Comment by igordmn** [comment]
Understood. In this case, reopening the issue.

Could you remove "aditionnaly to the shortcut ctrl+c/v on text field and context menu," to avoid misinterpretation from others?

**Comment by usert-4** [comment]
Yes done, thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4053">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
