### ISSUE TITLE
kotlin/wasm Unable to display Chinese strings correctly

### ISSUE THREAD

**Issue by pengxiaohua575527452** [JetBrains/compose-multiplatform#4054]
**Describe the bug**
The `Text()` function cannot display the Chinese part of the same string correctly, but the `println()` function can display it correctly in devTools, so it should not be a problem during compilation.

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.10-dev-wasm03
- OS version(s)* (required for Desktop and iOS issues):
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17.08

**To Reproduce**
The following code demonstrates the problem:
```kotlin
@OptIn(ExperimentalComposeUiApi::class)
fun main(){
    window.document.body?.run {
        val parentElementId = "canvas-root-container"
        val canvasId = "canvas-root-id"
        appendChild(window.document.createElement("div").apply {
            setAttribute("id", parentElementId)
            appendChild(window.document.createElement("canvas").apply {
                setAttribute("id", canvasId)
            })
        })
        val str = "English content 无法显示的中文内容"
        CanvasBasedWindow(title = "title", canvasElementId = canvasId){
            Column {
                Text(str)
                println(str)
            }
        }
    }
}
```

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/40903072/ff72a737-a0b3-46f6-b6ca-f01237a72634)

**Comment by ShirasawaSama** [comment]
dupe https://github.com/JetBrains/compose-multiplatform/issues/3967

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4054">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
