### ISSUE TITLE
[Desktop] TextLayoutResult#getLineForVerticalPosition returns wrong value + slow performance

### ISSUE THREAD

**Issue by sunny-chung** [JetBrains/compose-multiplatform#4058]
**Describe the bug**

**Issue 1**

According to the definition of this method:
> If you ask for a vertical position before 0, you get 0; if you ask for a vertical position beyond the last line, you get the last line.

But 0 is returned if the position queried is beyond the last line.

**Issue 2**

Also, the performance of the underlying method `SkiaParagraph#getLineMetricsForVerticalPosition` is slow. It can be optimized by using binary search.

**Affected platforms**
Select one of the platforms below:
- Desktop

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): macOS 14.0 Beta
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce**
```
@Composable
fun App() {
    val text = remember { "Some text\n".repeat(100) }
    var textLayoutResult by remember { mutableStateOf<TextLayoutResult?>(null) }
    val scrollState = rememberScrollState()

    textLayoutResult?.let { r ->
        println("Result: ${r.getLineForVerticalPosition(1000000f)}")
    }

    Box {
        BasicTextField(
            value = text,
            onValueChange = {},
            onTextLayout = { textLayoutResult = it },
            modifier = Modifier.fillMaxSize().verticalScroll(scrollState),
        )
        VerticalScrollbar(
            modifier = Modifier.align(Alignment.CenterEnd),
            adapter = rememberScrollbarAdapter(scrollState),
        )
    }
}
```

Steps and/or the code snippet to reproduce the behavior:
1. Run the demo
2. Observe the value printed to the console. It is `0`.

**Expected behavior**
Expected value is `100`.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by dhakehurst** [comment]
Also hitting this bug :(

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4058">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
