### ISSUE TITLE
Kotlin 1.9.22 support

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-multiplatform#4059]
As a workaround you can easily suppress the version checker:
```kotlin
compose {
    kotlinCompilerPluginArgs.add("suppressKotlinVersionCompatibilityCheck=1.9.22")
}
```

**Comment by dima-avdeev-jb** [comment]
Thanks! Sure we will support it.

**Comment by eymar** [comment]
Compose Multiplatform Compiler plugin `1.5.7` has been published. 

It can be used by setting:


```
compose {
    kotlinCompilerPlugin.set("1.5.7")
}
```
___

Out of a box, the support of 1.9.22 will be enabled in the next dev build. Fixed by: https://github.com/JetBrains/compose-multiplatform/pull/4075

**Comment by jamesonwilliams** [comment]
Hey there, sorry if I've misunderstood: is 1.5.7 the correct version for Kotlin 1.9.22 right now?

> This version (1.5.7) of the Compose Compiler requires Kotlin version 1.9.21 but you appear to be using Kotlin version 1.9.22 which is not known to be compatible.

**Comment by eymar** [comment]
@jamesonwilliams I guess you changed it like this:
```
android { 
 .....
  composeOptions {
          kotlinCompilerExtensionVersion "1.5.7"
      }
....
```
Right?


the thing is that the above DSL is only applicable to android.

While this DSL is for compose multiplatform projects:

```
compose {
    kotlinCompilerPlugin.set("1.5.7")
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4059">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
