### ISSUE TITLE
Whether to support dock menu

### ISSUE THREAD

**Issue by Xiaolangs** [JetBrains/compose-multiplatform#4060]
![screenshot-20231222-115445](https://github.com/JetBrains/compose-multiplatform/assets/26102232/5a455948-2bda-49cd-b360-2b16773050ea)
as the picture shows

**Comment by dima-avdeev-jb** [comment]
I think this question is not related with Compose.
You can take a look here: https://stackoverflow.com/questions/1319805/java-os-x-dock-menu

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4060">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
