### ISSUE TITLE
Can I use "fun App() { MaterialTheme {xxx}}" in html.core? 

### ISSUE THREAD

**Issue by alamhubb** [JetBrains/compose-multiplatform#4065]
Hello, I just started learning compose-multiplatform. 

I want to use compose-multiplatform to develop html pages. 

I found MaterialTheme, which looks better on Android.

I want to use it on the html platform, but I got an error,

ERROR: Compose targets. '[jscanvas]' are experimental and may have bugs!

```
My original code sourceSets {
         val jsMain by getting {
             kotlin.srcDir("src/main/kotlin")
             resources.srcDir("src/main/resources")

             dependencies {
                 implementation(compose.html.core)
                 implementation(compose.runtime)
             }
         }
     }
```

added code
```

     sourceSets {
         val jsMain by getting {
             kotlin.srcDir("src/main/kotlin")
             resources.srcDir("src/main/resources")

             dependencies {
                 implementation(compose.html.core)
                 implementation(compose.runtime)
                 implementation(compose.material)
             }
         }
     }

```
Just got this error
ERROR: Compose targets '[jscanvas]' are experimental and may have bugs!

Is it because MaterialTheme is rendered using canvas, so it does not support html?

I saw related questions,

https://github.com/JetBrains/compose-multiplatform/issues/1010

https://github.com/JetBrains/compose-multiplatform/issues/2186

I don't know if this is what I understand, I want to confirm, thank you

**Comment by dima-avdeev-jb** [comment]
MatheriaTheme works in Compose WASM target for browser.
You can check examples here: https://github.com/Kotlin/kotlin-wasm-examples/tree/main

MaterialTheme not working for Compose HTML library

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4065">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
