### ISSUE TITLE
menubar Can I hide it macOS

### ISSUE THREAD

**Issue by Xiaolangs** [JetBrains/compose-multiplatform#4068]
![1703498919996](https://github.com/JetBrains/compose-multiplatform/assets/26102232/c6f18180-c3d9-4b9b-a734-1f22b3f4a7d1)
menubar Can I hide it

**Comment by lizhongyue248** [comment]
I have found a solution and hope it can help you.

This is my old code
```
fun main = aoplication {
    DialogWindow() {
        // ...
    }
}
```

And add a Property `apple.awt.UIElement`

```
fun main() {
    System.setProperty("apple.awt.UIElement", "true");
    aoplication {
        DialogWindow() {
            // ...
        }
    }
}
```

This will treat the application as a UI element and no longer display menubar.

But I only tested `DialogWindow` without testing `Window`. You can try it based on your application, hoping it can help you

**Comment by dima-avdeev-jb** [comment]
This issue have a very interesting behavior what maybe usefull in current issue: https://github.com/JetBrains/compose-multiplatform/issues/4114

**Comment by lizhongyue248** [comment]
Another solution is to add the configuration to InfoPlist during the construction of macos
```
      macOS {
        iconFile.set(project.file("icon/mac.icns"))
        infoPlist {
          extraKeysRawXml = """
                        <key>LSUIElement</key>
                        <string>true</string>
                        <key>LSBackgroundOnly</key>
                        <string>true</string>
                    """.trimIndent()
        }
      }
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4068">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
