### ISSUE TITLE
SnackBar isn't queuing messages as it should per documentation

### ISSUE THREAD

**Issue by Zenturas** [JetBrains/compose-multiplatform#4070]
**Describe the bug**
On desktop, the SnackBar isn't queuing messages as it should per documentation. It only shows the first message, and the subsequent messages don't appear. Meanwhile, on Android, the SnackBar works correctly, displaying messages one after the other as intended

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.6.0-dev1347
- OS version(s)* (required for Desktop and iOS issues): win11
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 20

**To Reproduce**
- run the code and wait for the messages (only the first appear)

```
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.window.singleWindowApplication
import kotlinx.coroutines.launch

fun main() = singleWindowApplication {
	val scope = rememberCoroutineScope()
	val state = remember { SnackbarHostState() }

	Scaffold(snackbarHost = { SnackbarHost(state) }) {
		scope.launch {
			(0..3).forEach {
				state.showSnackbar(it.toString())
			}
		}
	}
}

```

**Comment by m-sasha** [comment]
Looks like this is a bug with `kotlinx-coroutines:1.8.0-RC`. The issue goes away by upgrading to `1.8.0-RC2`.

@eymar Should I update to RC2? Should we at all be using non-release versions of `kotlinx-coroutines`?

**Comment by eymar** [comment]
> Looks like this is a bug with `kotlinx-coroutines:1.8.0-RC`. The issue goes away by upgrading to `1.8.0-RC2`.
> 
> @eymar Should I update to RC2? Should we at all be using non-release versions of `kotlinx-coroutines`?

It think it's okay.We can use non-stable dependencies for non stable builds (dev build in this case).

Yes, please an update to RC2 is welcome:)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4070">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
