### ISSUE TITLE
Android studio doesn't recognize my real iOS device

### ISSUE THREAD

**Issue by Caij** [JetBrains/compose-multiplatform#4074]
iPhone 8   iOS 16

**work: Android Studio Giraffe Kotlin Multiplatform Mobile plugin 0.8.1(223)-26**

not work: Android Studio Iguana | 2023.2.1 Canary 18  ( Android Studio Hedgehong)  Kotlin Multiplatform Mobile plugin 0.8.1(232)-18

![image](https://github.com/JetBrains/compose-multiplatform/assets/8597839/267668d7-577b-4fb1-8df9-89182795bc7d)
![image](https://github.com/JetBrains/compose-multiplatform/assets/8597839/048675eb-6516-483a-8f28-fb42cd760980)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8597839/ed0796e7-868b-4301-93fb-a56c2ed99274)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8597839/eb73b1c4-27dc-4fc3-8ba2-71e43dcf3412)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8597839/ac954f7e-8bdd-4084-b627-08717db2084f)

**Comment by Caij** [comment]
update xcode  fixed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4074">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
