### ISSUE TITLE
Web Baseline Always 0

### ISSUE THREAD

**Issue by jonas-app** [JetBrains/compose-multiplatform#4078]
**Describe the bug**
On the web target (wasm) I do not get correct baseline information and therefore can't use the `alignByBaseline` modifier.
The baseline is always 0.

**Affected platforms**
Select one of the platforms below:
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*:  1.9.21
- Compose Multiplatform version*: 
compose = "1.5.4"
compose-compiler = "1.5.6"
compose-plugin = "1.6.0-alpha01"

**To Reproduce**
[Sample: WebBaselineAlways0.zip](https://github.com/JetBrains/compose-multiplatform/files/13786627/WebBaselineAlways0.zip)
```kotlin
Row {
            Text(
                    "Heading",
                    modifier = Modifier.alignByBaseline()
                        // Desktop: The heading alignment line is 66
                        // Web: The heading alignment line is 0
                        .onGloballyPositioned { println("The heading alignment line is ${it[FirstBaseline]}") },
                    style = MaterialTheme.typography.h4
            )
            Text(
                    " — Subtitle",
                    modifier = Modifier.alignByBaseline()
                        // Desktop: The subtitle alignment line is 31
                        // Web: The subtitle alignment line is 0
                        .onGloballyPositioned { println("The subtitle alignment line is ${it[FirstBaseline]}") },
                    style = MaterialTheme.typography.subtitle1
            )
        }
```

**Expected behavior**
On the web target I also get back the correct baseline and can use the alignByBaseline modifier.

**Screenshots**
![screenshot showing issue; web above; desktop below](https://github.com/JetBrains/compose-multiplatform/assets/17269256/8299d059-5723-466d-a130-a41069f93c1a)
(web above; desktop below)

**Additional context**
[Slack Discussion](https://kotlinlang.slack.com/archives/C01F2HV7868/p1703526910351489)

**Comment by jonas-app** [comment]
Just updated to the newest compose version and this issue is gone.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4078">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
