### ISSUE TITLE
[Component.Resources] `:android:assembleDebug` and `:desktop:run` raises error in a multi-module environment

### ISSUE THREAD

**Issue by subroh0508** [JetBrains/compose-multiplatform#4083]
**Describe the bug**
In a multi-module environment, Android and Desktop apps will fail to run if multiple strings.xml are placed for each module.

Stacktrace(Android)
```
> Task :android:mergeDebugJavaResource FAILED

Execution failed for task ':android:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'composeRes/values/strings.xml'.
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/8.2/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information

...
```

Stacktrace(Desktop)
```
> Task :desktop:run
Exception in thread "main" java.lang.IllegalStateException: String ID=`module2_text` is not found!
	at org.jetbrains.compose.resources.StringResourcesKt.loadString(StringResources.kt:102)
	at org.jetbrains.compose.resources.StringResourcesKt.access$loadString(StringResources.kt:1)
	at org.jetbrains.compose.resources.StringResourcesKt$stringResource$str$3.invokeSuspend(StringResources.kt:77)
	at org.jetbrains.compose.resources.StringResourcesKt$stringResource$str$3.invoke(StringResources.kt)
	at org.jetbrains.compose.resources.StringResourcesKt$stringResource$str$3.invoke(StringResources.kt)
	at 
...
```

**Affected platforms**
Select one of the platforms below:
- Android
- Desktop

**Versions**
- Kotlin version: 1.9.21 
- Compose Multiplatform version: 1.6.0-dev1350

**To Reproduce**
Clone [this repository](https://github.com/subroh0508/compose-mpp-components-resources-sample) and run the command `:android:assembleDebug` or `:desktop:run`.

**Expected behavior**
Android and Desktop apps must run correctly.

**Comment by terrakok** [comment]
Yes. At the moment the compose resources doesn't support multimodule projects. It will be fixed in the future.

**Comment by terrakok** [comment]
https://github.com/JetBrains/compose-multiplatform/pull/4454

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4083">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
