### ISSUE TITLE
Not able to run Project: Receiver class org.gradle.accessors.dm.LibrariesForLibs_Decorated does not define or inherit an implementation of the resolved method

### ISSUE THREAD

**Issue by sunildhiman90** [JetBrains/compose-multiplatform#4084]
**Describe the bug**
Getting this error:

`Receiver class org.gradle.accessors.dm.LibrariesForLibs_Decorated does not define or inherit an implementation of the resolved method 'abstract org.gradle.api.plugins.ExtensionContainer getExtensions()' of interface org.gradle.api.plugins.ExtensionAware.`

Tried all ways for workaround, Tried to use the Kotlin 1.9.22  & 2.0.0-Beta1  both versions, But it didnt worked with any of them.
Tried compose plugin 1.5.11 & 1.6.0-dev1334 versions, But nothing is working.

Checkout out these issues and tried all things mentioned there:  https://github.com/JetBrains/compose-multiplatform/issues/4037
https://github.com/gradle/gradle/issues/27099

Nothing is working still same error

**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version*: 1.9.21/1.9.22/2.0.0-Beta1
- Compose Multiplatform version*: 1.5.11/1.6.0-dev1334
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by eymar** [comment]
Could you please provide a minimal reproducer and describe the steps required to reproduce?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4084">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Germansdev** [comment]
I got the same/similar: PROBLEM: When adding the decompose extensions and sync gradle, an error occurs:

Method org/gradle/accessors/dm/LibrariesForLibs_Decorated.getExtensions()Lorg/gradle/api/plugins/ExtensionContainer; is abstract
Exception is:
java.lang.AbstractMethodError: Method org/gradle/accessors/dm/LibrariesForLibs_Decorated.getExtensions()Lorg/gradle/api/plugins/ExtensionContainer; is abstract
_____________________
build.gradle.kts(composeApp)
plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.jetbrainsCompose)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.compose.compiler)

}

repositories {
    google()
    mavenCentral()
}
kotlin {
    androidTarget()
    
    jvm("desktop")
    
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }
    
    sourceSets {
        val desktopMain by getting

        all {
            languageSettings.optIn("kotlinx.cinterop.ExperimentalForeignApi")
        }

        commonMain.dependencies {
....
 		//decompose:
            implementation(libs.decompose)
            implementation(libs.extensions.compose)
            implementation(libs.essenty.lifecycle)
...}

 androidMain.dependencies {
	implementation(libs.decompose)
...}

 iosMain.dependencies {...}

desktopMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutines.swing)

        }
    }
}

android {
    namespace = "cmp.project.free_market"
    compileSdk = AndroidSdk.COMPILE
    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    sourceSets["main"].res.srcDirs("src/androidMain/res")
  

    defaultConfig {
        applicationId = "cmp.project.free_market"
        minSdk = AndroidSdk.MIN
        targetSdk = AndroidSdk.TARGET
        versionCode = 1
        versionName = "1.0"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = true 
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"), 
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {

        sourceCompatibility = JavaVersion.VERSION_17 
        targetCompatibility = JavaVersion.VERSION_17 
    }
    buildFeatures {
        compose = true
    }
    dependencies {
        debugImplementation(compose.uiTooling)
    }
}
dependencies {
    implementation(libs.androidx.ui.graphics.android)
    implementation(libs.androidx.media3.exoplayer)
    implementation(libs.androidx.navigation.runtime.ktx)
    implementation(libs.firebase.firestore.ktx)
    implementation(libs.firebase.storage.ktx)
    implementation(libs.androidx.ui.desktop)
    implementation(libs.androidx.ui.unit.desktop)
    implementation(libs.androidx.core)
}
compose.resources {
    publicResClass = true
    packageOfResClass = "me.sample.library.resources"
    generateResClass = always
}

compose.desktop {
    application {
        mainClass = "cmp.project.free_market.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "cmp.project.free_market"
            packageVersion = "1.0.0"
        }
    }
}

object AndroidSdk {
    const val MIN = 24
    const val COMPILE = 34
    const val TARGET = COMPILE
}
_________________________

build.gradle.kts (Project)
plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidLibrary) apply false
    alias(libs.plugins.jetbrainsCompose) apply false
    alias(libs.plugins.compose.compiler) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.googleServices) apply false //generar y agregar el json primero y luego descomentar
   // alias(libs.plugins.kotlinxSerialization)
}


repositories {
    google()
    mavenCentral() 
    maven {
        url = uri("https://s01.oss.sonatype.org/content/repositories/releases/")
    }
}
___________________
libs.versions.toml:
[versions]
activityCompose = "1.9.1"
agp = "8.5.2"
compose-plugin = "1.6.11"
kotlin = "2.0.10"
gservices = "4.4.2"

decompose = "3.1.0"
#extensionsCompose = "3.1.0"
essenty = "2.1.0"
....
[libraries]
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
#extensions-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "extensionsCompose" }
essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
...
[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "gservices"}

---------------------------
# Decompose extensions for Jetpack/Jetbrains Compose
-keep class com.arkivanov.decompose.extensions.compose.jetbrains.mainthread.SwingMainThreadChecker
--------------------------

gradle-wrapper.prperties:
#Wed Sep 18 09:03:09 ART 2024
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
--------------------------

gradle.properties:

kotlin.code.style=official

#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#Kotlin Multiplatform
kotlin.mpp.enableCInteropCommonization=true

#To hide warning message log cannot be built on this machine..ios..
kotlin.native.ignoreDisabledTargets=true

org.gradle.unsafe.accessors=false
org.gradle.java.home=C\:/Users/Willkommen/.jdks/corretto-17.0.7
------------------------

**Comment by Germansdev** [comment]
My issue was solved with  [](https://github.com/arkivanov/Decompose/issues/74#issuecomment-2358694685)
