### ISSUE TITLE
components-resources-wasmJs isn't being published

### ISSUE THREAD

**Issue by luca992** [JetBrains/compose-multiplatform#4086]
**Describe the bug**
`components-resources-wasmJs` isn't being published

**Affected platforms**
Select one of the platforms below:
- Web (K/Wasm) - Canvas based API

**Versions**
- Compose Multiplatform version*: versions > 1.6.0-alpha01

**Additional context**
https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/components/components-resources-wasmJs/

**Comment by eymar** [comment]
Thanks! fixed on CI. The next dev build will include wasmJs.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4086">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
