### ISSUE TITLE
Adding Default Modifier to Box 

### ISSUE THREAD

**Issue by PalankiBharat** [JetBrains/compose-multiplatform#4091]
A default Modifier can be added to the Box I feel

**Comment by eymar** [comment]
Could you please elaborate on your idea? What's the purpose of a new modifier?  
If you believe your idea is applicable to all Compose targets (including android) then you're welcome to contribute directly to Jetpack Compose https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/README.md

**Comment by PalankiBharat** [comment]
I thought as for most composables we have a default modifier it's not a big thing but like every other composable has that like Colunm(modifier: Modifier = Modifier) so I thought Box can also have one although its a small change I really don't know is there a reason for it not being there to something else if it can be there can I contribute towards it although its a single line change

**Comment by eymar** [comment]
There is an override with default Modifier value:

https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/foundation/foundation-layout/src/commonMain/kotlin/androidx/compose/foundation/layout/Box.kt#L64

```
@Composable
inline fun Box(
    modifier: Modifier = Modifier,
    contentAlignment: Alignment = Alignment.TopStart,
    propagateMinConstraints: Boolean = false,
    content: @Composable BoxScope.() -> Unit
) {
    ....
}
```
So you can call it like this:
```
Box {}
```

You can't call 
```
Box()
//or
Column()
```

only:

```
Box { }
Column { }
```

So Box is not different than other blocks.

**Comment by PalankiBharat** [comment]
Yes I saw that and deleted my reply but any reason for what not to have 
`Box()
 Column()`

**Comment by eymar** [comment]
Box() would likely be equivalent to Box {}
It won't render anything.

 Currently I don't see a reason why I would need to call Box or Column without any content or not-default Modifier. It seems to be useless from UI perspective. 

So there should be a reason to have it like you suggest. Having it just because kotlin syntax allows to do so doesn't make a lot sense in my opinion

**Comment by PalankiBharat** [comment]
@eymar Understood, Great thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4091">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
