### ISSUE TITLE
Allow for the MSI installer to launch the application after installation

### ISSUE THREAD

**Issue by eskatos** [JetBrains/compose-multiplatform#4092]
I would like to run some code when the application is installed on Windows.

The MSI could do it but it seems there is currently no good way to customize the MSI installer

* https://github.com/JetBrains/compose-multiplatform/issues/1972

Another option would be to be able to build a MSI that launches the installed application on a successful install. The application itself could then take care of initializing the environment.

I imagine something like
```kotlin
nativeDistributions {
  windows {
    launchAppOnInstall = true
  }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4092">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
