### ISSUE TITLE
M3 Text fields supportingText is incorrectly layouted inside dialog

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#4093]
**Describe the bug**
M3 Text fields supportingText is incorrectly layouted inside dialog. Does not happen on Android

**Affected platforms**
Select one of the platforms below:
- Desktop
- Probably other skiko platforms too

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Win 10
- JDK (for desktop issues): zulu-17

**To Reproduce**
```kotlin
@Composable
fun App() {
    Dialog(
        onDismissRequest = {},
        content = {
            Column(Modifier.background(Color.White).padding(12.dp)) {
                OutlinedTextField(
                    value = "",
                    onValueChange = {},
                    supportingText = {
                        Text("a    b    c    d    e     f    g    h    i     j   k    l   m      n    o   p   q")
                    }
                )
                TextField(
                    value = "",
                    onValueChange = {},
                    supportingText = {
                        Text("a    b    c    d    e     f    g    h    i     j   k    l   m      n    o   p   q")
                    }
                )
            }
        }
    )
}
```

![image](https://github.com/JetBrains/compose-multiplatform/assets/63979218/7e2a2f57-7e13-4f88-bb74-c1b070712f18)

**Comment by alexzhirkevich** [comment]
For me it is some sort of measuring/placing bug. If supporting text width can be greater than field width then at least the whole composable size should reflect it (background modifier should be applied to the whole container including supporting text). Inside normal alert dialog this part of text is just cut. Seems like i have to write some ugly code to limit text width manually. Anyway it's upstream issue then. I was confused because i've never faced this on Android.

**Comment by alexzhirkevich** [comment]
Yep, i got it. To my mind decoration box should pick width as `maxOf(textFieldWidth, supportingTextWidth)`during placing

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4093">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
