### ISSUE TITLE
UIKitView has white space at the top in latest dev build

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#4095]
My UIKitView looks fine with 1.5.x and [1.6.0-alpha01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-alpha01), but in `1.6.0-dev1357` gets a weird white border at the top. Tested this with web views, video views (AVKit), video views (VLCKit) – all the same result:

![IMG_0080](https://github.com/JetBrains/compose-multiplatform/assets/2178959/2080c5d8-d196-442f-8d6d-25d4a3c3df90)

**Comment by eymar** [comment]
Hi Sebastian!
I'm trying to reproduce the issue. I tried with a mapview and webview. But they don't have a white border.

Is there something I need to consider?
Maybe a specific iOS version? Did you run on iPhone or iPad maybe? (the view seem to be in a lanscape mode)

Do you have this project on github?

**Comment by SebastianAigner** [comment]
Hi @eymar! You can check out https://github.com/SebastianAigner/reelchest/tree/dev-version-update/mobileapp to observe the issue. 


Start the app and click "Go directly to TikTok". The white bar at the top is not visible in the alpha release, only in dev.

<img width="783" alt="Screenshot 2024-01-08 at 23 48 22" src="https://github.com/JetBrains/compose-multiplatform/assets/2178959/c1b1c812-8c81-4a1a-9516-9854df869c1e">

**Comment by eymar** [comment]
git besect shows that it started to show extra white space after this change https://github.com/JetBrains/compose-multiplatform-core/commit/b42dfe4a325feff969d8df2a105799ce6c082905

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4095">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
