### ISSUE TITLE
LookaheadScope Breaks remeasure on window change

### ISSUE THREAD

**Issue by Selemba1000** [JetBrains/compose-multiplatform#4097]
**Describe the bug**
All content contained inside a LookahedScope seems to not react to parent element size changes. If for example i change the window size with a single Box inside of a LookahedScope that has Modifier.fillMaxSize(), the size of the Box will not change. Without the LookahedScope the Box will however change size accordingly.

**Affected platforms**
Select one of the platforms below:
- All (maybe?)
- Desktop (tested occurring)

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.3 & 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Ubuntu latest
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): OpenJDK 11

**To Reproduce**
1. Put the code in a empty Window.
Code:
``` Kotlin
LookaheadScope{
  Box(Modifier.fillMaxSize().background(Colors.Red))
}
```
2. Try and resize the window

**Expected behavior**
Box should change size with the window

**Screenshots**
Will add if needed.

**Additional context**

**Comment by Selemba1000** [comment]
Rechecked with Box as in the Example and it works as expected. The problem seems to only occur with a Surface contained in LookaheadScope. This code instead of the above has the described issue:
```Kotlin
LookaheadScope{
    Surface(modifier = Modifier.fillMaxSize(), color = Color.Red){
    }
}
```
The simple workaround for anyone wondering seems to be:
```Kotlin
LookaheadScope{
    Box(Modifier.fillMaxSize()){
        Surface(modifier = Modifier.fillMaxSize(), color = Color.Red){
        }
    }
}
```
The Surface will then change size accordingly.
Still wierd behaviour.

**Comment by m-sasha** [comment]
In my testing Box and Surface worked the same (no resizing).

However, this looks like a [bug in Jetpack Compose, which has already been fixed](https://issuetracker.google.com/issues/308001630) but we haven't pulled the fix in yet. It does behave slightly differently on Android - it does resize sporadically, whereas it doesn't resize at all on the Desktop, so there's a small chance there's an extra bug on the desktop. But I would wait until we merge Google's fix before investigating further.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4097">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
