### ISSUE TITLE
Compose Multiplatform Shared/Common Module Dependencies Error in IDEA and Android Studio

### ISSUE THREAD

**Issue by SnowCharmQ** [JetBrains/compose-multiplatform#4098]
**Describe the bug**
When I try to use the Java basic library in the shared/common module as shown below, an error occurs: Unresolved reference java.
![image](https://github.com/JetBrains/compose-multiplatform/assets/82224175/5198de0a-c07a-4e4f-b235-296cb9c4d41f)
But I can still compile and run the project in IDEA and Android Studio. And my another project with almost the same dependencies does not have this issue.

**Affected platforms**
Select one of the platforms below:
- shared/common module

**Versions**
- Kotlin version*:  1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Windows10
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): jdk 18

**Expected behavior**
Can you help me configure this issue, I think that the problem is that I do not configure the project correctly.

**Comment by alexzhirkevich** [comment]
That is how Kotlin multiplatform works. It will compile successfully until you try to make a build for a non-jvm platform. You should write a platfrom-specific code in dedicated jvm/android source set.
I guess it works well on your other projects because you have only desktop and android (both JVM) platforms enabled there. In this case linter knows that both of your platforms are JVM and allows you to make java imports in common source set.

**Comment by SnowCharmQ** [comment]
> That is how Kotlin multiplatform works. It will compile successfully until you try to make a build for a non-jvm platform. You should write a platfrom-specific code in dedicated jvm/android source set. I guess it works well on your other projects because you have only desktop and android (both JVM) platforms enabled there. In this case linter knows that both of your platforms are JVM and allows you to make java imports in common source set.

Oh, I get it! Thank you for your kind explanation!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4098">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
