### ISSUE TITLE
Support drag and drop of images from Compose app to other applications

### ISSUE THREAD

**Issue by hakanai** [JetBrains/compose-multiplatform#4101]
Some of the use cases for my apps require dragging _from_ the Compose application out into other applications, i.e. the reverse of the `onExternalDrag` modifier.

- Ability to select some text and drag that out to other text editors (already tracked as #322)
- Ability to drag an image to an image editor (or Discord, etc.)
- Ability to drag an image to a file explorer (or mail client, etc.)

Normal Java DnD would do this by putting the image into a `Transferable` which supports both image flavours and file list flavours. I guess the way the `DragData` interface has been modelled also allows this, by implementing multiple of its interfaces.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4101">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
