### ISSUE TITLE
Copy text via Ctrl+C/Cmd+C

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/compose-multiplatform#4104]
A Text composable wrapped in a SelectionContainer is selectable and on desktop can be copied via right mouse click and the resulting context menu. However most people would expect to be able to do the same with the keyboard via Ctrl+C/Cmd+C which is currently not possible. It would be nice if this expected standard functionality could be implemented.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4104">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
