### ISSUE TITLE
TextField/BasicTextField not adding new line on NumPadEnter.

### ISSUE THREAD

**Issue by antontucek** [JetBrains/compose-multiplatform#4109]
**Describe the bug**
When using TextField/BasicTextField with singleLine = false, I would expect to add new line on NumPadEnter press, but it doesn't. The behavior is different from when pressing normal enter or Swing JTextArea in general.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.5.11 (also tried on 1.6.0-alpha01, the bug persists)
- OS version: Windows 11
- OS architecture: x86
- JDK (for desktop issues): 17

**To Reproduce**
1. Run
```
fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        Column {
            Row {
                var textState by remember { mutableStateOf("") }
                TextField(
                    value = textState,
                    onValueChange = { textState = it },
                    modifier = Modifier
                        .padding(start = 4.dp, end = 4.dp)
                        .fillMaxSize(),
                    singleLine = false,
                )
            }
        }
    }
}
```
2. Click into TextField.
3. Press NumPadEnter 
4. See that no new line added.

**Expected behavior**
A new line added.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4109">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
