### ISSUE TITLE
MissingResourceException: Missing resource with path for fonts in iOS platform

### ISSUE THREAD

**Issue by serbelga** [JetBrains/compose-multiplatform#4111]
**Describe the bug**
When I use `compose.components.resources` for fonts in iOS, following exception is thrown

```
org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: font/quicksand_bold.ttf
```

The .TTF file is on `commonMain/resources/font`

Typography creation

```
val quickSandFontBold: Font
    @Composable get() = resolveFont(
        "quickSandFontBold",
        "font/quicksand_bold.ttf",
        FontWeight.Bold
    )

val quickSandFontFamily: FontFamily
    @Composable get() = FontFamily(
        quickSandFontBold
    )

@OptIn(ExperimentalResourceApi::class)
@Composable
private fun resolveFont(
    id: String,
    path: String,
    weight: FontWeight = FontWeight.Normal,
    style: FontStyle = FontStyle.Normal
): Font =
    Font(
        FontResource(
            id,
            setOf(ResourceItem(setOf(), path))
        ),
        weight,
        style
    )
```

**Affected platforms**
- iOS

**Versions**
- Kotlin version: 1.9.22
- Compose Multiplatform version: 1.6.0-dev1362
- OS version(s): iOS 17.0
- OS architecture (x86 or arm64): arm64

**Screenshots**

<img width="367" alt="Captura de pantalla 2024-01-09 a las 21 18 59" src="https://github.com/JetBrains/compose-multiplatform/assets/26246782/3aef4d37-1dec-418d-a1b0-e0302283f0c2">

<img width="1450" alt="Captura de pantalla 2024-01-09 a las 21 19 14" src="https://github.com/JetBrains/compose-multiplatform/assets/26246782/24f1fd5c-8e31-479f-b385-8c12c5c29107">

**Sample**

Branch: https://github.com/serbelga/Todometer-KMP/tree/compose_multiplatform_1.6.0
PR: https://github.com/serbelga/Todometer-KMP/pull/444

**Comment by terrakok** [comment]
Check the library demo: fonts should be placed in ```
commonMain/resources/composeResources/font
```

**Comment by terrakok** [comment]
https://github.com/JetBrains/compose-multiplatform/tree/master/components/resources/demo/shared/src/commonMain/resources/composeResources/font

**Comment by serbelga** [comment]
I get the same error:

```
Uncaught Kotlin exception: org.jetbrains.compose.resources.MissingResourceException: 
Missing resource with path: composeResources/font/quicksand_bold.ttf
```

<img width="353" alt="Captura de pantalla 2024-01-11 a las 1 29 18" src="https://github.com/JetBrains/compose-multiplatform/assets/26246782/6968ac23-2c13-4e44-b2e6-cdb04133cf3d">

**Comment by terrakok** [comment]
Do you know that the compose resources doesn't support multimodule projects?
If your project is not than show me a build log `./gradlew generateComposeResClass -i`

**Comment by terrakok** [comment]
I took a look at the project. It is a multimodule, so it isn't supported

**Comment by terrakok** [comment]
It will be implemented in the future

**Comment by carlos-prezzee** [comment]
@terrakok 
Do you know if is there any workaround to use fonts in a multimodule project?

**Comment by carlos-prezzee** [comment]
> use it in the top level app module and inject to other modules.

Thanks for that 🙏 
Is there any limitation on having the fonts when using XCFrameworks? I did add the fonts a top level module but same result.
I've created the xcframework with `isStatic false` and without it and same result.

**Comment by terrakok** [comment]
Resources cannot be shared with a XCFramework. It works only with the local Xcode integration

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4111">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
