### ISSUE TITLE
Support for Multiple Compose Windows on Separate Displays

### ISSUE THREAD

**Issue by GtechGovind** [JetBrains/compose-multiplatform#4117]
I would like to propose an enhancement to the Compose project to support the simultaneous display of two Compose windows on two separate physical displays. This feature would greatly enhance the user experience for those with multi-monitor setups, providing increased flexibility and productivity.

**Comment by MatkovIvan** [comment]
Compose for Desktop is already supported multiple windows. Please follow this tutorial - https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Window_API_new

**Comment by GtechGovind** [comment]
I'm aware Jetpack Compose for Desktop supports multiple windows, but I'm struggling to achieve a specific setup. In my multi-display environment, I'd like to launch my application with two distinct windows, each placed on a separate display. Unfortunately, no built-in APIs seem to enable this directly. Could I be missing something, or is this functionality truly absent?

**Comment by MatkovIvan** [comment]
Compose relies on AWT for window management, and might be initialized in any AWT window (or component).
So you can achieve programmatically moving AWT window (and Compose window since it's the same thing) to the 2nd screen by using AWT API.

Good starting point is:
```kt
GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4117">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
