### ISSUE TITLE
Missing Resource exception on IOs

### ISSUE THREAD

**Issue by Kashif-E** [JetBrains/compose-multiplatform#4120]
After updating to the latest dev release resources stopped working on iOS. Although it works fine on Android

Select one of the platforms below:
- iOS

- Kotlin version: 1.9.20 
- Compose Multiplatform version:  1.6.0-dev1362
- OS version(s): Ios 17
- OS architecture (x86 or arm64): arm64

This is how my resources are structured:
<img width="350" alt="Screenshot 2024-01-12 at 12 25 35 PM" src="https://github.com/JetBrains/compose-multiplatform/assets/61690178/5a3a717a-a899-45a1-b983-ccc159a98ee0">

The exception that I am getting:
<img width="707" alt="Screenshot 2024-01-12 at 12 26 40 PM" src="https://github.com/JetBrains/compose-multiplatform/assets/61690178/48cf9e9c-a99b-446d-9544-a0f56b9076ee">

Loading Resource Like this:
   ` DrawableResource("ic_markaz_logo.png")`

**Comment by terrakok** [comment]
Because you mustn't use resources by paths. Use generated accessors: `Res.drawable.ic_markaz_logo`

if you use dev versions of compose than you need to take a look at the resources demo app

**Comment by Kashif-E** [comment]
@terrakok I have a multimodule project all my resources are in the shared module. is there a workaround for multimodule apps?

**Comment by Kashif-E** [comment]
this is what i ended up doinng https://kotlinlang.slack.com/archives/C0346LWVBJ4/p1705044569082869

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4120">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
