### ISSUE TITLE
iOS Status Bar Color And Padding Issue In Compose Multiplatform

### ISSUE THREAD

**Issue by Mukuljangir372** [JetBrains/compose-multiplatform#4121]
**Describe the bug**
We've settled custom color to status bar in iOS application using Swift. But after changing the color of status bar, a while line under status bar started to appear in iOS application. After investigation, We've found its a padding under status bar inside compose view.

**Affected platforms**
- iOS

**Versions**
- Kotlin version: 1.9.20
- Compose Multiplatform version:  1.5.3
- OS version : 14
- OS architecture (x86 or arm64): arm64

**To Reproduce**
1. Launch the iOS application
2. Observe the Status Bar Color and while line under status bar (see screenshot)

**Expected behavior**
A while line under status bar should not appear.

**Screenshots**
![Simulator Screenshot - iPhone 15 Pro - 2024-01-12 at 14 20 40](https://github.com/JetBrains/compose-multiplatform/assets/64830777/ab92a7a8-8d26-489e-9f46-1c87554d75b9)

**Code**
iOS (Swift):
```swift
import SwiftUI
import shared

struct ContentView: View {
	var body: some View {
            ComposeView() .ignoresSafeArea(.all, edges: .bottom) // Because compose has its won handler
	}
}

struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> some UIViewController {
        let controller = App_iosKt.AppView()
        setupStatusBar(view: controller.view)
        return controller
    }
    
    func updateUIViewController(_ uiViewController: UIViewControllerType, context: Context) {
        
    }
    
    // Change the status bar color to a primary color
    private func setupStatusBar(view: UIView) {
        let statusBarColor = UIColor(red: 0.07, green: 0.20, blue: 0.37, alpha: 1.0)
        let statusbarView = UIApplication.shared.statusBarUIView
        statusbarView?.backgroundColor = statusBarColor
    }
}

struct ContentView_Previews: PreviewProvider {
	static var previews: some View {
		ContentView()
	}
}

extension UIApplication {
var statusBarUIView: UIView? {
    if #available(iOS 13.0, *) {
        let tag = 38482
        let keyWindow = UIApplication.shared.windows.filter {$0.isKeyWindow}.first
        
        if let statusBar = keyWindow?.viewWithTag(tag) {
            return statusBar
        } else {
            guard let statusBarFrame = keyWindow?.windowScene?.statusBarManager?.statusBarFrame else { return nil }
            let statusBarView = UIView(frame: statusBarFrame)
            statusBarView.tag = tag
            keyWindow?.addSubview(statusBarView)
            return statusBarView
        }
    } else if responds(to: Selector(("statusBar"))) {
        return value(forKey: "statusBar") as? UIView
    } else {
        return nil
    }
  }
}

```
Compose Multiplatform:
```kotlin
@Composable
fun App() {
    ScogoThemeUi {
          Screen()
    }
}

@Composable
fun Screen() {
    Scaffold(
          modifier = Modifier.fillMaxSize(),
          topBar = { ... },
          content = { ... }
     }
}
```

**Comment by alexzhirkevich** [comment]
You don't really have to change status bar color using SwiftUI. Just ignore safe area completelety: 
```swift
  ComposeView().ignoresSafeArea()
```
Compose scafffold and top bar will do everything else for you.

**Comment by alexzhirkevich** [comment]
Why does template generated by https://kmp.jetbrains.com wizard still ignores only keyboard inset is another question 🤔. Where is its issue tracker?

**Comment by terrakok** [comment]
<img width="578" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/3532155/32628956-3bce-4659-889e-a325a08bf60a">

https://youtrack.jetbrains.com/newIssue?project=KT&summary=Kotlin%20Multiplatform%20Wizard%20issue&c=tag%20kmp-wizard

**Comment by Mukuljangir372** [comment]
@alexzhirkevich @terrakok Thank you for your response! @alexzhirkevich If you have gone through the code, We're already using `ignoreSafeArea()` but the issue looks same.

**Comment by alexzhirkevich** [comment]
You have to ignore it **_completely_**. Not only the bottom edge

**Comment by Mukuljangir372** [comment]
@alexzhirkevich Thank you for your response! It worked.

**Comment by JurajBegovac** [comment]
> You don't really have to change status bar color using Swift. Just ignore safe area completelety:
> 
> ```swift
>   ComposeView().ignoresSafeArea()
> ```
> 
> Compose scafffold and top bar will do everything else for you.

Hi there! Thanks for sharing your approach, but I have a couple of questions:

1. When using `ignoreSafeArea()`, adding `Modifier.statusBarsPadding()` to the `TopAppBar` seems necessary. Without this, I've noticed that the iOS status bar overlaps with the content.

2. Also, I'm trying to figure out how to change the status bar color. On Android, the status bar color defaults to a grey color (or something like that). Do you have any tips on how to change this?

Appreciate your insights on these issues!

**Comment by dima-avdeev-jb** [comment]
@JurajBegovac Please take a look at this sample: https://github.com/dima-avdeev-jb/ios-android-inset-padding-safe-area

**Comment by JurajBegovac** [comment]
> @JurajBegovac Please take a look at this sample: https://github.com/dima-avdeev-jb/ios-android-inset-padding-safe-area

Thanks for sharing the project link. After looking at it, I noticed a few things:

1. Android Focus: The code seems specific to Android, and I'm looking for shared solutions across both Android and iOS. (I know how to do it just for Android)

2. In the statement above `You don't really have to change status bar color using Swift. Just ignore safe area completelety:` -> not sure how that fits here.

So in the end it looks to me like I have to:
For iOS:
1. Ignore safe area in swift
2. Add some surface behind scaffold and set background to the background that will be drawn behind statusBar
3. Add topInsets padding to scaffold (or to topBar of scaffold)

For Android:
1. Change systemBar color (like in the link you provided)

**Comment by amirhossein320** [comment]
I did like below:

in iosApp.swift :

`
ComposeView().ignoresSafeArea()
`

in screen contain Scaffold :

`Scaffold { innerPadding ->
    Box(
        Modifier.padding(
            top =
            if (getPlatform() == OS.IOS) innerPadding.calculateTopPadding() - 8.dp
            else innerPadding.calculateTopPadding(),
            bottom = innerPadding.calculateBottomPadding(),
            start = innerPadding.calculateStartPadding(LocalLayoutDirection.current),
            end = innerPadding.calculateEndPadding(LocalLayoutDirection.current),
        )
    ) {
    }
}`

**Comment by amirhossein320** [comment]
I did like below:

in iosApp.swift :

`
ComposeView().ignoresSafeArea()
`

in screen contain Scaffold :

`Scaffold { innerPadding ->
    Box(
        Modifier.padding(
            top =
            if (getPlatform() == OS.IOS) innerPadding.calculateTopPadding() - 8.dp
            else innerPadding.calculateTopPadding(),
            bottom = innerPadding.calculateBottomPadding(),
            start = innerPadding.calculateStartPadding(LocalLayoutDirection.current),
            end = innerPadding.calculateEndPadding(LocalLayoutDirection.current),
        )
    ) {
    }
}
`

**Comment by amirhossein320** [comment]
I did like below:

in iosApp.swift :

`
ComposeView().ignoresSafeArea()
`

in screen contain Scaffold :

```
Scaffold { innerPadding ->
    Box(
        Modifier.padding(
            top =
            if (getPlatform() == OS.IOS) innerPadding.calculateTopPadding() - 8.dp
            else innerPadding.calculateTopPadding(),
            bottom = innerPadding.calculateBottomPadding(),
            start = innerPadding.calculateStartPadding(LocalLayoutDirection.current),
            end = innerPadding.calculateEndPadding(LocalLayoutDirection.current),
        )
    ) {
    }
}
```

**Comment by YoussefHachicha** [comment]
> ```swift
> .all, edges: .bottom
> ```

i dont really get it ? where do i set desired status bar color?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4121">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
