### ISSUE TITLE
Modifier.imePadding() animates on Android but not on iOS

### ISSUE THREAD

**Issue by Ribesg** [JetBrains/compose-multiplatform#4122]
**Describe the bug**
`Modifier.imePadding()` animates on Android but not on iOS. I did not find an issue to upvote so I made this one.

**Affected platforms**
- iOS

**Versions**
- Kotlin version: 1.9.21
- Compose Multiplatform version: 1.5.11
- OS version(s) (required for Desktop and iOS issues): MacOS 14.0
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): Temurin 17

**To Reproduce**
Just use `Modifier.imePadding()`, it's pretty obvious.

**Expected behavior**
Opening the keyboard on iOS should animate the padding just like on Android.

**Comment by alexzhirkevich** [comment]
It was already implemented in https://github.com/JetBrains/compose-multiplatform-core/pull/875. Try 1.6 dev builds

**Comment by Ribesg** [comment]
`[1.6.0-alpha01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-alpha01)` was released before this was merged and subsequent dev versions just won't build. It's probably to unstable to use in an actual project with other dependencies I guess. I'll have to wait on the next alpha, at least.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4122">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
