### ISSUE TITLE
Tooltips and at least some forms of hover don't work in IntelliJ on 1.6

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#4123]
**Describe the bug**
```kotlin
TooltipArea({ BasicText("Tooltip", Modifier.background(Color.Magenta).padding(8.dp)) }) {
    BasicText("Hover here", Modifier.background(Color.Gray).padding(8.dp))
}
```

This doesn't show any tooltip in IJ, but works in standalone apps. It looks like in general hover doesn't work in the IDE anymore. Tested on 23.3.2 on macOS.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.8.21
- Compose Multiplatform version*: 1.6.0-dev1362
- OS version(s)* (required for Desktop and iOS issues): macOS 14.2.1
- OS architecture (x86 or arm64): aarch64
- JDK (for desktop issues): 17.0.9+7-b1087.9 aarch64 OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by rock3r** [comment]
@MatkovIvan thanks for the super quick fix! Can you let me know when the change ships in a dev build, so I can update the dependency in Jewel?

**Comment by MatkovIvan** [comment]
It's already in 1.6.0-dev1369

**Comment by rock3r** [comment]
@MatkovIvan just tested in Jewel and it seems to fix all issues on my machine! I'm going to release a Jewel version with the fix ASAP. Hopefully this also works for @fscarponi and @lamba92

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4123">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
