### ISSUE TITLE
Update Proguard to support Java 21

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#4125]
I've set my target Java to 21 (using toolchain):

```kotlin
kotlin {
    jvmToolchain(21)
}
```

When executing `packageMsi` task, proguard throws error (and fails the task) complaining it supports bytecode only up to java 18.

[Support for java 21](https://github.com/Guardsquare/proguard/issues/331) was added in [proguard 7.4](https://github.com/Guardsquare/proguard/releases).

Can you please update proguard to 7.4 or newer?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4125">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
