### ISSUE TITLE
Configuration Cache not working with wasm distribution

### ISSUE THREAD

**Issue by PaulWoitaschek** [JetBrains/compose-multiplatform#4128]
**Describe the bug**
With the new wasm task, the distribution task is not compatible with configuration cache

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*: 1.9.x
- Compose Multiplatform version*: 1.6.dev versions (tested with the latest snapshot 1.6.0-dev1369)

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Clone https://github.com/Kotlin/kotlin-wasm-examples
1. cd compose-imageviewer
2. ./gradlew wasmJsBrowserDistribution --configuration-cache

**Expected behavior**
No configuration cache errors are thrown

See the attached config cache report
[ccache.html.zip](https://github.com/JetBrains/compose-multiplatform/files/13943067/ccache.html.zip)

**Comment by PaulWoitaschek** [comment]
Also happening with 1.6.0-beta01

**Comment by eymar** [comment]
The fix is expected to be in kotlin 2.0.0-Beta4 - https://youtrack.jetbrains.com/issue/KT-64851

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4128">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
