### ISSUE TITLE
Package uber JAR with Proguard

### ISSUE THREAD

**Issue by badmannersteam** [JetBrains/compose-multiplatform#4129]
As I see there are 2 variants now:

1. `packageReleaseUberJarForCurrentOS` produces uber jar, but it's not obfuscated even in Release version
2. `createReleaseDistributable`/`packageReleaseDistributionForCurrentOS` use proguard, but it produces the same jars as input because of this code from `AbstractProguardTask`:
```kotlin
jarsConfigurationFile.ioFile.bufferedWriter().use { writer ->
    for ((input, output) in inputToOutputJars.entries) {
        writer.writeLn("-injars '${input.normalizedPath()}'")
        writer.writeLn("-outjars '${output.normalizedPath()}'")
    }
    // ...
}
```

Can you please add a possibility to package all classes to the single uber JAR after proguard, for example by specifying a single output jar in proguard config?

**Comment by pjBooms** [comment]
Thank you for the enhancement. We have more urgent tasks for now, you may provide a PR for this to facilitate.

**Comment by badmannersteam** [comment]
> may provide a PR for this to facilitate

done :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4129">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
