### ISSUE TITLE
packageDeb fails to run.

### ISSUE THREAD

**Issue by FooterManDev** [JetBrains/compose-multiplatform#4135]
**Describe the bug**
When running `packageDeb` Gradle Task, an error will occur:
```
External tool execution failed:
* Command: [/opt/jdk-17.0.8.1+1/bin/jpackage, @/home/balakay/Projects/Launcher/Tritium/build/compose/tmp/packageDeb.args.txt]
* Working dir: []
* Exit code: 1
* Standard output log: /home/balakay/Projects/Launcher/Tritium/build/compose/logs/packageDeb/jpackage-2024-01-17-10-15-43-out.txt
* Error log: /home/balakay/Projects/Launcher/Tritium/build/compose/logs/packageDeb/jpackage-2024-01-17-10-15-43-err.txt
  ```

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: `1.9.20`
- Compose Multiplatform version*: `1.5.11`, `1.5.10`
- OS version(s)* (required for Desktop and iOS issues): Linux Mint 21.2 (Kernel 5.15.0-76-generic)
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): `17.0.8.1+1`

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a Compose Project.
2. Run Task `packageDeb`.

**Expected behavior**
Deb Package to be created.

**Screenshots**

**Additional context**
[jpackage-2024-01-17-10-15-43-err.txt](https://github.com/JetBrains/compose-multiplatform/files/13965098/jpackage-2024-01-17-10-15-43-err.txt)

**Comment by pjBooms** [comment]
Do you have fakeroot package installed?

**Comment by Xinkle** [comment]
i got similar error. fakeroot already installed

```
IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.13-7-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 4008M
Cores: 8
Registry:
  ide.balloon.shadow.size=0
  ide.experimental.ui=true
  editor.minimap.enabled=true
Non-Bundled Plugins:
  socrates.tabshifter (0.34)
  com.nasller.CodeGlancePro (1.7.8)
  com.vecheslav.darculaSolidTheme (1.0.3)
  wu.seal.tool.jsontokotlin (3.7.4)
  com.intellij.ko (233.199)
  com.vermouthx.idea (1.15.2)
  IdeaVIM (2.7.5)
  io.cacher.intellij (1.1.1)
  com.c5inco.modifiers (1.0.14)
  com.intellij.ideolog (222.2.0.0)
  com.markskelton.one-dark-theme (5.9.0)
  com.godwin.json.parser (1.7.1)
  com.levinzonr.arch.jetpackcompose.plugin (1.1.1)
  Key Promoter X (2023.3.0)
  indent-rainbow.indent-rainbow (2.2.0)
  com.wakatime.intellij.plugin (14.3.10)
  org.intellij.RegexpTester (2.2.0)
  com.intellij.nativeDebug (233.13135.65)
  String Manipulation (9.12.0)
  GrepConsole (12.22.1-IJ2021.1)
  net.seesharpsoft.intellij.plugins.csv (3.2.3-233)
  com.intellij.ml.llm (233.13135.116)
  com.intellij.lang.jsgraphql (233.13135.65)
  izhangzhihao.rainbow.brackets (2023.3.9-233)
  org.jetbrains.compose.desktop.ide (1.5.11)
  zielu.gittoolbox (500.1.5+222)
  mobi.hsz.idea.gitignore (4.5.2)
  cn.yiiguxing.plugin.translate (3.5.6)
Kotlin: 233.13135.103-IJ
Current Desktop: KDE

```

**Comment by pjBooms** [comment]
I have tried jdk 17.10 (timurrin), corretto-20.0.2.1, oracle openjdk 21 for the Gradle task, all they have created the deb package correctly on Ubuntu 22.04.03 with fakerooi installed. May you try to launch jpackage manually and fire the bug to OpenJDK?

**Comment by Xinkle** [comment]
Thanks for check. i also think it is related with jpackage.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4135">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
