### ISSUE TITLE
Allow disabling stylistic animations for controls.

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#4138]
In JavaFX when we create a ChoiceBox and click on it, the dropdown menu appears instantly. When it loses focus, it disapears instantly.

In Compose, the opening and closing dropdown menus animate. Not only is the timings of this animation hardcoded, but also the animation as a whole cannot be disabled.

Optional, stylistic animation of controls like this should be configurable. Sometimes it is desirable to have a more "comfy" feel to the app (which is how I would describe the default animation behavior). Other times, it is more desirable to have a more responsive and fast feel.

I am focusing on DropdownMenu here, but this is a request for an overall strategy of making all optional, stylistic animations configurable. At minimun, we should be able to disable them with a boolean input property or a `CompositionalLocal` toggle.

See `androidx.compose.material.DropdownMenuContent` for Desktop for a reference for where some animations are hardcoded.

**Comment by pjBooms** [comment]
I believe it should be configurable not only for Desktop but for other targets as well taht should be addressed in JetPack Compose first. Please create an issue in [Jetpack Compose issue tracker](https://issuetracker.google.com/components/612128) for this. Closing this issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4138">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
