### ISSUE TITLE
Expose resources functions to non composable functions

### ISSUE THREAD

**Issue by Burtan** [JetBrains/compose-multiplatform#4139]
Hey,

kotlin multiplatform lacks some common resource handling. The experimental compose multiplatform component tries to fix that. However, its functions are only available in `@Composable` functions. Still, the resource loading itself does not depend on `@Composable` and could theoretically used from any suspended function. Exposing the resource loading to the user without having to rely on `@Composable` functions could improve the overall kotlin multiplatform experience.

Thanks for consideration!

**Comment by Sanlorng** [comment]
you can browse the api，it contains some suspend resource function like `suspend fun getString`

**Comment by Burtan** [comment]
Ah, I see, it was added recently and I just checked the api for 1.5.11.

**Comment by chrisjenx** [comment]
Also looking at 1.6 commits, they are overhaulling the resource handling system into common code to make resources much more sensible. So sounds like this will be done (and more) with 1.6.

**Comment by pjBooms** [comment]
Yes, it will be fixed in 1.6.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4139">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
