### ISSUE TITLE
MenuBar issue in 0.3.0 ( not visible on start )

### ISSUE THREAD

**Issue by shynline** [JetBrains/compose-multiplatform#414]
Following the issue, I explained in #392 regarding the MenuBar

> basically at startup menu bar is not visible at all
and after a small window resize it appear
but if you tap on the menu items the pop-up is kinda behind the window area.
A reeeaally small part if it, is visible.

The MenuBar is now working properly but it's not still visible at the start and it needs to resize the window manually to show up
```
fun main() = Window(
    menuBar = MenuBar(
        Menu(
            name = "Files",
            MenuItem("New", onClick = {}),
        ),
    )
) {

}
```
I'm testing it on Ubuntu 20.04

**Comment by Inego** [comment]
Same problem here. Microsoft Windows, just copy-pasting code from tutorials. Menus covered by the window content:

![image](https://user-images.githubusercontent.com/2033759/108938622-04e76900-7683-11eb-832a-0a7b4148c6b4.png)

**Comment by Vahalaru** [comment]
If you look at jetpack compose,  it states that if you want a composable to be on top of the background you have to Durand it with "Surface". My guess is you would need to wrap your menu inside of surface.  [https://developer.android.com/codelabs/jetpack-compose-basics#3(reference I found)

**Comment by shynline** [comment]
@Inego I had the exact issue with the pop up in versions prior to `0.3.0` but not anymore

my current problem is that I can't see the `MenuBar` at the start at all and it becomes visible with a slight resize.

**Comment by Inego** [comment]
> @Inego I had the exact issue with the pop up in versions prior to `0.3.0` but not anymore

Hmm, my version of Compose is `0.3.0-build152`.

**Comment by Vahalaru** [comment]
> @Inego I had the exact issue with the pop up in versions prior to `0.3.0` but not anymore
> 
> my current problem is that I can't see the `MenuBar` at the start at all and it becomes visible with a slight resize.

Could it be something to do with it renders the menu first? Then when you resize it re renders everything in the correct order? 

Or I could see it not updating your ui to show the menu till you resize it then once that occurs it then pushed the composable to the screen.

**Comment by shynline** [comment]
@Vahalaru 
Actually I'm not sure what could be the problem but you may be onto something.

I know it worked in `0.3.0 build 134` and I think they changed the menu implementation under the hood.
I might be wrong I  can't really remember

**Comment by Vahalaru** [comment]
@shynline 
I don't know if you got any where with this but I got curious about the difference between a screen composable and a box composable and feel like that might be apart of it or resolve the issue. 

Inside of your window wrap everything else in a box composable. That will change how the different composables are shown and allow them to stack.

**Comment by dimsuz** [comment]
This is reproducible for me on `0.3.2` too. 

Linux, JVM 15, Target JVM 11

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5498">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
