### ISSUE TITLE
SemanticsNode tree containing incorrect values

### ISSUE THREAD

**Issue by elijah-semyonov** [JetBrains/compose-multiplatform#4140]
**Describe the bug**
Freshly constructed SemanticsNode tree is corrupted.

**Affected platforms**
Select one of the platforms below:
- Desktop
- iOS

**Versions**
jb-main head 6a1e1dfd2fd9c49398f190d0f0568467d1016a36

**To Reproduce**
Apply patch:
[change.patch](https://github.com/JetBrains/compose-multiplatform/files/13976078/change.patch)
1. Launch `desktop Demo`.
2. Click `Components`.
3. Observe that the debugPrinted semantics tree in the console contains `SemanticNode`s  from previous recomposition.

**Expected behavior**
Should only contain nodes that reflect the widgets visible on the screen.

**Screenshots**
<img width="513" alt="Screenshot 2024-01-18 at 12 45 38" src="https://github.com/JetBrains/compose-multiplatform/assets/4167681/5bd5dfb7-0af0-4558-b750-d3acd801bf4a">
<img width="318" alt="Screenshot 2024-01-18 at 12 45 12" src="https://github.com/JetBrains/compose-multiplatform/assets/4167681/9eaf3620-b532-4e9c-a31c-e758931c6525">

**Comment by elijah-semyonov** [comment]
Can be differentiated by `SemanticsNode.layoutNode.isPlaced`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4140">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
