### ISSUE TITLE
Autostart of the application

### ISSUE THREAD

**Issue by ArystanK** [JetBrains/compose-multiplatform#4141]
It will be great to have the functionality to set applications for the desktop to start automatically when the OS is booted

**Comment by chrisjenx** [comment]
This is not a Compose Multiplatform issue nor feature, this is more OS and Application dev specific - I would do a quick Google on how to start your application at startup.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4141">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
