### ISSUE TITLE
Unable to view source of compose components in IntelliJ

### ISSUE THREAD

**Issue by iamcalledrob** [JetBrains/compose-multiplatform#4143]
**Describe the bug**
Unable to view source of compose components in IntelliJ for a compose multiplatform project.
Only the decompiled .class file is shown.

**Affected platforms**
- All

**Versions**
- Kotlin version*:  1.9.21
- Compose Multiplatform version*: 1.5.4
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): Temurin 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a new project using the [kotlin multiplatform wizard](https://kmp.jetbrains.com/)
2. Open that project in IntelliJ CE
3. Attempt to view sources of any compose component (e.g. Ctrl / Cmd + Click on a composable)

**Expected behavior**
To see the source of the compose component

**Screenshots**
![Screenshot 2024-01-18 143705](https://github.com/JetBrains/compose-multiplatform/assets/87964/2c7fd3f7-0481-4468-93b1-bbb5ae4d6b36)
![Screenshot 2024-01-18 144152](https://github.com/JetBrains/compose-multiplatform/assets/87964/b205dc6d-221d-4969-be50-3e78b5e97da8)
![Screenshot 2024-01-18 144207](https://github.com/JetBrains/compose-multiplatform/assets/87964/e3e7db40-7ec5-495d-9927-1cf6314d6a96)

**Additional context**
Clicking "download sources" is non responsive. Clicking "choose sources" and choosing the .jar presents a warning "IDEA cannot determine what kind of files the chosen items contain". Pressing "yes" does nothing.

Empty project, as downloaded from the wizard: [KotlinProject.zip](https://github.com/JetBrains/compose-multiplatform/files/13981496/KotlinProject.zip)

**Comment by pjBooms** [comment]
Please create the issue in IntelliJ IDEA issue tracker -- https://youtrack.jetbrains.com/issues/IDEA

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5986">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
