### ISSUE TITLE
Add buildFeatures compose to be able to preview composables

### ISSUE THREAD

**Issue by gastsail** [JetBrains/compose-multiplatform#4149]
I noticed that the current template does not include the 

```
buildFeatures {
        compose = true
    }
```

inside the `android` tag in the shared `build.gradle.kt` file, this will be awesome to be included since all tooling and preview dependencies are in place but without this we cannot preview any function inside `androidMain`

Here is the template (wizard) : https://kmp.jetbrains.com/

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4149">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
