### ISSUE TITLE
Want to add script when uninstall.

### ISSUE THREAD

**Issue by lizhongyue248** [JetBrains/compose-multiplatform#4150]
In my application, many configuration files and temporary files are generated.  And they are stored in the user directory and temporary directory. I hope to delete these files when uninstalling the application, but now I cannot control the uninstallation behavior.

So I want to add a script to execute during uninstallation.

Currently, it seems that this feature is not available, or have I not found the correct way to use it?

**Comment by chrisjenx** [comment]
This is unrelated to Jetbrains Compose, that is more specific to Java/Native Applications. This project is just for the multiplatform jetpack compose features. I would do some googling around for best practiceses when building java/native applications

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4150">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
