### ISSUE TITLE
BasicTextField with custom decoration box is not working on desktop

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#4151]
**Describe the bug**

Text field doesn't react on input if `innerTextField` is not used. 
It works normally on Android.

**Affected platforms**
- Desktop (haven't checked other)

**Versions**
- Compose Multiplatform version*: 1.5.11

**To Reproduce**
1. Run the code below
2. Click on the first rect
3. Try type something - nothing happens

When you tap on it - it receives and instantly loses focus.
It also doesn't produce press and release interactions like it does on Android (https://github.com/JetBrains/compose-multiplatform/issues/4087 - not only outlined text field affected).
If you  **_press on text field and hold it_** while typing - input works correctly (as it has focus during press)

```kotlin
 var text by remember {
        mutableStateOf("")
    }

BasicTextField(
    value = text,
    onValueChange = {
        text = it
    }
) { notUsedInnerTextField ->
    Row(
        horizontalArrangement = Arrangement
            .spacedBy(12.dp)
    ) {
        repeat(6) {
            Box(
                modifier = Modifier
                    .width(35.dp)
                    .height(50.dp)
                    .border(1.dp, Color.Black),
                contentAlignment = Alignment.Center
            ) {
                Text(text = text.getOrNull(it)?.toString().orEmpty(),)
            }
        }
    }
}
```

**Comment by alexzhirkevich** [comment]
Works fine on latest jb-main

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4151">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
