### ISSUE TITLE
Skipping frames while resizing a transparent window

### ISSUE THREAD

**Issue by GazimSoliev** [JetBrains/compose-multiplatform#4153]
**Describe the bug**
Skipping frames while resizing a transparant window

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): Arch Linux 6.7.0-arch3-1
- OS architecture (x86 or arm64): x86-64
- JDK (for desktop issues): 17.0.10 temurin

**To Reproduce**
```
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material.Surface
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

fun main() = application {
    Window(onCloseRequest = ::exitApplication, title = "Window", undecorated = true, transparent = true) {
        Surface(color = Color.Green, modifier = Modifier.fillMaxSize()) { }
    }
}
```

**Expected behavior**
Without skipping frames while resizing

**Comment by dima-avdeev-jb** [comment]
Made reproducible sample here: https://github.com/dima-avdeev-jb/issue-4153
Tested on Manjaro Linux, and found some janks while resizing.

@GazimSoliev Can you please recoed a video for better understanding?

**Comment by GazimSoliev** [comment]
I tried recorded, screenrecorder can't catch that cuz of bitrate, but in reality compose skips 1-2 frames while resizing that makes window invisible, espaseally hard UI window

**Comment by GazimSoliev** [comment]
and yeah, it's so glitch

**Comment by dima-avdeev-jb** [comment]
On my Manjaro Linux I haven't encountered any problems with the invisible window.

**Comment by GazimSoliev** [comment]
> On my Manjaro Linux I haven't encountered any problems with the invisible window.

I noticed this in XORG session, it doesn't exist in Wayland

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4153">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
