### ISSUE TITLE
Scrollbar causes deadlock if dragged while fling is in progress

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#4154]
**Describe the bug**
Scrollbar causes deadlock if dragged while fling is in progress

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Compose Multiplatform version*: 1.5.11

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Display lazy list with scroll bar.
2. Scroll lazy list
3.  Drag scroll bar while fling is running.
4. App hangs forever on [runBlockingIfPossible](https://github.com/JetBrains/compose-multiplatform-core/blob/296fcc418dd88d684820a54490c3bd866412fc88/compose/foundation/foundation/src/skikoMain/kotlin/androidx/compose/foundation/v2/Scrollbar.skiko.kt#L445) call

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4154">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
