### ISSUE TITLE
[Feature]: HarmonyOS support

### ISSUE THREAD

**Issue by rustamsmax** [JetBrains/compose-multiplatform#4155]
Huawei launching a new mobile platform with it's own language.
It would be good enhancement to support it.

https://developer.harmonyos.com/en/docs/documentation/doc-guides/start-with-ets-0000001168323542
![telegram-cloud-photo-size-2-5291796924883654179-y](https://github.com/JetBrains/compose-multiplatform/assets/36570577/aab4bd6f-79a2-4720-9bb1-8aab8ff1a56e)

**Comment by elijah-semyonov** [comment]
I'm not sure how that's related to Compose Multiplatform.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4155">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
