### ISSUE TITLE
Desktop components(scrollbars and tooltips) for compose web(wasm)

### ISSUE THREAD

**Issue by Artrosis** [JetBrains/compose-multiplatform#4156]
I have a compose for desktop application. 
In it, I use scrollbars for the data table component.
I'm trying to move my project to desktop+web(wasm).
But when I transfer my dataTable component to the commonMain code, I get an error, because there are no scroll bars for compose wasm.

I think it's worth making compose desktop components (scrollbars and tooltips) available for compose wasm.

**Comment by AzimMuradov** [comment]
There is also #3981. JB team, feel free to merge mine with this one if it's more convenient. Alternatively, this issue could be about scrollbars only.

**Comment by PMARZV** [comment]
Any news on this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4156">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
