### ISSUE TITLE
shrinkOut ExitTransition not working in 1.6.0-beta01

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-multiplatform#4164]
**Describe the bug**

`shrinkOut` doesn't work in 1.6.0-beta01

**Affected platforms**
- All

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-beta01
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 22.04

**To Reproduce**
1. Check out [the PR to update to 1.6.0-beta01](https://github.com/eygraber/portal/tree/renovate/composejetbrains)
2. Run any of the below commands
4. Notice that when all of the numbers animate out at the end, the "2" doesn't move
5. Changing the "2"s ExitAnimation to something else works (in [this file](https://github.com/eygraber/portal/blob/renovate/composejetbrains/samples/simple-portal/src/commonMain/kotlin/com/eygraber/portal/samples/simpleportal/SimplePortal.kt#L65))

```
./gradlew :samples:simple-portal:android-app:installRelease
./gradlew :samples:simple-portal:desktop-app:run
./gradlew :samples:simple-portal:webApp:wasmJsBrowserDevelopmentRun
```

**Expected behavior**
It works as it did before 1.6.0-beta01

**Comment by elijah-semyonov** [comment]
Since Android seems to be affected, could you please also make a ticket in [Google Tracker](https://issuetracker.google.com/issues/new?component=612128&template=1253476) and paste the ticket link here?

**Comment by eygraber** [comment]
Do you know which version is used for Android on 1.6.0-alpha01 and 1.6.0-beta01 so I can include that in the issue that I file?

**Comment by elijah-semyonov** [comment]
Have a look here in `Dependencies` section:
https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-alpha01
https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-beta01

**Comment by eygraber** [comment]
https://issuetracker.google.com/issues/322267501

**Comment by eygraber** [comment]
Closing this because it should be handled by Google (if they decide that anything needs to be done; it's technically working as intended).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4164">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
