### ISSUE TITLE
[Component.Resources] Android fails when multiple submodules have strings.xml file

### ISSUE THREAD

**Issue by blazsolar** [JetBrains/compose-multiplatform#4165]
**Describe the bug**
When using the new resources feature and multiple submodules have `composeResources/values/strings.xml` file, Android compilation will fail with `n files found with path 'values/strings.xml' from inputs: ...` in the `merge...JavaResource` task. 

Android has the `android.packaging.resources.merge` option, but it only combines all the string files, which results in an invalid XML file. 

**Affected platforms**
Select one of the platforms below:
- Android - compose gradle plugin issue

**Versions**
- Kotlin version*: 1.9.22 
- Compose Multiplatform version*: 1.6.0-dev1383
- OS architecture (x86 or arm64): arm64

**To Reproduce**
1. Create a project with multiple shared modules and add strings.xml file to all of them. 
2. Try to run the Android app.
3. Check the gradle compilation error.

**Expected behavior**
`values/strings.xml` files should either have a unique path per submodule, or they should be merged into a single file for final Android compilation.

**Comment by hellomr3** [comment]
is there any solution?

**Comment by terrakok** [comment]
Hi! Multi-module projects are not supported yet. Keep all resources in a single top level module now.
It will be implemented in the future

**Comment by Stuart-campbell** [comment]
Hi, I see this is marked as completed do you know which version this feature is added in?

Thanks

**Comment by Stuart-campbell** [comment]
Ah, no problem thanks for clarifying.

**Comment by dima-avdeev-jb** [comment]
For actual information you can follow this link:
https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4165">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
