### ISSUE TITLE
Mouse-up doesn't send `Enter` event after dragging into an element

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#4166]
When dragging from one element into another, the first element receives an `Exit` event as soon as the pointer leaves its bounds. The entered element doesn't receive an `Enter` event, which is correct. But it also doesn't receive an `Enter` event when the mouse button is released.

On Android this behaves correctly.

**Affected platforms**
- Desktop

**Versions**
- Compose Multiplatform version*: 1.6.0-beta01

**To Reproduce**
Run the following, press inside the green square and drag into the blue square. When releasing the mouse button "Enter Blue" should be printed, but isn't.

```
private fun Modifier.printEnterExit(name: String) = pointerInput(name) {
    awaitPointerEventScope {
        while (true) {
            val event = awaitPointerEvent(PointerEventPass.Main)
            when (event.type) {
                PointerEventType.Enter -> println("Enter $name")
                PointerEventType.Exit -> println("Exit $name")
            }
        }
    }
}

fun main() = singleWindowApplication {
    Column {
        Box(Modifier
            .size(100.dp)
            .background(Color.Green)
            .printEnterExit("Green")
        )
        Box(Modifier
            .size(100.dp)
            .background(Color.Blue)
            .printEnterExit("Blue")
        )
    }
}
```

**Comment by AndreasLill** [comment]
Any progress on this fix?
This bug is preventing a feature in my application. :(

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4166">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4166">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
