### ISSUE TITLE
iOS Keyboard suggestions appear blank and intermittent capitalisation issue

### ISSUE THREAD

**Issue by LaatonWalaBhoot** [JetBrains/compose-multiplatform#4168]
**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): iOS 17.2
- OS architecture (x86 or arm64): arm64, iPhone 13 device

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

Using TextField while typing on a real iOS device intermittently capitalizes letters.
Clicking on suggestions appears blank in the text field. 
This is not happening on Android. Works fine there.

```
@Composable
fun MedialTextField(
    value: TextFieldValue,
    onValueChange: (TextFieldValue) -> Unit,
    placeHolder: String,
    singleLine: Boolean = true,
    maxLines: Int = if(singleLine) 1 else Int.MAX_VALUE,
    readOnly: Boolean = false,
    isError: Boolean = false,
    textStyle: TextStyle = MaterialTheme.typography.bodyMedium,
    keyboardOptions: KeyboardOptions = KeyboardOptions(capitalization = KeyboardCapitalization.Sentences),
    keyboardActions: KeyboardActions = KeyboardActions.Default,
    enabled: Boolean = true,
    supportingText: @Composable (() -> Unit)? = null,
    leadingIcon: @Composable (() -> Unit)? = null,
    endIcon: @Composable (() -> Unit)? = null,
    modifier: Modifier = Modifier
) {
    TextField(
        value = value,
        onValueChange = onValueChange,
        placeholder = { Text(text = placeHolder) },
        singleLine = singleLine,
        maxLines = maxLines,
        textStyle = textStyle,
        shape = RoundedCornerShape(12.dp),
        trailingIcon = endIcon,
        leadingIcon = leadingIcon,
        modifier = modifier.fillMaxWidth(),
        readOnly = readOnly,
        isError = isError,
        enabled = enabled,
        keyboardOptions = keyboardOptions,
        keyboardActions =keyboardActions,
        supportingText = supportingText,
        colors = TextFieldDefaults.colors(
            unfocusedContainerColor = Color.Transparent,
            focusedContainerColor = Color.Transparent,
            focusedIndicatorColor = Color.Transparent,
            unfocusedIndicatorColor = Color.Transparent
        )
    )
}
```

**Expected behavior**
Text should behave as it does in Android platform and keyboard suggestions should not be blank

**Screenshots**
First video: capitalization issue
Second video: suggestion click appearing blank

https://github.com/JetBrains/compose-multiplatform/assets/30817376/b5389322-7422-4a3c-aaf7-ce426a3e812c

https://github.com/JetBrains/compose-multiplatform/assets/30817376/134283ed-b7e1-482f-ac92-371aea02ef2a

**Comment by elijah-semyonov** [comment]
I fail to reproduce both issues. Can you provide exact arguments you use to create `TextField`?

**Comment by alexzhirkevich** [comment]
Keyboard suggestions issue is no longer reproducible in 1.6-beta (probably capitalization too)

**Comment by elijah-semyonov** [comment]
I tested it on both beta of 1.6 and 1.5.11 :)

**Comment by alexzhirkevich** [comment]
Hmm, i had suggestion problems on 1.5.11 too

**Comment by alexzhirkevich** [comment]
Actually i haven't checked it on my app :D. It still running 1.5.11 and suggestions doesn't work. But in mpp app suggestions work well. I'll try it in my app

**Comment by alexzhirkevich** [comment]
I guess text fields whos state is produced by remembered string in composition works good. But those whos state is produced by the StateFlow that comes from viewModel (even if viewModel updates it syncronously) - does not.

**Comment by alexzhirkevich** [comment]
Yep, i know the reactive streams problem, and i use it as described in the article (like without any suspensions, from regular function). I don't have other reactive stream issues like jumping cursor and so on

**Comment by Vaibhav2002** [comment]
This is how me and @LaatonWalaBhoot are doing it
```
var text by mutableStateOf(TextFieldValue(""))
    private set
        
fun onTextChange(text: TextFieldValue) {
    if (text.text.length <= POST_MAX_LENGTH) this.text = text
}

@Composable
fun PostTextBox(
    placeHolder: String,
    feature: CreatePostFeature,
) {
    val text = feature.text
    val length = derivedStateOf { text.text.length }
    MedialTextField(
        value = text,
        onValueChange = feature::onTextChange,
        placeHolder = placeHolder,
        singleLine = false,
        modifier = Modifier.fillMaxWidth(),
        supportingText = {
            Text(
                text = "${length.value}/$POST_MAX_LENGTH",
                modifier = Modifier.fillMaxWidth(),
                textAlign = TextAlign.End
            )
        }
    )
}

```

**Comment by elijah-semyonov** [comment]
Can you setup a minimal compilable snippet? I don't see anything suspicious here, but in the same time It's missing a lot of outer context, which could be vital to resolve the issue.

**Comment by LaatonWalaBhoot** [comment]
@elijah-semyonov @alexzhirkevich 
https://github.com/Medial-Tech/Medial-App-Reproducer
This is the reproducer

**Comment by mazunin-v-jb** [comment]
@LaatonWalaBhoot, @Vaibhav2002 
I apologize for a long time answering.
Your reproducer is not compiling. Seems like you haven't cleared enough of your working code.
But, I made [my own reproducer](https://github.com/mazunin-v-jb/cmp-issue-4168/) based on the code from provided reproducer.
I've checked this example both on the real device and simulator — couldn't reproduce.
Could you please review is it similar to your and try to run too?

**Comment by LaatonWalaBhoot** [comment]
@mazunin-v-jb thanks for replying. 
We managed to fix this by following
 https://medium.com/androiddevelopers/effective-state-management-for-textfield-in-compose-d6e5b070fbe5

Moving from StateFlow to Compose State fixed it. But we were still not sure if that's the right way to handle it. Hence kept the issue open. You can go ahead and close this

PS: Would BasicTextField2 fix text ripples with async fallouts?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4168">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
