### ISSUE TITLE
Compose inside `UIViewControllerRepresentable` doesn't properly communicate its layout with SwiftUI.

### ISSUE THREAD

**Issue by joyzem** [JetBrains/compose-multiplatform#4169]
**Describe the bug**
When you use Compose Multiplatform though UIViewControllerRepresentable SwiftUI interop API, a composable function is not rendering if it is called inside the ScrollView

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*:  1.9.21
- Compose Multiplatform version*: 1.5.11
- OS version(s)* (required for Desktop and iOS issues): iOS 17.0
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create any composable function with content inside it
2. Create SwiftUI interop container through UIViewControllerRepresentable
3. Call this in SwiftUI ScrollView container
4. See the composable function is not rendering

**Expected behavior**
Composable function should be rendered

**Additional context**
The composable function is rendering without any problems when it is used inside VStack

**Comment by elijah-semyonov** [comment]
Hi, thanks for report. We currently didn't dig deep into SwiftUI layout mechanism so there is a chance that `Representable` widget can't properly calculate its intrinsic size. Does the problem persist when you explicitly use `.frame` modifier on it?

**Comment by joyzem** [comment]
Thanks for the answer! I forgot to mention about `.frame` modifier.. This helps, but suddenly the size of my composable is not static and it is useless in my case. By the way, Compose Multiplatform is great! I'm waiting for new releases and I have fully Compose Multiplatform app in App Store :)

**Comment by elijah-semyonov** [comment]
That's nice to hear! 
I understand your use case. It sounds completely legit and we'll be looking into what we can do about it.

**Comment by elijah-semyonov** [comment]
Fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/1027

**Comment by harry248** [comment]
Any updates on this? We currently have to use the [workaround](https://johnoreilly.dev/posts/swiftui-component-compose-ios/) suggested by John O'Reilly but that requires a lot of boilerplate code.

**Comment by elijah-semyonov** [comment]
Still not, did you try experimenting with setting up a width NSLayoutConstraint manually on view of interop view controller and trying to figure out its height to pass to Compose using https://developer.apple.com/documentation/uikit/uiview/1622624-systemlayoutsizefittingsize?

**Comment by harry248** [comment]
Unfortunately, I don't quite understand the answer. Can you perhaps give me an example? If I understand it correctly, should I calculate the size in the Swift part and pass it through to the composable? But how is that supposed to work, because I need the intrinsic size of the composable and if I don't pass it through from the composable to the Swift part, it just seems to be 0.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4169">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4169">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
