### ISSUE TITLE
Resources non composable functions

### ISSUE THREAD

**Issue by Vivecstel** [JetBrains/compose-multiplatform#4170]
I would be great if resources non composable functions would be in a separate library to be used for kotlin multiplatform without compose multiplatform (ideally with their own gradle plugin or as a part of kotlin multiplatfrom plugin).

**Comment by terrakok** [comment]
KMP doesn't support resources. Make an issue in the kotlin tracker: kotl.in/issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4170">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
