### ISSUE TITLE
TypeError `x is undefined` / `stringLength` when using `values/strings.xml` compose resources on `wasmJs` target

### ISSUE THREAD

**Issue by rjaros** [JetBrains/compose-multiplatform#4171]
**Describe the bug**
An exception is thrown when trying to get string resources on `wasmJs`.
```
Uncaught (in promise) TypeError: x is undefined
    stringLength webpack-internal:///./kotlin/kilua-examples-resources-wasm-js.uninstantiated.mjs:30
kilua-examples-resources-wasm-js.uninstantiated.mjs:26
``` 
**Affected platforms**
Select one of the platforms below:
- Web (K/Wasm)

**Versions**
- Kotlin 1.9.22: 
- Compose Multiplatform version: 1.6.0-beta01

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Checkout https://github.com/rjaros/kilua/
2. Run `./gradlew -t :examples:resources:wasmJsRun`
3. Open http://localhost:8080
4. Click `Test compose resources` button
5. Check the browser console
6. See error

**Expected behavior**
No error. The `Compose Resources App` string printed in console.

**Additional context**
The application source code is here:
https://github.com/rjaros/kilua/blob/main/examples/resources/src/commonMain/kotlin/main.kt
It works ok when compiled to `js` target.

**Comment by rjaros** [comment]
On Kotlin 2.0.0-RC1 Wasm target and Compose 1.6.2 it still doesn't work, but the error message is different and even less  telling :
```
JsException: Exception was thrown while running JavaScript code
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4171">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
