### ISSUE TITLE
[1.6.0-beta01] Icons.AutoMirrored.Filled.ArrowBack is not available on iOS

### ISSUE THREAD

**Issue by chrisbanes** [JetBrains/compose-multiplatform#4172]
**Describe the bug**
My projects use icons such as `Icons.Default.ArrowBack` in `androidx.compose.material`. Some of the icons have now been deprecated, containing a `replaceWith` to migrate to `Icons.AutoMirrored.Filled.ArrowBack`. Unfortunately those functions are not available in the iOS version of Material icons.

When building for iOS the build fails with:

```
Unresolved reference: ArrowBack
```

There might be other icons missing.

**Affected platforms**
Select one of the platforms below:
- iOS

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Compose Multiplatform version*: 1.6.0-beta01
- OS version(s)*: iOS

**Comment by m-sasha** [comment]
Hi, can you provide a reproducer? It worked for me in a simple project.
Maybe `./gradlew clean` will help?

**Comment by chrisbanes** [comment]
Sorry, yep just a Gradle caching issue.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4172">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
