### ISSUE TITLE
Support escaping special characters in string resources files

### ISSUE THREAD

**Issue by fbarthelery** [JetBrains/compose-multiplatform#4178]
strings.xml files on Android support [escaping special characters](https://developer.android.com/guide/topics/resources/string-resource#escaping_quotes). To facilitate migration to multiplatform this should be supported too.

**Comment by terrakok** [comment]
https://github.com/JetBrains/compose-multiplatform/pull/4220

**Comment by fbarthelery** [comment]
This was asked in the PR but wasn't answered : what about quotes ? 
It was \\' that makes me notice this was missing first.

**Comment by terrakok** [comment]
For the compose resources you don't have to mirror quotes. So, we don't want to copy all android restrictions. Yes, you are supposed to slightly modify your xml

**Comment by fbarthelery** [comment]
Thanks for the clarification 👍

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4178">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
