### ISSUE TITLE
launcher Window transparency

### ISSUE THREAD

**Issue by connectionlink** [JetBrains/compose-multiplatform#418]
Is background transparency for the main window supported?

**Comment by Rsedaikin** [comment]
Currently, not all supported operating systems support window transparency, so for now we decided to disable transparency in order to achieve the same behavior on all operating systems.
But of course, when we solve this problem, we will add this feature to a future CFD release.

**Comment by smallshen** [comment]
@Rsedaikin Is their anyway to enable the window transparent? When I am sure the system support it

**Comment by aclassen** [comment]
Running Windows you can change the opacity of a undecorated Window via
`LocalAppWindow.current.window.opacity = 0.5F`

**Comment by danieldaydan** [comment]
Can the window be rounded?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5495">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
