### ISSUE TITLE
Preview compose multiplatform

### ISSUE THREAD

**Issue by hafiz013** [JetBrains/compose-multiplatform#4180]
I would like to have similar function @preview compose for compose multiple platform which consist of wasmJs, ios and android. Tq

**Comment by elijah-semyonov** [comment]
Related to https://github.com/JetBrains/compose-multiplatform/issues/3499

**Comment by MatkovIvan** [comment]
@elijah-semyonov it's not about template, but yes it's a known feature request of course - https://github.com/JetBrains/compose-multiplatform/issues?q=is%3Aopen+is%3Aissue+label%3Apreview

**Comment by dima-avdeev-jb** [comment]
@hafiz013 
Thanks, we already have the similar Issue here:
https://github.com/JetBrains/compose-multiplatform/issues/2045

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4180">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
