### ISSUE TITLE
Support for iOS Inline Text Predictions

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#4186]
https://support.apple.com/en-gb/guide/iphone/iphd4ea90231/ios

![IMG_5272](https://github.com/JetBrains/compose-multiplatform/assets/2178959/b0ebca0e-1cbd-4f29-a82c-1d652b954230)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4186">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
