### ISSUE TITLE
Tap title bar to scroll to top on iOS

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#4187]
On iOS, when there is a scroll view (e.g. in the Mail App or in Safari), tapping the status bar (where the clock etc is located) scrolls to the top of the main scrollable list.

A lot of apps have their "main view" be some kind of list, whether it's a social feed, list of documents / notes / articles. As such, having support for scroll-to-top for the main scrollable view would make the applications feel more like natively rendered apps.

https://github.com/JetBrains/compose-multiplatform/assets/2178959/1fff25a5-d36a-405b-b0fc-545171b01de9

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4187">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
