### ISSUE TITLE
[1.6.0-beta-1] CircularProgressIndicator error

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#4191]
**Describe the bug**
```
ATAL EXCEPTION: main
Process: com.ainoapp.aino, PID: 9822
java.lang.NoSuchMethodError: No virtual method at(Ljava/lang/Object;I)Landroidx/compose/animation/core/KeyframesSpec$KeyframeEntity; in class Landroidx/compose/animation/core/KeyframesSpec$KeyframesSpecConfig; or its super classes (declaration of 'androidx.compose.animation.core.KeyframesSpec$KeyframesSpecConfig' appears in /data/app/~~kwOdEP539ykogU0iwGWUIw==/com.ainoapp.aino-UMAyPOGYzW_AsEWiaZ_62g==/base.apk)
at androidx.compose.material3.ProgressIndicatorKt$CircularProgressIndicator$endAngle$1.invoke(ProgressIndicator.kt:371)
at androidx.compose.material3.ProgressIndicatorKt$CircularProgressIndicator$endAngle$1.invoke(ProgressIndicator.kt:369)
at androidx.compose.animation.core.AnimationSpecKt.keyframes(AnimationSpec.kt:649)
at androidx.compose.material3.ProgressIndicatorKt.CircularProgressIndicator-LxG7B9w(ProgressIndicator.kt:369)
```

**Affected platforms**
Select one of the platforms below:
- Android

**Versions**
- Kotlin version*: 2.0
- Compose Multiplatform version*: 1.6.0-beta-1

**Comment by rushiiMachine** [comment]
https://github.com/JetBrains/compose-multiplatform/issues/4157

**Comment by MatkovIvan** [comment]
It's a known issue as mentioned above.

Also, please note that Compose Multiplatform uses original Google's Jetpack Compose binaries on Android, so please don't ignore this line in the issue template:
> If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Comment by MatkovIvan** [comment]
This issue in the Google's tracker: https://partnerissuetracker.corp.google.com/issues/322214617

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4191">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
