### ISSUE TITLE
[1,6.0-beta01] .DS_Store is not directory! Raw files should be placed in 'composeResources/files' directory.

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#4192]
hi
in macos for generate res class i get the following error :

` .DS_Store is not directory! Raw files should be placed in 'composeResources/files' directory.`

**Comment by Kashif-E** [comment]
you might have copy pasted something to composeResources directory. Delete the directory recreate it and copy paste through Android studio

**Comment by Kashif-E** [comment]
.Ds_store is a mac file which is used to store folder information

**Comment by mahramane** [comment]
Thank you.
it works.

**Comment by MatkovIvan** [comment]
Fixed by https://github.com/JetBrains/compose-multiplatform/commit/3040ea85bbc81cb6d1e22d6928646509ee8b601f

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4192">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
