### ISSUE TITLE
Add the possibility to make the generated Res class public

### ISSUE THREAD

**Issue by asapha** [JetBrains/compose-multiplatform#4193]
Right now, it's internal, which makes it not accessible by other modules.

Taking the `:resources:demo` project as an example, the app's name needs to be duplicated in 
`shared/src/commonMain/composeResources/values/strings.xml`, `desktopApp/src/jvmMain/kotlin/Main.kt`

```kotlin
singleWindowApplication(
        title = "Resources demo",
        state = WindowState(size = DpSize(800.dp, 800.dp))
    ) {
        MainView()
    }
``` 

and `androidApp/src/main/res/values/strings.xml`

```xml
<resources>
    <string name="app_name">Resources demo</string>
</resources>
``` 

It could be parameterized like in [moko-resources](https://github.com/icerockdev/moko-resources/?tab=readme-ov-file#gradle-setup)

cf. https://github.com/JetBrains/compose-multiplatform/blob/2e354eba3a98d8b39a0a6057b2547493ba2734b8/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/resources/ResourcesSpec.kt#L104-L106

**Comment by terrakok** [comment]
> Right now, it's internal, which makes it not accessible by other modules.
yes. it is the current design decision. module's resources are isolated from each other. if you want to provide it outside you are suppose to declare explicit API in the module.

**Comment by m0rtis** [comment]
> yes. it is the current design decision. module's resources are isolated from each other. if you want to provide it outside you are suppose to declare explicit API in the module.

 Konstantin I'm so grateful for your answer! I finally got how to get my resources from my compose ui design system library in my applications! But I have a question - why that design decision was made? I want to extract my compose elements to separate library and reuse it in several applications. May be I'm doing something wrong?

**Comment by MatkovIvan** [comment]
https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html

> - Multimodule projects are not supported yet. The JetBrains team is working on adding this functionality in future releases. For now, store all resources in the main application module.
>
> - The publication of Compose Multiplatform libraries with resources is not supported yet. The JetBrains team is working on adding this functionality in future releases.

Currently, there are some limitations in underlying things that block us from doing this. We're working with Kotlin and other teams to make this happen.

**Comment by m0rtis** [comment]
Ivan thank you a lot! Will wait quietly:))

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4193">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
