### ISSUE TITLE
[1.6.0-beta01] how to convert Res painterResource to ImageBitmap

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#4195]
Hi
I generate the Res class.
Now i want to convert the painterResource to the ImageBitmap.
How can i do it?

**Comment by terrakok** [comment]
use `org.jetbrains.compose.resources.ImageResourcesKt#imageResource`

**Comment by mahramane** [comment]
> use `org.jetbrains.compose.resources.ImageResourcesKt#imageResource`

Please give me an example

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4195">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
