### ISSUE TITLE
How building apps for different chip architectures on Mac?

### ISSUE THREAD

**Issue by Caij** [JetBrains/compose-multiplatform#4200]
built ARM64 app on a Mac with x86_64 architecture, or built x86_64 app on a Mac with arm64 architecture

**Comment by mazunin-v-jb** [comment]
Hello!
packageDmg can build both arm64 and x86_64

**Comment by m-sasha** [comment]
@Caij You can only build distributables on the same platform as the distributable target. This is because `jpackage`, which does the actual work, puts the JRE inside the distributable, and the JRE it puts there is the JRE it is part of itself.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4200">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
