### ISSUE TITLE
[IOS] The keyboard opens when I begin scrolling within a TextField.

### ISSUE THREAD

**Issue by dan15d** [JetBrains/compose-multiplatform#4204]
Hello!

I have a LazyColumn containing numerous TextFields as part of a form. It works fine on Android, but on iOS, when I start scrolling within a TextField by tapping and holding my finger without actually clicking, the keyboard opens up.

Version compose multiplatform 1.5.12

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4204">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
