### ISSUE TITLE
Allow enabling compose compiler per target in multiplatform module

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#4209]
Consider a project with a single multiplatform module with a js target for frontend and a jvm target for backend. This module might want to only enable the compose gradle plugin, compose compiler, and compose dependencies for the JS target and completely leave out compose for the jvm target.

This is discussed in https://github.com/JetBrains/compose-multiplatform/issues/1568. But it seems that issue is being treated as a question and not an enhancement proposal. So here I am making the proposal that the Compose Multiplatform Gradle Plugin allows developers to toggle compose per Kotlin Multiplatform target within a single module.

**Comment by eymar** [comment]
Will this solution work for you? https://github.com/JetBrains/compose-multiplatform/pull/3722

**Comment by eymar** [comment]
Not sure that configuring it per source set is possible at all. The source sets can't be compiled independetly. All relevant source sets get "combined" to compile for a particular target, and if a target declares to apply the Compose plugin, it means it's applied to all code (involved source sets). 

And as for gradle configurations, I'm not sure I understand how it can affect the logic to apply or not apply the plugin.
I guess we can only decide to apply or not based on the target type or target name.

**Comment by eymar** [comment]
Yes, those are 2 jvm targets with different names.

Sure, let's close it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4209">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
