### ISSUE TITLE
[IOS] AlertDialog on IOS don't have animation to avoid keyboard

### ISSUE THREAD

**Issue by hoanghai9650** [JetBrains/compose-multiplatform#4210]
**Describe the bug**
I'm using AlertDialog and having TextField inside it.
On Android when I focus the TextField, when keyboard appear, the AlertDialog's move up animation work perfectly, but on IOS there is no animation for that, and IOS don't have animation for appearing that AlertDialog

Another Problem with TextField, I have multiple TextField in Dialog, I'm focusing 1 TextField and select to another TextField, the keyboard of IOS auto closed and reopened, but in Android there is no problem.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.6.0-beta01
- OS version(s)* (required for Desktop and iOS issues): 17.2
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Use AlertDialog
2. Add TextField to it
3. Focus TextField
4. Dialog don't have move up animation to avoid keyboard

**Expected behavior**
Dialog must have move up animation to avoid keyboard on IOS.
Keyboard don't reopen when change focus on another TextField

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4210">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
