### ISSUE TITLE
MinHeight or MinWidth with weight

### ISSUE THREAD

**Issue by GazimSoliev** [JetBrains/compose-multiplatform#4212]
**Describe the bug**
Can't make behaivor like that. Componet min heigh is 512dp but parent component have more space than 512dp then occupy all available space in height. 
**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version*: 1.9.21 
- Compose Multiplatform version*: 1.6.0
- OS version(s)* (required for Desktop and iOS issues): Android 13 and Arch Linux
- OS architecture (x86 or arm64): amd 64
- JDK (for desktop issues): 17

**To Reproduce**
```
fun main() {
    application {
        Window(onCloseRequest = ::exitApplication) {
            Column(modifier = Modifier.fillMaxSize().verticalScroll(rememberScrollState())) {
                Box(Modifier.fillMaxWidth().height(256.dp).background(Color.Red))
                Box(Modifier.fillMaxWidth().heightIn(min = 512.dp).weight(1f).background(Color.Blue))
            }
        }
    }
}
```

**Expected behavior**
Child element has min height or min width and the same time has weight if parent is scrollable

**Comment by tahaak67** [comment]
I don't think is a compose multiplatform issue as the behaviour is the same on jetpack compose.
also when weight is used compose measures the size of all other components then gives the approperiate height / weight based on available space, so when you have a lot of other elements in the column and there is no space left the blue box will not be visible.

if you need the blue box to have a fixed height if the parent is scrollable but has a weight if its not scrollable you can set your modifier based on a condition
``` kotlin
        val scrollState = rememberScrollState()
        Column(modifier = Modifier.fillMaxSize().verticalScroll(scrollState)) {
            val boxModifier = if (scrollState.canScrollForward || scrollState.canScrollBackward) {
                Modifier.heightIn(min = 512.dp)
            } else {
                Modifier.weight(1f)
            }

            Box(Modifier.fillMaxWidth().height(256.dp).background(Color.Red))
            Box(boxModifier.fillMaxWidth().background(Color.Blue))
        }
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4212">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
