### ISSUE TITLE
Wrong FRAMEWORK_SEARCH_PATHS in generated iOS templates

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/compose-multiplatform#4214]
**Describe the bug**
When you create an application template for iOS with the Kotlin Multiplatform Wizard, it will contain two wrong FRAMEWORK_SEARCH_PATHS in the iosApp.xcodeproj file.

```
FRAMEWORK_SEARCH_PATHS = (
	"$(SRCROOT)/../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)\n$(SRCROOT)/../composeApp/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)",
);

```
As can be seen it uses `../shared` which does not exits anymore and should be `../composeApp` instead.

**Affected platforms**
Select one of the platforms below:
- iOS

**Comment by mazunin-v-jb** [comment]
Hello!
We're not responsible for Kotlin Multiplatform Wizard, could you [please create the issue here](http://kotl.in/issue)?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4214">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
