### ISSUE TITLE
Update KotlinPoet in Gradle plugin

### ISSUE THREAD

**Issue by chrisbanes** [JetBrains/compose-multiplatform#4217]
The CMP plugin is using [KotlinPoet 1.14.2](https://github.com/JetBrains/compose-multiplatform/blob/master/gradle-plugins/gradle/libs.versions.toml#L11), which is causing issues with other plugins which use a newer version. See https://github.com/gmazzo/gradle-buildconfig-plugin/issues/131

The simplest fix is for the CMP plugin to use a more recent version.

**Comment by terrakok** [comment]
https://github.com/JetBrains/compose-multiplatform/pull/4239

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4217">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
