### ISSUE TITLE
Request to support BasicTextField2

### ISSUE THREAD

**Issue by dhakehurst** [JetBrains/compose-multiplatform#4218]
seems not supported in mutiplatform yet

**Comment by chrisbanes** [comment]
BasicTextField2 was added in Jetpack Compose 1.6.0, so you need to use CMP [1.6.0-beta01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-beta01)

**Comment by dhakehurst** [comment]
erm....the code says it is still not supported !

![image](https://github.com/JetBrains/compose-multiplatform/assets/5618533/adb4f7bb-9794-447f-a485-04ceb89db128)

**Comment by mazunin-v-jb** [comment]
Hello!
For now, we don't support BasicTextField2, but we are working on it.

**Comment by m-sasha** [comment]
Initial support for BasicTextField2 is in [1.6.10-beta01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10-beta01)

**Comment by Cuyer** [comment]
Are there any updates on this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4218">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
