### ISSUE TITLE
Emoji weirdness with compose desktop

### ISSUE THREAD

**Issue by zoff99** [JetBrains/compose-multiplatform#4223]
**Describe the bug**
why do emoji in text work differently on macos, windows, ubuntu? and why does it work really bad on all three?
look at the 3 screenshots (lower right corner the emoji popup)
how to display at least the first 20 smiley emoji properly on the main OS's with compose desktop?

![aaa](https://github.com/JetBrains/compose-multiplatform/assets/6833516/17197a11-7d3b-4a27-a48c-3355c32d81b0)

what is used to draw smiley "images" instead of font? how does this work under the hood in compose desktop?
is this a font issue? a gtk issue? openGL issue? i dont even know

-----------------------------------

and then even more weirdness:

also can anybody explain this screenshot ?
on the right in the popup the thumbup emoji is black and white font, in the text input box on the bottom then the exact same text is pasted into, it suddenly is a yellow graphic. and in the middle in the message view the exact same text is a yellow image graphic again.
whats going on here?
![image_720](https://github.com/JetBrains/compose-multiplatform/assets/6833516/f2bc230b-7806-4d89-9286-c9315c7fb084)

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: all
- Compose Multiplatform version*: all
- OS version(s)* (required for Desktop and iOS issues): Linux and others
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 17 and 21

**Comment by m-sasha** [comment]
It's perfectly valid for emojis to look differently on different platforms. This is already the case for Android vs. iOS.
See https://www.howtogeek.com/784832/that-emoji-might-not-look-the-same-on-your-friends-phone/ for example.

**Comment by zoff99** [comment]
in the screenshot you can see the exact same emoji (copy and paste) look 2 different ways on linux

**Comment by mazunin-v-jb** [comment]
Hello, @zoff99.
Could you please send a minimal reproducer for that behavior? And better screenshots, if possible.

**Comment by m-sasha** [comment]
> in the screenshot you can see the exact same emoji (copy and paste) look 2 different ways on linux

That's likely a problem with transferring the text correctly through the clipboard.

**Comment by zoff99** [comment]
i dont think so. its the same if you write it into the textfield programmatically

**Comment by zoff99** [comment]
👍

**Comment by zoff99** [comment]
🫵👍

**Comment by zoff99** [comment]
paste the above into a textfield in compose desktop.
first paste the single emoji. then remove and paste the 2 emojis below.

**Comment by zoff99** [comment]
you should end up with different things like this screenshot

![image](https://github.com/JetBrains/compose-multiplatform/assets/6833516/c5a2dd85-2321-4f42-a139-f80a432e51f0)

**Comment by zoff99** [comment]
you can also programmatically write it into the text field
(i cant paste the text here, it will turn into an image, so its a screenshot)

![image](https://github.com/JetBrains/compose-multiplatform/assets/6833516/c61e31fe-30da-4a30-a1dc-7fe0124c5927)

and then

![image](https://github.com/JetBrains/compose-multiplatform/assets/6833516/7daa257a-0626-4272-b8e8-6c400bccf0c9)

**Comment by zoff99** [comment]
![output](https://github.com/JetBrains/compose-multiplatform/assets/6833516/17a04220-0b3a-47a8-a07e-0e2e188ed307)

**Comment by zoff99** [comment]
when i paste the right emoji to the start of the textfield, suddenly the middle emoji turns into a picture.
when i remove the emoji from the start, the middle emoji turns back into a pumpkin ähm monochrome font item

**Comment by zoff99** [comment]
and also why is the middle icon not a "yellow picture" in the first place? the picture clearly exists, otherwise how can i turn into a picture?

**Comment by m-sasha** [comment]
Doesn't appear to reproduce on macOS: 
```
fun main() = singleWindowApplication {
    Column(Modifier.fillMaxSize().background(Color.DarkGray)) {
        TextField(
            value = "\uD83D\uDC4D",
            onValueChange = { }
        )
        TextField(
            value = "\uD83E\uDEF5\uD83D\uDC4D",
            onValueChange = { }
        )

        var text by remember { mutableStateOf("") }
        TextField(
            value = text,
            onValueChange = { text = it }
        )
    }
}
```


https://github.com/JetBrains/compose-multiplatform/assets/5230206/3ec45292-51be-40ab-95f0-5ca6b2a0d828

**Comment by zoff99** [comment]
on ubuntu 22.04:

![ub_emoji_broken](https://github.com/JetBrains/compose-multiplatform/assets/6833516/7c0c083e-a464-4744-8dfe-efaed5395fde)

**Comment by zoff99** [comment]
there must be 2 bugs here. because apart from this weirdness, why is the yellow emoji not showing in the first place? the emoji image is clearly available, otherwise it couldn't show up later.

**Comment by zoff99** [comment]
also i saw the same issue on manjaro linux

**Comment by zoff99** [comment]
any idea yet where that bug can be located?

**Comment by zoff99** [comment]
any news on that one? what library is used under the hood to draw those emoji on linux?

**Comment by zoff99** [comment]
any more information what the underlying problem is?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4223">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by zoff99** [comment]
why are you closing tickets and referring to another platform?
