### ISSUE TITLE
How can I develop compose-multiplatform projects using Intellij IDEA.

### ISSUE THREAD

**Issue by Zeng1998** [JetBrains/compose-multiplatform#4224]
**Describe the bug**
How can I develop compose-multiplatform projects using Intellij IDEA.

I use Intellij IDEA to open the project from Kotlin Multiplatform Wizard. Everything work well except the android app.

**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version*: 1.9
- Compose Multiplatform version*: 1.6
- OS version(s)* (required for Desktop and iOS issues):  Windows 11
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues):  JDK 21

**To Reproduce**
Download from Kotlin Multiplatform Wizard and open using IDEA.

**Expected behavior**
Using IDEA to develop desktop, wasm and android projects.

**Screenshots**

![image](https://github.com/JetBrains/compose-multiplatform/assets/31177490/39546388-bda4-40c2-9b08-a2f542055853)

looks like that the android app module is not detected.

![image](https://github.com/JetBrains/compose-multiplatform/assets/31177490/1c63e911-03cf-491b-9352-d3fdedc0589b)

no syntax highlight and no run configuration.

**Comment by mazunin-v-jb** [comment]
Hello, @Zeng1998!
The problem may be that Android Plugin is disabled in your settings. Could you please check if it is enabled?
Follow Settings -> Plugins (in the menu bar on the left side) -> Installed (right tab on the appeared screen).

**Comment by Zeng1998** [comment]
Hello, @mazunin-v-jb , thanks your reply. I have made some retries and now there is something new.

I download a new project generated by https://kmp.jetbrains.com and open in IDEA directly. It contains Android, Desktop, and WASM.

Now, all modules are accurately detected. But there are still some that confuse me.

![image](https://github.com/JetBrains/compose-multiplatform/assets/31177490/ce0b0362-4116-4831-b8da-910b542ecf75)

1. For the desktop app, it's easy to run by just opening `main.kt` and clicking the 'run button'.

![image](https://github.com/JetBrains/compose-multiplatform/assets/31177490/14e8eeec-87f1-415f-922a-14043b342053)

2. For the WASM app, I open `main.kt` but there is no 'run button'. Is this because IDEA has not yet supported this experimental feature? Of course, I can find the corresponding running command in Gradle.

![image](https://github.com/JetBrains/compose-multiplatform/assets/31177490/b6234f6c-d086-439a-9b8d-ecc6e98e3b49)

![image](https://github.com/JetBrains/compose-multiplatform/assets/31177490/4671f2e4-0594-4afb-b3dd-61b639641aae)

3. For the Android app, I open `MainActivity.kt` and there is no 'run button' either. But I can find a run configuration named 'composeApp' in the IDEA.

![image](https://github.com/JetBrains/compose-multiplatform/assets/31177490/c8d4eddb-f884-4063-b3d5-4bf634ad959f)

![image](https://github.com/JetBrains/compose-multiplatform/assets/31177490/e23a3d9d-0744-4b9e-b69c-fdd7ef34c89f)

Overall, I can run all the apps so far, but it still looks a bit complicated and may require a clearer understanding of the Gradle configuration files for me.
