### ISSUE TITLE
Kotlin 2.0.0-Beta3 Support

### ISSUE THREAD

**Issue by ZacSweers** [JetBrains/compose-multiplatform#4227]
Are there plans to support K2 Beta3? Currently the only available compose-compiler release is Beta1.  I found a previous comment that said [no Beta2 support would come](https://github.com/JetBrains/compose-multiplatform/issues/4044#issuecomment-1889513471), but it's on Beta3 now and I haven't seen any update in discussions or `VERSIONING.md`.

**Comment by ZacSweers** [comment]
Someone pointed me at `1.5.6-dev2-kt2.0.0-Beta3`, but I don't know where they found that info 😅

**Comment by mahozad** [comment]
How about searching in the [jetbrains Compose dev repository](https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/compiler/compiler/) :)

**Comment by ZacSweers** [comment]
Closing this in favor of #4293 I guess?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4227">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
