### ISSUE TITLE
[Enhancement] More customization capabilities for resource generators plugins

### ISSUE THREAD

**Issue by xinzhengzhang** [JetBrains/compose-multiplatform#4228]
Currently composed resource generators do not have customization capabilities(https://github.com/JetBrains/compose-multiplatform/blob/master/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/resources/ResourcesGenerator.kt), e.g. Res is internal level.  Generation strategies for drawable density.

Is it possible to add some options such as at least one to turn off the autogeneration of res?

----
Another appeal: 

I am using Bazel to organize kmm projects, now because this tool is in the gradle plugin I need to strip it out to adapt to Bazel Is it possible to export a standalone cli tool like `aapt` for the Res source code generation?

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*: 1.6.0-beta01

**Comment by asapha** [comment]
(Related to #4193)

> > Right now, it's internal, which makes it not accessible by other modules.
>
>yes. it is the current design decision. module's resources are isolated from each other. if you want to provide it outside you >are suppose to declare explicit API in the module.

**Comment by mipastgt** [comment]
Another nice customization would be the possibility to set the root package name.

**Comment by terrakok** [comment]
Fixed by https://github.com/JetBrains/compose-multiplatform/pull/4482

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4228">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
