### ISSUE TITLE
Resources: multimodule projects support

### ISSUE THREAD

**Issue by xinzhengzhang** [JetBrains/compose-multiplatform#4229]
**Describe the bug**
Two modules has values/strings.xml cause compile error

**Affected platforms**
Select one of the platforms below:
- Android

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*:  1.6.0-dev1397

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Go to 'compose-multiplatform/components/resources'
2. Duplicated demo/shared directory to demo/shared2 and only leave demo/shared2/src/commonMain/composeResources/values/strings.xml
3. Add shared2 to deps of settings.gradle.kts and demo/androidApp
4. `:resources:demo:androidApp:assembleDebug`

**Expected behavior**
Compile succeed

**Screenshots**
<img width="971" alt="Screenshot 2024-02-04 at 13 05 06" src="https://github.com/JetBrains/compose-multiplatform/assets/1487445/9e51439c-b422-47c0-a60c-0b4615ee1626">

**Comment by xiaozhikang0916** [comment]
Any progress on this issue?

**Comment by blazsolar** [comment]
Based on the response https://github.com/JetBrains/compose-multiplatform/issues/4165#issuecomment-1956186629, this will not be implemented.

**Comment by xiaozhikang0916** [comment]
So, according to https://github.com/JetBrains/compose-multiplatform/issues/4327#issuecomment-1954607045 and https://github.com/JetBrains/compose-multiplatform/issues/4165#issuecomment-1956186629, if I need to use string resources in multiple modules with compose, I have to extract those resources in one public module and export all the resources by handwriting codes?

**Comment by MobiDevelop** [comment]
> So, according to [#4327 (comment)](https://github.com/JetBrains/compose-multiplatform/issues/4327#issuecomment-1954607045) and [#4165 (comment)](https://github.com/JetBrains/compose-multiplatform/issues/4165#issuecomment-1956186629), if I need to use string resources in multiple modules with compose, I have to extract those resources in one public module and export all the resources by handwriting codes?

This isn't really an acceptable solution.

**Comment by terrakok** [comment]
https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html

> - Multimodule projects are not supported yet. The JetBrains team is working on adding this functionality in future releases. For now, store all resources in the main application module.
>
> - The publication of Compose Multiplatform libraries with resources is not supported yet. The JetBrains team is working on adding this functionality in future releases.

Currently, there are some limitations in underlying things that block us from doing this. We're working with Kotlin and other teams to make this happen.

**Comment by xiaozhikang0916** [comment]
Please consider making the default visibility `public` of the generated `Res` class for the current limitations to avoid the boilerplate exposing fields or hacking scripts.

**Comment by terrakok** [comment]
https://github.com/JetBrains/compose-multiplatform/issues/4327#issuecomment-1964492518

**Comment by xinzhengzhang** [comment]
Is it possible to add at least a turn off switch to control the resource itself if it is not expected to use the resource? Or is it more recommended not to use the composeResources directory in this case?

**Comment by terrakok** [comment]
Could you explain your problem? I don't get it

**Comment by xinzhengzhang** [comment]
> Could you explain your problem? I don't get it

Main reasons:
I am using bazel to organize kmm projects, and will generate ide projects (gradle) for R & D similar to [rules_xcodeproj](https://github.com/MobileNativeFoundation/rules_xcodeproj) for iOS. For some generate artifacts (ksp & kapt) I currently have my own generation pipeline and do not use gradle plugin. This is why I want to be able to control the production products (Res) myself.

Other reasons:
Currently there are many limitation on using Res, such as requiring the use of one module to integrate Res, and handwriting template code to expose internal resources is not very friendly, and I will even consider analyzing the Res pipeline to make these internal resources public. This is also I hope there is a switch to turn off this part, and I manage the pipeline generation of integrated Res myself

**Comment by terrakok** [comment]
https://github.com/JetBrains/compose-multiplatform/pull/4454

**Comment by xinzhengzhang** [comment]
> #4454

Thank a lot for the support!
In addition, I would like to confirm about Resources.Options

So far I see only `enum class ResourceClassGeneration {Auto, Always}` I would like to ask if there are plans to separate the Resource compile tool like `aapt` in android and open {Never} to add more freedom for some customization scenarios?

**Comment by Deorigami** [comment]
![gambar](https://github.com/JetBrains/compose-multiplatform/assets/70903634/6ee491f2-fa3b-47bd-9795-2a2defd63cda)
Hi @xiaozhikang0916 .. can you please tell me on how to configure the Resources to be Public .. i cant fint the Resources Extensions .. thank you

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4229">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
