### ISSUE TITLE
[1.6.0-beta01] Unresolved stdlib imports in IDEA when only jvm and wasmJs targets are enabled

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-multiplatform#4230]
**Describe the bug**
IDEA shows stdlib imports unresolved with Compose `1.6.0-beta01` and only two targets enabled: `jvm` and `wasmJs`. If I add e.g. `iosX64` target then imports are resolved again. Also works fine with Compose `1.6.0-alpha01`.

**Affected platforms**

- Desktop
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*: 1.6.0-beta01
- OS version(s)* (required for Desktop and iOS issues): macOS 13.5.2
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): jbr-17
- IDE: IntelliJ IDEA 2023.3.3 (Ultimate Edition)

**To Reproduce**

See the project: [Reproducer.zip](https://github.com/JetBrains/compose-multiplatform/files/14157999/Reproducer.zip)

**Expected behavior**

Stdlib imports are resolved.

**Screenshots**

![image](https://github.com/JetBrains/compose-multiplatform/assets/26204457/f0a2e2e7-1b62-4a16-b32b-57f13cea023d)

**Comment by terrakok** [comment]
try a workaround: set the Kotlin version to 1.9.22

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4230">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
