### ISSUE TITLE
"Failed to launch JVM" message error at run 

### ISSUE THREAD

**Issue by Artrosis** [JetBrains/compose-multiplatform#4233]
**Describe the bug**
If there is an error (exception) when launching the application(packed from createDistributable task), i get a confusing error text: "Failed to launch JVM"

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*:  1.9.10
- Compose version*: 
  compose = "1.5.4"
  compose-plugin = "1.6.0-alpha01"
  compose-compiler = "1.5.4"
- OS version(s)* (required for Desktop and iOS issues): Windows7/10
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create new project from ComposeForDesktop template
2. Add row `throw Exception("Ошибка")` in main function(in application function, content argument)
3. run createDistributable task to package exe
4. run exe
5. see "Failed to launch JVM" message error

**Expected behavior**
Message from exception

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/12668763/9540fa6c-1464-495f-8bbb-d127d5f48bc6)

*I spent a lot of time to realize that this is a bug in my code, not in the packager.

**Comment by terrakok** [comment]
The Compose handles exceptions only inside the compose window. If you want to show an alert dialog in your application outside the compose content you are supposed to implement own [UncaughtExceptionHandler](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.UncaughtExceptionHandler.html)

```kotlin
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState
import org.company.app.App
import java.awt.*

fun main() {
    Thread.setDefaultUncaughtExceptionHandler { _, e ->
        Dialog(Frame(), e.message ?: "Error").apply {
            layout = FlowLayout()
            val label = Label(e.message)
            add(label)
            val button = Button("OK").apply {
                addActionListener { dispose() }
            }
            add(button)
            setSize(300,300)
            isVisible = true
        }
    }

    application {
        throw Exception("My custom error!")
        Window(
            title = "Multiplatform App",
            state = rememberWindowState(width = 800.dp, height = 600.dp),
            onCloseRequest = ::exitApplication,
        ) {
            window.minimumSize = Dimension(350, 600)
            App()
        }
    }
}
```

**Comment by cicoenote** [comment]
https://github.com/JetBrains/skiko/pull/541

**Comment by terrakok** [comment]
it is not related PR

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4233">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
