### ISSUE TITLE
Support `Modifier.dragAndDropSource` and `Modifier.dragAndDropTarget`

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4235]
It was merged from Jetpack Compose 1.6:
https://android-developers.googleblog.com/2024/01/whats-new-in-jetpack-compose-january-24-release.html
See "Drag and drop"

**Comment by hakanai** [comment]
Any signs of life?

**Comment by g3th** [comment]
Absolutely dreadful. Claiming 'Multiplatform support' for a framework, then lacking basic features for Desktop development (i.e. OnDragListener for Desktop) makes this framework nothing but a toy, where building anything more complex than a simple scope blog or news app is overly complex and nothing but a dream.

**Comment by g3th** [comment]
Absolutely dreadful. This framework has been in development since 2020, and yet something as basic as OnDragListener with DragEvents for Desktop is missing. Implementing drag-and-drop on Compose Desktop is an absolute nightmare, and something as simple as a jigsaw puzzle results in convulted, terrible code to maintain. 

What have you guys been doing for 4 years? 'Styling'? This framework is just a toy, the multiplatform promise is still a lie, and working on anything more interesting than trivial news/blog/reading apps is currently not worth it.

**Comment by yumiki** [comment]
> Absolutely dreadful. 
> 
> This framework has been in development since 2020, and yet something as basic as OnDragListener with DragEvents for Desktop is missing. Implementing drag-and-drop on Compose Desktop is an absolute nightmare, and something as simple as a jigsaw puzzle results in convulted, terrible code to maintain. 
> 
> What have you guys been doing for 4 years? 'Styling'? This framework is just a toy, the multiplatform promise is still a lie, and working on anything more interesting than trivial news/blog/reading apps is currently not worth it.

Are you serious, guy? I understand you're angry, but this is a complex open-source project. There are a ton of things to do or fix, as you may know in software development we need to prioritize. If you feel that it is too slow, you can try to contribute.

I'm waiting for this feature too. You can see that it as been prioritize.

**Comment by teewhydope** [comment]
> Absolutely dreadful.
> 
> This framework has been in development since 2020, and yet something as basic as OnDragListener with DragEvents for Desktop is missing. Implementing drag-and-drop on Compose Desktop is an absolute nightmare, and something as simple as a jigsaw puzzle results in convulted, terrible code to maintain.
> 
> What have you guys been doing for 4 years? 'Styling'? This framework is just a toy, the multiplatform promise is still a lie, and working on anything more interesting than trivial news/blog/reading apps is currently not worth it.

You sound entitled.

**Comment by tunjid** [comment]
Do you have a contribution guide? I wrote the `DragAndDropSource` and `DragAndDropTarget` implementation for Android and would like to add the desktop one.

**Comment by g3th** [comment]
> Do you have a contribution guide? I wrote the `DragAndDropSource` and `DragAndDropTarget` implementation for Android and would like to add the desktop one.

It would be great if you could speed up proceedings, although drag and drop is still perfectly implementable with ```pointerInput``` ```detectDragGestures``` and state holders, like compositionLocalOf. It is just more code to implement drag and drop without something like ```View.DragListener``` for desktop.

I hope these features come soon.

**Comment by tunjid** [comment]
@igordmn I'm familiar with using `repo` to contribute to androidx, is the same process used for the multiplatform fork? I just need to checkout the multiplatform branch?

**Comment by igordmn** [comment]
> @igordmn I'm familiar with using repo to contribute to androidx

https://github.com/JetBrains/compose-multiplatform-core doesn't use/require `repo`. You just clone it, open in IDEA/Android Studio, and make a PR via GitHub.

**Comment by gochev** [comment]
[g3th](https://github.com/g3th) is there a basic guide/example how to implement it via pointerInput ? I am migrating an android jetpack compose project to kotlin multiplatform compose and this is a huge blocker.

**Comment by gochev** [comment]
Ok I guess you meant this ; 
```
.pointerInput(Unit) {
                        detectDragGestures { change, dragAmount ->
                            change.consume()
                            offsetX += dragAmount.x
                            offsetY += dragAmount.y
                        }
                    }
```

which is fine and works but in this case you cannot drag the composable outside of the surrounding composable.. if you want to drag and drop into a target somewhere else like explained here : https://canopas.com/how-to-drag-and-drop-using-modifier-drag-and-drop-source-target-jetpack-compose its not possible

**Comment by g3th** [comment]
> Ok I guess you meant this ;
> 
> ```
> .pointerInput(Unit) {
>                         detectDragGestures { change, dragAmount ->
>                             change.consume()
>                             offsetX += dragAmount.x
>                             offsetY += dragAmount.y
>                         }
>                     }
> ```
> 
> which is fine and works but in this case you cannot drag the composable outside of the surrounding composable.. if you want to drag and drop into a target somewhere else like explained here : https://canopas.com/how-to-drag-and-drop-using-modifier-drag-and-drop-source-target-jetpack-compose its not possible

Hi gochev,

I am not sure I have understood what you mean correctly.

It is possible to create an event listener without using these newly implemented modifiers ```dragAndDropSource``` and ```dragAndDropTarget```; I have done this using a state holder in a "match the shape" game. These values are held and passed between composable via ```compositionLocalOf```, so that recomposition can occur. https://github.com/MatthiasKerat has implemented a similar example very efficiently. However, the code is convoluted and it would be much simpler to do using ```Modifier.dragAndDropTarget```. It is also tricky to pass values between composables, as the docs indicate composables should be free of side-effects unless there are particular cases (i.e. in the case of ```state hoisting```.

If you meant accepting drag and drop events which begin from outside the GUI (i.e. dropping a desktop textfile into your GUI, like you would drop into your browser) then I am not sure it is possible yet.

**Comment by igordmn** [comment]
The rough plan is to add this in the 1.7 release (1-3 months after the Jetpack Compose 1.7 release), but it can be available some time before that in a dev version, when it is ready.

No promises, as there are a lot of uncertainties.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4235">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
