### ISSUE TITLE
DialogWindow add alwaysOnTop

### ISSUE THREAD

**Issue by lizhongyue248** [JetBrains/compose-multiplatform#4238]
In my application, I need to build a main window without icons on the taskbar, so I chose to use `DialogWindow`. But now he cannot stay at the top level and will be overwritten by other application windows. We hope to add an `alwaysOnTop` attribute to provide this feature. Just like `Window`, I can control it.

This feature is very practical for most utility applications and is not difficult to modify. Currently, my solution is to copy a copy of the DialogWindow source code and manually add this attribute. But I don't think this is a recommended solution.
```
@Composable
fun MyDialogWindow(
  // ......
  enabled: Boolean = true,
  focusable: Boolean = true,
  alwaysOnTop: Boolean = false,  // add this... 
  // ......
) {
  // ......
  val currentOnCloseRequest by rememberUpdatedState(onCloseRequest)
  val currentOnAlwaysOnTop by rememberUpdatedState(alwaysOnTop)  // add this

  // .....
  DialogWindow(
    // ......
      update = { dialog ->
        updater.update {
          set(currentTitle, dialog::setTitle)
          set(currentIcon, dialog::setIcon)
          set(currentUndecorated, dialog::setUndecoratedSafely)
          set(currentTransparent, dialog::isTransparent::set)
          set(currentResizable, dialog::setResizable)
          set(currentEnabled, dialog::setEnabled)
          set(currentFocusable, dialog::setFocusableWindowState)
          set(currentOnAlwaysOnTop, dialog::setAlwaysOnTop)  // add this
        }
       // ......
    }
    // ......
  )
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4238">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
