### ISSUE TITLE
[1.6.0-beta02] Allow camelCase strings ids

### ISSUE THREAD

**Issue by Knoxvillekm** [JetBrains/compose-multiplatform#4241]
**Describe the bug**
Allow camelCase strings ids.

**Affected platforms**
- All

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-beta02

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Add line to strings.xml: `<string name="appName">App name</string>`
2. This generate Res.string.appname
3. Add `Text(text = stringResource(Res.string.appname))` to screen
4. Run app
5. See error: `String ID="appname" is not found!`

**Expected behavior**
Android strings allow camelCase in id.

I'm porting translations from json, what about dot support?
`<string name="app.name">App name</string>`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4241">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
