### ISSUE TITLE
After removing `resources` dependency, project doesn't compile

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4242]
Compose 1.6.0-beta02

1. use a project where resources are applied:
```
implementation(compose.components.resources)
```
2. build the project
3. remove the dependency:
```
//implementation(compose.components.resources)
```
4. build the project

**Actual**
Compilation error:
```
/Users/igor/Projects/compose-multiplatform-template/shared/build/generated/compose/resourceGenerator/kotlin/myapplication/shared/generated/resources/Res.kt:2:3: error: An annotation argument must be a compile-time constant
/Users/igor/Projects/compose-multiplatform-template/shared/build/generated/compose/resourceGenerator/kotlin/myapplication/shared/generated/resources/Res.kt:2:17: error: Unresolved reference: compose
...
```

**Expected**
No compilation errors, generated classes are removed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4242">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
