### ISSUE TITLE
Uninstalling software will delete files by mistake

### ISSUE THREAD

**Issue by tangshimin** [JetBrains/compose-multiplatform#4245]
**Describe the bug**
When installing the software, if you want to change the default installation location, select the folder and forget to create a new folder for the software  then click OK to install the software.

When uninstalling the software, all files in the installation location will be deleted.

**Affected platforms**
- Desktop

**Versions**
- OS version : Windows

**To Reproduce**
1. Create a new folder named `Program Files Test` in D drive, and then create a new folder named `JetBrains` in In `Program Files Test` .
2. Create an msi installation package for [Notepad](https://github.com/JetBrains/compose-multiplatform/tree/master/examples/notepad), then open notepad.msi and click Next, then click Change, then select `D:\Program Files Test\` and click Next, then click Yes in the confirmation dialog. Finally, click Install.
3. Uninstall the notepad you just installed, and JetBrains will be deleted from the `Program Files Test` folder.

**Expected behavior**
1. The JetBrains folder should not be deleted.
2. After selecting the installation directory `D:\Program Files Test\`, the Installer should change the installation directory to `D:\Program Files Test\Notepad\`.
When installing VLC, if you select the installation directory to `D:\Program Files Test\` the installer will automatically change the installation directory to `D:\Program Files Test\VLC\`.

**Comment by terrakok** [comment]
On the second step of the installation you select a destination dir for the app. And the dir will be deleted during an uninstallation. It is how it standard works. To change the logic mean to change standard logic of [the jpackage](https://docs.oracle.com/en/java/javase/20/docs/specs/man/jpackage.html)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4245">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
