### ISSUE TITLE
iPhone Pro version with dynamic island status bar height issue

### ISSUE THREAD

**Issue by HahhVwgwg** [JetBrains/compose-multiplatform#4248]
![image](https://github.com/JetBrains/compose-multiplatform/assets/49427678/c196c79a-76dc-41f9-be8a-f3f64b2e1d45)
There is this space between the status bar and the safe area in iPhone Pro versions

**Affected platforms**
- iOS

**To Reproduce**
1. Use this code to change status bar color  
![image](https://github.com/JetBrains/compose-multiplatform/assets/49427678/6018b4f2-22e3-4109-8ae0-efe6280372c8)
![image](https://github.com/JetBrains/compose-multiplatform/assets/49427678/d4ebc60d-d557-4b28-a952-0963ad332fba)

**Expected behavior**
Change status bar color without showing any space between ContentView and StatusBarView

**Additional context**
I found a solution in native swift. Can anyone help to convert this to kotlin? 
![image](https://github.com/JetBrains/compose-multiplatform/assets/49427678/0008d458-2864-4b7e-b7b1-c76b0c985b52)

**Comment by HahhVwgwg** [comment]
I was able to fix without using **.ignoresSafeArea()**. Just use this method to change StatusBarColor 
![image](https://github.com/JetBrains/compose-multiplatform/assets/49427678/82d3587e-151c-4e34-8dd5-2168298f5080)
![image](https://github.com/JetBrains/compose-multiplatform/assets/49427678/c1db3bca-7413-4286-9002-06952798f4a6)
![image](https://github.com/JetBrains/compose-multiplatform/assets/49427678/d21cdbdc-b950-4e29-940d-4d61b8ec91f2)

**Comment by HahhVwgwg** [comment]
@JurajBegovac You can find solution to your problem here

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4248">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
