### ISSUE TITLE
Add options to add a Windows manifest file to executables

### ISSUE THREAD

**Issue by Revxrsal** [JetBrains/compose-multiplatform#4251]
Hello o/
In Windows, executable applications can specify a [manifest](https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests), which lets them customize many things regarding the app, including high-DPI scale settings, requesting admin privileges, modern dialog boxes, etc.

The manifest is an XML file, and it can be injected or customized into any exe using Microsoft's command line tool [mt.exe](https://learn.microsoft.com/en-us/windows/win32/sbscs/mt-exe) (which comes with the Windows SDK).

I wonder if there is any way this can be integrated into Compose Desktop apps. This would fit nicely in the `WindowsPlatformSettings` DSL:
```build.gradle.kts
compose.desktop {
    application {
		// ...
        nativeDistributions {
			// ...
            windows {
				// ...
                manifestFile.set(project.file("app.manifest"))
            }
        }
    }
}
```

**Comment by iamcalledrob** [comment]
This would be very useful for my projects, too.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4251">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by mahozad** [comment]
Check out [this Gradle plugin](https://github.com/mahozad/compose-exe-manifest).

See the README for an example manifest file that makes the app exe start as admin.
