### ISSUE TITLE
Enter/Return doesn't work as expected in a single line TextField

### ISSUE THREAD

**Issue by luludevmuniz** [JetBrains/compose-multiplatform#4255]
**Describe the bug**
After setting the TextField parameter singleLine to true or maxLines to 1 and writing some text in it, pressing Enter/Return causes the cursor to return to the start of the TextField and the user can write some invisible text behind the text.

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*:  1.9.21
- Compose Multiplatform version*: 1.6.0-beta02

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Go to kmp.jetbrains.com 
2. Selected Wasm option 
3. Download the project
4. Replace the App() function for the codesnippet below
5. Run the app in your browser
6. Write some text in the TextField
7. Press Enter/Return
8. Text something and then you'll notice it will take a few deletes to reach the original text again.

Code Snippet:

```
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material.MaterialTheme
import androidx.compose.material.OutlinedTextField
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

@Composable
fun App() {
    MaterialTheme {
        var value by remember { mutableStateOf("") }
            OutlinedTextField(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 16.dp),
                value = value,
                onValueChange = {
                    value = it
                },
                singleLine = true
            )
        }
}

```

**Expected behavior**
Don't allow the cursor to go back to the start of the composable.

**Additional Context**
For some reason, the cursor is vanishing when I write the first text, so it's harder to see.

**Comment by eymar** [comment]
pressing Enter causes the cursor to go on the next line (TextField just doesn't show it)

adding a println shows that the actual text value has more lines
```
onValueChange = {
                value = it
                println("Value = $it")
            },
```

On desktop, the cursor never gets removed from the first (single) line.

**Comment by luludevmuniz** [comment]
Could not reproduce it on [1.6.10-beta02](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10-beta02).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4255">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
