### ISSUE TITLE
 When only on the desktop, generateComposeResClass cannot generate Res.drawable

### ISSUE THREAD

**Issue by lizhongyue248** [JetBrains/compose-multiplatform#4256]
**Describe the bug**

The application I developed only needs to support the desktop, so there is no dependency on mobile platforms such as Android. The directory structure of `composeResources` is as follows:

![image](https://github.com/JetBrains/compose-multiplatform/assets/29678316/eb2224fb-5700-4095-ae82-518c3e0e567a)

The generated `Res.kt` is as follows

```kotlin
@file:OptIn(
  org.jetbrains.compose.resources.InternalResourceApi::class,
  org.jetbrains.compose.resources.ExperimentalResourceApi::class,
)

package portview.composeapp.generated.resources

import kotlin.ByteArray
import kotlin.OptIn
import kotlin.String
import org.jetbrains.compose.resources.ExperimentalResourceApi
import org.jetbrains.compose.resources.readResourceBytes

@ExperimentalResourceApi
internal object Res {
  /**
   * Reads the content of the resource file at the specified path and returns it as a byte array.
   *
   * Example: `val bytes = Res.readBytes("files/key.bin")`
   *
   * @param path The path of the file to read in the compose resource's directory.
   * @return The content of the file as a byte array.
   */
  public suspend fun readBytes(path: String): ByteArray = readResourceBytes(path)
}

```
There is no relevant code for `Res.drawable`, but when I built multiple platforms (including Android and other mobile devices), it was successful.

```kotlin
@file:OptIn(
  org.jetbrains.compose.resources.InternalResourceApi::class,
  org.jetbrains.compose.resources.ExperimentalResourceApi::class,
)

package timeline.composeapp.generated.resources

import kotlin.ByteArray
import kotlin.OptIn
import kotlin.String
import org.jetbrains.compose.resources.DrawableResource
import org.jetbrains.compose.resources.ExperimentalResourceApi
import org.jetbrains.compose.resources.readResourceBytes

@ExperimentalResourceApi
internal object Res {
  /**
   * Reads the content of the resource file at the specified path and returns it as a byte array.
   *
   * Example: `val bytes = Res.readBytes("files/key.bin")`
   *
   * @param path The path of the file to read in the compose resource's directory.
   * @return The content of the file as a byte array.
   */
  public suspend fun readBytes(path: String): ByteArray = readResourceBytes(path)

  public object drawable {
    public val icon: DrawableResource = get_icon()

    public val loading: DrawableResource = get_loading()

    public val logo_ghost: DrawableResource = get_logo_ghost()
  }
}

private fun get_icon(): DrawableResource = org.jetbrains.compose.resources.DrawableResource(
  "drawable:icon",
    setOf(
      org.jetbrains.compose.resources.ResourceItem(setOf(), "drawable/icon.png"),
    )
)

private fun get_loading(): DrawableResource = org.jetbrains.compose.resources.DrawableResource(
  "drawable:loading",
    setOf(
      org.jetbrains.compose.resources.ResourceItem(setOf(), "drawable/loading.png"),
    )
)

private fun get_logo_ghost(): DrawableResource = org.jetbrains.compose.resources.DrawableResource(
  "drawable:logo_ghost",
    setOf(
      org.jetbrains.compose.resources.ResourceItem(setOf(), "drawable/logo-ghost.png"),
    )
)
```

How to generate it when there are only desktop related dependencies?

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*:  1.9.22
- Compose Multiplatform version*:  1.6.0-beta02
- OS version(s)* (required for Desktop and iOS issues):  Windows 11
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues):  17

**To Reproduce**
1. Go to https://kmp.jetbrains.com/ genernate only desktop project.
2. Upgrade `kotlin` and  `compose multiplatform` version.
3. Add `composeResources/drawable` dir and `image` files.
4. run `./gradlew generateComposeResClass`.
5. Generate `Res.kt` but not include `Res.drawable`.

**Expected behavior**
Generate `Res.kt` and include `Res.drawable` for desktop platform.

**Comment by terrakok** [comment]
you are suppose to place your resources in `src/commonMain/composeResources` directory when you apply the Kotlin Multiplatform Gradle plugin. It doesn't matter how many targets you have.

**Comment by terrakok** [comment]
If you want to develop a JVM only app, you can use the Kotlin Jvm Gradle plugin instead.
then composeResources may be in `src/main/composeResources`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4256">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
