### ISSUE TITLE
Some DatePicker and TimePicker color values cannot be modified.  

### ISSUE THREAD

**Issue by xavimolloy** [JetBrains/compose-multiplatform#4259]
**Describe the bug**

We are implementing our own custom calendar with some specific colors that differ from our theme but some colors from datePicker and TimePicker do not seem to be applied. 

Example: 
![image](https://github.com/JetBrains/compose-multiplatform/assets/44061143/5e09d080-0f4c-4565-a658-381788a1cfa7)
we would like the selected day text to be white
selectedDayContentColor in TimePickerDefaults.color() is not modified when used, neither is selectedDayContainerColor
all the disabledColors don't seem to be workink either. 

the latter can be modified with a workaround to improve visibility by overriding the theme but is not an ideal solution as it also modifies other colors like the border and cursor of the input field in the calendar when focused.
![image](https://github.com/JetBrains/compose-multiplatform/assets/44061143/2e5a8d39-37fa-45ef-a1b7-1493f5a675f8)
![image](https://github.com/JetBrains/compose-multiplatform/assets/44061143/ca5f4d1b-76e6-497f-8d14-0f917e0c657a)
issue also occurs with TimePicker periodSelectorSelectedContentColor
they seem to be detecting the 
**Affected platforms**
Select one of the platforms below:
- All
- Desktop
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library
- iOS
- Other

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.5.12
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
                DatePicker(
                    state = rememberDatePickerState(),
                    colors =  DatePickerDefaults.colors(
                        selectedDayContainerColor = Color.Red,
                        selectedDayContentColor = Color.Red,
                    )
                )

**Expected behavior**

when setting a color it should be set correctly

**Screenshots**

**Additional context**

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4259">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
