### ISSUE TITLE
[WEB] Resize a window causes freeze

### ISSUE THREAD

**Issue by jershell** [JetBrains/compose-multiplatform#4260]
**Describe the bug**
Resize a window causes freeze

**Affected platforms**
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API

Versions
Compose Multiplatform version*: 1.6.0-* latest master

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Go to js demo
2. run js demo in google chrome
3. resize window

**Expected behavior**
Window resized

**temporary workaround**
if we comment out this line, demo continue to work without error and keep the old size
https://github.com/JetBrains/compose-multiplatform-core/blob/5b36158c2301a10cfdb13ce7603eca9e0dc5f45f/compose/ui/ui/src/jsWasmMain/kotlin/androidx/compose/ui/window/ComposeWindow.js.kt#L195

**Additional context**
skiko.js:1 WebGL: INVALID_OPERATION: delete: object does not belong to this context
![image](https://github.com/JetBrains/compose-multiplatform/assets/1238301/c63affae-6a9c-4c60-96e6-fb98e0b2899a)

**Comment by terrakok** [comment]
duplicates https://github.com/JetBrains/compose-multiplatform/issues/4254

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4260">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
