### ISSUE TITLE
[Res] Font files duplicates in Android apk

### ISSUE THREAD

**Issue by xiaozhikang0916** [JetBrains/compose-multiplatform#4266]
**Describe the bug**
The font files bundled in by composeResource shows in `app.apk/font` and `app.apk/assets/font` in the assembled apk file.

**Affected platforms**
Android only by introduced by compose resource.

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-beta02

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Go to 'compose-multiplatform/components/resources'
2. `:resources:demo:androidApp:assemble`
3. Unzip the generated apks and check files

**Expected behavior**
Font files should only be in `assets/font`

**Additional context**
As workaround, I can add the following configuration in androidApp's `build.gradle.kts` but I believe it should be achieved by the compose resources task itself.

```kts
    packaging {
        resources {
            excludes += "/font/**"
        }
    }
```

**Comment by terrakok** [comment]
It is by design. Because Android can build a font only from assets but we have an API to read files by a resource path. So, at the moment we need it in two places

**Comment by xiaozhikang0916** [comment]
It should be a concern of the app size, any plan for the optimization?

**Comment by terrakok** [comment]
Yes, the Android Resources has own benefits but it is the platform specific solution. We implement a different thing with the multiplatform support.

> Fonts are duplicated  

No. The current issue shows that.

All your points are about android resources. It cannot be achieved on other platforms. If you need it for android only you may continue use android only resources.

We will continue work on resource optimizations. For example, xml values are already converted to optimized format in the application.

**Comment by cbeyls** [comment]
I was assuming this Resources library creates native resources on Android like Moko Resources so I was a bit surprised to discover that it wasn't the case. I assume this is an architectural limitation and if the performance is good enough and resources are no more duplicated on Android it's fine.

There is still room for improvement though. I saw that the resources are loaded using `ClassLoader.getResourceAsStream()` which causes [slow-downs and high memory usage on Android, especially for big APK files](https://medium.com/@NimbleDroid/why-is-classloader-getresourceasstream-so-slow-in-android-5f7c8583b63). So on Android I would recommend putting all resources in the assets folder and loading them using `AssetManager`.

**Comment by terrakok** [comment]
I checked the logic on both Android versions (API 24 and 33).
I haven't noticed the memory and start time problems with a 253 MB APK.
I think it was the problem of previous android versions and it doesn't exist anymore.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4266">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
