### ISSUE TITLE
Key mapping for NumPadDecimal

### ISSUE THREAD

**Issue by aharnisch** [JetBrains/compose-multiplatform#4270]
**Describe the bug**
androidx.compose.ui.input.key.Key doesn't provide a constant for NumPadDecimal.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0 
- Compose Plugin version: 1.5.12
- OS version(s)* (required for Desktop and iOS issues): Win11
- OS architecture (x86 or arm64): x86_64
- JDK (for desktop issues): 21.0.1

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Press the decimal key on numpad
```
fun main() = application {
    minimalApp()
}

@Composable
fun ApplicationScope.minimalApp() {
    Window(onCloseRequest = ::exitApplication,
        onPreviewKeyEvent = {
        if (it.type == KeyEventType.KeyUp) {
            when (it.key) {
                Key.Delete -> println("not triggered") // alternate label on the key
                Key.NumPadDot -> println("not triggered")
                Key.NumPadComma -> println("not triggered")
                Key(KeyEvent.VK_DECIMAL, KeyEvent.KEY_LOCATION_NUMPAD) -> println("Is triggered")
                else -> println(it)
            }
        }
        true
    }) { }
}
```

**Expected behavior**
Possible solutions:
1. Add new constant NumPadDecimal
2. Add new constant NumPadDelete
3. NumPadDot or NumPadComma should be triggered (dependend on keyboard layout)

**Screenshots**
German numpad:
![Numeric_keypad_of_a_German_keyboard_(about_2020)](https://github.com/JetBrains/compose-multiplatform/assets/8173334/8893434c-f485-46ab-99fc-fa6f0622e2a5)

**Additional context**
- German operation system
- German keyboard

**Comment by aharnisch** [comment]
Duplicate to #4211

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4270">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
