### ISSUE TITLE
EXC_RESOURCE (RESOURCE_TYPE_MEMORY: high watermark memory limit exceeded)

### ISSUE THREAD

**Issue by jbruchanov** [JetBrains/compose-multiplatform#4273]
**Describe the bug**
App crash with
Log: `Process finished with exit code 137 (interrupted by signal 9: SIGKILL)`
Debugger in Android studio: `EXC_RESOURCE (RESOURCE_TYPE_MEMORY: high watermark memory limit exceeded) (limit=2867 MB)`

**Affected platforms**
- iOS (real iphone 15, ios 17.1, simulator works fine)

**Versions**
compose = "1.6.0"
compose-plugin = "1.5.12"
kotlin = "1.9.22"

**To Reproduce**
1. repo https://github.com/jbruchanov/KMPPotentialMemLeak
2. run the app on real device (probably needs to fix/reselect signing certificate in xcode)
3. be sure you have some high resolution images (taken from camera in my case)
4. click on "click me" button, pick 3 photos, try to scroll horizontally
5. repeat 4 (in my case 2nd pick was always maximum, if 1st pick was successful)

**Expected behavior**
App doesn't crash

**Additional context**
My background is Android, so maybe my thinking about memory resources in iOS is incorrect.

The number of photos in step 4 doesn't have to be exactly 3, sometimes it's crashing right away for 1st attempt of 3.
Sometimes 2nd pick works and it's crashing during the horizontal scroll.
And the **crash during the scrolling is main reason why I think it might be potentially somewhere a memleak**.
Though, I couldn't reproduce the issue on simulator, loaded approx 1.2GB of image bitmaps, but I'm not sure how much different the ios simulator is, in terms of real device resources and the host mac resources (using MacMini M2Pro 16GB mem).

The code  is using iOS `PHPickerViewController` and showing the images in the app. 
In my case I loaded 
```
1st pick
RawData:2308kB, ImageMemSize:47628kB, Resolution:3024x4032 
RawData:1447kB, ImageMemSize:47628kB, Resolution:3024x4032 
RawData:3479kB, ImageMemSize:95587kB, Resolution:4284x5712 
2nd pick
RawData:3723kB, ImageMemSize:95587kB, Resolution:5712x4284 
RawData:4988kB, ImageMemSize:95587kB, Resolution:5712x4284 
RawData:3831kB, ImageMemSize:95587kB, Resolution:4284x5712 
```
Which is roughly if I'm not mistaken 500megs of memory needed to have the images as bitmaps in memory, which I think should be OK on iOS.
Deffo it's far from error message `...(limit=2867 MB)`.

I'm attaching saved [stack](https://github.com/JetBrains/compose-multiplatform/files/14220222/stack.txt) from android studio (not sure how to get better one), because it's not being printed out as regular crash for example with NullPointerException.

The debugger stops on this [line](https://github.com/JetBrains/skiko/blob/master/skiko/src/commonMain/kotlin/org/jetbrains/skia/Canvas.kt#L571) in `org.jetbrains.skiko:skiko-iosx64:0.7.85.4` module. 

It's somewhere in the middle of stack records in the android studio stack window, so not totally sure how relevant it is.

**Comment by elijah-semyonov** [comment]
Thanks for the report, I'll have a look

**Comment by elijah-semyonov** [comment]
I didn't manage to find a memory leak. What is certain is that the memory pressure is simply too high. 
What I found is:
1. NSData->ByteArray memcpy is not optimal, we should add Skiko API to create an ImageBitmap from raw pointers and pass NSData contents explicitly.
2. You decompress the image [twice](https://github.com/jbruchanov/KMPPotentialMemLeak/blob/1c1321cde7a974f29e25979fa636bd23d62a914f/composeApp/src/commonMain/kotlin/App.kt#L61-L63). It still lingers in the memory before next GC call.
3. You constantly keep all the full-size images in the memory, even if they are not visible on the screen.

You need to:
1. Downscale rasterised uncompressed images and cache the thumbnails on persistent storage to avoid loading full-scale picture again when you need those thumbnails.
2. Develop a strategy to discard images, that are not visible on the screen and only keep their identities to recover the thumbnails.

**Comment by jbruchanov** [comment]
@elijah-semyonov 
2) ah right, just for logging, but I guess it shouldn't be necessary the issue for showing the edge case...
3) I know this is far from optimal solution and it's nonsense to render images with this resolution just like that with size of 150.dp, but makes easier to hit the edge...

Would there be any explanation, why you can let's say load 6 images, but it is crashing just during the horizontal scroll due to the memory limits, that's the main thing I have hard time to understand...
Is there something way different what's happening during scrolling images android/others ?

**Comment by jbruchanov** [comment]
Even if I get rid of the the redundant image allocation for point 3, 
it's crashing with exactly same reason... I just need to be scrolling for ~10+ seconds...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4273">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
