### ISSUE TITLE
Bug: Kotlin Multiplatform Dependencies

### ISSUE THREAD

**Issue by AbdhilahiRWabwire** [JetBrains/compose-multiplatform#4276]
# Bug

Dependencies declared in Kotlin sourceSets cannot resolve dependencies for Gradle Tasks. Standard dependency declaration does not have this issue.

## Broken

```gradle
sourceSets {
   val desktopMain by getting
        
   androidMain.dependencies {

   }
   commonMain.dependencies {

   }
   desktopMain.dependencies {

   }
   iosMain.dependencies {

   }
   jsMain.dependencies {

   }
}
```

## Working

```gradle
dependencies {

}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4276">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
