### ISSUE TITLE
IOS build fails because of  org.jetbrains.compose.annotation-internal:annotation dependency

### ISSUE THREAD

**Issue by binishmatheww** [JetBrains/compose-multiplatform#4277]
I am unable to build my KMP app for IOS.
I am getting this error:
Could not find "org.jetbrains.compose.annotation-internal:annotation" in [/Users/binishmathew/binishmatheww/Kadalas, /Users/binishmathew/.konan/klib, /Users/binishmathew/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.22/klib/common, /Users/binishmathew/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.22/klib/platform/ios_simulator_arm64]

My common.gradle:
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    kotlin("multiplatform")
    id("com.android.library")
    id("kotlin-parcelize")
    kotlin("plugin.serialization") version "1.9.22"
    id("app.cash.sqldelight")
    id("dev.icerock.mobile.multiplatform-resources")
    id("org.jetbrains.compose") version "1.5.12"
}

@OptIn(org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi::class)
kotlin {
    kotlin.applyDefaultHierarchyTemplate()

    androidTarget {
        kotlin {
            jvmToolchain(19)
        }
    }

    jvm()

    val xcFramework = XCFramework("common")
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach {
        it.binaries.framework {
            baseName = "common"
            //isStatic = true // Has some issues related to lsqlite3. https://github.com/cashapp/sqldelight/issues/1442
            isStatic = false
            linkerOpts.add("-lsqlite3")
            xcFramework.add(this)
            export(libs.mocko.resources)
            export(libs.mocko.graphics)
            export(libs.decompose)
            export(libs.mvikotlin)
            export(libs.mvikotlin.main)
            export(libs.essenty.lifecycle)
        }
    }

    sourceSets {
        val commonMain by getting {
            sourceSets["commonMain"].resources.srcDirs("src/commonMain/resources/")
            dependencies {
                api(compose.runtime)
                api(compose.foundation)
                api(compose.material)
                api(libs.kotlinx.coroutines.core)
                api(libs.ktor.client.core)
                api(libs.ktor.client.content.negotiation)
                api(libs.ktor.serialization.kotlinx.json)
                api(libs.sqldelight.runtime)
                api(libs.sqldelight.coroutines.extensions)
                api(libs.kotlinx.datetime)
                api(libs.kotlinx.serialization.json)
                api(libs.mocko.resources)
                api(libs.mocko.resources.compose)
                api(libs.mocko.graphics)
                api(libs.decompose)
                api(libs.decompose.compose)
                api(libs.essenty.lifecycle)
                api(libs.reaktive)
                api("io.coil-kt.coil3:coil:3.0.0-SNAPSHOT")
                api("io.coil-kt.coil3:coil-compose:3.0.0-SNAPSHOT")
                api("io.coil-kt.coil3:coil-network:3.0.0-SNAPSHOT")
                api("com.mohamedrejeb.calf:calf-file-picker:0.3.0")
                api("com.squareup.okio:okio:3.6.0")
            }
        }
        val commonTest by getting {
            dependencies {
                api(kotlin("test"))
                api(libs.mocko.resources.test)
            }
        }
        val nativeMain by getting{
            dependencies {
                api(libs.sqldelight.native.driver)
            }
        }
        val nativeTest by getting {
            dependencies {

            }
        }
        val jvmMain by getting {
            dependsOn(commonMain)
            dependencies {
                api(libs.kotlinx.coroutines.swing)
                api(libs.ktor.client.okhttp)
                api(libs.ktor.client.serialization.jvm)
                api(libs.sqldelight.runtime.jvm)
                api(libs.sqldelight.sqlite.driver)
                api(libs.decompose.jvm)
                api(libs.mocko.resources)
                api(libs.mocko.resources.compose)
            }
        }
        val jvmTest by getting {
            dependencies {
                api(libs.junit)
                api(libs.mocko.resources.test)
            }
        }
        val androidMain by getting {
            dependsOn(commonMain)
            dependencies {
                api(libs.compose.ui)
                api(libs.compose.ui.tooling)
                api(libs.compose.ui.tooling.preview)
                api(libs.compose.foundation)
                api(libs.compose.material)
                api(libs.activity.compose)
                api(libs.ktor.client.android)
                api(libs.sqldelight.android.driver)
                api(libs.mvikotlin.logging)
                api(libs.mvikotlin.timetravel)
                api(project.dependencies.platform("com.google.firebase:firebase-bom:32.4.0"))
                api("com.google.firebase:firebase-messaging")
                api("com.google.firebase:firebase-installations")
            }
        }
        val androidUnitTest by getting {
            dependencies {

            }
        }
        val androidInstrumentedTest by getting {
            dependencies {

            }
        }
        val iosX64Main by getting
        val iosArm64Main by getting
        val iosSimulatorArm64Main by getting
        val iosMain by getting {
            dependsOn(commonMain)
            iosX64Main.dependsOn(this)
            iosArm64Main.dependsOn(this)
            iosSimulatorArm64Main.dependsOn(this)
            dependencies {
                api(libs.ktor.client.darwin)
                api(libs.sqldelight.native.driver)
            }
        }
        val iosTest by getting {
            dependencies {

            }
        }
    }
}

android {
    namespace = "x.y.z"
    compileSdk = 34
    defaultConfig {
        minSdk = 23
    }
}
dependencies {
    implementation(libs.androidx.annotation.jvm)
}

sqldelight {
    databases{
        create("KadalasDatabase"){
            packageName.set("x.y.z.sqldelight")
            verifyMigrations = true
            //dialect("app.cash.sqldelight:postgres-dialect:2.0.1")
            dialect("app.cash.sqldelight:sqlite-3-24-dialect:2.0.1")
        }
    }
    linkSqlite = true
}

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*:  1.9.22
- Compose Multiplatform version*:  1.5.12
- OS version(s)* (required for Desktop and iOS issues): 17
- OS architecture (x86 or arm64): arm64

**Comment by dima-avdeev-jb** [comment]
Thanks for this Issue.
Can you please provide minimal reproducible sample project on GitHub?

**Comment by eygraber** [comment]
@dima-avdeev-jb here's a failure in my smallish project due to this https://github.com/eygraber/vice/actions/runs/7893533731

**Comment by eygraber** [comment]
Actually my error is slightly different (`org.jetbrains.compose.collection-internal:collection`) and I'm using 1.6.0-rc01 but otherwise same concept.

**Comment by chrisbanes** [comment]
Seeing the same thing in [Tivi](https://github.com/chrisbanes/tivi). The update to 1.6.0-rc01 is failing with:

> Error: error: Could not find "org.jetbrains.compose.annotation-internal:annotation" in [/Users/runner/work/tivi/tivi, /Users/runner/.konan/klib, /Users/runner/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.22/klib/common, /Users/runner/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.22/klib/platform/ios_arm64]

**Comment by garretyoder** [comment]
Confirmed here as well.

**Comment by igordmn** [comment]
It happens because some library depends on `1.6.0-beta02`, which isn't binary compatible with `1.6.0-rc01`

Looking at the dependencies of `tivi`, I found:
```
|    +--- dev.chrisbanes.haze:haze:0.5.1
|    |    +--- org.jetbrains.compose.ui:ui:1.6.0-beta02 -> 1.6.0-rc01 (*)
```
Will upgrading `dev.chrisbanes.haze:haze:0.5.1` to Compose `1.6.0-rc01` or using the older version that depends on `1.5.12` help?

**Comment by chrisbanes** [comment]
Ah makes sense. I'm about to upgrade Haze anyway 👌

**Comment by eygraber** [comment]
I had a similar situation with a dependency. Updated it and the error has gone away.

**Comment by mahramane** [comment]
Hi 
I also have the same problem with 1.6.0-rc01 kotlin multiplatform when run ios.

```
error: Could not find "org.jetbrains.compose.annotation-internal:annotation" in [/Volumes/Aino/Aino, /Users/mohammad/.konan/klib, /Users/mohammad/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.22/klib/common, /Users/mohammad/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.22/klib/platform/ios_simulator_arm64]
Could not find "org.jetbrains.compose.annotation-internal:annotation" in [/Volumes/Aino/Aino, /Users/mohammad/.konan/klib, /Users/mohammad/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.22/klib/common, /Users/mohammad/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.22/klib/platform/ios_simulator_arm64]Compilation finished with errors
```

**Comment by igordmn** [comment]
> I also have the same problem with 1.6.0-rc01

The solution is to find the dependency that depend on `1.6.0-beta02` and downgrade it or ask the author of the library to upgrade it to `1.6.0-rc01`.

Added that in the [CHANGELOG](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-rc01).

**Comment by sureshmaidaragi1919** [comment]
@dima-avdeev-jb I am also facing the same issue in KMM project

settings.kt plugins
```

    plugins {
        val firebaseCrashlyticsVersion = extra["firebase.crashlytics.version"] as String
        val googleServicesVersion = extra["google.services.version"] as String

        id("org.jetbrains.compose").version("1.6.0-rc01")
        kotlin("jvm").version("1.9.20")
        kotlin("multiplatform").version("1.9.20")
        kotlin("android").version("1.9.20")
        id("com.android.application").version("8.0.2")
        id("com.android.library").version("8.0.2")
        id("com.google.gms.google-services").version(googleServicesVersion).apply(false)
        id("com.google.firebase.crashlytics").version(firebaseCrashlyticsVersion).apply(false)
    }
```

**Comment by MatkovIvan** [comment]
@sureshmaidaragi1919 

> The solution is to find the dependency that depend on 1.6.0-beta02 and downgrade it or ask the author of the library to upgrade it

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4277">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
