### ISSUE TITLE
[iOS][1.6.0-beta02] Wrong scroll behaviour of LazyColumn inside HorizontalPager

### ISSUE THREAD

**Issue by boiler23** [JetBrains/compose-multiplatform#4279]
**Describe the bug**
Overscrolling a LazyColumn inside a HorizontalPager to the top or bottom gets stuck in a weird position.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version: 1.9.22
- Compose Multiplatform version: 1.6.0-beta02
- OS version: iOS 17
- OS architecture: arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Compile and launch the app from this [repo](https://github.com/boiler23/lazy-column-issue)
2. Click on "Open list" in the app
3. Try to scroll the list upwards

4. See that the top item is stuck randomly on the screen.

**Expected behavior**
Once the scrolling is finished, the top item's position should return to the top.

**Screenshots**
https://github.com/JetBrains/compose-multiplatform/assets/215357/4ec6be9d-9967-497e-ae12-a67179942198

**Additional context**
The issue isn't reproduced on the stable version of Compose Multiplatform (1.5.12). On Android, everything also works fine.

Here is the problematic piece of code:
```
@OptIn(ExperimentalFoundationApi::class)
@Composable
fun MyView() = MyApplicationTheme {
    Surface(
        modifier = Modifier.fillMaxSize(),
        color = MaterialTheme.colorScheme.background
    ) {
        var currentPage by remember { mutableIntStateOf(0) }
        val pagerState = rememberPagerState(initialPage = currentPage, pageCount = { 2 })
        
        LaunchedEffect(currentPage) {
            pagerState.animateScrollToPage(currentPage)
        }
        
        HorizontalPager(
            pagerState,
            beyondBoundsPageCount = 1,
            userScrollEnabled = false,
        ) { page ->
            when (page) {
                0 -> FirstPage { currentPage = 1 }
                1 -> SecondPage()
            }
        }
    }
}

@Composable
private fun FirstPage(onOpenSecondPage: () -> Unit) = Box(Modifier.fillMaxSize()) {
    Button(onClick = onOpenSecondPage) {
        Text("Open list")
    }
}

@Composable
private fun SecondPage() {
    LazyColumn {
        for (i in 1..100) {
            item(key = i, contentType = i) {
                Text("Item $i", Modifier.fillMaxWidth().padding(8.dp))
            }
        }
    }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4279">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
