### ISSUE TITLE
Use immediate CoroutineDispatcher for Compose CoroutineScope

### ISSUE THREAD

**Issue by jeffdgr8** [JetBrains/compose-multiplatform#4280]
It would be helpful if the Compose `CoroutineScope`, accessible via `rememberCoroutineScope()`, used an [`immediate`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-main-coroutine-dispatcher/immediate.html) `CoroutineDispatcher`. This would allow `Flow`s to collect and emit synchronously with the UI, which is [a requirement for certain components, like `TextField`](https://medium.com/androiddevelopers/effective-state-management-for-textfield-in-compose-d6e5b070fbe5).

At the very least, if not immediate by default, it would be helpful to be able to reference an immediate version of the Compose dispatcher in order to use for synchronous state updating between coroutines.

[Related Slack thread.](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1707590794748829)

**Comment by m-sasha** [comment]
`rememberCoroutineScope` takes a `getContext` argument, allowing you to provide your own context:

```
fun main() = singleWindowApplication {
    Column {
        var textFieldValue by remember { mutableStateOf(TextFieldValue()) }
        TextField(
            value = textFieldValue,
            onValueChange = { textFieldValue = it }
        )

        val coroutineScope = rememberCoroutineScope(
            getContext = { Dispatchers.Unconfined }
        )

        Button(
            onClick = {
                println("Before launch")
                coroutineScope.launch {
                    println("In coroutine")
                }
                println("After launch")
            }
        ) {
            Text("Click me")
        }
    }
}
```

In general, for issues/questions that aren't specific to Compose *Multiplatform*, it's better to post them on the Google Jetpack Compose issue tracker.

**Comment by jeffdgr8** [comment]
Thanks @m-sasha. I created the issue here mostly because Compose desktop specifically has the problem that out of the box you don't have access to `Dispatchers.Main.immediate`. If the expectation is to add the `kotlinx-coroutines-swing` dependency, this isn't clear in the documentation that I've seen, only mentioned in the changelog [here](https://github.com/JetBrains/compose-multiplatform/blob/903a9bb8aa4cfd5576a7b13488be33cb02183d2a/CHANGELOG.md#api-changes-12).

But if the fact it doesn't use an immediate dispatcher by default comes from the upstream Jetpack Compose, that definitely makes sense to handle at that level.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4280">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
