### ISSUE TITLE
AlertDialog no work with ProvidableCompositionLocal

### ISSUE THREAD

**Issue by Gaubee** [JetBrains/compose-multiplatform#4281]
**Describe the bug**
AlertDialog no work with ProvidableCompositionLocal

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-beta02
- OS version(s)* (required for Desktop and iOS issues): 17.3
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
when `platformLayers = true`, ProvidableCompositionLocal will no working

Demo Code:
```kotlin
fun MainViewController() = ComposeUIViewController({
  platformLayers = true // now this is default setting
}) { App() }
```

```kotlin
val LocaleData = compositionLocalOf<String> {
  throw Exception("No Data")
}
@Composable
fun App() {
    CompositionLocalProvider(LocaleData provides "Gaubee") {
        AlertDialog(
          onDismissRequest = {
            showDialog = false
          },
          text = {
            Text("Hello ${LocaleData.current}") // Make Crash!!
          },
          buttons = {
            Button(onClick = {
              showDialog = false
            }) {
              Text("Exit")
            }
          }
        )
      }
}

```
[multi_layer-main.zip](https://github.com/JetBrains/compose-multiplatform/files/14231796/multi_layer-main.zip)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by MatkovIvan** [comment]
Thanks for the report. Found a race condition that causes that - first composition before setting locals inside dialog. I'll fix it before rc02

**Comment by Thomas-Vos** [comment]
Thanks, it is working with 1.6.0-rc02!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4281">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
