### ISSUE TITLE
compose resources locale language

### ISSUE THREAD

**Issue by pastafarianGit** [JetBrains/compose-multiplatform#4289]
is there a way to set compose resources locale language since i have different flavors on android/ios and only want to support one language per build (and not the one user has selected in android settings) but i still want to keep all the string resources inside shared/common multiplatform lib

 lets say you have multiple locales but you want to get specific one getString(R.id.helloTet, "en"),

**Comment by terrakok** [comment]
1) The flavors are the android gradle plugin feature. It does not work for other targets.
2) If you want to provide a local compose provider with a specific locale then it is not possible yet: https://github.com/JetBrains/compose-multiplatform/issues/4197

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4289">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
