### ISSUE TITLE
Ios accessability support - disable for specific composables

### ISSUE THREAD

**Issue by topmotree** [JetBrains/compose-multiplatform#4290]
Hello. Thanks for the great job first of all.
I have a question about accessibility support in version 1.6.0-beta02. It works great with almost every composable in my application.
But the problem only occurs with webview on iOS. Previously in version 1.5.12, ios voiceover could read information from a web page in the web view. But in 1.6.0-beta02 - the voiceover doesn't recognise it's a web page and doesn't play anything when I click on that composable.

I have a question. Is it possible to somehow disable the new iOS accessibility support for specific composables? 

If necessary I can add a test project to reproduce the issue.

**Comment by elijah-semyonov** [comment]
Hi! Thanks for appreciation remark. Previous accessibility defaulted to interop views in the hierarchy, but now it's represented by the actual semantics tree and the interop views need to be proxied through them. Accessibility proxying to native views from within compose interop is not yet implemented, but that's something we work on. Sorry for inconvenience.

**Comment by topmotree** [comment]
Thank you for your answer.
Do you know maybe when we can expect this accessibility proxying from iOS to Compose?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4290">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
