### ISSUE TITLE
Gradle Plugin: GenerateResClassTask - Use Worker API instead relocation dependencies

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-multiplatform#4298]
Instead adding and relocating dependencies used by Gradle tasks, you should not add the dependencies to the user build script classpath but use worker api with its own isolated class path.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4298">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
