### ISSUE TITLE
ExposedDropdownMenu has wrong padding when has more then 1 item

### ISSUE THREAD

**Issue by weekly71** [JetBrains/compose-multiplatform#4299]
**Describe the bug**
I have an app using Compose Multiplatform, which worked well on 1.5.12. But i updated to 1.6.0-beta2 (1.6.0-rc01 works behaves the same) because of PullRefresh which i needed in my app. But then i saw a bug (which isn't there on 1.6.0-beta1 and 1.5.12):
When ExposedDropdownMenu has more then 1 items it suddenly goes to the top of view.

**Affected platforms**
Select one of the platforms below:
- Android
- iOS (not tested but i think it persists there too)

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-rc01 and 1.6.0-beta2
- OS version(s)* (required for Desktop and iOS issues): Android 13 MIUI 14
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): JDK 17 jbr

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a simple app with ExposedDropdownMenu text input which can have multiple items
2. Run it on mobile device.
3. Try to enter some text that matches multiple items.
4. See that ExposedDropdownMenu is on the top.

**Expected behavior**

**Screenshots**
![Screenshot_2024-02-14-12-45-56-972_com weekly bebrobus](https://github.com/JetBrains/compose-multiplatform/assets/66445346/9a27492e-ab67-4d48-87db-28d0a1729295)
![Screenshot_2024-02-14-12-45-42-805_com weekly bebrobus](https://github.com/JetBrains/compose-multiplatform/assets/66445346/3f27f27e-e0cd-44b1-ab66-98980a2372e0)
![Bildschirmfoto 2024-02-14 um 13 02 33](https://github.com/JetBrains/compose-multiplatform/assets/66445346/1a88fa03-ba8b-4e6f-a575-657d301494b5)
The last screenshot is how it should be 

**Additional context**
On desktop is seems to work OK.

**Comment by Schahen** [comment]
Hi @weekly71 - if the bug is Android-only (which seemingly it is since it's tested only against Android and Desktop, being problematic only at Android) then please, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4299">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
