### ISSUE TITLE
Bug with ImageVector when resize

### ISSUE THREAD

**Issue by LAP2** [JetBrains/compose-multiplatform#430]
Hi team.

Found that if you create ImageVector from code, put it in Image and try to reize window it will create some sort of trace.
here is a code to reproduce:
```
@Composable
internal actual fun ReproducibleArc(
    modifier: Modifier
) = Box(
    modifier = modifier.fillMaxSize()
) {
    val vi = rememberVectorPainter(
        ImageVector.Builder(
            defaultWidth = 50.dp,
            defaultHeight = 50.dp,
            viewportWidth = 50f,
            viewportHeight = 50f,
        ).apply {
            val center = Offset(25f,25f)
            path(
                stroke = SolidColor(Color.Red),
                fill = SolidColor(Color.Red)
            ) {
                moveTo(center.x, center.y)
                lineToRelative(25f, 0f)
                arcToRelative(25f,25f,0f,false,true,-25f,25f)
                close()
            }
        }.build()
    )
    Surface(
        border = BorderStroke(2.dp, Color.Black),
        modifier = Modifier.wrapContentSize()
    ) {
        Image(
            vi,
            "Circle",
            modifier.fillMaxSize(),
        )
    }
}
```
![StrangeArc](https://user-images.githubusercontent.com/15348209/109211851-3fa6e980-77c8-11eb-810c-085e3cbd7bbe.gif)
Also it seems that `arcToRelative` theta parameter is not much usable, it could be calculated using other parameters.

**Comment by akurasov** [comment]
Tried it on Mac&latest build and it works fine. @LAP2 do you still have this issue? If yes, what is the Compose build# and OS?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5487">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
