### ISSUE TITLE
[Resources]Support multiple modules

### ISSUE THREAD

**Issue by hellomr3** [JetBrains/compose-multiplatform#4301]
**Describe the problem**
Explain the performance issue you're experiencing, including the following details:
` 
if (typeString == "values" && file.name.equals("strings.xml", true)) {
            val stringIds = getStringIds(file)
            return stringIds.map { strId ->
                ResourceItem(ResourceType.STRING, qualifiers, strId.asUnderscoredIdentifier(), path)
            }
        }
`
there force string named 'strings' limit multiple sub modules ,if  all named "strings.xml" led to "mergeDebugJavaResource error".is there any optimization name rule,example end of "strings" to avoid this ?
 
- What specific issue did you encounter? (e.g. missing frames, high CPU usage, memory leaks)
- Have you noticed any patterns or specific circumstances under which the problem occurs?

**Affected platforms**
Select one of the platforms below:
- All
- Desktop
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library
- iOS
- Other

If the problem is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version: 
- Compose Multiplatform version: 1.6.0-rc01
- OS version(s) (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**Sample code**
If possible, provide a small piece of code that reproduces the problem. If the code snippet is too large to paste here, please link to a Gist, a GitHub repo, or any other public code repository.

**Reproduction steps**
Please provide a detailed step-by-step guide on how to reproduce the issue you are experiencing.

**Video**
If you're reporting slow app work or missing frames, please provide a video of the problem.

**Profiling data**
Please provide any relevant profiling data that might be helpful. This could include information like FPS, memory usage, CPU time, or any other data that could provide insight into the performance issue.

**Additional information**
Provide any other details that you think might be helpful for us to understand the problem. This could include things like the system configuration, external factors, etc.

**Comment by hellomr3** [comment]
<img width="169" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/29541241/0be78d91-be23-4649-8cd3-786fc7e3e819">
Although this can avoid detection

**Comment by MatkovIvan** [comment]
Tracking multi-modules support request here: #4229

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4301">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
