### ISSUE TITLE
Support non-linear text scale for non-Android platforms

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4305]
It was introduced for Android in Jetpack Compose 1.6.0. See https://android-developers.googleblog.com/2024/01/whats-new-in-jetpack-compose-january-24-release.html, but isn't supported on other platforms.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4305">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
