### ISSUE TITLE
Res Class is not usable for very large project that supports multiple language

### ISSUE THREAD

**Issue by kazemcodes** [JetBrains/compose-multiplatform#4308]
**Describe the bug**
Res class code insight is disable in my project because it supports a lot of languages and and Res class consist of 77 thousands line and because of that I cant use Res class at all, and I can't use any resource inside Res class

**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: [1.6.0-rc01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-rc01)

**Comment by Schahen** [comment]
This will be fixed in 1.6.0-rc02, please raise this issue again if it won't be the case for you

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4308">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
