### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by hhartzer** [JetBrains/compose-multiplatform#4311]
Hi,

What would it take to add FreeBSD support? Maybe even under some kind of unaccelerated fallback mode?

Without FreeBSD support, Briar Desktop, for instance, cannot run on FreeBSD from what I understand: https://code.briarproject.org/briar/briar-desktop/-/issues/553#note_78878

Thank you!

**Comment by kirill-grouchnikov** [comment]
Is Skia even available on FreeBSD?

**Comment by hhartzer** [comment]
I think it might be?

https://lists.freebsd.org/pipermail/freebsd-gecko/2019-December/009806.html

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4311">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
