### ISSUE TITLE
Shared resources not working in compose multiplatform library

### ISSUE THREAD

**Issue by philipkraeutl** [JetBrains/compose-multiplatform#4313]
**Describe the bug**
When creating a compose-multiplatform library and using the library in a compose app, the resouces are not working for iOS and Web (K/wasm). More details on this are in the stackoverflow post here: https://stackoverflow.com/questions/78005978/shared-resources-not-working-in-compose-multiplatform-library
**Affected platforms**

 - Web (K/Wasm) - Canvas based API
 - iOS

**Versions**
Kotlin version*: 1.9.22
Compose Multiplatform version*:  1.6.0-beta02 (1.6.0-rc01 also not working)
OS version(s)* (required for Desktop and iOS issues): Any iOS version
OS architecture (x86 or arm64): both

**To Reproduce**
1. See  https://stackoverflow.com/questions/78005978/shared-resources-not-working-in-compose-multiplatform-library

**Comment by terrakok** [comment]
https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html

<img width="781" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/3532155/0234d50e-e45d-41c8-ab49-2a375afa70f0">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4313">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
