### ISSUE TITLE
runDistributable runs BUT distributable installed via packageMsi doesn't

### ISSUE THREAD

**Issue by wakaztahir** [JetBrains/compose-multiplatform#4317]
**Describe the bug**
I tried to start the executable using a terminal to expect some output so I could debug the release executable, which has been installed from the (packageReleaseMsi -> outputs executable) But there's no output, however runDistributable works

**Affected platforms**
Select one of the platforms below:
- All
- Desktop

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4317">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
