### ISSUE TITLE
Tooltips should disappear after 1.5 seconds

### ISSUE THREAD

**Issue by sproctor** [JetBrains/compose-multiplatform#4321]
**Describe the bug**
Tooltips generated by `androidx.compose.material3.TooltipBox` disappear immediately when you stop hovering them. They should remain visible for 1.5 seconds or until another tooltip is shown.

[androidx.compose.material3.TooltipBox](https://m3.material.io/components/tooltips/guidelines#b0386365-fe47-4e46-b4e0-e8f62ae55395)

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-rc02
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 22.04
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 17

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4321">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
