### ISSUE TITLE
`SelectionContainer` can't show options menu on iOS

### ISSUE THREAD

**Issue by robxyy** [JetBrains/compose-multiplatform#4322]
**Describe the bug**
`SelectionContainer` can't show options menu on iOS

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-rc02

**To Reproduce**

When long pressing `SelectionContainer`, the options menu  can't  be shown , like `Copy` ...

```kotlin
SelectionContainer {
  Text(text = "Hello World!")
}
```

**Expected behavior**

Show options menu like Android

**Screenshots**
<img src="https://github.com/JetBrains/compose-multiplatform/assets/9105106/4bfa8c3e-f068-4d3f-b27d-699c35f7e709" width=35% height=35%>

**Comment by bonamanada** [comment]
It is not reproduced in version 1.6.0-alpha01, but is reproduced starting from version 1.6.0-beta01.

**Comment by brendanw** [comment]
@dima-avdeev-jb @mazunin-v-jb I am seeing this on compose 1.6.1 -- this is a pretty serious regression. Is there an ETA for a fix?

**Comment by mazunin-v-jb** [comment]
Should be included in the next release.

**Comment by brendanw** [comment]
@mazunin-v-jb I just tested `1.6.10-beta01` and still seeing the issue fwiw.

**Comment by mazunin-v-jb** [comment]
@brendanw beta01 doesn't contain that fix, please wait for beta02

**Comment by brendanw** [comment]
I am also seeing the same two issues as @robxyy

**Comment by mazunin-v-jb** [comment]
@robxyy 
Thanks for describing problems!
Since these two problems not related to options menu, I decided to move them out into separate issues: [(iOS) Selection Container shows keyboard while selecting text](https://github.com/JetBrains/compose-multiplatform/issues/4986) and [Dragging to scroll clears selection](https://github.com/JetBrains/compose-multiplatform/issues/4951).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4322">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
