### ISSUE TITLE
`Component` should not request focus immediately when scrolling list on iOS

### ISSUE THREAD

**Issue by robxyy** [JetBrains/compose-multiplatform#4324]
**Describe the bug**
`Component` should not request focus immediately when scrolling list on iOS

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-rc02

**To Reproduce**

```kotlin
Column( Modifier.fillMaxSize().verticalScroll(rememberScrollState())) {
  repeat(100) {
    Text(
      "Hello world!",
      Modifier.height(56.dp).fillMaxWidth().clickable {
      },
    )
  }
}
```

**Expected behavior**

Consistent with Android scrolling behavior

**Screenshots**

iOS:

https://github.com/JetBrains/compose-multiplatform/assets/9105106/2d75cc83-7c3a-4950-a4af-c6c0313ac079

Android:

https://github.com/JetBrains/compose-multiplatform/assets/9105106/ff939371-2480-408d-9f72-05ff2702760e

**Comment by dima-avdeev-jb** [comment]
Thanks for Issue!

**Comment by robxyy** [comment]
Update: Also had similar issue with `TextField`.

**Comment by dan15d** [comment]
Same for me with Textfield. Issue #4204

**Comment by dima-avdeev-jb** [comment]
@mazunin-v-jb Is it duplicate?

**Comment by ASalavei** [comment]
It seems like behaviour with highlighting clickable text is similar for iOS and Android:
https://github.com/JetBrains/compose-multiplatform/assets/78535708/eedfbb52-c430-45cd-8c6c-9d39bea9b9ad

I would check if we can adjust initial delay a bit to match iOS timings.

However the issue https://github.com/JetBrains/compose-multiplatform/issues/4204 is still actual. I will look at it also.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4324">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
