### ISSUE TITLE
Can't build on release only

### ISSUE THREAD

**Issue by vivaCoda54** [JetBrains/compose-multiplatform#4328]
**Describe the bug**
I have a bug when I try to build my code only in release (debug work).

**Affected platforms**
Select one of the platforms below:
- Android/iOS

If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version*: 1.9.21 
- Compose Multiplatform version*: 1.5.12
- OS version(s)* (required for Desktop and iOS issues):  Android, iOS

**Expected behavior**
I not have a proxy, or something else, all work on debug, when I test my code. Only the release aab build didn't work.

**Additional context**
Execution failed for task ':androidApp:checkReleaseAarMetadata'.
> Could not resolve all files for configuration ':androidApp:releaseRuntimeClasspath'.
   > Failed to transform resources-compose-release.aar (dev.icerock.moko:resources-compose-android:0.23.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download resources-compose-release.aar (dev.icerock.moko:resources-compose-android:0.23.0)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/resources-compose-android/0.23.0/resources-compose-android-0.23.0.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/resources-compose-android/0.23.0/resources-compose-android-0.23.0.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform biometry-compose-release.aar (dev.icerock.moko:biometry-compose-android:0.4.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download biometry-compose-release.aar (dev.icerock.moko:biometry-compose-android:0.4.0)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/biometry-compose-android/0.4.0/biometry-compose-android-0.4.0.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/biometry-compose-android/0.4.0/biometry-compose-android-0.4.0.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform biometry-release.aar (dev.icerock.moko:biometry-android:0.4.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download biometry-release.aar (dev.icerock.moko:biometry-android:0.4.0)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/biometry-android/0.4.0/biometry-android-0.4.0.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/biometry-android/0.4.0/biometry-android-0.4.0.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform resources-release.aar (dev.icerock.moko:resources-android:0.23.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download resources-release.aar (dev.icerock.moko:resources-android:0.23.0)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/resources-android/0.23.0/resources-android-0.23.0.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/resources-android/0.23.0/resources-android-0.23.0.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform precompose-koin-release.aar (moe.tlaster:precompose-koin-android:1.5.8) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download precompose-koin-release.aar (moe.tlaster:precompose-koin-android:1.5.8)
         > Could not get resource 'https://repo.maven.apache.org/maven2/moe/tlaster/precompose-koin-android/1.5.8/precompose-koin-android-1.5.8.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/moe/tlaster/precompose-koin-android/1.5.8/precompose-koin-android-1.5.8.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform precompose-viewmodel-release.aar (moe.tlaster:precompose-viewmodel-android:1.5.8) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download precompose-viewmodel-release.aar (moe.tlaster:precompose-viewmodel-android:1.5.8)
         > Could not get resource 'https://repo.maven.apache.org/maven2/moe/tlaster/precompose-viewmodel-android/1.5.8/precompose-viewmodel-android-1.5.8.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/moe/tlaster/precompose-viewmodel-android/1.5.8/precompose-viewmodel-android-1.5.8.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform precompose-release.aar (moe.tlaster:precompose-android:1.5.8) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download precompose-release.aar (moe.tlaster:precompose-android:1.5.8)
         > Could not get resource 'https://repo.maven.apache.org/maven2/moe/tlaster/precompose-android/1.5.8/precompose-android-1.5.8.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/moe/tlaster/precompose-android/1.5.8/precompose-android-1.5.8.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform kmpnotifier-release.aar (io.github.mirzemehdi:kmpnotifier-android:0.2.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download kmpnotifier-release.aar (io.github.mirzemehdi:kmpnotifier-android:0.2.0)
         > Could not get resource 'https://repo.maven.apache.org/maven2/io/github/mirzemehdi/kmpnotifier-android/0.2.0/kmpnotifier-android-0.2.0.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/io/github/mirzemehdi/kmpnotifier-android/0.2.0/kmpnotifier-android-0.2.0.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform mvvm-compose-release.aar (dev.icerock.moko:mvvm-compose-android:0.16.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download mvvm-compose-release.aar (dev.icerock.moko:mvvm-compose-android:0.16.1)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/mvvm-compose-android/0.16.1/mvvm-compose-android-0.16.1.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/mvvm-compose-android/0.16.1/mvvm-compose-android-0.16.1.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform mvvm-flow-compose-release.aar (dev.icerock.moko:mvvm-flow-compose-android:0.16.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download mvvm-flow-compose-release.aar (dev.icerock.moko:mvvm-flow-compose-android:0.16.1)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/mvvm-flow-compose-android/0.16.1/mvvm-flow-compose-android-0.16.1.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/mvvm-flow-compose-android/0.16.1/mvvm-flow-compose-android-0.16.1.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform mvvm-flow-release.aar (dev.icerock.moko:mvvm-flow-android:0.16.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download mvvm-flow-release.aar (dev.icerock.moko:mvvm-flow-android:0.16.1)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/mvvm-flow-android/0.16.1/mvvm-flow-android-0.16.1.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/mvvm-flow-android/0.16.1/mvvm-flow-android-0.16.1.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform mvvm-core-release.aar (dev.icerock.moko:mvvm-core-android:0.16.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download mvvm-core-release.aar (dev.icerock.moko:mvvm-core-android:0.16.1)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/mvvm-core-android/0.16.1/mvvm-core-android-0.16.1.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/mvvm-core-android/0.16.1/mvvm-core-android-0.16.1.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform multiplatform-settings-coroutines-release.aar (com.russhwolf:multiplatform-settings-coroutines-android:1.1.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download multiplatform-settings-coroutines-release.aar (com.russhwolf:multiplatform-settings-coroutines-android:1.1.1)
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/russhwolf/multiplatform-settings-coroutines-android/1.1.1/multiplatform-settings-coroutines-android-1.1.1.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/russhwolf/multiplatform-settings-coroutines-android/1.1.1/multiplatform-settings-coroutines-android-1.1.1.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform mvvm-internal-release.aar (dev.icerock.moko:mvvm-internal-android:0.16.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download mvvm-internal-release.aar (dev.icerock.moko:mvvm-internal-android:0.16.1)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/mvvm-internal-android/0.16.1/mvvm-internal-android-0.16.1.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/mvvm-internal-android/0.16.1/mvvm-internal-android-0.16.1.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform parcelize-release.aar (dev.icerock.moko:parcelize-android:0.8.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download parcelize-release.aar (dev.icerock.moko:parcelize-android:0.8.0)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/parcelize-android/0.8.0/parcelize-android-0.8.0.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/parcelize-android/0.8.0/parcelize-android-0.8.0.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform multiplatform-settings-no-arg-release.aar (com.russhwolf:multiplatform-settings-no-arg-android:1.1.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download multiplatform-settings-no-arg-release.aar (com.russhwolf:multiplatform-settings-no-arg-android:1.1.1)
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/russhwolf/multiplatform-settings-no-arg-android/1.1.1/multiplatform-settings-no-arg-android-1.1.1.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/russhwolf/multiplatform-settings-no-arg-android/1.1.1/multiplatform-settings-no-arg-android-1.1.1.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform multiplatform-settings-serialization-release.aar (com.russhwolf:multiplatform-settings-serialization-android:1.1.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download multiplatform-settings-serialization-release.aar (com.russhwolf:multiplatform-settings-serialization-android:1.1.1)
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/russhwolf/multiplatform-settings-serialization-android/1.1.1/multiplatform-settings-serialization-android-1.1.1.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/russhwolf/multiplatform-settings-serialization-android/1.1.1/multiplatform-settings-serialization-android-1.1.1.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform kermit-release.aar (co.touchlab:kermit-android:2.0.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download kermit-release.aar (co.touchlab:kermit-android:2.0.0)
         > Could not get resource 'https://repo.maven.apache.org/maven2/co/touchlab/kermit-android/2.0.0/kermit-android-2.0.0.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/co/touchlab/kermit-android/2.0.0/kermit-android-2.0.0.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform kswift-runtime-release.aar (dev.icerock.moko:kswift-runtime-android:0.6.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download kswift-runtime-release.aar (dev.icerock.moko:kswift-runtime-android:0.6.1)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/kswift-runtime-android/0.6.1/kswift-runtime-android-0.6.1.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/kswift-runtime-android/0.6.1/kswift-runtime-android-0.6.1.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform graphics-release.aar (dev.icerock.moko:graphics-android:0.9.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download graphics-release.aar (dev.icerock.moko:graphics-android:0.9.0)
         > Could not get resource 'https://repo.maven.apache.org/maven2/dev/icerock/moko/graphics-android/0.9.0/graphics-android-0.9.0.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/dev/icerock/moko/graphics-android/0.9.0/graphics-android-0.9.0.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform kermit-core-release.aar (co.touchlab:kermit-core-android:2.0.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download kermit-core-release.aar (co.touchlab:kermit-core-android:2.0.0)
         > Could not get resource 'https://repo.maven.apache.org/maven2/co/touchlab/kermit-core-android/2.0.0/kermit-core-android-2.0.0.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/co/touchlab/kermit-core-android/2.0.0/kermit-core-android-2.0.0.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused
   > Failed to transform multiplatform-settings-release.aar (com.russhwolf:multiplatform-settings-android:1.1.1) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not download multiplatform-settings-release.aar (com.russhwolf:multiplatform-settings-android:1.1.1)
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/russhwolf/multiplatform-settings-android/1.1.1/multiplatform-settings-android-1.1.1.aar'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/russhwolf/multiplatform-settings-android/1.1.1/multiplatform-settings-android-1.1.1.aar'.
               > Connect to 127.0.0.1:9090 [/127.0.0.1] failed: Connection refused

**Comment by robxyy** [comment]
@vivaCoda54 Please check your IDEA/AS Proxy or Gradle Proxy.
https://stackoverflow.com/questions/36330895/error-gradle-sync-failed-connection-refused-connect

**Comment by dima-avdeev-jb** [comment]
@vivaCoda54 Can you please provide a minimal reproducible sample of your Issue on a GitHub?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4328">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
