### ISSUE TITLE
LazyColumn and LazyRow are very slow only on iOS

### ISSUE THREAD

**Issue by vivaCoda54** [JetBrains/compose-multiplatform#4329]
**Describe the problem**
Scrolling my lazycolum/lazyrow is very slow on iOS. It's very fluid on Android, but everything feels like it's slowing down on ios.

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version: 1.9.21
- Compose Multiplatform version: 1.5.12

**Comment by dima-avdeev-jb** [comment]
Hello! Thanks for an Issue!
Can you please provide a minimal reproducible sample there we can see a big difference between Android and iOS?

**Comment by vivaCoda54** [comment]
Hello @dima-avdeev-jb , this is a sample with the lag. Tell me if you succeed to get it (it's on a drive)
If not, I will put it on github but I prefer to avoid this.
https://drive.google.com/file/d/1KibJSEWI99U_OtaGZPGKWCAabXuIxlkl/view?usp=sharing

**Comment by elijah-semyonov** [comment]
I'll have a look!

**Comment by vivaCoda54** [comment]
Hello @elijah-semyonov 
did you have time to look ?

**Comment by elijah-semyonov** [comment]
Not yet, I'll post my findings when I'm done with it.

**Comment by vivaCoda54** [comment]
@elijah-semyonov @dima-avdeev-jb Following the release of version 1.6.0 of compose multiplatform I've changed the way resources are displayed, just to see. I used to use moko resources. I modified everything to use the more native way with the new Res. And now, miraculously, it works great, it's fluid as ever. The problem is solved, it was moko that was causing the slowdown.

**Comment by aldefy** [comment]
@vivaCoda54 by any chance u have a migration guide

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4329">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
