### ISSUE TITLE
Ability to use Compose Multiplatform resources in Preview

### ISSUE THREAD

**Issue by dima-avdeev-jb** [JetBrains/compose-multiplatform#4338]
It's good to have ability to use Compose Multiplatform resources, described [in this article](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html#resource-usage), in Preview annotation

**Comment by LukasAnda** [comment]
This would be a huge help 👍

**Comment by VladislavIzbash** [comment]
Problem is that regular java resources, that multiplatform resources library use, are not present in preview's classpath.

You can try to add your fonts to classpath by calling following method in beginning of each preview:
```
private fun hackClassLoader() {
    val classLoader = ClassLoader.getSystemClassLoader()
    val addURL = classLoader.javaClass.getMethod("addURL", URL::class.java)
    addURL.isAccessible = true
    addURL.invoke(classLoader, URL("<directory containing font resources>"))
}
```
I'm trying to do the same with vector images, but now getting `ClassNotFoundError` for `org.xml.sax.InputSource`

**Comment by terrakok** [comment]
Duplicates #4476

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4338">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
