### ISSUE TITLE
How to get packageName/packageVersion/vendor

### ISSUE THREAD

**Issue by LazyIonEs** [JetBrains/compose-multiplatform#4339]
```
val kitVersion by extra("1.0.0")

compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "appName"
            packageVersion = kitVersion
            description = "description"
            copyright = "© 2024 Name. All rights reserved."
            vendor = "Name"
            licenseFile.set(project.rootProject.file("LICENSE"))
            ...
        }
    }
}
```
I now want to create an about page within the application, which contains the application name, application version and other information, but I don’t know how to obtain these parameters in build.gradle.kts, How to write code

Mainly on mac/windows

**Comment by dima-avdeev-jb** [comment]
Hello! You can use some gradle plugins for code generation. For example pay attention to https://github.com/gmazzo/gradle-buildconfig-plugin.
And you can configure some values this such information right in your gradle scripts.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4339">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
