### ISSUE TITLE
Have the template projects use `libs.versions.toml` for versions instead of properties

### ISSUE THREAD

**Issue by hakanai** [JetBrains/compose-multiplatform#4341]
One of the first things I end up doing every project after using IDEA's Compose Multiplatform template is, renovate the project up to using version catalogs.

It would be nice if this were fresh out of the box.

The gist:

- `gradle/libs.versions.toml` gets:
    ```
    [versions]
    kotlin = "1.9.20"
    compose = "1.5.10"

    [plugins]
    kotlin-jvm = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
    compose = {id = "org.jetbrains.compose", version.ref = "compose"}
    ```
(-- or whatever is current at time of reading)

- The two lines in `gradle.properties` for those versions go away
- The `plugins` block in `settings.gradle.kts` goes away

- `build.gradle.kts` changes to
    ```kotlin
     plugins {
        alias(libs.plugins.kotlin.jvm)
        alias(libs.plugins.compose)
    }
    ```

**Comment by dima-avdeev-jb** [comment]
Thanks for enhancement suggestion!

**Comment by dima-avdeev-jb** [comment]
We already added `gradle/libs.versions.toml` in new KMP wizard:
https://kmp.jetbrains.com/

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4341">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
