### ISSUE TITLE
Outdated link to archived repo

### ISSUE THREAD

**Issue by LouisCAD** [JetBrains/compose-multiplatform#4343]
Hello!

I'm wondering what would be the correct link to setup instructions 

https://github.com/JetBrains/compose-multiplatform/blob/7849ed200cc4c09d5a92f74cbc5b82ada5dc1d41/examples/graphics-2d/README.md?plain=1#L8

For the link above, there are no setup instructions there, just an archived repo, and certainly not for native macOS 🤔

**Comment by dima-avdeev-jb** [comment]
Thanks! We will fix it!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4343">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
