### ISSUE TITLE
HTML: controlled text input cant edit text in the middle 

### ISSUE THREAD

**Issue by sergeych** [JetBrains/compose-multiplatform#4346]
Using controlled input, changing corresponding state value recomposes the input control with new input value which always sets the caret to the end of field. It is impossible to input more than 1 character to some caret position - it jumps to the end. This is too bad for the end user

**Affected platforms**
Select one of the platforms below:
- Web (K/JS) - HTML library

**Versions**
- Kotlin version*: 1.9.21, but any is affected
- Compose Multiplatform version*:  1.5.12

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

Create an controlled text input. Try to enter something then set cursor to the middle and try to insert text there.

**Expected behavior**
Controlled TextInput must allow entering more than one character at any caret position without jumping to the end.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4346">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
