### ISSUE TITLE
How to switch between Languages Programitically

### ISSUE THREAD

**Issue by JagadishaIncture** [JetBrains/compose-multiplatform#4347]
HI Team,

Iam working on feature to support multiple langs **en** and **fr** . so for that i've  created two strings.xml one for (en) and other for (fr) and now I'm able to access string from english lang using  below code

`stringResource(Res.strings.by_product)`

**Feature** :  will be providing dropdown in Profile Screen to switch between lang . as soon user selects **fr** then i should be able to show strings from strings.xml(fr)

is there any way to programatically  switch between lang
<img width="338" alt="Screenshot 2024-02-22 at 4 57 51 PM" src="https://github.com/JetBrains/compose-multiplatform/assets/55983819/a2dafca5-0b67-4379-9de0-5c6642de01be">

**Comment by dima-avdeev-jb** [comment]
Thanks!

We discussed this feature in our team. One of possible solution is to provide **staticCompositionLocal** with with ability to override qualifiers in part of Compose hierarchy.

**Comment by JagadishaIncture** [comment]
when can we expect this change?

**Comment by dima-avdeev-jb** [comment]
> What about reading strings from ViewModels, Widgets ?

@rustamsmax Thanks, good question. We should discuss it.

**Comment by dhng22** [comment]
Any progress on this issue?

**Comment by rustamsmax** [comment]
I got a wife and 2 beautiful children

**Comment by Melodeiro** [comment]
I think thats an important feature, because otherwise your option is to provide the default language, if proper language wasn't detected from OS. But its not guaranteed that the user will be comfortable with the default one

**Comment by terrakok** [comment]
We will implement the feature but it is not responsibility of the resources library. It will be done in the core/runtime modules. It requires approvals and some design decisions. So, have a patience 😉

**Comment by ahmedhosnypro** [comment]
@terrakok This comment  might help  at #4197
https://github.com/JetBrains/compose-multiplatform/issues/4197#issuecomment-2185561043


Also provides the solution for this question

> CompositionLocal changes locals only for @composables What about reading strings from ViewModels, Widgets ? @dima-avdeev-jb

**Comment by dhng22** [comment]
Is there a ticket on Youtrack for this issue?

**Comment by Vocaloid2048** [comment]
Sorry for bothering, Is any news of that function? It will be awesome to use it in an official way.
Anyway, thanks to everyone's hard work and effort in this useful function!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4347">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Vocaloid2048** [comment]
Sorry for the same bothering, is there have any possible way to do it now? Instead of editting Libuary's source code?
