### ISSUE TITLE
make TextField() behave more as expected

### ISSUE THREAD

**Issue by zoff99** [JetBrains/compose-multiplatform#4348]
**Describe the bug**
there is some basic universal expected behaviour of textfields. this should also be the case in compose desktop.
currently it is not so.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.5.12
- OS version(s)* (required for Desktop and iOS issues): Linux
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 17

**To Reproduce**
create a TextField() then:

keys on the numblock of the keyboard (when numlock is not active) do nothing

numblock enter does nothing

middle mouse button click does nothing

middle mouse button marking of some text doesnt not put it into the copy buffer

pressing shift+return does nothing (instead alt+return inserts a newline, which is less common. people expect shift return to do that)

pressing shift+numblock_return does nothing

**Expected behavior**
keys on the numblock of the keyboard (when numlock is not active) do as expected: cursor up/down/left/right/pos1/end/pgup/pgdown/del

numblock enter sends return

middle mouse button click does insert contents from the copy buffer

middle mouse button marking of some text does put it into the copy buffer

pressing shift+return inserts a newline

pressing shift+numblock_return inserts a newline

and last, if alt-return inserts a newline then at least alt-numblock_return should do the same

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4348">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by zoff99** [comment]
why are you closing tickets and referring to another platform?
