### ISSUE TITLE
Text field on iOS not showing paste action when content is empty on Compose 1.6.0-rc02

### ISSUE THREAD

**Issue by msasikanth** [JetBrains/compose-multiplatform#4353]
**Describe the bug**
When the text field content is empty, I can no longer double tap (like on iOS) or long press to bring up the context menu with paste action. I can do the double tap to bring up the context actions if there is text already and I can select it.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-rc02
- OS version(s)*: 17.3.1 
- OS architecture (x86 or arm64): arm64

**Expected behavior**
Bring up the context menu with paste action, even if the content is empty.

**Comment by rustamsmax** [comment]
Yes, only selection works. Long click is not working

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4353">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by aptech73** [comment]
This bug is reproduced on the version:
* Kotlin: 2.1.0-Beta1
* Compose Multiplatform: 1.7.1
* IOS: 18.0.1
