### ISSUE TITLE
Compose-web scroll event has a value of 100 per tick instead of 1

### ISSUE THREAD

**Issue by SPC-code** [JetBrains/compose-multiplatform#4354]
**Describe the bug**
Scroll event on Compose-Web on 1.6.0-rc2 gives change.scrollDelta.y equals 100f instead of 1f on the desktop. It causes different behavior on Desktop and web.

**Affected platforms**
Select one of the platforms below:
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*:  1.9.22
- Compose Multiplatform version*:  1.6.0-rc2

**To Reproduce**
```kotlin
Modifier.pointerInput(Unit) {
        awaitPointerEventScope {
            while (true) {
                val event: PointerEvent = awaitPointerEvent()
                event.changes.forEach { change ->

                    if (event.type == PointerEventType.Scroll) {
                        val (xPos, yPos) = change.position
                        //compute invariant point of translation
                        val invariant = DpOffset(xPos.toDp(), yPos.toDp()).toCoordinates()
                        viewPoint = with(space) {
                            viewPoint.zoomBy(-change.scrollDelta.y * viewConfig.zoomSpeed, invariant)
                        }
                        change.consume()
                    }
...
```

**Expected behavior**
Should be the same value per wheel tick for different platforms.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4354">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
