### ISSUE TITLE
Restore focus when window becomes visible

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#4355]
**Describe the bug**
When a window is hidden and then visible again, the focus is not restored to the element that had it before. 

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Compose Multiplatform version*: 1.6.0-rc03
- OS version(s)* (required for Desktop and iOS issues): macOS
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce**

```
fun main() = application {
    var windowVisible by remember { mutableStateOf(true) }
    Window(
        onCloseRequest = { windowVisible = false },
        visible = windowVisible
    ) {
        val focusRequester = remember { FocusRequester() }
        var text by remember { mutableStateOf("") }
        TextField(
            value = text,
            onValueChange = { text = it },
            modifier = Modifier.focusRequester(focusRequester)
        )

        LaunchedEffect(Unit) {
            focusRequester.requestFocus()
        }

        LaunchedEffect(windowVisible) {
            if (!windowVisible) {
                delay(2000)
                windowVisible = true
            }
        }
    }
}
```

It seems the focus is actively moved away from the currently focused element by `ComposeSceneMediator.focusListener.focusGained`.

https://github.com/JetBrains/compose-multiplatform/assets/5230206/56f6930f-23bf-4d35-97ea-891560912d82

**Expected behavior**
Focus should be kept/restored to the element that had it when the window became hidden.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4355">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
