### ISSUE TITLE
Compose web click gestures do not properly detect mouse buttons

### ISSUE THREAD

**Issue by SPC-code** [JetBrains/compose-multiplatform#4356]
**Describe the bug**
PointerEvent.buttons always the same whichever button is pressed.

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-rc2

**Expected behavior**
Should detect which button is pressed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4356">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
