### ISSUE TITLE
[Wasm] Pointer input is incorrect when the browser window is moved from one monitor to another with different scaling levels (on Windows)

### ISSUE THREAD

**Issue by ssttkkl** [JetBrains/compose-multiplatform#4357]
**Describe the bug**
Pointer input is incorrect when the browser window is moved from one monitor to another with different scaling levels.

Reproduced on Windows, not sure about macOS and Linux.

Just like the video says: 

https://github.com/JetBrains/compose-multiplatform/assets/17331698/eee90cbe-6f03-441f-b05e-2462d5334c11

- 0:00\~0:10: Everything works on monitor 1
- 0:10\~0:25: Pointer input is incorrect on monitor 2

(My OS language is Chinese, anyway it doesn't matter much)

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-rc02
- OS version(s)*: Windows 10
- OS architecture (x86 or arm64): x86
- Browser: Microsoft Edge 121.0.2277.83, and Chrome 121.0.6167.86

**To Reproduce**

To reproduce this bug, multiple monitors are required. Monitors should have different scaling levels. (In my case, I have two monitors, whose scaling levels are 150% and 125%)

1. Create a new project from https://kmp.jetbrains.com/

2. Add these piece of code

```kotlin
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.material.MaterialTheme
import androidx.compose.material.OutlinedButton
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@OptIn(ExperimentalLayoutApi::class)
@Composable
fun App() {
    MaterialTheme {
        FlowRow(Modifier.fillMaxWidth()) {
            repeat(30) {
                OutlinedButton({ }) {
                    Text(it.toString())
                }
            }
        }
    }
}
```

3. Build and run wasm. Run a brower in one monitor, open the page, then move the browser to the other monitor.

**Expected behavior**
Pointer input should work normally.

**Comment by ssttkkl** [comment]
After upgrade to compose 1.6.11 it seems to work correctly now :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4357">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
