### ISSUE TITLE
updated from 1.6.0-rc02 to 1.6.0-rc03 and some icons does not exist anymore (maybe only the extended one)

### ISSUE THREAD

**Issue by Zenturas** [JetBrains/compose-multiplatform#4358]
**Affected platforms**
Select one of the platforms below:
- All

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-rc03
- JDK (for desktop issues):  jdk20

See error: 

defaultIcons is Icons.Filled

1.6.0-rc02

![importexport02](https://github.com/JetBrains/compose-multiplatform/assets/128176107/a6f7a983-a2d9-4fe9-947f-e6d10bc66809)

1.6.0-rc03

![importexport03](https://github.com/JetBrains/compose-multiplatform/assets/128176107/9a2a0c46-1d63-471a-a20b-2e43ee15d8b7)

**Comment by igordmn** [comment]
Could you attach a project where it is reproducible?

I checked the standard project https://kmp.jetbrains.com, used `rc02`, upgraded it to `rc03` and the extended icons are found.

**Comment by Zenturas** [comment]
from the standard projects i cannot reproduce it, it works. For my projects it is a bit strange while it works with rc02, with rc03 it does not. here i shrink down my project maybe you can catch something that does not match: https://github.com/Zenturas/compose

**Comment by Zenturas** [comment]
found the problem inside settings.gradle.kts 

```
pluginManagement {
	repositories {
		gradlePluginPortal()
		mavenCentral()
		mavenLocal()
		google()
		maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
	}

	plugins {
		.......
	}
}

dependencyResolutionManagement {
	@Suppress("UnstableApiUsage")
	repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
	@Suppress("UnstableApiUsage")
	repositories {
		gradlePluginPortal()
		mavenCentral()
		mavenLocal()
		google()
		maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
	}
}

rootProject.name = "compose"
include("composeTests")
```

`maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")`

has to be first, but i dont understand why??


```
pluginManagement {
	repositories {
		maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
		gradlePluginPortal()
		mavenCentral()
		mavenLocal()
		google()
	}

	plugins {
		.......
	}
}

dependencyResolutionManagement {
	@Suppress("UnstableApiUsage")
	repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
	@Suppress("UnstableApiUsage")
	repositories {
		maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
		gradlePluginPortal()
		mavenCentral()
		mavenLocal()
		google()
	}
}

rootProject.name = "compose"
include("composeTests")
```

**Comment by igordmn** [comment]
Try to remove `mavenLocal()`, it can cause [issues](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:case-for-maven-local)

**Comment by Zenturas** [comment]
cant remove because i have some smaller libs created and published in maven local.
 thanks for the time

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4358">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
