### ISSUE TITLE
Expose an API for converting DrawableResource -> ByteArray

### ISSUE THREAD

**Issue by colinrtwhite** [JetBrains/compose-multiplatform#4360]
Hi I'm looking to add support for the new multiplatform resources API in [Coil](https://github.com/coil-kt/coil/issues/2077) so it's possible to do:

```kotlin
AsyncImage(
  model = Res.drawable.image,
  contentDescription = null,
)
```

Using `AsyncImage` would have a couple benefits vs. using `Image` and `painterResource`:

- Automatic downscaling for large images into small layout bounds.
- Support for `Decoder`s to decode custom file types.
- More memory cache control (e.g. control size and use LRU eviction, or disable caching).
- `AsyncImage` is a unified API that supports the file system and network URLs too.

At the moment I don't think it's possible to add support as the APIs to fetch a resource (`readResourceBytes`, `Resource.getPathByEnvironment`, and `ResourceEnvironment`) are internal. `Res.readBytes` is public, but it's generated so it can't easily be used in libraries. `Res.readBytes` also requires a path, but there's no public method to convert a `DrawableResource` into a path.

I think exposing `LocalComposeEnvironment.current.rememberEnvironment()` and `resource.getPathByEnvironment(environment)` (basically whatever `painterResource(resource: DrawableResource)` uses) would be enough to support this, but let me know what you think!

**Comment by dima-avdeev-jb** [comment]
Thanks! We will discuss it.

**Comment by terrakok** [comment]
Hi @colinrtwhite ! I have an idea to add a function `getAsUri(Res id)`. It will return an uri to the file based on current environment. Does it cover your case?

**Comment by colinrtwhite** [comment]
@terrakok Yep, I think that would work! Thinking out loud I think this is how Coil would use it:

- The user passes `DrawableResource` to `AsyncImage`.
- `AsyncImage` uses `getAsUri` to translate the `DrawableResource` -> `String` (or uri type)
- The URI is passed to the `ImageLoader`, which can already handle most URI formats (network, disk, Android `R`, etc.)

**Comment by terrakok** [comment]
Hi @colinrtwhite! I returned to the issue and think there is a problem: when we try to convert a DrawableResource to the Uri string, we do this depending on a current environment. It is a hidden logic which can leak to user's code. The uri string is static and points on concrete file instead of a dynamic accessor with the environment handling.

```kotlin
fun DrawableResource.toUri(): String {
    val resource = this
    val resourceReader = LocalResourceReader.current
    val environment = LocalComposeEnvironment.current.rememberEnvironment()
    val resourceItem = remember(resource, environment) { resource.getResourceItemByEnvironment(environment) }
    return resourceReader.getUri(resourceItem.path)
}
```

So, I will add the uri getter only for files by path: `Res.getUri("files/map.png")`. I hope it is enough. All coil's features will work for resources and the resource library API won't be broken.

**Comment by colinrtwhite** [comment]
@terrakok Thanks for the update. Unfortunately, I don't think this solves the use case as `Res` is a generated class that Coil, as a library, can't directly reference so we can't call `Res.getUri`. The underlying method `getResourceUri` is [marked as an internal API](https://github.com/JetBrains/compose-multiplatform/pull/4576/files#diff-e29c9f52f8b96745a7f81124e1cb7fae6a838ca6aeba3f910693a1f962df4c1bR24) so we can't use that either.

Also it sounds like it won't be possible to load the generated `DrawableResource` entries? I was hoping to be able to support `DrawableResource` references as I think most users will prefer type safe drawable references vs. string paths. Is it possible to expose the `path` associated with a `DrawableResource`? Then that path could be used to get the URI, which can then be loaded by Coil. Thanks!

**Comment by terrakok** [comment]
I don't say the coil calls `Res.getUri`. I'd expect a user may pass an uri string to coil. Will it work?
```kotlin
AsyncImage(
  model = Res.getUri("files/my_photo.jpg"),
  contentDescription = null,
)
```

Regarding type safe drawable references, could you explain why the following approach doesn't work for you?
```kotlin
AsyncImage(
  model = painterResource(Res.drawable.some_icon),
  contentDescription = null,
)
```

**Comment by colinrtwhite** [comment]
@terrakok Ah sorry - passing `model = Res.getUri("files/my_photo.jpg")` would work! That API does make it possible to load images given their path.

For `model = painterResource(Res.drawable.some_icon)` we could support it, but then there isn't any benefit to using `AsyncImage` over `Image`. The image is decoded by `painterResource` so `AsyncImage` wouldn't be able to downscale the image into the composable's bounds or add support for custom decoders.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4360">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
