### ISSUE TITLE
[iOS] iOS Dialog has no enter and exit animation

### ISSUE THREAD

**Issue by matsumo0922** [JetBrains/compose-multiplatform#4365]
**Describe the bug**
 iOS Dialog has no display or exit animation

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-rc03
- OS version(s)* (required for Desktop and iOS issues): iOS 17.3.1
- OS architecture (x86 or arm64): arm64e
- JDK (for desktop issues): 

**To Reproduce**
1. `Dialog` enter and exit components

**Expected behavior**
Animation shall be performed as in Android or as in UIAlertController of iOS.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4365">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
