### ISSUE TITLE
[Resource] Drawable scaling from other density-qualified resource

### ISSUE THREAD

**Issue by xiaozhikang0916** [JetBrains/compose-multiplatform#4368]
As [Android Devices Compatibility guide](https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp) shows, 

> To provide good graphical quality on devices with different pixel densities, provide multiple versions of each bitmap in your app—one for each density bucket, at a corresponding resolution. Otherwise, Android must **scale your bitmap so it occupies the same visible space on each screen**, resulting in scaling artifacts such as blurring.

Which indicates that if drawable with qualifier matches current screen is not found, Android will fetch drawable with other qualifier and scale it to fit.

In our prectice, we only provide `drawable-xxhdpi` to keep the product apk small. But in the generated compose resources, it just fail if the best-match drawable not found.

IMO, it would be nice to have features that:

1. Scaling drawable from other density-qualified resource if best-matched not found,
2. Attaching qualifiers info in the resources returned by Res.

**Comment by dima-avdeev-jb** [comment]
Thanks for this feature request! We will discuss it.

**Comment by terrakok** [comment]
Could you elaborate why the default `drawable` dir is not suitable for you?

**Comment by xiaozhikang0916** [comment]
Your question bring me to a rethought of my usage.

In some of our usages, we don't specify the size of drawable or ImageView, just set it to `wrap_content` and apply a drawable to it. The drawable itself, with size in pixel and density qualifier info can determine the size in Dp. But in compose resources, the size modifier will be required for variant devices density.

That is what I requested in feature 1. But I am not sure if it is a good prectice in UI coding.

Anyway, feature 2 will be helpful not only in this case, but also any other if more customization needed.

**Comment by terrakok** [comment]
I need more examples for "if more customization needed". I guess it should be covered by https://github.com/JetBrains/compose-multiplatform/issues/4197

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4368">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
