### ISSUE TITLE
Can I see logcat project compose mutilplatform in emulator IOS or android ?. I using android studio and import lib kermit logger but not show emulator IOS. 

### ISSUE THREAD

**Issue by thanhhoai162963** [JetBrains/compose-multiplatform#4373]
Can I see logcat project compose mutilplatform in emulator IOS or android?. I using android studio and import lib kermit logger but not show emulator IOS.

**Comment by dima-avdeev-jb** [comment]
You can see logs of iOS application in standart output stream in AndroidStudio or Xcode

<img width="955" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/fdc05d77-4872-4039-abec-6ab8a88352db">



For Android - you can use LogCat tab 

<img width="955" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/99798741/03975a11-06e7-45d8-bdbe-8cdce98b4fad">

**Comment by dima-avdeev-jb** [comment]
@thanhhoai162963 Is my answer good for you?

**Comment by thanhhoai162963** [comment]
Thanks you very much. I saw log in emulator ios, but I not filter logcat as logcat of android. Example filter "error:" in console android studio.

**Comment by dima-avdeev-jb** [comment]
Yes, for now filter feature is not available for iOS run configuration.
