### ISSUE TITLE
How to enable code obfuscation in ios

### ISSUE THREAD

**Issue by liufeng382641424** [JetBrains/compose-multiplatform#4374]
The project team would like the code to be kept confidential, and would like to enable obfuscation of the code on ios similar to the Android feature, I'm currently nearing completion of the project build but don't know how to enable obfuscation, and would like to get support for this. Thank you!

**Comment by elijah-semyonov** [comment]
@liufeng382641424 
Hello, what do you mean under `obfuscation` in this particular context? Compose on iOS is working on top of Kotlin Native: the Kotlin sources are compiled into machine code. It's not really possible to retrieve the original sources back from it.

**Comment by dima-avdeev-jb** [comment]
But I will ask about obfuscation possibilities and needness for iOS target in Kotlin team as well.

**Comment by liufeng382641424** [comment]
A shame indeed, is there an alternative? Or will support be prepared subsequently? Thank you!

**Comment by liufeng382641424** [comment]
@dima-avdeev-jb Hey, buddy, any luck with the discussion?

**Comment by elijah-semyonov** [comment]
@liufeng382641424 
We've approached Kotlin Native team and they said that there is no support and so far no plans for obfuscation tools.

They recommended to follow the general guidelines on how to protect the native binaries from reverse-engineering such as stripping symbols.

What is your specific case? You can't really decompile the Kotlin Native binary into a source code, so I'm wondering what you are trying to achieve.

**Comment by liufeng382641424** [comment]
@elijah-semyonov 
Team simply wanted to implement an Android-like obfuscation feature to secure private code.
As far as I know Flutter also has code obfuscation for iOS.
So I hope we can also implement code obfuscation for iOS.

Thanks buddy!

**Comment by PMARZV** [comment]
Is code shrinking and resource shrinking (like in android) on the table too?? Reducing app's size could be a great improvement (if its even possible to do it for ios)!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4374">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
