### ISSUE TITLE
How to encrypt, decrypt in compose mutilplatform ?

### ISSUE THREAD

**Issue by thanhhoai162963** [JetBrains/compose-multiplatform#4375]

**Comment by colinrtwhite** [comment]
Encryption/decryption is likely out of scope for Compose Multiplatform. You'll need to use a separate Kotlin Multiplatform library to accomplish this. [This might be what you're looking for.](https://github.com/whyoleg/cryptography-kotlin/tree/0.3.0)

**Comment by thanhhoai162963** [comment]
Thanks you very much. I used lib cryptography-mutilplatform and done features.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4375">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
