### ISSUE TITLE
I use ktor connect restful api, ios notify exception: ""A server with the specified hostname could not be found."

### ISSUE THREAD

**Issue by thanhhoai162963** [JetBrains/compose-multiplatform#4379]
failed with exception: io.ktor.client.engine.darwin.DarwinHttpRequestException: Exception in http request: Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x600002a54540 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en5, _kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <6528868F-F237-4581-B74A-DA90103621B3>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(

    "LocalDataTask <6528868F-F237-4581-B74A-DA90103621B3>.<2>"
<img width="1440" alt="Screenshot 2024-02-28 at 13 23 36" src="https://github.com/JetBrains/compose-multiplatform/assets/21314287/3abc1f75-a60f-4e5b-b4c8-a9464982d891">
<img width="1440" alt="Screenshot 2024-02-28 at 13 23 48" src="https://github.com/JetBrains/compose-multiplatform/assets/21314287/675aabe5-7845-425b-a74d-c8a259bc718b">

**Comment by pablichjenkov** [comment]
What url are you accessing? Seems to be invalid in iOS. Are you including paths in your hostname? I think iOS doesn't allow that.

**Comment by thanhhoai162963** [comment]
@pablichjenkov 

Tks you, my url : https://dev-apis.lizai.co/api/v1/Other/Hosts?appVersion=2.0&appType=1
I acccess in android app, and web, but ios emulator is not.

**Comment by pablichjenkov** [comment]
> @pablichjenkov 
> 
> Tks you, my url : https://dev-apis.lizai.co/api/v1/Other/Hosts?appVersion=2.0&appType=1
> I acccess in android app, and web, but ios emulator is not.

Try moving `/API/v1` out of the host and place them in the path

**Comment by MatkovIvan** [comment]
It is not related to Compose Multiplatform - it's a UI framework that doesn't deal with network requests at all.
Closing as invalid

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4379">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
