### ISSUE TITLE
[Desktop] Closing full screen is not working correctly

### ISSUE THREAD

**Issue by MohamedRejeb** [JetBrains/compose-multiplatform#4380]
**Describe the bug**
When I share the window state placement to `WindowPlacement.FullScreen` everything works fine but I change it back to `WindowPlacement.Maximized` it remains full screen.

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-rc02
- OS version(s)* (required for Desktop and iOS issues): MacOs 13.0.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Change window state placement to `WindowPlacement.FullScreen`
2. Change window state placement to `WindowPlacement.Maximized`
3. You will see that the window is still in full-screen mode.

This is a screen recording describing the issue:
https://github.com/JetBrains/compose-multiplatform/assets/41842296/4d7df284-b367-4452-bc34-8e7965425597

**Expected behavior**
The full-screen mode should be disabled.

This is a screen recording describing the expected behavior:
https://github.com/JetBrains/compose-multiplatform/assets/41842296/0b42c46e-b761-4f5b-b8d0-9e06e1ee366e

**Screenshots**

**Additional context**

**Comment by dima-avdeev-jb** [comment]
@MohamedRejeb Can you please create a minimal reproducible sample project on this problem and share it on GitHub?

**Comment by MohamedRejeb** [comment]
Here's a minimal reproducible sample project:
https://github.com/MohamedRejeb/CMPIssue4380

It's happening only for macos, try to click: floating -> fullscreen -> floating and the placement will end up maximized.
Also you can try fullscreen -> maximized and the fullscreen will exit correctly.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4380">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
