### ISSUE TITLE
Can I set edge to edge as android for ios and set color tranparent system bar ?

### ISSUE THREAD

**Issue by thanhhoai162963** [JetBrains/compose-multiplatform#4390]

**Comment by thanhhoai162963** [comment]
If you answer like that, write in swift code and "Closing". So should I write in kotlin mutilplatform or compose mutilplatform ? What is the purpose of compose mutilplatform to share logic and UI in one place?
@MatkovIvan

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4390">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
