### ISSUE TITLE
Can't access exposed resource from core module (iOS)

### ISSUE THREAD

**Issue by mpierucci** [JetBrains/compose-multiplatform#4392]
**Describe the bug**
In order to bypass the current limitation of multi modules ntonotsupported,  we add all the resources in a core module and then expose them through composable functions.
This works as expected on Android, but on iOS we get the exception:
`org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: values/strings.xml`
[Reproducer Project](https://github.com/mpierucci/ComposeMPResourcesIssue)

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*:  1.6.0
- OS version(s)* (required for Desktop and iOS issues):  15
- OS architecture (x86 or arm64):  simulator

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Clone the provided reproducer project
2. Run the iOS App
3. Click on "Click me!" Button
5. See error

**Expected behavior**
The app should not crash on iOS and the resource should be shown.

**Screenshots**

**Additional context**
Note that the reproducer project was created with the late [wizard](https://kmp.jetbrains.com/) and was only modified to expose the resources from a resource module.
Running the android app does not have any issues

**Comment by terrakok** [comment]
> In order to bypass the current limitation of multi modules ntonotsupported, we add all the resources in a core module and then expose them through composable functions.

resources must be in app module

**Comment by mpierucci** [comment]
> > In order to bypass the current limitation of multi modules ntonotsupported, we add all the resources in a core module and then expose them through composable functions.
> 
> resources must be in the top level app module

Does that means that is there no work around at all for project with feature modules? Essentially not being able to use the library at all?

If so is there a rough estimate  on when would that be possible? ( Just to decide if we can wait or we should pick another library)

**Comment by terrakok** [comment]
The first dev builds will be available soon but it will rtequire the kotlin gradle plugin 2.0+

It doesn't work as you expected on the android target. JVM ecosystem has binary for each module (jars) and it supports resources. Kotlin ecosystem doesn't have a resources support yet.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4392">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
