### ISSUE TITLE
The Windows should follow the system theme

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/compose-multiplatform#4393]
The `androidx.compose.ui.window.Window` should follow the system theme or provide a boolean to enable the dark mode.

Right now it's always in light mode. At least for macOS.

<img width="1026" alt="grafik" src="https://github.com/JetBrains/compose-multiplatform/assets/9299303/036c6126-234b-4b64-aec2-643bef243b78">

**Comment by m-sasha** [comment]
You can control this by setting the "apple.awt.application.appearance" system property to "system", e.g. by passing `-Dapple.awt.application.appearance=system` to Java.

**Comment by alexzhirkevich** [comment]
You can take a look at https://github.com/jetBrains/jewel. I use it for title bar styling. Pretty flexible tool that allows you to fully customize title bar while maintaining native-looking window decorations

**Comment by m-sasha** [comment]
@StefanOltmann Can we close this?

**Comment by StefanOltmann** [comment]
@m-sasha The option works. I would suggest to add this per default.

If you don't think this should be a default, we can close the issue.

**Comment by m-sasha** [comment]
I don't think this is such a big deal that breaking existing apps is worth it.

**Comment by igordmn** [comment]
The same issue encountered from an internal user.

If not changing default, we should provide docs/API (`apple.awt.application.appearance` is an AWT constant, which is implementation details) and change templates. Though, changing the default is also an option, we can't avoid behaviour changes between versions.

**Comment by igordmn** [comment]
Actually, we have an older issue. Let's keep only it: https://github.com/JetBrains/compose-multiplatform/issues/3928

**Comment by StefanOltmann** [comment]
Sorry, @igordmn, I did not find the other issue back then.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4393">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
