### ISSUE TITLE
Compose 1.6 js and wasmJs consume browser shortcuts

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-multiplatform#4399]
**Describe the bug**
Compose 1.6 (I tested back to beta01) seemingly consumes certain browser shortcuts like the dev tools with CTL+SHFT+i in Chrome and Firefox.

**Affected platforms**
- [x] Web (K/Wasm) - Canvas based API
- [x] Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 22.04
- OS architecture (x86 or arm64): x86

**To Reproduce**
Run an app containing just `CanvasBasedWindow("Title") {}` and see that keyboard shortcuts aren't working.

**Expected behavior**
That the browser handles the keyboard shortcuts.

**Comment by eygraber** [comment]
This is working now, thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4399">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
