### ISSUE TITLE
:configureDesktopPreviewJvm doesn't work without android.useAndroidX=true

### ISSUE THREAD

**Issue by singleton11** [JetBrains/compose-multiplatform#4403]
Mostly user experience issue, why should I care about android when I'm trying to create for instance JVM desktop app

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4403">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
