### ISSUE TITLE
Resource Library: No code-gen if using "api" instead of "implementation"

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/compose-multiplatform#4405]
It must be `implementation(compose.components.resources)` for code-gen to work, not `api(compose.components.resources)`. If using `api(compose.components.resources)` no `Res` class will be generated.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4405">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
