### ISSUE TITLE
Compose resources are not packages into APK with AGP 8.2.2

### ISSUE THREAD

**Issue by terrakok** [JetBrains/compose-multiplatform#4407]
**Describe the bug**
Gradle 8.6
AGP 8.2.2
Compose 1.6.0

If a project was built with `./gradlew build` it is broken because a resulting APK doesn't have resources inside

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4407">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
