### ISSUE TITLE
Using cocoapods in kmp library 

### ISSUE THREAD

**Issue by ismai117** [JetBrains/compose-multiplatform#4409]
I'm using the lottie-ios pod inside a library that I created. Whenever someone wants to use my library, they also have to add cocoapods and the lottie-ios pod. 

I just want developers to use my library by adding the dependency inside the commonMain sourceset and continue with their project without the extra steps of adding cocoapods.

Is there any way to add iOS libraries without using cocoapods?

**Comment by pablichjenkov** [comment]
In general that is the way `manually adding` dependencies work. If you want automatic distribution you will have to distribute it as a pod.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4409">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
