### ISSUE TITLE
Adding Offset to specify topLeft of drawArc produces different results in Android when comparing to Desktop & Wasm

### ISSUE THREAD

**Issue by GuilhE** [JetBrains/compose-multiplatform#4411]
**Describe the bug**
Adding `Offset` to specify `topLeft` of `drawArc`  produces different results in Android when comparing to Desktop & Wasm.

**Affected platforms**
- Android
- Desktop (Windows, Linux, macOS)
- iOS
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version: `1.9.22` 
- Compose Multiplatform version: `1.6.0`
- OS version(s)* (required for Desktop and iOS issues): `macOS 14.3.1 (23D60)`
- OS architecture (x86 or arm64): `arm64`
- JDK (for desktop issues): `17`

**To Reproduce**
1 - Use [Kotlin Multiplatform Wizard](https://kmp.jetbrains.com/) and select Android, Desktop and Wasm
2 - Replace `App` composable with:

```
@Composable
@Preview
fun App() {
    Box(
        Modifier
            .fillMaxSize()
            .background(Color.LightGray),
        contentAlignment = Alignment.Center
    ) {
        Canvas(Modifier.size(250.dp)) {
            val sweepAngle = 180f
            val startingAngle = 270f
            val ringRadius = size.minDimension * 0.15f
            val size = Size(size.width, size.height)
            drawArc(Color.Black, startingAngle, sweepAngle, false, Offset(0f, 50f), size, 0.2f, Stroke(ringRadius, cap = StrokeCap.Round))
            drawArc(Color.White, startingAngle, sweepAngle, false, size = size, style = Stroke(ringRadius, cap = StrokeCap.Round))
        }
    }
}
```
3 - Run and compare Android with Desktop and/or Wasm

**Expected behavior**
Same visual result for `Offset(0f, 50f)` in all platforms, instead of having Android with less "vertical translation".

**Screenshots**
![1](https://github.com/JetBrains/compose-multiplatform/assets/2677139/908c2fe8-048c-4798-8eb7-2c6cbe296c4d)
![2](https://github.com/JetBrains/compose-multiplatform/assets/2677139/73905b7d-d7f7-4e5f-a4af-33c5b615e71b)
![3](https://github.com/JetBrains/compose-multiplatform/assets/2677139/3472d54e-5cae-4488-9f5f-c43bfcd37bb9)

**Comment by kirill-grouchnikov** [comment]
You’re probably not accounting for the difference in density

**Comment by kirill-grouchnikov** [comment]
Your ring radius is effectively in dp units since it’s based on the canvas size which is in dp. Same for the stroke width. But not that offset.

**Comment by GuilhE** [comment]
I've tried with `Offset(0f, 50.dp.value)` and obtained the same output 🤔

**Comment by kirill-grouchnikov** [comment]
You need to do Dp.toPx()

**Comment by GuilhE** [comment]
> You need to do Dp.toPx()

Of course... 🤦🏼 
Thanks @kirill-grouchnikov 👍🏼

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4411">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
