### ISSUE TITLE
Performance regression in Web in 1.6.0

### ISSUE THREAD

**Issue by mahozad** [JetBrains/compose-multiplatform#4412]
**Describe the problem**
After updating to compose multiplatform 1.6.0 and adjusting the code:

```diff
- Window(title = "App") {
+ CanvasBasedWindow(
+     title = "App",
+     canvasElementId = "content",
+     applyDefaultStyles = false,
+     requestResize = { IntSize(width = 900, height = 800) }
+ ) {
```

```diff
Icon(
-   painterResource("m$n-logo.png"),
+   painterResource(DrawableResource("m$n-logo.png")),
```

```diff
- @OptIn(ExperimentalResourceApi::class)
+ @OptIn(InternalResourceApi::class)
suspend fun loadResource(path: String): ByteArray {
-    return resource(path).readBytes()
+    return readResourceBytes(path)
}
```

```diff
- <canvas id="ComposeTarget" width="900" height="800">Loading</canvas>
+ <canvas id="content"></canvas>
```

the web app performance is much worse than what it was in 1.5.10.

**Affected platforms**
- Web (K/JS) - Canvas based API
- Web (K/Wasm) - Maybe

**Versions**
- Kotlin version: 1.9.22
- Compose Multiplatform version: 1.6.0
- OS: Windows 11
- browser: chrome 122
- JDK (for desktop issues): 17

**Sample code**
See the [source code here](https://github.com/mahozad/wavy-slider/blob/website-source/showcase/src/jsMain/kotlin/Main.kt).
And the [live demo here](https://mahozad.ir/wavy-slider/).

**Additional information**
I am facing this on a system that has no dedicated graphics card (so it uses CPU to render?).

**Comment by eymar** [comment]
Do you notice it only on a system without a dedicated GPU?

I see these errors in the console:
<img width="754" alt="Screenshot 2024-03-12 at 11 10 19" src="https://github.com/JetBrains/compose-multiplatform/assets/7372778/121728b1-5fae-4a66-a36b-dcfc4e598778">

I'm wondering if there were the same errors with 1.5.1x versions? I couldn't quickly find a working commit with 1.5.x in your repo to try it. 

Btw, on my laptop I don't notice any performance issues with your app (the wave runs smoothly and Ui is responsive. But it has a GPU.

**Comment by mahozad** [comment]
Hello. The performance is bad on Chrome in an Android phone as well.

I too see those errors in the console.

On that system tried to run `jsBrowserRun` with cmp 1.5.12, 1.5.10, 1.5.0 and kotlin 1.9.22, 1.9.10 and all failed with the below error:
https://github.com/JetBrains/compose-multiplatform/issues/4003:

```
kotlin.NotImplementedError: Generation of stubs for class org.jetbrains.kotlin.ir.symbols.impl.IrValueParameterSymbolImpl is not supported yet
```

On my system performance is not as bad but it was better in previous versions.

**Comment by eymar** [comment]
Did you have the same app built with 1.5.1x versions? We would try to compare it with one built with 1.6.0. 

The error:
> kotlin.NotImplementedError: Generation of stubs for class org.jetbrains.kotlin.ir.symbols.impl.IrValueParameterSymbolImpl is not supported yet

It could mean there's a library incompatible with other libraries in your project. For example when you updated one library ("A") to a newer verision, but you also have another lib which depends on older version of "A".

**Comment by RafaelAthosPrime** [comment]
Maybe related to #4199 ?

**Comment by mahozad** [comment]
> Did you have the same app built with 1.5.1x versions? We would try to compare it with one built with 1.6.0.

Yes. But now cannot change the versions back to 1.5.1x and test the app again because of the error #4003.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4412">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
