### ISSUE TITLE
Android @Preview: Could not load font shared by composeResources

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#4416]
Hi
I have some fonts inside `commonMain/composeResources/font` directory and i share that to Android `res` directory with following code in gradle:
```
android {
    ...
    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    sourceSets["main"].res.srcDirs("src/androidMain/res")
    sourceSets["main"].res.srcDirs("src/commonMain/composeResources")
    
    ...
}
```

Now i use that fonts in androidMain directory with `FontFamily(Font(R.font.font_m))` i get the following error when i want show in @preview mode:

```
@PreviewScreenSizes
@Preview
@Composable
private fun Preview() {
    Theme {
        Text(text = "test", fontFamily = FontFamily(Font(R.font.font_m)))
    }
}
```
Error:
`Could not load font`

i have this problem only for `font` (not `drawable`) and only in `@preview` mode in androidMain.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4416">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
