### ISSUE TITLE
How can I change the App Name in macOS

### ISSUE THREAD

**Issue by michaellee123** [JetBrains/compose-multiplatform#4417]
I found many docs, but I can't do that, it shows `MainKt` but I can't change it.
<img width="114" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/18477367/e3ac4e20-a571-4d8a-8940-31f79360c14e">

**Comment by MatkovIvan** [comment]
Compose uses AWT for window management under the hood, so you can change it by AWT's system property: `apple.awt.application.name`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4417">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
