### ISSUE TITLE
Support `BackHandler`/`PredictiveBackHandler`

### ISSUE THREAD

**Issue by thanhhoai162963** [JetBrains/compose-multiplatform#4419]
Can I handle backHandle in compose mutilplatform as jetpack compose BackHandle {...} ?

**Comment by MatkovIvan** [comment]
This API is not ported to Compose Multiplatform yet

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4419">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
