### ISSUE TITLE
At startup, the window is black. Drag the window size or maximize the window will report an error

### ISSUE THREAD

**Issue by ghost** [JetBrains/compose-multiplatform#442]
https://user-images.githubusercontent.com/76673990/109390528-2b402980-794d-11eb-9d47-7ff590cca2ad.mp4

[hs_err_pid9612.log](https://github.com/JetBrains/compose-jb/files/6054653/hs_err_pid9612.log)

**Comment by xiao-cao-depot** [comment]
Version is 0.4.0-build168

**Comment by alialbaali** [comment]
Have you tried with `0.3.1`?

**Comment by xiao-cao-depot** [comment]
> 你试过吗？`0.3.1`

The latest version only has this problem, the previous version does not have this problem

**Comment by alialbaali** [comment]
`0.3.1` released after `0.4.0-build168`.

**Comment by olonho** [comment]
Please try OpenGL renderer by setting `SKIKO_RENDER_API` to `OPENGL` or `SOFTWARE`.

**Comment by Rsedaikin** [comment]
Could you please give your PC specification?
OS version: ?
Graphics card: ?
Graphics card driver version: ?

**Comment by xiao-cao-depot** [comment]
![OS version](https://user-images.githubusercontent.com/76673990/109789327-321bb480-7c4b-11eb-9f7a-2a279a3d95be.png)
![Graphics card and Driver](https://user-images.githubusercontent.com/76673990/109789335-33e57800-7c4b-11eb-824e-c81d34a1ef54.png)

**Comment by Rsedaikin** [comment]
Could you please check if the example from [skiko](https://github.com/JetBrains/skiko) works?
To build `skiko` you need to run in terminal `./gradlew publishToMavenLocal` from `skiko/skiko` directory.
To run the example (rendering clocks) you need to run in terminal `./gradlew run` from `skiko/samples/SkijaInjectSample` directory.
For more info on how to build `skiko`, please read the manual on the [skiko](https://github.com/JetBrains/skiko) github repository.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5480">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
