### ISSUE TITLE
Res object isn't generated when resources is imported via api DependencyHandler

### ISSUE THREAD

**Issue by amrfarid140** [JetBrains/compose-multiplatform#4420]
**Describe the bug**
In order to use compose resources you have to depend on the resources package in your gradle dependencies

`implementation(compose.components.resources)`

If I want to expose compose resources type to the android or iOS app, I would use `api` instead but using `api(compose.components.resources)` doesn't generate the `Res` object or any resource accessor.

**Affected platforms**

- [x] Desktop (Windows, Linux, macOS)
- [x] iOS
- [ ] Web (K/Wasm) - Canvas based API
- [x] Web (K/JS) - Canvas based API
- [ ] Web (K/JS) - HTML library

**Versions**
- Kotlin version*: 1.9.21
- Compose Multiplatform version*:  1.6.0
- OS version(s)* (required for Desktop and iOS issues): N/A
- OS architecture (x86 or arm64): N/A
- Device (model or simulator for iOS issues):  N/A
- JDK (for desktop issues):  N/A

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Use any compose sample project
2. Replace `implementation(compose.components.resources)` with `api(compose.components.resources)`
3. See error in compilation

**Expected behavior**
`Res` object and resource accessors are generated

**Comment by igordmn** [comment]
Also reported here: https://github.com/JetBrains/compose-multiplatform/issues/4405

And fixed here: https://github.com/JetBrains/compose-multiplatform/pull/4406

It will be included in 1.6.1

**Comment by bmc08gt** [comment]
> Also reported here: #4405
> 
> And fixed here: #4406
> 
> It will be included in 1.6.1

Any timeline for 1.6.1?

**Comment by igordmn** [comment]
in 2 weeks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4420">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
