### ISSUE TITLE
Crash on Scroll and Scroll-to-Top Button Press in Compose 1.6.0 (iOS)

### ISSUE THREAD

**Issue by topmotree** [JetBrains/compose-multiplatform#4422]
**Describe the bug**
When the application is scrolled rapidly downwards and the button to scroll back to the top is pressed, the application crashes. Additionally, the same exception occurs when changing the direction of the scroll. Initially observed in our company's project, I reproduced the error in the provided demo app: https://github.com/martinskindustries/imageviewer.
The error is specific to iOS and occurs only in Compose version 1.6.0. Previous versions (1.5.x) do not have this issue. The error occurs in both debug and release builds.

**Affected platforms**
- iOS

**Versions**
- Kotlin version: 1.9.22
- Compose Multiplatform version: 1.6.0 

**To Reproduce**
1. Open the demo app 
2. Rapidly scroll to the bottom of the page.
3. Press the button to scroll back to the top.

Video with exception: 
https://github.com/JetBrains/compose-multiplatform/assets/64073182/4edac29e-ff6c-4e7b-a2a3-cad4a820606c

**Screenshots**
![compose160-error](https://github.com/JetBrains/compose-multiplatform/assets/64073182/cb831f10-bd6f-4476-a304-36f089832a28)

**Comment by elijah-semyonov** [comment]
Thanks for the report, I'll look into it

**Comment by elijah-semyonov** [comment]
Minimised repro:
```
@Composable
fun RowItem(index: Int) {
    Row(modifier = Modifier.padding(end = 30.dp)) {
        var state by remember(index) { mutableStateOf<Unit?>(null) }

        LaunchedEffect(index) {
            delay((100..200).random().toLong())
            state = Unit
        }
        state?.let {
            Text("Item $index")
        }
    }
}

@Composable
fun RowItem(wrapInBox: Boolean, index: Int) {
    if (wrapInBox) {
        Box {
            RowItem(index)
        }
    } else {
        RowItem(index)
    }
}

@Composable
fun Repro() {
    val lazyColumnState = rememberLazyListState()
    var enableCrash by remember { mutableStateOf(false) }

    Column(
        modifier = Modifier.safeContentPadding()
    ) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Checkbox(
                checked = enableCrash,
                onCheckedChange = { enableCrash = it },
                modifier = Modifier.padding(16.dp),
            )

            Text("Enable crash")
        }
        Box(Modifier.fillMaxSize(), contentAlignment = Alignment.TopCenter) {
            LazyColumn(
                verticalArrangement = Arrangement.spacedBy(8.dp),
                state = lazyColumnState,
            ) {
                items(1000) { index ->
                    RowItem(enableCrash, index)
                }
            }
        }
    }
}

```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4422">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
