### ISSUE TITLE
Android DatePicker implementation doesn't take into account YearRange

### ISSUE THREAD

**Issue by xavimolloy** [JetBrains/compose-multiplatform#4423]
**Describe the bug**

Compose multiplatform datepicker does not respect allowed year range when consuming the android artifact form an android app. 

It works as expected when testing it in the library but behaves differently when consuming it from an android app. 

i've noticed that this also happens with things like colors and paddings, sometimes it works fine from the multiplatform project library, but behaves differently when consuming the actual component. 

**Affected platforms**

- [ ] Desktop (Windows, Linux, macOS)
- [ ] iOS
- [ ] Web (K/Wasm) - Canvas based API
- [ ] Web (K/JS) - Canvas based API
- [ ] Web (K/JS) - HTML library

**Versions**
- Kotlin version*: 
- Compose Multiplatform version*: 
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64):
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

create a custom Datepicker for a Multiplatform library that allows you to pass the year range as a parameter
consume the component from an android device
Observe that the allowed year range is not detected and goes to default

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by igordmn** [comment]
Please, create the issue in the Jetpack Compose tracker: https://issuetracker.google.com/issues/new?component=612128. The Android target is maintained there. Also, better to describe the issue there in more detail, with a code snippet, steps, actual and expected behaviour.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4423">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
