### ISSUE TITLE
Compose 1.6.0 crashes after quick resizing (Direct3d)

### ISSUE THREAD

**Issue by vladyslavv-ua** [JetBrains/compose-multiplatform#4425]
**Describe the bug**
When i collapse window to very small size and after that quickly expand my app craches in Direct3d and creates error log or do it very laggy in OPENGL. In 
System.setProperty("skiko.renderApi", "SOFTWARE") all works good

**Affected platforms**

- [ ] Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0
- OS version(s)* (required for Desktop and iOS issues): Win 11 Pro 23H2 22631.3155
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): 17.0.2

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Go to https://github.com/vladyslavv-ua/compose-desktop-discoloured-bug
2. Download project
3. Run gradle task "compose desktop -> run"
4. Collapse window as much as possible (like on the video)
5. Sharply expand
6. See crash in direct3d or lagging expansion in openGL

**Expected behavior**
A smoothly resizing

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/110237787/1cee8845-cca5-4e2b-bff2-612c0ba1eb5e

**Additional context**
Here is error log
[hs_err_pid1084.log](https://github.com/JetBrains/compose-multiplatform/files/14483417/hs_err_pid1084.log)

**Comment by MatkovIvan** [comment]
Let's track here only a crash, "laggy" part is not regression and there is a separate issue for that - #2925

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4425">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
