### ISSUE TITLE
I think foundation-layout-desktop-1.6.0-dev1369-sources.jar is malformed

### ISSUE THREAD

**Issue by juancnuno** [JetBrains/compose-multiplatform#4427]
I'm trying to examine the sources for foundation-layout-desktop-1.6.0-dev1369.jar in IDEA and even though the sources JAR is present IDEA is not loading them. I took a look at the JAR with GNOME Archive Manager and the root listing looks like

commonMain
jvmMain
META-INF
notMobileMain
skikoMain

I clicked into commonMain and see the root package directory (androidx) as expected

That's not right, is it?

**Comment by rock3r** [comment]
CC @igordmn, is this related to the malformed POMs?

**Comment by igordmn** [comment]
> the root listing looks like

It looks right, this is how multiplatform libraries are published. I checked the previous versions and side Compose libraries - they look the same way.

As for non available sources - I am not completely sure yet, but it seems reproducible on projects with `kotlin(jvm)` ( `kotlin("multitplatform")` works well). I will post details later.

> CC @igordmn, is this related to the malformed POMs?

It seems unrelated.

**Comment by juancnuno** [comment]
Hm. I just met with rock3r and he encouraged me to file an IDEA bug. But now I can see the sources and can't seem to reproduce my original issue. I'm personally inclined to close this but I'll leave that up to you folks.

**Comment by rock3r** [comment]
If it is WAI now I'd close this, and if it happens again file a bug against IJ

**Comment by igordmn** [comment]
It seems that this checkbox should be enabled for auto-source downloading:
<img width="739" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5963351/f8bc2181-c23d-49fb-9043-6fba3f2ee06e">

(I didn't find it in Android Studio)

I don't know why it is disabled by default, and why it auto-download in `kotlin("multiplatform)"` projects. You can create an issue in [IDEA tracker](https://youtrack.jetbrains.com/issues/IDEA) for clarification.

**Comment by rock3r** [comment]
Studio auto-downloads dependencies by default (overriding the IJ setting to default to enabled) as far as I know, as most Android devs expect this to be the case.

As for the auto-download setting in IJ, the canonical issue from yours truly complaining about it being nonsense: https://youtrack.jetbrains.com/issue/IDEA-333402/New-Gradle-behaviour-of-not-downloading-sources-is-confusing 😁

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4427">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
