### ISSUE TITLE
Compose 1.6.0 full recomposition after keyboard appearing (iOS)

### ISSUE THREAD

**Issue by piskunovvitaly** [JetBrains/compose-multiplatform#4434]
**Describe the bug**
When we click on any input to bring up the keyboard, we trigger a full recomposition several times starting with the ComposeUIViewController.
This bug is specific to iOS and only occurs in Compose version 1.6.0. In previous versions (1.5.x) this problem do not exist.

**Affected platforms**

- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Open any sample project with TextField
2. Click on TextField

**Expected behavior**
Lack of full recomposition

**Comment by babramovitch** [comment]
A workaround if you don't rely on any other iOS animation in the meantime is to disable animations

```
@main
struct iOSApp: App {
    
    init() {
        FirebaseApp.configure()
        UIView.setAnimationsEnabled(false)
    }
    
	var body: some Scene {
		WindowGroup {
		    ZStack {
			    ContentView()
            }.preferredColorScheme(.dark).ignoresSafeArea(.keyboard)
		}
	}
}
```

**Comment by solita-michalguspiel** [comment]
This also causes unnecessary recompositions even after text field interaction. I describe my issue in a bigger detail [in kotlin slack]( https://kotlinlang.slack.com/archives/C0346LWVBJ4/p1711461703746609)

`UIView.setAnimationsEnabled(false)` fixes it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4434">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
