### ISSUE TITLE
iOS. Reduce recompositions during keyboard showing

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4435]
Compose 1.6.0

When iOS keyboard appears, the whole app recomposes. It most probably happens because in https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/uikit/KeyboardOverlapHeight.uikit.kt#L27 `staticCompositionLocalOf` is used. `staticCompositionLocalOf` recomposes the whole UI tree every time it changes. As changing the height of the keyboard is an often thing, it is not a good thing to recompose everything.

If keyboard is animated, the whole app recomposes every frame.

The solution is to replace `staticCompositionLocalOf` by `compositionLocalOf`.

**Comment by igordmn** [comment]
Reported here https://github.com/JetBrains/compose-multiplatform/issues/4434

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4435">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
