### ISSUE TITLE
Separate window feature for popups/dropdowns doesn't work on Linux Desktop

### ISSUE THREAD

**Issue by Nohus** [JetBrains/compose-multiplatform#4437]
**Describe the bug**
When the feature is enabled, popups/dropdowns don't show up correctly and can even break rendering of the original window at times.

**Affected platforms**
- Desktop (Linux)

**Versions**
- Kotlin version: 1.9.21
- Compose Multiplatform version: 1.6.0
- OS version(s): Kubuntu 23.10
- OS architecture: x86
- JDK: openjdk-17

**To Reproduce**
1. Enable the feature with `System.setProperty("compose.layers.type", "WINDOW")`
2. Trigger a popup or dropdown, for example with `TooltipArea()`.
3. Popup does not render correctly.

**Videos**
Feature disabled, dropdown and tooltip work correctly:
<video src="https://github.com/JetBrains/compose-multiplatform/assets/11064768/192a6d70-dfc6-484e-8ba0-5ead8847ba8e"/>

Feature enabled, dropdown and tooltip do not work:
<video src="https://github.com/JetBrains/compose-multiplatform/assets/11064768/8eed7095-a90c-4a80-ba65-7c1f1396319f"/>

**Additional context**
This may be related to transparent window issues on Linux:
- https://github.com/JetBrains/compose-multiplatform/issues/1339
- https://bugs.openjdk.org/browse/JDK-8304900

But transparent windows do work on Linux as long as they are not dragged to a second monitor, and even then the transparency is just disabled, where here the bug is always present and results in glitches, so might or might not be related.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4437">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
