### ISSUE TITLE
Unresolved reference: rememberDismissState & Unresolved reference: DismissState

### ISSUE THREAD

**Issue by razaghimahdi** [JetBrains/compose-multiplatform#4439]
In version of 1.6.0, I get these:
Unresolved reference: rememberDismissState 
Unresolved reference: DismissState

In 1.5.10 everything used to be working. any solution?

**Comment by razaghimahdi** [comment]
replace with:
androidx.compose.material3.SwipeToDismiss
androidx.compose.material3.SwipeToDismissBox
androidx.compose.material3.SwipeToDismissBoxValue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4439">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
