### ISSUE TITLE
jvm/macos could not request location permission

### ISSUE THREAD

**Issue by Gaubee** [JetBrains/compose-multiplatform#4441]
**Describe the bug**
when I call `clLocationManager.requestWhenInUseAuthorization()` in macos, there has not system dialog showed for ask.
I have config in my build.gradle.kts like this:
```kotlin
compose.desktop {
  application {
    nativeDistributions {
      macOS {
        infoPlist {
          extraKeysRawXml = """
          <key>NSLocationUsageDescription</key>
          <string>Some Location Usage Description</string>
          <key>NSLocationAlwaysUsageDescription</key>
          <string>Privacy - Location Always Usage Description</string>
          <key>NSLocationTemporaryUsageDescriptionDictionary</key>
          <dict/>
          <key>NSLocationDefaultAccuracyReduced</key>
          <false/>
          <key>NSLocationWhenInUseUsageDescription</key>
          <string>Location When In Use Usage Description</string>
          <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
          <string>Location Always and When In Use Usage Description</string>
          """.trimIndent()
        }
        entitlementsFile.set(projectDir.resolve("composeApp.entitlements"))
        runtimeEntitlementsFile.set(projectDir.resolve("composeApp.entitlements"))
      }
```
the `composeApp.entitlements` file content is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.cs.debugger</key>
    <true/>
    <key>com.apple.security.device.audio-input</key>
    <true/>
	<key>com.apple.security.files.user-selected.read-only</key>
	<true/>
	<key>com.apple.security.personal-information.location</key>
	<true/>
</dict>
</plist>

```

**Affected platforms**

- Desktop (macOS)

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0
- MacOS version(s)*: 14.3.1 (23D60)
- OS architecture: arm64
- JDK: 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
> none.
>
> it request jni, so the whole project can be a bit cumbersome to configure. 
>
> So I want to know if there is something wrong with my configuration, or is this a bug?
> I searched github all over the Web, but couldn't find anyone trying to apply for NSLocation permission in kotlin-multiplatform-jvm-macos. I could be the first?

**Screenshots**
1. I use kotlin to create an dylib:
   ![image](https://github.com/JetBrains/compose-multiplatform/assets/2151644/3c77af0f-9390-487b-ac67-05ab654360de)
2. I use rust to implement jni project:
   ![image](https://github.com/JetBrains/compose-multiplatform/assets/2151644/ece394ed-d6e0-4bf4-a8f3-5b19ccd6a4aa)
3. load dylib in kotlin/jvm:
   ![image](https://github.com/JetBrains/compose-multiplatform/assets/2151644/0c746d4d-eccb-445a-9a00-f8cf7182802e)
4. call in kotlin/jvm/composeApp, and log is:
   ![image](https://github.com/JetBrains/compose-multiplatform/assets/2151644/e7f76cce-ca4c-47ea-aa8d-c9afe52b555e)
   ```log
   QAQ permission requesting: 0
   QAQ permission requested: 0
   ```

**Comment by waterbang** [comment]
I also encountered this kind of situation, is my permission setting not effective?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4441">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
