### ISSUE TITLE
Res class not generated for commonTest only resources

### ISSUE THREAD

**Issue by luca992** [JetBrains/compose-multiplatform#4442]
**Describe the bug**
I would like to have multiplatform resources only in my `commonTest` source set where the dependency on `compose.components.resources` is only added in `commonTest` like:

```
val commonTest by getting {
    dependencies {
        implementation(compose.components.resources)
    }
}
```

This does not work and the `Res` is not generated. I have to add `implementation(compose.components.resources)` in `commonMain` for `Res` to be generated.

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0

**To Reproduce**
Add resources to `commonTest/composeResources`  (not `commonMain`) and set:

```
val commonTest by getting {
    dependencies {
        implementation(compose.components.resources)
    }
}
```

**Expected behavior**
`Res` class is generated for `commonTest` only

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4442">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
