### ISSUE TITLE
iOS TextField crash when using speech-to-text

### ISSUE THREAD

**Issue by kodebach** [JetBrains/compose-multiplatform#4443]
**Describe the bug**
When using the builtin iOS speech-to-text feature to enter text into a TextField the app crashes with a stack trace pointing to Compose Multiplatform.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0
- OS version(s)*: confirmed on iOS 15.8 and 17.3.1
- OS architecture: arm64
- Device: confirmed on iPhone 7 (iOS 15.8) and iPhone XR (iOS 17.3.1)

**To Reproduce**
1. Run an iOS app with a Compose Multiplatform TextField
2. Tap the TextField to bring up the keyboard
3. Tap the microphone icon to start speech-to-text
4. Say something and wait for speech-to-text recognition
5. App crashes

**Expected behavior**
No crash, and speech-to-text recognized text entered into TextField.

**Additional context**

It seems speech-to-text did work at some point: https://github.com/JetBrains/compose-multiplatform/issues/2984

We have two similar but slightly different stack traces from production builds. The first one looks like this:

```
0   App             0x102e341d0 kfun:androidx.compose.ui.platform.toTextIterator#internal + 1040 (UIKitTextInputService.uikit.kt:0)
1   App             0x102e334a4 kfun:androidx.compose.ui.platform.UIKitTextInputService.object-2.isPositionAtBoundary#internal + 180 (UIKitTextInputService.uikit.kt:568)
2   App             0x102e57c78 kfun:androidx.compose.ui.platform.IOSSkikoInput#isPositionAtBoundary(kotlin.Int;platform.UIKit.UITextGranularity;kotlin.Long){}kotlin.Boolean-trampoline + 200 (IOSSkikoInput.uikit.kt:140)
3   App             0x102e57c78 kfun:androidx.compose.ui.window.IntermediateTextInputUIView.object-1.isPosition#internal + 492 (IntermediateTextInputUIView.uikit.kt:554)
4   App             0x1035def7c _6f72672e6a6574627261696e732e636f6d706f73652e75693a75692f6f70742f6275696c644167656e742f776f726b2f383339343731666333323931333563372f636f6d706f73652f75692f75692f7372632f75696b69744d61696e2f6b6f746c69... + 336
5   UIKitCore       0x184545094 +[UIDictationUtilities needsTrailingSpaceForPhrases:secureInput:] + 556 (UIDictationUtilities.m:388)
....
```

The second kind is almost identical, but the `UIDictationUtilities` method that calls into Compose is `selectionStartInfoWithBlock` instead.

In a debug build, we couldn't tell what UIKit method calls into Compose, but we found that a `kotlin.NotImplementedError` is thrown here:

https://github.com/JetBrains/compose-multiplatform-core/blob/99c5d1d3bd7eba7dbebcd42af0897f8862291822/compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/platform/UIKitTextInputService.uikit.kt#L614

```kotlin
UITextGranularity.UITextGranularityParagraph -> TODO("UITextGranularityParagraph iterator")
```

Is there any way for us to work around this issue, or is speech-to-text broken until Compose Multiplatform implements these TODOs?

**Comment by jxdom** [comment]
I also encountered the same problem. When I use voice input, the iOS app crashes. I'm using iOS 17.4.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4443">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
