### ISSUE TITLE
[Question] How to know when ImageBitmap has been rendered by Compose, so ByteArray can be updated? (Desktop Video Rendering)

### ISSUE THREAD

**Issue by yaroslavkulinich** [JetBrains/compose-multiplatform#4446]
I'm trying to create stable logic of rendering video using pure Compose to avoid using Swing interop on Desktop.
I have simple and efficient implementation with following steps:
1. receive frame from video framework (Gstreamer) as `ByteBuffer`;
2. get all bytes to my `ByteArray` buffer with `get()` + `rewind()`;
3. install that array of bytes to `Bitmap` (also used as buffer to avoid unnecessary creation);
4. convert that `Bitmap` to `ComposeBitmap` using `.asComposeImageBitmap()` extension function;
5. update Compose mutable state;
6. take this state in my Composable element and use it in `Image()` element;

```
private var buffer: ByteArray = ByteArray(0)
private var bufferBitmap: Bitmap = Bitmap()
var frameImage by mutableStateOf<ImageBitmap?>(null)

fun prepareBuffers(width: Int, height: Int) {
     bufferBitmap.allocN32Pixels(width, height, true)
     buffer = ByteArray(width * height * 4)
}

// called by gstreamer AppSink.onSample() in gstreamer's thread 
fun updateBuffer(byteBuffer: ByteBuffer) {
     // get bytes from buffer
     byteBuffer.let {
         it.get(buffer)
         it.rewind()
     }
     // install to bitmap
     bufferBitmap.installPixels(buffer)
     // update state
     frameImage = bufferBitmap.asComposeImageBitmap()
}
```

```
if (videoComponent.frameImage != null) {
     Image(videoComponent.frameImage!!, contentDescription = null, contentScale = contentScale, modifier = modifier)
}
```

Everything works quite good by CPU, GPU and RAM usage. But it constantly crashes in 2 cases: when you resize window and after some time of playing in random moment. Application crash happens with 2 errors (one at the time or both): 1) FATAL ERROR: `EXCEPTION_ACCESS_VIOLATION (0xc0000005);` 2) EXCEPTION: ` java.lang.RuntimeException: Failed to Image::makeFromBitmap Bitmap(_ptr=0x277f71a11e0) at org.jetbrains.skia.Image$Companion.makeFromBitmap(Image.kt:114)`. 
Errors is related with the access to the memory in Bitmap that used by Compose to render Image() and image update logic. 

In code everything is clear and simple at first glance - we receive image, install pixels, update state and Compose renders it. But if image update rate is higher than compose rendering rate then we update byte buffer faster - that causes the error. Even if update rate is lower than rendering rate - any suspension of rendering logic (window resize) can lead to the same problem. In this case some sync mechanism is needed. But to implement this mechanism we need to know when Compose had done rendering the image, so we can use buffer again. Currently I don't see the way to do it, because if you updated the state for Compose it doesn't mean you rendered. 

There is one more approach - to use `withFrameMillis{}` suspend function in `LaunchedEffect()` and do manipulations with pixels updating the image according to rendering frame rate. But problem is still the same - you can't safely avoid memory access violation. In addition to this the approach adds some complexity moving expensive buffer management logic in appropriate thread.

```
LaunchedEffect(Unit) {
   while (isActive) {
      val millis = withFrameMillis { it }
      // get buffer pixels, install them to bitmap and update frameImage state
   }
}
```

**How to know when ImageBitmap has been rendered by Compose, and buffer can be reused?**
Maybe there is some elegant solution I'm missing or even another approach? 
Generally, the pure-Compose video rendering example is missing... 

_Pay attention: we don't do copy of the `ByteArray` for every frame that can fix the problem to avoid memory allocations and dirty RAM usage._

_Tested on Windows._

**Comment by yaroslavkulinich** [comment]
@mahozad thank you for the link. But I see that the project uses exactly same approach as I described. In addition to this all memory related work executed in UI (AWT) thread with `SwingUtilities.invokeLater()` and it is unacceptable in my case, because a lot of work in UI thread causes performance degradation of other UI features. 
I have no reason to use another video framework because gstreamer perfectly fits my needs. Video frameworks is out of scope of my original question. This is a matter of correct memory management and mechanisms of achieving it.

**Comment by LandryNorris** [comment]
You're modifying the same frame Compose is rendering. I worked on a pure Compose video player before, and worked around this issue by having two bitmap buffers. If you always work on the one that's not rendered, then switch them when done, Compose won't be rendering the frame you're working on, which should also help prevent [screen tearing](https://en.wikipedia.org/wiki/Screen_tearing). This will likely be even better than waiting until the old frame was rendered, since you can do work while Compose is rendering the other frame (or waiting to do so), so the next frame may already be ready from gstreamer. If the second frame is done before the last is rendered, you could potentially use a boolean to gate rendering more that gets set by your withFrameMillis section.

**Comment by igordmn** [comment]
In the code above `byteBuffer` is modified in gstreamer's thread and at the same time is read in the UI (Composable) thread.

First, we need to synchronize writing and using it for drawing. A very simple option (but isn't performant) is:
```
val lock = Any()

fun updateBuffer(byteBuffer: ByteBuffer) = synchronized(lock) { ... }

if (videoComponent.frameImage != null) {
    Canvas(Modifier.fillMaxSize()) {
         synchronized(lock) {
              drawImage(videoComponent.frameImage)
         }
    }
}
```

If it still causes crashes, it means Skia doesn't lock and copy the buffer inside `drawImage`.

To solve this, see the approach suggested by @LandryNorris - you write into a buffer which isn't be used for drawing and then switch it.

If Skia doesn't copy the buffer, it means the buffer is considered used for drawing until a new frame reported, so you have to wait for a new frame until writing to a buffer. To avoid waiting, you can use 3 buffers and switch between them:
```
[write] buffer1 <-> buffer2 <-> [draw] buffer3
```

Will this info help?

**Comment by elijah-semyonov** [comment]
I think you can also do it lockless. We disallow more than 3 inflight frames (the third one is actually already presented and thus its sourcing memory is safe to modify). Thus you can do it lockless.

```
@Composable
fun Player() {
    var buffers = remember { mutableStateListOf<ByteArray>(/* 3 preallocated buffers */) }
    var index by remember { mutableStateOf(0) }
    val currentBuffer by derivedStateOf {
        buffers[index]
    }

    // use your buffers[index] here

    LaunchedEffect(Unit) {
        withFrameMillis {
            index = (index + 1) % buffers.size
            // update your buffers[index] here
        }
    }
}
```

**Comment by yaroslavkulinich** [comment]
Thanks to all for the recommendations! I returned with some results.
I managed to make a solution with only 2 buffers used and to move the most CPU-consuming work from AWT thread.
I tested it on Windows and under various conditions: when rendering rate is higher than video frame rate, when video frame rate is higher than rendering rate etc. For those conditions I added some optimizations to make everything more efficient.

```
class VideoComponent {

    private val buffersSize = 2
    private var bufferIndex = 0
    private val buffers = mutableListOf<ByteArray>()
    private val bitmaps = mutableListOf<Bitmap>()

    // bitmap state rendered in Compose
    var image by mutableStateOf<ImageBitmap?>(null)

    // indicates if we received information about frame and prepared buffers and bitmaps
    private var isPrerolled = false
    // indicates what frame (bitmap and buffer) consumed so can be used by render mechanism
    private var consumedFrame: Int = -1
    // indicates what frame (bitmap and buffer) is sent to Compose to render
    private var renderedFrame: Int = -1
    // indicates what buffer is busy by consume mechanism
    private var busyBuffer: Int = -1
    
    fun onPreroll(width: Int, height: Int, byteBuffer: ByteBuffer) {
        if (!isBitmapReady(width, height)) {
        bitmaps.addAll(
             List(buffersSize) { Bitmap().apply { allocN32Pixels(width, height, true) } }
        )
        image = bitmaps[bufferIndex].asComposeImageBitmap()
        // allocate byte buffers of defined size
        buffers.addAll(
             List(buffersSize) { ByteArray(width * height * 4) }
        )
        isPrerolled = true
    }

    // called in separate thread (in gsreamer thread in my case)
    private fun consumeBuffer(byteBuffer: ByteBuffer) {
        // Save current buffer index to val because it can be updated from AWT thread
        // in requestFrame() function during consumption operations
        val consumingIndex = bufferIndex
        // get number of new frame to consume
        val consumingFrame = consumedFrame + 1

        // if difference between new frame and last rendered frame number is more than 1 - skip
        // when consume rate is higher than  render rate - it saves us a lot of CPU by skipping
        // the most heavy operations when renderer is slow
        if (consumingFrame - renderedFrame > 1) {
            return
        }

        // report we are starting to use the buffer, so renderer should not use this buffer
        busyBuffer = consumingIndex

        // get destination (write) buffer
        val writeBuffer = buffers[consumingIndex]
        // get bytes from received byte buffer
        byteBuffer.let {
            it.get(writeBuffer) // #2 CPU-consuming operation
            it.rewind()
        }

        // get destination (write) bitmap and install pixels
        val writeBitmap = bitmaps[consumingIndex]
        writeBitmap.installPixels(writeBuffer) // #1 CPU-consuming operation

        // report that frame number as consumed
        consumedFrame = consumingFrame
        // report the buffer already was used so available to render
        busyBuffer = -1
    }
    
    private fun frameOld(): Boolean = consumedFrame == renderedFrame
    private fun bufferInUse() = busyBuffer == bufferIndex

    // This function called in AWT thread. Avoid any CPU-consuming operations here.
    fun requestFrame() {
        // Check if prerolled, so bitmap buffers with correct size are ready to use
        if (isPrerolled) {
            // We skip rendering phase to save resources when:
            // 1) frame (and buffer) is old, no need to render it again - happens when render rate is higher than consume rate;
            // 2) buffer is already used by consumer (consuming started) - happens when render rate is slower
            // than consumer rate and in case when consumer already started to work with current buffer
            if (frameOld() || bufferInUse()) {
                return
            }
            // get index of buffer to render it later
            val renderBufferIndex = bufferIndex
            // update index of buffer, so consumer will start write data to another buffer
            bufferIndex =  (bufferIndex + 1) % buffersSize
            // mark frame as rendered
            renderedFrame = consumedFrame
            // get bitmap to render, convert to Compose, and send to render
            image = bitmaps[renderBufferIndex].asComposeImageBitmap()
        }
    }

} 
```

And in Compose:

```
@Composable
fun ComposeVideoView(
    videoComponent : VideoComponent,
    modifier: Modifier = Modifier,
    contentScale: ContentScale = ContentScale.Fit,
) {
    if (videoComponent.image != null) {
        Image(videoComponent.image!!, contentDescription = null, contentScale = contentScale, modifier = modifier)
    } else {
        Spacer(modifier)
    }
    LaunchedEffect(Unit) {
        while (isActive) {
            withFrameMillis {
                videoComponent.requestFrame()
            }
        }
    }
}
```

Generally in described logic we have render (`requestFrame()`) and consume (`consumeBuffer()`) logics that work in different threads. We render frame from one buffer while consuming data from video framework to another buffer. 

The logic has List of `ByteArray `buffers of size 2 as well as List of Bitmaps of size 2. Unfortunately if you want to move the most expensive CPU operation (`Bitmap.installPixels()`) from AWT thread, you should mirror the `Bitmap `object for every buffer and swap them simultaneously. If you will try to work with only one `Bitmap `outside AWT thread, you will get `ACCESS VIOLATION`.

Hope this can be useful to somebody.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4446">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
