### ISSUE TITLE
Crash with UIKitView that wraps a MapLibre MLNMapView

### ISSUE THREAD

**Issue by brewin** [JetBrains/compose-multiplatform#4447]
**Describe the bug**
Using 1.6.10-dev1488, app crashes with `drawable must not be nil.` when using a MapLibre MLNMapView. It works with 1.6.10-dev1457. The issue seems to be related to the Metal backend.

Possibly related to https://github.com/JetBrains/compose-multiplatform-core/pull/1145

```
[CAMetalLayer nextDrawable] returning nil because allocation failed.
-[_MTLCommandBuffer presentDrawable:], line 771: error 'drawable must not be nil.'
```

**Affected platforms**
- iOS

**Versions**
- Kotlin version*:  1.9.22
- Compose Multiplatform version*: 1.6.10-dev1488
- OS version(s)* (required for Desktop and iOS issues): iOS 17.0
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): All

**To Reproduce**
Run iosApp: https://github.com/brewin/cmp-bug

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4447">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
