### ISSUE TITLE
Ability to support more language and region qualifiers

### ISSUE THREAD

**Issue by Junzz0** [JetBrains/compose-multiplatform#4449]
GenerateResClassTask was failed:
java.lang.IllegalStateException: values-b+zh+Hans/strings.xml contains unknown qualifier: 'b+zh+Hans'.

Can values-b+zh+Hans and values-b+zh+Hant be supported

https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html#language-and-regional-qualifiers
https://developer.android.google.cn/guide/topics/resources/app-languages

![11](https://github.com/JetBrains/compose-multiplatform/assets/24819084/145e78ec-ca72-48b3-b713-f48cfdc1c1bf)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4449">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
