### ISSUE TITLE
Optimization suggestions for debugging experience

### ISSUE THREAD

**Issue by xinzhengzhang** [JetBrains/compose-multiplatform#4450]
**Describe the problem**

* The file information of symbol mapping in all composition-native compile artifacts is absolute path such as `[107939] 0066ea27 0e (     SECT    ) 2d     0000   0000000101881870 '_state_global$androidx.compose.ui$/opt/buildAgent/work/5b4bef35b35b9f12/compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/ComposeScene.skiko.kt'`
* When debugging to the kotlin part, only the machine code after disassembe will be displayed, and the corresponding file information cannot be mapped, because the file information in the debug symbol is an absolute path.

**Proposal**
1. When publishing composition-native, it also publishes all source-map rules of the corresponding lldb and tell developers how to set up lldb in the documentation
```lldb
settings append target.source-map /opt/buildAgent/work/8ebe0a8279b7bdad8/ ${workspace_root}/compose-multiplatform-core
settings append target.source-map <OTHERLIBS> <PATH>
```
2. When compiling, use the relative path `-Xdebug-prefix-map =.` Erase the prefix in the absolute path. Note that there is currently a bug with relative paths. I also mentioned an issuse (https://youtrack.jetbrains.com/issue/KT-65366/Native-lldb-cannot-locate-the-source-code-when-relative-paths-are-used-in-debug-prefix-map), but it is ok for absolute paths currently, and we also use this method internally.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4450">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
