### ISSUE TITLE
`TextOverflow.Ellipsis` behaves inconsistently on Android and iOS

### ISSUE THREAD

**Issue by robxyy** [JetBrains/compose-multiplatform#4451]
**Describe the bug**
`TextOverflow.Ellipsis` behaves inconsistently on Android and iOS

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0

**To Reproduce**
```kt
Text("Hello World! \nHello World!", maxLines = 1, overflow = TextOverflow.Ellipsis)
```

**Expected behavior**
Behavior consistent with Android

**Screenshots**

iOS:

<img width="386" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/9105106/26c62e77-d94b-42ed-a3b4-b15ee1f70030">

Android:

<img width="386" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/9105106/f49d1c0d-b882-4755-b355-0afa1c64c891">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4451">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
