### ISSUE TITLE
How speeding up iOS building

### ISSUE THREAD

**Issue by touchnotes** [JetBrains/compose-multiplatform#4456]
Building for the iOS platform is too slow. Is there any way to speed up the build process?

**Comment by igordmn** [comment]
Follow https://youtrack.jetbrains.com/issue/KT-42294/Improve-Kotlin-Native-compilation-time

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4456">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
