### ISSUE TITLE
Flickering/App stays black with compose >0.3.1

### ISSUE THREAD

**Issue by twatzl** [JetBrains/compose-multiplatform#446]
Hi, 

I am  experiencing a weird issue with compose 0.3.1 on Windows 10. 
When I build any app, the app is either flickering or completely black. The same behavior could be observed with compose 0.4.0-build168.

![image](https://user-images.githubusercontent.com/18753370/109422388-97696e80-79db-11eb-94ad-3fbda34bfad3.png)

This is also true for the widgetsgallery and imageviewer examples, as well as for my own app.

As soon as reverting back to 0.3.0 and doing a clean rebuild, everything works again. 

Unfortunately I cannot provide more information at the moment, because there really is no difference other than the version, but I can provide more infos upon request.

Best
Tobi

**Comment by olonho** [comment]
Very hard to say anything without reproducer.

**Comment by andymue66** [comment]
I think this is the same problem like #413. I have the same problem with Windows 10.

When I do the following there is no flickering or black screen:

gradlew -stop
set SKIKO_RENDER_API=SOFTWARE
gradlew run

**Comment by olonho** [comment]
Will `set SKIKO_RENDER_API=OPENGL` work for you?

**Comment by andymue66** [comment]
OPENGL is also working.

**Comment by twatzl** [comment]
> Very hard to say anything without reproducer.

Yeah unfortunately I have no idea what causes the issue other than the version.

> I think this is the same problem like #413. I have the same problem with Windows 10.
> 
> When I do the following there is no flickering or black screen:
> 
> gradlew -stop
> set SKIKO_RENDER_API=SOFTWARE
> gradlew run

I can try this once I have time. Will take a couple of days though.

> Will set SKIKO_RENDER_API=OPENGL work for you?

Will try this as well.

**Comment by Rsedaikin** [comment]
Could you please give your PC specification?
OS version: ?
Graphics card: ?
Graphics card driver version: ?

**Comment by andymue66** [comment]
Notebook Asus ROG
Windows 10 Version 2004
Graphic Cards:
- Intel HD Graphics 530 - driver version 21.20.16.4550
- Nvidia GeForce GTX 960M - driver version 27.21.14.6140

**Comment by Rsedaikin** [comment]
Could you please check if the example from [skiko](https://github.com/JetBrains/skiko) works?
To build `skiko` you need to run in terminal `./gradlew publishToMavenLocal` from `skiko/skiko` directory.
To run the example (rendering clocks) you need to run in terminal `./gradlew run` from `skiko/samples/SkijaInjectSample` directory.
For more info on how to build `skiko`, please read the manual on the [skiko](https://github.com/JetBrains/skiko) github repository.

**Comment by Rsedaikin** [comment]
Please apply the patch [current_adapter.txt](https://github.com/JetBrains/compose-jb/files/6109459/current_adapter.txt) and give me the console output. No need to set SKIKO_RENDER_API (leave it unset).

**Comment by andymue66** [comment]
Hi,
this is the output:
Current graphics card: Intel(R) HD Graphics 530
Graphics card: Intel(R) HD Graphics 530 is blacklisted.
Current graphics card: NVIDIA GeForce GTX 960M
[67513510] FPS 30 (1-98)
[67515513] FPS 60 (23-92)
[67517527] FPS 60 (16-96)

**Comment by YektaDev** [comment]
I guess I have the same problem. The project is almost blank. Approximately, a black screen appears in every 4 to 9 executions of the project; it doesn't have a flickering problem though.

- Kotlin 1.4.31
- Compose 0.4.0-build173
- Windows 10
- Asus ROG Laptop
- Nvidia GeForce GTX 960M

**Comment by twatzl** [comment]
Sorry for the late response, my graphics adapters are

- Intel HD Graphics 4600 - driver version 20.19.15.5058
- NVIDIA Quadro K2100M - driver version 25.21.14.2591

`set SKIKO_RENDER_API=SOFTWARE` works
`set SKIKO_RENDER_API=opengl` does not work

As far as I have read you already have enough information to work on this? If not let me know and I can also try the stuff with the skiko examples.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-446">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
