### ISSUE TITLE
Platform layers clip popup shadows

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#4460]
**Affected platforms**
- iOS

**Versions**
- Compose Multiplatform version*: 1.6.0

**To Reproduce**

```kotlin
Box(
    modifier = Modifier.fillMaxSize(),
    contentAlignment = Alignment.Center
) {
    Popup(alignment = Alignment.Center) {
        Box(
            Modifier
                .shadow(elevation = 32.dp, shape = RoundedCornerShape(16.dp))
                .background(Color.White)
                .clip(RoundedCornerShape(16.dp))
                .padding(50.dp)
        ) {
            Text("platformLayers = true")
        }
    }
}
```

<img src="https://github.com/JetBrains/compose-multiplatform/assets/63979218/69296dd0-1550-4b93-bad5-bd86e15b18ca" width=500>
<img src="https://github.com/JetBrains/compose-multiplatform/assets/63979218/2d51e735-252c-4afb-bbba-523bb7bd60d6" width=500>

**Comment by MatkovIvan** [comment]
It's a known, documented limitation at the moment. See [docs](https://www.jetbrains.com/help/kotlin-multiplatform-dev/whats-new-compose-1-6-0.html#across-platforms):

> Note that popups and dialogs are still unable to draw anything out of their own bounds (for example, a shadow of the topmost container).

You can use old behaviour with `platformLayers = false` or wrap with bigger `Box` with padding as a workaroung.

Since there was no issue about it on GitHub, let's keep it to track this

**Comment by alexzhirkevich** [comment]
Is there any benefits of using platform layers in full-compose app?

**Comment by alexzhirkevich** [comment]
>documented limitation at the moment

May be this should've been documented in the Breaking Changes section as it is set by default and kinda breaks popups that've been working before

**Comment by MatkovIvan** [comment]
> Is there any benefits of using platform layers in full-compose app?

A new way is generally a more correct approach - Compose was designed there in a way to bind each layout node root to a separate platform view. In the case of a full-screen compose app - set of our old hacks should work fine. However, it might affect things like more correct a11y binding etc.

We're considering `platformLayers = false` as a temporal flag, so I encourage you to not consider it as a long-term solution

> May be this should've been mentioned in the Breaking Changes section

The limitation itself shouldn't be in "Breaking Changes" - we'll fix it in future releases (already have some draft), but probably the point about `platformLayers` should have different wording. Anyway, thanks for this note, we'll reconsider this part.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4460">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
