### ISSUE TITLE
Add wasmJs support to Compose HTML

### ISSUE THREAD

**Issue by luca992** [JetBrains/compose-multiplatform#4461]
`compose.html.core` is not available for `wasmJs`. Are there any plans to be add it?

**Comment by eymar** [comment]
> Are there any plans to be add it?

We don't have such plans at the moment. Please share your use cases.

**Comment by luca992** [comment]
The same use cases as a `js` target web app, but backed by wasm. Just like how you can do this in rust with something like [leptos](https://lib.rs/crates/leptos). 

Wasm kotlin is just faster than js (at least with compose-ui builds) while using less cpu from my experience. Also, I'd hope compiling to wasm could reduce the bundle size after `wasm-opt`, as compiled js sizes in kotlin are also larger than compiled wasm for compose-ui builds

**Comment by vdshb** [comment]
I'm also thinking about multithread coroutines will be abailable at wasm some day, and creating business-logic with it and UI on compose-html would be a good option. Much better than compose-web in many cases.

**Comment by luca992** [comment]
> I'm also thinking about multi-thread coroutines will be available at WASM-target some day. Hence creating multi-thread business-logic for browser with UI on compose-html would be a good option. Much better than compose-web in many cases.

Unfortunately, I think multithreading on web with wasm is in the same same situation as Js. The only way you can do it is with web workers.

**Comment by cromefire** [comment]
> Unfortunately, I think multithreading on web with wasm is in the same same situation as Js. The only way you can do it is with web workers.

There's work on it to enable threads for webassembly, although it'll probably still take some time to get there.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4461">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
