### ISSUE TITLE
Update ui-util to upstream androidx version

### ISSUE THREAD

**Issue by zt64** [JetBrains/compose-multiplatform#4462]
Hi. In upstream androidx maintained by Google `androidx.compose.ui:ui-util` it contains additional functions not present in JetBrains compose-multiplatform-core. Is there any reason why the JetBrains variant is out of date? As far as I could tell there should be very little work needed to get it fully multiplatform. Reason I ask is because I could make use of these in a library I'm developing.

**Comment by zt64** [comment]
> What version of androidx.compose:ui are you interested? If you mean 1.6.3, then the next Compose Multiplatform release 1.6.1 will contain its changes.

I mean the ui:ui-util project is behind, the ui:ui project is up to date. I'm unsure which version ui-util in compose-multiplatform-core is on

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4462">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
