### ISSUE TITLE
WebView support for Compose Multiplatform

### ISSUE THREAD

**Issue by JagadishaIncture** [JetBrains/compose-multiplatform#4463]
Hi Team,

We don't have official WebView from Compose Multiplatform Team yet. is there any plans to develop Webview which run on Android,iOS and Desktop and Web Platforms.

Note: We have one third part library for Webview which only Supports Android ,iOS and Desktop but no support for Web

https://github.com/KevinnZou/compose-webview-multiplatform

**Comment by farhazulMullick** [comment]
@eymar  What are your plans for providing support for webview in CMP.

**Comment by eymar** [comment]
We don't have such plans right now.
