### ISSUE TITLE
Make string resources available from Swift code

### ISSUE THREAD

**Issue by Shusek** [JetBrains/compose-multiplatform#4466]
I would like to have the ability to use texts placed in compose via code in Swift.

Usecase:

I have old code written in Swift, and I would like to streamline the mechanism responsible for handling texts in the application.

Proposed API
I think it's what's placed in the library moko-resources: 
https://github.com/icerockdev/moko-resources
`let string = MR.strings().my_string.desc().localized()`

**Comment by terrakok** [comment]
The library was designed for the compose specific use case. We don't have plans to support export resources outside the compose world. You may ask your question in the kotlin tracker to support resources in the plain kotlin multiplatform: https://youtrack.jetbrains.com/issue/KT-49981

To workaround the problem you can provide your own wrapper around the resources in your app.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4466">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
