### ISSUE TITLE
Blinking when showing dialog with `LayerType.OnWindow`

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4475]
Compose 1.6.10-dev1509, Windows

Run MPP demo in core repo with `layerType = LayerType.OnWindow`.

Components - Material3 - AlertDialog3 (Short). See that the first frames aren't clipped by rounded corners:
<img width="886" alt="image" src="https://github.com/JetBrains/compose-multiplatform-core/assets/5963351/f7282a43-add4-43b4-952f-294d2a35b576">
<img width="886" alt="image" src="https://github.com/JetBrains/compose-multiplatform-core/assets/5963351/858acade-209c-4f62-8073-c1fef18b16eb">
<img width="888" alt="image" src="https://github.com/JetBrains/compose-multiplatform-core/assets/5963351/758cef86-2d55-4f5b-ad04-0554d82c7684">

**Comment by igordmn** [comment]
Also visible on resize:
https://github.com/JetBrains/compose-multiplatform/assets/5963351/1a4617cc-bba7-4161-8c8d-4a3139c58a36

**Comment by igordmn** [comment]
If we switch to OpenGL, the issue seems isn't reproducible:
```
System.setProperty("skiko.renderApi", "OPENGL")
```
At least the issue described in https://github.com/JetBrains/compose-multiplatform-core/pull/1190#discussion_r1530146289

But we still have a white edges in the first frames:

https://github.com/JetBrains/compose-multiplatform/assets/5963351/6f399889-9155-43a7-9b9d-b01287a2a6bf

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4475">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
