### ISSUE TITLE
(🐞) Gradle fails to build when also using the ktor plugin

### ISSUE THREAD

**Issue by KotlinIsland** [JetBrains/compose-multiplatform#4478]
I guess this is because ktor also sets the run task. This case should be handled gracefully.
```kt
plugins {
    kotlin("jvm") version "1.9.23"
    id("org.jetbrains.compose") version "1.6.1"
    id("io.ktor.plugin") version "2.3.9"
}

repositories {
    mavenCentral()
}

compose.desktop.application.mainClass = "MainKt"
```
```
> ./gradlew build
...
A problem occurred configuring root project 'test-compose'.
> Cannot add task 'run' as a task with that name already exists.
```

gradle 8.6

**Comment by eymar** [comment]
Do you have a ktor web server in the same module as Compose Desktop UI app? 

As I see, `id("io.ktor.plugin")` is not needed for ktor client side. 

If you indeed want a ktor web server and Compose Desktop app in the same module, I'm wondering what's your use case?
Usually, those two would reside in 2 separate modules.

**Comment by KotlinIsland** [comment]
I was just messing around trying to learn how these technologies work. I ran into a bizarre error and had absolutely no idea what was happening. That's why I mentioned in the OP, can it be handled gracefully.

**Comment by eymar** [comment]
Got it. We'll consider it as a potential enhancement. Although it can be done by ktor side as well :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4478">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
