### ISSUE TITLE
Crash when we resize ComposePanel after re-adding it to the hierarchy

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4479]
Compose 1.6.10-dev1509

1. Clone to the Jewel repro: https://github.com/JetBrains/jewel
2. Run the ide sample configuration
3. Open an empty project
4. Wait for sync
5. Open the "Jewel Demo" tool window
6. Select the compose sample tab within the tool window
7. Toggle the tool window to close it
8. Reopen the "Jewel Demo" tool window
9. Resize Intellij
10. Observe error
```
ComposeScene is closed
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4479">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
