### ISSUE TITLE
Not a code problem, but a lack of information problem at plugins.jetbrains.com

### ISSUE THREAD

**Issue by b0r1ngx** [JetBrains/compose-multiplatform#4483]
At https://plugins.jetbrains.com/plugin/16541-compose-multiplatform-ide-support/versions,

there is no information about changes at "What’s New" topic, when we click at some version of the product (for example: https://plugins.jetbrains.com/plugin/16541-compose-multiplatform-ide-support/versions/stable/503048).

**Comment by b0r1ngx** [comment]
Reports it because thing that may help someone, to not goes to repository -> release versions.
And hope that my suggestion is not a not-topic one.

**Comment by eymar** [comment]
Noted! We'll discuss this potential improvement

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4483">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
