### ISSUE TITLE
Resizing the parent window clips the dialog with WINDOW layers

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4484]
Compose 1d73c9c4, Windows

1. `System.setProperty("compose.layers.type", "WINDOW")`
2. Open MPP Demo - Components - material3 - AlertDialog
3. Resize the main windows

Sometimes the dialog content clips:

https://github.com/JetBrains/compose-multiplatform/assets/5963351/1a4617cc-bba7-4161-8c8d-4a3139c58a36

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4484">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
