### ISSUE TITLE
How to add material3 in common

### ISSUE THREAD

**Issue by salimisler28** [JetBrains/compose-multiplatform#4489]
When I try to add material3 dependency to common, I face a sync issue. How can I use material 3 in iOS?

**Comment by PMARZV** [comment]
have you tried to add implementation(compose.material3) in  commonMain.dependencies {} block?

**Comment by salimisler28** [comment]
> have you tried to add implementation(compose.material3) in commonMain.dependencies {} block?

I dont see material 3 in toml file that I downloaded from the wizard. can you please share the dependency?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4489">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
