### ISSUE TITLE
JVM fatal error with 0.3.0 and 0.3.1 on AdoptOpenJDK (11.0.10+9) (build 11.0.10+9)

### ISSUE THREAD

**Issue by softwarehangar7** [JetBrains/compose-multiplatform#449]
When I run the wizard project changing the Compose plugin to 0.3.0 or 0.3.1, it works the first time.
Running a second time gives me a JVM fatal error.

[hs_err_pid23096.log](https://github.com/JetBrains/compose-jb/files/6058269/hs_err_pid23096.log)
[hs_err_pid22284.log](https://github.com/JetBrains/compose-jb/files/6058270/hs_err_pid22284.log)

Running the 0.2.0-build132, gives me the following message:
SkIcuLoader: datafile missing: C:\Program Files\AdoptOpenJDK\jdk-11.0.10.9-hotspot\bin\icudtl.dat.
But still runs fine.

**Comment by olonho** [comment]
Will software or OpenGL renderer help?

**Comment by softwarehangar7** [comment]
Yes. Forcing SKIKO_RENDER_API="SOFTWARE" or "OPENGL" works fine.

**Comment by Rsedaikin** [comment]
Could you please give your PC specification?
OS version: ?
Graphics card: ?
Graphics card driver version: ?

**Comment by softwarehangar7** [comment]
Edition	Windows 10 Pro
Version	20H2
Installed on	‎25/‎02/‎2021
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

Dell Precision 7510
Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz   2.71 GHz
16.0 GB

It has two graphic adapters. I don't know which one is using.
- Intel(R) HD Graphics 530 (25.20.100.6472)
- NVIDIA Quadro M2000M (24.21.14.1163)

Any tips on how to find out?

**Comment by Rsedaikin** [comment]
Could you please check if the example from [skiko](https://github.com/JetBrains/skiko) works?
To build `skiko` you need to run in terminal `./gradlew publishToMavenLocal` from `skiko/skiko` directory.
To run the example (rendering clocks) you need to run in terminal `./gradlew run` from `skiko/samples/SkijaInjectSample` directory.
For more info on how to build `skiko`, please read the manual on the [skiko](https://github.com/JetBrains/skiko) github repository.

**Comment by softwarehangar7** [comment]
Ok. I will try this weekend

**Comment by softwarehangar7** [comment]
There are some gradle errors when I try to build Skiko.
**[Fatal Error] org.gradle.kotlin.kotlin-dsl.gradle.plugin-1.3.6.pom:19:10: Already seen doctype**

The same for plugins-1.3.6.pom and kotlin-sam-with-receiver-1.3.72

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6377">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
