### ISSUE TITLE
Multi Module app is Failed to Run when Generated as .aar used in other Native project

### ISSUE THREAD

**Issue by sureshmaidaragi1919** [JetBrains/compose-multiplatform#4492]
**Describe the bug**
I have created the KMM multi module project as shown below

-- KmmUI
-- KmmNetwork
-- KmmCore
-- kmmpwpitara (Shared)

When I generate **`.aar`** file by cmd ` ./gradlew pitaraShared:assemble`, And use the generated .aar in Native Android app it showing file to find Module UI's imported file

**Affected platforms**

- Android

**Versions**
- Kotlin version*:  1.9.20
- Compose Multiplatform version*: 1.5.4
- OS version(s)* (required for Desktop and iOS issues):  All Android version
- OS architecture (x86 or arm64): N/A
- Device (model or simulator for iOS issues):  N/A
- JDK (for desktop issues):  N/A

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Created Multi modular KMM projects targeting only Android and iOS
2. Generated `.aar `for Android and `.framework` by cmd `./gradlew pitaraShared:assemble `
3. Put the the generated file native android project under libs and implement in build.gradle.kts(app) file 
4. in Native Code try using the one of the function which calls KMM modules components/functions/class 
5. App results in below error

**Expected behavior**
It should work in Multi module as well;

**Screenshots**

in below screen shot,` kmmpwui/ui/widget/UtilsKt;` is from kmmui modules file called in kmm's shared `kmmpwpitara` module and used in Native app project as attached screen. and gives the error
<img width="1509" alt="Screenshot 2024-03-16 at 10 19 43 AM" src="https://github.com/JetBrains/compose-multiplatform/assets/28126457/b08a6077-90a3-4fc7-8169-5381f13c57e7">

**Additional context**
If KMM projects still fully didn't support Multi modular architecture let us know in prior

**Comment by pablichjenkov** [comment]
Not just KMP but also traditional Android, an .aar doesn't include the dependent submodules in the .aar
You have to publish all submodules independently and include all of them in the final build.

**Comment by sureshmaidaragi1919** [comment]
> Not just KMP but also traditional Android, an .aar doesn't include the dependent submodules in the .aar You have to publish all submodules independently and include all of them in the final build.

Ho okay, Thanks for the information @pablichjenkov

**Comment by sureshmaidaragi1919** [comment]
> Not just KMP but also traditional Android, an .aar doesn't include the dependent submodules in the .aar You have to publish all submodules independently and include all of them in the final build.

Ho okay, Thanks for the information @pablichjenkov

**Comment by sureshmaidaragi1919** [comment]
> Not just KMP but also traditional Android, an .aar doesn't include the dependent submodules in the .aar You have to publish all submodules independently and include all of them in the final build.

@pablichjenkov I tried MavenLocal but still same issue, do I need to host them on sonartype?

**Comment by pablichjenkov** [comment]
Can you post your library pom.xml generated when you did the publication.

**Comment by devanshu6445** [comment]
@sureshmaidaragi1919 Hi, I think you can use```maven-publish``` plugin and configure each publication with the correct information such as artifactId pom info etc. It will automatically publish all the artifacts for all the targets defined in the build configuration. I have created a gradle plugin for this and it publishes all the artifacts to the repo.

**Comment by sureshmaidaragi1919** [comment]
> Can you post your library pom.xml generated when you did the publication. MavenLocal should work but each library should be published to the local repository and have the correct pom.xml file.

[kmm-pw-ui-module-1.0.0.pom.txt](https://github.com/JetBrains/compose-multiplatform/files/14661346/kmm-pw-ui-module-1.0.0.pom.txt)

**Comment by sureshmaidaragi1919** [comment]
> @sureshmaidaragi1919 Hi, I think you can use`maven-publish` plugin and configure each publication with the correct information such as artifactId pom info etc. It will automatically publish all the artifacts for all the targets defined in the build configuration. I have created a gradle plugin for this and it publishes all the artifacts to the repo.

Yes I did here is the snippet @devanshu6445 
<img width="853" alt="Screenshot 2024-03-20 at 7 41 51 AM" src="https://github.com/JetBrains/compose-multiplatform/assets/28126457/fc003e9e-a29a-4ef0-873b-948655d2fd43">

**Comment by sureshmaidaragi1919** [comment]
Also what is the plugin on Android Studio?

**Comment by devanshu6445** [comment]
@sureshmaidaragi1919 As I can see from your build configuration, you are not configuring each publication target of maven publications. If you do that I think it will work.
It is not an Android studio(IDE) plugin but rather my custom gradle plugin.

**Comment by sureshmaidaragi1919** [comment]
> @sureshmaidaragi1919 As I can see from your build configuration, you are not configuring each publication target of maven publications. If you do that I think it will work. It is not an Android studio(IDE) plugin but rather my custom gradle plugin.

can you help me to share any ref or doc todo that, I am not able to get exactly what I have missed

**Comment by sureshmaidaragi1919** [comment]
![Screenshot 2024-03-20 at 10 22 42 AM](https://github.com/JetBrains/compose-multiplatform/assets/28126457/40fcaf00-a0ac-4609-ae82-f1ca3469c968)

I can see the external library post running the current build

**Comment by pablichjenkov** [comment]
I see the ui module pom file reference core and player dependencies. The player  pom seems ok, and I guess core is ok too.
So with ui, player and core in your local maven. If you just use `implementation("live.pw:UI:1.0.0")`
in your pure Android project, it should work.
If you still get a missing class Exception. You can decompile the App with Android Studio or jadx and check if it was actually included or excluded by R8 I don't know. But in general gradle won't even compile if it doesn't resolve the dependecies.

**Comment by devanshu6445** [comment]
@sureshmaidaragi1919 what @pablichjenkov is saying is correct but can you confirm whether this exception is only coming for the UtilsKt class or for any other classes as well. And are you using R8 for debug build as well?

**Comment by sureshmaidaragi1919** [comment]
@devanshu6445 Issue is coming from other modules too,
No I am not using R8 for any builds

**Comment by AliAzaz** [comment]
I am also getting the issue while accessing moko-resources from .aar file.
