### ISSUE TITLE
Enhancement(web): Support onDrag/detectDragGestures Modifier on Web Platform

### ISSUE THREAD

**Issue by whitescent** [JetBrains/compose-multiplatform#4493]
It seems that `onDrag/pointerInput detectDragGestures` doesn't work with Web Platform, here's a simple example

```kotlin
var offset by remember { mutableStateOf(Offset.Zero) }
Image(
  painter = painterResource(Res.drawable.logo),
  contentDescription = null,
  modifier = Modifier.offset {
    IntOffset(offset.x.toInt(), offset.y.toInt())
  }
    .size(48.dp)
    .pointerInput(Unit) {
      detectDragGestures(
        matcher = PointerMatcher.Primary
      ) {
        offset += it
      }
    }
)
```

**Comment by eymar** [comment]
Thanks for reporting! 
It's rather a bug, since it's available for using it in the code but it doesn't work as expected :) 
The feature was not implemented internally yet.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4493">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
