### ISSUE TITLE
Use compose resources without skiko on Js and Wasm targets

### ISSUE THREAD

**Issue by rjaros** [JetBrains/compose-multiplatform#4495]
Currently the resources library depends on compose-foundation which depends on compose-ui and skiko. This makes a problem with bundle size, when using it with compose-based frameworks other then compose-web, which don't draw on canvas and don't use skiko  (e.g. compose-html, kilua).

Could you consider extracting some core functionality, like `files` and `strings`, which could be really useful for all compose apps, even those not using any graphics? E.g. creating a "core resources lib" without dependencies on foundations, ui and skiko.

**Comment by Burtan** [comment]
This core functionality is in fact useful for all kotlin-multiplatform apps.

**Comment by pjBooms** [comment]
Yes, initially we thought to provide the core functionality on KMP level. However it would take more time to appear in KMP and in fact resources are crucial for Compose so as a first step we introduced them in Compose Multiplatform only. Though I believe the core functionality will appear in KMP as well some day.

**Comment by ellet0** [comment]
Consider creating the same issue on YouTrack JetBrains

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4495">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
