### ISSUE TITLE
Resources component does not work in tests.

### ISSUE THREAD

**Issue by Burtan** [JetBrains/compose-multiplatform#4498]
**Describe the bug**
The resources component in 1.6.0 does not work in tests. 

**Affected platforms**
- Web (K/Wasm) - Canvas based API (gradle task wasmJsTest fails with 404, the resource is not found)
- Web (K/JS) - Canvas based API (gradle task jsTest does not run a single test (NO-SOURCE))

**Versions**
- Kotlin version*: 1.2.2
- Compose Multiplatform version*: 1.6.0
- OS version(s)* (required for Desktop and iOS issues): MacOS Sonoma 14.3.1
- OS architecture (x86 or arm64): x86

**To Reproduce**
[Run this test](https://github.com/Burtan/compose-multiplatform/blob/resources_in_tests/components/resources/demo/shared/src/commonTest/kotlin/TestResources.kt) in a fork of the resources demo application.

**Comment by terrakok** [comment]
Unfortunately, this is a known problem with Kotlin: https://youtrack.jetbrains.com/issue/KT-42923
Add your vote there to bump a priority as well 👍

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4498">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
