### ISSUE TITLE
Compose resources is incompatible with moko-resources on iOS

### ISSUE THREAD

**Issue by Burtan** [JetBrains/compose-multiplatform#4499]
**Describe the bug**
Resource loading from NSBundle does not work when moko-resources plugin is loaded.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): MacOS Sonoma 14.3.1
- OS architecture (x86 or arm64): x86

**To Reproduce**
Apply moko-resources and try to use compose resources

**Expected behavior**
moko-resources and compose resources work both

**Screenshots**
When moko-resources is used next to compose resources the bundle path is different.
<img width="316" alt="Bildschirmfoto 2024-03-17 um 17 31 19" src="https://github.com/JetBrains/compose-multiplatform/assets/3275473/42cd8117-fac8-4158-90f5-6c6f733b3633">

Here the folder files/testImage.jpg is placed in composeResources folder

I think this should at least be documented, because people using moko-resources will probably be interested in compose resources as well.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4499">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
