### ISSUE TITLE
How to turn off the resource generation ?

### ISSUE THREAD

**Issue by jbruchanov** [JetBrains/compose-multiplatform#4501]
Is there some flag how can be the new resources processing/generation disabled ?

**Comment by pjBooms** [comment]
If you don't use the resource library then the resources won't be processed and Res class won't be generated. Does it answer your question?

There is an opposite flag to always generate Res class.

**Comment by pjBooms** [comment]
>So I sort of using the resources library just for low level "loading" of binaries and it's ending with empty Res class.

Please explain your use case in more details. What do you mean by low level "loading" of binaries. Low level functionality is implementation details of the resource library, you should not rely on it. The only valid use case is to use resources via Res class. If you only need accessing the resources as byte arrays we may consider to not generate other accessors but byte array accessor only, though it is also pretty strange use case. You may achieve this functionality via putting all the resources to `files` folder.

**Comment by pjBooms** [comment]
>org.jetbrains.compose.resources.Resource#readBytes()

It is considered as internal API.

>given the fact of storage in NSBundle.mainBundle.resourcePath + "/compose-resources/" + path

It may change and will be changed in the next release. So relying on it is fragile.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4501">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
