### ISSUE TITLE
Text actions menu doesn't show up when a visual transformation is applied on iOS

### ISSUE THREAD

**Issue by zacharee** [JetBrains/compose-multiplatform#4502]
**Describe the bug**
Using a custom VisualTransformation or PasswordVisualTransformation breaks the text actions menu on iOS. Using `VisualTransformation.None` works as expected.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): iOS 17.4
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iPhone 15 Pro Max

**To Reproduce**
```kotlin
var valueState by remember {
    mutableStateOf("")
}

OutlinedTextField(
    value = valueState
    onValueChanged = { valueState = it },
    visualTransformation = PasswordVisualTransformation(),
}
```

**Expected behavior**
The text actions menu should show up on tap when a visual transformation is applied.

**Additional context**
Setting the visual transformation to `None` at runtime (with a conditional and state value) fixes the menu. Swapping back to the transformation while the menu is showing doesn't dismiss it, but dismissing it manually prevents it from showing again.

**Comment by Skeptick** [comment]
Maybe there are some workarounds? Copy-paste is often used for fields like phone number or bank card. And masks are very necessary for these fields :(

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4502">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by DenisVoronets** [comment]
I’m also waiting for updates on this.
When the field is empty, there's no option to paste text, but if something is already there, the paste works.

Kotlin version: 2.0.20
Compose Multiplatform version: 1.6.11
