### ISSUE TITLE
Incorrect `imePadding` and high cpu usage when repeatedly opening and closing `Keyboard` on iOS

### ISSUE THREAD

**Issue by robxyy** [JetBrains/compose-multiplatform#4506]
**Describe the bug**
Incorrect `imePadding` and high cpu usage when repeatedly opening and closing `Keyboard` on iOS

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-dev1514
- OS version(s)* (required for Desktop and iOS issues): 17.4
- Device (model or simulator for iOS issues): model

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

```kotlin
@Composable
fun App() {
  MaterialTheme(
    colors = darkColors()
  ) {
    Surface {
      Column(
        Modifier.statusBarsPadding().fillMaxSize(),
        verticalArrangement = Arrangement.Center
      ) {
        val focusManager = LocalFocusManager.current
        val imePadding = WindowInsets.ime.asPaddingValues()

        TextField("", {}, Modifier.fillMaxWidth())
        TextField("Hello World!", {}, Modifier.fillMaxWidth())
        Text(imePadding.toString())

        LazyColumn(
          Modifier.pointerInput(Unit) {
            detectTapGestures {
              focusManager.clearFocus(true)
            }
          }.imePadding()
        ) {
          items(100) {
            Text("Hello World!", Modifier.fillParentMaxWidth())
          }
        }
      }
    }
  }
}
```

**Expected behavior**
Normal cpu usage and correct `imePadding`

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/9105106/73f3b7ab-bef7-4316-adb4-11b5332cbb8b

<img width="664.5" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/9105106/daeaea28-a230-460d-9e25-cfb9f32a101e">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4506">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
