### ISSUE TITLE
[iOS] Resource not found. Run 'pod install' to update the copy resources script

### ISSUE THREAD

**Issue by gastsail** [JetBrains/compose-multiplatform#4510]
**Describe the bug**
I have updated to compose 1.6.1 , then inside my shared folder I have renamed the resources directory with composeResources as required to load resources.

My compose-multiplatform.xml file is having issues in the iOS side while trying to run the app

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.20 
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64):
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1- Run the app

**Expected behavior**
App runs normally

**Screenshots**
![Screenshot 2024-03-18 at 12 41 30](https://github.com/JetBrains/compose-multiplatform/assets/24615408/4248e7c1-7328-467c-a1bf-e08cf60b16c5)
![Screenshot 2024-03-18 at 12 41 39](https://github.com/JetBrains/compose-multiplatform/assets/24615408/a8a17b0a-0894-45df-8690-d2f2676ec86a)

**Additional context**
I want to know if there is anything else I need to do to sync the new renamed folder, I have restarted and cleaned cache multiple times but it seems to still fail

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4510">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
