### ISSUE TITLE
MissingResourceException: Missing resource with path: drawable/photo.png

### ISSUE THREAD

**Issue by gastsail** [JetBrains/compose-multiplatform#4514]
**Describe the bug**
I have implemented compose resources inside my project, I'm using compose 1.6.1 and the image loads correctly on Android, but fails on iOS

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.20
- Compose Multiplatform version*:  1.6.1
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64):
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 

**To Reproduce**
Play the app on iOS

**Expected behavior**
App plays correctly and image is shown

**Screenshots**

### iOS
![Screenshot 2024-03-19 at 14 29 03](https://github.com/JetBrains/compose-multiplatform/assets/24615408/c4b29d56-7a4f-482a-870b-48957b001aa9)

### Android
![Screenshot 2024-03-19 at 14 29 38](https://github.com/JetBrains/compose-multiplatform/assets/24615408/ba9db1ef-4210-41c5-8563-1a1c24875860)

### Structure
![Screenshot 2024-03-19 at 14 30 51](https://github.com/JetBrains/compose-multiplatform/assets/24615408/d276bd9b-5f05-47b1-b29b-95bc64edef32)

**Additional context**
Here is the code , I already implemented. 

```
sourceSets {
        commonMain.dependencies {
            implementation(compose.components.resources)
        }
```

Code

```
if (!isEditOrAddExpenses) {
                                    Row(
                                        modifier = Modifier.padding(end = 8.dp),
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        Image(
                                            modifier = Modifier.size(40.dp)
                                                .clip(RoundedCornerShape(45)),
                                            painter = painterResource(Res.drawable.photo),
                                            contentDescription = null
                                        )
                                        Spacer(modifier = Modifier.width(4.dp))
                                        Text(text = "Hello, Gastón", color = colors.textColor)
                                    }

                                }
```

**Comment by pjBooms** [comment]
This scenario should work indeed. The most probably it is some configuration issue. Could you please provide us a reproducible example (preferably as a project on GitHub) so we can check it?

**Comment by pjBooms** [comment]
If you use cocoa pods, don't forget to call  initial `pod install` after importing the project

**Comment by gastsail** [comment]
@pjBooms thanks for the reply, take a look at here https://github.com/gastsail/expenses-KMP/pull/6

**Comment by pjBooms** [comment]
I have reproduced the issue and will look into it

**Comment by gastsail** [comment]
thanks for your time @pjBooms

**Comment by pjBooms** [comment]
There are two problems with your project configuration:

1. Please remove 

`compose.ios.resources.sync=false`

from `gradle.propereties`

2. Please remove 
```
        extraSpecAttributes["resources"] =
            "['src/commonMain/resources/**', 'src/iosMain/resources/**']"

```

from `shared/build.gradle.kts`

Don't forget to call 

`pod install`

in `iosApp` folder

after re-syncing the project

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4514">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
