### ISSUE TITLE
[Web] incorrect windosw size in high resolution monitor

### ISSUE THREAD

**Issue by Sanlorng** [JetBrains/compose-multiplatform#4517]
**Describe the bug**

**Affected platforms**

- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*: 1.9.23 
- Compose Multiplatform version*:  1.6.1
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): X86
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 
- Browser: Edge & Chrome

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create Compose Wasm Project.
2. Open compose web app in a browser with 4k 150% scale Monitor

3. Canvas can't fill the whole web content size.
![image](https://github.com/JetBrains/compose-multiplatform/assets/26089739/0fa98390-8e5f-4af5-9edd-eb8f09020121)

4. if i changed the scale in the browser, if scale up, canvas' size will decrese, if scale down, canvas'size will increase.
![image](https://github.com/JetBrains/compose-multiplatform/assets/26089739/08b9032f-24e2-4283-924e-0db96b98b6ae)
![image](https://github.com/JetBrains/compose-multiplatform/assets/26089739/42e1cbe2-2697-4ca0-bd25-6508587ac317)

5. if i change monitor'setting to the 1080P 100%s scale，the canvas can fill whole  web content size.
![image](https://github.com/JetBrains/compose-multiplatform/assets/26089739/c7cc2b6d-f0e8-49fa-9a7c-7ec0a5a41891)

**Expected behavior**
Compose web app can fill whole content size in the high resolution monitor.

**Screenshots**
See above.

**Additional context**

**Comment by Skaldebane** [comment]
This is not a Windows-specific issue. Happens on any browser on Linux and Android as well.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4517">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
