### ISSUE TITLE
Add support for wlr-layer-shell

### ISSUE THREAD

**Issue by caughtquick** [JetBrains/compose-multiplatform#4518]
WLR-Layer-Shell is a wayland protocol implemented by wlroots (sway, hyprland, wayfire, etc), Smithay (PopOS Cosmic) and KWin (KDE Plasma); pretty much all major wayland compositors besides GNOME. Adding support for the wlr layer shell protocol would allow for the creation of, for example, a cross platform application launcher working on Windows, MacOS and Linux with Wayland, while currently can only be implemented via X11. 

For more information on wlr-layer shell: https://wayland.app/protocols/wlr-layer-shell-unstable-v1

Some implementations of layer shell currently include GTK-Layer-Shell and QT-Layer-Shell, used as add-on libraries to GTK and QT applications respectively to add support for wlr-layer-shell.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4518">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
