### ISSUE TITLE
AppWindow.removeMenuBar adds white bars on top and bottom

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#452]
Compose 0.3.1

See [imageviewer](https://github.com/JetBrains/compose-jb/blob/ae2366158a3ee514e377c3b7d046df739ebe19c1/examples/imageviewer/common/src/desktopMain/kotlin/example/imageviewer/utils/Application.kt#L80) example.

If we call `AppWindow.current.removeMenuBar` after the start of the window, window size will not be the same as the size without calling `removeMenuBar`
![image](https://user-images.githubusercontent.com/5963351/109479231-3a2cf600-7a8b-11eb-886e-892482c39ea4.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6376">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
