### ISSUE TITLE
Make iOS-like animations in `navigation-compose` by default

### ISSUE THREAD

**Issue by PMARZV** [JetBrains/compose-multiplatform#4528]
Since @MatkovIvan is working in commonizing all androidx libraries related to Navigation (lifecycle, navigation, savestate), it would be super cool to have IOS-like back animations for IOS (or maybe for all platforms).
 I've seen users say they can tell when an app is native or not depending on the back animation.

It would be a great addition to the overall experience!!

[predictive back gesture](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture) would be great  too (but for all version codes!!!)

Example:

https://github.com/JetBrains/compose-multiplatform/assets/100836358/21a93b71-9b09-4d1e-b0e4-25159f2c8758

**Comment by MatkovIvan** [comment]
> it would be super cool to have IOS-like back animations

I know it's not the same, but sliding animations might be easily implemented like:
```kt
val animationSpec = tween<IntOffset>(700)
NavHost(
    navController = navController,
    startDestination = startDestination,
    enterTransition = { slideIntoContainer(SlideDirection.Left, animationSpec) },
    exitTransition = { slideOutOfContainer(SlideDirection.Left, animationSpec) },
    popEnterTransition = { slideIntoContainer(SlideDirection.Right, animationSpec) },
    popExitTransition = { slideOutOfContainer(SlideDirection.Right, animationSpec) }
) { ... }
```

We might tune default behaviour in the future, but don't expect it in first versions.
Our general vision here is that should be possible to implement this via only public API, so everyone might customize it for their specific needs

> predictive back gesture

It on our radar too, no promises about ETA yet

**Comment by liufeng382641424** [comment]
@MatkovIvan Does navigation-compose already support kmp?

**Comment by MatkovIvan** [comment]
JetBrains started to publish dev builds of a multiplatform version of this package, but there is no stable version yet.
Usage example: https://github.com/MatkovIvan/nav_cupcake
Tracking of adding multiplatform support was there: https://github.com/JetBrains/compose-multiplatform/issues/85#issuecomment-2036264640

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4528">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
