### ISSUE TITLE
Can't download compose artifacts' source code in the common code.

### ISSUE THREAD

**Issue by Irineu333** [JetBrains/compose-multiplatform#4530]
**Describe the bug**

When the **android** and **desktop** targets are defined in a project with only one module, it is not possible to download the source code of the Compose artifacts in the common code nor in the desktop code (both seem to use the same artifacts, `*_desktop`). This is terrible because to develop for Compose, it is strictly necessary to explore the source code of the composable functions.

**Targets**
By adding more targets, for example, iOS, the problem is solved, from the moment the common code starts to use the common artifacts. So I assume that the problem is precisely the artifacts for JVM.

**Modules**
For some reason that I still don't understand, the bug does not exist in projects with multiple modules. So, projects created with the [Kotlin Multiplatform Wizard](https://kmp.jetbrains.com/) suffer from this bug.

[My personal template](https://github.com/Irineu333/KMP-AndroidAndDesktop), for example, started to show the bug after [consolidating everything into one module](https://github.com/Irineu333/KMP-AndroidAndDesktop/pull/11).

**Discussed in https://github.com/JetBrains/compose-multiplatform/discussions/4263**

**Affected platforms**

- Desktop (Windows, Linux, macOS)
- Android

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): Fedora 39
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Define the android and desktop targets.
2. Create a simple hello world in the common code.
3. Open the used composable and click on "download sources".
4. Nothing happens.

**Expected behavior**
It should download the source code so that we can explore it.

**Screenshots**
[Gravação de tela de 2024-03-23 00-12-41.webm](https://github.com/JetBrains/compose-multiplatform/assets/45833588/d6e25e2d-6eea-4271-af4c-5e012890c946)

**Comment by mazunin-v-jb** [comment]
Hello! Thank you for submitting the issue.
Looks like the problem with the Kotlin Wizard only. Please, create a ticket [in Kotlin Issue Tracker](kotl.in/issue)
And feel free to reopen if you have any questions.

**Comment by Irineu333** [comment]
@mazunin-v-jb I think it might be a bug in the IDE

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4530">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
