### ISSUE TITLE
Code only desktop appearing in the common sourceset

### ISSUE THREAD

**Issue by Irineu333** [JetBrains/compose-multiplatform#4532]
**Describe the bug**
When I target only Android and desktop, for some reason, artifacts that exist only for desktop start to appear in the common code. When I add other targets, this does not happen. This makes it difficult to develop an application aimed only at Android and desktop, causing the developer to end up using codes without realizing that they will fail when compiled for Android, being forced to add another target just to avoid this.

**Affected platforms**

- Desktop (Windows, Linux, macOS)
- Android

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): Fedora 39
- OS architecture (x86 or arm64): x86
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Add the Android and desktop targets
2. Use a desktop-only composable in the common code, like VerticalScrollbar (just as an obvious example).
3. Compile for Android.

**Expected behavior**
Just as when I add other non-JVM targets, it should restrict the common code to artifacts that work on all the defined targets, avoiding headaches and misunderstandings.

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/45833588/575fa9d2-fdec-4637-ab53-57163f63d4bb)

**Additional context**
The multiplatform composable seems to have several problems when targeted only for Android and desktop.

**Comment by MatkovIvan** [comment]
Tracking it here: https://youtrack.jetbrains.com/issue/KTIJ-27360

Also related: https://github.com/JetBrains/compose-multiplatform/issues/3503

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4532">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
