### ISSUE TITLE
Expose a scroll state in the BasicTextField in the common code

### ISSUE THREAD

**Issue by Irineu333** [JetBrains/compose-multiplatform#4533]
I have observed that in the desktop code, the `BasicTextField` exposes a `scrollState`, while in the common code it does not. However, the `CoreTextField` exposes a `textScrollerPosition` in both (different from Android), so I imagine it wouldn't be difficult to expose this control in the `BasicTextField` of the common code, just shouldn't use skiko.

**Comment by m-sasha** [comment]
This would require changes in the common (and now old) `BasicTextField` API, so it's not very likely to happen.

I will, however, leave this ticket open until Compose Multiplatform supports `BasicTextField2`, which already exposes `scrollState`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4533">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
