### ISSUE TITLE
Building an iOS Application fails when using cinterop

### ISSUE THREAD

**Issue by wooram-yang** [JetBrains/compose-multiplatform#4534]
**Describe the bug**
When I try to build an iOS Application with a pure c header file and c source file through cinterop, a linker error occurs. 
I attach the project file.

```
ld: Undefined symbols:
  _test_function, referenced from:
      _Samplecinterop_test_function_wrapper0 in ComposeApp[arm64][2](ComposeApp.framework.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```

**Affected platforms**

- Desktop (macOS)
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): macOS 13.6.4
- OS architecture (x86 or arm64): arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Put the below files into the path `src/nativeInterop/cinterop/`
```
Samplecinterop.h

#ifndef SAMPLE_CINTEROP_H
#define SAMPLE_CINTEROP_H

void test_function();

#endif //SAMPLE_CINTEROP_H
```

```
Samplecinterop.c

#include "Samplecinterop.h"
#include "stdio.h"

void test_function() {
    printf("AAA");
}
```

```
Samplecinterop.def

headers = Samplecinterop.h
package = Samplecinterop
```

2. Put this code into the `build.gradle.kts` file

```
build.gradle.kts

iosTarget.compilations {
    val main by getting {
        cinterops {
            val nativeLibrary by creating {
                defFile(project.file("src/nativeInterop/cinterop/Samplecinterop.def"))
                compilerOpts("-Isrc/nativeInterop/cinterop/")
            }
        }
    }
}
```

3. Select iOS app as the run configuration of Android Studio
4. Run

[Testcinterop.zip](https://github.com/JetBrains/compose-multiplatform/files/14734963/Testcinterop.zip)

**Expected behavior**
Building will be completed and check if calling a pure c functions is successful.

**Comment by mazunin-v-jb** [comment]
Hello!
We're not responsible for this. Please, [create an issue on Kotlin tracker.](kotl.in/issue).
And feel free to reopen this issue if you have any questions.

**Comment by paxbun** [comment]
@wooram-yang I know it's closed, but you're not compiling and linking `Sampleinterop.c`. You must compile it into a `.a` file (using Clang or any other equivalent C toolchain) and put it into `cinterop` like the following.

```
headers = Samplecinterop.h
staticLibraries = libsamplecinterop.a
```

The `package` property in cinterop `.def` files means the Kotlin package name of the generated `.klib` file.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4534">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
