### ISSUE TITLE
Unable to deploy wasmJs after update to version 1.6.1

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-multiplatform#4535]
**Describe the bug**
After [updating](https://github.com/arkivanov/Minesweeper/pull/19) Compose from 1.6.0-beta01 to 1.6.1 I'm no longer able to deploy the `wasmJs` browser app to GitHub Pages using GitHub actions.

I'm [using](https://github.com/arkivanov/Minesweeper/blob/master/.github/workflows/deploy.yml) `JamesIves/github-pages-deploy-action@v4.5.0` action for deployment.

It gives the following error:

```
remote: error: GH013: Repository rule violations found for refs/heads/gh-pages.        
remote: Review all repository rules at http://github.com/arkivanov/Minesweeper/rules?ref=refs%2Fheads%2Fgh-pages        
remote: 
remote: - GITHUB PUSH PROTECTION        
remote:   ——————————————————————————————————————————————————————        
remote:    Resolve the following secrets before pushing again.        
remote:           
remote:    (?) Learn how to resolve a blocked push        
remote:    https://docs.github.com/code-security/secret-scanning/pushing-a-branch-blocked-by-push-protection        
remote:           
remote:           
remote:   —— WorkOS Production API Key —————————————————————————        
remote:    locations:        
remote:      - commit: 854e4b61912faf30fb7892692716b18c935[74](https://github.com/arkivanov/Minesweeper/actions/runs/8410987224/job/23030055824#step:5:75)950        
remote:        path: skiko.wasm:40175        
remote:           
remote:    (?) To push, remove secret from commit(s) or follow this URL to allow the secret.        
remote:    https://github.com/arkivanov/Minesweeper/security/secret-scanning/unblock-secret/2e90EcZCjrL79KQ2I918jKmdyGx        
remote: 
To https://github.com/arkivanov/Minesweeper.git
 ! [remote rejected] github-pages-deploy-action/pdwvzfrfm -> gh-pages (push declined due to repository rule violations)
```

See the [full build log](https://github.com/arkivanov/Minesweeper/actions/runs/8410987224/job/23030055824) for details.

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4535">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
