### ISSUE TITLE
Missing 1.5.10.1 Compose Compiler Code in compose-multiplatform-core Repository

### ISSUE THREAD

**Issue by GavinNovate** [JetBrains/compose-multiplatform#4536]
Hello,

I have recently been compiling the "compose-multiplatform-core" project and have switched to the v1.6.1 tag. I noticed that it depends on the 1.5.10.1 version of the compose compiler. However, I could not find the code for version 1.5.10.1.

In the "compose/compiler/compiler-hosted" directory, I found the ComposePlugin.kt file. Within this file, the KOTLIN_VERSION_EXPECTATION in the checkCompilerVersion function is 1.9.20, which seems to be old code.

Could you please guide me on how I can find the code for the 1.5.10.1 version of the compose compiler?

I am submitting this issue here in the compose-multiplatform repository because I could not submit an issue in the compose-multiplatform-core repository.

Thank you.

**Comment by GavinNovate** [comment]
I think I found it. Is it the branch named "release/compiler-integration-1.5.10"?

**Comment by GavinNovate** [comment]
I used `./gradlew :compose:compiler:compiler:publishToMavenLocal` to compile, and found that in mavenLocal, it is `androidx.compose.compiler:compiler` instead of `org.jetbrains.compose.compiler:compiler`. Should the correct compilation result be the latter?

**Comment by GavinNovate** [comment]
I found that using the following commands works:

```
export COMPOSE_CUSTOM_GROUP=org.jetbrains.compose
./gradlew :compose:compiler:compiler:publishToMavenLocal

export COMPOSE_CUSTOM_GROUP=org.jetbrains.compose
./gradlew :compose:compiler:compiler-hosted:publishToMavenLocal 
```

**Comment by GavinNovate** [comment]
Thank you for your response! My issue has been resolved.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4536">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
