### ISSUE TITLE
String resources have huge impact on app startup time

### ISSUE THREAD

**Issue by mlilienberg** [JetBrains/compose-multiplatform#4537]
**Describe the problem**
A hello world sample project has an app startup time of multiple seconds when the string resources contain multiple thousand items. 

- I created a small sample project to assess the compatibility of the string set we use in our production applications. Currently, I have added approximately 4200 strings for one localization only. However, when the entry screen accesses one of the string resources, the app's startup time increases to multiple seconds. On the other hand, when none of the bundled resources are accessed, the time until the splash logo is replaced by the initial screen feels immediate. This issue is present on both Android and iOS platforms.

**Affected platforms**
Select one of the platforms below:
- Android
- iOS

**Versions**
- Kotlin version: 1.9.23
- Compose Multiplatform version: 1.6.1

**Reproduction steps**
Simply utilize the sample project and incorporate 4000 strings into it. Ensure that at least one of the strings is accessed within a composable.

**Comment by terrakok** [comment]
Could you check it with [1.6.10-dev1523](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10-dev1523) version? Resource class loading was reimplemented to be lazy

**Comment by terrakok** [comment]
I checked it. The problem is still here. I'll think what to do

**Comment by terrakok** [comment]
The bottleneck is a XML file parsing. I guess we can inject parsed resource's texts into the code during compile time. I will play with that. Thank you for the feedback

**Comment by mlilienberg** [comment]
Thank you for taking the time to investigate this issue. I believe that resource handling is one of the most crucial foundations of compose multiplatform. While I am uncertain if it warrants a separate ticket, it would be beneficial if the resource concept allows the removal of unused strings through obfuscation algorithms like R8.

**Comment by terrakok** [comment]
@mlilienberg could you check the new version?
[1.6.10-dev1559](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10-dev1559)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4537">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
