### ISSUE TITLE
MissingResourceException in Multimodule project with Kotlin 2.0.0-Beta5

### ISSUE THREAD

**Issue by dmitry-stakhov** [JetBrains/compose-multiplatform#4538]
**Describe the bug**
Uncaught Kotlin exception: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: composeResources/jp.ne.paypay.app_platform_sdk.ui.generated.resources/drawable/ic_check_mark_blue.xml

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 2.0.0-Beta5
- Compose Multiplatform version*: 1.6.10-dev1523
- OS version(s)* (required for Desktop and iOS issues): iOS 17.4

**To Reproduce**
Reproducer: [ComposeReproducer.zip](https://github.com/JetBrains/compose-multiplatform/files/14741911/ComposeReproducer.zip)
Steps and/or the code snippet to reproduce the behavior:
1. Build the XCFramework `./gradlew :ComposeReproducer:podPublishDebugXCFramework `
2. Add to iOS app
3. Add `ImageSimpleController` to iOS screen
4. Run the app and navigate to the screen

**Expected behavior**
The image should be shown. The resource should be found.

**Comment by terrakok** [comment]
The build of XCFramework is not supported. Resources are only packed into a final iOS application.
There is no a common approach for the resource sharing in the Native world. Usually it is done by package managers such as Cocoapods or SPM.
Something can be done on the Kotlin gradle plugin side. You may file an issue on https://kotl.in/issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4538">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
