### ISSUE TITLE
using drag events prevent desktop app to close

### ISSUE THREAD

**Issue by hgourvest** [JetBrains/compose-multiplatform#4541]
**Describe the bug**
Using "Modifier.onExternalDrag" sometimes prevents the application from closing properly when you close the window. The window closes but the application remains active.

**Affected platforms**
- Desktop Linux

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0
- OS version(s)* (required for Desktop and iOS issues): Fedora 39 
- OS architecture (x86 or arm64): x86_64
- JDK (for desktop issues): corretto 17

**To Reproduce**
I created an empty project using the "Kotlin Multiplatform Wizard", then modified the main function as indicated below. I run the "run" gradle task and then close the window several times without dragging any file to the window. I tested on all 3 platforms: Windows Linux and Mac OS. The problem only occurs on Linux, the error frequency is 25-33%.

```
fun main() = application {
    val windowState = rememberWindowState(width = 800.dp, height = 600.dp)
   Window(
        state = windowState,
        onCloseRequest = ::exitApplication,
    ) {
       Row(Modifier.onExternalDrag(onDrop = {}))  {

       }
    }
}
```
The problem occurs after 2 or 4 attempts.

**Expected behavior**
a call to "::exitApplication" should closes the application.

**Comment by hgourvest** [comment]
I created an empty project using the "Kotlin Multiplatform Wizard", then modified the main function as indicated in the bug report. I run the "run" gradle task and then close the window several times without dragging any file to the window. I tested on all 3 platforms: Windows Linux and Mac OS. The problem only occurs on Linux, the error frequency is 25-33%.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4541">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
