### ISSUE TITLE
How to convert String into StringResource

### ISSUE THREAD

**Issue by hulkdx** [JetBrains/compose-multiplatform#4550]
Is it possible to convert a normal string into StringResource ?

**Comment by terrakok** [comment]
No. Could you explain your problem?
The resource is much complicated than a just text. It has a lot of meta info for adopting to an environment.

**Comment by terrakok** [comment]
I suggest to avoid mix different resources together.
It is not only runtime library but the code generation and an application build all together.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4550">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
