### ISSUE TITLE
Incorrect example in Compose Desktop entry point documentation

### ISSUE THREAD

**Issue by Ribesg** [JetBrains/compose-multiplatform#4553]
[This example in the documentation of the `application` function](https://github.com/JetBrains/compose-multiplatform-core/blob/release/1.6.1/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/window/Application.desktop.kt#L71-L84) does not compile. It tries to modify a `val` and misses a required argument when calling `Window` :
```kotlin
fun main() = application {
    val isSplashScreenShowing by remember { mutableStateOf(true) }

    LaunchedEffect(Unit) {
        delay(2000)
        isSplashScreenShowing = false
    }

    if (isSplashScreenShowing) {
        Window(title = "Splash") {}
    } else {
        Window(title = "App") {}
    }
}
```
This would be a working version:
```kotlin
fun main() = application {
    var isSplashScreenShowing by remember { mutableStateOf(true) }

    LaunchedEffect(Unit) {
        delay(2000)
        isSplashScreenShowing = false
    }

    if (isSplashScreenShowing) {
        Window(onCloseRequest = ::exitApplication, title = "Splash") {}
    } else {
        Window(onCloseRequest = ::exitApplication, title = "App") {}
    }
}
```
I initially wanted to contribute but I'm unsure about the process.

**Comment by mazunin-v-jb** [comment]
Hello!
You can open a PR with this change right in the compose-multiplatform-core repo.
For this:
1. Make a fork of compose-multiplatform-core 
2. Clone repo to your local machine
3. Make new branch, make changes, commit your change and push your changes to your fork on GitHub
4. Go to the compose-multiplatform-core, and create new PR. You'll be able to choose your branch and your fork.

Please, feel free to ask here any questions regarding the process if something is unclear.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4553">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
