### ISSUE TITLE
How to make a "Single Instance App" for Desktop

### ISSUE THREAD

**Issue by dev-jesser** [JetBrains/compose-multiplatform#4554]
Is there a built-in feature or gradle configuration etc. that would prevent a user from running multiple instances of a Desktop app built in Kotlin Multiplatform?

I got an app running on a touch screen Windows computer but run into a problem where if the user hides the app by mistake (accidently using gestures to go to the Windows desktop), when they click on the app's executable it opens up a new instance of the app, but my preference would be it pulls up the existing running instance. I don't think the [singleWindowApplication](https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Window_API_new#function-singlewindowapplication) is what I'm looking for as it seems that's for within an app's instance.

**Comment by m-sasha** [comment]
There's no facility for this in Compose, and it falls just outside of the scope.

There are Java libraries that solve this. A quick googling found this one: https://www.sauronsoftware.it/projects/junique/

**Comment by dev-jesser** [comment]
For posterity, I did the following to make the above feature work:

1. Added the following check at the start of the app, which prevents the user from starting the app up twice. Taken from https://stackoverflow.com/a/52950331/13225055 :

```kotlin
fun lockInstance(): Boolean {
   return try {
      val file = File("/path/to/my/lockfile.lock")
      val randomAccessFile = RandomAccessFile(file, "rw")
      val fileLock = randomAccessFile.channel.tryLock()
      if (fileLock != null && fileLock.isValid && !fileLock.isShared) {
         Runtime.getRuntime().addShutdownHook(Thread {
            try {
               fileLock.release()
               randomAccessFile.close()
               file.delete()
            } catch (e: Exception) {
               false // log error
            }
         })
         true
      }
   } catch (e: Exception) {
      false // and log whatever
   }
}
```

2. Used a Powershell script and turned it into an .exe file which I copied into the my app's `appResourcesRootDir` directory so it can be copied out of the app's directory when installed. Taken mainly from https://stackoverflow.com/a/42567337/13225055 :

```sh
$programName = "MyApp"

if (Get-Process -Name $programName -ErrorAction SilentlyContinue) {
   $programProcesses = Get-Process -Name $programName | Sort-Object -Property WorkingSet -Descending

   Add-Type @"
using System;
using System.Runtime.InteropServices;
public class WinAp {
   [DllImport("user32.dll")]
   [return: MarshalAs(UnmanagedType.Bool)]
   public static extern bool SetForegroundWindow(IntPtr hWnd);

   [DllImport("user32.dll")]
   [return: MarshalAs(UnmanagedType.Bool)]
   public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
}
"@

   $hWnd = $programProcesses[0].MainWindowHandle
   [void] [WinAp]::SetForegroundWindow($hWnd);
   [void] [WinAp]::ShowWindow($hWnd, 3);
} else {
   # If I ran Start-Process it wouldn't show the app's splash screen
   Set-Location "c:\Program Files\MyApp"
   .\MyApp.exe
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4554">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
