### ISSUE TITLE
Expose resource generation task property in Gradle via `compose.resources` block

### ISSUE THREAD

**Issue by paxbun** [JetBrains/compose-multiplatform#4564]
For Kotlin compilation, we can access the compilation task via `KotlinCompilation.compileTaskProvider` property. Gradle plugins use this property to generate required Kotlin files before building.

Likewise, could you consider adding `ResourcesExtension.resourceTaskProvider` so users can make it depend on custom resource downloading tasks? It would be useful for those who have their own way of manging resources in their CI/CD pipeline.

We're downloading the required resource files from Azure Blob Storage and making the resource generation task depend on that download task so the download occurs during IDE import. We're achieving this like the following:

```kotlin
// downloads files from Azure Blob Storage
blobStorage {
  subscription = "..."
  accountName = "..."
  ...
  afterEvaluate {
    tasks.named("generateComposeResClass")
      .dependsOn(downloadTaskProvider /* from blobStorage block */)
    tasks.named("copyDebugFontsToAndroidAssets")
      .dependsOn(downloadTaskProvider)
    tasks.named("copyReleaseFontsToAndroidAssets")
      .dependsOn(downloadTaskProvider)
    tasks.named("syncComposeResourcesForIos")
      .dependsOn(downloadTaskProvider)
  }
}
```

and this is what we want to achieve:

```kotlin
// downloads files from Azure Blob Storage
blobStorage {
  subscription = "..."
  accountName = "..."
  ...
}

compose.resources {
  resourceTaskProvider.dependsOn(blobStorage.downloadTaskProvider)
}
```

**Comment by terrakok** [comment]
Why are you not able to use:
```kotlin
tasks.configureEach {
    if (name == "generateComposeResClass") {
        shouldRunAfter(blobStorage.downloadTaskProvider)
    }
}
```

**Comment by paxbun** [comment]
@terrakok We can do that, and we're actually doing that (though we're using `dependsOn`), but I'm just requesting some statically-checked way to achieve the same thing.

For me, it would be best to be able to use properties like `res` or `resources` as in Android Gradle Plugin:

```kotlin
// like the following
android {
  sourceSets {
    getByName("main").res.srcDirs(...)
  }
}

val blobStorageDownloadDir = project.layout.buildDirectory.dir(...)
blobStorage {
  destination = blobStorageDownloadDir
}
compose.resources {
  dirs(blobStorageDownloadDir)
}
```

This entails that the user can run a task, and the resource packaging task must depend on that custom task. However, I think this needs more work and stabilizing more APIs, so I just requested a static property to access the resource syncing task.

As there are many people migrating their Android app to Compose Multiplatform (or KMP), I think providing similar features on the Gradle side as well will benefit more people.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4564">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
