### ISSUE TITLE
iOS compose screen freeze when action moves user out of the app

### ISSUE THREAD

**Issue by BitByAVampire** [JetBrains/compose-multiplatform#4566]
**Describe the bug**
when triggering a navigation action pushing user outside of the app, if user returns again to the same screen, the animation effect that was happening just before the user had left are stuck frozen. 

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.5.12
- OS version(s)* (required for Desktop and iOS issues): ios 16.4, 17.2.1
- OS architecture (x86 or arm64):
- Device (model or simulator for iOS issues): iPhone 14, iPhone XR
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a screen that has a trigger that has animation effect like a button (with ripple effect) or a toggle switcher which navigates the user out of the app
2. trigger the action
3. on returning to the screen, sometimes the trigger animation is stuck frozen

**Expected behavior**
the animation effect should be gone. 
**Screenshots**
![Simulator Screenshot - iPhone 14 - 2024-04-01 at 00 29 29](https://github.com/JetBrains/compose-multiplatform/assets/147002455/f3573557-0e34-452a-ba14-0000508953dc)
![Simulator Screenshot - iPhone 14 - 2024-04-01 at 11 29 57](https://github.com/JetBrains/compose-multiplatform/assets/147002455/190c672e-2483-4a66-af36-69c105004b58)

**Additional context**

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4566">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
