### ISSUE TITLE
Resources (files) are not packed in SPM for native targets

### ISSUE THREAD

**Issue by checoalejandro** [JetBrains/compose-multiplatform#4569]
**Describe the bug**
When using compose-resources in a multiplatform project for iOS and Android and exported as an SPM with multiplatform-swiftpackage, when attempting to use resources in /files directory, the following error is thrown:

`Cause: org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: files/demo/majel.html`

This error is not happening when using library as a pod.

**Affected platforms**

- Desktop (macOS)
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): 17.0.1
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): simulator/physical device.
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Setup compose resources in a kotlin multiplatform library for Android and iOS.
2. Import multiplatform-swiftpackage gradle plugin to create SPM with `createSwiftPackage` task. This gets generated in `swiftpackage` directory.
3. After the package is created, import to an iOS application project in XCode, go to target dependencies and add local SPM.
4. Run project and use a section that requires any resource and crash will be thrown.

**Expected behavior**
SPM must contain the resources in Package.swift file and inside the XCFramework, resources directory must be created and included files.

**Additional context**
Is there any workaround to force the inclusion of these resources manually?
This looks to me more of a dependency on multiplatform-swiftpackage but need details on what to do to make it included.

**Comment by paxbun** [comment]
As stated in the [Docs](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html), multimodule resources are not supported yet. You can also check that in the actual code, which always references `NSBundle.mainBundle`, so it means the current Gradle plugin implementation copies all resources to the app directly, no matter the Kotlin library is built as a static library or a dynamic library.

https://github.com/JetBrains/compose-multiplatform/blob/04edeed084d9882d3a28950a11e722a3eb2860c7/components/resources/library/src/iosMain/kotlin/org/jetbrains/compose/resources/ResourceReader.ios.kt#L12-L15

In theory, static frameworks can't have resources (they're not represented as an `NSBundle`), so you have to export your library as a dynamic framework.

**Comment by terrakok** [comment]
Compose gradle plugin doesn't support publication native frameworks as SPM or other packages.
@paxbun is absolutely right. you may get resources manually from the build and do what you want, as workaround now

**Comment by checoalejandro** [comment]
I am able to get the bundle of resources when integrating mocko-resources along with its compose implementation. I will continue testing and if it works as expected, I will detail the process to make this XCFramework to contain resources.

**Comment by vcoolish** [comment]
> I am able to get the bundle of resources when integrating mocko-resources along with its compose implementation. I will continue testing and if it works as expected, I will detail the process to make this XCFramework to contain resources.

Hi! could you please share some details?

**Comment by terrakok** [comment]
Duplicates https://github.com/JetBrains/compose-multiplatform/issues/4643

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4569">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
