### ISSUE TITLE
Empty Material 3 TextField with label jumps when it gets focus

### ISSUE THREAD

**Issue by GazimSoliev** [JetBrains/compose-multiplatform#4570]
**Describe the bug**
Empty Material 3 TextField with label jumps when it gets focus
**Affected platforms**

- Desktop (Windows, Linux, macOS): Linux

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): 6.8.2-arch2-1
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): -
- JDK (for desktop issues): Temurin 17.0.10

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
```
Box(
    modifier = Modifier.fillMaxSize(),
    contentAlignment = Alignment.Center
) {
    Column(
        verticalArrangement = Arrangement.spacedBy(8.dp),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text("Hello")
        TextField(TextFieldValue(), {}, label = { Text("Label 1") })
        TextField(TextFieldValue(), {}, label = { Text("Label 2") })
    }
}
```

**Expected behavior**
It doesn't jump when it gets focus

**Video**

https://github.com/JetBrains/compose-multiplatform/assets/63443274/8cdd3a82-ede1-4a40-b664-4882a65ba736

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4570">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Feinate** [comment]
Same here. I don't know why.
