### ISSUE TITLE
stringResource filters the default when getting the resource path

### ISSUE THREAD

**Issue by Zhou-Kt** [JetBrains/compose-multiplatform#4571]
**Describe the bug**
Hey, I've found that on Android or Desktop, in  `org.jetbrains.compose.resources.ResourcesEnvironment.kt` , the extension function  `getPathByEnvironment`  of  `Resource`  class will filter the default `StringResource` (values/strings.xml) by `filterBy`. For example, I have default (its `qualifiers` is an empty `Set`), zh-HK, zh-TW and zh-MO in `StringResource.items`, and the platform language is zh-CN, the first `filterBy` will filter out zh-HK, zh-TW, and zh-MO, and the second `filterBy` will return an empty `List` because CN cannot be found, and finally cause an exception, instead of returning the default path. I have given a modification (it works in this case) in screenshot 2 below.
(My English is poor, wish I expressed it clearly enough.)

**Affected platforms**
- Desktop (Windows, Linux, macOS)
- Android
- other platforms, may be

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1

**Screenshots**
<img width="809" alt="Snipaste_2024-04-03_14-26-42" src="https://github.com/JetBrains/compose-multiplatform/assets/102935354/22fa0b6f-8cee-4d1c-a073-e3d22f0d2777">
<img width="722" alt="Snipaste_2024-04-03_14-27-39" src="https://github.com/JetBrains/compose-multiplatform/assets/102935354/fd6d90cc-ba6c-4dde-b33e-fc2fe49afae7">

**Comment by terrakok** [comment]
In a case when you provide region's specific localizations, you are suppose to provide default localization without the region (in your case `values-zh`). To get the default without any qualifier is not right because it can be an absolutely different locale.

The same loggic is being used in the Android:
https://developer.android.com/guide/topics/resources/providing-resources#BestMatch

![image](https://github.com/JetBrains/compose-multiplatform/assets/3532155/d788aeb5-cef4-4b8a-bee9-2d07008efe05)

**Comment by Zhou-Kt** [comment]
Okay, thank you very much, it's my mistake, i'm following the Android Resource approach, whose default string resource doesn't need to qualify "-zh" to values.

**Comment by terrakok** [comment]
Oh! I guess I got your point: the android logic works with a locale+region as a single qualifier. I need a time to think about it

**Comment by Zhou-Kt** [comment]
> Oh! I guess I got your point: the android logic works with a locale+region as a single qualifier. I need a time to think about it

Yes, since I only use zh, changing values to values-zh would have solved my case, but if there are multiple locales, lazy people like me would be more inclined to just create one default values for all locales.

**Comment by Thomas-Vos** [comment]
Same issue here. Strings in `values/` are English for my app. I added `values-en-rGB/` for UK English. Now when your phone is set to English with any other region it crashes. It should fallback to `values/` because there is no `values-en/`.
