### ISSUE TITLE
Compose Multiplatform string resources: only accepting "strings.xml"

### ISSUE THREAD

**Issue by dbaroncelli** [JetBrains/compose-multiplatform#4572]
**Describe the bug**
I tried to migrate some Android string resources to a Compose Multiplatform project.
These are multiple xml string files.
I get the error:
GenerateResClassTask was failed: java.lang.IllegalStateException: Unknown resource type: 'values'.

The error goes away only if I keep 1 file named "strings.xml".
It seems it only accepts strings resource files called "strings.xml"

**Affected platforms**
I tried only on Desktop

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues):  Mac Sonoma 14.4.1

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. create multiple XML string resource files inside the folder "commonMain/composeResources/values"

**Expected behavior**
it should work with no errors

**Additional context**
The error goes away only if I keep 1 file named "strings.xml".
It seems it only accepts strings resource files called "strings.xml"

**Comment by terrakok** [comment]
1) it was by design and described in the documentation
2) it was fixed in the latest dev builds

**Comment by dbaroncelli** [comment]
Does it mean in the next release, we can have multiple resource string files?

**Comment by terrakok** [comment]
yes

**Comment by KevinnZou** [comment]
@terrakok I also encountered a similar issue [here](https://github.com/KevinnZou/compose-webview-multiplatform/issues/148). It does not allow us to have the custom resource folder. Is it possible to open this restriction?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4572">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
