### ISSUE TITLE
Cannot make undecorated window fullscreen

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#4573]
**Describe the bug**

An undecorated window refuses to go fullscreen.

**Affected platforms**

- Desktop (macOS)

**Versions**
- Kotlin version*: 2.0.0-Beta5
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): macos
- OS architecture (x86 or arm64):arm64
- JDK (for desktop issues): 20

**To Reproduce**

```kotlin
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.WindowPlacement.Fullscreen
import androidx.compose.ui.window.WindowState
import androidx.compose.ui.window.application


fun main() {
    val state = WindowState()
    application {
        Window(
            onCloseRequest = ::exitApplication,
            state = state,
            undecorated = true
        ) {
            Box(Modifier.background(Color.DarkGray).fillMaxSize()) {
                Button(
                    onClick = {
                        state.placement = Fullscreen
                    }
                ) {
                    Text("Fullscreen")
                }
            }
        }
    }
}

```

**Expected behavior**
For the window to go fullscreen

**Actual behavior**

The window looks like it attempts to go fullscreen, but it refuses to fill the whole screen size. It shows the content of the window surrounded by black space.

**Screenshots**

<img width="1719" alt="Screenshot 2024-04-04 at 10 17 43 AM" src="https://github.com/JetBrains/compose-multiplatform/assets/12831489/83d6a8a6-8c3c-46e4-b9d9-faaf5eac33c0">

**Additional context**

Note that if the window is decorated, fullscreen works as expected

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4573">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
