### ISSUE TITLE
Kotlin `object` is null: incorrect static initialization

### ISSUE THREAD

**Issue by Zhou-Kt** [JetBrains/compose-multiplatform#4588]
**Describe the bug**
I used the following code and got an unexpected value null.
```
sealed class Route {
    data object Home : Route()

    data object Personal: Route()

    companion object {
        val list = listOf(Home, Personal)
    }
}

data class Info(val route: Route)


fun main() = application {
    val info = remember { mutableStateListOf(Info(Route.Home)) }

    println(Route.list) // [null, Personal]
}
```

**Affected platforms**
- Desktop (Windows, Linux, macOS)
- Android
- others, may be

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1

**Comment by Zhou-Kt** [comment]
> First, I created a Minimal Reproducible Example (MRE) that presents the same exact issue:
> 
> ```kotlin
> abstract class Route {
>     object Home : Route()
> 
>     object Personal : Route()
> 
>     companion object {
>         @JvmStatic val home = Home
>         @JvmStatic val personal = Personal
>     }
> }
> 
> fun main() {
>     Route.Home // this causes the issue
>     println(Route.home) // null
>     println(Route.personal) // Route$Personal@somehash
> }
> ```
> 
> In the MRE,
> 
> 1. I got rid of Compose entirely — in fact I wouldn't expect the Compose compiler to do anything about those classes given they don't even contain `@Composable`s or anything.
> 2. I replaced the `sealed` modifier of `Route` with `abstract` — in fact `sealed` does nothing besides providing additional guarantees from the Kotlin compiler about which subclasses are allowed, and similar guarantees by the JVM because of a JVM attribute added to it.
> 3. I removed the `data` modifier from `Home` and `Personal` — in fact `data` does nothing besides auto-generating implementations for `Any.hashCode()`, `Any.equals(Any?)`, and `Any.toString()`, plus generating a `copy` method and `componentN()` methods for constructor properties (and none of these members are referenced in the MRE, so they're irrelevant).
> 4. I removed the `Info` class entirely, as I felt that that was unrelated and that the real culprit was the `Route.Home` reference in `main`.
> 5. I replaced the `Route.list` companion field with a `home` and a `personal` fields initialized to the singleton instances of `Home` and `Personal`, respectively — this modification maintains the same side effects of the instance constructor of `Route.Companion` and therefore of its static constructor as well (that is, excluding that `listOf` was the issue, which seemed unrelated).
> 6. I added the `@JvmField` annotation to the `Route.home` and `Route.personal` fields to get us rid of redundant getters for them and to make them static so we can forget of the generated `Route.Companion` class.
> 
> Interestingly, when removing the first line inside the `main` function, where `Route.Home` is first referenced, the issue disappears.
> 
> Suspecting that the issue would be about the side effects of the static constructors initializing fields, I wanted to know the precise order in which they were called. Therefore, I set out to insert some `println` statements to debug. However, there's no way to add a static constructor to an `object` definition in Kotlin code, because `init` inside an `object` definition is its instance constructor. For this purpose, I converted the `object` definitions to plain classes and defined the static field `INSTANCE` (see [1]) from within Kotlin code. The result is in [this Kotlin playground](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS45LjIzIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiYWJzdHJhY3QgY2xhc3MgUm91dGUge1xuICAgIGNsYXNzIEhvbWUgOiBSb3V0ZSgpIHtcbiAgICAgICAgY29tcGFuaW9uIG9iamVjdCB7XG4gICAgICAgICAgICBpbml0IHsgcHJpbnRsbihcIkhvbWUuPGNsaW5pdD4gc3RhcnRcIikgfVxuICAgICAgICAgICAgQEp2bUZpZWxkIHZhbCBJTlNUQU5DRSA9IEhvbWUoKVxuICAgICAgICAgICAgaW5pdCB7IHByaW50bG4oXCJIb21lLjxjbGluaXQ+IGVuZFwiKSB9XG4gICAgICAgIH1cbiAgICB9XG5cbiAgICBjbGFzcyBQZXJzb25hbCA6IFJvdXRlKCkge1xuICAgICAgICBjb21wYW5pb24gb2JqZWN0IHtcbiAgICAgICAgICAgIGluaXQgeyBwcmludGxuKFwiUGVyc29uYWwuPGNsaW5pdD4gc3RhcnRcIikgfVxuICAgICAgICAgICAgQEp2bUZpZWxkIHZhbCBJTlNUQU5DRSA9IFBlcnNvbmFsKClcbiAgICAgICAgICAgIGluaXQgeyBwcmludGxuKFwiUGVyc29uYWwuPGNsaW5pdD4gZW5kXCIpIH1cbiAgICAgICAgfVxuICAgIH1cblxuICAgIGNvbXBhbmlvbiBvYmplY3Qge1xuICAgICAgICBpbml0IHsgcHJpbnRsbihcIlJvdXRlLjxjbGluaXQ+IHN0YXJ0XCIpIH1cbiAgICAgICAgQEp2bUZpZWxkIHZhbCBob21lID0gSG9tZS5JTlNUQU5DRVxuICAgICAgICBpbml0IHsgcHJpbnRsbihcIlJvdXRlLjxjbGluaXQ+IGFmdGVyIFJvdXRlLmhvbWUgaXMgaW5pdGlhbGl6ZWRcIikgfVxuICAgICAgICBASnZtRmllbGQgdmFsIHBlcnNvbmFsID0gUGVyc29uYWwuSU5TVEFOQ0VcbiAgICAgICAgaW5pdCB7IHByaW50bG4oXCJSb3V0ZS48Y2xpbml0PiBlbmRcIikgfVxuICAgIH1cbn1cblxuZnVuIG1haW4oKSB7XG4gICAgcHJpbnRsbihcIkF0dGVtcHRpbmcgdG8gY2FsbCBIb21lLjxjbGluaXQ+XCIpXG4gICAgUm91dGUuSG9tZSAvLyB0aGlzIGlzIHRoZSBpc3N1ZVxuICAgIHByaW50bG4oXCJBdHRlbXB0aW5nIHRvIGNhbGwgUm91dGUuPGNsaW5pdD5cIilcbiAgICBwcmludGxuKFJvdXRlLmhvbWUpIC8vIG51bGxcbiAgICBwcmludGxuKFJvdXRlLnBlcnNvbmFsKSAvLyBSb3V0ZSRIb21lQHNvbWVoYXNoXG59In0=).
> 
> Note that in this modified example, the `Route.Home` reference inside `main` is no longer referencing to the singleton instance of `Route.Home` as it did when using Kotlin `object`s, because that would now be `Route.Home.INSTANCE`. It is instead just forcing the JVM to load the `Route.Home` class, which in turn calls its static constructor, which still initializes the `INSTANCE` field. Therefore, the difference is just that we got rid of a field read, but field reads have no side effects in a single-threaded environment. Plus, interestingly, if we load `Route` before we load `Home` (as shown in the first line inside `main`), the issue disappears. Which leads us to believe that the the issue is a side effect of loading `Home` before `Route`.
> 
> By running the [same Kotlin playground](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS45LjIzIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiYWJzdHJhY3QgY2xhc3MgUm91dGUge1xuICAgIGNsYXNzIEhvbWUgOiBSb3V0ZSgpIHtcbiAgICAgICAgY29tcGFuaW9uIG9iamVjdCB7XG4gICAgICAgICAgICBpbml0IHsgcHJpbnRsbihcIkhvbWUuPGNsaW5pdD4gc3RhcnRcIikgfVxuICAgICAgICAgICAgQEp2bUZpZWxkIHZhbCBJTlNUQU5DRSA9IEhvbWUoKVxuICAgICAgICAgICAgaW5pdCB7IHByaW50bG4oXCJIb21lLjxjbGluaXQ+IGVuZFwiKSB9XG4gICAgICAgIH1cbiAgICB9XG5cbiAgICBjbGFzcyBQZXJzb25hbCA6IFJvdXRlKCkge1xuICAgICAgICBjb21wYW5pb24gb2JqZWN0IHtcbiAgICAgICAgICAgIGluaXQgeyBwcmludGxuKFwiUGVyc29uYWwuPGNsaW5pdD4gc3RhcnRcIikgfVxuICAgICAgICAgICAgQEp2bUZpZWxkIHZhbCBJTlNUQU5DRSA9IFBlcnNvbmFsKClcbiAgICAgICAgICAgIGluaXQgeyBwcmludGxuKFwiUGVyc29uYWwuPGNsaW5pdD4gZW5kXCIpIH1cbiAgICAgICAgfVxuICAgIH1cblxuICAgIGNvbXBhbmlvbiBvYmplY3Qge1xuICAgICAgICBpbml0IHsgcHJpbnRsbihcIlJvdXRlLjxjbGluaXQ+IHN0YXJ0XCIpIH1cbiAgICAgICAgQEp2bUZpZWxkIHZhbCBob21lID0gSG9tZS5JTlNUQU5DRVxuICAgICAgICBpbml0IHsgcHJpbnRsbihcIlJvdXRlLjxjbGluaXQ+IGFmdGVyIFJvdXRlLmhvbWUgaXMgaW5pdGlhbGl6ZWRcIikgfVxuICAgICAgICBASnZtRmllbGQgdmFsIHBlcnNvbmFsID0gUGVyc29uYWwuSU5TVEFOQ0VcbiAgICAgICAgaW5pdCB7IHByaW50bG4oXCJSb3V0ZS48Y2xpbml0PiBlbmRcIikgfVxuICAgIH1cbn1cblxuZnVuIG1haW4oKSB7XG4gICAgcHJpbnRsbihcIkF0dGVtcHRpbmcgdG8gY2FsbCBIb21lLjxjbGluaXQ+XCIpXG4gICAgUm91dGUuSG9tZSAvLyB0aGlzIGlzIHRoZSBpc3N1ZVxuICAgIHByaW50bG4oXCJBdHRlbXB0aW5nIHRvIGNhbGwgUm91dGUuPGNsaW5pdD5cIilcbiAgICBwcmludGxuKFJvdXRlLmhvbWUpIC8vIG51bGxcbiAgICBwcmludGxuKFJvdXRlLnBlcnNvbmFsKSAvLyBSb3V0ZSRIb21lQHNvbWVoYXNoXG59In0=), we can observe this output:
> 
> ```
> Attempting to call Home.<clinit>
> Route.<clinit> start
> Route.<clinit> after Route.home is initialized
> Personal.<clinit> start
> Personal.<clinit> end
> Route.<clinit> end
> Home.<clinit> start
> Home.<clinit> end
> Attempting to call Route.<clinit>
> null
> Route$Personal@7530d0a
> ```
> 
> This tells us that `Route.home` is initialized (and therefore `Home.INSTANCE` referenced) before the static constructor of `Home` is called, which is where `Home.INSTANCE` would be initialized. Which means that when `Route.home` is initialized, `Home.INSTANCE` is still uninitialized, and therefore `null` as the JVM specifies.
> 
> By inspecting the generated bytecode, it seems like the Kotlin compiler didn't make any mistakes, so I would conclude that this is actually a JVM issue, whether it's intended behavior or not. Whether the Kotlin compiler could spot situations like this and introduce a fix is another matter.
> 
> The fact is, when `Home` is loaded, as explained above, a new instance of it is created. However, `Home` inherits from `Route`, which means `Route` must be loaded before the instance constructor of `Home` can be called. And loading `Route` has the side effect of calling its own static constructor. Which explains why the `Route`'s static constructor is invariantly invoked before `Home`'s, which makes it so `Route.home` is initialized before `Home.INSTANCE` is initialized. And by the time `Route.personal` is getting initialized, `Route.home` was already initialized, and so `Route` was as well.
> 
> This looks like a cyclic reference in JVM class loading.
> 
> A quick fix would be to `lazy`-initialize `Route.list`, as follows:
> 
> ```kotlin
> sealed class Route {
>     data object Home : Route()
> 
>     data object Personal: Route()
> 
>     companion object {
>         val list by lazy { listOf(Home, Personal) }
>     }
> }
> ```
> 
> _*[1]: A static `INSTANCE` field is generated by the Kotlin compiler in the class of each `object` definition to store its singleton instance._

Wow, that's so professional👍. Thank you for your help.

**Comment by Zhou-Kt** [comment]
@DavideCannizzo my bad, i've reopened the issue and switched to your title (the old title isn't appropriate).

**Comment by DavideCannizzo** [comment]
@Zhou-Kt, I'm not sure if it is of any use to keep this issue open — after all, this doesn't depend on Compose, and at best could be worked around in Kotlin compiler, where I opened a separate issue via YouTrack which I linked in my previous comment.

Anyway, at this point we can wait and see what the Compose Multiplatform team says. I'm just a user of this library, and I don't even have the permission to close this issue.

**Comment by Zhou-Kt** [comment]
> @Zhou-Kt, I'm not sure if it is of any use to keep this issue open — after all, this doesn't depend on Compose, and at best could be worked around in Kotlin compiler, where I opened a separate issue via YouTrack which I linked in my previous comment.
> 
> Anyway, at this point we can wait and see what the Compose Multiplatform team says. I'm just a user of this library, and I don't even have the permission to close this issue.

Yes, at first I thought it was the effect of mutableStateListOf, so that I brought the issue here. One more issue means one more chance to be solved.

**Comment by m-sasha** [comment]
Thanks, @DavideCannizzo, for the detailed analysis. 

As there's nothing for the Compose Multiplatform team to do here, I'm closing the ticket.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4588">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
