### ISSUE TITLE
Hello! How to format decimal values using only Kotlin classes

### ISSUE THREAD

**Issue by ArleyPereira** [JetBrains/compose-multiplatform#4590]
I'm trying to find a way to format decimal values using only Kotlin classes to be compatible with Android and IOS. I need everything to be in Kotlin to be able to run in the commonMain module

**Comment by m-sasha** [comment]
You can use the `String.format` function.

But this is not a question or an issue with Compose.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4590">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
