### ISSUE TITLE
UIKitVIew with MKMapView subview crashes with kotlin.IllegalStateException: Size is out of range.

### ISSUE THREAD

**Issue by antailyaqwer** [JetBrains/compose-multiplatform#4591]
**Describe the bug**
In compose multiplatform on ios UIKitView with MKMapView and modifier FillMaxSize crashes with exception
`Uncaught Kotlin exception: kotlin.IllegalStateException: Size(1179 x 2147483647) is out of range. Each dimension must be between 0 and 16777215.`

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23 
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): ios 17.1.1
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iphone 15 pro

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. generate compose multiplatform project by wizard
2. write next code in App.kt
```
@Composable
internal fun App() = AppTheme {
    Box(
        modifier = Modifier
            .fillMaxSize()
            .height(IntrinsicSize.Min)
            .background(Color.Red)
    ) {
        Box(
            modifier = Modifier.fillMaxSize()
        ) {
            ExpectIosFunction()
        }
    }
}
```

```
@OptIn(ExperimentalForeignApi::class)
@Composable
actual fun ExpectIosFunction() {
    val mapView = remember {
        // Simple UIView() also crashes
        MKMapView()
    }

    Box {
        UIKitView(
            modifier = Modifier.fillMaxSize(),
            factory = {
                UIView().apply {
                    addSubview(mapView)
                    mapView.setFrame(this.bounds)
                }
            }
        )

        Box(
            modifier = Modifier.fillMaxSize()
                .background(Color.Green)
        )
    }
}

```

**Expected behavior**
No crash. Full size view resizing.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4591">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
