### ISSUE TITLE
iOS 17 hidden trackpad doesn't work in the TextFields (hold space bar and swipe to move cursor)

### ISSUE THREAD

**Issue by OSemenovBoyarka** [JetBrains/compose-multiplatform#4593]
**Describe the bug**
The iOS 17 introduced hidden trackpad feature, when you can hold the spacebar and then move the cursor with the swipe on the keyboard. 
This doesn't move the cursor in any TextField in Jetpack Compose Multiplatform.
Surprisingly - the same feature works fine on Android with the same code.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): 17.2
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): any iOS device or simulator

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Add a simple text field to the multiplatform app:
```Kotlin
@Composable
fun App() {
    MaterialTheme {
        var text by remember { mutableStateOf("") }
        TextField(
            modifier = Modifier.fillMaxWidth(),
            value = text,
            onValueChange = { text = it }
        )
    }
}
```
2. Run the app on either iOS 17 device or iOS 17 simulator
3. Enter something in the text field
4. Hold the space bar on the soft keyboard and move finger while holding it

**Expected behavior**
Cursor should move in the direction finger moves. Actually - cursor stays in place.

**Screenshots**
iOS simulator, how it actually works:
https://github.com/JetBrains/compose-multiplatform/assets/6439273/de8baba4-0785-4bb8-905e-6cbb34f58957

The same app running on Android Emulator (API 34):
https://github.com/JetBrains/compose-multiplatform/assets/6439273/57c61cc2-2aa7-44c3-a4c1-3778b0a4c693

**Additional context**
This is the new feature in iOS 17 - https://www.cnet.com/tech/mobile/this-secret-ios-trackpad-makes-typing-on-your-iphone-so-much-easier/

**Comment by m-sasha** [comment]
@mazunin-v-jb Are we working on this?

**Comment by mazunin-v-jb** [comment]
Yes, we're planning to support that but not in the nearest future.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4593">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
