### ISSUE TITLE
Drop frames when scrolling on iOS (only smooth when start screen recording)

### ISSUE THREAD

**Issue by kiethayqua** [JetBrains/compose-multiplatform#4594]
**Describe the problem**
I am using LazyColumn/LazyRow for my list. The scroll behavior was dropped frames. But when I start screen recording, I see the scroll behavior so smooth.

**Affected platforms**
- iOS

**Versions**
- Kotlin version: 1.9.23
- Compose Multiplatform version: 1.6.1
- OS version(s) (required for Desktop and iOS issues): 17.4.1
- OS architecture (x86 or arm64): arm64

**Sample code**
```
LazyRow(modifier = Modifier.fillMaxWidth()) {
    itemsIndexed(blockItems) { itemIndex, item ->
        TemplateMonoInfo(
            data = item,
            onEvent = onEvent,
            modifier = Modifier.width(itemWidth),
            blockId = block.block_id,
            blockIndex = blockIndex,
            itemIndex = itemIndex,
            pageIndex = pageIndex,
            screenName = screenName,
            resultType = resultType,
        )
    }
}
```

**Comment by m-sasha** [comment]
We don't know what `TemplateMonoInfo` is.

Please track this issue: https://github.com/JetBrains/compose-multiplatform/issues/4438
When that issue is fixed, if you are still experiencing frame drops, reopen this bug and provide a complete, but minimal, reproducer.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4594">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
