### ISSUE TITLE
Long press haptic feedback not working on iOS

### ISSUE THREAD

**Issue by msasikanth** [JetBrains/compose-multiplatform#4598]
**Describe the bug**
Long press haptic feedback not working on iOS. I have tried using `LocalHapticFeedback` to perform long-press haptic feedback. It works on Android, but on iOS it's not working.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): iOS 17.4.1
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iPhone 15 Pro

**To Reproduce**

```kt
val haptic = LocalHapticFeedback.current
haptic.performHapticFeedback(HapticFeedbackType.LongPress)
```

**Expected behavior**
Long-press haptic feedback

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4598">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
