### ISSUE TITLE
PagerState.currentPageOffsetFraction Incorrect Value Calculation

### ISSUE THREAD

**Issue by Alliancce1512** [JetBrains/compose-multiplatform#4599]
**Describe the bug**
In my project I need to use Horizontal Pager where I should make specific actions based on the PagerState.currentPageOffsetFraction. My pager should have one or more elements in it, however, when I have three elements and I scroll from the third to the second, the currentPageOffsetFraction becomes greater than 1 and so it breaks my logic around this value. From what I have read from the documentation the value of the currentPageOffsetFraction should vary from -0.5 to 0.5.

**Affected platforms**
- Android

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.61
- Device (model or simulator for iOS issues): Xiaomi MI 11 Lite 5G

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a Horizontal Pager with three elements
2. Add contentPadding (in my case PaddingValues(horizontal = 32.dp))
3. Scroll from the third to the second element
4. Check the value of PagerState.currentPageOffsetFraction (in my case is 4.656613E-9, but when it breaks it is usually greater than 1)

**Expected behavior**
From what I have read the value must vary from -0.5 and 0.5.

**Comment by Alliancce1512** [comment]
Additionally, I have just tried settings the padding values from 32 to 16 and the issue was gone, it seems like this issue only occurs on higher padding values. I have also tried to set only the horizontal padding value to 16 and it works in contrast to 32 and 24 where it did not work.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4599">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
