### ISSUE TITLE
[Desktop] Mouse wheel-scrolling a JScrollPane stops when cursor is over a ComposePanel

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#4601]
**Describe the bug**
If you have a `JScrollPane` with a `ComposePanel` in it, and use the mouse wheel or trackpad to scroll the scrollpane, when the mouse cursor is over the `ComposePanel`, the `JScrollPane` doesn't scroll anymore.

It looks as if the `ComposePanel` were swallowing scroll events, even if its contents aren't scrollable.

**Affected platforms**
- Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-dev1561
- OS version(s): macOS 14.4.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): JBR 17 (latest)

**To Reproduce**
1. Clone https://github.com/rock3r/cfd-repros/
2. Run `NoScrollingOnComposePanel.kt`
3. Try scrolling the `JScrollPane` and notice it stops when the mouse pointer is over a `ComposePanel`

**Expected behavior**
Scrolling should not stop

**Comment by MatkovIvan** [comment]
@rock3r I believe it's similar, but not the same - it should be handled in platform implementation with all of its specifics. Let's keep this issue for tracking the problem in swing panel implementation only

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4601">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
