### ISSUE TITLE
Confusion in reading PNG image from composeResources/files/assets/ in v1.6.0

### ISSUE THREAD

**Issue by Vocaloid2048** [JetBrains/compose-multiplatform#4602]
![image](https://github.com/JetBrains/compose-multiplatform/assets/47070571/d53255e4-6338-4ce4-b9ca-d80e4b34850e)
### Sorry if I've asked a duplicate question
I'm a new beginner in Compose Multiplatform, and I'm just trying to transfer my **Kotlin Compose (Android only) project** to *Compose Multiplatform Project*

## Thx for giving help first! It will save my life!

**Comment by m-sasha** [comment]
Please follow the instructions here: https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4602">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
