### ISSUE TITLE
"Unresolved reference: let" since Compose Multiplatform 1.6.1 on Android Studio

### ISSUE THREAD

**Issue by Tweener** [JetBrains/compose-multiplatform#4606]
**Describe the bug**
Since Compose Multiplatform 1.6.1 (and 1.6.2), whenever I use `.let { ... }` in my Composables, Android Studio shows the error `Unresolved reference: let`. It's only an error in Android Studio, I don't get any compilation error when I run the app.

When I use 1.6.0, I don't get this error.

I've tried "Repair IDE", "Invalidate Caches", didn't fix it.

**Affected platforms**

Not platform related

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.1
- Android Studio version: Android Studio Iguana | 2023.2.1 Patch 2

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Update Compose Multiplatform to version 1.6.1
2. Sync Project with Gradle Files
3. Go to any Composable with `.let { ... }`

**Expected behavior**
`.let { ... }` should not show the error `Unresolved reference: let` in Android Studio.

**Screenshots**
![Screenshot 2024-04-12 at 09 25 50](https://github.com/JetBrains/compose-multiplatform/assets/596985/ae040c2d-3801-415f-beca-ae9bf2f8a031)

**Comment by Nek-12** [comment]
Already reported as https://issuetracker.google.com/issues/331061784

**Comment by Tweener** [comment]
Oh great, thank you! 
So I guess we'll just have to wait for this issue to be resolved.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4606">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
