### ISSUE TITLE
Cannot change dependencies of dependency configuration 'X' after it has been included in dependency resolution

### ISSUE THREAD

**Issue by zacharee** [JetBrains/compose-multiplatform#4608]
**Describe the bug**
When using [1.6.10-dev1561](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10-dev1561) or later, Gradle syncing fails with the error

```
Cannot change dependencies of dependency configuration ':common:androidAndJvmMainApi' after it has been included in dependency resolution.
```

**Affected platforms**

- Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-dev1561 or later.
- OS version(s)* (required for Desktop and iOS issues): macOS 14.5.
- OS architecture (x86 or arm64): arm64.
- Device (model or simulator for iOS issues): 14" M2 Max MacBook Pro.
- JDK (for desktop issues): Oracle OpenJDK 18.0.2, JBR 17.0.10.

**To Reproduce**
1. Clone https://github.com/zacharee/SamloaderKotlin.
2. Set `compose` in `libs.version.toml` to `1.6.10-dev1580`.
3. Attempt to sync the project.

**Expected behavior**
Gradle sync should succeed.

**Comment by terrakok** [comment]
It is the moko resources problem.
It seems that [0.24.0-alpha-5](https://github.com/icerockdev/moko-resources/releases/tag/release%2F0.24.0-alpha-5) has fix for the problem

**Comment by zacharee** [comment]
That was it, thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4608">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
