### ISSUE TITLE
[iOS] Using Compose inside a ShareExtensionViewController renders it black

### ISSUE THREAD

**Issue by alexstyl** [JetBrains/compose-multiplatform#4610]
**Describe the bug**
I am trying to render Compose on a share extension. No matter what I tried, the view renders black.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.5 
- Device (model or simulator for iOS issues): iPhone 15 Simulator

**To Reproduce**
Create an iOS `Share Extension`, replace the ShareViewController with:

```swift
import UIKit
import SwiftUI
import ComposeApp

@objc(ShareExtensionViewController)
class ShareViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        let rootView = ComposeView()
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                        .background(.blue)
        let controller = UIHostingController(rootView: rootView)
       // also tried let controller = MainViewControllerKt.ShareViewController()
        
        controller.view.frame = self.view.bounds
        controller.view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        controller.view.backgroundColor = .clear
        
        addChild(controller)
        view.addSubview(controller.view)
        controller.didMove(toParent: self)
    }
}

struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        MainViewControllerKt.ShareViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}
```

**Expected behavior**
The contents of the `MainViewControllerKt.ShareViewController()` to be rendered

**Actual behavior**
The Compose View is rendered as a black view

**Screenshots**
![Screenshot 2024-04-13 at 15 08 36](https://github.com/JetBrains/compose-multiplatform/assets/1665273/846bf1ad-004e-4ea8-a0dc-52a82b1b5fa1)

**Comment by elijah-semyonov** [comment]
Can you try to rewrite this code using the anchors instead of autoresize mask? It seems to me that the size could be calculated incorrectly in this code.

**Comment by alexstyl** [comment]
I tried this code and the result is the same:

```swift
let rootView = ComposeView()
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .background(Color.white)
        let controller = UIHostingController(rootView: rootView)
               
        self.addChild(controller)

        controller.view.translatesAutoresizingMaskIntoConstraints = false
        self.view.addSubview(controller.view)
        
        controller.view.leadingAnchor.constraint(equalTo: self.view.leadingAnchor).isActive = true
        controller.view.trailingAnchor.constraint(equalTo: self.view.trailingAnchor).isActive = true
        controller.view.topAnchor.constraint(equalTo: self.view.topAnchor).isActive = true
        controller.view.bottomAnchor.constraint(equalTo: self.view.bottomAnchor).isActive = true
        
        controller.didMove(toParent: self)
```

**Comment by alexstyl** [comment]
Keep in mind that I tried the same code with a Swift View and it renders it correctly.

**Comment by elijah-semyonov** [comment]
Thanks, I'll have a look

**Comment by alexstyl** [comment]
@elijah-semyonov did u have a look? could you kindly confirm that is indeed a bug in compose?

**Comment by elijah-semyonov** [comment]
Yes, I reproduced it. Investigating.

**Comment by elijah-semyonov** [comment]
`UIApplication.shared` is illegal to access in App Extensions and we still wrongfully do it in order to ensure, that no drawing happens when app is in background. Working around it will also require us to update Skia. The version we use still performs `MtlIsAppInBackground` check (which does the same thing) and wrongfully exits not even trying to perform the draw logic.

This is possible to fix, but a bit later. We didn't plan supporting such a feature and didn't do any sort of investigations, so there are some implications in existing code (regarding lifecycle, etc).
