### ISSUE TITLE
ios WindowInsets.ime.getBottom return random LAST value when keyboard hide event

### ISSUE THREAD

**Issue by slartus** [JetBrains/compose-multiplatform#4618]
**Describe the bug**
WindowInsets.ime.getBottom return random LAST value on keyboard hide event

**Affected platforms**

- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.2
- OS version(s)* (required for Desktop and iOS issues): iOS 17

**To Reproduce**
```
fun App() {
    MaterialTheme {
        val keyboardController = LocalSoftwareKeyboardController.current
        Column(Modifier.fillMaxWidth(), horizontalAlignment = Alignment.CenterHorizontally) {
            TextField(
                value = "",
                onValueChange = {

                },
                label = { Text("Label") }
            )
            Text(
                text = "padding = ${KeyboardPadding().toString()}"
            )
            Button(onClick = {
                keyboardController?.hide()

            }) {
                Text("Hide keyboard")
            }
        }
    }
}
```
ios target:
```
@Composable
actual fun KeyboardPadding(): Int {
    return WindowInsets.ime.getBottom(LocalDensity.current)
}
```

**Additional context**

https://github.com/JetBrains/compose-multiplatform/assets/1107015/e480cd71-69e4-4c08-b9cc-f2beb656dbc4

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4618">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
