### ISSUE TITLE
`meta name="viewport"` not working properly on mobile browsers

### ISSUE THREAD

**Issue by alejandro-rios** [JetBrains/compose-multiplatform#4620]
**Describe the bug**
I'm using `<meta name="viewport" content="width=device-width, initial-scale=1.0">` to scale the content correctly on mobile browsers, but the result looks resized to fit the content width rather of the device width, this also happens on the device toolbar options from the web browser

**Affected platforms**
- Web (K/JS) - Canvas based API

**Versions**
- *Kotlin version*: 1.9.23
- *Compose Multiplatform version*: 1.6.1

**To Reproduce**
1. Open this [link](https://alejandro-rios.github.io/Boggle-Multiplatform/) in a mobile device, or web browser using the developer tools to get the `mobile preview`
2. See error

**Expected behavior**
Content should look adjusted to the device width

**Screenshots**
index.html

![Screenshot 2024-04-15 at 11 21 51](https://github.com/JetBrains/compose-multiplatform/assets/10689052/a64815f9-6be6-495f-90a3-0ee1606fabbd)

Firefox Focus

<img src="https://github.com/JetBrains/compose-multiplatform/assets/10689052/7599b1e5-6229-4908-a90d-85cf64d43a7a" width="400" />

DuckDuckGo

<img src="https://github.com/JetBrains/compose-multiplatform/assets/10689052/cce46e40-3723-44de-81ba-907fd4a2d2b9" width="400" />

Mobile preview from developer tools

<img src="https://github.com/JetBrains/compose-multiplatform/assets/10689052/d9646dea-4b0b-4013-96d5-7e892171cc8f" width="400" />

**Additional context**
Tested on safari and works as expected

<img src="https://github.com/JetBrains/compose-multiplatform/assets/10689052/aa0d6c08-bad7-4806-9603-81f5fc4bbeb6" width="400" />

Here's the [official repo](https://github.com/alejandro-rios/Boggle-Multiplatform), in case you want to look in the code

**Comment by Schahen** [comment]
The fix will happen in 1.6.10. Why can try build 1.6.10-dev1557 from https://maven.pkg.jetbrains.space which already contained alleged fix

**Comment by alejandro-rios** [comment]
> The fix will happen in 1.6.10. Why can try build 1.6.10-dev1557 from https://maven.pkg.jetbrains.space which already contained alleged fix

Did the update and looks better now, but, somehow is not taking the `padding` in count, here's how it looks on mobile:

<img src="https://github.com/JetBrains/compose-multiplatform/assets/10689052/3ce8346d-c20c-4947-8e98-d267ae8df338" width="400" />

and here is how it looks on mobile browser (with the version you mentioned):

<img src="https://github.com/JetBrains/compose-multiplatform/assets/10689052/22c3a18a-5476-4215-9c22-fe875e901a77" width="400" />

**Comment by LouisCAD** [comment]
Here's a thread where this issue is being discussed:
https://twitter.com/okatrych/status/1782501007546597389?t=Rx7JO-AdAdcgK-pVqa-mMw&s=19

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4620">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
