### ISSUE TITLE
:packageDeb or :packageReleaseDeb fails at jpackage task

### ISSUE THREAD

**Issue by diareuse** [JetBrains/compose-multiplatform#4622]
**Describe the bug**
Packaging deb (or AppImage for that matter) fails on jpackage while using temurin-17 or openjdk-17 due to jpackage input error. Error says non-descriptively "Input length = 1", which I figured out means "Input directory does not exist". To further elaborate…

File `build/compose/tmp/packageReleaseDeb.args.txt` contains input line which points to `build/compose/tmp/packageReleaseDeb/libs`, where `packageReleaseDeb` directory DOES NOT get created for whatever reason and therefore there are literally no input files for jpackage to process.

**Affected platforms**
- Desktop Linux

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): ubuntu-latest (22.04)
- OS architecture (x86 or arm64): x86_64
- Device (model or simulator for iOS issues): n/a
- JDK (for desktop issues): temurin-17 / openjdk-17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Add `TargetFormat.Deb` to `targetFormats` block
2. Run `./gradlew app:packageReleaseDistributionForCurrentOS`

**Expected behavior**
Task outputs .deb file to `build/compose/binaries/**/*.deb`

**Screenshots**
n/a

**Additional context**
n/a

**Comment by diareuse** [comment]
⚠️ There seems to be a lot of things involved in getting just the Linux to build, I'm afraid none of those things are in docs and nobody ever tried to build it. So if any member reads this, I'd love to ask you to at least include this in the docs - if not straight up changing the plugin internals and adding better error messages and failsaves.

---

It seems that apt package `fakeroot` is required together with `binutils` to build linux images. Therefore for anybody reading this:

```bash
sudo apt install -y binutils fakeroot
```

---

If you're also building `.Dmg`, `.Msi` and `.AppImage`, update the `targetFormats` to the following:

```bash
if (System.getProperty("os.name").toLowerCase().contains("linux"))
    targetFormats(TargetFormat.AppImage)
else
    targetFormats(TargetFormat.Dmg, TargetFormat.Msi)
```

Otherwise builds will fail on macOS in the current state (#3814)

---

Update toolchain to at-least JDK21, as JDK17 seems to have broken jpackage for whatever reason.

```groovy
kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}
```

---

If you're also building with proguard, JDK18 is the latest with support by default, so you need to update the proguard as well:

```groovy
buildTypes.release.proguard {
    version.set("7.4.0") // at least 7.4 is required, check https://www.guardsquare.com/manual/releasenotes for newer versions
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4622">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
