### ISSUE TITLE
Memory usage increases exponentially with each opening of `ModalBottomSheet` on `iOS`

### ISSUE THREAD

**Issue by robxyy** [JetBrains/compose-multiplatform#4626]
**Describe the bug**
Memory usage increases exponentially with each opening of `ModalBottomSheet` on `iOS`

**Affected platforms**

- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.2, 1.6.10-dev1583
- OS version(s)* (required for Desktop and iOS issues): 17.4.1
- Device (model or simulator for iOS issues): model

**To Reproduce**
```kotlin
@Composable
fun App() {
  MaterialTheme {
    var openBottomSheet by remember { mutableStateOf(false) }
    Button(onClick = {
      openBottomSheet = true
    }) {
      Text("ModalBottomSheet3")
    }

    if (openBottomSheet) {
      val sheetState = rememberModalBottomSheetState()
      ModalBottomSheet(
        onDismissRequest = {
          openBottomSheet = false
        },
        sheetState = sheetState,
      ) {
        Text("ModalBottomSheet3", Modifier.height(200.dp))
      }
    }
  }
}
```

**Expected behavior**
Normal memory growth

**Screenshots**
<img width="720" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/9105106/9025a286-fe76-4dc5-a563-98183e116444">

**Comment by robxyy** [comment]
After setting `platformLayers` to `false`, memory returned to normal growth.

**Comment by elijah-semyonov** [comment]
Yes, thank you! We've already proved, that the machinery responsible for Dialogs/Popups layers somehow leaks the memory, investigating it.

**Comment by elijah-semyonov** [comment]
Bisected a regression point:
https://github.com/JetBrains/compose-multiplatform-core/pull/1082

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4626">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
