### ISSUE TITLE
Focus is not displayed when requesting focus programmatically upon a mouse action

### ISSUE THREAD

**Issue by dpikhulya** [JetBrains/compose-multiplatform#4629]
**Describe the bug**

Radio button focus is not displayed when requesting focus programmatically. Interestingly, this behavior only takes place when `requestFocus()` is invoked as a result of a mouse action (e.g. when clicking a button that triggers the focus with mouse but not when pressing this button using keyboard alone).

**Affected platforms**

- Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*: 1.8.2
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64): x86
- Device (model or simulator for iOS issues): N/A
- JDK (for desktop issues): Oracle Open JDK 11

**To Reproduce**

Click "Focus RadioButtonWithText" or "Focus RadioButton" with mouse. No focus is highlighted. When pressing these buttons using the keyboard, the focus is displayed.

It should also be noted that despite the fact that focus is not highlighted, the radio button component appears to actually have been focused successfully. This can be checked by pressing the Enter key after either of the "Focus ..." buttons, or using Tab/Shift-Tab to see where the focus is.

The same scenario works fine with `TextField` regardless of how the "Focus..." button was pressed though.

```
public fun main(): Unit = singleWindowApplication {
    val focusRequester1 by remember { mutableStateOf(FocusRequester()) }
    val focusRequester2 by remember { mutableStateOf(FocusRequester()) }
    val focusRequester3 by remember { mutableStateOf(FocusRequester()) }

    Column {
        Button(onClick = { focusRequester1.requestFocus() }) {
            Text("Focus TextField")
        }

        TextField(value="", onValueChange={}, modifier = Modifier.focusRequester(focusRequester1))

        Button(onClick = { focusRequester2.requestFocus() }) {
            Text("Focus RadioButtonWithText")
        }
        var selected1 by remember { mutableStateOf(false) }
        RadioButtonWithText(selected1, { selected1 = !selected1 }, "Radio button", focusRequester2)

        Button(onClick = { focusRequester3.requestFocus() }) {
            Text("Focus RadioButton")
        }

        var selected2 by remember { mutableStateOf(false) }
        RadioButton(
            modifier = Modifier
                .focusable()
                .focusRequester(focusRequester3),
            selected = selected2,
            onClick = { selected2 = !selected2 }
        )
    }

}

@Composable
public fun RadioButtonWithText(
    selected: Boolean,
    onClick: () -> Unit,
    text: String,
    focusRequester: FocusRequester
) {
    Row(
        modifier = Modifier
            .focusRequester(focusRequester)
            .selectable(
                selected = selected,
                onClick = onClick,
                role = RadioButton
            ),
        verticalAlignment = CenterVertically,
    ) {
        RadioButton(
            selected = selected,
            onClick = null
        )
        Text(text)
    }
}
```
**Expected behavior**

The focus should be displayed when invoking `requestFocus` regardless of whether it is triggered via mouse or keyboard.

**Comment by m-sasha** [comment]
Compose doesn't draw the focus indication when in "mouse input mode".

See https://github.com/JetBrains/compose-multiplatform/issues/2818 for a workaround.

Please confirm that this solves the issue for you, so I can close this report as a duplicate.

**Comment by dpikhulya** [comment]
> Compose doesn't draw the focus indication when in "mouse input mode".
> 
> See #2818 for a workaround.
> 
> Please confirm that this solves the issue for you, so I can close this report as a duplicate.

Yes, this workaround appears to work for me and I'd consider these issues as duplicates indeed. Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4629">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
