### ISSUE TITLE
Canvas Limitations on the Web

### ISSUE THREAD

**Issue by altworowsky** [JetBrains/compose-multiplatform#4630]
Efforts for the web target are focussed on _canvas_ as the future. But, _canvas_ has extensive limitations when considered for a general user interface target on the web. I would suggest refocussing on HTML rendering for the web target for the time being.

**Improved or enabled by _canvas_**
1. Rendering accuracy
2. Layout and animation flexibility
3. Rendering performance

**Limited, complicated or prevented by _canvas_**
1. Accessibility
2. Search indexing
3. DevTools
4. Autocomplete (Password Managers)
5. E2E test automation
6. Web analytics (Google Analytics)
7. Session recording (HotJar, LogRocket)
8. Server-side rendering
9. Frames
10. Native interactions (page search, right click, text selection)
11. Native controls (forms, video)
12. Native text rendering
13. Browser plugins (translation, snippets, reader mode)

**Comment by jershell** [comment]
I think the canvas is way avoiding to overhead. Today more frameworks could to work in browser by canvas. Troubles that you presented will be resolved by browsers by providing better api for canvas based applications.

**Comment by jershell** [comment]
Also we have two variants of compose. Compose for web(canvas based) and compose html.

**Comment by terrakok** [comment]
Canvas based applications are a different kind of web apps. It is not the same as html sites.
The main idea behind compose web is to have ability to run the same mobile/desktop application in a browser.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4630">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
