### ISSUE TITLE
iOS accessibility elements locate incorrectly in SwiftUI when position.x is not zero.

### ISSUE THREAD

**Issue by NeilsonHu** [JetBrains/compose-multiplatform#4634]
**Describe the bug**
please check the demo code

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): iOS17
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iphone13
- JDK (for desktop issues): -

**To Reproduce**
- compose part:
`@Composable`
`fun TestView() {`
`    Text(text = "test text")`
`}`
...
`class Factory {`
`fun create(): UIViewController {`
`    return ComposeUIViewController(configure = {`
`        accessibilitySyncOptions = AccessibilitySyncOptions.Always(debugLogger = null)}) {`
`        TextView()`
`}`

- iOS part:
`struct TestComposeView: UIViewControllerRepresentable {`
`    func makeUIViewController(context: UIViewControllerRepresentableContext<TestComposeView>) -> UIViewController`
`    {`
`         Factory.create()`
`    }`
`    func updateUIViewController(`
`        _ uiViewController: UIViewController,`
`        context:UIViewControllerRepresentableContext<TestComposeView>) {`
`    }`
`}`
...
`VStack {`
`    Text("placeholder")`
`    TestComposeView()`
`}`

- enable voice over
- click "test text" label

**Expected behavior**
- "test text" label is focused with a black rectangle and read out

**Actually**
- "test text" label is not clickable
- when click on the screen under the label from no where, it will have a black rectangle and read out "test text"
- looks like the accessibilityFrame of that label is wrong. to be more specific:
- if the label frame is (0, 0, 200, 200) and it's superView's frame (UIViewController.view) is (0, 44, 200, 200),
the accessibilityFrame to UIWindow is supposed to be (0, 44, 200, 200). But actually it shows as (0, 88, 200, 200).

**Screenshots**
- none

**Additional context**
- guessing the logic to calculate the frame of the accessibility elements is wrong.

**Comment by elijah-semyonov** [comment]
Fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/1165

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4634">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
