### ISSUE TITLE
Web (wasm) Browser Zoom not working as expected

### ISSUE THREAD

**Issue by jonas-app** [JetBrains/compose-multiplatform#4636]
**Describe the bug**
If I zoom into the page (+) the content of the compose app just gets smaller if I zoom out the content gets bigger.
Kind of the opposite what should happen.
I just updated compose (from 1.5.4: where this issue did not exist).
As my browser defaults to 125% page zoom I immediately noticed the issue.
But this also happens on manual page zoom as well.

https://github.com/JetBrains/compose-multiplatform/assets/17269256/a22f4f95-dd04-4da5-af65-2b993558170c

- [Sample app used](https://journal-st-jonas-8dc3d02be694be955a0cd09cb3061ab40250620d7226c2.fairpage.net/)
- [Source Code](https://journal.st)

**Affected platforms**

- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*:  1.9.21
- Compose Multiplatform version*: 
compose = "1.6.5"
compose-compiler = "1.5.11"
compose-plugin = "1.6.2"

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Open sample app
2. Change zoom
4. See issue

**Expected behavior**
The compose app always fills the browser window.

**Comment by jonas-app** [comment]
Duplicate of https://github.com/JetBrains/compose-multiplatform/issues/4517

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4636">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
