### ISSUE TITLE
[Wasm] isSystemInDarkTheme does not return a correct value 

### ISSUE THREAD

**Issue by Nek-12** [JetBrains/compose-multiplatform#4637]
**Describe the bug**
isSystemInDarkTheme() always returns false on wasm, even if the system is on dark mode (tested on MacOS Sonoma 14 Chrome)

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.2
Chrome Version 124.0.6367.49 (Official Build) beta (arm64)

**Expected behavior**
isSystemInDarkTheme returns a correct value and updates itself when the theme is changed.

**Comment by Nek-12** [comment]
Pardon me for the mistake - the issue is different. Unlike Android, the app does not set the window background color automatically, hence, a `Modifier.background()` is required at the top level

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4637">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
