### ISSUE TITLE
[Wasm] `composeResources` are not bundled with the wasm application

### ISSUE THREAD

**Issue by Nek-12** [JetBrains/compose-multiplatform#4638]
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.2

**To Reproduce**

1. Create a shared module with wasm target that has `composeResources` defined
2. Create another module that uses the shared module and packages a wasm app
3. Deploy the app. Resources from composeResources of the shared app are not resolved and the app crashes

**Expected behavior**
All resources of all modules are bundled with the wasm application

Workaround: https://github.com/respawn-app/FlowMVI/blob/109e557e95b529d8cefc02d7dcfa7080e7f74502/sample/wasmApp/build.gradle.kts

**Comment by mdsadique-inam** [comment]
works only with Kotlin version 2.0.0 have a look into this https://github.com/JetBrains/compose-multiplatform/pull/4482

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4638">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
