### ISSUE TITLE
[Wasm] Document.visibilityState is not available on Wasm but is on JS

### ISSUE THREAD

**Issue by Nek-12** [JetBrains/compose-multiplatform#4639]
`kotlinx.browser.document.visibilityState` is not resolved on wasm but is on JS. 

Workaround:

```kotlin
@JsFun("(document) => document.visibilityState")
private external fun visibilityState(document: Document): String
```

Compose 1.6.2
Kotlin 1.9.23

**Comment by terrakok** [comment]
This is the Kotlin stdlib issue. Could you file it here: https://kotl.in/issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4639">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
