### ISSUE TITLE
Could not find "org.jetbrains.compose.collection-internal:collection"

### ISSUE THREAD

**Issue by hafiz013** [JetBrains/compose-multiplatform#4641]
**Describe the bug**
> Task :composeApp:compileKotlinIosSimulatorArm64 FAILED
error: Could not find "org.jetbrains.compose.collection-internal:collection" in [/Users/mohdhafiz/Downloads/AssetManagementSystem, /Users/mohdhafiz/.konan/klib, /Users/mohdhafiz/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/common, /Users/mohdhafiz/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/platform/ios_simulator_arm64]
error: Compilation finished with errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':composeApp:compileKotlinIosSimulatorArm64'.
> Compilation finished with errors

Note: I suspect after update jetpack compose plugin 1.6.0 this error come out. 

**Affected platforms**
- iOS

**Versions**
- Kotlin version*:  8.2.2
- Compose Multiplatform version*: 1.6.2
- OS architecture (arm64): arm64
- Device (model or simulator for iOS issues): iphone 15 pro 17.0.2
- JDK (for desktop issues): 1.7

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
Should smoothly when run iosApp

**Comment by terrakok** [comment]
Could you provide a reproducer for the problem? (And describe versions more accurately)

**Comment by MatkovIvan** [comment]
https://github.com/JetBrains/compose-multiplatform/issues/4277#issuecomment-1945922199

**Comment by terrakok** [comment]
duplicates https://github.com/JetBrains/compose-multiplatform/issues/4277

**Comment by hafiz013** [comment]
@terrakok  the error that point out not same as me, how?

**Comment by terrakok** [comment]
The error is `Could not find "org.jetbrains.compose.annotation-internal:annotation"`. The fix is to find a dependency with unsupported version of the compose.
If you think it is a different case then provide a more detailed information and a reproducer, please 👍

**Comment by hafiz013** [comment]
actually what does mean error "org.jetbrains.compose.collection-internal:collection" vs "org.jetbrains.compose.annotation-internal:annotation"? @terrakok

**Comment by terrakok** [comment]
Actually, it doesn't matter. The issue is in a wrong transitive dependency between native targets. Because libraries with Kotlin Native targets maybe incompatible between dev versions.

**Comment by hafiz013** [comment]
because like my case build success but when running composeApp in Android (ok) but in Ios (not ok).

**Comment by terrakok** [comment]
Before that, could you share the output of `./gradlew :composeApp:dependencies > dep.txt`?

**Comment by hafiz013** [comment]
[Uploading dep.txt…](Text dep)

attachment above that you requested.

**Comment by terrakok** [comment]
Where is Compose Multiplatform 1.6.2? I see `org.jetbrains.compose.foundation:foundation:1.6.0-alpha01 -> 1.6.0-beta01`

**Comment by terrakok** [comment]
Try to create a new project with the same dependencies as you have to reproduce the issue and post the project here

**Comment by hafiz013** [comment]
@terrakok i did test with 1.6.2 during time i do reporting this issue but same problem. so i try redo back original 1.6.0-beta01 but still same problem.  Can I help you email please because my project so easy that can trigger error. It error when run iosApp when try to install.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4641">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
