### ISSUE TITLE
Exporting resources via xcframework or maven in multiplatform library

### ISSUE THREAD

**Issue by Prajwal-jm25** [JetBrains/compose-multiplatform#4643]
Compose Multiplatform has supported Images and resources sharing across different platforms. Since KMP is used by various people to develop a multiplatform library or feature which can be integrated to native platforms, it would be helpful if we are able to export the resources via the framework so that we can have a common UI with resources for multiplatform. 
I am not sure whether the above requirement is already supported by the KMP library, if it is guide me on how it works

**Comment by terrakok** [comment]
The build of XCFramework is not supported. Resources are only packed into a final iOS application.
There is no a common approach for the resource sharing in the Native world. Usually it is done by package managers such as Cocoapods or SPM.
Something can be done on the Kotlin gradle plugin side. You may file an issue on https://kotl.in/issue

**Comment by terrakok** [comment]
https://youtrack.jetbrains.com/issue/KT-66790

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4643">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
