### ISSUE TITLE
Consider support more targets for the KMP Lifecycle

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-multiplatform#4645]
As far as I can see, the KMP version of AndroidX Lifecycle with additional targets is now [published](https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/androidx/lifecycle/) to Maven Central. I would like to try using AndroidX Lifecycle in Decompose instead of the custom Lifecycle API. However, some targets required by Decompose are still not supported. Currently missing targets are: `watchos`, `tvos`, `macos` and `linuxX64`. Please consider publishing those targets as well. Thanks!

**Comment by MatkovIvan** [comment]
`macos` and `linuxX64` are there already - they use redirect to Google's binaries for available targets

Could you please specify what modules exactly you're interesting in? Asking because some modules from lifecycle group depend on Compose UI and could not be built for targets that not supported by Compose

**Comment by arkivanov** [comment]
> they use redirect to Google's binaries for available targets

Right, I missed that, thanks!

> Could you please specify what modules exactly you're interesting in

I would need `Lifecycle`, `LifecycleOwner` and `LifecycleRegistry`. I believe that corresponds to `lifecycle-common` and `lifecycle-runtime`?

**Comment by MatkovIvan** [comment]
@arkivanov It's available in `org.jetbrains.androidx.lifecycle:lifecycle-*:2.8.0-dev1590`

**Comment by arkivanov** [comment]
Thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4645">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
