### ISSUE TITLE
Execution failed for task ':androidApp:processDebugResources' with LinkApplicationAndroidResourcesTask

### ISSUE THREAD

**Issue by GuilhE** [JetBrains/compose-multiplatform#4646]
**Describe the bug**
Version `1.6.10-beta01` release notes state that: 
> Support multi-module projects and libraries publication with Compose resources (Kotlin 2.0.0-Beta05 or higher is required)

So I've tested in my sample app [WhosNext](https://github.com/GuilhE/WhosNext) trying to run **androidApp** module and it fails with:

```
Execution failed for task ':androidApp:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > AAPT2 aapt2-8.3.2-10880808-osx Daemon #0: Unexpected error during link, attempting to stop daemon.
     This should not happen under normal circumstances, please file an issue if it does.
```

Which makes me think it's not functional yet for `android` (for `wasm` is fixed 🥳 ).

**Affected platforms**
- Android

**Versions**
- Kotlin version*: `2.0.0-RC1`
- Compose Multiplatform version*: `1.6.10-beta01`

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. git clone git@github.com:GuilhE/WhosNext.git
2. Run androidApp

**Expected behavior**
Not failing

**Comment by terrakok** [comment]
It happens because you are suppose to apply the Android Library Plugin to your shared-ui module instead the Android Application. After this change it works

**Comment by terrakok** [comment]
(and of course you have to delete your packaging filters which delete all needed resources)
https://github.com/JetBrains/compose-multiplatform/assets/3532155/98250410-55b7-4196-8cb9-5ddd14c373a4

**Comment by GuilhE** [comment]
My bad, I forgot to make those changes in the shared-ui module for Android because I started with Wasm 😓 
Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4646">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
