### ISSUE TITLE
add a config in nativeDistributions task to specify the language in generated msi file

### ISSUE THREAD

**Issue by stars-one** [JetBrains/compose-multiplatform#4648]
I have a confusion

> I can get a msi file of chinese language when execute the task `packageMsi` in my pc(window system and its language is chinese,but if I do the same oprator in the github action,get a msi file of english language.

So is the `packageMsi` task auto read current system language?can we write a config to specify the language of msi later?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4648">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
