### ISSUE TITLE
[CfW] Text fields are broken in new beta

### ISSUE THREAD

**Issue by alexzhirkevich** [JetBrains/compose-multiplatform#4649]
**Describe the bug**
After https://github.com/JetBrains/compose-multiplatform-core/pull/1259 text fields are broken on desktop browsers
- [ ] `singleLine` text fields don't react on input
- [ ] Cursor always jumps to the end of line when trying to type something in the middle
- [ ] Selection doesn't work on the right side from cursor (enter some text, move cursor to the beginning, try select something - doesn't work because of invisible textarea that is placed after cursor).

All issues are gone if i remove the invisible textarea from the dom tree.

**Affected platforms**
Web JS. Tested in Chrome and Edge on Windows. Didn't check wasm

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-beta01

**Comment by Nek-12** [comment]
Same story on wasm

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4649">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
