### ISSUE TITLE
viewModelScope.launch Error

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#4653]
**Describe the bug**
when i run viewModelScope.launch in viewmodel, i get the following error:
`Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'`

**Affected platforms**
- Desktop (Windows, Linux, macOS)
- iOS
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library

**Versions**
- Kotlin version*: 2.0.0-rc1
- Compose Multiplatform version*: 1.6.10-beta1
- OS version(s)* (required for Desktop and iOS issues): mac os
- OS architecture (x86 or arm64):
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 17

**Comment by MatkovIvan** [comment]
As mentioned in the error message you need to include `Dispatchers.Main` implementation to your project. Based on the error it fails on desktop, so you need `kotlinx-coroutines-swing` dependency. See [doc](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-main.html)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4653">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
