### ISSUE TITLE
[Wasm] [1.6.10] MissingResourceException: Missing resource with path: ./values/strings.commonMain.cvr

### ISSUE THREAD

**Issue by Nek-12** [JetBrains/compose-multiplatform#4654]
Just upgraded https://opensource.respawn.pro/FlowMVI/sample/ to 1.6.10. Resources no longer load. 

- Web (K/Wasm) - Canvas based API

Importantly, we still have to use 1.9.23 because of other dependencies. I saw some notices about public resources working in 2.0.0 only, but if that's true and resources won't work at all unles 2.0-rc is used, how can I get resources working with k 1.9.23 and compose 1.6.10?

**Versions**
- Kotlin version: 1.9.23 
- Compose Multiplatform version: 1.6.10-beta01

MissingResourceException: Missing resource with path: ./values/strings.commonMain.cvr

```
// shared module
compose.resources {
    packageOfResClass = Config.Sample.namespace
    publicResClass = false
}


// app module

val copyWasmResources = tasks.create("copyWasmResourcesWorkaround", Copy::class.java) {
    from(project(":sample").file("src/commonMain/composeResources"))
    into("build/processedResources/wasmJs/main")
}

afterEvaluate {
    tasks {
        getByName("wasmJsProcessResources").finalizedBy(copyWasmResources)
        getByName("wasmJsDevelopmentExecutableCompileSync").dependsOn(copyWasmResources)
        getByName("wasmJsProductionExecutableCompileSync").dependsOn(copyWasmResources)
        getByName("wasmJsJar").dependsOn(copyWasmResources)
    }
}
```

Maybe I need to fix the hack I'm using another time now?

**Comment by terrakok** [comment]
Could you share the project with me? And what exactly version of the compose do you use? (add it to the description)

**Comment by Nek-12** [comment]
Here: https://github.com/respawn-app/FlowMVI/tree/master/sample

**Comment by terrakok** [comment]
I see you have a multimodule project but the resources in such case works **only** with Kotlin Gradle Plugin >= 2.0.0-Beta5

**Comment by terrakok** [comment]
I understood that you worked around it with hacks. But it doesn't work anymore.
The final resources (cvr files) are generated as part of the build. You can try to do the trick again but with the build directory. Take a look into `build/generated/compose` directory.

**Comment by Nek-12** [comment]
Okay, I will try to copy the resources from that dir as well. Other users may hopefully use that as a workaround for now

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4654">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
