### ISSUE TITLE
Could not find androidx.compose.ui:ui-tooling-preview:1.6.10-beta01

### ISSUE THREAD

**Issue by dragitpro** [JetBrains/compose-multiplatform#4655]
**Describe the bug**

Just migrating the project from 1.6.2 to 1.6.10-beta01 triggered errors who makes compilation impossible

**Affected platforms**
- Android,
- compilation on desktop is ok 

**Versions**
- Kotlin version*: 2.0.0-RC1  
- Compose Multiplatform version*: 1.6.10-beta01 

```
> Could not resolve all files for configuration ':composeApp:debugRuntimeClasspath'.
   > Could not find androidx.compose.ui:ui-tooling-preview:1.6.10-beta01.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/androidx/compose/ui/ui-tooling-preview/1.6.10-beta01/ui-tooling-preview-1.6.10-beta01.pom
       - https://repo.maven.apache.org/maven2/androidx/compose/ui/ui-tooling-preview/1.6.10-beta01/ui-tooling-preview-1.6.10-beta01.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/androidx/compose/ui/ui-tooling-preview/1.6.10-beta01/ui-tooling-preview-1.6.10-beta01.pom
     Required by:
         project :composeApp
```

**Additional context**

        commonMain.dependencies {
            implementation(compose.components.uiToolingPreview)
}

**Comment by igordmn** [comment]
> implementation(compose.components.uiToolingPreview)

`compose.components.uiToolingPreview` doesn't contain links to `androidx.compose.ui:ui-tooling-preview` - I checked that, and it works for Android/Desktop.

Maybe you have another dependency on `androidx.compose.ui:ui-tooling-preview` somewhere? It is a part of Jetpack Compose, which has its own versioning, and doesn't have `1.6.10-beta01`. For Jetpack Compose you should use a different version (the latest version is 1.6.6).

It is a guess, but you might use a template https://kmp.jetbrains.com/, which generates this:
```
[versions]
...
compose = "1.6.5"
compose-plugin = "1.6.2"
...
```
`compose` here is Jetpack Compose
`compose-plugin` is Compose Multiplatform

We will fix this confusion [here](https://youtrack.jetbrains.com/issue/KT-66613/Kotlin-Multiplatform-Wizard.-Misusage-of-compose-name-in-libs.versions.toml)

**Comment by dragitpro** [comment]
Thanks for your answer, and sorry for wasting your time. In my build.gradle.kts, under the Android block, I had:

```
dependencies {
    debugImplementation(libs.compose.ui.tooling) 
```

and in my catalog, compose-tooling is defined as:
`compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
`
So yeah problem was that . Thanks again

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4655">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
