### ISSUE TITLE
MissingResourceException using readResourceBytes

### ISSUE THREAD

**Issue by dragitpro** [JetBrains/compose-multiplatform#4656]
**Describe the bug**

Just migrating the project from 1.6.2 to 1.6.10-beta01 triggered errors 
Seems like files are not included anymore or am I missing something ?

**Affected platforms**
- Desktop (cant test other plateforms for now) 

**Versions**
- Kotlin version*: 2.0.0-RC1  
- Compose Multiplatform version*: 1.6.10-beta01 

```
Exception in thread "AWT-EventQueue-0" org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: files/loader_player.json
	at org.jetbrains.compose.resources.ResourceReader_desktopKt$getPlatformResourceReader$1.getResourceAsStream(ResourceReader.desktop.kt:31)
	at org.jetbrains.compose.resources.ResourceReader_desktopKt$getPlatformResourceReader$1.read(ResourceReader.desktop.kt:7)
	at org.jetbrains.compose.resources.ResourceReaderKt.readResourceBytes(ResourceReader.kt:15)
```

**Additional context**
```
val uri= "files/loader_player.json"
val json = readResourceBytes(uri).decodeToString()
```

also tied with new api but doesnt seems made for that since path seems not correct : 
```
        val uri = Res.getUri("files/loader_player.json")
```
or with okio FileNotFoundException 
```
  val uri= "files/loader_player.json"
  val json = platformFileSystem().read(uri.toPath()) {
      readUtf8()
  }
```

**Comment by terrakok** [comment]
Did you try any dev versions before the update? There may be broken caches. Try to delete all builds dirs in the project and build it again

**Comment by dragitpro** [comment]
Thanks for your answer. I hadn't tried the dev version before the update. I deleted the build folders in both the root project and the composeApp folder, invalidated the caches (with all three options checked), and I'm still facing the problem

**Comment by terrakok** [comment]
I need a reproducer of the issue. Could you share your project?

**Comment by dragitpro** [comment]
Unfortunately, I can't share the project. However, I just tried to reproduce the issue on a minimal project and it works fine there. If you have any ideas about what could be causing this error, such as another cache folder to delete, please let me know. Otherwise, I will continue to investigate on my side

**Comment by terrakok** [comment]
Maybe you can show your build log which is a reason of the app crash?

**Comment by terrakok** [comment]
The code snippet uses java resources instead of compose multiplatform resources.

**Comment by terrakok** [comment]
It won't work with a composeResources directory

**Comment by dragitpro** [comment]
Thanks ...  Solution then : if someone find this issueto not waste a day like me         val json = Res.readBytes(uri).decodeToString()

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4656">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
