### ISSUE TITLE
VerticalScrollbar can not used with LazyVerticalStaggeredGrid

### ISSUE THREAD

**Issue by stars-one** [JetBrains/compose-multiplatform#4658]
I want to show a scrollbar with a LazyVerticalStaggeredGrid,but there is not support.

My compose-desktop version is 1.5.11.If version 1.6.x or later version support this ?

```kotlin
val state = rememberLazyStaggeredGridState()
Box{
	LazyVerticalStaggeredGrid(columns = StaggeredGridCells.Fixed(4), state = state) {
		
	}
	
	VerticalScrollbar(
		modifier = Modifier.align(Alignment.CenterEnd).fillMaxHeight(),
		//rememberScrollbarAdapter method is not support LazyStaggeredGridState
		adapter = rememberScrollbarAdapter(state)
	)
}
```

**Comment by Syer10** [comment]
I also encountered this issue, there doesn't seem to be a way to use a Scrollbar with a LazyStaggeredGrid, which I feel like is a bug or a missing implementation since all scrollable content needs scrollbars in desktop apps.

**Comment by starry-shivam** [comment]
+1 Same issue here (desktop)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4658">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
