### ISSUE TITLE
[desktop] ScrollBar freezes the app if listState.animateScrollBy or animateScrollToItem are used

### ISSUE THREAD

**Issue by avently** [JetBrains/compose-multiplatform#4661]
**Describe the bug**

When dragging scrollbar and something calls `listState.animateScrollBy(10f)`, the app freezes and there is no way to use it without restart. With `listState.scrollBy` it works fine, so it's somehow related to animation.

**Affected platforms**
- Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*:  1.9.23
- Compose Multiplatform version*: 1.6.2
- OS architecture (x86 or arm64): x86

**To Reproduce**
- `git clone https://github.com/JetBrains/compose-multiplatform`
- add this code to https://github.com/JetBrains/compose-multiplatform/blob/master/examples/todoapp-lite/shared/src/commonMain/kotlin/example/todoapp/lite/common/MainContent.kt#L86:
```kotlin
LaunchedEffect(items.size) {
    listState.animateScrollBy(10f)
}
```
- cd examples/todoapp-lite
- `./gradlew run`
- put mouse focus to text view and press `Enter` many times until you see scroll bar at the right side of screen. After you see it already, try to drag it and press `Enter` again without stopping dragging the scrollbar up and down. You'll notice the whole app is freezed.

This behaviour is somehow related to animation because if you call `listState.scrollBy(10f)` eveyrthing is fine. 
`animateScrollToItem` is also affected while `scrollToItem` is not.

**Expected behavior**
Shouldn't freeze the app

**Comment by alexzhirkevich** [comment]
It is the same bug as #3807 and should be already fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/575. Try `1.6.10-beta01`

**Comment by avently** [comment]
I found that issue before but not resulting PR. It works, thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4661">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
