### ISSUE TITLE
Desktop Fullscreen with undecorated not showing up.

### ISSUE THREAD

**Issue by MichaelALacefield** [JetBrains/compose-multiplatform#4662]
**Describe the bug**
With the application in full screen you can swipe from the edges and it will minimize the app.

**Affected platforms**
Windows

**Versions**
- Kotlin version*: 
kotlin = "1.9.23"
- Compose Multiplatform version*: 
1.6.2
- OS version(s)* (required for Desktop and iOS issues): 
-Windows 10 and 11
- OS architecture (x86 or arm64):
- x86
- Device (model or simulator for iOS issues): 
PC
- JDK (for desktop issues): 
21

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
    val state = rememberWindowState(
        size = DpSize.Unspecified,
        placement = WindowPlacement.Fullscreen
    )

    Window(onCloseRequest = ::exitApplication, state, undecorated = true) {
        mainScreen(MainViewModel())
    }

**Expected behavior**
Screen should pop up 

**Screenshots**

**Additional context**
It will also cause my pc's ui to start freaking out and being unresponive if I get rid of undecorated then it works but shows the top bar, and if i go undecorated with maximized I can swipe on the edges and minimize the application

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4662">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
