### ISSUE TITLE
Empty strings.xml throws unfriendly SAXParseException on import

### ISSUE THREAD

**Issue by zsmb13** [JetBrains/compose-multiplatform#4663]
**Describe the bug**
Import fails with

```
<-------------> 0% EXECUTING [198ms]
> :commonizeNativeDistribution
[Fatal Error] :-1:-1: Premature end of file.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':composeApp:convertXmlValueResourcesForCommonMain'.
> org.xml.sax.SAXParseException; Premature end of file.
```

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-beta01

**To Reproduce**
Create an empty `composeResources/values/strings.xml` file and try to import the project in Fleet.

**Expected behavior**
A clear error message that explains what went wrong, and points the user to the documentation to help with the correct contents of this file.

**Screenshots**

<img width="1339" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/12054216/1e611ec2-b25f-4983-9ed8-e8ba3d35f601">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4663">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
