### ISSUE TITLE
Escape char not supported on strings.xml

### ISSUE THREAD

**Issue by StanKocken** [JetBrains/compose-multiplatform#4664]
**Describe the bug**
The file strings.xml cannot contains escape char (`\`) while being mandatory on Android resource files.

**Affected platforms**
- Android
- Not tested on others

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-beta01

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Within the strings resource files `strings.xml`, located within `composeMain/composeResources/values`, escape a quote with a backslack
2. Display this string within your app
3. Notice that the backslash is displayed

As noted within https://developer.android.com/guide/topics/resources/string-resource#FormattingAndStyling, the spec of the `strings.xml` file, we can read "Beware that you must escape apostrophes and quotation marks".

**Expected behavior**
The escape chars should be working the same way for a `strings.xml` file, whether it's used on Android or Kotlin Multiplatform Compose context.

**Screenshots**

Example of `strings.xml`:

`<string name="my_string">Premium, it\'s for everybody!</string>`

That will lead to:
![Screenshot 2024-04-20 at 16 08 23](https://github.com/JetBrains/compose-multiplatform/assets/2204411/92d5e4e7-65b6-4c4a-98de-be46bd6aac6e)

**Comment by MatkovIvan** [comment]
https://github.com/JetBrains/compose-multiplatform/issues/4178#issuecomment-1931504804

**Comment by StanKocken** [comment]
Sorry I missed this other closed ticket. Does it mean I should close this ticket as "won't do" and modify the XML accordingly?

**Comment by terrakok** [comment]
Yes, it is 👍

**Comment by terrakok** [comment]
duplicates https://github.com/JetBrains/compose-multiplatform/issues/4178

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4664">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
