### ISSUE TITLE
Add bottomsheet to the NavHost

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#4665]
Hi
Please add `bottomsheet` like `composable` and `dialog` to the `NavHost`.

**Comment by MatkovIvan** [comment]
This was introduced as separate `androidx.compose.material:material-navigation` artifact only in `1.7.0-alpha04`. We'll look at it as part of Compose 1.7 adoptation.

If you need API that doesn't exist on Android - please file an issue to Google tracker first

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4665">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by FunkyMuse** [comment]
> This was introduced as separate `androidx.compose.material:material-navigation` artifact only in `1.7.0-alpha04`. We'll look at it as part of Compose 1.7 adoptation.
> 
> If you need API that doesn't exist on Android - please file an issue to Google tracker first

Is there any update on this, now it's in beta, we want to migrate from PreCompose but we have a lot of destinations that are using Bottom Sheets and it's a blocker for us.
