### ISSUE TITLE
[IOS] crash when launch

### ISSUE THREAD

**Issue by hellomr3** [JetBrains/compose-multiplatform#4668]
**Describe the bug**
<img width="708" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/29541241/1d53763f-7089-49c8-899f-b9a68f7905b1">
just real devices
**Affected platforms**

- iOS

**Versions**
- Kotlin version*: "2.0.0-RC1"
- Compose Multiplatform version*: "1.6.10-dev1593"
- OS version(s)* (required for Desktop and iOS issues): 14.4
- OS architecture (x86 or arm64):arm64
- Device (model or simulator for iOS issues): iphone 8
- JDK (for desktop issues): 

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by alexzhirkevich** [comment]
@ASalavei Have you tested the fix? As i understand it should be available in dev1593 :(

**Comment by terrakok** [comment]
duplicates https://github.com/JetBrains/compose-multiplatform/issues/4644

**Comment by hellomr3** [comment]
> duplicates #4644
same 1.6.10-dev1593 crash

**Comment by elijah-semyonov** [comment]
Can't reproduce.

@MatkovIvan 
Do youu know if 1.6.10-dev1593 includes @ASalavei fix?


<img width="185" alt="Screenshot 2024-04-23 at 18 06 49" src="https://github.com/JetBrains/compose-multiplatform/assets/4167681/db9d732c-76ea-4e9f-88dd-8e8c1cf53d22">

<img width="515" alt="Screenshot 2024-04-23 at 18 07 03" src="https://github.com/JetBrains/compose-multiplatform/assets/4167681/259c683e-624e-4a5d-9cdc-81093dfe3c5d">

**Comment by MatkovIvan** [comment]
Yes it does.

@hellomr3 please make sure you are using the correct version - gradle might resolve it to older one because of dependencies

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4668">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
