### ISSUE TITLE
LazyRow in desktopMain is not scrollable

### ISSUE THREAD

**Issue by kienzle13** [JetBrains/compose-multiplatform#4674]
LazyRow in commonMain does not scroll on desktop. Works on Android 
For reference LazyColumn works correctly on both platforms

**Affected platforms**
- Desktop
- 
**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-beta01
- OS version(s)* : Windows 11 23H2 build 22631.3447
- OS architecture: x86
- Device (model or simulator for iOS issues): n/a
- JDK (for desktop issues): openjdk version "17.0.9" 2023-10-17 build -11185874

**To Reproduce**
Create a LazyRow:
        LazyRow(userScrollEnabled = true)  {
            itemsIndexed(msc) { index, _ ->
.....
}
**Expected behavior**
Row is scrollable in desktop with mouse wheel

Works in Android but not desktop

**Comment by MatkovIvan** [comment]
It's already discussed in #2528 and #2690

It's not about desktop vs android but about touch vs mouse.
Long story short: A mouse might have multiple wheels or it might be a 2-directional touchpad, so scrolling delta is a vector, but just a number. A regular mouse wheel produces only y-axis delta. To scroll horizontally, hold the shift button - it will invert delta to x-axis.
This is a common practice even outside Compose, but we're [thinking](https://github.com/JetBrains/compose-multiplatform-core/pull/1300) how to improve it

Closing as duplicate

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4674">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
