### ISSUE TITLE
Plural quantity placeholder not working correctly

### ISSUE THREAD

**Issue by FunkyMuse** [JetBrains/compose-multiplatform#4675]
**Describe the bug**
Plural quantity placeholder is not respected

**Affected platforms**

- Desktop (Windows, Linux, macOS)
- iOS
- Web (K/Wasm) - Canvas based API
- Android

**Versions**
- Kotlin version*: 2.0.0-RC1
- Compose Multiplatform version*:  1.6.10-dev1593
- OS version(s)* (required for Desktop and iOS issues):  MacOS 14.4.1 (23E224)
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues):  Galaxy S22 Ultra Android 14, iOS 17.2 simulator
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. 
```kotlin 

<plurals name="downloading_files">
        <item quantity="zero">Downloading</item>
        <item quantity="one">Downloading 1 file</item>
        <item quantity="other">Downloading %1$d files</item>
</plurals> 
```
2.
```kotlin
val newValue = 10
val textToShow = getPluralString(
                            resource = Res.plurals.downloading_files,
                            quantity = newValue
                        )

// or when used in Compose manner

val text = pluralStringResource(Res.plurals.downloading_files, 10)
```
It just displays the placeholder `Downloading %1$d files`

**Expected behavior**
The text should show `Downloading 10 files`

**Screenshots**
![Screenshot_20240422_195045_Berg](https://github.com/JetBrains/compose-multiplatform/assets/25645122/2b01bc73-e1dc-46a3-8b51-ca82c63f3a40)

**Comment by terrakok** [comment]
There is third parameter for arguments: 
```kotlin
fun pluralStringResource(resource: PluralStringResource, quantity: Int, vararg formatArgs: Any): String {...}
```
You are supposed to use
`val text = pluralStringResource(Res.plurals.downloading_files, 10, 10)`

**Comment by b0r1ngx** [comment]
Hello, interesting why the first one is needed, when we provide just resource and quantity?

**Comment by paxbun** [comment]
@b0r1ngx The design is an imitation of Android's plural string resource. We can't decide which argument should be used as the quantity when there are multiple format arguments.

@terrakok, the plural string example in [the new documentation](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html#resource-usage) provides a code without format arguments.

```kotlin
Text(pluralStringResource(Res.string.new_message, 1))
```

I think the third formatArgs argument should be noted to make fewer people confused.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4675">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
