### ISSUE TITLE
Compilation aborts when trying to compile a project with Navigation Compose and AnchoredDraggableState

### ISSUE THREAD

**Issue by sodove** [JetBrains/compose-multiplatform#4677]
**Describe the bug**
Compilation aborts when trying to compile a project with Navigation Compose and AnchoredDraggableState, when navigation is not added to the project - the project is built normally.

```
None of the following functions can be called with the arguments supplied: 

public constructor AnchoredDraggableState<T>(initialValue: TypeVariable(T), positionalThreshold: (totalDistance: Float) -> Float, velocityThreshold: () -> Float, snapAnimationSpec: AnimationSpec<Float>, decayAnimationSpec: DecayAnimationSpec<Float>, confirmValueChange: (newValue: TypeVariable(T)) -> Boolean = ...) defined in androidx.compose.foundation.gestures.AnchoredDraggableState

public constructor AnchoredDraggableState<T>(initialValue: TypeVariable(T), anchors: DraggableAnchors<TypeVariable(T)>, positionalThreshold: (totalDistance: Float) -> Float, velocityThreshold: () -> Float, snapAnimationSpec: AnimationSpec<Float>, decayAnimationSpec: DecayAnimationSpec<Float>, confirmValueChange: (newValue: TypeVariable(T)) -> Boolean = ...) defined in androidx.compose.foundation.gestures.AnchoredDraggableState
```

**Affected platforms**
- Android

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: [1.6.10-beta01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10-beta01)

**To Reproduce**
Reproduction sample: https://github.com/sodove/anchored_repro
1. Add next code to project 
```
enum class DrawerState {
    Opened,
    Closed,
}

...
val state = remember {
                AnchoredDraggableState(
                    initialValue = DrawerState.Closed,
                    anchors = DraggableAnchors {
                        DrawerState.Opened at -startAnchor
                        DrawerState.Closed at 0f
                    },
                    positionalThreshold = { distance: Float -> distance * 0.5f },
                    velocityThreshold = { with(density) { 100.dp.toPx() } },
                    animationSpec = tween(),
                )
            }
...
```
2. Add the following dependency to your commonMain source set
implementation("org.jetbrains.androidx.navigation:navigation-compose:2.8.0-alpha01")
3. Try to compile project

**Expected behavior**
The project has to build and run

**Comment by Lonchi78** [comment]
Got the same issue, and not using Compose Multiplatform

**Comment by MatkovIvan** [comment]
@Lonchi78 The issue is about mixing 1.6 and 1.7 while using experimental API that were changed between these versions

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4677">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
