### ISSUE TITLE
Navigation with nested NavGraph produces error

### ISSUE THREAD

**Issue by Goregius** [JetBrains/compose-multiplatform#4678]
**Describe the bug**
When using Compose multiplatform navigation, it seems that navigation with a nested NavGraph doesn't work and throws an error when trying to navigate to one.

**Affected platforms**
- Desktop (Windows)
- Web (K/Wasm) - Canvas based API

(I only tested these two)

**Versions**
- Kotlin version*: 2.0.0-RC1
- Compose Multiplatform version*: 1.6.10-dev1593
- Compose Navigation version: 2.8.0-alpha01
- OS version(s)* (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Use a `navigation` function to create a nested `NavGraph` and include a route which navigates to a sibling route. For example:

    ```kotlin
    NavHost(navController, startDestination = "subgraph") {
        navigation(startDestination = "a", route = "subgraph") {
            composable("a") {
                Button(onClick = { navController.navigate("b") }) {
                    Text("Navigate to route b")
                }
            }
            composable("b") {
                Text("Route b")
            }
        }
    }
    ```

2. Launch app and try to navigate to the sibling route.
3. A similar error to the following will occur:

> Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Navigation destination that matches route b cannot be found in the navigation graph ComposeNavGraph startDestination={ComposeNavGraph route=subgraph startDestination={Destination route=a}}

**Expected behavior**
The navigation should act as it would in Android, no error should occur.

**Comment by MatkovIvan** [comment]
Already fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/1277

Available in the latest dev build

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4678">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
