### ISSUE TITLE
[iOS][Desktop] BottomNavigation crash when switch tab

### ISSUE THREAD

**Issue by Darkrai9x** [JetBrains/compose-multiplatform#4684]
**Describe the bug**
When I implement BottomNavigation following the guidelines on [Google](https://developer.android.com/develop/ui/compose/navigation), it crashes when switching between tabs on iOS and desktop, while it works fine on Android.

**Affected platforms**
- Desktop (Windows, Linux, macOS)
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-dev1596
- Navigation version*: 2.8.0-dev1596
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): x86
- Device (model or simulator for iOS issues): simulator iPhone 15 17.4
- JDK (for desktop issues): 17

**To Reproduce**
```Kotlin
val rootRoutes = remember {
    listOf(
        CupcakeScreen.Start.name,
        CupcakeScreen.Flavor.name,
        CupcakeScreen.Pickup.name,
        CupcakeScreen.Summary.name,
    )
}

Row(modifier = Modifier.fillMaxWidth()) {
    rootRoutes.forEachIndexed { i, route ->
        Button(
            onClick = {
                navController.navigate(
                    route,
                    navOptions {
                        navController.graph.findStartDestination().route?.let {
                            popUpTo(it) { saveState = true }
                        }
                        launchSingleTop = true
                        restoreState = true
                    }
                )
            }
        ) {
            Text("Tab $i")
        }
    }
}

```
When switching between tabs 1, 2, 3, 4, it crashes when switching from tabs 2, 3, 4 back to tab 1.
**Expected behavior**
It works like on Android.

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/21193738/b8c5b23a-cd39-4319-b3f7-d56c8ca0d55b)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4684">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
