### ISSUE TITLE
Compose Navigation Dependency import failed

### ISSUE THREAD

**Issue by breakingbeats** [JetBrains/compose-multiplatform#4686]
**Bug description**
When I want to include Navigation Compose for Compose Multiplatform, a build error is generated that looks like this:
Module "org.jetbrains.compose.foundation:foundation" has a reference to symbol org.jetbrains.skiko/SkikoKey.platformKeyCode.<get-platformKeyCode>|<get-platformKeyCode>(){}[0]. Neither the module itself nor its dependencies contain such declaration.

This could happen if the required dependency is missing in the project. Or if there is a dependency of "org.jetbrains.compose.foundation:foundation" that has a different version in the project than the version that "org.jetbrains.compose.foundation:foundation" was initially compiled with. Please check that the project configuration is correct and has consistent versions of all required dependencies.

**Affected platforms**

- Compose Multiplatform with sourcesets:
-- Android
-- iOS
-- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.2
- OS architecture: arm64 M2 Pro

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
commonMain.dependencies {
            implementation(projects.shared)
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.materialIconsExtended)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)

//comment in compose navigation reproduces the build error
            //implementation(libs.compose.navigation)
}

**Comment by MatkovIvan** [comment]
There is no mention of navigation library version in the description, but in the current state it's clear that

> Compose Multiplatform version*: 1.6.2

is a cause of version conflict, please use the version of Compose from the same release

In the case of [the latest beta](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10-beta01) it's:
Gradle Plugin `org.jetbrains.compose`, version `1.6.10-beta01`
Navigation libraries `org.jetbrains.androidx.navigation:navigation-*:2.8.0-alpha01`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4686">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
