### ISSUE TITLE
Black box testing of UI written on Compose with native widgets

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4687]
There is no obvious way to test a mixed UI as a black box.

There are 2 possible ways:

- Via accessibility API

- Via Compose Testing API, exposing `ComposePanel.semanticNode` (for desktop) and provide an usual Compose testing API for Compose part (`panel.onNodeWithTag("button").click()`)

https://youtrack.jetbrains.com/issue/COMPOSE-1371/Black-box-testing-of-UI-written-on-Compose-with-native-widgets

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4687">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
