### ISSUE TITLE
HorizontalPager doesn't snap to new page when tab-navigation focuses an element on a different page

### ISSUE THREAD

**Issue by zacharee** [JetBrains/compose-multiplatform#4689]
**Describe the bug**
It doesn't look like the pager state knows about keyboard navigation, or what to do when an element on a different page becomes focused. Instead of snapping, it acts as if no scroll happened.

**Affected platforms**

- Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-dev1599
- OS version(s)* (required for Desktop and iOS issues): macOS 14.5
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): OpenJDK 18.0.2.

**To Reproduce**
1. Create a HorizontalPager with multiple pages that have focusable elements.
2. Use the tab key to start navigating through them.
3. When an element on another page is focused, the pager will scroll to bring it into focus, but won't snap the whole page into place.

**Expected behavior**
The pager state should snap the page with the focused element into place.

**Screenshots**
https://github.com/JetBrains/compose-multiplatform/assets/9020352/f546b755-99ec-498c-b0d0-5788942b5531

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4689">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
