### ISSUE TITLE
Scrolling HorizontalPager on desktop doesn't respect `pagerSnapDistance`

### ISSUE THREAD

**Issue by zacharee** [JetBrains/compose-multiplatform#4690]
**Describe the bug**
When using the mouse/trackpad to scroll a HorizontalPager, the snapping behavior doesn't respect the `pagerSnapDistance` property in the `SnapFlingBehavior`.

**Affected platforms**

- Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-dev1599
- OS version(s)* (required for Desktop and iOS issues): macOS 14.5
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): OpenJDK 18.0.2

**To Reproduce**
1. Create a HorizontalPager with at least 3 pages.
2. Scroll quickly with the mouse/trackpad.
3. Instead of only scrolling by one page (the default for HorizontalPager), if the fling was fast enough, it will scroll by two pages.

**Expected behavior**
The snapping behavior should respect the max distance.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/9020352/78dc97ae-2c10-4722-b542-33731dc8621f

**Additional context**
This might be intentional behavior to better mimic how scrolling usually works with a mouse. If it's that, though, then `snapPositionalThreshold` should be respected at least. Even if just one pixel of the "next" page is in view, the pager will snap to that, even if the threshold is 50%.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4690">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
