### ISSUE TITLE
Pagination for multiplatform composeApp

### ISSUE THREAD

**Issue by hafiz013** [JetBrains/compose-multiplatform#4691]
Is there suitable library can use for pagination composeApp multiplatform that can support ios and android? One of sample that i get is cashApp however, when i see this library the author will not maintain it. If possible compose-multiplatform has their own function/code  without need to adjust code for iosApp or androidApp. Many thanks.

**Comment by Shusek** [comment]
Do you try pagination from the official library?
https://developer.android.com/jetpack/androidx/releases/paging

**Comment by hafiz013** [comment]
This library only for android not compose multiplatform. I already try.

**Comment by AlexanderEggers** [comment]
@hafiz013 I noticed that thd androidx paging lib is finally supporting multiplatform: https://developer.android.com/jetpack/androidx/releases/paging#3.3.0-alpha02

**Comment by luludevmuniz** [comment]
> @hafiz013 I noticed that the androidx paging lib is finally supporting multiplatform: https://developer.android.com/jetpack/androidx/releases/paging#3.3.0-alpha02

Still no support for wasm, though

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4691">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
