### ISSUE TITLE
Ellipse nodes in SVGs are not rendered if they only have rx or ry

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#4692]
**Describe the bug**
If you have an `<ellipse>` node in an SVG that only has the `rx` (or `ry`) node, then the ellipse doesn't get rendered. However, this is not how SVGs generally get rendered; both the IntelliJ built-in SVG renderer, and Google Chrome, are happy to render the ellipse with just `rx` or `ry`. Compose for Desktop only renders it when _both_ `rx` and `ry` are defined.

This works:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
    <rect x="1.5" y="5" width="13" height="6" fill="none" rx="2" stroke="#6C707E"/>
    <rect x="3" y="6.75" width="2.5" height="2.5" rx="1" fill="#6C707E"/>
    <rect x="6.5" y="6.75" width="2.5" height="2.5" rx="1" fill="#6C707E"/>
</svg>
```

This doesn't work:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
    <rect x="1.5" y="5" width="13" height="6" fill="none" rx="2" stroke="#6C707E"/>
    <ellipse cx="4.25" cy="8" rx="1.25" fill="#6C707E"/>
    <ellipse cx="7.75" cy="8" rx="1.25" fill="#6C707E"/>
</svg>
```

![image](https://github.com/JetBrains/compose-multiplatform/assets/153802/0dd899c2-67bb-458a-88fb-0ba46b21c648)

**Affected platforms**
- Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.0-beta01
- OS version(s)* (required for Desktop and iOS issues): macOS 14.4.1
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): JBR17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Take the "doesn't work" SVG above
2. Render it in CfD:
    ```kotlin
    Image(painterResource("sample-icons/broken.svg"), null)
    ```
3. Observe the ellipses don't get drawn
4. Add the `ry` attribute to the ellipses
5. Observe now they do get drawn

**Expected behavior**
Ellipse elements should be drawn even when only one of the two radii is set (the other is assumed to be identical). The 'broken' example from above renders correctly in Chrome:
<img width="789" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/153802/8ead9672-7aac-43ee-bc40-29fe0c2a385a">

**Comment by rock3r** [comment]
Filed Skia bug: https://issues.skia.org/issues/336711946

**Comment by rock3r** [comment]
Fixed on the Skia side, waiting for that to make its way into Skiko :)

**Comment by terrakok** [comment]
@igordmn who updates the skiko?

**Comment by igordmn** [comment]
We have updated Skia 2 times per year in the past, as it requires a lot of effort.

The last update was planned around 01.2024, but postponed because of lot of breaking changes.

The next update will be planned probably on 1.7.

No special person for this, we assigne who is more familiar and free, and decide that during planning.

**Comment by rock3r** [comment]
This is not super urgent, as the workaround is simply to add the other radius, but I imagine it would be more relevant for displaying images coming from the internet or from the user.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4692">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
