### ISSUE TITLE
[cfw] "No ViewModelStoreOwner was provided via LocalViewModelStoreOwner"

### ISSUE THREAD

**Issue by jershell** [JetBrains/compose-multiplatform#4694]
Unable to use the lifecycle-viewmodel-compose with web target

**Describe the bug**
"No ViewModelStoreOwner was provided via LocalViewModelStoreOwner"

**Affected platforms**
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-beta01, 1.6.10-dev1599
- Lifecycle-viewmodel-compose*: 2.8.0-alpha01
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 22.04.3
- OS architecture (x86 or arm64): x86_64
- Device (model or simulator for iOS issues): Chrome 123.0.63
- JDK (for desktop issues): Temurin 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Go to [web](https://jershell.github.io/web-kmp-mvvm/)
2. Open console
3. See error

**Expected behavior**
Label with current time on screen

**Source code**
- https://github.com/jershell/web-kmp-mvvm/blob/main/composeApp/src/commonMain/kotlin/com/github/jershell/containers/foobar/FooBar.kt#L24
- https://github.com/jershell/web-kmp-mvvm/

**Comment by kropp** [comment]
Hi @jershell 
please update to the just released `1.6.0-beta02` and change the line
`viewModelFactory { FooBarViewModel() }` to `viewModelFactory { initializer { FooBarViewModel() } }`
That should fix the issue.

**Comment by jershell** [comment]
> Hi @jershell please update to the just released `1.6.0-beta02` and change the line `viewModelFactory { FooBarViewModel() }` to `viewModelFactory { initializer { FooBarViewModel() } }` That should fix the issue.

Hi. I up version. Viewmodel is working. Thanks you!

**Comment by pablichjenkov** [comment]
Wow 😲 I never used it TBH. Thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4694">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
