### ISSUE TITLE
Support material3 1.3.0-alphaXX and material 1.7.0-alphaXX

### ISSUE THREAD

**Issue by mahramane** [JetBrains/compose-multiplatform#4696]
Hi
in `material 1.7.0-...` `RippleTheme` is deprecated and  `RippleConfiguration` has replaced it.
`androidx.compose.material3.LocalRippleConfiguration` and `androidx.compose.material3.RippleConfiguration` not found in `compose multiplatform 1.6.10-beta01`.
please add `material3-1.3.0-alpha05` and `material-1.7.0-alpha07` to `compose multiplatform`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4696">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
