### ISSUE TITLE
Moving the app to another monitor breaks dropdowns

### ISSUE THREAD

**Issue by Syer10** [JetBrains/compose-multiplatform#4697]
**Describe the bug**
After moving the app to another monitor, dropdown menu positioning allows overflow outside the window

**Affected platforms**
- Desktop (macOS)

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.2
- OS version(s)* (required for Desktop and iOS issues): MacOS 14
- OS architecture (x86 or arm64): Arm64
- Device (model or simulator for iOS issues): Mac Pro M1
- JDK (for desktop issues): Temurin 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Download https://github.com/Syer10/compose-window-issue
2. Open the app
3. Move the app to another monitor
4. Click the button to open the dropdown
5. See wrong position

**Expected behavior**
Dropdown is moved to show the whole dropdown instead of only the first part

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/6090655/1b939fd8-8fc6-46b6-a83b-96aa78a1b75d)

**Additional context**
Only happens on MacOS

**Comment by m-sasha** [comment]
Unfortunately I don't have a 2nd monitor to test this.
I used my iPad as another monitor, but the issue didn't reproduce there.

<img width="801" alt="SCR-20240430-nzgt" src="https://github.com/JetBrains/compose-multiplatform/assets/5230206/e5166077-a8e0-400c-a6e1-f020a2bd8d14">

**Comment by m-sasha** [comment]
Ok, managed to reproduce with a virtual monitor.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4697">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
