### ISSUE TITLE
Some emojis are not rendered correctly on iOS

### ISSUE THREAD

**Issue by GimazDo** [JetBrains/compose-multiplatform#4699]
**Describe the bug**
If use emoji (like ) in Text or TextField  they are not rendered correctly. 
**Affected platforms**
- iOS

**Versions**
- Kotlin version*:  1.9.23
- Compose Multiplatform version*: 1.6.2
- OS version(s)* (required for Desktop and iOS issues): iOS 17.2
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iPhone 15 (simulator only - upd. @mazunin-v-jb )

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Use emojis like 0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣ in Text or TextField

**Expected behavior**
Emojis render correctly

**Screenshots**
![Screenshot 2024-04-25 at 10 23 36](https://github.com/JetBrains/compose-multiplatform/assets/73364856/8eecb7e6-f291-4cec-bd46-c6d31737edc5)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4699">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
