### ISSUE TITLE
1.6.10-beta02 + Kotlin 2.0.0-RC1 Compose Resources not working with Android Flavours

### ISSUE THREAD

**Issue by iruizmar** [JetBrains/compose-multiplatform#4700]
**Describe the bug**
Trying to generate compose multimodule resources with Compose `1.6.10` and `Kotlin 2.0.0` ends up in the following error while syncing Gradle project:

``` 
Querying the mapped value of provider(java.util.Set) before task ':bard:androidStagingDebugResourcesCopyHierarchicalMultiplatformResources' has completed is not supported
    Querying the mapped value of provider(java.util.Set) before task ':business:common:androidStagingDebugResourcesCopyHierarchicalMultiplatformResources' has completed is not supported
    Querying the mapped value of provider(java.util.Set) before task ':business:user:androidStagingDebugResourcesCopyHierarchicalMultiplatformResources' has completed is not supported
    Querying the mapped value of provider(java.util.Set) before task ':common:resources:androidStagingDebugResourcesCopyHierarchicalMultiplatformResources' has completed is not supported
    Querying the mapped value of provider(java.util.Set) before task ':pub:app:androidStagingDebugResourcesCopyHierarchicalMultiplatformResources' has completed is not supported
    Querying the mapped value of provider(java.util.Set) before task ':user:app:androidStagingDebugResourcesCopyHierarchicalMultiplatformResources' has completed is not supported
    Querying the mapped value of provider(java.util.Set) before task ':user:ui:androidStagingDebugResourcesCopyHierarchicalMultiplatformResources' has completed is not supported
```

I'm suspecting about Android flavors because of #4318 and because all failed projects are `androidStagingDebug`.

**Affected platforms**
- Desktop (Windows, Linux, macOS)
- iOS
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library
- Android

**Versions**
- Kotlin version*: 2.0.0-RC1
- Compose Multiplatform version*: 1.6.10-beta02

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Add a compose resources directory
2. Sync the Gradle project

**Expected behavior**
The sync finishes successfully and the multimodule resources are generated

**Comment by terrakok** [comment]
https://youtrack.jetbrains.com/issue/KT-67806

**Comment by terrakok** [comment]
It seems as KGP or AGP problem.
Build works as expected. Only import to the IDE fails

**Comment by iruizmar** [comment]
Thanks for that :) I think we can close this issue in that case, can't we?

**Comment by igordmn** [comment]
Yes, let's move conversation to https://youtrack.jetbrains.com/issue/KT-67806.

There is a workaround for the issue.
