### ISSUE TITLE
When quickly entering `TextField` with `KeyboardType.Password` on iOS, the UI jank.

### ISSUE THREAD

**Issue by robxyy** [JetBrains/compose-multiplatform#4713]
**Describe the bug**
When quickly entering `TextField` with `KeyboardType.Password` on iOS, the UI jank.

**Affected platforms**

- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-beta02
- OS version(s)* (required for Desktop and iOS issues): 17.4.1
- Device (model or simulator for iOS issues): model

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

[PasswordTextfieldExample.kt](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/mpp/demo/src/commonMain/kotlin/androidx/compose/mpp/demo/textfield/PasswordTextfieldExample.kt)

https://github.com/JetBrains/compose-multiplatform/assets/9105106/9b9208b1-5589-447b-bcf7-537ba8ed789b

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4713">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
