### ISSUE TITLE
Support SVG on Android

### ISSUE THREAD

**Issue by Amr-A-AdbElBaky** [JetBrains/compose-multiplatform#4715]
**Describe the bug**
                App Crash:  java.lang.IllegalStateException: Android platform doesn't support SVG format.
 

**Affected platforms**

- Android

**Versions**
- Kotlin version*:  2.0.0-RC1
- Compose Multiplatform version*: 1.6.10-beta02
- OS version(s)* (required for Desktop and iOS issues):  Android

**Comment by igordmn** [comment]
SVG support isn't implemented for Android because it doesn't support SVG natively. The main focus of this support is desktop-only and desktop/web applications.

For Multiplatform projects with Android target, [XML vector drawables](https://developer.android.com/develop/ui/views/graphics/vector-drawable-resources) should be used.

**Comment by igordmn** [comment]
Supporting SVG for Android isn't trivial, but possible. Let's keep this issue open.

**Comment by MohamedRejeb** [comment]
Coil is using this library to render svg on Android https://github.com/BigBadaboom/androidsvg
Maybe you can add something similar to it to the resources library.

**Comment by Nek-12** [comment]
That library seems abandoned

**Comment by Nek-12** [comment]
Why close this? Igor asked to keep the issue open

**Comment by terrakok** [comment]
Side note by @nickbutcher: https://medium.com/androiddevelopers/understanding-androids-vector-image-format-vectordrawable-ab09e41d5c68
### Why not SVG?

If you’ve ever worked with vector image formats, you’ll likely have come across the SVG format (Scalable Vector Graphics), the industry standard on the web. It is capable and mature with established tooling, but it’s also a vast standard. It includes many complex capabilities like executing arbitrary javascript, blur and filter effects or embedding other images, even animated gifs. Android runs on constrained mobile devices so supporting the entirety of the SVG spec wasn’t a realistic goal.

SVG does however include a [path spec](https://www.w3.org/TR/SVG/paths.html) which defines how to describe and draw shapes. With this API you can express most vector shapes. This is essentially what Android supports: SVG’s path spec (plus a few additions).

**Comment by sergeych** [comment]
The "compose" is called here "multiplatform" so it just _must_ undertake any effort to be so. The issue should be reopened and somehow implemented. There is a reasonable subset of SVG that could be implemented without big problems.

**Comment by RaheemJnr** [comment]
This issue shouldn't be closed yet

**Comment by amgdeveloper** [comment]
I agree that this issue shouldn't be closed. Why doing such a simple thing as displaying an svg in cross platform becomes so difficult?  😅

**Comment by UAdenisyu** [comment]
Why closed? Every popular crossplatform has ability to use svg directly without any issues. Compose Multiplatform shouldn't
fall behind

**Comment by terrakok** [comment]
No-one will answer on the github. All communications are on the youtrack
https://youtrack.jetbrains.com/issue/CMP-5960
