### ISSUE TITLE
Allow for Resources accessors to be generated for custom directory structure

### ISSUE THREAD

**Issue by AlexBurdu** [JetBrains/compose-multiplatform#4718]
**Describe the bug**

In the project I'm working on we try to reduce the nesting of the directories and customized the directory structure:

```kotlin
  sourceSets {
    val commonMain by getting {
      kotlin.apply {
        srcDir("commonMain")
        resources.srcDir("commonMain/composeResources")
      }
  // missing code
  }
// missing code
```

What happens is that the Resources accessors (extensions) are not generated, hence we can't do `Res.drawable.cupcake` and still need to rely on `DrawableResource("drawable/copcake.xml")`.

It would appear that the new compose resources feature relies on the standard structure and does not generate the accessors when that is customized.

Changing the above to the following fixes the issue:

```kotlin
  sourceSets {
    val commonMain by getting {
      kotlin.apply {
        srcDir("src/commonMain")
        resources.srcDir("src/commonMain/composeResources")
      }
  // missing code
  }
// missing code
```

_Notice the `src` addition_.

**Affected platforms**
- Tested Desktop (Linux) and Android, but I expect it to happen on all

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.2
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 22.04.4 LTS
- OS architecture (x86 or arm64): x64
- JDK (for desktop issues): Temurin 17.0.6

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Create a new KMP project and customize the directory structure as above
2. Add a resource in the composeResources directory 
3. Build the project
4. Observe `Unresolved reference: cupcake`

**Expected behavior**
Resources should be accessible for custom directory structure, as the path to them is provided in the gradle configuration.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4718">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
