### ISSUE TITLE
Modify dim level in Dialog

### ISSUE THREAD

**Issue by dhng22** [JetBrains/compose-multiplatform#4721]
As stated, how do i change the dim level behind the dialog on IOS target?

**Comment by MatkovIvan** [comment]
`DialogProperties.scrimColor`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4721">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
