### ISSUE TITLE
Modifier.pointerInput or clickable not working for UIKitView

### ISSUE THREAD

**Issue by paxbun** [JetBrains/compose-multiplatform#4722]
**Describe the bug**

Callbacks passed to `AndroidView()` via `Modifier.pointerInput` or `Modifier.clickable` are invoked, while callbacks passed to `UIKitView()` are not invoked.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10
- OS version(s)* (required for Desktop and iOS issues): iOS 17
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): Both for real devices and simulators
- JDK (for desktop issues):

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

```kotlin
// MyView.kt
@Composable
expect fun MyView(modifier: Modifier)

// MyView.android.kt
@Composable
actual fun MyView(modifier: Modifier) {
  AndroidView(
    factory = {
      View(it).apply { background = ColorDrawable(Color.BLUE) }
    },
    modifier = modifier,
  )
}

// MyView.ios.kt
@Composable
actual fun MyView(modifier: Modifier) {
  UIKitView(
    factory = {
      UIView().apply { backgroundColor = UIColor.blueColor }
    },
    modifier = modifier,
  )
}

// App.kt
@Composable
fun App() {
  MyView(
    Modifier
      .fillMaxSize()
      .pointerInput(Unit) {
        detectTapGestures { offset -> println(offset) }
      }
  )
}
```

1. Observe a blue background is rendered.
2. Click anywhere.
3. On Android, logcat reports the xy coordinates of the touch position. On iOS, nothing is printed in stdout.

**Expected behavior**
`UIKitView` should also handle touch events like `AndroidView`.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by robxyy** [comment]
@paxbun You can try setting `interactive = false`

**Comment by paxbun** [comment]
Hi @robxyy, where can I set that?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4722">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
