### ISSUE TITLE
Is there any easy way to help me intercept the return key?

### ISSUE THREAD

**Issue by Oyama-Oyama** [JetBrains/compose-multiplatform#4724]
**Describe the problem**
Explain the performance issue you're experiencing, including the following details:

- What specific issue did you encounter? (e.g. missing frames, high CPU usage, memory leaks)
- Have you noticed any patterns or specific circumstances under which the problem occurs?

**Affected platforms**
Select one of the platforms below:
- All
- Desktop
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library
- iOS
- Other

If the problem is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version: 
- Compose Multiplatform version: 
- OS version(s) (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**Sample code**
If possible, provide a small piece of code that reproduces the problem. If the code snippet is too large to paste here, please link to a Gist, a GitHub repo, or any other public code repository.

**Reproduction steps**
Please provide a detailed step-by-step guide on how to reproduce the issue you are experiencing.

**Video**
If you're reporting slow app work or missing frames, please provide a video of the problem.

**Profiling data**
Please provide any relevant profiling data that might be helpful. This could include information like FPS, memory usage, CPU time, or any other data that could provide insight into the performance issue.

**Additional information**
Provide any other details that you think might be helpful for us to understand the problem. This could include things like the system configuration, external factors, etc.

**Comment by igordmn** [comment]
Use this:
```
        var text by remember { mutableStateOf("") }
        TextField(text, { text = it }, Modifier.onPreviewKeyEvent {
            if (it.key == Key.Enter) {
                println("Enter")
                true
            } else {
                false
            }
        })
```

**Comment by Oyama-Oyama** [comment]
This method has no effect when using NavController

**Comment by igordmn** [comment]
Could you provide a snippet with NavController where it doesn't work?

**Comment by Oyama-Oyama** [comment]
SudokuTheme(appTheme = appTheme) {
        NavHost(
            navController = navController,
            startDestination = "test",
            modifier = Modifier.fillMaxSize(1.0f).onPreviewKeyEvent { 
                println("key::${it.key.keyCode}")
                true
            }
        ) {
          
        }
    }

**Comment by Oyama-Oyama** [comment]
val navController = rememberNavController()
    SudokuTheme(appTheme = appTheme) {
        NavHost(
            navController = navController,
            startDestination = "test",
            modifier = Modifier.fillMaxSize(1.0f).onPreviewKeyEvent {
                println("key::${it.key.keyCode}")
                true
            }
        ) {

        }
    }

**Comment by igordmn** [comment]
`onPreviewKeyEvent` triggers only if some element inside is focused.

See the snippet in https://github.com/JetBrains/compose-multiplatform/issues/4764 how to request a focus.

This is also the task for simplifying this case.

**Comment by Oyama-Oyama** [comment]
androidx.compose.foundation:foundation-android:1.6.7
This dependent library does not support compose multiplatform, right?

**Comment by Oyama-Oyama** [comment]
Functioning normally, thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4724">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
