### ISSUE TITLE
Vertical Text Align Issue in iOS

### ISSUE THREAD

**Issue by dilip640** [JetBrains/compose-multiplatform#4725]
**Describe the bug**
Top and bottom padding is not same in iOS. When using background color with text, then content is misaligned.

**Affected platforms**

- iOS

**Versions**
- Kotlin version*: **1.9.23**
- Compose Multiplatform version*: **1.6.10-beta02**
- OS version(s)* (required for Desktop and iOS issues): **iOS 17.4.1**
- OS architecture (x86 or arm64): **arm64**
- Device (model or simulator for iOS issues):  **IPhone 13Pro**

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
```
Text(
   text = it,
   modifier = Modifier.then(modifier)
       .background(tagData.bgColor ?: Color.Yellow, shape = RoundedCornerShape(12.dp))
       .padding(horizontal = 8.dp),
   color = tagData.color ?: Color.Black,
   fontSize = 12.sp
)
```

**Expected behavior**
Top and bottom text padding should be same.

![image](https://github.com/JetBrains/compose-multiplatform/assets/30716861/625a836a-410f-42ed-847b-726eec5e88f3)

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/30716861/5f9958f0-e603-4fc3-99fa-cd37c749b3f0)

**Comment by gsrathoreniks** [comment]
@dilip640 Have you tried using fontPadding ?
Explanation and examples listed here : [Article](https://medium.com/androiddevelopers/fixing-font-padding-in-compose-text-768cd232425b)

**Comment by dilip640** [comment]
> @dilip640 Have you tried using fontPadding ? Explanation and examples listed here : [Article](https://medium.com/androiddevelopers/fixing-font-padding-in-compose-text-768cd232425b)

@gsrathoreniks This blog is specific to Android. I'm having issue in iOS. Also `includeFontPadding` is not available in compose-multiplatform.

**Comment by gsrathoreniks** [comment]
@dilip640 Try this one out, I used in kotlin multi-platform project only and it solved my issue.
Pass this style to the text.

`TextStyle(lineHeightStyle = LineHeightStyle(alignment = alignment, trim = trim))`

**Comment by dilip640** [comment]
@gsrathoreniks I know there are ways to remove the extra padding. But in multiplatform case the default should be right on each platform.

**Comment by gsrathoreniks** [comment]
maybe it's picking the platform default

**Comment by igordmn** [comment]
Full reproducer:
```
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.style.LineHeightStyle
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Composable
fun App() {
    Text(
        text = "Text",
        modifier = Modifier
            .background(Color.Yellow, shape = RoundedCornerShape(12.dp))
            .padding(horizontal = 8.dp),
        fontSize = 12.sp,
        style = TextStyle.Default.copy(
            lineHeight = 100.sp,
            lineHeightStyle = LineHeightStyle(
                alignment = LineHeightStyle.Alignment.Center,
                trim = LineHeightStyle.Trim.None,
            )
        ),
    )
}
```

Android:
![image](https://github.com/JetBrains/compose-multiplatform/assets/5963351/7a742de9-47df-4f87-ad9f-86ea553a5f68)

Other platforms:
![image](https://github.com/JetBrains/compose-multiplatform/assets/5963351/71036202-7929-4b84-8b20-4d98c17e4db8)

As a workaround, override `lineHeight`:
```
style = LocalTextStyle.current.copy(
    lineHeight = TextUnit.Unspecified
)
```
Otherwise it will use the hardcoded lineheight from the MaterialTheme.

**Comment by MatkovIvan** [comment]
@igordmn it's by design, see https://issuetracker.google.com/issues/321872412

Android/other platforms don't have a diff during my tests. Centering highly depends on font's data/metrics. Different platforms use different font by default.
To get equal positioning - use the same font (from resources for e
![Screenshot 2023-11-09 at 11 53 39](https://github.com/JetBrains/compose-multiplatform/assets/1836384/89d69845-7b8b-492f-a55d-a598be544224)
xample)
Also see my explanation here: https://github.com/JetBrains/compose-multiplatform/issues/3453#issuecomment-1803686130

**Comment by igordmn** [comment]
> Centering highly depends on font's data/metrics

In this case, yes, there is no issue.

Solution is either to use the same font or override `lineHeightStyle`.

Different default font on different systems is by design.

**Comment by MatkovIvan** [comment]
Rechecked this particular sample with default system fonts:
<img width="886" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/1836384/42a420ea-dc2a-4177-9392-900512abcc8f">

Full code is:
```kt

@Composable
fun App() {
    Row(Modifier.systemBarsPadding()) {
        androidx.compose.foundation.text.BasicText(
            text = "Declared",
            modifier = Modifier
                .background(Color.Yellow, shape = RoundedCornerShape(12.dp))
                .padding(horizontal = 8.dp),
            style = TextStyle(
                color = Color.Black,
                fontSize = 12.sp
            ),
        )
        androidx.compose.material3.Text(
            text = "Declared",
            modifier = Modifier
                .background(Color.Yellow, shape = RoundedCornerShape(12.dp))
                .padding(horizontal = 8.dp),
            style = TextStyle(
                color = Color.Black,
                fontSize = 12.sp
            ),
        )
    }
}
```

Regarding specifying only `fontSize` (without `lineHeightStyle` and `lineHeightStyle`) inside `MaterialTheme`, I'd follow Google's recommendation from [the issue mentioned above](https://issuetracker.google.com/issues/321872412):

> To support non-standard text sizes, we encourage users to follow the Material design system and use a different [type scale](https://m2.material.io/design/typography/the-type-system.html#type-scale) rather than changing the font size directly. Alternatively, users can overwrite the line height like so: `style = LocalTextStyle.current.copy(lineHeight = TextUnit.Unspecified)`, or create a custom `Typography` entirely.

**Comment by MatkovIvan** [comment]
> Also includeFontPadding is not available in compose-multiplatform.

and should not! See my explanation here: https://github.com/JetBrains/compose-multiplatform/issues/2477#issuecomment-1825716543

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4725">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
