### ISSUE TITLE
Ignore safe area below bottom bar

### ISSUE THREAD

**Issue by slikasgiedrius** [JetBrains/compose-multiplatform#4727]
**Describe the bug**
I am looking for an advice how to remove safe area on ios below the bottom bar (removing top would be beneficial also). Thank you

**Affected platforms**
- iOS

**Screenshots**
![Screenshot 2024-04-29 at 16 09 07](https://github.com/JetBrains/compose-multiplatform/assets/9390550/af11fc62-68c1-4c56-bc52-dc6c6f921e65)

Code:

```
@Composable
fun BottomNavigationExample() {
    val screens = listOf("Home", "Feed", "Alert", "Jobs")
    var selectedScreen by remember { mutableStateOf(screens.first()) }

    Scaffold(
        bottomBar = {
            BottomNavigation {
                screens.forEach { screen ->
                    BottomNavigationItem(
                        icon = { Icon(getIconForScreen(screen), contentDescription = screen) },
                        label = { Text(screen) },
                        selected = screen == selectedScreen,
                        onClick = { selectedScreen = screen },
                        modifier = Modifier.padding(0.dp)
                    )
                }
            }
        },
        content = {
            Column(
                modifier = Modifier.fillMaxSize(),
                verticalArrangement = Arrangement.Center,
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(text = "Selected Screen: $selectedScreen")
            }

        }
    )
}

@Composable
fun getIconForScreen(screen: String): ImageVector {
    return when (screen) {
        "Home" -> Icons.Default.Home
        "Feed" -> Icons.Default.AccountBox
        "Alert" -> Icons.Default.Notifications
        "Jobs" -> Icons.Default.Done
        else -> Icons.Default.Home
    }
}
```

**Comment by igordmn** [comment]
You should add `ignoresSafeArea` to the root container. [Example](https://github.com/JetBrains/compose-multiplatform/blob/722ad5291d1b9fb91ab2c02cb9c82df83fb01343/examples/imageviewer/iosApp/iosApp/ContentView.swift#L9)

**Comment by slikasgiedrius** [comment]
Is it possible to achieve this inside multiplatform code? I am trying to stay away from platform-based changes as much as possible

**Comment by igordmn** [comment]
No, root containers are platform-specific.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4727">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
