### ISSUE TITLE
CfW: clipboard events do not work on Windows with 1.6.10-beta02

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-multiplatform#4728]
Reported in slack: https://kotlinlang.slack.com/archives/C01F2HV7868/p1714050651787849

**Describe the bug**
Ctrl + C/V/X simply prints a character (C,V or X) into the TextField. It works as expected on macos with Cmd + C/V/X

**Affected platforms**
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API

**Versions**
- Kotlin version*: Any
- Compose Multiplatform version*: 1.6.10-beta02

**Expected behavior**
Ctrl + C/V/X should be handled as clipboard events.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4728">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
