### ISSUE TITLE
Crashed on Windows 7

### ISSUE THREAD

**Issue by michaellee123** [JetBrains/compose-multiplatform#4729]
![WechatIMG3871](https://github.com/JetBrains/compose-multiplatform/assets/18477367/baee6acc-7278-42d7-94cc-7bb8bd96447c)

- Desktop (Windows 7)

**Comment by igordmn** [comment]
Could you try `1.6.10-beta03`? We fixed [this crash](https://github.com/JetBrains/skiko/pull/909) recently

**Comment by igordmn** [comment]
Closing. Please tell if the issue persists

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4729">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
