### ISSUE TITLE
Support Kotlin 2.0.0-RC2

### ISSUE THREAD

**Issue by ZacSweers** [JetBrains/compose-multiplatform#4732]
When testing with RC2 and the new compose compiler plugin, the gradle plugin fails due to 

```
Compose Multiplatform 1.6.2 doesn't support Kotlin 2.0.0-RC2. Please see https://github.com/JetBrains/compose-jb/blob/master/VERSIONING.md#kotlin-compatibility to know the latest supported version of Kotlin.
```

My understanding is this should not longer be a scenario developers have to deal with per

https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compiler.html#migrating-a-jetpack-compose-project

https://android-developers.googleblog.com/2024/04/jetpack-compose-compiler-moving-to-kotlin-repository.html

Can this max version restriction be removed in favor of the first party plugin in K2 onward?

**Comment by AlexanderEggers** [comment]
@ZacSweers The new compose plugin already works with RC1 (just confrimed with my own project).

Just make certain to add the part below:
```
composeCompiler {
    // Not required in final Kotlin 2.0.0 release
    suppressKotlinVersionCompatibilityCheck = libs.versions.kotlin.get()

    // Configure compose compiler options if required
    enableExperimentalStrongSkippingMode = true
}
```

Ref: https://github.com/android/compose-samples/pull/1354/files

**Comment by igordmn** [comment]
It is supported in 1.6.10-beta03. The stable release is planned near the stable release of Kotlin 2.0.0

**Comment by igordmn** [comment]
For 1.6.2 [this](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compiler.html#test-with-the-stable-compose-multiplatform) can be used:
```
compose {
    kotlinCompilerPlugin = "org.jetbrains.kotlin:kotlin-compose-compiler-plugin-embeddable:2.0.0-RC2"
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4732">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
