### ISSUE TITLE
Multiple configuration changes not tracked correctly when using qualifiers

### ISSUE THREAD

**Issue by zsmb13** [JetBrains/compose-multiplatform#4734]
**Describe the bug**

Sometimes the configuration changes I make are not taken into account immediately, and I get (partially) stuck with values from a previous configuration. I have a project here with strings set up in the `values`, `values-dark`, `values-fr`, `values-fr-dark` folders.

So far could only reproduce this on an emulator and not a real device.

**Affected platforms**
- Android emulator (?)

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-dev1593
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): Pixel 7 Pro, API 34 (simulator)

**To Reproduce**

In the video below, using this sample [ResourcesDemo-issue (1).zip](https://github.com/JetBrains/compose-multiplatform/files/15159757/ResourcesDemo-issue.1.zip), I go from:

1. Light, English -> Dark, French ✅ 
1. Dark, French -> Light, English ❌  as this now shows Light, French resources (values-fr)
1. Finally, going from English to French and to English again makes it update correctly.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/12054216/a24a6e1e-8914-4af9-af8b-e03fb0710cbe

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4734">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
