### ISSUE TITLE
Investigate new Apple polices regarding using restricted API

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4738]
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Compose/Skiko/Skia have some internal API from the list, but it doesn't use it.

One of the options is to just remove this API from the build.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4738">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
