### ISSUE TITLE
Gradle tasks are using outputs without declaring an explicit or implicit dependency

### ISSUE THREAD

**Issue by romainbsl** [JetBrains/compose-multiplatform#4739]
**Describe the bug**

Migrating from _Kotlin 1.9.2x_ and _Compose 1.6.0-alpha01_ 👉  _Kotlin 2.0.0-RC2_ + _Compose Compiler_ + _Compose Multiplatrform 1.6.10-beta03_ and running `./gradlew check` I get multiple errors about tasks that are using outputs from `generateResourceAccessorsForAndroidUnitTest` without declaring explicit dependency.

Example:
```
Reason: Task ':framework:compose:kodein-di-framework-compose:generateDebugLintReportModel' uses this output of task ':framework:compose:kodein-di-framework-compose:generateResourceAccessorsForAndroidUnitTest' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```

Using the following workaround helps remove warnings:

```kotlin
tasks.withType<LintModelWriterTask> {
    dependsOn("generateResourceAccessorsForAndroidUnitTest")
}
tasks.withType<LintModelMetadataTask> {
    dependsOn("generateResourceAccessorsForAndroidUnitTest")
}
tasks.withType<AndroidLintAnalysisTask> {
    dependsOn("generateResourceAccessorsForAndroidUnitTest")
}
```

**Affected platforms**
- Probably linked to how Compose Multiplatform handles resources with the **Android** target? 

**Versions**
- Kotlin version*: 2.0.0-RC2
- Compose Multiplatform version*: 1.6.10-beta03

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Go to [Kodein's](https://github.com/kosi-libs/Kodein/tree/kotlin-2) repo and clone `kotlin-2` branch
2. Comment lines [from 28 to 33 include](https://github.com/kosi-libs/Kodein/blob/e1f5d2a1ff7072ba06b2fb4639219cce079489b4/framework/compose/kodein-di-framework-compose/build.gradle.kts#L28)
3. Run gradle task `check`
4. See Gradle warning/error

**Expected behavior**

Not having to use workaround.

**Comment by igordmn** [comment]
Reproduced with these steps:

1. Go to [Kodein's](https://github.com/kosi-libs/Kodein/tree/kotlin-2) repo and clone `kotlin-2` branch
2. Comment lines [from 28 to 33 include](https://github.com/kosi-libs/Kodein/blob/e1f5d2a1ff7072ba06b2fb4639219cce079489b4/framework/compose/kodein-di-framework-compose/build.gradle.kts#L28)
3. `./ gradlew framework:compose:kodein-di-framework-compose:check`
4. See Gradle warning/error

After commenting the Compose plugin, it is successful:
```
plugins {
    kodein.library.mppWithAndroid
    alias(libs.plugins.compose.compiler)
    //alias(libs.plugins.compose)
}

kotlin.kodein {
    jsEnv()
    allComposeUi()

    common.mainDependencies {
        implementation("org.jetbrains.compose.runtime:runtime:1.6.10-beta03")
        api(projects.kodeinDi)
    }

    android {
        sources.mainDependencies {
            api(projects.framework.android.kodeinDiFrameworkAndroidX)
            implementation(libs.android.x.lifecycle.viewmodel.compose)
        }
    }
}
```

**Comment by terrakok** [comment]
Google issue: https://partnerissuetracker.corp.google.com/issues/333831734

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4739">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
