### ISSUE TITLE
Unable to access LocalLifecycleOwner

### ISSUE THREAD

**Issue by cmpeguerog** [JetBrains/compose-multiplatform#4749]
**Describe the bug**
```
java.lang.IllegalStateException: CompositionLocal LocalLifecycleOwner not present
	at androidx.lifecycle.compose.LocalLifecycleOwnerKt$LocalLifecycleOwner$1.invoke(LocalLifecycleOwner.kt:26)
	at androidx.lifecycle.compose.LocalLifecycleOwnerKt$LocalLifecycleOwner$1.invoke(LocalLifecycleOwner.kt:25)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)
	at androidx.compose.runtime.CompositionLocalMapKt.read(CompositionLocalMap.kt:90)
	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:2135)
        .....
```

**Affected platforms**

- iOS
- Android

**Versions**
- Kotlin version*: 2.0.0-RC2
- Compose Multiplatform version*: 1.6.10-beta03
- Device (model or simulator for iOS issues): Google Pixel 3A

**Expected behavior**
- Lifecycle version*: 2.8.0-beta02

**Comment by pablichjenkov** [comment]
That version of the lifecycle library doesn't look valid.

**Comment by MatkovIvan** [comment]
You must use `androidx.compose.ui.platform.LocalLifecycleOwner` on Compose 1.6.

This was moved to another module (`androidx.lifecycle.compose.LocalLifecycleOwner`) recently in AOSP, but it **won't work** until Compose 1.7

**Comment by kodebach** [comment]
I get this error, when trying to use `LifecycleStartEffect` from `org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose:2.8.0`. Seems to me like the current release is simply broken.

I had to manually provide `androidx.compose.ui.platform.LocalLifecycleOwner.current` to `LifecycleStartEffect` to avoid the error

```kotlin
LifecycleStartEffect(Unit, lifecycleOwner = androidx.compose.ui.platform.LocalLifecycleOwner.current) {
    // ...
}
```

**Comment by MatkovIvan** [comment]
@kodebach if you're talking about Android, it's tracked on Google side here - https://issuetracker.google.com/issues/336842920

**Comment by kodebach** [comment]
Thanks for the info. I was testing on Android, but assumed it would affect all platforms since `LifecycleStartEffect` is defined in common code.

**Comment by MatkovIvan** [comment]
No, only Android is affected - multiplatform 1.6.10 uses a new one under the hood

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4749">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
