### ISSUE TITLE
Way to open external activity or app from compose multiplatform for android,ios

### ISSUE THREAD

**Issue by prabinshrestha** [JetBrains/compose-multiplatform#4750]
Hello, Is there any ways or workaround or sample to open external activity or app through intent for android and other implementation for ios using same codebase within compose multiplatform. If yes, please provide the hint.

**Comment by Sanlorng** [comment]
```Kotlin
Interface PlatformState {
    fun launchApp(id: String)
    fun launchWindow(route: String)
}

expect fun rememberPlatformState()
actual fun rememberPlatformState () = Android PlatformState()

private class AndroidPlatformState: PlatformState {
}
```

**Comment by igordmn** [comment]
Using expect/actual function is the way to solve this.

How to open the activity on Android target, see the Android and Jetpack Compose documentation, or ask in the #compose-android Slack channels

**Comment by Sanlorng** [comment]
> @Sanlorng Please provide a more precise solution. The current code contains errors and is not complete.

in the commonMain
```Kotlin
interface PlatformState {
    fun launchWindow(route: String)
}

@Composable
expect fun rememberPlatformState(): PlatformState
```
in the androidMain
```Kotlin
@Composable
actual fun rememberPlatformState(): PlatformState {
    val context = LocalContext.current
    val state = remember(context) {
        AndroidPlatformState(context)
    }
    return state
}

// Android side platform state implementation
@Stable
internal class AndroidPlatformState(
    private val context: Context
) : PlatformState {

    override fun launchWindow(route: String) {
        context.startActivity(context.packageManager.getLaunchIntentForPackage(route))
    }

}
```

finally call `rememberPlatformState` in the commonMain
```Kotlin
@Composable
fun Page() {
    val platformState = rememberPlatformState()
    Button(
        onClick = { platformState.launchWindow("com.test.window") },
        content = { Text(text = "Click to Open Window") }
    )
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4750">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
