### ISSUE TITLE
[Dialog] - BasicAlertDialog expand/collapse animation with TextField single line

### ISSUE THREAD

**Issue by cmpeguerog** [JetBrains/compose-multiplatform#4752]
**Describe the bug**
When user types a long string on a  single line TextField inside a BasicAlertDialog some times the dialog layout expand/collapse horizontally displaying a weird animation.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-beta03
- OS version(s)* (required for Desktop and iOS issues): Ventura 13.6.6
- OS architecture (x86 or arm64): x86
- Device (model or simulator for iOS issues): Simulator iPhone 15 Pro running iOS 17.2, iPhone 12 Pro Max running 17.4.1

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Add single line TextField inside BasicAlertDialog
2. Type a relatively large string.

**Expected behavior**
Alert dialog width should be the same independently of the string size.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/22971874/17089c10-0337-4504-a7a0-99a481ebc56a

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4752">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
