### ISSUE TITLE
Composables disappear on iPad Air 3 with iOS 16.3.1

### ISSUE THREAD

**Issue by brewin** [JetBrains/compose-multiplatform#4756]
**Describe the bug**
All composables disappear on iPad Air 3 with iOS 16.3.1 after opening, closing, then opening the app again. Rotating the screen makes them reappear until the app is closed again. UIKit views on the screen do not disappear, only composables. I was not able to reproduce the issue on an iPad simulator running iOS 16.4 or on an iPhone 8 running iOS 16.7.7. After updating the iPad Air 3 to iOS 17.4.1, the composables no longer disappear and everything appears to work correctly. Unfortunately, I now realize that it is not possible to downgrade iOS, so I can't investigate the issue further. 

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.10-dev1613
- OS version(s)* (required for Desktop and iOS issues): iOS 16.3.1
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iPad Air 3

**To Reproduce**

https://github.com/brewin/cmp-ipad-bug
Open app, close app, open app again.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/1248685/e108ad07-02ad-47e0-86ed-2842072454d1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4756">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
