### ISSUE TITLE
Compose Test not working with `ComposeUIViewController` in iOS 

### ISSUE THREAD

**Issue by igorescodro** [JetBrains/compose-multiplatform#4759]
**Describe the bug**
Following the [Testing Compose Multiplatform UI](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-test.html) article, I decided to reintroduce the UI tests in my project. I'm facing some issues in iOS because it seems that no nodes are found regardless of the parameters. In Android, the tests are working as expected.

If I run the sample in the documentation, it works fine. However, since I want to run integration tests, I need the "full app" to run with the DI and Navigation graph.

```kotlin
// UiTest.kt
@OptIn(ExperimentalTestApi::class)
fun uiTest(block: ComposeUiTest.() -> Unit) = runComposeUiTest {
    setContent { RenderApp() }
    block()
}

@Composable
expect fun RenderApp()

// --------

// UiTest.ios.kt
@Composable
actual fun RenderApp() {
    MainViewController()
}

// UiTest.android.kt
@Composable
actual fun RenderApp() {
    AlkaaMultiplatformApp()
}
```

```kotlin
@BeforeTest
fun setup() {
    initKoin(appModule = module)
}

@AfterTest
fun tearDown() {
    stopKoin()
}

@Test
fun test_titleChangesWhenBottomIconIsSelected() = uiTest {
    HomeSection.entries.forEach { section ->
        val title = resourcesProvider.getString(section.title.desc())

        // Click on each item and validate the title
        onNodeWithContentDescription(label = title, useUnmergedTree = true).performClick()
        onAllNodesWithText(title)[0].assertExists()
    }
}
```

```
// Error on iOS

kotlin.AssertionError: Failed to inject touch input.
Reason: Expected exactly '1' node but could not find any node that satisfies: (ContentDescription = 'Tasks' (ignoreCase: false))
```

I tried multiple other asserts, but all of them fails in iOS and works in Android.

Initially, I tried to implement the tests using [Maestro](https://github.com/mobile-dev-inc/maestro), but the `XCTest` didn't find any view in my application. After spending some time, I found that we need to implement `accessibilitySyncOptions` to make them visible. I thought that this could be related to the issue in Compose Test but now the tests works in Maestro and fails in Compose.

```kotlin
@OptIn(ExperimentalComposeApi::class)
@Suppress("Unused", "FunctionName")
fun MainViewController() = ComposeUIViewController(
    configure = {
        accessibilitySyncOptions = AccessibilitySyncOptions.Always(AccessibilityDebugLoggerImpl())
    }
) {
    AlkaaMultiplatformApp()
}
```

**Affected platforms**

- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.2
- OS version(s)* (required for Desktop and iOS issues): macOS Sonoma 14.4.1
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iPhone 15 - iOS 17.4.1
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Go to [Alkaa's PR](https://github.com/igorescodro/alkaa/pull/674)
2. Run `gradle shared:connectedAndroidTest`
3. Test passes
--
5. Run `gradle :shared:iosSimulatorArm64Test`
6. Test fails - no nodes with text or content description found

**Additional context**
In Jetpack Compose, I had similar tests where I could load the "full app" in the Composable and create integration tests. I don't have too much knowledge in iOS, so I'm not sure if I'm missing something or if this is a bug in the platform. Either way, the existing code is working as expect in Android.

**Comment by m-sasha** [comment]
Does it work without Koin? Without resources?

**Comment by igorescodro** [comment]
That's a very good question... No, it also fails with the exact same error. However, in Android it crashes because at some point the Koin Graph is needed to get the injections. Which leads me to think that something else is happening and my iOS' `MainViewController` is not being rendered. 


```
$ gradle shared:connectedAndroidTest

java.lang.IllegalStateException: KoinApplication has not been started
at org.koin.core.context.GlobalContext.get(GlobalContext.kt:36)
at org.koin.compose.KoinApplicationKt.getKoinContext(KoinApplication.kt:52)
at org.koin.compose.KoinApplicationKt.access$getKoinContext(KoinApplication.kt:1)
```

The sample code runs fine even with Koin and resources, though:
```kotlin
@BeforeTest
fun setup() {
    initKoin(appModule = module)
}

@AfterTest
fun tearDown() {
    stopKoin()
}

@Test
fun test_titleChangesWhenBottomIconIsSelected() = uiTest {
    val title = resourcesProvider.getString(HomeSection.Tasks.title.desc())
    setContent {
        var text by remember { mutableStateOf(title) }
        Text(
            text = text,
            modifier = Modifier.testTag("text")
        )
        Button(
            onClick = { text = "Compose" },
            modifier = Modifier.testTag("button")
        ) {
            Text("Click me")
        }
    }

    onNodeWithTag("text").assertTextEquals(title)
    onNodeWithTag("button").performClick()
    onNodeWithTag("text").assertTextEquals("Compose")
}
```

**Comment by m-sasha** [comment]
Wait, the testing framework only works with Compose UI. It won't work with native elements such as UIViewController.

**Comment by igorescodro** [comment]
But if I update the coding to directly call the `AlkaaMultiplatformApp()` directly in iOS, I face the following issue:

```
kotlin.IllegalStateException: CompositionLocal UIViewController not provided
```

That's my iOS's `MainViewController`:
```kotlin
@OptIn(ExperimentalComposeApi::class)
@Suppress("Unused", "FunctionName")
fun MainViewController(): UIViewController = ComposeUIViewController(
    configure = {
        accessibilitySyncOptions = AccessibilitySyncOptions.Always(AccessibilityDebugLoggerImpl())
    },
) {
    AlkaaMultiplatformApp()
}
```

Is there a way to use it directly and provide this custom `CompositionLocal`?

**Comment by m-sasha** [comment]
You need to remove the direct dependency on UIViewController from your test code.

**Comment by igorescodro** [comment]
Got it. The reason was the `WindowSizeClass` inside my `AppState` class. Removing caused another problems with `UNUserNotificationCenter.currentNotificationCenter()` but definitely not related to `ComposeUIViewController` as I reported. Thank you for the help!
