### ISSUE TITLE
[Compose resources]: Allow custom naming of "Res" class generated 

### ISSUE THREAD

**Issue by rustamsmax** [JetBrains/compose-multiplatform#4763]
Using compose resources in multi module project we have to give alias when importing Res classes from multiple modules 

```
import package.name.modulea.Res
import package.name.moduleb.Res as ResB
import package.name.modulec.Res as ResC
```

It would be good enhancement to allow custom names for this class

```
import package.name.modulea.ResA
import package.name.moduleb.ResB
import package.name.modulec.ResC
```

**Comment by terrakok** [comment]
Have you tried type aliases?
In modulea:
`typalias ResA = Res`

**Comment by rustamsmax** [comment]
@terrakok couldn't access inner property ResA.string

**Comment by rustamsmax** [comment]
The only solution was to create an extra object and expose properties

![telegram-cloud-photo-size-2-5316804612482783472-y](https://github.com/JetBrains/compose-multiplatform/assets/36570577/6ed7d91f-8153-47d6-9143-9d80379c2bea)

**Comment by terrakok** [comment]
https://youtrack.jetbrains.com/issue/KT-34281 😞

**Comment by psuzn** [comment]
I'm curious, multi-module resources are not supported yet, are they? @rustamsmax

**Comment by rustamsmax** [comment]
@psuzn supports from kotlin 2.0

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4763">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
