### ISSUE TITLE
[Compose resources]: Make url paths absolute for JS/Web

### ISSUE THREAD

**Issue by rustamsmax** [JetBrains/compose-multiplatform#4765]
Please, make url paths absolute for JS!

NOT: composeResources/package.name/values/strings.commonMain.cvr
BUT: /composeResources/package.name/values/strings.commonMain.cvr

When window url is dynamically changed via `window.history.pushState(data, url, title)`

https://domain.com -> https://domain.com/user/dashboard

resources cannot be found giving 404 error

**Comment by rustamsmax** [comment]
Here's a temporary workaround

![telegram-cloud-photo-size-2-5341559966458306010-y](https://github.com/JetBrains/compose-multiplatform/assets/36570577/b5a06f41-02bb-483c-91ee-4aa893e439f3)

**Comment by terrakok** [comment]
The current default was selected to support different compose apps on the same host and the API is exactly to configure that behaviour

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4765">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
