### ISSUE TITLE
Could not isolate value org.jetbrains.compose.internal.service.ConfigurationProblemReporterService

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4773]
https://youtrack.jetbrains.com/issue/KT-67968/Compose-Compiler-Plugin-Fails-to-configure-and-import-into-IDE-sometimes

**Comment by terrakok** [comment]
To fix the issue there is a requirement to load all gradle plugins in the root project:
```kotlin
plugins {
    id("pure-kotlin-ios.app-conventions").apply(false)
    id("pure-kotlin-ios.compose-conventions").apply(false)
    id("pure-kotlin-ios.ios-conventions").apply(false)
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4773">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
