### ISSUE TITLE
Unable to collect hover interactions over BasicText

### ISSUE THREAD

**Issue by iamcalledrob** [JetBrains/compose-multiplatform#4775]
**Describe the bug**

**Affected platforms**

- Desktop (Windows, Linux, macOS)
- iOS
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library 

**Versions**
- Libraries:
  - Compose Multiplatform version:
  - Navigation Multiplatform version (for related issues):
  - ...
- Kotlin version: 
- OS version(s) (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64):
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 

**To Reproduce**
1. Run this code snippet:
   ```kt
   @Composable
   fun BugReproduction() {
       // ...
   }
   ```
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4775">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
