### ISSUE TITLE
Add GPG signatures to released artifacts

### ISSUE THREAD

**Issue by YasserDbeis** [JetBrains/compose-multiplatform#4776]
Hello, I am an engineer in Android Studio. We are looking to utilize the compose desktop (including junit4 compose desktop testing) + skia artifacts in Studio, but to do so we required the GPG signatures/asc files to be released with the artifacts so that we can retrieve such signatures on fetch from the maven repository.

**Comment by YasserDbeis** [comment]
I forgot to mention that this also includes the junit4 compose desktop testing artifacts.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4776">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
