### ISSUE TITLE
Accessibility. Review enabling accessibility on Windows in native distributed apps

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4779]
For development, this is required:
https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Accessibility/Windows.md#enabling-java-accessibility-on-windows

For native distributed apps this very unconvinient, and shouldn't be required.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4779">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
