### ISSUE TITLE
Compose 1.6.2 iOS ComposeContainer memory leak

### ISSUE THREAD

**Issue by skytoup** [JetBrains/compose-multiplatform#4780]
Compose 1.6.2, iOS 17.5

After displaying ComposeUIViewController in iOS, the memory is not freed, and the ComposeContainer is not freed by Xcode Memory Graphs.

1. Show Compose View by present within iOS native View
2. Close the Compose View

<img width="1237" alt="Screenshot 2024-05-08 at 18 43 11" src="https://github.com/JetBrains/compose-multiplatform/assets/11342389/8d70a4fb-2884-4c24-b04d-87128eb72f5d">

### Demo Project
[MemoryLeakDemo.zip](https://github.com/JetBrains/compose-multiplatform/files/15247806/MemoryLeakDemo.zip)

**Comment by MatkovIvan** [comment]
I hope it's already fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/1082, but let @elijah-semyonov recheck

**Comment by elijah-semyonov** [comment]
@skytoup 
There shouldn't be a memory leak. ComposeUIViewController is not guaranteed to be GCed immediately after it's not used anymore, can take some time (so it's an expected situation that one or two ComposeUIViewController can reside in memory for some time).

Try to reproduce it on `1.6.10-rc0`?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4780">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
