### ISSUE TITLE
ComposeUIViewController don't Update View

### ISSUE THREAD

**Issue by FelixSubject211** [JetBrains/compose-multiplatform#4781]
Hello I have 

fun SelectAppointmentViewController(
    bookAppointmentScreenModel: BookAppointmentScreenModel,
    appointmentBody: AppointmentBody
) = ComposeUIViewController {
    MaterialTheme(colors = ColorSystem.ColorPalette()) {
        SelectAppointmentCompose(bookAppointmentScreenModel, appointmentBody)
    }
}

When I start the app in Android the SelectAppointmentCompose is updated. When the app starts from MainViewController in IOS also.

The problem occurs as soon as I call the SelectAppointmentCompose via the SelectAppointmentViewController in Swiftui. Then the compose is not redrawn with new calls, although SelectAppointmentViewController is called with new parameters

**Comment by FelixSubject211** [comment]
I found a solution. It may well be that this isn't a bug at all. If so, I'm very sorry for the disruption!

You have to use the updateUIViewController in the calling UIViewControllerRepresentable.

I did it like this:

```
func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        let newViewController = SelectAppointmentViewControllerKt.SelectAppointmentViewController(
            bookAppointmentScreenModel: bookAppointmentScreenModel,
            appointmentBody: appointmentBody
        )
        
        uiViewController.willMove(toParent: nil)
        uiViewController.view.removeFromSuperview()
        uiViewController.removeFromParent()
        
        uiViewController.addChild(newViewController)
        newViewController.view.frame = uiViewController.view.frame
        uiViewController.view.addSubview(newViewController.view)
        newViewController.didMove(toParent: uiViewController)
 }
```


Felt a bit hacky but it worked

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4781">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
