### ISSUE TITLE
TextField cannot input in ExposedDropdownMenuBox, when ExposedDropdownMenu is expanded

### ISSUE THREAD

**Issue by losomo** [JetBrains/compose-multiplatform#4782]
### Discussed in https://github.com/JetBrains/compose-multiplatform/discussions/4693

<div type='discussions-op-text'>

<sup>Originally posted by **JasonMing** April 24, 2024</sup>
> - Kotlin version*: 1.9.23
> - Compose Multiplatform version*: 1.6.5

I'm trying to implement a filterable drop down menu in **Compose Web** by using **Material3**'s `ExposedDropdownMenuBox`.
```kotlin
var expand by remember { mutableStateOf(false) }
var text by remember { mutableStateOf("") }
ExposedDropdownMenuBox(
    expanded = expand,
    onExpandedChange = { expand = !expand },
) {
    OutlinedTextField(
        value = text,
        label = { Text("Options") },
        onValueChange = {
            text = it
        },
        trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = expand) },
        modifier = Modifier.menuAnchor(),
    )

    ExposedDropdownMenu(
        expanded = expand,
        onDismissRequest = { expand = false },
    ) {
        listOf("foo", "bar", "baz")
            .filter { it.contains(text) }
            .forEach {
                DropdownMenuItem(
                    text = { Text(it) },
                    onClick = {
                        text = it
                        expand = false
                    }
                )
            }
    }
}
```
<img width="372" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/1220848/6b23e781-7ca8-43b0-ba71-acc8955128ec">

After click the TextField, menu will auto expand.
The focus is still on the TextField, it should be able to input, but actually NOT.
If I collapse the menu, the TextField will be able to input again.
</div>

**Comment by losomo** [comment]
I'm seeing the same behavior in Android. The keyboard is active, but pressing the keys does not do anything.

**Comment by lumkit** [comment]
Just set the focus of ExposedDropdownMenuBox to false(in PopupProperties).

**Comment by MatkovIvan** [comment]
The problem here is that `DropdownMenu` steals focus. In Material 3 1.3.*, there is a related change: https://android-review.googlesource.com/c/platform/frameworks/support/+/3028145

It adds a parameter to `menuAnchor` that controls if a dropdown menu is focusable or not. It cannot be just unconditionally changed in the current version because focus is usually required there (for example for keyboard arrows navigation)

**Comment by krazzbeluh** [comment]
I can confirm I have the same issue with desktop and iOS. Android is working well

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4782">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
