### ISSUE TITLE
Generate XCFramework with UI, resources and dependencies

### ISSUE THREAD

**Issue by nareshkommana** [JetBrains/compose-multiplatform#4789]
Can we get support how to generate an iOS framework (.xcframework) with Compose UI, we as team struggling from some time for the same.
FYI : We know how to generate .xcframework with the KMP but we stuck with Compose Multiplatform
In short we want to generate .xcframework with both Kotlin and Compose Multiplatform (Business logic + UI)
Once it got generated we want to release the framework in cocoapods and spm.

**Comment by terrakok** [comment]
There is no difference between a regular kotlin framework and a framework with compose.
Only thing you have to know is iOS world doesn't have a standard specification how to distribute resources together with a framework. So, each package manager does it on their own.

For example, with cocoapods you are suppose to declare a directory with resources in the xcframework's podspec file. To build the directory with resources you may call `syncFramework` task and get the resources in "build/compose/cocoapods/compose-resources" dir

**Comment by terrakok** [comment]
KGP issue: https://youtrack.jetbrains.com/issue/KT-68139

**Comment by terrakok** [comment]
https://youtrack.jetbrains.com/issue/KT-66790

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4789">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
