### ISSUE TITLE
Desktop artifact dependencies should not be of type aar

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-multiplatform#479]
Looking at the dependencies of many of the maven artifacts (eg. https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/desktop/desktop/0.3.2/desktop-0.3.2.pom) we see that dependencies are declared like:

```
    <dependency>
      <groupId>org.jetbrains.compose.runtime</groupId>
      <artifactId>runtime</artifactId>
      <version>0.3.2</version>
      <scope>compile</scope>
      <type>aar</type>
    </dependency>
```

But this is really weird because desktop does not use aars and so specifying the type as such can confuse the build systems.

**Comment by tadfisher** [comment]
Gradle will ignore the POMs and use the `.module` metadata file for resolution, which is probably why it works in Gradle. The `files` array looks like it specifies `.jar` dependencies and each variant is specifying the `"org.gradle.libraryelements": "jar"` attribute so that's the artifact that's resolved at build time.

**Comment by igordmn** [comment]
I think we should write the right type ("jar"). Even if "aar" works, it is not right :).

**Comment by olonho** [comment]
Is it something to be fixed in publishing task, right?

**Comment by igordmn** [comment]
>Is it something to be fixed in publishing task, right?

Yes, probably here:
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:buildSrc/src/main/kotlin/androidx/build/MavenUploadHelper.kt;l=227;bpv=0

**Comment by Kernald** [comment]
This is still a blocking issue with 1.0.0-beta5 from Maven Central using other build systems than Gradle.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6095">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
