### ISSUE TITLE
Kotlin/Wasm responsive layout

### ISSUE THREAD

**Issue by N7ghtm4r3** [JetBrains/compose-multiplatform#4791]
**Describe the problem**
Hi, I'm using Kotlin/Wasm to build a webapp with Compose for web and I wonder know how It possible to build a responsive layout for mobile and desktop versions? There is a built-in way to do that or not?

**Affected platforms**
Select one of the platforms below:
- Web (K/Wasm) - Canvas based API

**Versions**
- Kotlin version: 1.9.20
- Compose Multiplatform version: 1.6.0

**Comment by luludevmuniz** [comment]
It will be easier when material3-adaptive and Window Size Class support for CMP is out. See [3688](https://github.com/JetBrains/compose-multiplatform/issues/3688) and [2404](https://github.com/JetBrains/compose-multiplatform/issues/2404).
For the latter, we have https://github.com/chrisbanes/material3-windowsizeclass-multiplatform

**Comment by N7ghtm4r3** [comment]
Thanks for the information!

But I tried to use the Window Size class but the result  was more o less the same, so not correctly adapted to the mobile size, but the materia3-adaptive is still in development to be implemented in a future release?

**Comment by Sanlorng** [comment]
> Thanks for the information!
> 
> But I tried to use the `Window Size class` but the result  was more o less the same, so not correctly adapted to the mobile size, but the `materia3-adaptive` is still in development to be implemented in a future release?

Material3-windows-size is align the adaptive design guideline，if you want get the best experience ，you should read the [guideline](https://m3.material.io/foundations/layout/applying-layout/window-size-classes)

**Comment by N7ghtm4r3** [comment]
Yes sure! Thanks for the tip, but I'm facing this behavior also using the `Material3-windows-size': 

Viewed from desktop:
![Screenshot 2024-05-10 164751](https://github.com/JetBrains/compose-multiplatform/assets/64226606/b41b70b6-51d8-47b8-a3b6-64430443b724)

Viewed from a mobile device (the same text is that little dot in the center of the screen):
![Screenshot 2024-05-10 164845](https://github.com/JetBrains/compose-multiplatform/assets/64226606/9006ec05-e971-4f55-b44b-0257c508cedc)

It look like if the content of the page was zoomed out

**Comment by PMARZV** [comment]
its because <meta name="viewport" content="width=device-width, initial-scale=1.0"> is not set in the html file (i dont know if adding this will render the canvas unusable and clicks and pointer events will be affected )

**Comment by N7ghtm4r3** [comment]
Okay thanks! I will try and send a feedback about the click id are still usable

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4791">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by N7ghtm4r3** [comment]
Thank you, but it has been already solved
