### ISSUE TITLE
Support text hyphenation

### ISSUE THREAD

**Issue by brewin** [JetBrains/compose-multiplatform#4792]
**Describe the bug**
Automatic text hyphenation does not work on iOS.

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10-dev1623

- Kotlin version: 
- OS version(s) (required for Desktop and iOS issues): iOS 17.4
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): All

**To Reproduce**
```kt
@Composable
fun App() {
    MaterialTheme {
        Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
            Text(
                text = text,
                modifier = Modifier.width(200.dp).background(Color.LightGray).padding(8.dp),
                style = MaterialTheme.typography.bodyMedium.copy(
                    lineBreak = LineBreak.Paragraph,
                    hyphens = Hyphens.Auto
                )
            )
        }
    }
}

expect fun getPlatformName(): String

private val text =
    "This is compose multiplatform text on ${getPlatformName()}. This is more compose" +
        " multiplatform text on ${getPlatformName()}. This is even more compose multiplatform" +
        " text on ${getPlatformName()}. Supercalifragilisticexpialidocious!"
```

**Screenshots**
<img src="https://github.com/JetBrains/compose-multiplatform/assets/1248685/adfc8928-ff23-45dc-9ae7-eaa8732f9d74"  width="400"/>
<img src="https://github.com/JetBrains/compose-multiplatform/assets/1248685/baaadb38-da83-4cad-a5e5-b1c64e79d95c"  width="400"/>

**Comment by MatkovIvan** [comment]
It's currently not supported. As I see, it's not implemented in an underlying skia library either. On Android, Compose uses a system line breaker for this.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4792">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
