### ISSUE TITLE
Brush.linearGradient don't work

### ISSUE THREAD

**Issue by zhishuai-tang** [JetBrains/compose-multiplatform#4794]
**Describe the bug**
drawLine() with Brush.linearGradient() don't work 

**Affected platforms**

- Desktop (Windows)

**Versions**
- Libraries:
  - Compose Multiplatform version: since 1.5.1

- Kotlin version: 1.9.10

**To Reproduce**
1. Run this code snippet:

```kt
@Composable
private fun AirQualityProgress(aqi: Int) {
    val aqiValue = if (aqi < 500) {
        aqi
    } else {
        500
    }
    Canvas(
        modifier = Modifier
            .fillMaxWidth()
            .padding(5.dp)
    ) {
        drawLine(
            brush = Brush.linearGradient(
                0.0f to Color(red = 139, green = 195, blue = 74),
                0.1f to Color(red = 255, green = 239, blue = 59),
                0.2f to Color(red = 255, green = 152, blue = 0),
                0.3f to Color(red = 244, green = 67, blue = 54),
                0.4f to Color(red = 156, green = 39, blue = 176),
                1.0f to Color(red = 143, green = 0, blue = 0),
            ),
            start = Offset.Zero,
            end = Offset(size.width, 0f),
            strokeWidth = 20f,
            cap = StrokeCap.Round,
        )
        drawPoints(
            points = arrayListOf(
                Offset(size.width / 500 * aqiValue, 0f)
            ),
            pointMode = PointMode.Points,
            color = Color.White,
            strokeWidth = 20f,
            cap = StrokeCap.Round,
        )
    }
}
```
3. See UI like this

![image](https://github.com/JetBrains/compose-multiplatform/assets/43263553/7178ec28-ae3f-45f5-8ef9-72cc167bfa78)
linearGradient don't work，but it work right with compose-multplatform version:1.4.3 and kotlin version:1.9.0  。

**Expected behavior**

![image](https://github.com/JetBrains/compose-multiplatform/assets/43263553/9965273b-c91d-4966-93aa-8ddde94ecf3b)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4794">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
