### ISSUE TITLE
When targeting Android for a KMP project using `Coil 3.0.0-alpha06`, attempting to use `.toBitmap()` and `.asComposeImageBitmap()` results in `Unresolved reference`

### ISSUE THREAD

**Issue by realityexpander** [JetBrains/compose-multiplatform#4797]
**Describe the bug**
This problem only exists on Android for KMP, for the `Coil 3.0.0-alpha06` library.

Attempting to use the results of a pre-loaded `imageLoader.execute(imageResquest).image` in an `Image` Composable by converting it using `.toBitmap()` and `.asComposeImageBitmap()` results in a compile-time errors:

`Unresolved reference: toBitmap`
`Unresolved reference: asComposeImageBitmap`

_Note:_ 
- When targeting iOS, Desktop or Javascript works as expected with no problems.
- Using the normal coil3 `AsyncImage` works as expected in Android when using just `imageRequest`.

I'm not sure if this is a configuration issue, I checked all the examples and the Coil 3 upgrade guide, and could see no differences.

Referencing this conversation: https://github.com/coil-kt/coil/issues/2246

**To Reproduce**
Here's the line that won't compile when targeting Android:
https://github.com/realityexpander/CloudCoverUSA2/blob/56d7575ac95903974b099738a015994aa5fdb972/composeApp/src/commonMain/kotlin/App.kt#L302

Code:
https://github.com/realityexpander/CloudCoverUSA2/releases/tag/coil3.alpha06.bug.report

**Logs/Screenshots**
![image](https://github.com/coil-kt/coil/assets/5157474/97352902-c139-4215-af28-73ed3bed2241)

**Version**
What library version are you using? Does this occur on a specific API level or Android device?
coil 3.0.0.alpha-06

**Comment by colinrtwhite** [comment]
As mentioned, this issue isn't directly related to Coil. You can reproduce the issue by not importing Coil at all and adding a reference to `org.jetbrains.skia.Bitmap` in common code.

**Comment by MatkovIvan** [comment]
Both mentioned functions are not available in common/Android, they are defined in the appropriate source set. 
Issue for tracking the problem that IDE shows such suggestions: #3503

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4797">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
