### ISSUE TITLE
Todo example. Scrollbar does not fade out when mouse is moved out of the window

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#48]
![peek7EICT0](https://user-images.githubusercontent.com/26204457/97761370-76604200-1afd-11eb-8f07-8bc28db1dbe6.gif)

See also https://github.com/JetBrains/compose-jb/pull/41

**Comment by SebastianAigner** [comment]
This has since been resolved: 

https://github.com/JetBrains/compose-multiplatform/assets/2178959/e3afcc2c-d1ee-4ada-8431-ad44411eee79

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6026">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
