### ISSUE TITLE
Consider adding a boolean to disable `GlobalSnapshotManager.ensureStarted()` call during scene creation

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/compose-multiplatform#4800]
I am building Compose UI for a target you do not support using your repo. Thanks for all the hard work I can easily build upon!

It's hard to build Compose UI for targets which do not have `Dispatchers.Main` available from coroutines due to the global snapshot manager. I have a UI thread in my app, but it doesn't exist until I create it as part of app initialization. It is not known at the time that this library (well, compose-multiplatform-core) is being _compiled_.

I would like to set my `GlobalSnapshotManagerDispatcher` actual to throw when accessed, and instead initialize code similar to the implementation of global snapshot manager myself (before creating my scene).

Would you be open to a boolean flag for scene creation that disables the call to `GlobalSnapshotManager.ensureStarted()` in `BaseComposeScene`?

Of course, I could just disable this call myself, but I would prefer to leave the common sources untouched so that my changes are solely within source sets for the new target.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4800">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
