### ISSUE TITLE
Are there any good suggestions about using compose to generate UI through drag and drop and output the code to the local?

### ISSUE THREAD

**Issue by longqingzhao** [JetBrains/compose-multiplatform#4802]
I want to start a project about generate UI.
but I have no idea use compose to generate UI.

can you give me some good suggestions?

**Comment by eymar** [comment]
What do you mean by UI generation?

Compose Multiplatform requires writing some code in Kotlin in order to create and display some UI elements/views. 

Perhaps these links can help you:

https://github.com/davidleiti/ComposeGenerator
https://jetpackx.io/

**Comment by longqingzhao** [comment]
I think I need these function
1:drag and drop element.
2:generate ui In the designated place what the element was draged and droped
3:generate code which ui was generated
4:the code writed in XXX.kt

**Comment by longqingzhao** [comment]
like:https://github.com/alibaba/lowcode-engine.git
but this is difficute for people who are not programmers.
I want to create a project to use easily with compose.

**Comment by eymar** [comment]
I think it's possible to implement Compose code generator, but Compose Multiplatform doesn't have this feature itself and it won't have it. 

Perhaps, Large Language Models might be helpful here. I can imagine that such a model would take an image of your UI, it would describe it first in plain text, and then it will try to generate the Compose code.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4802">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
