### ISSUE TITLE
Make the generated resource accessors public

### ISSUE THREAD

**Issue by sergeys-opera** [JetBrains/compose-multiplatform#4812]
When working in a multi-module project sometimes it makes sense to share resources between modules.
I don't think it's possible now with Compose Resources as the generated Res object and the resources accessors have internal modifier. It would be good to be able to instruct the compose plugin to generate public resource accessors.

Compose version: 1.6.10-rc02

**Comment by terrakok** [comment]
https://www.jetbrains.com/help/kotlin-multiplatform-dev/1.6.10/compose-images-resources.html#setup

```kotlin
compose.resources {
    publicResClass = true
}
```

**Comment by sergeys-opera** [comment]
Great, thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4812">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
