### ISSUE TITLE
iOS - Scroll does not work at all when touch starts on a UIKitView inside eg a LazyColumn

### ISSUE THREAD

**Issue by AttilaBarany** [JetBrains/compose-multiplatform#4818]
**Affected platforms**
- iOS

**Versions**
- 1.6.0, 1.6.2, 1.6.10-rc01...

**To Reproduce**
Just extend the "uikit-in-compose" example app like this:
<img width="733" alt="Screenshot 2024-05-16 at 16 15 51" src="https://github.com/JetBrains/compose-multiplatform/assets/40792011/5abac7f5-7468-4616-b894-52279dce0862">

(adding a big box after the elements inside the column, and make the column scrollable)

and try to scroll by grabbing eg the textfield

You can reproduce this with any UIKitView, eg a simple UIView(), wkwebview etc... Adding eg Androidview webview does allow us to scroll by grabbing it, but UKitView does not bubble up anything, even tried with custom nestedscrollconnection just print out pre- or post scroll, but got not a single trigger. This failure just makes useless the UIKitView, or at least very limited. You can just integrate only in static pages, without any scrolling, otherwise the user will stuck on the page with invisible contents which are below in the column.

**Comment by brewin** [comment]
Funny, I was just about to submit this same issue. It does severely limit the use of UIKitView. Setting `interactive = false` makes it scrollable, but of course then it isn't interactive.

Here is my minimal reproducer:

```Kotlin
@OptIn(ExperimentalForeignApi::class)
fun MainViewController() = ComposeUIViewController {
    Column(modifier = Modifier.verticalScroll(state = rememberScrollState())) {
        UIKitView(
            factory = {
                UIView().apply {
                    backgroundColor = UIColor.redColor
                }
            },
            modifier = Modifier.fillMaxWidth().height(400.dp)
        )
        repeat(100) {
            Text("Item #$it")
        }
    }
}
```

**Comment by elijah-semyonov** [comment]
Hi, it's a known problem, and not exactly a trivial one to fix due to differences in touch processing in Compose and UIKit. We are investigating our options currently.

**Comment by elijah-semyonov** [comment]
As a workaround, you could present native `UIViewController` with web view modally on top of compose UI.
Use `LocalUIViewController.current`.

**Comment by AttilaBarany** [comment]
> As a workaround, you could present native `UIViewController` with web view modally on top of compose UI. Use `LocalUIViewController.current`.

So how that would could be part of the scrollable content? I dont get it.

**Comment by elijah-semyonov** [comment]
It won't be. But you don't have to reimplement entire screen natively.

**Comment by AttilaBarany** [comment]
> It won't be. But you don't have to reimplement entire screen natively.

Just the column content, get it. Which is the whole screen (except top and bottom bar).:) Never mind. I started and coded the UI already separately/natively, but wanted to refactor to only maintain one UI instead of two. Took almost 2 weeks, and this was the last piece which is missing, everything else looks working, thats why its so annoying :)) But I might keep going this direction and use this screen only natively as suggested. 

Thanks for your help anyway, and I am looking forward to have this fixed. :) 
(p.s I beleive flutter had the very same issue before)

**Comment by brewin** [comment]
Flutter's UIKitView has a `gestureRecognizers` property that allows customizing the gestures that are passed to the UIKit view.

https://api.flutter.dev/flutter/widgets/UiKitView/gestureRecognizers.html

> For example, with the following setup vertical drags will not be dispatched to the UIKitview as the vertical drag gesture is claimed by the parent [GestureDetector].

```dart
GestureDetector(
  onVerticalDragStart: (DragStartDetails details) {},
  child: const UiKitView(
    viewType: 'webview',
  ),
)
```

**Comment by elijah-semyonov** [comment]
Well, we can do that! The problem is, there is no way that is currently apparent to us, to _conditionally_ allow touches to slip to the interop view gesture recognisers.

The behavior on top is possible by the usage of `Modifier.draggable`  and using `intreactable = false` in UIKitView arguments.

**Comment by dilip640** [comment]
facing same issue

**Comment by vickyleu** [comment]
same

**Comment by kavindudiyes** [comment]
@elijah-semyonov could you please expand on your suggestion of "_The behavior in your example is possible by the usage of Modifier.draggable and using interactable = false in UIKitView arguments._". I tried a few combinations of setting interactive = false and implementing draggable on the Modifier, without success. With interactive = false, scrolling is fine, but it doesn't register any click events as @brewin has pointed out above.

My use-case is to embed a Native Ad using Google AdMob, where the UIView for the Ad is coming from Swift for iOS. In the ideal case, I want to be able to scroll on top of the Ad, but still be able to click on the Ad.

**Comment by vickyleu** [comment]
My solution is to turn off the touch event of UIView and unify the click penetration through the click event hitTest of compose to the rect of UIView.

For example, my UIView put a webview, and I need to click on the picture inside. I will first register a query of the coordinates of all pictures through js, get a set of rectangular arrays, and confirm that the picture is clicked by matching the array.

**Comment by elijah-semyonov** [comment]
Awaiting your feedback (and perhaps future issues) after these changes are released!
Track release notes for iOS :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4818">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by AttilaBarany** [comment]
@elijah-semyonov I have imported 1.7.0-dev1727, But I do not experience any difference. The same lazycolumn which holds a wkwebview or a single uiview, does not scroll if the drag starts on the UIKitview (Modify.draggable also not triggered). But it does scroll with Androidview.

**Comment by paskowski** [comment]
I also see no difference when running 1.7.0-dev1727. In my case it's lazy column with `UIKitView` that has `UITextField` inside of it.

**Comment by elijah-semyonov** [comment]
You need to move a finger over the screen fast to recognise a scroll

**Comment by AttilaBarany** [comment]
> I don’t think 1.7.0-dev1727 includes the changes. The next dev release will.

I got it from his commit linked in this issue above. https://github.com/JetBrains/compose-multiplatform-core/commit/174766b50bf9fda2aa04a4a276026f6ee6bd9d5f

<img width="485" alt="Screenshot 2024-07-15 at 14 45 49" src="https://github.com/user-attachments/assets/193e4d32-2ef8-4e34-a29f-c7fd50ef6bf7">

**Comment by elijah-semyonov** [comment]
@AttilaBarany 
Please provide a full repro project, I can't reproduce your behavior from a snippet:
```
val factory = remember {
    {
        UIView().apply {
            backgroundColor = UIColor.blueColor
            userInteractionEnabled = true
        }
    }
}

LazyColumn(modifier = Modifier.fillMaxSize()) {
    item {
        UIKitView(
            modifier = Modifier.fillMaxWidth().height(300.dp),
            factory = factory
        )
    }

    item {
        Box(Modifier.fillMaxWidth().height(1500.dp).background(Color.Red))
    }
}
```

https://github.com/user-attachments/assets/4a2702cd-2683-4e37-87a0-a5cd3e2e1bf2

**Comment by paskowski** [comment]
I agree with https://github.com/JetBrains/compose-multiplatform/issues/4818#issuecomment-2228420632 that https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.7.0-dev1727 does not have the changes that were supposed to fix this issue.

**Comment by AttilaBarany** [comment]
@elijah-semyonov The video looks very promising, thank you for testing and showing me the error maybe is in my setup!!! I had a mistake providing the library version. I have changed the lib to 1.7.0-dev1727, but the gradle was set to use the compose.plugin which had an earlier version set. After fixed (set the plugin version to 1.7.0-dev1727), or I thought I fixed, gradle does not want to sync:
Could not find org.jetbrains.compose.runtime:runtime:1.7.0-dev1727.
Required by:
    project :shared

**Comment by AttilaBarany** [comment]
@elijah-semyonov I got the versions sorted, I set 1.7.0-alpha01 whis is the latest, and the scroll still does not work. So @paskowski  and @brewin  are correct. The fix is still not included.

<img width="146" alt="Screenshot 2024-07-15 at 20 37 04" src="https://github.com/user-attachments/assets/7d545fde-ce0e-4b01-a1c7-5112a29ae777">

**Comment by elijah-semyonov** [comment]
That's super awkward, CI shows that it _was_ included. Anyway, let's w8 for other dev build and see if it flies.

**Comment by MatkovIvan** [comment]
> I got the versions sorted, I set 1.7.0-alpha01 whis is the latest,

`1.7.0-dev1727` is newer than `1.7.0-alpha01`. `1.7.0-alpha01` does not contain @elijah-semyonov 's fix, but dev1727 does. `devXXXX` is regular builds from master that are not uploaded to maven central (available only from dev one), so sorting is not really correct here. We might improve naming in the future, but now it is what it is.

**Comment by paskowski** [comment]
I can confirm that both `1.7.0-dev1727` and `1.7.0-dev1731` work correctly. I think I set an incorrect dependency's version yesterday, apologies for that. Thank you for fixing this, it's a real game changer @elijah-semyonov 🎉 .

**Comment by inveders** [comment]
Hello @elijah-semyonov I use the `1.7.0-dev1727` and I have this error with resources:
` org.jetbrains.compose.resources.MissingResourceException: Missing resource with path: drawable-xxhdpi/splash.png`

When I use the `1.6.0` I didn't have this error. So I can't test the issue with the scroll on UiKitView because it's the image of my splashscreen which crash.

**Comment by yuroyami** [comment]
This broke one of the things that used to work fine. I am wrapping an (native iOS) eBook reader (which is basically a UIViewController) which internally responds to gestures, especially tap gestures. I am wrapping that UIViewController in Compose, in a box that **also has a Compose** tap gesture listener:

```kotlin
@OptIn(ExperimentalForeignApi::class)
@Composable
fun ReadiumViewport(c: UIViewController) {
    Box(
         modifier = Modifier.clickable(.....) <--- This makes the UIViewController internal gesture listeners nonfunctional
    ) {
        UIKitViewController(
            factory = { obtainReadiumController() },
            modifier = Modifier.fillMaxSize()
        )
    }
}
```

It used to scroll, tap, pinch in/out fine, but now it's not responding to touches at all. The only thing that works is the clickable modifier itself, which responds to the click gesture. It seems like the Compose gesture listener is preventing all gestures from propagating to the UIViewController itself.

**Comment by yuroyami** [comment]
This broke one of the things that used to work fine. I am wrapping an (native iOS) eBook reader (which is basically a UIViewController) which internally responds to gestures, especially tap gestures. I am wrapping that UIViewController in Compose:

```kotlin
@OptIn(ExperimentalForeignApi::class)
@Composable
fun ReadiumViewport(c: UIViewController) {
    UIKitViewController(
            factory = { obtainReadiumController() },
            modifier = Modifier.fillMaxSize()
     )
}
```

It used to scroll, tap, pinch in/out fine, but now it's not responding to touches at all. It seems like Compose is preventing all gestures from propagating to the UIViewController itself. I am not sure why this is happening because I am not setting any external Compose tap listeners. All the gesture listening is happening internally inside the UIViewController itself.

**Comment by elijah-semyonov** [comment]
@yuroyami 
We'll provide opt-out to previous behavior. Implementation is already there, just wait a bit for API addition.

**Comment by AttilaBarany** [comment]
@elijah-semyonov the problem looks solved and perfect on published 7.0.0-alpha02. Thanks very much, now it acts how android was/is.

**Comment by elijah-semyonov** [comment]
@AttilaBarany 
You are welcome. Please don't hesitate to post other issues and proposals on our issue tracker.

**Comment by vickyleu** [comment]
@elijah-semyonov I can confirm that compose 1.7.0 xxx has disrupted the scrolling event of webview in UIKitView, 1.6.11 work well
[compose-webview-multiplatform](https://github.com/vickyleu/compose-webview-multiplatform)

**Comment by elijah-semyonov** [comment]
You just need to hold your finger still for 150ms before scrolling.
An opt-out to previous behavior is in https://github.com/JetBrains/compose-multiplatform-core/pull/1494

**Comment by mndsl** [comment]
I have tried al the 1.7xxx versions (dev too) and none of them works as expected. I'm using UIKitView to display PDFView,  the view reacts to taps and double taps, but is impossible to scroll the pages of the pdf documents. There are no nested scrolls, nor click modifiers... 1.6.11 used to work perfectly, unfortunately i can't rollback to it. Please fix this, it's vital part from very large multiplatform app we are developing, and with this bug is impossible to publish the app.

**Comment by brewin** [comment]
They are working on improving interop.

https://youtrack.jetbrains.com/issue/CMP-5875/iOS-interop-epic

**Comment by mekutluca** [comment]
In version 1.7.0, this worked for me: (Notice that I've selected interaction mode as `NonCooperative`)
```
UIKitView(
        factory = {
            PDFView()
        },
        modifier = Modifier.fillMaxSize(),
        update = { view ->
            view.autoScales = true
            view.document = NSData.create(base64Encoding = encodedString)?.let { data ->
                PDFDocument(data = data)
            }
        },
        properties = UIKitInteropProperties(
            isNativeAccessibilityEnabled = true,
            interactionMode = UIKitInteropInteractionMode.NonCooperative,
        ),
    )
```
