### ISSUE TITLE
Invisible text in Text()

### ISSUE THREAD

**Issue by Exidel** [JetBrains/compose-multiplatform#482]
The same issue as #214. App builded on kotlin 1.4.20, 0.2.0-build132. On PC Win10 x64 work fine, on notebook Win7 x64 all Text() contains invisible text, it selectable, can copy/paste but can't see. I try to change kotlin and compose versions like in #214 but all text become unselectable or just gone. Tryed latest versions, all the same.
on 1.4.31, 0.4.0-build173
> Task :run
Failed to create DirectX12 device.
Failed to create Skia Direct3D context!
Falling back to OPENGL rendering...

**Comment by Exidel** [comment]
![Untitled-2](https://user-images.githubusercontent.com/80458677/110947467-4188b500-8351-11eb-9f25-f4887d57c524.jpg)
![Untitled-1](https://user-images.githubusercontent.com/80458677/110947482-464d6900-8351-11eb-8dbf-a5bee5f4b126.jpg)

**Comment by olonho** [comment]
We need to know what is your machine, OS and videocard. Also will `export SKIKO_RENDER_API=SOFTWARE` fix the problem?

**Comment by Exidel** [comment]
Operating System: Windows 7 Home Basic 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr.170913-0600)
System Manufacturer: ASUSTeK Computer Inc.
       System Model: K53SJ
Processor: Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (4 CPUs), ~2.1GHz
DirectX Version: DirectX 11
![VCards](https://user-images.githubusercontent.com/80458677/111133395-8861ef00-858b-11eb-8159-da0e75f0d933.jpg)
**SKIKO_RENDER fix it on 0.4.0**. Think it's may be conflict between integrated and discrete video cards.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6368">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
