### ISSUE TITLE
Request for opting out of generating skiko wasm / js resources in latest compose plugin (1.6.10-rc03)

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-multiplatform#4823]
I'm using Compose HTML, and it seems like the most recent version of Compose started generating skiko wasm and js as part of the build process. This seems to be because "Compose for Web" is now enabled by default.

I have my own resource processing task, and now I'm getting:

> Reason: Task ':site:kobwebxMarkdownProcess' uses this output of task ':site:unpackSkikoWasmRuntimeJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

Of course, I can hook my task up to the skiko task, but if I don't need the skiko resources, I would much rather skip over generating them in the first place.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4823">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
