### ISSUE TITLE
Material3 Icon and Text vertical alignment is abnormal.

### ISSUE THREAD

**Issue by kingsword09** [JetBrains/compose-multiplatform#4825]
**Describe the bug**
The demo I downloaded from [kmp.jetbrains.com](https://kmp.jetbrains.com/) for testing Icon and Text vertical alignment works fine on the Android end, but it is not vertically centered on desktop jvm and iOS.

**Affected platforms**

- Desktop (Windows, Linux, macOS)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.2、1.6.10-rc03
  - org.jetbrains.compose.material:material-icons-extended: 1.6.2、1.6.10-rc03

- Kotlin version: 1.9.24
- OS version(s) (required for Desktop and iOS issues): MacOS: 14.4.1  iOS: 17.4
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): simulator
- JDK (for desktop issues): corretto-17

**To Reproduce**
1. Run this code snippet:
   ```kt
      import androidx.compose.foundation.layout.Column
      import androidx.compose.foundation.layout.Row
      import androidx.compose.foundation.layout.fillMaxWidth
      import androidx.compose.foundation.layout.height
      import androidx.compose.material3.Icon
      import androidx.compose.material.MaterialTheme
      import androidx.compose.material3.Text
      import androidx.compose.material.icons.Icons
      import androidx.compose.material.icons.outlined.Verified
      import androidx.compose.runtime.Composable
      import androidx.compose.ui.Alignment
      import androidx.compose.ui.Modifier
      import androidx.compose.ui.unit.dp
      import org.jetbrains.compose.ui.tooling.preview.Preview
      
      @Composable
      @Preview
      fun App() {
        MaterialTheme {
          Column(
            Modifier.fillMaxWidth().height(50.dp),
            horizontalAlignment = Alignment.CenterHorizontally
          ) {
            Row(
              modifier = Modifier.fillMaxWidth(),
              verticalAlignment = Alignment.CenterVertically
            ) {
              Icon(imageVector = Icons.Outlined.Verified, null)
              Text("test")
            }
          }
        }
      }
   ```
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
Hoping for the icon and text to align vertically in the center.

**Screenshots**
Desktop:
![image](https://github.com/JetBrains/compose-multiplatform/assets/19650362/aa95defb-5ce0-4185-ba7a-8a6f8e04c320)

iOS：
![image](https://github.com/JetBrains/compose-multiplatform/assets/19650362/87c18ff0-8eb5-43cd-8be9-0975ed8c4609)

Android:
![image](https://github.com/JetBrains/compose-multiplatform/assets/19650362/0c08a206-9874-4d05-8dc3-6e8d8c3b54e9)

**Additional context**
The Android and iOS platform meets the requirements, but Desktop do not.

**Comment by MatkovIvan** [comment]
Different platforms have different default fonts, so the exact position of glyphs may vary a bit.

<img width="1259" alt="Screenshot 2023-11-09 at 11 53 39" src="https://github.com/JetBrains/compose-multiplatform/assets/1836384/f0f7bfaa-5527-487e-ad01-f145ad15ea44">

Marking it as duplicate as it was answered a few times already ([1](https://github.com/JetBrains/compose-multiplatform/issues/3453#issuecomment-1803686130), [2](https://github.com/JetBrains/compose-multiplatform/issues/4725#issuecomment-2089174868), ...).
The only leftover is to support all `lineHeightStyle` values: #2602, but it won't affect the case in the description of this issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4825">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
