### ISSUE TITLE
Support 1Password Universal Autofill on Mac

### ISSUE THREAD

**Issue by Syer10** [JetBrains/compose-multiplatform#4829]
1Password Universal auto-fill is a feature that lets apps be associated with passwords that we can auto-fill with. This works with most apps, even Java Swing apps using JTextFields.

For some reason it is unable to work with Compose TextFields, when I try to use the auto-input, it doesn't input anything.

https://support.1password.com/mac-universal-autofill/

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4829">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
