### ISSUE TITLE
1.6.10: MPP with JS but without WASM target: Cannot determine the version of Skiko for Compose '1.6.10

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-multiplatform#4834]
**Describe the bug**
I use a MPP module with JS (compose html) but without WASM but the Gradle plugin tries to add the wasm dependency which fails due the missing target.

**Affected platforms**
- Web (K/JS) - HTML library 

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10

- Kotlin version: 2.0.0-RC3

**To Reproduce**
Bump a K/JS compose html project from 1.6.10-rc03 to 1.6.10
https://github.com/hfhbd/ComposeTodo/actions/runs/9138327814/job/25129335777?pr=981

**Expected behavior**

**Screenshots**

**Additional context**
https://gradle.com/s/nsucmftltej5a

**Comment by eymar** [comment]
@hfhbd I see another attempt passed: https://github.com/hfhbd/ComposeTodo/pull/985/files Is there still a problem?

Tried in our compose.html (k/js) example, and it worked. I'll try with your project too.

**Comment by hfhbd** [comment]
@eymar Well, I removed the JetBrains Compose plugin for the html modules and added the runtime dependency manually to not be blocked.

**Comment by eymar** [comment]
I see. Thanks for clarification

**Comment by eymar** [comment]
Do you mean you did this change - https://github.com/hfhbd/ComposeTodo/pull/984?
Is it supposed to fail on this commit (+ version update) https://github.com/hfhbd/ComposeTodo/commit/73b14f51c04effb0c43c549edd2be7d798a40c8c ?

I did the following:
- Checked out https://github.com/hfhbd/ComposeTodo/commit/73b14f51c04effb0c43c549edd2be7d798a40c8c
- Updated the version from 1.6.10-rc03 to 1.6.10 in libs.versions.toml
- Synced the project - no issues
- `./gradlew clean :web:jsBrowserRun` - works fine.

Am I missing something?

**Comment by eymar** [comment]
Perhaps it was caused by the timing: compose-multiplatform-plugin became available and the bot decided to update right away. But the artefacts (compose libs) were not available yet in mavenCentral at that moment. 

Feel free to reopen, if you have any more details or if you disagree.
