### ISSUE TITLE
Compose for Desktop doesn't emit lifecycle events, only states

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#4835]
1.6.10-rc03.

iOS:

<img width="934" alt="Screenshot 2024-05-19 at 11 28 03" src="https://github.com/JetBrains/compose-multiplatform/assets/2178959/572f495d-bfc6-4138-bf01-b1b0d656f38c">

Desktop:

<img width="1213" alt="Screenshot 2024-05-19 at 11 28 27" src="https://github.com/JetBrains/compose-multiplatform/assets/2178959/02315e5d-68f1-477f-a363-b8363632495d">

Observed via:

```
@Composable
fun LifecycleLogger() {
    val lc = LocalLifecycleOwner.current
    LaunchedEffect(lc) {
        launch {
            lc.lifecycle.currentStateFlow.collect {
                println("New State: $it")
            }
        }
        launch {
            lc.lifecycle.eventFlow.collect {
                println("New Event: $it")
            }
        }
    }
}
```

**Comment by zsmb13** [comment]
Looking at the impl of `eventFlow`:

```
public val Lifecycle.eventFlow: Flow<Lifecycle.Event>
    get() = callbackFlow {
        val observer = LifecycleEventObserver { _, event ->
            trySend(event)
        }.also { addObserver(it) }

        awaitClose { removeObserver(observer) }
    }.flowOn(Dispatchers.Main.immediate)
```

Apparently it uses `Dispatchers.Main`, which is not available if you don't add `coroutines-swing` to the project explicitly. Adding this dependency fixes the issue:

```kotlin
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.8.1")
```

**Comment by SebastianAigner** [comment]
Very strange that I'm seeing no indication (warning, error, log output) indicating this.

**Comment by MatkovIvan** [comment]
It's expected because `kotlinx-coroutines-swing` is optional. I'll check why a warning message is missed + make sure that it's desired in docs

**Comment by MatkovIvan** [comment]
Rechecked what's going on here.

> Compose for Desktop doesn't emit lifecycle events

It does. Even without this extra dependency. You can receive it via:
```kt
lifecycle.addObserver(object : LifecycleEventObserver {
    override fun onStateChanged(source: LifecycleOwner, event: Lifecycle.Event) {
        println("New Event: $event")
    }

})
```

> Very strange that I'm seeing no indication (warning, error, log output) indicating this.

It looks like behavior of `flowOn` function + missed `Dispatchers.Main`. Example:

```kt
flowOf(1, 2, 3)
    .flowOn(Dispatchers.Main.immediate)
    .collect {
        println("collect: $it")
    }
```

Will print nothing and hang on `collect` function without any exceptions. I guess it is out of the scope of Compose Multiplatfrom repo, but maybe worth creating YT issue for coroutines library.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4835">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
