### ISSUE TITLE
ImageViewer example: Android application crash due to missing Android Manifest FileProvider

### ISSUE THREAD

**Issue by issamux** [JetBrains/compose-multiplatform#4841]
**Describe the bug**
ImageViewer android application crash due to missing Android Manifest FileProvider

**Affected platforms**
- Android application

**Versions**
Libraries:
 - Compose Multiplatform version: LAST
 - Kotlin version: 1.9.23
 - OS architecture (x86 or arm64): arm64
 - Device (model or simulator for iOS issues): simulator
 - JDK (for desktop issues): 17

**To Reproduce**
1. Start android application on emulator
2. Click on some image
3. Click again on selected image (Top) to view details
4. Scroll down to show share button
5. click on Share button

**Expected behavior**
Share dialog open

**current behavior**
Application crash

**Comment by issamux** [comment]
it seem that **ImageViewerFileProvider** is not merged in manifest project !!!

**Comment by mazunin-v-jb** [comment]
Hello, @issamux!
Thanks for highlighting this. 
We forgot to add <meta-data> tag with fileprovider paths to the android manifest.

I reviewed your PR, and it seems like it doesn't fix that issue in its current state. But adding this should fix it:
`<meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
`
right after `android:grantUriPermissions="true">` in the `shared/src/androidMain/AndroidManifest.xml`
Thus, if you want to fix it yourself, please, consider my suggestion. We would be glad for your contribution here.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4841">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
