### ISSUE TITLE
Compose Compiler (iOS): public Composable functions in expect/actual class is attempted to be exported to ObjC

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-multiplatform#4848]
When updating the `jetsnack` example to Kotlin 2, the iOS target won't compile:

> e: Compilation failed: no implementation for FUN MISSING_DECLARATION name:shouldShowBottomBar visibility:public modality:FINAL <> () returnType:kotlin.Nothing

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0

**To Reproduce**
```
expect abstract class JetSnackCartViewModel() {
    @Composable
    fun collectOrderLinesAsState(flow: StateFlow<List<OrderLine>>): State<List<OrderLine>>
}

// Then an actual
actual abstract class JetSnackCartViewModel actual constructor()  {
    @Composable
    actual fun collectOrderLinesAsState(flow: StateFlow<List<OrderLine>>): State<List<OrderLine>> {
        return flow.collectAsState()
    }
}
```

The workaround is to add:
```
@OptIn(kotlin.experimental.ExperimentalObjCRefinement::class)
@HiddenFromObjC
```

on the actual class., or make the class internal.

**Comment by eymar** [comment]
Marking it as a regression, because there is no issue when using kotlin 1.9.2x
My guess is that the issue could be on Kotlin side, but only an investigation can confirm.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4848">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
