### ISSUE TITLE
Be able to define define keyboard event handlers that are always active in the current window, globally.

### ISSUE THREAD

**Issue by Zenturas** [JetBrains/compose-multiplatform#4851]
``e.g. using the window object after calling singleWindowApplication. 

Currently, you can define keyboard event handlers during the call to singleWindowApplication, but afterward, it's impossible. I'd like the ability to hook up and add/remove keyboard handlers even after calling singleWindowApplication for this window.

Like for mouse event handling you can

```
@Composable
fun WindowsMouseEventBackHandler(
	composeWindow: ComposeWindow,
	navController: NavController
) {
	val mouseListener = object : MouseListener {
		override fun mouseClicked(event: MouseEvent?) {}
		override fun mousePressed(event: MouseEvent?) {}
		override fun mouseEntered(event: MouseEvent?) {}
		override fun mouseExited(event: MouseEvent?) {}
		override fun mouseReleased(event: MouseEvent?) {
			event?.let {
				if (it.button == 4) {
					// todo navigateUp
				}
			}
		}
	}

	LaunchedEffect(Unit) {
		composeWindow.addMouseListener(mouseListener)
	}

	DisposableEffect(Unit) {
		onDispose {
			composeWindow.removeMouseListener(mouseListener)
		}
	}
}
```

**Comment by igordmn** [comment]
There is a cumbersome way mentioned in https://github.com/JetBrains/compose-multiplatform/issues/4764. Please vote for it, if it is useful to have a simple API.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4851">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
