### ISSUE TITLE
`BasicAlertDialog` Crash iOS with OOM (Memory Leak)

### ISSUE THREAD

**Issue by chrisjenx** [JetBrains/compose-multiplatform#4852]
**Describe the bug**
Since 1.6.10x, m3 `BasicAlertDialog`s with lots of content will recompose and leak memory causing out of memory crashes on iOS.

iOS will throw `didReceiveMemoryWarning` then crash:

![Screenshot 2024-05-22 at 5 38 33 PM](https://github.com/JetBrains/compose-multiplatform/assets/1167793/d29f9fc7-c49e-4e71-9448-6ca4e7aa210a)

More diagnostics to follow once got a sample project for you.

**Affected platforms**
- iOS
 
**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10 (or RC's)
  - Decompose: 3.0
- Kotlin version: 1.9.23
- Device (model or simulator for iOS issues): Physical iPhone (Simulators do no crash) iOS 17.4

**To Reproduce**

More to follow, but full screen dialogs will recompose unconditionally and crash (will try and create a reproduction project for you)

1. Open Dialog with scrollable content
2. Scroll Content very slowly, app will crash after it runs out of memory drawing

**Expected behavior**
Don't OOM and crash on iOS

**Screenshots**
![Screenshot 2024-05-22 at 5 38 33 PM](https://github.com/JetBrains/compose-multiplatform/assets/1167793/047c1c60-149f-4a07-9708-6abf3a045901)

**Additional context**
I thought it was related to Kotlin 2.x but downgraded and still an issue, downgraded CMP to 1.6.1 and now not crashing.

Link to trace from Profling iOS App, looks like a Skia Canvas draw leak in 1.6.10. If you stop moving it will dealloc the objects, but scrolling slowly will not release quick enough.

https://drive.google.com/drive/folders/1UUPOyAWaeg7uTKaXc5EMCp-03jSy4hrk?usp=sharing

**Comment by mazunin-v-jb** [comment]
Hello!
I'll notify the team about that, however, a small reproducible example would really help.

**Comment by chrisjenx** [comment]
Yeah we're working on deploying a hot fix to users once that's done I'll create a sample for y'all

**Comment by chrisjenx** [comment]
Added Trace, easy to reproduce, any dialog with scrollable content, scroll _SLOWLY_ and you'll eventually run out of memory

**Comment by mazunin-v-jb** [comment]
Unfortunately, I wasn't able to successfully reproduce this crash. Memory usage on a small project from template was about 70 mb and didn't increase no matter how I scrolled.
Could you please make a reproducible example?

**Comment by chrisjenx** [comment]
> Unfortunately, I wasn't able to successfully reproduce this crash. Memory usage on a small project from template was about 70 mb and didn't increase no matter how I scrolled. Could you please make a reproducible example?

Dang, OK, will try and create a sample project. Sorry about that

**Comment by chrisjenx** [comment]
> Unfortunately, I wasn't able to successfully reproduce this crash. Memory usage on a small project from template was about 70 mb and didn't increase no matter how I scrolled. Could you please make a reproducible example?

Oh just checking this ONLY happens on a physical device, simulators are fine (faster/more ram from host machine)

**Comment by chrisjenx** [comment]
As requested: 
[DialogCrash.zip](https://github.com/JetBrains/compose-multiplatform/files/15444172/DialogCrash.zip)

I should have noted it was BasicAlertDialogs from the m3 lib

**Comment by chrisjenx** [comment]
Nvm mind, I tested on the foundation `Dialog` and the same thing, guessing it's an underlying skia issue from what I can tell.

**Comment by mazunin-v-jb** [comment]
@chrisjenx many thanks!
I haven't reproduced the crash, but the memory warning was received many times, and memory consumption is very weird. We'll look at it

**Comment by chrisjenx** [comment]
Oh good, maybe a placebo, but 1.6.10 doesn't feel as smooth as 1.6.0 potentially related if it's over drawing, leaking, etc

**Comment by chrisjenx** [comment]
@mazunin-v-jb I will give 1.6.11 ago, I'm wondering if this was the cause of the OOM https://github.com/JetBrains/compose-multiplatform-core/pull/1355

**Comment by chrisjenx** [comment]
Tested 1.6.11, still crashing for me. Looks like it's something else :(

**Comment by chrisjenx** [comment]
Initial testing, looks like https://github.com/JetBrains/compose-multiplatform-core/pull/1390 fixed it, just running profiling now.

**Comment by chrisjenx** [comment]
So far looks like peak memory usage is 90mb on the demo project, no more OOM crashes, still churning memory but at least not exploding.
Will test on my main project then close if doesn't crash there.

**Comment by chrisjenx** [comment]
Looks like this is resolved

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4852">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
