### ISSUE TITLE
1.6.10 depends on pre-release versions of Kotlin

### ISSUE THREAD

**Issue by ZacSweers** [JetBrains/compose-multiplatform#4853]
**Describe the bug**

When building against 1.6.10, Gradle attempts to resolve a transitive `org.jetbrains.kotlin:kotlin-stdlib:2.0.20-dev-2651` stdlib artifact, suggesting this release was built against a pre-release of an upcoming Kotlin 2.0.20.

Repro: https://github.com/slackhq/circuit/pull/1006. https://github.com/slackhq/circuit/actions/runs/9199761361/job/25305121623?pr=1006

**Affected platforms**

- Desktop (Windows, Linux, macOS)

**Versions**
- Libraries:
  - foundation, ui, multiple artifacts
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): N/A
- OS architecture (x86 or arm64): N/A
- Device (model or simulator for iOS issues):  N/A
- JDK (for desktop issues):  21

**To Reproduce**
See above

**Expected behavior**
This library only publishes releases that depend on other release artifacts

**Comment by ZacSweers** [comment]
Actually nevermind, I think this is an issue with KSP. The error message was just misleading https://github.com/google/ksp/issues/1917

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4853">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
