### ISSUE TITLE
[Web] Uncaught runtime error in Material3 DatePicker (DisplayMode.Input) when enter incorrect date

### ISSUE THREAD

**Issue by denzap** [JetBrains/compose-multiplatform#4856]
**Describe the bug**
There is a crash (runtime error DateTimeException) when you use `material3.DatePicker` in `DisplayMode.Input` and enter incorrect date like `50/50/2024`. Only reproduces in Web, all other targets work correctly.

**Affected platforms**

- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.1, 1.6.10
- Kotlin version: 1.9.23, 2.0.0

**To Reproduce**
1. Run this code snippet:
   ```kt
   @Composable
   fun BugReproduction() {
       Column(Modifier.fillMaxWidth(), horizontalAlignment = Alignment.CenterHorizontally) {
           val state = rememberDatePickerState(initialDisplayMode = DisplayMode.Input)
           DatePicker(state = state)
       }
   }
   ```
2. Enter 50/50/2024 date
3. See error

**Expected behavior**
There should be no crash but the error tip like "Date does not match expected pattern" like on all other platforms

**Screenshots**
Web crash: 
<img width="600" alt="Screenshot 2024-05-23 at 11 16 28" src="https://github.com/JetBrains/compose-multiplatform/assets/6185534/f38a8984-ee77-49ce-86f6-e105dd72c689">

Desktop ok: 
<img width="600" alt="Screenshot 2024-05-23 at 11 17 15" src="https://github.com/JetBrains/compose-multiplatform/assets/6185534/1b2ebc7e-3b21-4bc0-9683-7cb4f583eeae">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4856">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
