### ISSUE TITLE
1.6.10 has broken the screenWidth calculation

### ISSUE THREAD

**Issue by hayk-kerobyan** [JetBrains/compose-multiplatform#4858]
**Describe the bug**
In a Kotlin/JS application 
`with(LocalDensity.current) {
        LocalWindowInfo.current.containerSize.width.toDp()
}` stopped working on mobile devices after I updated the kotlin to `2.0.0` and `org.jetbrains.compose` to `1.6.10`. While the Chrome web browser works as expected it doesn't work as expected on Android simulator and iOS device. Same for Safari on iOS. The root wrapper is `ComposeViewport`. This means, the checks to that decide whether to show web composable or mobile view composable are no longer working.

Source code: https://github.com/hayk-kerobyan/srcpassaporteaupair
The project is deployed at https://passaporteaupair.com/

**Affected platforms**

- Web (K/JS) mobile devices

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0

**To Reproduce**
1. Run this code snippet on a mobile device:
   ```kt
   val screenWidth = with(LocalDensity.current) {
        LocalWindowInfo.current.containerSize.width.toDp()
    }
   ```
2. See error the value returned by the function is not correct in mobile browsers.
or
1. Visit https://passaporteaupair.com/ on web browser(works as expected) and mobile devices(not working)

Web UI
<img width="1512" alt="Screenshot 2024-05-23 at 12 29 32" src="https://github.com/JetBrains/compose-multiplatform/assets/36127475/e70dff98-1d09-41ea-a362-5d0756c83a98">

Web Adaptive UI(when the chrome browser's width is lessened)
<img width="501" alt="Screenshot 2024-05-23 at 12 29 22" src="https://github.com/JetBrains/compose-multiplatform/assets/36127475/53661198-fac9-41f2-abd0-32d482867c6d">

Android(must get the correct width and use the adaptive UI)
<img width="501" alt="Screenshot_20240523_122948" src="https://github.com/JetBrains/compose-multiplatform/assets/36127475/642bc9b7-0339-41cd-8f12-01a28df9f01b">

iOS
<img width="501" alt="IMG_0E44F731523E-1" src="https://github.com/JetBrains/compose-multiplatform/assets/36127475/3f02c88a-e707-4c48-8890-fac41eec5de3">

**Comment by mazunin-v-jb** [comment]
@Schahen, could you please look at it?

**Comment by hayk-kerobyan** [comment]
Hey @Schahen jan, any idea what can be the reason? Also, as you can see from the 3rd screenshot of Andrpoid phone Chrome the tip part is cut(the website is not scrolled, it shows its top). Can't release unless the responsive UI works correct. This is the only blocker.

**Comment by Schahen** [comment]
@hayk-kerobyan ջան we'll do our best to fix this ASAP, will keep you posted

**Comment by Schahen** [comment]
@hayk-kerobyan it looks like I need additional information. To be 100% sure I'm looking into the same issue that is actually reported. So, first of all - 
  * issue is about the js target (not the wasm one)?
  * what exactly happens at step "See error the value returned by the function is not correct in mobile browsers.
or" - is it a runtime error one can see in console or an error in that sense that application get incorrect dimensions?
 * which browsers are affected on mobile?
 
  I'm checking https://passaporteaupair.com/  but failing to see something that's wrong

**Comment by hayk-kerobyan** [comment]
1. Target is JS(screenshot attached, [source code](https://github.com/hayk-kerobyan/srcpassaporteaupair/blob/main/composeApp/build.gradle.kts))
 
2. To make things easier:
With the following code I am getting the screen width **979.dp** on Pixel 6A, however, running a native android application on the same device shows that the screen width is **411.dp** which must be the correct width of the screen(device)
<img width="529" alt="Screenshot 2024-05-27 at 12 02 21" src="https://github.com/JetBrains/compose-multiplatform/assets/36127475/9d04d57c-addb-40dd-b673-8d874c59c90b">
<img width="603" alt="Screenshot 2024-05-27 at 12 06 05" src="https://github.com/JetBrains/compose-multiplatform/assets/36127475/1ec436bb-8597-47a0-b7f1-0eaf2f460318">
<img width="359" alt="Screenshot 2024-05-27 at 12 06 15" src="https://github.com/JetBrains/compose-multiplatform/assets/36127475/3bad0b1a-9cc9-4005-bfb7-a4b09338a9a2">
**Android native application code that returns 411.dp**:
<img width="594" alt="Screenshot 2024-05-27 at 11 57 48" src="https://github.com/JetBrains/compose-multiplatform/assets/36127475/b3644fe5-b063-4ddb-bb62-42e5bdc0d150">

3. Browsers affected:
- Android Chrome
- Android Firefox
- iOS Chrome
- iOS Safari


In addition, for some reason the screen is shifted up only on Android Chrome (as if there is offsetY = -300.dp) which makes the top part of the composable be cut.

**Comment by hayk-kerobyan** [comment]
Btw, the density from `LocalDensity.current.density` method is returned correct(although there is a small difference: for the same screen android Chrome and Firefox returned 2.625 and 2.608 respectively)

However, `LocalWindowInfo.current.containerSize.width` returned  **2572 px** on Android Chrome and **2556 px** on Android Firefox while the native android application returned **1080 px** using `currentWindowSize().width` method from androidx.compose.material3.adaptive:adaptive library.

Apparently the problem is in the width value of this method `LocalWindowInfo.current.containerSize.width`. The browser container itself seems to work correct as the content composable doesn't go beyond the screen (to the right of the screen) except the only case mentioned in my previous message for android Chrome.

**Comment by hayk-kerobyan** [comment]
@Schahen jan, my bad I modified the index.html to the following and it started to work. Aparently it's not an issue on Compose multiplatform, it's just a matter of the `index.html` config. The top part of the website is cut on Chrome when desktop mode is being enabled, however this is an another issue, for which I will try to find a sollution. Closing the issue. Sorry for inconvenience.
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Passaporte AuPair</title>
    <style>
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            overflow: hidden;
        }
        #root {
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: #f0f0f0;
        }
    </style>
    <script src="skiko.js"></script>

</head>
<body>
<div id="root"></div>
<script src="composeApp.js"></script>
</body>
</html>
```

**Comment by Schahen** [comment]
@hayk-kerobyan ջա՜ն Thank you very much for investigating! It's actually still the problem of our API that people keep in mind all this meta/viewport related issues. We'll try to come up with something that will make developers live easier in that aspect.
