### ISSUE TITLE
Need "Start after install complete" option in configuration of windows installer

### ISSUE THREAD

**Issue by Mina-1316** [JetBrains/compose-multiplatform#4862]
Hello community!

I'm currently using Kotlin Multiplatform to provide dedicated purpose softwares, and I've implementated an automatic software update by just executing the installer generated by the options below:
```kotlin
compose.desktop.nativeDistributions {
            windows {
                perUserInstall = true
                dirChooser = false
                upgradeUuid = properties["application.installer.updateid"] as? String
                exePackageVersion = packageVersion
                msiPackageVersion = packageVersion
                shortcut = true
                iconFile.set(file("$projectDir/assets/icon.ico"))
            }
}
```

By this options, Installer will automatically update the software, without user operation, with creating shortcuts.
However, I want to make application automatically start after install is done.

Is there any options to make it done?
maybe this issue is related to this: https://github.com/JetBrains/compose-multiplatform/issues/1972

**Comment by Mina-1316** [comment]
btw, maybe seperatable issue, installer's `intallationPath` is not applied when `dirChooser = false`...

Is it intended behavior?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4862">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
