### ISSUE TITLE
Font is not updated to the new font resource

### ISSUE THREAD

**Issue by PhilipDukhov** [JetBrains/compose-multiplatform#4863]
**Describe the bug**
`org.jetbrains.compose.resources.Font` composable is ignorant to updated `resource` value.

This is Android only issue, but it's not reproduced on regular compose - it's related to using shared resources from common part.

**Affected platforms**
- Android

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): Android emulator

**To Reproduce**
1. Put fonts in `commonMain/composeResources/font/` folder, so `Res.font` is autogenerated.
2. Run this code snippet:
    ```kt
    var flag by remember {
        mutableStateOf(false)
    }
    Column {
        Text(
            "hey",
            fontFamily = FontFamily(Font(if (flag) Res.font.HelveticaNeueMedium else Res.font.COMICSANS, FontWeight.Normal))
        )
        Switch(checked = flag, onCheckedChange = { flag = it })
    }
    ```
3. Click on Switch

**Expected behavior**
Text font is changed

**Additional context**
As you can see in the [source code](https://github.com/JetBrains/compose-multiplatform/blob/b32350459acceb9cca6b9e4422b7aaa051d9ae7d/components/resources/library/src/androidMain/kotlin/org/jetbrains/compose/resources/FontResources.android.kt#L9-L13) of `org.jetbrains.compose.resources.Font` composable, it remembers result of `getResourceItemByEnvironment` and doesn't update it in case new `resource` value is passed.

On other platforms it's not an issue because `resource` value is [passed](https://github.com/JetBrains/compose-multiplatform/blob/b32350459acceb9cca6b9e4422b7aaa051d9ae7d/components/resources/library/src/skikoMain/kotlin/org/jetbrains/compose/resources/FontResources.skiko.kt#L33-L41) into `rememberResourceState`.

Suggested fix is passing `resource` to `remember`:
```kotlin
val path = remember(environment, resource) { resource.getResourceItemByEnvironment(environment).path }
```

Related [stackoverflow](https://stackoverflow.com/questions/78527695/multiplatform-compose-state-does-not-update-font-change-in-text-on-android-on-i?noredirect=1#comment138441242_78527695) question.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4863">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
