### ISSUE TITLE
Desktop. Native distribution. `intallationPath` doesn't work if `dirChooser` = false

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4868]
from https://github.com/JetBrains/compose-multiplatform/issues/4862#issuecomment-2129026290

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4868">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
