### ISSUE TITLE
Reduce variety of Preview annotations

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#4869]
We have 3 Previews:
- `androidx.compose.ui.tooling.preview.Preview`
  - for androidMain
  - supported in Android Studio/IDEA
  - `build.gradle` should have `implementation(compose.preview)`
- `androidx.compose.desktop.ui.tooling.preview.Preview`
  - for desktopMain
  - supported in Android Studio/IDEA
  - needed a separated installed [IDE plugin](https://plugins.jetbrains.com/plugin/16541-compose-multiplatform-ide-support)
  - is available by default, no need extra lines in `build.gradle`
- `org.jetbrains.compose.ui.tooling.preview.Preview`
  - for commonMain/androidMain/desktopMain
  - supported by Fleet
  - `build.gradle` should have `implementation(compose.components.uiToolingPreview)`

We should reduce the count, and make consistent guidelines/templates.

**Comment by igordmn** [comment]
Sub-issue: project created by kmp.jetbrains.com doesn't support Preview in IDEA/Android Studio

**Comment by ellet0** [comment]
I agree that we wither have to use the Android one for compability or the one from Jetbrains compose multiplatform as it's more future proof, Kotlin is not limited to Android and still many tools and JVM libraries still identified as Android library even though some of them work independently of Android, let's say you want to develop a server or desktop app, it doesn't make much sense to have Android word in the imports, in the JAR content and in the code in general, I understand it's only naming for compability and Compose multiplatform is inspired by Jetpack compose but that make confusion for beginners and even advance developers from other frameworks and tools, usually they won't go to the issues tab or in the docs and investigate why we have Android imports, we would like to see Kotlin more independent from Android and Androidx

Thank you.

**Comment by akexorcist** [comment]
Preview an UI in `commonMain` on IntelliJ IDEA that is what I want.

**Comment by malbanese** [comment]
+1 Getting multiplatform compose previews to work in different places is currently a hassle.

**Comment by igordmn** [comment]
A report in Kotlin IDEA plugin tracker: https://youtrack.jetbrains.com/issue/KTIJ-30072

**Comment by malbanese** [comment]
For anyone else who finds this, I've found a solution that fits my needs while waiting for better preview support in Compose Multiplatform and Android Studio.

I was able to use the new [Compose Preview Screenshot Testing](https://gist.github.com/malbanese/6f015e0390ee767c4bc0acb87f697755) library inside fully KMP / Compose multiplatform modules. 

Previews work inside Android Studio under the proper package, and this (mostly) solves my screenshot testing needs as well. Obviously there are some requirements like putting previews in the `screenshotTesting` source directory, require an Android target with AGP 8.5.0, and only being able to pull from the common/android sources.

Here's the Gradle convention plugin I'm using to apply to the relevant modules:
https://gist.github.com/malbanese/6f015e0390ee767c4bc0acb87f697755

**Comment by igordmn** [comment]
> Preview an UI in commonMain on IntelliJ IDEA that is what I want.

Let's move this into a separate task: https://github.com/JetBrains/compose-multiplatform/issues/5078

**Comment by igordmn** [comment]
Parent task: https://github.com/JetBrains/compose-multiplatform/issues/2045

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4869">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
