### ISSUE TITLE
Being able to create a ComposePanel with vsync disabled

### ISSUE THREAD

**Issue by MohamedRejeb** [JetBrains/compose-multiplatform#4870]
Hi,
I've been discussing the current latency issue with @igordmn , especially when working with inputs. One of the possible solutions to reduce latency is to disable vsync, but it's not a good option because it will make the program slower. 
So Igor suggested having 2 panels one for ui (with vsync) and one for drawing (without vsync).
We will need the ability to configure `ComposePanel(skiaLayerProperties = SkiaLayerProperties(isVsyncEnabled = false))`

Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4870">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
