### ISSUE TITLE
`Dialogs` are not rendered as expected when used inside a `ImageComposeScene`

### ISSUE THREAD

**Issue by alexstyl** [JetBrains/compose-multiplatform#4875]
**Describe the bug**
`Dialog`s are normally rendered on the center of the screen on Android. On Compose Desktop they are rendered in the center of a `Window`. However, when used within a `ImageComposeScene` the dialog is placed on the top left corner of the scene instead.

Composable content:

```kotlin
@Composable
fun Content() {
    Box(Modifier.fillMaxSize().background(Color.White), contentAlignment = Alignment.Center) {
        BasicText("Content")
        Dialog(onDismissRequest = { /* TODO */ }) {
            Box(Modifier.fillMaxSize().border(1.dp, Color.Red), contentAlignment = Alignment.BottomEnd) {
                Box(Modifier.background(Color.White).padding(8.dp)) {
                    BasicText("Dialog Content")
                }
            }
        }
    }
}
```

Using it in a window like this:

```kotlin
fun main() = singleWindowApplication {
    Content()
}
```

renders the following:

<img width="912" alt="window" src="https://github.com/JetBrains/compose-multiplatform/assets/1665273/3c957db5-7d4a-4ea5-a1fe-d412baf9fadf">

However, when used inside of a `ImageComposeScene` using this code:

```kotlin
fun main() = application {
    ImageComposeScene(width = 1200, height = 800) {
        Content()
    }.use { scene ->
        scene.render()
        val directory = File(".")
        directory.mkdirs()
        val fileName = "test.png"

        val file = File(directory, fileName)

        val image = scene.render(1000)
        val data = image.encodeToData()!!

        Files.write(file.toPath(), data.bytes)
        Desktop.getDesktop().open(File(file.absolutePath))
    }
}
```
the output image has the dialog on the top left corner like this:
![test](https://github.com/JetBrains/compose-multiplatform/assets/1665273/dcc77617-cc42-4f30-b67f-483b1d7d3591)

**Affected platforms**
- Desktop: macOS

**Versions**
kotlin = "2.0.0-RC1"
compose = "1.6.10"

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4875">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
