### ISSUE TITLE
Jetsnack images are not loading

### ISSUE THREAD

**Issue by pkdhankher** [JetBrains/compose-multiplatform#4884]
If the bug is in Android, IOS, Web and Desktop App, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Describe the bug**
Jetsnack images are not loading, Seems like removed from the source.

**Affected platforms**
- Desktop (Windows, Linux, macOS)
- iOS
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library 

**To Reproduce**
1. Run anu module Android/IOS/Web
2. Images are not loading
3. IOS app crashing

**Expected behavior**
Images are not loading on all the platforms

**Screenshots**
![Screenshot 2024-05-28 at 10 55 58 AM](https://github.com/JetBrains/compose-multiplatform/assets/22525435/1559400a-589b-42bc-98cf-b75186328ac9)

**Additional context**
N/A

**Comment by terrakok** [comment]
Image urls are broken in the original repo too: https://github.com/android/compose-samples/blob/main/Jetsnack/app/src/main/java/com/example/jetsnack/model/Snack.kt

For example: https://source.unsplash.com/pGM4sjt_BdQ

<img width="918" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/3532155/e87a2206-c67d-41ed-bf8d-048f6033ca25">
