### ISSUE TITLE
[Gradle] tryGetSkikoRuntimeIfNeeded() eagerly resolves KMP runtime configuration on task creation

### ISSUE THREAD

**Issue by Tapchicoma** [JetBrains/compose-multiplatform#4886]
**Describe the bug**

We've got [following report](https://youtrack.jetbrains.com/issue/KT-68476) in Kotlin issues where `jvmRuntimeClasspath` configuration could not be further modified as it was already resolved:
```
Cannot change dependencies of dependency configuration ':micro_utils.android.pickers:jvmMainImplementation' after it has been included in dependency resolution.
```

The problem comes from both user repository and JB Compose Gradle plugin:
- user repository use Gradle `tasks.whenTaskAdded()` API [here](https://github.com/InsanusMokrassar/MicroUtils/blob/fa8a5bcd97d500c7c3d0ac40a7d00e7914559191/build.gradle#L35) which triggers eager tasks creation.
- The issue above triggers eager creation of Compose `AbstractConfigureDesktopPreviewTask` task which itself triggers `tryGetSkikoRuntimeIfNeeded()` method. Inside this method `previewClasspath` `FileCollection` [is resolved](https://github.com/JetBrains/compose-multiplatform/blob/7131b5b9a665e8b1d72aabc9476947650145c11e/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/preview/tasks/AbstractConfigureDesktopPreviewTask.kt#L89) which prevents further configuration modification (adding new dependencies)

**Affected platforms**
- All

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version:  2.0.0
- Gradle: 8.7

**To Reproduce**
1. Clone https://github.com/InsanusMokrassar/MicroUtils repository
2. Checkout `0.21.0` branch
3. Run `./gradlew :micro_utils.android.pickers:help -i -s`

**Expected behavior**

Configurations should not be resolved on Gradle configuration phase.

**Comment by InsanusMokrassar** [comment]
[Commit](https://github.com/InsanusMokrassar/MicroUtils/pull/451/commits/46e16e3fc89fc522f5c8c4ce798bfeb87d6bdb8c) with incorrect work of plugin

**Comment by InsanusMokrassar** [comment]
Hello, could you say if there is some progress on this issue? It is currently blocking me from upgrade allmy projects up to kotlin 2.0 and the lates compose :(

**Comment by eymar** [comment]
@InsanusMokrassar the proper fix is in progress. 

In the meantime, your project doesn't seem to use js legacy target. So you can remove this part:
```
 tasks.whenTaskAdded { task ->
            if(task.name == "jsLegacyBrowserTest" || task.name == "jsLegacyNodeTest") {
                task.enabled = false
            }
        }
```

and it works.

**Comment by InsanusMokrassar** [comment]
> @InsanusMokrassar the proper fix is in progress.
> 
> In the meantime, your project doesn't seem to use js legacy target. So you can remove this part:
> 
> ```
>  tasks.whenTaskAdded { task ->
>             if(task.name == "jsLegacyBrowserTest" || task.name == "jsLegacyNodeTest") {
>                 task.enabled = false
>             }
>         }
> ```
> 
> and it starts to work.

Your advice working, thank you :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4886">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
