### ISSUE TITLE
Cannot change preferredStatusBarStyle on ComposeUIViewController

### ISSUE THREAD

**Issue by chokokatana** [JetBrains/compose-multiplatform#4889]
The usual way to [change the status bar style on iOS is to override the `var preferredStatusBarStyle`](https://stackoverflow.com/a/70626646/172690):
```
override var preferredStatusBarStyle: UIStatusBarStyle {
     return .lightContent
}

override func viewDidLoad() {
    super.viewDidLoad()

    setNeedsStatusBarAppearanceUpdate()
}
```
However, `ComposeUIViewController()` returns a final UIViewController and there is no way to change this value. Maybe `ComposeUIViewControllerConfiguration` could _grow_ extra nullable blocks that could be implemented to provide extra customization.

**Comment by elijah-semyonov** [comment]
I'll forward this API, as a temporary workaround, you can wrap your ComposeUIViewController into UIViewController with overriden properties

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4889">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
