### ISSUE TITLE
Annotated string with gradient spans is not rendered on skiko targets

### ISSUE THREAD

**Issue by gleb-skobinsky** [JetBrains/compose-multiplatform#4897]
**Describe the bug**
Gradients in annotated strings are not rendered.

**Affected platforms**
- iOS
- Other skiko targets might be affected, too

**Versions**
- Libraries:
- Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): iOS 17.2
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iPhone 15

**To Reproduce**
1. Run this code snippet:
```kt
@Composable
@Preview
fun App() {
    MaterialTheme {
        val annotatedString = remember {
            buildAnnotatedString {
                pushStyle(SpanStyle(fontSize = 56.sp))
                withStyle(SpanStyle(brush = textGradient)) {
                    append("Text with gradient")
                }
                withStyle(SpanStyle(color = Color.Black)) {
                    append(", and without")
                }
            }
        }
        Box(Modifier.fillMaxSize(), Alignment.Center) {
            Text(annotatedString, textAlign = TextAlign.Center, lineHeight = 64.sp)
        }
    }
}
```
2. On android the output is ok:
![photo_2024-05-30 12 02 57](https://github.com/JetBrains/compose-multiplatform/assets/90451272/d8909f68-5164-4fb6-8ed5-bef03da0f6eb)

On iOS the span with gradient is not visible:
![photo_2024-05-30 12 02 55](https://github.com/JetBrains/compose-multiplatform/assets/90451272/b6583bf3-56e9-4cbd-8665-7ef5c61bd06a)

**Expected behavior**
Same rendering for all platforms.

You can reproduce the issue with this repo: https://github.com/gleb-skobinsky/BugReport

**Comment by elijah-semyonov** [comment]
Reproduced on all skiko-based targets indeed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4897">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
