### ISSUE TITLE
Support Compose Animation version 1.7.0-Beta01

### ISSUE THREAD

**Issue by master-lzh** [JetBrains/compose-multiplatform#4898]
The animation package for Android has added new features [Shared Elements](https://developer.android.com/develop/ui/compose/animation/shared-elements) in **androidx.compose.animation:animation:1.7.0-beta01**, this feature is very useful, please support these new features in CMP!

**Comment by MatkovIvan** [comment]
Available in the latest dev build

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4898">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
