### ISSUE TITLE
[iOS] Composable doesn't recompose when screen with child controller orientation changes

### ISSUE THREAD

**Issue by slartus** [JetBrains/compose-multiplatform#4899]
**Describe the bug**
Composable doesn't recompose when screen with child controller orientation changes.
UIViewController add child compose UIViewController, rotate.

**Affected platforms**
- iOS

**Versions**
compose from 1.5... to actual versions

Using the https://kmp.jetbrains.com/ (30.05.2024)

changed just ComposeView.swift

**To Reproduce**
https://github.com/slartus/IosRotationTest
1. start project on ios target
2. rotate device

![image](https://github.com/JetBrains/compose-multiplatform/assets/1107015/cdf2ef01-d683-45c9-b97c-114c340f562d)
![image](https://github.com/JetBrains/compose-multiplatform/assets/1107015/22c8d1e5-d04a-49bc-a758-8688d6b56304)

**Comment by slartus** [comment]
temporary fix:
https://github.com/slartus/IosRotationTest/commit/77617990642678b5cdd6676ad630188737305857

**Comment by elijah-semyonov** [comment]
Hi, the repository you linked is private.
Can you make it public or post the code snippet that contains the repro?
I can't reproduce it.

**Comment by slartus** [comment]
Done

**Comment by slartus** [comment]
ok, thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4899">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
