### ISSUE TITLE
Scaffold scrolls improperly when keyboard opened on iOS

### ISSUE THREAD

**Issue by oblakr24** [JetBrains/compose-multiplatform#4902]
**Describe the bug**

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): Mac Sonoma 14.4.1
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iPhone 15 Simulator

**To Reproduce**
1. Prepare a minimum Scaffold setup (Material3 imports)
2. Click on the text field
3. Observe as the keyboard opens, but the top part of the scaffold (top bar and the top couple of items) are obscured and cannot be scrolled back down

**Expected behavior**
The content should be scrollable to the top item, and the top bar should be pinned at the top.
Works as expected on Android.

**Screenshots**

![Simulator Screenshot - iPhone 15 - 2024-05-30 at 18 46 11](https://github.com/JetBrains/compose-multiplatform/assets/32245831/f9f64cd8-81ba-4924-a3a2-b9fa1be46614)
![Simulator Screenshot - iPhone 15 - 2024-05-30 at 18 45 55](https://github.com/JetBrains/compose-multiplatform/assets/32245831/470c4900-ec6f-4727-a4dd-2d1ce77c6fb6)

**Minimum reproducible example**

```
 ComposeUIViewController(configure = {
        this.onFocusBehavior = OnFocusBehavior.FocusableAboveKeyboard
    }) {
        Scaffold(
            topBar = {
                Text("TOP BAR")
            },
            content = { paddingValues ->
                val lazyListState = rememberLazyListState()

                LazyColumn(
                    state = lazyListState,
                    modifier = Modifier.padding(paddingValues).fillMaxWidth()
                ) {

                    items(60, key = { it.toString() }, itemContent = { idx ->
                        Text("Item $idx")
                    })
                }
            },
            bottomBar = {
                TextField(value = "", onValueChange = {

                })
            }
        )
    }

```

Swift code:

```
struct ComposeView: UIViewControllerRepresentable {

    func makeUIViewController(context: Context) -> UIViewController {
        MainViewControllerKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}

struct ContentView: View {
    
    var body: some View {
        ComposeView()
            .ignoresSafeArea(.keyboard, edges: .all)
    }
}

```

**Comment by ASalavei** [comment]
What `android:windowSoftInputMode` was used in your activity manifest file?
`OnFocusBehavior.FocusableAboveKeyboard` corresponds to the `adjustPan`, and it works as intended.
it seems you're looking for `adjustResize` behaviour of the compose scene, which currently does not have analogs in SDK for iOS (not supported for now).
I would recommend to use `WindowInsets.ime` in combination with `OnFocusBehavior.DoNothing` to reach desired behaviour.

**Comment by oblakr24** [comment]
Thank you, the combination recommended did the job. I suppose this can be closed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4902">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
