### ISSUE TITLE
ShaderBrush#createShader state reads do not invalidate Text composable

### ISSUE THREAD

**Issue by halilozercan** [JetBrains/compose-multiplatform#4903]
**Describe the bug**
Brush instances created using the abstract `ShaderBrush` class, does not animate when applied on Text.

**Affected platforms**
Only tested on;
- Desktop (Windows, Linux, macOS)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10

**To Reproduce**
1. Run this code snippet:

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/integration-tests/foundation-demos/src/main/java/androidx/compose/foundation/demos/text/BrushDemo.kt;l=204-233

```
fun AnimatedBrush() {
    val infiniteTransition = rememberInfiniteTransition()
    val radius by infiniteTransition.animateFloat(
        initialValue = 100f,
        targetValue = 300f,
        animationSpec = infiniteRepeatable(
            animation = tween(durationMillis = 1000, easing = LinearEasing),
            repeatMode = RepeatMode.Reverse
        )
    )
    val brush = remember {
        // postpone the state read to shader creation time which happens during draw.
        ShaderBrush { size ->
            RadialGradientShader(
                center = size.center,
                radius = radius,
                colors = RainbowColors,
                colorStops = RainbowStops,
                tileMode = TileMode.Mirror
            )
        }
    }
    Text(
        text = loremIpsum(wordCount = 29),
        style = TextStyle(
            brush = brush,
            fontSize = 30.sp
        )
    )
}
```

**Expected behavior**
Expecting text to have an animated brush coloring.

**Additional context**

Android handles this by creating the shader in a `derivedStateOf`. This way any state read that happens in `createShader` invalidates the derived state and only re-runs the draw phase. Otherwise devs need to change the brush instance for every animation frame which can get very costly due to unnecessary recomposition.

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-text/src/androidMain/kotlin/androidx/compose/ui/text/platform/AndroidTextPaint.android.kt;l=111-143

**Comment by m-sasha** [comment]
Looks like we need to apply (https://github.com/androidx/androidx/commit/16311966039d5d0cd98652b333059f1741bed564) to `SkiaTextPaint` where it says `// Copied from AndroidTextPaint.`

**Comment by MatkovIvan** [comment]
Unfortunately the fix from mentioned commit won't work for CMP because unlike Android we do not control `Paint` state during paragraph redrawing - it's fulling inside C++/skia. So to apply such changes, currently it requires full re-layout/re-creation of skia's paragraph. Even with a few layers of caching that we currently have, I doubt that it will animate smoothly. To properly do this, global changes in text rendering/layout are required.

**Comment by rock3r** [comment]
😭

**Comment by MatkovIvan** [comment]
Adopted it with re-layouting in https://github.com/JetBrains/compose-multiplatform-core/pull/1395

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4903">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
