### ISSUE TITLE
Material 3 depends on some Material 2 modules

### ISSUE THREAD

**Issue by EchoEllet** [JetBrains/compose-multiplatform#4908]
This is not a bug but will cause other unrelated bugs to other issues

The Material 3 module depends on some Material 2 modules like `material-icons-core` and `material-ripple`, refer to [Compose Multiplatform Core](https://github.com/JetBrains/compose-multiplatform-core/) GitHub repository, in [material3/material3/build.gradle#L104](https://github.com/JetBrains/compose-multiplatform-core/blob/1694668f0d423babe94805bba603e087bd5ca943/compose/material3/material3/build.gradle#L104)

```groovy
api(project(":compose:material:material-icons-core"))
api(project(":compose:material:material-ripple"))
```

While this may sound like not an issue as it depends on the individual perspective, it could cause other issues that are not directly related to this

Like on **Compose Desktop**

- #497
- #4883 
- https://github.com/JetBrains/compose-multiplatform/issues/4883#issuecomment-2142445581
- #4035

The desktop release version that is created by the Compose desktop Gradle plugin will Proguard, and currently with the current default Proguard rules, it seems there is an issue when using Material 3 in the release version (with Proguard), I managed to get it working with a workaround and I have to not exclude Material 2 from Material 3 in the comment mentioned above, take a look at the issue [#4883](https://github.com/JetBrains/compose-multiplatform/issues/#4883) or other related issues and you will notice it's quite related to this feature request

A solution would be to have a separate Gradle module like `material-shared` and extract the shared code between Material 2 and 3 to use it in this module, this can be achieved without a breaking change, which could help fixing #4883 and #497 but other specific changes is needed to fix them and related issues

**Comment by ellet0** [comment]
> It should be reported to Google issue tracker. It's not the change introduced by this fork and we're not going to change module structure without Google's AOSP repo.

I see, regarding using Material 3 without 2 or something else like Cupertino.

The module `compose.desktop.currentOs` doesn't seem to be from Google, it require Material 2 unless it explicitly excludes it. On Google Android, you can either use Material 2, 3, or both.

Which is not the same module structure as Google.

**Comment by MatkovIvan** [comment]
`compose.desktop.currentOs` is different thing, yes. And it's tracked in #497

But in this issue description you wrote not about this gradle plugin getter, but about `material-icons-core` and `material-ripple`. And [it's from AOSP](https://github.com/androidx/androidx/blob/2a0023d8e74ad300ea1ab11d12944d279a6052c8/compose/material3/material3/build.gradle#L49-L50)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4908">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
