### ISSUE TITLE
String resource parsing works differently when compared to Android

### ISSUE THREAD

**Issue by Thomas-Vos** [JetBrains/compose-multiplatform#4910]
**Describe the bug**
There are some differences with string parsing with compose when compared to official string resources on Android:

## 1. Format args

It is possible to pass format args to `org.jetbrains.compose.resources.stringResource`. Great, but it doesn't work with:
- `%s`
- `%d`

On Android this does work. Example string:
```xml
<string name="last_updated_s">Last updated: %s</string>
```
Usage:
```kt
stringResource(R.string.last_updated_s, "test")
```
Expected output:
```
Last updated: test
```

## 2. Newlines

Example string:
```xml
<string name="test">Test1
\nTest2
\nTest3</string>
```
Expected output:
```
Test1
Test2
Test3
```
There are additional newlines in the output which is incorrect when compared to Android. On Android, a simple newline (not `\n` but literally a new line) is ignored.

## 3. Backslashes

Here are two strings:
```xml
<string name="test1">Test \"Test\" Test</string>
<string name="test2">Test \'Test\' Test</string>
```
On Android the output would be:
```
Test "Test" Test
Test 'Test' Test
```
But with compose the output still contains the backwards slashes.

**Affected platforms**
All

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0

**Expected behavior**
Same behaviour as official Android strings.

**Comment by terrakok** [comment]
> There are some differences with string parsing with compose when compared to official string resources on Android

Yes. It is by design

**Comment by terrakok** [comment]
1) You are suppose to use Res class for that and a slightly different format
https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html#string-templates
2) Because you do have new lines and `\n` symbols in you text
https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html#simple-strings
3) Because you are not suppose to use backslashes for that, just have a text in a clean form

**Comment by Thomas-Vos** [comment]
Alright, but in my project the strings are imported by translation services. They use the Android format. That compose works differently does make it more difficult.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4910">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
