### ISSUE TITLE
Compose on iOS resulting huge memory and CPU consumption resulting in ios app crashing, phone warming and freezing issues

### ISSUE THREAD

**Issue by sureshmaidaragi1919** [JetBrains/compose-multiplatform#4912]
### **Describe the problem**
In our project, we are seeing two blocker issues,
High CPU and Memory consumption on iOS app due to which we have halted the project development until it is resolved. Videos attached here is from our code base, and code base attached for sample demo to reproduce the issue.

#### Memory consumption issue

We are loading simple Bottomsheet dialog around 10 to 15 times on screen, on each instance it results in 3MB increase and 3MB is not releasing at all even if we come back from the screen

#### CPU consumption issue:
When a particular job is done by app, immediately CPU should return to 0-1%, which is not happening.
in our usecase  CPU utlisiation going up to 180% and returning to ~104% and staying in ~104% for around 1min later coming back to 0-1% if app is idle.

- What specific issue did you encounter? 
high CPU usage and memory leaks
- Have you noticed any patterns or specific circumstances under which the problem occurs?
**Memory issue:**
Yes, whenever new screens load memory being added which is not releases when user comes out from that screens.
If we close and open 1screen around 15 times there is an increasing memory graph being drawn which is resulting in huge memory consumption, and grows to extent and system crash's the app in case of iOS.
**CPU issue :** 
Utilise CPU is not releasing up to 30 sec to 1min, resulting in a phone heating issue.

**Affected platforms**
Select one of the platforms below:
- iOS

If the problem is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version:  2.0.0
- Compose Multiplatform version:  1.6.10
- OS version(s) (required for Desktop and iOS issues):  All version
- OS architecture (x86 or arm64):  Both

**Sample code**
[Sample project code link](https://drive.google.com/file/d/1PZ8nz-Cc4-Qx5jMjVgsxdvBakRCbTlnn/view?usp=sharing)

**Reproduction steps**
Please provide a detailed step-by-step guide on how to reproduce the issue you are experiencing.

**Video**
[video link](https://drive.google.com/file/d/1sDauxVmTL1KHCa6EFaMKjjuTD6yAqjDc/view?usp=sharing)

**Profiling data**
Please provide any relevant profiling data that might be helpful. This could include information like FPS, memory usage, CPU time, or any other data that could provide insight into the performance issue.
![Screenshot 2024-05-31 at 3 16 10 PM](https://github.com/JetBrains/compose-multiplatform/assets/28126457/413eb3dd-c1cf-4d6f-ade0-bcaaf7ac8be5)
![Screenshot 2024-05-31 at 6 13 42 PM](https://github.com/JetBrains/compose-multiplatform/assets/28126457/59450d08-9f4b-44d8-bed0-830bc00965ee)
![Screenshot 2024-05-31 at 8 08 31 PM](https://github.com/JetBrains/compose-multiplatform/assets/28126457/93859c53-4d52-4ce5-a49b-91681be8395e)

**Additional information**

**Comment by terrakok** [comment]
Hi. Thank you for the report. We will investigate it soon and will ask you more information if it is required

**Comment by elijah-semyonov** [comment]
@sureshmaidaragi1919 
> turning to ~104% and staying in ~104% for around 1min

Can you make a screenshot of _all the active threads_ when this happens? I can't reproduce it.

**Comment by sureshmaidaragi1919** [comment]
here it is @elijah-semyonov https://drive.google.com/file/d/1-pEe6-UZcy6NGJLgrbNgNb7LdEZCIS3B/view?usp=sharing

**Comment by sureshmaidaragi1919** [comment]
There is memory consumption issue that still persists on compose 1.6.10, when I navigate between two simple screens, it does not completely drop the retained memory when I move back from the screen.

Is there any workaround for this?

**Comment by terrakok** [comment]
- To file a new issue
- To attach a small reproducer
- To attach your logs

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4912">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
