### ISSUE TITLE
WkWebView inside a UIKit View is not displayed when height is fixed and used inside a LazyColumn Item

### ISSUE THREAD

**Issue by Vaibhav2002** [JetBrains/compose-multiplatform#4913]
**Describe the bug**
When using a WkWebView inside a UIKit view without setting a fixed height using `Modifier.height()` inside a LazyColumn Item, it is not displayed
When a fixed height it set, it is displayed.

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0

**To Reproduce**
1. Run this code snippet:
   ```kt
    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        verticalArrangement = Arrangement.spacedBy(8.dp),
        contentPadding = PaddingValues(16.dp),
    ) {
        items(30, contentType = { it }) {
            ListItem(modifier = Modifier.fillParentMaxWidth())
        }
    }

    @Composable
    fun ListItem(modifier: Modifier = Modifier) {
        Column(modifier = modifier, verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Box(modifier = Modifier.fillMaxWidth().background(Color.Red).height(30.dp))
            Box(modifier = Modifier.fillMaxWidth().background(Color.Green).height(64.dp))
            NativeWebView(
                url="https://youtube.com"
                modifier = Modifier.fillMaxWidth(),
            )
            Box(modifier = Modifier.fillMaxWidth().background(Color.Blue).height(30.dp))
        }
    }
    
    @OptIn(ExperimentalForeignApi::class)
    @Composable
    actual fun NativeWebView(url: String, modifier: Modifier) {
        UIKitView(
            factory = {
                val config =
                    WKWebViewConfiguration().apply {
                        allowsInlineMediaPlayback = true
                        defaultWebpagePreferences.allowsContentJavaScript = true
                        preferences.javaScriptEnabled = true
                    }
                WKWebView(
                    frame = CGRectZero.readValue(),
                    configuration = config,
                ).apply {
                    setOpaque(false)
                }
            },
            modifier = modifier,
            onRelease = {},
            update = {
               it.loadRequest(NSMutableURLRequest.requestWithURL(URL = NSURL(string = url)))
            }
        )
    }
   ```

**Screenshots**
### When fixed height `Modifier.height(400.dp)` applied to `NativeWebView`, It looks fine
<img width="453" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/64367926/840f9943-d2b2-4edc-9811-d281570ca145">

### Without fixed height:
<img width="453" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/64367926/c7a663cb-d45b-433b-9491-e78939265d4e">

## **Additional context**
My use case is to embed Tweets, Reddit Post, Yt Videos and other embeddable html in a LazyColumn Item

**Comment by elijah-semyonov** [comment]
Interop views don't support sizing based on intrinsic content size of native views.
Moreover, WKWebView doesn't have one.
These closest you can get to mimic it is - https://stackoverflow.com/questions/27515236/how-to-determine-the-content-size-of-a-wkwebview and provide it explicitly.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4913">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
