### ISSUE TITLE
Can't build with compose 1.6.10 and kotlin 2.0.0

### ISSUE THREAD

**Issue by dhakehurst** [JetBrains/compose-multiplatform#4914]
Error
```
Execution failed for task ':myproject:transformCommonMainDependenciesMetadata'.
> Could not resolve all files for configuration ':myproject:commonMainResolvableDependenciesMetadata'.
   > Could not find androidx.arch.core:core-common:2.2.0.
     Required by:
         project :myproject > org.jetbrains.androidx.lifecycle:lifecycle-runtime:2.8.0
```

**Comment by StefanLobbenmeier** [comment]
Could you share your build.gradle.kts? In particular do you have the repositories configured?

I have those and it works on my machine:
```
repositories {
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    google()
}
```

**Comment by dhakehurst** [comment]
Hi,
I do not have the 
maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
repository.

but why should I need it when everything else seems to be on maven central ?
and I'm not using a 'dev' version!
I did not have this repo when I used the previous version  - I'm upgrading from 1.6.0  (beta01)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4914">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
