### ISSUE TITLE
kotlin.IllegalStateException: ComposeScene is closed for Popup on iOS

### ISSUE THREAD

**Issue by syru88** [JetBrains/compose-multiplatform#4916]
**Describe the bug**
When Popup on iOS is opened and closed after short period of time (milliseconds), `kotlin.IllegalStateException: ComposeScene is closed` is thrown.

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): 17.0, 17.5...
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iPhone 15 iOS 17.5 Simulator (happens on other versions as well)

**To Reproduce**
1. Checkout code from https://github.com/syru88/PopupCrash or use  this snippet:
``` kotlin
@Composable
@Preview
fun App() {
    MaterialTheme {
        var showContent by remember { mutableStateOf(false) }

        if (showContent) {
            LoadingHud()
        }

        val coroutineScope = rememberCoroutineScope()
        Column(Modifier.fillMaxWidth(), horizontalAlignment = Alignment.CenterHorizontally) {
            Button(onClick = {
                showContent = true
                coroutineScope.launch {
                    // no crash when delay is 50ms or more
                    delay(10.milliseconds)
                    showContent = false
                }
            }) {
                Text("Click me!")
            }
        }
    }
}

@Composable
fun LoadingHud() {
    Popup {
        Box(
            modifier = Modifier.fillMaxSize(),
            contentAlignment = Alignment.Center,
        ) {
            Column(
                modifier = Modifier
                    .requiredWidth(150.dp)
                    .wrapContentHeight()
                    .background(
                        color = Color.Gray.copy(alpha = 0.7f),
                        shape = RoundedCornerShape(12.dp)
                    )
                    .padding(horizontal = 16.dp, vertical = 24.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
            ) {
                CircularProgressIndicator(modifier = Modifier.size(48.dp).padding(8.dp))
                Spacer(Modifier.height(8.dp))
                Text("Popup")
            }

        }
    }
}
```
2. Click on 'Click me'
3. See error

**Expected behavior**
No crash should happen. It's working on Android or when longer delay is used (60ms).

**Comment by MatkovIvan** [comment]
Fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/1384

**Comment by liufeng382641424** [comment]
@MatkovIvan This problem has not been fixed in version 1.6.11. I call the Dialog to display and close it in milliseconds, but it still behaves abnormally. In addition, I have not found a way to modify the semi-transparent background of the Dialog. Can you tell me? Thank you, brother.

**Comment by MatkovIvan** [comment]
> This problem has not been fixed in version 1.6.11.

It's not included to this version

> I have not found a way to modify the semi-transparent background of the Dialog

There is no common way to do that. For Multiplatform/non-Android you can use `DialogProperties.scrimColor` for that

**Comment by liufeng382641424** [comment]
@MatkovIvan Thanks, can you tell me which version has been fixed?
I encountered a similar bug in iPhone 6s and iPhone 7Plus, and I don't know how to fix it. After entering text in the input box, I keep double-clicking the input box. At this time, a copy prompt box will pop up. If I keep double-clicking the prompt box, it will keep appearing and closing. At this time, it will also crash. The exception is also the same. I feel that it is the same bug, right?

**Comment by MatkovIvan** [comment]
> Thanks, can you tell me which version has been fixed?

It will be part of 1.7.0

> I feel that it is the same bug, right?

It sounds so

**Comment by liufeng382641424** [comment]
@MatkovIvan There are 2 input boxes on a page. I enter text in one of them and double-click to pop up the copy prompt box. At this time, clicking the other input box will cause an abnormality. I would like to ask if there is any preventive solution at present?
In addition, when is 1.7.0 expected to be released?

**Comment by liufeng382641424** [comment]
@MatkovIvan Or can I disable the copy function of the input box? Thanks bro

**Comment by MatkovIvan** [comment]
> There are 2 input boxes on a page. I enter text in one of them and double-click to pop up the copy prompt box. At this time, clicking the other input box will cause an abnormality. I would like to ask if there is any preventive solution at present?

Sorry, it's not clear what "abnormality" is. It doesn't seem related to the topic. If you think that it's some problem that should bt fixed - please open separate issue with full description and repro

> In addition, when is 1.7.0 expected to be released?

From [docs](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compatibility-and-versioning.html#jetpack-compose-and-compose-multiplatform-release-cycles): "The gap between a Compose Multiplatform release and a Jetpack Compose release is usually 1–3 months."

> Or can I disable the copy function of the input box?

#3286

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4916">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
