### ISSUE TITLE
Increasing space in Column content (with Arrangement.spacedBy(16.dp)) when ModalBottomSheet is opened

### ISSUE THREAD

**Issue by syru88** [JetBrains/compose-multiplatform#4920]
**Describe the bug**
When bottom sheet is in Column with `verticalArrangement = Arrangement.spacedBy(16.dp)` then after bottom sheet is shown, spacing in main content increases. (check attached video)

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): 17.0, 17.5...
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iPhone 15 iOS 17.5 Simulator (happens on other versions as well)

**To Reproduce**
1. Checkout code from https://github.com/syru88/BottomSheetJumpingIssue or use this snippet:
```kt
@OptIn(ExperimentalMaterial3Api::class)
@Composable
@Preview
fun App() {
    MaterialTheme {
        Scaffold { paddingValues ->
            val sheetState = rememberModalBottomSheetState()
            val scope = rememberCoroutineScope()
            var showBottomSheet by remember { mutableStateOf(false) }

            Column(
                modifier = Modifier.fillMaxWidth().padding(paddingValues),
                // ok without arrangement
                verticalArrangement = Arrangement.spacedBy(16.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text("Just random text")

                if (showBottomSheet) {
                    ModalBottomSheet(
                        onDismissRequest = {
                            showBottomSheet = false
                        },
                        sheetState = sheetState
                    ) {
                        Button(onClick = {
                            scope.launch { sheetState.hide() }.invokeOnCompletion {
                                if (!sheetState.isVisible) {
                                    showBottomSheet = false
                                }
                            }
                        }) {
                            Text("Hide bottom sheet")
                        }
                    }
                }

                Button(onClick = { showBottomSheet = true }) {
                    Text("Click me!")
                }

            }
        }
    }
}
```
2. Click on "Click me!"
3. Spacing between text and button in main content has increased.

**Expected behavior**
Space should be same as before bottom sheet is opened. It works on Android.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/3898471/9d887ef4-ff37-4070-8fdd-1ce677caff3f

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4920">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
