### ISSUE TITLE
Cannot determine the version of Skiko for Compose '1.6.11'

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-multiplatform#4921]
**Describe the bug**
Updating to 1.6.11 causes building to fail with the error:

```
Could not determine the dependencies of task ':<my-project>:unpackSkikoWasmRuntimeJs'.
> Could not resolve all dependencies for configuration ':<my-project>:COMPOSE_SKIKO_JS_WASM_RUNTIME'.
   > Cannot determine the version of Skiko for Compose '1.6.11'
```

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.11
- Kotlin version: 2.0.0

**To Reproduce**
1. See https://github.com/eygraber/virtue/pull/9

**Comment by terrakok** [comment]
I couldn't reproduce it. Could you provide a small reproducer? Your project is overcomplicated for that

**Comment by eygraber** [comment]
It looks like I may have updated too soon and the skiko release wasn't available yet (see [here on Slack](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1717523402356939?thread_ts=1717474431.512529&cid=C01D6HTPATV)).

It's working now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4921">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
