### ISSUE TITLE
IOS Material3 ripple increases button size on click 

### ISSUE THREAD

**Issue by alaegin** [JetBrains/compose-multiplatform#4924]
**Describe the bug**
Hello!

I use ModalBottomSheet from Material3 with Material3 Button inside. When I click on the edge of the button it changes it's size for several frames causing the whole container to resize, then it returns to the original size. If the click is executed to the center of the button then nothing happens. This behavior is valid only for a few clicks and then it's becomes better.

This issue is only valid for iOS. Exact the same steps doesn't do anything unexpected on Android.

**Affected platforms**

- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.11
- Kotlin version: 2.0.0
- Device (model or simulator for iOS issues): Iphone 13 and Iphone 14 Pro Max were tested.

**To Reproduce**

```kotlin
ModalBottomSheet(
    sheetState = bottomSheetState,
    onDismissRequest = { onDismissRequest() },
) {
    Column(
        modifier = Modifier.padding(top = 24.dp, bottom = 24.dp, start = 24.dp, end = 24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Button(
            modifier = Modifier
                .fillMaxWidth()
                .padding(top = 24.dp),
            onClick = onDeleteClick,
        ) {
            Text("delete")
        }

        Button(
            modifier = Modifier
                .fillMaxWidth()
                .padding(top = 8.dp),
            onClick = onCancelClick,
        ) {
            Text("cancel")
        }
    }
}
```

I tried to replace the Button with the same-size Box and add a `clickable` modifier and it works the same way. (bug repeats)

```kotlin
.clickable(
    onClick = onClick,
    indication = rememberRipple(),
    interactionSource = remember { MutableInteractionSource() },
)
```

But, if I add `bounded = false` to the ripple, the bug is gone.
```kotlin
.clickable(
    onClick = onClick,
    indication = rememberRipple(bounded = false),
    interactionSource = remember { MutableInteractionSource() },
)
```

Also, If I remove `fillMaxWidth` modifier from the button and make the width less than the available space then the issue is gone. 

**Expected behavior**
Button doesn't change it's size when the ripple effect is being drawn.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/10329086/df03d785-c8ce-4ed1-b92a-d530ba97ce7b

**Comment by terrakok** [comment]
Reproduced
https://github.com/JetBrains/compose-multiplatform/assets/3532155/21f36254-f5ee-4a33-9b15-1e3bc6910fc1

[issues_4924 2.zip](https://github.com/user-attachments/files/15566520/issues_4924.2.zip)

**Comment by MatkovIvan** [comment]
The current workaround is to disable platform layers via

```kt
ComposeUIViewController(
    configure = { platformLayers = false }
)
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4924">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
