### ISSUE TITLE
Change visibility of helper functions (Resources)

### ISSUE THREAD

**Issue by angelix** [JetBrains/compose-multiplatform#4925]
Change visibility of the following extension functions. 

```
internal expect fun ByteArray.toImageBitmap(): ImageBitmap
internal expect fun ByteArray.toXmlElement(): Element
internal expect fun ByteArray.toSvgElement(): SvgElement
```

Those are very useful especially for native targets.

**Comment by terrakok** [comment]
It is not responsibility of the resources library. We will do that in the compose core.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4925">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
