### ISSUE TITLE
Using scss in compose multiplatform

### ISSUE THREAD

**Issue by madagama89** [JetBrains/compose-multiplatform#4927]
I'm starting to use compose multiplatform, but I have a concern. Is it possible to reference a scss style file and inherit it in the elements' attributes when using material design?

**Comment by terrakok** [comment]
Compose Multiplatform doesn't use HTML elements. It draws on a canvas via SKIA. So, the answer is no.
But you may take a look at community frameworks like https://kobweb.varabyte.com/

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4927">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
