### ISSUE TITLE
Desktop window not capturable after upgrade from Compose 1.5 to 1.6

### ISSUE THREAD

**Issue by Stuie** [JetBrains/compose-multiplatform#4931]
**Describe the bug**

A desktop app with a `Window` that is `undecorated`, `transparent`, and not `focusable` was capturable in [OBS](https://obsproject.com/) (software for streaming on services like Twitch or YouTube) using at least Compose 1.3.1, 1.4.x, and 1.5.x up to 1.5.12.

The same application with Compose upgraded to 1.6.x (starting with 1.6.0 for sure) is not capturable in OBS any more.

**Affected platforms**
- Desktop - Only tested on Windows

**Versions**
- Libraries:
```
[versions]
kotlin = "1.9.22"
compose = "1.6.0"

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }

[libraries]

androidx-annotations = { group = "androidx.annotation", name = "annotation", version = "1.7.1" }
```

- Kotlin version: 1.9.22
- OS version(s) (required for Desktop and iOS issues): Windows 11
- OS architecture (x86 or arm64): x86
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 19 (Amazon Corretto)

**To Reproduce**
1. Create a window in your application that is `undecorated`, `transparent`, and not `focusable`
2. Add that window to a scene in OBS
3. With 1.5.12 the window will show up, from 1.6.0 it will not show up

I have created [a minimal project that reproduces the issue](https://github.com/Stuie/compose-window-capture-issue/tree/compose-1.5.12), along with screenshots. The only relevant change between the two branches on the repo is the Compose version in `libs.versions.toml`.

**Expected behavior**
I would expect a window that was capturable by OBS with Compose 1.5.12 would continue to be capturable when upgrading to Compose 1.6.0.

**Screenshots**
Here's how OBS looks for 1.5.12:
![OBS-Compose-1 5 12](https://github.com/JetBrains/compose-multiplatform/assets/389169/2ef98c2e-4550-4cc0-985c-90bd830bde9a)

Here's the same window in OBS for 1.6.0:
![OBS-Compose-1 6 0](https://github.com/JetBrains/compose-multiplatform/assets/389169/b7a549de-2638-4788-b3d6-1fdd7f008ab6)

**Additional context**
No additional context, please see the linked repo for a repro case.

**Comment by terrakok** [comment]
Could you try to call `System.setProperty("skiko.renderApi", "OPENGL")` before the app window creation.

**Comment by Stuie** [comment]
@terrakok Thanks for that. I pulled the UI stuff out to a post-main function, set the property before calling it, and it seems to do the trick.

Was there documentation that I missed? The closest relevant thing I see in the release notes for 1.6.0 is [this PR to do with transparency on desktop](https://github.com/JetBrains/skiko/pull/837). It doesn't mention the property you mentioned above.

**Comment by MatkovIvan** [comment]
This property isn't new and you're right about that change - it fixes transparent window support on D3D (previously it failed on init and used OpenGL as fallback).
So you can use OpenGL if it works better in your case, hovewer I'd recommend to set this property only for WIndows.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4931">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
