### ISSUE TITLE
[Desktop] Can't capture native inputs in windows using windowHandle

### ISSUE THREAD

**Issue by MohamedRejeb** [JetBrains/compose-multiplatform#4934]
I was trying capturing native input events in desktop to get some data related to stylus (pressure, tilt...) and I used `window.windowHandle`  to access native window and it's working fine for macos. But for windows I realised that the `HWND` created by the `windowHandle` is different than the `HWND` coming with the events when the cursor is on top of my composables. But when I move the cursor on top of the window top bar or on top of swing components the  `HWND` coming with the events is the same as the  `HWND` from the `windowHandle` in case of interop blending is disabled but when I enable interop blending even hovering on top of swing components gives a different `HWND` than the events.
I'm not sure what's happening exactly behind the scenes but I think that compose is getting rendered on a kind of invisible window on top of the swing window (Sometimes closing the app doesn't go well and only the compose content disappears but the window and swing components remains visible which increased my suspicion that there's two windows on top of each other).

**Affected platforms**
- Desktop (Windows)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 1.9.24
- OS version(s) (required for Desktop and iOS issues): Windows
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): jbr 17

**Comment by MatkovIvan** [comment]
`HWND` is handle for any native view on Windows, not "window" handle. Compose provides it as-is from AWT.

Interop blending is just putting Compose above the interop and makes it transparent. So since events are received to top-most view, yes, it's not the same to swing. For interop view compose redispatching events to right view manually via AWT/Swing API.

So the situation is explainable but it's about implementation defaults of not only Compose but also AWT/Swing.

**Comment by MohamedRejeb** [comment]
Is there a way to get the handle for Compose view?

**Comment by MatkovIvan** [comment]
Well Compose has a few views internally. Public `windowHandle` is for rendering one (used in skia). Getting handle for other components again is AWT implementation details (with all lightweight/heavyweight specifics), but theoretically it should seem something like https://stackoverflow.com/a/413895/1703290
Another reference: https://github.com/openjdk/jdk/blob/8ffc35d117846a7a2aa08afed662273d2f887770/src/java.desktop/windows/native/libawt/windows/awt_Component.h#L165
But again, please note that it might vary across JDK distributions

**Comment by MohamedRejeb** [comment]
Currently it's working fine. I'm accepting events from all views but sometimes I'm getting some unwanted events (ex: events for window top bar) which is filtered now using `PointerEventType.Enter` and `PointerEventType.Exit` to enable/disable the listener. But I want to improve it more by forcing a single `HWND` to receive the events from.
I will check the references.

Thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4934">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
