### ISSUE TITLE
CupertinoOverscrollEffect keeps LazyColumn offseted up even more items are added in

### ISSUE THREAD

**Issue by xiaozhikang0916** [JetBrains/compose-multiplatform#4935]
**Describe the bug**

In a LazyColumn with loadmore functions, quick fling to bottom will bring up the list content area. But after new items added in, this area remains blank.

https://github.com/JetBrains/compose-multiplatform/assets/8273026/704b943c-2ffb-40be-96cb-a077d7137d57

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 1.9.23
- OS version(s) (required for Desktop and iOS issues): 16
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): reproduced in simulator and iPhone 8

**To Reproduce**

Run the code in iOS

https://gist.github.com/xiaozhikang0916/6d258929845f14b72923640ad893e273

Keep flinging to bottom rapidly

**Expected behavior**

New items are filling the blank area and keep flinging to the new bottom

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4935">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
