### ISSUE TITLE
TextFiled Cursor Issues

### ISSUE THREAD

**Issue by pankaj1920** [JetBrains/compose-multiplatform#4936]
1. - In IOS device while typing in textfiled. if we long press the Space bar and try to move cursor in between its not working. 

kotlin = "2.0.0"
compose-plugin = "1.6.11"

**Comment by terrakok** [comment]
Duplicates https://github.com/JetBrains/compose-multiplatform/issues/4593

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4936">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
