### ISSUE TITLE
iOS. Crash when exceeding some height value in vertically scrollable content of ModalBottomSheet

### ISSUE THREAD

**Issue by DimaSidukov** [JetBrains/compose-multiplatform#4937]
**Describe the bug**
If `ModalBottomSheet` has scrollable content and is shown on the screen, the following error occurs. Whether the scrolling started or not, the crash is happening on first composition of the composable. Important: ModalBottomSheet's content height must be a large number. Hard to tell the exact value.
```
-[MTLTextureDescriptorInternal validateWithDevice:]:1357: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor has height (11700) greater than the maximum allowed size of 8192.
```
**Affected platforms**

- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): 17.4
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): iPhone 15 Pro iOS 17.4 Simulator (happens on other versions as well)

**To Reproduce**
1. Run this code snippet:
```kt
ModalBottomSheet(
    onDismissRequest = { },
    content = {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
        ) {
            Box(
                modifier = Modifier
                .fillMaxWidth().height(1000.dp)
                .background(Color.Black)
            )
            Box(
                modifier = Modifier
                    .fillMaxWidth().height(1000.dp)
                    .background(Color.Red)
            )
            Box(
                modifier = Modifier
                    .fillMaxWidth().height(1000.dp)
                    .background(Color.Green)
            )
        }
    },
    sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
)
```
2. See error

**Expected behavior**
No crash should happen.

**Comment by elijah-semyonov** [comment]
Should be fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/1385

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4937">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
