### ISSUE TITLE
Compose Resource incorrectly reads string chunks from a file  

### ISSUE THREAD

**Issue by AChep** [JetBrains/compose-multiplatform#4938]
**Describe the bug**
App crashes during base64 decoding of the resources. 

![image](https://github.com/JetBrains/compose-multiplatform/assets/990982/96fc0290-b44e-4f92-bf4d-50410b9f4e18)

![image](https://github.com/JetBrains/compose-multiplatform/assets/990982/ce3e0d49-e178-446f-ab97-084abd944862)

If I go to the file itself and read the given range
```
> dd if=strings.commonMain.cvr ibs=1 skip=23401 count=83
string|feat_item_show_barcode_text|RW5jb2RlIGEgdGV4dCBhcyBkaWZmZXJlbnQgYmFyY29kZXMu
83+0 records in
0+1 records out
83 bytes copied, 7.6769e-05 s, 1.1 MB/s
```

we can see that the range is correct. However the record data is different to what Compose resources reads:
```
RW5jb2RlIGEgdGV4dCBhcyBkaWZmZXJlbnQgY
RW5jb2RlIGEgdGV4dCBhcyBkaWZmZXJlbnQgYmFyY29kZXMu
```

if we investigate further we see that the `ResourceReader.desktop.kt` has read the following sequence of bytes:

```
[115, 116, 114, 105, 110, 103, 124, 102, 101, 97, 116, 95, 105, 116, 101, 109, 95, 115, 104, 111, 119, 95, 98, 97, 114, 99, 111, 100, 101, 95, 116, 101, 120, 116, 124, 82, 87, 53, 106, 98, 50, 82, 108, 73, 71, 69, 103, 100, 71, 86, 52, 100, 67, 66, 104, 99, 121, 66, 107, 97, 87, 90, 109, 90, 88, 74, 108, 98, 110, 81, 103, 89, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

if I pause there and execute two different commands:
```kotlin
String(getResourceAsStream(path).use { it.readAllBytes() }).slice(offset.toInt()..(offset+size).toInt())
// prints string|feat_item_show_barcode_text|RW5jb2RlIGEgdGV4dCBhcyBkaWZmZXJlbnQgYmFyY29kZXMu which is correct
String(getResourceAsStream(path).use { it.skipNBytes(offset); it.readNBytes(size.toInt()) })
// prints string|feat_item_show_barcode_text|RW5jb2RlIGEgdGV4dCBhcyBkaWZmZXJlbnQgYmFyY29kZXMu which is correct
String(getResourceAsStream(path).use { it.skip(offset); it.read(result, 0, size.toInt()); result })
// prints string|feat_item_show_barcode_text|RW5jb2RlIGEgdGV4dCBhcyBkaWZmZXJlbnQgY which is not correct
```
The idea why it happens is because both `.skip()` and `.read()` methods that the current implementation uses can skip and read less than requested. 

**Affected platforms**

- Desktop (Windows, Linux, macOS)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.11 
- Kotlin version: 2.0.0

**To Reproduce**
1. Clone https://github.com/AChep/keyguard-app/commit/1ceb9f5ef9518218a78b1bb5bd3ec3734cd96ee7
2.  Execute `:desktopApp:run` Gradle task
3. Enter any data in the app to skip the setup flow and head straight to Settings / Other / Features overview

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4938">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4938">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
