### ISSUE TITLE
Add androidx.lifecycle.compose.LifecycleEventEffect

### ISSUE THREAD

**Issue by rschattauer** [JetBrains/compose-multiplatform#4940]
Compose Multiplatform should support https://developer.android.com/jetpack/androidx/releases/lifecycle?authuser=1#2.8.0+ and within that version, there is LifecycleEventEffect that I would like to see.

It works fine if I copy
```
@Composable
fun LifecycleEventEffect(
    event: Lifecycle.Event,
    lifecycleOwner: LifecycleOwner = LocalLifecycleOwner.current,
    onEvent: () -> Unit
) {
    if (event == Lifecycle.Event.ON_DESTROY) {
        throw IllegalArgumentException("LifecycleEventEffect cannot be used to " +
            "listen for Lifecycle.Event.ON_DESTROY, since Compose disposes of the " +
            "composition before ON_DESTROY observers are invoked.")
    }

    // Safely update the current `onEvent` lambda when a new one is provided
    val currentOnEvent by rememberUpdatedState(onEvent)
    DisposableEffect(lifecycleOwner) {
        val observer = LifecycleEventObserver { _, e ->
            if (e == event) {
                currentOnEvent()
            }
        }

        lifecycleOwner.lifecycle.addObserver(observer)

        onDispose {
            lifecycleOwner.lifecycle.removeObserver(observer)
        }
    }
}
```
and use that one, but those Lifecycle*Effects should be available out of the box.

**Comment by MatkovIvan** [comment]
It's already supported. It's in `lifecycle-runtime-compose` that you should include to your project

**Comment by rschattauer** [comment]
Oh wow, thanks, I was missing this dependency, my bad!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4940">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
