### ISSUE TITLE
Ress Class name - Compose multiplatform resources

### ISSUE THREAD

**Issue by mpierucci** [JetBrains/compose-multiplatform#4942]
For compose multiplatform resources it would be nice to allow config for setting the name of the generated class, similar to how mokko does it.
Something like 

`    resClassName.set("MyName")
`

**Comment by terrakok** [comment]
duplicates https://github.com/JetBrains/compose-multiplatform/issues/4763

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4942">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4942">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
