### ISSUE TITLE
[Web][Wasm] Issue with Color Rendering in Compose Web: Inconsistent Lightness in Arabic Fonts

### ISSUE THREAD

**Issue by Saif-Alhaider** [JetBrains/compose-multiplatform#4949]
**Describe the bug**
I am experiencing issues with color rendering in my Compose Web application when using Arabic fonts. When applying a color with a specific lightness value (e.g., 87%), the text does not render uniformly. Some parts of the Arabic characters appear with inconsistent lightness, leading to visual discrepancies and an uneven appearance.

**Affected platforms**

- Web (K/Wasm) - Canvas based API 

**Versions**
- Libraries:
  - Compose Multiplatform version:1.6.10
- Kotlin version: 2.0.0

**To Reproduce**
1. Run this code snippet:
```
Text(
        text,
        color = color,
        fontFamily = FontFamily(
            Font(
                resource = Res.font.Tajawal_Medium,
                FontWeight.Medium
            )
        ),
        style = TextStyle(
            textDirection = TextDirection.Rtl
        ),
        fontSize = fontSize,
        modifier = modifier.graphicsLayer(translationY = 2f)
            .pointerHoverIcon(if (clickable) PointerIcon.Hand else PointerIcon.Default),
    )
```

**Expected behavior**
The Arabic text should render uniformly with a consistent lightness of 87% across all characters and glyphs

**Screenshots**
<img width="312" alt="Screenshot 2024-06-08 at 9 40 58 PM" src="https://github.com/JetBrains/compose-multiplatform/assets/58166633/2b4be321-8a28-46e8-bc5b-b4a938dc8978">

**Additional Information**
I also tried with multiple arabic fonts like Tajawal cairo all gave same result
I also tried to use BasicText instead of Text gave me same result

**Comment by terrakok** [comment]
This is not the Compose issue. The font behaves the same in a regular html page:

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>issues-4949</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@200;300;400;500;700;800;900&display=swap"
          rel="stylesheet">
    <style>
        body {
            font-family: 'Tajawal';
            font-size: 120px;
            color: rgba(0, 0, 0, 0.3);
        }
    </style>
</head>
<body>
<div>
    <h1>تقف المنازل بين الغابات</h1>
</div>
</body>
</html>
```

<img width="1610" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/3532155/32da374e-f810-453e-b965-064c44c8fc7b">

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4949">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
