### ISSUE TITLE
Dragging to scroll clears selection

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/compose-multiplatform#4951]
On iOS (or other platforms with touch), the current selection is cleared on touch-up in `SelectionContainer` after dragging to scroll.

**Affected platforms**
- iOS
- (probably) Web when used with touch.

**Versions**
- Compose Multiplatform version: 1.6.11

**To Reproduce**
1. Run the mpp demo on iOS.
2. In the SelectionContainer demo, in the scrollable text, select some text
3. Drag the scrollable. Note that on touch-up, the selection is cleared.

**Expected behavior**
Selection should not be cleared.

**Screenshots**
https://github.com/JetBrains/compose-multiplatform/assets/5230206/e41a45cc-0f42-480a-8420-5fb2230b99b0

**Additional context**
The selection is cleared by `SelectionManager.Modifier.onClearSelectionRequested`, because the scroll is not recognized as a drag, so basically it thinks it was a click (because the pointer didn't move relative to the element).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4951">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
