### ISSUE TITLE
Support `material3-adaptive-navigation-suite`

### ISSUE THREAD

**Issue by Yue-plus** [JetBrains/compose-multiplatform#4952]
How to use [`NavigationSuiteScaffold`](https://developer.android.com/develop/ui/compose/layouts/adaptive/build-adaptive-navigation) ?
如何使用 [`NavigationSuiteScaffold`](https://developer.android.google.cn/develop/ui/compose/layouts/adaptive/build-adaptive-navigation?hl=zh-cn)？

I tried to add dependence by myself, but failed.
我尝试自行添加依赖，但是失败了。

![image](https://github.com/JetBrains/compose-multiplatform/assets/33195150/47ae645e-06ce-4149-98c7-abaacfe60284)

**Comment by mahramane** [comment]
> `material3-adaptive-navigation-suite` is not ported to multiplatform yet

Hi
Why `material3-adaptive-navigation-suite` is not support in `[1.7.0-dev1698](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.7.0-dev1698)`?

**Comment by MatkovIvan** [comment]
Because it's not ported to multiplatform yet

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4952">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by toaster217** [comment]
@MatkovIvan Any update on Adaptive navigation suite?

**Comment by MatkovIvan** [comment]
Fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/1539
