### ISSUE TITLE
 KLIB resolver: Could not find "org.jetbrains.compose.annotation-internal:annotation"

### ISSUE THREAD

**Issue by KhubaibKhan4** [JetBrains/compose-multiplatform#4961]
**Describe the bug**
Getting this error while running the iosApp from the Android Studio:  KLIB resolver: Could not find "org.jetbrains.compose.annotation-internal:annotation". 

I'm unable to resolve this issue. I'm facing this issue on many of my projects. 

**Affected platforms**
- iOS

**Versions**
  - Compose Multiplatform version: 1.6.11
  - ...
- Kotlin version: 2.0.0
- Device (model or simulator for iOS issues): iMac & Macbook m1

**Expected behavior**
When I try to run to it, it should run and launch the app but I get this issue: e: KLIB resolver: Could not find "org.jetbrains.compose.annotation-internal:annotation" in [/Users/zohaibkhan/Downloads/Youtube-Clone-KMP-master 9, /Users/zohaibkhan/.konan/klib, /Users/zohaibkhan/.konan/kotlin-native-prebuilt-macos-x86_64-2.0.0/klib/common, /Users/zohaibkhan/.konan/kotlin-native-prebuilt-macos-x86_64-2.0.0/klib/platform/ios_simulator_arm64]

**Screenshots**
![iosApp-Error](https://github.com/JetBrains/compose-multiplatform/assets/98816544/6fb7e223-fe02-414e-84cf-2f927904c414)

**Additional context**
The error that I mentioned above occours when i try to launch iosApp from the Android Studio but when I try to open the application from the xocde, I get error : No Such Module 'ComposeApp'

**Comment by KhubaibKhan4** [comment]
I forget to add few of my projects where I'm facing this issue:

YouTube Clone KMP: https://github.com/KhubaibKhan4/Youtube-Clone-KMP
Flexi-Store-KMP: https://github.com/KhubaibKhan4/Flexi-Store-KMP
Mind in Motion: https://github.com/KhubaibKhan4/MindinMotion-KMP

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4961">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Kashif-E** [comment]
@KhubaibKhan4  were you able to resolve this?

**Comment by KhubaibKhan4** [comment]
Yes. In the latest updates, It's working fine. Basically I was using old versions of some libraries. Make sure to use the latest version.

**Comment by KhubaibKhan4** [comment]
And in some cases, We get this issues due to brew installation with not completed packages. I still get these issues sometimes. Do you have any suggestions about it? @Kashif-E
