### ISSUE TITLE
Fix SemanticsNodeInteraction class properties visibility

### ISSUE THREAD

**Issue by aleks-ex** [JetBrains/compose-multiplatform#4964]
The SemanticsNodeInteraction class is defined as follows:

```kotlin
class SemanticsNodeInteraction constructor(
    internal val testContext: TestContext,
    internal val useUnmergedTree: Boolean,
    internal val selector: SemanticsSelector
)
```
The properties `testContext`, `useUnmergedTree`, and `selector` have internal visibility. This restricts access to these properties from external code that utilizes the library. Consequently, it hinders the creation of custom extension functions necessary for certain testing scenarios.

Current testing API doesn't allow to search descendant deeper than 1st generation as SemanticsNodeInteraction has just `onChildren()` and `onChildAt(index: Int)` to find it. `(commonMain/androidx/compose/ui/test/Selectors.kt)`

For instance, the library provides extension functions for working with lists, such as:
```kotlin
/**
 * Returns children of this node.
 */
fun SemanticsNodeInteraction.onChildren(): SemanticsNodeInteractionCollection {
    return SemanticsNodeInteractionCollection(
        testContext,
        useUnmergedTree,
        selector.addSelectionFromSingleNode("children") { it.children }
    )
}
```

In my framework, I need to create similar extension functions with custom logic of target elements search. However, I am unable to do so because I do not have access to the testContext, useUnmergedTree, and selector properties.

I kindly request to change the visibility of these properties in the SemanticsNodeInteraction class from internal to public.

Jetpack Compose version: `1.6.7`
Jetpack Compose component used: `androidx.compose.ui:ui-test`

**Comment by aleks-ex** [comment]
Similar issue in google tracker https://issuetracker.google.com/issues/342778294

**Comment by Schahen** [comment]
Hi! The thing is that SemanticsNodeInteraction belongs to a common code shared with Android Jetpack so whatever proposals you have on this API it's better to start here - https://github.com/androidx/androidx

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4964">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
