### ISSUE TITLE
[ImageViewer/iOS] The function of sharing a picture ends with an infinite loop.

### ISSUE THREAD

**Issue by issamux** [JetBrains/compose-multiplatform#4970]
**Describe the bug**
compose-multiplatform: examples: ImageViewer:  The function of sharing a picture in iOS ends with an infinite loop.

**Affected platforms**
- compose-multiplatform: examples: ImageViewer : iOS

**Affected code**
iosMain/example.imageviewer.storage.FileExtensions.kt

    suspend fun NSURL.readData(): NSData {
       while (true) {
        val data = NSData.dataWithContentsOfURL(this)
        if (data != null)
            return data
        yield()
    }
   }

**Versions**
- Libraries:
kotlin.version=2.0.0
agp.version=8.0.2
compose.version=1.6.10
Xcode = 15.4
Simulator = Iphone 15 pro

**To Reproduce**
1. Open and Build iOS project
2. Click on Picture
3. Scroll down to Share Button
4. Click Share Button.
5. No Response no result ( see video)

**Expected behavior**
New Ui open to share selected picture

**Screenshots/ Video**

https://github.com/JetBrains/compose-multiplatform/assets/195905/110e1708-9d67-47aa-9d74-734e8cf3215c

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4970">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
