### ISSUE TITLE
upgrade of experimental - cef

### ISSUE THREAD

**Issue by mallumoSK** [JetBrains/compose-multiplatform#4972]
Hi,
please upgrade [expermimental module of cef](https://github.com/JetBrains/compose-multiplatform/tree/master/experimental/cef)
To latest stable version  compose 1.6.11.
 Because current version is very old, 3 years.
And multiple interfaces to compose / siko not exist or are internal already. 
Thanx.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4972">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
