### ISSUE TITLE
Resizing the window leads to the UI elements scaling proportionally

### ISSUE THREAD

**Issue by MrZhuKeXin** [JetBrains/compose-multiplatform#4981]
**Describe the bug**
When I resize the window, the UI elements scale proportionally, and after a certain delay, they return to the correct size.

**Affected platforms**
- Desktop (Windows)
-->

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.11
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): win11 22631.3737
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): Open JDK 17.0.11

**To Reproduce**
It's just the hellocompose code generated by ide.

1. Run this code snippet:
```kt
@Composable
fun HelloCompose() {
    var showContent by remember { mutableStateOf(false) }
    Column(Modifier.fillMaxWidth(), horizontalAlignment = Alignment.CenterHorizontally) {
        Button(onClick = { showContent = !showContent }) {
            Text("Click me!")
        }
        AnimatedVisibility(showContent) {
            val greeting = remember { Greeting().greet() }
            Column(Modifier.fillMaxWidth(), horizontalAlignment = Alignment.CenterHorizontally) {
                Image(painterResource(Res.drawable.compose_multiplatform), null)
                Text("Compose: $greeting")
            }
        }
    }
}
```
2. run
3. resize the window
4. see the error

**Expected behavior**
When I resize the window, the UI elements do not scale proportionally but instead display correctly according to their configuration.
Additionally, the delay from proportional scaling to correct display seems to be longer compared to other software, such as those based on SWT.

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/28593015/e500602f-17f5-4e5d-bc5e-60daff4e79a4

**Additional context**
Is this a known issue, or can this proportional scaling behavior be canceled through proper configuration? Can it be resolved in the future?

**Comment by MatkovIvan** [comment]
Another duplicate. Just previous issue opened before this one was about the same. See my comment there - https://github.com/JetBrains/compose-multiplatform/issues/4980#issuecomment-2172539689

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4981">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
