### ISSUE TITLE
is compose multiplatform for web wasmJs support routing ?

### ISSUE THREAD

**Issue by YuXunSTC** [JetBrains/compose-multiplatform#4983]
In android and iOS ,the application is only one program entry, However, when we use web pages, we like to visit specific pages directly through the web address, which is supported by raw html, so I wonder if compose multiplatform now supports configuring different urls for different pages

**Comment by MatkovIvan** [comment]
> In android and iOS ,the application is only one program entry

It's not, both supports deeplinks

> if compose multiplatform now supports configuring different urls for different pages

If we're speaking of Compose itself, it's clearly not a part of its scope. Compose doesn't block to implement handling a route.

If the question is about adopted to multiplatform Jetpack Navigation library - first alphas don't support deeplinks and integration with browser history yet.

**Comment by YuXunSTC** [comment]
I want to develop a website with compose multiplatform, which has many entries, such as xxxx/home xxxx/about xxxx/future. When a user types in a specific address in the address bar of the browser, the corresponding page can be opened directly. Is this feature currently supported

**Comment by MatkovIvan** [comment]
Currently the library won't do it automatically, but you can handle it in an application code by reading current url location and show content accordingly.
Kotlin [supports](https://kotlinlang.org/docs/wasm-js-interop.html#kotlin-functions-with-javascript-code) calling browser JS API, so it shouldn't be a problem

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4983">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
