### ISSUE TITLE
SelectionContainer crashed when right click space area

### ISSUE THREAD

**Issue by Yricky** [JetBrains/compose-multiplatform#4985]
**Describe the bug**
See 'To Reproduce'
**Affected platforms**

- Desktop (Windows, Linux, macOS)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.11
  - Navigation Multiplatform version (for related issues):
  - ...
- Kotlin version: 1.9.23
- OS version(s) (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64):
- Device (model or simulator for iOS issues): 
- JDK (for desktop issues): 

**To Reproduce**
1. Run this code snippet:
   ```kt
   @Composable
   fun BugReproduction() {
        SelectionContainer {
            Text("aaaa",Modifier.background(androidx.compose.ui.graphics.Color.White).padding(40.dp))
        }
   }
   ```
2. Right click on space area
3. See error

**Expected behavior**
No action instead of crash occuring

**Screenshots**
<img width="1276" alt="截屏2024-06-17 16 18 35" src="https://github.com/JetBrains/compose-multiplatform/assets/30372219/5bf577e5-8895-4aa1-99eb-056ce0fd1ff8">
<img width="1017" alt="截屏2024-06-17 16 14 12" src="https://github.com/JetBrains/compose-multiplatform/assets/30372219/a2744a13-7c57-47f2-89f8-3b30b5e7f861">

**Additional context**

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4985">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
