### ISSUE TITLE
(iOS) Selection Container shows keyboard while selecting text

### ISSUE THREAD

**Issue by mazunin-v-jb** [JetBrains/compose-multiplatform#4986]
**Describe the bug**
If SelectionContainer contains Text and this Text is being selected, the keyboard will be shown

**Affected platforms**

- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.11

**To Reproduce**
Run this code snippet:
   ```kt
   SelectionContainer {
  Text(text = "Hello World!")
   }
   ```

**Expected behavior**
Keyboard shouldn't be opened while selecting Text in SelectionContainer

**Screenshots**

https://github.com/JetBrains/compose-multiplatform/assets/124871594/bbf63a8e-a2c7-497c-a803-f46dde678f22

**Additional context**

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4986">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4986">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
