### ISSUE TITLE
Wrong vertical alignment of TextField in widgetsgallery sample

### ISSUE THREAD

**Issue by stephanepechard** [JetBrains/compose-multiplatform#499]
Hi,

When I run the widgetsgallery sample from this repo with IntelliJ 2020.3, the TextField examples show the input text a bit higher than vertically centered. The following screenshot shows the result I get:

<img width="550" alt="Screenshot 2021-03-14 at 21 36 11" src="https://user-images.githubusercontent.com/703194/111083417-cd474080-850d-11eb-9c3e-dbdcff6ca647.png">

The expected result would be to see a vertically centered input text as seen on the Material design specs: https://material.io/components/text-fields#filled-text-field

Thanks!

**Comment by jimgoog** [comment]
I read on slack that it renders correctly if you set `singleLine = true` on the text field.

**Comment by stephanepechard** [comment]
@jimgoog  Yes, it was the answer I get when I asked the question, and it works. My concern is more about the conformance to the Material specs, which does not specify a parameter to get text aligned. Such a difference could lead to misinterpretation by developers.

**Comment by jimgoog** [comment]
Yeah, totally.  It's a bug, remains open, thanks for filing.  I was just posting the workaround here for posterity.

**Comment by m-sasha** [comment]
Fixed by https://github.com/JetBrains/compose-multiplatform/pull/3054

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6055">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
