### ISSUE TITLE
ModalBottomSheet no appearance animation in skiko targets

### ISSUE THREAD

**Issue by ZacSweers** [JetBrains/compose-multiplatform#4990]
**Describe the bug**
The Material3 ModalBottomSheet enter animation on iOS appears to just blip into existence rather than actually translate the sheet or fade in the scrim.

| Android | iOS |
| ------- | --- |
| [Screen_recording_20240617_125721.webm](https://github.com/JetBrains/compose-multiplatform/assets/1361086/d670e64b-e816-4650-951f-71928575402e) | https://github.com/JetBrains/compose-multiplatform/assets/1361086/600e99fd-a295-436a-bf60-9dbca4daa571 |

**Affected platforms**

- iOS

**Versions**
- Libraries: 1.6.11
  - Material3
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): See below
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): 
  - iOS 17.5 (21F77) SDK + iOS 17.5 (21F79) Simulator (Installed)
  - iOS 17.5 on iPhone 15 Pro

**To Reproduce**
1. Reproducible project: https://github.com/ZacSweers/FieldSpottr/
2. Specific code for the sheet is here: https://github.com/ZacSweers/FieldSpottr/blob/bf99cfd56422b4d75ba5057713721c8e77cf35ea/src/commonMain/kotlin/dev/zacsweers/fieldspottr/Home.kt#L172
3. Which in turn uses this library impl: https://github.com/slackhq/circuit/blob/main/circuitx/overlays/src/commonMain/kotlin/com/slack/circuitx/overlays/BottomSheetOverlay.kt

**Expected behavior**
It should animate in smoothly

**Screenshots**
See above

**Additional context**

**Comment by MatkovIvan** [comment]
iOS reuses animation from common in this place, so it looks more like performance/missing frames issue.
@elijah-semyonov could you please take a look?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4990">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
