### ISSUE TITLE
App crashes when launched on x86_64 iOS simulator after migrated to Kotlin 2.0

### ISSUE THREAD

**Issue by aaalaniz** [JetBrains/compose-multiplatform#4991]
**Describe the bug**

I have a Compose Multiplatform [project](https://github.com/aaalaniz/compose-lightsaber) that I recently migrated to Kotlin 2.0. I have a few [Maestro](https://maestro.mobile.dev/) tests that run on [Maestro Cloud](https://cloud.mobile.dev/) devices that are running an x86_64 iPhone 15 with iOS 17. Prior to migrating to Kotlin 2.0, these tests ran fine, but now they crash with the following stack trace.

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib            0x00007fff7017322a __pthread_kill + 10
1   libsystem_pthread.dylib           0x00007fff701ccf7b pthread_kill + 263
2   libsystem_c.dylib                 0x0000000114aa06b7 abort + 130
3   xyz.alaniz.aaron.Lightsaber       0x000000011053f59e (anonymous namespace)::terminateWithUnhandledException(ObjHeader*)::$_1::operator()() const + 14
4   xyz.alaniz.aaron.Lightsaber       0x000000011053f47f void (anonymous namespace)::$_0::operator()<(anonymous namespace)::terminateWithUnhandledException(ObjHeader*)::$_1>((anonymous namespace)::terminateWithUnhandledException(ObjHeader*)::$_1) + 47
5   xyz.alaniz.aaron.Lightsaber       0x000000011053f299 (anonymous namespace)::terminateWithUnhandledException(ObjHeader*) + 9
6   xyz.alaniz.aaron.Lightsaber       0x000000011053f257 (anonymous namespace)::processUnhandledException(ObjHeader*) + 55
7   xyz.alaniz.aaron.Lightsaber       0x000000011053ef59 (anonymous namespace)::TerminateHandler::kotlinHandler() + 217
8   libc++abi.dylib                   0x00000001135879c7 std::__terminate(void (*)()) + 8
9   libc++abi.dylib                   0x000000011358a204 __cxa_rethrow + 99
10  libobjc.A.dylib                   0x00000001128d9baf objc_exception_rethrow + 37
11  com.apple.CoreFoundation          0x0000000112aa8825 CFRunLoopRunSpecific + 851
12  com.apple.GraphicsServices        0x0000000117e27c8e GSEventRunModal + 139
13  com.apple.UIKitCore               0x000000012d12165a -[UIApplication _run] + 928
14  com.apple.UIKitCore               0x000000012d1262b5 UIApplicationMain + 101
15  com.apple.SwiftUI                 0x0000000120443e5d closure #1 in KitRendererCommon(_:) + 196
16  com.apple.SwiftUI                 0x0000000120443d97 runApp<A>(_:) + 148
17  com.apple.SwiftUI                 0x000000011fe06854 static App.main() + 61
18  xyz.alaniz.aaron.Lightsaber       0x000000010f7b3cae static iOSApp.$main() + 30
19  xyz.alaniz.aaron.Lightsaber       0x000000010f7b3d49 main + 9
20  dyld_sim                          0x000000011277ff21 start_sim + 10
21  dyld                              0x000000011f8db310 start + 2432
```

**Affected platforms**

- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: `1.6.11`
- Kotlin version: `2.0.0`
- OS version(s): `MacOS 14 with Xcode 15.3`
- OS architecture: `arm64`
- Device (model or simulator for iOS issues):  `x86_64`

**To Reproduce**

I have an open pull request where I am trying to debug this crash [here](https://github.com/aaalaniz/compose-lightsaber/pull/22), but essentially the steps to reproduce are to recreate what is being run in the GitHub Actions:

1. Build the shared module: `./gradlew shared:assemble`
2. `./gradlew podInstall`
3. Build the iOS app:

```
xcodebuild -workspace iosApp/iosApp.xcworkspace \
  -scheme iosApp \
  -configuration Debug \
  -xcconfig iosApp/Configuration/Config.xcconfig \
  OBJROOT=iosApp/build/ios SYMROOT=iosApp/build/ios \
  -sdk iphonesimulator
```

4. Run the app on an x86_64 iPhone simulator.

**Expected behavior**
The app shouldn't crash on launch.

**Additional context**

I am able to run the Maestro test suite on my M1 iMac using the arm64 iPhone 15 simulator with iOS 17. This crash only appears to happen on x86, and this is the only option available on Maestro Cloud, according to [the documentation](https://cloud.mobile.dev/reference/device-configuration#simulator-specs).

**Comment by aaalaniz** [comment]
Thank you @MatkovIvan 

After some more investigation, I discovered that the crash happens regardless of the architecture the test suite is run on. I think I found a bug with resources not being available at runtime, but it is _**not**_ an X86_64 issue. I will create a new bug and close this one. Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4991">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
