### ISSUE TITLE
MLKit linkPodDebugFrameworkIosArm64 FAILED 

### ISSUE THREAD

**Issue by LuuNguyen0811** [JetBrains/compose-multiplatform#4992]
I'm using CocoaPods to install the ML Kit Face Detection library. Here is the configuration:
cocoapods {
...
        ios.deploymentTarget = "13.0"

        pod("GoogleMLKit/FaceDetection"){
            moduleName = "MLKitFaceDetection"
            version = "6.0.0"
            extraOpts += listOf("-compiler-option", "-fmodules")
        }

        framework {
            freeCompilerArgs += composeArgs
            baseName = libName
            isStatic = false // REQUIRE
            embedBitcode(DISABLE)

            noPodspec()
            xcf.add(this)
        }
    }
However, I encounter the following error when building for iOS:
```
    ld: Undefined symbols:
  _MLKITx_AbslInternalSpinLockWake, referenced from:
      -[MLKFace landmarkOfType:] in MLKitFaceDetection
      -[MLKFace landmarkOfType:] in MLKitFaceDetection
      
```
Has anyone found a solution for this issue?

**Comment by MatkovIvan** [comment]
It doesn't seem related to Compose, please use appropriate issue tracker

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4992">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
