### ISSUE TITLE
Screen flickering On WIndows Desktop

### ISSUE THREAD

**Issue by jarvis1801** [JetBrains/compose-multiplatform#4994]
Like this issue
https://youtrack.jetbrains.com/issue/TBX-12282/Toolbox-keeps-flickering-screen-on-Windows-11

How can I set to OpenGL to render the application

**Comment by MatkovIvan** [comment]
> How can I set to OpenGL to render the application

`System.setProperty("skiko.renderApi", "OPENGL")`

Closing as the question is answered and details to reproduce/debug "flickering" is not provided

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4994">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
