### ISSUE TITLE
LazyVerticalStaggeredGrid two columns with five items with difference horizontalArrangement, the last item sometimes on the left, sometimes on the right

### ISSUE THREAD

**Issue by ganluo960214** [JetBrains/compose-multiplatform#4996]
**Describe the bug**
LazyVerticalStaggeredGrid two columns with five items with difference horizontalArrangement, the last item sometimes on the left, sometimes on the right

i only have android. i only runing on android. did i post to Jetpack Compose?

**Affected platforms**
android

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version:  2
- OS version(s) (required for Desktop and iOS issues): api29
- OS architecture (x86 or arm64): x86
- Device (model or simulator for iOS issues):  simulator 

**To Reproduce**
1. Run this code snippet:
```kt
@Composable
@Preview
fun App() {
    MaterialTheme {
        val paddingDp = 1.dp // <----------
        LazyVerticalStaggeredGrid(
            columns = StaggeredGridCells.Fixed(2),
            verticalItemSpacing = 2.dp,
            horizontalArrangement = Arrangement.spacedBy(paddingDp),
            contentPadding = PaddingValues(
                bottom = paddingDp,
            ),
        ) {
            item(
                span = StaggeredGridItemSpan.FullLine
            ) {
                Text(
                    text = paddingDp.toString()
                )
            }
            // SightCards
            (1..5).forEach { _ ->
                item {
                    Box(modifier = Modifier
                        .aspectRatio(1F,)
                        .background(Color.Black)
                    )
                }
            }

        }
    }
}
```

![image](https://github.com/JetBrains/compose-multiplatform/assets/8499204/b4997976-fe5a-432f-a0f9-485c56f34e2f)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8499204/6f526af1-d9cc-409e-9689-02dbb6f8eaa8)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8499204/4a4d7213-3698-4447-8929-8ad030098312)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8499204/01e7eeee-fbdc-4d7e-98d6-ed808ccf7d60)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8499204/825aca60-ff2d-4aa1-bfe5-427a89d087f9)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8499204/7c6a581b-3e30-4fdb-8874-4eb69a0e663e)

![image](https://github.com/JetBrains/compose-multiplatform/assets/8499204/c94e3b88-68cb-464b-876d-e39db12b3899)

**Comment by MatkovIvan** [comment]
> i only have android. i only runing on android. did i post to Jetpack Compose?

Yes please report about this there. It was even mentioned in issue template: "If the bug is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)"

Compose Multiplatform uses original Google's binaries on Android (no changes, even no re-compilation), so it's not something that caused by changes in JetBrains fork.

**Comment by ganluo960214** [comment]
@MatkovIvan i repeat it on windows, this issue can reopen?

**Comment by MatkovIvan** [comment]
Our changes here won't affect Android. Please open the issue in Google's tracker. It needs to be fixed in AOSP, not in fork

> it's looks right side boxes is smaller.

In your Android screenshots rounding issues persist too
<img width="235" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/1836384/e67e8269-6cd3-42f5-bf8c-c8d40c2d0912">

**Comment by ganluo960214** [comment]
@MatkovIvan thanks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4996">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
