### ISSUE TITLE
(Desktop) minimumInteractiveComponentSize + size/width/height Modifier leads to inconsistent placement

### ISSUE THREAD

**Issue by F-J-S-P** [JetBrains/compose-multiplatform#4999]
**Describe the bug**
When using both .minimumInteractiveComponentSize() and .size()/.width()/.height() on the same composable, it is placed correctly when the value used for .size() is an even number and one pixel off (to the right for width, down for height, both for size) when it is an odd number. I noticed this when using IconButton scaling with AppTheme.fixedLineHeight (in this case 19), since IconButton has .minimumInteractiveComponentSize() integrated, but it is not restricted to them.

**Affected platforms**
- Desktop (Windows, Linux, macOS)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.11
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): 
  - Linux Mint 21.3 Cinnamon:
    - Cinnamon Version: 6.0.4
    - Kernel: 6.5.0-41-generic 
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): 21.0.3

**To Reproduce**
Run this code snippet:
   ```kt
    import androidx.compose.foundation.*
    import androidx.compose.foundation.layout.*
    import androidx.compose.material3.*
    import androidx.compose.ui.*
    import androidx.compose.ui.graphics.Color
    import androidx.compose.ui.unit.*
    import androidx.compose.ui.window.*
    
    fun main() = application {
        Window(
            onCloseRequest = ::exitApplication,
            title = "ComposeBugTest",
        ) {
            Column{
                repeat(20) {
                    Box(
                        modifier = Modifier
                            .size((it+1).dp)
                            .minimumInteractiveComponentSize()
                            .background(Color.Green.copy(0.7f)),
                    )
                }
            }
        }
    }
   ```
**Expected behavior**
20 green boxes appear above each other without space between them and aligned with the window's left border.

**Observed behavior**
20 green boxes appear, every second one is shifted one pixel to the right and below, leading to unintended spaces and overlap.
 
**Screenshots**
![Screenshot from 2024-06-20 03-47-48](https://github.com/JetBrains/compose-multiplatform/assets/51082019/8aa46142-32fb-4754-827e-ec5fbb806caa)

**Additional context**
The Column + repeat is just to make the problem and how it's tied to odd numbers more obvious (the first box is not visible as it's fully inside the second one); the problem will also appear when using just a single box.

**Comment by MatkovIvan** [comment]
<img width="84" alt="Screenshot 2024-06-20 at 08 50 01" src="https://github.com/JetBrains/compose-multiplatform/assets/1836384/775f9ebb-d230-4f27-893a-b1f2d3d45008">

It's reproducible on Android too

**Comment by MatkovIvan** [comment]
@F-J-S-P could you please duplicate this issue to Google issue tracker (with main point about Android/common instead of Desktop)? Thanks

**Comment by F-J-S-P** [comment]
o7
https://issuetracker.google.com/issues/348199047

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4999">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
