### ISSUE TITLE
iOS. Animation crashes with OOM inside bottom sheet

### ISSUE THREAD

**Issue by logutenko** [JetBrains/compose-multiplatform#5000]
When playing an animation inside bottom sheet, a large amount of memory is allocated. This causes an application to crash with  OOM error. 

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform: 1.6.10
- Kotlin: 2.0.0
- OS: 17.1.1
- OS architecture: arm64
- Device: iPhone 15 Pro

**To Reproduce**
1. In the example [graphics-2d](https://github.com/JetBrains/compose-multiplatform/tree/master/examples/graphics-2d) replace Scaffold with ModalBottomSheet:
```
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun Graphics2D(requestWindowSize: ((width: Dp, height: Dp) -> Unit) = EMPTY_WINDOW_RESIZER) {
    val exampleState: MutableState<Example?> = remember { mutableStateOf(null) }
    val example = exampleState.value

    MaterialTheme(
        colorScheme = if (isSystemInDarkTheme()) darkColorScheme() else lightColorScheme()
    ) {
        ModalBottomSheet(onDismissRequest = {}) {
            if (example == null) {
                LazyColumn(Modifier.padding(horizontal = 16.dp)) {
                    items(examples) {
                        Button(onClick = {
                            exampleState.value = it
                        }) {
                            Text(it.name)
                        }
                    }
                }
            } else {
                example.content { w, h ->
                    requestWindowSize(w, h + TOP_APP_BAR_HEIGHT)
                }
            }
        }
    }
}
```
2. Run an app and click on RotatingWords button
3. OS terminates app

According to the profiler, memory consumption is over 3 GiB

![Снимок экрана 2024-06-20 в 13 05 27](https://github.com/JetBrains/compose-multiplatform/assets/37524723/02a94299-3dfb-442f-a282-2630ad20f1e3)

**Comment by okushnikov** [comment]
test

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5000">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
