### ISSUE TITLE
TextField error: kotlin.IllegalStateException: ComposeScene is closed

### ISSUE THREAD

**Issue by liufeng382641424** [JetBrains/compose-multiplatform#5001]
Version 1.6.11, the exception only occurs on iPhone 6 6s 7 7Plus. There are 2 input boxes on the page. I enter text in one of the input boxes and double-click to pop up the copy prompt box. At this time, clicking to switch to the other input box will cause an exception. Please try a few more times.

Here is my code:
`Column {
            TextField(
                value = "123",
                onValueChange = {}
            )

            TextField(
                value = "",
                onValueChange = {}
            )
        }`

The error is as follows:
Uncaught Kotlin exception: kotlin.IllegalStateException: ComposeScene is closed
    at 0   My App                            0x100ffa9af        kfun:kotlin.Throwable#<init>(kotlin.String?){} + 119 
    at 1   My App                            0x100ff3e8f        kfun:kotlin.Exception#<init>(kotlin.String?){} + 115 
    at 2   My App                            0x100ff40af        kfun:kotlin.RuntimeException#<init>(kotlin.String?){} + 115 
    at 3   My App                            0x100ff464f        kfun:kotlin.IllegalStateException#<init>(kotlin.String?){} + 115 
    at 4   My App                            0x101694a73        kfun:androidx.compose.ui.scene.SingleLayerComposeSceneImpl.invalidatePositionInWindow#internal + 271 
    at 5   My App                            0x10175b08f        kfun:androidx.compose.ui.scene.ComposeScene#invalidatePositionInWindow(){}-trampoline + 91 
    at 6   My App                            0x1016ebfd7        kfun:androidx.compose.ui.scene.ComposeSceneMediator.<init>$lambda$14$lambda$13#internal + 1027 
    at 7   My App                            0x1016f297f        kfun:androidx.compose.ui.scene.ComposeSceneMediator.$<init>$lambda$14$lambda$13$FUNCTION_REFERENCE$52.invoke#internal + 87 
    at 8   My App                            0x1016f2a83        kfun:androidx.compose.ui.scene.ComposeSceneMediator.$<init>$lambda$14$lambda$13$FUNCTION_REFERENCE$52.$<bridge-UNNB>invoke(kotlin.Double){}#internal + 123 
    at 9   My App                            0x1011250c3        kfun:kotlin.Function1#invoke(1:0){}1:1-trampoline + 107 
    at 10  My App                            0x10171146f        kfun:androidx.compose.ui.window.ComposeSceneKeyboardOffsetManager.<set-viewBottomOffset>#internal + 203 
    at 11  My App                            0x101712b63        kfun:androidx.compose.ui.window.ComposeSceneKeyboardOffsetManager.animateKeyboard$updateAnimationValues#internal + 375 
    at 12  My App                            0x101713bef        kfun:androidx.compose.ui.window.ComposeSceneKeyboardOffsetManager.object-1.animationDidUpdate#internal + 139 
    at 13  My App                            0x101713c93        kfun:androidx.compose.ui.window.ComposeSceneKeyboardOffsetManager.object-1.$imp:animationDidUpdate#internal + 143 
    at 14  QuartzCore                          0x184fdfceb        <redacted> + 759 
    at 15  QuartzCore                          0x184fe687f        <redacted> + 367 
    at 16  CoreFoundation                      0x1814dfa3b        <redacted> + 171 
    at 17  CoreFoundation                      0x18151fc8b        <redacted> + 55 
    at 18  CoreFoundation                      0x18152328f        <redacted> + 595 
    at 19  CoreFoundation                      0x1814e049f        <redacted> + 2391 
    at 20  CoreFoundation                      0x1814f3193        CFRunLoopRunSpecific + 571 
    at 21  GraphicsServices                    0x1a2026987        GSEventRunModal + 159 
    at 22  UIKitCore                           0x183cf6a87        <redacted> + 1079 
    at 23  UIKitCore                           0x183a8ffc7        UIApplicationMain + 335 
    at 24  SwiftUI                             0x188d48d67        <redacted> + 159 
    at 25  SwiftUI                             0x188c9383b        <redacted> + 179 
    at 26  SwiftUI                             0x188c791db        $s7SwiftUI3AppPAAE4mainyyFZ + 95 
    at 27  My App                            0x1001a07b7        $s8My_App6iOSAppV5$mainyyFZ + 39 
    at 28  My App                            0x1001a0867        main + 11 
    at 29  dyld                                0x1049ec4cf        0x0 + 4372481231

**Comment by MatkovIvan** [comment]
Based on stack trace, it's clearly the same as #4916 and fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/1384

**Comment by MatkovIvan** [comment]
Sorry, from [your previous description](https://github.com/JetBrains/compose-multiplatform/issues/4916#issuecomment-2179721848) without stacktrace it wasn't clear

**Comment by liufeng382641424** [comment]
https://github.com/JetBrains/compose-multiplatform/issues/3286 It works on desktop.
I hope there is a temporary solution on iOS, for example, if I disable the pop-up prompt box when double-clicking or long pressing, it should not trigger the exception if it does not pop up. tks @MatkovIvan

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5001">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
