### ISSUE TITLE
connection to Database

### ISSUE THREAD

**Issue by richnmond** [JetBrains/compose-multiplatform#5007]
$pdo = new pdo('mysql:host=localhost; port=3306;dbname=Product Dev','root','');
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

**Comment by chrisjenx** [comment]
What does this have to do with Compose Multiplatform?

**Comment by richnmond** [comment]
These two technologies serve different purposes and wouldn't be directly used together. Compose Multiplatform focuses on the visual layer of an application, while PDO interacts with databases.

**Comment by MatkovIvan** [comment]
I don't see how it's related to Compose Multiplatform (UI framework). Please open the issue in corresponding tracker

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5007">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
