### ISSUE TITLE
Where can I see the changes to the slot table in the Compose July '24 release?

### ISSUE THREAD

**Issue by wucong1997** [JetBrains/compose-multiplatform#5014]
I want to know about the latest changes in slot table. Where can I get the information?

**Comment by kropp** [comment]
Hey,
the Compose runtime is being developed in the AOSP repository.
Here is the relevant changelist: https://android-review.googlesource.com/c/platform/frameworks/support/+/2644758
It is still active, the changes are not yet merged nor released.
