### ISSUE TITLE
Improve code style: Replace wildcard imports with explicit imports

### ISSUE THREAD

**Issue by soleil-colza** [JetBrains/compose-multiplatform#5019]
## Description

Currently, the codebase contains several wildcard imports (e.g., import androidx.compose.foundation.layout.*). While functional, these imports can negatively impact code readability and maintainability, especially as the project grows and more libraries are introduced.

## Proposed solution

Refactor the code to replace all wildcard imports with explicit imports, specifying the exact classes being used.

## Benefits

- Enhanced readability: Explicit imports make it clear which classes are being used from each package, improving code understanding.
- Reduced risk of conflicts: Explicit imports help prevent potential naming conflicts that could arise when adding new libraries with similar class names.
- Improved maintainability: By clearly defining dependencies, it becomes easier to manage and update the codebase in the future.
You can also link this issue to the corresponding pull request in the description for easy reference.

I am currently working on this issue on [this pull request](https://github.com/JetBrains/compose-multiplatform/pull/5018).

**Comment by elijah-semyonov** [comment]
I guess you should also have a look at the [core repository](https://github.com/JetBrains/compose-multiplatform-core).
Avoid changing anything in `common` source set though.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5019">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
