### ISSUE TITLE
Questions related to `*.dll ` packaging

### ISSUE THREAD

**Issue by GangJust** [JetBrains/compose-multiplatform#5024]
Hello, I think I need help. The screenshot is as follows:

![image](https://github.com/JetBrains/compose-multiplatform/assets/30917584/e9418a5c-5082-435c-b505-c051fdb65890)
![image](https://github.com/JetBrains/compose-multiplatform/assets/30917584/190d413e-db8e-4549-91f7-1d6274437a56)

I tried the following two methods to package 'api_jni. ll' into the application, but none of them were successful.
![image](https://github.com/JetBrains/compose-multiplatform/assets/30917584/634a8307-520f-4775-9958-b3133bdcc224)
![image](https://github.com/JetBrains/compose-multiplatform/assets/30917584/47c8d709-2bf5-4459-a490-862a5e37c9f4)

Is it the way I write that is wrong?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5024">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
