### ISSUE TITLE
[Navigation] commonrize `NavDeepLinkDslBuilder`

### ISSUE THREAD

**Issue by Sanlorng** [JetBrains/compose-multiplatform#5027]
In the navigation latest dev build (2.8.0-dev1698), `NavDeepLinkDslBuilder` and `navDeepLink` is still androild only api. Would you consider making this api move to common sourse set?

**Comment by MatkovIvan** [comment]
Already done in https://github.com/JetBrains/compose-multiplatform-core/commit/60ab74dd01f2441f29894f76c67053ecbc16505c but it (and adoption of 2.8 in general) isn't merged to main branch yet. Since dev versions are build from that, it is still based on 2.7.7

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5027">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
