### ISSUE TITLE
Detekt tasks are being registered when using the 1.7.0 dev gradle plugin

### ISSUE THREAD

**Issue by eygraber** [JetBrains/compose-multiplatform#5028]
**Describe the bug**
I've been playing around with the 1.7.0 dev builds of the gradle plugin, and starting from [1.7.0-dev1688](https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/org.jetbrains.compose.gradle.plugin/1.7.0-dev1688/) I get an error saying that:

> Cannot add task 'detektMetadataTest' as a task with that name already exists.

I use detekt in my project, so my assumption is that something in the Compose gradle plugin has started registering detekt tasks which is causing the error.

**Comment by eygraber** [comment]
Looks like it's specifically for the task `detektMetadataTest`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5028">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
