### ISSUE TITLE
Clicking TextField should consume pointer press event

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#5029]
**Describe the bug**

Clicking a TextField should consume the press event (in the Main pass). But instead, it is not consumed and propagates to the parent element.

**Affected platforms**
- Desktop (macOS)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.7.0-dev1698

- Kotlin version: 
- OS version(s) (required for Desktop and iOS issues):  Mac 14.5 (23F79)
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): 20

**To Reproduce**
1. Run this code snippet:

```kt
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.size
import androidx.compose.material3.TextField
import androidx.compose.runtime.mutableStateOf
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.awt.awtEventOrNull
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.PointerEventType
import androidx.compose.ui.input.pointer.onPointerEvent
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@OptIn(ExperimentalComposeUiApi::class)
fun main() {
    val text = mutableStateOf("some text")
    var nextPointerEvent = 0
    application {
        Window(
            onCloseRequest = ::exitApplication
        ) {
            Box(
                Modifier
                    .size(400.dp)
                    .background(Color.Yellow)
                    .onPointerEvent(PointerEventType.Press) {
                        val consumed = it.awtEventOrNull!!.isConsumed
                        text.value = "Got pointer event ${nextPointerEvent++} (consumed=$consumed)"
                    }
            ) {
                TextField(
                    value = text.value,
                    onValueChange = {
                        text.value = it
                    }
                )
            }
        }
    }
}
```

2. Click on the text field
3. See that the pointer event progated to the parent

**Expected behavior**

The event handler registered to the container should not receive the click event.

If the pass was `PointerEventPass.Initial`, then the click event should be received. However, the default value for `pass` is `PointerEventPass.Main`. Since the TextField behaves as expected, it seems that the TextField does handle the mouse press event. However, it then fails to consume it and prevent it from propagating further up the tree.

**Additional context**

I have a mouse click handler on the TextField container in my app. When it receives a click, it uses `focusRequester.requestFocus()` on its own component. But when the click was actually in the TextField (inside the container), this unexpectedly messes with the focus in the TextField.

**Comment by m-sasha** [comment]
Does Android consume taps on TextField?

**Comment by kropp** [comment]
@m-sasha please take a look

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5029">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
