### ISSUE TITLE
Adding a new  resource dir to sourceSets.commonMain is not affecting Res.drawable

### ISSUE THREAD

**Issue by AgnaldoNP** [JetBrains/compose-multiplatform#5030]
## **Scenario**
I'm implementing the android flavor strategy to my project. To do that I've added new source and resource dirs. Let's focus in the commomMain:
```kts
sourceSets {
    commonMain {
        kotlin.srcDir("src/commonFlavor1/kotlin")
        resources.srcDir("src/commonFlavor1/composeResources")
    }
}
``` 

In fact, I added new sources to each flavors (flavor1 and falvor2) and variantes(flavor1Debug, flavor1Release, flavor2Debug, flavor2Release)
```kts
sourceSets {
    commonMain {
        kotlin.srcDir("src/common${variant.flavor.flavorName.capitalized()}/kotlin")
        resources.srcDir("src/common${variant.flavor.flavorName.capitalized()}/composeResources")

        kotlin.srcDir("src/common${variant.variantName.capitalized()}/kotlin")
        resources.srcDir("src/common${variant.variantName.capitalized()}/composeResources")
    }
}
```
The object `variant` above is gotten according to gradle command been runned.

## **Problem**
All the rouserces added in src/commonFlavor1/composeResources/drawable are not being processed and added to `Res.drawable`.

## **Workarrouund**
As a way to "solve" this I've create a task to copy the necessary resources to `build/generated/compose/resourceGenerator/preparedResources/commonMain/composeResources/`.
Unfortunatelly It doesn't work right after a `./gradlew clean` I don't know why
```kt
fun recursiveCopy(from: File, to: File) {
    if (!from.exists()) return
    from.listFiles()?.forEach { file ->
        if (file.name != ".DS_Store") {
            if (file.isDirectory) {
                val newDir = File(to, file.name)
                newDir.mkdir()
                recursiveCopy(file, newDir)
            } else {
                val destinationFile = File(to, file.name)
                if (destinationFile.exists()) {
                    println("Overwriting $destinationFile")
                    destinationFile.delete()
                }
                if (!destinationFile.parentFile.exists()) {
                    destinationFile.parentFile.mkdirs()
                }
                println("Copying $file to $to")
                file.copyTo(destinationFile)
            }
        }
    }
}

tasks.register("copyKmpResources") {
    doLast {
        println("\n\n--> Copying Flavored KMP Resources")
        val variant = BuildSrcConfig.Variant.getVariant(project = project, gradle = gradle)
        val projectDir = project.projectDir.absolutePath

        val fromFlavor = File(
            projectDir,
            "src/common${variant.flavor.flavorName.capitalized()}/composeResources/"
        )
        val fromVariant = File(
            projectDir,
            "src/common${variant.flavor.flavorName.capitalized()}/composeResources/"
        )

        val destination = "build/generated/compose/resourceGenerator/preparedResources/commonMain/composeResources/"

        println("destination:\n  $destination")
        val destinationFile = File(projectDir, destination)
        println(" - copying \"$fromFlavor\" to \"$destinationFile\"")
        recursiveCopy(fromFlavor, destinationFile)
        println(" - copying \"$fromFlavor\" to \"$destinationFile\"")
        recursiveCopy(fromVariant, destinationFile)
    }
}

tasks.named("prepareComposeResourcesTaskForCommonMain").configure {
    dependsOn("copyKmpResources")
}
```

**Affected platforms**

- Desktop (Windows, Linux, macOS)
- iOS
- Web (K/Wasm) - Canvas based API
- Android

**Versions**
- Libraries:
  - org.jetbrains.compose: 1.6.10
- Kotlin version: 2.0.0
- OS version: MAC OS 14.5
- OS architecture: arm64

**To Reproduce**
1. Add a new composableResource to commomMain
```kts
sourceSets {
    commonMain {
        resources.srcDir("src/commonFlavor1/composeResources")
    }
}
```
2. Add a new file in the drawable folder in this new source.
 - e.g.: `src/commonFlavor1/composeResources/drawable/icon.xml`

3. Rebuild the project
4. Check Res.drawable availble items, "icon" will not be an option

**Expected behavior**
As I've added a new source dir to `sourceSets -> commomMain -> resources`, I expected that the new resources can be used normally.

**Additional context**
Adding a new source dir to `.kt` files has worked as expected, only the composeResources doesn't.

I hope I'm not duplicating a bug, I search for similar issues but I wasn't  able to find
Tks.

**Comment by terrakok** [comment]
> I'm implementing the android flavor strategy to my project. To do that I've added new source and resource dirs.

Please don't! The projects source sets are not for the flavoring. The flavoring as you described is the android specific thing. If you need to have different logic/resources then use gradle modules

**Comment by terrakok** [comment]
Anyway, for resourc directory customization there was implemented a feature: 
https://github.com/JetBrains/compose-multiplatform/pull/5016

**Comment by terrakok** [comment]
Additional info:

There is no **resources** in Kotlin Multiplatform!

sourceSets {
    commonMain {
        kotlin.srcDir("...") // <- adds new source directory to the kotlin source set
        resources.srcDir("...") // <- meaningless for the kotlin multiplatform
    }
}

**Comment by terrakok** [comment]
The task in the kotlin tracker: https://youtrack.jetbrains.com/issue/KT-33432/MPP-build-variant-feature

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5030">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
