### ISSUE TITLE
iOS App crashes on launch with MissingResourceException 

### ISSUE THREAD

**Issue by DEVENDRAN-S** [JetBrains/compose-multiplatform#5032]
Describe the bug
when i create a kmp projects and added my resources in shared module and tried to access my resources in ios app of kmp project it works properly . but when i tried by creating a xcframework from my shared kmm module and intergrating the Xcframwork in another new sample ios app facing issue as (org.jetbrains.compose.resources.MissingResourceException) resource not found .

Affected platforms

iOS
Versions

Libraries:
Compose Multiplatform version:1.6.10
Kotlin version: 1.9.14

**Comment by terrakok** [comment]
Duplicates https://github.com/JetBrains/compose-multiplatform/issues/4643

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5032">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
