### ISSUE TITLE
ImageViewer/Desktop - Build error due to a code not updated after some refactoring

### ISSUE THREAD

**Issue by issamux** [JetBrains/compose-multiplatform#5034]
**Describe the bug**
An error occurred during the build of the ImageViewer sample project because the code was not updated after some refactoring ( a1b88db890ca77e9212c3d2c495b675ce871e7fa )

**Version**
Last version of project

**Affected code**
DesktopTest -  ImageViewerTest.kt

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5034">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
