### ISSUE TITLE
How to complete the check for updates and automatic updates

### ISSUE THREAD

**Issue by LazyIonEs** [JetBrains/compose-multiplatform#5037]
In [compose-multiplatform](https://github.com/JetBrains/compose-multiplatform), how to complete the check update or automatic update in the application? Android may be relatively simple, but in desktop, I don’t know how to do it, but this function is very practical, isn’t it?

**Comment by LazyIonEs** [comment]
Are [Sparkle](https://github.com/sparkle-project/Sparkle) and [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) available in compose-multiplatform?

**Comment by kropp** [comment]
Compose Multiplatform project does not include update functionality out of the box.
Please consider using existing third party solutions, such as Hydraulic Conveyor or the aforementioned platform-specific frameworks.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5037">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
