### ISSUE TITLE
The release package failed on Android

### ISSUE THREAD

**Issue by Junzz0** [JetBrains/compose-multiplatform#5038]
**Describe the bug**
Using 1.7.0-dev1698 to release the release package on Android failed,
With 1.6.11, you can successfully release the Android release package.

buildTypes == debug 
The packaging will succeed

buildTypes == release
* What went wrong:
A problem was found with the configuration of task ':composeApp:generateReleaseLintVitalReportModel' (type 'LintModelWriterTask').
  - Gradle detected a problem with the following location: '/composeApp/build/generated/assets/releaseAssetsCopyForAGP'.
    
    Reason: Task ':composeApp:generateReleaseLintVitalReportModel' uses this output of task ':composeApp:releaseAssetsCopyForAGP' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':composeApp:releaseAssetsCopyForAGP' as an input of ':composeApp:generateReleaseLintVitalReportModel'.
      2. Declare an explicit dependency on ':composeApp:releaseAssetsCopyForAGP' from ':composeApp:generateReleaseLintVitalReportModel' using Task#dependsOn.
      3. Declare an explicit dependency on ':composeApp:releaseAssetsCopyForAGP' from ':composeApp:generateReleaseLintVitalReportModel' using Task#mustRunAfter.

**Affected platforms**
- Android

**Versions**
- Libraries:
  - Compose Multiplatform version: "1.7.0-dev1698"
- Kotlin version: 2.0.0
- JDK (for desktop issues): 17

**To Reproduce**
Publish an Android release package.

**Expected behavior**
A release package for Android has been successfully released

**Screenshots**
![1](https://github.com/JetBrains/compose-multiplatform/assets/24819084/188ce222-9142-4934-a43b-b30d1e801b97)
![2](https://github.com/JetBrains/compose-multiplatform/assets/24819084/830cf081-00ba-4bb2-b2ca-6ba05a6f8778)

**Additional context**
If you use dependencyGuard, it will report a missing releaseRuntimeClasspath

dependencyGuard {
  configuration("debugAndroidTestCompileClasspath")
  configuration("debugAndroidTestRuntimeClasspath")
  configuration("debugCompileClasspath")
  configuration("debugRuntimeClasspath")
  configuration("debugUnitTestCompileClasspath")
  configuration("debugUnitTestRuntimeClasspath")
  configuration("desktopCompileClasspath")
  configuration("desktopRuntimeClasspath")
  configuration("desktopTestCompileClasspath")
  configuration("desktopTestRuntimeClasspath")
  configuration("metadataCompileClasspath")
}

**Comment by terrakok** [comment]
Fixed here: https://github.com/JetBrains/compose-multiplatform/commit/22dfb1431a85a76d2f8e6f0290f836a4a8547413

**Comment by hmy65** [comment]
@terrakok @Junzz0 
Update to agp 8.3.0 fixed this issue.

**Comment by terrakok** [comment]
@Junzz0 I don't understand why you added the comment here. Did your build fail with the same log?

**Comment by terrakok** [comment]
Anyway, this was fixed in https://github.com/JetBrains/compose-multiplatform/pull/5076 as well

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5038">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
