### ISSUE TITLE
Overriding string resources causes crashes or inelligible strings

### ISSUE THREAD

**Issue by chris6647** [JetBrains/compose-multiplatform#5039]
Coming from the Android world, we're used to being able to define a String resource in a feature module, and then have the app override any string keys it may need to. This allows a feature to have defaults, which gets superseeded by the app, as long as they're in the same `publicResClass`.

Doing so in Compose Resources does not work, due to the `offset` and `size` parameters which match the initial `StringResource` in the feature. When we runtime try to resolve it, it may not match with the final string causing ineligble strings (/empty strings) to be returned, or even crashes if the base64 decoder fails with invalid chars.

Any chance for an implementation that supports this, or ideas for a workaround? So far I havn't been able to come up with anything that I can do from my end of the code.
Had a hard time chosing between a bug report or enhancement request - but went with bug due to how the issues surface with wrong texts or crashes.

Similar problem as this issue https://github.com/JetBrains/compose-multiplatform/issues/4837 , but another use case, which will hopefully reconsider :)

**Comment by terrakok** [comment]
Yes, there is no and is not planned the overriding resources feature for now. Because accessors are being generated as code and compiled into Kotlin klibs. The android resources work different an ids are handled during a final app build. It is one of the reasons why android has own library format - AAR, as I understand.

**Comment by chris6647** [comment]
At a glance, it seems like "just" parsing untill the line end, instead of offset and size, would work and would let you override string resources in the same nameSpaces. Would that be an option?

**Comment by terrakok** [comment]
No. You are not able to read bytes from a centre of the file without offset/size

**Comment by chris6647** [comment]
Alright. Well I hope you guys will consider supporting it in the future :) Thanks for your prompt replies!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5039">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
