### ISSUE TITLE
Plural string not working properly

### ISSUE THREAD

**Issue by dhng22** [JetBrains/compose-multiplatform#5040]
I have this plural string in strings.xml:
![Screenshot 2024-06-28 at 14 20 09](https://github.com/JetBrains/compose-multiplatform/assets/86188270/b755c9d0-ed93-4051-a96e-4f5fb04dc35e)

And i called it like this:
![Screenshot 2024-06-28 at 14 22 55](https://github.com/JetBrains/compose-multiplatform/assets/86188270/6814288b-83d3-4db2-99e5-48dcecc8eeed)

But the output is "1 items" regardless the quantity input is 1 or more

**Comment by dhng22** [comment]
And the doc even has a incorrect example:
![Screenshot 2024-06-30 at 16 12 27](https://github.com/JetBrains/compose-multiplatform/assets/86188270/77a973b4-0a3a-4df7-9dd4-93e1f6e01bcd)

@terrakok you might want to take a quick look, it's not Res.string, it's Res.plurals

**Comment by terrakok** [comment]
The quantity logic is based on a locale rules. It depends on your environment.
https://developer.android.com/guide/topics/resources/string-resource#Plurals

if it doesn't help, reopen the issue with a reproducer project

**Comment by terrakok** [comment]
thank you for the doc issue: https://github.com/JetBrains/kotlin-multiplatform-dev-docs/pull/173

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5040">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
