### ISSUE TITLE
Is there any consideration for supporting the HarmonyOS? Or adding some public interfaces to adapt to other systems?

### ISSUE THREAD

**Issue by weimingjue** [JetBrains/compose-multiplatform#5041]
HarmonyOS has become the third largest mobile system. Have you considered adapting to it? Or have you considered providing some public interfaces for developers to adapt themselves?

**Comment by kropp** [comment]
We are investigating all existing platforms. However, I have nothing to share right now. If and when we support a new platform, we will announce it here and on our website.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5041">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
