### ISSUE TITLE
LazyVerticalStaggeredGrid rearranges items when scrolling up

### ISSUE THREAD

**Issue by rdsarna** [JetBrains/compose-multiplatform#5042]
**Describe the bug**
Related to `LazyVerticalStagggeredGrid`. When the grid is in a scrolled down state and recreated due to returning from another screen, scrolling up causes the items to rearrange.

**Affected platforms**
- Android
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.11
  
- Kotlin version: 2.0.0
- OS version(s) (required for Desktop and iOS issues): iOS 17.5
- Device (model or simulator for iOS issues): iPhone 15 Pro simulator/ iPhone 13 Pro device/ Android any device

**To Reproduce**

Repository that exhibits the issue - https://github.com/rdsarna/KMP-App-Template
This is a fork of a sample from the Kotlin Multiplatform Wizard. Commits added to recreate the issue - [commit1](https://github.com/rdsarna/KMP-App-Template/commit/ba65956b4c2171f4c4700b26df0cbf2bbc855b7d) and [commit2](https://github.com/rdsarna/KMP-App-Template/commit/2fbe13bccc824fd919c601b896701f34cc19ab12).

1. Fresh install the app with an active internet connection (from the repo mentioned above)
2. Scroll down quite a bit
3. Tap on any item so the next screen opens
4. Return back to the grid
5. Slowly scroll up

**Expected behavior**
The items should remain in place as user scroll up.

**Screenshots**
Video for issue - https://youtube.com/shorts/369AA3R0XpQ

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5042">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by igordmn** [comment]
See the comment there https://youtrack.jetbrains.com/issue/CMP-5042

**Comment by chrislacy** [comment]
The issue was moved to Jetbrains' repo. 

They declined it saying it's an Android bug: https://youtrack.jetbrains.com/issue/CMP-5042
