### ISSUE TITLE
Support for "Plus Darker" and "Plus Lighter" blend modes

### ISSUE THREAD

**Issue by iamcalledrob** [JetBrains/compose-multiplatform#5046]
These two blend modes (Plus Darker, Plus Lighter) are very useful when building UI, in particular, for iOS -- yet they are missing in Compose Multiplatform.

The web now somewhat supports this kind of blending via css `mix-blend-mode`:
```css
mix-blend-mode: plus-darker;
mix-blend-mode: plus-lighter;
```

Sidenote: I believe "Plus Darker" is also known as "Linear Burn"

Here's Figma's video showing the effect of this type of blending -- as you can see, this is necessary for building native looking UI for Apple platforms.

https://github.com/JetBrains/compose-multiplatform/assets/87964/179b8661-5c8b-4452-b8bc-5e299b399cd2

Alternatively, support for custom blend mode formulae might be even more versatile

More reading:
- [Figma forum discussion](https://forum.figma.com/t/launched-plus-lighter-and-plus-darker-blending-modes/685)
- https://github.com/w3c/fxtf-drafts/issues/447
- [NSCompositingOperation.plusDarker](https://developer.apple.com/documentation/appkit/nscompositingoperation/plusdarker)
- [How to achieve linear burn using Subtract and Invert](https://photoblogstop.com/photoshop/photoshop-blend-modes-explained/#AdditionalBlendModeMathTips)
- [Skia: Custom blend modes using SkBlender](https://groups.google.com/g/skia-discuss/c/AYpB0Z-fX94)

**Comment by iamcalledrob** [comment]
I believe this may also be made possible via a shader if `RuntimeEffect.makeForBlender()` (skia: `SkRuntimeEffect::makeBlender`) was made available within Skiko -- it's conspicuously missing.

[Skiko RuntimeEffect.kt](https://github.com/JetBrains/skiko/blob/45c1a7df474ce1e2df44c00505d5d497d0fed70a/skiko/src/commonMain/kotlin/org/jetbrains/skia/RuntimeEffect.kt)
[Skia SkRuntimeEffect::makeBlender](https://api.skia.org/classSkRuntimeEffect.html#a76ab187d71a40745db0ccf2ff6f7d744)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5046">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
