### ISSUE TITLE
Need some help with debugging the compose multiplatform core code

### ISSUE THREAD

**Issue by smileding** [JetBrains/compose-multiplatform#5048]
I downloaded the compose-multiplatform-core code only and wanted to debug it. But when syncing the gradle, it threw this error: ":internal-testutils-paging:main: Could not find androidx.paging:paging-common:0.0.0-SNAPSHOT." 

And when I tried to run the DemoActivity which lies in  "\compose\integration-tests\demos\src\main\java\androidx\compose\integration\demos\DemoActivity.kt", it threw these errors:

"> Task :compose:integration-tests:demos:checkDebugAarMetadata FAILED"
"e: file:///D:/Code/compose-multiplatform-core-jb-main/compose-multiplatform-core-jb-main/compose/runtime/runtime/src/androidMain/kotlin/androidx/compose/runtime/ActualAndroid.android.kt:117:21 Actual property 'MainThreadId' has no corresponding expected declaration".

How can I fix this? And it would be better if you could give me some tutorials on how to set the environment and debug the compose multiplatform core code. Thank you very much!

**Comment by igordmn** [comment]
Answered in https://github.com/JetBrains/compose-multiplatform/issues/5065#issuecomment-2213302787. Please don't create multiple issues.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5048">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
