### ISSUE TITLE
need help with compiling CM-core code

### ISSUE THREAD

**Issue by smileding** [JetBrains/compose-multiplatform#5055]
I downloaded [compose-multiplatform-core](https://github.com/JetBrains/compose-multiplatform-core) project, and I wanted to compile it using android studio on Windows, could you please give me some detailed tutorials on how to set the environment and compile the code? The tutorial in MULTIPLATFORM.md [compose-multiplatform-core] is just too general
. 
Thank you very much!

**Comment by igordmn** [comment]
Answered in https://github.com/JetBrains/compose-multiplatform/issues/5065#issuecomment-2213302787. Please don't create multiple issues.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5055">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
