### ISSUE TITLE
How to get performance data between Kotlin Multiplatform Mobile on iOS and Native iOS Development in Swift?

### ISSUE THREAD

**Issue by wucong1997** [JetBrains/compose-multiplatform#5057]
We would like to know the performance gap between Kotlin Multiplatform Mobile on iOS and Native iOS Development in Swift. Is there any official data to analyze?

**Comment by elijah-semyonov** [comment]
No, there is no _official data_, what would you consider measuring?

**Comment by igordmn** [comment]
Moved to https://youtrack.jetbrains.com/issue/CMP-5057/How-to-get-performance-data-between-Kotlin-Multiplatform-Mobile-on-iOS-and-Native-iOS-Development-in-Swift

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5057">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
