### ISSUE TITLE
1.7.0-dev1703 android release build failed when r8 is on

### ISSUE THREAD

**Issue by hmy65** [JetBrains/compose-multiplatform#5058]
> Task :composeApp:lintVitalAnalyzeRelease
ERROR: C:\Users\xxx\Desktop\projects\WorkSpaceCMP\composeApp\build\intermediates\merged_java_res\release\base.jar: R8: com.android.tools.r8.ResourceException: com.android.tools.r8.internal.vc: I/O exception while reading 'C:\Users\xxx\Desktop\projects\WorkSpaceCMP\composeApp\build\intermediates\merged_java_res\release\base.jar': C:\Users\xxx\Desktop\projects\WorkSpaceCMP\composeApp\build\intermediates\merged_java_res\release\base.jar
> Task :composeApp:lintAnalyzeDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':composeApp:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin: C:\Users\xxx\Desktop\projects\WorkSpaceCMP\composeApp\build\intermediates\merged_java_res\release\base.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3s

**Comment by hmy65** [comment]
@Junzz0 
I found a solution. Update to agp 8.3.0 fixed this issue.

[versions]
agp = "8.3.0"
kotlin = "2.0.0"
kotlinxCoroutines = "1.9.0-RC"
composePlugin = "1.7.0-alpha01"  #1.7.0-alpha01 1.6.11
jetbrainsNavigation = "2.8.0-alpha08"
jetbrainsLifecycle = "2.8.0"
androidxActivity = "1.9.0"

**Comment by hmy65** [comment]
> > @Junzz0 I found a solution. Update to agp 8.3.0 fixed this issue.
> > [versions] agp = "8.3.0" kotlin = "2.0.0" kotlinxCoroutines = "1.9.0-RC" composePlugin = "1.7.0-alpha01" #1.7.0-alpha01 1.6.11 jetbrainsNavigation = "2.8.0-alpha08" jetbrainsLifecycle = "2.8.0" androidxActivity = "1.9.0"
> 
> Thanks, because IntelliJ IDEA Community Edition 2024.1.4 locks AGP 8.2.0, resulting in the inability to use the updated AGP, then I'll wait for the release of 2024.2.

You may try fleet. https://www.jetbrains.com/fleet/
I know switch IDE is not a easy thing.
But fleet is alao developed by jetbrains. And it supports compose multiplatform better.
The best part is it supports preview in commonMain.
And when you enable smart mode and set keymap to intellij, it's basically a Intellij+.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5058">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
