### ISSUE TITLE
KeyboardCapitalization.Sentences randomly capitalizes text when chaning cursor position

### ISSUE THREAD

**Issue by Vaibhav2002** [JetBrains/compose-multiplatform#5060]
**Describe the bug**
`KeyboardCapitalization.Sentences` randomly capitalizes the Text when the cursor position is changed only on iOS.

**Affected platforms**
- iOS

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.10
- Kotlin version: 2.0.0

**Expected behavior**
Should only capitalize on sentence start, i.e. after a fullstop.

**Recording**

https://github.com/JetBrains/compose-multiplatform/assets/64367926/0f352105-84bf-461c-90b1-cc421d92dd7d

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5060">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
