### ISSUE TITLE
How to debug the Compose Multiplatform

### ISSUE THREAD

**Issue by smileding** [JetBrains/compose-multiplatform#5065]
![image](https://github.com/JetBrains/compose-multiplatform/assets/46594271/75359b1c-3d2e-4fdb-8107-97727719de2c)

Following the instruction in Compose-Multiplatform-Core/MULTIPLATFORM.md, I successfully built a KMP project with the locally published Compose. But when I made some changes in Compose Multiplatform core source code, I didn't find a way to debug it. I may be missing something obvious, could you give me some tutorials on how to debug? Thank you!

**Comment by igordmn** [comment]
Use IDEA/Android Studio to debug desktop/web and AppCode on macOS for running iOS (it is obsolete, but Android Studio currently has issues in the current configuration).

![image](https://github.com/JetBrains/compose-multiplatform/assets/5963351/160851f2-7e43-4de0-97cf-0ca861c8756a)

Running Android target in `compose-multiplatform-core` isn't supported at the moment, as CMP doesn't build/maintain it, it reuses Jetpack Compose artifacts. Read [the Google manual](https://android.googlesource.com/platform/frameworks/support/+/android-room-release/README.md) how to open/build it.

**Comment by smileding** [comment]
Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5065">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
