### ISSUE TITLE
[1.7.0-alpha01] GraphicsLayer do not seems to like being drawn multiple times

### ISSUE THREAD

**Issue by chrisbanes** [JetBrains/compose-multiplatform#5066]
**Describe the bug**
This morning I've be updating my Haze library to CMP 1.7.0-alpha01, which gives us access to the new GraphicsLayer APIs. My Android implementation already used RenderNode (which is basically the same), so I've moved that impl over to `commonMain` and now have a single implementation for all platforms.

It works as expected on Android, but on Skiko backed platforms it seems to have issues when you have multiple child layers drawing another layer. The first child layer is drawn fine, but others are not

I've also seen issues when a layer's position is outside the window bounds, the layer just doesn't draw anything. 

Haze is a bit of a stress test for the graphics layers integration, so it might be worth investigating. The sample app is an easy way to see play around. https://github.com/chrisbanes/haze/pull/250

**Affected platforms**
Skiko-backed platforms (JVM, iOS, etc)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.7.0-alpha01
- Kotlin version: 2.0/0

**Comment by chrisbanes** [comment]
Went a bit deeper into this today.

The way Haze works is by drawing the main content into a graphics layer (and keeping that around), and then creating more graphics layers for each blurred area. This works fine on Android, but on the Skiko platforms the layer stops drawing at certain positions. You can see the issue in the videos below.

https://github.com/JetBrains/compose-multiplatform/assets/227486/6fb2c3a9-4d52-43ed-beca-4f72f431e572

https://github.com/JetBrains/compose-multiplatform/assets/227486/347db3b1-15ce-44dc-a979-e8b18caa944e

**Comment by chrisbanes** [comment]
Ok, I've worked out the trigger for this.

My current code updates the layer's `topLeft` property, to tell it where to draw. If I stop setting the `topLeft`, and instead use `GraphicsLayer.translationX/Y` (or a Canvas translate when drawing the graphics layer) it works fine.

My guess is that somewhere in `PictureRecorder` (or below) is coercing or rejecting the bounds if they become too far out of the size?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5066">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by MatkovIvan** [comment]
Fixed by https://github.com/JetBrains/compose-multiplatform-core/pull/1541
