### ISSUE TITLE
MacOS Notarize App with Native Library Failed Error 65

### ISSUE THREAD

**Issue by codaman** [JetBrains/compose-multiplatform#5067]
If I add 

implementation("org.bytedeco:javacv-platform:1.5.7") this dependency and then notarizeDmg it fails 

Processing: /***/MyApplication.app
CloudKit query for MyApplication.app (2/[sha256]) failed due to "record not found".
Could not find base64 encoded ticket in response for 2/[sha256]
The staple and validate action failed! Error 65.

If I remove this dependency it notarizes perfectly

openCV uses native library. I searched all documentation, I tried many things but still fails. There is no example

**Comment by codaman** [comment]
Today I removed opencv and I added ffmpeg in lib folder. still I got  Error 65

**Comment by AChep** [comment]
The native binary must be signed for the notarization process to succeed.

**Comment by igordmn** [comment]
Moved to https://youtrack.jetbrains.com/issue/CMP-5067/MacOS-Notarize-App-with-Native-Library-Failed-Error-65

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5067">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
