### ISSUE TITLE
[1.7.0-alpha01] Moving after initiating a click cancels it

### ISSUE THREAD

**Issue by asapha** [JetBrains/compose-multiplatform#5069]
Alternative title from a user's standpoint:
- Sometimes clicks aren't getting registered

**Describe the bug**
`Modifier.clickable`'s `onClick` isn't called if you slightly move between pressing down the mouse button and releasing it.
It seems to happen when there's a scrollable parent.
This leads to a frustrating experience as buttons don't work when you move fast. Or, hypothetically, if your mouse pointer isn't stable.

<details><summary>1.6 video</summary>

![CleanShot 2024-07-05 at 14 09 36](https://github.com/JetBrains/compose-multiplatform/assets/1147807/e3bb1182-5568-45d7-aa1c-569ce90a87a6)

</details> 

<details><summary>1.7 video</summary>

With 1.7
![CleanShot 2024-07-05 at 14 23 26](https://github.com/JetBrains/compose-multiplatform/assets/1147807/74e8539b-55ee-4ad4-b468-c04ea8f9bb5d)

</details> 

**Affected platforms**
-  macOS at least

**Versions**
- `1.7.0-alpha01`, kotlin `2.0.0`
- macOS 14, arm64, JDK: 21

**To Reproduce**
- Run the jetsnack example with `1.7.0-alpha01`.
- Start a click on a card
- Slightly move the mouse inside the card
- Release the button
- There's no navigation, `onClick` isn't called

**Expected behavior**
- The click should happen, since we didn't move the cursor outside the click target.

**Additional context**

If you try this code, only the `Vertical scroll` button exhibits the behavior.
```kotlin
application {
        Window(onCloseRequest = {}) {
            Row(horizontalArrangement = Arrangement.spacedBy(16.dp)) {
                // Ok
                Button(onClick = { println("No scroll") }) { Text("No scroll") }
                // Ok
                Column { Button(onClick = { println("Column") }) { Text("Column") } }
                // Not Ok
                Column(modifier = Modifier.verticalScroll(rememberScrollState())) {
                    Button(onClick = { println("Vertical scroll") }) { Text("Vertical scroll") }
                }
            }
        }
}
```

**Comment by igordmn** [comment]
Moved to https://youtrack.jetbrains.com/issue/CMP-5069/1.7.0-alpha01-Moving-after-initiating-a-click-cancels-it
