### ISSUE TITLE
Preview in commonMain?

### ISSUE THREAD

**Issue by Andrew0000** [JetBrains/compose-multiplatform#5070]
**Describe the bug**
I'm not sure if it's a bug but seems like that.
The issue:
@ Preview annotation doesn't work in Compose Multiplatform + commonMain + Android Studio.

**Affected platforms**
**commonMain** source set in a multiplatform project with Android and iOS targets.

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.0

- Kotlin version: 1.9.22
- OS version(s) (required for Desktop and iOS issues): MacOS Sonoma 14.5
- OS architecture (x86 or arm64): x86
- Android Studio: Koala 2024.1.1 built on June 10, 202

**To Reproduce**
1. Create this code snippet in the **commonMain**:
```kt
import org.jetbrains.compose.ui.tooling.preview.Preview

@Preview
@Composable
private fun ASample() {
    Text("1234")
}
```

2. Click on 'Layout Validation'
3. See nothing: 
<img width="417" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/4018244/305bba19-bc4b-4739-ad49-12c376805259">

  
**Expected behavior**
Working preview like it works in case of Jetpack Compose and pure Android projects and modules.

**Comment by igordmn** [comment]
Follow https://github.com/JetBrains/compose-multiplatform/issues/5078. Common preview is supported only in Fleet at the moment

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5070">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
