### ISSUE TITLE
[1.7.0-alpha01] Cannot change attributes of dependency configuration ':debugFrameworkIosArm64' after it has been resolved

### ISSUE THREAD

**Issue by GuilhE** [JetBrains/compose-multiplatform#5071]
**Describe the bug**
After updating to [1.7.0-alpha01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.7.0-alpha01) a simple build will fail with:

> Cannot change attributes of dependency configuration ':debugFrameworkIosArm64' after it has been resolved

**Affected platforms**
All

**Versions**
- Libraries:
  - Compose Multiplatform version: `1.7.0-alpha01`
  - `gradle-8.6-bin.zip`
- Kotlin version: `2.0.20-Beta1`
- OS version(s) (required for Desktop and iOS issues): `14.5 (23F79)`
- OS architecture (x86 or arm64): `arm64`

**To Reproduce**
1. Clone https://github.com/GuilhE/WhosNext
2. Bump `kotlinxCompose = "1.7.0-alpha01"`
3. Sync 

**Expected behavior**
Not failing

**Comment by eymar** [comment]
Trying to investigate.

It seems there is an issue in a combination of compose-multiplatform gradle plugin and `alias(libs.plugins.composeuiviewcontroller)`.

In other projects with compose-multiplatform plugin applied, there is no issue.

The error message suggest that the configuration was resolved and then a change of its attributes was attempted. Does your plugin (https://github.com/GuilhE/KMP-ComposeUIViewController) work with configurations and perhaps resolves them?

**Comment by GuilhE** [comment]
Hello @eymar , 
I've created a KSP lib to help me with some code generation, and the plugin heavy lifts the [configurations](https://github.com/GuilhE/KMP-ComposeUIViewController/blob/45f3d81dc50ee6d24963b0e9422770a4d0c7b9e1/sample/shared/build.gradle.kts) automatically, specially this:

```
iosMain.dependencies { implementation(libs.composeuiviewcontroller.annotations) }
listOf(iosX64(), iosArm64(), iosSimulatorArm64()).forEach { target ->
   target.binaries.framework { baseName = "MyFramework" }
   dependencies.add("ksp${target.name.replaceFirstChar { it.uppercaseChar() }}", libs.composeuiviewcontroller.ksp)
}
```        

I have not encountered any problems with Compose Multiplatform versions until now, if I downgrade to 1.6.11, everything works smoothly. What changes have been made in the newer versions that could potentially cause issues? What adjustments do I need to make in my library/plugin to resolve this situation? Although I am aware that version 1.7.0 is still in alpha, I hope that my library/plugin will remain compatible when it reaches Beta or RC status.

**Comment by GuilhE** [comment]
Still experimenting, but if I move those configurations to a `beforeEvaluate` block, the project build successfully.

**Comment by eymar** [comment]
Here is a PR and the file: https://github.com/JetBrains/compose-multiplatform/pull/4965/files#diff-11183ffee6bc1247f66a3f6c5e9c057a9b4cf32c6155f1622c2fb1893b95a09a The changes in that file are involved in the problem. 
___

cc: @terrakok Could it be related to AGP issues you mentioned?

**Comment by GuilhE** [comment]
> cc: @terrakok Could it be related to AGP issues you mentioned?

The sample included with the library is designed for iOS and JVM, which explains why it passes. However, the other two projects also target Android, causing them to fail. This could be a significant clue 🤔

**Comment by eymar** [comment]
I build locally the  lastest compose gradle plugin with this recent change: https://github.com/JetBrains/compose-multiplatform/pull/5076/files 

And then I used it in your project. And it works now.

So you can wait for the next 1.7.0-dev build to get the fix. 

You may try to build the gradle plugin yourself: https://github.com/JetBrains/compose-multiplatform/tree/master/gradle-plugins

```
./gradlew :compose:publishToMavenLocal -Pcompose.version=1.7.0-alpha01 -Pdeploy.version=24.7.8
```

And then set `kotlinxCompose = "24.7.8"`

**Comment by eymar** [comment]
If you don't mind, I close this one as fixed.
Feel free to ask any questions or reopen if needed.

**Comment by GuilhE** [comment]
I confirm that it works with `1.7.0-dev1721` 👍🏼

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5071">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
