### ISSUE TITLE
`const auctionConfig = {

### ISSUE THREAD

**Issue by Jakkapob850** [JetBrains/compose-multiplatform#5084]
`const auctionConfig = {
 // This should be the same origin as decisionLogicUrl below
 seller: "https://paapi-demo-ssp.local",
 decisionLogicUrl: "https://paapi-demo-ssp.local/decision-logic.js",
 
 // This should be a list of all DSPs that you wish to participate in this auction
 interestGroupBuyers: ['https://paapi-demo-dsp.local'],
 
 // This object will be available to all auction participants
 auctionSignals: { },
 
 // This object will only be available to the seller during scoreAd function
 sellerSignals: { },
 
 // This parameter is optional, and is only available to the Buyer of each object. This is data the seller explicitly provides to individual buyers.
 // Each key in this object should match an entry in the interestGroupBuyers array above
 perBuyerSignals: {
   "https://paapi-demo-dsp.local": { },
 },
};
 
async function runAuction(){
 // Run ad auction
 const opaqueUrl = await navigator.runAdAuction(auctionConfig);
 
 // Render ad
 const iframeEl = document.createElement('iframe');
 iframeEl.src = opaqueUrl;
 document.body.appendChild(iframeEl);
}
 
runAuction(); `

_Originally posted by @Jakkapob850 in https://github.com/JetBrains/kotlin-playground/issues/215#issuecomment-2217990123_

**Comment by Jakkapob850** [comment]
- const interestGroup = {
   name: "test",
 
   // This should be the origin where this file will be hosted
   // This should be the same origin as biddingLogicUrl below
   owner: "https://paapi-demo-dsp.local",
 
   // This script must have the same origin as the owner directly above
   // An example of bidding logic is provided in the next section.
   biddingLogicUrl: "https://paapi-demo-dsp.local/bidding-logic.js",
 
   // Protected Audience API requires that any ad that could be returned by bidding logic is listed here.
   // For this example there is only one ad which you will set up in Step 4.2
   ads: [{
       renderUrl: "https://paapi-demo-advertiser.local/ad.html",
   }],
};
 
document.addEventListener("DOMContentLoaded", (e) => {
   // An interest group expires in 30 days unless it is rejoined.
   // You can set a shorter expiration depending on your use case
   const kSecsPerDay = 3600;
   navigator.joinAdInterestGroup(interestGroup, kSecsPerDay * 24 * 30);
});

**Comment by Jakkapob850** [comment]
- [ ] function generateBid(interestGroup, auctionSignals, perBuyerSignals, trustedBiddingSignals, browserSignals) {
   return {
 
       // Free form object provided to Seller's scoreAd(...) function
       // alongside the bid that can be used to inform the
       // desirability score
       ad: {},
 
       // bid amount
       bid: 1,
 
       // This URL needs to match one of the URLs in the ads object provided to the interestGroup object during the call to joinAdInterestGroup.
       render: interestGroup.ads[0].renderUrl,
   };
}
 
// While this walkthrough won’t cover reporting, the current implementation of Protected Audience in Chrome will warn if reportWin() is not defined.
function reportWin(auctionSignals, perBuyerSignals, sellerSignals, browserSignals) {
   // UNIMPLEMENTED
}

**Comment by Jakkapob850** [comment]
### const frameConfig = await navigator.runAdAuction({
 // ...auction configuration
 resolveToConfig: true
});
 
if (window.FencedFrameConfig && frameConfig instanceof FencedFrameConfig) {
 const frame = document.createElement('fencedframe');
 frame.config = frameConfig;
}

**Comment by Jakkapob850** [comment]
_ <!DOCTYPE html>
 <body>
   <meta charset=utf-8>
   <meta name=viewport content="width=device-width,initial-scale=1">
   <title>Protected Audience Demo Ad</title>
 </head>
 <body>
   <svg id="circle" viewBox="0 0 100 100" height="100" width="100">
     <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
   </svg>
 </body>
 
</html>_

**Comment by eymar** [comment]
Closing this: no clear description of the issue/suggestion.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5084">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
