### ISSUE TITLE
Google chrome 

### ISSUE THREAD

**Issue by Jakkapob850** [JetBrains/compose-multiplatform#5085]
**Describe the problem**
Explain the performance issue you're experiencing, including the following details:

- What specific issue did you encounter? (e.g. missing frames, high CPU usage, memory leaks)
- Have you noticed any patterns or specific circumstances under which the problem occurs?

**Affected platforms**
Select one of the platforms below:
- All
- Desktop
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library
- iOS
- Other

If the problem is Android-only, report it in the [Jetpack Compose tracker](https://issuetracker.google.com/issues/new?component=612128)

**Versions**
- Kotlin version: 
- Compose Multiplatform version: 
- OS version(s) (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): 
- JDK (for desktop issues): 

**Sample code**
If possible, provide a small piece of code that reproduces the problem. If the code snippet is too large to paste here, please link to a Gist, a GitHub repo, or any other public code repository.

**Reproduction steps**
Please provide a detailed step-by-step guide on how to reproduce the issue you are experiencing.

**Video**
If you're reporting slow app work or missing frames, please provide a video of the problem.

**Profiling data**
Please provide any relevant profiling data that might be helpful. This could include information like FPS, memory usage, CPU time, or any other data that could provide insight into the performance issue.

**Additional information**
Provide any other details that you think might be helpful for us to understand the problem. This could include things like the system configuration, external factors, etc.

**Comment by Jakkapob850** [comment]
**_ function generateBid(interestGroup, auctionSignals, perBuyerSignals, trustedBiddingSignals, browserSignals) {
   return {
 
       // Free form object provided to Seller's scoreAd(...) function
       // alongside the bid that can be used to inform the
       // desirability score
       ad: {},
 
       // bid amount
       bid: 1,
 
       // This URL needs to match one of the URLs in the ads object provided to the interestGroup object during the call to joinAdInterestGroup.
       render: interestGroup.ads[0].renderUrl,
   };
}
 
// While this walkthrough won’t cover reporting, the current implementation of Protected Audience in Chrome will warn if reportWin() is not defined.
function reportWin(auctionSignals, perBuyerSignals, sellerSignals, browserSignals) {
   // UNIMPLEMENTED
}_**

**Comment by eymar** [comment]
Closing this: no clear description of the issue/suggestion.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5085">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
