### ISSUE TITLE
Chrome web store 

### ISSUE THREAD

**Issue by Jakkapob850** [JetBrains/compose-multiplatform#5086]
<!DOCTYPE html>
 <head>
   <meta charset=utf-8>
   <meta name=viewport content="width=device-width,initial-scale=1">
   <title>Protected Audience Demo Publisher</title>
   <script src="https://paapi-demo-ssp.local/run-ad-auction.js"></script>
 </head>
 <body>
   <h1>Protected Audience Demo Publisher</h1>
 </body>
</html>
 
 const auctionConfig = {
 // This should be the same origin as decisionLogicUrl below
 seller: "https://paapi-demo-ssp.local",
 decisionLogicUrl: "https://paapi-demo-ssp.local/decision-logic.js",
 
 // This should be a list of all DSPs that you wish to participate in this auction
 interestGroupBuyers: ['https://paapi-demo-dsp.local'],
 
 // This object will be available to all auction participants
 auctionSignals: { },
 
 // This object will only be available to the seller during scoreAd function
 sellerSignals: { },
 
 // This parameter is optional, and is only available to the Buyer of each object. This is data the seller explicitly provides to individual buyers.
 // Each key in this object should match an entry in the interestGroupBuyers array above
 perBuyerSignals: {
   "https://paapi-demo-dsp.local": { },
 },
};
 
async function runAuction(){
 // Run ad auction
 const opaqueUrl = await navigator.runAdAuction(auctionConfig);
 
 // Render ad
 const iframeEl = document.createElement('iframe');
 iframeEl.src = opaqueUrl;
 document.body.appendChild(iframeEl);
}
 
runAuction();
 
 Create a file at https://paapi-demo-ssp.local/decision-logic.js file with the following contents.  The script needs to define a [scoreAd(...)](https://developer.chrome.com/docs/privacy-sandbox/fledge-api/ad-auction/#scoread) function and a [reportResult(...)](https://developer.chrome.com/docs/privacy-sandbox/fledge-api/reports/#seller-reportresult) function.

function scoreAd(adMetadata, bid, auctionConfig, trustedScoringSignals, browserSignals) {
   // You can use any parameters provided to this function to define a desirability score.
   // For this example the original bid value of each bid becomes the desirability score. The score of each ad is compared automatically and the ad with the highest score is returned by the Protected Audience auction.
   return bid;
}
 
function reportResult(auctionConfig, browserSignals) {
   // this can be any information you wish to pass to the winning bidder’s reportWin function
   return {};
}

**Comment by Jakkapob850** [comment]
> <title>Protected Audience Demo Publisher</title> <script src="https://paapi-demo-ssp.local/run-ad-auction.js"></script>
> # Protected Audience Demo Publisher
> const auctionConfig = { // This should be the same origin as decisionLogicUrl below seller: "https://paapi-demo-ssp.local", decisionLogicUrl: "https://paapi-demo-ssp.local/decision-logic.js",
> 
> // This should be a list of all DSPs that you wish to participate in this auction interestGroupBuyers: ['https://paapi-demo-dsp.local'],
> 
> // This object will be available to all auction participants auctionSignals: { },
> 
> // This object will only be available to the seller during scoreAd function sellerSignals: { },
> 
> // This parameter is optional, and is only available to the Buyer of each object. This is data the seller explicitly provides to individual buyers. // Each key in this object should match an entry in the interestGroupBuyers array above perBuyerSignals: { "https://paapi-demo-dsp.local": { }, }, };
> 
> async function runAuction(){ // Run ad auction const opaqueUrl = await navigator.runAdAuction(auctionConfig);
> 
> // Render ad const iframeEl = document.createElement('iframe'); iframeEl.src = opaqueUrl; document.body.appendChild(iframeEl); }
> 
> runAuction();
> 
> Create a file at https://paapi-demo-ssp.local/decision-logic.js file with the following contents. The script needs to define a [scoreAd(...)](https://developer.chrome.com/docs/privacy-sandbox/fledge-api/ad-auction/#scoread) function and a [reportResult(...)](https://developer.chrome.com/docs/privacy-sandbox/fledge-api/reports/#seller-reportresult) function.
> 
> function scoreAd(adMetadata, bid, auctionConfig, trustedScoringSignals, browserSignals) { // You can use any parameters provided to this function to define a desirability score. // For this example the original bid value of each bid becomes the desirability score. The score of each ad is compared automatically and the ad with the highest score is returned by the Protected Audience auction. return bid; }
> 
> function reportResult(auctionConfig, browserSignals) { // this can be any information you wish to pass to the winning bidder’s reportWin function return {}; }

**Comment by eymar** [comment]
Closing this: no clear description of the issue/suggestion. 

The description is not relevant/doesn't make sense.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5086">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
