### ISSUE TITLE
iOS: ModalBottomSheet can't ignore safeArea

### ISSUE THREAD

**Issue by kingsword09** [JetBrains/compose-multiplatform#5089]
**Describe the bug**
iOS platform ModalBottomSheet can't ignore safeArea, Causes a blank area to appear bottom.

**Affected platforms**

- iOS
**Versions**
- Libraries:
  - Compose Multiplatform version: 1.7.0-alpha01、1.7.0-dev1721
  - ...
- Kotlin version: 2.0.0、2.0.0-beta01
- OS version(s) (required for Desktop and iOS issues): iOS 17.5
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): all
- JDK (for desktop issues): 17

**To Reproduce**
1. Run this code snippet:
  ContentView.swift
  ```swift
  
import UIKit
import SwiftUI
import ComposeApp

struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        MainViewControllerKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}

struct ContentView: View {
    var body: some View {
        ComposeView()
                .ignoresSafeArea(.all) // Compose has own keyboard handler
    }
}
  ```

   ```kt
   @OptIn(ExperimentalMaterial3Api::class)
@Composable
fun App() {
    MaterialTheme {
      var showContent by remember { mutableStateOf(false) }
      Column(
        Modifier.fillMaxWidth().padding(top = 100.dp),
        horizontalAlignment = Alignment.CenterHorizontally
      ) {
        Button(onClick = { showContent = !showContent }) {
          Text("Click me!")
        }
      }
  
      if (showContent) {
        ModalBottomSheet(
          onDismissRequest = { showContent = !showContent },
          modifier = Modifier.fillMaxSize(),
          sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
        ) {
          Text("ModalBottomSheet")
        }
      }
    }
}
   ```
3. Click on 'Click me!'

**Expected behavior**
ignore safeArea

**Screenshots**
![image](https://github.com/JetBrains/compose-multiplatform/assets/19650362/9accfb13-3ef6-41e2-bc55-20337df71b72)

**Additional context**
DialogProperties usePlatformInsets property?

**Comment by kingsword09** [comment]
@MatkovIvan

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5089">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
