### ISSUE TITLE
[WASM] Custom Font Text flickering from tofu to the actual text with the right font

### ISSUE THREAD

**Issue by Shusshu** [JetBrains/compose-multiplatform#5094]
**Describe the bug**
When opening the wasm website the text font changes from tofu to the actual text with the right font

**Affected platforms**
- Web (K/Wasm) - Canvas based API

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.6.11 & 1.7.0-xxx
  - Navigation Multiplatform version (for related issues):
  
- Kotlin version: 2.0.0 & 2.0.20-beta1 & 2.0.20-beta2-48

**To Reproduce**
1. Clone project https://github.com/Shusshu/wasm-fonts-issue
2. Run this code snippet:
   ```
   ./gradlew wasmJsBrowserRun
   ```
3. See the flickering issue

**Expected behavior**
Text is shown directly in the right font

**Comment by eymar** [comment]
To get rid of flickering (or at least improve it), please have a look at the comments here: https://github.com/JetBrains/compose-multiplatform/issues/4968

**Comment by Shusshu** [comment]
Thanks for the tips - the perf improvement is definitely there but the issue persist.

@eymar could you check my commit here https://github.com/Shusshu/wasm-fonts-issue/commit/ba39a38d1ca6d8ed511bd28d8f2d43ee929aaee9

**Comment by Shusshu** [comment]
@eymar I allow myself to bump this as it might have been forgotten or you might be on holiday.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5984">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
