### ISSUE TITLE
Important: please use YouTrack for bugs and feature requests

### ISSUE THREAD

**Issue by kropp** [JetBrains/compose-multiplatform#5102]
Hey everyone,

As you may have seen we’ve disabled new issue form on GitHub and imported all existing issues to JetBrains’ YouTrack.

There are several reasons for that:
It streamlines our internal processes and allows us to use a single tool for all work management.
Enables closer interaction with related teams at JetBrains (Kotlin/Native, Build Tools, Release, QA, Tech Writing, Tooling, etc.)

We value community contributions a lot. If you regularly post issues to GitHub, we encourage you to [submit issues to YouTrack](https://youtrack.jetbrains.com/newIssue?project=CMP). You can conveniently authorize there with your GitHub account. And our GitHub repo is open for PRs as before.

If you have a question consider asking it at StackOverlow with `compose-multiplatform` tag https://stackoverflow.com/questions/tagged/compose-multiplatform

Feel free to discuss any related questions on `#compose-ios`, `#compose-desktop`, or `#compose-web` channels in Slack workspace for Kotlin community. Get your invite at  https://slack.kotl.in/.

Hope to hear from you soon!

**Comment by alexstyl** [comment]
Quick jump to [view All issues](https://youtrack.jetbrains.com/issues?q=project:%20%7BCompose%20Multiplatform%7D)
