### ISSUE TITLE
Some components doesn't react to density changes

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#528]
0.4.0-build174

When we move a window to another screen with a different density (scale), or just change density in the system settings, some of the components doesn't change their size.

Known components:
- FloatingActionButton
- text inside Scaffold(topBar = { TopAppBar(title = { Text("text") } ) } )
- vectorXmlResource (it changes size, but leaves "dirty" background)

How to reproduce:
./gradlew run1  -Pandroidx.compose.multiplatformEnabled=true
in androidx repo

**Comment by igordmn** [comment]
Probably the root cause is common - all components were inside `Scaffold`. Maybe somewhere inside it we don't take into account density changing.

**Comment by Rsedaikin** [comment]
Also `androidx.compose.ui.layout.Layout`
```
Layout(
        content = {},
        modifier = modifier.onGloballyPositioned { childCoordinates ->
            val coordinates = childCoordinates.parentCoordinates!!
            val size = coordinates.size // the size does not change
            ...
```

**Comment by igordmn** [comment]
> FloatingActionButton

Seems fixed

> text inside Scaffold(topBar = { TopAppBar(title = { Text("text") } ) } )

see https://issuetracker.google.com/issues/189170789

> vectorXmlResource (it changes size, but leaves "dirty" background)

see https://github.com/JetBrains/compose-jb/issues/677

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5468">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
