### ISSUE TITLE
Weird keyboard behavior in JCEF demo

### ISSUE THREAD

**Issue by bjonnh** [JetBrains/compose-multiplatform#529]
Under Linux Wayland (Sway),

Pressing enter on the JCEF demo (in the browser) does nothing and displays:
[0322/120748.585200:WARNING:keyboard_code_conversion_x.cc(1445)] Unknown keycode:0

Escape does the same, as well as classical text editing Ctrl+A , shift-home …

When a text is selected and Ctrl is pressed, the text disappears.

Some of those keys work properly in the url bar (but not enter).

**Comment by olonho** [comment]
JCEF is not yet fully functional, but if you could perform further analysis of what's going on - it would be valuable.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5467">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
