### ISSUE TITLE
No accurate way to retrieve desktop screen DPI

### ISSUE THREAD

**Issue by opatry** [JetBrains/compose-multiplatform#531]
I quote Adam Powell [G] from Kotlin slack:
> density is a function of dpi. `density = screenDpi / 160.0`

So, I used `LocalDensity.current.density` but the value doesn't seems what I expect.

I expect to have the same value `AwtToolkit.getDefaultToolkit().screenResolution`.

I run on an iMac macOS Catalina, AWT returns 102 for my screen, and the above computation returns 160 (because the returned density is 1).

It doesn't seem to have an accurate way to retrieve screen DPI on desktop so far.

**Comment by olonho** [comment]
Why cannot one use AWT method?

**Comment by opatry** [comment]
I can, but following the discussion we had with Adam Powell, he told me to raise such issue because it might be better to deal with this with Compose API (also, that was my initial expectations, why some elements comes from `LocalDensity` and others from AWT? Why not having a common API for Android & Desktop?)

Here is the link to the discussion on Slack: https://kotlinlang.slack.com/archives/CJLTWPH7S/p1616458290446700?thread_ts=1616433010.402600&cid=CJLTWPH7S

I quote Adam:
> The density system compose uses is inherited from Android where it's a function of screen dpi but rounded into buckets. It's not exact by design, but I would have expected 102 to be rounded into a 120dpi bucket or similar.

and
> Please file a bug, we should get a standard of compatible buckets worked out for desktop sooner rather than later. A lot of people are probably going to be surprised by the change in existing code behavior for any fix we do

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5465">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
