### ISSUE TITLE
Ability to have non-Compose JVM targets 

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [JetBrains/compose-multiplatform#537]
See the following discussions:
* https://kotlinlang.slack.com/archives/C01D6HTPATV/p1616688529214100
* https://kotlinlang.slack.com/archives/C3PQML5NU/p1614816886156900

Currently using Compose Gradle plugin 
configures Compose compiler plugin for all targets.
This may add compiler overhead, force using IR backend
and force to depend on Compose runtime (?), which may not be
desirable for non-Desktop targets.

There are the following possibilities to tackle the issue:
1. Add ability to opt-in applying Compose to JVM MPP targets;
2. Add ability to opt-out of applying Compose to JVM MPP targets;
3. Wait for [KT-27217](https://youtrack.jetbrains.com/issue/KT-27217) to be fixed;
4. Make adding Compose compiler plugin to Kotlin compiler plugin classpath cost free (i.e. no exceptions and no additional work if a target does not use IR backend or does not depend on Compose runtime).

**Comment by AlexeyTsvetkov** [comment]
We discussed the issue and decided to change the plugin, so that the plugin is applied automatically to a single JVM target, but if there are multiple (non-Android) JVM targets, Compose targets will have to be specified explicitly. This would not affect Android targets.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5460">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
