### ISSUE TITLE
Why Windows shows description instead of packageName?

### ISSUE THREAD

**Issue by theapache64** [JetBrains/compose-multiplatform#542]
**build.gradle.kts**

```kotlin
nativeDistributions {
    packageName = "Stackzy"
    description = "An application to identify libraries used inside an android application"
}
```

**In Windows**

![image](https://user-images.githubusercontent.com/9678279/112733268-dcde7480-8f64-11eb-918e-233d1c822797.png)

Is this expected? :thinking:

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5455">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
