### ISSUE TITLE
Window content flickering (randomly getting black when mouse moves)

### ISSUE THREAD

**Issue by mpointner** [JetBrains/compose-multiplatform#553]
I just tried out the demo applications for Jetpack compose and on like every second start the window content flickers when moving with the mouse around:

![lJ4K1DHaBj](https://user-images.githubusercontent.com/9437366/113272874-60d58b00-92dc-11eb-83b6-5dda01683dcc.gif)

Sometimes it also stays completely black at certain cursor positions.

### System:
Windows 10 x64
Intellij Ultimate 2020.3.3 build 203.7717.56
OpenJDK 64-Bit Server VM Corretto-11.0.8.10.1
SDK Android 8.0
Intel(R) HD Graficis 4600 (Monitor connected to this graphics card)
NVIDIA GeForce RTX 2060

### Output:
```
11:30:30: Executing task 'run'...

Executing tasks: [run] in project C:\Users\Michael\Documents\Projects\compose-jb-master\examples\codeviewer\desktop


> Configure project :common
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.


> Task :common:compileKotlinDesktop UP-TO-DATE
> Task :common:desktopProcessResources UP-TO-DATE
> Task :common:desktopMainClasses UP-TO-DATE
> Task :common:desktopJar UP-TO-DATE
> Task :desktop:compileKotlinJvm UP-TO-DATE
> Task :desktop:jvmProcessResources UP-TO-DATE
> Task :desktop:jvmMainClasses UP-TO-DATE
> Task :desktop:jvmJar UP-TO-DATE

> Task :desktop:run
The os does not support: 'Taskbar.setIconImage'
```

Whenever the flickering happens, the application also crashes when I try to resize the window:

```
> Task :desktop:run
The os does not support: 'Taskbar.setIconImage'
Failed Direct3D call. Error: 0x887a0001
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ff9f60ed759, pid=2756, tid=18528
#
# JRE version: OpenJDK Runtime Environment Corretto-11.0.8.10.1 (11.0.8+10) (build 11.0.8+10-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-11.0.8.10.1 (11.0.8+10-LTS, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [KERNELBASE.dll+0x2d759]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Michael\Documents\Projects\compose-jb-master\examples\codeviewer\desktop\hs_err_pid2756.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

> Task :desktop:run FAILED

Execution failed for task ':desktop:run'.
> Process 'command 'C:\Program Files\Amazon Corretto\jdk11.0.8_10\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

### VM crash dump:
[hs_err_pid25920.log](https://github.com/JetBrains/compose-jb/files/6244396/hs_err_pid25920.log)

With **SKIKO_RENDER_API=OPENGL** as environment variable it works just fine.

**Comment by olonho** [comment]
Maybe new Angle-based renderer may help here.

**Comment by olonho** [comment]
Please attach VM crashdump, or at least stacktrace from it.

**Comment by mpointner** [comment]
Added the stacktrace, how do I get the VW crash dump?

**Comment by olonho** [comment]
From file like `C:\Users\Michael\Documents\Projects\compose-jb-master\examples\codeviewer\desktop\hs_err_pid2756.log`. Also what is exact videocard model?
And what if you'll use OpenGL renderer?

**Comment by mpointner** [comment]
Updated the description with the crashdump.
With **SKIKO_RENDER_API=OPENGL** as environment variable it works just fine.

**Comment by mpointner** [comment]
@olonho did you find something out from the crashdump that could fix it for the default renderer?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5449">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
