### ISSUE TITLE
onLongClick blocking clicked element

### ISSUE THREAD

**Issue by Exidel** [JetBrains/compose-multiplatform#554]
Continuing issue #540. 
If using `onLongClick = {}` to popup `dropdownMenu` it locking clicked item, after dismiss `ddMenu` you need to click on it to unlock and once again to select. 
This issue affecting only on selected with `onLongClick` element. So programm think what the pressed mouse button wasn't released.

https://user-images.githubusercontent.com/80458677/113281778-b0bd4d80-92ee-11eb-9cad-a2c3b8edac5b.mp4

**Comment by akurasov** [comment]
@Exidel could you please share your code for such behavior?

**Comment by Exidel** [comment]
I was reproduced this issue again.  The same result + ContextMenu lil bug.


https://user-images.githubusercontent.com/80458677/126193716-4440289a-1c9a-4f6b-9d08-52e2ba231f5f.mp4

diffirence with old one: 
newer version of compose (0.5.0-build245)
newer version of Kotlin (1.5.10)
used ContextMenu instead of DropdownMenu + pointerInputFilter (for mouse position) in old

<details>
<summary>TestCode</summary>

```
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.*
import androidx.compose.material.ContextMenu
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.WindowSize
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState


@OptIn(ExperimentalComposeUiApi::class)
fun main() = application {

    var mainWin = rememberWindowState(size = WindowSize(600.dp, 500.dp))

    Window(
        state = mainWin,
        title = "BugTest",
        onCloseRequest = { exitApplication() }
    ) {

        MainView()

    }


}


@OptIn(ExperimentalFoundationApi::class)
@Composable
fun MainView() {

    var index by remember { mutableStateOf(0) }
    var expand by remember { mutableStateOf(false) }

    Box(Modifier.fillMaxSize()) {


        Box(Modifier.padding(10.dp).size(250.dp, 500.dp).border(5.dp, Color.Red).align(Alignment.TopStart)) {

            Column(Modifier.size(200.dp, 400.dp).align(Alignment.Center).background(Color.Yellow)) {
                for (i in 1..20) {
                    Text( text = "item$i", modifier = Modifier.fillMaxWidth().combinedClickable(
                        onClick = { index = i },
                        onLongClick = { index = i; expand = true }
                    ) )
                }
            }

        }


        Box(Modifier.padding(10.dp).size(250.dp, 500.dp).border(5.dp, Color.Green).align(Alignment.TopEnd)) {
            Text(text = "$index", Modifier.align(Alignment.Center))
        }

        if (expand) {
            DropdownToContextMenu(expand, { expand = it })
        }

    }

}

@Composable
fun DropdownToContextMenu(expand: Boolean, expandLamb: (Boolean) -> Unit) {

    ContextMenu(
        expanded = expand,
        onDismissRequest = { expandLamb(false) }
    ) { Text("ForExample") }

}
```

</details>

**Comment by akurasov** [comment]
By the issue you mean, that in case of long click, ordinary onClick is not triggered?

**Comment by akurasov** [comment]
Thank you! 

Played with the code a bit. Without ContextMenu clickable works fine. When contextMenu is added, the hover stays over text even when long click is completed. However adding it to ordinary click doesn't lead to such behavior.

**Comment by Exidel** [comment]
I think opened ContextMenu get focus which prevent longClick to be completed. If i remember right ContextMenu and DropdownMenu based on Frame underhood like a Window and Dialog and when it in focus all mouse events got from this Frame.
When I was using pointerMoveFilter to got current cursor position for the DropdownMenu in test it showed diffirent numbers when cursor hover main window and DropdownMenu.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5448">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
