### ISSUE TITLE
Window white line on the bottom before resizing

### ISSUE THREAD

**Issue by TheMrCodes** [JetBrains/compose-multiplatform#555]
Wenn I use a Box with backgroundcolor modifier it results in this weard thing where it shows a white Line (the real background color of the window) on the bottom of the screen

![image](https://user-images.githubusercontent.com/28106561/113328450-9732fa80-931c-11eb-9650-f94314dfbffb.png)

This bug got discussed on in the #compose -desktop slack channel under 
https://kotlinlang.slack.com/archives/C01D6HTPATV/p1617269489331100

Igor Demin [JB] :
> This was supposed to help:
```
fun main() = SwingUtilities.invokeLater {
    val window = AppWindow()
    window.window.background = java.awt.Color.BLACK
    window.window.contentPane.background = java.awt.Color.BLACK
    window.show {
        Box(Modifier.fillMaxSize().background(Color.Black))
    }
}
```
> But we still have a white line. It disappears only after resize.
> A white line isn't pretty, so we will figure something in the future.
> Maybe it is the issue in our renderer.

**Comment by igordmn** [comment]
Similar [issue](https://github.com/JetBrains/compose-jb/issues/179).

Maybe they have common cause, maybe not.

> I guess this is the result of rounding to pixels but it resolves in an unwanted behavior

Yes, it looks like rounding error. Maybe on Swing side, maybe on [skiko](https://github.com/JetBrains/skiko) side.

My guess - it only happens when scale in the system is not 100% (but not sure).

**Comment by hristogochev** [comment]
If we resize the window automatically, the white lines will be replaced by whatever color we specify:

``` kotlin
fun main() = application {

    val windowState = rememberWindowState(size = DpSize(890.dp, 648.dp))

    Window(state = windowState, onCloseRequest = ::exitApplication) {

        LaunchedEffect(key1 = Unit) {
            window.background = java.awt.Color.BLACK
            window.contentPane.background = java.awt.Color.BLACK
            window.size = Dimension(window.width + 1, window.height)
            delay(1)
            window.size = Dimension(window.width - 1, window.height)
        }

        Box(modifier = Modifier.fillMaxSize().background(Color.Black)) {

        }
    }
}
```

**Comment by PMARZV** [comment]
For me (Windows 11), it only happens when window is maximized and scale is 125%

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5447">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
