### ISSUE TITLE
Resize window immediately after dragging it to another monitor with different density

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#56]
Most applications will resize their windows immediately. Compose windows don't resized before releasing left mouse button:
![ezgif-3-33d545145757](https://user-images.githubusercontent.com/5963351/98245238-af773700-1f81-11eb-866c-66fd103fcf49.gif)

How it is happening with native window on Windows:
![ezgif-3-47c445f0b65b](https://user-images.githubusercontent.com/5963351/98245375-e2b9c600-1f81-11eb-9d06-72345a9475ce.gif)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6392">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
