### ISSUE TITLE
Button should click after mousedown-dragaway-dragback-mouseup

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-multiplatform#567]
As per https://kotlinlang.slack.com/archives/C01D6HTPATV/p1617733261405800 the mouse behavior should differ from the touch behavior here.

Problem statement from @orangy :
> In modern OSes when you push the button (but don’t release the mouse!), move cursors away from button it gets depressed, and if you release it, no click is registered. All fine here. But, if you don’t release mouse after moving away, and move cursor back into button area, it gets pressed back and if you release the mouse the click is registered. This is not working in Compose (desktop).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5441">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
