### ISSUE TITLE
Support OS font scale

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#57]
Font size can be changed on Windows 10 in Settings - Ease of Access - Make text bigger:
![image](https://user-images.githubusercontent.com/5963351/98245549-244a7100-1f82-11eb-8f3c-f861ab7b052c.png)

On Ubuntu in Settings - Universal Access - Large Text:
![image](https://user-images.githubusercontent.com/5963351/98245563-290f2500-1f82-11eb-8624-2481ff0e03c4.png)

On macOS there is no such setting

See FrameSkiaLayer.detectCurrentDensity

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6391">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
