### ISSUE TITLE
Incorrect value for firstVisibleItemIndex in lazy column with sticky header

### ISSUE THREAD

**Issue by samuelprince77** [JetBrains/compose-multiplatform#591]
While working with a lazy column that has a sticky header, the value for firstVisibleItemIndex seems to be incorrect. It returns the next "fully visible index" even though the previous index is still partially visible. This seems to happen at the point where the currently visible index reaches the top of the sticky header, at that point, the firstVisibleItemIndex automatically returns the next index in the list even though the previous item might be partially visible.

Without the sticky header, the behaviour is such that only once the item is fully invisible, does it return the next index as the value for firstVisibleItemIndex. This behaviour with the sticky header leads to incorrect calculations that make use of this value, creating strange UI states.

Using the custom adapter linked in this issue: https://github.com/JetBrains/compose-jb/issues/181#issuecomment-787070067 and using the IntellijPlugin sample here: http://github.com/JetBrains/compose-jb/tree/master/examples/intelliJPlugin i can reproduce this behaviour when i add a sticky header to the list

```
@OptIn(ExperimentalFoundationApi::class)
@Composable
fun LazyScrollable() {
    MaterialTheme {
        DesktopTheme {
            Box(
                modifier = Modifier.fillMaxSize()
                    .padding(10.dp)
            ) {

                val state = rememberLazyListState()
                val itemCount = 100

                LazyColumn(Modifier.fillMaxSize().padding(end = 12.dp), state) {
                    stickyHeader {
                        Text(
                            color = Color.White,
                            modifier = Modifier
                                .fillMaxWidth()
                                .background(Color.Transparent)
                                .wrapContentWidth(Alignment.CenterHorizontally)
                                .padding(
                                    PaddingValues(
                                        bottom = 16.dp,
                                        end = 0.dp,
                                        start = 16.dp,
                                        top = 4.dp
                                    )
                                ),
                            text = "Sample Sticky header",
                        )
                    }
                    items(itemCount) { x ->
                        TextBox("Item in ScrollableColumn #$x")
                        Spacer(modifier = Modifier.height(5.dp))
                    }
                }
                VerticalScrollbar(
                    adapter = CustomScrollAdapter(state),
                    modifier = Modifier.align(Alignment.CenterEnd).fillMaxHeight(),
                )
            }
        }
    }
}

@Composable
private fun TextBox(text: String = "Item") {
    Surface(
        color = Color(135, 135, 135, 40),
        shape = RoundedCornerShape(4.dp)
    ) {
        Box(
            modifier = Modifier.height(52.dp)
                .fillMaxWidth()
                .padding(start = 10.dp),
            contentAlignment = Alignment.CenterStart
        ) {
            Text(text = text)
        }
    }
}

```

Here is a screen shot of the point where the "transition" of firstVisibleItemIndex happens. Included one that is transparent and one that is colored to highlight the effect

![Screenshot 2021-04-15 at 23 09 51](https://user-images.githubusercontent.com/13033740/114939231-71d7dd80-9e40-11eb-8d0b-6d4c7949afa7.png)

![Screenshot 2021-04-15 at 23 14 11](https://user-images.githubusercontent.com/13033740/114939233-72707400-9e40-11eb-9ae8-bb25e9116ead.png)

**Comment by olonho** [comment]
Does such behaviour exist  on Android as well? If so, please report to Google's issue tracker.

**Comment by samuelprince77** [comment]
@olonho I'm not sure if it is the same on android, are ScrollBars implemented on android? Last i checked, they were only implemented for compose desktop

**Comment by samuelprince77** [comment]
Yes, it behaves the same on android, linking the goggle issue tracker here: https://issuetracker.google.com/issues/185916470

**Comment by Dominaezzz** [comment]
Looks like the issue has been fixed?

**Comment by akurasov** [comment]
2check if it is fine in desktop now

**Comment by m-sasha** [comment]
It's just the intended behavior of `LazyListState`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6057">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
