### ISSUE TITLE
Application Tray Icon not configured on Linux Desktop with Gnome (images and icons tutorial)

### ISSUE THREAD

**Issue by fauxvillage** [JetBrains/compose-multiplatform#595]
Tutorial for image and icon manipulation has section for configuring an application tray icon (https://github.com/JetBrains/compose-jb/tree/master/tutorials/Image_And_Icons_Manipulations#setting-the-application-tray-icon) 

Unfortunately, it does not affect the tray icon's menu, even when packaged and installed.

I have tested this on Red Hat 8.3 and Ubuntu 20.04 with Gnome 3.32 and 3.36 respectively; both with JDK 15 (oracle)

Results are the same for compose 0.3.1, 0.3.2, 0.4.0build183 and their respective kotlin versions 1.4.31 and .32

additionally:  desktop for rpm package is not yet an available task; with debian, setting the application window icon example only works for first method, not the second (using setIcon method) and needs to be run as installed application to display icon properly

this previous, related issue seems to suggest that Gnome is the problem source; but is it? https://github.com/JetBrains/compose-jb/issues/65

**Comment by soloturn** [comment]
@fauxvillage what is a "tray icon" on macosX or gnome, and what does it do?

**Comment by fauxvillage** [comment]
the "tray" or "system tray" is a desktop panel showing running programs, usually including an "actions" menu when right-clicked

**Comment by fauxvillage** [comment]
@soloturn 
the "tray" or "system tray" is a desktop panel showing running programs, usually including an "actions" menu when right-clicked

**Comment by olonho** [comment]
We're not currently planning to support many distinct Linux package managers ourselves, but practically there are tools for such conversions available, i.e https://www.thegeekstuff.com/2010/11/alien-command-examples/.

**Comment by fauxvillage** [comment]
it appears from the current documentation that support for ".deb" and ".rpm" is a goal; and I think it is a fine tutorial without being able to package for both

I agree the challenge with Linux is the many "flavors" of desktops and window managers

It seems, too that Gnome has a substantial enough installation base that it warrants being used as a default Linux desktop; I'm guessing that as I learn more about this, I'll see why the previous statement is wrong (perhaps that should be my tagline)

Thanks for the great work you guys are doing and the help you provide here

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6361">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
