### ISSUE TITLE
combinedClickable onClick is different then clickable onClick

### ISSUE THREAD

**Issue by atoktoto** [JetBrains/compose-multiplatform#604]
Seems like `Modifier.combinedClickable()` fires `onClick` on mouse down event while `Modifier.clickable()` fires on mouse up. Is there a way to handle mouse down event and long-press or double click event in the same Composable without measuring time between clicks :) ?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-604">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
