### ISSUE TITLE
Tab character not rendered in a TextField

### ISSUE THREAD

**Issue by atoktoto** [JetBrains/compose-multiplatform#615]
Compose: 0.4.0-build183
Os: Windows 10

When tab character is pasted in, it is rendered as a square:
![obraz](https://user-images.githubusercontent.com/34739613/116104074-727a3a80-a6b0-11eb-940e-497ad3e28d21.png)
Curiously, when it is the only character in a line, it is rendered correctly.

**Comment by Icyrockton** [comment]
Is there any progress on this bug?

**Comment by akurasov** [comment]
On Mac it is fine

**Comment by igordmn** [comment]
Reproduced on Windows:

https://user-images.githubusercontent.com/5963351/144247630-ddb89ce9-8742-4249-98fd-e38bc5a0b9c9.mp4

**Comment by maffelbaffel** [comment]
Same on Linux. 

I actually expected tab to focus the next input, but that does not work for me.
Instead the tab is badly rendered.

**Comment by igordmn** [comment]
> Maybe this is the fault? https://bugs.chromium.org/p/skia/issues/detail?id=12334
(https://github.com/JetBrains/compose-jb/issues/2626#issuecomment-1384287879)

To fix the issue, we should update to the new Skia, and call `setReplaceTabCharacters(true)`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6071">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
