### ISSUE TITLE
Inputting emoji into a TextField breaks text selection of empty lines

### ISSUE THREAD

**Issue by atoktoto** [JetBrains/compose-multiplatform#616]
![selection1](https://user-images.githubusercontent.com/34739613/116105746-e49f4f00-a6b1-11eb-9b87-7b7e9e772bac.gif)
![selection3](https://user-images.githubusercontent.com/34739613/116105978-1ca69200-a6b2-11eb-97d9-95338ac911d1.gif)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6096">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
