### ISSUE TITLE
Emoji not rendered in TextField if it is the first non-whiltespace character

### ISSUE THREAD

**Issue by atoktoto** [JetBrains/compose-multiplatform#617]
OS: Windows 10
Compose: 0.4.0-build184

![emoji3](https://user-images.githubusercontent.com/34739613/116106970-e0bffc80-a6b2-11eb-8d61-49c6e650259b.gif)

**Comment by malliaridis** [comment]
Can confirm this issue on `0.4.0-build185`. Occurs however only if there is a line break before. When only an emoji is typed in it is rendered properly.

**Comment by malliaridis** [comment]
No more an issue in `0.4.0-rc2`. @atoktoto can you confirm that?

**Comment by akurasov** [comment]
@atoktoto do you still have this issue?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6097">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
