### ISSUE TITLE
Loading resources in intellij plugins require classloader to be explicitly specified

### ISSUE THREAD

**Issue by samuelprince77** [JetBrains/compose-multiplatform#618]
While trying to load resources(images, vectors etc, from resources folder) from an intellij plugin context, we get the error 
```ERROR` - llij.ide.plugins.PluginManager - Resource * not found```. 

The only way to fix this is by adding this line somewhere before the resource is loaded
```Thread.currentThread().contextClassLoader = SomeClassInYourPlugin::class.java.classLoader```

Perhaps this could be something that should be documented somewhere if it is the intended behaviour.

**Comment by olonho** [comment]
Guess it could also be fixed by having an additional argument with proper default value.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6099">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
