### ISSUE TITLE
Size is handled incorrectly for text InlineContent

### ISSUE THREAD

**Issue by tchernykh** [JetBrains/compose-multiplatform#621]
I am trying to use simple InlineTextContent according to the sample: https://developer.android.com/reference/kotlin/androidx/compose/foundation/text/InlineTextContent
Here is full code for the composable:
```Kotlin
@Composable
fun issue() {
    val myId = "inlineContent"
    MaterialTheme {
        BasicText(
            text = buildAnnotatedString {
                append("Hello")
                appendInlineContent(myId, "[myBox]")
                append("world")
            },
            inlineContent = mapOf(
                myId to InlineTextContent(
                    Placeholder(
                        width = 50.sp,
                        height = 5.sp,
                        placeholderVerticalAlign = PlaceholderVerticalAlign.AboveBaseline
                    )
                ) {
                    Box(modifier = Modifier.fillMaxSize().background(color = Color.Red))
                }
            )
        )
    }
}
```
Jetpack Desktop shows that incorrectly like square while it should be shown as a rectangle. Android shows the same sample correctly.
Desktop: 
<img width="166" alt="Desktop - wrong" src="https://user-images.githubusercontent.com/8757071/116426134-30a2ed00-a886-11eb-9e9c-c22d0c8174d3.png">
vs
Android: 
<img width="147" alt="Android - correct" src="https://user-images.githubusercontent.com/8757071/116426185-3c8eaf00-a886-11eb-98dc-4193da3bf665.png">

OS: MacOS
Library version: 0.3.2 and 0.4.0-build182

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6098">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
