### ISSUE TITLE
Desktop: Touch slop support for touch devices on desktop platforms

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#644]
Android uses specific distance to differentiate between touch drag and touch click (`ViewConfiguration.touchSlop`).
On desktop we significally decrease the touch slop in https://android-review.googlesource.com/c/platform/frameworks/support/+/1698450.
Unwanted drags on desktop are usually prevented by the friction between mouse and surface.

The open question - should we use a different touch slop when we use a touch screen on desktop?
(for example on Microsoft Surface)

We should investigate on the real touch devices:
- to know if touch slop is implemented on the driver level, or not
- if not - should we use a bigger slop in Compose 
- to know how macOs/Windows/Linux handle this

**Comment by igordmn** [comment]
See also:
https://github.com/JetBrains/compose-jb/issues/343
https://github.com/JetBrains/compose-jb/issues/325

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6429">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
