### ISSUE TITLE
Desktop: fix test DesktopFontTest.findTypeface for Windows and Linux

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#647]
Currently it works only on macOs.

It disabled for Windows/Linux [here](https://android-review.googlesource.com/c/platform/frameworks/support/+/1698446/1/compose/ui/ui-text/src/desktopTest/kotlin/androidx/compose/ui/text/DesktopFontTest.kt#87)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6360">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
