### ISSUE TITLE
Desktop: Issue with SelectionContainer

### ISSUE THREAD

**Issue by SaiNageswarS** [JetBrains/compose-multiplatform#650]
Error: Another selectable with the id  has already subscribed.

I have a scrollable layout of cards. Each card has a SelectionContainer. When a new card is added, sometimes above error comes up.

Repo: https://github.com/SaiNageswarS/Omnishell
https://github.com/SaiNageswarS/Omnishell/commit/7cd08d7bd9af67f092628c68f8073ff2b5df4364#diff-28887f92513afa6e17d8df16d0d200dffd5683d6d72764631bd850c85cfbee4dR19

Steps to reproduce:
1. Run project using "gradle run"
2. Enter date
3. Enter ls
4. Enter "npm init"
5. After package.json is created, enter another command say "ls"

**Comment by anye6488** [comment]
I also encountered this issue in version 1.4.0-alpha01-dev1003. I added SelectionContainer to each item in LazyColumn.

**Comment by jerryion** [comment]
I also encountered this issue

**Comment by wispborne** [comment]
Compose 1.5.10-beta02.
I encountered this but was able to fix it by wrapping only the individual widgets that needed to be selectable with `SelectionContainer`, rather than wrapping their parent container(s) with a single `SelectionContainer`.

**Comment by zacharee** [comment]
I've been running into this too, on iOS with 1.5.0-dev1357. 

It looks like wrapping a `SelectionContainer` around a composable that has an `AnimatedVisibility` causes this to be thrown when the visibility changes.

**Comment by p-vorobyev** [comment]
Also had the same error with `SelectionContainer ` inside `LazyColumn` until the `key` for the `items` was specified correctly.

Example:
```
LazyColumn(modifier = Modifier.background(Color.White).fillMaxSize().padding(start = 5.dp, end = 12.dp), verticalArrangement = Arrangement.Bottom, state = chatHistoryListState) {
                val messageCardColor = Color(0xFFF7F4F4)
                val headerColor = Color(0xFF95C2F0)

                val contentLoaderCodec: Codec = contentLoaderCodec()

                items(clientStates.chatHistory, key = {it.id}) { message ->

                    Row(modifier = Modifier.fillMaxWidth())  {
                        //Adds items to the hierarchy of context menu items
                        ContextMenuDataProvider(items = { messageContextMenuItems(message, chatListUpdateScope) }) {
                            ChatIcon(encodedChatPhoto = message.senderPhoto, chatTitle = message.senderInfo, circleSize = 44.dp)
                            Spacer(Modifier.width(4.dp))
                            SelectionContainer {
                                Column {
                                    Text(text = message.senderInfo, fontWeight = FontWeight.Bold, fontSize = 12.sp, color = headerColor)
                                    Spacer(Modifier.height(4.dp))
                                    message.photoPreview?.let {
                                        MessagePhoto(it, contentLoaderCodec)
                                    }
                                    MessageTextCard(message, messageCardColor)
                                }
                            }
                        }
                    }

                    Spacer(modifier = Modifier.height(12.dp))

                }
            }
```

If I remove the `key` from the `items` and add the elements to the list, I get an error in some cases:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Another selectable with the id: androidx.compose.foundation.text.selection.MultiWidgetSelectionDelegate@1040bc6d.selectableId has already subscribed.
``` 

Hope it would be helpful. My compose-desktop version is `1.5.12`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6011">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
