### ISSUE TITLE
Text "✿ﾟ" makes the app hang forever!

### ISSUE THREAD

**Issue by wumo** [JetBrains/compose-multiplatform#651]
The following code will simply make the app hang forever!
```kotlin
import androidx.compose.desktop.Window
import androidx.compose.material.Text

fun main() {
  Window {
    Text("✿ﾟ")
  }
}
```

**Comment by wumo** [comment]
OS: Windows 10
Build: 0.3.1 , 0.4.0-build188

**Comment by sergeych** [comment]
Also on MacOS 10.15.7, (0.3.1). Interesting that meeting a space between: `Text("✿ ﾟ")`

**Comment by olonho** [comment]
Reproducible in plain Skiko sample if add "✿ﾟ" to text in https://github.com/JetBrains/skiko/blob/eed5ec810005b8d1b4cb9b55edd65bbe350678e1/samples/SkijaInjectSample/src/main/kotlin/SkijaInjectSample/App.kt#L171

**Comment by bungeman** [comment]
Reproduced in Skia and opened https://bugs.chromium.org/p/skia/issues/detail?id=11996 .

**Comment by olonho** [comment]
Skiko 0.3.0 contains the fix for the low level problem.

**Comment by akurasov** [comment]
Works fine on MacOs+build245. @wumo do you still have such issue?

**Comment by wumo** [comment]
> Works fine on MacOs+build245. @wumo do you still have such issue?

Tried on windows+build245, it didn't hang but still render as square.

**Comment by taodongl** [comment]
Works fine on WIndows 11
![image](https://user-images.githubusercontent.com/1430663/149654535-15fd261e-a5b4-4b34-b47a-abd050c02ea3.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6143">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
