### ISSUE TITLE
Ripples are low-fps (regression)

### ISSUE THREAD

**Issue by lucas-ap150** [JetBrains/compose-multiplatform#664]
In builds after 0.4.0-build180, the ripple indications for `TextButton()`, `OutlinedButton()` and `clickable()` became low-fps.
`Button()` is unaffected for some reason.

0.4.0-build180 (ok, smooth ripples):
https://user-images.githubusercontent.com/67303532/118195540-c65f8000-b421-11eb-9c1f-ec5eaceee249.mp4

0.4.0-build190 (not smooth, except `Button`):
https://user-images.githubusercontent.com/67303532/118195753-30782500-b422-11eb-8c24-316c876f669d.mp4

Code:
```
fun main() {
    // Force opengl renderer because directx doesn't work on my machine
    if (hostOs.isWindows) {
        System.setProperty("skiko.renderApi", "OPENGL")
    }

    Window {
        MaterialTheme {
            Row(Modifier.fillMaxSize()) {
                val sizeMod = Modifier.size(150.dp)

                Button({}, sizeMod) { Text("Button") }

                TextButton({}, sizeMod) { Text("TextButton") }

                OutlinedButton({}, sizeMod) { Text("OutlinedButton") }

                Box(sizeMod.then(Modifier.clickable {})) { Text("clickable Box") }
            }
        }
    }
}
```

All builds after 180 have this issue (i couldn't test 181, because gradle complains about missing dependencies).

I'm using Windows 10 64bit.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5420">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
