### ISSUE TITLE
WebView support for desktop

### ISSUE THREAD

**Issue by youngxhui** [JetBrains/compose-multiplatform#668]
How to use webview in compose-jb?

**Comment by olonho** [comment]
WebView is Android notion, there is not currently fully functional CEF integration at 
https://github.com/JetBrains/compose-jb/tree/master/cef - you may try to help us make it working again. Also note that any Swing browser component, such as those listed in https://blog.disy.net/swing-browser-integration/ may work via interop.

**Comment by xinkunZ** [comment]
flutter already has the desktop webview https://pub.dev/packages/desktop_webview_window
compose desktop has no webview solution until now,  even if jcef just work in swing mode, it has the z-order problem, it really matter

**Comment by KevinnZou** [comment]
I would recommend this library https://github.com/KevinnZou/compose-webview-multiplatform. It supports WebView on the desktop side using JCEF.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5418">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
