### ISSUE TITLE
Adding shortcuts to Box and Dialog

### ISSUE THREAD

**Issue by David-Zhubrev** [JetBrains/compose-multiplatform#673]
I'm trying to implement shortcuts logic into a dialog window. However, I'm not being able to, because I failed to find any docs about adding Shortcuts to anything other than TextField or AppWindow. Is there any way to add shortcuts to Dialog widget?
Also, Modifier.shortcuts can be used anywhere, but I was not able to fire its listeners somehow. Would you kindly add some more documentation about Modifier.shortucts usage?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5415">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
