### ISSUE TITLE
Missing platform-consistent default font sizing on texts

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-multiplatform#675]
Maybe this belongs at Skiko level.

It looks like https://github.com/androidx/androidx/blob/androidx-main/compose/ui/ui-text/src/commonMain/kotlin/androidx/compose/ui/text/TextStyle.kt#L41 is used in https://github.com/androidx/androidx/blob/androidx-main/compose/ui/ui-text/src/commonMain/kotlin/androidx/compose/ui/text/TextStyle.kt#L373 to get the default font size.

While the Material layer comes with its typography system, that one does not follow desktop-consistent default sizes for control texts - like Segoe UI at 9pt for Windows, San Francisco 13pt on macOS, etc.

This might not necessarily be an issue for Compose-only desktop apps, but it is an issue for hybrid Compose-Swing apps where the Swing "side" is using correct, platform-consistent font sizes.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5413">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
