### ISSUE TITLE
Ubuntu touchpad double tap does not trigger double click when tapped fast

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-multiplatform#683]
There seems to be an issue in double click handling. I'm using Ubuntu 21.04 on a Dell XPS laptop with touchpad. As usual, there are two ways of making clicks - by pressing the touchpad's hardware buttons or by finger-tapping on the touchpad's sensitive area.

Given the following code, the "hardware buttons" case works fine. However the "finger-tapping" case does not work when I tap fast enough. If I double tap a bit slower, then it works. All other apps (e.g. IDEA) work fine.

```kotlin
        var count by remember { mutableStateOf(0) }

        Text(
            text = "Count: $count",
            modifier = Modifier
                .combinedClickable(
                    onClick = {},
                    onDoubleClick = { count += 1 }
                )
                .padding(16.dp)
        )
```

**Comment by arkivanov** [comment]
Also looks like there is a delay in the normal `onClick` modifier when finger-tapped. When I click using the touchpad's hardware button, then the listener is fired as soon as the button is released, without any delay. But when I finger-tap on the touchpad's area, then the listener is called after some delay (~200ms) after the finger is released.

**Comment by igordmn** [comment]
Maybe related (not sure yet):
https://github.com/JetBrains/compose-jb/issues/358

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-683">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
