### ISSUE TITLE
package version not spec compliant for mac, windows, jar file

### ISSUE THREAD

**Issue by soloturn** [JetBrains/compose-multiplatform#686]
if one tries to give a version like 1.0.0-10-asdf which is perfectly fine for a jar file, all gradle commands fail. same is when using 1.0.0.10-asdf. 10 is the number of commits since last tag, asdf is the git hash. please allow the real versions. or do not check at all leave it to the developer to create a proper version.

IF you really want to check the situation is, for mac/ios it might be 0.0.0.0: https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion

the same numbering scheme is valid for windows: 0.0.0.0

for linux it is more complicated, e.g. this one for debian:
https://serverfault.com/questions/604541/debian-packages-version-convention

for maven jar files it is:
https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8855

**Comment by AlexeyTsvetkov** [comment]
@soloturn please provide your Gradle configuration file, a task you're trying to execute and an error you're getting

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5406">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
