### ISSUE TITLE
how to create jars for various platforms

### ISSUE THREAD

**Issue by soloturn** [JetBrains/compose-multiplatform#687]
gradle packageUberJarForCurrentOS

packages a jar for current os, which is great. how can one package jars for other OS, to avoid creating msi / deb / msi and provide a more straight forward upgrade path to users doing "java -jar whatever-it-is-new-now.jar".

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5405">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
