### ISSUE TITLE
Create simple example for video component

### ISSUE THREAD

**Issue by DusanLesan** [JetBrains/compose-multiplatform#711]
I am considering learning kotlin in order to use compose. My biggest requirement is to have a video player that is capable to play videos from online sources. I was trying to use the [video component](https://github.com/JetBrains/compose-jb/tree/master/components/VideoPlayer) but had no idea how to set it up. 
Please create the example/tutorial for the simplest possible video player to be used in desktop app.

**Comment by akurasov** [comment]
@DusanLesan  Please see https://github.com/JetBrains/compose-jb/blob/master/components/VideoPlayer/demo/src/jvmMain/kotlin/org/jetbrains/compose/videoplayer/demo/Main.kt

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5396">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
