### ISSUE TITLE
0.4.0 multiplatform template: Android dependencies declared in common module not entirely clear

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-multiplatform#730]
```
named("androidMain") {
            dependencies {
                api("androidx.appcompat:appcompat:1.3.0-beta01")
                api("androidx.core:core-ktx:1.3.1")
            }
        }
```

As someone new to compose and KMM (but does android development) I don't understand why the common module declares android dependencies. Especially why does it declare deps here AND in the android module? If I move these deps into android module the project still builds. I think it would be better to add a comment here explaining why they are here even though they could just be in the /android module.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5387">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
