### ISSUE TITLE
0.4.0 multiplatform template: Android compileSdk, minSdk, targetSdk, etc declared twice (once in common and once in android)

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-multiplatform#732]
common module has the following which doesn't seem necessary. I commented it out and everything still worked. This is also defined in the android module and so having it in two places is confusing to me (as an android developer)
```
//    compileSdkVersion(30)

//    defaultConfig {
//        minSdkVersion(21)
//        targetSdkVersion(30)
//        versionCode = 1
//        versionName = "1.0"
//    }

//    compileOptions {
//        sourceCompatibility = JavaVersion.VERSION_1_8
//        targetCompatibility = JavaVersion.VERSION_1_8
//    }
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5385">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
