### ISSUE TITLE
Unable to set PopupProperties in DropdownMenu

### ISSUE THREAD

**Issue by armay** [JetBrains/compose-multiplatform#739]
The API on Android and desktop differ for DropdownMenu component. In particular, PopupProperties can't be set. The property significantly simplifies building search bars and alike components as mentioned on [StackOverflow](https://stackoverflow.com/questions/66675748/auto-complete-text-view-in-compose). On Android one can write
```kotlin
DropdownMenu(
  properties = PopupProperties(focusable = false),
  // Some other properties...
)
```
Currently, on desktop such an API is not present, so opening a dropdown menu makes the currently used textfield uneditable.

**Comment by helmysaeed** [comment]
yes It important property should fix quickly

**Comment by MatkovIvan** [comment]
Compatible with Android overload was added in [1.5.0](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.5.0)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5380">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
