### ISSUE TITLE
Window not transparent

### ISSUE THREAD

**Issue by smallshen** [JetBrains/compose-multiplatform#759]
```kotlin
import androidx.compose.desktop.ComposeWindow
import androidx.compose.ui.ExperimentalComposeUiApi
import java.awt.*
import javax.swing.SwingUtilities


@OptIn(ExperimentalComposeUiApi::class)
fun main() = SwingUtilities.invokeLater {
    ComposeWindow().apply {
        isUndecorated = true
        background = Color(0, 0, 0, 1)
        size = Dimension(300, 300)
        isVisible = true
    }
}
```

The window is white instead of transparent.

**Comment by olonho** [comment]
Unfortunately, we do not support transparent window on all platforms at the moment.

**Comment by smallshen** [comment]
are there any plans for the desktop platform?
transparent window in UI design is popular, like blur (compose doesn't support that too I think)

**Comment by olonho** [comment]
No immediate plans for that, but we consider external contributions.

**Comment by graycatdeveloper** [comment]
Pls join to discussion [https://github.com/JetBrains/compose-jb/discussions/646](https://github.com/JetBrains/compose-jb/discussions/646)
