### ISSUE TITLE
TextActual should probably not be exposed in the public API

### ISSUE THREAD

**Issue by LouisCAD** [JetBrains/compose-multiplatform#782]
Hello,
I was wondering why composables with names like `TextActual` are part of the public API when it seems they're designed to be called by `Text` and alike.

I think they should be `internal`. If there's any issue preventing to apply the correct visibility, I'd be happy to get the link to it, and it'd be great that it's mentioned in the code comments as well to prevent further confusion.

Have a great day!
Louis CAD

**Comment by olonho** [comment]
It was implemented that way due to https://youtrack.jetbrains.com/issue/KT-34823, which seems to be fixed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6356">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
