### ISSUE TITLE
Packaging fails when appImage build property is set

### ISSUE THREAD

**Issue by saket** [JetBrains/compose-multiplatform#793]
I'm exploring if I can set `--type app-image` for modifying images built for my macOS app ([docs](https://docs.oracle.com/en/java/javase/14/jpackage/image-and-runtime-modifications.html)). Doing this for specifying an app image directory doesn't seem to work:

```kotlin
tasks.withType<AbstractJPackageTask>().all {
  appImage.set(file("foo"))
}
```

This fails with a jpackage error:

```bash
> External tool execution failed:
  * Command: [/Users/saket/.sdkman/candidates/java/16.0.1.j9-adpt/bin/jpackage, @/Users/saket/projects/teleport/desktop/build/compose/tmp/packageDmg.args.txt]
  * Working dir: []
  * Exit code: 1
  * Standard output log: .../build/compose/logs/packageDmg/jpackage-2021-06-17-17-41-19-out.txt
  * Error log: .../build/compose/logs/packageDmg/jpackage-2021-06-17-17-41-19-err.txt
```

The error log file contains this message:

```
Error: Option [--java-options] is not valid with type [dmg]
```

What am I doing wrong?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6355">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
