### ISSUE TITLE
Modifying app image through jpackage

### ISSUE THREAD

**Issue by saket** [JetBrains/compose-multiplatform#794]
jpackage allows modification of app images by passing in a `--type app-image` option. Is this something that's supported by compose for desktop right now? https://docs.oracle.com/en/java/javase/14/jpackage/image-and-runtime-modifications.html

To add some context, I'm trying to include a custom `/PlugIns` folder to my app's image for manually adding [macOS app extensions](https://developer.apple.com/app-extensions/).

![image (2)](https://user-images.githubusercontent.com/2387680/122476426-281c8800-cf94-11eb-8a87-5afcdd53e33d.png)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6411">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
