### ISSUE TITLE
Sources artifacts missing from Gradle module metadata

### ISSUE THREAD

**Issue by tadfisher** [JetBrains/compose-multiplatform#806]
The `androidx.compose.*` artifacts are published to [Google's Maven repository](https://maven.google.com) with a `sourcesElements` variant included in the Gradle module metadata ([example](https://dl.google.com/android/maven2/androidx/compose/ui/ui/1.0.0-beta09/ui-1.0.0-beta09.module)).

The `org.jetbrains.compose.*` artifacts are published with no `sourcesElements` variant ([example](https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/ui/ui/0.5.0-build226/ui-0.5.0-build226.module)). This impacts me as I rely on the metadata to pin artifacts for reproducible builds and to create an offline repository for development, which makes it difficult to fetch the `-sources` artifacts as the file hashes are not published in the module metadata, meaning I would have to write a separate script to prefetch those hashes.

The androidx build has [an example](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:buildSrc/src/main/kotlin/androidx/build/SourceJarTaskHelper.kt;drc=8a61443e0bb2fe0048cf27314cb3142423f4a1b9) of manually creating the `sourcesElements` variants (which you get for free with Gradle's `java.withSourcesJar()`).

Looks like a corresponding feature request was filed for the Kotlin Gradle plugin here: https://youtrack.jetbrains.com/issue/KT-36943

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6323">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
