### ISSUE TITLE
Make DropDownMenuItem hoverable by default

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#819]
Currently when we show DropdownMenu, items are not highlighted under the mouse cursor:

https://user-images.githubusercontent.com/5963351/123407833-1307b080-d5b5-11eb-960d-4987a7fc1d42.mp4

It looks very unintuitive on desktop platforms. Probably we need to highlight item when mouse is over the item.

Issue for Button's: https://github.com/JetBrains/compose-jb/issues/339

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6406">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
