### ISSUE TITLE
Complex media queries are broken

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-multiplatform#839]
For instance. combining screen and max-width will generate following media query: 
`@media (screen, (max-width: 400px)

We've missed this because headless Chrome is matching media query without screen while Firefox actually does not.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5377">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
