### ISSUE TITLE
Discourage users from using anonymous objects as stylesheets

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-multiplatform#843]
Consider following code:

```kotlin
private object A : StyleSheet() {
    val someClass by style {
        media(minWidth(200.px), maxWidth(400.px)) {
        }
    }
}

private val B = object : StyleSheet() {
    val someClass by style {
        media(minWidth(200.px), maxWidth(400.px)) {
        }
    }
```   
Both constructions are perfectly valid, however in class names we rely on existence of name, which we add to the prefix as a class name.  That said, in first case we'll get A-someClass and in second -  undefined-someClass.

I'm not sure what's the best thing we can do. Right not it seems the most reasonable thing to do - is to throw a Runtime error, forcing users use named entities (or otherwise it might be a clash in naming)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-843">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
