### ISSUE TITLE
Support creation of menu bar apps

### ISSUE THREAD

**Issue by saket** [JetBrains/compose-multiplatform#850]
It'd be really nice if compose-desktop supported creation of apps that live solely on the system tray. It is currently possible to interact with the system tray using [Tray](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/window/v1/MenuBar.desktop.kt?q=MenuBar%20compose), but it is limited to text buttons. Being able to add arbitrary content to the popup would enable us to create apps like these:

![image](https://user-images.githubusercontent.com/2387680/124421896-648c0a00-dd30-11eb-9a78-9e3ea77310b4.png)

I came across this StackOverflow answer which suggests doing so should be possible with AWT: https://stackoverflow.com/questions/13481504/creating-an-nsstatusitem-menubar-app-in-java

**Comment by saket** [comment]
Someone on kotlin lang suggested these kind of apps are actually called "daemon" apps that don't have any main UI windows and are only accessible through their tray icon.

**Comment by olonho** [comment]
Guess it could be implemented as a regular app without border rendered at predefined position.

**Comment by saket** [comment]
True. It'll also need to,
1. Align its window with the tray icon when its opened. I wasn't able to find anything for AWT, but if this [electron app](https://github.com/lucasbento/menubar-brightness) is able to do it, there must be a way.
2. Hide its dock icon. There are various [ways of doing this](https://stackoverflow.com/questions/24312260/javafx-application-hide-osx-dock-icon) with AWT.

**Comment by saket** [comment]
After spending some time on this, this seems impossible with the set of APIs provided by AWT. I couldn't find any existing pattern or app that has managed to do this. In comparison, there are tons of examples with electron. Here's one: https://github.com/maxogden/menubar

**Comment by natanfudge** [comment]
Just being able to customize the tray content would be really nice, considering the current implementation is really limiting (and ugly on windows)

**Comment by Giuliopime** [comment]
Any update on this?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5370">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
