### ISSUE TITLE
Check deep linking support on Linux and Windows

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [JetBrains/compose-multiplatform#855]
Macos example https://github.com/JetBrains/compose-jb/pull/845

Windows docs https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking

**Comment by akurasov** [comment]
@AlexeyTsvetkov is it the same as https://github.com/JetBrains/compose-jb/issues/380 ?

**Comment by AlexeyTsvetkov** [comment]
@akurasov I would say this is a subtask of #380

**Comment by JoeSteven** [comment]
@AlexeyTsvetkov  hi, i've noticed that Jetbrains Toolbox  is supporting deep link and it has finished migration to Compose for Desktop. I was wondering is there any sample code for implement deep link on Windows? really appreciate

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5369">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
