### ISSUE TITLE
Support constraint layout (and motionlayout) in Compose Multiplatform

### ISSUE THREAD

**Issue by yogurtearl** [JetBrains/compose-multiplatform#858]
[Right now the `constraintlayout-compose` artifact is an `aar`. ](https://github.com/androidx/constraintlayout/blob/407fab4b269a88324c8e96649076c17e09f94c5b/constraintlayout/compose/build.gradle#L3)
This means we can't use it in Compose for Desktop. 

Would be good to move all the android stuff to interfaces that can be eventually be abstracted with `expect`/`actual`. 

Where should a Compose for Desktop version of constraint-layout live? in this repo? in the [constraintlayout repo](https://github.com/androidx/constraintlayout)? in a new third repo?

Wasn't sure if I should file this here or at https://github.com/androidx/constraintlayout/issues

**Comment by igordmn** [comment]
ConstraintLayout is a good candidate to make it available in a common code, and many people in the Slack channel asked about this.

But currently we don't have any plans how, when and who will do this (Google, JetBrains, or maybe third-party developers).

**Comment by igordmn** [comment]
Not sure about MotionLayout. Compose has powerfull tools to [animate any value/attribute](https://developer.android.com/jetpack/compose/animation) (by the way, Compose for Android doesn't support MotionLayout too, if I am not mistaken)

**Comment by yogurtearl** [comment]
It is a recent addition, but [MotionLayout does exist for Compose for Android](https://github.com/androidx/constraintlayout/blob/fe968294e273c98b2fb49ca7dd54180f3b6f873f/constraintlayout/compose/src/main/java/androidx/constraintlayout/compose/MotionLayout.kt).

**Comment by igordmn** [comment]
> It is a recent addition, but [MotionLayout does exist for Compose for Android](https://github.com/androidx/constraintlayout/blob/fe968294e273c98b2fb49ca7dd54180f3b6f873f/constraintlayout/compose/src/main/java/androidx/constraintlayout/compose/MotionLayout.kt).

Awesome!

Then it is worth to port MotionLayout to.

**Comment by linde9821** [comment]
Are there any news regarding this issue?

**Comment by igordmn** [comment]
No news, sorry. It is not in our priority at the moment and in the near future

**Comment by linde9821** [comment]
alright thx for the update

**Comment by TomislavMladenov** [comment]
+1 for this :)

**Comment by xiaobo0528n** [comment]
+1 for this :) the sooner the better.

**Comment by wznshuai** [comment]
+1 for this :) the sooner the better.

**Comment by Diddielou** [comment]
+1 here!

**Comment by NickZt** [comment]
+1

**Comment by AhmedMourad0** [comment]
+1 missing the CL adds extra unnecessary trouble when porting existing Android apps to desktop

**Comment by akelix** [comment]
+1

**Comment by moten-07** [comment]
+1

**Comment by Ekt0s** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by nowiwr01w** [comment]
+1

**Comment by wagnod** [comment]
+1

**Comment by zengziming2023** [comment]
+1

**Comment by hehua2008** [comment]
+1
We need ConstraintLayout !!!!

**Comment by nowiwr01w** [comment]
Now we can use ConstraintLayout with Compose Multiplatform for Web with K/Wasm, thanks to [this great man](https://github.com/Lavmee/constraintlayout-compose-multiplatform/issues/16)
Check supported platforms [here](https://central.sonatype.com/namespace/tech.annexflow.compose) or just add deoendency in `commonMain`
```kotlin
commonMain.dependencies {
    /// ....
    implementation("tech.annexflow.compose:constraintlayout-compose-multiplatform:0.3.0-alpha01")
}
```

**Comment by rvenky125** [comment]
+1 for motion layout

**Comment by encyclist** [comment]
+1

**Comment by minmax1993** [comment]
+1

**Comment by GJean** [comment]
+1

**Comment by ArtyomZhukov** [comment]
+1

**Comment by DevAlves1993** [comment]
+1

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5367">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by VahidGarousi** [comment]
+1
