### ISSUE TITLE
Samples - Integrating 3D renderer

### ISSUE THREAD

**Issue by Zingam** [JetBrains/compose-multiplatform#867]
I think it will be valuable to demonstrated with samples how to efficiently integrate high performance, low overhead 3D renderers in a cross-platform way while using the respective 3D API (Vulkan/Direct3D 12, Metal) for each platform (Windows, Linux/Android, Apple).

**Comment by ln-12** [comment]
I would also welcome any samples regarding this topic. [This issue](https://github.com/JetBrains/compose-jb/issues/649) also asks for it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5364">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
