### ISSUE TITLE
Desktop. Support Right-To-Left languages

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#872]
Compose 0.5.0-build235

Core Compose already supports right-to-left languages and changes layout accordingly.

All we need is to get `LayoutDirection` at the window/component level and pass it down to all internal classes (DesktopOwner, SkijaLayer, Window.setIcon, Tray).

We can use this property:
```
package androidx.compose.ui.util

import androidx.compose.ui.unit.LayoutDirection
import java.awt.ComponentOrientation
import java.util.Locale

internal val Locale.layoutDirection: LayoutDirection
    get() {
        return if (ComponentOrientation.getOrientation(this).isLeftToRight) {
            LayoutDirection.Ltr
        } else {
            LayoutDirection.Rtl
        }
    }
```
get it from the component in ComposeLayer.setContent: `component.locale.layoutDirection` and pass it to `DesktopOwner`

Besides layout, we need to be sure that any RTL text looks okay.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5362">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
