### ISSUE TITLE
Debug Breakpoints don't work in Intellij Idea Community Edition (Windows 10)

### ISSUE THREAD

**Issue by ReaktorDTR** [JetBrains/compose-multiplatform#874]

**Comment by atsushieno** [comment]
I am hitting the same issue on Ubuntu 20.04. I have a repro screen recording: https://drive.google.com/file/d/1jbNdwQfTOZ5F0Qba6JKNDf9TCFkH4UHp/view?usp=sharing

I still see "some code" or "sometimes" IDEA stops at breakpoint as expected, but it's not predictable to me.

```
IntelliJ IDEA 2021.2 (Community Edition)
Build #IC-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-25-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins: com.github.ushiosan23.darktheme (1.0.2), com.jetbrains.darkPurpleTheme (1.2), com.vecheslav.darculaDarkerTheme (1.2.0), org.antlr.intellij.plugin (1.16), org.antlr.jetbrains.st4plugin (0.8)
Kotlin: 212-1.5.10-release-IJ4746.92
Current Desktop: ubuntu:GNOME
```

Possible conditions I can think of:

- code file opens with some specific context (e.g. commonMain opens within desktop context while breakpoints are set on Android context) - if such a bug exists on MPP support plugin.
- some cmpiler plugin injection involves debuggee code that JDWP can normally handle, and it does not work at `Window()`'s immediate content on Desktop (which is what I particularly observe).
- It works only with certain JVM. I tried 14 and 16 as well, but I don't think I can reliably run the debuggee (app), IDEA and/or Gradle with certain version to verify - especially when Gradle deamon persists.

**Comment by tnc-tianwen** [comment]
Same here, I am using the ultimate version of Inteliij on Ubuntu 20.04

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5360">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
