### ISSUE TITLE
macOS Feature: Allow to change Titlebar to a Transparent Toolbar

### ISSUE THREAD

**Issue by lucsoft** [JetBrains/compose-multiplatform#877]
Currently Windows only can look like this:
![Frame 1 (1)](https://user-images.githubusercontent.com/11093382/125252582-d2b86a00-e2f8-11eb-8496-f07b03ca665b.png)

But i'd love to change the window titlebar/toolbar to this:
![Frame 1](https://user-images.githubusercontent.com/11093382/125252544-c7fdd500-e2f8-11eb-9f70-74f824e2375c.png)

Notice the Window Buttons have more margin
 
On the toolbar mode:
I can put components behind the toolbar
I can click on the components behind the toolbar
i can still move the window

**Comment by RinOrz** [comment]
Similarly, the title bar of IDEA is transparent. Maybe there is a way to go there?

**Comment by Thomas-Vos** [comment]
Would love to see this as well.

**Comment by Thomas-Vos** [comment]
Found a way to get this working on macOS:
```kt
Window(...) {
    window.rootPane.apply {
        rootPane.putClientProperty("apple.awt.fullWindowContent", true)
        rootPane.putClientProperty("apple.awt.transparentTitleBar", true)
        rootPane.putClientProperty("apple.awt.windowTitleVisible", false)
    }
}
```

**Comment by akurasov** [comment]
Cool, thank you! I'll add this to the documentation.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5357">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
