### ISSUE TITLE
Menu. Support arbitrary key shortcuts

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#914]
[Here](https://android-review.googlesource.com/c/platform/frameworks/support/+/1769930) we implemented shortcuts for Window Menu.

Currently we support only mainstream shortcuts [Ctrl]+[Shift]+[Alt]+[Meta]+Key

Investigate how we can support arbitrary shortcuts that works even if we press some key outside of the our application:
1. Key1 + Key2 (order doesn't matter)
2. Key1 + Key2 (order is matter)
3. LeftCtrl + Key1
4. Multiple shortcuts for the same action (i.e. LeftCtrl + Key1 and RightCtrl + Key1 or Ctrl-Shift-Z and Ctrl-Y for Redo).

To do that, we need to:
1. Make a public API for KeyShortcut. One of the possible solutions:
```
class KeyShortcut(val sets: List<KeySet>)

class KeySet(private val keys: Set<Key>) : Set<Key> 
```
Usage:
```
KeyShortcut(Key.CtrlLeft + Key.C, Key.CtrlRight + Key.C)
```

2.
a. Observe all keys at the global application level, even if application is minimized (there can be a security issue though)

Swing doesn't allow it (`Toolkit.getDefaultToolkit().addAWTEventListener` only works if application in focus)
There is a native library https://github.com/kwhat/jnativehook. We can implement something similar in skiko.

b (alternative). instead of observing keys at the global level we can ask OS to get the current state of the Key.

P.2 is needed because users can press part of the shortcut outside of the application window (Ctrl, for example)

**Comment by Ifropc** [comment]
Hi, are there any updates on this issue? 
Is my understanding correct that to create a global shortcut (when window is out of focus, e.g. minimized), the only way is to use the mentioned library?

**Comment by adrientetar** [comment]
For api reference, see QShortcut and QKeyReference <https://doc.qt.io/qt-5/qshortcut.html>
QKeyReference has a constructor that between 1-4 keys, so no need for vector or set.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5337">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
