### ISSUE TITLE
"Impossible" OnPositionedDispatcher.dispatch NPE regression in 262

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-multiplatform#917]
This happens when I use a `ComposeWindow` to show popup content in Aurora

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatch(OnPositionedDispatcher.kt:43)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks(MeasureAndLayoutDelegate.kt:251)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks$default(MeasureAndLayoutDelegate.kt:247)
	at androidx.compose.ui.platform.DesktopOwner.measureAndLayout(DesktopOwner.desktop.kt:269)
	at androidx.compose.desktop.ComposeLayer$Wrapped.doLayout(ComposeLayer.desktop.kt:118)
```

The relevant code in Aurora is in the block that starts at https://github.com/kirill-grouchnikov/aurora/blob/icicle/component/src/desktopMain/kotlin/org/pushingpixels/aurora/component/AuroraCommandButton.kt#L1314

The code in `androidx.compose.ui.node.OnPositionedDispatcher` crashes on `if (layoutNode.needsOnPositionedDispatch)` with NPE - where Kotlin "promises" that `layoutNode` cannot be null

**Comment by igordmn** [comment]
Reproducer:
```
import androidx.compose.desktop.ComposeWindow
import androidx.compose.foundation.layout.Box
import androidx.compose.ui.Modifier
import androidx.compose.ui.layout.onGloballyPositioned
import java.awt.Dimension
import javax.swing.SwingUtilities

fun main() = SwingUtilities.invokeLater {
    val window = ComposeWindow()
    window.isVisible = true
    window.setContent {
        Box(Modifier.onGloballyPositioned {
            window.preferredSize = Dimension(200, 200)
            window.size = Dimension(200, 200)
            window.invalidate()
            window.validate()
        })
    }
}
```

**Comment by igordmn** [comment]
In the new version we made Compose layout as a part of Swing layout pipeline. So when we call `validate()`, Swing will layout Swing content, and so Compose content. During Compose content layouting we call onGloballyPositioned. So we will have ethier stackoverflow of state inconsistency:
```
isVisible = true -> window layout -> compose layout -> onGloballyPositioned -> validate -> window layout -> compose layout -> ...
```
I will investigate if we can detach Compose layout from Swing layout again. But at the first glance this kind of code isn't valid. For example, if you write a Swing component, it is not right to call `validate()` during component's layout?

What are you trying to achive calling validate in onGloballyPositioned? Is it possible to move logic out of onGloballyPositioned, and call it after ComposeWindow creation and `window.pack()`?

BTW, if you need to make Window as the size of the content, now you can write this:
```
import androidx.compose.desktop.ComposeWindow
import androidx.compose.material.Text
import androidx.compose.ui.ExperimentalComposeUiApi
import java.awt.Dimension
import javax.swing.SwingUtilities

@OptIn(ExperimentalComposeUiApi::class)
fun main() = SwingUtilities.invokeLater {
    val frame = ComposeWindow()
    frame.setContent {
        Text(
            "fhjkgh fdjkghgjksdhgjkfsdhgjkfdsh gjksfdghsdfkjghfdkgljfdshgkjlfdshgklsdjfghsdfjklg" +
                " hsdkljfghsdjklgfhsdkjf ghsdfjkgh " +
                "sdfkgjsdhgkjlfdshgkljfdshglksdfhgkjsfdhgjkfd hg"
        )
    }
    frame.preferredSize = Dimension(300, Int.MAX_VALUE)
    frame.pack()
    frame.preferredSize = null
    frame.pack()
    frame.isVisible = true
}
```
It looks hacky to call `pack()` two times though. The first call calculates the content's preferedSize based on the window's preferredSize.

**Comment by kirill-grouchnikov** [comment]
The reproducer here is not quite what I have for the popup windows in Aurora. I use `onGloballyPositioned` to "wait" to know the position of the combobox on the screen, and then position a separate `ComposeWindow` based on its preferred content size and the screen position of the combobox. So it is the second / popup `ComposeWindow.validate()` that I call during the layout, not of the window that has the combobox.

**Comment by kirill-grouchnikov** [comment]
And replacing `validate` with `pack` is an almost similar stack trace:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatch(OnPositionedDispatcher.kt:43)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks(MeasureAndLayoutDelegate.kt:251)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks$default(MeasureAndLayoutDelegate.kt:247)
	at androidx.compose.ui.platform.DesktopOwner.measureAndLayout(DesktopOwner.desktop.kt:269)
	at androidx.compose.desktop.ComposeLayer$Wrapped.doLayout(ComposeLayer.desktop.kt:118)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Container.validateUnconditionally(Container.java:1694)
	at java.desktop/java.awt.Window.pack(Window.java:835)
```

**Comment by kirill-grouchnikov** [comment]
Sorry, what I wrote above is not correct.

The flow is indeed waiting for `onGloballyPositioned` to know how much space the popup content needs (width x height) to then compute the preferred size of the popup. Imagine the scenario that you have 100 items in the popup menu, and you want to limit the maximum visible to what can fit on the screen with vertical scrolling if necessary.

So until you make the layout pass on the content of the popup window, how do you know if it's going to be more than what fits on the screen?

**Comment by igordmn** [comment]
>And replacing validate with pack is an almost similar stack trace:
pack = `create a native window` + `validate` +`set the size to preferredSize`

During validation we layout/measure content and determine preferredSize by content's size

> So until you make the layout pass on the content of the popup window, how do you know if it's going to be more than what fits on the screen?

We defenetely need a layout pass to know the content's size. The question how we request it and where we read the result.
If we request a new layout in another layout (i.e. `validate` in `onGloballyPositioned`) - should we schedule layouting on the next frame or throw an exception?

The are two workarounds/solutions:
1. schedule `validate()` in the `SwingUtilities.invokeLater`

2. use `pack` outside of layout step, before `window.isVisible = true`
The problems are arise if we want to measure only part of the content, or resize window dynamically. I don't have an answer yet, will investigate futher, how we should behave in such cases.

**Comment by kirill-grouchnikov** [comment]
Not sure if this is the right place to discuss these higher level issues, but here goes.

First, I think the original exception still needs to be addressed. Something somewhere is breaking the Kotlin nullability promise.
Second, there needs to be some sort of a warning message printed to the log when Compose Desktop detects this now-erroneous usage pattern of the infinite layout loop.
Third, and perhaps this is coming from my experience of working with Swing - what I really miss is the ability to compute the preferred size of a thing (a single component or a whole layout) without having it on the screen yet.

This last part is a more general comment on how approachable it is to write complex custom components. In Aurora, I have built a whole set of APIs to do that. Perhaps I'm missing something obvious in here, but this is my main scenario so far (but not the only one).

How do I determine the position and the size of a popup without knowing how much space it needs? It can be something as simple as a combobox with N items. How do I determine the size of the combo popup without having it already on the screen?

What I had in Aurora up until now (and what became broken with this last Compose Desktop build - and probably rightfully so) is this:
1. Create a `ComposeWindow` of arbitrarily large size, say 1000x1000 pixels and opacity 0
2. Add content into it, make it visible (it's still not visible to the user because of zero opacity)
3. Wait for the layout pass in that `onGloballyPositioned` callback
4. Get the content size there, resize the `ComposeWindow` that is hosting the popup and switch its opacity to 1

With the latest refactoring linked above, I'm using the APIs that I have in Aurora to determine the preferred size of the entire popup even before I create that `ComposeWindow`. This way, now I can remove the opacity switching, as well as the usage of `onGloballyPositioned`.

So right now I have a better behaving layout pipeline for my popups in general. 

I don't mind if this gets closed, but I think that my first point about violating the nullability contract, and the second point of warning the developer about incorrect usage of the layout APIs still need to be addressed.

**Comment by igordmn** [comment]
> what I really miss is the ability to compute the preferred size of a thing (a single component or a whole layout) without having it on the screen yet.

But after the recent change in 262 you can do exactly that. After you call `pack()` window will be composed and layouted without showing on the screen. PreferredSize will be calculated by window's content (see this [comment](https://github.com/JetBrains/compose-jb/issues/917#issuecomment-885594016)

For getting the size of the individual components before showing the window you can do this trick:
```
import androidx.compose.desktop.ComposeWindow
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.layout.boundsInWindow
import androidx.compose.ui.layout.onGloballyPositioned
import androidx.compose.ui.unit.dp
import java.awt.Dimension
import javax.swing.SwingUtilities

@OptIn(ExperimentalComposeUiApi::class)
fun main() = SwingUtilities.invokeLater {
    val frame = ComposeWindow()
    lateinit var rect: Rect
    frame.setContent {
        Column {
            Box(Modifier.size(200.dp))
            Box(Modifier.padding(100.dp)) {
                Box(Modifier.size(300.dp).onGloballyPositioned {
                    rect = it.boundsInWindow()
                })
            }
        }
    }
    frame.preferredSize = Dimension(300, Int.MAX_VALUE)
    frame.pack()
    println(rect)
    frame.isVisible = true
}
```

> violating the nullability contract

There are cases in Kotlin where compiler can't determine violation of nullability (at least yet). The simplest example is accessing the not-yet initialized property of the base class:
```
fun main() {
    A()
}

class A : B() {
    init {
        println(v.length)
    }

    override val g = ""
}

abstract class B {
    val v: String = f()
    fun f() = g
    abstract val g: String
}
```
But not sure yet what is happening in the case of onGloballyPositioned

> second point of warning the developer about incorrect usage of the layout APIs

Yes, if it is really incorrect (I am still not 100% sure, need to check some use cases), we should throw an exception.

Let's not close it, until the issues will be fixed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5335">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
