### ISSUE TITLE
Introduce special signature for span values in CSS Grid

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-multiplatform#924]
According to CSS spec, grid-column (or grid-row) can accept _**span together with either a <custom-ident> or an <integer> or both**_. That said, span acts here as sort of function - and we want to use the same approach for such definitions as we are going to use in #922 and #923

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6114">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
