### ISSUE TITLE
LayerDialog. Dialog which shows in a separate layer of the current window

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#933]
[Here](https://android-review.googlesource.com/c/platform/frameworks/support/+/1775165) we implemented `AlertDialog` as a `Popup`:

![image](https://user-images.githubusercontent.com/5963351/126814120-ab7e30d0-e6ef-4ab2-a34c-623eaaf36db5.png)

Using `Popup` for `AlertDialog` may look like a "cheat", because we don't have concept of a Dialog that shows not as a separate platform window, but as a layer in the current window (aka `LayerDialog`).

The difference between `Popup` and `LayerDialog` is that `Popup` usually don't block user input, but `LayerDialog` blocks all user input (and sometimes shows a dark scrim behind).

The question - do we need such concept, so users will use it for their own `LayerDialog`'s, or we will treat `LayerDialog` as special case of `Popup` which blocks the user input.

Currently our `Popup` don't block user input at all: `focusable=false` or `focusable=true` doesn't change that. Is it correct behavior for Popup? If it is correct, then we definitely need `LayerDialog` (or make `AlertDIalog` the real window)

Also there is another question - how to name `LayerDialog` and how to name the usual platform `Dialog` that looks like a window:
1. LayerDialog + Dialog
2. Dialog + PlatformDialog
3. Dialog + WindowDialog
4. LayerDialog + WindowDialog

**Comment by igordmn** [comment]
Besides LayerDialog itself, we can also introduce a more narrow low-level abstraction `Layer` that will occupy the whole window space, no matter where it is declared in the UI hierarchy. Without additional handlers (like blocking UI, or closing it by Esc). It will be used inside Popup, AlertDialog and (?) LayerDialog (if we introduce `Layer`, the existence of `LayerDialog` becomes questionable though).

A similar concept exists in React, if I am not mistaken (see [Portal](https://reactjs.org/docs/portals.html)).

It is more powerful, according the description - we can define a portal in the middle of the UI hierarchy, not only on the root level. There is already a way to define a user-defined "portal" in Compose:
```
interface Portal {
  @Composable
  fun Child(content: @Composable () -> Unit) {
    DisposableEffect {
      // add/remove to some list
    }
  }

  @Composable
  fun Content() {
    // iterate over list
  }
}

val LocalSidePanelPortal = ...


@Composable
fun SidePanel() {
  CompositionLocalProvider(LocalSidePanelPortal provides ...) {
    ...
  }
}

@Composable
fun SidePanelWidget() {
    if (shouldShowAdditionalInfo) {
        LocalSidePanelPortal.current.Child {
   
        }
    }
}
```
But for root-level we can need to have something that is built-in in Compose itself.

**Comment by MatkovIvan** [comment]
Not relevant anymore (since 1.5)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6030">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
