### ISSUE TITLE
Preview tool. Resize of preview window doesn't force recomposition

### ISSUE THREAD

**Issue by akurasov** [JetBrains/compose-multiplatform#945]
0.5.0 - build 270.
```
@Preview //annotation that says that this function could be used
@Composable //Composable function
fun testUI() { //No parameters! Preview tool has no idea what to pass!
    Box(Modifier.background(Color.LightGray).fillMaxSize()) {
        Text("Hello World!!", Modifier.align(Alignment.Center).padding(10.dp))
    }
}
```
Scenario:
1. Run Preview
2. Make preview window floating
3. Resize preview window it. Issue 1->text will stay on the same position
4. Modify text (e.g. remove one !) and rerun preview. Text and box again will keep their positions/sizes.

Making preview window  pinned and floating again helps.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6321">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
