### ISSUE TITLE
Support content and content-attr in CSS API

### ISSUE THREAD

**Issue by Schahen** [JetBrains/compose-multiplatform#946]
This would be the last thing shoved in Web Alpha RC-1.

The goal of this task is to introduce API for calling content and content: attr in our CSS API

this is marginally related to #926

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6113">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
