### ISSUE TITLE
There is a rendering problem on border.

### ISSUE THREAD

**Issue by wwalkingg** [JetBrains/compose-multiplatform#948]
when i set border
```kotlin
Box(
                modifier = Modifier.size(20.dp).clip(CircleShape).background(grade.color).border(1.dp,Color.Primary,
                    CircleShape)
            )
```
it show:
![1](https://user-images.githubusercontent.com/42681996/127337845-bbdd2c7f-83cf-4cbe-95d6-0cac3770012d.png)
but this looks jagged.The correct effect should be

![1](https://user-images.githubusercontent.com/42681996/127338294-ac7994be-636b-4d2e-ad0b-2af906b6a57b.png)

**Comment by kirill-grouchnikov** [comment]
What if you change the modifier order so that your clip doesn't clip the border?

`Modifier.size(20.dp).border(1.dp,Color.Primary, CircleShape).clip(CircleShape).background(grade.color)`

**Comment by akurasov** [comment]
@WWALKINGG and how have you got "should be" circles?

**Comment by WWALKINGG** [comment]
> Modifier.size(20.dp).border(1.dp,Color.Primary, CircleShape).clip(CircleShape).background(grade.color)
it shows.
![Screenshot_20210729_003732](https://user-images.githubusercontent.com/42681996/127361971-ce332e97-1b69-45cd-a365-3fe33241a119.png)

**Comment by WWALKINGG** [comment]
> @WWALKINGG and how have you got "should be" circles?

just use two box with CircleShape.
I always think there are some problem with the border part when i do my graduation project.🐻Maybe I should spend times to look at the source code

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6083">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
