### ISSUE TITLE
ContextMenu. Support different localizations by default

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#955]
[Here](https://android-review.googlesource.com/c/platform/frameworks/support/+/1742314/2..13/compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/platform/PlatformLocalization.kt#b27) we implemented ContextMenu for text and named items only in English language.

Usually native context text menu's have localization to each popular language.

Consider localizing text context menu for Compose too.

**Comment by wwalkingg** [comment]
Two years past

**Comment by igordmn** [comment]
Until this issue is resolved, you can localize menu providing a custom `LocalLocalization`:
```
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.platform.LocalLocalization
import androidx.compose.ui.platform.PlatformLocalization
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
   CompositionLocalProvider(LocalLocalization provides object : PlatformLocalization {
       override val copy: String
           get() = TODO("Not yet implemented")
       override val cut: String
           get() = TODO("Not yet implemented")
       override val paste: String
           get() = TODO("Not yet implemented")
       override val selectAll: String
           get() = TODO("Not yet implemented")
   }) {
       ...
   }
}
```

**Comment by wwalkingg** [comment]
> Until this issue is resolved, you can localize menu providing a custom `LocalLocalization`:
> 
> ```
> 
> import androidx.compose.runtime.CompositionLocalProvider
> 
> import androidx.compose.ui.platform.LocalLocalization
> 
> import androidx.compose.ui.platform.PlatformLocalization
> 
> import androidx.compose.ui.window.singleWindowApplication
> 
> 
> 
> fun main() = singleWindowApplication {
> 
>    CompositionLocalProvider(LocalLocalization provides object : PlatformLocalization {
> 
>        override val copy: String
> 
>            get() = TODO("Not yet implemented")
> 
>        override val cut: String
> 
>            get() = TODO("Not yet implemented")
> 
>        override val paste: String
> 
>            get() = TODO("Not yet implemented")
> 
>        override val selectAll: String
> 
>            get() = TODO("Not yet implemented")
> 
>    }) {
> 
>        ...
> 
>    }
> 
> }
> 
> ```

It's helpful.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6069">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
