### ISSUE TITLE
Linxu deb installed, uses multiple tray positions (one to launch, another to run)

### ISSUE THREAD

**Issue by thejoeba** [JetBrains/compose-multiplatform#956]
https://user-images.githubusercontent.com/6234204/127516008-5c40fa9b-480b-4024-b3b6-8f3256e7f46a.mp4

sample of build.gradle
```
compose.desktop {
    application {
        mainClass = "MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "AdbGenie"
            packageVersion = "1.0.0"
            ...
            linux {
                iconFile.set(project.file("res/drawable/AdbGenie.png"))
            }
        }
    }
}
```
snippet of MainKts
```
@ExperimentalComposeUiApi
fun main() {
    application {
        Window(
            ::exitApplication,
            title = "Adb Genie",
            state = WindowState(width = 400.dp),
        ) {
            MaterialTheme {
                addOnlineStatusText()
                Column(
                    modifier = Modifier
                        .fillMaxSize()
                        .verticalScroll(rememberScrollState())
                        .padding(PaddingValues(5.dp))
                ) {
                    addButtons()
                }
            }
        }
    }
}
```

**Comment by igordmn** [comment]
Thanks!

The issue was described originally in Slack.

The problem here, that the application creates the second icon in the taskbar after the launch. "icon" here means button in the taskbar, not the picture.

It should reuse the icon on which we clicked to launch the application (Android icon on the video) and add a red point on the left.

I checked packages created on macOs/Windows 10 - they are work as expected (they don't create additional icon in the taskbar and reuse the original one).

The issue can be in jpackage, or how we use it.

Or maybe Ubuntu has some sort of AI which compares icon of the application and icon of the window. And if they don't equal - creates additional icon.

**Comment by sieveo** [comment]
I have encountered this problem a few times before when creating JavaFX applications targeted at gnome based systems. 

X11 has a concept of a ```WM_CLASS``` which is a property of the X Window application. This gets matched with the .desktop file which is what gives you the icon on your dock and menu.

Lots of times in Java GUIs there is a mismatch between the application name and the ```WM_CLASS``` which is set. Which results in the default Java icon.

You can check the ```WM_CLASS``` that X11 gives your app based on the output of this command:  ```xprop | grep WM_CLASS``` and then clicking on the application window which returns you some details. Eg. 

```
xprop | grep WM_CLASS                   
WM_CLASS(STRING) = "jetbrains-idea-ce", "jetbrains-idea-ce"
```
There are 2 work arounds here:
1. Explicitly set the ```StartupWMClass``` variable in the .desktop file - this is what intellij does: 
```
[Desktop Entry]
Name=IntelliJ IDEA Community Edition
Icon=/home/xxxxx/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/.icon.svg
StartupWMClass=jetbrains-idea-ce
Comment=The most intelligent Java IDE
Exec="/home/xxxxx/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/212.4746.92/bin/idea.sh" %u
Version=1.0
Type=Application
Categories=Development;IDE;
Terminal=false
StartupNotify=true
```

2. Or you can set the ```awtAppClassName``` property in ```java.awt.Toolkit``` via reflection - but this is bad practice and as far as I recall you will probably get an ```IllegalAccessException``` if you do not ```--illegal-access=permit```. Which is also bad practice. Some more info here: https://stackoverflow.com/questions/10593075/how-to-alter-wm-class-value-in-a-java-gui-application-based-on-swing-or-netbeans

I've always corrected this inside of .desktop files in CI. And I'm curious why this still happens in the new JPackage.

Some other useful info on this Github issue: https://github.com/cryptomator/cryptomator/issues/956

I hope this helps! But I'm pretty sure people at Jetbrains might have more insight or a nice way to fix this within Compose for Desktop. :)

**Comment by igordmn** [comment]
> I have encountered this problem a few times before when creating JavaFX applications targeted at gnome based systems.
> ...

Thanks!

This information is very helpful!

I guess the first approach is what we need.
