### ISSUE TITLE
Compose Multiplatform IDE Support plugin needs hidpi support

### ISSUE THREAD

**Issue by floatingrain** [JetBrains/compose-multiplatform#985]
I'm using 4k screen and this is the display picture:
![2021-08-03-21-25-57](https://user-images.githubusercontent.com/22867565/128023292-4367137d-155c-424d-b9d2-39262224af9f.png)
It is too small to view and different from program when the program is running. By the way, I'm using Linux.

**Comment by floatingrain** [comment]
By the way, I'm using Linux

**Comment by AlexeyTsvetkov** [comment]
@floatingrain what Linux distribution and desktop environment do you use?

**Comment by floatingrain** [comment]
> @floatingrain what Linux distribution and desktop environment do you use?

It's Ubuntu 21.04 with Gnome 3.38

**Comment by Rsedaikin** [comment]
@floatingrain Could you please install and run `DebugWriter` (download link https://spvessel.com/dw/debugwritertool_1.0.0-1_amd64.deb) and add a screenshot or debug-info.txt file (you can click "Open file" in the applicationor in case of application crash you can find this file in `/home/<UserName>/.debug-writer` directory). You should see something like this:
![image1](https://user-images.githubusercontent.com/32446626/128475157-d51d64fa-2426-4153-bbfe-2cd4ef07dc3d.png)

**Comment by floatingrain** [comment]
@Rsedaikin 
![2021-08-06-17-05-32](https://user-images.githubusercontent.com/22867565/128486338-e5bd5479-c763-4f75-ba9d-985a0b71ab8b.png)

**Comment by floatingrain** [comment]
@Rsedaikin

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6041">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
